### PR TITLE
SF-3008 Fix error destroying Biblical terms component

### PR DESCRIPTION
**Pull request by Nateowami**
This change is [Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/2752)

### CODE REVIEW

**Review by Nateowami — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/2752)* status: 0 of 1 files reviewed, 2 unresolved discussions

___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/translate/biblical-terms/biblical-terms.component.ts` line 15 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/2752#-O82nFMvC_CjrPP8ms55:-O82nFMvC_CjrPP8ms56:b-i7e5se) ([raw file](https://github.com/sillsdev/web-xforge/blob/3d24684bf5fbd7088ffa409377e07ca1e50a6f10/src/SIL.XForge.Scripture/ClientApp/src/app/translate/biblical-terms/biblical-terms.component.ts#L15)):*
> ```XML
>   NoteThread,
>   NoteType,
>   getNoteThreadDocId
> ```

The reformatting of the imports at the top of the file was automatic. I believe the Angular language server imposes this sort order, but if it crashes, it falls back to a (VSCode?) sort order that is different. The Angular language server was not crashed when I was working on this.
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/translate/biblical-terms/biblical-terms.component.ts` line 298 at r2](https://reviewable.io/reviews/sillsdev/web-xforge/2752#-O82p2rJDErlUGWU7hFT:-O82p2rJDErlUGWU7hFU:b-vcgdd) ([raw file](https://github.com/sillsdev/web-xforge/blob/85e645046309fe8255300949a30457b98447bd3e/src/SIL.XForge.Scripture/ClientApp/src/app/translate/biblical-terms/biblical-terms.component.ts#L298)):*
> ```XML
>     super.ngOnDestroy();
>     if (this.bookNum$ != null) {
>       this.bookNum$.unsubscribe();
> ```

These are `BehaviorSubject`s. The only thing that subscribes to them also unsubscribes to them. So I can't think of any reason why an unsubscribe would be needed here.

**Review by pmachapman — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/2752#-:-O83WBbLDOpCjO6ObYTd:bnfp4nl)* status: all files reviewed, 1 unresolved discussion

___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/translate/biblical-terms/biblical-terms.component.ts` line 298 at r2](https://reviewable.io/reviews/sillsdev/web-xforge/2752#-O82p2rJDErlUGWU7hFT:-O83XXDL8SehEsTZwS74:b-azkb7e) ([raw file](https://github.com/sillsdev/web-xforge/blob/85e645046309fe8255300949a30457b98447bd3e/src/SIL.XForge.Scripture/ClientApp/src/app/translate/biblical-terms/biblical-terms.component.ts#L298)):*
<details><summary><i>Previously, Nateowami (Nathaniel Paulus) wrote…</i></summary><blockquote>

These are `BehaviorSubject`s. The only thing that subscribes to them also unsubscribes to them. So I can't think of any reason why an unsubscribe would be needed here.
</blockquote></details>

It looks like I implemented this wrong. Thanks for catching this.

**Comment by Nateowami** [comment]
@pmachapman What I don't understand is why it wasn't 100% reproducible.

**Review by pmachapman — APPROVED** [review]
I think it is related to timing. I have had it happen once, but struggled to reproduce. Alternatively it will still happen because the query subscription is the cause. This PR is a good step in elimination potential causes in any case by removing unnecessary `unsubscribe` calls.

> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/2752#-:-O83e0lo2Q5e5Bfg4-6g:bdznvgd)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @Nateowami)

___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/translate/biblical-terms/biblical-terms.component.ts` line 15 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/2752#-O82nFMvC_CjrPP8ms55:-O83eacZ4G4QTVQwoqK7:b-xx8fyy) ([raw file](https://github.com/sillsdev/web-xforge/blob/3d24684bf5fbd7088ffa409377e07ca1e50a6f10/src/SIL.XForge.Scripture/ClientApp/src/app/translate/biblical-terms/biblical-terms.component.ts#L15)):*
<details><summary><i>Previously, Nateowami (Nathaniel Paulus) wrote…</i></summary><blockquote>

The reformatting of the imports at the top of the file was automatic. I believe the Angular language server imposes this sort order, but if it crashes, it falls back to a (VSCode?) sort order that is different. The Angular language server was not crashed when I was working on this.
</blockquote></details>

I will set aside a little bit of time to investigate this reformatting weirdness...

**Comment by Nateowami** [comment]
@pmachapman I can get it to happen 100% of the time. But then after you said you couldn't reproduce it, I couldn't either. But today I can reliably reproduce it. I do think it's timing related. I think if you add an additional delay in `ngOnInit` before `this.biblicalTermSub = this.subscribe(`, you can probably get it to happen too.

**Pull request merged**
