### PR TITLE
SF-2986 Add step to confirm language codes before generating draft

### PR DESCRIPTION
**Pull request by Nateowami**
@josephmyers There are two designs here. One is based on a grid with three quadrants filled, and one is based on two rows, with the first row having a right and left. I like the concept @josephmyers came up with, but I also feel like the layout it produces is harder to understand. The structure of the page doesn't seem as clear to me. It's like there's just a bunch of text floating around and it's hard to tell what is associated with what. Feel free to fork this and propose changes.

# Below screenshots are outdated

### Other concept that I worked on (on this branch, one commit behind the current tip of this branch)

- - -
This change is [Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/2730)

### CODE REVIEW

**Review by josephmyers — COMMENTED** [review]
Thanks for poking me on this. I've made [a new branch](https://github.com/sillsdev/web-xforge/pull/2783) off this one with my layout touchups. I think the core here is excellent, but I tweaked the sizing, colors, and other styles for various items to better visually organize it. They are all aesthetic tweaks, I think, except that I did remove the descriptions. I found them to clutter up the page, but I understand that there may in fact be a need for them, though they're not in the accepted mockup. If you do want to maintain descriptions, we should limit them to two, one just above each gray box.

Finally, about the wording, I was wondering if we'll run into localization problems with "Drafting from," as you mentioned for my "Scripture Forge will be trained that..." If we could improve this wording at all, that'd be great, though I don't want to hold things up too long. I think that the use of "language model" in the first step is isolated and a little obscure, but we may be able to mitigate that by reusing the term here?

> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/2730#-:-O8ee89kBKeI2CH0CL03:b-80sne)* status: 0 of 8 files reviewed, all discussions resolved

**Comment by Nateowami** [comment]
@josephmyers I've incorporated your changes and cleaned things up, as well as adding some new ideas. Here's what it looks like now, in French:

**Review by josephmyers — COMMENTED** [review]
Yeah, this looks solid.

> Reviewed 1 of 7 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/2730#-:-O9NFhsH0hXJUV5q9yhz:b-eczc1n)* status: 1 of 8 files reviewed, all discussions resolved

**Review by kylebuss — CHANGES_REQUESTED** [review]
Nice work Joseph and Nathaniel! I've made a few suggestions.

> Reviewed 1 of 8 files at r1, 9 of 9 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/2730#-:-OD8-LMr9EOfsqeJ1Djd:b5mware)* status: all files reviewed, 4 unresolved discussions (waiting on @Nateowami and @RaymondLuong3)

___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-generation-steps/draft-generation-steps.component.spec.ts` line 389 at r3](https://reviewable.io/reviews/sillsdev/web-xforge/2730#-OD7zoIK5egAD8PxgJ9R:-OD7zoIK5egAD8PxgJ9S:b-r12vw) ([raw file](https://github.com/sillsdev/web-xforge/blob/ecb601f1b10b03b9b68396f8075a3fdd50c14fb8/src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-generation-steps/draft-generation-steps.component.spec.ts#L389)):*
> ```XML
>     });
>   });
> ```

We should probably add a test that the warning on the first step if the user clicks the Next button without marking the checkbox.
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-generation-steps/draft-generation-steps.component.html` line 11 at r3](https://reviewable.io/reviews/sillsdev/web-xforge/2730#-OD7xAtB9Zh2Gdok_B-n:-OD7xAtB9Zh2Gdok_B-o:b-lzckq4) ([raw file](https://github.com/sillsdev/web-xforge/blob/ecb601f1b10b03b9b68396f8075a3fdd50c14fb8/src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-generation-steps/draft-generation-steps.component.html#L11)):*
> ```HTML
>         <app-confirm-sources (languageCodesVerified)="languagesVerified = $event"></app-confirm-sources>
>         @if (nextClickedOnLanguageVerification && !languagesVerified) {
>           <app-notice type="error" mode="fill-dark">{{ t("confirm_codes_correct_to_continue") }}</app-notice>
> ```

nit  I'm not certain how intuitive this will be for users to know what to do if the try and proceed without checking the 'All languages codes are correct.'

We may want to highlight or inform users that the checkbox is required for users to mark before they can proceed to the next step.

Perhaps the warning could simply be moved to the top of the container and remind the user to review the language codes and mark that they are all correct before proceeding?




_Code quote:_
```HTML
<app-notice type="error" mode="fill-dark">{{ t("confirm_codes_correct_to_continue") }}</app-notice>
```
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/confirm-sources/confirm-sources.stories.ts` line 5 at r3](https://reviewable.io/reviews/sillsdev/web-xforge/2730#-OD7uKnk-K3tuXyqWyHD:-OD7uKnk-K3tuXyqWyHE:b-x9cfsj) ([raw file](https://github.com/sillsdev/web-xforge/blob/ecb601f1b10b03b9b68396f8075a3fdd50c14fb8/src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/confirm-sources/confirm-sources.stories.ts#L5)):*
> ```XML
> import { Meta, moduleMetadata, StoryObj } from '@storybook/angular';
> // import { I18nStoryModule } from '../../../../xforge-common/i18n-story.module';
> // import { UICommonModule } from '../../../../xforge-common/ui-common.module';
> ```

Please remove these since they are not being used.



_Code quote:_
```XML
// import { I18nStoryModule } from '../../../../xforge-common/i18n-story.module';
// import { UICommonModule } from '../../../../xforge-common/ui-common.module';
```
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/confirm-sources/confirm-sources.stories.ts` line 8 at r3](https://reviewable.io/reviews/sillsdev/web-xforge/2730#-OD7uW2z7XR9lwVwFo_m:-OD7uW2z7XR9lwVwFo_n:bc8p8ac) ([raw file](https://github.com/sillsdev/web-xforge/blob/ecb601f1b10b03b9b68396f8075a3fdd50c14fb8/src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/confirm-sources/confirm-sources.stories.ts#L8)):*
> ```XML
> import { createTestProjectProfile } from 'realtime-server/lib/esm/scriptureforge/models/sf-project-test-data';
> import { instance, mock, when } from 'ts-mockito';
> import { ActivatedProjectService } from '../../../../xforge-common/activated-project.service';
> ```

Please remove the '../../../../'.



_Code quote:_
```XML
'../../../../xforge-common/activated-project.service'
```

**Review by RaymondLuong3 — CHANGES_REQUESTED** [review]
Looks like be both started reviewing this about the same time. I also have some suggestions, but the core of it looks solid.

> Reviewed 1 of 8 files at r1, 9 of 9 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/2730#-:-OD88ul97ZHs7GiJ8z22:b-d53kf7)* status: all files reviewed, 13 unresolved discussions (waiting on @Nateowami)

___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-generation-steps/draft-generation-steps.component.html` line 23 at r3](https://reviewable.io/reviews/sillsdev/web-xforge/2730#-OD82gY5B7rKf9I_mW_l:-OD82gY5B7rKf9I_mW_m:b-e5sx4o) ([raw file](https://github.com/sillsdev/web-xforge/blob/ecb601f1b10b03b9b68396f8075a3fdd50c14fb8/src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-generation-steps/draft-generation-steps.component.html#L23)):*
> ```HTML
>       <mat-step [completed]="userSelectedTranslateBooks.length > 0">
>         <ng-template matStepLabel>
>           {{ t("choose_books_to_translate_label") }}
> ```

Any reason to not use the wording in the screenshots. Right now this just says "Drafting" instead of "Choose books to translate."



_Code quote:_
```HTML
          {{ t("choose_books_to_translate_label") }}
```
___
*[`src/SIL.XForge.Scripture/ClientApp/src/assets/i18n/non_checking_en.json` line 111 at r3](https://reviewable.io/reviews/sillsdev/web-xforge/2730#-OD83nXq3qzB2v1yFDDc:-OD83nXq3qzB2v1yFDDd:b-fu9saq) ([raw file](https://github.com/sillsdev/web-xforge/blob/ecb601f1b10b03b9b68396f8075a3fdd50c14fb8/src/SIL.XForge.Scripture/ClientApp/src/assets/i18n/non_checking_en.json#L111)):*
> ```JSON
>     "confirm_project_setup": "Confirm project setup",
>     "drafting_from_heading": "Drafting from {{ draftingSourceShortNames }} ({{ draftingSourceLanguage }})",
>     "how_to_change_language_codes": "Language codes can be changed in Paratext by going to Project Settings > Project Properties > Language.",
> ```

This is not easy to translate, and the wedges would not work for RTL languages. I think you may have to be more explicit here. "Languages codes can be changed in Paratext by choosing project settings, then project properties, then language.



_Code quote:_
```JSON
   "how_to_change_language_codes": "Language codes can be changed in Paratext by going to Project Settings > Project Properties > Language.",
```
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-generation-steps/draft-generation-steps.component.spec.ts` line 238 at r3](https://reviewable.io/reviews/sillsdev/web-xforge/2730#-OD81CHq02AV71Xjm3Lq:-OD81CHq02AV71Xjm3Lr:b-emb1bp) ([raw file](https://github.com/sillsdev/web-xforge/blob/ecb601f1b10b03b9b68396f8075a3fdd50c14fb8/src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-generation-steps/draft-generation-steps.component.spec.ts#L238)):*
> ```XML
> 
>       clickConfirmLanguages(fixture);
>       var test = fixture.debugElement.queryAll(By.css('mat-step-header'));
> ```

This could be a const.



_Code quote:_
```XML
      var test = fixture.debugElement.queryAll(By.css('mat-step-header'));
```
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-generation-steps/draft-generation-steps.component.spec.ts` line 295 at r3](https://reviewable.io/reviews/sillsdev/web-xforge/2730#-OD81fpqDOp9uqgixj_3:-OD81fpqDOp9uqgixj_4:b-hkuqzq) ([raw file](https://github.com/sillsdev/web-xforge/blob/ecb601f1b10b03b9b68396f8075a3fdd50c14fb8/src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-generation-steps/draft-generation-steps.component.spec.ts#L295)):*
> ```XML
> 
>       clickConfirmLanguages(fixture);
>       var test = fixture.debugElement.queryAll(By.css('mat-step-header'));
> ```

This can be a const.



_Code quote:_
```XML
     var test = fixture.debugElement.queryAll(By.css('mat-step-header'));
```
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-generation-steps/draft-generation-steps.component.spec.ts` line 331 at r3](https://reviewable.io/reviews/sillsdev/web-xforge/2730#-OD81jET-E1v8Qp0c2r8:-OD81jET-E1v8Qp0c2r9:b-hkuqzq) ([raw file](https://github.com/sillsdev/web-xforge/blob/ecb601f1b10b03b9b68396f8075a3fdd50c14fb8/src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-generation-steps/draft-generation-steps.component.spec.ts#L331)):*
> ```XML
>       fixture.detectChanges();
>       clickConfirmLanguages(fixture);
>       var test = fixture.debugElement.queryAll(By.css('mat-step-header'));
> ```

This can be a const.



_Code quote:_
```XML
      var test = fixture.debugElement.queryAll(By.css('mat-step-header'));
```
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/confirm-sources/confirm-sources.component.ts` line 8 at r3](https://reviewable.io/reviews/sillsdev/web-xforge/2730#-OD84ktTBHJli_lEYykh:-OD84ktTBHJli_lEYyki:bou7p8x) ([raw file](https://github.com/sillsdev/web-xforge/blob/ecb601f1b10b03b9b68396f8075a3fdd50c14fb8/src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/confirm-sources/confirm-sources.component.ts#L8)):*
> ```XML
> import { TranslateSource } from 'realtime-server/lib/esm/scriptureforge/models/translate-config';
> import { ActivatedProjectService } from '../../../../xforge-common/activated-project.service';
> import { I18nService } from '../../../../xforge-common/i18n.service';
> ```

Nit: Remove the `../../../../`



_Code quote:_
```XML
import { I18nService } from '../../../../xforge-common/i18n.service';
```
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/confirm-sources/confirm-sources.component.ts` line 68 at r3](https://reviewable.io/reviews/sillsdev/web-xforge/2730#-OD86xHqBDy1DJWaXZ4V:-OD86xHqBDy1DJWaXZ4W:bp6j71q) ([raw file](https://github.com/sillsdev/web-xforge/blob/ecb601f1b10b03b9b68396f8075a3fdd50c14fb8/src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/confirm-sources/confirm-sources.component.ts#L68)):*
> ```XML
>     return Array.from(new Set(projects.map(p => p.writingSystem.tag)))
>       .map(tag => this.i18nService.getLanguageDisplayName(tag) ?? tag)
>       .join(', ');
> ```

We want to use i18nService.enumerateList here.



_Code quote:_
```XML
      .join(', ');
```
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/confirm-sources/confirm-sources.component.ts` line 69 at r3](https://reviewable.io/reviews/sillsdev/web-xforge/2730#-OD85EA0-eF1oSfwvVDP:-OD85EA0-eF1oSfwvVDQ:b-xdawl1) ([raw file](https://github.com/sillsdev/web-xforge/blob/ecb601f1b10b03b9b68396f8075a3fdd50c14fb8/src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/confirm-sources/confirm-sources.component.ts#L69)):*
> ```XML
>       .map(tag => this.i18nService.getLanguageDisplayName(tag) ?? tag)
>       .join(', ');
>   }
> ```

These methods should come below the getters



_Code quote:_
```XML
  confirmationChanged(change: MatCheckboxChange): void {
    this.languageCodesVerified.emit(change.checked);
  }

  displayNameForProjectsLanguages(projects: (TranslateSource | SFProjectProfile)[]): string {
    return Array.from(new Set(projects.map(p => p.writingSystem.tag)))
      .map(tag => this.i18nService.getLanguageDisplayName(tag) ?? tag)
      .join(', ');
  }
```
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/confirm-sources/confirm-sources.component.ts` line 85 at r3](https://reviewable.io/reviews/sillsdev/web-xforge/2730#-OD86NfDEunV1MwKtgre:-OD86NfDEunV1MwKtgrf:b1z1b23) ([raw file](https://github.com/sillsdev/web-xforge/blob/ecb601f1b10b03b9b68396f8075a3fdd50c14fb8/src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/confirm-sources/confirm-sources.component.ts#L85)):*
> ```XML
>   get draftingSourceShortNames(): string {
>     return this.draftingSources.map(p => p.shortName).join(', ');
>   }
> ```

I see that we currently do not support more than 1 drafting source, and I am not certain if there ever will be more than 1 drafting source, so this does not seem necessary.
If we will indeed support more than 1 drafting source, then we should call enumerateList in i18nService to stitch the source shortnames together.



_Code quote:_
```XML
  get draftingSourceShortNames(): string {
    return this.draftingSources.map(p => p.shortName).join(', ');
  }
```

**Review by Nateowami — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/2730)* status: 7 of 10 files reviewed, 12 unresolved discussions (waiting on @kylebuss and @RaymondLuong3)

___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/confirm-sources/confirm-sources.component.ts` line 68 at r3](https://reviewable.io/reviews/sillsdev/web-xforge/2730#-OD86xHqBDy1DJWaXZ4V:-OD8EVTvEJy1RBr3sBUt:b-896fix) ([raw file](https://github.com/sillsdev/web-xforge/blob/ecb601f1b10b03b9b68396f8075a3fdd50c14fb8/src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/confirm-sources/confirm-sources.component.ts#L68)):*
<details><summary><i>Previously, RaymondLuong3 (Raymond Luong) wrote…</i></summary><blockquote>

We want to use i18nService.enumerateList here.
</blockquote></details>

Done.
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/confirm-sources/confirm-sources.component.ts` line 69 at r3](https://reviewable.io/reviews/sillsdev/web-xforge/2730#-OD85EA0-eF1oSfwvVDP:-OD8EWicCu9LCq8Tkbg1:bb76mu4) ([raw file](https://github.com/sillsdev/web-xforge/blob/ecb601f1b10b03b9b68396f8075a3fdd50c14fb8/src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/confirm-sources/confirm-sources.component.ts#L69)):*
<details><summary><i>Previously, RaymondLuong3 (Raymond Luong) wrote…</i></summary><blockquote>

These methods should come below the getters
</blockquote></details>

Why?
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/confirm-sources/confirm-sources.component.ts` line 85 at r3](https://reviewable.io/reviews/sillsdev/web-xforge/2730#-OD86NfDEunV1MwKtgre:-OD8HxC-8waKo1A-0IQ9:bqc8szj) ([raw file](https://github.com/sillsdev/web-xforge/blob/ecb601f1b10b03b9b68396f8075a3fdd50c14fb8/src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/confirm-sources/confirm-sources.component.ts#L85)):*
<details><summary><i>Previously, RaymondLuong3 (Raymond Luong) wrote…</i></summary><blockquote>

I see that we currently do not support more than 1 drafting source, and I am not certain if there ever will be more than 1 drafting source, so this does not seem necessary.
If we will indeed support more than 1 drafting source, then we should call enumerateList in i18nService to stitch the source shortnames together.
</blockquote></details>

I think we likely will in the future, and wanted to bake it in early. Updated.
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/confirm-sources/confirm-sources.stories.ts` line 5 at r3](https://reviewable.io/reviews/sillsdev/web-xforge/2730#-OD7uKnk-K3tuXyqWyHD:-OD8EZTh8LB5oEXgS_6x:b-896fix) ([raw file](https://github.com/sillsdev/web-xforge/blob/ecb601f1b10b03b9b68396f8075a3fdd50c14fb8/src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/confirm-sources/confirm-sources.stories.ts#L5)):*
<details><summary><i>Previously, kylebuss (Kyle Buss) wrote…</i></summary><blockquote>

Please remove these since they are not being used.
</blockquote></details>

Done.
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/confirm-sources/confirm-sources.stories.ts` line 8 at r3](https://reviewable.io/reviews/sillsdev/web-xforge/2730#-OD7uW2z7XR9lwVwFo_m:-OD8EZwHAPnc8VBxEa5A:b-896fix) ([raw file](https://github.com/sillsdev/web-xforge/blob/ecb601f1b10b03b9b68396f8075a3fdd50c14fb8/src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/confirm-sources/confirm-sources.stories.ts#L8)):*
<details><summary><i>Previously, kylebuss (Kyle Buss) wrote…</i></summary><blockquote>

Please remove the '../../../../'.
</blockquote></details>

Done.
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-generation-steps/draft-generation-steps.component.html` line 23 at r3](https://reviewable.io/reviews/sillsdev/web-xforge/2730#-OD82gY5B7rKf9I_mW_l:-OD8Ebcp5PiXUPppg0f9:bx61gi0) ([raw file](https://github.com/sillsdev/web-xforge/blob/ecb601f1b10b03b9b68396f8075a3fdd50c14fb8/src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-generation-steps/draft-generation-steps.component.html#L23)):*
<details><summary><i>Previously, RaymondLuong3 (Raymond Luong) wrote…</i></summary><blockquote>

Any reason to not use the wording in the screenshots. Right now this just says "Drafting" instead of "Choose books to translate."
</blockquote></details>

This is not changed in this branch. It was changed as part of moving to a horizontal stepper.
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-generation-steps/draft-generation-steps.component.spec.ts` line 238 at r3](https://reviewable.io/reviews/sillsdev/web-xforge/2730#-OD81CHq02AV71Xjm3Lq:-OD8Ehn436m-HjOC9Gzl:b-896fix) ([raw file](https://github.com/sillsdev/web-xforge/blob/ecb601f1b10b03b9b68396f8075a3fdd50c14fb8/src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-generation-steps/draft-generation-steps.component.spec.ts#L238)):*
<details><summary><i>Previously, RaymondLuong3 (Raymond Luong) wrote…</i></summary><blockquote>

This could be a const.
</blockquote></details>

Done.
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-generation-steps/draft-generation-steps.component.spec.ts` line 295 at r3](https://reviewable.io/reviews/sillsdev/web-xforge/2730#-OD81fpqDOp9uqgixj_3:-OD8EiAcBcf--Ut0ok2Y:b-896fix) ([raw file](https://github.com/sillsdev/web-xforge/blob/ecb601f1b10b03b9b68396f8075a3fdd50c14fb8/src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-generation-steps/draft-generation-steps.component.spec.ts#L295)):*
<details><summary><i>Previously, RaymondLuong3 (Raymond Luong) wrote…</i></summary><blockquote>

This can be a const.
</blockquote></details>

Done.
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-generation-steps/draft-generation-steps.component.spec.ts` line 331 at r3](https://reviewable.io/reviews/sillsdev/web-xforge/2730#-OD81jET-E1v8Qp0c2r8:-OD8EiSzAJC1oQ3ahZra:b-896fix) ([raw file](https://github.com/sillsdev/web-xforge/blob/ecb601f1b10b03b9b68396f8075a3fdd50c14fb8/src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-generation-steps/draft-generation-steps.component.spec.ts#L331)):*
<details><summary><i>Previously, RaymondLuong3 (Raymond Luong) wrote…</i></summary><blockquote>

This can be a const.
</blockquote></details>

Done.
___
*[`src/SIL.XForge.Scripture/ClientApp/src/assets/i18n/non_checking_en.json` line 111 at r3](https://reviewable.io/reviews/sillsdev/web-xforge/2730#-OD83nXq3qzB2v1yFDDc:-OD8EqZdDBK203JsSDc-:b-sfxwn6) ([raw file](https://github.com/sillsdev/web-xforge/blob/ecb601f1b10b03b9b68396f8075a3fdd50c14fb8/src/SIL.XForge.Scripture/ClientApp/src/assets/i18n/non_checking_en.json#L111)):*
<details><summary><i>Previously, RaymondLuong3 (Raymond Luong) wrote…</i></summary><blockquote>

This is not easy to translate, and the wedges would not work for RTL languages. I think you may have to be more explicit here. "Languages codes can be changed in Paratext by choosing project settings, then project properties, then language.
</blockquote></details>

Why would this be hard to translate, and why can't RTL languages use wedges (or some similar device)?

**Review by RaymondLuong3 — CHANGES_REQUESTED** [review]
> Reviewed 3 of 3 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/2730)* status: all files reviewed, 5 unresolved discussions (waiting on @kylebuss and @Nateowami)

___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/confirm-sources/confirm-sources.component.ts` line 69 at r3](https://reviewable.io/reviews/sillsdev/web-xforge/2730#-OD85EA0-eF1oSfwvVDP:-OD8NJHrEcWfdXFQy5Gt:bwdtgo9) ([raw file](https://github.com/sillsdev/web-xforge/blob/ecb601f1b10b03b9b68396f8075a3fdd50c14fb8/src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/confirm-sources/confirm-sources.component.ts#L69)):*
<details><summary><i>Previously, Nateowami wrote…</i></summary><blockquote>

Why?
</blockquote></details>

Our convention is to have public and private getters below the constructor, and then public and private methods below that. It would be nice to follow those conventions. Not a blocker though.
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-generation-steps/draft-generation-steps.component.spec.ts` line 389 at r3](https://reviewable.io/reviews/sillsdev/web-xforge/2730#-OD7zoIK5egAD8PxgJ9R:-OD8Oa7s0k29sTB2q4Hx:b3ftnv1) ([raw file](https://github.com/sillsdev/web-xforge/blob/ecb601f1b10b03b9b68396f8075a3fdd50c14fb8/src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-generation-steps/draft-generation-steps.component.spec.ts#L389)):*
<details><summary><i>Previously, kylebuss (Kyle Buss) wrote…</i></summary><blockquote>

We should probably add a test that the warning on the first step if the user clicks the Next button without marking the checkbox.
</blockquote></details>

It should be fairly easy to have a test that the next button does not work if the checkbox has not been emitted.
___
*[`src/SIL.XForge.Scripture/ClientApp/src/assets/i18n/non_checking_en.json` line 111 at r3](https://reviewable.io/reviews/sillsdev/web-xforge/2730#-OD83nXq3qzB2v1yFDDc:-OD8NxJb9WhGqGjDCuMQ:b-h7km3c) ([raw file](https://github.com/sillsdev/web-xforge/blob/ecb601f1b10b03b9b68396f8075a3fdd50c14fb8/src/SIL.XForge.Scripture/ClientApp/src/assets/i18n/non_checking_en.json#L111)):*
<details><summary><i>Previously, Nateowami wrote…</i></summary><blockquote>

Why would this be hard to translate, and why can't RTL languages use wedges (or some similar device)?
</blockquote></details>

I tried doing a quick google search to see if wedges are or are not recommended. I didn't find anything useful. I know wedges are used like "" in French and other languages. I'm not sure what meaning they carry in Arabic, but the translator would need to know it use the correct direction for the wedge. Wouldn't it be safer to update the string to minimize issues in the translation?

**Comment by josephmyers** [comment]
Note that this PR will not include the message containing the Settings link, which is present in the Balsamiq wireframe. We decided to postpone this line to a later task.

**Review by josephmyers — COMMENTED** [review]
> Reviewed 4 of 4 files at r9.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/2730)* status: 9 of 10 files reviewed, 3 unresolved discussions (waiting on @kylebuss, @Nateowami, and @RaymondLuong3)

___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-generation-steps/draft-generation-steps.component.html` line 11 at r3](https://reviewable.io/reviews/sillsdev/web-xforge/2730#-OD7xAtB9Zh2Gdok_B-n:-OD9suKn1LJAaeL79r8a:b-ocq9a4) ([raw file](https://github.com/sillsdev/web-xforge/blob/ecb601f1b10b03b9b68396f8075a3fdd50c14fb8/src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-generation-steps/draft-generation-steps.component.html#L11)):*
<details><summary><i>Previously, kylebuss (Kyle Buss) wrote…</i></summary><blockquote>

nit  I'm not certain how intuitive this will be for users to know what to do if the try and proceed without checking the 'All languages codes are correct.'

We may want to highlight or inform users that the checkbox is required for users to mark before they can proceed to the next step.

Perhaps the warning could simply be moved to the top of the container and remind the user to review the language codes and mark that they are all correct before proceeding?

</blockquote></details>

I feel like this is picky enough that we can postpone it to a later task, to do if necessary. As long as the page is simple, the user should easily be able to scan the page and figure out what to do. This is the single only interactive element on the page content, so we shouldn't be asking too much.
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-generation-steps/draft-generation-steps.component.spec.ts` line 389 at r3](https://reviewable.io/reviews/sillsdev/web-xforge/2730#-OD7zoIK5egAD8PxgJ9R:-OD9zh75-nxxq3lqlRd-:bynmxsx) ([raw file](https://github.com/sillsdev/web-xforge/blob/ecb601f1b10b03b9b68396f8075a3fdd50c14fb8/src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-generation-steps/draft-generation-steps.component.spec.ts#L389)):*
<details><summary><i>Previously, RaymondLuong3 (Raymond Luong) wrote…</i></summary><blockquote>

It should be fairly easy to have a test that the next button does not work if the checkbox has not been emitted.
</blockquote></details>

Done. I used `tryAdvanceNextStep`, which I believe is equivalent, if y'all are fine with this

**Review by kylebuss — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r10, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/2730#-:-ODBiLR52PNR5WaCdcje:bnfp4nl)* status: all files reviewed, 2 unresolved discussions (waiting on @Nateowami and @RaymondLuong3)

**Review by RaymondLuong3 — APPROVED** [review]
> Reviewed 4 of 4 files at r9, 1 of 1 files at r10, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/2730)* status: all files reviewed, 1 unresolved discussion (waiting on @Nateowami)

**Pull request merged**
