### PR TITLE
SF-2960 Remove flex-layout dependency

### PR DESCRIPTION
**Pull request by RaymondLuong3**
This PR removes the angular flex-layout dependency and converts the component template files to work without using flex layout api. The best way to ensure that the conversion is adequate is by having 2 windows open, one on QA and one on this branch and check that each component still behaves as expected.

It would be good to check the layout of each component by varying the screen size and checking right-to-left interface.

- - -
This change is [Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/2729)

### CODE REVIEW

**Review by Nateowami — DISMISSED** [review]
Thanks for your work on this. I have reviewed roughly half the files. I've found a bunch of things that I don't think are actually needed. Can you 

> Reviewed 17 of 21 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/2729#-:-O7Usow62Z3WotuNoyOH:by57fsg)* status: 17 of 21 files reviewed, 11 unresolved discussions (waiting on @kylebuss and @RaymondLuong3)

___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/connect-project/connect-project.component.html` line 51 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/2729#-O7UZR7jDROR-kdh_PYP:-O7UZR7jDROR-kdh_PYQ:b50x1jx) ([raw file](https://github.com/sillsdev/web-xforge/blob/9e99208a222f790c56364693e7df067665f7d3b6/src/SIL.XForge.Scripture/ClientApp/src/app/connect-project/connect-project.component.html#L51)):*
> ```HTML
>                 @if (isBasedOnProjectSet) {
>                   <div>
>                     <div class="flex-column">
> ```

I don't think this class is doing anything.
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/settings/settings.component.html` line 1 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/2729#-O7U_6vY0Fwq9L_BCHhB:-O7U_6vY0Fwq9L_BCHhC:b-xhxht2) ([raw file](https://github.com/sillsdev/web-xforge/blob/9e99208a222f790c56364693e7df067665f7d3b6/src/SIL.XForge.Scripture/ClientApp/src/app/settings/settings.component.html#L1)):*
> ```HTML
> <ng-container *transloco="let t; read: 'settings'">
> ```

The spacing/margin of this component has been broken. 

- There is now too much spacing between the top title of the page, and the container below it
- There is now not enough spacing above the "Danger Zone" text

I strongly recommend opening QA in one tab, and localhost in another, and for every component you work on, switch between the two tabs so you get a visual indication of what has changed. We don't need everything to be identical to the pixel, but obvious issues like this can be caught very easily.
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/settings/settings.component.html` line 2 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/2729#-O7UZjTb79Idzolicd3t:-O7UZjTb79Idzolicd3u:b796yjo) ([raw file](https://github.com/sillsdev/web-xforge/blob/9e99208a222f790c56364693e7df067665f7d3b6/src/SIL.XForge.Scripture/ClientApp/src/app/settings/settings.component.html#L2)):*
> ```HTML
> <ng-container *transloco="let t; read: 'settings'">
>   <div class="container flex-column">
> ```

I can't tell that this flex-column class is doing anything.
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/settings/settings.component.html` line 387 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/2729#-O7Uaakf4ga08pT_MeOa:-O7Uaakf4ga08pT_MeOb:blynewe) ([raw file](https://github.com/sillsdev/web-xforge/blob/9e99208a222f790c56364693e7df067665f7d3b6/src/SIL.XForge.Scripture/ClientApp/src/app/settings/settings.component.html#L387)):*
> ```HTML
>           </p>
>         }
>         <div class="delete-btn-container">
> ```

You don't need a container at all if you just set `align-self: flex-end;` on the button.
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/shared/share/share-control.component.html` line 11 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/2729#-O7Ubg_wD_X-u-CrBpv7:-O7Ubg_wD_X-u-CrBpv8:bzen2l0) ([raw file](https://github.com/sillsdev/web-xforge/blob/9e99208a222f790c56364693e7df067665f7d3b6/src/SIL.XForge.Scripture/ClientApp/src/app/shared/share/share-control.component.html#L11)):*
> ```HTML
>     <div class="invite-by-email">
>       <h3>{{ t("send_a_link") }}</h3>
>       <div class="flex-row">
> ```

This class doesn't appear to do anything.
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.scss` line 72 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/2729#-O7V18CD7G2ncT_e5n5H:-O7V18CD7G2ncT_e5n5I:b5ldxe8) ([raw file](https://github.com/sillsdev/web-xforge/blob/9e99208a222f790c56364693e7df067665f7d3b6/src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.scss#L72)):*
> ```SCSS
> 
>   .toolbar-options {
>     display: flex;
> ```

As far as I can tell, only `display: flex` is needed.
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/multi-viewer/multi-viewer.component.scss` line 27 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/2729#-O7UYJ0c1qnQoGenwvlA:-O7UYJ0c1qnQoGenwvlB:b-hhc0l9) ([raw file](https://github.com/sillsdev/web-xforge/blob/9e99208a222f790c56364693e7df067665f7d3b6/src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/multi-viewer/multi-viewer.component.scss#L27)):*
> ```SCSS
> }
> 
> ::ng-deep .other-viewer {
> ```

Using `::ng-deep` as the first item makes this completely global. I think you can rewrite this to `.other-viewer ::ng-deep` and it will still match the element, without bleeding out of this component.
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/note-dialog/note-dialog.component.html` line 76 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/2729#-O7Ub2wL0tBQ3PorJnSO:-O7Ub2wL0tBQ3PorJnSP:bxms8v6) ([raw file](https://github.com/sillsdev/web-xforge/blob/9e99208a222f790c56364693e7df067665f7d3b6/src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/note-dialog/note-dialog.component.html#L76)):*
> ```HTML
>       }
>     </mat-dialog-content>
>     <mat-dialog-actions align="end">
> ```

I don't think this is actually needed.
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/translate/training-progress/training-progress.component.html` line 11 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/2729#-O7UUEWZDy8mB81yN5vB:-O7UUEWZDy8mB81yN5vC:b2s2ria) ([raw file](https://github.com/sillsdev/web-xforge/blob/9e99208a222f790c56364693e7df067665f7d3b6/src/SIL.XForge.Scripture/ClientApp/src/app/translate/training-progress/training-progress.component.html#L11)):*
> ```HTML
>       </div>
>       <div class="training-content">
>         <div class="text-ellipsis">A message to be added</div>
> ```

What is this?
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/translate/training-progress/training-progress.component.scss` line 20 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/2729#-O7UvNNV8XRqEdKmQt3z:-O7UvNNV8XRqEdKmQt4-:b-yzivts) ([raw file](https://github.com/sillsdev/web-xforge/blob/9e99208a222f790c56364693e7df067665f7d3b6/src/SIL.XForge.Scripture/ClientApp/src/app/translate/training-progress/training-progress.component.scss#L20)):*
> ```SCSS
>     padding-inline-start: 10px;
>     display: flex;
>     place-content: space-between;
> ```

The entire purpose of the `place-content` property is to be able to specify `align-content` and `justify-content` at the same time. Since this is only specifying one, it would be clearer to use the actual property name (`justify-content: space-between`). (Same later in the file)
___
*[`src/SIL.XForge.Scripture/ClientApp/src/xforge-common/system-administration/system-administration.component.html` line 1 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/2729#-O7UP9vJC7MBv0I-f8Oq:-O7UP9vK1GjxxFe2BlP3:b-zhwq8k) ([raw file](https://github.com/sillsdev/web-xforge/blob/9e99208a222f790c56364693e7df067665f7d3b6/src/SIL.XForge.Scripture/ClientApp/src/xforge-common/system-administration/system-administration.component.html#L1)):*
> ```HTML
> <div class="body-content flex-start">
> ```

I don't think the`flex-start` class is doing anything.

**Review by kylebuss — COMMENTED** [review]
As Nathaniel mentioned, most of the changed `flex` classes can be removed entirely and not see any UI changes. It appears that the `app-content` class in `app.component.scss` is handling a bulk of the work for us. 

> Reviewed 2 of 21 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/2729#-:-O7VEm0x9kGzCe8YuF27:b-lrrew2)* status: 19 of 21 files reviewed, 11 unresolved discussions (waiting on @Nateowami and @RaymondLuong3)

___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/settings/settings.component.html` line 1 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/2729#-O7U_6vY0Fwq9L_BCHhB:-O7VGmyvABDDiu0bisYi:bb9tupr) ([raw file](https://github.com/sillsdev/web-xforge/blob/9e99208a222f790c56364693e7df067665f7d3b6/src/SIL.XForge.Scripture/ClientApp/src/app/settings/settings.component.html#L1)):*
<details><summary><i>Previously, Nateowami (Nathaniel Paulus) wrote…</i></summary><blockquote>

The spacing/margin of this component has been broken. 

- There is now too much spacing between the top title of the page, and the container below it
- There is now not enough spacing above the "Danger Zone" text

I strongly recommend opening QA in one tab, and localhost in another, and for every component you work on, switch between the two tabs so you get a visual indication of what has changed. We don't need everything to be identical to the pixel, but obvious issues like this can be caught very easily.
</blockquote></details>

There was a `margin-bottom: 2rem;` that was set by the `fxLayoutGap` directly on the `element.style` for both the Settings and Translate `div` which is causing the spacing to now be off.

**Review by RaymondLuong3 — COMMENTED** [review]
Thanks for reviewing this. I found a couple more places where `flex-column` and `flex-row` classes could be removed. I've fixed the spacing issues on the settings page and another one for the share control. Let me know if you see anything else.

> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/2729#-:-O7_Bz2HAx5hhoK3aumi:b-jorzmz)* status: 19 of 21 files reviewed, 9 unresolved discussions (waiting on @kylebuss and @Nateowami)

___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/connect-project/connect-project.component.html` line 51 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/2729#-O7UZR7jDROR-kdh_PYP:-O7_19oV2ILTKs4Fumf9:b-896fix) ([raw file](https://github.com/sillsdev/web-xforge/blob/9e99208a222f790c56364693e7df067665f7d3b6/src/SIL.XForge.Scripture/ClientApp/src/app/connect-project/connect-project.component.html#L51)):*
<details><summary><i>Previously, Nateowami (Nathaniel Paulus) wrote…</i></summary><blockquote>

I don't think this class is doing anything.
</blockquote></details>

Done.
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/settings/settings.component.html` line 1 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/2729#-O7U_6vY0Fwq9L_BCHhB:-O7_Cn0y79LLIKrXVYVh:b-896fix) ([raw file](https://github.com/sillsdev/web-xforge/blob/9e99208a222f790c56364693e7df067665f7d3b6/src/SIL.XForge.Scripture/ClientApp/src/app/settings/settings.component.html#L1)):*
<details><summary><i>Previously, kylebuss (Kyle Buss) wrote…</i></summary><blockquote>

There was a `margin-bottom: 2rem;` that was set by the `fxLayoutGap` directly on the `element.style` for both the Settings and Translate `div` which is causing the spacing to now be off.
</blockquote></details>

Done.
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/settings/settings.component.html` line 2 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/2729#-O7UZjTb79Idzolicd3t:-O7_1Egv9Q_hCGwRZyZz:b-896fix) ([raw file](https://github.com/sillsdev/web-xforge/blob/9e99208a222f790c56364693e7df067665f7d3b6/src/SIL.XForge.Scripture/ClientApp/src/app/settings/settings.component.html#L2)):*
<details><summary><i>Previously, Nateowami (Nathaniel Paulus) wrote…</i></summary><blockquote>

I can't tell that this flex-column class is doing anything.
</blockquote></details>

Done.
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/settings/settings.component.html` line 387 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/2729#-O7Uaakf4ga08pT_MeOa:-O7_2Z7-5VGBbRBLew_9:b-896fix) ([raw file](https://github.com/sillsdev/web-xforge/blob/9e99208a222f790c56364693e7df067665f7d3b6/src/SIL.XForge.Scripture/ClientApp/src/app/settings/settings.component.html#L387)):*
<details><summary><i>Previously, Nateowami (Nathaniel Paulus) wrote…</i></summary><blockquote>

You don't need a container at all if you just set `align-self: flex-end;` on the button.
</blockquote></details>

Done.
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/shared/share/share-control.component.html` line 11 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/2729#-O7Ubg_wD_X-u-CrBpv7:-O7_3QDX99Pc8M9Q1cAN:b-896fix) ([raw file](https://github.com/sillsdev/web-xforge/blob/9e99208a222f790c56364693e7df067665f7d3b6/src/SIL.XForge.Scripture/ClientApp/src/app/shared/share/share-control.component.html#L11)):*
<details><summary><i>Previously, Nateowami (Nathaniel Paulus) wrote…</i></summary><blockquote>

This class doesn't appear to do anything.
</blockquote></details>

Done.
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.scss` line 72 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/2729#-O7V18CD7G2ncT_e5n5H:-O7_4KOCBvJqrh4NiF3u:b7e3d3v) ([raw file](https://github.com/sillsdev/web-xforge/blob/9e99208a222f790c56364693e7df067665f7d3b6/src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.scss#L72)):*
<details><summary><i>Previously, Nateowami (Nathaniel Paulus) wrote…</i></summary><blockquote>

As far as I can tell, only `display: flex` is needed.
</blockquote></details>

It is needed to get everything to work when there are other viewers on the page.

___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/multi-viewer/multi-viewer.component.scss` line 27 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/2729#-O7UYJ0c1qnQoGenwvlA:-O7_4p4uBKpgBvx6x-D4:bhnlb1a) ([raw file](https://github.com/sillsdev/web-xforge/blob/9e99208a222f790c56364693e7df067665f7d3b6/src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/multi-viewer/multi-viewer.component.scss#L27)):*
<details><summary><i>Previously, Nateowami (Nathaniel Paulus) wrote…</i></summary><blockquote>

Using `::ng-deep` as the first item makes this completely global. I think you can rewrite this to `.other-viewer ::ng-deep` and it will still match the element, without bleeding out of this component.
</blockquote></details>

Thanks. I even had in mind to do that but it slipped through.
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/note-dialog/note-dialog.component.html` line 76 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/2729#-O7Ub2wL0tBQ3PorJnSO:-O7_5PUm1nDIRlGiHm03:b-jjawnn) ([raw file](https://github.com/sillsdev/web-xforge/blob/9e99208a222f790c56364693e7df067665f7d3b6/src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/note-dialog/note-dialog.component.html#L76)):*
<details><summary><i>Previously, Nateowami (Nathaniel Paulus) wrote…</i></summary><blockquote>

I don't think this is actually needed.
</blockquote></details>

This keeps the dialog action buttons aligned to the end. If you remove it, the save and cancel buttons become left aligned.
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/translate/training-progress/training-progress.component.html` line 11 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/2729#-O7UUEWZDy8mB81yN5vB:-O7_5ieH1gkTm5hxg1jz:bfx04dz) ([raw file](https://github.com/sillsdev/web-xforge/blob/9e99208a222f790c56364693e7df067665f7d3b6/src/SIL.XForge.Scripture/ClientApp/src/app/translate/training-progress/training-progress.component.html#L11)):*
<details><summary><i>Previously, Nateowami (Nathaniel Paulus) wrote…</i></summary><blockquote>

What is this?
</blockquote></details>

Thanks for catching that. Removed.
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/translate/training-progress/training-progress.component.scss` line 20 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/2729#-O7UvNNV8XRqEdKmQt3z:-O7_6Lbs1RjP3rPnubjB:b-896fix) ([raw file](https://github.com/sillsdev/web-xforge/blob/9e99208a222f790c56364693e7df067665f7d3b6/src/SIL.XForge.Scripture/ClientApp/src/app/translate/training-progress/training-progress.component.scss#L20)):*
<details><summary><i>Previously, Nateowami (Nathaniel Paulus) wrote…</i></summary><blockquote>

The entire purpose of the `place-content` property is to be able to specify `align-content` and `justify-content` at the same time. Since this is only specifying one, it would be clearer to use the actual property name (`justify-content: space-between`). (Same later in the file)
</blockquote></details>

Done.
___
*[`src/SIL.XForge.Scripture/ClientApp/src/xforge-common/system-administration/system-administration.component.html` line 1 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/2729#-O7UP9vJC7MBv0I-f8Oq:-O7_7-P97mBoJ4dbBNlf:bss4a2b) ([raw file](https://github.com/sillsdev/web-xforge/blob/9e99208a222f790c56364693e7df067665f7d3b6/src/SIL.XForge.Scripture/ClientApp/src/xforge-common/system-administration/system-administration.component.html#L1)):*
<details><summary><i>Previously, Nateowami (Nathaniel Paulus) wrote…</i></summary><blockquote>

I don't think the`flex-start` class is doing anything.
</blockquote></details>

Removed.

**Review by Nateowami — COMMENTED** [review]
> Reviewed 4 of 10 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/2729)* status: 15 of 22 files reviewed, 5 unresolved discussions (waiting on @kylebuss)

**Review by Nateowami — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/2729)* status: 15 of 22 files reviewed, 2 unresolved discussions (waiting on @kylebuss and @RaymondLuong3)

___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.scss` line 72 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/2729#-O7V18CD7G2ncT_e5n5H:-O7_NY1GEwrJn8HIvYoL:ba3cexy) ([raw file](https://github.com/sillsdev/web-xforge/blob/9e99208a222f790c56364693e7df067665f7d3b6/src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.scss#L72)):*
<details><summary><i>Previously, RaymondLuong3 (Raymond Luong) wrote…</i></summary><blockquote>

It is needed to get everything to work when there are other viewers on the page.

</blockquote></details>

Ah, I see. I wasn't able to get to the situation where another avatar is shown.
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/note-dialog/note-dialog.component.html` line 76 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/2729#-O7Ub2wL0tBQ3PorJnSO:-O7_OKGJ0Vn4f8lHXhx5:b-upqxcg) ([raw file](https://github.com/sillsdev/web-xforge/blob/9e99208a222f790c56364693e7df067665f7d3b6/src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/note-dialog/note-dialog.component.html#L76)):*
<details><summary><i>Previously, RaymondLuong3 (Raymond Luong) wrote…</i></summary><blockquote>

This keeps the dialog action buttons aligned to the end. If you remove it, the save and cancel buttons become left aligned.
</blockquote></details>

Ah, I see. I removed it using dev tools and it still worked, but apparently Material adds some classes when it sees the attribute that results in it staying aligned right, which made me think it wasn't needed.

**Review by kylebuss — COMMENTED** [review]
Great job on this! Just a couple of small things I noticed.

> Reviewed 1 of 21 files at r1, 6 of 10 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/2729#-:-O7_aSO59p3q2LaDLHOH:bgu4fhe)* status: all files reviewed, 4 unresolved discussions (waiting on @RaymondLuong3)

___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/shared/share/share-control.component.scss` line 51 at r2](https://reviewable.io/reviews/sillsdev/web-xforge/2729#-O7_VCD6DkF5uLh2XLxc:-O7_VCD6DkF5uLh2XLxd:b-fa8h9m) ([raw file](https://github.com/sillsdev/web-xforge/blob/24c85d01bc5ba3ff5744891829627b4464f82852/src/SIL.XForge.Scripture/ClientApp/src/app/shared/share/share-control.component.scss#L51)):*
> ```SCSS
> }
> 
> ::ng-deep .invitation-role-panel .mat-mdc-option {
> ```

nit I noticed this, @Nateowami will this have a similar issue that you mentioned with `::ng-deep` being first? (I'm not very familiar with it).

Not sure if you want it handled with this PR but the following component.scss files have the `::ng-deep .another-class` order:

app, import-questions-dialog, navigation, settings, book-chapter-chooser, info, share-control, bibilical-terms, history-chooser, multi-viewer, editor-tab-add-resource-dialog.

Also found font-size, checking-overview, book-chapter-chooser, and tab-group use `::ng-deep {}` with no additional classes.



_Code quote:_
```SCSS
::ng-deep .invitation-role-panel .mat-mdc-option
```
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.html` line 160 at r2](https://reviewable.io/reviews/sillsdev/web-xforge/2729#-O7_ZlG18y8ADw-iwe0S:-O7_ZlG18y8ADw-iwe0T:b3jnrjv) ([raw file](https://github.com/sillsdev/web-xforge/blob/24c85d01bc5ba3ff5744891829627b4464f82852/src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.html#L160)):*
> ```HTML
>                   }
>                   <div class="text-container" [dir]="isTargetRightToLeft ? 'rtl' : 'ltr'">
>                     <app-text
> ```

Not sure if this is a font issue or quill issue but I did notice the editor spacing when a verse wraps in the editor can end up squished. It doesn't seem to be every project/font but it happened for me with the DRB project's font.

**Review by Nateowami — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/2729)* status: all files reviewed, 3 unresolved discussions (waiting on @kylebuss and @RaymondLuong3)

___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/shared/share/share-control.component.scss` line 51 at r2](https://reviewable.io/reviews/sillsdev/web-xforge/2729#-O7_VCD6DkF5uLh2XLxc:-O7_c2AB-LvpOyvquNFR:bk3yuw4) ([raw file](https://github.com/sillsdev/web-xforge/blob/24c85d01bc5ba3ff5744891829627b4464f82852/src/SIL.XForge.Scripture/ClientApp/src/app/shared/share/share-control.component.scss#L51)):*
<details><summary><i>Previously, kylebuss (Kyle Buss) wrote…</i></summary><blockquote>

nit I noticed this, @Nateowami will this have a similar issue that you mentioned with `::ng-deep` being first? (I'm not very familiar with it).

Not sure if you want it handled with this PR but the following component.scss files have the `::ng-deep .another-class` order:

app, import-questions-dialog, navigation, settings, book-chapter-chooser, info, share-control, bibilical-terms, history-chooser, multi-viewer, editor-tab-add-resource-dialog.

Also found font-size, checking-overview, book-chapter-chooser, and tab-group use `::ng-deep {}` with no additional classes.
</blockquote></details>

@kylebuss 

Yes, the same issue is in play here, but:
1. It's not related to this PR
2. Changing it here isn't an option because we're targeting an element in an overlay.

**Review by RaymondLuong3 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/2729)* status: all files reviewed, 1 unresolved discussion (waiting on @kylebuss)

___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.html` line 160 at r2](https://reviewable.io/reviews/sillsdev/web-xforge/2729#-O7_ZlG18y8ADw-iwe0S:-O7ePKUR9hO-arYKULFk:b-aquzzf) ([raw file](https://github.com/sillsdev/web-xforge/blob/24c85d01bc5ba3ff5744891829627b4464f82852/src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.html#L160)):*
<details><summary><i>Previously, kylebuss (Kyle Buss) wrote…</i></summary><blockquote>

Not sure if this is a font issue or quill issue but I did notice the editor spacing when a verse wraps in the editor can end up squished. It doesn't seem to be every project/font but it happened for me with the DRB project's font.

</blockquote></details>

What do you mean by squished? It does look like the spacing is tight for the verse that wraps, but I don't think it is related to converting the flex layout.

**Comment by Nateowami** [comment]
@RaymondLuong3 The button is overlapping the scrollbar. I'm not sure whether it has anything to do with this PR.

**Comment by kylebuss** [comment]
*[`src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.html` line 160 at r2](https://reviewable.io/reviews/sillsdev/web-xforge/2729#-O7_ZlG18y8ADw-iwe0S:-O7eahr58uMVfhU9Fawh:b-hv81hs) ([raw file](https://github.com/sillsdev/web-xforge/blob/24c85d01bc5ba3ff5744891829627b4464f82852/src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.html#L160)):*
<details><summary><i>Previously, RaymondLuong3 (Raymond Luong) wrote…</i></summary><blockquote>

What do you mean by squished? It does look like the spacing is tight for the verse that wraps, but I don't think it is related to converting the flex layout.
</blockquote></details>

You're right, it's not related to the changes made in this PR.

**Review by Nateowami — COMMENTED** [review]
I have reviewed most of the files. The checking overview page has broken the text overflow for long questions. How do you get to the multiviewer component? 

> Reviewed 4 of 10 files at r2.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/2729#-:-O7oiOmO3ajp3VkdEA5W:b360kpg)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @kylebuss)

**Comment by kylebuss** [comment]
For the multiviewer component, it is only showing up for me if I am logged in with two users and one is a non-PT user (share link worked for me).

**Review by kylebuss — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/2729#-:-O83J4KX09NnDhDQt_52:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @RaymondLuong3)

**Comment by RaymondLuong3** [comment]
I can see the text overflow change. Instead of elipses when the question is long, it just cuts off the question. I did some experimenting to get it back, but I was unsuccessful

**Pull request merged**
