### PR TITLE
SF-2013 Convert error dialog to Material

### PR DESCRIPTION
**Pull request by siltomato**
This change is [Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1851)

### CODE REVIEW

**Review by Nateowami — CHANGES_REQUESTED** [review]
> Reviewed 12 of 24 files at r1.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1851)* status: 12 of 24 files reviewed, 1 unresolved discussion (waiting on @siltomato)

___
*[`src/SIL.XForge.Scripture/ClientApp/.storybook/preview-head.html` line 7 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/1851#-NW3HV1D0WaVU85tn55H:-NW3HV1D0WaVU85tn55I:bwn9fyn) ([raw file](https://github.com/sillsdev/web-xforge/blob/247b8912389e6762898c3fa0b2920bc81b98c79d/src/SIL.XForge.Scripture/ClientApp/.storybook/preview-head.html#L7)):*
> ```HTML
>   // Allows global font effects from mdc typography
>   setTimeout(() => {
>     document.body.classList.add("mdc-typography");
> ```

As far as I can tell, this isn't having any effect at all. The class doesn't even get added.

Have you looked at how the `I18nStoryModule` sets the `dir` attribute on the body element, by setting decorators in `preview.ts`? I'm not sure it's the greatest example of how to do something like this, but it at least works.

**Review by siltomato — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1851)* status: 7 of 24 files reviewed, 1 unresolved discussion (waiting on @Nateowami)

___
*[`src/SIL.XForge.Scripture/ClientApp/.storybook/preview-head.html` line 7 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/1851#-NW3HV1D0WaVU85tn55H:-NWES-WLD3_4SEkq3Oy9:b-xji12f) ([raw file](https://github.com/sillsdev/web-xforge/blob/247b8912389e6762898c3fa0b2920bc81b98c79d/src/SIL.XForge.Scripture/ClientApp/.storybook/preview-head.html#L7)):*
<details><summary><i>Previously, Nateowami (Nathaniel Paulus) wrote…</i></summary><blockquote>

As far as I can tell, this isn't having any effect at all. The class doesn't even get added.

Have you looked at how the `I18nStoryModule` sets the `dir` attribute on the body element, by setting decorators in `preview.ts`? I'm not sure it's the greatest example of how to do something like this, but it at least works.
</blockquote></details>

Done in SF-2010.

**Review by Nateowami — APPROVED** [review]
:lgtm:

> Reviewed 2 of 24 files at r1, 15 of 15 files at r2.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1851#-:-NWI7J5s7iZ0QeW4Ou8f:bnfp4nl)* status: all files reviewed (commit messages unreviewed), all discussions resolved (waiting on @siltomato)

**Review by siltomato — COMMENTED** [review]
Changed `ExceptionHandlingService` to use `DialogService` to launch the error dialog.  This will cause it to pick up the correct i18n direction.

> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1851#-:-NWkStRV0ApcpIzi0cWc:b6gjkzb)* status: 11 of 24 files reviewed, 1 unresolved discussion (waiting on @github-code-scanning[bot] and @Nateowami)

___
*[`src/SIL.XForge.Scripture/ClientApp/src/xforge-common/exception-handling-service.spec.ts` line 4 at r3](https://reviewable.io/reviews/sillsdev/web-xforge/1851#gh-1211123054:-NWkS3jCBLne7OlKWEQ_:b-896fix) ([raw file](https://github.com/sillsdev/web-xforge/blob/6bdc4bfab2fc0372fcf761552f131c0050c0ab38/src/SIL.XForge.Scripture/ClientApp/src/xforge-common/exception-handling-service.spec.ts#L4)):*
<details><summary><i>Previously, github-code-scanning[bot] wrote…</i></summary><blockquote>

## Unused variable, import, function or class

Unused import MatDialog.

[Show more details](https://github.com/sillsdev/web-xforge/security/code-scanning/531)
</blockquote></details>

Done.

**Review by Nateowami — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1851)* status: all files reviewed, 1 unresolved discussion (waiting on @siltomato)

___
*[`src/SIL.XForge.Scripture/ClientApp/src/xforge-common/error-dialog/error-dialog.component.html` line 11 at r4](https://reviewable.io/reviews/sillsdev/web-xforge/1851#-NWnUtrf2rkqpUF9tAFC:-NWnUtrf2rkqpUF9tAFD:b-i9xpvd) ([raw file](https://github.com/sillsdev/web-xforge/blob/9751bf264edb5298535c83562238b6b746a4ed55/src/SIL.XForge.Scripture/ClientApp/src/xforge-common/error-dialog/error-dialog.component.html#L11)):*
> ```HTML
>     <ng-container *ngIf="data.stack">
>       <a (click)="this.showDetails = !this.showDetails">{{ showDetails ? t("hide_details") : t("show_details") }}</a>
>       <pre *ngIf="showDetails">{{ data.stack }}</pre>
> ```

I think adding `dir="ltr"` on this would make sense, so the stack trace isn't right-aligned when the UI is RTL.

Very non-critical though, and I don't want to hold up this change.

**Review by siltomato — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1851)* status: all files reviewed, 1 unresolved discussion (waiting on @siltomato)

___
*[`src/SIL.XForge.Scripture/ClientApp/src/xforge-common/error-dialog/error-dialog.component.html` line 11 at r4](https://reviewable.io/reviews/sillsdev/web-xforge/1851#-NWnUtrf2rkqpUF9tAFC:-NWnVUHjCNqEqX0awXiB:bhy9ot6) ([raw file](https://github.com/sillsdev/web-xforge/blob/9751bf264edb5298535c83562238b6b746a4ed55/src/SIL.XForge.Scripture/ClientApp/src/xforge-common/error-dialog/error-dialog.component.html#L11)):*
<details><summary><i>Previously, Nateowami (Nathaniel Paulus) wrote…</i></summary><blockquote>

I think adding `dir="ltr"` on this would make sense, so the stack trace isn't right-aligned when the UI is RTL.

Very non-critical though, and I don't want to hold up this change.
</blockquote></details>

Will do.

**Review by Nateowami — APPROVED** [review]
> Reviewed 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1851)* status: all files reviewed, 1 unresolved discussion (waiting on @siltomato)

**Pull request merged**
