### PR TITLE
SF-2397 Allow rebuilding when Serval data is missing from SF or Serval

### PR DESCRIPTION
**Pull request by pmachapman**
This Pull Request improves the stability of Scripture Forge for the two following scenarios:

 * When the project's translation engines are deleted from Serval
 * When the `ServalData` property is removed from `sf_project_secrets`

When these scenarios occur, the user can rebuild the SMT or NMT translation engines, and recover from the scenario.

***Note:** Testing should be performed by a developer, as it requires modification of the Mongo database.*

- - -
This change is [Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/2229)

### CODE REVIEW

**Review by pmachapman — COMMENTED** [review]
> Dismissed @github-advanced-security[bot] from a discussion.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/2229)* status: 0 of 8 files reviewed, all discussions resolved (waiting on @github-advanced-security[bot])

**Review by RaymondLuong3 — CHANGES_REQUESTED** [review]
I was able to follow the steps in the acceptance tests, and they all worked as expected except for the final step to generate a back translation draft. It failed and I captured the following error message in the terminal. It looks erroneous, but thought I would let you have a look.


> Reviewed 4 of 8 files at r1, 4 of 4 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/2229#-:-NlV7ol-8i178wskmnFh:b38eb4p)* status: all files reviewed, 5 unresolved discussions (waiting on @pmachapman)

___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/machine-api/remote-translation-engine.ts` line 111 at r2](https://reviewable.io/reviews/sillsdev/web-xforge/2229#-NlUtREJDjSXfkDjC2pj:-NlUtREJDjSXfkDjC2pk:b-llz64a) ([raw file](https://github.com/sillsdev/web-xforge/blob/4cb4a2b501453a535d73701ee731d0538fdc4535/src/SIL.XForge.Scripture/ClientApp/src/app/machine-api/remote-translation-engine.ts#L111)):*
> ```XML
>         })
>       )
>       .toPromise();
> ```

FYI, Nathaniel has a PR open to upgrade to Rxjs 7 where `toPromise()` is replaced with the Rxjs operator `lastValueFrom()`. When you rebase, you will probably need to change this.



_Code quote:_
```XML
      .toPromise();
```
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/translate/translate-overview/translate-overview.component.ts` line 259 at r2](https://reviewable.io/reviews/sillsdev/web-xforge/2229#-NlUvJD47F8JVitAXcfS:-NlUvJD47F8JVitAXcfT:b-gq5i8v) ([raw file](https://github.com/sillsdev/web-xforge/blob/4cb4a2b501453a535d73701ee731d0538fdc4535/src/SIL.XForge.Scripture/ClientApp/src/app/translate/translate-overview/translate-overview.component.ts#L259)):*
> ```XML
>     } else if (this.trainingSub != null) {
>       this.trainingSub.unsubscribe();
>       this.trainingSub = undefined;
> ```

instead of an else if block, this could just be `this.trainingSub?.unsubscribe()`
___
*[`src/SIL.XForge.Scripture/Services/MachineApiService.cs` line 610 at r2](https://reviewable.io/reviews/sillsdev/web-xforge/2229#-NlUw6ujENv4wY6WUZCz:-NlUw6uk8g_dYi9h08DB:b-fcvup6) ([raw file](https://github.com/sillsdev/web-xforge/blob/4cb4a2b501453a535d73701ee731d0538fdc4535/src/SIL.XForge.Scripture/Services/MachineApiService.cs#L610)):*
> ```Smalltalk
>                     // Clear the existing translation engine id
>                     if (!string.IsNullOrWhiteSpace(translationEngineId))
>                     {
> ```

Why is it important to unset the TranslationEngineId. I would think that when you call `StartBuildAsync` the new ID will just overwrite what is in the project secrets.
___
*[`src/SIL.XForge.Scripture/Services/MachineProjectService.cs` line 121 at r2](https://reviewable.io/reviews/sillsdev/web-xforge/2229#-NlUwoAXCNKrFGJNbQ1j:-NlUwoAY1WowBUmyi6lw:b-9whgfm) ([raw file](https://github.com/sillsdev/web-xforge/blob/4cb4a2b501453a535d73701ee731d0538fdc4535/src/SIL.XForge.Scripture/Services/MachineProjectService.cs#L121)):*
> ```Smalltalk
>         )
>         {
>             // We do not need the returned translation engine id
> ```

This comment does not seem necessary anymore.



_Code quote:_
```Smalltalk
       // We do not need the returned translation engine id
```
___
*[`test/SIL.XForge.Scripture.Tests/Services/MachineApiServiceTests.cs` line 1728 at r2](https://reviewable.io/reviews/sillsdev/web-xforge/2229#-NlV-blY7b3C0sEt-m_V:-NlV-blY7b3C0sEt-m_W:b-2w10mt) ([raw file](https://github.com/sillsdev/web-xforge/blob/4cb4a2b501453a535d73701ee731d0538fdc4535/test/SIL.XForge.Scripture.Tests/Services/MachineApiServiceTests.cs#L1728)):*
> ```Smalltalk
> 
>     [Test]
>     public async Task StartBuildAsync_ServalCreatesRemovedTranslationEngine()
> ```

I'm not sure I understand. How was the translation engine removed? Did the translation engine exist, but it was removed somehow? Oh, that must be when you check the Translation engine exists and it returns false. Can you leave a comment with how you set-up this behaviour?



_Code quote:_
```Smalltalk
 public async Task StartBuildAsync_ServalCreatesRemovedTranslationEngine()
```

**Review by pmachapman — COMMENTED** [review]
@RaymondLuong3 Thank you for catching that bug. I have written a fix for it and updated the PR - the old corpora were stuck in the project secrets. You will need to remove and reconnect to the project on your localhost before retesting or running any builds with this project.

> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/2229#-:-Nl_mCYmE7tiLFKixY5S:b-mzzvzc)* status: all files reviewed, 4 unresolved discussions (waiting on @RaymondLuong3)

___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/machine-api/remote-translation-engine.ts` line 111 at r2](https://reviewable.io/reviews/sillsdev/web-xforge/2229#-NlUtREJDjSXfkDjC2pj:-NlZutJv-v8qKoVXuU-Y:b-9755fn) ([raw file](https://github.com/sillsdev/web-xforge/blob/4cb4a2b501453a535d73701ee731d0538fdc4535/src/SIL.XForge.Scripture/ClientApp/src/app/machine-api/remote-translation-engine.ts#L111)):*
<details><summary><i>Previously, RaymondLuong3 (Raymond Luong) wrote…</i></summary><blockquote>

FYI, Nathaniel has a PR open to upgrade to Rxjs 7 where `toPromise()` is replaced with the Rxjs operator `lastValueFrom()`. When you rebase, you will probably need to change this.
</blockquote></details>

Thank you!
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/translate/translate-overview/translate-overview.component.ts` line 259 at r2](https://reviewable.io/reviews/sillsdev/web-xforge/2229#-NlUvJD47F8JVitAXcfS:-NlZv1x78L0jAFJbihrV:boyexb3) ([raw file](https://github.com/sillsdev/web-xforge/blob/4cb4a2b501453a535d73701ee731d0538fdc4535/src/SIL.XForge.Scripture/ClientApp/src/app/translate/translate-overview/translate-overview.component.ts#L259)):*
<details><summary><i>Previously, RaymondLuong3 (Raymond Luong) wrote…</i></summary><blockquote>

instead of an else if block, this could just be `this.trainingSub?.unsubscribe()`
</blockquote></details>

Done. Thanks!
___
*[`src/SIL.XForge.Scripture/Services/MachineApiService.cs` line 610 at r2](https://reviewable.io/reviews/sillsdev/web-xforge/2229#-NlUw6ujENv4wY6WUZCz:-NlZvLzb8L57WdyqYTYM:bbqrwug) ([raw file](https://github.com/sillsdev/web-xforge/blob/4cb4a2b501453a535d73701ee731d0538fdc4535/src/SIL.XForge.Scripture/Services/MachineApiService.cs#L610)):*
<details><summary><i>Previously, RaymondLuong3 (Raymond Luong) wrote…</i></summary><blockquote>

Why is it important to unset the TranslationEngineId. I would think that when you call `StartBuildAsync` the new ID will just overwrite what is in the project secrets.
</blockquote></details>

`_machineProjectService.AddProjectAsync()` requires it to be not set to create the new translation engine. I have updated the comment to reflect that.
___
*[`src/SIL.XForge.Scripture/Services/MachineProjectService.cs` line 121 at r2](https://reviewable.io/reviews/sillsdev/web-xforge/2229#-NlUwoAXCNKrFGJNbQ1j:-NlZwlXXA_IxvHYQmMoc:b-896fix) ([raw file](https://github.com/sillsdev/web-xforge/blob/4cb4a2b501453a535d73701ee731d0538fdc4535/src/SIL.XForge.Scripture/Services/MachineProjectService.cs#L121)):*
<details><summary><i>Previously, RaymondLuong3 (Raymond Luong) wrote…</i></summary><blockquote>

This comment does not seem necessary anymore.
</blockquote></details>

Done.
___
*[`test/SIL.XForge.Scripture.Tests/Services/MachineApiServiceTests.cs` line 1728 at r2](https://reviewable.io/reviews/sillsdev/web-xforge/2229#-NlV-blY7b3C0sEt-m_V:-NlZwumH8qrbQ70Snnag:bercjqu) ([raw file](https://github.com/sillsdev/web-xforge/blob/4cb4a2b501453a535d73701ee731d0538fdc4535/test/SIL.XForge.Scripture.Tests/Services/MachineApiServiceTests.cs#L1728)):*
<details><summary><i>Previously, RaymondLuong3 (Raymond Luong) wrote…</i></summary><blockquote>

I'm not sure I understand. How was the translation engine removed? Did the translation engine exist, but it was removed somehow? Oh, that must be when you check the Translation engine exists and it returns false. Can you leave a comment with how you set-up this behaviour?
</blockquote></details>

I have renamed it, and added a comment to explain. Thanks!

**Review by RaymondLuong3 — APPROVED** [review]
Thanks, I retested it and it is working as expected. I'm glad you were able to identify the problem with just the minimal info I posted. I'll get this merged in.

> Reviewed 4 of 4 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/2229#-:-Nld_gpA1spCqHq37419:b-w9pjl0)* status: all files reviewed, 1 unresolved discussion (waiting on @pmachapman)

___
*[`src/SIL.XForge.Scripture/Services/MachineApiService.cs` line 610 at r2](https://reviewable.io/reviews/sillsdev/web-xforge/2229#-NlUw6ujENv4wY6WUZCz:-NldVJq97Uw8FW_LKTmz:bug5y6v) ([raw file](https://github.com/sillsdev/web-xforge/blob/4cb4a2b501453a535d73701ee731d0538fdc4535/src/SIL.XForge.Scripture/Services/MachineApiService.cs#L610)):*
<details><summary><i>Previously, pmachapman (Peter Chapman) wrote…</i></summary><blockquote>

`_machineProjectService.AddProjectAsync()` requires it to be not set to create the new translation engine. I have updated the comment to reflect that.
</blockquote></details>

Ok, thanks for the comment.

**Pull request merged**
