### PR TITLE
Re-add HasTransceleratorQuestions API endpoint

### PR DESCRIPTION
**Pull request by Nateowami**
This was prematurely removed in #1182. We don't need it anymore, but existing clients call it, so we shouldn't remove it until #1182 is live on nearly all clients.

---
This change is [Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1199)

### CODE REVIEW

**Review by irahopkinson — APPROVED** [review]
Looks good. Just one question but not blocking.

> Reviewed 6 of 6 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1199#-:-MpiYrHFCN4P7MUC2Fy3:bgb4ev5)* status: all files reviewed, 1 unresolved discussion (waiting on @Nateowami)

___
*[src/SIL.XForge.Scripture/Controllers/SFProjectsRpcController.cs, line 365 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/1199#-MpiYQvC3J_ItXYLCajz:-MpiYQvC3J_ItXYLCak-:b-nku91j) ([raw file](https://github.com/sillsdev/web-xforge/blob/db5c0a3339d9a85a92675fe184927f65b65ae0a7/src/SIL.XForge.Scripture/Controllers/SFProjectsRpcController.cs#L365)):*
> ```
> /// Deprecated;
> ```
I would think there is a proper way to mark a method as deprecated in C# such that it displays correctly in IDEs.

**Review by Nateowami — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1199)* status: 3 of 6 files reviewed, 1 unresolved discussion (waiting on @irahopkinson)

___
*[src/SIL.XForge.Scripture/Controllers/SFProjectsRpcController.cs, line 365 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/1199#-MpiYQvC3J_ItXYLCajz:-MpivC2t17HE51XmQKpt:b-fnu5f8) ([raw file](https://github.com/sillsdev/web-xforge/blob/db5c0a3339d9a85a92675fe184927f65b65ae0a7/src/SIL.XForge.Scripture/Controllers/SFProjectsRpcController.cs#L365)):*
<details><summary><i>Previously, irahopkinson (Ira Hopkinson) wrote…</i></summary><blockquote>

> ```
> /// Deprecated;
> ```
I would think there is a proper way to mark a method as deprecated in C# such that it displays correctly in IDEs.
</blockquote></details>

I made some changes but I really don't know if this is for the better or not.

Marking a method as obsolete causes warnings everywhere it's called, which is the point of marking it as obsolete. Marking this method obsolete has no such effect, since we don't call it anywhere in our C# code. So I marked the other methods we plan to remove as obsolete and just left a comment on this method.

And now I see LGTM is complaining about calls to obsolete methods.

What do you think?

**Review by irahopkinson — COMMENTED** [review]
> Reviewed 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1199)* status: all files reviewed, 1 unresolved discussion (waiting on @Nateowami)

___
*[src/SIL.XForge.Scripture/Controllers/SFProjectsRpcController.cs, line 365 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/1199#-MpiYQvC3J_ItXYLCajz:-Mpj-NR44fIwqGC5N146:b5llkny) ([raw file](https://github.com/sillsdev/web-xforge/blob/db5c0a3339d9a85a92675fe184927f65b65ae0a7/src/SIL.XForge.Scripture/Controllers/SFProjectsRpcController.cs#L365)):*
<details><summary><i>Previously, Nateowami (Nathaniel Paulus) wrote…</i></summary><blockquote>

I made some changes but I really don't know if this is for the better or not.

Marking a method as obsolete causes warnings everywhere it's called, which is the point of marking it as obsolete. Marking this method obsolete has no such effect, since we don't call it anywhere in our C# code. So I marked the other methods we plan to remove as obsolete and just left a comment on this method.

And now I see LGTM is complaining about calls to obsolete methods.

What do you think?
</blockquote></details>

The Obsolete looks right to me, but I don't really want to ignore the lgtm-com warnings. We could enclose the two calls with
```
#pragma warning disable 0612, 0618
            ...
#pragma warning restore 0612, 0618
```

**Review by irahopkinson — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1199)* status: all files reviewed, 1 unresolved discussion (waiting on @Nateowami)

___
*[src/SIL.XForge.Scripture/Controllers/SFProjectsRpcController.cs, line 365 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/1199#-MpiYQvC3J_ItXYLCajz:-Mpj-ssg2K32dh32Scm-:be902qc) ([raw file](https://github.com/sillsdev/web-xforge/blob/db5c0a3339d9a85a92675fe184927f65b65ae0a7/src/SIL.XForge.Scripture/Controllers/SFProjectsRpcController.cs#L365)):*
<details><summary><i>Previously, irahopkinson (Ira Hopkinson) wrote…</i></summary><blockquote>

The Obsolete looks right to me, but I don't really want to ignore the lgtm-com warnings. We could enclose the two calls with
```
#pragma warning disable 0612, 0618
            ...
#pragma warning restore 0612, 0618
```
</blockquote></details>

Opps, don't use the leading `0`, so this is actually correct:
```
#pragma warning disable 612, 618
            ...
#pragma warning restore 612, 618
```

**Review by irahopkinson — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1199)* status: 5 of 6 files reviewed, 1 unresolved discussion (waiting on @irahopkinson and @Nateowami)

___
*[src/SIL.XForge.Scripture/Controllers/SFProjectsRpcController.cs, line 365 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/1199#-MpiYQvC3J_ItXYLCajz:-Mpj3Gjt6q29Upt9wcA8:bw2eh5t) ([raw file](https://github.com/sillsdev/web-xforge/blob/db5c0a3339d9a85a92675fe184927f65b65ae0a7/src/SIL.XForge.Scripture/Controllers/SFProjectsRpcController.cs#L365)):*
<details><summary><i>Previously, irahopkinson (Ira Hopkinson) wrote…</i></summary><blockquote>

Opps, don't use the leading `0`, so this is actually correct:
```
#pragma warning disable 612, 618
            ...
#pragma warning restore 612, 618
```
</blockquote></details>

Actually I just obsoleted the API method as suggested by VS Code. Hopefully lgtm-com is happy with that.

**Review by irahopkinson — APPROVED** [review]
> Reviewed 1 of 1 files at r3, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1199)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @Nateowami)

**Pull request merged**
