### PR TITLE
SF-1880 Prompt before deleting comment

### PR DESCRIPTION
**Pull request by Nateowami**
This change is [Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1715)

### CODE REVIEW

**Review by nigel-wells — APPROVED** [review]
Just one point that I'm not overly fussed about - your call.

> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1715#-:-NOfb2oi682H4eeQBFPO:b-5ssqdi)* status: all files reviewed, 1 unresolved discussion (waiting on @Nateowami)

___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-answers/checking-comments/checking-comments.component.html` line 27 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/1715#-NOfadR7-wawZ33sB7Qa:-NOfadR7-wawZ33sB7Qb:b-as2ycl) ([raw file](https://github.com/sillsdev/web-xforge/blob/5d4d8aa2ca71c4bdc0f5d24cd0828149105662cc/src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-answers/checking-comments/checking-comments.component.html#L27)):*
> ```HTML
>           mdc-button
>           type="button"
>           (click)="deleteCommentClicked(comment)"
> ```

Do you think we need to rename this to include `Clicked`? I think it is fine without and then it leave the method available to be called outside of `Clicked` event without feeling weird about it.

**Review by Nateowami — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1715)* status: all files reviewed, 1 unresolved discussion (waiting on @nigel-wells)

___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-answers/checking-comments/checking-comments.component.html` line 27 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/1715#-NOfadR7-wawZ33sB7Qa:-NOjgVMh1QA_57FyLnm1:b-3cnf2v) ([raw file](https://github.com/sillsdev/web-xforge/blob/5d4d8aa2ca71c4bdc0f5d24cd0828149105662cc/src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-answers/checking-comments/checking-comments.component.html#L27)):*
<details><summary><i>Previously, nigel-wells (Nigel Wells) wrote…</i></summary><blockquote>

Do you think we need to rename this to include `Clicked`? I think it is fine without and then it leave the method available to be called outside of `Clicked` event without feeling weird about it.
</blockquote></details>

I don't like to have a method named `deleteComment()` that doesn't actually delete a comment (it prompts the user to ask if the comment should be deleted). If we wanted to call it elsewhere, not due to the user clicking the button, then I would question whether we want to show the prompt or not in that situation. We might want to refactor to have a method called `deleteComment()` and a method called `deleteCommentClicked()`, where `deleteCommentClicked()` is essentially:
``` ts
if (await this.dialogService.confirm(...)) this.deleteComment();
```
We have the same issue in a lot of other components (pretty much any time we want to confirm anything), so if there's a better convention for naming things I'm all for it.

**Review by nigel-wells — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1715)* status: all files reviewed, 1 unresolved discussion (waiting on @Nateowami)

___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-answers/checking-comments/checking-comments.component.html` line 27 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/1715#-NOfadR7-wawZ33sB7Qa:-NOkdEae3IWFtTEYyZ_6:b-mcu4wh) ([raw file](https://github.com/sillsdev/web-xforge/blob/5d4d8aa2ca71c4bdc0f5d24cd0828149105662cc/src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-answers/checking-comments/checking-comments.component.html#L27)):*
<details><summary><i>Previously, Nateowami (Nathaniel Paulus) wrote…</i></summary><blockquote>

I don't like to have a method named `deleteComment()` that doesn't actually delete a comment (it prompts the user to ask if the comment should be deleted). If we wanted to call it elsewhere, not due to the user clicking the button, then I would question whether we want to show the prompt or not in that situation. We might want to refactor to have a method called `deleteComment()` and a method called `deleteCommentClicked()`, where `deleteCommentClicked()` is essentially:
``` ts
if (await this.dialogService.confirm(...)) this.deleteComment();
```
We have the same issue in a lot of other components (pretty much any time we want to confirm anything), so if there's a better convention for naming things I'm all for it.
</blockquote></details>

I personally see `deleteComment` being fine and it just happens to contain a safe guard to the action of deleting. If anything else wanted to delete a comment it should also show any safe guards before deleting. I do see your point though. Perhaps the real `deleteComment` - the one that actually deletes the comment - should be a private method. We can then have one called `confirmDeleteComment`. This way templates can only call the public method requiring confirmation but we have the flexibility within the component to also directly delete the comment without confirmation.

I realize this is overkill for what you're doing and adding code for something that may or may not happen. Good discussion though :)

**Review by Nateowami — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1715)* status: all files reviewed, 1 unresolved discussion (waiting on @nigel-wells)

___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-answers/checking-comments/checking-comments.component.html` line 27 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/1715#-NOfadR7-wawZ33sB7Qa:-NOvhehKAKDtKGJuYeqE:b-xl59na) ([raw file](https://github.com/sillsdev/web-xforge/blob/5d4d8aa2ca71c4bdc0f5d24cd0828149105662cc/src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-answers/checking-comments/checking-comments.component.html#L27)):*
<details><summary><i>Previously, nigel-wells (Nigel Wells) wrote…</i></summary><blockquote>

I personally see `deleteComment` being fine and it just happens to contain a safe guard to the action of deleting. If anything else wanted to delete a comment it should also show any safe guards before deleting. I do see your point though. Perhaps the real `deleteComment` - the one that actually deletes the comment - should be a private method. We can then have one called `confirmDeleteComment`. This way templates can only call the public method requiring confirmation but we have the flexibility within the component to also directly delete the comment without confirmation.

I realize this is overkill for what you're doing and adding code for something that may or may not happen. Good discussion though :)
</blockquote></details>

I see what you mean. An example of why I think this could be confusing is something similar to the checking overview component. In that component I originally started writing something like:
``` ts
archiveQuestionsInBook(book: number) {
  if (userConfirms) {
    for (const chapter of book) {
      archiveQuestionsInChapter() // but this will open a confirmation for each chapter
    }
  }
}
```
However, I was also confirming if the user wanted to archive all the questions in the chapter, so that didn't work. I ended up just nesting a loop in a loop in the method for archiving all questions in a book.

I also ended up naming the methods not very well, because they had to be able to both archive and republish, but that's kind of beside the point.

**Pull request merged**
