### PR TITLE
SF-2589 Send/Receive USFM to Serval

### PR DESCRIPTION
**Pull request by pmachapman**
This PR adds:

 * Add backend endpoints to retrieve pre-translation drafts as a Delta or USFM
 * Add frontend interface with new endpoints
 * Remove Paratext zip feature flag and upgrade projects from using text to Paratext zip files

- - -
This change is [Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/2364)

### CODE REVIEW

**Review by nigel-wells — CHANGES_REQUESTED** [review]
Part way through this - looking pretty good so far.

> Reviewed 16 of 27 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/2364#-:-NtZFirW7XiUUHeaFGuw:b-jm6b8c)* status: 16 of 27 files reviewed, 2 unresolved discussions (waiting on @pmachapman)

___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-viewer/draft-viewer.component.scss` line 76 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/2364#-NtYq2-4A1v8q0t1tUHF:-NtYq2-58hJf_qyheERn:bcxe6gd) ([raw file](https://github.com/sillsdev/web-xforge/blob/e4e48a8dfd6993aaeb538cf862d3e016794fc403/src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-viewer/draft-viewer.component.scss#L76)):*
> ```SCSS
> 
>   // Show a small amount of padding below the notice
>   app-notice {
> ```

Probably best to target the `.legacy-draft-warning` class in case another notice is added to this component.
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor-draft/editor-draft.component.ts` line 43 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/2364#-NtZCfQO8GFhU12q1sVP:-NtZCfQO8GFhU12q1sVQ:b5gjm1g) ([raw file](https://github.com/sillsdev/web-xforge/blob/e4e48a8dfd6993aaeb538cf862d3e016794fc403/src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor-draft/editor-draft.component.ts#L43)):*
> ```XML
> 
>   inputChanged$ = new Subject<void>();
>   draftCheckState: 'draft-unknown' | 'draft-present' | 'draft-empty' | 'legacy-draft' = 'draft-unknown';
> ```

nit  am I being too picky to wonder why all the other states start with "draft" except for your new one.

**Review by pmachapman — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/2364)* status: 16 of 27 files reviewed, 1 unresolved discussion (waiting on @nigel-wells)

___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-viewer/draft-viewer.component.scss` line 76 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/2364#-NtYq2-4A1v8q0t1tUHF:-Ntlr9OD05vQW8NDUQMa:b-896fix) ([raw file](https://github.com/sillsdev/web-xforge/blob/e4e48a8dfd6993aaeb538cf862d3e016794fc403/src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-viewer/draft-viewer.component.scss#L76)):*
<details><summary><i>Previously, nigel-wells (Nigel Wells) wrote…</i></summary><blockquote>

Probably best to target the `.legacy-draft-warning` class in case another notice is added to this component.
</blockquote></details>

Done.
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor-draft/editor-draft.component.ts` line 43 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/2364#-NtZCfQO8GFhU12q1sVP:-NtlrOaIDonOumCF-jyI:bsk71y4) ([raw file](https://github.com/sillsdev/web-xforge/blob/e4e48a8dfd6993aaeb538cf862d3e016794fc403/src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor-draft/editor-draft.component.ts#L43)):*
<details><summary><i>Previously, nigel-wells (Nigel Wells) wrote…</i></summary><blockquote>

nit  am I being too picky to wonder why all the other states start with "draft" except for your new one.
</blockquote></details>

Done. It looked wrong when I did it last week, but this week it looks right - so you are not too picky! :-)

**Review by nigel-wells — CHANGES_REQUESTED** [review]
Looks great thanks Peter - just one real discussion point.

> Reviewed 10 of 27 files at r1, 5 of 5 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/2364#-:-NtnHSCG9waHhR2gLGdj:b-iuy1dk)* status: all files reviewed, 3 unresolved discussions (waiting on @pmachapman)

___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-viewer/draft-viewer.component.ts` line 48 at r2](https://reviewable.io/reviews/sillsdev/web-xforge/2364#-NtnFwqS4CwGNFgzgDeV:-NtnFwqS4CwGNFgzgDeW:bwawb8f) ([raw file](https://github.com/sillsdev/web-xforge/blob/9a91574c510533eb15f690b3c4a28f1b26b6ea25/src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-viewer/draft-viewer.component.ts#L48)):*
> ```XML
> 
>   isDraftApplied = false;
>   isLegacyDraft = false;
> ```

nit  Let's make this `isDraftLegacy` as well
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-viewer/draft-viewer.component.ts` line 58 at r2](https://reviewable.io/reviews/sillsdev/web-xforge/2364#-NtnGDS9BLwX1pH7C9vs:-NtnGDS9BLwX1pH7C9vt:b-i2hx0) ([raw file](https://github.com/sillsdev/web-xforge/blob/9a91574c510533eb15f690b3c4a28f1b26b6ea25/src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-viewer/draft-viewer.component.ts#L58)):*
> ```XML
>   bookHasSource = false;
> 
>   draftSubscription?: Subscription;
> ```

Can this be private?
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-viewer/draft-viewer.component.ts` line 229 at r2](https://reviewable.io/reviews/sillsdev/web-xforge/2364#-NtnGu4S-oI9UB-s_x0D:-NtnGu4S-oI9UB-s_x0E:b6owdcn) ([raw file](https://github.com/sillsdev/web-xforge/blob/9a91574c510533eb15f690b3c4a28f1b26b6ea25/src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-viewer/draft-viewer.component.ts#L229)):*
> ```XML
>           catchError(err => {
>             // If the corpus does not support USFM
>             if (err.status === 405) {
> ```

How often might a user hit the other `40x` codes - should we offer a nicer path to resolution with potentially translated strings rather than just throwing an error? I'm thinking if there is a state they are in but have the ability to get out of themselves if they understood the issue and had a clear way to resolve it - similar to what you've offered with the `405`
___
*[`test/SIL.XForge.Scripture.Tests/Services/MachineProjectServiceTests.cs` line 150 at r2](https://reviewable.io/reviews/sillsdev/web-xforge/2364#-NtnD97BBhr1ImEbsN9z:-NtnD97BBhr1ImEbsNA-:b-ju0m3l) ([raw file](https://github.com/sillsdev/web-xforge/blob/9a91574c510533eb15f690b3c4a28f1b26b6ea25/test/SIL.XForge.Scripture.Tests/Services/MachineProjectServiceTests.cs#L150)):*
> ```Smalltalk
> 
>     [Test]
>     public async Task BuildProjectAsync_DoesNotPassTrainOnIfAlternateTrainingSourceEnabledWithoutAlternateSourceWhenSendAllSegments()
> ```

Why not just rename this to "Taumatawhakatangihangakoauauotamateaturipukakapikimaungahoronukupokaiwhenuakitanatahu" and be done with it - both the same length!

**Review by nigel-wells — APPROVED** [review]
> Reviewed 6 of 6 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/2364)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @pmachapman)

___
*[`test/SIL.XForge.Scripture.Tests/Services/MachineProjectServiceTests.cs` line 150 at r2](https://reviewable.io/reviews/sillsdev/web-xforge/2364#-NtnD97BBhr1ImEbsN9z:-NtsFKXH7Y_F7vNE8HQt:b-k0wxbw) ([raw file](https://github.com/sillsdev/web-xforge/blob/9a91574c510533eb15f690b3c4a28f1b26b6ea25/test/SIL.XForge.Scripture.Tests/Services/MachineProjectServiceTests.cs#L150)):*
<details><summary><i>Previously, pmachapman (Peter Chapman) wrote…</i></summary><blockquote>

Yeah, I know. If you know better ways we can document what a test is doing. I am only aware of two ways to document tests like this - naming or codedoc comments. I fall on the side of names for the reasons discussed here: https://stackoverflow.com/questions/706354/writing-long-test-method-names-to-describe-tests-vs-using-in-code-documentation
</blockquote></details>

Yeah, I think having it in the method name is best for the same reasons. Can we break it up into chunks so each part is meaningful on it's own and it is easier to scan i.e. `BuildProjectAsync_DoesNotPassTrainOnIf_AlternateTrainingSourceEnabled_WithoutAlternateSource_WhenSendAllSegments()`
Doesn't need to hold up from getting the testers over it so I'll approve and move along.

**Comment by Nateowami** [comment]
@pmachapman I checked this out locally and ran a build to generate Ruth. It succeeded, but when I go to preview the draft, it doesn't load. Looking at the network tab, I see the request for `http://localhost:5000/machine-api/v3/translation/engines/project:66032c6cef14cbdf7d213956/actions/pretranslate/8_1/delta` is returning 404. Am I missing something?

**Comment by Nateowami** [comment]
Hang on. If I check out master, then the draft that was generated on this branch does show up. It's loaded from `http://localhost:5000/machine-api/v3/translation/engines/project:66032c6cef14cbdf7d213956/actions/pretranslate/8_1` (no `/delta` on the end)

**Comment by pmachapman** [comment]
@Nateowami Is the "Pre-translate headings and non-verse material" box ticked in Settings? USMF upload is not performed when that box is ticked for a project.

**Comment by Nateowami** [comment]
@pmachapman No, it's not. And even if it was, there ought to be a draft coming back anyway.

**Comment by Nateowami** [comment]
Working with Peter, I determined the change does work fine. My back end most likely didn't actually restart when I checked out the branch.

**Pull request merged**
