### PR TITLE
Clarify source of NullReferenceException

### PR DESCRIPTION
**Pull request by marksvc**
Such as from SF-1776.

- - -
This change is [Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1573)

### CODE REVIEW

**Review by RaymondLuong3 — COMMENTED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1573)* status: all files reviewed, 1 unresolved discussion (waiting on @marksvc)

___
*[`src/SIL.XForge.Scripture/Services/ParatextService.cs` line 895 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/1573#-NFoeFxXE79ocFF_B-P7:-NFoeFxXE79ocFF_B-P8:bn92w36) ([raw file](https://github.com/sillsdev/web-xforge/blob/d4f1853e8f36dccd6209a4784450362ffa6de997/src/SIL.XForge.Scripture/Services/ParatextService.cs#L895)):*
> ```Smalltalk
>                     if (remotePtProject.SourceUsers is null)
>                     {
>                         throw new InvalidDataException(
> ```

Is there a reason we need to throw an error here? Is it because if SourceUsers is null, then the project is not one that we can handle? Previously, no exceptions were thrown, and I imagine this would simply return an empty array of user mappings.



_Code quote:_
```Smalltalk
                    throw new InvalidDataException(
```

**Review by marksvc — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1573)* status: all files reviewed, 1 unresolved discussion (waiting on @RaymondLuong3)

___
*[`src/SIL.XForge.Scripture/Services/ParatextService.cs` line 895 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/1573#-NFoeFxXE79ocFF_B-P7:-NFoqNMmCCL6PqUxdyGS:b58j2ty) ([raw file](https://github.com/sillsdev/web-xforge/blob/d4f1853e8f36dccd6209a4784450362ffa6de997/src/SIL.XForge.Scripture/Services/ParatextService.cs#L895)):*
<details><summary><i>Previously, RaymondLuong3 (Raymond Luong) wrote…</i></summary><blockquote>

Is there a reason we need to throw an error here? Is it because if SourceUsers is null, then the project is not one that we can handle? Previously, no exceptions were thrown, and I imagine this would simply return an empty array of user mappings.
</blockquote></details>

If `remotePtProject.SourceUsers` or `remotePtProject.SourceUsers.Users` are null, then a few lines below with `remotePtProject.SourceUsers.Users.SingleOrDefault(`, there would be a NullReferenceException. 
As to whether we should have an exception at all in this situation, or return an empty list, I lean toward exception because
  - If either of those properties are null, it seems that we received some data that is broken somehow. (Unless it's correct or expected behaviour for that to happen, then I might think that we should handle it without throwing.)
  - When we call GetProjectRolesAsync(), if we somehow fail to actually query the PT role list, an exception more clearly passes that error back than a statement of no roles.

**Review by RaymondLuong3 — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1573)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @marksvc)

**Review by Nateowami — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1573)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @marksvc)

**Pull request merged**
