### PR TITLE
Angular 11

### PR DESCRIPTION
**Pull request by irahopkinson**
- ng update @angular/core@11 @angular/cli@11 --force
- ng update @angular/material --force
- manually update
  - @angular/flex-layout
  - @angular/pwa
  - @ngneat/transloco
- remove @ngneat/transloco-keys-manager (due to TS)

Configuration cleanup
- whitelist styles
- update realtime-server dependencies
- don't need legacy relativeLinkResolution
- also increase NG strictness
- also latest npm, bugsnag, ngx-avatar
- fix LGTM build & unit tests

To test this branch (and when you go back to the current `master`):
- Repo root `dotnet clean` - this removes .NET's cache of node packages
- RealtimeServer `npm i`
- ClientApp `npm i`

---
This change is [Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1071)

### CODE REVIEW

**Comment by marksvc** [comment]
:eyes:

**Review by marksvc — CHANGES_REQUESTED** [review]
Thanks for your work on this. 
I made use of the separated-out commits when reviewing; thank you. 

Both Nathaniel and I were not able to successfully update our modules using `npm i`. Or rather, we could run `npm i` successfully, but it doesn't update the modules. (!). 

I was able to fix mine by removing package-lock.json in ClientApp. Nathaniel was able to fix his by removing the directory node_modules. 

(Otherwise, after doing `npm i` in ClientApp and in RealtimeServer, I have errors when using ng:

```bash
$ ng serve
/home/vagrant/src/web-xforge/src/SIL.XForge.Scripture/ClientApp/node_modules/@angular/cli/utilities/color.js:22
const colors = ansiColors.create();
                          ^

TypeError: ansiColors.create is not a function
```
)

I wonder if there is something else you haven't committed, or that you need to re-generate with better info (like package-lock.json ?).

In my  RealtimeServer directory, npm  also claimed to succeed at npm i, but did not update its modules. I tried removing package-lock.json and doing npm i, which claims success, but did not work. For example, RealtimeServer/package.json says we should move from ts-jest ^26.4.4 to ^27.0.3. But my node_modules/ts-jest/package.json file still shows version 26.4.4. 

I'm still learning about npm and its package json files. But something does seem to be amiss.

I have (after successfully updating from ClientApp):

```bash
$ npm --version
7.18.1
```

> Reviewed 26 of 26 files at r1.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1071#-:-McysxiaD4n6QpfKr7Ct:bi78km)* status: all files reviewed, 4 unresolved discussions (waiting on @irahopkinson)

___
*[src/SIL.XForge.Scripture/ClientApp/package.json, line 89 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/1071#-McyrUzlAhxlJM131L4f:-McyrUzm7Qwc6GnIFvIe:bbweix5) ([raw file](https://github.com/sillsdev/web-xforge/blob/1ee2aa257a2be6adf589a1df251c5b8e61d2af2b/src/SIL.XForge.Scripture/ClientApp/package.json#L89)):*
> ```
>     "jasmine-spec-reporter": "~5.0.0",
> ```

This went down from '~6.0.0'. FYI if not desired.
___
*[src/SIL.XForge.Scripture/ClientApp/tsconfig.json, line 6 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/1071#-MczHjWU2FK4kErMuuhO:-MczHjWV4TCGPytHC4vZ:b-iie7ee) ([raw file](https://github.com/sillsdev/web-xforge/blob/1ee2aa257a2be6adf589a1df251c5b8e61d2af2b/src/SIL.XForge.Scripture/ClientApp/tsconfig.json#L6)):*
> ```jsonc
>     "baseUrl": "./",
>     "outDir": "./dist/out-tsc",
>     "forceConsistentCasingInFileNames": true,
> ```

Some of the changes are just line moves. Were these caused by a tool, or were you adhering to a specific ordering that you determined was preferable? Or what caused it? Wondering; not a problem.
___
*[src/SIL.XForge.Scripture/ClientApp/src/app/project-select/project-select.component.spec.ts, line 222 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/1071#-MczJN96ApyJmTF1StKW:-MczJN96ApyJmTF1StKX:bo78843) ([raw file](https://github.com/sillsdev/web-xforge/blob/1ee2aa257a2be6adf589a1df251c5b8e61d2af2b/src/SIL.XForge.Scripture/ClientApp/src/app/project-select/project-select.component.spec.ts#L222)):*
> ```XML
> 
>   get groupLabels(): string[] {
>     return Array.from(this.panel.querySelectorAll('.mat-optgroup-label')).map(e => e.textContent?.trim() || '');
> ```

Was this needed because when the template is turned into html, there is no line saying`<mat-optgroup label="...">` but instead some line saying something like `<li class="mat-optgroup-label" ...`, and so the query needed to match on `.mat-optgroup-label` ?
___
*[src/SIL.XForge.Scripture/ClientApp/src/app/shared/sfvalidators.ts, line 117 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/1071#-McysVzh21PjZ3F2l_kd:-McysVzh21PjZ3F2l_ke:bii0o82) ([raw file](https://github.com/sillsdev/web-xforge/blob/1ee2aa257a2be6adf589a1df251c5b8e61d2af2b/src/SIL.XForge.Scripture/ClientApp/src/app/shared/sfvalidators.ts#L117)):*
> ```XML
>     const invalidCtrl = control.invalid && control.parent!.dirty;
>     const invalidStart =
>       !control.parent!.controls['scriptureStart'].hasError('verseFormat') &&
> ```

Let's prevent `!` from creeping in. I think we can modify this and the following method by adding something like

```ts
if (control.parent == null) {
  return false;
}
```

I tried this in my IDE and it made the errors go away that were there when I removed the `!`s.

Probably good to combine with the `if (control == null)`.
___
*[src/SIL.XForge.Scripture/ClientApp/src/xforge-common/sharedb-realtime-remote-store.ts, line 31 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/1071#-MczIUV7AMLsVRLlJEmA:-MczIUV7AMLsVRLlJEmB:b-41r94y) ([raw file](https://github.com/sillsdev/web-xforge/blob/1ee2aa257a2be6adf589a1df251c5b8e61d2af2b/src/SIL.XForge.Scripture/ClientApp/src/xforge-common/sharedb-realtime-remote-store.ts#L31)):*
> ```XML
>   }
> 
>   async init(getAccessToken: () => string | undefined): Promise<void> {
> ```

I am pleased at the adding of the explicit return types. However I have been unable to make my machine complain if I revert this. 
I can run a production build. I can run ng lint. How do I trigger a problem if there is no return type specified?

**Review by irahopkinson — COMMENTED** [review]
I added instructions to the PR description to help running.

> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1071#-:-Md0Y_mKDwoJwrr28Sq8:bq9zx2)* status: 0 of 29 files reviewed, 1 unresolved discussion (waiting on @marksvc)

___
*[src/SIL.XForge.Scripture/ClientApp/package.json, line 89 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/1071#-McyrUzlAhxlJM131L4f:-Md0dPaVEaqJacy4aprL:b-hsm8oh) ([raw file](https://github.com/sillsdev/web-xforge/blob/1ee2aa257a2be6adf589a1df251c5b8e61d2af2b/src/SIL.XForge.Scripture/ClientApp/package.json#L89)):*
> ```
> jasmine-spec-reporter
> ```
Good spotting as I hadn't noticed. On further investigation this seems intentional by the updater to move to a earlier version but I don't know why. However its not production code so I'm not inclined to spend any more time on it.
___
*[src/SIL.XForge.Scripture/ClientApp/tsconfig.json, line 6 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/1071#-MczHjWU2FK4kErMuuhO:-Md0_mZv6ZKLGb6pgEQV:bpsgm14) ([raw file](https://github.com/sillsdev/web-xforge/blob/1ee2aa257a2be6adf589a1df251c5b8e61d2af2b/src/SIL.XForge.Scripture/ClientApp/tsconfig.json#L6)):*
<details><summary><i>Previously, marksvc wrote…</i></summary><blockquote>

Some of the changes are just line moves. Were these caused by a tool, or were you adhering to a specific ordering that you determined was preferable? Or what caused it? Wondering; not a problem.
</blockquote></details>

I think the `ng update` tool moved these but I might have made some changes too.
___
*[src/SIL.XForge.Scripture/ClientApp/src/app/project-select/project-select.component.spec.ts, line 222 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/1071#-MczJN96ApyJmTF1StKW:-Md0a7QQ48WiOO2Gbl9H:b-xq2lxo) ([raw file](https://github.com/sillsdev/web-xforge/blob/1ee2aa257a2be6adf589a1df251c5b8e61d2af2b/src/SIL.XForge.Scripture/ClientApp/src/app/project-select/project-select.component.spec.ts#L222)):*
<details><summary><i>Previously, marksvc wrote…</i></summary><blockquote>

Was this needed because when the template is turned into html, there is no line saying`<mat-optgroup label="...">` but instead some line saying something like `<li class="mat-optgroup-label" ...`, and so the query needed to match on `.mat-optgroup-label` ?
</blockquote></details>

Yes, it looks like in the later version of Material they have changed the way this is implemented. But because we have the getter method I only have to change this in one place.
___
*[src/SIL.XForge.Scripture/ClientApp/src/app/shared/sfvalidators.ts, line 117 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/1071#-McysVzh21PjZ3F2l_kd:-Md0sbE11844BjWJz_I-:b-fznogt) ([raw file](https://github.com/sillsdev/web-xforge/blob/1ee2aa257a2be6adf589a1df251c5b8e61d2af2b/src/SIL.XForge.Scripture/ClientApp/src/app/shared/sfvalidators.ts#L117)):*
<details><summary><i>Previously, marksvc wrote…</i></summary><blockquote>

Let's prevent `!` from creeping in. I think we can modify this and the following method by adding something like

```ts
if (control.parent == null) {
  return false;
}
```

I tried this in my IDE and it made the errors go away that were there when I removed the `!`s.

Probably good to combine with the `if (control == null)`.
</blockquote></details>

Good idea, done.
___
*[src/SIL.XForge.Scripture/ClientApp/src/xforge-common/sharedb-realtime-remote-store.ts, line 31 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/1071#-MczIUV7AMLsVRLlJEmA:-Md0ayPkEjmASfG7YcDP:b7ncb0z) ([raw file](https://github.com/sillsdev/web-xforge/blob/1ee2aa257a2be6adf589a1df251c5b8e61d2af2b/src/SIL.XForge.Scripture/ClientApp/src/xforge-common/sharedb-realtime-remote-store.ts#L31)):*
<details><summary><i>Previously, marksvc wrote…</i></summary><blockquote>

I am pleased at the adding of the explicit return types. However I have been unable to make my machine complain if I revert this. 
I can run a production build. I can run ng lint. How do I trigger a problem if there is no return type specified?

</blockquote></details>

I have noticed also recently that nothing is complaining about not having return types. I thought we already had that turned on but I might be remembering that incorrectly. I plan to address that in my ESLint migration branch.

**Review by marksvc — APPROVED** [review]
> Reviewed 24 of 28 files at r4, 1 of 1 files at r6, 1 of 1 files at r8, 1 of 1 files at r9, 2 of 2 files at r10.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1071)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @irahopkinson)

**Comment by marksvc** [comment]
Ok I also ran the frontend and backend locally and smoke-tested using SF. 

:ship:

**Review by marksvc — APPROVED** [review]
Smoke testing Scripture Forge at r11 showed that it's working. However: I had to give to give SF quite a shake, and along the way I sometimes had trouble getting text data to load, trouble with Gondi Test fonts showing up instead of showing as boxes, and a couple times the frontend said I was offline even tho the backend was running. So I'm not sure what to make of that. Right now I'm running SF and it's fine. Er, actually I _just_ got a popup and an error saying 
> DOMException: Transaction timed out due to inactivity.

But otherwise it seems fine now :).
Maybe try poking around in SF a bit more. It's working ok for Nathaniel. If it is working ok for you, then maybe something is just twisted on my machine. 

> Reviewed 1 of 1 files at r11.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1071#-:-MdOKiYwDnptZRH579QN:bq22fm6)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @irahopkinson)

**Review by irahopkinson — COMMENTED** [review]
@marksvc have you tried running those same tests at the point this branch branches off of master? What you are seeing may already exist.

> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1071#-:-MdQANBqAPhso6c8h0fM:b-ry1csp)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @irahopkinson)

**Comment by marksvc** [comment]
@irahopkinson  Today I went back to master at SF-QAv206, where this branched from, and did not have any problems. Then I went to the feature/ng11 branch and did some smoke testing and also did not have any problems. (Except after I did a Synchronize, the source text pane did not show up at first until I Reloaded my browser, but that's probably not related to this PR.)

So it must have been something weird on my system that day. 

:ship:

**Review by Nateowami — COMMENTED** [review]
Unfortunately, this isn't working on my machine. Even deleting `node_modules`, running `npm ci`, clearing storage, trying multiple browsers, etc., isn't making it work. Logging in, it just keeps loading forever. Might I be missing something?

> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1071#-:-MdJh43C6cuaQC0RkZ4W:b-e275pj)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @irahopkinson)

**Review by irahopkinson — COMMENTED** [review]
@nateowami you shouldn't have to do all that other stuff now - I'm just doing `npm i` in both folders. However you do have to do `dotnet clean` in the repo root. If you still have trouble I'd like you to share screens with me.

> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1071#-:-MdeDSpz5n7OpMmkqZpa:bs3tc2m)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @irahopkinson)

**Review by irahopkinson — COMMENTED** [review]
Actually another thing that might be important is if you have `npm` installed globally then you will need to update it first.

> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1071#-:-MdgHPtc1kumsx8LPVxA:b-cpuxj6)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @irahopkinson)

**Review by irahopkinson — COMMENTED** [review]
Ready for review again. Nathaniel is able to run it now. I've fixed an issue the testers found (too newer version of sharedb). I've also done some PWA testing which is about as close as we can get to a production build before QA.

> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1071#-:-Me-7xIO8PhCfsWZkNuF:b-mqihys)* status: 22 of 32 files reviewed, all discussions resolved (waiting on @marksvc)

**Review by marksvc — APPROVED** [review]
I approve.
I smoke tested connecting a project and looking at a text.
:ship: 

> Reviewed 1 of 7 files at r12, 9 of 9 files at r14.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1071#-:-Me0dUl1D_x1kgCnlStV:bdqny69)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @irahopkinson)

**Comment by marksvc** [comment]
Ira we have been diagnosing a problem with Nathaniel's computer today, which can't run feature/ng11 branch. 
We don't know yet what the problem is or if it's with his machine or what, but you might want to delay merging this until we know more.

**Review by irahopkinson — COMMENTED** [review]
No problem. I haven't rebased it so it can't be merged yet.

> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1071#-:-Me3ULTyBVrFjPNF6lpZ:bu009sb)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @irahopkinson)

**Pull request merged**
