### PR TITLE
SF-2498 Fix crash when no access to source project

### PR DESCRIPTION
**Pull request by pmachapman**
This PR fixes crashes that occur when a user attempting to generate a pre-translation draft does not have access to the:

 * Source
 * Training Source
 * Alternate Training Source

Instead of a crash, a message will be displayed requesting that the user connect to the project they do not have access to.

In addition, if there is already a draft generated or underway for the project, they will be available to view build progress or the generated draft, but not have the ability to generate a new draft, so long as they have access top the source project.

- - -
This change is [Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/2329)

### CODE REVIEW

**Review by josephmyers — CHANGES_REQUESTED** [review]
I ran through setting the Source Project for my review. Couple comments!

I notice that the Translator has to be given full (admin) access to the source. Why isn't Translator enough to generate a draft? They don't need to edit the source, just read it, right?

I also notice that the Translator can apply a generated draft even when he doesn't have edit permissions? I'll create a separate issue for this. SF-2524

> Reviewed 8 of 8 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/2329#-:-Nq62b3A3rkOKDXAI5iq:b-s2xzj2)* status: all files reviewed, 5 unresolved discussions (waiting on @pmachapman)

___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-generation.component.ts` line 123 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/2329#-Nq6BQDn5SZ4AaLlXPgC:-Nq6BQDn5SZ4AaLlXPgD:bn8q1e2) ([raw file](https://github.com/sillsdev/web-xforge/blob/771b7ff1de1d3e30659e5221b612d3596eeba60d/src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-generation.component.ts#L123)):*
> ```XML
>   }
> 
>   get isGenerationSupported(): boolean {
> ```

This is just isPreviewSupported plus a couple more boolean's, right? Can we remove the duplication?
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-generation.component.ts` line 229 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/2329#-Nq6I2Rf3Y8OwyT_wuVR:-Nq6I2Rf3Y8OwyT_wuVS:bqgcc7m) ([raw file](https://github.com/sillsdev/web-xforge/blob/771b7ff1de1d3e30659e5221b612d3596eeba60d/src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-generation.component.ts#L229)):*
> ```XML
>             this.canAccessSource = !(source?.noAccess ?? false);
>             this.canAccessAlternateSource = !(alternateSource?.noAccess ?? false);
>             this.canAccessAlternateTrainingSource = !(alternateTrainingSource?.noAccess ?? false);
> ```

Can we extract this logic into a method that accepts a DraftSource? Then we can get rid of the three public booleans.
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-sources.service.ts` line 56 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/2329#-Nq6K14MBp6TfsA8CDkj:-Nq6K14MBp6TfsA8CDkk:bbqtgoo) ([raw file](https://github.com/sillsdev/web-xforge/blob/771b7ff1de1d3e30659e5221b612d3596eeba60d/src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-sources.service.ts#L56)):*
> ```XML
>           sourceProjectId != null &&
>           !currentUser.data?.sites[environment.siteId].projects?.includes(sourceProjectId) &&
>           targetDoc?.data != null &&
> ```

You can remove this line by using optional chaining twice on the line below. Same for the copies
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-sources.service.ts` line 71 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/2329#-Nq6L68l-XKHTSYb3xTu:-Nq6L68l-XKHTSYb3xTv:b-ij1y7s) ([raw file](https://github.com/sillsdev/web-xforge/blob/771b7ff1de1d3e30659e5221b612d3596eeba60d/src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-sources.service.ts#L71)):*
> ```XML
>         }
> 
>         // If the user cannot access the alternate source project, populate using the target's alternate source info
> ```

These first two blocks are almost identical and should be converted use a common private method. Bonus points if the third block can use it, too. It's really close!
___
*[`src/SIL.XForge.Scripture/ClientApp/src/assets/i18n/non_checking_en.json` line 157 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/2329#-Nq6ANk2DePgXTguQpet:-Nq6ANk2DePgXTguQpeu:b-1729ly) ([raw file](https://github.com/sillsdev/web-xforge/blob/771b7ff1de1d3e30659e5221b612d3596eeba60d/src/SIL.XForge.Scripture/ClientApp/src/assets/i18n/non_checking_en.json#L157)):*
> ```JSON
>     "info_alert_no_source_access": "You do not have access to the translation source project {{ name }}. You must [link:connectProjectUrl]connect to this project[/link] before you can generate a draft.",
>     "info_alert_no_alternate_source_access": "You do not have access to the drafting source project {{ name }}. You must [link:connectProjectUrl]connect to this project[/link] before you can generate a draft.",
>     "info_alert_no_alternate_training_source_access": "You do not have access to the training source project {{ name }}. You must [link:connectProjectUrl]connect to this project[/link] before you can generate a draft.",
> ```

To me, the warning messages for the Translator don't make perfect sense. If they go to Connect Project, the source won't be there until the admin adds them. Wouldn't it be better to say something like, "First, get your admin to make you an admin on the project, then connect in SF"? Obviously doctor up that wording.

**Review by pmachapman — COMMENTED** [review]
> I notice that the Translator has to be given full (admin) access to the source.

I tested using an Observer on all 3 source projects and had no issues. Please let me know what was blocking you RE: access and I will see what the problem is.

There is a change in behavior on Serval QA, so please don't retest this until that is resolved (see the thread for Serval 1.2 in the SF Slack).

> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/2329#-:-NqOmJm9Ex3-ViPaSg4K:b-ogp8if)* status: 5 of 8 files reviewed, 5 unresolved discussions (waiting on @josephmyers)

___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-generation.component.ts` line 123 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/2329#-Nq6BQDn5SZ4AaLlXPgC:-NqOdrtx5n7TkFesnrLc:b-ydonir) ([raw file](https://github.com/sillsdev/web-xforge/blob/771b7ff1de1d3e30659e5221b612d3596eeba60d/src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-generation.component.ts#L123)):*
<details><summary><i>Previously, josephmyers wrote…</i></summary><blockquote>

This is just isPreviewSupported plus a couple more boolean's, right? Can we remove the duplication?
</blockquote></details>

Done. Good idea.
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-generation.component.ts` line 229 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/2329#-Nq6I2Rf3Y8OwyT_wuVR:-NqOjrWt-IQFF22HR-j0:bedtrpc) ([raw file](https://github.com/sillsdev/web-xforge/blob/771b7ff1de1d3e30659e5221b612d3596eeba60d/src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-generation.component.ts#L229)):*
<details><summary><i>Previously, josephmyers wrote…</i></summary><blockquote>

Can we extract this logic into a method that accepts a DraftSource? Then we can get rid of the three public booleans.
</blockquote></details>

The public booleans made the unit testing a lot easier, and the frontend clear. I was also able to work with the existing test matrix, and find bugs and inconsistencies in my test coverage.

I see how it could get bloated as we add further checks though - `canDoThis`, `canDoThat`, `isAbleToDoSomething`, etc...

Are we able to keep these booleans for now?
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-sources.service.ts` line 56 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/2329#-Nq6K14MBp6TfsA8CDkj:-NqOegMy9f7KIMKNu8o9:b-ioxi27) ([raw file](https://github.com/sillsdev/web-xforge/blob/771b7ff1de1d3e30659e5221b612d3596eeba60d/src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-sources.service.ts#L56)):*
<details><summary><i>Previously, josephmyers wrote…</i></summary><blockquote>

You can remove this line by using optional chaining twice on the line below. Same for the copies
</blockquote></details>

Done. Thank you!
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-sources.service.ts` line 71 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/2329#-Nq6L68l-XKHTSYb3xTu:-NqOgmYLCKYiECsfYy-T:b-896fix) ([raw file](https://github.com/sillsdev/web-xforge/blob/771b7ff1de1d3e30659e5221b612d3596eeba60d/src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-sources.service.ts#L71)):*
<details><summary><i>Previously, josephmyers wrote…</i></summary><blockquote>

These first two blocks are almost identical and should be converted use a common private method. Bonus points if the third block can use it, too. It's really close!
</blockquote></details>

Done.
___
*[`src/SIL.XForge.Scripture/ClientApp/src/assets/i18n/non_checking_en.json` line 157 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/2329#-Nq6ANk2DePgXTguQpet:-NqOj6_y-yv_601kIxqr:b-hrj1vw) ([raw file](https://github.com/sillsdev/web-xforge/blob/771b7ff1de1d3e30659e5221b612d3596eeba60d/src/SIL.XForge.Scripture/ClientApp/src/assets/i18n/non_checking_en.json#L157)):*
<details><summary><i>Previously, josephmyers wrote…</i></summary><blockquote>

To me, the warning messages for the Translator don't make perfect sense. If they go to Connect Project, the source won't be there until the admin adds them. Wouldn't it be better to say something like, "First, get your admin to make you an admin on the project, then connect in SF"? Obviously doctor up that wording.
</blockquote></details>

Done. I have updated the wording - please let me know if it is clear.

**Review by josephmyers — CHANGES_REQUESTED** [review]
I retested just now and didn't see anything as just a Translator, so I must've been doing something wrong. Maybe I forgot to sync? Sorry!

> Reviewed 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/2329#-:-NqQCy8T1bfzWs-2YX2r:ba2qeca)* status: all files reviewed, 1 unresolved discussion (waiting on @pmachapman)

___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-generation.component.ts` line 229 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/2329#-Nq6I2Rf3Y8OwyT_wuVR:-NqQDHnO8V4jcBq5X33q:b-468657) ([raw file](https://github.com/sillsdev/web-xforge/blob/771b7ff1de1d3e30659e5221b612d3596eeba60d/src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-generation.component.ts#L229)):*
<details><summary><i>Previously, pmachapman (Peter Chapman) wrote…</i></summary><blockquote>

The public booleans made the unit testing a lot easier, and the frontend clear. I was also able to work with the existing test matrix, and find bugs and inconsistencies in my test coverage.

I see how it could get bloated as we add further checks though - `canDoThis`, `canDoThat`, `isAbleToDoSomething`, etc...

Are we able to keep these booleans for now?
</blockquote></details>

It's just the design of it. The more ways that consumers can publicly tinker with business model and state, the easier it is to introduce unintended side-effects. This is more important when making things reusable, so I guess we're not incredibly concerned about it here.

As for the unit testing, I always try to avoid making properties on production code that exist just to ease testing. It is easier, sure, but it means the tests don't recreate the scenarios for which they exist in the first place. I do like that these tests are really easy to read, but they're not fully testing the component.

Look at DraftSourcesService in the test file. It's got the same data for every test, because you're using the booleans instead of it. So we have a coverage gap, where we're not actually verifying that we're reading the right data from this service. Comment out the DraftSourcesService lines in the production code, and no tests will fail.

**Review by josephmyers — APPROVED** [review]
Sorry for the confusion. In my last message, I meant I didn't see anything wrong. Everything worked as expected when just a Translator. Maybe in my original testing, maybe I hadn't synced, and that was why things weren't showing up as I'd expected. When I ran through the next day, Translators were working fine. Your code is good!

> Reviewed 3 of 3 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/2329#-:-NqViB6u4M3yIydV1j5h:b-bcrqna)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @pmachapman)

___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-generation.component.ts` line 229 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/2329#-Nq6I2Rf3Y8OwyT_wuVR:-NqViaWA9SBMgO7RDgA0:banihfu) ([raw file](https://github.com/sillsdev/web-xforge/blob/771b7ff1de1d3e30659e5221b612d3596eeba60d/src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-generation.component.ts#L229)):*
<details><summary><i>Previously, pmachapman (Peter Chapman) wrote…</i></summary><blockquote>

OK - I have refactored the logic. Let me know if I implemented it along the lines you were thinking.
</blockquote></details>

Thanks, it's better!

**Pull request merged**
