### PR TITLE
SF-3022 Do not allow a project to be deleted while it is syncing

### PR DESCRIPTION
**Pull request by pmachapman**
This PR stops  a project from being deleted while it is syncing, and adds a log message when the project is deleted.

This should stop the issues that are occurring where the Paratext directory for a project is present when a project is in the process of creation.

- - -
This change is [Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/2798)

### CODE REVIEW

**Review by marksvc — CHANGES_REQUESTED** [review]
Thanks for your work on this. I approve, except for one comment in the tests. 

I tested locally and when a project is syncing, the Settings page disables the Delete button and says I can not delete while syncing. When this message is not present, and the button is enabled, I am able to delete a project. Good.

I did find, only for the first project that I tried deleting, that it gave an error when I deleted it, and seemed to leave me at a partial view of the project (I could see settings, but not get to anything else project related). Reloading the page showed that the project was gone, and I could Connect to it again without trouble. I'm not aware that this error is related to the PR at hand, but just in case, the error message was as follows. 

<blockquote>
       Start processing HTTP request DELETE https://qa.serval-api.org/api/v1/translation/engines/65e291c967328c059c1686ab           
[2024-10-15 19:42:22] info: System.Net.Http.HttpClient.machine_api.ClientHandler[100]                                              
      Sending HTTP request DELETE https://qa.serval-api.org/api/v1/translation/engines/65e291c967328c059c1686ab                    
[2024-10-15 19:42:23] info: System.Net.Http.HttpClient.machine_api.ClientHandler[101]                                              
      Received HTTP response headers after 349.1891ms - 403                                                                        
[2024-10-15 19:42:23] info: System.Net.Http.HttpClient.machine_api.LogicalHandler[101]                                                                                                                                                                                
      End processing HTTP request after 349.7412ms - 403                                                                           
[2024-10-15 19:42:23] fail: EdjCase.JsonRpc.Router.Defaults.DefaultRpcInvoker[0]                                                   
      An Rpc error occurred while trying to invoke request.                                                                                                                                                                                                           
      EdjCase.JsonRpc.Common.RpcException: Exception occurred from target method execution.                                        
       ---> HTTP Response:                                                                                                                                                                                                                                            
                                                                                                                                   
                                                                                                                                                                                                                                                                      
                                                                                                                                   
      Serval.Client.ServalApiException: The authenticated client cannot perform the operation or does not own the translation engine.                                                                                                                                 
                                                                                                                                   
      Status: 403                                                                                                                  
      Response:                                                                                                                                                                                                                                                       
                                                                                                                                   
         at Serval.Client.TranslationEnginesClient.DeleteAsync(String id, CancellationToken cancellationToken)                     
         at SIL.XForge.Scripture.Services.MachineProjectService.RemoveProjectAsync(String curUserId, String sfProjectId, Boolean preTranslate, CancellationToken cancellationToken) in /home/vagrant/src/web-xforge/src/SIL.XForge.Scripture/Services/MachineProjectSe
rvice.cs:line 598                                                                                                                  
         at SIL.XForge.Scripture.Services.SFProjectService.DeleteProjectAsync(String curUserId, String projectId) in /home/vagrant/src/web-xforge/src/SIL.XForge.Scripture/Services/SFProjectService.cs:line 305                                                      
         at SIL.XForge.Scripture.Controllers.SFProjectsRpcController.Delete(String projectId) in /home/vagrant/src/web-xforge/src/SIL.XForge.Scripture/Controllers/SFProjectsRpcController.cs:line 103                                                                
         at EdjCase.JsonRpc.Router.Defaults.DefaultRpcInvoker.HandleAsyncResponses(Object returnObj)                               
         --- End of inner exception stack trace ---                                                                                                                                                                                                                   
         at EdjCase.JsonRpc.Router.Defaults.DefaultRpcInvoker.InvokeAsync(IRpcMethodInfo methodInfo, Object[] parameters, RpcRequest request, IServiceProvider serviceProvider)                                                                                       
         at EdjCase.JsonRpc.Router.Defaults.DefaultRpcInvoker.InvokeRequestAsync(RpcRequest request)                               
      EdjCase.JsonRpc.Common.RpcException: Exception occurred from target method execution.                                        
</blockquote>

> Reviewed 8 of 9 files at r1, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/2798#-:-O9GgrQZ21IDM7XtoN4e:b-5iafi6)* status: all files reviewed, 5 unresolved discussions (waiting on @pmachapman)

___
*[`test/SIL.XForge.Scripture.Tests/Services/SFProjectServiceTests.cs` line 2684 at r4](https://reviewable.io/reviews/sillsdev/web-xforge/2798#-O9GVI4y3se1q793VyhY:-O9GVI4y3se1q793VyhZ:b3lrs9h) ([raw file](https://github.com/sillsdev/web-xforge/blob/d59b0e0588e37f175359572409051160c0f9719d/test/SIL.XForge.Scripture.Tests/Services/SFProjectServiceTests.cs#L2684)):*
> ```Smalltalk
>         Assert.That(env.ProjectSecrets.Contains(Project01), Is.True, "setup");
>         // SUT
>         await env.Service.DeleteProjectAsync(User01, Project01);
> ```

I think this unit test may have two separate SUTs, though only one is labelled, which is a bit confusing. There isn't a special reason to just check that the logging occurred for the second `env.Service.DeleteProjectAsync`, instead of checking that the logging occurred both times, is there? Or maybe I'm missing something.


<!-- Sent from Reviewable.io -->

**Review by pmachapman — COMMENTED** [review]
> I did find, only for the first project that I tried deleting, that it gave an error when I deleted it,

That looks like it occurred because the Serval Project was created with the old API keys, while your local Scripture Forge is using the newer keys. If you were to reconnect to the project, the error would not reoccur on deletion.

> Dismissed @github-advanced-security[bot] from 4 discussions.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/2798#-:-O9HDVzT8i2H_e7EBtsq:b5bya0e)* status: all files reviewed, 1 unresolved discussion (waiting on @marksvc)

___
*[`test/SIL.XForge.Scripture.Tests/Services/SFProjectServiceTests.cs` line 2684 at r4](https://reviewable.io/reviews/sillsdev/web-xforge/2798#-O9GVI4y3se1q793VyhY:-O9HF5684M-iYVmFLunl:b-za4zi1) ([raw file](https://github.com/sillsdev/web-xforge/blob/d59b0e0588e37f175359572409051160c0f9719d/test/SIL.XForge.Scripture.Tests/Services/SFProjectServiceTests.cs#L2684)):*
<details><summary><i>Previously, marksvc wrote…</i></summary><blockquote>

I think this unit test may have two separate SUTs, though only one is labelled, which is a bit confusing. There isn't a special reason to just check that the logging occurred for the second `env.Service.DeleteProjectAsync`, instead of checking that the logging occurred both times, is there? Or maybe I'm missing something.
</blockquote></details>

I have marked two SUTs, and added logging. I think this test has incrementally grown overtime, so the additional log check was probably missed sometime in the past.

**Review by marksvc — APPROVED** [review]
Ah. Thank you. Yes, reconnecting the project and doing Delete again did not give the error. 

> Reviewed 1 of 1 files at r5.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/2798#-:-O9HJVe4DqKDL6Vhz9Cb:b-zbbf34)* status: all files reviewed (commit messages unreviewed), all discussions resolved (waiting on @pmachapman)

**Review by pmachapman — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/2798)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @pmachapman)

**Pull request merged**
