### PR TITLE
SF-2691 Fixed manage audio button not displaying for non-admin users

### PR DESCRIPTION
**Pull request by kylebuss**
Removed Audio Button code from `ng-container` for Add/Edit Questions.

- - -
This change is [Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/2587)

### CODE REVIEW

**Review by RaymondLuong3 — CHANGES_REQUESTED** [review]
Excellent fix. You will need to add a test to `checking.component.spec.ts`. This will help to prevent this change from regressing. Please also update you PR title to reflect how the code was changed from the user's perspective. Something like "Fix problem with manage audio button not showing for non-admins"

> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/2587#-:-O1c_gp_1djzECPefk8-:b-i2fo00)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @kylebuss)

**Comment by kylebuss** [comment]
@RaymondLuong3 I went ahead and deleted the repo from my local and re-cloned it. Looks like my push issue is now resolved. Test cases have been added to the PR.

**Review by RaymondLuong3 — CHANGES_REQUESTED** [review]
Nice! I'm glad that ended up solving the problem. I updated my review with one more minor comment.

> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/2587#-:-O21pMcFDu2gIoLqbHZl:b-a0m53h)* status: all files reviewed, 1 unresolved discussion (waiting on @kylebuss)

___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking.component.spec.ts` line 2654 at r2](https://reviewable.io/reviews/sillsdev/web-xforge/2587#-O21p34i4DcaJ0w1DxKh:-O21p34i4DcaJ0w1DxKi:bx307di) ([raw file](https://github.com/sillsdev/web-xforge/blob/65090a348295a5915f3d39569654a7c8635a758a/src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking.component.spec.ts#L2654)):*
> ```XML
>       [TRANSLATOR_USER.id]: audioPermissions,
>       [CONSULTANT_USER.id]: questionPermissions,
>       [ADMIN_USER.id]: adminPermissions
> ```

I don't think this is necessary. I don't think that we check permissions for admins, they have permission by their role.



_Code quote:_
```XML
      [ADMIN_USER.id]: adminPermissions
```

**Review by RaymondLuong3 — APPROVED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/2587)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @kylebuss)

**Review by RaymondLuong3 — APPROVED** [review]
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/2587)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @kylebuss)

**Pull request merged**
