### PR TITLE
SF-3081 Show draft queued immediately when job started

### PR DESCRIPTION
**Pull request by RaymondLuong3**
There is a small delay between when a draft is started and when we get the draft job from the draft generation service that indicates that the build was queued. The small delay after the build is started will look like nothing happened when the user initiates a draft build and can be confusing. This PR delays closing the draft generation stepper until a queued job is retrieved from serval. A spinner progress is displayed as the user waits for the queued job.

- - -
This change is [Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/2853)

### CODE REVIEW

**Comment by Nateowami** [comment]
This is an improvement, but it's more of a band-aid than a fix.

Here's what it looks like in the new state that's been added:



And here's what it looks like a few second later:



- Description of old draft is different
- The "New draft" button is still present

I also don't see anything addressing or commenting on the related related race-condition bug mentioned on the issue. It's possible it should be a separate fix, but I included it as part of the issue because they're extremely similar and can't be separated without investigating the cause.

**Comment by RaymondLuong3** [comment]
I can investigate further into why a draft does not get started if leaving the page before the queued build returns.

**Review by RaymondLuong3 — COMMENTED** [review]
I found a better solution for this issue. If we delay closing the draft generation stepper until we get the initial queued job, then it will be much less confusing to users. I've made this change.
I was unable to reproduce the issue with the draft not starting when navigating away from the draft generation page. With this change, it seems less likely for a user to do that (but still possible). I think that deserves a new card if desired.

> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/2853#-:-OBm-_AaE2WeIeDTS4wZ:b-rsqmv9)* status: 0 of 7 files reviewed, all discussions resolved

**Comment by Nateowami** [comment]
I haven't reviewed the code, but this looks a lot cleaner. Thanks for working on this @RaymondLuong3

**Review by pmachapman — APPROVED** [review]
Your code looks good - just one nit.

I was able to recreate the initial bug with a Back Translation: (up to you if you want to fix that in this PR or another PR)

1. Connect to a back translation project and set the source
2. Start a build
3. Refresh the page

The Generate Draft button will display, rather than the build progress. This is because the `sf_project.translateConfig.preTranslate` flag has not been set (see the checkbox in Serval Admin in screenshot below). My suggested solution is to set the `preTranslate` flag as on of the first actions in `MachineApiService.StartPreTranslationBuildAsync()`


> Reviewed 7 of 7 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/2853#-:-OC-un_E6V0KBfKW5lPv:b-e9fxjd)* status: all files reviewed, 1 unresolved discussion (waiting on @RaymondLuong3)

___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-generation.component.spec.ts` line 82 at r2](https://reviewable.io/reviews/sillsdev/web-xforge/2853#-OC-wP4JBXg7ld4JUuVR:-OC-wP4JBXg7ld4JUuVS:bt0pnn7) ([raw file](https://github.com/sillsdev/web-xforge/blob/9d408b3c1de0688777c3e908083654435536509d/src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-generation.component.spec.ts#L82)):*
> ```XML
>   class TestEnvironment {
>     readonly testOnlineStatusService: TestOnlineStatusService;
>     readonly startedOrActiveBuild$: Subject<BuildDto> = new Subject<BuildDto>();
> ```

NIT: Remove the double type declaration, i.e.
```ts
readonly startedOrActiveBuild$ = new Subject<BuildDto>();
```

**Review by RaymondLuong3 — COMMENTED** [review]
I will open a new card for this so that it can be properly tested in isolation. Thanks for the steps to reproduce the bug!

> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/2853#-:-OC04Fxs5UE9MKKQ-LhD:b4nasm2)* status: 6 of 7 files reviewed, all discussions resolved (waiting on @pmachapman)

___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-generation.component.spec.ts` line 82 at r2](https://reviewable.io/reviews/sillsdev/web-xforge/2853#-OC-wP4JBXg7ld4JUuVR:-OC04NKyCnwICWwFGOEV:b-896fix) ([raw file](https://github.com/sillsdev/web-xforge/blob/9d408b3c1de0688777c3e908083654435536509d/src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-generation.component.spec.ts#L82)):*
<details><summary><i>Previously, pmachapman (Peter Chapman) wrote…</i></summary><blockquote>

NIT: Remove the double type declaration, i.e.
```ts
readonly startedOrActiveBuild$ = new Subject<BuildDto>();
```
</blockquote></details>

Done.

**Review by pmachapman — APPROVED** [review]
:lgtm: 

> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/2853#-:-OC0LtAv8IORsm6VpCre:bg7igkv)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @RaymondLuong3)

**Pull request merged**
