### PR TITLE
SF-1608 Improve quality of Bugsnag reporting

### PR DESCRIPTION
**Pull request by pmachapman**
This pull request improves reporting to Bugsnag in .NET as follows:
 * Upgraded Bugsnag to 3.1.0 to improve .NET 6.0 support
 * Fixed a scoping issue that stopped request data from being sent to Bugsnag
 * The userId is now sent to Bugsnag
 * Endpoint specific data is now sent to Bugsnag , including the projectId, endpoint method name, and any relevant parameters that do not expose PII

---
This change is [Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1449)

### CODE REVIEW

**Review by RaymondLuong3 — CHANGES_REQUESTED** [review]
> Reviewed 8 of 8 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1449)* status: all files reviewed, 4 unresolved discussions (waiting on @pmachapman)

___
*[`src/SIL.XForge/Controllers/UsersRpcController.cs` line 46 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/1449#-N8db2DL053WGiRyk86R:-N8db2DL053WGiRyk86S:bojtcjp) ([raw file](https://github.com/sillsdev/web-xforge/blob/fc0934c42befead34c1eaa020551cd8c9a65a21b/src/SIL.XForge/Controllers/UsersRpcController.cs#L46)):*
> ```Smalltalk
>             {
>                 // Send additional to bugsnag, then rethrow the error
>                 _bugsnag.BeforeNotify(report =>
> ```

What do you think about creating a new method called AddEndpointInfoAndReport(). And supply the dictionary as a param. I know this would just create a method that then calls a method, but it could look cleaner.



_Code quote:_
```Smalltalk
                // Send additional to bugsnag, then rethrow the error
                _bugsnag.BeforeNotify(report =>
                {
```
___
*[`src/SIL.XForge/ExceptionLogging/ExceptionHandlerServiceCollectionExtensions.cs` line 11 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/1449#-N8dbpNP6IFHzN01vzeD:-N8dbpNQ2S-l2knUu4pQ:b-l70vdk) ([raw file](https://github.com/sillsdev/web-xforge/blob/fc0934c42befead34c1eaa020551cd8c9a65a21b/src/SIL.XForge/ExceptionLogging/ExceptionHandlerServiceCollectionExtensions.cs#L11)):*
> ```Smalltalk
>         public static IServiceCollection AddExceptionReporting(this IServiceCollection services, IConfiguration configuration)
>         {
>             services.AddScoped<IExceptionHandler, ExceptionHandler>();
> ```

What does this do? I could look this up, but you may be able to explain why you made this change.



_Code quote:_
```Smalltalk
services.AddScoped<IExceptionHandler, ExceptionHandler>();
```
___
*[`src/SIL.XForge.Scripture/Controllers/ParatextController.cs` line 34 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/1449#-N8dc1t88H4AgjabO31k:-N8dc1t88H4AgjabO31l:b-9u3urp) ([raw file](https://github.com/sillsdev/web-xforge/blob/fc0934c42befead34c1eaa020551cd8c9a65a21b/src/SIL.XForge.Scripture/Controllers/ParatextController.cs#L34)):*
> ```Smalltalk
>             _bugsnag = client;
> 
>             // Report the user id to bugsnag for this request
> ```

Could we create a protected method in ControllerBase  called AddUserToBugsnagReport() and call this in all the child class constructors



_Code quote:_
```Smalltalk
            // Report the user id to bugsnag for this request
            if (!string.IsNullOrWhiteSpace(_userAccessor.UserId))
            {
```
___
*[`src/SIL.XForge.Scripture/Controllers/SFProjectsRpcController.cs` line 122 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/1449#-N8ddUFq66zRIVp4DfnJ:-N8ddUFq66zRIVp4DfnK:b-uuzbw5) ([raw file](https://github.com/sillsdev/web-xforge/blob/fc0934c42befead34c1eaa020551cd8c9a65a21b/src/SIL.XForge.Scripture/Controllers/SFProjectsRpcController.cs#L122)):*
> ```Smalltalk
>                         { "method", "UpdateSettings"},
>                         { "projectId", projectId },
>                         { "CheckingShareLevel", settings?.CheckingShareLevel },
> ```

I assume that if settings is null, then we add null to the dictionary. And bugsnag would interpret that null to be a string. Is that correct?



_Code quote:_
```Smalltalk
 { "CheckingShareLevel", settings?.CheckingShareLevel },
```
___
*[`src/SIL.XForge.Scripture/Controllers/SFProjectsRpcController.cs` line 280 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/1449#-N8ddGf4DtBUcPFlnVws:-N8ddGf4DtBUcPFlnVwt:b-7ldkr6) ([raw file](https://github.com/sillsdev/web-xforge/blob/fc0934c42befead34c1eaa020551cd8c9a65a21b/src/SIL.XForge.Scripture/Controllers/SFProjectsRpcController.cs#L280)):*
> ```Smalltalk
>                         { "method", "Invite"},
>                         { "projectId", projectId },
>                         // Exclude email as it is PII
> ```

Good thinking



_Code quote:_
```Smalltalk
   // Exclude email as it is PII
```

**Review by pmachapman — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1449)* status: 1 of 13 files reviewed, 4 unresolved discussions (waiting on @RaymondLuong3)

___
*[`src/SIL.XForge/Controllers/UsersRpcController.cs` line 46 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/1449#-N8db2DL053WGiRyk86R:-N8jgJHk8WP4FvAanryg:bx8dura) ([raw file](https://github.com/sillsdev/web-xforge/blob/fc0934c42befead34c1eaa020551cd8c9a65a21b/src/SIL.XForge/Controllers/UsersRpcController.cs#L46)):*
<details><summary><i>Previously, RaymondLuong3 (Raymond Luong) wrote…</i></summary><blockquote>

What do you think about creating a new method called AddEndpointInfoAndReport(). And supply the dictionary as a param. I know this would just create a method that then calls a method, but it could look cleaner.
</blockquote></details>

Good idea. I have created `IExceptionHander.RecordEndpointInfoForException()`, which does this. It makes it a tiny bit clearer, but definitely more readable/understandable.
___
*[`src/SIL.XForge/ExceptionLogging/ExceptionHandlerServiceCollectionExtensions.cs` line 11 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/1449#-N8dbpNP6IFHzN01vzeD:-N8jo9O35kuv6sVeJu9D:b-cw8sms) ([raw file](https://github.com/sillsdev/web-xforge/blob/fc0934c42befead34c1eaa020551cd8c9a65a21b/src/SIL.XForge/ExceptionLogging/ExceptionHandlerServiceCollectionExtensions.cs#L11)):*
<details><summary><i>Previously, RaymondLuong3 (Raymond Luong) wrote…</i></summary><blockquote>

What does this do? I could look this up, but you may be able to explain why you made this change.
</blockquote></details>

Previously, `ExceptionHandler` was scoped as a singleton. This meant that request data was not being included in the exception report to Bugsnag, as there was only one global instance of the class. Changing the class to a Scoped lifetime means that one instance is created per request. This means that request data is now sent to Bugsnag, and also that the user data and metadata could now be included in the exception report (if it was a singleton, this would leak between requests).
___
*[`src/SIL.XForge.Scripture/Controllers/ParatextController.cs` line 34 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/1449#-N8dc1t88H4AgjabO31k:-N8jgdbw2B9Ueis39cGu:b4hu1yj) ([raw file](https://github.com/sillsdev/web-xforge/blob/fc0934c42befead34c1eaa020551cd8c9a65a21b/src/SIL.XForge.Scripture/Controllers/ParatextController.cs#L34)):*
<details><summary><i>Previously, RaymondLuong3 (Raymond Luong) wrote…</i></summary><blockquote>

Could we create a protected method in ControllerBase  called AddUserToBugsnagReport() and call this in all the child class constructors
</blockquote></details>

`ControllerBase` is a part of ASP.NET Core MVC, so instead I have added a `RecordUserIdForException` method to `IExceptionHander`. I did consider creating a superclass, but then realised the only logic in it would be the constructor. Please let me know if this is acceptable?
___
*[`src/SIL.XForge.Scripture/Controllers/SFProjectsRpcController.cs` line 122 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/1449#-N8ddUFq66zRIVp4DfnJ:-N8jjUuAEdFPG-N_Bgep:bqktsph) ([raw file](https://github.com/sillsdev/web-xforge/blob/fc0934c42befead34c1eaa020551cd8c9a65a21b/src/SIL.XForge.Scripture/Controllers/SFProjectsRpcController.cs#L122)):*
<details><summary><i>Previously, RaymondLuong3 (Raymond Luong) wrote…</i></summary><blockquote>

I assume that if settings is null, then we add null to the dictionary. And bugsnag would interpret that null to be a string. Is that correct?
</blockquote></details>

Yes. Under the endpoint tab in the Bugsnag report, Bugsnag will just display "CheckingShareLevel null", i.e.

**Review by RaymondLuong3 — CHANGES_REQUESTED** [review]
Nice. It does look nice to keep the bugsnag classes inside exception handler. Just one more minor comment, then it will be good to go.

> Reviewed 12 of 12 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1449#-:-N8jvQJyAi3E0z4Nz1h5:b-bgplxr)* status: all files reviewed, 4 unresolved discussions (waiting on @pmachapman)

___
*[`src/SIL.XForge/Controllers/UsersRpcController.cs` line 46 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/1449#-N8db2DL053WGiRyk86R:-N8jvetX0I7D0VRuasgZ:btojbfd) ([raw file](https://github.com/sillsdev/web-xforge/blob/fc0934c42befead34c1eaa020551cd8c9a65a21b/src/SIL.XForge/Controllers/UsersRpcController.cs#L46)):*
<details><summary><i>Previously, pmachapman (Peter Chapman) wrote…</i></summary><blockquote>

Good idea. I have created `IExceptionHander.RecordEndpointInfoForException()`, which does this. It makes it a tiny bit clearer, but definitely more readable/understandable.
</blockquote></details>

Great!
___
*[`src/SIL.XForge/Controllers/UsersRpcController.cs` line 50 at r2](https://reviewable.io/reviews/sillsdev/web-xforge/1449#-N8juLQE4LdcjPkcTFhC:-N8juLQFAxYnxa5zoA37:ba1f78a) ([raw file](https://github.com/sillsdev/web-xforge/blob/1eb635efa403285bd898e5213a6e2a88fc34f2ec/src/SIL.XForge/Controllers/UsersRpcController.cs#L50)):*
> ```Smalltalk
>             catch (Exception)
>             {
>                 // Send additional to bugsnag, then rethrow the error
> ```

I think we can remove these comments, or if you want to leave them there it should say "send additional info to bugsnag...
Here an below.



_Code quote:_
```Smalltalk
      // Send additional to bugsnag, then rethrow the error
```
___
*[`src/SIL.XForge/ExceptionLogging/ExceptionHandlerServiceCollectionExtensions.cs` line 11 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/1449#-N8dbpNP6IFHzN01vzeD:-N8junlB0q502UnsAH52:b-r2461y) ([raw file](https://github.com/sillsdev/web-xforge/blob/fc0934c42befead34c1eaa020551cd8c9a65a21b/src/SIL.XForge/ExceptionLogging/ExceptionHandlerServiceCollectionExtensions.cs#L11)):*
<details><summary><i>Previously, pmachapman (Peter Chapman) wrote…</i></summary><blockquote>

Previously, `ExceptionHandler` was scoped as a singleton. This meant that request data was not being included in the exception report to Bugsnag, as there was only one global instance of the class. Changing the class to a Scoped lifetime means that one instance is created per request. This means that request data is now sent to Bugsnag, and also that the user data and metadata could now be included in the exception report (if it was a singleton, this would leak between requests).
</blockquote></details>

That makes sense. Thanks
___
*[`src/SIL.XForge.Scripture/Controllers/ParatextController.cs` line 34 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/1449#-N8dc1t88H4AgjabO31k:-N8jvk9B2ijGBpPD6rcB:bk46d0l) ([raw file](https://github.com/sillsdev/web-xforge/blob/fc0934c42befead34c1eaa020551cd8c9a65a21b/src/SIL.XForge.Scripture/Controllers/ParatextController.cs#L34)):*
<details><summary><i>Previously, pmachapman (Peter Chapman) wrote…</i></summary><blockquote>

`ControllerBase` is a part of ASP.NET Core MVC, so instead I have added a `RecordUserIdForException` method to `IExceptionHander`. I did consider creating a superclass, but then realised the only logic in it would be the constructor. Please let me know if this is acceptable?
</blockquote></details>

Oh yes, I didn't realize the `ControllerBase` was part of MVC. This is good enough for me.
___
*[`src/SIL.XForge.Scripture/Controllers/SFProjectsRpcController.cs` line 122 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/1449#-N8ddUFq66zRIVp4DfnJ:-N8jv22F8VRYBiaWudX1:b-16yetq) ([raw file](https://github.com/sillsdev/web-xforge/blob/fc0934c42befead34c1eaa020551cd8c9a65a21b/src/SIL.XForge.Scripture/Controllers/SFProjectsRpcController.cs#L122)):*
<details><summary><i>Previously, pmachapman (Peter Chapman) wrote…</i></summary><blockquote>

Yes. Under the endpoint tab in the Bugsnag report, Bugsnag will just display "CheckingShareLevel null", i.e.


</blockquote></details>

Good. Thanks for checking on that.

**Review by pmachapman — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1449)* status: 8 of 13 files reviewed, 1 unresolved discussion (waiting on @RaymondLuong3)

___
*[`src/SIL.XForge/Controllers/UsersRpcController.cs` line 50 at r2](https://reviewable.io/reviews/sillsdev/web-xforge/1449#-N8juLQE4LdcjPkcTFhC:-N8k0H4F6WmChdhYnJ1l:bjtts1x) ([raw file](https://github.com/sillsdev/web-xforge/blob/1eb635efa403285bd898e5213a6e2a88fc34f2ec/src/SIL.XForge/Controllers/UsersRpcController.cs#L50)):*
<details><summary><i>Previously, RaymondLuong3 (Raymond Luong) wrote…</i></summary><blockquote>

I think we can remove these comments, or if you want to leave them there it should say "send additional info to bugsnag...
Here an below.
</blockquote></details>

Sounds good - done. I was unsure whether to remove them, but I think it is understandable without the comments. Thank you!

**Review by RaymondLuong3 — APPROVED** [review]
> Reviewed 5 of 5 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1449)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @pmachapman)

**Pull request merged**
