### PR TITLE
SF-3060 Add secure ports for localhost development

### PR DESCRIPTION
**Pull request by pmachapman**
This Pull Request adds support for secure access to Scripture Forge via https://localhost:5001/. This will allow BrowserStack Live to run Scripture Forge on iOS devices. See https://github.com/sillsdev/web-xforge/wiki/BrowserStack#iOS for details.

You will need to trust the certificate `dev-certs/localhost.crt` for your browser to accept the request. This certificate is not to be deployed to any environment, and is exclusively for localhost use on developer machines.

- - -
This change is [Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/2840)

### CODE REVIEW

**Review by kylebuss — CHANGES_REQUESTED** [review]
Awesome work so far. I am only able to get as far as the home page (at least that's loading). I set the accept self-signed certificate as mentioned. Do I need to install this certificate on my local machine?

I get the following when I try and login:


> Reviewed 13 of 13 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/2840#-:-OB112p89U9ZM_D52AtZ:b79s1wq)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @pmachapman)

**Comment by kylebuss** [comment]
I was able to get logged in. So I'm wondering if it was just a blip with communication between SF and Auth0. However, I did get the following error dialog when I selected a project:

**Review by pmachapman — COMMENTED** [review]
Hi Kyle,
To answer your questions:

 > I set the accept self-signed certificate as mentioned. Do I need to install this certificate on my local machine?

No, it looks like the certificate is being handled OK by BrowserStack, according to your screenshot.

> I get the following when I try and login:

Those errors are being the Angular Dev Server `ng serve` is not using the Secure Certificate. I don't think this is an issue, as if you were to run `ng serve` and specify a secure certificate, the frontend would fail to load, as `dotnet` would not be able to communicate with the Angular Development Server. I would just ignore these errors.

> I was able to get logged in. So I'm wondering if it was just a blip with communication between SF and Auth0. 

Highly likely, given the issues we have bene having.

> However, I did get the following error dialog when I selected a project:

That looks like a bug occurring with the `@sillsdev/machine` library. Can you create this on your local Chrome? Does this occur for a specific chapter/book? It maybe an iOS bug for a specific scenario in the editor.

> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/2840#-:-OB1_OKl307r1TIbXPTx:bhz628g)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @pmachapman)

**Review by kylebuss — APPROVED** [review]
The error dialog is not reproducing. I am marking this approved!

> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/2840#-:-OB277l664WBh1cgPL2T:b1ojhvv)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @pmachapman)

**Pull request merged**
