### PR TITLE
Disable End Reference on load in Answer panel

### PR DESCRIPTION
**Pull request by jasonleenaylor**
* Fix in this area for the problem reported in SF-556

---
This change is [Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/309)

### CODE REVIEW

**Comment by jasonleenaylor** [comment]
___
*[src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking.component.spec.ts, line 65 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/309#-LpiO24o9IFmINLq6uZI:-LpiOu2C7jQZgYBsvS7_:b-896lm1) ([raw file](https://github.com/sillsdev/web-xforge/blob/5705d90f2a27955504f9e5b411a3d217a82b6ac7/src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking.component.spec.ts#L65)):*
<details><summary><i>Previously, RaymondLuong3 (Raymond Luong) wrote…</i></summary><blockquote>

> ```
> fdescribe('CheckingComponent', () => {
> ```
Remove the f in `fdescribe`
</blockquote></details>

Doh!

**Comment by jasonleenaylor** [comment]
Comments addressed.

**Comment by jasonleenaylor** [comment]
___
*[src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking.component.spec.ts, line 427 at r2](https://reviewable.io/reviews/sillsdev/web-xforge/309#-LpiQ3XJAaHHoUX51QU1:-LpiVF8zCJhzM4ZsTYhz:b-896fix) ([raw file](https://github.com/sillsdev/web-xforge/blob/286cb7d74d6b1d2e1221f7214df6edddbfc9be7c/src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking.component.spec.ts#L427)):*
<details><summary><i>Previously, RaymondLuong3 (Raymond Luong) wrote…</i></summary><blockquote>

> ```
>       expect(env.component.answersPanel.answerForm.hasError('startReferenceRequired'));
>       env.setTextFieldValue(env.scriptureEndField, '');
>       expect(env.component.answersPanel.answerForm.valid).toBe(true);
> ```
This can also be removed, including the comment above. I would have expected this to cause a text failure.
</blockquote></details>

Done.

**Comment by jasonleenaylor** [comment]
New comment addressed.

**Comment by Nateowami** [comment]
@RaymondLuong3 It enables it fine on my machine, in Firefox.

It appears this also fixes [SF-535](https://jira.sil.org/browse/SF-535), "Scripture text does not appear immediately for a valid reference". @jasonleenaylor You may want to pick up that card as well. However, it raises another issue: Typing "Mat 1:1" when looking at Hebrews, it automatically inserts the text for Heb 1:1.

**Pull request merged**
