### PR TITLE
SF-2718 Add button to run webhook manually

### PR DESCRIPTION
**Pull request by pmachapman**
This PR adds a button to the Serval Administration area to run the webhook which updates the `hasDraft` property of the project's chapters.

This enables either re-running of the webhook on Production/QA, or executing the webhook for Developer machines.

- - -
This change is [Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/2438)

### CODE REVIEW

**Comment by Nateowami** [comment]
I haven't reviewed this, but I tested it, and it works.

**Review by Nateowami — APPROVED** [review]
> Reviewed 8 of 8 files at r1, 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/2438)* status: all files reviewed, 2 unresolved discussions (waiting on @pmachapman)

___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/serval-administration/serval-project.component.scss` line 10 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/2438#-NxFJtFo2xo9OQLpSuEV:-NxFJtFp0FTbllzBgbOh:b-ddp9c5) ([raw file](https://github.com/sillsdev/web-xforge/blob/01e5b2f56189a7319dfe9fef683e54f507f38bfa/src/SIL.XForge.Scripture/ClientApp/src/app/serval-administration/serval-project.component.scss#L10)):*
> ```SCSS
>     flex-direction: row;
>     &:not(:last-child) {
>       padding-bottom: 16px;
> ```

Why are we adding padding on the bottom in addition to the row gap? Why not change the `row-gap` to `32px`, and remove the padding-bottom?
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/serval-administration/serval-project.component.spec.ts` line 160 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/2438#-NxFLX4s0NOf12pe6xfI:-NxFLX4t0kuIYoVlnpa0:b-bh6ljh) ([raw file](https://github.com/sillsdev/web-xforge/blob/01e5b2f56189a7319dfe9fef683e54f507f38bfa/src/SIL.XForge.Scripture/ClientApp/src/app/serval-administration/serval-project.component.spec.ts#L160)):*
> ```XML
> 
>     get runWebhookButton(): HTMLInputElement {
>       return this.fixture.nativeElement.querySelector('button#run-webhook');
> ```

Generally I think it's best to make selectors specific, but not more specific than is useful. IDs are supposed to be unique (they're being misused if they're not), so `#run-webhook` should be specific enough. Years ago when refactoring some Language Forge components I  had to fix a ton of tests that had selectors like `div > #some-element` <sup>1</sup>. The HTML tag `div` has no semantic meaning, so the selectors were more specific than necessary, and once the template changed, the tests were broken because they were more tightly coupled than necessary. Buttons don't have to be implemented using the `button` tag (the `a` tag is a common alternative). Generally if you have an ID, just using that ID is ideal because it means you can completely change the implementation, and as long as the ID is kept the tests will still work exactly as before.

<sup>1 I'm not sure it was actually as extreme as this example selector, I just remember that it was needlessly specific.</sup>

**Review by pmachapman — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/2438)* status: 6 of 9 files reviewed, all discussions resolved (waiting on @Nateowami)

___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/serval-administration/serval-project.component.scss` line 10 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/2438#-NxFJtFo2xo9OQLpSuEV:-NxFTZTdEhQw5IK7-qqt:b-xyns1c) ([raw file](https://github.com/sillsdev/web-xforge/blob/01e5b2f56189a7319dfe9fef683e54f507f38bfa/src/SIL.XForge.Scripture/ClientApp/src/app/serval-administration/serval-project.component.scss#L10)):*
<details><summary><i>Previously, Nateowami (Nathaniel Paulus) wrote…</i></summary><blockquote>

Why are we adding padding on the bottom in addition to the row gap? Why not change the `row-gap` to `32px`, and remove the padding-bottom?
</blockquote></details>

Done. Fixed - thank you!
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/serval-administration/serval-project.component.spec.ts` line 160 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/2438#-NxFLX4s0NOf12pe6xfI:-NxFTacX5U-EsWsq7I6V:b-ydonir) ([raw file](https://github.com/sillsdev/web-xforge/blob/01e5b2f56189a7319dfe9fef683e54f507f38bfa/src/SIL.XForge.Scripture/ClientApp/src/app/serval-administration/serval-project.component.spec.ts#L160)):*
<details><summary><i>Previously, Nateowami (Nathaniel Paulus) wrote…</i></summary><blockquote>

Generally I think it's best to make selectors specific, but not more specific than is useful. IDs are supposed to be unique (they're being misused if they're not), so `#run-webhook` should be specific enough. Years ago when refactoring some Language Forge components I  had to fix a ton of tests that had selectors like `div > #some-element` <sup>1</sup>. The HTML tag `div` has no semantic meaning, so the selectors were more specific than necessary, and once the template changed, the tests were broken because they were more tightly coupled than necessary. Buttons don't have to be implemented using the `button` tag (the `a` tag is a common alternative). Generally if you have an ID, just using that ID is ideal because it means you can completely change the implementation, and as long as the ID is kept the tests will still work exactly as before.

<sup>1 I'm not sure it was actually as extreme as this example selector, I just remember that it was needlessly specific.</sup>
</blockquote></details>

Done. Good idea.

**Review by Nateowami — APPROVED** [review]
> Reviewed 4 of 4 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/2438)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @pmachapman)

**Pull request merged**
