### PR TITLE
PtdaSyncAll: Skip failed PT book fetch if unneeded

### PR DESCRIPTION
**Pull request by marksvc**
- 5 projects failed to sync during migration stage 1 when they got a
500 Internal Server Error fetching a book from PTDA. But in one or
more of these cases, there were no text changes in SF anyway, and so
in that situation we can skip fetching the book in stage 1 and get it
from migration stage 2.

**Note that this PR is targetting branch `sync-all-build`, which is where the PtdaSyncAll stage1 migrator tool gets built from.**

---
This change is [Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/808)

### CODE REVIEW

**Review by jasonleenaylor — APPROVED** [review]
:LGTM: One quick observation. I noticed that you return null *before* calling UpdateProgress.  I didn't go read what UpdateProgress does so I don't know if that was intentional.

> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/808#-:-MHXsicU8rFtdhoilnx4:b-6byabp)* status: 0 of 1 files reviewed, all discussions resolved

**Review by jasonleenaylor — APPROVED** [review]
> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/808)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by RaymondLuong3 — APPROVED** [review]
I looked, and technically we should call update progress. However, in the context of migration, there is no need.

> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/808#-:-MHXu9P7AI_ng-ZgYt0J:b-shhsgr)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by marksvc — COMMENTED** [review]
Thanks for examining. Thank you. I just had a look at UpdateProgress, and it looks like it won't be an issue for our migration situation. It updates PercentCompleted in the SF DB, which gets Unset anyway when a synchronization has been completed. Omitting the update to PercentCompleted will be fine. 

> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/808#-:-MHXudqg4ySCyPJML02_:by9vn9t)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
