### PR TITLE
SF-2288 Allow Selection of books on Serval for pre-translation

### PR DESCRIPTION
**Pull request by pmachapman**
This PR provides the backend support for the interface created in #2120.

It allows the front end to specify training books to the backend, sends these to Serval, and stores them so the front end can pre-select the previously selected books.

- - -
This change is [Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/2129)

### CODE REVIEW

**Review by siltomato — CHANGES_REQUESTED** [review]
Looks great.  I just have a few suggestions below.

> Reviewed 10 of 15 files at r1, 18 of 18 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/2129#-:-NiIaajICn503xtu_Lg-:bws4o0y)* status: all files reviewed, 11 unresolved discussions (waiting on @pmachapman)

___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-generation.ts` line 9 at r2](https://reviewable.io/reviews/sillsdev/web-xforge/2129#-NiIOeTf6IAuxUKoixms:-NiIOeTf6IAuxUKoixmt:b-8e6hi7) ([raw file](https://github.com/sillsdev/web-xforge/blob/2bb25a550bc9064c3a8d3e030a0f90cc8c89e5b5/src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-generation.ts#L9)):*
> ```XML
> export interface BuildConfig {
>   projectId: string;
>   sourceBooks: number[];
> ```

Would `trainingBooks` be more descriptive?
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-generation.component.ts` line 43 at r2](https://reviewable.io/reviews/sillsdev/web-xforge/2129#-NiINwtUD6gobpGuBz5K:-NiINwtUD6gobpGuBz5L:b-ebkcot) ([raw file](https://github.com/sillsdev/web-xforge/blob/2bb25a550bc9064c3a8d3e030a0f90cc8c89e5b5/src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-generation.component.ts#L43)):*
> ```XML
> export class DraftGenerationComponent extends SubscriptionDisposable implements OnInit {
>   @ViewChild(MatTabGroup) tabGroup?: MatTabGroup;
>   @ViewChild(DraftGenerationStepsComponent) draftGenerationSteps?: DraftGenerationStepsComponent;
> ```

Not needed... see below.
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-generation.component.ts` line 216 at r2](https://reviewable.io/reviews/sillsdev/web-xforge/2129#-NiIMqd17n_OKGSYbRXS:-NiIMqd17n_OKGSYbRXT:bgxi66z) ([raw file](https://github.com/sillsdev/web-xforge/blob/2bb25a550bc9064c3a8d3e030a0f90cc8c89e5b5/src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-generation.component.ts#L216)):*
> ```XML
> 
>     // TODO: Send selected books to the back-end
>     this.startBuild();
> ```

I think it would be better to pass the books from the event rather than getting them from the stepper component directly.
```ts
this.startBuild(result.books);
```
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-generation.component.ts` line 268 at r2](https://reviewable.io/reviews/sillsdev/web-xforge/2129#-NiIO1FlD89TnudjiGVN:-NiIO1FlD89TnudjiGVO:b52q5un) ([raw file](https://github.com/sillsdev/web-xforge/blob/2bb25a550bc9064c3a8d3e030a0f90cc8c89e5b5/src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-generation.component.ts#L268)):*
> ```XML
>   }
> 
>   startBuild(): void {
> ```

```ts
startBuild(trainingBooks: number[]): void {
```
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-generation.component.ts` line 274 at r2](https://reviewable.io/reviews/sillsdev/web-xforge/2129#-NiIOE_zAiocv1YnzKtJ:-NiIOE_zAiocv1YnzKtK:bsyxkxt) ([raw file](https://github.com/sillsdev/web-xforge/blob/2bb25a550bc9064c3a8d3e030a0f90cc8c89e5b5/src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-generation.component.ts#L274)):*
> ```XML
>         .startBuildOrGetActiveBuild({
>           projectId: this.activatedProject.projectId!,
>           sourceBooks: this.draftGenerationSteps?.selectedBooks ?? []
> ```

```ts
sourceBooks: trainingBooks
```
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-generation-steps/draft-generation-steps.component.ts` line 53 at r2](https://reviewable.io/reviews/sillsdev/web-xforge/2129#-NiIAv-j5TsDzMXYJohn:-NiIAv-kAh2SLZk--_fL:bjzu6c6) ([raw file](https://github.com/sillsdev/web-xforge/blob/2bb25a550bc9064c3a8d3e030a0f90cc8c89e5b5/src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-generation-steps/draft-generation-steps.component.ts#L53)):*
> ```XML
> 
>         // The intersection is all of the available books in the source project that match the target's previous books
>         const intersection = availableBooks.filter(bookNum => previousBooks.includes(bookNum));
> ```

Should we do an intersection for the available books also to limit them to books that are in the target project?  If so, maybe something like this could work?
```ts
ngOnInit(): void {
  this.availableBooks$ = this.activatedProject.projectDoc$.pipe(
    // Build available book list from source project
    switchMap(targetProjectDoc => {
      // See if there is an alternate project set.  Otherwise, use the source project.
      const sourceProjectId: string | undefined =
        targetProjectDoc?.data?.translateConfig.draftConfig.alternateSource?.projectRef ??
        targetProjectDoc?.data?.translateConfig.source?.projectRef;

      if (sourceProjectId == null) {
        throw new Error('Source project is not set');
      }

      return this.projectService.getProfile(sourceProjectId);
    }),
    map(sourceProjectDoc => {
      const availableSourceBooks = new Set<number>(sourceProjectDoc?.data?.texts.map(t => t.bookNum) ?? []);

      // Create list of available books that is intersection of source and target projects books
      return (
        this.activatedProject.projectDoc?.data?.texts
          ?.filter(text => availableSourceBooks.has(text.bookNum))
          ?.map(text => text.bookNum) ?? []
      );
    }),
    tap((availableBooks: number[]) => {
      // Get the previously selected training books from the target project
      const previousBooks: Set<number> = new Set<number>(
        this.activatedProject.projectDoc?.data?.translateConfig.draftConfig.lastSelectedBooks ?? []
      );

      // Create list of selected books that is intersection of available books and previously selected books
      const intersection = availableBooks.filter(bookNum => previousBooks.has(bookNum));

      // Set the selected books to the intersection if not empty.  Otherwise, set it to all available books.
      this.selectedBooks = intersection.length > 0 ? intersection : availableBooks;
    })
  );
}
```
___
*[`src/SIL.XForge.Scripture/Services/BuildConfigJsonConverter.cs` line 29 at r2](https://reviewable.io/reviews/sillsdev/web-xforge/2129#-NiIUM8w1VKgeswguotU:-NiIUM8w1VKgeswguotV:b-h285dr) ([raw file](https://github.com/sillsdev/web-xforge/blob/2bb25a550bc9064c3a8d3e030a0f90cc8c89e5b5/src/SIL.XForge.Scripture/Services/BuildConfigJsonConverter.cs#L29)):*
> ```Smalltalk
>         if (value.SourceBooks.Count > 0)
>         {
>             writer.WritePropertyName("SourceBooks");
> ```

You can use `nameof` to avoid hard-coding the property name:
```cs
writer.WritePropertyName(nameof(value.SourceBooks));
```
___
*[`src/SIL.XForge.Scripture/Services/BuildConfigJsonConverter.cs` line 33 at r2](https://reviewable.io/reviews/sillsdev/web-xforge/2129#-NiIUmvZDRRuB3aMNCrB:-NiIUmvZDRRuB3aMNCrC:b-augwb4) ([raw file](https://github.com/sillsdev/web-xforge/blob/2bb25a550bc9064c3a8d3e030a0f90cc8c89e5b5/src/SIL.XForge.Scripture/Services/BuildConfigJsonConverter.cs#L33)):*
> ```Smalltalk
>         }
> 
>         writer.WritePropertyName("ProjectId");
> ```

Also `nameof` here.
___
*[`src/SIL.XForge.Scripture/Services/BuildConfigJsonConverter.cs` line 48 at r2](https://reviewable.io/reviews/sillsdev/web-xforge/2129#-NiI_mhcCXiDUy5hLwsq:-NiI_mhcCXiDUy5hLwsr:b-dyjvgf) ([raw file](https://github.com/sillsdev/web-xforge/blob/2bb25a550bc9064c3a8d3e030a0f90cc8c89e5b5/src/SIL.XForge.Scripture/Services/BuildConfigJsonConverter.cs#L48)):*
> ```Smalltalk
>     )
>     {
>         // If we were just passed a json string, this will be the project id
> ```

Cool idea to make it backward compatible!

**Review by pmachapman — COMMENTED** [review]
> Dismissed @github-advanced-security[bot] from 2 discussions.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/2129)* status: 16 of 28 files reviewed, 8 unresolved discussions (waiting on @siltomato)

___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-generation.ts` line 9 at r2](https://reviewable.io/reviews/sillsdev/web-xforge/2129#-NiIOeTf6IAuxUKoixms:-NiVseHtEu57HPn3-Zhg:b-32mi04) ([raw file](https://github.com/sillsdev/web-xforge/blob/2bb25a550bc9064c3a8d3e030a0f90cc8c89e5b5/src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-generation.ts#L9)):*
<details><summary><i>Previously, siltomato wrote…</i></summary><blockquote>

Would `trainingBooks` be more descriptive?
</blockquote></details>

Yes. Good idea. I think it will reduce confusion with source books used elsewhere. Thanks!
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-generation.component.ts` line 43 at r2](https://reviewable.io/reviews/sillsdev/web-xforge/2129#-NiINwtUD6gobpGuBz5K:-NiVuZdM9Binr8WzSNpY:b-896fix) ([raw file](https://github.com/sillsdev/web-xforge/blob/2bb25a550bc9064c3a8d3e030a0f90cc8c89e5b5/src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-generation.component.ts#L43)):*
<details><summary><i>Previously, siltomato wrote…</i></summary><blockquote>

Not needed... see below.
</blockquote></details>

Done.
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-generation.component.ts` line 216 at r2](https://reviewable.io/reviews/sillsdev/web-xforge/2129#-NiIMqd17n_OKGSYbRXS:-NiVuHYD4GzqLgqaAC59:bwgue8l) ([raw file](https://github.com/sillsdev/web-xforge/blob/2bb25a550bc9064c3a8d3e030a0f90cc8c89e5b5/src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-generation.component.ts#L216)):*
<details><summary><i>Previously, siltomato wrote…</i></summary><blockquote>

I think it would be better to pass the books from the event rather than getting them from the stepper component directly.
```ts
this.startBuild(result.books);
```
</blockquote></details>

Done. Thank you! I don't know why I couldn't see that!
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-generation.component.ts` line 268 at r2](https://reviewable.io/reviews/sillsdev/web-xforge/2129#-NiIO1FlD89TnudjiGVN:-NiVubi_558NaWtFSLiF:b-896fix) ([raw file](https://github.com/sillsdev/web-xforge/blob/2bb25a550bc9064c3a8d3e030a0f90cc8c89e5b5/src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-generation.component.ts#L268)):*
<details><summary><i>Previously, siltomato wrote…</i></summary><blockquote>

```ts
startBuild(trainingBooks: number[]): void {
```
</blockquote></details>

Done.
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-generation.component.ts` line 274 at r2](https://reviewable.io/reviews/sillsdev/web-xforge/2129#-NiIOE_zAiocv1YnzKtJ:-NiVueQC9zapAoPHwmaF:b-896fix) ([raw file](https://github.com/sillsdev/web-xforge/blob/2bb25a550bc9064c3a8d3e030a0f90cc8c89e5b5/src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-generation.component.ts#L274)):*
<details><summary><i>Previously, siltomato wrote…</i></summary><blockquote>

```ts
sourceBooks: trainingBooks
```
</blockquote></details>

Done.
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-generation-steps/draft-generation-steps.component.ts` line 53 at r2](https://reviewable.io/reviews/sillsdev/web-xforge/2129#-NiIAv-j5TsDzMXYJohn:-NiVw7K-2ROhMPSJdABe:b-cnesg2) ([raw file](https://github.com/sillsdev/web-xforge/blob/2bb25a550bc9064c3a8d3e030a0f90cc8c89e5b5/src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-generation-steps/draft-generation-steps.component.ts#L53)):*
<details><summary><i>Previously, siltomato wrote…</i></summary><blockquote>

Should we do an intersection for the available books also to limit them to books that are in the target project?  If so, maybe something like this could work?
```ts
ngOnInit(): void {
  this.availableBooks$ = this.activatedProject.projectDoc$.pipe(
    // Build available book list from source project
    switchMap(targetProjectDoc => {
      // See if there is an alternate project set.  Otherwise, use the source project.
      const sourceProjectId: string | undefined =
        targetProjectDoc?.data?.translateConfig.draftConfig.alternateSource?.projectRef ??
        targetProjectDoc?.data?.translateConfig.source?.projectRef;

      if (sourceProjectId == null) {
        throw new Error('Source project is not set');
      }

      return this.projectService.getProfile(sourceProjectId);
    }),
    map(sourceProjectDoc => {
      const availableSourceBooks = new Set<number>(sourceProjectDoc?.data?.texts.map(t => t.bookNum) ?? []);

      // Create list of available books that is intersection of source and target projects books
      return (
        this.activatedProject.projectDoc?.data?.texts
          ?.filter(text => availableSourceBooks.has(text.bookNum))
          ?.map(text => text.bookNum) ?? []
      );
    }),
    tap((availableBooks: number[]) => {
      // Get the previously selected training books from the target project
      const previousBooks: Set<number> = new Set<number>(
        this.activatedProject.projectDoc?.data?.translateConfig.draftConfig.lastSelectedBooks ?? []
      );

      // Create list of selected books that is intersection of available books and previously selected books
      const intersection = availableBooks.filter(bookNum => previousBooks.has(bookNum));

      // Set the selected books to the intersection if not empty.  Otherwise, set it to all available books.
      this.selectedBooks = intersection.length > 0 ? intersection : availableBooks;
    })
  );
}
```
</blockquote></details>

I don't think this will help the draft generation, as there are cases where source books not in the target will want to be sent to improve training data (this will occur for MT more than BT). I think it is best to allow the user to send them, and if Serval can't use a source (because it won't be in the target and it needs it there for some reason), then it will just ignore them (i.e. we push the decision to Serval rather than make it ourselves).

I have optimized the `switchMap` based on your example - I had written it long form thinking it was clearer, but your optimization is clear too.

I am curious - why did you choose a `Set` over an array in your `tap` example? I would have thought an array was faster and we don't need the unique functionality of a set as it is used as a query input rather than output?
___
*[`src/SIL.XForge.Scripture/Services/BuildConfigJsonConverter.cs` line 29 at r2](https://reviewable.io/reviews/sillsdev/web-xforge/2129#-NiIUM8w1VKgeswguotU:-NiVv0r88nNe1zWs9Nb-:bqaho0d) ([raw file](https://github.com/sillsdev/web-xforge/blob/2bb25a550bc9064c3a8d3e030a0f90cc8c89e5b5/src/SIL.XForge.Scripture/Services/BuildConfigJsonConverter.cs#L29)):*
<details><summary><i>Previously, siltomato wrote…</i></summary><blockquote>

You can use `nameof` to avoid hard-coding the property name:
```cs
writer.WritePropertyName(nameof(value.SourceBooks));
```
</blockquote></details>

Done. Great idea. Thank you!
___
*[`src/SIL.XForge.Scripture/Services/BuildConfigJsonConverter.cs` line 33 at r2](https://reviewable.io/reviews/sillsdev/web-xforge/2129#-NiIUmvZDRRuB3aMNCrB:-NiVv2gG2mxAvSdL-lOO:b-896fix) ([raw file](https://github.com/sillsdev/web-xforge/blob/2bb25a550bc9064c3a8d3e030a0f90cc8c89e5b5/src/SIL.XForge.Scripture/Services/BuildConfigJsonConverter.cs#L33)):*
<details><summary><i>Previously, siltomato wrote…</i></summary><blockquote>

Also `nameof` here.
</blockquote></details>

Done.

**Review by siltomato — CHANGES_REQUESTED** [review]
> Reviewed 13 of 13 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/2129)* status: all files reviewed, 2 unresolved discussions (waiting on @pmachapman)

___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-generation.component.ts` line 208 at r3](https://reviewable.io/reviews/sillsdev/web-xforge/2129#-NiWXwRy5wujMAb1WLr9:-NiWXwRy5wujMAb1WLrA:b71xcmq) ([raw file](https://github.com/sillsdev/web-xforge/blob/0016ebdfbefd43ac24a6868309141028e5eed5b4/src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-generation.component.ts#L208)):*
> ```XML
>   }
> 
>   onPreGenerationStepsComplete(_result: DraftGenerationStepsResult): void {
> ```

I had prefixed the parameter name with underscore to satisfy the linter, but now that we're actually using the parameter, we should probably remove the underscore.
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-generation-steps/draft-generation-steps.component.ts` line 53 at r2](https://reviewable.io/reviews/sillsdev/web-xforge/2129#-NiIAv-j5TsDzMXYJohn:-NiWZbOj27ZSzmk5k8yq:bo14gcb) ([raw file](https://github.com/sillsdev/web-xforge/blob/2bb25a550bc9064c3a8d3e030a0f90cc8c89e5b5/src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-generation-steps/draft-generation-steps.component.ts#L53)):*
<details><summary><i>Previously, pmachapman (Peter Chapman) wrote…</i></summary><blockquote>

I don't think this will help the draft generation, as there are cases where source books not in the target will want to be sent to improve training data (this will occur for MT more than BT). I think it is best to allow the user to send them, and if Serval can't use a source (because it won't be in the target and it needs it there for some reason), then it will just ignore them (i.e. we push the decision to Serval rather than make it ourselves).

I have optimized the `switchMap` based on your example - I had written it long form thinking it was clearer, but your optimization is clear too.

I am curious - why did you choose a `Set` over an array in your `tap` example? I would have thought an array was faster and we don't need the unique functionality of a set as it is used as a query input rather than output?
</blockquote></details>

Ok, thanks for that explanation.  That makes sense.

As for `Set`, my understanding is that `Set.has()` is `O(1)`, so that would make the set initialization + intersection `O(n+m)` (iterate `previousBooks` once to initialize the Set, and then iterate `availableBooks` once to filter).  Without using `Set`, it would be `O(n*m)`, as `previousBooks.includes()` causes a nested loop for each book in the filter function.

For this small dataset of books, this isn't a big deal, but I figured that it didn't add much code complexity.  I'm ok with either way.

**Review by pmachapman — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/2129)* status: all files reviewed, 1 unresolved discussion (waiting on @siltomato)

___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-generation.component.ts` line 208 at r3](https://reviewable.io/reviews/sillsdev/web-xforge/2129#-NiWXwRy5wujMAb1WLr9:-NiWjO2KATi9i3PsXtcw:b-896fix) ([raw file](https://github.com/sillsdev/web-xforge/blob/0016ebdfbefd43ac24a6868309141028e5eed5b4/src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-generation.component.ts#L208)):*
<details><summary><i>Previously, siltomato wrote…</i></summary><blockquote>

I had prefixed the parameter name with underscore to satisfy the linter, but now that we're actually using the parameter, we should probably remove the underscore.
</blockquote></details>

Done.
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-generation-steps/draft-generation-steps.component.ts` line 53 at r2](https://reviewable.io/reviews/sillsdev/web-xforge/2129#-NiIAv-j5TsDzMXYJohn:-NiWkPSr5Q8Q3_9kHhtA:b-ce32ns) ([raw file](https://github.com/sillsdev/web-xforge/blob/2bb25a550bc9064c3a8d3e030a0f90cc8c89e5b5/src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-generation-steps/draft-generation-steps.component.ts#L53)):*
<details><summary><i>Previously, siltomato wrote…</i></summary><blockquote>

Ok, thanks for that explanation.  That makes sense.

As for `Set`, my understanding is that `Set.has()` is `O(1)`, so that would make the set initialization + intersection `O(n+m)` (iterate `previousBooks` once to initialize the Set, and then iterate `availableBooks` once to filter).  Without using `Set`, it would be `O(n*m)`, as `previousBooks.includes()` causes a nested loop for each book in the filter function.

For this small dataset of books, this isn't a big deal, but I figured that it didn't add much code complexity.  I'm ok with either way.
</blockquote></details>

Done. Thanks! I have changed it to Set.

**Review by siltomato — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/2129#-:-NiWm-42E79g6GcEAqPP:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @pmachapman)

**Pull request merged**
