### PR TITLE
Allow silent cloning mode for clone all migration tool

### PR DESCRIPTION
**Pull request by RaymondLuong3**
This allows us to run a silent clone of the projects, and then deletes the cloned repositories without persisting anything to the SF mongo database.

---
This change is [Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/796)

### CODE REVIEW

**Comment by marksvc** [comment]
___
*[src/Migrations/PTDDCloneAll/PTDDSyncRunner.cs, line 93 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/796#-MGjfhuA3nZQtr0BuV_T:-MGjfhuA3nZQtr0BuV_U:b-1r30jb) ([raw file](https://github.com/sillsdev/web-xforge/blob/86822b6fa30ec4de750c8f4781d5ac660a16313f/src/Migrations/PTDDCloneAll/PTDDSyncRunner.cs#L93)):*
> ```Smalltalk
>                 if (!await InitAsync(projectId, userId))
>                 {
>                     await CompleteSync(false);
> ```

We should probably not do CompleteSync() here either, if `silent`.

**Comment by marksvc** [comment]
___
*[src/Migrations/PTDDCloneAll/Program.cs, line 141 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/796#-MGjgyvA-Xd9f8FnD5Or:-MGjgyvA-Xd9f8FnD5Os:b2s5re4) ([raw file](https://github.com/sillsdev/web-xforge/blob/86822b6fa30ec4de750c8f4781d5ac660a16313f/src/Migrations/PTDDCloneAll/Program.cs#L141)):*
> ```Smalltalk
>         {
>             Log($"Cloning {proj.Name} ({proj.Id}) as SF user {userId}");
>             string partialCloneDir = Path.Combine(syncDir, proj.ParatextId);
> ```

I think after this line, it should check if the directory already exists. And if it exists (and if `silent`), then stop the operation and don't proceed with this project. 
Because the project might have already been cloned, and then we're doing a more-real S/R with the PT server. And we also wouldn't want to delete the directory afterward in the case either.

**Review by marksvc — COMMENTED** [review]
> Reviewed 2 of 2 files at r1, 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/796)* status: all files reviewed, 1 unresolved discussion (waiting on @RaymondLuong3)

___
*[src/Migrations/PTDDCloneAll/PTDDSyncRunner.cs, line 93 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/796#-MGjfhuA3nZQtr0BuV_T:-MGjjrgX9MRsJWE0if_V:bb6un1j) ([raw file](https://github.com/sillsdev/web-xforge/blob/86822b6fa30ec4de750c8f4781d5ac660a16313f/src/Migrations/PTDDCloneAll/PTDDSyncRunner.cs#L93)):*
<details><summary><i>Previously, marksvc wrote…</i></summary><blockquote>

We should probably not do CompleteSync() here either, if `silent`.
</blockquote></details>

Done

**Review by marksvc — COMMENTED** [review]
I approve, minus remaining comment. Tho the importance/urgency of that is debatable.

> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/796#-:-MGjk8qm7gf6ABZtmcBP:btkxqvu)* status: all files reviewed, 1 unresolved discussion (waiting on @RaymondLuong3)

**Review by RaymondLuong3 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/796)* status: 1 of 2 files reviewed, 1 unresolved discussion (waiting on @marksvc)

___
*[src/Migrations/PTDDCloneAll/Program.cs, line 141 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/796#-MGjgyvA-Xd9f8FnD5Or:-MGjm_CX-YYzitgxVibg:b-3l0pxr) ([raw file](https://github.com/sillsdev/web-xforge/blob/86822b6fa30ec4de750c8f4781d5ac660a16313f/src/Migrations/PTDDCloneAll/Program.cs#L141)):*
<details><summary><i>Previously, marksvc wrote…</i></summary><blockquote>

I think after this line, it should check if the directory already exists. And if it exists (and if `silent`), then stop the operation and don't proceed with this project. 
Because the project might have already been cloned, and then we're doing a more-real S/R with the PT server. And we also wouldn't want to delete the directory afterward in the case either. 
</blockquote></details>

Good thinking. I've made those changes. That will allow us to run the migration tool multiple times, and only cloning projects that have not succeeded.

**Review by marksvc — APPROVED** [review]
> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/796)* status: :shipit: complete! all files reviewed, all discussions resolved

___
*[src/Migrations/PTDDCloneAll/Program.cs, line 141 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/796#-MGjgyvA-Xd9f8FnD5Or:-MGjn9lnBNRLkNMgfrPA:bb6un1j) ([raw file](https://github.com/sillsdev/web-xforge/blob/86822b6fa30ec4de750c8f4781d5ac660a16313f/src/Migrations/PTDDCloneAll/Program.cs#L141)):*
<details><summary><i>Previously, RaymondLuong3 (Raymond Luong) wrote…</i></summary><blockquote>

Good thinking. I've made those changes. That will allow us to run the migration tool multiple times, and only cloning projects that have not succeeded.
</blockquote></details>

Done

**Pull request merged**
