### PR TITLE
SF-1760 Allow auth0 account users to edit name while online

### PR DESCRIPTION
**Pull request by RaymondLuong3**
* detect if user is online before opening dialog
* show message if user is offline
* convert edit name dialog to angular material
* add scss style to edit name dialog
* do not show name confirmation dialog when user is offline

Before
image

After
image

- - -
This change is [Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1532)

### CODE REVIEW

**Review by nigel-wells — CHANGES_REQUESTED** [review]
I do love how much cleaner the material dialog is from the old MDC one. 

> Reviewed 11 of 11 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1532#-:-NE8xiAq8KGPaG2TISw4:b-l7252i)* status: all files reviewed, 4 unresolved discussions (waiting on @RaymondLuong3)

___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/app.component.ts` line 477 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/1532#-NE8tN-S3N9opebeaMDV:-NE8tN-S3N9opebeaMDW:b8aszio) ([raw file](https://github.com/sillsdev/web-xforge/blob/fa747230f8a78c552b132de7740f90c5d9cc306b/src/SIL.XForge.Scripture/ClientApp/src/app/app.component.ts#L477)):*
> ```XML
>       this.userService.editDisplayName(false);
>     } else {
>       this.noticeService.show(translate('app.action_not_available_offline'));
> ```

I wonder if instead of this we don't show the edit button or disable it? I know we typically disable buttons and show in-line messages but I think it would be ok in this instance to not have to show and translate another message.
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/app.component.spec.ts` line 643 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/1532#-NE8v17n0RdLhMKyEvFi:-NE8v17n0RdLhMKyEvFj:b-bvugvn) ([raw file](https://github.com/sillsdev/web-xforge/blob/fa747230f8a78c552b132de7740f90c5d9cc306b/src/SIL.XForge.Scripture/ClientApp/src/app/app.component.spec.ts#L643)):*
> ```XML
>     when(mockedPwaService.online).thenReturn(comesOnline);
>     when(mockedPwaService.onlineStatus).thenReturn(this.webSocketOnline$);
>     when(mockedPwaService.onlineBrowserStatus).thenReturn(this.browserOnline$);
> ```

Did moving these actually make a difference?



_Code quote:_
```XML
    when(mockedPwaService.isOnline).thenReturn(this.browserOnline$.getValue() && this.webSocketOnline$.getValue());
    when(mockedPwaService.isBrowserOnline).thenReturn(this.browserOnline$.getValue());
    when(mockedPwaService.online).thenReturn(comesOnline);
    when(mockedPwaService.onlineStatus).thenReturn(this.webSocketOnline$);
    when(mockedPwaService.onlineBrowserStatus).thenReturn(this.browserOnline$);
```
___
*[`src/SIL.XForge.Scripture/ClientApp/src/xforge-common/edit-name-dialog/edit-name-dialog.component.spec.ts` line 27 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/1532#-NE8wuKR2HFa9EPLeyOX:-NE8wuKR2HFa9EPLeyOY:b-d34xwz) ([raw file](https://github.com/sillsdev/web-xforge/blob/fa747230f8a78c552b132de7740f90c5d9cc306b/src/SIL.XForge.Scripture/ClientApp/src/xforge-common/edit-name-dialog/edit-name-dialog.component.spec.ts#L27)):*
> ```XML
>     expect(env.cancelButton).not.toBe(null);
>     env.submitButton.click();
>     tick();
> ```

Perhaps a method could be created for the submit button click and the `tick()` can be placed in there. That would save remembering in the future and also help keep the tests looking cleaner
___
*[`src/SIL.XForge.Scripture/ClientApp/src/xforge-common/edit-name-dialog/edit-name-dialog.component.spec.ts` line 147 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/1532#-NE8xTdK8yhV2chBEMne:-NE8xTdK8yhV2chBEMnf:bt5nd8z) ([raw file](https://github.com/sillsdev/web-xforge/blob/fa747230f8a78c552b132de7740f90c5d9cc306b/src/SIL.XForge.Scripture/ClientApp/src/xforge-common/edit-name-dialog/edit-name-dialog.component.spec.ts#L147)):*
> ```XML
> 
>   setTextFieldValue(element: HTMLElement, value: string) {
>     const inputElem = element as HTMLInputElement;
> ```

Can you not simply set  the `element` type as `HTMLInputElement` in the first place?

**Review by RaymondLuong3 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1532)* status: all files reviewed, 3 unresolved discussions (waiting on @nigel-wells)

___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/app.component.ts` line 477 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/1532#-NE8tN-S3N9opebeaMDV:-NEBxc4A2kASr-k0Yyoo:bzc9kbk) ([raw file](https://github.com/sillsdev/web-xforge/blob/fa747230f8a78c552b132de7740f90c5d9cc306b/src/SIL.XForge.Scripture/ClientApp/src/app/app.component.ts#L477)):*
<details><summary><i>Previously, nigel-wells (Nigel Wells) wrote…</i></summary><blockquote>

I wonder if instead of this we don't show the edit button or disable it? I know we typically disable buttons and show in-line messages but I think it would be ok in this instance to not have to show and translate another message.
</blockquote></details>

I thought about that too and wasn't sure which one was better. I've made your suggestion.
___
*[`src/SIL.XForge.Scripture/ClientApp/src/xforge-common/edit-name-dialog/edit-name-dialog.component.spec.ts` line 27 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/1532#-NE8wuKR2HFa9EPLeyOX:-NEBxXSdEuqE8eVxDNof:btyeq5o) ([raw file](https://github.com/sillsdev/web-xforge/blob/fa747230f8a78c552b132de7740f90c5d9cc306b/src/SIL.XForge.Scripture/ClientApp/src/xforge-common/edit-name-dialog/edit-name-dialog.component.spec.ts#L27)):*
<details><summary><i>Previously, nigel-wells (Nigel Wells) wrote…</i></summary><blockquote>

Perhaps a method could be created for the submit button click and the `tick()` can be placed in there. That would save remembering in the future and also help keep the tests looking cleaner
</blockquote></details>

Good thinking. Done.
___
*[`src/SIL.XForge.Scripture/ClientApp/src/xforge-common/edit-name-dialog/edit-name-dialog.component.spec.ts` line 147 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/1532#-NE8xTdK8yhV2chBEMne:-NEBx_8S5XFBn-6QyreP:bphiz22) ([raw file](https://github.com/sillsdev/web-xforge/blob/fa747230f8a78c552b132de7740f90c5d9cc306b/src/SIL.XForge.Scripture/ClientApp/src/xforge-common/edit-name-dialog/edit-name-dialog.component.spec.ts#L147)):*
<details><summary><i>Previously, nigel-wells (Nigel Wells) wrote…</i></summary><blockquote>

Can you not simply set  the `element` type as `HTMLInputElement` in the first place?
</blockquote></details>

Yes it can. Thanks.

**Review by nigel-wells — APPROVED** [review]
:lgtm:

> Reviewed 5 of 5 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1532#-:-NED70058I9D2gSZl0bO:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @RaymondLuong3)

**Review by nigel-wells — APPROVED** [review]
Did you want testing on this?

> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1532#-:-NED7DYa0U-cPecTSB1G:bnigk0p)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @RaymondLuong3)

**Comment by Nateowami** [comment]
Since we have an issue it's pretty simple to have it tested. Go ahead and mark it ready to test and move the card if you have time (I'm on mobile).

**Review by Nateowami — DISMISSED** [review]
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1532)* status: all files reviewed, 1 unresolved discussion (waiting on @RaymondLuong3)

___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/app.component.ts` line 477 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/1532#-NE8tN-S3N9opebeaMDV:-NEHePzYAC_1u0pTXPEI:b-pkn9oa) ([raw file](https://github.com/sillsdev/web-xforge/blob/fa747230f8a78c552b132de7740f90c5d9cc306b/src/SIL.XForge.Scripture/ClientApp/src/app/app.component.ts#L477)):*
<details><summary><i>Previously, RaymondLuong3 (Raymond Luong) wrote…</i></summary><blockquote>

I thought about that too and wasn't sure which one was better. I've made your suggestion.
</blockquote></details>

I think our practice has been to show every UI component and just disable those that can't be used offline, with a message stating why. So for example, here's the share dialog, which can be opened while offline:



This also avoids the loophole of "I can open the dialog while online, and then I lose my connection, and am now offline". Of course, no matter what there's always loopholes, because a user can lose their network connection at any moment without our UI being able to react first, but it's a smaller loophole.

I think our general strategy for this is as follows:
1. Disable (but don't hide) any input or button that can't be used offline, and tell the user it's unavailable.
2. If a network request fails, handle it gracefully, informing the user and retrying it in the background. There's some work that's been done on this, but it's far from complete. See `RetryingRequestService` and the places that use it. It's probably more suited to read operations (fetching data repeatedly until successful) than write operations (we don't want to keep trying to write the same thing over and over, at lest without thinking through potential consequences).

One of the advantages of this approach is that users won't be confused why a UI element that they either remember, or see in documentation, or have been told about by someone else isn't just gone.

**Comment by Nateowami** [comment]
@nigel-wells Would you have time to re-review this?

**Review by nigel-wells — CHANGES_REQUESTED** [review]
> Reviewed 12 of 12 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1532)* status: all files reviewed, 9 unresolved discussions (waiting on @RaymondLuong3)

___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/app.component.html` line 109 at r3](https://reviewable.io/reviews/sillsdev/web-xforge/1532#-NIiuWpv26fQmtfiJo60:-NIiuWpv26fQmtfiJo61:b-z15p8u) ([raw file](https://github.com/sillsdev/web-xforge/blob/c7190cf669a56c87322a7c81b0ce0f8bdf184f9d/src/SIL.XForge.Scripture/ClientApp/src/app/app.component.html#L109)):*
> ```HTML
>                     <strong class="user-menu-name">{{ currentUser.displayName }}</strong>
>                     <button
>                       *ngIf="hasAccountAuthType"
> ```

If someone signs up via SMS is their `AuthType` still `Account`?
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/app.component.spec.ts` line 434 at r3](https://reviewable.io/reviews/sillsdev/web-xforge/1532#-NIivm4i7mB34DEy46xI:-NIivm4i7mB34DEy46xJ:b-dtf78f) ([raw file](https://github.com/sillsdev/web-xforge/blob/c7190cf669a56c87322a7c81b0ce0f8bdf184f9d/src/SIL.XForge.Scripture/ClientApp/src/app/app.component.spec.ts#L434)):*
> ```XML
>   }));
> 
>   it('social users cannot edit name', fakeAsync(() => {
> ```

Perhaps change this to reflect non auth0 account users cannot edit as PT is included in this list but I first interpreted this as Google and Facebook. Still not sure where SMS fits in as per my other message.
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/app.component.spec.ts` line 544 at r3](https://reviewable.io/reviews/sillsdev/web-xforge/1532#-NIiw7rR8mgjHVE7XOqd:-NIiw7rR8mgjHVE7XOqe:bovo2i7) ([raw file](https://github.com/sillsdev/web-xforge/blob/c7190cf669a56c87322a7c81b0ce0f8bdf184f9d/src/SIL.XForge.Scripture/ClientApp/src/app/app.component.spec.ts#L544)):*
> ```XML
>     }));
> 
>     it('can edit name online', fakeAsync(() => {
> ```

As per other comment, clarify name to reflect Auth0 native accounts can edit the name
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking.component.spec.ts` line 654 at r3](https://reviewable.io/reviews/sillsdev/web-xforge/1532#-NIj7dKABrWEc_-cIgOS:-NIj7dKBA4ygKhBpXcnO:bjyk5sh) ([raw file](https://github.com/sillsdev/web-xforge/blob/c7190cf669a56c87322a7c81b0ce0f8bdf184f9d/src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking.component.spec.ts#L654)):*
> ```XML
>     }));
> 
>     it('does not open dialog if offline', fakeAsync(() => {
> ```

change to `does not open edit display name dialog if offline`
___
*[`src/SIL.XForge.Scripture/ClientApp/src/xforge-common/user.service.ts` line 127 at r3](https://reviewable.io/reviews/sillsdev/web-xforge/1532#-NIj8E873mTw1moeyRtD:-NIj8E873mTw1moeyRtE:b-i2n2bq) ([raw file](https://github.com/sillsdev/web-xforge/blob/c7190cf669a56c87322a7c81b0ce0f8bdf184f9d/src/SIL.XForge.Scripture/ClientApp/src/xforge-common/user.service.ts#L127)):*
> ```XML
>         await this.updateAvatarFromDisplayName();
>       } catch {
>         this.noticeService.showError(translate('error_messages.failed_to_update_avatar'));
> ```

I assume this is a temporary fallback until we fix the updating issue in the backend?
___
*[`src/SIL.XForge.Scripture/ClientApp/src/xforge-common/edit-name-dialog/edit-name-dialog.component.scss` line 2 at r3](https://reviewable.io/reviews/sillsdev/web-xforge/1532#-NIj8wqu5jRU-DHJr4Uq:-NIj8wqu5jRU-DHJr4Ur:b-e775ef) ([raw file](https://github.com/sillsdev/web-xforge/blob/c7190cf669a56c87322a7c81b0ce0f8bdf184f9d/src/SIL.XForge.Scripture/ClientApp/src/xforge-common/edit-name-dialog/edit-name-dialog.component.scss#L2)):*
> ```SCSS
> .mat-dialog-content {
>   width: 280px;
> ```

Any reason to not set the width when the dialog is opened instead of using CSS?
___
*[`src/SIL.XForge.Scripture/ClientApp/src/xforge-common/edit-name-dialog/edit-name-dialog.component.spec.ts` line 66 at r3](https://reviewable.io/reviews/sillsdev/web-xforge/1532#-NIj9yXM5hHfCHgH4_gQ:-NIj9yXM5hHfCHgH4_gR:b-7nscit) ([raw file](https://github.com/sillsdev/web-xforge/blob/c7190cf669a56c87322a7c81b0ce0f8bdf184f9d/src/SIL.XForge.Scripture/ClientApp/src/xforge-common/edit-name-dialog/edit-name-dialog.component.spec.ts#L66)):*
> ```XML
>     env.submitButton.click();
>     tick();
>     env.fixture.detectChanges();
> ```

Should these be replaced with `wait()`? And below



_Code quote:_
```XML
    tick();
    env.fixture.detectChanges();
```
___
*[`src/SIL.XForge.Scripture/ClientApp/src/xforge-common/edit-name-dialog/edit-name-dialog.component.spec.ts` line 159 at r3](https://reviewable.io/reviews/sillsdev/web-xforge/1532#-NIjAKFc30rxSkxpYv_q:-NIjAKFc30rxSkxpYv_r:bp1hl1c) ([raw file](https://github.com/sillsdev/web-xforge/blob/c7190cf669a56c87322a7c81b0ce0f8bdf184f9d/src/SIL.XForge.Scripture/ClientApp/src/xforge-common/edit-name-dialog/edit-name-dialog.component.spec.ts#L159)):*
> ```XML
>     this.onlineStatus$.next(value);
>     tick();
>     this.fixture.detectChanges();
> ```

Change to `this.wait()`



_Code quote:_
```XML
    tick();
    this.fixture.detectChanges();
```

**Review by RaymondLuong3 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1532)* status: all files reviewed, 9 unresolved discussions (waiting on @Nateowami and @nigel-wells)

___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/app.component.html` line 109 at r3](https://reviewable.io/reviews/sillsdev/web-xforge/1532#-NIiuWpv26fQmtfiJo60:-NJ6virS6ByUGGrnvwko:befuuqy) ([raw file](https://github.com/sillsdev/web-xforge/blob/c7190cf669a56c87322a7c81b0ce0f8bdf184f9d/src/SIL.XForge.Scripture/ClientApp/src/app/app.component.html#L109)):*
<details><summary><i>Previously, nigel-wells (Nigel Wells) wrote…</i></summary><blockquote>

If someone signs up via SMS is their `AuthType` still `Account`?
</blockquote></details>

Good catch. SMS has its own type of account and the username should be. I've taken that into account now.
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/app.component.ts` line 477 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/1532#-NE8tN-S3N9opebeaMDV:-NJ6x9SX73-3QVkBF4qN:b-ck2cds) ([raw file](https://github.com/sillsdev/web-xforge/blob/fa747230f8a78c552b132de7740f90c5d9cc306b/src/SIL.XForge.Scripture/ClientApp/src/app/app.component.ts#L477)):*
<details><summary><i>Previously, Nateowami (Nathaniel Paulus) wrote…</i></summary><blockquote>

I think our practice has been to show every UI component and just disable those that can't be used offline, with a message stating why. So for example, here's the share dialog, which can be opened while offline:



This also avoids the loophole of "I can open the dialog while online, and then I lose my connection, and am now offline". Of course, no matter what there's always loopholes, because a user can lose their network connection at any moment without our UI being able to react first, but it's a smaller loophole.

I think our general strategy for this is as follows:
1. Disable (but don't hide) any input or button that can't be used offline, and tell the user it's unavailable.
2. If a network request fails, handle it gracefully, informing the user and retrying it in the background. There's some work that's been done on this, but it's far from complete. See `RetryingRequestService` and the places that use it. It's probably more suited to read operations (fetching data repeatedly until successful) than write operations (we don't want to keep trying to write the same thing over and over, at lest without thinking through potential consequences).

One of the advantages of this approach is that users won't be confused why a UI element that they either remember, or see in documentation, or have been told about by someone else isn't just gone.
</blockquote></details>

Thanks! I've added the message to the edit name dialog so the user knows they need an internet connection to update their name and avatar.


In the event that the network flakes out, then an error is shown to the user. I debated whether it would be best to retry in the background, or to just let the avatar be out of sync. I think the retrying request service needs some more work before using that for update requests that should be in another PR. So I'll leave it as is for now.
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/app.component.spec.ts` line 434 at r3](https://reviewable.io/reviews/sillsdev/web-xforge/1532#-NIivm4i7mB34DEy46xI:-NJ707el0BXsX_TAeeE2:b-896fix) ([raw file](https://github.com/sillsdev/web-xforge/blob/c7190cf669a56c87322a7c81b0ce0f8bdf184f9d/src/SIL.XForge.Scripture/ClientApp/src/app/app.component.spec.ts#L434)):*
<details><summary><i>Previously, nigel-wells (Nigel Wells) wrote…</i></summary><blockquote>

Perhaps change this to reflect non auth0 account users cannot edit as PT is included in this list but I first interpreted this as Google and Facebook. Still not sure where SMS fits in as per my other message.
</blockquote></details>

Done.
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/app.component.spec.ts` line 544 at r3](https://reviewable.io/reviews/sillsdev/web-xforge/1532#-NIiw7rR8mgjHVE7XOqd:-NJ70DEy64hMxyw3fpy1:b-896fix) ([raw file](https://github.com/sillsdev/web-xforge/blob/c7190cf669a56c87322a7c81b0ce0f8bdf184f9d/src/SIL.XForge.Scripture/ClientApp/src/app/app.component.spec.ts#L544)):*
<details><summary><i>Previously, nigel-wells (Nigel Wells) wrote…</i></summary><blockquote>

As per other comment, clarify name to reflect Auth0 native accounts can edit the name
</blockquote></details>

Done.
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking.component.spec.ts` line 654 at r3](https://reviewable.io/reviews/sillsdev/web-xforge/1532#-NIj7dKABrWEc_-cIgOS:-NJ70kW79XskH8RL6HN0:b-896fix) ([raw file](https://github.com/sillsdev/web-xforge/blob/c7190cf669a56c87322a7c81b0ce0f8bdf184f9d/src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking.component.spec.ts#L654)):*
<details><summary><i>Previously, nigel-wells (Nigel Wells) wrote…</i></summary><blockquote>

change to `does not open edit display name dialog if offline`
</blockquote></details>

Done.
___
*[`src/SIL.XForge.Scripture/ClientApp/src/xforge-common/user.service.ts` line 127 at r3](https://reviewable.io/reviews/sillsdev/web-xforge/1532#-NIj8E873mTw1moeyRtD:-NJ70nKv2Z49XOifD3RD:b-pn4ehk) ([raw file](https://github.com/sillsdev/web-xforge/blob/c7190cf669a56c87322a7c81b0ce0f8bdf184f9d/src/SIL.XForge.Scripture/ClientApp/src/xforge-common/user.service.ts#L127)):*
<details><summary><i>Previously, nigel-wells (Nigel Wells) wrote…</i></summary><blockquote>

I assume this is a temporary fallback until we fix the updating issue in the backend?
</blockquote></details>

This could also be triggered by a network issue. As I mentioned above, there is still more work before I feel confident using the retrying request service.
___
*[`src/SIL.XForge.Scripture/ClientApp/src/xforge-common/edit-name-dialog/edit-name-dialog.component.scss` line 2 at r3](https://reviewable.io/reviews/sillsdev/web-xforge/1532#-NIj8wqu5jRU-DHJr4Uq:-NJ71hOq4puNB0kVr1pS:b3ezsvu) ([raw file](https://github.com/sillsdev/web-xforge/blob/c7190cf669a56c87322a7c81b0ce0f8bdf184f9d/src/SIL.XForge.Scripture/ClientApp/src/xforge-common/edit-name-dialog/edit-name-dialog.component.scss#L2)):*
<details><summary><i>Previously, nigel-wells (Nigel Wells) wrote…</i></summary><blockquote>

Any reason to not set the width when the dialog is opened instead of using CSS?
</blockquote></details>

I'm not sure if there is a benefit of one over the other. I included it in the ts file now.
___
*[`src/SIL.XForge.Scripture/ClientApp/src/xforge-common/edit-name-dialog/edit-name-dialog.component.spec.ts` line 66 at r3](https://reviewable.io/reviews/sillsdev/web-xforge/1532#-NIj9yXM5hHfCHgH4_gQ:-NJ72HFkBRkCQkLogmSN:b-896fix) ([raw file](https://github.com/sillsdev/web-xforge/blob/c7190cf669a56c87322a7c81b0ce0f8bdf184f9d/src/SIL.XForge.Scripture/ClientApp/src/xforge-common/edit-name-dialog/edit-name-dialog.component.spec.ts#L66)):*
<details><summary><i>Previously, nigel-wells (Nigel Wells) wrote…</i></summary><blockquote>

Should these be replaced with `wait()`? And below
</blockquote></details>

Done.
___
*[`src/SIL.XForge.Scripture/ClientApp/src/xforge-common/edit-name-dialog/edit-name-dialog.component.spec.ts` line 159 at r3](https://reviewable.io/reviews/sillsdev/web-xforge/1532#-NIjAKFc30rxSkxpYv_q:-NJ72GpL4FiXz8ofX4TO:b-896fix) ([raw file](https://github.com/sillsdev/web-xforge/blob/c7190cf669a56c87322a7c81b0ce0f8bdf184f9d/src/SIL.XForge.Scripture/ClientApp/src/xforge-common/edit-name-dialog/edit-name-dialog.component.spec.ts#L159)):*
<details><summary><i>Previously, nigel-wells (Nigel Wells) wrote…</i></summary><blockquote>

Change to `this.wait()`
</blockquote></details>

Done.

**Review by nigel-wells — APPROVED** [review]
:lgtm:

> Reviewed 8 of 8 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1532#-:-NJ7wV-X3RnOoit_2ADA:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @Nateowami)

___
*[`src/SIL.XForge.Scripture/ClientApp/src/xforge-common/edit-name-dialog/edit-name-dialog.component.scss` line 2 at r3](https://reviewable.io/reviews/sillsdev/web-xforge/1532#-NIj8wqu5jRU-DHJr4Uq:-NJ7wGYM6IYA3oeD7tNv:b-kzimfs) ([raw file](https://github.com/sillsdev/web-xforge/blob/c7190cf669a56c87322a7c81b0ce0f8bdf184f9d/src/SIL.XForge.Scripture/ClientApp/src/xforge-common/edit-name-dialog/edit-name-dialog.component.scss#L2)):*
<details><summary><i>Previously, RaymondLuong3 (Raymond Luong) wrote…</i></summary><blockquote>

I'm not sure if there is a benefit of one over the other. I included it in the ts file now.
</blockquote></details>

Just consistency I suppose - I've seen it more in the component so let's go with that. Thanks for changing.

**Comment by Nateowami** [comment]
@RaymondLuong3 I think the title of this PR needs to be updated? I haven't been following the changes in this PR closely.

**Pull request merged**
