### PR TITLE
SF-1025 Train text segments modified offline

### PR DESCRIPTION
**Pull request by RaymondLuong3**
* added translation-engine.service class to access translation engine
* store segments that need to be trained in indexedDB when offline
* train segments when returning online
* add online feature types to type registry
* bump up indexedDB version

This change is [Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/856)

### CODE REVIEW

**Review by Nateowami — COMMENTED** [review]
What happens when the user returns online? Do the segments never get trained? Or would they get picked up later? Supposing the user closed the browser and then opened it again before returning online?

> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/856#-:-ML9V3WEAA2TChb8bH8g:b-ditr3v)* status: 0 of 2 files reviewed, all discussions resolved

**Review by RaymondLuong3 — COMMENTED** [review]
I quickly did some testing and looked on the overview page to see how many segments are trained. If a user is offline, no new segments get trained. If a user is online, modified segments are changed (only if selecting a new segment after editing). When returning online after making edits, no new segments are trained. I will bring this up in tonight's planning meeting.

> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/856#-:-ML9azJr0v1dvjYq8GlG:bk3fxde)* status: 0 of 2 files reviewed, all discussions resolved

**Review by Nateowami — COMMENTED** [review]
It almost seems as if the training should just happen automatically on the back end whenever it is informed that a segment has changed (that way whenever the realtime docs get updated the training runs, rather than trying to do it at the time the edit is made).

> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/856#-:-ML9cLhdBH1EJCmz91YO:b-fvt9vr)* status: 0 of 2 files reviewed, all discussions resolved

**Review by RaymondLuong3 — COMMENTED** [review]
I wonder if our translation engine is compatible with a .Net application. I agree that it would be beneficial if the training could happen on the back-end, but I'm not sure if that's an option for us.

> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/856#-:-ML9oQCb8JtO-WbIccgT:b3uvl8x)* status: 0 of 2 files reviewed, all discussions resolved

**Review by Nateowami — COMMENTED** [review]
Unless I'm mistaken, our translation engine _is_ a .NET application. I'm pretty sure all the training and suggesting happens on the back end. All the front end does is inform the back end when a segment is ready to be trained.

> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/856#-:-MLARD3Q7azDCMf7xoJc:bmvk2k6)* status: 0 of 2 files reviewed, all discussions resolved

**Review by RaymondLuong3 — COMMENTED** [review]
The segments that are modified while offline will now get trained when the user returns online. I welcome any suggestions to be this clearer, especially better names. I really struggled to find the best names for the different data classes I introduced.

> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/856#-:-MLPi1lP-q_bZuGMtCyP:btx9our)* status: 0 of 21 files reviewed, all discussions resolved

**Review by ddaspit — CHANGES_REQUESTED** [review]
> Reviewed 21 of 21 files at r2.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/856)* status: all files reviewed, 5 unresolved discussions (waiting on @RaymondLuong3)

___
*[src/SIL.XForge.Scripture/ClientApp/src/app/core/translation-engine.service.ts, line 53 at r2](https://reviewable.io/reviews/sillsdev/web-xforge/856#-MLkK-iM7BKJMcIYxxAy:-MLkK-iM7BKJMcIYxxAz:b-gbpy5a) ([raw file](https://github.com/sillsdev/web-xforge/blob/2b2d2e19d130eda0966524ed54c2bdd74e36d590/src/SIL.XForge.Scripture/ClientApp/src/app/core/translation-engine.service.ts#L53)):*
> ```XML
>     this.onlineCallback(async () => {
>       const translationSuggestionsData = await this.getAll<TranslationSuggestionsData>(FEATURE_TRANSLATION);
>       for (const chapterData of translationSuggestionsData) {
> ```

I would have a separate entry for each segment. The current design can result in the same segment being trained multiple times.
___
*[src/SIL.XForge.Scripture/ClientApp/src/app/core/translation-engine.service.ts, line 79 at r2](https://reviewable.io/reviews/sillsdev/web-xforge/856#-MLkKUip2PKfDwcdAD-l:-MLkKUip2PKfDwcdAD-m:b-1tviqu) ([raw file](https://github.com/sillsdev/web-xforge/blob/2b2d2e19d130eda0966524ed54c2bdd74e36d590/src/SIL.XForge.Scripture/ClientApp/src/app/core/translation-engine.service.ts#L79)):*
> ```XML
>    * Train the translation engine with the text for a specified segment using the target and source text
>    */
>   async trainSelectedSegment(data: SegmentTrainingData): Promise<void> {
> ```

I would split this method into two methods: `trainSelectedSegment(projectUserConfig: SFProjectUserConfig)` and `trainSegment(projectRef: string, bookNum: number, chapterNum: number, segment: string)`. `trainSelectedSegment` would be public and `trainSegment` would be private. This would allow you to get rid of the `SegmentTrainingData` interface. The online callback would call `trainSegment`. 
___
*[src/SIL.XForge.Scripture/ClientApp/src/xforge-common/online-feature.service.ts, line 11 at r2](https://reviewable.io/reviews/sillsdev/web-xforge/856#-MLkMvRH5swMzRFQZL4S:-MLkMvRI5bKVaQscJ9NG:b-lq4jkh) ([raw file](https://github.com/sillsdev/web-xforge/blob/2b2d2e19d130eda0966524ed54c2bdd74e36d590/src/SIL.XForge.Scripture/ClientApp/src/xforge-common/online-feature.service.ts#L11)):*
> ```XML
>  * A service to execute a feature that requires an internet connection using data stored in IndexedDB
>  */
> export abstract class OnlineFeatureService extends SubscriptionDisposable {
> ```

I would get rid of this class entirely and move its implementation in to the `TranslationEngineService`. I'm not convinced that we need an abstraction for this yet. This very well could be a one-off situation. If there is more offline data like this that we add in the future, we can always refactor it to an appropriate abstraction.
___
*[src/SIL.XForge.Scripture/ClientApp/src/xforge-common/type-registry.ts, line 29 at r2](https://reviewable.io/reviews/sillsdev/web-xforge/856#-MLkNwIX9HBpi212IkrC:-MLkNwIX9HBpi212IkrD:bd59jkj) ([raw file](https://github.com/sillsdev/web-xforge/blob/2b2d2e19d130eda0966524ed54c2bdd74e36d590/src/SIL.XForge.Scripture/ClientApp/src/xforge-common/type-registry.ts#L29)):*
> ```XML
>   }
> 
>   get onlineFeatureTypes(): Iterable<string> {
> ```

I agree that the naming is difficult for this. Maybe `customOfflineTypes` or just `customTypes`. I am thinking of this as being a simple way to add custom stores to IndexedDB that a service can use however it wants. This will keep it really general-purpose for exceptional cases.
___
*[src/SIL.XForge.Scripture/ClientApp/src/xforge-common/models/feature-offline-data.ts, line 3 at r2](https://reviewable.io/reviews/sillsdev/web-xforge/856#-MLkNlhN20sqvEneIzww:-MLkNlhN20sqvEneIzwx:b-nk46eh) ([raw file](https://github.com/sillsdev/web-xforge/blob/2b2d2e19d130eda0966524ed54c2bdd74e36d590/src/SIL.XForge.Scripture/ClientApp/src/xforge-common/models/feature-offline-data.ts#L3)):*
> ```XML
> import { OfflineData } from '../offline-store';
> 
> export interface FeatureOfflineData extends OfflineData {
> ```

I would get rid of this interface. See my discussion on the `OnlineFeatureService` class.

**Review by RaymondLuong3 — COMMENTED** [review]
Ok, I've removed the classes that were an unnecessary abstraction, and am using customTypes in the typeRegistry for the Engine Training data. 

> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/856#-:-MLneZdM-UhFyxVoHHyf:b-28tdz6)* status: 10 of 19 files reviewed, 5 unresolved discussions (waiting on @ddaspit)

___
*[src/SIL.XForge.Scripture/ClientApp/src/app/core/translation-engine.service.ts, line 53 at r2](https://reviewable.io/reviews/sillsdev/web-xforge/856#-MLkK-iM7BKJMcIYxxAy:-MLneUaw9AoO5wRQvZ3M:b-896fix) ([raw file](https://github.com/sillsdev/web-xforge/blob/2b2d2e19d130eda0966524ed54c2bdd74e36d590/src/SIL.XForge.Scripture/ClientApp/src/app/core/translation-engine.service.ts#L53)):*
<details><summary><i>Previously, ddaspit (Damien Daspit) wrote…</i></summary><blockquote>

I would have a separate entry for each segment. The current design can result in the same segment being trained multiple times.
</blockquote></details>

Done.
___
*[src/SIL.XForge.Scripture/ClientApp/src/app/core/translation-engine.service.ts, line 79 at r2](https://reviewable.io/reviews/sillsdev/web-xforge/856#-MLkKUip2PKfDwcdAD-l:-MLneX2f86WgaPuiYKit:b-896fix) ([raw file](https://github.com/sillsdev/web-xforge/blob/2b2d2e19d130eda0966524ed54c2bdd74e36d590/src/SIL.XForge.Scripture/ClientApp/src/app/core/translation-engine.service.ts#L79)):*
<details><summary><i>Previously, ddaspit (Damien Daspit) wrote…</i></summary><blockquote>

I would split this method into two methods: `trainSelectedSegment(projectUserConfig: SFProjectUserConfig)` and `trainSegment(projectRef: string, bookNum: number, chapterNum: number, segment: string)`. `trainSelectedSegment` would be public and `trainSegment` would be private. This would allow you to get rid of the `SegmentTrainingData` interface. The online callback would call `trainSegment`. 
</blockquote></details>

Done.
___
*[src/SIL.XForge.Scripture/ClientApp/src/xforge-common/online-feature.service.ts, line 11 at r2](https://reviewable.io/reviews/sillsdev/web-xforge/856#-MLkMvRH5swMzRFQZL4S:-MLn96wFALUV86dNV1IX:b-896fix) ([raw file](https://github.com/sillsdev/web-xforge/blob/2b2d2e19d130eda0966524ed54c2bdd74e36d590/src/SIL.XForge.Scripture/ClientApp/src/xforge-common/online-feature.service.ts#L11)):*
<details><summary><i>Previously, ddaspit (Damien Daspit) wrote…</i></summary><blockquote>

I would get rid of this class entirely and move its implementation in to the `TranslationEngineService`. I'm not convinced that we need an abstraction for this yet. This very well could be a one-off situation. If there is more offline data like this that we add in the future, we can always refactor it to an appropriate abstraction.
</blockquote></details>

Done.
___
*[src/SIL.XForge.Scripture/ClientApp/src/xforge-common/type-registry.ts, line 29 at r2](https://reviewable.io/reviews/sillsdev/web-xforge/856#-MLkNwIX9HBpi212IkrC:-MLnACrU2F0zJ6SS6xnn:b-896fix) ([raw file](https://github.com/sillsdev/web-xforge/blob/2b2d2e19d130eda0966524ed54c2bdd74e36d590/src/SIL.XForge.Scripture/ClientApp/src/xforge-common/type-registry.ts#L29)):*
<details><summary><i>Previously, ddaspit (Damien Daspit) wrote…</i></summary><blockquote>

I agree that the naming is difficult for this. Maybe `customOfflineTypes` or just `customTypes`. I am thinking of this as being a simple way to add custom stores to IndexedDB that a service can use however it wants. This will keep it really general-purpose for exceptional cases.
</blockquote></details>

Done.
___
*[src/SIL.XForge.Scripture/ClientApp/src/xforge-common/models/feature-offline-data.ts, line 3 at r2](https://reviewable.io/reviews/sillsdev/web-xforge/856#-MLkNlhN20sqvEneIzww:-MLnAAqzEMVquKOrYwhp:b-896fix) ([raw file](https://github.com/sillsdev/web-xforge/blob/2b2d2e19d130eda0966524ed54c2bdd74e36d590/src/SIL.XForge.Scripture/ClientApp/src/xforge-common/models/feature-offline-data.ts#L3)):*
<details><summary><i>Previously, ddaspit (Damien Daspit) wrote…</i></summary><blockquote>

I would get rid of this interface. See my discussion on the `OnlineFeatureService` class.
</blockquote></details>

Done.

**Review by ddaspit — CHANGES_REQUESTED** [review]
Looking good. Just a couple more suggestions.

> Reviewed 11 of 11 files at r3.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/856#-:-MLpgf7U1s8E3cu8mQ5M:bx2ty8c)* status: all files reviewed, 5 unresolved discussions (waiting on @RaymondLuong3)

___
*[src/SIL.XForge.Scripture/ClientApp/src/app/core/translation-engine.service.ts, line 100 at r3](https://reviewable.io/reviews/sillsdev/web-xforge/856#-MLpdaFbEQddOCQ_4n6G:-MLpdaFbEQddOCQ_4n6H:b-nsq83z) ([raw file](https://github.com/sillsdev/web-xforge/blob/3a109a36967f9f2c2ba774340a1d07f7e459db8a/src/SIL.XForge.Scripture/ClientApp/src/app/core/translation-engine.service.ts#L100)):*
> ```XML
>     chapterNum: number,
>     segment: string,
>     checksum: number | undefined
> ```

You can make this parameter optional.
___
*[src/SIL.XForge.Scripture/ClientApp/src/app/core/translation-engine.service.ts, line 107 at r3](https://reviewable.io/reviews/sillsdev/web-xforge/856#-MLpdd74EColJCfj72vr:-MLpdd74EColJCfj72vs:b5ayq4b) ([raw file](https://github.com/sillsdev/web-xforge/blob/3a109a36967f9f2c2ba774340a1d07f7e459db8a/src/SIL.XForge.Scripture/ClientApp/src/app/core/translation-engine.service.ts#L107)):*
> ```XML
>       return;
>     }
>     const targetChecksum = crc.str(targetText);
> ```

No need to compute the CRC if `checksum` is `undefined`.
___
*[src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.ts, line 349 at r3](https://reviewable.io/reviews/sillsdev/web-xforge/856#-MLpg7MTEu9xol7xTiCy:-MLpg7MTEu9xol7xTiCz:bogxsgl) ([raw file](https://github.com/sillsdev/web-xforge/blob/3a109a36967f9f2c2ba774340a1d07f7e459db8a/src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.ts#L349)):*
> ```XML
>             await this.trainSegment(
>               prevSegment,
>               this.projectUserConfigDoc.data.projectRef,
> ```

I don't think it is necessary to pass in these values from `projectUserConfigDoc`. You should be able to reference `projectUserConfigDoc` directly in `trainSegment`.
___
*[src/SIL.XForge.Scripture/ClientApp/src/app/core/models/engine-training-storage-data.ts, line 3 at r3](https://reviewable.io/reviews/sillsdev/web-xforge/856#-MLpeIiyBaw8-XH4lTTP:-MLpeIiyBaw8-XH4lTTQ:bl2c4qc) ([raw file](https://github.com/sillsdev/web-xforge/blob/3a109a36967f9f2c2ba774340a1d07f7e459db8a/src/SIL.XForge.Scripture/ClientApp/src/app/core/models/engine-training-storage-data.ts#L3)):*
> ```XML
> import { OfflineData } from 'xforge-common/offline-store';
> 
> export const FEATURE_TRANSLATION = 'feature_translation';
> ```

I feel like this name is specific enough. Maybe `edited_segments`.
___
*[src/SIL.XForge.Scripture/ClientApp/src/app/core/models/engine-training-storage-data.ts, line 8 at r3](https://reviewable.io/reviews/sillsdev/web-xforge/856#-MLpeU_58ybEytMDq6et:-MLpeU_58ybEytMDq6eu:b-6ycc0o) ([raw file](https://github.com/sillsdev/web-xforge/blob/3a109a36967f9f2c2ba774340a1d07f7e459db8a/src/SIL.XForge.Scripture/ClientApp/src/app/core/models/engine-training-storage-data.ts#L8)):*
> ```XML
>  * Data that can be stored in browser storage and used to train edited segments while offline
>  */
> export interface EngineTrainingStorageData extends OfflineData {
> ```

Same with this interface. Maybe `EditedSegmentData`.

**Review by RaymondLuong3 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/856)* status: all files reviewed, 5 unresolved discussions (waiting on @ddaspit)

___
*[src/SIL.XForge.Scripture/ClientApp/src/app/core/translation-engine.service.ts, line 100 at r3](https://reviewable.io/reviews/sillsdev/web-xforge/856#-MLpdaFbEQddOCQ_4n6G:-MM1tgWe7RSy2GMYJae3:b-896fix) ([raw file](https://github.com/sillsdev/web-xforge/blob/3a109a36967f9f2c2ba774340a1d07f7e459db8a/src/SIL.XForge.Scripture/ClientApp/src/app/core/translation-engine.service.ts#L100)):*
<details><summary><i>Previously, ddaspit (Damien Daspit) wrote…</i></summary><blockquote>

You can make this parameter optional.
</blockquote></details>

Done.
___
*[src/SIL.XForge.Scripture/ClientApp/src/app/core/translation-engine.service.ts, line 107 at r3](https://reviewable.io/reviews/sillsdev/web-xforge/856#-MLpdd74EColJCfj72vr:-MM1thNqAz1PTAJalpjv:byh5gr3) ([raw file](https://github.com/sillsdev/web-xforge/blob/3a109a36967f9f2c2ba774340a1d07f7e459db8a/src/SIL.XForge.Scripture/ClientApp/src/app/core/translation-engine.service.ts#L107)):*
<details><summary><i>Previously, ddaspit (Damien Daspit) wrote…</i></summary><blockquote>

No need to compute the CRC if `checksum` is `undefined`.
</blockquote></details>

That would be smart. Done.
___
*[src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.ts, line 349 at r3](https://reviewable.io/reviews/sillsdev/web-xforge/856#-MLpg7MTEu9xol7xTiCy:-MM1toN_3aqAtfaHsRn1:btc38d0) ([raw file](https://github.com/sillsdev/web-xforge/blob/3a109a36967f9f2c2ba774340a1d07f7e459db8a/src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.ts#L349)):*
<details><summary><i>Previously, ddaspit (Damien Daspit) wrote…</i></summary><blockquote>

I don't think it is necessary to pass in these values from `projectUserConfigDoc`. You should be able to reference `projectUserConfigDoc` directly in `trainSegment`.
</blockquote></details>

Yes, I hadn't even thought of that. Done.
___
*[src/SIL.XForge.Scripture/ClientApp/src/app/core/models/engine-training-storage-data.ts, line 3 at r3](https://reviewable.io/reviews/sillsdev/web-xforge/856#-MLpeIiyBaw8-XH4lTTP:-MM1tmqv0Bot3hFVvibE:b-896fix) ([raw file](https://github.com/sillsdev/web-xforge/blob/3a109a36967f9f2c2ba774340a1d07f7e459db8a/src/SIL.XForge.Scripture/ClientApp/src/app/core/models/engine-training-storage-data.ts#L3)):*
<details><summary><i>Previously, ddaspit (Damien Daspit) wrote…</i></summary><blockquote>

I feel like this name is specific enough. Maybe `edited_segments`.
</blockquote></details>

Done.
___
*[src/SIL.XForge.Scripture/ClientApp/src/app/core/models/engine-training-storage-data.ts, line 8 at r3](https://reviewable.io/reviews/sillsdev/web-xforge/856#-MLpeU_58ybEytMDq6et:-MM1tnCnEde0pMGeK8zD:b-896fix) ([raw file](https://github.com/sillsdev/web-xforge/blob/3a109a36967f9f2c2ba774340a1d07f7e459db8a/src/SIL.XForge.Scripture/ClientApp/src/app/core/models/engine-training-storage-data.ts#L8)):*
<details><summary><i>Previously, ddaspit (Damien Daspit) wrote…</i></summary><blockquote>

Same with this interface. Maybe `EditedSegmentData`.
</blockquote></details>

Done.

**Review by ddaspit — APPROVED** [review]
:lgtm:

> Reviewed 6 of 6 files at r4.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/856#-:-MMJWjdk2MwCdRtQwp7u:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
