### PR TITLE
SF-2337 Replace ngx-avatar with custom component

### PR DESCRIPTION
**Pull request by siltomato**
Package 'ngx-avatar' had incompatibilities with Angular 16.  This PR replaces the 'ngx-avatar' dependency with a custom component.

- - -
This change is [Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/2248)

### CODE REVIEW

**Review by Nateowami — CHANGES_REQUESTED** [review]
Did you check whether `src/SIL.XForge.Scripture/ClientApp/src/xforge-common/avatar/avatar-testing.component.ts` is:
1. Still needed, and
2. Still a proper/reasonable replacement for the actual avatar component

?

> Reviewed 9 of 9 files at r1, 13 of 13 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/2248#-:-Nlz9uM36uw4rdL4bxy1:b3x5t7e)* status: all files reviewed, 5 unresolved discussions (waiting on @siltomato)

___
*[`src/SIL.XForge.Scripture/ClientApp/src/xforge-common/avatar/avatar.component.ts` line 17 at r2](https://reviewable.io/reviews/sillsdev/web-xforge/2248#-Nlz6d255jPtItw3EvpV:-Nlz6d255jPtItw3EvpW:b-9z7e2z) ([raw file](https://github.com/sillsdev/web-xforge/blob/ae679d3f05673933583728d77157bcb06eb94d71/src/SIL.XForge.Scripture/ClientApp/src/xforge-common/avatar/avatar.component.ts#L17)):*
> ```XML
> })
> export class AvatarComponent implements OnChanges {
>   @Input() round: boolean = false;
> ```

I think this property should have been removed?
___
*[`src/SIL.XForge.Scripture/ClientApp/src/xforge-common/avatar/avatar.component.ts` line 21 at r2](https://reviewable.io/reviews/sillsdev/web-xforge/2248#-Nlz96AODJWlsZREFyhr:-Nlz96AODJWlsZREFyhs:b-88023s) ([raw file](https://github.com/sillsdev/web-xforge/blob/ae679d3f05673933583728d77157bcb06eb94d71/src/SIL.XForge.Scripture/ClientApp/src/xforge-common/avatar/avatar.component.ts#L21)):*
> ```XML
>   @Input() user?: UserProfile;
>   @Input() borderColor: string = 'transparent';
>   @Input() showOnlineStatus: boolean = true;
> ```

I've always found it very odd that `showOnlineStatus` is part of this component. It seems like it should be the parent component's job to show an icon over the avatar, not the avatar component's responsiblity.

Not directly related to this change, but as this component is completely re-written, it seems reasonable to me to remove it.
___
*[`src/SIL.XForge.Scripture/ClientApp/src/xforge-common/avatar/avatar.component.ts` line 40 at r2](https://reviewable.io/reviews/sillsdev/web-xforge/2248#-NlzAEru0XI2DZXmsVmu:-NlzAEru0XI2DZXmsVmv:b-dzzkr5) ([raw file](https://github.com/sillsdev/web-xforge/blob/ae679d3f05673933583728d77157bcb06eb94d71/src/SIL.XForge.Scripture/ClientApp/src/xforge-common/avatar/avatar.component.ts#L40)):*
> ```XML
>   getMode(): AvatarMode {
>     if (this.avatarUrl != null && this.avatarUrl !== '') {
>       return 'image';
> ```

What if the image fails to load (e.g. because we're offline)? Should we not fall back to initials? Can we add an onerror handler to the image to find out that it failed to load? This would be a great test case to put in Storybook as well. I think our existing avatar component was already doing that.
___
*[`src/SIL.XForge.Scripture/ClientApp/src/xforge-common/avatar/avatar.stories.ts` line 11 at r2](https://reviewable.io/reviews/sillsdev/web-xforge/2248#-Nlz8YBM0HJBqC66f1AH:-Nlz8YBM0HJBqC66f1AI:b-rx87e6) ([raw file](https://github.com/sillsdev/web-xforge/blob/ae679d3f05673933583728d77157bcb06eb94d71/src/SIL.XForge.Scripture/ClientApp/src/xforge-common/avatar/avatar.stories.ts#L11)):*
> ```XML
> export default meta;
> 
> type Story = StoryObj<AvatarComponent>;
> ```

These stories appear to have serious omissions, like demonstrating the use of size and borderColor. Maybe we could get some examples of that, since we are depending on that working throughout the app?
___
*[`src/SIL.XForge.Scripture/ClientApp/src/xforge-common/avatar/avatar.stories.ts` line 22 at r2](https://reviewable.io/reviews/sillsdev/web-xforge/2248#-NlzAX2z6qyTnFGcx-87:-NlzAX2z6qyTnFGcx-88:b8fxy5z) ([raw file](https://github.com/sillsdev/web-xforge/blob/ae679d3f05673933583728d77157bcb06eb94d71/src/SIL.XForge.Scripture/ClientApp/src/xforge-common/avatar/avatar.stories.ts#L22)):*
> ```XML
>   args: {
>     user: createTestUserProfile({
>       avatarUrl: 'https://lh3.googleusercontent.com/a/AAcHTtcyQUN11i9S3aHfAPpIKzvsqjWOz3fKQnMfigwpklWc4q4=s96-c',
> ```

Curious whether we have a more "generic" image that's still a useful test? Feels weird to insert my own face as a test.

**Review by siltomato — COMMENTED** [review]
Good point.  Removed AvatarTestingModule

> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/2248#-:-NlzNOuS-qUkzXcoHOg0:bisrn6v)* status: 13 of 29 files reviewed, 2 unresolved discussions (waiting on @Nateowami)

___
*[`src/SIL.XForge.Scripture/ClientApp/src/xforge-common/avatar/avatar.component.ts` line 17 at r2](https://reviewable.io/reviews/sillsdev/web-xforge/2248#-Nlz6d255jPtItw3EvpV:-NlzNkMQ32ArGHXHN-tq:b-896fix) ([raw file](https://github.com/sillsdev/web-xforge/blob/7488eb2263a2e8559902b42fc775c83e610d4cfd/src/SIL.XForge.Scripture/ClientApp/src/xforge-common/avatar/avatar.component.ts#L17)):*
<details><summary><i>Previously, Nateowami (Nathaniel Paulus) wrote…</i></summary><blockquote>

I think this property should have been removed?
</blockquote></details>

Done.
___
*[`src/SIL.XForge.Scripture/ClientApp/src/xforge-common/avatar/avatar.component.ts` line 21 at r2](https://reviewable.io/reviews/sillsdev/web-xforge/2248#-Nlz96AODJWlsZREFyhr:-Nm7BaA69ixC-B7MC9Om:b-896fix) ([raw file](https://github.com/sillsdev/web-xforge/blob/7488eb2263a2e8559902b42fc775c83e610d4cfd/src/SIL.XForge.Scripture/ClientApp/src/xforge-common/avatar/avatar.component.ts#L21)):*
<details><summary><i>Previously, Nateowami (Nathaniel Paulus) wrote…</i></summary><blockquote>

I've always found it very odd that `showOnlineStatus` is part of this component. It seems like it should be the parent component's job to show an icon over the avatar, not the avatar component's responsiblity.

Not directly related to this change, but as this component is completely re-written, it seems reasonable to me to remove it.
</blockquote></details>

Done.
___
*[`src/SIL.XForge.Scripture/ClientApp/src/xforge-common/avatar/avatar.component.ts` line 40 at r2](https://reviewable.io/reviews/sillsdev/web-xforge/2248#-NlzAEru0XI2DZXmsVmu:-Nm7LmVlE7PvMRqD0SE3:b-896fix) ([raw file](https://github.com/sillsdev/web-xforge/blob/7488eb2263a2e8559902b42fc775c83e610d4cfd/src/SIL.XForge.Scripture/ClientApp/src/xforge-common/avatar/avatar.component.ts#L40)):*
<details><summary><i>Previously, Nateowami (Nathaniel Paulus) wrote…</i></summary><blockquote>

What if the image fails to load (e.g. because we're offline)? Should we not fall back to initials? Can we add an onerror handler to the image to find out that it failed to load? This would be a great test case to put in Storybook as well. I think our existing avatar component was already doing that.
</blockquote></details>

Done.
___
*[`src/SIL.XForge.Scripture/ClientApp/src/xforge-common/avatar/avatar.stories.ts` line 11 at r2](https://reviewable.io/reviews/sillsdev/web-xforge/2248#-Nlz8YBM0HJBqC66f1AH:-Nm7iF2169R70SPfUyB1:b-896fix) ([raw file](https://github.com/sillsdev/web-xforge/blob/7488eb2263a2e8559902b42fc775c83e610d4cfd/src/SIL.XForge.Scripture/ClientApp/src/xforge-common/avatar/avatar.stories.ts#L11)):*
<details><summary><i>Previously, Nateowami (Nathaniel Paulus) wrote…</i></summary><blockquote>

These stories appear to have serious omissions, like demonstrating the use of size and borderColor. Maybe we could get some examples of that, since we are depending on that working throughout the app?
</blockquote></details>

Done.
___
*[`src/SIL.XForge.Scripture/ClientApp/src/xforge-common/avatar/avatar.stories.ts` line 22 at r2](https://reviewable.io/reviews/sillsdev/web-xforge/2248#-NlzAX2z6qyTnFGcx-87:-Nm7Lsuq1waqU6rQPOhr:b-ojlf9z) ([raw file](https://github.com/sillsdev/web-xforge/blob/7488eb2263a2e8559902b42fc775c83e610d4cfd/src/SIL.XForge.Scripture/ClientApp/src/xforge-common/avatar/avatar.stories.ts#L22)):*
<details><summary><i>Previously, Nateowami (Nathaniel Paulus) wrote…</i></summary><blockquote>

Curious whether we have a more "generic" image that's still a useful test? Feels weird to insert my own face as a test.
</blockquote></details>

Ha!  Nah, we'd all love to see that smiling mug in storybook.  Denied!

JK, I swapped it out =).

**Review by Nateowami — CHANGES_REQUESTED** [review]
> Reviewed 11 of 11 files at r3, 2 of 5 files at r4, 4 of 4 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/2248)* status: all files reviewed, 1 unresolved discussion (waiting on @siltomato)

___
*[`src/SIL.XForge.Scripture/ClientApp/src/xforge-common/avatar/avatar.stories.ts` line 11 at r2](https://reviewable.io/reviews/sillsdev/web-xforge/2248#-Nlz8YBM0HJBqC66f1AH:-Nm8qEtgBVYdRdTKpK5p:b-ucfkn4) ([raw file](https://github.com/sillsdev/web-xforge/blob/7488eb2263a2e8559902b42fc775c83e610d4cfd/src/SIL.XForge.Scripture/ClientApp/src/xforge-common/avatar/avatar.stories.ts#L11)):*
<details><summary><i>Previously, siltomato wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Thanks.
___
*[`src/SIL.XForge.Scripture/ClientApp/src/xforge-common/avatar/avatar.stories.ts` line 24 at r5](https://reviewable.io/reviews/sillsdev/web-xforge/2248#-Nm8qXog9R3m75P2Nk6a:-Nm8qXog9R3m75P2Nk6b:b6y8q27) ([raw file](https://github.com/sillsdev/web-xforge/blob/0568f009d781fd3c534d39e29a890f16428e7742/src/SIL.XForge.Scripture/ClientApp/src/xforge-common/avatar/avatar.stories.ts#L24)):*
> ```XML
>     user: createTestUserProfile({
>       displayName: 'John Doe',
>       avatarUrl: 'https://cdn.drawception.com/drawings/O6Bfl1QP5R.png'
> ```

Good choice.
___
*[`src/SIL.XForge.Scripture/ClientApp/src/xforge-common/system-administration/sa-delete-dialog.component.spec.ts` line 39 at r3](https://reviewable.io/reviews/sillsdev/web-xforge/2248#-Nm8a9fe-HZG-8lqS79G:-Nm8a9fe-HZG-8lqS79H:bfutntr) ([raw file](https://github.com/sillsdev/web-xforge/blob/44696483435ea96194b90e5cfbab7a0ed6e94380/src/SIL.XForge.Scripture/ClientApp/src/xforge-common/system-administration/sa-delete-dialog.component.spec.ts#L39)):*
> ```XML
> 
> @NgModule({
>   imports: [CommonModule, UICommonModule, TestOnlineStatusModule.forRoot(), AvatarComponent, NoopAnimationsModule],
> ```

`TestOnlineStatusModule.forRoot()` can be removed.

**Comment by Nateowami** [comment]
Since my only complaint has to do with testing, I'm going to move this to "ready to test."

**Review by siltomato — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/2248)* status: 3 of 29 files reviewed, 1 unresolved discussion (waiting on @Nateowami)

___
*[`src/SIL.XForge.Scripture/ClientApp/src/xforge-common/system-administration/sa-delete-dialog.component.spec.ts` line 39 at r3](https://reviewable.io/reviews/sillsdev/web-xforge/2248#-Nm8a9fe-HZG-8lqS79G:-NmC0S69Dlw22mX6t786:b9uh8xl) ([raw file](https://github.com/sillsdev/web-xforge/blob/44696483435ea96194b90e5cfbab7a0ed6e94380/src/SIL.XForge.Scripture/ClientApp/src/xforge-common/system-administration/sa-delete-dialog.component.spec.ts#L39)):*
<details><summary><i>Previously, Nateowami (Nathaniel Paulus) wrote…</i></summary><blockquote>

`TestOnlineStatusModule.forRoot()` can be removed.
</blockquote></details>

Ah, good catch, thanks.

**Review by Nateowami — CHANGES_REQUESTED** [review]
> Reviewed 26 of 26 files at r6, 8 of 13 files at r7, 9 of 11 files at r8, 2 of 5 files at r9, 3 of 4 files at r10, 1 of 1 files at r11, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/2248)* status: 28 of 29 files reviewed, 1 unresolved discussion (waiting on @siltomato)

___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/shared/text/text.component.spec.ts` line 109 at r11](https://reviewable.io/reviews/sillsdev/web-xforge/2248#-NmC2teVCEDkUox2Se4X:-NmC2teVCEDkUox2Se4Y:bhjxjit) ([raw file](https://github.com/sillsdev/web-xforge/blob/2d2e3002387344e63524fd8072979dc9e8c672f8/src/SIL.XForge.Scripture/ClientApp/src/app/shared/text/text.component.spec.ts#L109)):*
> ```XML
>     expect(env.component.editor?.getContents().ops?.length)
>       .withContext('setup')
>       .toEqual(25);
> ```

This reformatting is invalid according to Prettier. Not sure why your machine keeps reformatting it.

**Review by Nateowami — APPROVED** [review]
> Reviewed 23 of 24 files at r12, 13 of 13 files at r13, 10 of 11 files at r14, 2 of 5 files at r15, 4 of 4 files at r16, 1 of 1 files at r17, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/2248)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @siltomato)

___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/shared/text/text.component.spec.ts` line 109 at r11](https://reviewable.io/reviews/sillsdev/web-xforge/2248#-NmC2teVCEDkUox2Se4X:-NmC42Kw0NTbgDilQdnW:b-8c4h41) ([raw file](https://github.com/sillsdev/web-xforge/blob/2d2e3002387344e63524fd8072979dc9e8c672f8/src/SIL.XForge.Scripture/ClientApp/src/app/shared/text/text.component.spec.ts#L109)):*
<details><summary><i>Previously, Nateowami (Nathaniel Paulus) wrote…</i></summary><blockquote>

This reformatting is invalid according to Prettier. Not sure why your machine keeps reformatting it.
</blockquote></details>

Just went ahead and fixed this.

**Comment by Nateowami** [comment]
Reviewable is being a nightmare on this PR. It keeps making me review things I've already reviewed.

**Review by siltomato — COMMENTED** [review]
Strange.  I updated file that had the 'prettier' issue (saw your note after i had already force-pushed).  Maybe this had something to do with it?

> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/2248#-:-NmC8IM94BHpm-lGSnUu:bq7hxfp)* status: 5 of 29 files reviewed, all discussions resolved (waiting on @Nateowami)

**Pull request merged**
