### PR TITLE
SF-1905 Disable adding a note on unavailable text

### PR DESCRIPTION
**Pull request by RaymondLuong3**
On projects where there are texts are unavailable we should not allow a user to add a note. This change makes a snackbar appear when a user clicks the add note button when viewing a texts that is unavailable because a user is offline.

- - -
This change is [Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1742)

### CODE REVIEW

**Review by nigel-wells — CHANGES_REQUESTED** [review]
> Reviewed 5 of 5 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1742)* status: all files reviewed, 1 unresolved discussion (waiting on @RaymondLuong3)

___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.ts` line 826 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/1742#-NQXEMiG18TCh8mEFJKX:-NQXEMiH2pP8NLR2_1qn:bkdas4n) ([raw file](https://github.com/sillsdev/web-xforge/blob/285e9e866de33ceee028751149a0d0a13ea40fbf/src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.ts#L826)):*
> ```XML
>       return;
>     }
>     if (!this.isUsfmValid || !this.dataInSync || this.target.areOpsCorrupted || !this.target.contentShowing) {
> ```

Perhaps if a sync is taking place then a different message should appear? Why is the sync an issue specifically with notes anyway and not any other data we're adding in SF?

**Review by Nateowami — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1742)* status: all files reviewed, 1 unresolved discussion (waiting on @nigel-wells)

___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.ts` line 826 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/1742#-NQXEMiG18TCh8mEFJKX:-NQ_mcfd7yZH6PbrXiXJ:b-v3tar9) ([raw file](https://github.com/sillsdev/web-xforge/blob/285e9e866de33ceee028751149a0d0a13ea40fbf/src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.ts#L826)):*
<details><summary><i>Previously, nigel-wells (Nigel Wells) wrote…</i></summary><blockquote>

Perhaps if a sync is taking place then a different message should appear? Why is the sync an issue specifically with notes anyway and not any other data we're adding in SF?
</blockquote></details>

@nigel-wells `this.dataInSync` does not mean "a sync is in progress". It's something to do with a sync not going correctly and the SF data being out of sync with PT data, and when that happens, we lock to prevent editing. At least to the best of my recollection. If you want to be sure, follow the code paths that actually set the value. I haven't taken the time to do that.

**Review by RaymondLuong3 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1742)* status: all files reviewed, 1 unresolved discussion (waiting on @nigel-wells)

___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.ts` line 826 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/1742#-NQXEMiG18TCh8mEFJKX:-NQa60V75MJHKO1Qjv5P:b-3n6c5w) ([raw file](https://github.com/sillsdev/web-xforge/blob/285e9e866de33ceee028751149a0d0a13ea40fbf/src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.ts#L826)):*
<details><summary><i>Previously, Nateowami (Nathaniel Paulus) wrote…</i></summary><blockquote>

@nigel-wells `this.dataInSync` does not mean "a sync is in progress". It's something to do with a sync not going correctly and the SF data being out of sync with PT data, and when that happens, we lock to prevent editing. At least to the best of my recollection. If you want to be sure, follow the code paths that actually set the value. I haven't taken the time to do that.
</blockquote></details>

That's right, the dataInSync property doesn't relate to whether the project is synchronizing, just that there was a sync that wasn't completed right. In those cases we lock the editor and ask the user to sync again. In the case that a sync is happening, there isn't anything stopping the user from editing the text (which is something I'm not sure we have thought much about)

**Review by nigel-wells — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1742#-:-NQb2ZK58Uo_DlaW9d_0:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @RaymondLuong3)

___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.ts` line 826 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/1742#-NQXEMiG18TCh8mEFJKX:-NQb2FOh37IcMTAdogmV:b-cvh5y4) ([raw file](https://github.com/sillsdev/web-xforge/blob/285e9e866de33ceee028751149a0d0a13ea40fbf/src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.ts#L826)):*
<details><summary><i>Previously, RaymondLuong3 (Raymond Luong) wrote…</i></summary><blockquote>

That's right, the dataInSync property doesn't relate to whether the project is synchronizing, just that there was a sync that wasn't completed right. In those cases we lock the editor and ask the user to sync again. In the case that a sync is happening, there isn't anything stopping the user from editing the text (which is something I'm not sure we have thought much about)
</blockquote></details>

Ah, ok then. Yes, I see there is a comment on the product doc sync.dataInSync property - perhaps just an ambiguous choice of name here. Happy then as it is just referring to a bad state rather than something in progress.

**Review by nigel-wells — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1742)* status: all files reviewed, 1 unresolved discussion (waiting on @RaymondLuong3)

___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.html` line 130 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/1742#-NQcW7DF5XSLq6M4o9Vb:-NQcW7DG5NUZL9YTW7Ok:b-q984v3) ([raw file](https://github.com/sillsdev/web-xforge/blob/285e9e866de33ceee028751149a0d0a13ea40fbf/src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.html#L130)):*
> ```HTML
>               <button mat-flat-button (click)="insertNote()" color="accent">
>                 <mat-icon>add_comment</mat-icon>
>                 {{ t("insert_note") }}
> ```

Adding a note here based on recent discussions with @Nateowami around preferring "Add comment" instead of changing to "Insert note".

**Review by RaymondLuong3 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1742)* status: 1 of 5 files reviewed, 1 unresolved discussion (waiting on @Nateowami and @nigel-wells)

___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.html` line 130 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/1742#-NQcW7DF5XSLq6M4o9Vb:-NR4Bz0r2yzxve5EmLqv:bm9gs7p) ([raw file](https://github.com/sillsdev/web-xforge/blob/285e9e866de33ceee028751149a0d0a13ea40fbf/src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.html#L130)):*
<details><summary><i>Previously, nigel-wells (Nigel Wells) wrote…</i></summary><blockquote>

Adding a note here based on recent discussions with @Nateowami around preferring "Add comment" instead of changing to "Insert note".
</blockquote></details>

Thanks for checking this. I've updated the component to use the consistent wording for translators or reviewers

**Review by nigel-wells — CHANGES_REQUESTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1742)* status: 1 of 5 files reviewed, 1 unresolved discussion (waiting on @Nateowami)

___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.html` line 130 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/1742#-NQcW7DF5XSLq6M4o9Vb:-NR5nR5v7rSrBfJorxSQ:b-1mniri) ([raw file](https://github.com/sillsdev/web-xforge/blob/285e9e866de33ceee028751149a0d0a13ea40fbf/src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.html#L130)):*
<details><summary><i>Previously, RaymondLuong3 (Raymond Luong) wrote…</i></summary><blockquote>

Thanks for checking this. I've updated the component to use the consistent wording for translators or reviewers
</blockquote></details>

I discussed this with Nathaniel and confirmed we'll stick with "Comment" rather than "Note" on Scripture Forge as the focus is now on the commenter.

**Review by nigel-wells — APPROVED** [review]
:lgtm:

> Reviewed 4 of 4 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1742#-:-NR_8VbR-rOSxnW2_CWh:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @RaymondLuong3)

**Pull request merged**
