### PR TITLE
SF-1092 Update to Angular 10

### PR DESCRIPTION
**Pull request by Nateowami**
The individual steps are broken down into separate commits.

See https://update.angular.io/?l=3&v=9.1-10.2

---
This change is [Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/904)

### CODE REVIEW

**Review by irahopkinson — DISMISSED** [review]
Looks good although I have run out of time to run the branch. It would be good to have at least someone else run the branch.

> Reviewed 72 of 72 files at r1.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/904#-:-MQRTuFU90w8Q5G9qc7a:blv5z8t)* status: all files reviewed, 2 unresolved discussions (waiting on @Nateowami)

___
*[src/SIL.XForge.Scripture/ClientApp/package.json, line 107 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/904#-MQRTHemD4_tJ0oWvtPk:-MQRTHemD4_tJ0oWvtPl:bdz069l) ([raw file](https://github.com/sillsdev/web-xforge/blob/a60cb41d832f49e968a13e754d1112f8465b2cd3/src/SIL.XForge.Scripture/ClientApp/package.json#L107)):*
> ```
> "typescript": "~4.0.5",
> ```
Although this is set here, the `package-lock.json` is only set to v3.9.7. Your 2nd to last commit drops it from v4.0.5 down to v3.9.7. Any idea what that's about?
___
*[src/SIL.XForge.Scripture/ClientApp/src/xforge-common/error/error.component.spec.ts, line 77 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/904#-MQRT5pB0xKuew1LN_Yl:-MQRT5pB0xKuew1LN_Ym:b-l269tv) ([raw file](https://github.com/sillsdev/web-xforge/blob/a60cb41d832f49e968a13e754d1112f8465b2cd3/src/SIL.XForge.Scripture/ClientApp/src/xforge-common/error/error.component.spec.ts#L77)):*
> ```
> this.overlayContainer = TestBed.inject(OverlayContainer);
> ```
This doesn't appear to be used anymore.

**Review by marksvc — COMMENTED** [review]
I did not review the files. But I checked out the branch on my dev machine, did a RealtimeServer npm i, and did a ClientApp npm i.
I ran frontend and backend. The frontend compiled a bunch of angular etc things "as esm2015". 
My frontend gave a dozen warnings about "CommonJS or AMD dependencies can cause optimization bailouts." to the Terminal.
I ran C# and TS unit tests. Some more angular things were compiled "as esm2015". All tests passed except for my usual failures from checking-audio-recorder.component.spec.ts (I see 6 right now.)
I smoke tested using the web site.

It all looks good. 

> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/904#-:-MQSm1UY5hAcrY39Hb6D:bkfz685)* status: all files reviewed, 2 unresolved discussions (waiting on @Nateowami)

**Review by marksvc — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/904)* status: all files reviewed, 2 unresolved discussions (waiting on @irahopkinson and @Nateowami)

___
*[src/SIL.XForge.Scripture/ClientApp/package.json, line 107 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/904#-MQRTHemD4_tJ0oWvtPk:-MQSqto-6FQBH7L1HUPY:b-56knfl) ([raw file](https://github.com/sillsdev/web-xforge/blob/a60cb41d832f49e968a13e754d1112f8465b2cd3/src/SIL.XForge.Scripture/ClientApp/package.json#L107)):*
<details><summary><i>Previously, irahopkinson (Ira Hopkinson) wrote…</i></summary><blockquote>

> ```
> "typescript": "~4.0.5",
> ```
Although this is set here, the `package-lock.json` is only set to v3.9.7. Your 2nd to last commit drops it from v4.0.5 down to v3.9.7. Any idea what that's about?
</blockquote></details>

FWIW, on my dev machine after doing `npm i` and trying out this patch, my package-lock.json had a change of

```diff
     "typescript": {
-      "version": "3.9.7",
-      "resolved": "https://registry.npmjs.org/typescript/-/typescript-3.9.7.tgz",
-      "integrity": "sha512-BLbiRkiBzAwsjut4x/dsibSTB6yWpwT5qWmC2OfuCg3GgVQCSgMs4vEctYPhsaGtd0AeuuHMkjZ2h2WG8MSzRw==",
+      "version": "4.0.5",
+      "resolved": "https://registry.npmjs.org/typescript/-/typescript-4.0.5.tgz",
+      "integrity": "sha512-ywmr/VrTVCmNTJ6iV2LwIrfG1P+lv6luD8sUJs+2eI9NLGigaN+nUQc13iHqisq7bra9lnmUSYqbJvegraBOPQ==",
       "dev": true
     },
```

**Review by Nateowami — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/904)* status: 69 of 72 files reviewed, 2 unresolved discussions (waiting on @irahopkinson)

___
*[src/SIL.XForge.Scripture/ClientApp/package.json, line 107 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/904#-MQRTHemD4_tJ0oWvtPk:-MQT8Fm_2xp03Y4-6uR2:b5zlcf5) ([raw file](https://github.com/sillsdev/web-xforge/blob/a60cb41d832f49e968a13e754d1112f8465b2cd3/src/SIL.XForge.Scripture/ClientApp/package.json#L107)):*
Thanks for catching this.

The Angular update steps state:
> Angular now requires tslint v6, tslib v2, and TypeScript 3.9. ng update will migrate you automatically.

When I was running into test failures and couldn't figure out the cause, I noticed that the update had in fact installed version 4.0.5. This was one of many incongruities between what the update steps stated, and what I actually observed. So I tried downgrading to 3.9. That turned out to not be the issue, and I forgot to revert it.
___
*[src/SIL.XForge.Scripture/ClientApp/src/xforge-common/error/error.component.spec.ts, line 77 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/904#-MQRT5pB0xKuew1LN_Yl:-MQTL0Cp0ktKuZ2tJm77:b-896fix) ([raw file](https://github.com/sillsdev/web-xforge/blob/a60cb41d832f49e968a13e754d1112f8465b2cd3/src/SIL.XForge.Scripture/ClientApp/src/xforge-common/error/error.component.spec.ts#L77)):*
<details><summary><i>Previously, irahopkinson (Ira Hopkinson) wrote…</i></summary><blockquote>

> ```
> this.overlayContainer = TestBed.inject(OverlayContainer);
> ```
This doesn't appear to be used anymore.
</blockquote></details>

Done.

**Review by irahopkinson — COMMENTED** [review]
:lgtm:

> Reviewed 3 of 3 files at r2.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/904#-:-MQX6kcS7kJ9a-vAI6Qh:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved

**Comment by Nateowami** [comment]
@irahopkinson Pretty sure you meant to leave an approving review, but that was just a comment.

**Review by irahopkinson — APPROVED** [review]
Yes and no. When I added the comment the branch hadn’t been rebased. If you merge this to master before we ship develop to master and QA, please make a PR to merge master to develop. 

> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/904#-:-MQXqDVBBJvLuJNRiJx1:b-6t9lpn)* status: :shipit: complete! all files reviewed, all discussions resolved

**Comment by Nateowami** [comment]
Ah, I see. When are we likely to ship develop to master and QA?

**Comment by irahopkinson** [comment]
Early next week, up to you if you have confidence to include the ng 10 upgrade.

**Pull request merged**
