### PR TITLE
SF-2201 Audio-only questions have text in the questions list

### PR DESCRIPTION
**Pull request by nigel-wells**
* Show default text for questions that only have audio in the question panel

**BEFORE**
image

**AFTER**
image

- - -
This change is [Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/2020)

### CODE REVIEW

**Review by RaymondLuong3 — CHANGES_REQUESTED** [review]
Thanks for making these changes. A I had a few observations

> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/2020#-:-NcZPvfXEzJ_habaDHKp:b-7to78b)* status: all files reviewed, 2 unresolved discussions (waiting on @nigel-wells)

___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-questions/checking-questions.component.ts` line 337 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/2020#-NcZKE0j-MYvDyAVQsgs:-NcZKE0k34UazyUblcCK:b7irb07) ([raw file](https://github.com/sillsdev/web-xforge/blob/e1942728647ea04d2794982f04e6c40c4ce0cc9d/src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-questions/checking-questions.component.ts#L337)):*
> ```XML
> 
>   questionText(questionDoc: QuestionDoc): string {
>     return questionDoc?.data?.text
> ```

I can see that this could be null or it could be the empty string. That might be the best way to handle it. Normally I would suggest being explicit about what you are checking. But I can see questionDoc.data.text != null && questionDoc.data.text !== '' is a bit of a hassle.
What do you think of this, and adding the reference parameter in the json file.



_Code quote (i):_
```XML
questionDoc?.data?.text
```



_Code snippet (ii):_
```XML
    if (questionDoc?.data == null) return '';
    return questionDoc.data.text
      ? questionDoc.data.text
      : questionDoc.data.audioUrl != null 
      ? translate('checking_question.listen_to_question', { reference: this.referenceForDisplay(questionDoc.data.verseRef) })
      : '';
```
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-questions/checking-questions.component.ts` line 358 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/2020#-NcZOiG_2biZ332DBHh1:-NcZOiG_2biZ332DBHh2:b-uzvkdt) ([raw file](https://github.com/sillsdev/web-xforge/blob/e1942728647ea04d2794982f04e6c40c4ce0cc9d/src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-questions/checking-questions.component.ts#L358)):*
> ```XML
> 
>   private referenceForDisplay(questionDoc: QuestionDoc): string {
>     const verseRefData: VerseRefData | undefined = questionDoc?.data?.verseRef;
> ```

I'm not entirely sure that it is a good idea to use toString() to get the verse reference. I checked Arabic, and the verse comes out not looking good.


How about using the localization function in our i18nService.



_Code quote (i):_
```XML
    const verseRefData: VerseRefData | undefined = questionDoc?.data?.
```



_Code snippet (ii):_
```XML
  private referenceForDisplay(verseRefData: VerseRefData): string {
    return this.i18n.localizeReference(toVerseRef(verseRefData));
  }
```

**Review by nigel-wells — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/2020)* status: 0 of 5 files reviewed, 2 unresolved discussions (waiting on @RaymondLuong3)

___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-questions/checking-questions.component.ts` line 337 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/2020#-NcZKE0j-MYvDyAVQsgs:-Nc_dYBf5o-2uPzjYVEP:ba2a4kc) ([raw file](https://github.com/sillsdev/web-xforge/blob/e1942728647ea04d2794982f04e6c40c4ce0cc9d/src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-questions/checking-questions.component.ts#L337)):*
<details><summary><i>Previously, RaymondLuong3 (Raymond Luong) wrote…</i></summary><blockquote>

I can see that this could be null or it could be the empty string. That might be the best way to handle it. Normally I would suggest being explicit about what you are checking. But I can see questionDoc.data.text != null && questionDoc.data.text !== '' is a bit of a hassle.
What do you think of this, and adding the reference parameter in the json file.
</blockquote></details>

Yep, happy with that especially with including the reference in the translate files. I've also updated the other place that has similar logic where I based this code from.
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-questions/checking-questions.component.ts` line 358 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/2020#-NcZOiG_2biZ332DBHh1:-Nc_At8w3vIVEfmj-t_P:b-n3ycqc) ([raw file](https://github.com/sillsdev/web-xforge/blob/e1942728647ea04d2794982f04e6c40c4ce0cc9d/src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-questions/checking-questions.component.ts#L358)):*
<details><summary><i>Previously, RaymondLuong3 (Raymond Luong) wrote…</i></summary><blockquote>

I'm not entirely sure that it is a good idea to use toString() to get the verse reference. I checked Arabic, and the verse comes out not looking good.


How about using the localization function in our i18nService.
</blockquote></details>

I did initially but that made the string too long and the verse was getting cut off. With the verse cut off it made every question read the same and you couldn't distinguish one from the other. Is there a localize reference for the verse ref that keeps it as the short version?

**Review by RaymondLuong3 — CHANGES_REQUESTED** [review]
> Reviewed 5 of 5 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/2020)* status: all files reviewed, 2 unresolved discussions (waiting on @nigel-wells)

___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-questions/checking-questions.component.html` line 19 at r2](https://reviewable.io/reviews/sillsdev/web-xforge/2020#-NccXkv9Bmc8xfW6LnBz:-NccXkv9Bmc8xfW6LnC-:b-8ha1tw) ([raw file](https://github.com/sillsdev/web-xforge/blob/8bbfbe1c01687a867a441b003f24e9f554a9f8b5/src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-questions/checking-questions.component.html#L19)):*
> ```HTML
>       </div>
>       <a
>         *ngIf="getUnreadAnswers(questionDoc)"
> ```

Nit: You could be more explicit and assert the number is greater than 0.



_Code quote:_
```HTML
   *ngIf="getUnreadAnswers(questionDoc)"
```
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-questions/checking-questions.component.ts` line 358 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/2020#-NcZOiG_2biZ332DBHh1:-NccYs9eBeKQVK4QRKq5:b-cjgo8d) ([raw file](https://github.com/sillsdev/web-xforge/blob/e1942728647ea04d2794982f04e6c40c4ce0cc9d/src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-questions/checking-questions.component.ts#L358)):*
<details><summary><i>Previously, nigel-wells (Nigel Wells) wrote…</i></summary><blockquote>

I did initially but that made the string too long and the verse was getting cut off. With the verse cut off it made every question read the same and you couldn't distinguish one from the other. Is there a localize reference for the verse ref that keeps it as the short version?
</blockquote></details>

Because this matter for community checkers who are unfamiliar with the Paratext book codes, we really need to include a useful reference that community checkers will understand. To me, that is more important than the rest of the test. Because of the space limitation, can we just display `Audio Question: Mark 3:5`. Even though that is not consistent with the text that is shown when you select the question, I think it makes sense to do that here.
But if you have other ideas, let me know.

**Review by nigel-wells — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/2020)* status: 2 of 5 files reviewed, 1 unresolved discussion (waiting on @RaymondLuong3)

___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-questions/checking-questions.component.ts` line 358 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/2020#-NcZOiG_2biZ332DBHh1:-Ncef_3P4csWiHY_wnkM:bjm59g1) ([raw file](https://github.com/sillsdev/web-xforge/blob/e1942728647ea04d2794982f04e6c40c4ce0cc9d/src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-questions/checking-questions.component.ts#L358)):*
<details><summary><i>Previously, RaymondLuong3 (Raymond Luong) wrote…</i></summary><blockquote>

Because this matter for community checkers who are unfamiliar with the Paratext book codes, we really need to include a useful reference that community checkers will understand. To me, that is more important than the rest of the test. Because of the space limitation, can we just display `Audio Question: Mark 3:5`. Even though that is not consistent with the text that is shown when you select the question, I think it makes sense to do that here.
But if you have other ideas, let me know.
</blockquote></details>

Good point. I've changed this to now just be the translated reference only. I then added a tooltip which displays the full string. This tooltip is displaying for any audio question even if text was supplied with the question - I figured this was best rather than only showing it on icons that had no text.

**Review by RaymondLuong3 — APPROVED** [review]
> Reviewed 2 of 3 files at r3, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/2020)* status: all files reviewed, 1 unresolved discussion (waiting on @nigel-wells)

___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-questions/checking-questions.component.ts` line 358 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/2020#-NcZOiG_2biZ332DBHh1:-NchMVQUAcQCfmjU2Fs-:b3pm43g) ([raw file](https://github.com/sillsdev/web-xforge/blob/e1942728647ea04d2794982f04e6c40c4ce0cc9d/src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-questions/checking-questions.component.ts#L358)):*
<details><summary><i>Previously, nigel-wells (Nigel Wells) wrote…</i></summary><blockquote>

Good point. I've changed this to now just be the translated reference only. I then added a tooltip which displays the full string. This tooltip is displaying for any audio question even if text was supplied with the question - I figured this was best rather than only showing it on icons that had no text.
</blockquote></details>

Yes, this will be our best option so that it looks good in all languages, and the most useful information is never cut off. Thanks!

**Review by nigel-wells — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/2020)* status: 3 of 5 files reviewed, 1 unresolved discussion (waiting on @github-code-scanning[bot] and @RaymondLuong3)

___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-questions/checking-questions.component.ts` line 26 at r3](https://reviewable.io/reviews/sillsdev/web-xforge/2020#gh-1305085423:-NdS94Oh9AmjqqS5pgqY:b-896fix) ([raw file](https://github.com/sillsdev/web-xforge/blob/033fb179b5797af65ad1f9d4c203a4c5212f5313/src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-questions/checking-questions.component.ts#L26)):*
<details><summary><i>Previously, github-code-scanning[bot] wrote…</i></summary><blockquote>

## Unused variable, import, function or class

Unused import Question.

[Show more details](https://github.com/sillsdev/web-xforge/security/code-scanning/626)
</blockquote></details>

Done.

**Pull request merged**
