### PR TITLE
SF-3020 Add progress and error reporting to draft generation page

### PR DESCRIPTION
**Pull request by RaymondLuong3**
This PR adds progress and error reporting to the draft generation page when applying a draft to a book. The progress and error reporting will not persist on the page, so once a user leaves the page, the information will be gone. If desired, this information can be persisted.

Active
Draft progress adding draft

Success
Draft progress complete

Error
Draft progress error

- - -
This change is [Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/2836)

### CODE REVIEW

**Review by kylebuss — APPROVED** [review]
Great work! 
:lgtm:

> Reviewed 11 of 11 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/2836#-:-OB2O-J2B5dycwiO2PCq:b-6uofi0)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @RaymondLuong3)

**Review by kylebuss — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/2836)* status: all files reviewed, 1 unresolved discussion (waiting on @RaymondLuong3)

___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-apply-progress/draft-apply-progress.component.scss` line 2 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/2836#-OB2PATK6qkzy1c_SyUd:-OB2PATK6qkzy1c_SyUe:b-gjko5h) ([raw file](https://github.com/sillsdev/web-xforge/blob/3157d7e5406c73a132b4416c62232a3fa9c82d54/src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-apply-progress/draft-apply-progress.component.scss#L2)):*
> ```SCSS
> .progress-card {
>   height: 150px;
> ```

nit This could be smaller. It would probably need to expand if we have a long list of chapters but we could probably start with `75px` or maybe `4rem`.



_Code quote:_
```SCSS
height: 150px;
```

**Comment by Nateowami** [comment]
Showing this outside the dialog doesn't make sense to me. It's extremely common to show progress and errors in a dialog that is taking users through a process:



It also means you don't end up with a weird UI state like you described, where leaving and coming back causes the user to lose the progress.

**Comment by RaymondLuong3** [comment]
My thinking of keeping it out of a dialog is that this happens so extremely quickly that a dialog really is not needed. Just like when we load pages and show a loading bar at the top of the screen. It makes sense for the dialog for importing questions since there could be hundreds, but it takes typically less than 5 seconds to import chapters for a book.

**Comment by Nateowami** [comment]
How about a quick progress bar, and then a "all chapters imported successfully" message, and then a close button the dialog? It then gives a very logical place to show any errors.

**Comment by Nateowami** [comment]
> this happens so extremely quickly

On localhost and fast networks, or on user machines? It's possible it really is fast on all of them, but I don't think it's a safe assumption.

**Comment by RaymondLuong3** [comment]
Ok, I can convert the progress component to open in a dialog.

**Comment by Nateowami** [comment]
This is a good improvement, but I'm seeing this for several seconds when running this locally (with zero network delay), and I would assume it would be worse on users' machines:

**Review by kylebuss — APPROVED** [review]
The change to the dialog progress looks nice. Thanks for working on this!

> Reviewed 10 of 14 files at r3, 5 of 5 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/2836#-:-OBb_FxHDPK_7ZldNfyu:b-vl873j)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @RaymondLuong3)

**Pull request merged**
