### PR TITLE
SF-2219 Support audio timing files from HearThis

### PR DESCRIPTION
**Pull request by RaymondLuong3**
* parse heading labels other than \s
* parse headings with an iteration value
* add checking utils tests
* show the most recently played verse when playing section heading audio

- - -
This change is [Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/2030)

### CODE REVIEW

**Review by pmachapman — CHANGES_REQUESTED** [review]
> Reviewed 5 of 5 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/2030)* status: all files reviewed, 5 unresolved discussions (waiting on @RaymondLuong3)

___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking.utils.ts` line 70 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/2030#-Nd7HwEcDRmK8Orqc_D1:-Nd7HwEcDRmK8Orqc_D2:bpdwqt8) ([raw file](https://github.com/sillsdev/web-xforge/blob/eba4472dfdf7566452eb868cf9188a984a3a5a12/src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking.utils.ts#L70)):*
> ```XML
>   static parseAudioRef(timingData: AudioTiming[], currentTime: number): AudioTextRef | undefined {
>     const index: number = timingData.filter(t => t.from <= currentTime).length - 1;
>     let i: number = index;
> ```

Should this just be:
```ts
let i: number = timingData.filter(t => t.from <= currentTime).length - 1;

```



_Code quote:_
```XML
    const index: number = timingData.filter(t => t.from <= currentTime).length - 1;
    let i: number = index;
```
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking.utils.ts` line 71 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/2030#-Nd7I7Oo1kgJih62bFmd:-Nd7I7Oo1kgJih62bFme:b-f992gf) ([raw file](https://github.com/sillsdev/web-xforge/blob/eba4472dfdf7566452eb868cf9188a984a3a5a12/src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking.utils.ts#L71)):*
> ```XML
>     const index: number = timingData.filter(t => t.from <= currentTime).length - 1;
>     let i: number = index;
>     for (i; i >= 0; i--) {
> ```

Reverse `for` loops always require a double take to figure out what is going on. Are you able to add a short comment explaining what this block is doing?



_Code quote:_
```XML
for (i; i >= 0; i--) {
```
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking.utils.spec.ts` line 20 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/2030#-Nd7ENkCAMenSyz0dRJ4:-Nd7ENkCAMenSyz0dRJ5:b-ljmkvt) ([raw file](https://github.com/sillsdev/web-xforge/blob/eba4472dfdf7566452eb868cf9188a984a3a5a12/src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking.utils.spec.ts#L20)):*
> ```XML
>     { textRef: '3', from: 3.0, to: 4.0 }
>   ];
> }
> ```

What is your rationale for moving these functions here?

I guess my main concern is that because they are not in an obviously named file, like checking-test-utils or test-audio-utils, these might be modified with consequences for other test that the developer did not realize?



_Code quote:_
```XML
export function getAudioTimings(): AudioTiming[] {
  return [
    { textRef: '1', from: 0.0, to: 1.0 },
    { textRef: '2', from: 1.0, to: 2.0 },
    { textRef: '3-4', from: 2.0, to: 3.0 }
  ];
}

export function getAudioTimingWithHeadings(): AudioTiming[] {
  return [
    { textRef: '1', from: 0.0, to: 0.75 },
    { textRef: 's', from: 0.75, to: 1.5 },
    { textRef: '2', from: 1.5, to: 2.25 },
    { textRef: 's', from: 2.25, to: 3.0 },
    { textRef: '3', from: 3.0, to: 4.0 }
  ];
}
```
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking.utils.spec.ts` line 32 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/2030#-Nd7EfSo2MGws1kbiJ92:-Nd7EfSo2MGws1kbiJ93:b2s38km) ([raw file](https://github.com/sillsdev/web-xforge/blob/eba4472dfdf7566452eb868cf9188a984a3a5a12/src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking.utils.spec.ts#L32)):*
> ```XML
>     { textRef: '3', from: 3.0, to: 3.5 }
>   ];
> }
> ```

Should this be in a `TestEnvironment` class - what was your reasoning behind putting it in a function here?



_Code quote:_
```XML
function getAudioTimingFromHearThis(): AudioTiming[] {
  return [
    { textRef: 'c', from: 0.0, to: 0.5 },
    { textRef: 'ms1', from: 0.5, to: 1.0 },
    { textRef: 's1', from: 1.0, to: 1.5 },
    { textRef: '1', from: 1.5, to: 2.0 },
    { textRef: 's2', from: 2.0, to: 2.5 },
    { textRef: '2', from: 2.5, to: 3.0 },
    { textRef: '3', from: 3.0, to: 3.5 }
  ];
}
```
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-scripture-audio-player/checking-scripture-audio-player.component.spec.ts` line 76 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/2030#-Nd7FDy72zCqqBwtPBEE:-Nd7FDy72zCqqBwtPBEF:b-uyqidl) ([raw file](https://github.com/sillsdev/web-xforge/blob/eba4472dfdf7566452eb868cf9188a984a3a5a12/src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-scripture-audio-player/checking-scripture-audio-player.component.spec.ts#L76)):*
> ```XML
>     env.previousRefButton.nativeElement.click();
>     await env.waitForPlayer();
>     // section heading before verse 2
> ```

Is this comment meant to be the same as the preceding one?

Also, should we have a comment like this before each of the `expect()`s?

(I found the change in state a little unclear on first glance because of the similarity of 'Genesis 1:1' and 'Genesis 1:2').



_Code quote:_
```XML
// section heading before verse 2
```

**Review by pmachapman — APPROVED** [review]
> Reviewed 4 of 4 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/2030)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @RaymondLuong3)

**Review by pmachapman — CHANGES_REQUESTED** [review]
> Reviewed 4 of 5 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/2030)* status: 6 of 7 files reviewed, 1 unresolved discussion (waiting on @RaymondLuong3)

___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-scripture-audio-player/checking-scripture-audio-player.component.ts` line 49 at r3](https://reviewable.io/reviews/sillsdev/web-xforge/2030#-NdgTuwv9LbJebCMUWt_:-NdgTuwv9LbJebCMUWta:buy752n) ([raw file](https://github.com/sillsdev/web-xforge/blob/6c4e9d75af76520c881243e82d7e7350e4cca38e/src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-scripture-audio-player/checking-scripture-audio-player.component.ts#L49)):*
> ```XML
>   private get currentVerseLabel(): string {
>     if (this._textDocId == null) return '';
>     const currentTime: number = this.audioPlayer?.audio?.currentTime || 0;
> ```

Should this be:
```
const currentTime: number \= this.audioPlayer?.audio?.currentTime ?? 0;
```

My understanding is that we should only use  `||` if we want the right hand value to be used when the left hand value is 0 or an empty string, in addition to null or undefined (as per `??`)?



_Code quote:_
```XML
const currentTime: number = this.audioPlayer?.audio?.currentTime || 0;
```

**Review by RaymondLuong3 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/2030)* status: 5 of 7 files reviewed, 1 unresolved discussion (waiting on @pmachapman)

___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-scripture-audio-player/checking-scripture-audio-player.component.ts` line 49 at r3](https://reviewable.io/reviews/sillsdev/web-xforge/2030#-NdgTuwv9LbJebCMUWt_:-NdgZyDBAu2j020YhbPp:bjgzsje) ([raw file](https://github.com/sillsdev/web-xforge/blob/6c4e9d75af76520c881243e82d7e7350e4cca38e/src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-scripture-audio-player/checking-scripture-audio-player.component.ts#L49)):*
<details><summary><i>Previously, pmachapman (Peter Chapman) wrote…</i></summary><blockquote>

Should this be:
```
const currentTime: number \= this.audioPlayer?.audio?.currentTime ?? 0;
```

My understanding is that we should only use  `||` if we want the right hand value to be used when the left hand value is 0 or an empty string, in addition to null or undefined (as per `??`)?
</blockquote></details>

You are right. Good catch.

**Review by pmachapman — APPROVED** [review]
> Reviewed 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/2030)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @RaymondLuong3)

**Pull request merged**
