### PR TITLE
SF-1821 Confirm before deleting answers

### PR DESCRIPTION
**Pull request by Nateowami**
- - -
This change is [Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1606)

### CODE REVIEW

**Review by nigel-wells — CHANGES_REQUESTED** [review]
I was thinking this would be handy while I was working on my other task.

> Reviewed 5 of 5 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1606#-:-NHfi6En9u9NUJ7qxKoy:bfjbqnr)* status: all files reviewed, 2 unresolved discussions (waiting on @Nateowami)

___
*[`src/SIL.XForge.Scripture/ClientApp/src/xforge-common/dialog.service.ts` line 45 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/1606#-NHfga8i7Qc2-5inF5uc:-NHfga8j2cWlRBoug1LA:bb15s71) ([raw file](https://github.com/sillsdev/web-xforge/blob/b7ae44c57452e9452c4454fbd84388e7b5b3badc/src/SIL.XForge.Scripture/ClientApp/src/xforge-common/dialog.service.ts#L45)):*
> ```XML
>     negative?: string | Observable<string>
>   ): Promise<boolean> {
>     negative = negative == null ? this.i18n.translate('edit_name_dialog.cancel') : this.ensureLocalized(negative);
> ```

Could be `negative = this.ensureLocalized(negative ?? 'edit_name_dialog.cancel');`

Also, why are we using `edit_name_dialog`? Has this been merged from other dialogs?
___
*[`src/SIL.XForge.Scripture/ClientApp/src/xforge-common/dialog.service.ts` line 65 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/1606#-NHfh39uAQoMAQdYAOvg:-NHfh39uAQoMAQdYAOvh:b6vntkv) ([raw file](https://github.com/sillsdev/web-xforge/blob/b7ae44c57452e9452c4454fbd84388e7b5b3badc/src/SIL.XForge.Scripture/ClientApp/src/xforge-common/dialog.service.ts#L65)):*
> ```XML
>    */
>   async message(message: string | Observable<string>, close?: string | Observable<string>): Promise<void> {
>     const closeText = close instanceof Observable ? close : this.i18n.translate(close ?? 'dialog.close');
> ```

Could be `const closeText = this.ensureLocalized(close ??  'dialog.close');`



_Code quote:_
```XML
const closeText = close instanceof Observable ? close : this.i18n.translate(close ?? 'dialog.close');
```

**Review by Nateowami — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1606)* status: 3 of 5 files reviewed, 2 unresolved discussions (waiting on @nigel-wells)

___
*[`src/SIL.XForge.Scripture/ClientApp/src/xforge-common/dialog.service.ts` line 45 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/1606#-NHfga8i7Qc2-5inF5uc:-NI0QLd29ndbKkwXG_GA:b-sut9c8) ([raw file](https://github.com/sillsdev/web-xforge/blob/b7ae44c57452e9452c4454fbd84388e7b5b3badc/src/SIL.XForge.Scripture/ClientApp/src/xforge-common/dialog.service.ts#L45)):*
<details><summary><i>Previously, nigel-wells (Nigel Wells) wrote…</i></summary><blockquote>

Could be `negative = this.ensureLocalized(negative ?? 'edit_name_dialog.cancel');`

Also, why are we using `edit_name_dialog`? Has this been merged from other dialogs?
</blockquote></details>

Good point. In general we've been using components for namespaces within the loaclization files, so I just "stole" a string from an existing component. But now we have a `dialog` namespace, so I've added `cancel` there and updated this.

And good point about simplifying `negative`; I think it makes enough of a difference that I changed it to be inline rather than separately declaring a variable. Then I moved the values to the front of the object so they can be clearly seen and contrasted.
___
*[`src/SIL.XForge.Scripture/ClientApp/src/xforge-common/dialog.service.ts` line 65 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/1606#-NHfh39uAQoMAQdYAOvg:-NI0PR3n1MdZDolgT-Z5:bcvjgzp) ([raw file](https://github.com/sillsdev/web-xforge/blob/b7ae44c57452e9452c4454fbd84388e7b5b3badc/src/SIL.XForge.Scripture/ClientApp/src/xforge-common/dialog.service.ts#L65)):*
<details><summary><i>Previously, nigel-wells (Nigel Wells) wrote…</i></summary><blockquote>

Could be `const closeText = this.ensureLocalized(close ??  'dialog.close');`
</blockquote></details>

Good idea. Done.

**Review by nigel-wells — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1606)* status: all files reviewed, 1 unresolved discussion (waiting on @Nateowami)

___
*[`src/SIL.XForge.Scripture/ClientApp/src/xforge-common/dialog.service.ts` line 45 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/1606#-NHfga8i7Qc2-5inF5uc:-NI4xdrS2fUJisWcqzKR:b-17sn85) ([raw file](https://github.com/sillsdev/web-xforge/blob/b7ae44c57452e9452c4454fbd84388e7b5b3badc/src/SIL.XForge.Scripture/ClientApp/src/xforge-common/dialog.service.ts#L45)):*
<details><summary><i>Previously, Nateowami (Nathaniel Paulus) wrote…</i></summary><blockquote>

Good point. In general we've been using components for namespaces within the loaclization files, so I just "stole" a string from an existing component. But now we have a `dialog` namespace, so I've added `cancel` there and updated this.

And good point about simplifying `negative`; I think it makes enough of a difference that I changed it to be inline rather than separately declaring a variable. Then I moved the values to the front of the object so they can be clearly seen and contrasted.
</blockquote></details>

That reads much better. Can you update the negative string to use the new `dialog.cancel` string.

**Review by Nateowami — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1606)* status: 4 of 5 files reviewed, 1 unresolved discussion (waiting on @nigel-wells)

___
*[`src/SIL.XForge.Scripture/ClientApp/src/xforge-common/dialog.service.ts` line 45 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/1606#-NHfga8i7Qc2-5inF5uc:-NI5KWaPEOBVGwtNgO8z:b470g1z) ([raw file](https://github.com/sillsdev/web-xforge/blob/b7ae44c57452e9452c4454fbd84388e7b5b3badc/src/SIL.XForge.Scripture/ClientApp/src/xforge-common/dialog.service.ts#L45)):*
<details><summary><i>Previously, nigel-wells (Nigel Wells) wrote…</i></summary><blockquote>

That reads much better. Can you update the negative string to use the new `dialog.cancel` string.
</blockquote></details>

Good catch. I think I just overlooked it last time.

**Review by nigel-wells — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1606#-:-NI5Q0OD4bnSf-FV3t34:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @Nateowami)

**Pull request merged**
