### PR TITLE
SF-2715 Upgrade to Angular 17

### PR DESCRIPTION
**Pull request by pmachapman**
This PR upgrades Angular from version 16 to 17. As a part of this upgrade:
 * TypeScript is upgraded to 5.2.2
 * TypeScript's import sorting is reverted to ignore case (approximating the pre-5.0 setting)
 * RouterTestingModule is removed
 * Some lint warnings in test specs were fixed

- - -
This change is [Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/2449)

### CODE REVIEW

**Review by Nateowami — COMMENTED** [review]
> Reviewed 38 of 38 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/2449)* status: all files reviewed, 1 unresolved discussion (waiting on @pmachapman)

___
*[`.gitignore` line 6 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/2449#-NxO-JAyAm7FTm0ERHaF:-NxO-JAyAm7FTm0ERHaG:bj3z7ig) ([raw file](https://github.com/sillsdev/web-xforge/blob/8bbddff9b375cc2f6cba5f7ff55682bc67199f6f/.gitignore#L6)):*
> ```ignore
> .externalToolBuilders
> .idea/
> .nx
> ```

I don't understand why this was added. Did Angular add it for completeness?

**Review by pmachapman — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/2449)* status: all files reviewed, 1 unresolved discussion (waiting on @Nateowami)

___
*[`.gitignore` line 6 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/2449#-NxO-JAyAm7FTm0ERHaF:-NxOyoXQ1s29tZ3xJJTN:bkdmt73) ([raw file](https://github.com/sillsdev/web-xforge/blob/8bbddff9b375cc2f6cba5f7ff55682bc67199f6f/.gitignore#L6)):*
<details><summary><i>Previously, Nateowami (Nathaniel Paulus) wrote…</i></summary><blockquote>

I don't understand why this was added. Did Angular add it for completeness?
</blockquote></details>

If you run `npm ci`, a file will be created - "src/SIL.XForge.Scripture/ClientApp/.nx/cache/18.3.4-nx.win32-x64-msvc.node".

This used to be in the npm cache, but was moved - see https://github.com/nrwl/nx/discussions/20605

**Review by Nateowami — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/2449)* status: all files reviewed, 1 unresolved discussion (waiting on @pmachapman)

___
*[`.gitignore` line 6 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/2449#-NxO-JAyAm7FTm0ERHaF:-NxP6kFmCrVAxWNw0DZY:b2aonyy) ([raw file](https://github.com/sillsdev/web-xforge/blob/8bbddff9b375cc2f6cba5f7ff55682bc67199f6f/.gitignore#L6)):*
<details><summary><i>Previously, pmachapman (Peter Chapman) wrote…</i></summary><blockquote>

If you run `npm ci`, a file will be created - "src/SIL.XForge.Scripture/ClientApp/.nx/cache/18.3.4-nx.win32-x64-msvc.node".

This used to be in the npm cache, but was moved - see https://github.com/nrwl/nx/discussions/20605
</blockquote></details>

Ah, OK. I didn't realize the `.gitignore` would apply to sub-directories.

**Comment by Nateowami** [comment]
We need to upgrade Node on the TeamCity agent before merging this so the tests will pass.

**Review by Nateowami — APPROVED** [review]
> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/2449)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @pmachapman)

**Comment by Nateowami** [comment]
@pmachapman Somehow I'm only just now noticing that we didn't upgrade @angular/material at the same time as Angular. Do you know why that was? Was there a technical problem I've forgotten about that just didn't get documented on this PR?

**Comment by pmachapman** [comment]
> @pmachapman Somehow I'm only just now noticing that we didn't upgrade @angular/material at the same time as Angular. Do you know why that was? Was there a technical problem I've forgotten about that just didn't get documented on this PR?

Angular Material 17 removed the Material Legacy Components. We need to remove our use of these before upgrading Material. See https://blog.angular.dev/introducing-angular-v17-4d7033312e4b

**Comment by pmachapman** [comment]
> @pmachapman Somehow I'm only just now noticing that we didn't upgrade @angular/material at the same time as Angular. Do you know why that was? Was there a technical problem I've forgotten about that just didn't get documented on this PR?

@Nateowami Angular Material 17 removed the Legacy Components - we needed to remove our use of these before upgrading Material. See https://blog.angular.dev/introducing-angular-v17-4d7033312e4b

**Pull request merged**
