### PR TITLE
hotfix: SF-2865 Fix nav to open 'Auto Draft' tab from draft gen (#2601)

### PR DESCRIPTION
**Pull request by marksvc**
(cherry picked from commit 5b171944541fb3f116aef92d5e3cd20b8a0799e4)

- - -
This change is [Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/2609)

### CODE REVIEW

**Comment by marksvc** [comment]
(Hmm, I guess I don't do this very often, but I think this is the right way to cherry-pick to live.)

**Comment by Nateowami** [comment]
@marksvc While I'm not the greatest fan of the `keyword: ` style of commit message, I think we need to make it *really* obvious when a hotfix is a hotfix, so I've updated the title.

**Review by Nateowami — APPROVED** [review]
> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/2609)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @marksvc)

**Comment by marksvc** [comment]
@Nateowami Sounds good. Thank you.

**Pull request merged**
