### PR TITLE
SF-2516 Remove project selector from connect project page

### PR DESCRIPTION
**Pull request by RaymondLuong3**
This change removes the project selector from the connect project page since it is no longer expected that users will be updating which project they intend to connect to.
Connect project connect
Connect project join

- - -
This change is [Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/2635)

### CODE REVIEW

**Comment by Nateowami** [comment]
Why does it still take some time for the page to load? Instead of passing a Paratext project id, can't you pass all the information needed about the project to connect from the my projects page, to this component, thereby skipping the delay waiting for the registry to respond?

**Comment by RaymondLuong3** [comment]
It is possible that we can remove some logic for loading things from Paratext, but we still need to load projects and resources when users connect for the first time since these are needed so a user can set a source text.
Additionally, we need to hit the "projects" endpoint to access connectable paratext projects so we can get the full name of the project. This could be resolved by passing it in as an additional parameter. That wouldn't be difficult, I can do that.

**Comment by Nateowami** [comment]
Yes, that's true; we do need the full list. However, on current master it doesn't wait for the list of resources to make the component mostly functional. It waits for the list of projects, but if the resources take longer, the page loads before they're fetched. Now that projects are only needed in the same context as resources, it could do that for both of them.

**Comment by RaymondLuong3** [comment]
I have updated the PR to account for when there is no need to get additional projects and resources in the event that the user is just joining an existing project. The my projects page will pass in the project meta data so there is no reason for accessing projects and resources.

**Comment by marksvc** [comment]
If helpful, a diff of another time working on removing the project selector from Connect Project component can be found at 
https://github.com/sillsdev/web-xforge/pull/2441/commits/c76fdf33bcf7ce8eeb020b85ddcac3f10a3a3960 and 
https://github.com/sillsdev/web-xforge/pull/2441/commits/2d16e64e19bc4b07fa3195bbb34ad564183b8460

**Comment by Nateowami** [comment]
@RaymondLuong3 That's a great improvement I didn't even think of. However, I still think we can dramatically improve page load time by not waiting on the projects, just like we don't wait on the resources. See the `populateProjectList()` method.

**Comment by RaymondLuong3** [comment]
Thanks for the suggestion. I have made it so the page is instantly available for both joining and connecting. In the case of connecting, the only thing that waits for the projects to load is the source text input field and the connect button. Apart from that, all settings inputs can be interacted with immediately.

**Review by nigel-wells — CHANGES_REQUESTED** [review]
Always nice to remove so much code. I think we could improve the "Join" flow a bit more. I've I'm Joining then I get presented with a screen that seems a bit pointless along with a "Connect" button which is different from the connect button on the projects screen. Instead, if this user can't do anything other than click the connect button then how about we automate the whole thing and send them straight to the project without having to interact any further?


> Reviewed 7 of 7 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/2635#-:-O3VC-Ef1T__6vTin8ZQ:b-baquqa)* status: all files reviewed, 7 unresolved discussions (waiting on @RaymondLuong3)

___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/connect-project/connect-project.component.ts` line 102 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/2635#-O3V8wfa0GSNFfs595AE:-O3V8wfa0GSNFfs595AF:b-k0wqu6) ([raw file](https://github.com/sillsdev/web-xforge/blob/af444afd8ff7f28421251c03607da1c9eeca1ef4/src/SIL.XForge.Scripture/ClientApp/src/app/connect-project/connect-project.component.ts#L102)):*
> ```XML
> 
>   get projects(): ParatextProject[] {
>     return this.projectsFromParatext != null ? this.projectsFromParatext : [];
> ```

Could be simplified to `return this.projectsFromParatext ?? [];`
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/connect-project/connect-project.component.ts` line 105 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/2635#-O3V7_252zaS-AqkkBGu:-O3V7_252zaS-AqkkBGv:b-gcb4mf) ([raw file](https://github.com/sillsdev/web-xforge/blob/af444afd8ff7f28421251c03607da1c9eeca1ef4/src/SIL.XForge.Scripture/ClientApp/src/app/connect-project/connect-project.component.ts#L105)):*
> ```XML
>   }
> 
>   get translationSuggestionsEnabled(): boolean {
> ```

nit Can you remove this while you're here as it isn't used any more
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/connect-project/connect-project.component.ts` line 119 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/2635#-O3V9HgQ7jf0c3-3W1ym:-O3V9HgQ7jf0c3-3W1yn:b8s5zkp) ([raw file](https://github.com/sillsdev/web-xforge/blob/af444afd8ff7f28421251c03607da1c9eeca1ef4/src/SIL.XForge.Scripture/ClientApp/src/app/connect-project/connect-project.component.ts#L119)):*
> ```XML
>   get projectTitle(): string {
>     if (this.projectMetadata == null) return '';
>     return `${this.projectMetadata.shortName} - ${this.projectMetadata.name}`;
> ```

Would be beneficial to still use `projectLabel` to keep the label consistent with project select autocomplete component otherwise the utility is only ever used with the project auto complete component - there may be some logic in that utility that you need to ensure is still accounted for here as well.
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/connect-project/connect-project.component.ts` line 191 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/2635#-O3V7PKF4fKTrnFuuyYB:-O3V7PKF4fKTrnFuuyYC:b-gcb4mf) ([raw file](https://github.com/sillsdev/web-xforge/blob/af444afd8ff7f28421251c03607da1c9eeca1ef4/src/SIL.XForge.Scripture/ClientApp/src/app/connect-project/connect-project.component.ts#L191)):*
> ```XML
>   }
> 
>   translateFromSettings(key: string): string {
> ```

nit Can you remove this while you're here as it isn't used any more
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/connect-project/connect-project.component.spec.ts` line 119 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/2635#-O3VCtz60o48nQTYav1R:-O3VCtz60o48nQTYav1S:b-v8zsj7) ([raw file](https://github.com/sillsdev/web-xforge/blob/af444afd8ff7f28421251c03607da1c9eeca1ef4/src/SIL.XForge.Scripture/ClientApp/src/app/connect-project/connect-project.component.spec.ts#L119)):*
> ```XML
> 
>   it('should redirect to my projects if missing paratext id in params', fakeAsync(() => {
>     const env = new TestEnvironment({ useUndefinedParatextId: true });
> ```

Just a note that I found this variable name odd as by default `paratextId` is already considered undefined in `TestEnvironmentParams`. What if you set `paratextId` to `null` and then in this test you set it to `undefined`?
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/connect-project/connect-project.component.spec.ts` line 467 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/2635#-O3VF0XrDLUWX7QFuwdV:-O3VF0XrDLUWX7QFuwdW:b-g900w0) ([raw file](https://github.com/sillsdev/web-xforge/blob/af444afd8ff7f28421251c03607da1c9eeca1ef4/src/SIL.XForge.Scripture/ClientApp/src/app/connect-project/connect-project.component.spec.ts#L467)):*
> ```XML
>   }
> 
>   get sourceParatextIdControl(): AbstractControl {
> ```

nit  can be deleted
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/connect-project/connect-project.component.spec.ts` line 526 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/2635#-O3VF641CGJogO0X8EUO:-O3VF641CGJogO0X8EUP:b-g900w0) ([raw file](https://github.com/sillsdev/web-xforge/blob/af444afd8ff7f28421251c03607da1c9eeca1ef4/src/SIL.XForge.Scripture/ClientApp/src/app/connect-project/connect-project.component.spec.ts#L526)):*
> ```XML
>   }
> 
>   getMenuItems(menu: DebugElement): DebugElement[] {
> ```

nit  can be deleted

**Comment by Nateowami** [comment]
> how about we automate the whole thing and send them straight to the project without having to interact any further?

I agree, though I'm not sure the user should even get sent to this component. Perhaps the my projects component should call the endpoint to add the user to a project, and then redirect? I don't have a strong opinion either way; just wanting to bring up the possibility for consideration.

**Comment by RaymondLuong3** [comment]
Hmm, I think that would be reasonable to go straight to the project without ever coming to the connect project page. It shouldn't be too much work to make that happen.

**Review by RaymondLuong3 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/2635)* status: 2 of 8 files reviewed, 2 unresolved discussions (waiting on @nigel-wells)

___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/connect-project/connect-project.component.ts` line 102 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/2635#-O3V8wfa0GSNFfs595AE:-O3djthsD3B-tJF8DMrq:b-896fix) ([raw file](https://github.com/sillsdev/web-xforge/blob/af444afd8ff7f28421251c03607da1c9eeca1ef4/src/SIL.XForge.Scripture/ClientApp/src/app/connect-project/connect-project.component.ts#L102)):*
<details><summary><i>Previously, nigel-wells (Nigel Wells) wrote…</i></summary><blockquote>

Could be simplified to `return this.projectsFromParatext ?? [];`
</blockquote></details>

Done.
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/connect-project/connect-project.component.ts` line 119 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/2635#-O3V9HgQ7jf0c3-3W1ym:-O3djzpk7jePP1T-f-i-:by3n4uf) ([raw file](https://github.com/sillsdev/web-xforge/blob/af444afd8ff7f28421251c03607da1c9eeca1ef4/src/SIL.XForge.Scripture/ClientApp/src/app/connect-project/connect-project.component.ts#L119)):*
<details><summary><i>Previously, nigel-wells (Nigel Wells) wrote…</i></summary><blockquote>

Would be beneficial to still use `projectLabel` to keep the label consistent with project select autocomplete component otherwise the utility is only ever used with the project auto complete component - there may be some logic in that utility that you need to ensure is still accounted for here as well.
</blockquote></details>

Done. Good thinking!
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/connect-project/connect-project.component.spec.ts` line 119 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/2635#-O3VCtz60o48nQTYav1R:-O3dk8Nl5lnO5jNE6MGw:b-4e8k5s) ([raw file](https://github.com/sillsdev/web-xforge/blob/af444afd8ff7f28421251c03607da1c9eeca1ef4/src/SIL.XForge.Scripture/ClientApp/src/app/connect-project/connect-project.component.spec.ts#L119)):*
<details><summary><i>Previously, nigel-wells (Nigel Wells) wrote…</i></summary><blockquote>

Just a note that I found this variable name odd as by default `paratextId` is already considered undefined in `TestEnvironmentParams`. What if you set `paratextId` to `null` and then in this test you set it to `undefined`?
</blockquote></details>

Good thinking. that was confusing but I think it is more obvious now that we can pass undefined explicitly.

**Review by nigel-wells — CHANGES_REQUESTED** [review]
That's much better thanks. 
I have observed that it can show the project in a not connected and connected state while joining now. It only lasts a few seconds but it is long enough to make me wonder what has happened as a user.


> Reviewed 7 of 7 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/2635#-:-O3eRjdZD06en-2PY71v:bsc3au0)* status: all files reviewed, 2 unresolved discussions (waiting on @RaymondLuong3)

___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/my-projects/my-projects.component.html` line 107 at r2](https://reviewable.io/reviews/sillsdev/web-xforge/2635#-O3eQPS1BqZxTDcHhryJ:-O3eQPS1BqZxTDcHhryK:b2a06ht) ([raw file](https://github.com/sillsdev/web-xforge/blob/a40e8941e42795710471f917b6f65b36e1a2a250/src/SIL.XForge.Scripture/ClientApp/src/app/my-projects/my-projects.component.html#L107)):*
> ```HTML
>         {{ "connect_project.connect" | transloco }}
>       </a>
>       <button
> ```

Any reason to make this one a `<button>` vs using the `<a>`?
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/my-projects/my-projects.component.spec.ts` line 88 at r2](https://reviewable.io/reviews/sillsdev/web-xforge/2635#-O3eRb8a2kLIXMGxBRbj:-O3eRb8a2kLIXMGxBRbk:b-vsknmy) ([raw file](https://github.com/sillsdev/web-xforge/blob/a40e8941e42795710471f917b6f65b36e1a2a250/src/SIL.XForge.Scripture/ClientApp/src/app/my-projects/my-projects.component.spec.ts#L88)):*
> ```XML
>   }));
> 
>   it('click Join, passes PT project id and SF project id', fakeAsync(() => {
> ```

nit  Can you rename the test to reflect what is now happening

**Review by RaymondLuong3 — COMMENTED** [review]
Thanks. I've added a check to make sure that does not happen.

> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/2635#-:-O3itV13EgcE99PEu2ZA:begsv3x)* status: all files reviewed, 1 unresolved discussion (waiting on @nigel-wells)

___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/my-projects/my-projects.component.html` line 107 at r2](https://reviewable.io/reviews/sillsdev/web-xforge/2635#-O3eQPS1BqZxTDcHhryJ:-O3itYQg6wtsSoaISY2M:b1ql7so) ([raw file](https://github.com/sillsdev/web-xforge/blob/a40e8941e42795710471f917b6f65b36e1a2a250/src/SIL.XForge.Scripture/ClientApp/src/app/my-projects/my-projects.component.html#L107)):*
<details><summary><i>Previously, nigel-wells (Nigel Wells) wrote…</i></summary><blockquote>

Any reason to make this one a `<button>` vs using the `<a>`?
</blockquote></details>

I made it a button instead of an `<a>` since it doesn't actually link to anything so I thought it would make the most sense as a button.

**Review by nigel-wells — APPROVED** [review]
Working as expected now. 
I've left one nit as part of the template syntax conversion - doesn't need to hold up testing though.
:lgtm: 

> Reviewed 4 of 4 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/2635#-:-O3jkbZ55bWcOQoMdvxe:b-72xss4)* status: all files reviewed, 1 unresolved discussion (waiting on @RaymondLuong3)

___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/my-projects/my-projects.component.html` line 107 at r2](https://reviewable.io/reviews/sillsdev/web-xforge/2635#-O3eQPS1BqZxTDcHhryJ:-O3jkZpq22ZsBnS20KUl:bqqapj4) ([raw file](https://github.com/sillsdev/web-xforge/blob/a40e8941e42795710471f917b6f65b36e1a2a250/src/SIL.XForge.Scripture/ClientApp/src/app/my-projects/my-projects.component.html#L107)):*
<details><summary><i>Previously, RaymondLuong3 (Raymond Luong) wrote…</i></summary><blockquote>

I made it a button instead of an `<a>` since it doesn't actually link to anything so I thought it would make the most sense as a button.
</blockquote></details>

Thanks - makes sense.
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/my-projects/my-projects.component.html` line 36 at r3](https://reviewable.io/reviews/sillsdev/web-xforge/2635#-O3jjLOg0SLl1pnusPSa:-O3jjLOg0SLl1pnusPSb:bglp2jr) ([raw file](https://github.com/sillsdev/web-xforge/blob/1678e07d089f1adbd7f77063834457390e5d60d4/src/SIL.XForge.Scripture/ClientApp/src/app/my-projects/my-projects.component.html#L36)):*
> ```HTML
>     </mat-card>
>   }
>   @if (initialLoadingSFProjects) {
> ```

nit  I realize you converted what was there but this if statement can be combined with the one above it.

**Pull request merged**
