### PR TITLE
PtdaSyncAll: Print the chapter diff

### PR DESCRIPTION
**Pull request by marksvc**
- To provide more context for responding to permission failures.

---
This change is [Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/811)

### CODE REVIEW

**Comment by marksvc** [comment]
I updated the code to fix the missing disposes.

**Review by RaymondLuong3 — APPROVED** [review]
Just one comment, but it is non-blocking.

> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/811#-:-MHqOpvtCGdkw4UbvgE1:b-qlkfw1)* status: all files reviewed, 1 unresolved discussion (waiting on @marksvc)

___
*[src/Migrations/PtdaSyncAll/PtdaSyncRunner.cs, line 384 at r2](https://reviewable.io/reviews/sillsdev/web-xforge/811#-MHqOZDe3FLwSabURBvL:-MHqOZDe3FLwSabURBvM:b7yhfio) ([raw file](https://github.com/sillsdev/web-xforge/blob/4a394c7316f91e10d530447b7a234dbfaa2123de/src/Migrations/PtdaSyncAll/PtdaSyncRunner.cs#L384)):*
> ```
> FileName = "/usr/bin/diff",
> ```
Is this already installed on the live server?

**Review by marksvc — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/811)* status: :shipit: complete! all files reviewed, all discussions resolved

___
*[src/Migrations/PtdaSyncAll/PtdaSyncRunner.cs, line 384 at r2](https://reviewable.io/reviews/sillsdev/web-xforge/811#-MHqOZDe3FLwSabURBvL:-MHqU_rFCRT93dh77q0I:brki09s) ([raw file](https://github.com/sillsdev/web-xforge/blob/4a394c7316f91e10d530447b7a234dbfaa2123de/src/Migrations/PtdaSyncAll/PtdaSyncRunner.cs#L384)):*
<details><summary><i>Previously, RaymondLuong3 (Raymond Luong) wrote…</i></summary><blockquote>

> ```
> FileName = "/usr/bin/diff",
> ```
Is this already installed on the live server?
</blockquote></details>

Good point. All the paths in this PR are rather specific, aren't they. 
Yes, /usr/bin/diff is on SF Live, and is probably part of a core OS package. 

Better than how it's done here would be to run `diff` from the PATH, and to gracefully handle its absence. But for our remaining migration work I don't see that as particularly important.

**Review by marksvc — COMMENTED** [review]
I specified `-u` to increase the diff context so we get more information, if that helps us.

> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/811#-:-MHqW2qc9Y0olLJJsKVc:b-rn0urt)* status: 0 of 1 files reviewed, all discussions resolved (waiting on @RaymondLuong3)

**Review by Nateowami — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/811)* status: 0 of 1 files reviewed, all discussions resolved (waiting on @RaymondLuong3)

___
*[src/Migrations/PtdaSyncAll/PtdaSyncRunner.cs, line 384 at r2](https://reviewable.io/reviews/sillsdev/web-xforge/811#-MHqOZDe3FLwSabURBvL:-MHqQ3Q52rtmm6CbJLoU:ben9h71) ([raw file](https://github.com/sillsdev/web-xforge/blob/4a394c7316f91e10d530447b7a234dbfaa2123de/src/Migrations/PtdaSyncAll/PtdaSyncRunner.cs#L384)):*
<details><summary><i>Previously, marksvc wrote…</i></summary><blockquote>

Good point. All the paths in this PR are rather specific, aren't they. 
Yes, /usr/bin/diff is on SF Live, and is probably part of a core OS package. 

Better than how it's done here would be to run `diff` from the PATH, and to gracefully handle its absence. But for our remaining migration work I don't see that as particularly important.
</blockquote></details>

Looks like it comes from the diffutils package:
``` bash
$ dpkg -S /usr/bin/diff
diffutils: /usr/bin/diff
```
Running `apt show diffutils` or visiting https://packages.ubuntu.com/xenial/diffutils shows that this package is marked "essential". The hover text for this on that page says "package manager will refuse to remove this package by default". It seems unlikely that a package that the package manager would refuse to remove wouldn't be installed by default.

**Review by RaymondLuong3 — APPROVED** [review]
Looks like this LGTM alert is not relevant.

> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/811#-:-MHqYkB96HbqQy2z3Qz-:b-renip8)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
