### PR TITLE
SF-1678 Convert scripture view dialogs to angular material

### PR DESCRIPTION
**Pull request by RaymondLuong3**
* convert templates to use angular material
* use dialog service to launch dialogs with scripture views
* add mat flat button styling

Before

image

Text-chooser-before

After

Question Dialog Material

Text-chooser-after

- - -
This change is [Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1469)

### CODE REVIEW

**Review by Nateowami — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1469)* status: 0 of 17 files reviewed, 1 unresolved discussion (waiting on @Nateowami and @RaymondLuong3)

___
*[`src/SIL.XForge.Scripture/ClientApp/src/material-styles.scss` line 84 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/1469#-N9hQQcK9XGLbTa7UfHz:-N9hQQcK9XGLbTa7UfI-:b-yfz7qg) ([raw file](https://github.com/sillsdev/web-xforge/blob/11008962f97bfa9b5bd30cd04f1e03c67a558e4f/src/SIL.XForge.Scripture/ClientApp/src/material-styles.scss#L84)):*
> ```SCSS
> 
> .mat-dialog-content {
>   max-width: 560px;
> ```

This doesn't work very well with the import questions dialog. It really should be wider. I don't think there's a one-size-fits-all solution to dialog width.

I think in most cases dialogs should style their own width.

**Review by Nateowami — COMMENTED** [review]
I also notice that the question dialog form fields are marked as invalid before they are touched (after the first one is touched).

> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1469#-:-N9hVAPQ65i_6Zdk6LGI:bxbjx4)* status: 0 of 17 files reviewed, 1 unresolved discussion (waiting on @Nateowami and @RaymondLuong3)

**Review by RaymondLuong3 — COMMENTED** [review]
I see that now. I'm not sure why it seemed to work before, but I've updated the logic in sfvalidators.ts so that the error state of the scripture end only shows if the scripture start control is valid.

> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1469#-:-N9i0RE4B1U3oeqpe27W:bqxlc1b)* status: 0 of 18 files reviewed, 1 unresolved discussion (waiting on @Nateowami)

___
*[`src/SIL.XForge.Scripture/ClientApp/src/material-styles.scss` line 84 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/1469#-N9hQQcK9XGLbTa7UfHz:-N9i0Kcg00xvo1IsXjGX:bjavccm) ([raw file](https://github.com/sillsdev/web-xforge/blob/11008962f97bfa9b5bd30cd04f1e03c67a558e4f/src/SIL.XForge.Scripture/ClientApp/src/material-styles.scss#L84)):*
<details><summary><i>Previously, Nateowami (Nathaniel Paulus) wrote…</i></summary><blockquote>

This doesn't work very well with the import questions dialog. It really should be wider. I don't think there's a one-size-fits-all solution to dialog width.

I think in most cases dialogs should style their own width.
</blockquote></details>

thanks for the suggestion. I've removed it here and made it component specific.

**Review by Nateowami — CHANGES_REQUESTED** [review]
A few issues. Sorry this is still not a full review, just a cursory look over it.

I'm still seeing that errors are shown even before I've finished selecting a verse:



> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1469#-:-NAFwSF8-wz9FU-5yXlJ:b-28kdu2)* status: 0 of 18 files reviewed, 3 unresolved discussions (waiting on @Nateowami and @RaymondLuong3)

___
*[`src/SIL.XForge.Scripture/ClientApp/src/material-styles.scss` line 83 at r2](https://reviewable.io/reviews/sillsdev/web-xforge/1469#-NAFwzuY79P-RpPjyzix:-NAFwzuY79P-RpPjyziy:b-cevafx) ([raw file](https://github.com/sillsdev/web-xforge/blob/f69fe29260be585315591923ca53afc239117c34/src/SIL.XForge.Scripture/ClientApp/src/material-styles.scss#L83)):*
> ```SCSS
> }
> 
> .mat-flat-button {
> ```

Material has a way of configuring the theme directly, so that you can tell Material what color scheme you want and it will apply the correct colors in the correct places according to your theme.

In our case, if you set `color="primary"` on the button, it gives the right colors. 

In general we should prefer configuring the Material theme over overriding colors using CSS. See `src/SIL.XForge.Scripture/ClientApp/src/material-styles.scss`
___
*[`src/SIL.XForge.Scripture/ClientApp/src/material-styles.scss` line 85 at r2](https://reviewable.io/reviews/sillsdev/web-xforge/1469#-NAFwtPlEgXpYlpYQYhi:-NAFwlP8CpXpyQp7mOOi:b-ps0q8p) ([raw file](https://github.com/sillsdev/web-xforge/blob/f69fe29260be585315591923ca53afc239117c34/src/SIL.XForge.Scripture/ClientApp/src/material-styles.scss#L85)):*
> ```SCSS
> .mat-flat-button {
>   color: #fff;
>   background-color: #343a31;
> ```

Can we not import this from `_variables.scss` so we reduce duplication of values?
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/scripture-chooser-dialog/scripture-chooser-dialog.component.scss` line 10 at r2](https://reviewable.io/reviews/sillsdev/web-xforge/1469#-NAFutkTEl9HtAzG6385:-NAFutkTEl9HtAzG6386:b-61fkep) ([raw file](https://github.com/sillsdev/web-xforge/blob/f69fe29260be585315591923ca53afc239117c34/src/SIL.XForge.Scripture/ClientApp/src/app/scripture-chooser-dialog/scripture-chooser-dialog.component.scss#L10)):*
> ```SCSS
> 
> .dialog-container {
>   min-height: 400px;
> ```

I know you didn't add this line, but it's having a different effect with MatDialog than it did with MdcDialog, which looks kind of odd:

**Review by RaymondLuong3 — COMMENTED** [review]
Ah yes, it appears that the form was mistakenly getting a signal to submit when the scripture chooser dialog opens. I really had to poke around and try different things to get it to work, but I think I got it.

> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1469#-:-NAumYaC9H-6z3mA06GJ:b-umebao)* status: 0 of 18 files reviewed, 3 unresolved discussions (waiting on @Nateowami)

___
*[`src/SIL.XForge.Scripture/ClientApp/src/material-styles.scss` line 83 at r2](https://reviewable.io/reviews/sillsdev/web-xforge/1469#-NAFwzuY79P-RpPjyzix:-NAunoej7dIHnNKQAa3N:b-prt7rf) ([raw file](https://github.com/sillsdev/web-xforge/blob/f69fe29260be585315591923ca53afc239117c34/src/SIL.XForge.Scripture/ClientApp/src/material-styles.scss#L83)):*
<details><summary><i>Previously, Nateowami (Nathaniel Paulus) wrote…</i></summary><blockquote>

Material has a way of configuring the theme directly, so that you can tell Material what color scheme you want and it will apply the correct colors in the correct places according to your theme.

In our case, if you set `color="primary"` on the button, it gives the right colors. 

In general we should prefer configuring the Material theme over overriding colors using CSS. See `src/SIL.XForge.Scripture/ClientApp/src/material-styles.scss`
</blockquote></details>

Good suggestion. It does seem to be working.
___
*[`src/SIL.XForge.Scripture/ClientApp/src/material-styles.scss` line 85 at r2](https://reviewable.io/reviews/sillsdev/web-xforge/1469#-NAFwtPlEgXpYlpYQYhi:-NAunttX1tTbRFf5LD9I:b-w5ckpu) ([raw file](https://github.com/sillsdev/web-xforge/blob/f69fe29260be585315591923ca53afc239117c34/src/SIL.XForge.Scripture/ClientApp/src/material-styles.scss#L85)):*
<details><summary><i>Previously, Nateowami (Nathaniel Paulus) wrote…</i></summary><blockquote>

Can we not import this from `_variables.scss` so we reduce duplication of values?
</blockquote></details>

Not relevant anymore.
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/scripture-chooser-dialog/scripture-chooser-dialog.component.scss` line 10 at r2](https://reviewable.io/reviews/sillsdev/web-xforge/1469#-NAFutkTEl9HtAzG6385:-NAupUk-3fCEUW1BnQfn:b-1h9ahj) ([raw file](https://github.com/sillsdev/web-xforge/blob/f69fe29260be585315591923ca53afc239117c34/src/SIL.XForge.Scripture/ClientApp/src/app/scripture-chooser-dialog/scripture-chooser-dialog.component.scss#L10)):*
<details><summary><i>Previously, Nateowami (Nathaniel Paulus) wrote…</i></summary><blockquote>

I know you didn't add this line, but it's having a different effect with MatDialog than it did with MdcDialog, which looks kind of odd:



</blockquote></details>

Nice catch. Fixed.

**Review by Nateowami — CHANGES_REQUESTED** [review]
I've finally started reviewing the actual changes in this PR. Unfortunately I spent a ton of time confusing text-chooser-dialog with scripture-chooser-dialog and ended up spending a ton of time to just review one component. (I also spent a ton of time fiddling with a layout issue; I've included my recommended solution to it in one of the comments).

Hopefully the other components will go faster.

> Reviewed 3 of 17 files at r1, 1 of 7 files at r2.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1469#-:-NBOXT1_5wBI16McBwCF:b-76zgf9)* status: 4 of 18 files reviewed, 4 unresolved discussions (waiting on @Nateowami and @RaymondLuong3)

___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/text-chooser-dialog/text-chooser-dialog.component.html` line 24 at r3](https://reviewable.io/reviews/sillsdev/web-xforge/1469#-NBOWsKV-mxKlrtl0fDx:-NBOWsKV-mxKlrtl0fDy:br7fizp) ([raw file](https://github.com/sillsdev/web-xforge/blob/2e450306a5951f1a669c46da26b21650af85c8cb/src/SIL.XForge.Scripture/ClientApp/src/app/text-chooser-dialog/text-chooser-dialog.component.html#L24)):*
> ```HTML
>     <mat-dialog-actions align="end">
>       <button mat-button type="button" id="cancel-button" [mat-dialog-close]="'close'">{{ t("cancel") }}</button>
>       <button mat-flat-button type="submit" cdkFocusInitial (click)="submit()">
> ```

I think you probably want to add `color="primary"` to this button.

master | this branch
-----------|----------------
 | 
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/text-chooser-dialog/text-chooser-dialog.component.scss` line 34 at r3](https://reviewable.io/reviews/sillsdev/web-xforge/1469#-NBOS_H79zAi4b-Avugx:-NBOS_H79zAi4b-Avugy:blfzz23) ([raw file](https://github.com/sillsdev/web-xforge/blob/2e450306a5951f1a669c46da26b21650af85c8cb/src/SIL.XForge.Scripture/ClientApp/src/app/text-chooser-dialog/text-chooser-dialog.component.scss#L34)):*
> ```SCSS
> }
> 
> .selection-preview {
> ```

The selection preview is now too short to be usable. It seems that having flex items that have scrollbars causes their heights to not change quite how you might expect.

If you wrap it with a `div` then the `div` will have the right height. You might want to remove the margin-bottom from the `p` element.

**Review by Nateowami — CHANGES_REQUESTED** [review]
> Reviewed 5 of 17 files at r1, 3 of 7 files at r2, 6 of 6 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1469)* status: all files reviewed, 5 unresolved discussions (waiting on @RaymondLuong3)

___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/checking/question-dialog/question-dialog.component.spec.ts` line 277 at r3](https://reviewable.io/reviews/sillsdev/web-xforge/1469#-NBPwgLYAEnKNdddCzND:-NBPwgLYAEnKNdddCzNE:b-duigfk) ([raw file](https://github.com/sillsdev/web-xforge/blob/2e450306a5951f1a669c46da26b21650af85c8cb/src/SIL.XForge.Scripture/ClientApp/src/app/checking/question-dialog/question-dialog.component.spec.ts#L277)):*
> ```XML
>     expect(env.component.scriptureEnd.enabled).toBe(true);
>     expect(env.scriptureEndInputIcon.classList).not.toContain('mat-button-disabled');
>     console.log(env.scriptureEndInputIcon);
> ```

I think maybe you forgot to remove this?
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/scripture-chooser-dialog/scripture-chooser-dialog.component.spec.ts` line 36 at r3](https://reviewable.io/reviews/sillsdev/web-xforge/1469#-NBPxZuO9UJLJl_VF8nh:-NBPxZuO9UJLJl_VF8ni:b-eurkta) ([raw file](https://github.com/sillsdev/web-xforge/blob/2e450306a5951f1a669c46da26b21650af85c8cb/src/SIL.XForge.Scripture/ClientApp/src/app/scripture-chooser-dialog/scripture-chooser-dialog.component.spec.ts#L36)):*
> ```XML
>   afterEach(fakeAsync(() => {
>     while (env.backoutButton != null) {
>       env.click(env.backoutButton);
> ```

What does this do?
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/scripture-chooser-dialog/scripture-chooser-dialog.component.spec.ts` line 576 at r3](https://reviewable.io/reviews/sillsdev/web-xforge/1469#-NBPxbmW-5t9oquunSvP:-NBPxbmW-5t9oquunSvQ:bucs8n4) ([raw file](https://github.com/sillsdev/web-xforge/blob/2e450306a5951f1a669c46da26b21650af85c8cb/src/SIL.XForge.Scripture/ClientApp/src/app/scripture-chooser-dialog/scripture-chooser-dialog.component.spec.ts#L576)):*
> ```XML
>       element!.nativeElement.click();
>       this.fixture.detectChanges();
>       flush();
> ```

This is not actually needed. I'm guessing it was added while working on making the tests pass?

**Review by Nateowami — CHANGES_REQUESTED** [review]
> Reviewed 3 of 3 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1469)* status: all files reviewed, 1 unresolved discussion (waiting on @RaymondLuong3)

___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/scripture-chooser-dialog/scripture-chooser-dialog.component.spec.ts` line 36 at r3](https://reviewable.io/reviews/sillsdev/web-xforge/1469#-NBPxZuO9UJLJl_VF8nh:-NBy3Hm91Zhq8h7qbAc3:b-d7n5gm) ([raw file](https://github.com/sillsdev/web-xforge/blob/2e450306a5951f1a669c46da26b21650af85c8cb/src/SIL.XForge.Scripture/ClientApp/src/app/scripture-chooser-dialog/scripture-chooser-dialog.component.spec.ts#L36)):*
<details><summary><i>Previously, RaymondLuong3 (Raymond Luong) wrote…</i></summary><blockquote>

To close the dialog, we have to back out to the top level book view where the close button is. I'm not sure if that is the best design, but that is what it is currently.
</blockquote></details>

Ah, OK. I assumed the scripture chooser dialog was mocked.
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/text-chooser-dialog/text-chooser-dialog.component.scss` line 34 at r3](https://reviewable.io/reviews/sillsdev/web-xforge/1469#-NBOS_H79zAi4b-Avugx:-NBy3ZbC0pFYSZ2kdDFj:brotqis) ([raw file](https://github.com/sillsdev/web-xforge/blob/2e450306a5951f1a669c46da26b21650af85c8cb/src/SIL.XForge.Scripture/ClientApp/src/app/text-chooser-dialog/text-chooser-dialog.component.scss#L34)):*
<details><summary><i>Previously, RaymondLuong3 (Raymond Luong) wrote…</i></summary><blockquote>

I am having trouble reproducing what you are describing. Could you send a screenshot for me to look at?
</blockquote></details>

**Review by RaymondLuong3 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1469)* status: all files reviewed, 1 unresolved discussion (waiting on @Nateowami)

___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/text-chooser-dialog/text-chooser-dialog.component.scss` line 34 at r3](https://reviewable.io/reviews/sillsdev/web-xforge/1469#-NBOS_H79zAi4b-Avugx:-NCS-DdB-HlN8EAbbSH9:bmt7iyh) ([raw file](https://github.com/sillsdev/web-xforge/blob/2e450306a5951f1a669c46da26b21650af85c8cb/src/SIL.XForge.Scripture/ClientApp/src/app/text-chooser-dialog/text-chooser-dialog.component.scss#L34)):*
<details><summary><i>Previously, Nateowami (Nathaniel Paulus) wrote…</i></summary><blockquote>


</blockquote></details>

Thanks. I see the issue now. Good catch. I've updated the styling now.

**Review by Nateowami — APPROVED** [review]
:lgtm:

> Reviewed 3 of 3 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1469#-:-NCS3cNP46E4Gg9B1XI9:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @RaymondLuong3)

**Review by Nateowami — APPROVED** [review]
> Reviewed 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1469)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @RaymondLuong3)

**Pull request merged**
