### PR TITLE
SF-2593 Replace Skip Audio Persistence by DB with In-Memory

### PR DESCRIPTION
**Pull request by josephmyers**
This change is [Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/2374)

### CODE REVIEW

**Review by pmachapman — CHANGES_REQUESTED** [review]
> Reviewed 16 of 17 files at r1, 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/2374)* status: all files reviewed, 5 unresolved discussions (waiting on @josephmyers)

___
*[`src/RealtimeServer/scriptureforge/services/sf-project-user-config-migrations.ts` line 1 at r2](https://reviewable.io/reviews/sillsdev/web-xforge/2374#-NtSEDki5RTzSjsVQa3U:-NtSEDki5RTzSjsVQa3V:b-qi805e) ([raw file](https://github.com/sillsdev/web-xforge/blob/5080ac86104f1b7cd578bd5b898a07fce7f1261c/src/RealtimeServer/scriptureforge/services/sf-project-user-config-migrations.ts#L1)):*
> ```XML
> import { Doc, ObjectInsertOp, ObjectDeleteOp } from 'sharedb/lib/client';
> ```

NIT: The imports should be sorted:
```ts
import { Doc, ObjectDeleteOp, ObjectInsertOp } from 'sharedb/lib/client';
```



_Code quote:_
```XML
import { Doc, ObjectInsertOp, ObjectDeleteOp } from 'sharedb/lib/client';
```
___
*[`src/RealtimeServer/scriptureforge/services/sf-project-user-config-migrations.ts` line 60 at r2](https://reviewable.io/reviews/sillsdev/web-xforge/2374#-NtSCtNiAiB8JmqsLL-a:-NtSCtNiAiB8JmqsLL-b:b-wuhxny) ([raw file](https://github.com/sillsdev/web-xforge/blob/5080ac86104f1b7cd578bd5b898a07fce7f1261c/src/RealtimeServer/scriptureforge/services/sf-project-user-config-migrations.ts#L60)):*
> ```XML
>   async migrateDoc(doc: Doc): Promise<void> {
>     if (doc.data.audioRefsPlayed !== undefined) {
>       const op: ObjectDeleteOp = { p: ['audioRefsPlayed'], od: [] };
> ```

The `od` value should contain the old value of the property being deleted:
```ts
  async migrateDoc(doc: Doc): Promise<void> {
    const audioRefsPlayed: string[] | undefined = doc.data.audioRefsPlayed;
    if (audioRefsPlayed !== undefined) {
      const op: ObjectDeleteOp = { p: ['audioRefsPlayed'], od: audioRefsPlayed };
      await submitMigrationOp(SFProjectUserConfigMigration5.VERSION, doc, [op]);
    }
  }
```
See `sf-project-migrations.ts` for other examples.



_Code quote:_
```XML
od: []
```
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking.component.spec.ts` line 38 at r2](https://reviewable.io/reviews/sillsdev/web-xforge/2374#-NtSEcOPDrvd5ioptAxf:-NtSEcOPDrvd5ioptAxg:b-9jh2ku) ([raw file](https://github.com/sillsdev/web-xforge/blob/5080ac86104f1b7cd578bd5b898a07fce7f1261c/src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking.component.spec.ts#L38)):*
> ```XML
> import { BehaviorSubject, of, Subject } from 'rxjs';
> import { first } from 'rxjs/operators';
> import { SFProjectProfileDoc } from 'src/app/core/models/sf-project-profile-doc';
> ```

NIT: Thank you for organizing the imports in this file - I really appreciate housekeeping like this!

While you  are here, could you please change this to a relative path, and run Organize Imports again?
```ts
import { SFProjectProfileDoc } from '../../core/models/sf-project-profile-doc';
```



_Code quote:_
```XML
import { SFProjectProfileDoc } from 'src/app/core/models/sf-project-profile-doc';
```
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-answers/checking-question/checking-question.component.ts` line 200 at r2](https://reviewable.io/reviews/sillsdev/web-xforge/2374#-NtSG-0j68wCSQIKIs-5:-NtSG-0j68wCSQIKIs-6:bhdtzi5) ([raw file](https://github.com/sillsdev/web-xforge/blob/5080ac86104f1b7cd578bd5b898a07fce7f1261c/src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-answers/checking-question/checking-question.component.ts#L200)):*
> ```XML
>     const haveListenedToAllVerses = verseRefs.every(v => this._versesListenedTo.has(v.toString()));
> 
>     // Select a question if there is no audio or if all verses have been played already
> ```

Thank you for noticing and correcting this comment!



_Code quote:_
```XML
// Select a question if there is no audio or if all verses have been played already
```
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-answers/checking-question/checking-question.component.spec.ts` line 11 at r2](https://reviewable.io/reviews/sillsdev/web-xforge/2374#-NtSGI3DDFpzFFG2gpmx:-NtSGI3DDFpzFFG2gpmy:b-tn30sw) ([raw file](https://github.com/sillsdev/web-xforge/blob/5080ac86104f1b7cd578bd5b898a07fce7f1261c/src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-answers/checking-question/checking-question.component.spec.ts#L11)):*
> ```XML
> import { lastValueFrom, Subject } from 'rxjs';
> import { takeWhile } from 'rxjs/operators';
> import { AudioPlayer, AudioStatus } from 'src/app/shared/audio/audio-player';
> ```

NIT: Can you please change this to a relative path too, and re-organize imports?
```ts
import { AudioPlayer, AudioStatus } from '../../../../shared/audio/audio-player';
```



_Code quote:_
```XML
import { AudioPlayer, AudioStatus } from 'src/app/shared/audio/audio-player';
```
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-answers/checking-question/checking-question.component.spec.ts` line 110 at r2](https://reviewable.io/reviews/sillsdev/web-xforge/2374#-NtSIEoI7xnVCwiAMnnf:-NtSIEoI7xnVCwiAMnng:b-qkdbk) ([raw file](https://github.com/sillsdev/web-xforge/blob/5080ac86104f1b7cd578bd5b898a07fce7f1261c/src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-answers/checking-question/checking-question.component.spec.ts#L110)):*
> ```XML
>     const newQuestionDoc = mock(QuestionDoc);
>     when(newQuestionDoc.data).thenReturn(instance(newQuestion));
>     env.component.questionDoc = instance(newQuestionDoc);
> ```

I notice this code is substantially duplicated in the following test. Would you be able to refactor this into a method, something like:
```ts
class TestEnvironment {
...
  createQuestionDocWithAudio(verseRef: VerseRefData): void {
    const newQuestion = mock<Question>();
    when(newQuestion.projectRef).thenReturn('project01');
    when(newQuestion.text).thenReturn('another question');
    when(newQuestion.audioUrl).thenReturn('test-audio-player-b.webm');
    when(newQuestion.verseRef).thenReturn(verseRef);
    const newQuestionDoc = mock(QuestionDoc);
    when(newQuestionDoc.data).thenReturn(instance(newQuestion));
    this.component.questionDoc = instance(newQuestionDoc);
  }
...
}
```

And then update this block here to be:
```ts
env.createQuestionDocWithAudio(env.component.questionDoc.data!.verseRef!);
```

Or perhaps it might be simpler to rewrite each case to be something like:
```ts
    env.component.questionDoc = {
      data: {
        audioUrl: 'test-audio-player-b.webm',
        projectRef: 'project01',
        text: 'another question',
        verseRef: env.component.questionDoc.data!.verseRef!
      }
    } as QuestionDoc;
```
But, I notice the other tests use the same mock technique as you use here - so up to you - whichever you think is best!



_Code quote:_
```XML
    const newQuestion = mock<Question>();
    when(newQuestion.projectRef).thenReturn('project01');
    when(newQuestion.text).thenReturn('another question');
    when(newQuestion.audioUrl).thenReturn('test-audio-player-b.webm');
    when(newQuestion.verseRef).thenReturn(env.component.questionDoc.data!.verseRef!);
    const newQuestionDoc = mock(QuestionDoc);
    when(newQuestionDoc.data).thenReturn(instance(newQuestion));
    env.component.questionDoc = instance(newQuestionDoc);
```

**Review by josephmyers — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/2374)* status: 9 of 20 files reviewed, 9 unresolved discussions (waiting on @github-advanced-security[bot] and @pmachapman)

___
*[`src/RealtimeServer/scriptureforge/services/sf-project-user-config-migrations.ts` line 60 at r2](https://reviewable.io/reviews/sillsdev/web-xforge/2374#-NtSCtNiAiB8JmqsLL-a:-NtyTug-AMMfdXF3TXVD:b-2lplmo) ([raw file](https://github.com/sillsdev/web-xforge/blob/5080ac86104f1b7cd578bd5b898a07fce7f1261c/src/RealtimeServer/scriptureforge/services/sf-project-user-config-migrations.ts#L60)):*
<details><summary><i>Previously, pmachapman (Peter Chapman) wrote…</i></summary><blockquote>

The `od` value should contain the old value of the property being deleted:
```ts
  async migrateDoc(doc: Doc): Promise<void> {
    const audioRefsPlayed: string[] | undefined = doc.data.audioRefsPlayed;
    if (audioRefsPlayed !== undefined) {
      const op: ObjectDeleteOp = { p: ['audioRefsPlayed'], od: audioRefsPlayed };
      await submitMigrationOp(SFProjectUserConfigMigration5.VERSION, doc, [op]);
    }
  }
```
See `sf-project-migrations.ts` for other examples.
</blockquote></details>

Ah! Thanks for the info
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking.component.spec.ts` line 38 at r2](https://reviewable.io/reviews/sillsdev/web-xforge/2374#-NtSEcOPDrvd5ioptAxf:-NtyaTpbDFDjkY4L5aL7:b-896fix) ([raw file](https://github.com/sillsdev/web-xforge/blob/5080ac86104f1b7cd578bd5b898a07fce7f1261c/src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking.component.spec.ts#L38)):*
<details><summary><i>Previously, pmachapman (Peter Chapman) wrote…</i></summary><blockquote>

NIT: Thank you for organizing the imports in this file - I really appreciate housekeeping like this!

While you  are here, could you please change this to a relative path, and run Organize Imports again?
```ts
import { SFProjectProfileDoc } from '../../core/models/sf-project-profile-doc';
```
</blockquote></details>

Done.
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking.component.spec.ts` line 32 at r3](https://reviewable.io/reviews/sillsdev/web-xforge/2374#gh-1540514770:-NtyZZ7sCJdlMNlDwyvH:b-896fix) ([raw file](https://github.com/sillsdev/web-xforge/blob/e583b67727662c7f6f198771d40acb9cceb4df3d/src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking.component.spec.ts#L32)):*
<details><summary><i>Previously, github-advanced-security[bot] wrote…</i></summary><blockquote>

## Syntax error

Error: ',' expected.

[Show more details](https://github.com/sillsdev/web-xforge/security/code-scanning/773)
</blockquote></details>

Done.
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking.component.spec.ts` line 2297 at r3](https://reviewable.io/reviews/sillsdev/web-xforge/2374#gh-1540514772:-NtyaVUz73YezyiDQVtb:b-896fix) ([raw file](https://github.com/sillsdev/web-xforge/blob/e583b67727662c7f6f198771d40acb9cceb4df3d/src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking.component.spec.ts#L2297)):*
<details><summary><i>Previously, github-advanced-security[bot] wrote…</i></summary><blockquote>

## Syntax error

Error: ')' expected.

[Show more details](https://github.com/sillsdev/web-xforge/security/code-scanning/774)
</blockquote></details>

Done.
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking.component.spec.ts` line 2308 at r3](https://reviewable.io/reviews/sillsdev/web-xforge/2374#gh-1540514774:-NtyaVvt5_Y7WL6S25VH:b-896fix) ([raw file](https://github.com/sillsdev/web-xforge/blob/e583b67727662c7f6f198771d40acb9cceb4df3d/src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking.component.spec.ts#L2308)):*
<details><summary><i>Previously, github-advanced-security[bot] wrote…</i></summary><blockquote>

## Syntax error

Error: ')' expected.

[Show more details](https://github.com/sillsdev/web-xforge/security/code-scanning/775)
</blockquote></details>

Done.
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking.component.spec.ts` line 2323 at r3](https://reviewable.io/reviews/sillsdev/web-xforge/2374#gh-1540514778:-NtyaZDC4eoqOaTAtWw6:b-896fix) ([raw file](https://github.com/sillsdev/web-xforge/blob/e583b67727662c7f6f198771d40acb9cceb4df3d/src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking.component.spec.ts#L2323)):*
<details><summary><i>Previously, github-advanced-security[bot] wrote…</i></summary><blockquote>

## Syntax error

Error: ')' expected.

[Show more details](https://github.com/sillsdev/web-xforge/security/code-scanning/776)
</blockquote></details>

Done.
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking.component.spec.ts` line 2340 at r3](https://reviewable.io/reviews/sillsdev/web-xforge/2374#gh-1540514779:-NtyaZk928PhB1K9CPdJ:b-896fix) ([raw file](https://github.com/sillsdev/web-xforge/blob/e583b67727662c7f6f198771d40acb9cceb4df3d/src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking.component.spec.ts#L2340)):*
<details><summary><i>Previously, github-advanced-security[bot] wrote…</i></summary><blockquote>

## Syntax error

Error: ')' expected.

[Show more details](https://github.com/sillsdev/web-xforge/security/code-scanning/777)
</blockquote></details>

Done.
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-answers/checking-question/checking-question.component.spec.ts` line 11 at r2](https://reviewable.io/reviews/sillsdev/web-xforge/2374#-NtSGI3DDFpzFFG2gpmx:-NtyasoYBekS6bq1tL6j:b-jndf28) ([raw file](https://github.com/sillsdev/web-xforge/blob/5080ac86104f1b7cd578bd5b898a07fce7f1261c/src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-answers/checking-question/checking-question.component.spec.ts#L11)):*
<details><summary><i>Previously, pmachapman (Peter Chapman) wrote…</i></summary><blockquote>

NIT: Can you please change this to a relative path too, and re-organize imports?
```ts
import { AudioPlayer, AudioStatus } from '../../../../shared/audio/audio-player';
```
</blockquote></details>

Done. When I use VS to add missing imports for me, I think it defaults to absolute pathing.
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-answers/checking-question/checking-question.component.spec.ts` line 110 at r2](https://reviewable.io/reviews/sillsdev/web-xforge/2374#-NtSIEoI7xnVCwiAMnnf:-NtybVr_1OJ7Hs9R_cF_:bv4wo5a) ([raw file](https://github.com/sillsdev/web-xforge/blob/5080ac86104f1b7cd578bd5b898a07fce7f1261c/src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-answers/checking-question/checking-question.component.spec.ts#L110)):*
<details><summary><i>Previously, pmachapman (Peter Chapman) wrote…</i></summary><blockquote>

I notice this code is substantially duplicated in the following test. Would you be able to refactor this into a method, something like:
```ts
class TestEnvironment {
...
  createQuestionDocWithAudio(verseRef: VerseRefData): void {
    const newQuestion = mock<Question>();
    when(newQuestion.projectRef).thenReturn('project01');
    when(newQuestion.text).thenReturn('another question');
    when(newQuestion.audioUrl).thenReturn('test-audio-player-b.webm');
    when(newQuestion.verseRef).thenReturn(verseRef);
    const newQuestionDoc = mock(QuestionDoc);
    when(newQuestionDoc.data).thenReturn(instance(newQuestion));
    this.component.questionDoc = instance(newQuestionDoc);
  }
...
}
```

And then update this block here to be:
```ts
env.createQuestionDocWithAudio(env.component.questionDoc.data!.verseRef!);
```

Or perhaps it might be simpler to rewrite each case to be something like:
```ts
    env.component.questionDoc = {
      data: {
        audioUrl: 'test-audio-player-b.webm',
        projectRef: 'project01',
        text: 'another question',
        verseRef: env.component.questionDoc.data!.verseRef!
      }
    } as QuestionDoc;
```
But, I notice the other tests use the same mock technique as you use here - so up to you - whichever you think is best!
</blockquote></details>

Thanks. I'm used to mocking things in C# and historically not being able to do fancy stuff like this partial object casting (or whatever this is).
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-answers/checking-question/checking-question.stories.ts` line 37 at r3](https://reviewable.io/reviews/sillsdev/web-xforge/2374#gh-1540514769:-Ntybm5lCnTT7HUn06w2:b-896fix) ([raw file](https://github.com/sillsdev/web-xforge/blob/e583b67727662c7f6f198771d40acb9cceb4df3d/src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-answers/checking-question/checking-question.stories.ts#L37)):*
<details><summary><i>Previously, github-advanced-security[bot] wrote…</i></summary><blockquote>

## Syntax error

Error: ')' expected.

[Show more details](https://github.com/sillsdev/web-xforge/security/code-scanning/772)
</blockquote></details>

Done.
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking-overview/checking-overview.component.spec.ts` line 773 at r3](https://reviewable.io/reviews/sillsdev/web-xforge/2374#gh-1540514780:-NtybmdDEp45HLjS2I6Q:b-896fix) ([raw file](https://github.com/sillsdev/web-xforge/blob/e583b67727662c7f6f198771d40acb9cceb4df3d/src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking-overview/checking-overview.component.spec.ts#L773)):*
<details><summary><i>Previously, github-advanced-security[bot] wrote…</i></summary><blockquote>

## Syntax error

Error: ')' expected.

[Show more details](https://github.com/sillsdev/web-xforge/security/code-scanning/778)
</blockquote></details>

Done.

**Review by pmachapman — APPROVED** [review]
:lgtm:

> Reviewed 12 of 12 files at r4, all commit messages.
> Dismissed @github-advanced-security[bot] from 6 discussions.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/2374#-:-Nu08GnO9LhxcnZc29bT:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @github-advanced-security[bot])

**Review by pmachapman — APPROVED** [review]
> Dismissed @github-advanced-security[bot] from a discussion.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/2374)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @josephmyers)

**Pull request merged**
