### PR TITLE
SF-2914 Remove Bootstrap

### PR DESCRIPTION
**Pull request by nigel-wells**
* Remove bootstrap package
* Refactor show/hide helper classes to use the same @media query logic
* Change over from @import to @use

- - -
This change is [Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/2733)

### CODE REVIEW

**Comment by Nateowami** [comment]
Thanks for making this change. I thought Bootstrap was only providing Sass helper methods and therefore wasn't increasing our build size, but I see the CSS file dropped in size by about 25%. 

Before
```
Initial chunk files           | Names         |  Raw size | Estimated transfer size
main.efe2462ec082bae7.js      | main          |   3.76 MB |               667.95 kB
styles.32ce86c812c3464d.css   | styles        | 163.38 kB |                15.89 kB
polyfills.ee5bc8517874ba3f.js | polyfills     |  58.43 kB |                17.82 kB
runtime.c7fc43bd7fe37f91.js   | runtime       |   1.79 kB |               942 bytes

                              | Initial total |   3.98 MB |               702.58 kB
```

After
```
Initial chunk files           | Names         |  Raw size | Estimated transfer size
main.fc0d046f29f0b337.js      | main          |   3.68 MB |               663.75 kB
styles.f8cf5c68c6472a02.css   | styles        | 123.12 kB |                13.19 kB
polyfills.ee5bc8517874ba3f.js | polyfills     |  58.43 kB |                17.82 kB
runtime.c7fc43bd7fe37f91.js   | runtime       |   1.79 kB |               942 bytes

                              | Initial total |   3.86 MB |               695.68 kB
```

**Comment by nigel-wells** [comment]
That's a nice saving! It may have also been from swapping out the `@import` to `@use` as well that helped reduce it down.

**Comment by Nateowami** [comment]
This is breaking the tab layout.

**Comment by nigel-wells** [comment]
I've added in the missing styles for this. There was some reset styles applied to all elements that I've now applied. I figured this can be an initial step to get Bootstrap out sooner. We can then consider more when it comes to the new theming.

I also tweaked the audio dialog better to work with button widths in different languages.

**Review by Nateowami — CHANGES_REQUESTED** [review]
Thanks.

> Reviewed 13 of 16 files at r1, 3 of 4 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/2733#-:-O7oHn7b0oj5p__oAiGW:b-ucfkn4)* status: 16 of 18 files reviewed, 1 unresolved discussion (waiting on @nigel-wells)

___
*[`src/SIL.XForge.Scripture/ClientApp/src/styles.scss` line 133 at r2](https://reviewable.io/reviews/sillsdev/web-xforge/2733#-O7oGV8HAWv9VDmPvoGD:-O7oGV8HAWv9VDmPvoGE:bj0uu5r) ([raw file](https://github.com/sillsdev/web-xforge/blob/c903c56f64e7cc5f7de84268fa09981cf613179c/src/SIL.XForge.Scripture/ClientApp/src/styles.scss#L133)):*
> ```SCSS
> 
> .hide-lt-sm {
>   @include breakpoints.media-breakpoint-down(sm) {
> ```

The breakpoints have fundamentally changed. They are not working the same as before. See the lengthy comment above for an explanation of what is probably wrong.

**Comment by nigel-wells** [comment]
I've adjusted this as I see I did misunderstand what the intention was. It does seem confusing this setup to be honest but it does work as it did before from my testing.

**Comment by nigel-wells** [comment]
I've added the Bootstrap license in @Nateowami

**Review by Nateowami — APPROVED** [review]
> Reviewed 1 of 1 files at r3, 7 of 7 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/2733)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @nigel-wells)

**Pull request merged**
