### PR TITLE
SF-2192 Optimize note thread query and display

### PR DESCRIPTION
**Pull request by RaymondLuong3**
* query the chapter specific notes each time the text changes
* extract note display information when the dialog opens
* remove test for html display of note content

- - -
This change is [Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/2011)

### CODE REVIEW

**Review by RaymondLuong3 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/2011)* status: 0 of 6 files reviewed, 1 unresolved discussion

___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/note-dialog/note-dialog.component.spec.ts` line 129 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/2011#-Nc8gHlt9RcACJK76_aM:-Nc8gHlt9RcACJK76_aN:bgo8res) ([raw file](https://github.com/sillsdev/web-xforge/blob/cca4502e00455a0323f38f9ab533248a2e3ad63f/src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/note-dialog/note-dialog.component.spec.ts#L129)):*
> ```XML
>   }));
> 
>   it('should style notes', fakeAsync(() => {
> ```

This style test has been moved to `utils.spec.ts` in the PR for SF-2185.



_Code quote:_
```XML
 it('should style notes', fakeAsync(() => {
```

**Review by pmachapman — CHANGES_REQUESTED** [review]
The query change is awesome - thanks @RaymondLuong3 - it makes my Large Test Project (which has 35000+ notes) very usable where previously it ground to a halt while downloading every note in the background.

Also, the changing of the note dialog to use a view model makes the code far easier to understand - just a couple of minor suggestions.

> Reviewed 6 of 6 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/2011#-:-NcP10_3DmCx0Yxhwytg:b-6lx5e7)* status: all files reviewed, 3 unresolved discussions (waiting on @RaymondLuong3)

___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/note-dialog/note-dialog.component.ts` line 249 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/2011#-NcP2z202sggIb1ezAkK:-NcP2z202sggIb1ezAkL:b-so2cv8) ([raw file](https://github.com/sillsdev/web-xforge/blob/74ea354983811f9b7265cec12463fbffc01ad532/src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/note-dialog/note-dialog.component.ts#L249)):*
> ```XML
>   }
> 
>   async submit(): Promise<void> {
> ```

There is no async code in this method, so we could change the header to:
```ts
submit(): void {
```



_Code quote:_
```XML
async submit(): Promise<void> {
```
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/note-dialog/note-dialog.component.ts` line 261 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/2011#-NcP3cSP73fkXrvigbeL:-NcP3cSP73fkXrvigbeM:b-qwijil) ([raw file](https://github.com/sillsdev/web-xforge/blob/74ea354983811f9b7265cec12463fbffc01ad532/src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/note-dialog/note-dialog.component.ts#L261)):*
> ```XML
>   }
> 
>   updateNotesForDisplay(): void {
> ```

We could make this method private:
```ts
private updateNotesForDisplay(): void {
```

Also do you think it makes sense to rename it to `updateNotesToDisplay` as it updates the collection notesToDisplay?



_Code quote:_
```XML
updateNotesForDisplay(): void {
```
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/note-dialog/note-dialog.component.ts` line 263 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/2011#-NcP4ltg8QQE-mwwNY4B:-NcP4ltg8QQE-mwwNY4C:b-cr7jai) ([raw file](https://github.com/sillsdev/web-xforge/blob/74ea354983811f9b7265cec12463fbffc01ad532/src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/note-dialog/note-dialog.component.ts#L263)):*
> ```XML
>   updateNotesForDisplay(): void {
>     if (this.threadDoc?.data == null) return;
>     const notesToDisplay: Note[] = sortBy(
> ```

I found this variable name a little bit confusing at first glance as it is named the same as the class level array.

Are we able to rename it to something like `notes` or `sortedNotes`?



_Code quote:_
```XML
const notesToDisplay: Note[] = sortBy(
```
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/note-dialog/note-dialog.component.spec.ts` line 129 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/2011#-Nc8gHlt9RcACJK76_aM:-NcP42Xs5VU2o8KNips1:bb6ywmx) ([raw file](https://github.com/sillsdev/web-xforge/blob/cca4502e00455a0323f38f9ab533248a2e3ad63f/src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/note-dialog/note-dialog.component.spec.ts#L129)):*
<details><summary><i>Previously, RaymondLuong3 (Raymond Luong) wrote…</i></summary><blockquote>

This style test has been moved to `utils.spec.ts` in the PR for SF-2185.
</blockquote></details>

LGTM

**Review by RaymondLuong3 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/2011)* status: all files reviewed, 3 unresolved discussions (waiting on @pmachapman)

___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/note-dialog/note-dialog.component.ts` line 249 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/2011#-NcP2z202sggIb1ezAkK:-NcPCWgV1EpaEv4QaxUl:b-896fix) ([raw file](https://github.com/sillsdev/web-xforge/blob/74ea354983811f9b7265cec12463fbffc01ad532/src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/note-dialog/note-dialog.component.ts#L249)):*
<details><summary><i>Previously, pmachapman (Peter Chapman) wrote…</i></summary><blockquote>

There is no async code in this method, so we could change the header to:
```ts
submit(): void {
```
</blockquote></details>

Done.
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/note-dialog/note-dialog.component.ts` line 261 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/2011#-NcP3cSP73fkXrvigbeL:-NcPClwk4BZSIeaXjZTt:boj1qgt) ([raw file](https://github.com/sillsdev/web-xforge/blob/74ea354983811f9b7265cec12463fbffc01ad532/src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/note-dialog/note-dialog.component.ts#L261)):*
<details><summary><i>Previously, pmachapman (Peter Chapman) wrote…</i></summary><blockquote>

We could make this method private:
```ts
private updateNotesForDisplay(): void {
```

Also do you think it makes sense to rename it to `updateNotesToDisplay` as it updates the collection notesToDisplay?
</blockquote></details>

Good catch. Done.
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/note-dialog/note-dialog.component.ts` line 263 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/2011#-NcP4ltg8QQE-mwwNY4B:-NcPDEtVAKvll_5J-5Qe:b-896fix) ([raw file](https://github.com/sillsdev/web-xforge/blob/74ea354983811f9b7265cec12463fbffc01ad532/src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/note-dialog/note-dialog.component.ts#L263)):*
<details><summary><i>Previously, pmachapman (Peter Chapman) wrote…</i></summary><blockquote>

I found this variable name a little bit confusing at first glance as it is named the same as the class level array.

Are we able to rename it to something like `notes` or `sortedNotes`?
</blockquote></details>

Done.

**Review by pmachapman — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/2011#-:-NcPJHis8ao2MC96IIJv:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @RaymondLuong3)

**Pull request merged**
