### PR TITLE
SF-1166 Create projectUserConfig before adding a user to a project

### PR DESCRIPTION
**Pull request by RaymondLuong3**
There appears to be a race condition when adding a user to the project through the invitation link. If the user is logged in on and open tab, it navigates to the project and tries to access the projectUserConfig before it is available. This ensures that the ProjectUserConfig is created first before updating the userDoc and projectDoc.

---
This change is [Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/960)

### CODE REVIEW

**Review by irahopkinson — CHANGES_REQUESTED** [review]
Given your description above, I'm concerned we are just patching and not getting to the root of the issue. Do you have reproducible steps for the issue? Keep asking 'why' until you get to the root cause.

How will adding a dialog stop the endless refresh dialog from showing, i.e. won't the loop still happen but just paused by the dialog? There is no cancel button - does clicking outside the dialog cancel it?

> Reviewed 4 of 4 files at r1.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/960#-:-MTuwYIN8dzJv8OZ09ZO:b23m3ze)* status: all files reviewed, 2 unresolved discussions (waiting on @RaymondLuong3)

___
*[src/SIL.XForge.Scripture/ClientApp/src/xforge-common/location.service.ts, line 44 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/960#-MTuy-pR2IXxn4tWrL5l:-MTuy-pR2IXxn4tWrL5m:b-izfiee) ([raw file](https://github.com/sillsdev/web-xforge/blob/3f9c31cc3e85ab8bea6738fafdd6ed4e8ab195b0/src/SIL.XForge.Scripture/ClientApp/src/xforge-common/location.service.ts#L44)):*
> ```
> document.location
> ```
What is the difference between `document.location` and `window.location` used in the rest of this service? I looked it up and they are equivalent except that `window` is the preferred browser compatible one. Change to using `window`.
___
*[src/SIL.XForge.Scripture/ClientApp/src/xforge-common/location.service.ts, line 44 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/960#-MTuzH4uEsSAjslurms1:-MTuzH4uEsSAjslurms2:b-c55hs) ([raw file](https://github.com/sillsdev/web-xforge/blob/3f9c31cc3e85ab8bea6738fafdd6ed4e8ab195b0/src/SIL.XForge.Scripture/ClientApp/src/xforge-common/location.service.ts#L44)):*
> ```
> document.location.reload()
> ```
This is used in 2 other places in our code. Apart from changing them to use `window` instead (see comment above), invoking DRY, can they both call this service as well since you have introduced it here?

**Review by RaymondLuong3 — COMMENTED** [review]
So it appears that if I swap the order of updating the userDoc and projectDoc with creating the projectUserConfig it all works happily. This is an easy fix and may be the best. Alternatively, I tried listening to the projectUserConfig on the frontend for the doc to be created/loaded but that didn't work. It appears that if you attempt to get the doc before it is created it may not get subscribed to properly. That's just my best guess.

> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/960#-:-MTvadaz9hLqiayizgBZ:b-51tfww)* status: 0 of 4 files reviewed, 2 unresolved discussions (waiting on @irahopkinson)

___
*[src/SIL.XForge.Scripture/ClientApp/src/xforge-common/location.service.ts, line 44 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/960#-MTuy-pR2IXxn4tWrL5l:-MTvbjZF44B_cQhtmY6_:b-896fix) ([raw file](https://github.com/sillsdev/web-xforge/blob/3f9c31cc3e85ab8bea6738fafdd6ed4e8ab195b0/src/SIL.XForge.Scripture/ClientApp/src/xforge-common/location.service.ts#L44)):*
<details><summary><i>Previously, irahopkinson (Ira Hopkinson) wrote…</i></summary><blockquote>

> ```
> document.location
> ```
What is the difference between `document.location` and `window.location` used in the rest of this service? I looked it up and they are equivalent except that `window` is the preferred browser compatible one. Change to using `window`.
</blockquote></details>

Done.
___
*[src/SIL.XForge.Scripture/ClientApp/src/xforge-common/location.service.ts, line 44 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/960#-MTuzH4uEsSAjslurms1:-MTvbkGw7Tqiun7DqG8w:b-896fix) ([raw file](https://github.com/sillsdev/web-xforge/blob/3f9c31cc3e85ab8bea6738fafdd6ed4e8ab195b0/src/SIL.XForge.Scripture/ClientApp/src/xforge-common/location.service.ts#L44)):*
<details><summary><i>Previously, irahopkinson (Ira Hopkinson) wrote…</i></summary><blockquote>

> ```
> document.location.reload()
> ```
This is used in 2 other places in our code. Apart from changing them to use `window` instead (see comment above), invoking DRY, can they both call this service as well since you have introduced it here?
</blockquote></details>

Done.

**Review by irahopkinson — CHANGES_REQUESTED** [review]
Almost there, see comment below.

> Reviewed 4 of 7 files at r2.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/960#-:-MUDGdGm1n1MnN349goz:bmblzau)* status: all files reviewed, 1 unresolved discussion (waiting on @RaymondLuong3)

___
*[src/SIL.XForge.Scripture/ClientApp/src/xforge-common/location.service.ts, line 44 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/960#-MTuzH4uEsSAjslurms1:-MUDFuSv4Vyly-ndpWTg:b-lqpiut) ([raw file](https://github.com/sillsdev/web-xforge/blob/3f9c31cc3e85ab8bea6738fafdd6ed4e8ab195b0/src/SIL.XForge.Scripture/ClientApp/src/xforge-common/location.service.ts#L44)):*
<details><summary><i>Previously, RaymondLuong3 (Raymond Luong) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

It looks like you have only done this on 1 place not 2. You have done this in `pwa.service.ts` but not in `auth.service.ts`.

**Review by RaymondLuong3 — COMMENTED** [review]
Good catch! I didn't even think it was in more than one place.

> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/960#-:-MUG1pHqE99pplpNjgr1:brohe7b)* status: 4 of 5 files reviewed, 1 unresolved discussion (waiting on @irahopkinson)

___
*[src/SIL.XForge.Scripture/ClientApp/src/xforge-common/location.service.ts, line 44 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/960#-MTuzH4uEsSAjslurms1:-MUG1uBi6bip-GLW_QTC:b-uces7d) ([raw file](https://github.com/sillsdev/web-xforge/blob/3f9c31cc3e85ab8bea6738fafdd6ed4e8ab195b0/src/SIL.XForge.Scripture/ClientApp/src/xforge-common/location.service.ts#L44)):*
<details><summary><i>Previously, irahopkinson (Ira Hopkinson) wrote…</i></summary><blockquote>

It looks like you have only done this on 1 place not 2. You have done this in `pwa.service.ts` but not in `auth.service.ts`.
</blockquote></details>

should have known to check if it was in more than one place...

**Review by irahopkinson — APPROVED** [review]
:lgtm: thanks for this.

> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/960#-:-MUNLCQM7rojNiEOdOJq:bb82xw1)* status: :shipit: complete! all files reviewed, all discussions resolved

___
*[src/SIL.XForge.Scripture/ClientApp/src/xforge-common/location.service.ts, line 44 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/960#-MTuzH4uEsSAjslurms1:-MUNKajqDh7E5PN0vB14:br75uoe) ([raw file](https://github.com/sillsdev/web-xforge/blob/3f9c31cc3e85ab8bea6738fafdd6ed4e8ab195b0/src/SIL.XForge.Scripture/ClientApp/src/xforge-common/location.service.ts#L44)):*
<details><summary><i>Previously, RaymondLuong3 (Raymond Luong) wrote…</i></summary><blockquote>

should have known to check if it was in more than one place...
</blockquote></details>

No problem although my original post did say there where 2 you needed to deal with.

**Pull request merged**
