### PR TITLE
SF-1419 Get note threads to appear on combined verses

### PR DESCRIPTION
**Pull request by RaymondLuong3**
Verses that are combined have a verse segment ref that looks like `verse_1_2-3`. This change takes into consideration this format for a verse segment of a combined verse so that notes can be correctly embedded.

Verse range note
.

---
This change is [Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1176)

### CODE REVIEW

**Review by irahopkinson — CHANGES_REQUESTED** [review]
Nearly there, just a few questions.

> Reviewed 4 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1176#-:-MnP9adg3vGUAoVWr2xP:bjh9xai)* status: all files reviewed, 3 unresolved discussions (waiting on @RaymondLuong3)

___
*[src/SIL.XForge.Scripture/ClientApp/src/app/shared/text/text.component.ts, line 518 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/1176#-MnP6YTWD0Np45Qyo49q:-MnP6YTWD0Np45Qyo49r:b-817nwp) ([raw file](https://github.com/sillsdev/web-xforge/blob/56469933ec27aaaa9fccfa094d83e27646362eeb/src/SIL.XForge.Scripture/ClientApp/src/app/shared/text/text.component.ts#L518)):*
> ```
> [ref].concat(this.getRelatedSegmentRefs(ref));
> ```
I think you can just use the spread operator, i.e. `[ref, ...this.getRelatedSegmentRefs(ref)];`, which is more readable.
___
*[src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.spec.ts, line 2288 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/1176#-MnP7pQw1RRmcDh5WQMj:-MnP7pQw1RRmcDh5WQMk:bclw9bs) ([raw file](https://github.com/sillsdev/web-xforge/blob/56469933ec27aaaa9fccfa094d83e27646362eeb/src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.spec.ts#L2288)):*
> ```
> verseRef: vrd,
> ```
Now that you have a `verseRef` just use it as is. We were only fudging a partial one before with `vrd`.
___
*[src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.spec.ts, line 2326 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/1176#-MnP8rMD3Fwcetf_AdOl:-MnP8rMD3Fwcetf_AdOm:b3qffsf) ([raw file](https://github.com/sillsdev/web-xforge/blob/56469933ec27aaaa9fccfa094d83e27646362eeb/src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.spec.ts#L2326)):*
> ```
> addCustomVerseTextDoc
> ```
Why 'custom verse'? Should this be `addCombinedVerseTextDoc`?

**Review by RaymondLuong3 — COMMENTED** [review]
Thanks. I realize that there is some inconsistency in how we work with verse ranges. The checking tool represents a verse range as a single verse ref with a range in the verses property. I've updated a few things so that when we search for the segments that pertain to a verse or range of verses, the segments we get back come directly from the segments in the editor.

> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1176#-:-MnS6xyaC1HmrdOiG8x_:b-92g3n8)* status: all files reviewed, 3 unresolved discussions (waiting on @irahopkinson)

___
*[src/SIL.XForge.Scripture/ClientApp/src/app/shared/text/text.component.ts, line 518 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/1176#-MnP6YTWD0Np45Qyo49q:-MnR7ncUAuwrY9FpZJv7:bydn3e2) ([raw file](https://github.com/sillsdev/web-xforge/blob/56469933ec27aaaa9fccfa094d83e27646362eeb/src/SIL.XForge.Scripture/ClientApp/src/app/shared/text/text.component.ts#L518)):*
<details><summary><i>Previously, irahopkinson (Ira Hopkinson) wrote…</i></summary><blockquote>

> ```
> [ref].concat(this.getRelatedSegmentRefs(ref));
> ```
I think you can just use the spread operator, i.e. `[ref, ...this.getRelatedSegmentRefs(ref)];`, which is more readable.
</blockquote></details>

Nice. I haven't had the chance to use the ellipsis operator in so long, I forgot it existed.
___
*[src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.spec.ts, line 2288 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/1176#-MnP7pQw1RRmcDh5WQMj:-MnS6iri-RzUzcEAG5SD:b-8gzzds) ([raw file](https://github.com/sillsdev/web-xforge/blob/56469933ec27aaaa9fccfa094d83e27646362eeb/src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.spec.ts#L2288)):*
<details><summary><i>Previously, irahopkinson (Ira Hopkinson) wrote…</i></summary><blockquote>

> ```
> verseRef: vrd,
> ```
Now that you have a `verseRef` just use it as is. We were only fudging a partial one before with `vrd`.
</blockquote></details>

Ok, remembered that we have a helper function to convert from a verseRef to a verseRefData. I'll use that.
___
*[src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.spec.ts, line 2326 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/1176#-MnP8rMD3Fwcetf_AdOl:-MnS6hyf3EPv_1PYlNQH:b-896fix) ([raw file](https://github.com/sillsdev/web-xforge/blob/56469933ec27aaaa9fccfa094d83e27646362eeb/src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.spec.ts#L2326)):*
<details><summary><i>Previously, irahopkinson (Ira Hopkinson) wrote…</i></summary><blockquote>

> ```
> addCustomVerseTextDoc
> ```
Why 'custom verse'? Should this be `addCombinedVerseTextDoc`?
</blockquote></details>

Done.

**Review by RaymondLuong3 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1176)* status: 0 of 5 files reviewed, 3 unresolved discussions (waiting on @irahopkinson)

___
*[src/SIL.XForge.Scripture/ClientApp/src/app/shared/text/text.component.ts, line 518 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/1176#-MnP6YTWD0Np45Qyo49q:-MnSAHb1Cu1316zESEfC:b-vw9ntf) ([raw file](https://github.com/sillsdev/web-xforge/blob/56469933ec27aaaa9fccfa094d83e27646362eeb/src/SIL.XForge.Scripture/ClientApp/src/app/shared/text/text.component.ts#L518)):*
<details><summary><i>Previously, RaymondLuong3 (Raymond Luong) wrote…</i></summary><blockquote>

Nice. I haven't had the chance to use the ellipsis operator in so long, I forgot it existed.
</blockquote></details>

Ok, turns out that it makes more sense to have a method that does it all by getting all segments for a given verse. But good to know that the ellipsis operator exists.

**Review by irahopkinson — CHANGES_REQUESTED** [review]
Yes, we might need to get this work on`master` too or at least make @nateowami aware of it.

> Reviewed 5 of 5 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1176#-:-MnUoZ2v4r5czBR9yjZ7:bs2nou0)* status: all files reviewed, 2 unresolved discussions (waiting on @RaymondLuong3)

___
*[src/SIL.XForge.Scripture/ClientApp/src/app/shared/text/text-view-model.ts, line 295 at r2](https://reviewable.io/reviews/sillsdev/web-xforge/1176#-MnUnv9F9XT-edc7l0Sq:-MnUnv9G91aqRrl1dogV:b-pj979s) ([raw file](https://github.com/sillsdev/web-xforge/blob/a325b65ea246ce2fc41a87f6207d76899ba06a20/src/SIL.XForge.Scripture/ClientApp/src/app/shared/text/text-view-model.ts#L295)):*
> ```
> Array.from(
> ```
You seem to like using this. Can you explain its need of use here?
___
*[src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.spec.ts, line 2288 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/1176#-MnP7pQw1RRmcDh5WQMj:-MnUa7Z-0kw4dPTQrJdh:b-xsv1ks) ([raw file](https://github.com/sillsdev/web-xforge/blob/56469933ec27aaaa9fccfa094d83e27646362eeb/src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.spec.ts#L2288)):*
<details><summary><i>Previously, RaymondLuong3 (Raymond Luong) wrote…</i></summary><blockquote>

Ok, remembered that we have a helper function to convert from a verseRef to a verseRefData. I'll use that.
</blockquote></details>

Yep, that's better.
___
*[src/SIL.XForge.Scripture/ClientApp/src/xforge-common/utils.ts, line 15 at r2](https://reviewable.io/reviews/sillsdev/web-xforge/1176#-MnUjj0yA-WONs6l7kZJ:-MnUjj0yA-WONs6l7kZK:b-ichozf) ([raw file](https://github.com/sillsdev/web-xforge/blob/a325b65ea246ce2fc41a87f6207d76899ba06a20/src/SIL.XForge.Scripture/ClientApp/src/xforge-common/utils.ts#L15)):*
<details><summary><i alt="summary">Quoted 5 lines of code…</i></summary>

> ```
> // Regular expression for getting the verse from a segment ref
> export const VERSE_FROM_SEGMENT_REF_REGEX = /verse_[0-9]+_([0-9]+)[-/]*/;
> // Regular expression for the verse segment ref of scripture content
> export const VERSE_REGEX = /verse_[0-9]+_[0-9]+/;
> 
> ```
</details>

As I think about it more, these don't belong in here (nor does `verseSlug`). They are not things that need to be common across other Forges. They should all be moved to `src\SIL.XForge.Scripture\ClientApp\src\app\shared\utils.ts` or similar.

**Review by RaymondLuong3 — COMMENTED** [review]
Ok, I'll move some of these changes into another PR for master. It looks like SF-1433 is a result of this. I'll add a test to demonstrate that this fixes that.

> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1176#-:-MnXmT2I7KR79Pj86H-0:b-8ezezz)* status: 1 of 7 files reviewed, 2 unresolved discussions (waiting on @irahopkinson)

___
*[src/SIL.XForge.Scripture/ClientApp/src/app/shared/text/text-view-model.ts, line 295 at r2](https://reviewable.io/reviews/sillsdev/web-xforge/1176#-MnUnv9F9XT-edc7l0Sq:-MnXmjiA7wAfZL3O08Wo:bl6auvl) ([raw file](https://github.com/sillsdev/web-xforge/blob/a325b65ea246ce2fc41a87f6207d76899ba06a20/src/SIL.XForge.Scripture/ClientApp/src/app/shared/text/text-view-model.ts#L295)):*
<details><summary><i>Previously, irahopkinson (Ira Hopkinson) wrote…</i></summary><blockquote>

> ```
> Array.from(
> ```
You seem to like using this. Can you explain its need of use here?
</blockquote></details>

Yea, it looks like I've been over zealous with the use of array.from. Just a habit of mine.
___
*[src/SIL.XForge.Scripture/ClientApp/src/xforge-common/utils.ts, line 15 at r2](https://reviewable.io/reviews/sillsdev/web-xforge/1176#-MnUjj0yA-WONs6l7kZJ:-MnXmusv57Xsq07ndybj:b-v3ktm5) ([raw file](https://github.com/sillsdev/web-xforge/blob/a325b65ea246ce2fc41a87f6207d76899ba06a20/src/SIL.XForge.Scripture/ClientApp/src/xforge-common/utils.ts#L15)):*
<details><summary><i>Previously, irahopkinson (Ira Hopkinson) wrote…</i></summary><blockquote>

> ```
> // Regular expression for getting the verse from a segment ref
> export const VERSE_FROM_SEGMENT_REF_REGEX = /verse_[0-9]+_([0-9]+)[-/]*/;
> // Regular expression for the verse segment ref of scripture content
> export const VERSE_REGEX = /verse_[0-9]+_[0-9]+/;
> 
> ```
As I think about it more, these don't belong in here (nor does `verseSlug`). They are not things that need to be common across other Forges. They should all be moved to `src\SIL.XForge.Scripture\ClientApp\src\app\shared\utils.ts` or similar.
</blockquote></details>

You are right. I didn't ask any questions about why verseSlug was in xforge.utils but I should have asked why. I've moved them to your suggested location.

**Review by irahopkinson — APPROVED** [review]
> Reviewed 6 of 6 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1176)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @RaymondLuong3)

**Pull request merged**
