### PR TITLE
SF-2731 Create script to summarize project user edit activity

### PR DESCRIPTION
**Pull request by siltomato**
This PR creates ts-node script `report-user-edits` that takes a project and time window and outputs a TSV file summarizing:
- Which chapters were edited
- Who edited each chapter
- How many insertions and deletions happened in each chapter, calculated in two ways:
  - Raw insert/delete count
    - Sums the inserts/deletes for o_text ops for the user/book/chapter
  - Net word insert/delete count
    - Fetches snapshots book-ending contiguous user edits, concats the strings for each snapshot, and diffs the two strings using [fast-diff](https://github.com/jhchen/fast-diff), counting the words in the resulting insert/delete diff.

- - -
This change is [Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/2465)

### CODE REVIEW

**Review by Nateowami — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/2465)* status: 0 of 4 files reviewed, 1 unresolved discussion (waiting on @siltomato)

___
*[`scripts/db_tools/report-user-edits.ts` line 1 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/2465#-NyNs6RN3GqY5VMrjgga:-NyNs6RN3GqY5VMrjggb:b-p0iwne) ([raw file](https://github.com/sillsdev/web-xforge/blob/0b04d3c98154cf24ff368fe7be4a5d8cf59de88a/scripts/db_tools/report-user-edits.ts#L1)):*
> ```XML
> #!/usr/bin/env -S bash -c '"$(dirname "$0")"/node_modules/.bin/ts-node "$(dirname "$0")/$(basename "$0")" "$@"'
> ```

This file is not executable. I'm wondering how you were executing it? Most of our scripts we make executable (`chmod +x report-user-edits.ts`)

**Review by siltomato — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/2465)* status: 0 of 4 files reviewed, all discussions resolved (waiting on @Nateowami)

___
*[`scripts/db_tools/report-user-edits.ts` line 1 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/2465#-NyNs6RN3GqY5VMrjgga:-NyO7tiU7gWHe0oX6rzo:b8n0d4q) ([raw file](https://github.com/sillsdev/web-xforge/blob/0b04d3c98154cf24ff368fe7be4a5d8cf59de88a/scripts/db_tools/report-user-edits.ts#L1)):*
<details><summary><i>Previously, Nateowami (Nathaniel Paulus) wrote…</i></summary><blockquote>

This file is not executable. I'm wondering how you were executing it? Most of our scripts we make executable (`chmod +x report-user-edits.ts`)
</blockquote></details>

It seems that in Windows, the presence of the shebang makes it executable in the bash shell.

I did some digging, and it looks like while `chmod +x` isn't showing commitable changes (on my Windows machine), the following is working in windows:
```bash
git add --chmod=+x
```

**Review by pmachapman — APPROVED** [review]
:lgtm:

I ran this script on a project on prod that had a lot of edits in the NT, and it took quite some time (30 minutes). I don't see a way around that, though, at this time, but it is something to be aware of. (I assume it won't be run often?)

I also appreciate how your script shows the way to having SF show who wrote a history revision.

> Reviewed 3 of 4 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/2465#-:-NySqYX82RDWerFEnd9D:bbq5z36)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @siltomato)

**Comment by Nateowami** [comment]
@pmachapman Does it appear most of that time is CPU time, network time, or Mongo query time? Mainly want to make sure we aren't working our database too hard and having performance consequences.

**Comment by pmachapman** [comment]
> @pmachapman Does it appear most of that time is CPU time, network time, or Mongo query time? Mainly want to make sure we aren't working our database too hard and having performance consequences.

No, it was mostly latency and client side diff'ing. I had the performance monitor running and the live database was not doing much at the time.

**Pull request merged**
