### PR TITLE
Use site-specific 503 error page

### PR DESCRIPTION
**Pull request by marksvc**
This change is [Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/2908)

### CODE REVIEW

**Review by RaymondLuong3 — COMMENTED** [review]
Will this page be uploaded to cloudflare? How does cloudflare know to use this page over the existing page?

> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/2908#-:-ODvwofTB8Xo5mlCojRY:bn5o4yy)* status: all files reviewed, 1 unresolved discussion (waiting on @marksvc)

___
*[`src/SIL.XForge.Scripture/ErrorPages/503-generic.html` line 129 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/2908#-ODvwREY9cJ3ohT8K-uU:-ODvwREY9cJ3ohT8K-uV:b-nqqz0w) ([raw file](https://github.com/sillsdev/web-xforge/blob/a31a5cb23a646731b2ba79bd5aa3c738af1195ce/src/SIL.XForge.Scripture/ErrorPages/503-generic.html#L129)):*
> ```HTML
>                         x="0"
>                         xmlns="http://www.w3.org/2000/svg"
>                         id="圖層_1"
> ```

Interesting choice of ID here.



_Code quote:_
```HTML
                  id="圖層_1"
```

**Review by Nateowami — COMMENTED** [review]
> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/2908)* status: all files reviewed, 2 unresolved discussions (waiting on @marksvc)

___
*[`src/SIL.XForge.Scripture/ErrorPages/503-generic.html` line 7 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/2908#-ODvszN26J7OqEKVlC4Q:-ODvszN26J7OqEKVlC4R:b7j4lek) ([raw file](https://github.com/sillsdev/web-xforge/blob/a31a5cb23a646731b2ba79bd5aa3c738af1195ce/src/SIL.XForge.Scripture/ErrorPages/503-generic.html#L7)):*
> ```HTML
>         <meta http-equiv="X-UA-Compatible" content="IE=edge" />
>         <meta name="viewport" content="width=device-width, initial-scale=1.0" />
>         <title>503: unavailable</title>
> ```

How about `503: Site unavailable`?

**Review by marksvc — COMMENTED** [review]
I'm very sorry. I should have made it clear that 503.html was renamed to 503-sf.html, for review purposes.

We use these pages on our server, served from Apache. We also need to separately give this kind of thing to Cloudflare, but I need to learn more to know how that should be done. 

> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/2908#-:-ODx00s-B8BL5Pgwz2BG:br6ucfh)* status: all files reviewed, 1 unresolved discussion (waiting on @RaymondLuong3)

___
*[`src/SIL.XForge.Scripture/ErrorPages/503-generic.html` line 129 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/2908#-ODvwREY9cJ3ohT8K-uU:-ODx0KenAdq9Ob1CikD_:b-x0paxf) ([raw file](https://github.com/sillsdev/web-xforge/blob/a31a5cb23a646731b2ba79bd5aa3c738af1195ce/src/SIL.XForge.Scripture/ErrorPages/503-generic.html#L129)):*
<details><summary><i>Previously, RaymondLuong3 (Raymond Luong) wrote…</i></summary><blockquote>

Interesting choice of ID here.
</blockquote></details>

Yes :)

**Review by marksvc — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/2908)* status: 1 of 2 files reviewed, 1 unresolved discussion (waiting on @Nateowami and @RaymondLuong3)

___
*[`src/SIL.XForge.Scripture/ErrorPages/503-generic.html` line 7 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/2908#-ODvszN26J7OqEKVlC4Q:-ODx0nccBmKMuBizu2K5:bb6un1j) ([raw file](https://github.com/sillsdev/web-xforge/blob/a31a5cb23a646731b2ba79bd5aa3c738af1195ce/src/SIL.XForge.Scripture/ErrorPages/503-generic.html#L7)):*
<details><summary><i>Previously, Nateowami wrote…</i></summary><blockquote>

How about `503: Site unavailable`?
</blockquote></details>

Done

**Review by marksvc — COMMENTED** [review]
Okay, good, I see that there is indication of the rename in the UI here.

> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/2908#-:-ODx0znu5YXC7pyqkkRn:b-7fezkf)* status: 1 of 2 files reviewed, 1 unresolved discussion (waiting on @Nateowami and @RaymondLuong3)

**Review by Nateowami — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/2908#-:-ODx26dd2VsTPkm6GMw8:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @RaymondLuong3)

**Comment by Nateowami** [comment]
@marksvc I've renamed the PR to be more specific. Does it look OK to you? I think this is ready to merge.

**Comment by marksvc** [comment]
It is good; thank you.

**Pull request merged**
