### PR TITLE
SF-2592 Persist editor tabs

### PR DESCRIPTION
**Pull request by siltomato**
This PR adds persistence to the editor tabs.  Tab state is stored in `SFProjectUserConfig`.  Page reloads and route changes should maintain the tab state with the caveat that history does not currently maintain the last selected revision (it resets to the first revision in the list).

- - -
This change is [Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/2413)

### CODE REVIEW

**Review by pmachapman — CHANGES_REQUESTED** [review]
Just some questions and a bug. Looks good, otherwise!

> Reviewed 25 of 25 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/2413#-:-NvdDQ4_0FW_fTUMtf7b:b-l0j5e0)* status: all files reviewed, 8 unresolved discussions (waiting on @siltomato)

___
*[`src/RealtimeServer/scriptureforge/models/editor-tab.ts` line 8 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/2413#-NvcvAQP7-S6PIv26qJs:-NvcvAQP7-S6PIv26qJt:b-lxoygv) ([raw file](https://github.com/sillsdev/web-xforge/blob/c8a305667ae5f8df471b66f1e5e38b9f1ce1ed7a/src/RealtimeServer/scriptureforge/models/editor-tab.ts#L8)):*
> ```XML
>  * Minimal data to persist and reconstruct an editor tab.
>  */
> export interface EditorTabPersistData {
> ```

Are you able to rename this file to `editor-tab-persist-data.ts`? That will match the current convention for file naming.



_Code quote:_
```XML
EditorTabPersistData
```
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/core/models/sf-project-user-config-doc.ts` line 33 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/2413#-Nvd68c2CAEpUH5tEjGy:-Nvd68c3DJm6kv953UW5:b-otyhou) ([raw file](https://github.com/sillsdev/web-xforge/blob/c8a305667ae5f8df471b66f1e5e38b9f1ce1ed7a/src/SIL.XForge.Scripture/ClientApp/src/app/core/models/sf-project-user-config-doc.ts#L33)):*
> ```XML
>     }
> 
>     this.submitJson0Op(op => {
> ```

Do you think this async method should be awaited?



_Code quote:_
```XML
this.submitJson0Op(op => {
```
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/shared/sf-tab-group/tab-state/tab-group.ts` line 15 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/2413#-Nvd78Uq-GIBbCfg1MGQ:-Nvd78Ur4dF12ePpi6W_:b-kagxy6) ([raw file](https://github.com/sillsdev/web-xforge/blob/c8a305667ae5f8df471b66f1e5e38b9f1ce1ed7a/src/SIL.XForge.Scripture/ClientApp/src/app/shared/sf-tab-group/tab-state/tab-group.ts#L15)):*
> ```XML
> 
>   addTab(tab: T, selectTab: boolean = true): void {
>     this.tabs = [...this.tabs, tab];
> ```

I didn't know we could use this syntax in TypeScript (as we do in C#) - awesome!



_Code quote:_
```XML
[...this.tabs, tab];
```
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.ts` line 1247 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/2413#-Nvd2FgN1bgb-7CfXriT:-Nvd2FgN1bgb-7CfXriU:bbknx7m) ([raw file](https://github.com/sillsdev/web-xforge/blob/c8a305667ae5f8df471b66f1e5e38b9f1ce1ed7a/src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.ts#L1247)):*
> ```XML
>                 tabType: tab.type,
>                 groupId: tab.groupId,
>                 isSelected: tab.selectedIndex === index,
> ```

The value for `selectedIndex` and `index` do not correspond correctly. I am not sure on cause of the bug, but can give you a couple of examples on how to recreate it:

Note: these examples assume you are starting with just a source and target tab visible


1. Create a history tab on the target side (it will be selected)
2. Reload the page
3. Result: No tab is selected

1. Create a history tab on the source side (it will be selected)
2. Create a history tab on the target side (it will be selected)
3. Reload the page
4. Result: Only the history tab on the source side is selected

1. Create a history tab on the target side (it will be selected)
2. Create another history tab on the target side (it will be selected)
3. Reload the page
4. Result: Only the first history tab is selected

1. Create a history tab on the target side (it will be selected)
2. Create another history tab on the target side (it will be selected)
3. Move the second tab to the position of the first tab
4. Reload the page
5. Result: Only the target tab is selected

These scenarios work correctly when done on just the source side



_Code quote:_
```XML
isSelected: tab.selectedIndex === index,
```
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.ts` line 1258 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/2413#-Nvd8RVY7Va4-dUO78YS:-Nvd8RVY7Va4-dUO78YT:b-809oy8) ([raw file](https://github.com/sillsdev/web-xforge/blob/c8a305667ae5f8df471b66f1e5e38b9f1ce1ed7a/src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.ts#L1258)):*
> ```XML
>       .subscribe((tabs: EditorTabPersistData[]) => {
>         this.editorTabPersistenceService.persistTabsOpen(tabs);
>       });
> ```

Do we need to async/await this? i.e.
```
      .subscribe(async (tabs: EditorTabPersistData[]) =>{
        await this.editorTabPersistenceService.persistTabsOpen(tabs);
      });
```
In C# we generally would, but I am not sure of the ramifications for promises in TypeScript.



_Code quote:_
```XML
      .subscribe((tabs: EditorTabPersistData[]) => {
        this.editorTabPersistenceService.persistTabsOpen(tabs);
      });
```
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/tabs/editor-tab-persistence.service.ts` line 7 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/2413#-Nvd3e5y57a-8lz5-vk2:-Nvd3e5y57a-8lz5-vk3:bqu3rif) ([raw file](https://github.com/sillsdev/web-xforge/blob/c8a305667ae5f8df471b66f1e5e38b9f1ce1ed7a/src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/tabs/editor-tab-persistence.service.ts#L7)):*
> ```XML
> import { distinctUntilChanged, finalize, shareReplay } from 'rxjs/operators';
> import { SFProjectUserConfigDoc } from 'src/app/core/models/sf-project-user-config-doc';
> import { SFProjectService } from 'src/app/core/sf-project.service';
> ```

If you rebase with the latest changes on master, these should be cleaned up on save to be relative paths.



_Code quote:_
```XML
import { SFProjectUserConfigDoc } from 'src/app/core/models/sf-project-user-config-doc';
import { SFProjectService } from 'src/app/core/sf-project.service';
```
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/tabs/editor-tab-persistence.service.ts` line 35 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/2413#-Nvd5VGb5PljyitisrkC:-Nvd5VGb5PljyitisrkD:bel5rwm) ([raw file](https://github.com/sillsdev/web-xforge/blob/c8a305667ae5f8df471b66f1e5e38b9f1ce1ed7a/src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/tabs/editor-tab-persistence.service.ts#L35)):*
> ```XML
>    * Persist the specified list of open editor tabs to SFProjectUserConfigDoc.
>    */
>   async persistTabsOpen(tabs: EditorTabPersistData[]): Promise<void> {
> ```

I notice you don't await this method any of the places you call it - is that deliberate?

Also, what are you thoughts on adding the suffix `Async` to `async` methods in TypeScript (like we do in C#). I am not aware of the conventions in TypeScript for `async` methods.



_Code quote:_
```XML
async persistTabsOpen
```
___
*[`src/SIL.XForge.Scripture/Models/EditorTab.cs` line 6 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/2413#-NvcxHRZ2ep_8bYA0yKF:-NvcxHRZ2ep_8bYA0yKG:bkzujk9) ([raw file](https://github.com/sillsdev/web-xforge/blob/c8a305667ae5f8df471b66f1e5e38b9f1ce1ed7a/src/SIL.XForge.Scripture/Models/EditorTab.cs#L6)):*
> ```Smalltalk
> /// Minimal data to persist and reconstruct an editor tab.
> /// </summary>
> public class EditorTab
> ```

Would we be able to have the same name for this class as the corresponding TypeScript interface? I don't mind which name is chosen, but consistency will help with future maintenance.



_Code quote:_
```Smalltalk
EditorTab
```

**Review by siltomato — COMMENTED** [review]
Thanks, Peter.  Good catch on that bug!

> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/2413#-:-NviMjry1X1FLeCGPrd7:bk6lqix)* status: 11 of 26 files reviewed, 7 unresolved discussions (waiting on @pmachapman)

___
*[`src/RealtimeServer/scriptureforge/models/editor-tab.ts` line 8 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/2413#-NvcvAQP7-S6PIv26qJs:-NvhrGtp4Dccgau3G4Ny:b-9vxw49) ([raw file](https://github.com/sillsdev/web-xforge/blob/c8a305667ae5f8df471b66f1e5e38b9f1ce1ed7a/src/RealtimeServer/scriptureforge/models/editor-tab.ts#L8)):*
<details><summary><i>Previously, pmachapman (Peter Chapman) wrote…</i></summary><blockquote>

Are you able to rename this file to `editor-tab-persist-data.ts`? That will match the current convention for file naming.
</blockquote></details>

Done.  I left the type definitions in`editor-tab.ts`, as they are not specific to the persistence data.  Not sure what else to name the file since there are multiple types.  I figure grouping them under 'editor-tab' makes sense, unless you have another idea.
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/core/models/sf-project-user-config-doc.ts` line 33 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/2413#-Nvd68c2CAEpUH5tEjGy:-NvhtvhpCO-qVmdqWyN4:b-zciwb2) ([raw file](https://github.com/sillsdev/web-xforge/blob/c8a305667ae5f8df471b66f1e5e38b9f1ce1ed7a/src/SIL.XForge.Scripture/ClientApp/src/app/core/models/sf-project-user-config-doc.ts#L33)):*
<details><summary><i>Previously, pmachapman (Peter Chapman) wrote…</i></summary><blockquote>

Do you think this async method should be awaited?
</blockquote></details>

Definitely, good catch.  I had figured that there isn't any code after, but I wasn't considering that the calling function may want to wait!
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/shared/sf-tab-group/tab-state/tab-group.ts` line 15 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/2413#-Nvd78Uq-GIBbCfg1MGQ:-NvhwmIE3aFOVbIaOS0B:b-ga9xw5) ([raw file](https://github.com/sillsdev/web-xforge/blob/c8a305667ae5f8df471b66f1e5e38b9f1ce1ed7a/src/SIL.XForge.Scripture/ClientApp/src/app/shared/sf-tab-group/tab-state/tab-group.ts#L15)):*
<details><summary><i>Previously, pmachapman (Peter Chapman) wrote…</i></summary><blockquote>

I didn't know we could use this syntax in TypeScript (as we do in C#) - awesome!
</blockquote></details>

Word, it is really handy when you want to create a new array reference for the sake of immutability / change detection.
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.ts` line 1247 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/2413#-Nvd2FgN1bgb-7CfXriT:-NviHFdM1LOgfS3VF-o8:b-qzwo6a) ([raw file](https://github.com/sillsdev/web-xforge/blob/c8a305667ae5f8df471b66f1e5e38b9f1ce1ed7a/src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.ts#L1247)):*
<details><summary><i>Previously, pmachapman (Peter Chapman) wrote…</i></summary><blockquote>

The value for `selectedIndex` and `index` do not correspond correctly. I am not sure on cause of the bug, but can give you a couple of examples on how to recreate it:

Note: these examples assume you are starting with just a source and target tab visible


1. Create a history tab on the target side (it will be selected)
2. Reload the page
3. Result: No tab is selected

1. Create a history tab on the source side (it will be selected)
2. Create a history tab on the target side (it will be selected)
3. Reload the page
4. Result: Only the history tab on the source side is selected

1. Create a history tab on the target side (it will be selected)
2. Create another history tab on the target side (it will be selected)
3. Reload the page
4. Result: Only the first history tab is selected

1. Create a history tab on the target side (it will be selected)
2. Create another history tab on the target side (it will be selected)
3. Move the second tab to the position of the first tab
4. Reload the page
5. Result: Only the target tab is selected

These scenarios work correctly when done on just the source side
</blockquote></details>

Good catch!  Fixed.
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.ts` line 1258 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/2413#-Nvd8RVY7Va4-dUO78YS:-NvhzOov2F_K1Zh3vq2e:b-d4n6bl) ([raw file](https://github.com/sillsdev/web-xforge/blob/c8a305667ae5f8df471b66f1e5e38b9f1ce1ed7a/src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.ts#L1258)):*
<details><summary><i>Previously, pmachapman (Peter Chapman) wrote…</i></summary><blockquote>

Do we need to async/await this? i.e.
```
      .subscribe(async (tabs: EditorTabPersistData[]) =>{
        await this.editorTabPersistenceService.persistTabsOpen(tabs);
      });
```
In C# we generally would, but I am not sure of the ramifications for promises in TypeScript.
</blockquote></details>

I'm not sure of a benefit here.  Somewhat unrelated, but looking at this code, I did add a debounce, in case tab state has a burst of emissions.
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/tabs/editor-tab-persistence.service.ts` line 7 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/2413#-Nvd3e5y57a-8lz5-vk2:-Nvi37YP080qcv7wpB4T:b-896fix) ([raw file](https://github.com/sillsdev/web-xforge/blob/c8a305667ae5f8df471b66f1e5e38b9f1ce1ed7a/src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/tabs/editor-tab-persistence.service.ts#L7)):*
<details><summary><i>Previously, pmachapman (Peter Chapman) wrote…</i></summary><blockquote>

If you rebase with the latest changes on master, these should be cleaned up on save to be relative paths.
</blockquote></details>

Done.
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/tabs/editor-tab-persistence.service.ts` line 35 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/2413#-Nvd5VGb5PljyitisrkC:-NviAyQHDInpikcXwwQI:b-fo4ql3) ([raw file](https://github.com/sillsdev/web-xforge/blob/c8a305667ae5f8df471b66f1e5e38b9f1ce1ed7a/src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/tabs/editor-tab-persistence.service.ts#L35)):*
<details><summary><i>Previously, pmachapman (Peter Chapman) wrote…</i></summary><blockquote>

I notice you don't await this method any of the places you call it - is that deliberate?

Also, what are you thoughts on adding the suffix `Async` to `async` methods in TypeScript (like we do in C#). I am not aware of the conventions in TypeScript for `async` methods.
</blockquote></details>

Currently, I believe `persistTabsOpen()` is just called in subscription to tab state change in the editor component.  I see it as a "fire and forget", so I don't any benefit to awaiting it there.

On another note, I added an await to `pucDoc.updateEditorOpenTabs(tabs);` as part of your suggestion above for `sf-project-user-config-doc.ts`.
___
*[`src/SIL.XForge.Scripture/Models/EditorTab.cs` line 6 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/2413#-NvcxHRZ2ep_8bYA0yKF:-NviEatREfEYnqHSwPFx:b-896fix) ([raw file](https://github.com/sillsdev/web-xforge/blob/c8a305667ae5f8df471b66f1e5e38b9f1ce1ed7a/src/SIL.XForge.Scripture/Models/EditorTab.cs#L6)):*
<details><summary><i>Previously, pmachapman (Peter Chapman) wrote…</i></summary><blockquote>

Would we be able to have the same name for this class as the corresponding TypeScript interface? I don't mind which name is chosen, but consistency will help with future maintenance.
</blockquote></details>

Done.

**Review by pmachapman — APPROVED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/2413)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @siltomato)

**Review by pmachapman — APPROVED** [review]
> Reviewed 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/2413)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @siltomato)

**Review by pmachapman — APPROVED** [review]
> Reviewed 4 of 4 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/2413)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @siltomato)

**Review by pmachapman — APPROVED** [review]
> Reviewed 2 of 2 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/2413)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @siltomato)

**Pull request merged**
