### PR TITLE
SF-2895 Add recording visualizer to the audio recorder dialog

### PR DESCRIPTION
**Pull request by RaymondLuong3**
This change adds the visualization of the active audio recording. See the Jira issue for the link to the tutorial for creating a frequency bar visualization of an audio recording.
Please feel free to make suggestions for improving the layout of the bar.

Visualize Recording

- - -
This change is [Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/2691)

### CODE REVIEW

**Comment by nigel-wells** [comment]
This sounds (mind the pun) that it would have been a fun one to work through.
I see there is an option for a ""waveform/oscilloscope" which is probably close to what we had in mind but hadn't communicated in the Jira card. 

This example here is closer to what we had in mind for look and feel. It has the waveform centered and underneath. It also has a nice pulse coming out of the microphone as well which is a nice touch. The pulse would just be a simple CSS animation that would start whenever there was a frequency high enough to trigger it.
image

**Comment by Nateowami** [comment]
@nigel-wells 

>whenever there was a frequency high enough to trigger it

Do you mean amplitude?

**Comment by RaymondLuong3** [comment]
@nigel-wells Thanks for the suggestion. I played around with it to see what I can come up with. Using the waveform data, I could make a visualization of what looks a lot like the element in the picture you provided. I started to try my luck at getting the pulse effect, but it is tricky getting the animation to work multiple times. Perhaps that can added later? Let me know if this is on the right track.
Waveform audio dialog

**Comment by nigel-wells** [comment]
Yes, that is getting closer. 
This is probably closer to what I had in mind - not perfect though. Thoughts? I mostly used ChatGPT to refine it closer and then made tweaks :)

https://github.com/user-attachments/assets/85b1d8ea-c7c7-4289-b096-c504cfa64f69

**Comment by RaymondLuong3** [comment]
That's neat! I have not tried to get ChatGPT to help do graphical things. I have been able to mostly replicate your video. I've made it less fine-grain and slowed it down to refresh every 150ms. To me, that is a nice pace, any faster and it becomes distracting. I was also able to get the ripple to work reasonably well. Let me know what you think.
Waveform audio dialog (2)

**Comment by nigel-wells** [comment]
Yeah, that's looking much better. I'd drop the grey background on it though.
The ripple looks like what I had in mind too! It would be nice if it was creating pulses along with the audio waves rather than on a one second timer - I think to do this you'd need to be dynamically adding and destroying div tags so that each div can have its own animation and cause a neat overlap effect.

**Review by nigel-wells — CHANGES_REQUESTED** [review]
> Reviewed 4 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/2691)* status: all files reviewed, 7 unresolved discussions (waiting on @RaymondLuong3)

___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/shared/audio-recorder-dialog/audio-recorder-dialog.component.html` line 41 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/2691#-O5ujTTq1MtOlkewfURT:-O5ujTTq1MtOlkewfURU:b-nfgtiw) ([raw file](https://github.com/sillsdev/web-xforge/blob/8bb0a13823b19d6d58f8d130599810d35abbd0b2/src/SIL.XForge.Scripture/ClientApp/src/app/shared/audio-recorder-dialog/audio-recorder-dialog.component.html#L41)):*
> ```HTML
>       }
>     </div>
>     <div class="visualizer-container">
> ```

To avoid the buttons being further down under white space, can you set it up so there is one block of white space and then the visualizer or buttons take up that space? Currently they are stacked with the `visible` property and it makes the buttons get pushed further down than they need to. Happy to chat this through if this comment didn't make enough sense :)
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/shared/audio-recorder-dialog/audio-recorder-dialog.component.scss` line 30 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/2691#-O5ulTcE5LooEk1LOudG:-O5ulTcE5LooEk1LOudH:b694pxg) ([raw file](https://github.com/sillsdev/web-xforge/blob/8bb0a13823b19d6d58f8d130599810d35abbd0b2/src/SIL.XForge.Scripture/ClientApp/src/app/shared/audio-recorder-dialog/audio-recorder-dialog.component.scss#L30)):*
> ```SCSS
>   }
> 
>   .stop-background {
> ```

I'd love if we could have this element repeated `x` number of times which would let the animation run and overlap multiple times.
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/shared/audio-recorder-dialog/audio-recorder-dialog.component.ts` line 76 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/2691#-O5ulw__2qBgNnUtpGOw:-O5ulw__2qBgNnUtpGOx:b9q5mgw) ([raw file](https://github.com/sillsdev/web-xforge/blob/8bb0a13823b19d6d58f8d130599810d35abbd0b2/src/SIL.XForge.Scripture/ClientApp/src/app/shared/audio-recorder-dialog/audio-recorder-dialog.component.ts#L76)):*
> ```XML
>   private canvasContext: CanvasRenderingContext2D | null = null;
>   // height and width are calculated in ngAfterViewInit
>   private HEIGHT = 150;
> ```

Can you give `HEIGHT` and `WIFTH` better names as to what they are referring to i.e. `visualizerHeight`
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/shared/audio-recorder-dialog/audio-recorder-dialog.component.ts` line 78 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/2691#-O5umHW26Jccmhdt1FcT:-O5umHW26Jccmhdt1FcU:bthmlhj) ([raw file](https://github.com/sillsdev/web-xforge/blob/8bb0a13823b19d6d58f8d130599810d35abbd0b2/src/SIL.XForge.Scripture/ClientApp/src/app/shared/audio-recorder-dialog/audio-recorder-dialog.component.ts#L78)):*
> ```XML
>   private HEIGHT = 150;
>   private WIDTH = 300;
>   private audioBase = 128;
> ```

Can this one have a better name as well
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/shared/audio-recorder-dialog/audio-recorder-dialog.component.ts` line 122 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/2691#-O5ume7e3xEf7C8FuUvD:-O5ume7e3xEf7C8FuUvE:bku3kjo) ([raw file](https://github.com/sillsdev/web-xforge/blob/8bb0a13823b19d6d58f8d130599810d35abbd0b2/src/SIL.XForge.Scripture/ClientApp/src/app/shared/audio-recorder-dialog/audio-recorder-dialog.component.ts#L122)):*
> ```XML
>     this.canvasContext = canvas.getContext('2d');
>     if (this.canvasContext == null) return;
>     this.canvasContext.fillStyle = 'rgb(200, 200, 200)';
> ```

Set the background to white
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/shared/audio-recorder-dialog/audio-recorder-dialog.component.ts` line 276 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/2691#-O5unC_U-4cXAWmmCR_7:-O5unC_U-4cXAWmmCR_8:b1gqao1) ([raw file](https://github.com/sillsdev/web-xforge/blob/8bb0a13823b19d6d58f8d130599810d35abbd0b2/src/SIL.XForge.Scripture/ClientApp/src/app/shared/audio-recorder-dialog/audio-recorder-dialog.component.ts#L276)):*
> ```XML
>         this.drawOnCanvas(dataArray, bufferLength);
> 
>         const threshold = 1.25;
> ```

Rename this to what sort of threshold it is i.e. volume, noise, etc.
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/shared/audio-recorder-dialog/audio-recorder-dialog.component.ts` line 285 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/2691#-O5umxXc2Sdy6-223GMY:-O5umxXc2Sdy6-223GMZ:bpzuwth) ([raw file](https://github.com/sillsdev/web-xforge/blob/8bb0a13823b19d6d58f8d130599810d35abbd0b2/src/SIL.XForge.Scripture/ClientApp/src/app/shared/audio-recorder-dialog/audio-recorder-dialog.component.ts#L285)):*
> ```XML
>     };
> 
>     drawWaveForm();
> ```

Does this need to be called like this - can you simply remove the method and then use some `rxjs` instead of `setTimeout()`

**Comment by Nateowami** [comment]
Can we use a CSS gradient instead of constantly adding and removing elements? https://codepen.io/Nateowami/pen/wvLRaZN

**Comment by RaymondLuong3** [comment]
We are dynamically creating div elements for the purpose of showing overlapping ripples if the threshold is hit multiple times within a second. Alternative, we would not need to create more div elements if we do not want overlapping ripples.
I see your gradient example, but I don't see how we can animate that in a way that corresponds to the audio waveform.

**Review by nigel-wells — CHANGES_REQUESTED** [review]
I think the animation triggering of the waveform is a nice touch. I have just tested this again Raymond and, it is working, but it doesn't always trigger. I'm not sure if that is a threshold thing or if it is my mic? I believe I'm being loud enough for the wave to animate. Setting it to `1` works quite well

> Reviewed 4 of 4 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/2691#-:-O64l8cs90ARKhSL_wTM:b413a36)* status: all files reviewed, 3 unresolved discussions (waiting on @RaymondLuong3)

___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/shared/audio-recorder-dialog/audio-recorder-dialog.component.scss` line 56 at r2](https://reviewable.io/reviews/sillsdev/web-xforge/2691#-O64lvvJ--9P8-gLEbYp:-O64lvvJ--9P8-gLEbYq:b-r4mz9z) ([raw file](https://github.com/sillsdev/web-xforge/blob/f045f20c7238af64241c407fd64ada4d76a12cc2/src/SIL.XForge.Scripture/ClientApp/src/app/shared/audio-recorder-dialog/audio-recorder-dialog.component.scss#L56)):*
> ```SCSS
>     position: relative;
> 
>     ::ng-deep .animate {
> ```

Can we add a comment as to why we needed to use `ng-deep` as it was a little odd that we needed to
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/shared/audio-recorder-dialog/audio-recorder-dialog.component.scss` line 57 at r2](https://reviewable.io/reviews/sillsdev/web-xforge/2691#-O64l1YsBK5ZObkEQMVY:-O64l1YsBK5ZObkEQMVZ:bljf7uw) ([raw file](https://github.com/sillsdev/web-xforge/blob/f045f20c7238af64241c407fd64ada4d76a12cc2/src/SIL.XForge.Scripture/ClientApp/src/app/shared/audio-recorder-dialog/audio-recorder-dialog.component.scss#L57)):*
> ```SCSS
> 
>     ::ng-deep .animate {
>       content: '';
> ```

This isn't needed any more
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/shared/audio-recorder-dialog/audio-recorder-dialog.component.scss` line 62 at r2](https://reviewable.io/reviews/sillsdev/web-xforge/2691#-O64l3HVDEzi92jIFUZ6:-O64l3HVDEzi92jIFUZ7:b-8n0ult) ([raw file](https://github.com/sillsdev/web-xforge/blob/f045f20c7238af64241c407fd64ada4d76a12cc2/src/SIL.XForge.Scripture/ClientApp/src/app/shared/audio-recorder-dialog/audio-recorder-dialog.component.scss#L62)):*
> ```SCSS
>       width: 80px;
>       border-radius: 50%;
>       display: flex;
> ```

Doesn't look like we need flex or the justify and align properties

**Comment by Nateowami** [comment]
How do I actually test this with real audio recording? All of the stories seem to fake the audio (which is good for automated testing, but I don't see one that works with manual testing).

**Comment by nigel-wells** [comment]
To test you can adjust one of the `startRecording` methods to open the dialog i.e. `QuestionDialog`

```
startRecording(): void {
    // this.textAndAudio?.audioComponent?.startRecording();
    this.dialogService.openMatDialog(AudioRecorderDialogComponent);
}
```

**Review by RaymondLuong3 — COMMENTED** [review]
I've lowered the waveform threshold to 1.2 and updated the threshold calculation to consider the absolute value. On my browser, this seems to work. I wonder if there is some browser specific thing going on?

> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/2691#-:-O6N3c552lDJqEXiHA5S:b-8hrpk8)* status: all files reviewed, 3 unresolved discussions (waiting on @nigel-wells)

___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/shared/audio-recorder-dialog/audio-recorder-dialog.component.scss` line 56 at r2](https://reviewable.io/reviews/sillsdev/web-xforge/2691#-O64lvvJ--9P8-gLEbYp:-O6N4vKK9gASqd_877Bq:b-896fix) ([raw file](https://github.com/sillsdev/web-xforge/blob/f045f20c7238af64241c407fd64ada4d76a12cc2/src/SIL.XForge.Scripture/ClientApp/src/app/shared/audio-recorder-dialog/audio-recorder-dialog.component.scss#L56)):*
<details><summary><i>Previously, nigel-wells (Nigel Wells) wrote…</i></summary><blockquote>

Can we add a comment as to why we needed to use `ng-deep` as it was a little odd that we needed to
</blockquote></details>

Done.
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/shared/audio-recorder-dialog/audio-recorder-dialog.component.scss` line 57 at r2](https://reviewable.io/reviews/sillsdev/web-xforge/2691#-O64l1YsBK5ZObkEQMVY:-O6N4vbK0AyfgsL-3r2l:b-896fix) ([raw file](https://github.com/sillsdev/web-xforge/blob/f045f20c7238af64241c407fd64ada4d76a12cc2/src/SIL.XForge.Scripture/ClientApp/src/app/shared/audio-recorder-dialog/audio-recorder-dialog.component.scss#L57)):*
<details><summary><i>Previously, nigel-wells (Nigel Wells) wrote…</i></summary><blockquote>

This isn't needed any more
</blockquote></details>

Done.
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/shared/audio-recorder-dialog/audio-recorder-dialog.component.scss` line 62 at r2](https://reviewable.io/reviews/sillsdev/web-xforge/2691#-O64l3HVDEzi92jIFUZ6:-O6N4w24DZMOlonhJ2bi:b-896fix) ([raw file](https://github.com/sillsdev/web-xforge/blob/f045f20c7238af64241c407fd64ada4d76a12cc2/src/SIL.XForge.Scripture/ClientApp/src/app/shared/audio-recorder-dialog/audio-recorder-dialog.component.scss#L62)):*
<details><summary><i>Previously, nigel-wells (Nigel Wells) wrote…</i></summary><blockquote>

Doesn't look like we need flex or the justify and align properties
</blockquote></details>

Done.

**Review by nigel-wells — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/2691#-:-O6NT5EED5eq30gcDXWK:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @RaymondLuong3)

**Comment by RaymondLuong3** [comment]
@nigel-wells The UI changes also need to be reviewed

**Comment by nigel-wells** [comment]
Thanks for the reminder. I've approved those now. Will let you merge when you're ready

**Pull request merged**
