### PR TITLE
SF-2298 Upgrade to Angular 15

### PR DESCRIPTION
**Pull request by Nateowami**
I recommend looking at the changes one commit at a time. Most of the changes were created by migrations run by scripts. The exact thing that was run is specified in the respective commits.

See https://update.angular.io/?l=3&v=14.0-15.0 for the instructions I followed.

Most of the changes are updates to imports to migrate us to the legacy Material components. For details, see https://v15.material.angular.io/guide/mdc-migration

- - -
This change is [Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/2141)

### CODE REVIEW

**Review by Nateowami — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/2141)* status: 0 of 80 files reviewed, 1 unresolved discussion

___
*[`src/SIL.XForge.Scripture/ClientApp/src/xforge-common/i18n.service.ts` line 65 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/2141#-NhZTgto0hN5L8mwkuW1:-NhZTgto0hN5L8mwkuW2:b-3ew5jh) ([raw file](https://github.com/sillsdev/web-xforge/blob/00093c7d2267c29c196af88f2b467482faafbbeb/src/SIL.XForge.Scripture/ClientApp/src/xforge-common/i18n.service.ts#L65)):*
> ```XML
> }
> 
> const locales = getI18nLocales().concat(PseudoLocalization.locale);
> ```

This file was the most perplexing. Revert the changes to this file and you'll see the errors I ran into at runtime. It appears to be related to decorators and the ES version TypeScript is targeting. I don't like this change, but it made everything run smoothly.

**Review by pmachapman — APPROVED** [review]
The change runs well and looks good.

Running `npm run lint` shows a lot of deprecation warnings! I assume we will chip away at these over the coming months?

> Reviewed 80 of 80 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/2141#-:-NhdQRQ2Ae01TBAOE2wT:bjbgnt4)* status: all files reviewed, 2 unresolved discussions (waiting on @Nateowami)

___
*[`src/SIL.XForge.Scripture/ClientApp/package.json` line 41 at r2](https://reviewable.io/reviews/sillsdev/web-xforge/2141#-NhdS-VR3tVLJjw1yi1S:-NhdS-VR3tVLJjw1yi1T:bslc7c2) ([raw file](https://github.com/sillsdev/web-xforge/blob/2fa83a2537e97f0e66cc2e76adbe94e024565ea2/src/SIL.XForge.Scripture/ClientApp/package.json#L41)):*
> ```JSON
>     "@angular/platform-browser": "^15.2.10",
>     "@angular/platform-browser-dynamic": "^15.2.10",
>     "@angular/pwa": "^14.2.10",
> ```

Is there a reason this package was not upgraded to v15?



_Code quote:_
```JSON
"@angular/pwa": "^14.2.10",
```

**Review by Nateowami — COMMENTED** [review]
Yes, that would be the plan. I wouldn't view deprecations as something to have to immediately fix in the update step; their entire purpose for existing is to make transitions like this smoother. Most of the deprecations are related to Material UI components.

> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/2141#-:-Nhdlen6113inR84L8T2:bsu5tns)* status: 78 of 81 files reviewed, 2 unresolved discussions (waiting on @pmachapman)

___
*[`src/SIL.XForge.Scripture/ClientApp/package.json` line 41 at r2](https://reviewable.io/reviews/sillsdev/web-xforge/2141#-NhdS-VR3tVLJjw1yi1S:-NhdlMst5AAFIXyJhfxe:b-oj58e2) ([raw file](https://github.com/sillsdev/web-xforge/blob/2fa83a2537e97f0e66cc2e76adbe94e024565ea2/src/SIL.XForge.Scripture/ClientApp/package.json#L41)):*
Good catch. The package describes itself as
> a [schematic](https://angular.io/guide/schematics) for adding [Progressive Web App](https://web.dev/progressive-web-apps/) support to an Angular project

So that's probably why it isn't included in the regular update process. But it would be good to keep it in sync with the others. Updated.

**Comment by Nateowami** [comment]
@pmachapman I've sent this to testing, despite having made a change you haven't reviewed.

**Review by pmachapman — APPROVED** [review]
:lgtm: 

> Reviewed 3 of 3 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/2141#-:-NhdzDNb8z_VbDQhG3EF:bg7igkv)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @Nateowami)

**Pull request merged**
