### PR TITLE
SF-1178 Access source project only if user has permission

### PR DESCRIPTION
**Pull request by RaymondLuong3**
* Add an endpoint to return a user's role on a project

---
This change is [Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/932)

### CODE REVIEW

**Comment by marksvc** [comment]
:eyes:

**Review by marksvc — CHANGES_REQUESTED** [review]
Thanks for your work on this. I have some quibbles which I have commented about below.

> Reviewed 7 of 7 files at r1.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/932#-:-MS54fiN7OiwuTTTRwmo:b7e5cmu)* status: all files reviewed, 5 unresolved discussions (waiting on @RaymondLuong3)

___
*[src/SIL.XForge/Services/ProjectService.cs, line 81 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/932#-MS5-pXe-faQxJswUwZp:-MS5-pXf0MUZG8GHs1fk:b-a99b6j) ([raw file](https://github.com/sillsdev/web-xforge/blob/89802ca2c9dde4248d0eee0a89afa0d38ba0df62/src/SIL.XForge/Services/ProjectService.cs#L81)):*
> ```
> var attempt 
> ```
Let's use type `Attempt<string>` instead, to conform to our usually-dont-use-var style.
___
*[src/SIL.XForge/Services/ProjectService.cs, line 82 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/932#-MS52Z0-BnnvIw9ev1Be:-MS52Z0-BnnvIw9ev1Bf:bv5gpf6) ([raw file](https://github.com/sillsdev/web-xforge/blob/89802ca2c9dde4248d0eee0a89afa0d38ba0df62/src/SIL.XForge/Services/ProjectService.cs#L82)):*
> ```Smalltalk
>             TModel project = await GetProjectAsync(projectId);
>             var attempt = await TryGetProjectRoleAsync(project, curUserId);
>             return attempt.Result;
> ```

I see that in class ProjectRole.cs, we define a `None` (as well as in sf-project-role.ts). What do you think about not returning null, but returning ProjectRole.None if we find that the user doesn't have a role on the project?

Hmm, I see tho that in the spec tests, you set the mock up to return 'None' sometimes instead of null. Do we sometimes return "None" from this method and sometimes null? Or what's going on?
___
*[src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.ts, line 294 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/932#-MS53DWu88kHNgYwISOB:-MS53DWu88kHNgYwISOC:bamfgw4) ([raw file](https://github.com/sillsdev/web-xforge/blob/89802ca2c9dde4248d0eee0a89afa0d38ba0df62/src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.ts#L294)):*
> ```
> : string | undefined 
> ```
(Based on another comment regarding using 'None') So we could condense this type to just `string`.
___
*[src/SIL.XForge.Scripture/ClientApp/src/xforge-common/project.service.ts, line 77 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/932#-MS50BJX9iLu9CF6CsvN:-MS50BJX9iLu9CF6CsvO:bi2oksn) ([raw file](https://github.com/sillsdev/web-xforge/blob/89802ca2c9dde4248d0eee0a89afa0d38ba0df62/src/SIL.XForge.Scripture/ClientApp/src/xforge-common/project.service.ts#L77)):*
> ```XML
>   }
> 
>   onlineGetProjectRole(id: string): Promise<string | undefined> {
> ```

I comment elsewhere about returning 'None' instead of null. If we do that, then we can hopefully change this return type to just `Promise<string>`.
___
*[src/SIL.XForge.Scripture/ClientApp/src/xforge-common/project.service.ts, line 78 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/932#-MS50M0-0zjpu21j3HNj:-MS50M0-0zjpu21j3HNk:bv6ej5l) ([raw file](https://github.com/sillsdev/web-xforge/blob/89802ca2c9dde4248d0eee0a89afa0d38ba0df62/src/SIL.XForge.Scripture/ClientApp/src/xforge-common/project.service.ts#L78)):*
> ```
> 'projectRole'
> ```
I notice that the API has some inconsistent naming for the introduced endpoint.

project.service.ts exposes `onlineGetProjectRole`.
SFProjectsRpcController.cs exposes `ProjectRole`.
IProjectService provides `RoleOnProjectAsync`.
Could we make these all use a common base name  so it's easier to quickly jump to some back-end functionality when looking at a call to it on the front-end? For example, maybe they could be something like the set of:

```
onlineGetProjectRole()
GetProjectRole()
GetProjectRoleAsync()
```

**Review by RaymondLuong3 — COMMENTED** [review]
Thanks for the review.

> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/932#-:-MS5BlPf3-fDp97itXy7:b-9qdoyq)* status: 3 of 8 files reviewed, 5 unresolved discussions (waiting on @marksvc)

___
*[src/SIL.XForge/Services/ProjectService.cs, line 81 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/932#-MS5-pXe-faQxJswUwZp:-MS5Bo5C17wjjj6tYGg4:b-896fix) ([raw file](https://github.com/sillsdev/web-xforge/blob/89802ca2c9dde4248d0eee0a89afa0d38ba0df62/src/SIL.XForge/Services/ProjectService.cs#L81)):*
<details><summary><i>Previously, marksvc wrote…</i></summary><blockquote>

> ```
> var attempt 
> ```
Let's use type `Attempt<string>` instead, to conform to our usually-dont-use-var style.

</blockquote></details>

Done.
___
*[src/SIL.XForge/Services/ProjectService.cs, line 82 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/932#-MS52Z0-BnnvIw9ev1Be:-MS5Bpm2BFi1eJZPD7mk:b-6pcbn0) ([raw file](https://github.com/sillsdev/web-xforge/blob/89802ca2c9dde4248d0eee0a89afa0d38ba0df62/src/SIL.XForge/Services/ProjectService.cs#L82)):*
<details><summary><i>Previously, marksvc wrote…</i></summary><blockquote>

I see that in class ProjectRole.cs, we define a `None` (as well as in sf-project-role.ts). What do you think about not returning null, but returning ProjectRole.None if we find that the user doesn't have a role on the project?

Hmm, I see tho that in the spec tests, you set the mock up to return 'None' sometimes instead of null. Do we sometimes return "None" from this method and sometimes null? Or what's going on?
</blockquote></details>

I'm happy with not returning null. It returned none now if the user does not have a role.
___
*[src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.ts, line 294 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/932#-MS53DWu88kHNgYwISOB:-MS5CW9Q5dnUecm92Z_5:bv5mqc2) ([raw file](https://github.com/sillsdev/web-xforge/blob/89802ca2c9dde4248d0eee0a89afa0d38ba0df62/src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.ts#L294)):*
<details><summary><i>Previously, marksvc wrote…</i></summary><blockquote>

> ```
> : string | undefined 
> ```
(Based on another comment regarding using 'None') So we could condense this type to just `string`.
</blockquote></details>

Unfortunately there is an error in the editor if we limit the type to string only.
___
*[src/SIL.XForge.Scripture/ClientApp/src/xforge-common/project.service.ts, line 77 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/932#-MS50BJX9iLu9CF6CsvN:-MS5Cj1J6jYLzl55iWs4:bvgz6vt) ([raw file](https://github.com/sillsdev/web-xforge/blob/89802ca2c9dde4248d0eee0a89afa0d38ba0df62/src/SIL.XForge.Scripture/ClientApp/src/xforge-common/project.service.ts#L77)):*
<details><summary><i>Previously, marksvc wrote…</i></summary><blockquote>

I comment elsewhere about returning 'None' instead of null. If we do that, then we can hopefully change this return type to just `Promise<string>`.
</blockquote></details>

onlineInvoke will return a `string` or `undefined` according to the my editor. I don't think this change can be made.
___
*[src/SIL.XForge.Scripture/ClientApp/src/xforge-common/project.service.ts, line 78 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/932#-MS50M0-0zjpu21j3HNj:-MS5CwyC5WdDFQhXBJOm:b-896fix) ([raw file](https://github.com/sillsdev/web-xforge/blob/89802ca2c9dde4248d0eee0a89afa0d38ba0df62/src/SIL.XForge.Scripture/ClientApp/src/xforge-common/project.service.ts#L78)):*
<details><summary><i>Previously, marksvc wrote…</i></summary><blockquote>

> ```
> 'projectRole'
> ```
I notice that the API has some inconsistent naming for the introduced endpoint.

project.service.ts exposes `onlineGetProjectRole`.
SFProjectsRpcController.cs exposes `ProjectRole`.
IProjectService provides `RoleOnProjectAsync`.
Could we make these all use a common base name  so it's easier to quickly jump to some back-end functionality when looking at a call to it on the front-end? For example, maybe they could be something like the set of:

```
onlineGetProjectRole()
GetProjectRole()
GetProjectRoleAsync()
```


</blockquote></details>

Done.

**Review by marksvc — CHANGES_REQUESTED** [review]
> Reviewed 5 of 5 files at r2.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/932)* status: all files reviewed, 2 unresolved discussions (waiting on @marksvc and @RaymondLuong3)

___
*[src/SIL.XForge.Scripture/ClientApp/src/xforge-common/project.service.ts, line 77 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/932#-MS50BJX9iLu9CF6CsvN:-MS9Xbh11hkoZ6Zvxa-A:b-zaubtf) ([raw file](https://github.com/sillsdev/web-xforge/blob/89802ca2c9dde4248d0eee0a89afa0d38ba0df62/src/SIL.XForge.Scripture/ClientApp/src/xforge-common/project.service.ts#L77)):*
<details><summary><i>Previously, RaymondLuong3 (Raymond Luong) wrote…</i></summary><blockquote>

onlineInvoke will return a `string` or `undefined` according to the my editor. I don't think this change can be made.
</blockquote></details>

Right, okay. What if we change this method to do something like

```cs
return this.onlineInvoke<string>('getProjectRole', { projectId: id }) ?? SFProjectRole.None;
```

I think that would let us always return Promise<string>.

**Review by marksvc — APPROVED** [review]
Thanks for your work on this.

> Reviewed 3 of 3 files at r3.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/932#-:-MSE0t-L3hd2frRU_LXQ:b7tt6m2)* status: :shipit: complete! all files reviewed, all discussions resolved

**Comment by irahopkinson** [comment]
___
*[src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.ts, line 295 at r2](https://reviewable.io/reviews/sillsdev/web-xforge/932#-MS7-Je10mPrYbl3uTqO:-MS7-Je2BiGTfo_7tq7g:bz7dhq9) ([raw file](https://github.com/sillsdev/web-xforge/blob/8ddfbf39bc0581c565ed1dd85629fb927225c22d/src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.ts#L295)):*
> ```
> await this.projectService.get(sourceId)
> ```
Is there some reason why this call doesn't just return `undefined` if the user doesn't have a source role rather than making 2 calls to the backend? Also now with book/chapter permissions it might be we have to check that rather than their role? Since previously your role gave you permission whereas now it is deermined properly by your book/chapter permissions.

**Comment by RaymondLuong3** [comment]
___
*[src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.ts, line 295 at r2](https://reviewable.io/reviews/sillsdev/web-xforge/932#-MS7-Je10mPrYbl3uTqO:-MSTGbFoDAhPokVVXyBa:b-b1gn6m) ([raw file](https://github.com/sillsdev/web-xforge/blob/8ddfbf39bc0581c565ed1dd85629fb927225c22d/src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.ts#L295)):*
<details><summary><i>Previously, irahopkinson (Ira Hopkinson) wrote…</i></summary><blockquote>

> ```
> await this.projectService.get(sourceId)
> ```
Is there some reason why this call doesn't just return `undefined` if the user doesn't have a source role rather than making 2 calls to the backend? Also now with book/chapter permissions it might be we have to check that rather than their role? Since previously your role gave you permission whereas now it is deermined properly by your book/chapter permissions.
</blockquote></details>

Right, I hadn't considered returning `undefined` as an option. It seems that our system was setup assuming that `projectService.get()` would only be used if it was determined that a user has access (that's why it throws an error if a user did not). We may need to review our permission structures.
I chose to check the role on projects because our realtime server uses that information specifically to determine if a user has access to a project. Again this may require that we review our permission structure.

**Pull request merged**
