### PR TITLE
dev: Update sfdev to Ubuntu 22.04

### PR DESCRIPTION
**Pull request by marksvc**
----
The sfdev vagrant box is a virtual machine with pre-installed tools and configuration that allows for testing and development of SF. 
This PR adjusts the vagrant box creation script and instructions to what I propose to use with the Ubuntu 22.04 vagrant box. 

The current vagrant box uses Ubuntu 20.04. This PR uses Ubuntu 22.04. 

Most of the changes will probably not be very user-visible. One of the biggest user-visible changes is that the box comes pre-installed with all of Chromium, Chrome, Edge, Firefox, and Brave browsers. And six different keyboard input methods, including two RTL.

I have tested the result, but have not yet published the pre-built box, so there is opportunity to apply changes if desired.

Screenshot showing sfdev using the proposed changes:

sfdev

I applied label "will require testing" so the PR does not get merged upon approval, because the pre-built box should be published at the same time that this is merged (since the `Vagrantfile` is also being correspondingly changed, in a way not compatible with the current sfdev machine).

- - -
This change is [Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/2554)

### CODE REVIEW

**Review by pmachapman — APPROVED** [review]
Just one (non-blocking) question.

:lgtm: Let me know when you publish the 22.04 vagrant box, so I can test this PR - I assume you will merge the PR and publish the box around the same time.

> Reviewed 4 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/2554#-:-O0kSECGAM9f5fbiQMXy:b-wg6zkm)* status: all files reviewed, 1 unresolved discussion (waiting on @marksvc)

___
*[`deploy/vagrant/sfdev/Vagrantfile` line 47 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/2554#-O0kSO8m7Auk-5YiCsGX:-O0kSO8m7Auk-5YiCsGY:bxhpgqm) ([raw file](https://github.com/sillsdev/web-xforge/blob/dedc4b0fe21df0ef4d3096aa149a2a351fb48cc7/deploy/vagrant/sfdev/Vagrantfile#L47)):*
> ```Ruby
> 
>     # Update code repo
>     cd ~/code/web-xforge
> ```

Why do you change the source location from `~/src/` to `~/code`?

As a sidenote, the UpdateHelp program assumes that `web-sf-helps` is in the `~/src/` directory, so I have always checked out `web-xforge` into `~/src/` for consistency with that.



_Code quote:_
```Ruby
 cd ~/code/web-xforge
```

**Review by marksvc — COMMENTED** [review]
Okay. The box is on its way to the Vagrant Cloud. Later today or tomorrow I can publish it.

> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/2554#-:-O0ocS1rAOxspZ90Yb09:b99ybcj)* status: all files reviewed, 1 unresolved discussion (waiting on @pmachapman)

___
*[`deploy/vagrant/sfdev/Vagrantfile` line 47 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/2554#-O0kSO8m7Auk-5YiCsGX:-O0oZ2pZ4d_qqCMycydt:b-qtv3ow) ([raw file](https://github.com/sillsdev/web-xforge/blob/dedc4b0fe21df0ef4d3096aa149a2a351fb48cc7/deploy/vagrant/sfdev/Vagrantfile#L47)):*
<details><summary><i>Previously, pmachapman (Peter Chapman) wrote…</i></summary><blockquote>

Why do you change the source location from `~/src/` to `~/code`?

As a sidenote, the UpdateHelp program assumes that `web-sf-helps` is in the `~/src/` directory, so I have always checked out `web-xforge` into `~/src/` for consistency with that.
</blockquote></details>

I find that there isn't much consistency in the naming for where developers check out software projects. Some naming people use for a high-level directory containing projects includes `dev`, `projects`, `code`, `src`, `Projects`, and `git`.

Much of our documentation is written assuming the developer/tester starts out in the web-xforge repository location, independently of its naming, so in that regard I don't think it should matter too much where the repo is. 

When I came to Scripture Forge, Ira had been using `~/src`, and so I went with that for consistency. But it had long bugged me as a naming choice. 

I experimented with some of the different names and decided upon `code` as being most ideal. I adjusted the vagrant to use `~/code` rather than `~/src`, but symlinked `~/src` to the `code` directory, so any vagrant instructions regarding `~/src/web-xforge/...` should still work. I expect UpdateHelp will too, then.

The naming of the location is somewhat arbitrary, and quite influenced by subjective factors. `code` isn't inarguably better that `src`. So I'm quite open to critique on what directory name to use.

**Review by pmachapman — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/2554)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @marksvc)

___
*[`deploy/vagrant/sfdev/Vagrantfile` line 47 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/2554#-O0kSO8m7Auk-5YiCsGX:-O0oyxqI5297Z0_A6stg:b-cvfuvq) ([raw file](https://github.com/sillsdev/web-xforge/blob/dedc4b0fe21df0ef4d3096aa149a2a351fb48cc7/deploy/vagrant/sfdev/Vagrantfile#L47)):*
<details><summary><i>Previously, marksvc wrote…</i></summary><blockquote>

I find that there isn't much consistency in the naming for where developers check out software projects. Some naming people use for a high-level directory containing projects includes `dev`, `projects`, `code`, `src`, `Projects`, and `git`.

Much of our documentation is written assuming the developer/tester starts out in the web-xforge repository location, independently of its naming, so in that regard I don't think it should matter too much where the repo is. 

When I came to Scripture Forge, Ira had been using `~/src`, and so I went with that for consistency. But it had long bugged me as a naming choice. 

I experimented with some of the different names and decided upon `code` as being most ideal. I adjusted the vagrant to use `~/code` rather than `~/src`, but symlinked `~/src` to the `code` directory, so any vagrant instructions regarding `~/src/web-xforge/...` should still work. I expect UpdateHelp will too, then.

The naming of the location is somewhat arbitrary, and quite influenced by subjective factors. `code` isn't inarguably better that `src`. So I'm quite open to critique on what directory name to use.
</blockquote></details>

All good - thank you!

**Comment by marksvc** [comment]
I have published the v1.1.0 box image. Though my `vagrant box update` doesn't seem to see it yet. Hopefully that's just a matter of caches or something that will properly see v1.1.0 soon.

**Review by pmachapman — COMMENTED** [review]
I updated the vagrant box via `vagrant box update`, then ran `vagrant up`, but the script is stuck trying to connect to the box via SSH, but SSH has not started. See the screenshots below:



> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/2554#-:-O1JaihgEfdXJnVCKF0i:b-l6jxna)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @marksvc)

**Comment by marksvc** [comment]
Wow, you're right. I was able to reproduce it easily as well. I have made a fix but will need to rearrange some things on my computer before I can apply it.

**Comment by marksvc** [comment]
I pushed the fix to this branch, but it is not yet ready to test in a published basebox.

**Comment by marksvc** [comment]
A basebox was published with version 1.1.1. I had some unexpected trouble getting my workstation to understand that, but normally `vagrant box update` will pull down the available new basebox. 

The basebox version 1.1.1 should successfully regenerate the sshd keys now and allow vagrant to do the local provision.

**Review by pmachapman — CHANGES_REQUESTED** [review]
I had the same issue occur with the latest image. I have left a comment with more details, and what I did to resolve it. (Reviewable is putting my comments in the wrong place, so please refer to the Code Quote section of the comment below)

> Reviewed 2 of 2 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/2554#-:-O2aWQK-5EMFtwLlt0zx:bi78z6w)* status: all files reviewed, 1 unresolved discussion (waiting on @marksvc)

___
*[`deploy/vagrant/sfdev/base/provision` line 94 at r3](https://reviewable.io/reviews/sillsdev/web-xforge/2554#-O2aluPD9V4ensV4LazA:-O2aluPD9V4ensV4LazB:b-o5k5h3) ([raw file](https://github.com/sillsdev/web-xforge/blob/c5a80b3026158e66fa6cd8f2d5ac0aa65be1b63e/deploy/vagrant/sfdev/base/provision#L94)):*
> ```
> 
> ## Configure task bar
> ```

When running `vagrant up` (after `vagrant box update && vagrant destroy`), I had the same error as before, and could not SSH into the box:

Journal:
```
░░ The job identifier is 2653.
Jul 24 15:41:40 sfdev sshd[3653]: sshd: no hostkeys available -- exiting.
Jul 24 15:41:40 sfdev systemd[1]: ssh.service: Control process exited, code=exited, status=1/FAILURE
░░ Subject: Unit process exited
░░ Defined-By: systemd
░░ Support: http://www.ubuntu.com/support
░░
░░ An ExecStartPre= process belonging to unit ssh.service has exited.
░░
░░ The process' exit code is 'exited' and its exit status is 1.
Jul 24 15:41:40 sfdev systemd[1]: ssh.service: Failed with result 'exit-code'.
░░ Subject: Unit failed
░░ Defined-By: systemd
░░ Support: http://www.ubuntu.com/support
░░
░░ The unit ssh.service has entered the 'failed' state with result 'exit-code'.
Jul 24 15:41:40 sfdev systemd[1]: Failed to start OpenBSD Secure Shell server.
░░ Subject: A start job for unit ssh.service has failed
░░ Defined-By: systemd
░░ Support: http://www.ubuntu.com/support
░░
░░ A start job for unit ssh.service has finished with a failure.
░░
░░ The job identifier is 2653 and the job result is failed.
Jul 24 15:41:40 sfdev systemd[1]: ssh.service: Scheduled restart job, restart counter is at 1.
░░ Subject: Automatic restarting of a unit has been scheduled
░░ Defined-By: systemd
░░ Support: http://www.ubuntu.com/support
```

I then tried to run sshd manually inside the VM, but received the following output:
```sh
root@sfdev:/var/log# /usr/sbin/sshd -d
debug1: sshd version OpenSSH_8.9, OpenSSL 3.0.2 15 Mar 2022
debug1: Unable to load host key: /etc/ssh/ssh_host_rsa_key
debug1: Unable to load host key: /etc/ssh/ssh_host_ecdsa_key
debug1: Unable to load host key: /etc/ssh/ssh_host_ed25519_key
sshd: no hostkeys available -- exiting.
```

I think the problem was that `regenerate-ssh-host-keys` was not being run, so I added the following line:
```sh
sudo systemctl start regenerate-ssh-host-keys
```

And it ran perfectly. I assume there was previously a reboot to sort this out?



_Code quote:_
```
sudo systemctl enable regenerate-ssh-host-keys
```

**Review by marksvc — COMMENTED** [review]
That's so strange! Can you tell me, what is the "Creation date" in the ~/machine-info.txt file? And does `sudo cat /root/regenerate-ssh-host-keys` show  that `--frontend=noninteractive` is in the script?

What should happen is that when the system boots, the regenerate-ssh-host-keys.service is called upon, which runs the regenerate-ssh-host-keys script, which generates host keys if they are not present. 
It was a problem recently in Ubuntu 22.04, because at boot time `dpkg-reconfigure` was trying to communicate with the user, couldn't, and gave up, and so no sshd host keys were created. I changed the script to use the `noninteractive` frontend. In my testing it successfully generated sshd host keys at boot time.

The vagrant guest should boot, provision, and work successfully when `vagrant up` is first run. It should say, for example, 

```
==> default: Booting VM...                                                                                                                                                                              
==> default: Waiting for machine to boot. This may take a few minutes...                                                                                                                                
    default: SSH address: 127.0.0.1:19149                                                                                                                                                               
    default: SSH username: vagrant                                                                                                                                                                      
    default: SSH auth method: private key                                                                                                                                                               
    default:                                                                                                                                                                                            
    default: Vagrant insecure key detected. Vagrant will automatically replace
    default: this with a newly generated keypair for better security.
...
==> default: Running provisioner: shell...
    default: Running: inline script
```

Inside the vagrant guest, `journalctl` should show messages like 
```
Jul 24 16:36:51 sfdev regenerate-ssh-host-keys[1272]: Creating SSH2 RSA key; this may take some time ...
...
Jul 24 16:36:52 sfdev systemd[1]: Starting OpenBSD Secure Shell server...
Jul 24 16:36:52 sfdev sshd[2051]: Server listening on 0.0.0.0 port 22.
Jul 24 16:36:52 sfdev sshd[2051]: Server listening on :: port 22.
Jul 24 16:36:52 sfdev systemd[1]: Started OpenBSD Secure Shell server.
```

I'm hoping it's just a matter of your box not getting updated all the way to version 1.1.1, but it may be something else I'll need to sort out.

Thanks!

> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/2554#-:-O2apCQ07D2jb2s1Lhv1:byvbygd)* status: all files reviewed, 1 unresolved discussion (waiting on @marksvc)

**Review by pmachapman — APPROVED** [review]
:lgtm: OK - I can't get the issue recreate now. I ran`vagrant destroy && vagrant up`, and it worked perfectly.

I deleted the `~/.vagrant.d` directory, then ran `vagrant up`, and it ran perfectly, too (and showed it was downloading 1.1.1).

I think it was perhaps a weird cache issue. I think if it occurs for anyone else, the solution will likely be to run `rm -rf ~/.vagrant.d`

I believe this is ready for release, but will leave it to you to change the PR status, and coordinate with the dev and test teams the rollout of this updated image.

To answer your questions, here are the timestamps for `~/machine-info.txt`:


Running `sudo cat /root/regenerate-ssh-host-keys` displays:
```sh
vagrant0sfdev:~
$ sudo cat /root/regenerate-ssh-host-keys
#!/bin/bash
# Regenerate ssh host keys if not present
test -f /etc/ssh/ssh_host_rsa_key || dpkg-reconfigure --frontend=noninteractive openssh-server
```

> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/2554#-:-O2b2BV6CYqYZUhQp5_v:b-q26az8)* status: all files reviewed, 1 unresolved discussion (waiting on @marksvc)

**Review by marksvc — COMMENTED** [review]
> Dismissed @pmachapman from a discussion.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/2554)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @marksvc)

___
*[`deploy/vagrant/sfdev/base/provision` line 94 at r3](https://reviewable.io/reviews/sillsdev/web-xforge/2554#-O2aluPD9V4ensV4LazA:-O2ewRXC5N8isPzlkuc_:b-896fix) ([raw file](https://github.com/sillsdev/web-xforge/blob/c5a80b3026158e66fa6cd8f2d5ac0aa65be1b63e/deploy/vagrant/sfdev/base/provision#L94)):*
<details><summary><i>Previously, pmachapman (Peter Chapman) wrote…</i></summary><blockquote>

When running `vagrant up` (after `vagrant box update && vagrant destroy`), I had the same error as before, and could not SSH into the box:

Journal:
```
░░ The job identifier is 2653.
Jul 24 15:41:40 sfdev sshd[3653]: sshd: no hostkeys available -- exiting.
Jul 24 15:41:40 sfdev systemd[1]: ssh.service: Control process exited, code=exited, status=1/FAILURE
░░ Subject: Unit process exited
░░ Defined-By: systemd
░░ Support: http://www.ubuntu.com/support
░░
░░ An ExecStartPre= process belonging to unit ssh.service has exited.
░░
░░ The process' exit code is 'exited' and its exit status is 1.
Jul 24 15:41:40 sfdev systemd[1]: ssh.service: Failed with result 'exit-code'.
░░ Subject: Unit failed
░░ Defined-By: systemd
░░ Support: http://www.ubuntu.com/support
░░
░░ The unit ssh.service has entered the 'failed' state with result 'exit-code'.
Jul 24 15:41:40 sfdev systemd[1]: Failed to start OpenBSD Secure Shell server.
░░ Subject: A start job for unit ssh.service has failed
░░ Defined-By: systemd
░░ Support: http://www.ubuntu.com/support
░░
░░ A start job for unit ssh.service has finished with a failure.
░░
░░ The job identifier is 2653 and the job result is failed.
Jul 24 15:41:40 sfdev systemd[1]: ssh.service: Scheduled restart job, restart counter is at 1.
░░ Subject: Automatic restarting of a unit has been scheduled
░░ Defined-By: systemd
░░ Support: http://www.ubuntu.com/support
```

I then tried to run sshd manually inside the VM, but received the following output:
```sh
root@sfdev:/var/log# /usr/sbin/sshd -d
debug1: sshd version OpenSSH_8.9, OpenSSL 3.0.2 15 Mar 2022
debug1: Unable to load host key: /etc/ssh/ssh_host_rsa_key
debug1: Unable to load host key: /etc/ssh/ssh_host_ecdsa_key
debug1: Unable to load host key: /etc/ssh/ssh_host_ed25519_key
sshd: no hostkeys available -- exiting.
```

I think the problem was that `regenerate-ssh-host-keys` was not being run, so I added the following line:
```sh
sudo systemctl start regenerate-ssh-host-keys
```

And it ran perfectly. I assume there was previously a reboot to sort this out?
</blockquote></details>

Done.

**Pull request merged**
