### PR TITLE
SF-1878 Mark note read when inserting new notes

### PR DESCRIPTION
**Pull request by RaymondLuong3**
* add note dataId to the project user config when saving a new note

- - -
This change is [Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1709)

### CODE REVIEW

**Review by nigel-wells — CHANGES_REQUESTED** [review]
Looks good - just one minor query.

> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1709#-:-NOfa3Ly7pbBhyaOCuOb:b-yu6kme)* status: all files reviewed, 1 unresolved discussion (waiting on @RaymondLuong3)

___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/note-dialog/note-dialog.component.spec.ts` line 782 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/1709#-NOf_oHW4GyDa051Oufi:-NOf_oHW4GyDa051Oufj:b3zb5y7) ([raw file](https://github.com/sillsdev/web-xforge/blob/80ddaee156207acaa61a33da0c28183c1e11cdc7/src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/note-dialog/note-dialog.component.spec.ts#L782)):*
> ```XML
> 
>     when(mockedProjectService.getUserConfig(configData.projectId, currentUserId)).thenCall((projectId, userId) =>
>       this.realtimeService.subscribe(SFProjectUserConfigDoc.COLLECTION, `${projectId}:${userId}`)
> ```

I see this is written differently from the other ways that used the `.join(':')`? Perhaps you could create a simple method to create the ID you're after and use that everywhere?

**Review by Nateowami — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1709)* status: all files reviewed, 2 unresolved discussions (waiting on @RaymondLuong3)

___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/note-dialog/note-dialog.component.spec.ts` line 880 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/1709#-NOjoR1V01sGJUuWFars:-NOjoR1V01sGJUuWFart:b-62jhtl) ([raw file](https://github.com/sillsdev/web-xforge/blob/80ddaee156207acaa61a33da0c28183c1e11cdc7/src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/note-dialog/note-dialog.component.spec.ts#L880)):*
> ```XML
> 
>   getProjectUserConfigDoc(projectId: string, userId: string): SFProjectUserConfigDoc {
>     const id: string = [projectId, userId].join(':');
> ```

How about using this function from `src/RealtimeServer/scriptureforge/models/sf-project-user-config.ts`:
``` ts
export function getSFProjectUserConfigDocId(projectId: string, userId: string): string {
  return `${projectId}:${userId}`;
}
```

**Review by RaymondLuong3 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1709)* status: 1 of 2 files reviewed, 2 unresolved discussions (waiting on @Nateowami and @nigel-wells)

___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/note-dialog/note-dialog.component.spec.ts` line 782 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/1709#-NOf_oHW4GyDa051Oufi:-NOvJzxLAXkwVUBGRgOk:bwgzq3k) ([raw file](https://github.com/sillsdev/web-xforge/blob/80ddaee156207acaa61a33da0c28183c1e11cdc7/src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/note-dialog/note-dialog.component.spec.ts#L782)):*
<details><summary><i>Previously, nigel-wells (Nigel Wells) wrote…</i></summary><blockquote>

I see this is written differently from the other ways that used the `.join(':')`? Perhaps you could create a simple method to create the ID you're after and use that everywhere?
</blockquote></details>

Good catch. I've used Nathaniel's suggestion to use the existing function to get the project user doc ID.
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/note-dialog/note-dialog.component.spec.ts` line 880 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/1709#-NOjoR1V01sGJUuWFars:-NOvK8glDq1sAZhjcGaB:b-896fix) ([raw file](https://github.com/sillsdev/web-xforge/blob/80ddaee156207acaa61a33da0c28183c1e11cdc7/src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/note-dialog/note-dialog.component.spec.ts#L880)):*
<details><summary><i>Previously, Nateowami (Nathaniel Paulus) wrote…</i></summary><blockquote>

How about using this function from `src/RealtimeServer/scriptureforge/models/sf-project-user-config.ts`:
``` ts
export function getSFProjectUserConfigDocId(projectId: string, userId: string): string {
  return `${projectId}:${userId}`;
}
```
</blockquote></details>

Done.

**Review by nigel-wells — COMMENTED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1709)* status: all files reviewed, 2 unresolved discussions (waiting on @Nateowami)

**Review by nigel-wells — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1709#-:-NP-34557rcOYjAILZfi:bnfp4nl)* status: all files reviewed, 2 unresolved discussions (waiting on @Nateowami)

**Review by nigel-wells — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1709)* status: all files reviewed, 1 unresolved discussion (waiting on @Nateowami)

**Comment by RaymondLuong3** [comment]
Whoops, I accidentally merged this before testing was done. I'll get the testers on this.

**Pull request merged**
