### PR TITLE
Add Deploy GitHub workflows

### PR DESCRIPTION
**Pull request by marksvc**
release.yml does the work to build and deploy.
release-qa.yml and release-live.yml instruct release,yml to deploy for a given branch.

This change is [Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/2535)

### CODE REVIEW

**Comment by marksvc** [comment]
Well, since testing, I did a bunch of refactoring.

**Comment by jasonleenaylor** [comment]
*[`.github/workflows/compute-next-version.yml` line 9 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/2535#-O2fSvETDdN8WsDrVcKP:-O2fSvETDdN8WsDrVcKQ:bp6jl0u) ([raw file](https://github.com/sillsdev/web-xforge/blob/4f33ae30c0f3e82cfb5165d49affd525597ddeb0/.github/workflows/compute-next-version.yml#L9)):*
> ```YAML
>         description: "The type of versioning system. Options: production, staging."
>         required: true
>         type: string
> ```

Enhancement:
`type: choice
options:
- production
- staging
`

**Comment by jasonleenaylor** [comment]
*[`.github/workflows/compute-next-version.yml` line 9 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/2535#-O2fSvETDdN8WsDrVcKP:-O2fTQUjCoFgYn3GbsXV:b-ntk9n2) ([raw file](https://github.com/sillsdev/web-xforge/blob/4f33ae30c0f3e82cfb5165d49affd525597ddeb0/.github/workflows/compute-next-version.yml#L9)):*
<details><summary><i>Previously, jasonleenaylor (Jason Naylor) wrote…</i></summary><blockquote>

Enhancement:
`type: choice
options:
- production
- staging
`
</blockquote></details>

(hmm, markdown applied to code...)

**Comment by jasonleenaylor** [comment]
*[`.github/workflows/compute-next-version.yml` line 9 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/2535#-O2fSvETDdN8WsDrVcKP:-O2fTb2Z9GwOH1MlkFNH:b-xazwje) ([raw file](https://github.com/sillsdev/web-xforge/blob/4f33ae30c0f3e82cfb5165d49affd525597ddeb0/.github/workflows/compute-next-version.yml#L9)):*
<details><summary><i>Previously, jasonleenaylor (Jason Naylor) wrote…</i></summary><blockquote>

(hmm, markdown applied to code...)
</blockquote></details>

Oh, actually, this is a call rather than a dispatch. I'm not sure if choice is available.

**Comment by jasonleenaylor** [comment]
*[`.github/workflows/release.yml` line 47 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/2535#-O2fUK_WAow4jhbrc7ei:-O2fUK_WAow4jhbrc7ej:bssn6x2) ([raw file](https://github.com/sillsdev/web-xforge/blob/4f33ae30c0f3e82cfb5165d49affd525597ddeb0/.github/workflows/release.yml#L47)):*
> ```YAML
>         required: true
>       node_options:
>         description: ""
> ```

perhaps a better description here?

**Review by marksvc — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/2535)* status: 0 of 6 files reviewed, all discussions resolved (waiting on @jasonleenaylor)

___
*[`.github/workflows/compute-next-version.yml` line 9 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/2535#-O2fSvETDdN8WsDrVcKP:-O2fibiaEpugwp6tLLJ6:b-tnb5lw) ([raw file](https://github.com/sillsdev/web-xforge/blob/4f33ae30c0f3e82cfb5165d49affd525597ddeb0/.github/workflows/compute-next-version.yml#L9)):*
<details><summary><i>Previously, jasonleenaylor (Jason Naylor) wrote…</i></summary><blockquote>

Oh, actually, this is a call rather than a dispatch. I'm not sure if choice is available.
</blockquote></details>

I gave it a try, and VSCode complained. It looks like the [docs](https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#onworkflow_callinputsinput_idtype) say the type is limited to boolean, number, and string. Makes sense.
___
*[`.github/workflows/release.yml` line 47 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/2535#-O2fUK_WAow4jhbrc7ei:-O2fhLEz0ukIOVTApc4o:b-jpuws) ([raw file](https://github.com/sillsdev/web-xforge/blob/4f33ae30c0f3e82cfb5165d49affd525597ddeb0/.github/workflows/release.yml#L47)):*
<details><summary><i>Previously, jasonleenaylor (Jason Naylor) wrote…</i></summary><blockquote>

perhaps a better description here?
</blockquote></details>

Yeah. I left that blank because I was uncertain. 
I think it's only affecting the `npm install` and building of RealtimeServer. I'll fill something in.

**Review by jasonleenaylor — APPROVED** [review]
:lgtm:

> Reviewed 6 of 6 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/2535#-:-O2fnG1H5f8mF0txOK99:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @marksvc)

**Pull request merged**
