### PR TITLE
Remove unused SFRegistrationInfo

### PR DESCRIPTION
**Pull request by marksvc**
---
This change is [Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/961)

### CODE REVIEW

**Review by RaymondLuong3 — CHANGES_REQUESTED** [review]
> Reviewed 3 of 3 files at r1.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/961)* status: all files reviewed, 1 unresolved discussion (waiting on @marksvc)

___
*[src/SIL.XForge.Scripture/Services/LazyScrTextCollection.cs, line 13 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/961#-MTw_poV1hlZCPsSic7v:-MTw_poV1hlZCPsSic7w:b-24bkvb) ([raw file](https://github.com/sillsdev/web-xforge/blob/b8ac65c4eb2bd0377f68772ba63ecea95ec55a98/src/SIL.XForge.Scripture/Services/LazyScrTextCollection.cs#L13)):*
> ```
> Provides a FindById() method that can be queried for a specific Paratext username.
> ```
Maybe a comment like 'A class that can be used to get a ScrText without using a cache. This class is not related...` The comment on FindById already explains what FindById does.

**Review by marksvc — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/961#-:-MUA26WK-xM2oNA1DlqT:bnfp4nl)* status: 2 of 3 files reviewed, 1 unresolved discussion (waiting on @RaymondLuong3)

___
*[src/SIL.XForge.Scripture/Services/LazyScrTextCollection.cs, line 13 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/961#-MTw_poV1hlZCPsSic7v:-MUA23nI9CKfp6EXKAqk:b-cmhn70) ([raw file](https://github.com/sillsdev/web-xforge/blob/b8ac65c4eb2bd0377f68772ba63ecea95ec55a98/src/SIL.XForge.Scripture/Services/LazyScrTextCollection.cs#L13)):*
<details><summary><i>Previously, RaymondLuong3 (Raymond Luong) wrote…</i></summary><blockquote>

> ```
> Provides a FindById() method that can be queried for a specific Paratext username.
> ```
Maybe a comment like 'A class that can be used to get a ScrText without using a cache. This class is not related...` The comment on FindById already explains what FindById does.
</blockquote></details>

Thanks! Good point.

**Review by marksvc — COMMENTED** [review]
(Haha, I meant to click to "Acknowledge" preceding messages, not to mark the commit as approved :) 

> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/961#-:-MUA28xj-SdZLs_V3_qZ:bbyradh)* status: 2 of 3 files reviewed, 1 unresolved discussion (waiting on @RaymondLuong3)

**Review by RaymondLuong3 — APPROVED** [review]
:lgtm: 

> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/961#-:-MUEeN2uAcUpLuKplDL6:bg7igkv)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
