### PR TITLE
SF-2263 Notify users when chapter audio is missing

### PR DESCRIPTION
**Pull request by RaymondLuong3**
This PR adds the info to notify a user if the question currently in view is on a chapter that do not have scripture audio when the project has the setting for hiding scripture text set to true.

Users with the ability to upload scripture audio get an additional message that is visible above the questions panel to indicate that there are questions in the project on chapters without audio. Community checker users will not see this so that they will not be distracted from answering questions.

Message on the questions list and the active question
No audio for chapter with questions

Community checker view
No audio for chapter community checker

- - -
This change is [Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/2152)

### CODE REVIEW

**Review by Nateowami — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/2152)* status: 0 of 6 files reviewed, 1 unresolved discussion (waiting on @RaymondLuong3)

___
*[`src/SIL.XForge.Scripture/ClientApp/src/assets/i18n/checking_en.json` line 173 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/2152#-Ni5KLrn8sncADDj81fX:-Ni5KLrn8sncADDj81fY:bv0qzi2) ([raw file](https://github.com/sillsdev/web-xforge/blob/4dbfa02f0c8789874a5b2191eae8e4c03dca19ad/src/SIL.XForge.Scripture/ClientApp/src/assets/i18n/checking_en.json#L173)):*
> ```JSON
>     "question_filter_not_reviewed": "Unreviewed answers",
>     "question_filter_resolved": "Answers marked resolved",
>     "questions_on_chapters_no_audio": "Questions exist for chapters that have no audio recordings. Please upload audio for these chapters.",
> ```

I think this is very confusing wording. Even knowing approximately what this was about, I had trouble fully understanding it.

What about "Some chapters in the project have questions but no audio recordings. Please upload audio for these chapters."

I don't want this task to creep in size too much, but this warning seems like something that could easily be used in multiple places, e.g. on the project dashboard, or shown when inviting users. Which makes it an ideal candidate for a service.

**Review by RaymondLuong3 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/2152)* status: 0 of 6 files reviewed, 1 unresolved discussion (waiting on @Nateowami)

___
*[`src/SIL.XForge.Scripture/ClientApp/src/assets/i18n/checking_en.json` line 173 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/2152#-Ni5KLrn8sncADDj81fX:-Ni5QOqR8hHbjMw1wCro:b-xl4hci) ([raw file](https://github.com/sillsdev/web-xforge/blob/4dbfa02f0c8789874a5b2191eae8e4c03dca19ad/src/SIL.XForge.Scripture/ClientApp/src/assets/i18n/checking_en.json#L173)):*
<details><summary><i>Previously, Nateowami (Nathaniel Paulus) wrote…</i></summary><blockquote>

I think this is very confusing wording. Even knowing approximately what this was about, I had trouble fully understanding it.

What about "Some chapters in the project have questions but no audio recordings. Please upload audio for these chapters."

I don't want this task to creep in size too much, but this warning seems like something that could easily be used in multiple places, e.g. on the project dashboard, or shown when inviting users. Which makes it an ideal candidate for a service.
</blockquote></details>

Hmm, you are probably right that this could be added to a service. We can always make that happen at a later time.

**Review by pmachapman — CHANGES_REQUESTED** [review]
> Reviewed 5 of 6 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/2152)* status: all files reviewed, 1 unresolved discussion (waiting on @RaymondLuong3)

___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking.component.scss` line 171 at r2](https://reviewable.io/reviews/sillsdev/web-xforge/2152#-NiBDM3J8c-YrZEl1fCP:-NiBDM3J8c-YrZEl1fCQ:b-p1c8e7) ([raw file](https://github.com/sillsdev/web-xforge/blob/9cabe30d631619ef2a4cd7619ca712f855568473/src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking.component.scss#L171)):*
> ```SCSS
>       justify-content: space-between;
>       flex: 1;
>       width: 100%;
> ```

Why did you add this? I would have thought that `flex: 1;` would have caused it to fill the width of the parent container?

In my brief testing removing it didn't seem to change anything?



_Code quote:_
```SCSS
width: 100%;
```
___
*[`src/SIL.XForge.Scripture/ClientApp/src/assets/i18n/checking_en.json` line 173 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/2152#-Ni5KLrn8sncADDj81fX:-NiB8fCI8BWAunKBrYdS:bb6ywmx) ([raw file](https://github.com/sillsdev/web-xforge/blob/4dbfa02f0c8789874a5b2191eae8e4c03dca19ad/src/SIL.XForge.Scripture/ClientApp/src/assets/i18n/checking_en.json#L173)):*
<details><summary><i>Previously, RaymondLuong3 (Raymond Luong) wrote…</i></summary><blockquote>

Hmm, you are probably right that this could be added to a service. We can always make that happen at a later time.
</blockquote></details>

LGTM

**Review by RaymondLuong3 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/2152)* status: all files reviewed, 1 unresolved discussion (waiting on @pmachapman)

___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking.component.scss` line 171 at r2](https://reviewable.io/reviews/sillsdev/web-xforge/2152#-NiBDM3J8c-YrZEl1fCP:-NiBEXtV-L6NjVrI2rAa:blvc268) ([raw file](https://github.com/sillsdev/web-xforge/blob/9cabe30d631619ef2a4cd7619ca712f855568473/src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking.component.scss#L171)):*
<details><summary><i>Previously, pmachapman (Peter Chapman) wrote…</i></summary><blockquote>

Why did you add this? I would have thought that `flex: 1;` would have caused it to fill the width of the parent container?

In my brief testing removing it didn't seem to change anything?
</blockquote></details>

Done. I think this was an artifact from a rebase that I missed.

**Review by marksvc — CHANGES_REQUESTED** [review]
> Reviewed 5 of 5 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/2152)* status: all files reviewed, 2 unresolved discussions (waiting on @RaymondLuong3)

___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking.component.ts` line 641 at r4](https://reviewable.io/reviews/sillsdev/web-xforge/2152#-NikH7xsBDyce7uAoh2J:-NikH7xsBDyce7uAoh2K:b3zvj3k) ([raw file](https://github.com/sillsdev/web-xforge/blob/63a1dda64dfa2e9be611cedf323978c1d2288be9/src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking.component.ts#L641)):*
> `!`

I recently found a `!` in production that was causing a crash. I think it will help us to avoid putting these into production. Maybe the code could be prefixed with a check, like the following?
```ts
if (this.projectDoc) {
    this.textAudioSub = this.subscribe(
        merge(this.questionsQuery.ready$, this.projectDoc.remoteChanges$),
        () => this.updateAudioMissingWarning()
    );
}
```
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking.component.ts` line 700 at r4](https://reviewable.io/reviews/sillsdev/web-xforge/2152#-NikdevFDz0CHNXrgRVw:-NikdevFDz0CHNXrgRVx:b-f159h8) ([raw file](https://github.com/sillsdev/web-xforge/blob/63a1dda64dfa2e9be611cedf323978c1d2288be9/src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking.component.ts#L700)):*
> ```XML
>               ),
>               () => {
>                 this.updateAudioMissingWarning();
> ```

It seems odd to do this in the subscription watching for watching for questions changes. Wouldn't we instead want to do this in response to (1) changing the chapter, and (2) project audio appearing or disappearing ?

**Review by RaymondLuong3 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/2152)* status: 5 of 6 files reviewed, 2 unresolved discussions (waiting on @marksvc)

___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking.component.ts` line 641 at r4](https://reviewable.io/reviews/sillsdev/web-xforge/2152#-NikH7xsBDyce7uAoh2J:-NikiPgr4mLQAhmu4MEj:bdzgul0) ([raw file](https://github.com/sillsdev/web-xforge/blob/63a1dda64dfa2e9be611cedf323978c1d2288be9/src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking.component.ts#L641)):*
<details><summary><i>Previously, marksvc wrote…</i></summary><blockquote>

> `!`

I recently found a `!` in production that was causing a crash. I think it will help us to avoid putting these into production. Maybe the code could be prefixed with a check, like the following?
```ts
if (this.projectDoc) {
    this.textAudioSub = this.subscribe(
        merge(this.questionsQuery.ready$, this.projectDoc.remoteChanges$),
        () => this.updateAudioMissingWarning()
    );
}
```
</blockquote></details>

Good thinking. I've made this change.
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking.component.ts` line 700 at r4](https://reviewable.io/reviews/sillsdev/web-xforge/2152#-NikdevFDz0CHNXrgRVw:-NikiUsl-IWByz8_2jwk:bzdsnkg) ([raw file](https://github.com/sillsdev/web-xforge/blob/63a1dda64dfa2e9be611cedf323978c1d2288be9/src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking.component.ts#L700)):*
<details><summary><i>Previously, marksvc wrote…</i></summary><blockquote>

It seems odd to do this in the subscription watching for watching for questions changes. Wouldn't we instead want to do this in response to (1) changing the chapter, and (2) project audio appearing or disappearing ?
</blockquote></details>

The update needs to happen (1) when the question query updates and (2) when the text audio query updates. Here we update the warning message when changes are made to the questions collection because if a question is added on a chapter without audio, we need to show this message.
When changing chapters, the question query updates, and then this will get called also.

**Review by marksvc — APPROVED** [review]
> Reviewed 1 of 6 files at r1, 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/2152)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @RaymondLuong3)

**Pull request merged**
