### PR TITLE
SF-2036 Checking comments components use mat-button

### PR DESCRIPTION
**Pull request by josephmyers**
This change is [Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1866)

### CODE REVIEW

**Review by Nateowami — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1866)* status: all files reviewed (commit messages unreviewed), 1 unresolved discussion (waiting on @josephmyers)

___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-answers/checking-comments/checking-comments.component.html` line 16 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/1866#-NWGOado7syExDRgy-t0:-NWGOado7syExDRgy-t1:bmyiski) ([raw file](https://github.com/sillsdev/web-xforge/blob/6d7fad0349812a7af677de83c85e744185849647/src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-answers/checking-comments/checking-comments.component.html#L16)):*
> ```HTML
>         <button
>           *ngIf="canEditComment(comment)"
>           mat-button
> ```

The changes here alter the height of the buttons, making them taller than they were before.

**Review by josephmyers — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1866)* status: 2 of 3 files reviewed, 1 unresolved discussion (waiting on @Nateowami)

___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-answers/checking-comments/checking-comments.component.html` line 16 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/1866#-NWGOado7syExDRgy-t0:-NWHTnM42HgFPwrvyq-c:b-896fix) ([raw file](https://github.com/sillsdev/web-xforge/blob/6d7fad0349812a7af677de83c85e744185849647/src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-answers/checking-comments/checking-comments.component.html#L16)):*
<details><summary><i>Previously, Nateowami (Nathaniel Paulus) wrote…</i></summary><blockquote>

The changes here alter the height of the buttons, making them taller than they were before.
</blockquote></details>

Done.

**Review by RaymondLuong3 — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1866)* status: all files reviewed, 3 unresolved discussions (waiting on @josephmyers and @Nateowami)

___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-answers/checking-comments/checking-comments.component.scss` line 37 at r2](https://reviewable.io/reviews/sillsdev/web-xforge/1866#-NWhlQ5Z7tYaCOhCts1q:-NWhlQ5_6B99dp0hj5aI:b-78m8kd) ([raw file](https://github.com/sillsdev/web-xforge/blob/5434e71dc358724a65fa84276ae73e694bc1a87f/src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-answers/checking-comments/checking-comments.component.scss#L37)):*
> ```SCSS
>     }
> 
>     .mat-button {
> ```

Hey, I noticed that some of the buttons is really close to author label. You can improve it like this.

___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-answers/checking-comments/checking-comments.component.scss` line 46 at r2](https://reviewable.io/reviews/sillsdev/web-xforge/1866#-NWhmIFsAsk6nII6jo2A:-NWhmIFsAsk6nII6jo2B:bif7kzs) ([raw file](https://github.com/sillsdev/web-xforge/blob/5434e71dc358724a65fa84276ae73e694bc1a87f/src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-answers/checking-comments/checking-comments.component.scss#L46)):*
> ```SCSS
>   line-height: unset;
>   padding: 0 8px;
>   margin-top: 8px;
> ```

I see what you mean here. Nice.

**Review by Nateowami — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1866)* status: all files reviewed, 5 unresolved discussions (waiting on @josephmyers)

___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-answers/checking-comments/checking-comments.component.html` line 55 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/1866#-NWhrraFA3J4WLOwqSa3:-NWhrraFA3J4WLOwqSa4:bijiw7w) ([raw file](https://github.com/sillsdev/web-xforge/blob/6d7fad0349812a7af677de83c85e744185849647/src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-answers/checking-comments/checking-comments.component.html#L55)):*
> ```HTML
>     {{ showMoreCommentsLabel }}
>   </button>
>   <button
> ```

This button is now shorter than it was before.
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-answers/checking-comments/checking-comment-form/checking-comment-form.component.html` line 10 at r2](https://reviewable.io/reviews/sillsdev/web-xforge/1866#-NWhsVep1jDQWsRDRVnX:-NWhsVep1jDQWsRDRVnY:b-7cfuwg) ([raw file](https://github.com/sillsdev/web-xforge/blob/5434e71dc358724a65fa84276ae73e694bc1a87f/src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-answers/checking-comments/checking-comment-form/checking-comment-form.component.html#L10)):*
> ```HTML
>     <div class="form-actions">
>       <button mat-button type="button" (click)="submitCancel()" class="cancel-comment">{{ t("cancel") }}</button>
>       <button mat-flat-button type="submit" class="save-comment">
> ```

This button doesn't look like it did before.

**Review by josephmyers — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1866)* status: 1 of 3 files reviewed, 4 unresolved discussions (waiting on @Nateowami and @RaymondLuong3)

___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-answers/checking-comments/checking-comments.component.html` line 55 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/1866#-NWhrraFA3J4WLOwqSa3:-NWkGEmWEGO2cfxM7Aof:b-896fix) ([raw file](https://github.com/sillsdev/web-xforge/blob/6d7fad0349812a7af677de83c85e744185849647/src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-answers/checking-comments/checking-comments.component.html#L55)):*
<details><summary><i>Previously, Nateowami (Nathaniel Paulus) wrote…</i></summary><blockquote>

This button is now shorter than it was before.
</blockquote></details>

Done.
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-answers/checking-comments/checking-comments.component.scss` line 37 at r2](https://reviewable.io/reviews/sillsdev/web-xforge/1866#-NWhlQ5Z7tYaCOhCts1q:-NWkJIX4-sfcpLVx0dCz:b-giyvjj) ([raw file](https://github.com/sillsdev/web-xforge/blob/5434e71dc358724a65fa84276ae73e694bc1a87f/src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-answers/checking-comments/checking-comments.component.scss#L37)):*
<details><summary><i>Previously, RaymondLuong3 (Raymond Luong) wrote…</i></summary><blockquote>

Hey, I noticed that some of the buttons is really close to author label. You can improve it like this.


</blockquote></details>

It does increase the spacing, but this makes all comments 8 pixels taller as well. Is that the direction we want to go? It looks a little clunky to me. The previous buttons were close, like they are without this proposed change. I have no problem either way, just let me know
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-answers/checking-comments/checking-comment-form/checking-comment-form.component.html` line 10 at r2](https://reviewable.io/reviews/sillsdev/web-xforge/1866#-NWhsVep1jDQWsRDRVnX:-NWkLP-Y4PMcyuyDesJW:b-4cmjx8) ([raw file](https://github.com/sillsdev/web-xforge/blob/5434e71dc358724a65fa84276ae73e694bc1a87f/src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-answers/checking-comments/checking-comment-form/checking-comment-form.component.html#L10)):*
<details><summary><i>Previously, Nateowami (Nathaniel Paulus) wrote…</i></summary><blockquote>

This button doesn't look like it did before.
</blockquote></details>

Excellent, thank you

**Review by RaymondLuong3 — APPROVED** [review]
I'm happy with these changes.

> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1866#-:-NWmehEgEqCZiz4ug0y4:b-i2qhdg)* status: all files reviewed, 3 unresolved discussions (waiting on @Nateowami)

___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-answers/checking-comments/checking-comments.component.scss` line 37 at r2](https://reviewable.io/reviews/sillsdev/web-xforge/1866#-NWhlQ5Z7tYaCOhCts1q:-NWmeVsr-vzHkONy_THN:b-w5oc1w) ([raw file](https://github.com/sillsdev/web-xforge/blob/5434e71dc358724a65fa84276ae73e694bc1a87f/src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-answers/checking-comments/checking-comments.component.scss#L37)):*
<details><summary><i>Previously, josephmyers wrote…</i></summary><blockquote>

It does increase the spacing, but this makes all comments 8 pixels taller as well. Is that the direction we want to go? It looks a little clunky to me. The previous buttons were close, like they are without this proposed change. I have no problem either way, just let me know
</blockquote></details>

Hmm, I see what you mean as it looks as it did before without the extra margin. I'm ok with that.

**Pull request merged**
