### PR TITLE
SF-2449 Add verse ref to checking question list items

### PR DESCRIPTION
**Pull request by siltomato**
The added verse ref is on a second line along with the "answers" indicator.

image

- - -
This change is [Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/2282)

### CODE REVIEW

**Review by RaymondLuong3 — CHANGES_REQUESTED** [review]
It is really minor, but it might look better to have the forum icon centered vertically.
I noticed that in RTL mode, the verse reference does not look correct, the chapter and verse do not display in the right order. I wonder if the mat list does not have the direction set correctly

> Reviewed 4 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/2282#-:-NneI3AgAqOidxLhLAbb:byqwus4)* status: all files reviewed, 1 unresolved discussion (waiting on @siltomato)

___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-questions/checking-questions.component.ts` line 396 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/2282#-NneKoHlDvTvb0WRZIPf:-NneKoHlDvTvb0WRZIPg:b8bx4rt) ([raw file](https://github.com/sillsdev/web-xforge/blob/803e608adfbccb0a1692078f4b8c383a9bff2861/src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-questions/checking-questions.component.ts#L396)):*
> ```XML
> 
>     const { bookNum, chapterNum, verseNum, verse } = questionDoc.data.verseRef;
>     return `${this.i18n.localizeBook(bookNum)} ${chapterNum}:${verse || verseNum}`;
> ```

You should make a verseRef the question doc.



_Code quote (i):_
```XML
    return `${this.i18n.localizeBook(bookNum)} ${chapterNum}:${verse || verseNum}`;
```



_Code snippet (ii):_
```XML
    this.i18n.localizeReference(toVerseRef(questionDoc.data.verseRef));
```

**Review by siltomato — COMMENTED** [review]
I agree that the forum icon looks better when the questions are shorter, but the extra text space does seem nice when the question text runs longer.  What do you think is the norm for question length?

I took inspiration from Nigel's suggestion where the verse text can run all the way to the end:


> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/2282#-:-NneQ4IFCFAxh_GJd-Zy:b4r6oro)* status: 3 of 4 files reviewed, 1 unresolved discussion (waiting on @RaymondLuong3)

___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-questions/checking-questions.component.ts` line 396 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/2282#-NneKoHlDvTvb0WRZIPf:-NneUc0m7uRDiiqE4ucw:b-cut63l) ([raw file](https://github.com/sillsdev/web-xforge/blob/803e608adfbccb0a1692078f4b8c383a9bff2861/src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-questions/checking-questions.component.ts#L396)):*
<details><summary><i>Previously, RaymondLuong3 (Raymond Luong) wrote…</i></summary><blockquote>

You should make a verseRef the question doc.
</blockquote></details>

Ah thanks for that.  Done.

**Review by RaymondLuong3 — APPROVED** [review]
Hmm, good thinking. That is probably a good reason to keep it at the bottom. Thanks.

> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/2282#-:-NneoK1L78OhFscn-0K_:b-b6tq0v)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @siltomato)

**Review by siltomato — COMMENTED** [review]
Added `&rlm;` "direction mark" before chapter number for the case where non-localized book names are in a RTL environment so the chapter number displays with the verse.  See tester image below:



> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/2282#-:-Nno7DbmE9kfLVr48pQB:b-xak0as)* status: 4 of 6 files reviewed, all discussions resolved (waiting on @RaymondLuong3)

**Review by RaymondLuong3 — APPROVED** [review]
Nice fix!

> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/2282#-:-NnoPJHj53i1FmaJy3bO:b-k6moza)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @siltomato)

**Pull request merged**
