### PR TITLE
SF-2124 Rewrite NotesFormatter.ParseParagraph to use XElement

### PR DESCRIPTION
**Pull request by Nateowami**
This change is [Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1820)

### CODE REVIEW

**Review by Nateowami — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1820)* status: all files reviewed, 1 unresolved discussion (waiting on @RaymondLuong3)

___
*[`src/SIL.XForge.Scripture/Services/NotesFormatter.cs` line 229 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/1820#-NUbLAtR84TP9b_QTT9b:-NUcDp9559R0uj14wCsI:b-73rtq0) ([raw file](https://github.com/sillsdev/web-xforge/blob/23c231bdc998ed928db84218c3743d89acab2262/src/SIL.XForge.Scripture/Services/NotesFormatter.cs#L229)):*
<details><summary><i>Previously, RaymondLuong3 (Raymond Luong) wrote…</i></summary><blockquote>

Why did you default the style to be a span other than bold? Is that because that is a better default?
</blockquote></details>

I thought it made more sense to map `<span>Text</span>` to `<span>Text</span>` than to `<bold>Text</bold>`. I'm not sure why we would apply a bold style when none was specified.

**Review by RaymondLuong3 — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1820)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @Nateowami)

___
*[`src/SIL.XForge.Scripture/Services/NotesFormatter.cs` line 229 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/1820#-NUbLAtR84TP9b_QTT9b:-NUcg9Ez5h_vBewMHFzq:b4vpaje) ([raw file](https://github.com/sillsdev/web-xforge/blob/23c231bdc998ed928db84218c3743d89acab2262/src/SIL.XForge.Scripture/Services/NotesFormatter.cs#L229)):*
<details><summary><i>Previously, Nateowami (Nathaniel Paulus) wrote…</i></summary><blockquote>

I thought it made more sense to map `<span>Text</span>` to `<span>Text</span>` than to `<bold>Text</bold>`. I'm not sure why we would apply a bold style when none was specified.
</blockquote></details>

I looked through our code, and I do not believe that we create an `<span>...</span>` nodes without a style. This means that when we ship this it should not make massive changes to projects with lots of answers, so that is good.

**Review by RaymondLuong3 — APPROVED** [review]
You will want to create an issue and add some acceptance tests so testers know what to look for.

> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1820#-:-NUcgr1mEINYVKS5afeR:bomjhxd)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @Nateowami)

**Comment by Nateowami** [comment]
@RaymondLuong3 I'm not actually sure what the issue description for this should be or how exactly it's used. Would you mind creating an issue for this with some basic acceptance tests?

**Pull request merged**
