### PR TITLE
SF-2080 Create circular audio progress component

### PR DESCRIPTION
**Pull request by Nateowami**
This is a display-only component; it knows nothing about audio.

- - -
This change is [Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1898)

### CODE REVIEW

**Review by Nateowami — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1898)* status: 0 of 4 files reviewed, all discussions resolved

___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/single-button-audio-player/single-button-audio-player.component.html` line 1 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/1898#-NXrGVG7-VZALzhO1928:-NXrGVG7-VZALzhO1929:b-s2fmtg) ([raw file](https://github.com/sillsdev/web-xforge/blob/3ca5a1f87718d201b94a8d72f47f789344fe7ccc/src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/single-button-audio-player/single-button-audio-player.component.html#L1)):*
> ```HTML
> <button type="button" [style.--audio-progress]="progressInDegrees">
> ```

In case it's not clear, this is setting a CSS variable, which is then used in our CSS.

**Review by RaymondLuong3 — CHANGES_REQUESTED** [review]
> Reviewed 4 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1898)* status: all files reviewed, 2 unresolved discussions (waiting on @Nateowami)

___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/single-button-audio-player/single-button-audio-player.component.html` line 1 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/1898#-NXrGVG7-VZALzhO1928:-NXvUYdGClhzYahT7TSc:b3pg0p3) ([raw file](https://github.com/sillsdev/web-xforge/blob/3ca5a1f87718d201b94a8d72f47f789344fe7ccc/src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/single-button-audio-player/single-button-audio-player.component.html#L1)):*
<details><summary><i>Previously, Nateowami (Nathaniel Paulus) wrote…</i></summary><blockquote>

In case it's not clear, this is setting a CSS variable, which is then used in our CSS.
</blockquote></details>

Hmm, that's a neat trick to set a CSS variable and bind it to a value in the ts. I'll have to remember that one.
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/single-button-audio-player/single-button-audio-player.component.scss` line 4 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/1898#-NXvY8p7-SsdQ0-oPlpT:-NXvY8p7-SsdQ0-oPlpU:bu8rgp) ([raw file](https://github.com/sillsdev/web-xforge/blob/3ca5a1f87718d201b94a8d72f47f789344fe7ccc/src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/single-button-audio-player/single-button-audio-player.component.scss#L4)):*
> ```SCSS
> 
> $buttonColor: $purpleLight;
> $progressColor: rgb(26, 179, 18);
> ```

Is there a reason why the progress colour has the be green? I think it would look nicer if the colour matched the light purple button colour. The green and purple kind of clash.
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/single-button-audio-player/single-button-audio-player.component.scss` line 20 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/1898#-NXvUzY72G0xL2YAbQxf:-NXvUzY72G0xL2YAbQxg:b-5dtcao) ([raw file](https://github.com/sillsdev/web-xforge/blob/3ca5a1f87718d201b94a8d72f47f789344fe7ccc/src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/single-button-audio-player/single-button-audio-player.component.scss#L20)):*
> ```SCSS
>   // Create a radial gradient and then remove the center of it with a conic gradient to create a circular progress bar
>   // The transition between white and transparent happens over several percentage points to avoid aliasing
>   background: radial-gradient(white 57%, transparent 61% 100%),
> ```

I'm not really sure what is meant by aliasing here. What is aliasing in this context?

**Review by Nateowami — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1898)* status: all files reviewed, 2 unresolved discussions (waiting on @RaymondLuong3)

___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/single-button-audio-player/single-button-audio-player.component.scss` line 4 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/1898#-NXvY8p7-SsdQ0-oPlpT:-NXvbPCi6iMfuPIyTV4b:b-67xk9t) ([raw file](https://github.com/sillsdev/web-xforge/blob/3ca5a1f87718d201b94a8d72f47f789344fe7ccc/src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/single-button-audio-player/single-button-audio-player.component.scss#L4)):*
<details><summary><i>Previously, RaymondLuong3 (Raymond Luong) wrote…</i></summary><blockquote>

Is there a reason why the progress colour has the be green? I think it would look nicer if the colour matched the light purple button colour. The green and purple kind of clash.
</blockquote></details>

I was following the design in the UX pin. I think this is an ideal candidate to merge and discuss in Slack, since this isn't part of the application yet, and since we're trying to iterate quickly.
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/single-button-audio-player/single-button-audio-player.component.scss` line 20 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/1898#-NXvUzY72G0xL2YAbQxf:-NXvcJjR47OIXzaYQesD:b2wjst7) ([raw file](https://github.com/sillsdev/web-xforge/blob/3ca5a1f87718d201b94a8d72f47f789344fe7ccc/src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/single-button-audio-player/single-button-audio-player.component.scss#L20)):*
<details><summary><i>Previously, RaymondLuong3 (Raymond Luong) wrote…</i></summary><blockquote>

I'm not really sure what is meant by aliasing here. What is aliasing in this context?
</blockquote></details>

It's possible my terminology is not entirely correct.

Anti-aliasing (in the context of images) is the process of smoothing transitions over multiple pixels.


In our particular case, if I change the radial-gradient to `radial-gradient(white 60%, transparent 60% 100%)` (a sharp transition) we get this:

**Review by Nateowami — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1898)* status: 3 of 4 files reviewed, 2 unresolved discussions (waiting on @RaymondLuong3)

___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/single-button-audio-player/single-button-audio-player.component.scss` line 4 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/1898#-NXvY8p7-SsdQ0-oPlpT:-NXxUvZ-3tihaHmq6OwH:bck7ymf) ([raw file](https://github.com/sillsdev/web-xforge/blob/3ca5a1f87718d201b94a8d72f47f789344fe7ccc/src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/single-button-audio-player/single-button-audio-player.component.scss#L4)):*
<details><summary><i>Previously, Nateowami (Nathaniel Paulus) wrote…</i></summary><blockquote>

I was following the design in the UX pin. I think this is an ideal candidate to merge and discuss in Slack, since this isn't part of the application yet, and since we're trying to iterate quickly.
</blockquote></details>

Due to agreement in Slack on purple, I've made the change.

**Pull request merged**
