### PR TITLE
Update all translation files from Crowdin

### PR DESCRIPTION
**Pull request by Nateowami**
This change is [Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1596)

### CODE REVIEW

**Review by Nateowami — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1596)* status: 0 of 11 files reviewed, 1 unresolved discussion

___
*[`src/SIL.XForge.Scripture/ClientApp/src/assets/i18n/non_checking_pt_BR.json` line 263 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/1596#-NGNlsrK2euWVPvECy1J:-NGNlsrK2euWVPvECy1K:bz7n84w) ([raw file](https://github.com/sillsdev/web-xforge/blob/c2e8fa9fbc50d8f9241bded8e7d868919e8e2ef3/src/SIL.XForge.Scripture/ClientApp/src/assets/i18n/non_checking_pt_BR.json#L263)):*
> ```JSON
>     "your_project_is_being_synchronized": "Seu projeto está sendo sincronizado...",
>     "sync_is_disabled": "A sincronização para este projeto deveria ter sido desativada, por isso não está disponível no momento. Por favor, entre em contato com {{ email }} para discutir o que precisa ser feito para que a sincronização do projeto possa ser ativada novamente.",
>     "sync_failure_support_message": "Algo deu errado na última vez que o Scripture Forge tentou sincronizar o projeto com o Paratext. Se não funcionar mesmo depois de tentar novamente, por favor, envie um relatório de problemas escrevendo para {{{email}}."
> ```

I made this change in Crowdin. I'm assuming it's going to fix a problem the testers found where the sync failure message doesn't show the email address in Portuguese.

**Review by nigel-wells — CHANGES_REQUESTED** [review]
Just one main comment - seems a shame the whole `csv_instructions` needs to revert to English?

> Reviewed 11 of 11 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1596#-:-NGONMfs3xu4bWQv_do-:b-hsd2xk)* status: all files reviewed, 5 unresolved discussions (waiting on @Nateowami)

___
*[`src/SIL.XForge.Scripture/ClientApp/src/assets/i18n/non_checking_ar.json` line 114 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/1596#-NGOMXkjB3Sb8Ayao6X3:-NGOMXkjB3Sb8Ayao6X4:bxlodlu) ([raw file](https://github.com/sillsdev/web-xforge/blob/45591ac8376d458bd77eebe2e031f6c571946822/src/SIL.XForge.Scripture/ClientApp/src/assets/i18n/non_checking_ar.json#L114)):*
> ```JSON
>     "close": "إغلاق",
>     "continue_import": "مواصلة الاستجلاب",
>     "csv_instructions": "Create a spreadsheet with a column for the reference and a column for the question, as shown below:\nExport or save the spreadsheet as a CSV or TSV file.\nClick {{ boldStart }}{{ importFromCsvFile }}{{ boldEnd }} below and select the file.",
> ```

Was this supposed translate back to English?



_Code quote:_
```JSON
ions": "Create a spreadsheet with a column for the reference and a column for the question, as shown below:\nExport or save the spreadsheet as a CSV or TSV file.\nClick {{ boldStart }}{{ importFromCsvFile }}{{ boldEnd }} below and select the file.",
```
___
*[`src/SIL.XForge.Scripture/ClientApp/src/assets/i18n/non_checking_es.json` line 114 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/1596#-NGON2wv054953WHRkhH:-NGON2wv054953WHRkhI:bxlodlu) ([raw file](https://github.com/sillsdev/web-xforge/blob/45591ac8376d458bd77eebe2e031f6c571946822/src/SIL.XForge.Scripture/ClientApp/src/assets/i18n/non_checking_es.json#L114)):*
> ```JSON
>     "close": "Cerrar",
>     "continue_import": "Seguir importando",
>     "csv_instructions": "Create a spreadsheet with a column for the reference and a column for the question, as shown below:\nExport or save the spreadsheet as a CSV or TSV file.\nClick {{ boldStart }}{{ importFromCsvFile }}{{ boldEnd }} below and select the file.",
> ```

Was this supposed translate back to English?
___
*[`src/SIL.XForge.Scripture/ClientApp/src/assets/i18n/non_checking_fr.json` line 114 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/1596#-NGON6681ZTR4mkr28NL:-NGON6681ZTR4mkr28NM:bxlodlu) ([raw file](https://github.com/sillsdev/web-xforge/blob/45591ac8376d458bd77eebe2e031f6c571946822/src/SIL.XForge.Scripture/ClientApp/src/assets/i18n/non_checking_fr.json#L114)):*
> ```JSON
>     "close": "Fermer",
>     "continue_import": "Continuer l'importation",
>     "csv_instructions": "Create a spreadsheet with a column for the reference and a column for the question, as shown below:\nExport or save the spreadsheet as a CSV or TSV file.\nClick {{ boldStart }}{{ importFromCsvFile }}{{ boldEnd }} below and select the file.",
> ```

Was this supposed translate back to English?
___
*[`src/SIL.XForge.Scripture/ClientApp/src/assets/i18n/non_checking_pt_BR.json` line 114 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/1596#-NGONIIS3aWQRpWlRz4h:-NGONIIS3aWQRpWlRz4i:bxlodlu) ([raw file](https://github.com/sillsdev/web-xforge/blob/45591ac8376d458bd77eebe2e031f6c571946822/src/SIL.XForge.Scripture/ClientApp/src/assets/i18n/non_checking_pt_BR.json#L114)):*
> ```JSON
>     "close": "Fechar",
>     "continue_import": "Continuar importando",
>     "csv_instructions": "Create a spreadsheet with a column for the reference and a column for the question, as shown below:\nExport or save the spreadsheet as a CSV or TSV file.\nClick {{ boldStart }}{{ importFromCsvFile }}{{ boldEnd }} below and select the file.",
> ```

Was this supposed translate back to English?

**Review by Nateowami — COMMENTED** [review]
Good catch. I must have accidentally selected to discard translations when I updated the file in Crowdin. I'll fix it.

> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1596#-:-NGOQZvw5ssJZlwP1XpA:brqzz4s)* status: all files reviewed, 5 unresolved discussions (waiting on @nigel-wells)

**Review by Nateowami — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1596)* status: 7 of 11 files reviewed, 4 unresolved discussions (waiting on @nigel-wells)

___
*[`src/SIL.XForge.Scripture/ClientApp/src/assets/i18n/non_checking_ar.json` line 114 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/1596#-NGOMXkjB3Sb8Ayao6X3:-NGOQjrG1Fl32iP1bRZd:b-896fix) ([raw file](https://github.com/sillsdev/web-xforge/blob/45591ac8376d458bd77eebe2e031f6c571946822/src/SIL.XForge.Scripture/ClientApp/src/assets/i18n/non_checking_ar.json#L114)):*
<details><summary><i>Previously, nigel-wells (Nigel Wells) wrote…</i></summary><blockquote>

Was this supposed translate back to English?
</blockquote></details>

Done.
___
*[`src/SIL.XForge.Scripture/ClientApp/src/assets/i18n/non_checking_es.json` line 114 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/1596#-NGON2wv054953WHRkhH:-NGOQqa8EVYkJRwZnPp4:b-896fix) ([raw file](https://github.com/sillsdev/web-xforge/blob/45591ac8376d458bd77eebe2e031f6c571946822/src/SIL.XForge.Scripture/ClientApp/src/assets/i18n/non_checking_es.json#L114)):*
<details><summary><i>Previously, nigel-wells (Nigel Wells) wrote…</i></summary><blockquote>

Was this supposed translate back to English?
</blockquote></details>

Done.
___
*[`src/SIL.XForge.Scripture/ClientApp/src/assets/i18n/non_checking_fr.json` line 114 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/1596#-NGON6681ZTR4mkr28NL:-NGOQuBo977n8NU4fvfI:b-896fix) ([raw file](https://github.com/sillsdev/web-xforge/blob/45591ac8376d458bd77eebe2e031f6c571946822/src/SIL.XForge.Scripture/ClientApp/src/assets/i18n/non_checking_fr.json#L114)):*
<details><summary><i>Previously, nigel-wells (Nigel Wells) wrote…</i></summary><blockquote>

Was this supposed translate back to English?
</blockquote></details>

Done.
___
*[`src/SIL.XForge.Scripture/ClientApp/src/assets/i18n/non_checking_pt_BR.json` line 114 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/1596#-NGONIIS3aWQRpWlRz4h:-NGOQyzO61yMYAe_VvL4:b-896fix) ([raw file](https://github.com/sillsdev/web-xforge/blob/45591ac8376d458bd77eebe2e031f6c571946822/src/SIL.XForge.Scripture/ClientApp/src/assets/i18n/non_checking_pt_BR.json#L114)):*
<details><summary><i>Previously, nigel-wells (Nigel Wells) wrote…</i></summary><blockquote>

Was this supposed translate back to English?
</blockquote></details>

Done.

**Review by nigel-wells — APPROVED** [review]
> Reviewed 4 of 4 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1596)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @Nateowami)

**Pull request merged**
