### PR TITLE
Merge branch 'develop' into master

### PR DESCRIPTION
**Pull request by RaymondLuong3**
There are some recently reported bugs on the develop branch related to notes. So far these bugs are relatively minor and can be fixed after this merge. The current list of issues are SF-1521, SF-1524 and SF-1525.

We will hold off on merging this PR until the beta migration changes are shipped to QA. Note that once this PR is merged in, your project on localhost will need to be deleted or migrated using the sync user migration tool.

This change is [Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1285)

### CODE REVIEW

**Comment by marksvc** [comment]
Looks identical to the files when I do the same merge locally.

**Review by marksvc — APPROVED** [review]

**Review by Nateowami — COMMENTED** [review]
@raymondluong3 Can you address the LGTM alerts before we merge? By address, I mean either fix, or explain why they're not really something we should be too worried about.

> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1285#-:-MzO8eRQ-nWXB-vKFf0M:b9loi84)* status: 0 of 243 files reviewed, all discussions resolved

**Review by RaymondLuong3 — COMMENTED** [review]
It appears that the 3 alerts are reporting on issues that are already on master branch. They are not being introduced by the merged. These could be cleaned up, but that can be after applying this merge.

> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1285#-:-MzQvjYQBks1bZdY_vdl:bn21ys3)* status: 0 of 243 files reviewed, all discussions resolved

**Review by Nateowami — COMMENTED** [review]
Actually at least two of them were new. I don't know about the third, as it's a little more complicated and I didn't look into it. Not a big issue; it's fine to fix it after the merge.

> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1285#-:-MzR2QRz3JGVXljrT1rF:b50y068)* status: 0 of 243 files reviewed, 2 unresolved discussions

___
*[src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.ts, line 1059 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/1285#-MzR2D8t7-bQpUSRbxoh:-MzR2D8t7-bQpUSRbxoi:b-m48rce) ([raw file](https://github.com/sillsdev/web-xforge/blob/96fe8d61ff156d9e5ffbd8d9bb333837a5dc2e48/src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.ts#L1059)):*
> ```XML
> 
>   private stripXml(xmlContent: string): string {
>     return xmlContent.replace(/<[^>]+>/g, '');
> ```

This method causing one of the alerts wasn't on master.
___
*[src/SIL.XForge.Scripture/Services/ParatextService.cs, line 1351 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/1285#-MzR0jd5-3kYQ0M12LJP:-MzR0jd5-3kYQ0M12LJQ:bzhw8kn) ([raw file](https://github.com/sillsdev/web-xforge/blob/96fe8d61ff156d9e5ffbd8d9bb333837a5dc2e48/src/SIL.XForge.Scripture/Services/ParatextService.cs#L1351)):*
> ```Smalltalk
>                 throw new DataNotFoundException("Can't get access to cloned project.");
>             CommentManager manager = CommentManager.Get(scrText);
>             var ptUser = new SFParatextUser(username);
> ```

On master we had this:
``` csharp
var ptUser = new SFParatextUser(username);
var notes = NotesFormatter.ParseNotes(notesText, ptUser);
```
With the second line now gone, there's no longer anything reading the `ptUser` variable.

**Comment by RaymondLuong3** [comment]
You are right. I was looking at the wrong thing on LGTM. Two of the alerts do not need to be address. The sanitize warning isn't something we care about. The null check is handled in a way that LGTM can't see. But I did create a PR for the useless variable assignment.

**Pull request merged**
