### PR TITLE
SF-2228 Allow Pre-Translation build cancellation during upload to Serval

### PR DESCRIPTION
**Pull request by pmachapman**
Currently, while a pre-translation build is being uploaded to Serval, cancelling it before it has finished uploading does nothing.

This Pull Request changes this so that when a pre-translation build is cancelled in this state, the Hangfire job is stopped.

- - -
This change is [Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1991)

### CODE REVIEW

**Review by RaymondLuong3 — COMMENTED** [review]
What are ways that I can test this change. If I set up my environment to start a build and hit cancel, is that the best way?

> Reviewed 5 of 5 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1991#-:-Naw1t0r7jrZ21kNuLIi:b99zsft)* status: all files reviewed, 1 unresolved discussion (waiting on @pmachapman)

___
*[`src/SIL.XForge.Scripture/Services/MachineApiService.cs` line 118 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/1991#-NavxXDu7qqQXpiKbh2G:-NavxXDv-4z61mUU3kdk:bcgb69d) ([raw file](https://github.com/sillsdev/web-xforge/blob/f432a620bb7e83699af60d22afee0eb7d7db439c/src/SIL.XForge.Scripture/Services/MachineApiService.cs#L118)):*
> ```Smalltalk
>             (await _projectSecrets.TryGetAsync(sfProjectId)).TryResult(out SFProjectSecret projectSecret)
>             && (
>                 projectSecret.ServalData?.PreTranslationJobId is not null
> ```

From this my guess is that projects with existing pretranslation build jobs will not be able to be cancelled. Is that right? Or is that not relevant since you can only cancel jobs that are still ongoing?

**Review by Nateowami — COMMENTED** [review]
In my testing it appears this cancels the build fine, but the UI doesn't show it as canceled. I'm guessing that's actually a UI issue though, but I can't be sure.

> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1991#-:-NaxDLxV7QQw2gCPK4kr:bgl7lh2)* status: all files reviewed, 1 unresolved discussion (waiting on @pmachapman)

**Review by Nateowami — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1991)* status: all files reviewed, 1 unresolved discussion (waiting on @RaymondLuong3)

___
*[`src/SIL.XForge.Scripture/Services/MachineApiService.cs` line 118 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/1991#-NavxXDu7qqQXpiKbh2G:-Nb178gQCX_x_E8r_cD8:b3o8bdl) ([raw file](https://github.com/sillsdev/web-xforge/blob/f432a620bb7e83699af60d22afee0eb7d7db439c/src/SIL.XForge.Scripture/Services/MachineApiService.cs#L118)):*
<details><summary><i>Previously, RaymondLuong3 (Raymond Luong) wrote…</i></summary><blockquote>

From this my guess is that projects with existing pretranslation build jobs will not be able to be cancelled. Is that right? Or is that not relevant since you can only cancel jobs that are still ongoing?
</blockquote></details>

What do you mean by "pretranslation build jobs"? You mean jobs that are already running? They should be possible to cancel. It just wasn't possible to cancel while the upload to Serval was still running.

(At least, it's supposed to be possible. I haven't been able to test that very well).

**Review by pmachapman — COMMENTED** [review]
It will likely be an issue with the UI and the return result from this API call?

> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1991#-:-NbBTwvg9Rmk23TkvQtr:bjwolom)* status: all files reviewed, 1 unresolved discussion (waiting on @Nateowami and @RaymondLuong3)

___
*[`src/SIL.XForge.Scripture/Services/MachineApiService.cs` line 118 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/1991#-NavxXDu7qqQXpiKbh2G:-NbBSnOk5IeUHBLZzf-k:b-ocdlqc) ([raw file](https://github.com/sillsdev/web-xforge/blob/f432a620bb7e83699af60d22afee0eb7d7db439c/src/SIL.XForge.Scripture/Services/MachineApiService.cs#L118)):*
<details><summary><i>Previously, Nateowami (Nathaniel Paulus) wrote…</i></summary><blockquote>

What do you mean by "pretranslation build jobs"? You mean jobs that are already running? They should be possible to cancel. It just wasn't possible to cancel while the upload to Serval was still running.

(At least, it's supposed to be possible. I haven't been able to test that very well).
</blockquote></details>

You can only cancel jobs that are being uploaded to Serval, or are queued/running on Serval.

The `PreTranslationJobId` and `PreTranslationQueuedAt properties are only set while the files for the job are being uploaded to Serval (they are unset when the build has been uploaded then started on Serval), so this block of code acts to cancel that part of the process, which is running in Hangfire.

The existing code that cancels the build on Serval (i.e. if the build is queued/running on Serval) is still executed after this block.

**Review by pmachapman — COMMENTED** [review]
@RaymondLuong3 I have updated this PR to refer to the JIRA ticket, and to update the UI when the job is cancelled. Is there anything else blocking the code review?

> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1991#-:-NdXvRkNAcdWkJ999nNy:b3v6h5o)* status: 3 of 6 files reviewed, 1 unresolved discussion (waiting on @Nateowami and @RaymondLuong3)

**Review by RaymondLuong3 — COMMENTED** [review]
I tried this branch out. I have a project that already had a pre-translation build completed. I told the project to start a new pre-translation build, and then tried to cancel it. But after clicking cancel, and confirming the dialog, nothing really happens. Maybe we can look at this together when you come online.

> Reviewed 1 of 1 files at r2, 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1991#-:-NdadP7m1xmN9HnjQojg:b-66ez07)* status: all files reviewed, 2 unresolved discussions (waiting on @Nateowami and @pmachapman)

___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-generation.component.ts` line 192 at r3](https://reviewable.io/reviews/sillsdev/web-xforge/1991#-Nda_8Rb493OrTy_40g2:-Nda_8Rb493OrTy_40g3:b3qgvs) ([raw file](https://github.com/sillsdev/web-xforge/blob/6afa328a2a8a363590296db413df11c0fca518b1/src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-generation.component.ts#L192)):*
> ```XML
>         })
>       )
>       .subscribe();
> ```

I see you didn't change this, but I'm having a hard time understanding why we call subscribe on this. Maybe the callback should be in the subscribe block instead of in a `tap()`?



_Code quote (i):_
```XML
      .subscribe();
```



_Code snippet (ii):_
```XML
    this.draftGenerationService
      .cancelBuild(this.activatedProject.projectId!)
      .pipe(switchMap(() => this.draftGenerationService.getBuildProgress(this.activatedProject.projectId!)))
      .subscribe(job => {
        this.draftJob = job;
        this.isDraftJobFetched = true;
      });
```
___
*[`src/SIL.XForge.Scripture/Services/MachineApiService.cs` line 118 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/1991#-NavxXDu7qqQXpiKbh2G:-NdaZ5p3DAREdsQv2jI-:brc2mz5) ([raw file](https://github.com/sillsdev/web-xforge/blob/f432a620bb7e83699af60d22afee0eb7d7db439c/src/SIL.XForge.Scripture/Services/MachineApiService.cs#L118)):*
<details><summary><i>Previously, pmachapman (Peter Chapman) wrote…</i></summary><blockquote>

You can only cancel jobs that are being uploaded to Serval, or are queued/running on Serval.

The `PreTranslationJobId` and `PreTranslationQueuedAt properties are only set while the files for the job are being uploaded to Serval (they are unset when the build has been uploaded then started on Serval), so this block of code acts to cancel that part of the process, which is running in Hangfire.

The existing code that cancels the build on Serval (i.e. if the build is queued/running on Serval) is still executed after this block.
</blockquote></details>

Ok, I see that now. This is just trying the cancel the upload task, which is indicated by the `PreTranslationJobId` or `PreTranslationQueuedAt` being set.

**Review by RaymondLuong3 — APPROVED** [review]
:lgtm: other than the conflict to resolve.

> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1991#-:-NdbHTZq-7XPuYZdAhZw:b7ixsaw)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @pmachapman)

**Pull request merged**
