### PR TITLE
SF-1613 Upgrade to .NET 6.0

### PR DESCRIPTION
**Pull request by pmachapman**
This PR fixes:

 - SF-1500 Incorrect line numbers in stack traces
 - [Upcoming .NET Core 3.1 EOS](https://dotnet.microsoft.com/en-us/platform/support/policy/dotnet-core)

This PR includes:

 - Upgraded base package versions to 6.0
 - Removed deprecated and obsolete features:
   - [libuv is now obsolete](https://docs.microsoft.com/en-us/dotnet/core/compatibility/aspnet-core/5.0/kestrel-libuv-transport-obsolete)
   - [Assembly.CodeBase is deprecated](https://docs.microsoft.com/en-us/dotnet/api/system.reflection.assembly.codebase)
   - [JsonSerializerOptions.IgnoreNullValues is deprecated](https://docs.microsoft.com/en-us/dotnet/api/system.text.json.jsonserializeroptions.ignorenullvalues)
 - Fixed new warnings post-upgrade:
   - [--self-contained must be specified if -r is specified on publish](https://docs.microsoft.com/en-us/dotnet/core/compatibility/sdk/6.0/runtimeidentifier-self-contained)
   - The version of DotNetZip included with ParatextData is not compatible with .Net 6.0
 - README file fixes

---
This change is [Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1404)

### CODE REVIEW

**Review by marksvc — APPROVED** [review]
Thank you. I'm not very familiar with libuv.
We need to fix the CI, and also let's leave this PR unmerged while we choose the timing of when to make this change.

> Reviewed 15 of 15 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1404#-:-N50ro307j5u17MMgKZD:bmuedza)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @pmachapman)

**Review by Nateowami — COMMENTED** [review]
Great work.

> Reviewed 15 of 15 files at r1.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1404#-:-N52l6JM96ULknB84cXR:b-9dwnyz)* status: all files reviewed, 1 unresolved discussion (waiting on @pmachapman)

___
*[`src/Help/UpdateHelp/UpdateHelp.csproj` line 5 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/1404#-N52jmBX34Z6q-Ey5Kpz:-N52jmBX34Z6q-Ey5Kq-:b-db4nl3) ([raw file](https://github.com/sillsdev/web-xforge/blob/ca36abc9e0cf3e725347ee0190e9eb58802c98b5/src/Help/UpdateHelp/UpdateHelp.csproj#L5)):*
> ```XML
>   <PropertyGroup>
>     <OutputType>Exe</OutputType>
>     <TargetFramework>net6.0</TargetFramework>
> ```

Did you test that the UpdateHelp program actually runs properly post upgrade? I'm guessing you couldn't test it without access to S3 and Crowdin. @raymondluong3 can you check whether this still works?

**Review by pmachapman — COMMENTED** [review]
libuv was used as an IO transport for old version of .NET core, as the standard implementation then was slow. It is replaced by sockets now (which are faster and more normal), and I couldn't see any other dependency (i.e. in the RealtimeServer) so it appeared to be safe to remove. I believe it will be removed in .NET 7.0 completely. If it was a required dependency, we would notice a breakdown in communication between the RealtimeServer, Web API, and the Angular frontend.

Microsoft created a ticket for anyone to complain about libuv being removed, and no one complained, so I am confident there are no third party dependencies to it in .NET libraries used.

No problem from my perspective with delaying the timing of deployment - this change is not a blocker for any of the other units of work planned.

> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1404#-:-N53_0_x1zgLU7TUSB2R:b-69fzzj)* status: all files reviewed, 1 unresolved discussion (waiting on @RaymondLuong3)

___
*[`src/Help/UpdateHelp/UpdateHelp.csproj` line 5 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/1404#-N52jmBX34Z6q-Ey5Kpz:-N53am0S59fukIpAdWJF:bir0sh7) ([raw file](https://github.com/sillsdev/web-xforge/blob/ca36abc9e0cf3e725347ee0190e9eb58802c98b5/src/Help/UpdateHelp/UpdateHelp.csproj#L5)):*
<details><summary><i>Previously, Nateowami (Nathaniel Paulus) wrote…</i></summary><blockquote>

Did you test that the UpdateHelp program actually runs properly post upgrade? I'm guessing you couldn't test it without access to S3 and Crowdin. @raymondluong3 can you check whether this still works?
</blockquote></details>

I was able to test that the program ran in test mode on my Ubuntu server, but I could not verify the output was correct when running `dotnet run en write` as I had nothing to compare it to.

The third party dependency (HtmlAgilityPack) is fully compatible with .Net 6.0, and there seemed to be nothing unusual in Program.cs, but if it can be verified to create the same output, that would be reassuring.

**Review by RaymondLuong3 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1404)* status: all files reviewed, 1 unresolved discussion (waiting on @Nateowami and @pmachapman)

___
*[`src/Help/UpdateHelp/UpdateHelp.csproj` line 5 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/1404#-N52jmBX34Z6q-Ey5Kpz:-N5667ra6fM-dxrNu2cg:b6z6hum) ([raw file](https://github.com/sillsdev/web-xforge/blob/ca36abc9e0cf3e725347ee0190e9eb58802c98b5/src/Help/UpdateHelp/UpdateHelp.csproj#L5)):*
<details><summary><i>Previously, pmachapman (Peter Chapman) wrote…</i></summary><blockquote>

I was able to test that the program ran in test mode on my Ubuntu server, but I could not verify the output was correct when running `dotnet run en write` as I had nothing to compare it to.

The third party dependency (HtmlAgilityPack) is fully compatible with .Net 6.0, and there seemed to be nothing unusual in Program.cs, but if it can be verified to create the same output, that would be reassuring.
</blockquote></details>

This looks to be working.

**Comment by marksvc** [comment]
The build agent was updated to have dotnet-sdk-6.0. 
TeamCity also needs its dotnet plugin updated. This requires a restart of TC, which may happen in the next day or so.

**Review by pmachapman — COMMENTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1404#-:-N5M8YGR8DRl6bqG4IRh:bnfp4nl)* status: 12 of 16 files reviewed, all discussions resolved (waiting on @marksvc, @Nateowami, and @RaymondLuong3)

**Comment by Nateowami** [comment]
I think this PR is ready to merge except we need to get the testers on dotnet 6 first. TeamCity has gotten the update, and most or all of the developers have updated. Monday is a holiday in the US, so this will probably be a project for Tuesday. In hindsight it would have been a good idea to get that done before now.

**Comment by Nateowami** [comment]
I just rebased this PR to fix a trivial merge conflict in README.md. Once I've confirmed the testers can run on .NET 6.0 we can merge this.

**Review by Nateowami — COMMENTED** [review]
> Reviewed 2 of 2 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1404)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @pmachapman)

**Pull request merged**
