### PR TITLE
Merge 'master' in to 'develop'

### PR DESCRIPTION
**Pull request by nigel-wells**
There is one failed front end test relating to notes - I'm not sure if that was already there in develop though.

Also received the following warnings in the console after running `dotnet test`
```
Services\ParatextSyncRunnerTests.cs(685,17): error CS1501: No overload for method 'SetupSFData' takes 3 arguments [C:\Git Projects\web-xforge\test\SIL.XForge.Scripture.Tests\SIL.XForge.Scripture.Tests.csproj]
Services\ParatextSyncRunnerTests.cs(777,17): error CS1501: No overload for method 'SetupSFData' takes 3 arguments [C:\Git Projects\web-xforge\test\SIL.XForge.Scripture.Tests\SIL.XForge.Scripture.Tests.csproj]
C:\Git Projects\web-xforge\after.xForge.sln.targets(3,5): error MSB4181: The "MSBuild" task returned false but did not log an error. [C:\Git Projects\web-xforge\xForge.sln]
```

---
This change is [Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1101)

### CODE REVIEW

**Review by RaymondLuong3 — COMMENTED** [review]
I'll get through this review tomorrow. I bet that the front-end test failure may be related to the blank segment change. I can also take a look at it if you don't get to it.

> Reviewed 18 of 75 files at r1.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1101#-:-Mf53lmxEK6XWwomR5Vp:b-xj4k9j)* status: 18 of 75 files reviewed, all discussions resolved (waiting on @nigel-wells)

**Review by irahopkinson — COMMENTED** [review]
You'll want to amend that last commit into the merge commit before accepting this (assuming its good although there are still failing tests). Note that `develop` was passing all tests previously so it still should be.

> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1101#-:-Mf7C-32BDAG7g5XL4hB:b-v2dfah)* status: 18 of 75 files reviewed, all discussions resolved (waiting on @nigel-wells)

**Comment by nigel-wells** [comment]
That was odd - the prettier test failed on a couple of files - I wonder how they made it that far? Anyway, fixed now and I've also amended the merge commit... well, I think that is what I did. Just need @RaymondLuong3 review on those C# tests that I ended up changing.

**Review by irahopkinson — COMMENTED** [review]
`master` has updated the version of prettier which has changed it disposition on files. `master` was fixed but files on `develop` that have changed or added will need to be fixed like you have.

> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1101#-:-MfBncHh6xaX_ItofDUF:b-n83t69)* status: 18 of 76 files reviewed, all discussions resolved (waiting on @nigel-wells)

**Review by RaymondLuong3 — APPROVED** [review]
Thanks for your work on this. Looks good from my side.

> Reviewed 53 of 75 files at r1, 3 of 3 files at r2, 2 of 2 files at r3.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1101#-:-MfDus0b6VY0VIknLpqj:bcyxxu0)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @nigel-wells)

**Pull request merged**
