### PR TITLE
Mongo query to reconstruct invite link

### PR DESCRIPTION
**Pull request by irahopkinson**
- also, users still to migrate Mongo query

---
This change is [Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1142)

### CODE REVIEW

**Review by Nateowami — COMMENTED** [review]
Just a couple questions.

> Reviewed 2 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1142#-:-MjWE0tE2yRcEH25k74v:bcq77ir)* status: all files reviewed (commit messages unreviewed), 2 unresolved discussions (waiting on @irahopkinson)

___
*[mongodb/Users/InviteLink.mongodb, line 12 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/1142#-MjWC7Uc7aT_OfBEYKLC:-MjWC7Ud09q9MQy79oOE:bja4edi) ([raw file](https://github.com/sillsdev/web-xforge/blob/6c95e1ee1d83497f941d5c8add71496fd49b2b58/mongodb/Users/InviteLink.mongodb#L12)):*
> ```
> const projectSecret = db.sf_project_secrets.findOne(
>   { _id: projectId, shareKeys: { $elemMatch: { email } } },
>   { _id: 0, shareKeys: { $elemMatch: { email } } }
> ```

When would `_id` be `0`?
___
*[mongodb/Users/InviteLink.mongodb, line 16 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/1142#-MjWCESb5vumQ9RrpCT1:-MjWCESb5vumQ9RrpCT2:b5ac0as) ([raw file](https://github.com/sillsdev/web-xforge/blob/6c95e1ee1d83497f941d5c8add71496fd49b2b58/mongodb/Users/InviteLink.mongodb#L16)):*
> ```
> 
> const key = projectSecret.shareKeys[0].key;
> const link = `${site}/projects/${projectId}?sharing=true&shareKey=${key}&locale=en-GB`;
> ```

Why do we have `&locale=en-GB`? Shouldn't the locale come from the project secret? And if it's unimportant, I would think we wouldn't include it.

**Review by irahopkinson — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1142)* status: 1 of 2 files reviewed, all discussions resolved (waiting on @Nateowami)

___
*[mongodb/Users/InviteLink.mongodb, line 12 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/1142#-MjWC7Uc7aT_OfBEYKLC:-MjXQ9_S3Ap5aNnnZbHv:b66p9iz) ([raw file](https://github.com/sillsdev/web-xforge/blob/6c95e1ee1d83497f941d5c8add71496fd49b2b58/mongodb/Users/InviteLink.mongodb#L12)):*
<details><summary><i>Previously, Nateowami (Nathaniel Paulus) wrote…</i></summary><blockquote>

When would `_id` be `0`?
</blockquote></details>

For `findOne` the first argument is the query but the second argument is the projection (https://docs.mongodb.com/v4.0/reference/method/db.collection.findOne/). We use the value `0` to exclude the id from being output and `$elemMatch` to only show the matched items (unmatched items are excluded).
___
*[mongodb/Users/InviteLink.mongodb, line 16 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/1142#-MjWCESb5vumQ9RrpCT1:-MjXRfP_8lHFas5XVKcY:b-sqqyeo) ([raw file](https://github.com/sillsdev/web-xforge/blob/6c95e1ee1d83497f941d5c8add71496fd49b2b58/mongodb/Users/InviteLink.mongodb#L16)):*
<details><summary><i>Previously, Nateowami (Nathaniel Paulus) wrote…</i></summary><blockquote>

Why do we have `&locale=en-GB`? Shouldn't the locale come from the project secret? And if it's unimportant, I would think we wouldn't include it.
</blockquote></details>

Good point, I've fixed this so we can choose.

**Review by Nateowami — APPROVED** [review]
Looks good. Just one more non-blocking comment that I should have added last time.

Then good to merge.

> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1142#-:-MjXXFN20SkY2CEDsxLb:b6p000o)* status: all files reviewed, 1 unresolved discussion (waiting on @irahopkinson)

___
*[-- commits, line 4 at r2](https://reviewable.io/reviews/sillsdev/web-xforge/1142#-MjXWwcdEyFaEpJwIPXy):*
The wording here is a bit odd and difficult to parse. Maybe "Also, add Mongo query to find users remaining to migrate"?
___
*[mongodb/Users/InviteLink.mongodb, line 12 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/1142#-MjWC7Uc7aT_OfBEYKLC:-MjXWrNnDdE2FpjKdNkX:b-so3f9v) ([raw file](https://github.com/sillsdev/web-xforge/blob/6c95e1ee1d83497f941d5c8add71496fd49b2b58/mongodb/Users/InviteLink.mongodb#L12)):*
<details><summary><i>Previously, irahopkinson (Ira Hopkinson) wrote…</i></summary><blockquote>

For `findOne` the first argument is the query but the second argument is the projection (https://docs.mongodb.com/v4.0/reference/method/db.collection.findOne/). We use the value `0` to exclude the id from being output and `$elemMatch` to only show the matched items (unmatched items are excluded).
</blockquote></details>

Ah, right, somehow I missed that.

**Review by irahopkinson — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1142)* status: all files reviewed (commit messages unreviewed), all discussions resolved (waiting on @irahopkinson)

___
*[-- commits, line 4 at r2](https://reviewable.io/reviews/sillsdev/web-xforge/1142#-MjXWwcdEyFaEpJwIPXy):*
<details><summary><i>Previously, Nateowami (Nathaniel Paulus) wrote…</i></summary><blockquote>

The wording here is a bit odd and difficult to parse. Maybe "Also, add Mongo query to find users remaining to migrate"?
</blockquote></details>

Done

**Pull request merged**
