### PR TITLE
SF-2359 Update from legacy card theme

### PR DESCRIPTION
**Pull request by josephmyers**
This change is [Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/2450)

### CODE REVIEW

**Review by pmachapman — CHANGES_REQUESTED** [review]
> Reviewed 13 of 13 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/2450)* status: all files reviewed, 1 unresolved discussion (waiting on @josephmyers)

___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/settings/settings.component.html` line 102 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/2450#-NxjM_aR89dhU-BO8Ssk:-NxjM_aSEdiMlV2t_asR:b5hlk4b) ([raw file](https://github.com/sillsdev/web-xforge/blob/16ca6d622affbeba68b7e0421f0c5d404209d3ee/src/SIL.XForge.Scripture/ClientApp/src/app/settings/settings.component.html#L102)):*
> ```HTML
>             </div>
>           </mat-card-content>
>           <mat-divider *ngIf="showPreTranslationSettings"></mat-divider>
> ```

Are we able to add back the mat-dividers? I think they are important for usability on the Settings screen given how large it can grow to.

I think they will just need a 16px margin on the left and right sides to match the old look



_Code quote:_
```HTML
<mat-divider *ngIf="showPreTranslationSettings"></mat-divider>
```

**Review by josephmyers — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/2450)* status: 12 of 13 files reviewed, 1 unresolved discussion (waiting on @pmachapman)

___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/settings/settings.component.html` line 102 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/2450#-NxjM_aR89dhU-BO8Ssk:-NxkX4V766pcD8QZBgUM:b8yjzvn) ([raw file](https://github.com/sillsdev/web-xforge/blob/16ca6d622affbeba68b7e0421f0c5d404209d3ee/src/SIL.XForge.Scripture/ClientApp/src/app/settings/settings.component.html#L102)):*
<details><summary><i>Previously, pmachapman (Peter Chapman) wrote…</i></summary><blockquote>

Are we able to add back the mat-dividers? I think they are important for usability on the Settings screen given how large it can grow to.

I think they will just need a 16px margin on the left and right sides to match the old look
</blockquote></details>

We are able, but I disagree that they're important. In fact I believe they're detrimental, in that they add busyness to an already busy page and make it harder to scan/parse. Negative space is important in page design, as it allows for breathability and natural (implicit) grouping. If we can't achieve clear grouping with negative space, our use of space is probably bad.

Here's a short article that contrasts lines and negative space, and it points to the Gestalt principles, which are fundamental to page design.
https://bootcamp.uxdesign.cc/visual-dividers-in-user-interfaces-da4313db7e1

If you still have strong disagreements, let me know!

**Review by pmachapman — APPROVED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/2450)* status: all files reviewed, 1 unresolved discussion (waiting on @josephmyers)

___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/settings/settings.component.html` line 102 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/2450#-NxjM_aR89dhU-BO8Ssk:-NxnTSsMAlKMfdj0pVH5:b-cpl4v4) ([raw file](https://github.com/sillsdev/web-xforge/blob/16ca6d622affbeba68b7e0421f0c5d404209d3ee/src/SIL.XForge.Scripture/ClientApp/src/app/settings/settings.component.html#L102)):*
<details><summary><i>Previously, josephmyers wrote…</i></summary><blockquote>

We are able, but I disagree that they're important. In fact I believe they're detrimental, in that they add busyness to an already busy page and make it harder to scan/parse. Negative space is important in page design, as it allows for breathability and natural (implicit) grouping. If we can't achieve clear grouping with negative space, our use of space is probably bad.

Here's a short article that contrasts lines and negative space, and it points to the Gestalt principles, which are fundamental to page design.
https://bootcamp.uxdesign.cc/visual-dividers-in-user-interfaces-da4313db7e1

If you still have strong disagreements, let me know!
</blockquote></details>

Aight! Let's give it a try. Thanks for the info!

**Review by josephmyers — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/2450)* status: all files reviewed, 1 unresolved discussion (waiting on @pmachapman)

___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/settings/settings.component.html` line 102 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/2450#-NxjM_aR89dhU-BO8Ssk:-NyJ57YJ5cBZdQnIgbmg:b-896fix) ([raw file](https://github.com/sillsdev/web-xforge/blob/16ca6d622affbeba68b7e0421f0c5d404209d3ee/src/SIL.XForge.Scripture/ClientApp/src/app/settings/settings.component.html#L102)):*
<details><summary><i>Previously, pmachapman (Peter Chapman) wrote…</i></summary><blockquote>

Aight! Let's give it a try. Thanks for the info!
</blockquote></details>

Done.

**Review by josephmyers — COMMENTED** [review]
> Reviewed 12 of 13 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/2450)* status: all files reviewed, 1 unresolved discussion (waiting on @pmachapman)

**Comment by Nateowami** [comment]
@josephmyers If you could, when merging PRs, use this format:
```
SF-123 Some change (#1234)
```

This helps with matching commits with Jira issues.

**Pull request merged**
