### PR TITLE
SF-2268 Custom Configuration for MT Drafting

### PR DESCRIPTION
**Pull request by pmachapman**
This PR adds support for custom configuration for MT drafting. This config can be set in the Settings page for a project, and for security reasons, can only be set by a System Administrator.

A sample configuration to use on QA that would make it behave like Production would be:
```json
{"max_steps":20000}
```

- - -
This change is [Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/2173)

### CODE REVIEW

**Review by marksvc — APPROVED** [review]
I reviewed the commits individually, which was a helpful way to break up the parts of the review.

I did some testing, checking the setting of json and non-json, and also whether I can cause trouble by changing another setting in the same act of unbluring the Serval config (since our onFormValueChanges() now returns early if the serval config is changed), but was not able to find any problems.

> Reviewed 2 of 2 files at r1, 6 of 6 files at r2, 7 of 7 files at r3, 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/2173#-:-Njn1gDKBN6a2iZlWZZG:b-idxehe)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @pmachapman)

**Review by Nateowami — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/2173)* status: 2 of 15 files reviewed, 2 unresolved discussions (waiting on @marksvc and @pmachapman)

___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/settings/settings.component.html` line 134 at r9](https://reviewable.io/reviews/sillsdev/web-xforge/2173#-NkQj2T7-HEwJ3ItPQoy:-NkQj2T7-HEwJ3ItPQoz:b-ebl6ky) ([raw file](https://github.com/sillsdev/web-xforge/blob/4c8714dcda3985466aa8fb25fe1c62fb63a5624c/src/SIL.XForge.Scripture/ClientApp/src/app/settings/settings.component.html#L134)):*
> ```HTML
>                   <mat-label>{{ t("serval_config") }}</mat-label>
>                   <textarea
>                     appAutofocus
> ```

Why is `appAutofocus` here? It's intended to focus an element as soon as it exists. It's used for things like the add answer form, where after the user clicks "add answer" the form field appears and we want to to immediately focus. I can't think of any reason it should belong here.
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/settings/settings.component.ts` line 252 at r9](https://reviewable.io/reviews/sillsdev/web-xforge/2173#-NkQjg9cAP2tKv8QZIOm:-NkQjg9cAP2tKv8QZIOn:b9nmdz5) ([raw file](https://github.com/sillsdev/web-xforge/blob/4c8714dcda3985466aa8fb25fe1c62fb63a5624c/src/SIL.XForge.Scripture/ClientApp/src/app/settings/settings.component.ts#L252)):*
> ```XML
>     if (
>       this.projectDoc == null ||
>       this.projectDoc.data == null ||
> ```

This can be `this.projectDoc?.data == null`

**Review by pmachapman — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/2173)* status: 2 of 15 files reviewed, 2 unresolved discussions (waiting on @marksvc and @Nateowami)

___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/settings/settings.component.html` line 134 at r9](https://reviewable.io/reviews/sillsdev/web-xforge/2173#-NkQj2T7-HEwJ3ItPQoy:-NkRH9KsA553Orr-ZXpa:by6wctd) ([raw file](https://github.com/sillsdev/web-xforge/blob/814bc398d02022d6c7dc4355065a5f71baa7f2bd/src/SIL.XForge.Scripture/ClientApp/src/app/settings/settings.component.html#L134)):*
<details><summary><i>Previously, Nateowami (Nathaniel Paulus) wrote…</i></summary><blockquote>

Why is `appAutofocus` here? It's intended to focus an element as soon as it exists. It's used for things like the add answer form, where after the user clicks "add answer" the form field appears and we want to to immediately focus. I can't think of any reason it should belong here.
</blockquote></details>

Done. Removed - I misunderstood what it did. Thanks!
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/settings/settings.component.ts` line 252 at r9](https://reviewable.io/reviews/sillsdev/web-xforge/2173#-NkQjg9cAP2tKv8QZIOm:-NkRHHse5Ou0K4gQ8v7o:bpdhpv0) ([raw file](https://github.com/sillsdev/web-xforge/blob/814bc398d02022d6c7dc4355065a5f71baa7f2bd/src/SIL.XForge.Scripture/ClientApp/src/app/settings/settings.component.ts#L252)):*
<details><summary><i>Previously, Nateowami (Nathaniel Paulus) wrote…</i></summary><blockquote>

This can be `this.projectDoc?.data == null`
</blockquote></details>

Done. Thanks - old habits die hard.

**Review by Nateowami — COMMENTED** [review]
> Reviewed 1 of 2 files at r1, 2 of 2 files at r10, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/2173)* status: 4 of 15 files reviewed, all discussions resolved (waiting on @marksvc)

___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/settings/settings.component.html` line 134 at r9](https://reviewable.io/reviews/sillsdev/web-xforge/2173#-NkQj2T7-HEwJ3ItPQoy:-NkRJ-PmEEAHL5N6MQpe:b-ucfkn4) ([raw file](https://github.com/sillsdev/web-xforge/blob/814bc398d02022d6c7dc4355065a5f71baa7f2bd/src/SIL.XForge.Scripture/ClientApp/src/app/settings/settings.component.html#L134)):*
<details><summary><i>Previously, pmachapman (Peter Chapman) wrote…</i></summary><blockquote>

Done. Removed - I misunderstood what it did. Thanks!
</blockquote></details>

Thanks.

**Pull request merged**
