### PR TITLE
drop: expect and hide console logs in tests

### PR DESCRIPTION
**Pull request by marksvc**
- @triviality/logger is not here used in a way that requires it in
production, and so it is added only to the development set of
dependencies.

---
This change is [Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1234)

### CODE REVIEW

**Review by Nateowami — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1234)* status: 0 of 4 files reviewed, 2 unresolved discussions (waiting on @marksvc and @Nateowami)

___
*[src/SIL.XForge.Scripture/ClientApp/src/app/shared/text/text.component.spec.ts, line 1837 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/1234#-Mux8AMn7WnOfQbNGsdO:-Mux8AMn7WnOfQbNGsdP:b1tpulg) ([raw file](https://github.com/sillsdev/web-xforge/blob/9396afa67594dd8f4ad1909eeed5c42067910a1c/src/SIL.XForge.Scripture/ClientApp/src/app/shared/text/text.component.spec.ts#L1837)):*
> ```XML
>         document.caretRangeFromPoint = (_x: number, _y: number) => ({ startOffset: 0 } as Range);
>       });
>       mockedConsole.verify();
> ```

Stating an expectation at the beginning and then calling `verify()` a the end is kind of odd. Is there a reason you couldn't just call `shouldOnlyGet()` at the end?
___
*[src/SIL.XForge.Scripture/ClientApp/src/xforge-common/mock-console.ts, line 28 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/1234#-MuwkDZa412HtU_4XtTs:-MuwkDZa412HtU_4XtTt:bgdhmfe) ([raw file](https://github.com/sillsdev/web-xforge/blob/9396afa67594dd8f4ad1909eeed5c42067910a1c/src/SIL.XForge.Scripture/ClientApp/src/xforge-common/mock-console.ts#L28)):*
> ```XML
>   static install(): MockConsole {
>     const instance: MockConsole = new this();
>     (console as any) = instance;
> ```

I'm not really a fan of redefining a global variable. It's not really a big deal though since it's just the tests. But it looks to me like deliberately avoiding something we *should* be doing, namely, having a logger class that is used by each component, rather than having each component directly access a global variable. It seems like a perfect place to use dependency injection. And right now we're already dependency injecting the console in a few places, and it's *super ugly*:
``` ts
// constructor argument
@Inject(CONSOLE) private readonly console: ConsoleInterface
```
If we instead created a LoggingService class that has the console internally, then it would make dependency injecting it easier (presumably we could ditch the `@Inject(CONSOLE)` decorator that looks so out of place). The tests could then provide their own class (MockConsole) that would have the same interface, but would provide helper methods for verifying what was logged. There are only a few classes that actually log to the console, and a couple of them are already injecting the console.

**Review by marksvc — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1234)* status: 0 of 4 files reviewed, 2 unresolved discussions (waiting on @Nateowami)

___
*[src/SIL.XForge.Scripture/ClientApp/src/app/shared/text/text.component.spec.ts, line 1837 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/1234#-Mux8AMn7WnOfQbNGsdO:-Mv-xbpBBYa_xd13-xzO:biamobc) ([raw file](https://github.com/sillsdev/web-xforge/blob/9396afa67594dd8f4ad1909eeed5c42067910a1c/src/SIL.XForge.Scripture/ClientApp/src/app/shared/text/text.component.spec.ts#L1837)):*
<details><summary><i>Previously, Nateowami (Nathaniel Paulus) wrote…</i></summary><blockquote>

Stating an expectation at the beginning and then calling `verify()` a the end is kind of odd. Is there a reason you couldn't just call `shouldOnlyGet()` at the end?
</blockquote></details>

Sure, and specifically there are methods in the mock-console.ts for that like `assertHasOnly(expectedMessage)`. A reason to write the expectation first and verify it after the SUT is because anything not expected or muted is shown. If you run `shouldOnlyGet('file not found')` then when the SUT runs it will mute any matching messages. 

I did make provision for muting arbitrary messages (`.muteFor(pattern)`). Using `shouldOnlyGet(pattern)` lets you define an expectation and cause muting for a pattern in one step. 
___
*[src/SIL.XForge.Scripture/ClientApp/src/xforge-common/mock-console.ts, line 28 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/1234#-MuwkDZa412HtU_4XtTs:-Mv-yUR0Asg7RyNHPx5S:b-vykm6x) ([raw file](https://github.com/sillsdev/web-xforge/blob/9396afa67594dd8f4ad1909eeed5c42067910a1c/src/SIL.XForge.Scripture/ClientApp/src/xforge-common/mock-console.ts#L28)):*
<details><summary><i>Previously, Nateowami (Nathaniel Paulus) wrote…</i></summary><blockquote>

I'm not really a fan of redefining a global variable. It's not really a big deal though since it's just the tests. But it looks to me like deliberately avoiding something we *should* be doing, namely, having a logger class that is used by each component, rather than having each component directly access a global variable. It seems like a perfect place to use dependency injection. And right now we're already dependency injecting the console in a few places, and it's *super ugly*:
``` ts
// constructor argument
@Inject(CONSOLE) private readonly console: ConsoleInterface
```
If we instead created a LoggingService class that has the console internally, then it would make dependency injecting it easier (presumably we could ditch the `@Inject(CONSOLE)` decorator that looks so out of place). The tests could then provide their own class (MockConsole) that would have the same interface, but would provide helper methods for verifying what was logged. There are only a few classes that actually log to the console, and a couple of them are already injecting the console.
</blockquote></details>

Yeah, we could inject something. I was injecting something like that at first until I found that I could just overwrite the global console and leave the application class unchanged. I like that overriding the console is very _clean_ for the application class, since it's transparent.

If we do inject a console/logger, then we will have two consoles: One that we are supposed to log to (injected), and one that we might quickly log to for debugging but need to remember not to use for anything else (`console.log`). We can do that. 

I remember that we've talked before about rolling console messages into automated bug reports, so whatever console/logger is injected in production would presumably be something that would play into that.

**Review by Nateowami — COMMENTED** [review]
> Reviewed 1 of 4 files at r1.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1234)* status: 1 of 4 files reviewed, 1 unresolved discussion (waiting on @Nateowami)

___
*[src/SIL.XForge.Scripture/ClientApp/src/app/shared/text/text.component.spec.ts, line 1837 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/1234#-Mux8AMn7WnOfQbNGsdO:-Mv01pzBAYslIxzMVIkY:b-sw1zpy) ([raw file](https://github.com/sillsdev/web-xforge/blob/9396afa67594dd8f4ad1909eeed5c42067910a1c/src/SIL.XForge.Scripture/ClientApp/src/app/shared/text/text.component.spec.ts#L1837)):*
<details><summary><i>Previously, marksvc wrote…</i></summary><blockquote>

Sure, and specifically there are methods in the mock-console.ts for that like `assertHasOnly(expectedMessage)`. A reason to write the expectation first and verify it after the SUT is because anything not expected or muted is shown. If you run `shouldOnlyGet('file not found')` then when the SUT runs it will mute any matching messages. 

I did make provision for muting arbitrary messages (`.muteFor(pattern)`). Using `shouldOnlyGet(pattern)` lets you define an expectation and cause muting for a pattern in one step. 
</blockquote></details>

Ah, that makes sense. Maybe that behavior would be more obvious if the method was called something like "expectAndHide"?

**Review by marksvc — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1234)* status: 1 of 4 files reviewed, 1 unresolved discussion (waiting on @Nateowami)

___
*[src/SIL.XForge.Scripture/ClientApp/src/app/shared/text/text.component.spec.ts, line 1837 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/1234#-Mux8AMn7WnOfQbNGsdO:-MxBh7-U-dMYf5Jjt-ia:b-896fix) ([raw file](https://github.com/sillsdev/web-xforge/blob/9396afa67594dd8f4ad1909eeed5c42067910a1c/src/SIL.XForge.Scripture/ClientApp/src/app/shared/text/text.component.spec.ts#L1837)):*
<details><summary><i>Previously, Nateowami (Nathaniel Paulus) wrote…</i></summary><blockquote>

Ah, that makes sense. Maybe that behavior would be more obvious if the method was called something like "expectAndHide"?
</blockquote></details>

Done.

**Review by Nateowami — COMMENTED** [review]
@marksvc Sorry I've taken so long to return to this PR. Could you update it to resolve conflicts?

> Reviewed 2 of 4 files at r1, 1 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1234#-:-MzIbeMV-y4vDG7p_Y9B:b-wmi290)* status: 2 of 4 files reviewed, all discussions resolved (waiting on @Nateowami)

**Review by Nateowami — APPROVED** [review]
:lgtm:

> Reviewed 1 of 2 files at r3, 3 of 3 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1234#-:-MzwkNPT2hucjfO0dKoa:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @marksvc)

**Comment by Nateowami** [comment]
Wait, what, this was a PR against develop? I never noticed that. Should it have been changed to master?

**Pull request merged**
