### PR TITLE
SF-1736 Confirm before removing user

### PR DESCRIPTION
**Pull request by Nateowami**
This creates a new generic dialog for showing messages and offering options. Here's how it looks in the collaborators component (and this is the only new dialog introduced in this commit):

This change is [Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1497)

### CODE REVIEW

**Review by Nateowami — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1497)* status: 0 of 9 files reviewed, all discussions resolved

___
*[`src/SIL.XForge.Scripture/ClientApp/src/xforge-common/dialog.service.ts` line 54 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/1497#-NBtLgWI8di9EBowdUMF:-NBtLgWI8di9EBowdUMG:byn24dy) ([raw file](https://github.com/sillsdev/web-xforge/blob/1a5327a50bbf45b3f630f25e4b3f1fe1bc01891b/src/SIL.XForge.Scripture/ClientApp/src/xforge-common/dialog.service.ts#L54)):*
> ```XML
>   }
> 
>   async message(message: Observable<string>, close?: Observable<string>): Promise<void> {
> ```

I created this method in order to test that everything was implemented properly to be able to show just a message. It's not used in this PR, in the interests of keeping this change as small as possible.

**Review by RaymondLuong3 — CHANGES_REQUESTED** [review]
Nice work. It looks good. I wonder if you can replace the message dialog, since it will no long be needed. It looks like it is used in at least 5 other components. That could be a follow-up task.

> Reviewed 8 of 9 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1497#-:-NBy3OC8586Hgso39iIP:b-uk8cbz)* status: all files reviewed, 4 unresolved discussions (waiting on @Nateowami)

___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/users/collaborators/collaborators.component.ts` line 197 at r2](https://reviewable.io/reviews/sillsdev/web-xforge/1497#-NBy0O6n9I-bHgaDh6xN:-NBy0O6n9I-bHgaDh6xO:b-urogum) ([raw file](https://github.com/sillsdev/web-xforge/blob/7044c4c6275e1208838fe41ec621f1cf9587454b/src/SIL.XForge.Scripture/ClientApp/src/app/users/collaborators/collaborators.component.ts#L197)):*
> ```XML
> 
>   async removeProjectUserClicked(row: Row): Promise<void> {
>     const confirmed = await this.dialogService.confirm(
> ```

Add a type on this.



_Code quote:_
```XML
    const confirmed = await this.dialogService.confirm(
```
___
*[`src/SIL.XForge.Scripture/ClientApp/src/assets/i18n/non_checking_en.json` line 38 at r2](https://reviewable.io/reviews/sillsdev/web-xforge/1497#-NBy0k8p9gPuP1eu7IGI:-NBy0k8qDVY9DcEqakIS:bju3mde) ([raw file](https://github.com/sillsdev/web-xforge/blob/7044c4c6275e1208838fe41ec621f1cf9587454b/src/SIL.XForge.Scripture/ClientApp/src/assets/i18n/non_checking_en.json#L38)):*
> ```JSON
>     "cancel_invite": "Cancel invite",
>     "change_roles_and_permissions": "Users' roles and permissions can {{ boldStart }}only{{ boldEnd }} be changed in {{ boldStart }}Paratext{{ boldEnd }}. Open the project in {{ boldStart }}Paratext{{ boldEnd }}, on the project window click {{ templateTagBoundary }}{{ templateTagBoundary }}, then {{ boldStart }}Project settings{{ boldEnd }}, then {{ boldStart }}User permissions{{ boldEnd }}. After a {{ italicsStart }}Send/Receive{{ italicsEnd }} in {{ boldStart }}Paratext{{ boldEnd }} and then a {{ italicsStart }}Synchronize{{ italicsEnd }} in {{ boldStart }}Scripture Forge{{ boldEnd }}, their role will come into effect here, once that user logs in with their {{ boldStart }}Paratext{{ boldEnd }} account.",
>     "confirm_remove_user": "Are you sure you want to remove \"{{ user }}\" from the  project?",
> ```

Nit: This is an extra space between 'the' and 'project'



_Code quote:_
```JSON
from the  project?",
```
___
*[`src/SIL.XForge.Scripture/ClientApp/src/xforge-common/i18n.service.ts` line 199 at r2](https://reviewable.io/reviews/sillsdev/web-xforge/1497#-NBy2Pu0AwGEKc47kiZ4:-NBy2Pu0AwGEKc47kiZ5:brp9agy) ([raw file](https://github.com/sillsdev/web-xforge/blob/7044c4c6275e1208838fe41ec621f1cf9587454b/src/SIL.XForge.Scripture/ClientApp/src/xforge-common/i18n.service.ts#L199)):*
> ```XML
> 
>   translate(key: string, params: object = {}): Observable<string> {
>     return this.transloco.selectTranslate<string>(key, params);
> ```

Are you using `selectTranslate` because you cannot be sure the translation file is loaded, or because there is a chance the active language could change?



_Code quote:_
```XML
 return this.transloco.selectTranslate<string>(key, params);
```
___
*[`src/SIL.XForge.Scripture/ClientApp/src/xforge-common/generic-dialog/generic-dialog.component.ts` line 16 at r2](https://reviewable.io/reviews/sillsdev/web-xforge/1497#-NBy45Ys8y6vYOtX62UL:-NBy45Ys8y6vYOtX62UM:b-r08cbc) ([raw file](https://github.com/sillsdev/web-xforge/blob/7044c4c6275e1208838fe41ec621f1cf9587454b/src/SIL.XForge.Scripture/ClientApp/src/xforge-common/generic-dialog/generic-dialog.component.ts#L16)):*
> ```XML
> 
> @Component({
>   templateUrl: './generic-dialog.component.html'
> ```

Nit: It may be helpful to define a selector like `app-generic-dialog`



_Code quote:_
```XML
  templateUrl: './generic-dialog.component.html'
```

**Review by Nateowami — COMMENTED** [review]
> I wonder if you can replace the message dialog, since it will no long be needed. It looks like it is used in at least 5 other components. That could be a follow-up task.

That is my plan. Also there are some confirmation dialogs that can be replaced, but I wanted to make that a separate step. And then I plan to finish up SF-1701, which needs a confirmation dialog.

> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1497#-:-NByEY845JLAjNe4vWOm:b-mwmw0b)* status: all files reviewed, 3 unresolved discussions (waiting on @RaymondLuong3)

___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/users/collaborators/collaborators.component.ts` line 197 at r2](https://reviewable.io/reviews/sillsdev/web-xforge/1497#-NBy0O6n9I-bHgaDh6xN:-NByE-u32W94iQrsvTyu:b1j6gln) ([raw file](https://github.com/sillsdev/web-xforge/blob/7044c4c6275e1208838fe41ec621f1cf9587454b/src/SIL.XForge.Scripture/ClientApp/src/app/users/collaborators/collaborators.component.ts#L197)):*
<details><summary><i>Previously, RaymondLuong3 (Raymond Luong) wrote…</i></summary><blockquote>

Add a type on this.
</blockquote></details>

Done. I also changed the return type of this method to always be boolean.
___
*[`src/SIL.XForge.Scripture/ClientApp/src/assets/i18n/non_checking_en.json` line 38 at r2](https://reviewable.io/reviews/sillsdev/web-xforge/1497#-NBy0k8p9gPuP1eu7IGI:-NByE6md4l45S9DarMLS:b-4nowv7) ([raw file](https://github.com/sillsdev/web-xforge/blob/7044c4c6275e1208838fe41ec621f1cf9587454b/src/SIL.XForge.Scripture/ClientApp/src/assets/i18n/non_checking_en.json#L38)):*
<details><summary><i>Previously, RaymondLuong3 (Raymond Luong) wrote…</i></summary><blockquote>

Nit: This is an extra space between 'the' and 'project'
</blockquote></details>

Nice catch. Done.
___
*[`src/SIL.XForge.Scripture/ClientApp/src/xforge-common/i18n.service.ts` line 199 at r2](https://reviewable.io/reviews/sillsdev/web-xforge/1497#-NBy2Pu0AwGEKc47kiZ4:-NByDGDw3iwTULNo4opo:b-uxzjqo) ([raw file](https://github.com/sillsdev/web-xforge/blob/7044c4c6275e1208838fe41ec621f1cf9587454b/src/SIL.XForge.Scripture/ClientApp/src/xforge-common/i18n.service.ts#L199)):*
<details><summary><i>Previously, RaymondLuong3 (Raymond Luong) wrote…</i></summary><blockquote>

Are you using `selectTranslate` because you cannot be sure the translation file is loaded, or because there is a chance the active language could change?
</blockquote></details>

Yes, those are the exact reasons I considered for doing this. It might be that a dialog pops up just as the page is loading. I also considered that we may want to write automated tests that take screenshots in multiple languages, and that's somewhat harder if the dialog has to be re-opened every time.
___
*[`src/SIL.XForge.Scripture/ClientApp/src/xforge-common/generic-dialog/generic-dialog.component.ts` line 16 at r2](https://reviewable.io/reviews/sillsdev/web-xforge/1497#-NBy45Ys8y6vYOtX62UL:-NByF_Jv6a9fkBYXpyVp:bw5vwjr) ([raw file](https://github.com/sillsdev/web-xforge/blob/7044c4c6275e1208838fe41ec621f1cf9587454b/src/SIL.XForge.Scripture/ClientApp/src/xforge-common/generic-dialog/generic-dialog.component.ts#L16)):*
<details><summary><i>Previously, RaymondLuong3 (Raymond Luong) wrote…</i></summary><blockquote>

Nit: It may be helpful to define a selector like `app-generic-dialog`
</blockquote></details>

I've never understood why some of our dialogs have selectors, when we don't actually select them using selectors. Is there a reason I might be missing? I assumed they were written as a force of habit.

**Review by RaymondLuong3 — APPROVED** [review]
I just had a non-blocking comment. I'll use this dialog in the delete note PR that I have opened.

> Reviewed 3 of 3 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1497#-:-NCRrb6Z3ufGz2Bn8wmD:bd2a1b7)* status: all files reviewed, 2 unresolved discussions (waiting on @Nateowami)

___
*[`src/SIL.XForge.Scripture/ClientApp/src/xforge-common/i18n.service.ts` line 199 at r2](https://reviewable.io/reviews/sillsdev/web-xforge/1497#-NBy2Pu0AwGEKc47kiZ4:-NCRr6u856ovC_jsdOfR:b-m704au) ([raw file](https://github.com/sillsdev/web-xforge/blob/7044c4c6275e1208838fe41ec621f1cf9587454b/src/SIL.XForge.Scripture/ClientApp/src/xforge-common/i18n.service.ts#L199)):*
<details><summary><i>Previously, Nateowami (Nathaniel Paulus) wrote…</i></summary><blockquote>

Yes, those are the exact reasons I considered for doing this. It might be that a dialog pops up just as the page is loading. I also considered that we may want to write automated tests that take screenshots in multiple languages, and that's somewhat harder if the dialog has to be re-opened every time.
</blockquote></details>

Ok, that's good to know so I can also follow this pattern.
___
*[`src/SIL.XForge.Scripture/ClientApp/src/xforge-common/generic-dialog/generic-dialog.component.ts` line 16 at r2](https://reviewable.io/reviews/sillsdev/web-xforge/1497#-NBy45Ys8y6vYOtX62UL:-NCRrLFjCofmLhfh5Hxu:b-5k6kg9) ([raw file](https://github.com/sillsdev/web-xforge/blob/7044c4c6275e1208838fe41ec621f1cf9587454b/src/SIL.XForge.Scripture/ClientApp/src/xforge-common/generic-dialog/generic-dialog.component.ts#L16)):*
<details><summary><i>Previously, Nateowami (Nathaniel Paulus) wrote…</i></summary><blockquote>

I've never understood why some of our dialogs have selectors, when we don't actually select them using selectors. Is there a reason I might be missing? I assumed they were written as a force of habit.
</blockquote></details>

The reason I include it is so that it is easy to find this component in the DOM tree when it has a name. Otherwise, it may just be a preference thing.

**Pull request merged**
