### PR TITLE
Update dependencies in all package.json files

### PR DESCRIPTION
**Pull request by Nateowami**
This only updates packages to versions already satisfied by the package.json file; it doesn't update to new major versions of anything.

As far as I can tell, all packages are at the same version across our project.

---
This change is [Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1371)

### CODE REVIEW

**Review by marksvc — APPROVED** [review]
> Reviewed 6 of 6 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1371)* status: all files reviewed, 1 unresolved discussion (waiting on @Nateowami)

___
*[`scripts/db_tools/package-lock.json` line 96 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/1371#-N2XR3QT5bhtKMQmSU2k:-N2XR3QT5bhtKMQmSU2l:bfzarym) ([raw file](https://github.com/sillsdev/web-xforge/blob/381f10b15af4f6aa12befb74328f6b2fcbdd2a52/scripts/db_tools/package-lock.json#L96)):*
> ```JSON
>     },
>     "node_modules/@types/node": {
>       "version": "17.0.34",
> ```

16 to 17. Hm, ok. 



_Code quote:_
```JSON
 "17.0.34",
```

**Review by Nateowami — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1371)* status: all files reviewed, 1 unresolved discussion (waiting on @marksvc)

___
*[`scripts/db_tools/package-lock.json` line 96 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/1371#-N2XR3QT5bhtKMQmSU2k:-N2Xil5i9FE9gXgKfHSt:bcdsz) ([raw file](https://github.com/sillsdev/web-xforge/blob/381f10b15af4f6aa12befb74328f6b2fcbdd2a52/scripts/db_tools/package-lock.json#L96)):*
<details><summary><i>Previously, marksvc wrote…</i></summary><blockquote>

16 to 17. Hm, ok. 
</blockquote></details>

Running `npm why node_modules/@types/node` is interesting. It looks like projects are specifying `@types/node@"*"`.

**Review by Nateowami — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1371)* status: 0 of 6 files reviewed, 1 unresolved discussion (waiting on @marksvc)

___
*[`scripts/db_tools/package-lock.json` line 96 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/1371#-N2XR3QT5bhtKMQmSU2k:-N2YHh2a2hoAiRQTlg2S:b-ac0vb8) ([raw file](https://github.com/sillsdev/web-xforge/blob/381f10b15af4f6aa12befb74328f6b2fcbdd2a52/scripts/db_tools/package-lock.json#L96)):*
<details><summary><i>Previously, Nateowami (Nathaniel Paulus) wrote…</i></summary><blockquote>

Running `npm why node_modules/@types/node` is interesting. It looks like projects are specifying `@types/node@"*"`.
</blockquote></details>

I think you're on to something noticing this. My guess is they specify `@types/node@"*"` meaning it needs to be installed, but the version is really up to the user of the module to decide. We should have `@types/node` as a dependency ourselves, and we should specify the version ourselves. I just added a commit after running `npm install --save-dev @types/node@16` in each directory where we have a `package.json`.

Also, interesting that `npm why node_modules/@types/node` worked when I meant to run`npm why @types/node`.

**Review by marksvc — COMMENTED** [review]
> Reviewed 6 of 6 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1371)* status: all files reviewed, 1 unresolved discussion (waiting on @Nateowami)

___
*[`src/SIL.XForge.Scripture/ClientApp/package.json` line 89 at r2](https://reviewable.io/reviews/sillsdev/web-xforge/1371#-N2YMAPF5e0iaAM9kMHj:-N2YMAPF5e0iaAM9kMHk:b-kht4vb) ([raw file](https://github.com/sillsdev/web-xforge/blob/ab18c29f301d59bfb146dd4db0d8686ca780091f/src/SIL.XForge.Scripture/ClientApp/package.json#L89)):*
> ```JSON
>     "@types/jasminewd2": "~2.0.10",
>     "@types/lodash-es": "^4.17.6",
>     "@types/node": "^16.11.36",
> ```

12 to 16.  Oh, although, maybe should we be specifying v12 since that's our target platform right now?



_Code quote:_
```JSON
: "^12.20.52",
```

**Review by Nateowami — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1371)* status: all files reviewed, 1 unresolved discussion (waiting on @marksvc)

___
*[`src/SIL.XForge.Scripture/ClientApp/package.json` line 89 at r2](https://reviewable.io/reviews/sillsdev/web-xforge/1371#-N2YMAPF5e0iaAM9kMHj:-N2YN9ZLES3s2GxtOMll:b-8mlkb2) ([raw file](https://github.com/sillsdev/web-xforge/blob/ab18c29f301d59bfb146dd4db0d8686ca780091f/src/SIL.XForge.Scripture/ClientApp/package.json#L89)):*
<details><summary><i>Previously, marksvc wrote…</i></summary><blockquote>

12 to 16.  Oh, although, maybe should we be specifying v12 since that's our target platform right now?
</blockquote></details>

Our target platform is v16 now. It's in master but not yet qa.

**Review by marksvc — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1371)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @Nateowami)

___
*[`src/SIL.XForge.Scripture/ClientApp/package.json` line 89 at r2](https://reviewable.io/reviews/sillsdev/web-xforge/1371#-N2YMAPF5e0iaAM9kMHj:-N2qV8vH60f2DBV9zBTR:b-a1yyt3) ([raw file](https://github.com/sillsdev/web-xforge/blob/ab18c29f301d59bfb146dd4db0d8686ca780091f/src/SIL.XForge.Scripture/ClientApp/package.json#L89)):*
<details><summary><i>Previously, Nateowami (Nathaniel Paulus) wrote…</i></summary><blockquote>

Our target platform is v16 now. It's in master but not yet qa.
</blockquote></details>

:-)  That occurred to me on the weekend: this is part of moving to v16.

**Pull request merged**
