### PR TITLE
SF-1201 Allow inviting users from the translate app

### PR DESCRIPTION
**Pull request by nigel-wells**
- Created a new translate observer role
- Added role selection to the share component for admins
- Added share button to the translate app for admins

image

---
This change is [Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/979)

### CODE REVIEW

**Review by RaymondLuong3 — CHANGES_REQUESTED** [review]
Good work! A few comments below. I also observed that users with the "View Translation" role are basically community checkers with permission to see the translate app. @irahopkinson I'm not entirely sure if this was intended, or if View Translation users should not have access to the community checking app.

> Reviewed 17 of 18 files at r1, 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/979#-:-MVqjz6l2HcI_sSfFQYW:b-hx6ejj)* status: all files reviewed, 5 unresolved discussions (waiting on @nigel-wells)

___
*[src/RealtimeServer/scriptureforge/models/sf-project-rights.ts, line 54 at r2](https://reviewable.io/reviews/sillsdev/web-xforge/979#-MVqVzBN9YZs4V0JyvkX:-MVqVzBN9YZs4V0JyvkY:b304lom) ([raw file](https://github.com/sillsdev/web-xforge/blob/ec846a26bba724b42d5d8ac1240fe3c80e7d3642/src/RealtimeServer/scriptureforge/models/sf-project-rights.ts#L54)):*
> ```
>     const translatorObserverRights: ProjectRight[] = reviewerRights.concat([
>       { projectDomain: SFProjectDomain.Texts, operation: Operation.View }
>     ]);
> ```
This isn't necessary because the reviewer already has permission to view texts
___
*[src/SIL.XForge.Scripture/ClientApp/src/app/shared/share/share-control.component.html, line 28 at r2](https://reviewable.io/reviews/sillsdev/web-xforge/979#-MVqcvic5phGsSd6qTaH:-MVqcvidDUxQ4d7u2fco:b-gie22z) ([raw file](https://github.com/sillsdev/web-xforge/blob/ec846a26bba724b42d5d8ac1240fe3c80e7d3642/src/SIL.XForge.Scripture/ClientApp/src/app/shared/share/share-control.component.html#L28)):*
> ```
> <mat-form-field *ngIf="isProjectAdmin" id="invitation_role">
> ```
The other element id names use a hyphen instead of underscore. We should keep that consistent to the hyphen. And below for invitation_language.
___
*[src/SIL.XForge.Scripture/ClientApp/src/app/shared/share/share-control.component.html, line 46 at r2](https://reviewable.io/reviews/sillsdev/web-xforge/979#-MVqZMeH2UEtT7yaAYx-:-MVqZMeH2UEtT7yaAYx0:b-47gy3d) ([raw file](https://github.com/sillsdev/web-xforge/blob/ec846a26bba724b42d5d8ac1240fe3c80e7d3642/src/SIL.XForge.Scripture/ClientApp/src/app/shared/share/share-control.component.html#L46)):*
<details><summary><i alt="summary">Quoted 5 lines of code…</i></summary>

> ```
>           <button
>             id="send-btn"
>             mdc-button
>             form="email-form"
>             type="submit"
> ```
</details>

This could be a raised button or an outlined button. In mobile view the send goes on its own line, and isn't very prominent.
___
*[src/SIL.XForge.Scripture/ClientApp/src/app/shared/share/share-control.component.scss, line 28 at r2](https://reviewable.io/reviews/sillsdev/web-xforge/979#-MVq_aV945xX2147CQaY:-MVq_aV945xX2147CQaZ:b94bs3e) ([raw file](https://github.com/sillsdev/web-xforge/blob/ec846a26bba724b42d5d8ac1240fe3c80e7d3642/src/SIL.XForge.Scripture/ClientApp/src/app/shared/share/share-control.component.scss#L28)):*
> ```
> :host:not(.share-dialog) {
>   mat-form-field {
>     &:not(:last-child) {
> ```
Hey, that's neat you can specify that this only applies if the host isn't a share dialog.
___
*[src/SIL.XForge.Scripture/ClientApp/src/app/shared/share/share-control.component.ts, line 93 at r2](https://reviewable.io/reviews/sillsdev/web-xforge/979#-MVqauiP5TBvaXJSCNvT:-MVqauiP5TBvaXJSCNvU:b-akt9fq) ([raw file](https://github.com/sillsdev/web-xforge/blob/ec846a26bba724b42d5d8ac1240fe3c80e7d3642/src/SIL.XForge.Scripture/ClientApp/src/app/shared/share/share-control.component.ts#L93)):*
> ```
>     if (this.defaultRole != null && this.roles.filter(r => r.role === this.defaultRole).length) {
> ```
I've seen generally that we write out length > 0
___
*[src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.spec.ts, line 111 at r2](https://reviewable.io/reviews/sillsdev/web-xforge/979#-MVqe9Ad6WBL0J3sCu9q:-MVqe9Ad6WBL0J3sCu9r:b-dh4xru) ([raw file](https://github.com/sillsdev/web-xforge/blob/ec846a26bba724b42d5d8ac1240fe3c80e7d3642/src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.spec.ts#L111)):*
> ```
>     expect(env.sharingButton).toBeTruthy();
> ```
This could be `.not.toBeNull()` to contrast what is checked above.

**Review by nigel-wells — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/979)* status: 13 of 18 files reviewed, 5 unresolved discussions (waiting on @Nateowami and @RaymondLuong3)

___
*[src/RealtimeServer/scriptureforge/models/sf-project-rights.ts, line 54 at r2](https://reviewable.io/reviews/sillsdev/web-xforge/979#-MVqVzBN9YZs4V0JyvkX:-MVscscV4KFvKbcHcTqz:b-29mnvv) ([raw file](https://github.com/sillsdev/web-xforge/blob/ec846a26bba724b42d5d8ac1240fe3c80e7d3642/src/RealtimeServer/scriptureforge/models/sf-project-rights.ts#L54)):*
<details><summary><i>Previously, RaymondLuong3 (Raymond Luong) wrote…</i></summary><blockquote>

> ```
>     const translatorObserverRights: ProjectRight[] = reviewerRights.concat([
>       { projectDomain: SFProjectDomain.Texts, operation: Operation.View }
>     ]);
> ```
This isn't necessary because the reviewer already has permission to view texts
</blockquote></details>

Ah I see `Operation.View` is permission for the source text and the target will still show. So this observer role really has no rights to do anything and they purely only get to the translate app because we've said that role can? I commented on something @nateowami mentioned in Slack that I think we might need to come up with a different way of who has access to what app based on their rights rather than what role it happens to be. I'll leave as and we can discuss at our planning meeting.
___
*[src/SIL.XForge.Scripture/ClientApp/src/app/shared/share/share-control.component.html, line 28 at r2](https://reviewable.io/reviews/sillsdev/web-xforge/979#-MVqcvic5phGsSd6qTaH:-MVsddbzA8iVMDgiJU3P:bietc8n) ([raw file](https://github.com/sillsdev/web-xforge/blob/ec846a26bba724b42d5d8ac1240fe3c80e7d3642/src/SIL.XForge.Scripture/ClientApp/src/app/shared/share/share-control.component.html#L28)):*
<details><summary><i>Previously, RaymondLuong3 (Raymond Luong) wrote…</i></summary><blockquote>

> ```
> <mat-form-field *ngIf="isProjectAdmin" id="invitation_role">
> ```
The other element id names use a hyphen instead of underscore. We should keep that consistent to the hyphen. And below for invitation_language.
</blockquote></details>

Done. I typically used underscore for IDs and hyphens for classes in other projects so forget to change that in SF :)
___
*[src/SIL.XForge.Scripture/ClientApp/src/app/shared/share/share-control.component.html, line 46 at r2](https://reviewable.io/reviews/sillsdev/web-xforge/979#-MVqZMeH2UEtT7yaAYx-:-MVsegGo4WUJHZijuKp6:b85i90q) ([raw file](https://github.com/sillsdev/web-xforge/blob/ec846a26bba724b42d5d8ac1240fe3c80e7d3642/src/SIL.XForge.Scripture/ClientApp/src/app/shared/share/share-control.component.html#L46)):*
<details><summary><i>Previously, RaymondLuong3 (Raymond Luong) wrote…</i></summary><blockquote>

> ```
>           <button
>             id="send-btn"
>             mdc-button
>             form="email-form"
>             type="submit"
> ```
This could be a raised button or an outlined button. In mobile view the send goes on its own line, and isn't very prominent.
</blockquote></details>

Changed to a flat primary button.
___
*[src/SIL.XForge.Scripture/ClientApp/src/app/shared/share/share-control.component.scss, line 28 at r2](https://reviewable.io/reviews/sillsdev/web-xforge/979#-MVq_aV945xX2147CQaY:-MVseibHBgmF9b6CKg0M:bd9diz1) ([raw file](https://github.com/sillsdev/web-xforge/blob/ec846a26bba724b42d5d8ac1240fe3c80e7d3642/src/SIL.XForge.Scripture/ClientApp/src/app/shared/share/share-control.component.scss#L28)):*
<details><summary><i>Previously, RaymondLuong3 (Raymond Luong) wrote…</i></summary><blockquote>

> ```
> :host:not(.share-dialog) {
>   mat-form-field {
>     &:not(:last-child) {
> ```
Hey, that's neat you can specify that this only applies if the host isn't a share dialog.
</blockquote></details>

Yes new trick I learned for this!
___
*[src/SIL.XForge.Scripture/ClientApp/src/app/shared/share/share-control.component.ts, line 93 at r2](https://reviewable.io/reviews/sillsdev/web-xforge/979#-MVqauiP5TBvaXJSCNvT:-MVsex4J7iK9xhG-izBa:bb6un1j) ([raw file](https://github.com/sillsdev/web-xforge/blob/ec846a26bba724b42d5d8ac1240fe3c80e7d3642/src/SIL.XForge.Scripture/ClientApp/src/app/shared/share/share-control.component.ts#L93)):*
<details><summary><i>Previously, RaymondLuong3 (Raymond Luong) wrote…</i></summary><blockquote>

> ```
>     if (this.defaultRole != null && this.roles.filter(r => r.role === this.defaultRole).length) {
> ```
I've seen generally that we write out length > 0
</blockquote></details>

Done
___
*[src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.spec.ts, line 111 at r2](https://reviewable.io/reviews/sillsdev/web-xforge/979#-MVqe9Ad6WBL0J3sCu9q:-MVsfBoS0ODxaT92tB47:b-896fix) ([raw file](https://github.com/sillsdev/web-xforge/blob/ec846a26bba724b42d5d8ac1240fe3c80e7d3642/src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.spec.ts#L111)):*
<details><summary><i>Previously, RaymondLuong3 (Raymond Luong) wrote…</i></summary><blockquote>

> ```
>     expect(env.sharingButton).toBeTruthy();
> ```
This could be `.not.toBeNull()` to contrast what is checked above.
</blockquote></details>

Done.

**Review by RaymondLuong3 — COMMENTED** [review]
I have two things to mention. (1) If a user is already a community checker, they won't be allowed to see the translate app even if they use the view translation share link. And (2) we mentioned last night that we want to split out domains for the checking and translate app. They doesn't have to hold up this PR though.

> Reviewed 5 of 5 files at r3.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/979#-:-MVvXK4B4Owch4PFfOqP:bo9tc32)* status: all files reviewed, 3 unresolved discussions (waiting on @Nateowami and @RaymondLuong3)

**Review by nigel-wells — COMMENTED** [review]
Looking at `InviteAsync` it already discards any user being invited more than once to a project
```
if (await RealtimeService.QuerySnapshots<User>()
   .AnyAsync(u => project.UserRoles.Keys.Contains(u.Id) && u.Email == email))
{
   return false;
 }
```
I've tested it out now and it appears to work fine. 

Yes let's create a new task for adding new rights for accessing the translate and checking app as I suspect there may be more required to that as well.

> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/979#-:-MVxt80a6-mNqAr3SByo:b-aqdvb)* status: all files reviewed, 3 unresolved discussions (waiting on @Nateowami and @RaymondLuong3)

**Review by RaymondLuong3 — APPROVED** [review]
:lgtm: We are holding off from merging changes into master at the moment so hotfix changes on master can be pushed to QA while testing non-beta migration on QA. Once that is done this can go in.

> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/979#-:-MW4nEdr-tZNRaOJ7No1:buagr0r)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @nigel-wells)

**Review by Nateowami — COMMENTED** [review]
@nigel-wells Is there a place where what a reviewer is is defined? I couldn't find it in the spec anywhere. I don't think it's very obvious to the user what a reviewer is.

> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/979#-:-MWRM4q3DWi74vIR2JUA:b-mxxn0a)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @nigel-wells)

**Review by nigel-wells — COMMENTED** [review]
@nateowami if you look in `sf-project-rights.ts` you'll see what rights they have. Currently it is the same rights as a community checker and a paratext consultant. I believe it will get expanded in to the translate app but @irahopkinson will need to confirm that.

> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/979#-:-MWRQnSs2oSyoRI08vJY:b-t0lttt)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @nigel-wells)

**Review by Nateowami — COMMENTED** [review]
@nigel-wells Thanks; I did see that file. I'm just wondering whether now is the correct time to enable that role. Was this documented or discussed somewhere?

> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/979#-:-MWRSk6P63TSzlRfkHmz:b-boabed)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @nigel-wells)

**Review by nigel-wells — COMMENTED** [review]
The role is already enabled but currently can only be assigned via the sys admin screen. Only admins can select this role for sharing but that does open it up to paratext admins rather than just sys admins. Could discuss in today's meeting if you have concerns. It is easy enough to switch off from the sharing dialog if we don't want to enable it there just yet.

> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/979#-:-MWRURpW2Z85Cq1Dbid-:b-e8m08f)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @nigel-wells)

**Review by irahopkinson — COMMENTED** [review]
@nigel-wells we definitely don't want the Reviewer user available in the invite Role dropdown until we are ready to go with SF-1192 is ready (not for SF-1198). I've made this PR a draft for now.

> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/979#-:-MWTG79o9-N5rwmEXcl4:bz4x0co)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @nigel-wells)

**Comment by Nateowami** [comment]
@nigel-wells Is there anything holding up this PR other than the reviewer role being prematurely enabled? I'm guessing with a small change this PR can be merged?

**Review by nigel-wells — COMMENTED** [review]
@nateowami I've rebased and disabled the reviewer role from being shareable. Tests passing. Good to go I believe.

> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/979#-:-MZL81GVAG7l_mPJaHo5:b7m0c7b)* status: 9 of 18 files reviewed, all discussions resolved (waiting on @RaymondLuong3)

**Review by irahopkinson — CHANGES_REQUESTED** [review]
> Reviewed 8 of 18 files at r1, 1 of 1 files at r2, 9 of 9 files at r4.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/979)* status: all files reviewed, 5 unresolved discussions (waiting on @nigel-wells)

___
*[src/RealtimeServer/scriptureforge/models/sf-project-rights.ts, line 54 at r4](https://reviewable.io/reviews/sillsdev/web-xforge/979#-MZN3Lm7A79XoZMJjuDg:-MZN3Lm8AOWaQ15mv7We:b-uy3lff) ([raw file](https://github.com/sillsdev/web-xforge/blob/22f46757d4d5a9d52694cde751c16e6447d68764/src/RealtimeServer/scriptureforge/models/sf-project-rights.ts#L54)):*
> ```
> translatorObserverRights
> ```
This seems unfortunate to have `translator` in the name which confusing because it is another role. What other name could we use?
___
*[src/SIL.XForge.Scripture/ClientApp/src/app/core/models/sf-project-role-info.ts, line 22 at r4](https://reviewable.io/reviews/sillsdev/web-xforge/979#-MZN34QY4Z_o_8WiE4as:-MZN34QY4Z_o_8WiE4at:b-6gpgem) ([raw file](https://github.com/sillsdev/web-xforge/blob/22f46757d4d5a9d52694cde751c16e6447d68764/src/SIL.XForge.Scripture/ClientApp/src/app/core/models/sf-project-role-info.ts#L22)):*
> ```
> SF_DEFAULT_SHARE_ROLE
> ```
Perhaps this would be better as `SF_DEFAULT_CHECKING_SHARE_ROLE`?
___
*[src/SIL.XForge.Scripture/ClientApp/src/app/shared/share/share-control.component.html, line 36 at r4](https://reviewable.io/reviews/sillsdev/web-xforge/979#-MZN4ea_2xzp3wa74Bk8:-MZN4ea_2xzp3wa74Bk9:b-luig7w) ([raw file](https://github.com/sillsdev/web-xforge/blob/22f46757d4d5a9d52694cde751c16e6447d68764/src/SIL.XForge.Scripture/ClientApp/src/app/shared/share/share-control.component.html#L36)):*
> ```
> *ngIf="isProjectAdmin"
> ```
Shouldn't this be checking a right (like canShare) rather than a role?
___
*[src/SIL.XForge.Scripture/ClientApp/src/app/shared/share/share-control.component.ts, line 3 at r4](https://reviewable.io/reviews/sillsdev/web-xforge/979#-MZN6OLY9DCIq6F5V15B:-MZN6OLY9DCIq6F5V15C:brwx3kv) ([raw file](https://github.com/sillsdev/web-xforge/blob/22f46757d4d5a9d52694cde751c16e6447d68764/src/SIL.XForge.Scripture/ClientApp/src/app/shared/share/share-control.component.ts#L3)):*
> ```
> OnInit
> ```
This should be part of the inputs above from `@angular/core`.
___
*[src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.html, line 25 at r4](https://reviewable.io/reviews/sillsdev/web-xforge/979#-MZN4pR_9AMiwAQ42ngH:-MZN4pR_9AMiwAQ42ngI:b-luig7w) ([raw file](https://github.com/sillsdev/web-xforge/blob/22f46757d4d5a9d52694cde751c16e6447d68764/src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.html#L25)):*
> ```
> *ngIf="isProjectAdmin"
> ```
Shouldn't this be checking a right (like canShare) rather than a role?

**Review by nigel-wells — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/979)* status: 17 of 18 files reviewed, 5 unresolved discussions (waiting on @irahopkinson)

___
*[src/RealtimeServer/scriptureforge/models/sf-project-rights.ts, line 54 at r4](https://reviewable.io/reviews/sillsdev/web-xforge/979#-MZN3Lm7A79XoZMJjuDg:-MZQQOQqEv2vxmKPM1PT:bvafj77) ([raw file](https://github.com/sillsdev/web-xforge/blob/22f46757d4d5a9d52694cde751c16e6447d68764/src/RealtimeServer/scriptureforge/models/sf-project-rights.ts#L54)):*
<details><summary><i>Previously, irahopkinson (Ira Hopkinson) wrote…</i></summary><blockquote>

> ```
> translatorObserverRights
> ```
This seems unfortunate to have `translator` in the name which confusing because it is another role. What other name could we use?
</blockquote></details>

Not sure I follow - this is an observer role for the translate app isn't it? Or will this server a different purpose? We already have a translate role and an observer role as you know. Maybe`translateObserverRights`?
___
*[src/SIL.XForge.Scripture/ClientApp/src/app/core/models/sf-project-role-info.ts, line 22 at r4](https://reviewable.io/reviews/sillsdev/web-xforge/979#-MZN34QY4Z_o_8WiE4as:-MZQQv7G7CGYTcAR16My:b-mw3rfd) ([raw file](https://github.com/sillsdev/web-xforge/blob/22f46757d4d5a9d52694cde751c16e6447d68764/src/SIL.XForge.Scripture/ClientApp/src/app/core/models/sf-project-role-info.ts#L22)):*
<details><summary><i>Previously, irahopkinson (Ira Hopkinson) wrote…</i></summary><blockquote>

> ```
> SF_DEFAULT_SHARE_ROLE
> ```
Perhaps this would be better as `SF_DEFAULT_CHECKING_SHARE_ROLE`?
</blockquote></details>

I initially did that but decided it is almost redundant. I needed a default role for the sharing component for wherever it gets added i.e. user settings. The default value for the component would be, at this stage, the same as the checking app. So I decided to just leave the generic one in instead of duplicating the line just to set the same value in two different places.
___
*[src/SIL.XForge.Scripture/ClientApp/src/app/shared/share/share-control.component.html, line 36 at r4](https://reviewable.io/reviews/sillsdev/web-xforge/979#-MZN4ea_2xzp3wa74Bk8:-MZQRa6k2foJxBsuYfBG:b-6xzi2t) ([raw file](https://github.com/sillsdev/web-xforge/blob/22f46757d4d5a9d52694cde751c16e6447d68764/src/SIL.XForge.Scripture/ClientApp/src/app/shared/share/share-control.component.html#L36)):*
<details><summary><i>Previously, irahopkinson (Ira Hopkinson) wrote…</i></summary><blockquote>

> ```
> *ngIf="isProjectAdmin"
> ```
Shouldn't this be checking a right (like canShare) rather than a role?
</blockquote></details>

Yes, it should. I think that is part of a bigger task we need to undertake as the majority of our app is checking roles at the moment so that task is probably out of scope for this task.
___
*[src/SIL.XForge.Scripture/ClientApp/src/app/shared/share/share-control.component.ts, line 3 at r4](https://reviewable.io/reviews/sillsdev/web-xforge/979#-MZN6OLY9DCIq6F5V15B:-MZQS82b7AomF0YJoL5P:b649ko8) ([raw file](https://github.com/sillsdev/web-xforge/blob/22f46757d4d5a9d52694cde751c16e6447d68764/src/SIL.XForge.Scripture/ClientApp/src/app/shared/share/share-control.component.ts#L3)):*
<details><summary><i>Previously, irahopkinson (Ira Hopkinson) wrote…</i></summary><blockquote>

> ```
> OnInit
> ```
This should be part of the inputs above from `@angular/core`.
</blockquote></details>

Not sure what my IDE was thinking there.... Fixed.
___
*[src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.html, line 25 at r4](https://reviewable.io/reviews/sillsdev/web-xforge/979#-MZN4pR_9AMiwAQ42ngH:-MZQSCRY1nX11Qva7Bco:b6djk9m) ([raw file](https://github.com/sillsdev/web-xforge/blob/22f46757d4d5a9d52694cde751c16e6447d68764/src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.html#L25)):*
<details><summary><i>Previously, irahopkinson (Ira Hopkinson) wrote…</i></summary><blockquote>

> ```
> *ngIf="isProjectAdmin"
> ```
Shouldn't this be checking a right (like canShare) rather than a role?
</blockquote></details>

As per previous comment about roles and rights.

**Review by irahopkinson — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r5.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/979)* status: all files reviewed, 3 unresolved discussions (waiting on @irahopkinson and @nigel-wells)

___
*[src/RealtimeServer/scriptureforge/models/sf-project-rights.ts, line 54 at r4](https://reviewable.io/reviews/sillsdev/web-xforge/979#-MZN3Lm7A79XoZMJjuDg:-MZQneW-4tcqTjYFbSWp:bod2t2j) ([raw file](https://github.com/sillsdev/web-xforge/blob/22f46757d4d5a9d52694cde751c16e6447d68764/src/RealtimeServer/scriptureforge/models/sf-project-rights.ts#L54)):*
<details><summary><i>Previously, nigel-wells (Nigel Wells) wrote…</i></summary><blockquote>

Not sure I follow - this is an observer role for the translate app isn't it? Or will this server a different purpose? We already have a translate role and an observer role as you know. Maybe`translateObserverRights`?
</blockquote></details>

Using `translate` instead of `translator` would be an improvement. However, now that I look at this closer, I'm pretty sure this role shouldn't inherit from a reviewer at all - we don't want hem to have those rights. In fact, the `observerRights` already exist above and should be sufficient. I don't see a need for a new set of rights?

I think all you need to do is add this line below line 31: `this.addRights(SFProjectRole.Observer, observerRights);` to give your new role the correct rights.
___
*[src/SIL.XForge.Scripture/ClientApp/src/app/core/models/sf-project-role-info.ts, line 22 at r4](https://reviewable.io/reviews/sillsdev/web-xforge/979#-MZN34QY4Z_o_8WiE4as:-MZQq5Qi2oHYIoyYb2nl:b-s9buna) ([raw file](https://github.com/sillsdev/web-xforge/blob/22f46757d4d5a9d52694cde751c16e6447d68764/src/SIL.XForge.Scripture/ClientApp/src/app/core/models/sf-project-role-info.ts#L22)):*
<details><summary><i>Previously, nigel-wells (Nigel Wells) wrote…</i></summary><blockquote>

I initially did that but decided it is almost redundant. I needed a default role for the sharing component for wherever it gets added i.e. user settings. The default value for the component would be, at this stage, the same as the checking app. So I decided to just leave the generic one in instead of duplicating the line just to set the same value in two different places.
</blockquote></details>

Sure, this wasn't blocking anyway.
___
*[src/SIL.XForge.Scripture/ClientApp/src/app/shared/share/share-control.component.html, line 36 at r4](https://reviewable.io/reviews/sillsdev/web-xforge/979#-MZN4ea_2xzp3wa74Bk8:-MZQqEmUDchiQS58RNLC:b5qrf5d) ([raw file](https://github.com/sillsdev/web-xforge/blob/22f46757d4d5a9d52694cde751c16e6447d68764/src/SIL.XForge.Scripture/ClientApp/src/app/shared/share/share-control.component.html#L36)):*
<details><summary><i>Previously, nigel-wells (Nigel Wells) wrote…</i></summary><blockquote>

Yes, it should. I think that is part of a bigger task we need to undertake as the majority of our app is checking roles at the moment so that task is probably out of scope for this task.
</blockquote></details>

Sure, but I don't want to propagate bad examples especially when we are adding new code. All you need to do here is change the name of the property to something like `canShare`. That way the HTML is checking rights. The fact that the code is determining that right from a role can then be refactored separately if needed.

**Review by nigel-wells — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/979)* status: all files reviewed, 3 unresolved discussions (waiting on @irahopkinson)

___
*[src/RealtimeServer/scriptureforge/models/sf-project-rights.ts, line 54 at r4](https://reviewable.io/reviews/sillsdev/web-xforge/979#-MZN3Lm7A79XoZMJjuDg:-MZVUDDK2KB7Yrm9rRJ9:bauq92a) ([raw file](https://github.com/sillsdev/web-xforge/blob/22f46757d4d5a9d52694cde751c16e6447d68764/src/RealtimeServer/scriptureforge/models/sf-project-rights.ts#L54)):*
<details><summary><i>Previously, irahopkinson (Ira Hopkinson) wrote…</i></summary><blockquote>

Using `translate` instead of `translator` would be an improvement. However, now that I look at this closer, I'm pretty sure this role shouldn't inherit from a reviewer at all - we don't want hem to have those rights. In fact, the `observerRights` already exist above and should be sufficient. I don't see a need for a new set of rights?

I think all you need to do is add this line below line 31: `this.addRights(SFProjectRole.Observer, observerRights);` to give your new role the correct rights.
</blockquote></details>

If that's the case then I've completely misunderstood the original task. I thought this user was to ONLY have viewing rights to the translate app and NOT the checking app which is why I setup what I did. If it is to be exactly the same as the Paratext Observer then, yes, I can do as you suggest. Please confirm.
___
*[src/SIL.XForge.Scripture/ClientApp/src/app/shared/share/share-control.component.html, line 36 at r4](https://reviewable.io/reviews/sillsdev/web-xforge/979#-MZN4ea_2xzp3wa74Bk8:-MZVvwDeCRhw93rLmISx:b6ytjn5) ([raw file](https://github.com/sillsdev/web-xforge/blob/22f46757d4d5a9d52694cde751c16e6447d68764/src/SIL.XForge.Scripture/ClientApp/src/app/shared/share/share-control.component.html#L36)):*
<details><summary><i>Previously, irahopkinson (Ira Hopkinson) wrote…</i></summary><blockquote>

Sure, but I don't want to propagate bad examples especially when we are adding new code. All you need to do here is change the name of the property to something like `canShare`. That way the HTML is checking rights. The fact that the code is determining that right from a role can then be refactored separately if needed.
</blockquote></details>

Actually this one is just an admin specific check as only admins can set the role on the invitation - there is no project rights for who has permission to set the invitation role.

**Review by nigel-wells — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/979)* status: 13 of 18 files reviewed, 3 unresolved discussions (waiting on @irahopkinson and @RaymondLuong3)

___
*[src/RealtimeServer/scriptureforge/models/sf-project-rights.ts, line 54 at r4](https://reviewable.io/reviews/sillsdev/web-xforge/979#-MZN3Lm7A79XoZMJjuDg:-MZW0o_SEl8NLsp3eGYL:b-896fix) ([raw file](https://github.com/sillsdev/web-xforge/blob/22f46757d4d5a9d52694cde751c16e6447d68764/src/RealtimeServer/scriptureforge/models/sf-project-rights.ts#L54)):*
<details><summary><i>Previously, nigel-wells (Nigel Wells) wrote…</i></summary><blockquote>

If that's the case then I've completely misunderstood the original task. I thought this user was to ONLY have viewing rights to the translate app and NOT the checking app which is why I setup what I did. If it is to be exactly the same as the Paratext Observer then, yes, I can do as you suggest. Please confirm.
</blockquote></details>

Done.
___
*[src/SIL.XForge.Scripture/ClientApp/src/app/shared/share/share-control.component.html, line 36 at r4](https://reviewable.io/reviews/sillsdev/web-xforge/979#-MZN4ea_2xzp3wa74Bk8:-MZW0nKK7hh5so9wm1UJ:b-896fix) ([raw file](https://github.com/sillsdev/web-xforge/blob/22f46757d4d5a9d52694cde751c16e6447d68764/src/SIL.XForge.Scripture/ClientApp/src/app/shared/share/share-control.component.html#L36)):*
<details><summary><i>Previously, nigel-wells (Nigel Wells) wrote…</i></summary><blockquote>

Actually this one is just an admin specific check as only admins can set the role on the invitation - there is no project rights for who has permission to set the invitation role.
</blockquote></details>

Done.
___
*[src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.html, line 25 at r4](https://reviewable.io/reviews/sillsdev/web-xforge/979#-MZN4pR_9AMiwAQ42ngH:-MZW0loj8PwFL2Xjx6WA:b-896fix) ([raw file](https://github.com/sillsdev/web-xforge/blob/22f46757d4d5a9d52694cde751c16e6447d68764/src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.html#L25)):*
<details><summary><i>Previously, nigel-wells (Nigel Wells) wrote…</i></summary><blockquote>

As per previous comment about roles and rights.
</blockquote></details>

Done.

**Review by irahopkinson — APPROVED** [review]
:lgtm:

> Reviewed 5 of 5 files at r6.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/979#-:-MZW5NhUEuM8q4jtYjgd:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @nigel-wells)

**Pull request merged**
