### PR TITLE
SF-1852 Hide conflict notes from SF

### PR DESCRIPTION
**Pull request by RaymondLuong3**
This change hides conflict notes from being displayed in SF. Since there is not much usefulness to showing the conflicts in SF, we can clean up the editor this way. The code is still there, so if we need to introduce a setting to show conflict notes in the future, we can do that easily.
Other notes such as biblical terms and spelling notes will still be visible.

- - -
This change is [Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1688)

### CODE REVIEW

**Review by nigel-wells — CHANGES_REQUESTED** [review]
I'm ok with this but I do wonder about the code being left laying around forever. Are we leaving it there because we will enable it again in the future or are we still deciding? Perhaps it could be behind a feature a flag to justify its existence :)

> Reviewed 4 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1688#-:-NNiku-z5PV_xDGCuGrC:b-15e8q0)* status: all files reviewed, 2 unresolved discussions (waiting on @RaymondLuong3)

___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.ts` line 1613 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/1688#-NNik6Lb6Zzvm8QhhX6c:-NNik6Lc4we8yjWz-7AY:b-9hgfb7) ([raw file](https://github.com/sillsdev/web-xforge/blob/4da752a804fb226ff4e60ac159ba99ad65d4bf21/src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.ts#L1613)):*
> ```XML
>         nt.data.verseRef.chapterNum === this.chapter &&
>         nt.data.notes.length > 0 &&
>         nt.data.notes[0].type !== NoteType.Conflict
> ```

Just checking, will a conflict note always be the first index of the array or could they appear anywhere within the notes array?
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.spec.ts` line 1536 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/1688#-NNikkByB7GzO6YpHxET:-NNikkByB7GzO6YpHxEU:bg0va84) ([raw file](https://github.com/sillsdev/web-xforge/blob/4da752a804fb226ff4e60ac159ba99ad65d4bf21/src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.spec.ts#L1536)):*
> ```XML
>     }));
> 
>     it('hides conflict notes', fakeAsync(() => {
> ```

The test is to assert that conflict notes don't appear rather than the ability to hide them isn't it?

**Review by RaymondLuong3 — COMMENTED** [review]
From what I understand, we might want to remove it all together since it is unlikely that anyone will ask for the ability to see conflict notes in SF. So I've decided to remove it all together. In the unlikely case when someone does ask for it, we can always retrieve it from the git history.

> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1688#-:-NNmv3A9CMdk-4SvBiWR:b-hw6htb)* status: 2 of 6 files reviewed, 2 unresolved discussions (waiting on @nigel-wells)

___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.ts` line 1613 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/1688#-NNik6Lb6Zzvm8QhhX6c:-NNmvRNf2s5MY-WlooQg:b-d4rg1s) ([raw file](https://github.com/sillsdev/web-xforge/blob/4da752a804fb226ff4e60ac159ba99ad65d4bf21/src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.ts#L1613)):*
<details><summary><i>Previously, nigel-wells (Nigel Wells) wrote…</i></summary><blockquote>

Just checking, will a conflict note always be the first index of the array or could they appear anywhere within the notes array?
</blockquote></details>

Yes, as far as I am aware.
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.spec.ts` line 1536 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/1688#-NNikkByB7GzO6YpHxET:-NNmw9By41pFBls6wDzQ:b-7yayrv) ([raw file](https://github.com/sillsdev/web-xforge/blob/4da752a804fb226ff4e60ac159ba99ad65d4bf21/src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.spec.ts#L1536)):*
<details><summary><i>Previously, nigel-wells (Nigel Wells) wrote…</i></summary><blockquote>

The test is to assert that conflict notes don't appear rather than the ability to hide them isn't it?
</blockquote></details>

Right. I've updated the name of the test to be more fitting.

**Review by nigel-wells — APPROVED** [review]
Agreed.

> Reviewed 5 of 5 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1688#-:-NNnshrk23BBMHKDcdDu:b-pbdqz3)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @RaymondLuong3)

**Comment by Nateowami** [comment]
> I've decided to remove it all together. In the unlikely case when someone does ask for it, we can always retrieve it from the git history.

I think this was the right call. This way we don't have to maintain the code in the meantime.

**Pull request merged**
