### PR TITLE
SF-1778 Add reviewer role for invitation and share links

### PR DESCRIPTION
**Pull request by RaymondLuong3**
* enable inviting users as a reviewer
* only allow administrators to invite reviewers
* update endpoint to accept the reviewer role in the invite

- - -
This change is [Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1549)

### CODE REVIEW

**Review by RaymondLuong3 — COMMENTED** [review]
I will need to factor this into the feature flag. Should be a quick change for Monday.

> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1549#-:-NEwe2W15lBjHHQD7M2c:b-cjqclq)* status: 0 of 5 files reviewed, all discussions resolved

**Review by RaymondLuong3 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1549)* status: 0 of 5 files reviewed, 1 unresolved discussion

___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/shared/share/share-control.component.ts` line 157 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/1549#-NFA1AgdDtNRPp-sUlp1:-NFA1AgdDtNRPp-sUlp2:b2zookg) ([raw file](https://github.com/sillsdev/web-xforge/blob/9d32577cc3594d1505aa5bd29c5c32ff197791fc/src/SIL.XForge.Scripture/ClientApp/src/app/shared/share/share-control.component.ts#L157)):*
> ```XML
>         role: SFProjectRole.Reviewer,
>         available: this.featureFlags.allowAddingNotes.enabled,
>         permission: this.isProjectAdmin
> ```

I'm not entirely certain if we want any user to be able to invite other reviewers. Maybe we do, since we already have the ability to create a share link.



_Code quote:_
```XML
  permission: this.isProjectAdmin
```

**Review by marksvc — CHANGES_REQUESTED** [review]
> Reviewed 5 of 5 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1549)* status: all files reviewed, 3 unresolved discussions (waiting on @RaymondLuong3)

___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/shared/share/share-control.component.ts` line 155 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/1549#-NFG438ADn9AWInTV_72:-NFG438ADn9AWInTV_73:bdq3zrv) ([raw file](https://github.com/sillsdev/web-xforge/blob/9d32577cc3594d1505aa5bd29c5c32ff197791fc/src/SIL.XForge.Scripture/ClientApp/src/app/shared/share/share-control.component.ts#L155)):*
> ```XML
>       },
>       {
>         role: SFProjectRole.Reviewer,
> ```

Hmm, I'm a bit concerned that seems that the thing that prevents someone from getting a shareable link, which makes Joining users have the Reviewer role, is allowed or disallowed by the frontend. It appears that the C# code will make a shareable link with Reviewer role, if asked by the frontend, as long as TranslateConfig.ShareEnabled and sharelevel is Anyone. Hmm, it appears that there may be similar problems with the permissions check for the CommunityChecker and Observer, a few lines above, where the permissions are specified on the client, but the backend just checks that the user is on the project at all. 
Let's talk about this some more.

I also wonder if maybe the backend should not include the capability for a shareable link to be created for people to Join as Reviewers.
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/shared/share/share-control.component.ts` line 172 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/1549#-NFG8ciBEHCfVKZuCvRu:-NFG8ciBEHCfVKZuCvRv:b-vt647a) ([raw file](https://github.com/sillsdev/web-xforge/blob/9d32577cc3594d1505aa5bd29c5c32ff197791fc/src/SIL.XForge.Scripture/ClientApp/src/app/shared/share/share-control.component.ts#L172)):*
> ```XML
>       return SF_DEFAULT_SHARE_ROLE;
>     }
>     return roles.some(role => role === SF_DEFAULT_TRANSLATE_SHARE_ROLE) ? SF_DEFAULT_TRANSLATE_SHARE_ROLE : roles[0];
> ```

I can't help but think that `roles` could be an empty list some time, such as if `project.translateConfig.shareEnabled===false` and `project.checkingConfig.checkingEnabled===false` and `this.isProjectAdmin===false`. But so far, looking at the code and fiddling with the frontend hasn't led me to it. 



_Code quote:_
```XML
[0];
```
___
*[`test/SIL.XForge.Scripture.Tests/Services/SFProjectServiceTests.cs` line 103 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/1549#-NFG0Wtq1sz8kSmLocQs:-NFG0Wtq1sz8kSmLocQt:b-dwa9mj) ([raw file](https://github.com/sillsdev/web-xforge/blob/9d32577cc3594d1505aa5bd29c5c32ff197791fc/test/SIL.XForge.Scripture.Tests/Services/SFProjectServiceTests.cs#L103)):*
> ```Smalltalk
>             env.SecurityService.GenerateKey().Returns("sfobserverkey");
>             await env.Service.InviteAsync(User01, Project04, observerEmail, "en", SFProjectRole.SFObserver);
>             await env.EmailService
> ```

I think a significant thing to check is that when InviteAsync() is called in a valid way, the project secrets are modified such that there is now a new share key with specific values for the  email address, share key code, and in this situation, the role. So checking that an email is sent is good, but some of our 'security' of how sharing is handled relies on the values of the share key in the project secrets. 

eg, maybe something like
```cs
shareKey = GetProjectShareKeyByKeyCode("sfobserverkey")
Assert.That(shareKey.Email, Is.EqualTo("sf_observer@example.com"));
Assert.That(shareKey.Role, Is.EqualTo(SFProjectRole.SFObserver));
Assert.That(shareKey.Key, Is.EqualTo("sfobserverkey")); // which may or may not be very necessary depending on how GetProjectShareKeyByKeyCode() works
```

**Review by RaymondLuong3 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1549)* status: all files reviewed, 2 unresolved discussions (waiting on @marksvc)

___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/shared/share/share-control.component.ts` line 155 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/1549#-NFG438ADn9AWInTV_72:-NFtvpg12pnYfVIlKVnv:b-i2oarc) ([raw file](https://github.com/sillsdev/web-xforge/blob/9d32577cc3594d1505aa5bd29c5c32ff197791fc/src/SIL.XForge.Scripture/ClientApp/src/app/shared/share/share-control.component.ts#L155)):*
<details><summary><i>Previously, marksvc wrote…</i></summary><blockquote>

Hmm, I'm a bit concerned that seems that the thing that prevents someone from getting a shareable link, which makes Joining users have the Reviewer role, is allowed or disallowed by the frontend. It appears that the C# code will make a shareable link with Reviewer role, if asked by the frontend, as long as TranslateConfig.ShareEnabled and sharelevel is Anyone. Hmm, it appears that there may be similar problems with the permissions check for the CommunityChecker and Observer, a few lines above, where the permissions are specified on the client, but the backend just checks that the user is on the project at all. 
Let's talk about this some more.

I also wonder if maybe the backend should not include the capability for a shareable link to be created for people to Join as Reviewers.
</blockquote></details>

I've added a check that a user must be an admin in order to create a link. I also added some logic to check whether a user should have the right to invite a specific role to the backend. This will restrict who has permission to get a share link.
___
*[`test/SIL.XForge.Scripture.Tests/Services/SFProjectServiceTests.cs` line 103 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/1549#-NFG0Wtq1sz8kSmLocQs:-NFuAkdS0wsDKNb-mkOM:b-yjfgon) ([raw file](https://github.com/sillsdev/web-xforge/blob/9d32577cc3594d1505aa5bd29c5c32ff197791fc/test/SIL.XForge.Scripture.Tests/Services/SFProjectServiceTests.cs#L103)):*
<details><summary><i>Previously, marksvc wrote…</i></summary><blockquote>

I think a significant thing to check is that when InviteAsync() is called in a valid way, the project secrets are modified such that there is now a new share key with specific values for the  email address, share key code, and in this situation, the role. So checking that an email is sent is good, but some of our 'security' of how sharing is handled relies on the values of the share key in the project secrets. 

eg, maybe something like
```cs
shareKey = GetProjectShareKeyByKeyCode("sfobserverkey")
Assert.That(shareKey.Email, Is.EqualTo("sf_observer@example.com"));
Assert.That(shareKey.Role, Is.EqualTo(SFProjectRole.SFObserver));
Assert.That(shareKey.Key, Is.EqualTo("sfobserverkey")); // which may or may not be very necessary depending on how GetProjectShareKeyByKeyCode() works
```
</blockquote></details>

Good thinking. I'll update the test to also check the project secrets were updated.

**Review by marksvc — CHANGES_REQUESTED** [review]
> Reviewed 4 of 4 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1549)* status: all files reviewed, 2 unresolved discussions (waiting on @RaymondLuong3)

___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/shared/share/share-control.component.ts` line 155 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/1549#-NFG438ADn9AWInTV_72:-NFubej64CeivuYcchcH:b-6mhyx0) ([raw file](https://github.com/sillsdev/web-xforge/blob/9d32577cc3594d1505aa5bd29c5c32ff197791fc/src/SIL.XForge.Scripture/ClientApp/src/app/shared/share/share-control.component.ts#L155)):*
<details><summary><i>Previously, RaymondLuong3 (Raymond Luong) wrote…</i></summary><blockquote>

I've added a check that a user must be an admin in order to create a link. I also added some logic to check whether a user should have the right to invite a specific role to the backend. This will restrict who has permission to get a share link.
</blockquote></details>

Great, thanks!
___
*[`test/SIL.XForge.Scripture.Tests/Services/SFProjectServiceTests.cs` line 103 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/1549#-NFG0Wtq1sz8kSmLocQs:-NFuYXmdDJRP7nM1QTyN:b-6t2132) ([raw file](https://github.com/sillsdev/web-xforge/blob/9d32577cc3594d1505aa5bd29c5c32ff197791fc/test/SIL.XForge.Scripture.Tests/Services/SFProjectServiceTests.cs#L103)):*
<details><summary><i>Previously, RaymondLuong3 (Raymond Luong) wrote…</i></summary><blockquote>

Good thinking. I'll update the test to also check the project secrets were updated.
</blockquote></details>

This is good, but it didn't check a key part here which is that the _role_ is what is intended :)
___
*[`test/SIL.XForge.Scripture.Tests/Services/SFProjectServiceTests.cs` line 2592 at r2](https://reviewable.io/reviews/sillsdev/web-xforge/1549#-NFu_Al40k_pNeGcvPrK:-NFu_Al40k_pNeGcvPrL:b-nt8ydb) ([raw file](https://github.com/sillsdev/web-xforge/blob/337acf9c4688d788d92eb0257ebe05933d9ef60e/test/SIL.XForge.Scripture.Tests/Services/SFProjectServiceTests.cs#L2592)):*
> ```Smalltalk
>                                     }
>                                 },
>                                 CheckingConfig = new CheckingConfig { CheckingEnabled = true, ShareEnabled = false },
> ```

I wonder if it would help what is being tested if 
```cs
ShareEnabled=true,
ShareLevel = Checking...Anyone
```
It may not make a difference, but seems like it should be relevant.  (?)



_Code quote:_
```Smalltalk
ShareEnabled = false
```
___
*[`test/SIL.XForge.Scripture.Tests/Services/SFProjectServiceTests.cs` line 2697 at r2](https://reviewable.io/reviews/sillsdev/web-xforge/1549#-NFu_hyp8CZhAT4swvtG:-NFu_hyp8CZhAT4swvtH:b4safy1) ([raw file](https://github.com/sillsdev/web-xforge/blob/337acf9c4688d788d92eb0257ebe05933d9ef60e/test/SIL.XForge.Scripture.Tests/Services/SFProjectServiceTests.cs#L2697)):*
> ```Smalltalk
>                                     ShareLevel = TranslateShareLevel.Anyone
>                                 },
>                                 UserRoles = { { User01, SFProjectRole.Administrator } }
> ```

This sort of change  makes me wonder if it will make some other test start passing now but for the wrong reason :)
For example, suppose the prior code was actually
```cs
UserRoles = { { User01, SFProjectRole.Translator } }
```
and we had a test saying
```cs
MyTest() 
{
  Assert.That(CheckUserPermissions(User01), Is.True, "Translators have adequate access");
}
```
which runs thru SUT code of
```cs
CheckUserPermissions(User01)
{
  if (user is a translator) 
    return true;
  if (user is an admin)
    return true;
  return false;
}
```
Then if we change the TestEnvironment so that User01 is now an Administrator, we are no longer really testing the point of `MyTest()`, which is that a _translator_ has adequate access. So then if we later change the SUT code in `CheckUserPermissions()` so that only, say, admininstrators can do the activity, we don't break the corresponding test. 
That.. maybe wasn't a super example. But anyway, it's something that can be mitigated if in `MyTest()` we specify the environment we are meaning to test, for example
```cs
Assert.That(User01 has the Translator role, "setup");
```
Something to keep in mind.



_Code quote:_
```Smalltalk
UserRoles = { { User01, SFProjectRole.Administrator } }
```

**Review by RaymondLuong3 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1549)* status: all files reviewed, 2 unresolved discussions (waiting on @marksvc)

___
*[`test/SIL.XForge.Scripture.Tests/Services/SFProjectServiceTests.cs` line 103 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/1549#-NFG0Wtq1sz8kSmLocQs:-NGIgIK3E7sD6WYyH9KV:b-mbf4vj) ([raw file](https://github.com/sillsdev/web-xforge/blob/9d32577cc3594d1505aa5bd29c5c32ff197791fc/test/SIL.XForge.Scripture.Tests/Services/SFProjectServiceTests.cs#L103)):*
<details><summary><i>Previously, marksvc wrote…</i></summary><blockquote>

This is good, but it didn't check a key part here which is that the _role_ is what is intended :)
</blockquote></details>

Ah yes. Good catch.
___
*[`test/SIL.XForge.Scripture.Tests/Services/SFProjectServiceTests.cs` line 2592 at r2](https://reviewable.io/reviews/sillsdev/web-xforge/1549#-NFu_Al40k_pNeGcvPrK:-NGIX6xZCNXESsxrnbDi:b-r7kn8a) ([raw file](https://github.com/sillsdev/web-xforge/blob/337acf9c4688d788d92eb0257ebe05933d9ef60e/test/SIL.XForge.Scripture.Tests/Services/SFProjectServiceTests.cs#L2592)):*
<details><summary><i>Previously, marksvc wrote…</i></summary><blockquote>

I wonder if it would help what is being tested if 
```cs
ShareEnabled=true,
ShareLevel = Checking...Anyone
```
It may not make a difference, but seems like it should be relevant.  (?)
</blockquote></details>

This looks to be intentional. I get test failures if I update this to link sharing.
___
*[`test/SIL.XForge.Scripture.Tests/Services/SFProjectServiceTests.cs` line 2697 at r2](https://reviewable.io/reviews/sillsdev/web-xforge/1549#-NFu_hyp8CZhAT4swvtG:-NGIg6WjBaHWD0Z9L54V:b-yox7ka) ([raw file](https://github.com/sillsdev/web-xforge/blob/337acf9c4688d788d92eb0257ebe05933d9ef60e/test/SIL.XForge.Scripture.Tests/Services/SFProjectServiceTests.cs#L2697)):*
<details><summary><i>Previously, marksvc wrote…</i></summary><blockquote>

This sort of change  makes me wonder if it will make some other test start passing now but for the wrong reason :)
For example, suppose the prior code was actually
```cs
UserRoles = { { User01, SFProjectRole.Translator } }
```
and we had a test saying
```cs
MyTest() 
{
  Assert.That(CheckUserPermissions(User01), Is.True, "Translators have adequate access");
}
```
which runs thru SUT code of
```cs
CheckUserPermissions(User01)
{
  if (user is a translator) 
    return true;
  if (user is an admin)
    return true;
  return false;
}
```
Then if we change the TestEnvironment so that User01 is now an Administrator, we are no longer really testing the point of `MyTest()`, which is that a _translator_ has adequate access. So then if we later change the SUT code in `CheckUserPermissions()` so that only, say, admininstrators can do the activity, we don't break the corresponding test. 
That.. maybe wasn't a super example. But anyway, it's something that can be mitigated if in `MyTest()` we specify the environment we are meaning to test, for example
```cs
Assert.That(User01 has the Translator role, "setup");
```
Something to keep in mind.
</blockquote></details>

Good thinking. I added a new user to the project with the administrator role instead.

**Review by marksvc — CHANGES_REQUESTED** [review]
Great! One more thing :)

> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1549#-:-NGIqaxw8O24edLHWFMB:bi71yi3)* status: all files reviewed, 1 unresolved discussion (waiting on @RaymondLuong3)

___
*[`test/SIL.XForge.Scripture.Tests/Services/SFProjectServiceTests.cs` line 2697 at r2](https://reviewable.io/reviews/sillsdev/web-xforge/1549#-NFu_hyp8CZhAT4swvtG:-NGInAkLBMtbN18BwgAY:b4c9lyr) ([raw file](https://github.com/sillsdev/web-xforge/blob/337acf9c4688d788d92eb0257ebe05933d9ef60e/test/SIL.XForge.Scripture.Tests/Services/SFProjectServiceTests.cs#L2697)):*
<details><summary><i>Previously, RaymondLuong3 (Raymond Luong) wrote…</i></summary><blockquote>

Good thinking. I added a new user to the project with the administrator role instead.
</blockquote></details>

:thumbsup: 
___
*[`test/SIL.XForge.Scripture.Tests/Services/SFProjectServiceTests.cs` line 2857 at r3](https://reviewable.io/reviews/sillsdev/web-xforge/1549#-NGIqIjgC7PvifURbtDQ:-NGIqIjgC7PvifURbtDR:b-duwse3) ([raw file](https://github.com/sillsdev/web-xforge/blob/6f921367661680706f3bb0aaa682e3743b7a4744/test/SIL.XForge.Scripture.Tests/Services/SFProjectServiceTests.cs#L2857)):*
> ```Smalltalk
>                             new SFProjectUserConfig { Id = SFProjectUserConfig.GetDocId(Project02, User02) },
>                             new SFProjectUserConfig { Id = SFProjectUserConfig.GetDocId(Project03, User01) },
>                             new SFProjectUserConfig { Id = SFProjectUserConfig.GetDocId(Project03, User02) },
> ```

Obviously this doesn't matter for the tests that are running at present, but it may be helpful in the future if we now add
```cs
new SFProjectUserConfig { Id = SFProjectUserConfig.GetDocId(Project04, User02) },
```
to correspond to adding the user to the project.



_Code quote:_
```Smalltalk
new MemoryRepository
```

**Review by RaymondLuong3 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1549)* status: 4 of 5 files reviewed, 1 unresolved discussion (waiting on @marksvc)

___
*[`test/SIL.XForge.Scripture.Tests/Services/SFProjectServiceTests.cs` line 2857 at r3](https://reviewable.io/reviews/sillsdev/web-xforge/1549#-NGIqIjgC7PvifURbtDQ:-NGJLCpl345pkZqI4zLC:br4occ9) ([raw file](https://github.com/sillsdev/web-xforge/blob/6f921367661680706f3bb0aaa682e3743b7a4744/test/SIL.XForge.Scripture.Tests/Services/SFProjectServiceTests.cs#L2857)):*
<details><summary><i>Previously, marksvc wrote…</i></summary><blockquote>

Obviously this doesn't matter for the tests that are running at present, but it may be helpful in the future if we now add
```cs
new SFProjectUserConfig { Id = SFProjectUserConfig.GetDocId(Project04, User02) },
```
to correspond to adding the user to the project.
</blockquote></details>

Done. And added a few more missing configs.

**Review by marksvc — APPROVED** [review]
> Reviewed 2 of 2 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1549)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @RaymondLuong3)

**Review by Nateowami — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1549)* status: all files reviewed, 1 unresolved discussion (waiting on @RaymondLuong3)

___
*[`src/SIL.XForge.Scripture/Services/SFProjectService.cs` line 1127 at r5](https://reviewable.io/reviews/sillsdev/web-xforge/1549#-NGy6Ana83BbWqRaR4tJ:-NGy6Ana83BbWqRaR4tK:bmxkili) ([raw file](https://github.com/sillsdev/web-xforge/blob/ea64d9f885b7693528824ed6c79d1cd3d4c3fd93/src/SIL.XForge.Scripture/Services/SFProjectService.cs#L1127)):*
> ```Smalltalk
>                 return false;
>             if (role == SFProjectRole.CommunityChecker)
>                 return true;
> ```

This logic seems wrong. What if the user is an observer?

**Review by RaymondLuong3 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1549)* status: all files reviewed, 1 unresolved discussion (waiting on @Nateowami)

___
*[`src/SIL.XForge.Scripture/Services/SFProjectService.cs` line 1127 at r5](https://reviewable.io/reviews/sillsdev/web-xforge/1549#-NGy6Ana83BbWqRaR4tJ:-NH0TZp-EeYInm1glZpS:b-f3gnto) ([raw file](https://github.com/sillsdev/web-xforge/blob/ea64d9f885b7693528824ed6c79d1cd3d4c3fd93/src/SIL.XForge.Scripture/Services/SFProjectService.cs#L1127)):*
<details><summary><i>Previously, Nateowami (Nathaniel Paulus) wrote…</i></summary><blockquote>

This logic seems wrong. What if the user is an observer?
</blockquote></details>

That is a good question. As it is now, an observer is allowed to invite community checkers before these changes. And as it stands, an observer has access to the community checking tool, so observers inviting community checkers is not overreaching what they should be able to share. It is worth revisiting the sharing workflow.

**Comment by Nateowami** [comment]
> As it is now, an observer is allowed to invite community checkers before these changes. And as it stands, an observer has access to the community checking tool

Surely observers can't answer questions, right? If they can that's a bug.

**Comment by RaymondLuong3** [comment]
Observers cannot answer questions or comment. They only have view access. I just checked, and the add answer button is not available to observer users.

**Pull request merged**
