### PR TITLE
SF-1939 Improve error message for invalid invitations

### PR DESCRIPTION
**Pull request by nigel-wells**
- Return relevant error codes when checking a share key or generating a user
- Created stories
- Improved type checking for errors
- Bug fix for unknown errors returning an empty string

- - -
This change is [Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1872)

### CODE REVIEW

**Review by RaymondLuong3 — CHANGES_REQUESTED** [review]
> Reviewed 5 of 5 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1872)* status: all files reviewed, 3 unresolved discussions (waiting on @nigel-wells)

___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/join/join.stories.ts` line 178 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/1872#-NWhpe7S3NCO7R7CPiHn:-NWhpe7S3NCO7R7CPiHo:bpw5ru9) ([raw file](https://github.com/sillsdev/web-xforge/blob/a3cf8af024af978749fe429e1dd71f04b55597b0/src/SIL.XForge.Scripture/ClientApp/src/app/join/join.stories.ts#L178)):*
> ```XML
>   play: async ({ canvasElement }) => {
>     const canvas = within(canvasElement);
>     const joinButton = canvas.getByRole('button');
> ```

Add types to these objects where you can. Here and below.
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/join/join.stories.ts` line 197 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/1872#-NWht-KZ-WbKXIuM3QHs:-NWht-KZ-WbKXIuM3QHt:b-dxd0su) ([raw file](https://github.com/sillsdev/web-xforge/blob/a3cf8af024af978749fe429e1dd71f04b55597b0/src/SIL.XForge.Scripture/ClientApp/src/app/join/join.stories.ts#L197)):*
> ```XML
> };
> 
> export const DialogInvalidShareKey: Story = {
> ```

Are these tests? I don't see how it works. Maybe the play is implicit?
___
*[`src/SIL.XForge.Scripture/ClientApp/src/assets/i18n/non_checking_en.json` line 163 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/1872#-NWhqT_9Di-OBuqbJi7j:-NWhqT_9Di-OBuqbJi7k:bpy7k9b) ([raw file](https://github.com/sillsdev/web-xforge/blob/a3cf8af024af978749fe429e1dd71f04b55597b0/src/SIL.XForge.Scripture/ClientApp/src/assets/i18n/non_checking_en.json#L163)):*
> ```JSON
>     "please_connect_to_use_link": "Please connect to the internet to join a project using a link.",
>     "project_link_is_invalid": "The project link is invalid. Please contact the person who sent you the link and ask for a new one.",
>     "role_not_found": "The role you were assigned on this project is no longer available. Please contact the person who sent you the link and ask for a new one.",
> ```

This error might not be very useful for the user. The only way I see this as useful is if the user was expecting to have the community checker role, and then they can tell the original person that the share link said the role was incorrect, and the original person could check and see if community checking is enabled, or something like that. But just mentioning my thoughts.

**Review by Nateowami — COMMENTED** [review]
I have a bunch of suggested changes for this PR at https://github.com/sillsdev/web-xforge/pull/1876

> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1872#-:-NWhvfnP3fb9yoRLp-4G:b-zcluhk)* status: all files reviewed, 3 unresolved discussions (waiting on @nigel-wells)

**Review by nigel-wells — COMMENTED** [review]
Ah, thanks for the suggestions. Great idea moving away from the `Template` idea and putting it all in `Meta` as that cleans it up heaps and moves away from constantly bringing in the defaults. I'll bring across the relevant updates into this branch and then we can close your other one.

> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1872#-:-NWj7rKb7c8FixyVwaRA:bxqvrx0)* status: all files reviewed, 3 unresolved discussions (waiting on @nigel-wells)

**Comment by Nateowami** [comment]
@nigel-wells You should be able to just merge the other PR into this one.

**Comment by Nateowami** [comment]
@siltomato Would you be willing to take a look at the storybook file and see if there are any ways to improve it?

**Review by nigel-wells — COMMENTED** [review]
I've added some tweaks to this. The issue I was having with trying to `include` is the the string value you enter in the array is either the `name` and not the parameter. As I had added an additional `name` property it required entering that instead. Based on that I decided to make use of the description field instead.

> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1872#-:-NWk71n2-HkvaoKCWBdb:b-f34i95)* status: 4 of 7 files reviewed, 3 unresolved discussions (waiting on @RaymondLuong3)

___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/join/join.stories.ts` line 178 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/1872#-NWhpe7S3NCO7R7CPiHn:-NWjUaKt8mF0qeaGctAk:bb6un1j) ([raw file](https://github.com/sillsdev/web-xforge/blob/3daef993a89af552a73150f2abe6569b78c7ac62/src/SIL.XForge.Scripture/ClientApp/src/app/join/join.stories.ts#L178)):*
<details><summary><i>Previously, RaymondLuong3 (Raymond Luong) wrote…</i></summary><blockquote>

Add types to these objects where you can. Here and below.
</blockquote></details>

Done
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/join/join.stories.ts` line 197 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/1872#-NWht-KZ-WbKXIuM3QHs:-NWjUbq40f4dU7px46lZ:b-8u2dqn) ([raw file](https://github.com/sillsdev/web-xforge/blob/3daef993a89af552a73150f2abe6569b78c7ac62/src/SIL.XForge.Scripture/ClientApp/src/app/join/join.stories.ts#L197)):*
<details><summary><i>Previously, RaymondLuong3 (Raymond Luong) wrote…</i></summary><blockquote>

Are these tests? I don't see how it works. Maybe the play is implicit?
</blockquote></details>

No, not tests in this instances. Chromatic is used, however, to offer a "test" in the sense of did we break anything visually. Once these stories get accepted then they will be compared against in future PRs to ensure they haven't visual changed.
___
*[`src/SIL.XForge.Scripture/ClientApp/src/assets/i18n/non_checking_en.json` line 163 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/1872#-NWhqT_9Di-OBuqbJi7j:-NWjVFV20WaK5_MaQT3_:b-xgwb6b) ([raw file](https://github.com/sillsdev/web-xforge/blob/3daef993a89af552a73150f2abe6569b78c7ac62/src/SIL.XForge.Scripture/ClientApp/src/assets/i18n/non_checking_en.json#L163)):*
<details><summary><i>Previously, RaymondLuong3 (Raymond Luong) wrote…</i></summary><blockquote>

This error might not be very useful for the user. The only way I see this as useful is if the user was expecting to have the community checker role, and then they can tell the original person that the share link said the role was incorrect, and the original person could check and see if community checking is enabled, or something like that. But just mentioning my thoughts.
</blockquote></details>

Fair point raised. The scenario I see likely to happen is if an `anyone` link was shared

**Comment by siltomato** [comment]
Here's a minor improvement to the storybook file.  You could reduce code duplication by using the spread operator:
```typescript
export const JoiningWithValidKey: Story = {
  play: async ({ canvasElement }) => {
    const canvas = within(canvasElement);
    const joinButton: HTMLElement = canvas.getByRole('button');
    const nameInput: HTMLElement = canvas.getByRole('textbox');
    await userEvent.type(nameInput, 'Anonymous');
    await userEvent.click(joinButton);
  }
};

export const DialogExpiredKey: Story = {
  ...JoiningWithValidKey,
  args: { shareKey: ShareKeys.Expired },
}

export const DialogInvalidRole: Story = {
  ...JoiningWithValidKey,
  args: { shareKey: ShareKeys.InvalidRole },
}

export const DialogMaxUsersReached: Story = {
  ...JoiningWithValidKey,
  args: { shareKey: ShareKeys.MaxUsersReached },
}
```

**Review by nigel-wells — COMMENTED** [review]
Ah, good call! Done.

> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1872#-:-NWos5Sk6wPVSlU2-_B4:bqhsx3g)* status: 4 of 7 files reviewed, 3 unresolved discussions (waiting on @RaymondLuong3)

**Review by RaymondLuong3 — APPROVED** [review]
Nice! And I like that we set up a test environment equivalent in the story `meta` decorator property.

> Reviewed 3 of 3 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1872#-:-NWsS83O36Zh4Mlg5Htt:b-jlum2k)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @nigel-wells)

**Review by Nateowami — COMMENTED** [review]
> Reviewed 2 of 3 files at r6, 2 of 2 files at r9, 1 of 1 files at r11.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1872)* status: all files reviewed (commit messages unreviewed), all discussions resolved (waiting on @nigel-wells)

**Pull request merged**
