### PR TITLE
SF-1635 Open footnotes in dialog

### PR DESCRIPTION
**Pull request by nigel-wells**
- Created new dialog component for showing text notes
- Set background colors for end notes, cross-references, and end notes and made them clickable

SF Clickable Notes

---
This change is [Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1448)

### CODE REVIEW

**Review by Nateowami — CHANGES_REQUESTED** [review]
> Reviewed 7 of 11 files at r1.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1448)* status: 7 of 11 files reviewed, 3 unresolved discussions (waiting on @Nateowami and @nigel-wells)

___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/shared/utils.ts` line 72 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/1448#-N8eXvwN4h2s7jUPtmIZ:-N8eXvwO9t4FktoxT4ib:bxnyjt3) ([raw file](https://github.com/sillsdev/web-xforge/blob/c06a869c1386044e23c08662efef2fa16780f45d/src/SIL.XForge.Scripture/ClientApp/src/app/shared/utils.ts#L72)):*
> ```XML
>     target = target['offsetParent'] as EventTarget;
>   }
>   if (target['parentNode']['nodeName'] === nodeName) {
> ```

It looks like target is an `EventTarget` and is not guaranteed to have `offsetParent` or `parentNode`. Why should we think they won't possibly be undefined? Is there a reason we don't check for their existence? I think this would be more typesafe as something like:
``` ts
(target as any)?.parentNode?.nodeName === nodeName
```
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/shared/text/text-note-dialog/text-note-dialog.component.ts` line 6 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/1448#-N8eUdsA4IFqNRXCWGH4:-N8eUdsB43uBOGgkkoYz:b-4yaq4q) ([raw file](https://github.com/sillsdev/web-xforge/blob/c06a869c1386044e23c08662efef2fa16780f45d/src/SIL.XForge.Scripture/ClientApp/src/app/shared/text/text-note-dialog/text-note-dialog.component.ts#L6)):*
> ```XML
> 
> export interface NoteDialogData {
>   type: 'f' | 'fe' | 'x';
> ```

Could this be an enum? For example:
``` ts
export enum TextNoteType {
  footnote = 'f',
  endNote = 'fe',
  crossReference = 'x'
}
export interface NoteDialogData {
  type: TextNoteType;
}
```
(I had to look for a bit to even figure out what each of them were intended to be used for)

Alternatively you could do:
``` ts
export enum TextNoteType {
  footnote = 'footnote',
  endNote = 'end_note',
  crossReference = 'cross_reference'
}
```
And then `getType()` can be:
``` ts
get type(): string {
  return this.transloco.translate(this.data.type);
}
```
Maybe that's too magic? Or makes the data-style thing extra difficult?
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/shared/text/text-note-dialog/text-note-dialog.component.ts` line 12 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/1448#-N8eVHT22ghfqDpTEHe_:-N8eVHT22ghfqDpTEHea:bfwegab) ([raw file](https://github.com/sillsdev/web-xforge/blob/c06a869c1386044e23c08662efef2fa16780f45d/src/SIL.XForge.Scripture/ClientApp/src/app/shared/text/text-note-dialog/text-note-dialog.component.ts#L12)):*
> ```XML
> 
> @Component({
>   selector: 'app-text-note-dialog',
> ```

Would the selector every be used? Most of our dialogs don't have them.

**Review by nigel-wells — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1448)* status: 4 of 11 files reviewed, 3 unresolved discussions (waiting on @Nateowami and @nigel-wells)

___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/shared/utils.ts` line 72 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/1448#-N8eXvwN4h2s7jUPtmIZ:-N8v1XZL3bA1KzGHCnmO:beo6b4i) ([raw file](https://github.com/sillsdev/web-xforge/blob/c06a869c1386044e23c08662efef2fa16780f45d/src/SIL.XForge.Scripture/ClientApp/src/app/shared/utils.ts#L72)):*
<details><summary><i>Previously, Nateowami (Nathaniel Paulus) wrote…</i></summary><blockquote>

It looks like target is an `EventTarget` and is not guaranteed to have `offsetParent` or `parentNode`. Why should we think they won't possibly be undefined? Is there a reason we don't check for their existence? I think this would be more typesafe as something like:
``` ts
(target as any)?.parentNode?.nodeName === nodeName
```
</blockquote></details>

Reading the docs those values will always be available in the context of where we use them. That said, I've changed it just to be safe.
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/shared/text/text-note-dialog/text-note-dialog.component.ts` line 12 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/1448#-N8eVHT22ghfqDpTEHe_:-N8uzf3T9Hli6mmS1_z3:bnmial1) ([raw file](https://github.com/sillsdev/web-xforge/blob/c06a869c1386044e23c08662efef2fa16780f45d/src/SIL.XForge.Scripture/ClientApp/src/app/shared/text/text-note-dialog/text-note-dialog.component.ts#L12)):*
<details><summary><i>Previously, Nateowami (Nathaniel Paulus) wrote…</i></summary><blockquote>

Would the selector every be used? Most of our dialogs don't have them.
</blockquote></details>

Good point! Have removed.

**Review by nigel-wells — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1448)* status: 4 of 11 files reviewed, 3 unresolved discussions (waiting on @Nateowami)

___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/shared/text/text-note-dialog/text-note-dialog.component.ts` line 6 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/1448#-N8eUdsA4IFqNRXCWGH4:-N8v8dvT-UMq89WKXk1U:bntyrsw) ([raw file](https://github.com/sillsdev/web-xforge/blob/c06a869c1386044e23c08662efef2fa16780f45d/src/SIL.XForge.Scripture/ClientApp/src/app/shared/text/text-note-dialog/text-note-dialog.component.ts#L6)):*
<details><summary><i>Previously, Nateowami (Nathaniel Paulus) wrote…</i></summary><blockquote>

Could this be an enum? For example:
``` ts
export enum TextNoteType {
  footnote = 'f',
  endNote = 'fe',
  crossReference = 'x'
}
export interface NoteDialogData {
  type: TextNoteType;
}
```
(I had to look for a bit to even figure out what each of them were intended to be used for)

Alternatively you could do:
``` ts
export enum TextNoteType {
  footnote = 'footnote',
  endNote = 'end_note',
  crossReference = 'cross_reference'
}
```
And then `getType()` can be:
``` ts
get type(): string {
  return this.transloco.translate(this.data.type);
}
```
Maybe that's too magic? Or makes the data-style thing extra difficult?
</blockquote></details>

I've swapped out for the first enum. I believe the `f, fe, x` are coming from PT is that right Raymond?
I also re-worked the translate method - same, but different.

**Review by Nateowami — COMMENTED** [review]
> Reviewed 3 of 5 files at r2.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1448)* status: 7 of 11 files reviewed, all discussions resolved (waiting on @Nateowami)

**Review by Nateowami — CHANGES_REQUESTED** [review]
> Reviewed 2 of 11 files at r1, 2 of 5 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1448)* status: all files reviewed, 3 unresolved discussions (waiting on @nigel-wells)

___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/shared/text/text.component.spec.ts` line 2846 at r2](https://reviewable.io/reviews/sillsdev/web-xforge/1448#-N9-MqDd7pgVTDhzJam5:-N9-MqDd7pgVTDhzJam6:b-qsn1xi) ([raw file](https://github.com/sillsdev/web-xforge/blob/a5d6150a1800ccd2963bf636d993824bdd35b551/src/SIL.XForge.Scripture/ClientApp/src/app/shared/text/text.component.spec.ts#L2846)):*
> ```XML
>     const footNote = 'f';
>     const endNote = 'fe';
>     const crossReferenceNote = 'fe';
> ```

Is there a way to do this by referencing where they're defined, e.g. `TextNoteType.Footnote`?
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/shared/text/text.component.spec.ts` line 2852 at r2](https://reviewable.io/reviews/sillsdev/web-xforge/1448#-N9-Mkh11OygF1dKX6hV:-N9-Mkh11OygF1dKX6hW:b-v4v6vq) ([raw file](https://github.com/sillsdev/web-xforge/blob/a5d6150a1800ccd2963bf636d993824bdd35b551/src/SIL.XForge.Scripture/ClientApp/src/app/shared/text/text.component.spec.ts#L2852)):*
> ```XML
>       note!.click();
>     });
>     // env.fixture.detectChanges();
> ```

I think maybe this line was going to be deleted and got forgotten?
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/shared/text/text-note-dialog/text-note-dialog.component.spec.ts` line 88 at r2](https://reviewable.io/reviews/sillsdev/web-xforge/1448#-N9-KfK--DXAmwQ1A6jG:-N9-KfK--DXAmwQ1A6jH:bpu2ldj) ([raw file](https://github.com/sillsdev/web-xforge/blob/a5d6150a1800ccd2963bf636d993824bdd35b551/src/SIL.XForge.Scripture/ClientApp/src/app/shared/text/text-note-dialog/text-note-dialog.component.spec.ts#L88)):*
> ```XML
> 
>   get title(): string {
>     return this.overlayContainerElement.query(By.css('h1 span'))!.nativeElement.innerHTML.trim();
> ```

How about `textContent` instead of `innerHTML`?

**Review by nigel-wells — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1448)* status: 9 of 11 files reviewed, 3 unresolved discussions (waiting on @Nateowami)

___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/shared/text/text.component.spec.ts` line 2846 at r2](https://reviewable.io/reviews/sillsdev/web-xforge/1448#-N9-MqDd7pgVTDhzJam5:-N9-kIOf4EI79KVU6LxU:br9mznn) ([raw file](https://github.com/sillsdev/web-xforge/blob/a5d6150a1800ccd2963bf636d993824bdd35b551/src/SIL.XForge.Scripture/ClientApp/src/app/shared/text/text.component.spec.ts#L2846)):*
<details><summary><i>Previously, Nateowami (Nathaniel Paulus) wrote…</i></summary><blockquote>

Is there a way to do this by referencing where they're defined, e.g. `TextNoteType.Footnote`?
</blockquote></details>

Have changed to reference the new enum.
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/shared/text/text.component.spec.ts` line 2852 at r2](https://reviewable.io/reviews/sillsdev/web-xforge/1448#-N9-Mkh11OygF1dKX6hV:-N9-kHKZ0uPfj_afhjbg:bss4a2b) ([raw file](https://github.com/sillsdev/web-xforge/blob/a5d6150a1800ccd2963bf636d993824bdd35b551/src/SIL.XForge.Scripture/ClientApp/src/app/shared/text/text.component.spec.ts#L2852)):*
<details><summary><i>Previously, Nateowami (Nathaniel Paulus) wrote…</i></summary><blockquote>

I think maybe this line was going to be deleted and got forgotten?
</blockquote></details>

Removed.
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/shared/text/text-note-dialog/text-note-dialog.component.spec.ts` line 88 at r2](https://reviewable.io/reviews/sillsdev/web-xforge/1448#-N9-KfK--DXAmwQ1A6jG:-N9-lqza31ikTV_HocmG:b-896fix) ([raw file](https://github.com/sillsdev/web-xforge/blob/a5d6150a1800ccd2963bf636d993824bdd35b551/src/SIL.XForge.Scripture/ClientApp/src/app/shared/text/text-note-dialog/text-note-dialog.component.spec.ts#L88)):*
<details><summary><i>Previously, Nateowami (Nathaniel Paulus) wrote…</i></summary><blockquote>

How about `textContent` instead of `innerHTML`?
</blockquote></details>

Done.

**Review by Nateowami — APPROVED** [review]
:lgtm:

Just one comment, but non-blocking.

> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1448#-:-N9-yhjnESTq9vWNT78D:bacctyc)* status: all files reviewed, 1 unresolved discussion (waiting on @nigel-wells)

___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/shared/text/text-note-dialog/text-note-dialog.component.spec.ts` line 23 at r3](https://reviewable.io/reviews/sillsdev/web-xforge/1448#-N9-y_ks009tDfbI0EDv:-N9-y_ks009tDfbI0EDw:b-ysqnlb) ([raw file](https://github.com/sillsdev/web-xforge/blob/2c4b3e903197e6ac01017fcdae870afe8284e25e/src/SIL.XForge.Scripture/ClientApp/src/app/shared/text/text-note-dialog/text-note-dialog.component.spec.ts#L23)):*
> ```XML
>     const text = 'Footnote text';
>     env = new TestEnvironment({ type: TextNoteType.Footnote, text, isRightToLeft: false });
>     expect(env.title).toBe('text_note_dialog.footnote');
> ```

I'm guessing you tried to get this to show the actual text. I tried and failed. I'm not sure why it works in the other dialogs but not here.

**Review by nigel-wells — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1448)* status: all files reviewed, 1 unresolved discussion (waiting on @Nateowami)

___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/shared/text/text-note-dialog/text-note-dialog.component.spec.ts` line 23 at r3](https://reviewable.io/reviews/sillsdev/web-xforge/1448#-N9-y_ks009tDfbI0EDv:-N94yKdpBoKDroKTO4Kx:bf8eyu5) ([raw file](https://github.com/sillsdev/web-xforge/blob/2c4b3e903197e6ac01017fcdae870afe8284e25e/src/SIL.XForge.Scripture/ClientApp/src/app/shared/text/text-note-dialog/text-note-dialog.component.spec.ts#L23)):*
<details><summary><i>Previously, Nateowami (Nathaniel Paulus) wrote…</i></summary><blockquote>

I'm guessing you tried to get this to show the actual text. I tried and failed. I'm not sure why it works in the other dialogs but not here.
</blockquote></details>

I've tried. It is probably because I'm calling the `TranslocoService.translate()` method rather than it being defined in the HTML template file. I could mock the service and return something using `when` but it isn't really proving anything new in the test.

**Pull request merged**
