### PR TITLE
Make projectToDraftSources from ConfirmSourcesComponent a util function

### PR DESCRIPTION
**Pull request by Nateowami**
There are a lot of ways to misinterpret the configured draft sources, and the model may change in the future. Read the doc comment for rationale.

- - -
This change is [Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/2906)

### CODE REVIEW

**Review by RaymondLuong3 — APPROVED** [review]
Very nice! I have some suggestions but nothing blocking.

> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/2906#-:-ODvs3l19n691yE0GFkB:b2fyr8q)* status: all files reviewed, 2 unresolved discussions (waiting on @Nateowami and @pmachapman)

___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-utils.ts` line 25 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/2906#-ODvrfUz8GhGmJastWmH:-ODvrfUz8GhGmJastWmI:b-7qjmpv) ([raw file](https://github.com/sillsdev/web-xforge/blob/8aa203d11a3fefafcde7924dd92d9f2940817495/src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-utils.ts#L25)):*
> ```XML
>   trainingSources: [TranslateSource?, TranslateSource?];
>   trainingTargets: [SFProjectProfile];
>   draftingSources: [TranslateSource?];
> ```

You could add an interface for the return type for this function. Then it will be easier to declare a type from calling this function.



_Code quote:_
```XML
  trainingSources: [TranslateSource?, TranslateSource?];
  trainingTargets: [SFProjectProfile];
  draftingSources: [TranslateSource?];
```
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-utils.ts` line 46 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/2906#-ODvqtAp9A1EUGRZhz16:-ODvqtAp9A1EUGRZhz17:bka7k65) ([raw file](https://github.com/sillsdev/web-xforge/blob/8aa203d11a3fefafcde7924dd92d9f2940817495/src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-utils.ts#L46)):*
> ```XML
> 
>   if (draftConfig.additionalTrainingSourceEnabled && draftConfig.additionalTrainingSource != null) {
>     trainingSources.push(draftConfig.additionalTrainingSource!);
> ```

Nit: You don't need the bang here since you already have the null check.



_Code quote:_
```XML
draftConfig.additionalTrainingSource!
```

**Review by Nateowami — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/2906)* status: 0 of 2 files reviewed, 1 unresolved discussion (waiting on @pmachapman and @RaymondLuong3)

___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-utils.ts` line 25 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/2906#-ODvrfUz8GhGmJastWmH:-ODw26PU5SFLRu-OqECt:b-896fix) ([raw file](https://github.com/sillsdev/web-xforge/blob/8aa203d11a3fefafcde7924dd92d9f2940817495/src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-utils.ts#L25)):*
<details><summary><i>Previously, RaymondLuong3 (Raymond Luong) wrote…</i></summary><blockquote>

You could add an interface for the return type for this function. Then it will be easier to declare a type from calling this function.
</blockquote></details>

Done.
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-utils.ts` line 46 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/2906#-ODvqtAp9A1EUGRZhz16:-ODw23i2Ajb9HYL8MMi0:b6zrrkh) ([raw file](https://github.com/sillsdev/web-xforge/blob/8aa203d11a3fefafcde7924dd92d9f2940817495/src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-utils.ts#L46)):*
<details><summary><i>Previously, RaymondLuong3 (Raymond Luong) wrote…</i></summary><blockquote>

Nit: You don't need the bang here since you already have the null check.
</blockquote></details>

Good catch.

**Review by RaymondLuong3 — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/2906)* status: all files reviewed, 1 unresolved discussion (waiting on @Nateowami and @pmachapman)

___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-utils.ts` line 25 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/2906#-ODvrfUz8GhGmJastWmH:-ODwEqu_D-WdSqnPt-pW:b6cx447) ([raw file](https://github.com/sillsdev/web-xforge/blob/8aa203d11a3fefafcde7924dd92d9f2940817495/src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-utils.ts#L25)):*
<details><summary><i>Previously, Nateowami wrote…</i></summary><blockquote>

Done.
</blockquote></details>

DraftSources already exists in `draft-sources.service.ts`. To avoid confusion, let's change this to ActiveDraftingSources or ProjectDraftSources

**Review by Nateowami — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/2906)* status: 0 of 2 files reviewed, 1 unresolved discussion (waiting on @pmachapman and @RaymondLuong3)

___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-utils.ts` line 25 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/2906#-ODvrfUz8GhGmJastWmH:-ODx4ftv6kh--fzQX19g:bf2ur8t) ([raw file](https://github.com/sillsdev/web-xforge/blob/8aa203d11a3fefafcde7924dd92d9f2940817495/src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-utils.ts#L25)):*
<details><summary><i>Previously, RaymondLuong3 (Raymond Luong) wrote…</i></summary><blockquote>

DraftSources already exists in `draft-sources.service.ts`. To avoid confusion, let's change this to ActiveDraftingSources or ProjectDraftSources
</blockquote></details>

I was not aware of that service. Thanks for bringing it to my attention. Probably this utility function could be incorporated into that service in some way.

However, I'm not sure adding "Active" or "Project" actually correctly specifies the difference. What do you think about appending "AsArrays"?

**Review by RaymondLuong3 — APPROVED** [review]
> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/2906)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @pmachapman)

___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-utils.ts` line 25 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/2906#-ODvrfUz8GhGmJastWmH:-ODxJ3wg5_3kpVkhdGXq:bb1e85x) ([raw file](https://github.com/sillsdev/web-xforge/blob/8aa203d11a3fefafcde7924dd92d9f2940817495/src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-utils.ts#L25)):*
<details><summary><i>Previously, Nateowami wrote…</i></summary><blockquote>

I was not aware of that service. Thanks for bringing it to my attention. Probably this utility function could be incorporated into that service in some way.

However, I'm not sure adding "Active" or "Project" actually correctly specifies the difference. What do you think about appending "AsArrays"?
</blockquote></details>

Good point. I like it.

**Pull request merged**
