### PR TITLE
SF-2455 Upgrade to .NET 8.0

### PR DESCRIPTION
**Pull request by pmachapman**
This Pull Request updates Scripture Forge to .NET 8.0, and updates other dependencies.

**Summary**
 * Update C# projects from .NET .6.0 to .NET 8.0
 * Update workflow actions to latest versions
 * Update vagrantfile to use .NET 8.0 SDK
 * Update dockerfile to use .NET 8.0 jammy (Microsoft have not published focal images for .NET 8.0)
 * Update icu.net (ParatextData dependency) support to run on Ubuntu jammy and later and .Net 8.0
 * Updated all other dependencies except MongoDB and Hangfire (these can only be updated when SIL.Machine is removed - to be done at a later date)

**Deployment notes**
 * The file `~/.local/share/Paratext93/InternetSettings.xml` should be moved to `~/.local/share/Paratext95/InternetSettings.xml`
 * You can install the .NET 8.0 SDK by running `sudo apt-get update && sudo apt-get install -y dotnet-sdk-8.0`

**Testing Notes**
 * This should be tested by a developer, as it should provide no noticeable change to Scripture Forge.

- - -
This change is [Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/2292)

### CODE REVIEW

**Review by marksvc — COMMENTED** [review]
Thank you for your work on this!
I tested it on my workstation. I am able to Connect a project. Edits to the project from SF and PT sync back and forth.

I have just a tiny bit more to do, but am posting what I have so far. 

> Reviewed 33 of 34 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/2292#-:-NosYikv3EaJ-WXxEOCy:b-qi03l7)* status: 33 of 34 files reviewed, 1 unresolved discussion (waiting on @pmachapman)

___
*[`src/SIL.XForge/Models/Tokens.cs` line 20 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/2292#-Nos_lZhAH8vDybIwoFl:-NosQIVD6wT4r_9h4ID0:b-21qsfj) ([raw file](https://github.com/sillsdev/web-xforge/blob/d26ee4fc06d321023bd620fb392e0149e1c4142c/src/SIL.XForge/Models/Tokens.cs#L20)):*
> ```Smalltalk
>             }
>             var accessToken = new JwtSecurityToken(AccessToken);
>             return accessToken.Payload.IssuedAt;
> ```

Ah, good.
___
*[`src/SIL.XForge/Realtime/ExistingNodeJSProcess.cs` line 15 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/2292#-NosRfRQD1ULb9jeO37p:-NosRfRQD1ULb9jeO37q:bxif8ua) ([raw file](https://github.com/sillsdev/web-xforge/blob/d26ee4fc06d321023bd620fb392e0149e1c4142c/src/SIL.XForge/Realtime/ExistingNodeJSProcess.cs#L15)):*
> ```Smalltalk
>     {
>         GC.SuppressFinalize(this);
>         return ValueTask.CompletedTask;
> ```

Why is this better than `return;`?
___
*[`tools/CommentGenerator/CommentGenerator.csproj` line 12 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/2292#-NosURtZEYIxswpwDN04:-NosURt_9fdPe2-S_cWk:bpfa3d4) ([raw file](https://github.com/sillsdev/web-xforge/blob/d26ee4fc06d321023bd620fb392e0149e1c4142c/tools/CommentGenerator/CommentGenerator.csproj#L12)):*
> ```XML
>   <ItemGroup>
>     <PackageReference Include="NLipsum" Version="1.1.0" />
>     <PackageReference Include="ParatextData" Version="9.3.0.9" />
> ```

I noticed this ParatextData wasn't updated from 9.3. That may not matter at all; just pointing out something I noticed.

**Review by pmachapman — COMMENTED** [review]
No problem!

> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/2292#-:-Not8SCRDRnsFpAK7fJJ:blyphgc)* status: 31 of 35 files reviewed, 1 unresolved discussion (waiting on @marksvc)

___
*[`src/SIL.XForge/Realtime/ExistingNodeJSProcess.cs` line 15 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/2292#-NosRfRQD1ULb9jeO37p:-Not71tYEsO83eXGShwL:b-kbbpey) ([raw file](https://github.com/sillsdev/web-xforge/blob/d26ee4fc06d321023bd620fb392e0149e1c4142c/src/SIL.XForge/Realtime/ExistingNodeJSProcess.cs#L15)):*
<details><summary><i>Previously, marksvc wrote…</i></summary><blockquote>

Why is this better than `return;`?
</blockquote></details>

Because the interface this method implements expects a method that runs asynchronous code, we return `ValueTask.CompletedTask` to say we ran synchronous code. If there was code that `await`ed in the method we could just say `return;`.
___
*[`tools/CommentGenerator/CommentGenerator.csproj` line 12 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/2292#-NosURtZEYIxswpwDN04:-Not7srf52P49jIAY1lv:boyexb3) ([raw file](https://github.com/sillsdev/web-xforge/blob/d26ee4fc06d321023bd620fb392e0149e1c4142c/tools/CommentGenerator/CommentGenerator.csproj#L12)):*
<details><summary><i>Previously, marksvc wrote…</i></summary><blockquote>

I noticed this ParatextData wasn't updated from 9.3. That may not matter at all; just pointing out something I noticed.
</blockquote></details>

Done. Thanks!

**Review by marksvc — CHANGES_REQUESTED** [review]
> Reviewed 1 of 34 files at r1, 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/2292)* status: all files reviewed, 1 unresolved discussion (waiting on @pmachapman)

___
*[`src/SIL.XForge/Realtime/ExistingNodeJSProcessFactory.cs` line 10 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/2292#-NoxEffm7CtPV6eax0tS:-NoxEffm7CtPV6eax0tT:b-152apb) ([raw file](https://github.com/sillsdev/web-xforge/blob/d26ee4fc06d321023bd620fb392e0149e1c4142c/src/SIL.XForge/Realtime/ExistingNodeJSProcessFactory.cs#L10)):*
> ```Smalltalk
>     public INodeJSProcess Create(string serverScript) => new ExistingNodeJSProcess();
> 
>     public INodeJSProcess Create(string serverScript, EventHandler exitedEventHandler) => new ExistingNodeJSProcess();
> ```

Hmm. So I've been looking at our code and [Jering](https://github.com/JeringTech/Javascript.NodeJS/blob/5999180f381cb41405f47eb31015be27dfb7facb/src/NodeJS/NodeJSServiceImplementations/OutOfProcess/NodeJSProcessFactory.cs#L91) and wondering if we should do anything with the exitedEventHandler. Can you comment on this?

**Review by pmachapman — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/2292)* status: all files reviewed, 1 unresolved discussion (waiting on @marksvc)

___
*[`src/SIL.XForge/Realtime/ExistingNodeJSProcessFactory.cs` line 10 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/2292#-NoxEffm7CtPV6eax0tS:-NpGJZc0Aq-YyKUHQEpH:b26iipb) ([raw file](https://github.com/sillsdev/web-xforge/blob/d26ee4fc06d321023bd620fb392e0149e1c4142c/src/SIL.XForge/Realtime/ExistingNodeJSProcessFactory.cs#L10)):*
<details><summary><i>Previously, marksvc wrote…</i></summary><blockquote>

Hmm. So I've been looking at our code and [Jering](https://github.com/JeringTech/Javascript.NodeJS/blob/5999180f381cb41405f47eb31015be27dfb7facb/src/NodeJS/NodeJSServiceImplementations/OutOfProcess/NodeJSProcessFactory.cs#L91) and wondering if we should do anything with the exitedEventHandler. Can you comment on this?
</blockquote></details>

As I understand it, this was added to allow implementations to clean up resources dependent on the NodeJS process.

We might be able to use this to restart the NodeJS service if it crashes? We would have to be careful in our implementation of it though, to check whether or not the parent process is being exited or shutdown.

**Review by marksvc — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/2292#-:-NpL8GYp01aNHGQ9z0gk:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @pmachapman)

**Comment by marksvc** [comment]
I didn't merge it in case there are announcements or a timing that you want to do the move to .NET 8.0.

**Review by marksvc — APPROVED** [review]
> Reviewed 8 of 8 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/2292)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @pmachapman)

**Comment by Nateowami** [comment]
@pmachapman Is there anything we need to do to make sure all developers and testers have .NET 8 on their machines?

**Comment by pmachapman** [comment]
> @pmachapman Is there anything we need to do to make sure all developers and testers have .NET 8 on their machines?

Just the two actions in the deployment notes:

* The file `~/.local/share/Paratext93/InternetSettings.xml` should be moved (or copied on a dev/test machine) to `~/.local/share/Paratext95/InternetSettings.xml`
* Install the .NET 8.0 SDK by running `sudo apt-get update && sudo apt-get install -y dotnet-sdk-8.0`

**Comment by Nateowami** [comment]
Sorry; should have actually read. Let's make sure all developers and testers have successfully installed .NET 8. Commands are:
- `mkdir ~/.local/share/Paratext95`
- `cp ~/.local/share/Paratext93/InternetSettings.xml ~/.local/share/Paratext95/InternetSettings.xml`
- `sudo apt-get update && sudo apt-get install -y dotnet-sdk-8.0`

I thought `cp` might be able to create directories, but turns out `mkdir` is needed. Are we close enough to merging that we should have everyone run these?

**Comment by pmachapman** [comment]
> Are we close enough to merging that we should have everyone run these?

Yes. I will make the post on Slack.

**Review by marksvc — APPROVED** [review]
> Reviewed 5 of 5 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/2292)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @pmachapman)

**Pull request merged**
