### PR TITLE
SF-3063 Specify updated learning rate for Serval

### PR DESCRIPTION
**Pull request by pmachapman**
This PR adds support for the updated learning rate for Serval.

I have placed this behind a feature flag so we may disable it when Serval implements this rate as the default, or if the new rate proves problematic.

- - -
This change is [Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/2829)

### CODE REVIEW

**Review by kylebuss — CHANGES_REQUESTED** [review]
Thanks for working on this and good idea making this a feature flag. 

> Reviewed 6 of 6 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/2829#-:-OASsXlq7U_oYHl4V-En:b8lvmt8)* status: all files reviewed, 1 unresolved discussion (waiting on @pmachapman)

___
*[`src/SIL.XForge.Scripture/Services/MachineProjectService.cs` line 1192 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/2829#-OASrH8b9lOCAwUe5EHJ:-OASrH8b9lOCAwUe5EHK:bub7pew) ([raw file](https://github.com/sillsdev/web-xforge/blob/8fd5b2592f30c1fbdde507645e15ff71ae8b32aa/src/SIL.XForge.Scripture/Services/MachineProjectService.cs#L1192)):*
> ```Smalltalk
>             servalConfig = JObject.Parse(draftConfig.ServalConfig);
>         }
>         else if (await featureManager.IsEnabledAsync(FeatureFlags.UpdatedLearningRateForServal))
> ```

Should this be the first check and we only use the `draftConfig.ServalConfig` if the feature flag is not enabled?



_Code quote:_
```Smalltalk
else if (await featureManager.IsEnabledAsync(FeatureFlags.UpdatedLearningRateForServal))
```

**Review by pmachapman — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/2829)* status: all files reviewed, 1 unresolved discussion (waiting on @kylebuss)

___
*[`src/SIL.XForge.Scripture/Services/MachineProjectService.cs` line 1192 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/2829#-OASrH8b9lOCAwUe5EHJ:-OATVUOeELSOz_9KJ4yY:bcr6ynr) ([raw file](https://github.com/sillsdev/web-xforge/blob/8fd5b2592f30c1fbdde507645e15ff71ae8b32aa/src/SIL.XForge.Scripture/Services/MachineProjectService.cs#L1192)):*
<details><summary><i>Previously, kylebuss (Kyle Buss) wrote…</i></summary><blockquote>

Should this be the first check and we only use the `draftConfig.ServalConfig` if the feature flag is not enabled?
</blockquote></details>

No, because this value can be overridden in the Project's Settings. If it is overridden, we want the override to take precedence.

**Review by ddaspit — APPROVED** [review]
:lgtm:

> Reviewed 6 of 6 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/2829#-:-OATdded2vdcepmtgc2w:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @kylebuss)

**Review by kylebuss — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/2829#-:-OATiEK09zb-h1HO19O6:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @pmachapman)

___
*[`src/SIL.XForge.Scripture/Services/MachineProjectService.cs` line 1192 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/2829#-OASrH8b9lOCAwUe5EHJ:-OATgii41UBqfcodIAg8:b-6gvai8) ([raw file](https://github.com/sillsdev/web-xforge/blob/8fd5b2592f30c1fbdde507645e15ff71ae8b32aa/src/SIL.XForge.Scripture/Services/MachineProjectService.cs#L1192)):*
<details><summary><i>Previously, pmachapman (Peter Chapman) wrote…</i></summary><blockquote>

No, because this value can be overridden in the Project's Settings. If it is overridden, we want the override to take precedence.
</blockquote></details>

Aw, that's what the 'Serval Config' in the project settings is for. Makes sense that it would take precedence.

**Pull request merged**
