### PR TITLE
SF-1472 Bump version number on indexeddb

### PR DESCRIPTION
**Pull request by RaymondLuong3**
This change is [Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1280)

### CODE REVIEW

**Review by Nateowami — COMMENTED** [review]
Should this not be part of a commit that introduces a new migration?

> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1280#-:-MywtL4ICi58H0XLJbhB:b-1le1x)* status: 0 of 4 files reviewed, all discussions resolved

**Review by RaymondLuong3 — COMMENTED** [review]
This actually affects the entire notes features since we introduce the new note_thread collection in the indexedDB offline store. It's not really related to the migration of sync users.

> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1280#-:-MywzACM7yYKQDt8E7Fy:b-c24r6a)* status: 0 of 4 files reviewed, all discussions resolved

**Review by marksvc — APPROVED** [review]
I guess ideally this would have been put on a specific commit that caused the meaningful difference in the indexeddb, but branch develop is kind of like a big feature branch right now, so this change is like saying the whole branch bumps up the indexeddb version.

> Reviewed 1 of 4 files at r1.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1280#-:-MzGVlHo3jYqaw3HpMsD:b-7k51ng)* status: 1 of 4 files reviewed, 1 unresolved discussion (waiting on @marksvc and @RaymondLuong3)

___
*[src/SIL.XForge.Scripture/ClientApp/src/environments/environment.prod.ts, line 20 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/1280#-MzGUpJ30u1HqWkSgB0o:-MzGUpJ30u1HqWkSgB0p:bgxyi8) ([raw file](https://github.com/sillsdev/web-xforge/blob/ad4dcc80e4e5ec9639a1d54d95d15eec699b1779/src/SIL.XForge.Scripture/ClientApp/src/environments/environment.prod.ts#L20)):*
> ```XML
>   authDomain: 'login.languagetechnology.org',
>   authClientId: 'tY2wXn40fsL5VsPM4uIHNtU6ZUEXGeFn',
>   offlineDBVersion: 5
> ```

And this is because 
- the SFProject docs are now expected to have a new field called something like ParatextUsers, and 
- there is now a new 'doc' of SFProjectProfile.
And this change helps us state that there is such an important difference in the DB. 

Is that so?


Oh. I see you say in a comment that it's about the note_thread collection. Hmm.



_Code quote:_
```XML
DBVersion: 5
```

**Review by RaymondLuong3 — COMMENTED** [review]
That is an accurate way of looking at it. The develop branch is just one large feature branch.

> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1280#-:-MzH24NL91k_wmgsD_Dl:b-lm69jr)* status: 1 of 4 files reviewed, 1 unresolved discussion (waiting on @marksvc)

___
*[src/SIL.XForge.Scripture/ClientApp/src/environments/environment.prod.ts, line 20 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/1280#-MzGUpJ30u1HqWkSgB0o:-MzH2ApS3T5_Z-X292Sc:b-1z6wnu) ([raw file](https://github.com/sillsdev/web-xforge/blob/0a716832c7091fc5733e4c3c7c305ee148d0a41c/src/SIL.XForge.Scripture/ClientApp/src/environments/environment.prod.ts#L20)):*
<details><summary><i>Previously, marksvc wrote…</i></summary><blockquote>

And this is because 
- the SFProject docs are now expected to have a new field called something like ParatextUsers, and 
- there is now a new 'doc' of SFProjectProfile.
And this change helps us state that there is such an important difference in the DB. 

Is that so?


Oh. I see you say in a comment that it's about the note_thread collection. Hmm.
</blockquote></details>

That's right, we need to let the browsers know that when we start serving the updated app, in order to hit indexedDB, it needs to be updated to include the new note_thread collection, otherwise we get a "store does not exist" error.

**Review by marksvc — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1280)* status: 1 of 4 files reviewed, all discussions resolved (waiting on @marksvc)

___
*[src/SIL.XForge.Scripture/ClientApp/src/environments/environment.prod.ts, line 20 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/1280#-MzGUpJ30u1HqWkSgB0o:-MzH3n9U8VWRpymvqVvV:brf6ss2) ([raw file](https://github.com/sillsdev/web-xforge/blob/0a716832c7091fc5733e4c3c7c305ee148d0a41c/src/SIL.XForge.Scripture/ClientApp/src/environments/environment.prod.ts#L20)):*
<details><summary><i>Previously, RaymondLuong3 (Raymond Luong) wrote…</i></summary><blockquote>

That's right, we need to let the browsers know that when we start serving the updated app, in order to hit indexedDB, it needs to be updated to include the new note_thread collection, otherwise we get a "store does not exist" error.
</blockquote></details>

Okay. So to what extent does it relate to the changes to SFProject and SFProjectProfile?

**Review by marksvc — APPROVED** [review]
> Reviewed 3 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1280)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @RaymondLuong3)

**Pull request merged**
