### PR TITLE
SF-2762 Prompt user to log in again when refresh token is rejected

### PR DESCRIPTION
**Pull request by pmachapman**
This PR will prompt the user to log out, then log back in again if their Paratext Refresh Token is invalid.

Due to the need to modify the database to recreate the error state that this PR resolves, testing should be performed by a developer.

**Changes in PR**

 * C# Backend: Check for for PT Archives/Registry access before starting sync.
 * C# Backend: Return Unauthorized errors for Token refresh errors.
 * Angular Frontend: Display prompt to log out on Sync screen.
 * Angular Frontend: Display prompt to log out on Connect Project screen.
 * Angular Frontend: Display prompt to logout/login on Settings screen.
 * Angular Frontend: Display prompt to log out when retraining on Translate Overview screen.
 * Angular Frontend: Correct verb use of the word logout to log out.
 * Angular Frontend: Display prompt to log out on Draft Generation screen.

- - -
This change is [Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/2506)

### CODE REVIEW

**Review by marksvc — CHANGES_REQUESTED** [review]
Going to test next.

> Reviewed 8 of 8 files at r1, 6 of 6 files at r2, 10 of 10 files at r3, 3 of 3 files at r4, 2 of 2 files at r5, 2 of 2 files at r6, 7 of 7 files at r7, 2 of 27 files at r8, 4 of 6 files at r9, 9 of 10 files at r10, 1 of 3 files at r11, 7 of 7 files at r14, 11 of 12 files at r17, 1 of 1 files at r18, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/2506#-:-O-IR78-Ed_v4LZbZfh0:b-vuruzd)* status: all files reviewed, 6 unresolved discussions (waiting on @pmachapman)

___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/sync/sync.component.ts` line 172 at r4](https://reviewable.io/reviews/sillsdev/web-xforge/2506#-O-8TNMj1_SxXeetYoeO:-O-8TNMj1_SxXeetYoeP:b-fiq80o) ([raw file](https://github.com/sillsdev/web-xforge/blob/e7e16c44c54dfcf60c6e40fbe3208ec17f4a012b/src/SIL.XForge.Scripture/ClientApp/src/app/sync/sync.component.ts#L172)):*
> ```XML
>     }
>     this._syncActive = true;
>     this.projectService.onlineSync(this.projectDoc.id).catch((error: any) => {
> ```

Okay. Did you have a particular reason to use .catch() and .then() instead of await?
(in other words, something like
```ts
try {
  await this.projectService.onlineSync(this.projectDoc.id);
} catch (error) {
  ...
  const logOut = await this.dialogService.confirm('...');
  if (logOut) this.authService.logOut();
  ...
}
```
)
It's okay to leave it as is; I'm just surprised when I see .catch() and .then().
___
*[`src/SIL.XForge.Scripture/ClientApp/src/assets/i18n/non_checking_en.json` line 518 at r4](https://reviewable.io/reviews/sillsdev/web-xforge/2506#-O-8UWYo-GNUh3mTDhVW:-O-8UWYo-GNUh3mTDhVX:b-336o3w) ([raw file](https://github.com/sillsdev/web-xforge/blob/e7e16c44c54dfcf60c6e40fbe3208ec17f4a012b/src/SIL.XForge.Scripture/ClientApp/src/assets/i18n/non_checking_en.json#L518)):*
To nit pick the wording :), what do you think about lower-casing "User Credentials", and adjusting the second sentence. Such as:
> Your Paratext user credentials have expired. Please log out and log back in again. Then Synchronize your project.
or
> Your Paratext user credentials have expired. Please log out, log back in, and Synchronize your project.
___
*[`src/SIL.XForge.Scripture/ClientApp/src/assets/i18n/non_checking_pt_BR.json` line 514 at r3](https://reviewable.io/reviews/sillsdev/web-xforge/2506#-O-8OWjB3Mn3Y6-1pHmC:-O-8OWjB3Mn3Y6-1pHmD:bomkl1z) ([raw file](https://github.com/sillsdev/web-xforge/blob/07c7b0eb7f1e09f32c522731888f44d771c36d4b/src/SIL.XForge.Scripture/ClientApp/src/assets/i18n/non_checking_pt_BR.json#L514)):*
> ```JSON
>     "users": "Usuários"
>   },
>   "warnings": {
> ```

You speak so many languages!
___
*[`src/SIL.XForge.Scripture/ClientApp/src/xforge-common/auth.service.spec.ts` line 705 at r18](https://reviewable.io/reviews/sillsdev/web-xforge/2506#-O-IMFhd9xLAbnyLYcAp:-O-IMFhj7PaFz4oaOmwc:b53bnxa) ([raw file](https://github.com/sillsdev/web-xforge/blob/b573d18e7e7b00ec4e5f87b9eab1b857acba78a5/src/SIL.XForge.Scripture/ClientApp/src/xforge-common/auth.service.spec.ts#L705)):*
> ```XML
>     verify(mockedDialogService.confirm(anything(), anything())).once();
>     verify(mockedWebAuth.logout(anything())).once();
>     expect(capture(mockedWebAuth.logout).last()).toBeDefined();
> ```

What is the significance of this expect?
___
*[`src/SIL.XForge.Scripture/Services/SFProjectService.cs` line 502 at r2](https://reviewable.io/reviews/sillsdev/web-xforge/2506#-O-8Kgy08AEeqHU3H8Kl:-O-8Kgy08AEeqHU3H8Km:byw4lzu) ([raw file](https://github.com/sillsdev/web-xforge/blob/4a6aa9b807071c3143b1962b206fb82936c3d372/src/SIL.XForge.Scripture/Services/SFProjectService.cs#L502)):*
> ```Smalltalk
>         Attempt<UserSecret> userSecretAttempt = await _userSecrets.TryGetAsync(curUserId);
>         if (!userSecretAttempt.TryResult(out UserSecret userSecret))
>             throw new DataNotFoundException("The user does not exist.");
> ```

Oh, isn't it just that the user's secrets don't exist? I suppose it's not too bad if we say of the accessing user that they don't exist. But it might be more accurate to say something like "The user secrets could not be found" or "Private user information was not found". ?
___
*[`src/SIL.XForge.Scripture/Services/SFProjectService.cs` line 514 at r2](https://reviewable.io/reviews/sillsdev/web-xforge/2506#-O-8LxqUEoY2xU-gWjRU:-O-8LxqUEoY2xU-gWjRV:b-bnrqkl) ([raw file](https://github.com/sillsdev/web-xforge/blob/4a6aa9b807071c3143b1962b206fb82936c3d372/src/SIL.XForge.Scripture/Services/SFProjectService.cs#L514)):*
> ```Smalltalk
> 
>         // Queue the sync
>         await _syncService.SyncAsync(new SyncConfig { ProjectId = projectId, UserId = curUserId });
> ```

Nice, before even queuing.
___
*[`test/SIL.XForge.Scripture.Tests/Services/ParatextSyncRunnerTests.cs` line 626 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/2506#-O-8H7vAAmeOwpTf0ikQ:-O-8H7vAAmeOwpTf0ikR:b-obekz1) ([raw file](https://github.com/sillsdev/web-xforge/blob/82623f1e03b1046617a06f3043761b9163235f5a/test/SIL.XForge.Scripture.Tests/Services/ParatextSyncRunnerTests.cs#L626)):*
> ```Smalltalk
>         )
>             .Throws<UnauthorizedAccessException>();
>         env.ParatextService.GetProjectRolesAsync(Arg.Any<UserSecret>(), Arg.Any<SFProject>(), CancellationToken.None)
> ```

Why is it that you are setting both GetParatextUsernameMappingAsync and GetProjectRolesAsync to throw, rather than just one of them? 
___
*[`test/SIL.XForge.Scripture.Tests/Services/SFProjectServiceTests.cs` line 3689 at r2](https://reviewable.io/reviews/sillsdev/web-xforge/2506#-O-8Nj_LAYilj65ybXHx:-O-8Nj_LAYilj65ybXHy:b-m4fnjh) ([raw file](https://github.com/sillsdev/web-xforge/blob/4a6aa9b807071c3143b1962b206fb82936c3d372/test/SIL.XForge.Scripture.Tests/Services/SFProjectServiceTests.cs#L3689)):*
> ```Smalltalk
>             );
>             RealtimeService.AddRepository(
>                 "note_threads",
> ```

Hmm. That's not comforting that our test data here was using the wrong repository name. :/

**Review by marksvc — CHANGES_REQUESTED** [review]
I have tested and it is good.

> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/2506#-:-O-IcgjzEzlXQW-uGKlq:bgrlrg4)* status: all files reviewed, 6 unresolved discussions (waiting on @pmachapman)

___
*[`src/SIL.XForge.Scripture/ClientApp/src/assets/i18n/non_checking_en.json` line 518 at r4](https://reviewable.io/reviews/sillsdev/web-xforge/2506#-O-8UWYo-GNUh3mTDhVW:-O-IbdRU6ObhAvbjxrME:bz27zem) ([raw file](https://github.com/sillsdev/web-xforge/blob/e7e16c44c54dfcf60c6e40fbe3208ec17f4a012b/src/SIL.XForge.Scripture/ClientApp/src/assets/i18n/non_checking_en.json#L518)):*
<details><summary><i>Previously, marksvc wrote…</i></summary><blockquote>

To nit pick the wording :), what do you think about lower-casing "User Credentials", and adjusting the second sentence. Such as:
> Your Paratext user credentials have expired. Please log out and log back in again. Then Synchronize your project.
or
> Your Paratext user credentials have expired. Please log out, log back in, and Synchronize your project.
</blockquote></details>

Hmm. Also, in some situations, I'm not sure the user needs to Synchronize their project. For example, when I go to the Settings page and get the dialog, don't I just need to log out and log back in again, but I don't need to Synchronize my project, right?

**Review by marksvc — APPROVED** [review]
Approving to speed it to the server to deal with a problem at hand. We can continue to discuss and adjust the PR after the fact.

> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/2506#-:-O-Ie9wEEFlgxo_PbnYb:b-mlp6h4)* status: all files reviewed, 6 unresolved discussions (waiting on @pmachapman)

**Review by pmachapman — COMMENTED** [review]
Even though the PR is merged, I will continue the conversation. A follow PR will be on its way later.

> Dismissed @marksvc from a discussion.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/2506#-:-O-XfJDF5iAb3vgUPfAU:b-d3ijlu)* status: 39 of 40 files reviewed, 5 unresolved discussions

___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/sync/sync.component.ts` line 172 at r4](https://reviewable.io/reviews/sillsdev/web-xforge/2506#-O-8TNMj1_SxXeetYoeO:-O-XaNu4DomdpNIEIHfs:bm972uq) ([raw file](https://github.com/sillsdev/web-xforge/blob/e7e16c44c54dfcf60c6e40fbe3208ec17f4a012b/src/SIL.XForge.Scripture/ClientApp/src/app/sync/sync.component.ts#L172)):*
<details><summary><i>Previously, marksvc wrote…</i></summary><blockquote>

Okay. Did you have a particular reason to use .catch() and .then() instead of await?
(in other words, something like
```ts
try {
  await this.projectService.onlineSync(this.projectDoc.id);
} catch (error) {
  ...
  const logOut = await this.dialogService.confirm('...');
  if (logOut) this.authService.logOut();
  ...
}
```
)
It's okay to leave it as is; I'm just surprised when I see .catch() and .then().
</blockquote></details>

I only did this so I didn't have to change the `syncProject()` function to a `Promise<void>`.
___
*[`src/SIL.XForge.Scripture/ClientApp/src/assets/i18n/non_checking_en.json` line 518 at r4](https://reviewable.io/reviews/sillsdev/web-xforge/2506#-O-8UWYo-GNUh3mTDhVW:-O-XafGVAkq8QZlFhlK-:bnammlw) ([raw file](https://github.com/sillsdev/web-xforge/blob/e7e16c44c54dfcf60c6e40fbe3208ec17f4a012b/src/SIL.XForge.Scripture/ClientApp/src/assets/i18n/non_checking_en.json#L518)):*
<details><summary><i>Previously, marksvc wrote…</i></summary><blockquote>

Hmm. Also, in some situations, I'm not sure the user needs to Synchronize their project. For example, when I go to the Settings page and get the dialog, don't I just need to log out and log back in again, but I don't need to Synchronize my project, right?
</blockquote></details>

You are right for both counts. I will fix this in the follow up PR.
___
*[`src/SIL.XForge.Scripture/ClientApp/src/assets/i18n/non_checking_pt_BR.json` line 514 at r3](https://reviewable.io/reviews/sillsdev/web-xforge/2506#-O-8OWjB3Mn3Y6-1pHmC:-O-XaygqC2vN3WTg4drY:b6axlem) ([raw file](https://github.com/sillsdev/web-xforge/blob/07c7b0eb7f1e09f32c522731888f44d771c36d4b/src/SIL.XForge.Scripture/ClientApp/src/assets/i18n/non_checking_pt_BR.json#L514)):*
<details><summary><i>Previously, marksvc wrote…</i></summary><blockquote>

You speak so many languages!
</blockquote></details>

I was unsure whether the best solution was to rename the word when in English in the localization files, or just delete the translation string from these affected files.

I checked the localizations which were in their target language (French, Spanish, and Bahasa Indonesia), and these appeared to use the correct phrasing based on my very primitive understanding of them, so I didn't see a need to correct or remove them.
___
*[`src/SIL.XForge.Scripture/ClientApp/src/xforge-common/auth.service.spec.ts` line 705 at r18](https://reviewable.io/reviews/sillsdev/web-xforge/2506#-O-IMFhd9xLAbnyLYcAp:-O-Xc6nl3pP5tqtBz7P2:bdb6as0) ([raw file](https://github.com/sillsdev/web-xforge/blob/b573d18e7e7b00ec4e5f87b9eab1b857acba78a5/src/SIL.XForge.Scripture/ClientApp/src/xforge-common/auth.service.spec.ts#L705)):*
<details><summary><i>Previously, marksvc wrote…</i></summary><blockquote>

What is the significance of this expect?
</blockquote></details>

I mostly wanted an `expect()` so that I didn't get the "has no expectations." error, and I am not a fan of `expect().nothing();`. This just gets the last arguments passed to logout, which I have verifying they were defined.
___
*[`src/SIL.XForge.Scripture/Services/SFProjectService.cs` line 502 at r2](https://reviewable.io/reviews/sillsdev/web-xforge/2506#-O-8Kgy08AEeqHU3H8Kl:-O-Xe66p4eoWKIU3WiBv:bvqn7ny) ([raw file](https://github.com/sillsdev/web-xforge/blob/4a6aa9b807071c3143b1962b206fb82936c3d372/src/SIL.XForge.Scripture/Services/SFProjectService.cs#L502)):*
<details><summary><i>Previously, marksvc wrote…</i></summary><blockquote>

Oh, isn't it just that the user's secrets don't exist? I suppose it's not too bad if we say of the accessing user that they don't exist. But it might be more accurate to say something like "The user secrets could not be found" or "Private user information was not found". ?
</blockquote></details>

I thought of that, but thought it might be a leaking of data? Maybe I am being too paranoid.
___
*[`test/SIL.XForge.Scripture.Tests/Services/ParatextSyncRunnerTests.cs` line 626 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/2506#-O-8H7vAAmeOwpTf0ikQ:-O-XeldKAiJTI5WpPyB3:byid0bn) ([raw file](https://github.com/sillsdev/web-xforge/blob/82623f1e03b1046617a06f3043761b9163235f5a/test/SIL.XForge.Scripture.Tests/Services/ParatextSyncRunnerTests.cs#L626)):*
<details><summary><i>Previously, marksvc wrote…</i></summary><blockquote>

Why is it that you are setting both GetParatextUsernameMappingAsync and GetProjectRolesAsync to throw, rather than just one of them?
</blockquote></details>

I am not sure. On reflection, it is superfluous.

That said, I am planning to combine these two methods, as both call the same Registry API endpoint, so this will be cleaned up in the coming week or so.

**Review by marksvc — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/2506)* status: 39 of 40 files reviewed, 1 unresolved discussion

___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/sync/sync.component.ts` line 172 at r4](https://reviewable.io/reviews/sillsdev/web-xforge/2506#-O-8TNMj1_SxXeetYoeO:-O-bYhqz0p6wVuPaTDrE:b-jwkuic) ([raw file](https://github.com/sillsdev/web-xforge/blob/e7e16c44c54dfcf60c6e40fbe3208ec17f4a012b/src/SIL.XForge.Scripture/ClientApp/src/app/sync/sync.component.ts#L172)):*
<details><summary><i>Previously, pmachapman (Peter Chapman) wrote…</i></summary><blockquote>

I only did this so I didn't have to change the `syncProject()` function to a `Promise<void>`.
</blockquote></details>

Ahh, right, that makes sense. 
___
*[`src/SIL.XForge.Scripture/ClientApp/src/assets/i18n/non_checking_pt_BR.json` line 514 at r3](https://reviewable.io/reviews/sillsdev/web-xforge/2506#-O-8OWjB3Mn3Y6-1pHmC:-O-bZQ8z3DFG4RsiWiGn:b8qbkll) ([raw file](https://github.com/sillsdev/web-xforge/blob/07c7b0eb7f1e09f32c522731888f44d771c36d4b/src/SIL.XForge.Scripture/ClientApp/src/assets/i18n/non_checking_pt_BR.json#L514)):*
<details><summary><i>Previously, pmachapman (Peter Chapman) wrote…</i></summary><blockquote>

I was unsure whether the best solution was to rename the word when in English in the localization files, or just delete the translation string from these affected files.

I checked the localizations which were in their target language (French, Spanish, and Bahasa Indonesia), and these appeared to use the correct phrasing based on my very primitive understanding of them, so I didn't see a need to correct or remove them.
</blockquote></details>

I'm just joking. Though I only modify the _en.json files and expect/assume the files for other languages will receive the updates.
___
*[`src/SIL.XForge.Scripture/ClientApp/src/xforge-common/auth.service.spec.ts` line 705 at r18](https://reviewable.io/reviews/sillsdev/web-xforge/2506#-O-IMFhd9xLAbnyLYcAp:-O-bU9AeB7rEbbH_Mpvw:b78kfev) ([raw file](https://github.com/sillsdev/web-xforge/blob/b573d18e7e7b00ec4e5f87b9eab1b857acba78a5/src/SIL.XForge.Scripture/ClientApp/src/xforge-common/auth.service.spec.ts#L705)):*
<details><summary><i>Previously, pmachapman (Peter Chapman) wrote…</i></summary><blockquote>

I mostly wanted an `expect()` so that I didn't get the "has no expectations." error, and I am not a fan of `expect().nothing();`. This just gets the last arguments passed to logout, which I have verifying they were defined.
</blockquote></details>

Okay, that makes sense.
___
*[`src/SIL.XForge.Scripture/Services/SFProjectService.cs` line 502 at r2](https://reviewable.io/reviews/sillsdev/web-xforge/2506#-O-8Kgy08AEeqHU3H8Kl:-O-bXoVh4Cpkogri7OH-:bx5s3m0) ([raw file](https://github.com/sillsdev/web-xforge/blob/4a6aa9b807071c3143b1962b206fb82936c3d372/src/SIL.XForge.Scripture/Services/SFProjectService.cs#L502)):*
<details><summary><i>Previously, pmachapman (Peter Chapman) wrote…</i></summary><blockquote>

I thought of that, but thought it might be a leaking of data? Maybe I am being too paranoid.
</blockquote></details>

Hmm. Yeah, that's good to consider. I suspect that in this case we don't need to worry about that though since we are checking for user secrets of the current user, rather than for another user, hey?

Hmm, "user secrets" and "Private user information" may seem a bit serious; maybe "User access tokens not found" is simpler.
___
*[`test/SIL.XForge.Scripture.Tests/Services/ParatextSyncRunnerTests.cs` line 626 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/2506#-O-8H7vAAmeOwpTf0ikQ:-O-bY6aA7zACOmBgpodv:b-837i3v) ([raw file](https://github.com/sillsdev/web-xforge/blob/82623f1e03b1046617a06f3043761b9163235f5a/test/SIL.XForge.Scripture.Tests/Services/ParatextSyncRunnerTests.cs#L626)):*
<details><summary><i>Previously, pmachapman (Peter Chapman) wrote…</i></summary><blockquote>

I am not sure. On reflection, it is superfluous.

That said, I am planning to combine these two methods, as both call the same Registry API endpoint, so this will be cleaned up in the coming week or so.
</blockquote></details>

Okay.

**Pull request merged**
