### PR TITLE
SF-1195 - Pop-up dialog when clicking notes icon

### PR DESCRIPTION
**Pull request by nigel-wells**
- Refactored checking owner component so that it can be used be the translate app
- Added a dialog to display notes from Paratext when a note flag is clicked on

The end result is relatively straight forward and a large part of the changes is the owner component being moved and renamed.

This is intended as part one for the notes dialog. Once a few more features are integrated i.e. syncing resolving notes then the dialog will need to be updated again to reflect the new information it has access to.

There is a todo note to implement a diff similar to Paratext for showing what has changed in the current text from the original note text. We'll may need more information than what is currently being syncing in order to effectively do this as it looks like the diff in Paratext can compare text changes outside of the selected text context.

image

---
This change is [Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1164)

### CODE REVIEW

**Review by RaymondLuong3 — CHANGES_REQUESTED** [review]
Looking good so far. I'll finish this review after Thanksgiving! :turkey: 

> Reviewed 18 of 27 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1164#-:-MlX4C-04CB3LDWmfzVN:byvfe2l)* status: 18 of 27 files reviewed, 12 unresolved discussions (waiting on @nigel-wells and @RaymondLuong3)

___
*[src/RealtimeServer/scriptureforge/models/paratext-note.ts, line 3 at r2](https://reviewable.io/reviews/sillsdev/web-xforge/1164#-MlWLfC44d2cSEiVblpp:-MlWLfC44d2cSEiVblpq:bf4x9i4) ([raw file](https://github.com/sillsdev/web-xforge/blob/482c58bc20aea66be6f61888850bb4f97dd1d943/src/RealtimeServer/scriptureforge/models/paratext-note.ts#L3)):*
> ```
> export interface ParatextNote extends Comment {
> ```
This class needs to be deleted. The most recent changes have this named Notes.
___
*[src/SIL.XForge.Scripture/ClientApp/src/app/core/sf-project.service.ts, line 9 at r2](https://reviewable.io/reviews/sillsdev/web-xforge/1164#-MlWs4LuE72cV5UoCKZg:-MlWs4LuE72cV5UoCKZh:bvhikma) ([raw file](https://github.com/sillsdev/web-xforge/blob/482c58bc20aea66be6f61888850bb4f97dd1d943/src/SIL.XForge.Scripture/ClientApp/src/app/core/sf-project.service.ts#L9)):*
> ```
> import { Note } from 'realtime-server/scriptureforge/models/note';
> ```
This import looks wrong. It should be 'realtime-server/lib/esm/scriptureforge/models"
___
*[src/SIL.XForge.Scripture/ClientApp/src/app/core/sf-project.service.ts, line 78 at r2](https://reviewable.io/reviews/sillsdev/web-xforge/1164#-MlX0xzw7CSQvVFJSYz7:-MlX0xzw7CSQvVFJSYz8:bsyvqpp) ([raw file](https://github.com/sillsdev/web-xforge/blob/482c58bc20aea66be6f61888850bb4f97dd1d943/src/SIL.XForge.Scripture/ClientApp/src/app/core/sf-project.service.ts#L78)):*
> ```
>   getNoteThreadIcon(thread: NoteThread): NoteThreadIcon {
> ```
I wonder if a more appropriate place for this method would be in the NoteThread class, since it seems that `sf-project.service` is the place to handle requests about the project.
___
*[src/SIL.XForge.Scripture/ClientApp/src/app/core/sf-project.service.spec.ts, line 5 at r2](https://reviewable.io/reviews/sillsdev/web-xforge/1164#-MlWtids456W6o54zO28:-MlWtids456W6o54zO29:b-kmjda1) ([raw file](https://github.com/sillsdev/web-xforge/blob/482c58bc20aea66be6f61888850bb4f97dd1d943/src/SIL.XForge.Scripture/ClientApp/src/app/core/sf-project.service.spec.ts#L5)):*
> ```
> import { NoteThread } from 'realtime-server/scriptureforge/models/note-thread';
> ```
This import is also incorrect. See above.
___
*[src/SIL.XForge.Scripture/ClientApp/src/app/core/sf-project.service.spec.ts, line 88 at r2](https://reviewable.io/reviews/sillsdev/web-xforge/1164#-MlWt4wl-89BqNPiZAOB:-MlWt4wl-89BqNPiZAOC:b-xq149t) ([raw file](https://github.com/sillsdev/web-xforge/blob/482c58bc20aea66be6f61888850bb4f97dd1d943/src/SIL.XForge.Scripture/ClientApp/src/app/core/sf-project.service.spec.ts#L88)):*
> ```
>           dateModified: new Date().toJSON()
> ```
I wonder if it is worth checking that if somehow notes do get out of date order, that we correctly pick out the icon from the latest note. I don't expect notes to get out of order, but to be safe it seems worth a test.
___
*[src/SIL.XForge.Scripture/ClientApp/src/app/core/models/text-doc.ts, line 93 at r2](https://reviewable.io/reviews/sillsdev/web-xforge/1164#-MlWuRxT55e3FbbkXUEI:-MlWuRxT55e3FbbkXUEJ:b8wdasj) ([raw file](https://github.com/sillsdev/web-xforge/blob/482c58bc20aea66be6f61888850bb4f97dd1d943/src/SIL.XForge.Scripture/ClientApp/src/app/core/models/text-doc.ts#L93)):*
> ```
>     /** Locate range of ops that match the verse segments
>      * This is done to capture important inserts between segments like blank lines
>      */
> ```
Nit: this comment doesn't need the javadocs formatting. Unless there is a real reason I didn't know about.
___
*[src/SIL.XForge.Scripture/ClientApp/src/app/core/models/text-doc.ts, line 100 at r2](https://reviewable.io/reviews/sillsdev/web-xforge/1164#-MlWzEXr6hecrP3Revq5:-MlWzEXr6hecrP3Revq6:b-lyu4a6) ([raw file](https://github.com/sillsdev/web-xforge/blob/482c58bc20aea66be6f61888850bb4f97dd1d943/src/SIL.XForge.Scripture/ClientApp/src/app/core/models/text-doc.ts#L100)):*
> ```
>       const index = parseInt(i, 10);
> ```
What a neat
___
*[src/SIL.XForge.Scripture/ClientApp/src/app/core/models/text-doc.ts, line 118 at r2](https://reviewable.io/reviews/sillsdev/web-xforge/1164#-MlWzoQo7n4LsBt5EZnn:-MlWzoQo7n4LsBt5EZno:b755h4x) ([raw file](https://github.com/sillsdev/web-xforge/blob/482c58bc20aea66be6f61888850bb4f97dd1d943/src/SIL.XForge.Scripture/ClientApp/src/app/core/models/text-doc.ts#L118)):*
> ```
>     for (const i in this.data.ops) {
> ```
Instead of having two for loops, I think this could be condensed into just one loop.
___
*[src/SIL.XForge.Scripture/ClientApp/src/app/core/models/text-doc.ts, line 123 at r2](https://reviewable.io/reviews/sillsdev/web-xforge/1164#-MlWzUPd30Z-UHwLk0to:-MlWzUPd30Z-UHwLk0tp:b-puqehw) ([raw file](https://github.com/sillsdev/web-xforge/blob/482c58bc20aea66be6f61888850bb4f97dd1d943/src/SIL.XForge.Scripture/ClientApp/src/app/core/models/text-doc.ts#L123)):*
> ```
>       if (index < opIndexStart || index > opIndexEnd) {
> ```
If index > opIndexEnd, we could just return the text at that point?
___
*[src/SIL.XForge.Scripture/ClientApp/src/app/shared/utils.ts, line 54 at r2](https://reviewable.io/reviews/sillsdev/web-xforge/1164#-MlX-rRcE74P9mr_4r2y:-MlX-rRcE74P9mr_4r2z:b-89hcm3) ([raw file](https://github.com/sillsdev/web-xforge/blob/482c58bc20aea66be6f61888850bb4f97dd1d943/src/SIL.XForge.Scripture/ClientApp/src/app/shared/utils.ts#L54)):*
> ```
> function attributeFromMouseEvent(event: MouseEvent, nodeName: string, attribute: string): string | undefined {
> ```
Nice helper function :)
___
*[src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/note-dialog/note-dialog.component.ts, line 5 at r2](https://reviewable.io/reviews/sillsdev/web-xforge/1164#-MlX3YlO66CjHn69jcel:-MlX3YlO66CjHn69jcem:b-o3l7vg) ([raw file](https://github.com/sillsdev/web-xforge/blob/482c58bc20aea66be6f61888850bb4f97dd1d943/src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/note-dialog/note-dialog.component.ts#L5)):*
> ```
> import { Note } from 'realtime-server/scriptureforge/models/note';
> ```
The import is incorrect.
___
*[src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/note-dialog/note-dialog.component.ts, line 95 at r2](https://reviewable.io/reviews/sillsdev/web-xforge/1164#-MlX3tT4E7_ekzCXiNeU:-MlX3tT4E7_ekzCXiNeV:b-5luqcs) ([raw file](https://github.com/sillsdev/web-xforge/blob/482c58bc20aea66be6f61888850bb4f97dd1d943/src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/note-dialog/note-dialog.component.ts#L95)):*
> ```
>   toggleSegmentText(): void {
>     this.showSegmentText = !this.showSegmentText;
>   }
> ```
Methods should go below getters I believe. Even below private getters.

**Review by nigel-wells — COMMENTED** [review]
I've removed those first 2 commits now.

> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1164#-:-MlwqfDWEQN9Lpweqhhx:bvofdjv)* status: 25 of 31 files reviewed, 2 unresolved discussions (waiting on @nigel-wells and @RaymondLuong3)

___
*[src/SIL.XForge.Scripture/ClientApp/src/app/core/models/text-doc.ts, line 113 at r6](https://reviewable.io/reviews/sillsdev/web-xforge/1164#-MluTbnV4nBskuip1oKN:-Mlwi1ppBBYicVUsMb_t:b-896fix) ([raw file](https://github.com/sillsdev/web-xforge/blob/b56d1def3be9d86693b650f029970039f0efefc5/src/SIL.XForge.Scripture/ClientApp/src/app/core/models/text-doc.ts#L113)):*
<details><summary><i>Previously, RaymondLuong3 (Raymond Luong) wrote…</i></summary><blockquote>

> ```
>   if (text != '') {
> ```
I would have expected this to be a `if (text !== '')`
</blockquote></details>

Done.
___
*[src/SIL.XForge.Scripture/ClientApp/src/assets/i18n/checking_en.json, line 281 at r5](https://reviewable.io/reviews/sillsdev/web-xforge/1164#-MlpGRpK-KjCLJG2lRMY:-Mlwjt9w9z9GHcE4nvnW:b-mu39u3) ([raw file](https://github.com/sillsdev/web-xforge/blob/84f3e643e61cc0cd6c4c2b990d741da5a8548a96/src/SIL.XForge.Scripture/ClientApp/src/assets/i18n/checking_en.json#L281)):*
<details><summary><i>Previously, RaymondLuong3 (Raymond Luong) wrote…</i></summary><blockquote>

I tried moving this to the `non_checking_en.json` file, and it worked without a problem. Could you try again?
</blockquote></details>

Working again now - no idea what happened yesterday then.

**Comment by irahopkinson** [comment]
___
*[src/SIL.XForge.Scripture/ClientApp/src/app/core/models/note-thread-doc.ts, line 11 at r8](https://reviewable.io/reviews/sillsdev/web-xforge/1164#-MmGkhZwBFOGcpEtDY5j:-MmGkhZwBFOGcpEtDY5k:b3mo52c) ([raw file](https://github.com/sillsdev/web-xforge/blob/7c9d71c7e2339405a7620bbc07f5557593a2f373/src/SIL.XForge.Scripture/ClientApp/src/app/core/models/note-thread-doc.ts#L11)):*
> ```
> var
> ```
`var` is a reserved word. Don't use it for property names! Does your IDE highlight that (it does in mine)?

**Comment by irahopkinson** [comment]
___
*[src/SIL.XForge.Scripture/ClientApp/src/app/translate/translate.module.ts, line 31 at r8](https://reviewable.io/reviews/sillsdev/web-xforge/1164#-MmGqNTcA912CARZ2EyF:-MmGqNTcA912CARZ2EyG:b-afimrx) ([raw file](https://github.com/sillsdev/web-xforge/blob/7c9d71c7e2339405a7620bbc07f5557593a2f373/src/SIL.XForge.Scripture/ClientApp/src/app/translate/translate.module.ts#L31)):*
> ```
>     MatIconModule,
>     MatMenuModule
> ```
These shouldn't be needed because they have been added into `UICommonModule`.

**Pull request merged**
