### PR TITLE
Add logging when SharedProject is null

### PR DESCRIPTION
**Pull request by RaymondLuong3**
This change is [Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1261)

### CODE REVIEW

**Review by Nateowami — COMMENTED** [review]
This is a great idea. Thanks.

> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1261#-:-Mxexmoy1_mGMX-stVIt:b1shx8x)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @Nateowami and @RaymondLuong3)

___
*[src/SIL.XForge.Scripture/Services/ParatextService.cs, line 1378 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/1261#-MxexlYP2vIw1nCgKd78:-MxexlYP2vIw1nCgKd79:b-qiz8hs) ([raw file](https://github.com/sillsdev/web-xforge/blob/72b9c7cda3b6a21bc665059048c637817a61fdad/src/SIL.XForge.Scripture/Services/ParatextService.cs#L1378)):*
> ```Smalltalk
>             IEnumerable<SharedRepository> sourceRepositories)
>         {
>             _logger.LogInformation($"Creating ShareProject: {projId}");
> ```

Given we already know it failed, could we log that right at the beginning? That way it will be easier to grep for this.

**Review by RaymondLuong3 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1261)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @Nateowami)

___
*[src/SIL.XForge.Scripture/Services/ParatextService.cs, line 1378 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/1261#-MxexlYP2vIw1nCgKd78:-MxfDJgf3bDxA63PNtKL:bc8fuez) ([raw file](https://github.com/sillsdev/web-xforge/blob/72b9c7cda3b6a21bc665059048c637817a61fdad/src/SIL.XForge.Scripture/Services/ParatextService.cs#L1378)):*
<details><summary><i>Previously, Nateowami (Nathaniel Paulus) wrote…</i></summary><blockquote>

Given we already know it failed, could we log that right at the beginning? That way it will be easier to grep for this.
</blockquote></details>

Good thinking. How is this?

**Review by Nateowami — COMMENTED** [review]
Do you think we're still going to want this, given we now know what the cause likely is?

> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1261#-:-MxjxGJm7ZrHzvjtKEdJ:b-e64kv)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @Nateowami and @RaymondLuong3)

___
*[src/SIL.XForge.Scripture/Services/ParatextService.cs, line 1378 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/1261#-MxexlYP2vIw1nCgKd78:-MxjxEx09SgiFizkKItI:b-qm5qv) ([raw file](https://github.com/sillsdev/web-xforge/blob/72b9c7cda3b6a21bc665059048c637817a61fdad/src/SIL.XForge.Scripture/Services/ParatextService.cs#L1378)):*
<details><summary><i>Previously, RaymondLuong3 (Raymond Luong) wrote…</i></summary><blockquote>

Good thinking. How is this?
</blockquote></details>

That's good.

**Review by RaymondLuong3 — COMMENTED** [review]
Let's merge this. It won't run unless the project is null, so I don't see it adding unnecessary logging.

> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1261#-:-MxvAESL8HOBh0Jvk3io:brjifj1)* status: 0 of 1 files reviewed, all discussions resolved (waiting on @Nateowami)

**Review by Nateowami — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1261#-:-Mxw1S-Q0iEBWxBEg8_V:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @RaymondLuong3)

**Pull request merged**
