### PR TITLE
Fix direction in splitter when in RTL mode

### PR DESCRIPTION
**Pull request by Nateowami**
After upgrading angular-split to 15.0.0, RTL within the splitter was broken. It appears the splitter always sets `dir=ltr`

- - -
This change is [Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/2178)

### CODE REVIEW

**Comment by josephmyers** [comment]
I see that this makes the LTR sentences better, but doesn't this mess up the layout? All the Arabic buttons inside the splitter are now being laid out LTR (ordering, alignment, etc.), which seems wrong.

**Comment by Nateowami** [comment]
@josephmyers Are you referring to what you see on your machine, or in my screenshot? My screenshot was supposed to show the bug, not the solution.

**Comment by josephmyers** [comment]
Interesting. My machine on master looks different than yours. I think I'm missing what you're actually doing here
image

**Comment by josephmyers** [comment]
I just realized I'm still on the old version of angular-split.

```
PS C:\Users\joseph\source\web-xforge\src\SIL.XForge.Scripture\ClientApp> npm list angular-split
sil.xforge.scripture@4.7.1 C:\Users\joseph\source\web-xforge\src\SIL.XForge.Scripture\ClientApp
`-- angular-split@5.0.0 invalid: "~15.0.0" from the root project

npm ERR! code ELSPROBLEMS
npm ERR! invalid: angular-split@5.0.0 C:\Users\joseph\source\web-xforge\src\SIL.XForge.Scripture\ClientApp\node_modules\angular-split

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\joseph\AppData\Local\npm-cache\_logs\2023-11-21T22_06_25_492Z-debug-0.log
```

**Comment by Nateowami** [comment]
Ah, yes, you need to do `npm i`

**Review by josephmyers — APPROVED** [review]
Yep, thanks

> Reviewed 3 of 3 files at r1, 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/2178#-:-NjnzycQESYpCDBqyqIF:b-c3iuc)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @Nateowami)

**Comment by Nateowami** [comment]
Oops. I merged this without sending it through testing.

**Pull request merged**
