### PR TITLE
SF-753 Expire specific user invites and remove email constraint

### PR DESCRIPTION
**Pull request by RaymondLuong3**
* email link expires in 14 days
* resending an email invitation renews the 14 day valid period
* user can choose any email to access the project
* expired invitations show as expired on users page
* notify user the link will expire

---
This change is [Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/954)

### CODE REVIEW

**Review by irahopkinson — CHANGES_REQUESTED** [review]
This is looking good. Just one blocking comment and 2 others to discuss.

> Reviewed 5 of 5 files at r1.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/954#-:-MTefakY3cq8BOMti-3Z:b5648j4)* status: all files reviewed, 3 unresolved discussions (waiting on @RaymondLuong3)

___
*[src/SIL.XForge.Scripture/Resources/SharedResource.resx, line 150 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/954#-MTeVgoN-YXMEbQMEr6Q:-MTeVgoO8AnqMp5B6C94:b-34o93u) ([raw file](https://github.com/sillsdev/web-xforge/blob/308604f3424ed0e10c24c883b49ef0fd827970ef/src/SIL.XForge.Scripture/Resources/SharedResource.resx#L150)):*
> ```
> 14
> ```
Perhaps this should be a variable so we don't have to re-translate if we change the expire period?
___
*[src/SIL.XForge.Scripture/Services/SFProjectService.cs, line 339 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/954#-MTecTgv45ORRAq2HIAQ:-MTecTgv45ORRAq2HIAR:b-rjzffo) ([raw file](https://github.com/sillsdev/web-xforge/blob/308604f3424ed0e10c24c883b49ef0fd827970ef/src/SIL.XForge.Scripture/Services/SFProjectService.cs#L339)):*
<details><summary><i alt="summary">Quoted 5 lines of code…</i></summary>

> ```
>             // Remove any expired sharekeys on this project
>             await ProjectSecrets.UpdateAsync(
>                 p => p.Id == projectId,
>                 update => update.RemoveAll(p => p.ShareKeys, sk => sk.ExpirationTime < DateTime.UtcNow)
>             );
> ```
</details>

Its good to have a plan for cleaning up expired invites. I'm wondering what the UX will be like when an *Administrator* is viewing the **Users** page? Won't un-related email invites disappear when creating a new invite? Do we display that the invite has expired or do we filter out expired invites? How will an *Administrator* know if they have previously invited but now expired? Do they care?
___
*[src/SIL.XForge.Scripture/Services/SFProjectService.cs, line 351 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/954#-MTediW4Ak71ZoBTRb6x:-MTediW4Ak71ZoBTRb6y:b5q4uga) ([raw file](https://github.com/sillsdev/web-xforge/blob/308604f3424ed0e10c24c883b49ef0fd827970ef/src/SIL.XForge.Scripture/Services/SFProjectService.cs#L351)):*
> ```
> // Renew the expiration time of the valid key
> ```
Doesn't this comment belong a line or 2 below?

**Review by RaymondLuong3 — COMMENTED** [review]
Since there are advantages to showing admins when invitations expire, I've decided not to clear out expired invitations. Project admins can manually do this from the Users page if they so desire.

> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/954#-:-MTmSg0W0jhsqRUDzEEV:b-ifc5rp)* status: 3 of 13 files reviewed, 1 unresolved discussion (waiting on @irahopkinson)

___
*[src/SIL.XForge.Scripture/Resources/SharedResource.resx, line 150 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/954#-MTeVgoN-YXMEbQMEr6Q:-MTmRC2C2E1WtxsBgQyD:br5dqo8) ([raw file](https://github.com/sillsdev/web-xforge/blob/308604f3424ed0e10c24c883b49ef0fd827970ef/src/SIL.XForge.Scripture/Resources/SharedResource.resx#L150)):*
<details><summary><i>Previously, irahopkinson (Ira Hopkinson) wrote…</i></summary><blockquote>

> ```
> 14
> ```
Perhaps this should be a variable so we don't have to re-translate if we change the expire period?
</blockquote></details>

I wonder if there may be languages where they do not use our numbering. I know that in chinese 14 would be understood, but could also be written another way. Let's keep it in this string for now.
___
*[src/SIL.XForge.Scripture/Services/SFProjectService.cs, line 339 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/954#-MTecTgv45ORRAq2HIAQ:-MTmSEZu3JpOeI2EsRb3:b2chsd7) ([raw file](https://github.com/sillsdev/web-xforge/blob/308604f3424ed0e10c24c883b49ef0fd827970ef/src/SIL.XForge.Scripture/Services/SFProjectService.cs#L339)):*
<details><summary><i>Previously, irahopkinson (Ira Hopkinson) wrote…</i></summary><blockquote>

> ```
>             // Remove any expired sharekeys on this project
>             await ProjectSecrets.UpdateAsync(
>                 p => p.Id == projectId,
>                 update => update.RemoveAll(p => p.ShareKeys, sk => sk.ExpirationTime < DateTime.UtcNow)
>             );
> ```
Its good to have a plan for cleaning up expired invites. I'm wondering what the UX will be like when an *Administrator* is viewing the **Users** page? Won't un-related email invites disappear when creating a new invite? Do we display that the invite has expired or do we filter out expired invites? How will an *Administrator* know if they have previously invited but now expired? Do they care?
</blockquote></details>

Initially I thought it would be better to remove expired invitations, but now that I think of it there may be a benefit from administrators seeing invitations that have expired. This could prompt admins to investigate, which is a good thing. I have made changes so now it will show expired invitations in the Users pages.

**Review by Nateowami — COMMENTED** [review]
> Reviewed 3 of 5 files at r1.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/954)* status: 3 of 13 files reviewed, 1 unresolved discussion (waiting on @irahopkinson)

___
*[src/SIL.XForge.Scripture/Resources/SharedResource.resx, line 150 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/954#-MTeVgoN-YXMEbQMEr6Q:-MTmWSDg1-aJ4J45jnNK:b-la1l67) ([raw file](https://github.com/sillsdev/web-xforge/blob/308604f3424ed0e10c24c883b49ef0fd827970ef/src/SIL.XForge.Scripture/Resources/SharedResource.resx#L150)):*
<details><summary><i>Previously, RaymondLuong3 (Raymond Luong) wrote…</i></summary><blockquote>

I wonder if there may be languages where they do not use our numbering. I know that in chinese 14 would be understood, but could also be written another way. Let's keep it in this string for now.
</blockquote></details>

@raymondluong3 Throughout our entire app we assume we can write numbers using Arabic numerals. If a particular language needs them formatted differently, we're going to have to handle rendering numbers that we won't know until runtime, everywhere that we use numbers.

**Review by irahopkinson — APPROVED** [review]
> Reviewed 10 of 10 files at r2.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/954)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
