### PR TITLE
SF-955 - Editing in a RTL text is inconsistent

### PR DESCRIPTION
**Pull request by nigel-wells**
- Removed previous logic that set RTL/LTR based on text contained in a paragraph
- Enforce direction based on project `isRightToLeft` setting from Paratext
- Improved USX formatting for RTL

Issues identified to be addressed were:

1. Arrow keys do not work at the end of a segment.
2. Unable to select the first position in a segment.
3. In a LTR segment, typing at the beginning of the segment adds to the end.
4. Unable to navigate to a blank segment.
5. In a LTR segment, unable to select the end of the segment.
6. Selection marker should appear on right side when document is RTL.

This PR does not look heavily at bidirectional text within segments but focuses on RTL scripts working correctly. Segments can contain LTR scripts but Chrome decides to handle things differently where it will jump the cursor to the left side of the script and work backwards whereas Firefox does the opposite. If the LTR script is at the start/end of a segment this can be a little disorignating when trying to click at the right position. We decided that those who use Chrome in RTL would likely be used to how it operates and those who use Firefox would equally be used to how it operates. 

Testing was completed on a real Arabic project and compared with how it rendered in Paratext.

---
This change is [Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/840)

### CODE REVIEW

**Review by RaymondLuong3 — CHANGES_REQUESTED** [review]
ީI had a problem using the backspace button in the divehi rtl script. The backspace didn't do anything, but the delete button (the key under insert on the keyboard) would delete a character on the left of the cursor in Chrome. (In firefox backspace deletes the char on the right of the cursor, and delete will delete the char on the left.)
Other than that, it is working well in my test project!

> Reviewed 14 of 14 files at r1.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/840#-:-MJhEWVGDr8lz4PwNq1l:b-tlufnm)* status: all files reviewed, 3 unresolved discussions (waiting on @nigel-wells)

___
*[src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking.component.ts, line 198 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/840#-MJhArJQBxwdwCmqSN-n:-MJhArJR54RrZqfyTFo8:bvc0903) ([raw file](https://github.com/sillsdev/web-xforge/blob/e2b7c2cbccb61ae29fb75b59d06b2555ce78aa08/src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking.component.ts#L198)):*
> ```
> if (this.projectDoc?.data && this.projectDoc.data?.isRightToLeft) {
> ```
This could be shortened to `if (this.projectDoc?.data?.isRightToLeft != null)` I suggest using `!= null` since the majority of our components explicitly do that.
___
*[src/SIL.XForge.Scripture/ClientApp/src/app/shared/text/text.component.ts, line 78 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/840#-MJhG-et1nQC0CXOGQ1X:-MJhG-et1nQC0CXOGQ1Y:b-vqjdwn) ([raw file](https://github.com/sillsdev/web-xforge/blob/e2b7c2cbccb61ae29fb75b59d06b2555ce78aa08/src/SIL.XForge.Scripture/ClientApp/src/app/shared/text/text.component.ts#L78)):*
> ```
> private direction: string | null = null;
> ```
This can be removed.
___
*[src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.ts, line 199 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/840#-MJhGbKPBiIcUhBT4zZT:-MJhGbKPBiIcUhBT4zZU:bvc0903) ([raw file](https://github.com/sillsdev/web-xforge/blob/e2b7c2cbccb61ae29fb75b59d06b2555ce78aa08/src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.ts#L199)):*
> ```
> if (this.projectDoc?.data && this.projectDoc.data?.isRightToLeft) {
> ```
This could be shortened to `if (this.projectDoc?.data?.isRightToLeft != null)` I suggest using `!= null` since the majority of our components explicitly do that.

**Review by nigel-wells — COMMENTED** [review]
Where you testing on a project with actual RTL script or did it have latin script? Even though the DOM has `dir="rtl"` Chrome will change behaviour with the cursor depending on the script you're looking at which I attempted to describe in my PR notes. The deleting is correct but it feels backwards from what Chrome is doing. I've just tested it again with a RTL script (Arabic) and the backspace and delete keys do what you'd expect for me. Did you want to try again with a RTL script?

> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/840#-:-MJhjJm-8Gmioam0Dj1u:b-odebmo)* status: 11 of 14 files reviewed, 3 unresolved discussions (waiting on @RaymondLuong3)

___
*[src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking.component.ts, line 198 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/840#-MJhArJQBxwdwCmqSN-n:-MJhiUcfAcqgNlgZge0H:bq4x2au) ([raw file](https://github.com/sillsdev/web-xforge/blob/e2b7c2cbccb61ae29fb75b59d06b2555ce78aa08/src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking.component.ts#L198)):*
<details><summary><i>Previously, RaymondLuong3 (Raymond Luong) wrote…</i></summary><blockquote>

> ```
> if (this.projectDoc?.data && this.projectDoc.data?.isRightToLeft) {
> ```
This could be shortened to `if (this.projectDoc?.data?.isRightToLeft != null)` I suggest using `!= null` since the majority of our components explicitly do that.
</blockquote></details>

Done - bad habit of mine :)
___
*[src/SIL.XForge.Scripture/ClientApp/src/app/shared/text/text.component.ts, line 78 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/840#-MJhG-et1nQC0CXOGQ1X:-MJhidaWEHCAkgup1WmO:bbfs713) ([raw file](https://github.com/sillsdev/web-xforge/blob/e2b7c2cbccb61ae29fb75b59d06b2555ce78aa08/src/SIL.XForge.Scripture/ClientApp/src/app/shared/text/text.component.ts#L78)):*
<details><summary><i>Previously, RaymondLuong3 (Raymond Luong) wrote…</i></summary><blockquote>

> ```
> private direction: string | null = null;
> ```
This can be removed.
</blockquote></details>

Done - interesting that our automated checks didn't pull me up on that?
___
*[src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.ts, line 199 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/840#-MJhGbKPBiIcUhBT4zZT:-MJhiz1Y3E_v9ZW6i--o:b-896fix) ([raw file](https://github.com/sillsdev/web-xforge/blob/e2b7c2cbccb61ae29fb75b59d06b2555ce78aa08/src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.ts#L199)):*
<details><summary><i>Previously, RaymondLuong3 (Raymond Luong) wrote…</i></summary><blockquote>

> ```
> if (this.projectDoc?.data && this.projectDoc.data?.isRightToLeft) {
> ```
This could be shortened to `if (this.projectDoc?.data?.isRightToLeft != null)` I suggest using `!= null` since the majority of our components explicitly do that.
</blockquote></details>

Done.

**Review by RaymondLuong3 — APPROVED** [review]
The backspacing issue may be something specific to my computer. @irahopkinson maybe you can look to see if the backspace issue I see is something you can reproduce.

> Reviewed 3 of 3 files at r2.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/840#-:-MJiFRh5-f-CnPf2lnoq:bkhyqjc)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by irahopkinson — CHANGES_REQUESTED** [review]
@raymondluong3 I can't reproduce the backspace issue on Windows. @nigel-wells can you try it on Linux?

I only have 4 relatively minor comments below.

> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/840#-:-MK4J4ZB7eO-PDpSpchq:bf88qbn)* status: all files reviewed, 4 unresolved discussions (waiting on @nigel-wells)

___
*[src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking.component.ts, line 198 at r2](https://reviewable.io/reviews/sillsdev/web-xforge/840#-MK4G0zoE4uC51eEQtcf:-MK4G0zoE4uC51eEQtcg:b-685965) ([raw file](https://github.com/sillsdev/web-xforge/blob/b22c81db5994cd6678a851c737a1076096facff5/src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking.component.ts#L198)):*
> ```
> if (this.projectDoc?.data && this.projectDoc.data?.isRightToLeft != null) {
> ```
nit: I'm pretty sure this can be simplified to (i.e. you don't need the `&&` anymore):
` if (this.projectDoc?.data?.isRightToLeft != null) {`
___
*[src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-text/checking-text.component.ts, line 65 at r2](https://reviewable.io/reviews/sillsdev/web-xforge/840#-MK4H6IBB-9fD7UI9DaQ:-MK4H6IBB-9fD7UI9DaR:b-envd3b) ([raw file](https://github.com/sillsdev/web-xforge/blob/b22c81db5994cd6678a851c737a1076096facff5/src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-text/checking-text.component.ts#L65)):*
<details><summary><i alt="summary">Quoted 6 lines of code…</i></summary>

> ```
>   @Input() set isRightToLeft(value: boolean) {
>     this._isRightToLeft = value;
>   }
>   get isRightToLeft(): boolean {
>     return this._isRightToLeft;
>   }
> ```
</details>

I don't think you don't need a getter and setter for this.  `@Input() isRightToLeft: boolean = false;` is all that is needed.
___
*[src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.ts, line 199 at r2](https://reviewable.io/reviews/sillsdev/web-xforge/840#-MK4IKDQ9qHG422QkAmD:-MK4IKDR5fnvsKm-97WE:bod7zdf) ([raw file](https://github.com/sillsdev/web-xforge/blob/b22c81db5994cd6678a851c737a1076096facff5/src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.ts#L199)):*
> ```
>     if (this.projectDoc?.data && this.projectDoc.data?.isRightToLeft != null) {
> ```
nit: I'm pretty sure this can be simplified to (i.e. you don't need the `&&` anymore):
` if (this.projectDoc?.data?.isRightToLeft != null) {`
___
*[src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.spec.ts, line 703 at r2](https://reviewable.io/reviews/sillsdev/web-xforge/840#-MK4IRrGAIdtjg_RrMcH:-MK4IRrGAIdtjg_RrMcI:b9o8d7j) ([raw file](https://github.com/sillsdev/web-xforge/blob/b22c81db5994cd6678a851c737a1076096facff5/src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.spec.ts#L703)):*
> ```
> 'ensure direction is RTL when project is to to RTL'
> ```
nit typo: maybe should be "...project is set to RTL" or  "...project is RTL"?

**Review by nigel-wells — COMMENTED** [review]
My Hyper-V box is stuck in and endless loop booting up at the moment so can't test on Linux. @marksvc are you able to do a check for us at all? See original comment from @raymondluong3 about backspace

> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/840#-:-MK8Ilu44Nd6Zb6d1spm:b-2mas30)* status: 10 of 14 files reviewed, 2 unresolved discussions (waiting on @irahopkinson and @RaymondLuong3)

___
*[src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-text/checking-text.component.ts, line 65 at r2](https://reviewable.io/reviews/sillsdev/web-xforge/840#-MK4H6IBB-9fD7UI9DaQ:-MK8FauF4VZPXQ2XUG4H:b-ahle5t) ([raw file](https://github.com/sillsdev/web-xforge/blob/b22c81db5994cd6678a851c737a1076096facff5/src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-text/checking-text.component.ts#L65)):*
<details><summary><i>Previously, irahopkinson (Ira Hopkinson) wrote…</i></summary><blockquote>

> ```
>   @Input() set isRightToLeft(value: boolean) {
>     this._isRightToLeft = value;
>   }
>   get isRightToLeft(): boolean {
>     return this._isRightToLeft;
>   }
> ```
I don't think you don't need a getter and setter for this.  `@Input() isRightToLeft: boolean = false;` is all that is needed.
</blockquote></details>

Good to know!
___
*[src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.spec.ts, line 703 at r2](https://reviewable.io/reviews/sillsdev/web-xforge/840#-MK4IRrGAIdtjg_RrMcH:-MK8FrSH0jM-pYLH9egg:b-5mxya7) ([raw file](https://github.com/sillsdev/web-xforge/blob/b22c81db5994cd6678a851c737a1076096facff5/src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.spec.ts#L703)):*
<details><summary><i>Previously, irahopkinson (Ira Hopkinson) wrote…</i></summary><blockquote>

> ```
> 'ensure direction is RTL when project is to to RTL'
> ```
nit typo: maybe should be "...project is set to RTL" or  "...project is RTL"?
</blockquote></details>

Doh! Fixed.

**Review by irahopkinson — APPROVED** [review]
:lgtm:

> Reviewed 4 of 4 files at r3.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/840#-:-MK8RZEe9x_TZoL1NIFT:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved

___
*[src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-text/checking-text.component.ts, line 65 at r2](https://reviewable.io/reviews/sillsdev/web-xforge/840#-MK4H6IBB-9fD7UI9DaQ:-MK8Pb3U-obFPoh394hr:b-1fzxzb) ([raw file](https://github.com/sillsdev/web-xforge/blob/b22c81db5994cd6678a851c737a1076096facff5/src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-text/checking-text.component.ts#L65)):*
<details><summary><i>Previously, nigel-wells (Nigel Wells) wrote…</i></summary><blockquote>

Good to know!
</blockquote></details>

The getter and setter are only useful if you need to do more than just get or set the value. Another good reason to not use a straight property is if you want to only get or only set.

**Pull request merged**
