### PR TITLE
SF-1445 Highlight unread note threads

### PR DESCRIPTION
**Pull request by RaymondLuong3**
* add highlight class to unread note thread embeds
* record notes read in project user config doc

Unread note threads in Paratext appear with a border and a highlight colour behind the note icon. I chose to use only a border to identify an unread note thread, but I am open to suggestions on how to make it look clean in our app.
image

---
This change is [Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1219)

### CODE REVIEW

**Review by Nateowami — CHANGES_REQUESTED** [review]
Looks pretty good. Just a couple comments and questions. Functionality working fine in my tests.

> Reviewed 10 of 12 files at r1, 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1219#-:-MskvaKlDzVIRMPkMJb2:b-2hqp2v)* status: all files reviewed, 5 unresolved discussions (waiting on @RaymondLuong3)

___
*[src/SIL.XForge.Scripture/ClientApp/src/_text.scss, line 123 at r2](https://reviewable.io/reviews/sillsdev/web-xforge/1219#-MskoYDtAGx5pMkP_HZo:-MskoYDtAGx5pMkP_HZp:b-5h9k8e) ([raw file](https://github.com/sillsdev/web-xforge/blob/1054b326282a89fe6492e17281a4c4cdaa9b25b1/src/SIL.XForge.Scripture/ClientApp/src/_text.scss#L123)):*
> ```SCSS
>       &:before {
>         border: solid 1px #a9ca25;
>         margin-left: 0.25em;
> ```

In some ways this looks a bit odd because as the icons are clicked on they shift left and slightly upward (due to loss of margin and border). What do you think about making all the icons have the margin, and all the icons have a `solid 1px transparent` border, but set it to non-transparent when it needs to be highlighted?
___
*[src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.ts, line 665 at r2](https://reviewable.io/reviews/sillsdev/web-xforge/1219#-MskwH-c5O06_nQwkEGA:-MskwH-c5O06_nQwkEGB:bchy4yo) ([raw file](https://github.com/sillsdev/web-xforge/blob/1054b326282a89fe6492e17281a4c4cdaa9b25b1/src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.ts#L665)):*
> ```XML
>   private updateReadNotes(threadId: string) {
>     const noteThread: NoteThreadDoc | undefined = this.noteThreadQuery?.docs.find(
>       d => d.data != null && d.data.dataId == threadId
> ```

What about `d.data?.dataId === threadId`? Shouldn't the comparison be `===`?
___
*[src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.ts, line 1292 at r2](https://reviewable.io/reviews/sillsdev/web-xforge/1219#-MskzPpK2yL5osXCmgPn:-MskzPpK2yL5osXCmgPo:bs2dch1) ([raw file](https://github.com/sillsdev/web-xforge/blob/1054b326282a89fe6492e17281a4c4cdaa9b25b1/src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.ts#L1292)):*
> ```XML
> 
>   private hasNewContent(thread: NoteThreadDoc): boolean {
>     const noteId: string | undefined = thread.data?.notes[thread.data?.notes.length - 1].dataId;
> ```

Is it a safe assumption that the last note in the thread is the most recent? What if user 1 in Paratext creates a note, user 2 then creates a note, and changes from user 2 are synced first? Later on changes from user 1 are synced.

I'm guessing you've thought this through, but I'm not familiar with the sync code that pulls the notes in, so I just wanted to check.
___
*[src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.spec.ts, line 2506 at r2](https://reviewable.io/reviews/sillsdev/web-xforge/1219#-MskqS4h5ht_pZ1Mo5zZ:-MskqS4h5ht_pZ1Mo5z_:b-deywsq) ([raw file](https://github.com/sillsdev/web-xforge/blob/1054b326282a89fe6492e17281a4c4cdaa9b25b1/src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.spec.ts#L2506)):*
> ```XML
>   isNoteIconHighlighted(threadId: string): boolean {
>     const thread: HTMLElement | null = this.targetTextEditor.nativeElement.querySelector(
>       'usx-segment display-note[data-thread-id="' + threadId + '"].note-thread-highlight'
> ```

Is there a reason this isn't using backtick strings like `getNoteThreadIconElement` above, for consistency? 
___
*[src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.spec.ts, line 2670 at r2](https://reviewable.io/reviews/sillsdev/web-xforge/1219#-Msks1zL5m6u5NzUf_xS:-Msks1zL5m6u5NzUf_xT:bcd1wtb) ([raw file](https://github.com/sillsdev/web-xforge/blob/1054b326282a89fe6492e17281a4c4cdaa9b25b1/src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.spec.ts#L2670)):*
> ```XML
>       const id = userIds[i];
>       const date = new Date('2021-03-01T12:00:00');
>       date.setHours(date.getHours() + i);
> ```

OK, so each note was created and modified an hour apart, starting March 2021. Does that turn out to be significant? As in, would changing that break the tests? I'm just trying to understand what's going on here.

**Review by RaymondLuong3 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1219)* status: all files reviewed, 5 unresolved discussions (waiting on @Nateowami)

___
*[src/SIL.XForge.Scripture/ClientApp/src/_text.scss, line 123 at r2](https://reviewable.io/reviews/sillsdev/web-xforge/1219#-MskoYDtAGx5pMkP_HZo:-MspVXEh8zc_Fn5tsYKj:btyeq5o) ([raw file](https://github.com/sillsdev/web-xforge/blob/1054b326282a89fe6492e17281a4c4cdaa9b25b1/src/SIL.XForge.Scripture/ClientApp/src/_text.scss#L123)):*
<details><summary><i>Previously, Nateowami (Nathaniel Paulus) wrote…</i></summary><blockquote>

In some ways this looks a bit odd because as the icons are clicked on they shift left and slightly upward (due to loss of margin and border). What do you think about making all the icons have the margin, and all the icons have a `solid 1px transparent` border, but set it to non-transparent when it needs to be highlighted?
</blockquote></details>

Good thinking. Done.
___
*[src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.ts, line 665 at r2](https://reviewable.io/reviews/sillsdev/web-xforge/1219#-MskwH-c5O06_nQwkEGA:-MspVoGu-Ga0BShM8DTH:b-896fix) ([raw file](https://github.com/sillsdev/web-xforge/blob/1054b326282a89fe6492e17281a4c4cdaa9b25b1/src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.ts#L665)):*
<details><summary><i>Previously, Nateowami (Nathaniel Paulus) wrote…</i></summary><blockquote>

What about `d.data?.dataId === threadId`? Shouldn't the comparison be `===`?
</blockquote></details>

Done.
___
*[src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.ts, line 1292 at r2](https://reviewable.io/reviews/sillsdev/web-xforge/1219#-MskzPpK2yL5osXCmgPn:-MspaW1W92tkJPYOYJln:bndf2a0) ([raw file](https://github.com/sillsdev/web-xforge/blob/1054b326282a89fe6492e17281a4c4cdaa9b25b1/src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.ts#L1292)):*
<details><summary><i>Previously, Nateowami (Nathaniel Paulus) wrote…</i></summary><blockquote>

Is it a safe assumption that the last note in the thread is the most recent? What if user 1 in Paratext creates a note, user 2 then creates a note, and changes from user 2 are synced first? Later on changes from user 1 are synced.

I'm guessing you've thought this through, but I'm not familiar with the sync code that pulls the notes in, so I just wanted to check.
</blockquote></details>

Good eye! In the noteThread's notes property, notes are added at the end, and do not get reordered. That's what I thought anyways, but turns out they were being added at the beginning! Now they are added at the end of the notes array, so even if a use creates a notes later and syncs it first, SF can be sure that the last note in the notes array is the latest one we know to exist.
___
*[src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.spec.ts, line 2506 at r2](https://reviewable.io/reviews/sillsdev/web-xforge/1219#-MskqS4h5ht_pZ1Mo5zZ:-MspYDHvBIlLKnxgSCbf:btyeq5o) ([raw file](https://github.com/sillsdev/web-xforge/blob/1054b326282a89fe6492e17281a4c4cdaa9b25b1/src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.spec.ts#L2506)):*
<details><summary><i>Previously, Nateowami (Nathaniel Paulus) wrote…</i></summary><blockquote>

Is there a reason this isn't using backtick strings like `getNoteThreadIconElement` above, for consistency? 
</blockquote></details>

Good thinking. Done.
___
*[src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.spec.ts, line 2670 at r2](https://reviewable.io/reviews/sillsdev/web-xforge/1219#-Msks1zL5m6u5NzUf_xS:-MspYI3H7C3Pz8Vr74EE:b-nnzm8o) ([raw file](https://github.com/sillsdev/web-xforge/blob/1054b326282a89fe6492e17281a4c4cdaa9b25b1/src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.spec.ts#L2670)):*
<details><summary><i>Previously, Nateowami (Nathaniel Paulus) wrote…</i></summary><blockquote>

OK, so each note was created and modified an hour apart, starting March 2021. Does that turn out to be significant? As in, would changing that break the tests? I'm just trying to understand what's going on here.
</blockquote></details>

This was mostly to simulate what is seen in real life. But there is also the fact that comments in a comment thread in paratext are identified using their threadId, user and date created, so they do need to be unique.

**Review by Nateowami — COMMENTED** [review]
> Reviewed 5 of 5 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1219)* status: all files reviewed, 1 unresolved discussion (waiting on @RaymondLuong3)

___
*[src/SIL.XForge.Scripture/ClientApp/src/_text.scss, line 119 at r3](https://reviewable.io/reviews/sillsdev/web-xforge/1219#-MsrF1SDB6eLQcUlYCia:-MsrF1SDB6eLQcUlYCib:b-73bd5) ([raw file](https://github.com/sillsdev/web-xforge/blob/272888bb04fb2e75e4837aedc1879fbf61bbdd9d/src/SIL.XForge.Scripture/ClientApp/src/_text.scss#L119)):*
> ```SCSS
>       text-indent: 0;
>       background: var(--icon-file) no-repeat;
>       margin-left: 0.25em;
> ```

Should the margins be even on right and left, or is there a reason to put all the margin on the left side?
___
*[src/SIL.XForge.Scripture/ClientApp/src/_text.scss, line 119 at r3](https://reviewable.io/reviews/sillsdev/web-xforge/1219#-MsrFKjs5Yh5z7qD4Egj:-MsrFKjs5Yh5z7qD4Egk:blcqjhc) ([raw file](https://github.com/sillsdev/web-xforge/blob/cab0dc037fd9fef2d68b1b7f3c164eaa07bb05aa/src/SIL.XForge.Scripture/ClientApp/src/_text.scss#L119)):*
> ```SCSS
>       color: #fff;
>       text-indent: 0;
>       margin: 0em 0.5em;
> ```

For what it's worth, I think the generally accepted style for CSS is to not specify units when the value is 0.

**Review by RaymondLuong3 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1219)* status: all files reviewed, 1 unresolved discussion (waiting on @Nateowami)

___
*[src/SIL.XForge.Scripture/ClientApp/src/_text.scss, line 119 at r3](https://reviewable.io/reviews/sillsdev/web-xforge/1219#-MsrFKjs5Yh5z7qD4Egj:-Mt3zVKh-E5vIapJ_kEI:bw3g516) ([raw file](https://github.com/sillsdev/web-xforge/blob/cab0dc037fd9fef2d68b1b7f3c164eaa07bb05aa/src/SIL.XForge.Scripture/ClientApp/src/_text.scss#L119)):*
<details><summary><i>Previously, Nateowami (Nathaniel Paulus) wrote…</i></summary><blockquote>

For what it's worth, I think the generally accepted style for CSS is to not specify units when the value is 0.
</blockquote></details>

Ok, I see that text-indent doesn't appear to make a difference for the element, and it is hard to say why it is there in the first place. I'll remove it.
___
*[src/SIL.XForge.Scripture/ClientApp/src/_text.scss, line 119 at r3](https://reviewable.io/reviews/sillsdev/web-xforge/1219#-MsrF1SDB6eLQcUlYCia:-Mt3zfmZ1z5XNSwT1PaD:b-aptsly) ([raw file](https://github.com/sillsdev/web-xforge/blob/272888bb04fb2e75e4837aedc1879fbf61bbdd9d/src/SIL.XForge.Scripture/ClientApp/src/_text.scss#L119)):*
<details><summary><i>Previously, Nateowami (Nathaniel Paulus) wrote…</i></summary><blockquote>

Should the margins be even on right and left, or is there a reason to put all the margin on the left side?
</blockquote></details>

My preference was not to have a margin at all, but you can see that when the cursor is on the left of the note embed, the note embed covers the cursor. This is only true about the left side.

**Review by Nateowami — COMMENTED** [review]
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1219)* status: all files reviewed, 1 unresolved discussion (waiting on @RaymondLuong3)

___
*[src/SIL.XForge.Scripture/ClientApp/src/_text.scss, line 119 at r3](https://reviewable.io/reviews/sillsdev/web-xforge/1219#-MsrF1SDB6eLQcUlYCia:-Mt4Ajrn2Na_1U47BsT9:blcuit1) ([raw file](https://github.com/sillsdev/web-xforge/blob/272888bb04fb2e75e4837aedc1879fbf61bbdd9d/src/SIL.XForge.Scripture/ClientApp/src/_text.scss#L119)):*
<details><summary><i>Previously, RaymondLuong3 (Raymond Luong) wrote…</i></summary><blockquote>

My preference was not to have a margin at all, but you can see that when the cursor is on the left of the note embed, the note embed covers the cursor. This is only true about the left side. 


</blockquote></details>

Ah, OK, makes sense then. Did you test RTL?
___
*[src/SIL.XForge.Scripture/ClientApp/src/_text.scss, line 119 at r3](https://reviewable.io/reviews/sillsdev/web-xforge/1219#-MsrFKjs5Yh5z7qD4Egj:-Mt4B5rq9CBAqO36LEYD:be0h16g) ([raw file](https://github.com/sillsdev/web-xforge/blob/cab0dc037fd9fef2d68b1b7f3c164eaa07bb05aa/src/SIL.XForge.Scripture/ClientApp/src/_text.scss#L119)):*
<details><summary><i>Previously, RaymondLuong3 (Raymond Luong) wrote…</i></summary><blockquote>

Ok, I see that text-indent doesn't appear to make a difference for the element, and it is hard to say why it is there in the first place. I'll remove it.
</blockquote></details>

By the way, this comment was supposed to be with regards to `margin: 0em 0.5em`, noting that `0em` could be just `0`.

That line is deleted though, so it's no longer relevant.

**Review by RaymondLuong3 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1219)* status: 13 of 14 files reviewed, 1 unresolved discussion (waiting on @Nateowami)

___
*[src/SIL.XForge.Scripture/ClientApp/src/_text.scss, line 119 at r3](https://reviewable.io/reviews/sillsdev/web-xforge/1219#-MsrF1SDB6eLQcUlYCia:-Mt4wK3T0DR4OXAuE36_:b-n8jzxz) ([raw file](https://github.com/sillsdev/web-xforge/blob/272888bb04fb2e75e4837aedc1879fbf61bbdd9d/src/SIL.XForge.Scripture/ClientApp/src/_text.scss#L119)):*
<details><summary><i>Previously, Nateowami (Nathaniel Paulus) wrote…</i></summary><blockquote>

Ah, OK, makes sense then. Did you test RTL?
</blockquote></details>

Good thinking. It looks like RTL text need to be considered. I decided to just give the note embed margin on both the left and the right side.

**Review by Nateowami — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1219#-:-Mt5Iu4b4QV0H7LuDpJv:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @RaymondLuong3)

**Pull request merged**
