### PR TITLE
SF-2015 Convert font size component to material

### PR DESCRIPTION
**Pull request by siltomato**
This change is [Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1862)

### CODE REVIEW

**Review by siltomato — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1862)* status: 0 of 5 files reviewed, 2 unresolved discussions (waiting on @Nateowami)

___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/font-size/font-size.component.scss` line 26 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/1862#-NWDrBIY0O8ejZHEL8qU:-NWECG7eBYRwHRApPPL7:b6zrrkh) ([raw file](https://github.com/sillsdev/web-xforge/blob/6347b7ec5b563adad52f025776ec657b0c41cd54/src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/font-size/font-size.component.scss#L26)):*
<details><summary><i>Previously, Nateowami (Nathaniel Paulus) wrote…</i></summary><blockquote>

This doesn't work when the UI is RTL.


</blockquote></details>

Good catch.
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/font-size/font-size.component.ts` line 42 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/1862#-NWDpoAfAAKtTbTmckKi:-NWE56Al-st52FEh66Ab:bkwfoyr) ([raw file](https://github.com/sillsdev/web-xforge/blob/6347b7ec5b563adad52f025776ec657b0c41cd54/src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/font-size/font-size.component.ts#L42)):*
<details><summary><i>Previously, Nateowami (Nathaniel Paulus) wrote…</i></summary><blockquote>

What about:
``` ts
  adjustFontSize($event: Event, direction: 1 | -1): void {
    this.fontSize += direction * this.step;
```
</blockquote></details>

Oooh, I like it.

**Review by RaymondLuong3 — CHANGES_REQUESTED** [review]
Nice work, it is looking really good. I had a few comments about the styles that you used. I don't think we need to accept new input values for the step and the initial, unless there was a reason to introduce that.

> Reviewed 3 of 5 files at r1, 1 of 1 files at r3, 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1862#-:-NWhghOkEcWzm8zIXszr:b-ootlgs)* status: all files reviewed, 11 unresolved discussions (waiting on @Nateowami and @siltomato)

___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/font-size/font-size.component.html` line 6 at r2](https://reviewable.io/reviews/sillsdev/web-xforge/1862#-NWhZGyE3qQrX5lFN0Sc:-NWhZGyE3qQrX5lFN0Sd:b-ausajn) ([raw file](https://github.com/sillsdev/web-xforge/blob/aa5f31e726d5b9f36b02dd3f154f25b0c39437ff/src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/font-size/font-size.component.html#L6)):*
> ```HTML
>   [mat-menu-trigger-for]="menu"
>   class="font-size-menu-trigger"
>   [ngClass]="{ 'menu-open': trigger.menuOpen }"
> ```

Nice, I had to look up what this was doing and saw it kept the font size button appear to be selected after it has been clicked.
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/font-size/font-size.component.scss` line 26 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/1862#-NWDrBIY0O8ejZHEL8qU:-NWhc6wj9VdCtdy-3h2D:b-en2kjl) ([raw file](https://github.com/sillsdev/web-xforge/blob/6347b7ec5b563adad52f025776ec657b0c41cd54/src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/font-size/font-size.component.scss#L26)):*
<details><summary><i>Previously, siltomato wrote…</i></summary><blockquote>

Good catch.
</blockquote></details>

I see that the menu is now centered beneath the font size button. I think this is acceptable.
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/font-size/font-size.component.scss` line 2 at r2](https://reviewable.io/reviews/sillsdev/web-xforge/1862#-NWhceZTCx97XVLvxL_i:-NWhceZTCx97XVLvxL_j:biale5g) ([raw file](https://github.com/sillsdev/web-xforge/blob/aa5f31e726d5b9f36b02dd3f154f25b0c39437ff/src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/font-size/font-size.component.scss#L2)):*
> ```SCSS
> :host {
>   display: flex;
> ```

I don't see this having any affect. You could probably remove this.
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/font-size/font-size.component.scss` line 9 at r4](https://reviewable.io/reviews/sillsdev/web-xforge/1862#-NWhdx1TALAL-oQalRB_:-NWhdx1TALAL-oQalRBa:bm3wvym) ([raw file](https://github.com/sillsdev/web-xforge/blob/8ad96e6af5a8d8c8fc4502a810089e2b4343242b/src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/font-size/font-size.component.scss#L9)):*
> ```SCSS
>   > button {
>     &.menu-open {
>       background: #e0e0e0;
> ```

We typically add variable values that might be important into `ClientApp/src/_variables.scss`. Have a look and see if you think it might belong there. Non blocking though.
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/font-size/font-size.component.scss` line 49 at r4](https://reviewable.io/reviews/sillsdev/web-xforge/1862#-NWhexwl2CrM3ug2Cq3h:-NWhexwl2CrM3ug2Cq3i:bx1pjqi) ([raw file](https://github.com/sillsdev/web-xforge/blob/8ad96e6af5a8d8c8fc4502a810089e2b4343242b/src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/font-size/font-size.component.scss#L49)):*
> ```SCSS
> 
>   button {
>     position: relative;
> ```

This doesn't seem necessary.
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/font-size/font-size.component.scss` line 60 at r4](https://reviewable.io/reviews/sillsdev/web-xforge/1862#-NWhfxPfBxL-wQV5VNr0:-NWhfASi3dokk8kpqby9:b897a8x) ([raw file](https://github.com/sillsdev/web-xforge/blob/8ad96e6af5a8d8c8fc4502a810089e2b4343242b/src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/font-size/font-size.component.scss#L60)):*
> ```SCSS
> 
>       &:hover {
>         background-color: #f5f5f5;
> ```

You might be able to find an existing colour you can use in `_variables.scss`
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/font-size/font-size.component.scss` line 64 at r4](https://reviewable.io/reviews/sillsdev/web-xforge/1862#-NWhgQbQ5rwR3wmUj-U_:-NWhgQbQ5rwR3wmUj-Ua:bkme9yn) ([raw file](https://github.com/sillsdev/web-xforge/blob/8ad96e6af5a8d8c8fc4502a810089e2b4343242b/src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/font-size/font-size.component.scss#L64)):*
> ```SCSS
> 
>       &.cdk-focused {
>         ::after {
> ```

I couldn't figure out what this was for, and removing it doesn't appear to change anything.



_Code quote:_
```SCSS
      &.cdk-focused {
        ::after {
```
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/font-size/font-size.component.ts` line 15 at r2](https://reviewable.io/reviews/sillsdev/web-xforge/1862#-NWhZrS18u5kk8PFXXT8:-NWhZrS25105Li0lqxZ9:bb7cqgp) ([raw file](https://github.com/sillsdev/web-xforge/blob/aa5f31e726d5b9f36b02dd3f154f25b0c39437ff/src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/font-size/font-size.component.ts#L15)):*
> ```XML
>   @Output() apply = new EventEmitter<string>();
> 
>   fontSize!: number;
> ```

You don't need the bang here.
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/font-size/font-size.component.ts` line 11 at r4](https://reviewable.io/reviews/sillsdev/web-xforge/1862#-NWhb1gt1KSrkc_VVLp4:-NWhb1gt1KSrkc_VVLp5:b1g1s5v) ([raw file](https://github.com/sillsdev/web-xforge/blob/8ad96e6af5a8d8c8fc4502a810089e2b4343242b/src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/font-size/font-size.component.ts#L11)):*
> ```XML
>   @Input() min: number = 1;
>   @Input() max: number = 3;
>   @Input() step: number = 0.1;
> ```

I don't think we really need to accept initial values for step and initial, unless there was a reason that I am overlooking.
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/font-size/font-size.component.spec.ts` line 48 at r2](https://reviewable.io/reviews/sillsdev/web-xforge/1862#-NWhaOj79vQt-SjwgXgl:-NWhaOj79vQt-SjwgXgm:bsbyzti) ([raw file](https://github.com/sillsdev/web-xforge/blob/aa5f31e726d5b9f36b02dd3f154f25b0c39437ff/src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/font-size/font-size.component.spec.ts#L48)):*
> ```XML
>   it('should open the mat-menu when the button is clicked', async () => {
>     const button = await getMenuTrigger();
>     expect(button).toBeTruthy();
> ```

Add the types to these variables whenever you can and when it is not already explicit i.e. const button = new Button()

**Review by Nateowami — COMMENTED** [review]
I think it would be good to expand the font size stories to show the font size picker when it's open as well, that way we have a test for the positioning of the menu. I think we've had issues with the positioning several times. You may need to add a Storybook decorator to add margin around it.

> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1862#-:-NWnSUuZDpSEZkexMy8Y:b-u8qgta)* status: all files reviewed, 9 unresolved discussions (waiting on @siltomato)

**Review by siltomato — COMMENTED** [review]
I added some stories for the open state as well as clicking the 'adjust' buttons both when active and disabled.

> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1862#-:-NWthXxl3STsCugtqK1i:b-9i02qx)* status: 2 of 6 files reviewed, 9 unresolved discussions (waiting on @RaymondLuong3 and @siltomato)

___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/font-size/font-size.component.html` line 6 at r2](https://reviewable.io/reviews/sillsdev/web-xforge/1862#-NWhZGyE3qQrX5lFN0Sc:-NWtfuBW0QTftXRx9Bdn:bmsvnu3) ([raw file](https://github.com/sillsdev/web-xforge/blob/93750e516bb4faa293e7136987370f916d5ffccb/src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/font-size/font-size.component.html#L6)):*
<details><summary><i>Previously, RaymondLuong3 (Raymond Luong) wrote…</i></summary><blockquote>

Nice, I had to look up what this was doing and saw it kept the font size button appear to be selected after it has been clicked.
</blockquote></details>

Yes, I was trying to keep the appearance as close to the mdc version as possible.
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/font-size/font-size.component.scss` line 2 at r2](https://reviewable.io/reviews/sillsdev/web-xforge/1862#-NWhceZTCx97XVLvxL_i:-NWtZukr5tb9T0Bcl_-l:b-oxq242) ([raw file](https://github.com/sillsdev/web-xforge/blob/93750e516bb4faa293e7136987370f916d5ffccb/src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/font-size/font-size.component.scss#L2)):*
<details><summary><i>Previously, RaymondLuong3 (Raymond Luong) wrote…</i></summary><blockquote>

I don't see this having any affect. You could probably remove this.
</blockquote></details>

Good eyes.
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/font-size/font-size.component.scss` line 9 at r4](https://reviewable.io/reviews/sillsdev/web-xforge/1862#-NWhdx1TALAL-oQalRB_:-NWtg42OEkrbXO476-Dq:b-26idvb) ([raw file](https://github.com/sillsdev/web-xforge/blob/b15b98ea19f13e184fd28c040abb648cdf858940/src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/font-size/font-size.component.scss#L9)):*
<details><summary><i>Previously, RaymondLuong3 (Raymond Luong) wrote…</i></summary><blockquote>

We typically add variable values that might be important into `ClientApp/src/_variables.scss`. Have a look and see if you think it might belong there. Non blocking though.
</blockquote></details>

These hard-coded colors are so specific to this component, I'm not sure it would be valuable to pull them into the variables file.
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/font-size/font-size.component.scss` line 49 at r4](https://reviewable.io/reviews/sillsdev/web-xforge/1862#-NWhexwl2CrM3ug2Cq3h:-NWtbrHrDWVdcdq984vw:b-bveh2v) ([raw file](https://github.com/sillsdev/web-xforge/blob/b15b98ea19f13e184fd28c040abb648cdf858940/src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/font-size/font-size.component.scss#L49)):*
<details><summary><i>Previously, RaymondLuong3 (Raymond Luong) wrote…</i></summary><blockquote>

This doesn't seem necessary.
</blockquote></details>

Good catch.  I included it for positioning the `::after` pseudo element, but apparently all mat-buttons already include this style.
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/font-size/font-size.component.scss` line 60 at r4](https://reviewable.io/reviews/sillsdev/web-xforge/1862#-NWhfxPfBxL-wQV5VNr0:-NWtg_g06IyOuJeCderf:bt3x3b5) ([raw file](https://github.com/sillsdev/web-xforge/blob/b15b98ea19f13e184fd28c040abb648cdf858940/src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/font-size/font-size.component.scss#L60)):*
<details><summary><i>Previously, RaymondLuong3 (Raymond Luong) wrote…</i></summary><blockquote>

You might be able to find an existing colour you can use in `_variables.scss`
</blockquote></details>

This and the other hard-coded color above were the result of color matching to the mdc component, so I'm not sure they'd be much value to factor out to this file.
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/font-size/font-size.component.scss` line 64 at r4](https://reviewable.io/reviews/sillsdev/web-xforge/1862#-NWhgQbQ5rwR3wmUj-U_:-NWta9CqA4RCIRVTBBKj:bxee5vu) ([raw file](https://github.com/sillsdev/web-xforge/blob/b15b98ea19f13e184fd28c040abb648cdf858940/src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/font-size/font-size.component.scss#L64)):*
<details><summary><i>Previously, RaymondLuong3 (Raymond Luong) wrote…</i></summary><blockquote>

I couldn't figure out what this was for, and removing it doesn't appear to change anything.
</blockquote></details>

After clicking the increase or decrease button, the clicked button will remain as a visible circle.  This is to imitate the previous mdc behavior.
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/font-size/font-size.component.ts` line 15 at r2](https://reviewable.io/reviews/sillsdev/web-xforge/1862#-NWhZrS18u5kk8PFXXT8:-NWtd-35DNKmJBpNyMEX:b9cagc4) ([raw file](https://github.com/sillsdev/web-xforge/blob/93750e516bb4faa293e7136987370f916d5ffccb/src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/font-size/font-size.component.ts#L15)):*
<details><summary><i>Previously, RaymondLuong3 (Raymond Luong) wrote…</i></summary><blockquote>

You don't need the bang here.
</blockquote></details>

If I remove it, my compiler complains
```
error TS2564:  Property 'fontSize' has no initializer and is not definitely assigned in the constructor.
```

I could just set it to `initial`, but I didn't want to confuse the fact that this is done on `ngOnInit()`, which I call in the tests after setting any `min`, `max`, and/or `initial` values.
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/font-size/font-size.component.ts` line 11 at r4](https://reviewable.io/reviews/sillsdev/web-xforge/1862#-NWhb1gt1KSrkc_VVLp4:-NWtdaAW1boj1RC_UdVK:bgij8z9) ([raw file](https://github.com/sillsdev/web-xforge/blob/b15b98ea19f13e184fd28c040abb648cdf858940/src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/font-size/font-size.component.ts#L11)):*
<details><summary><i>Previously, RaymondLuong3 (Raymond Luong) wrote…</i></summary><blockquote>

I don't think we really need to accept initial values for step and initial, unless there was a reason that I am overlooking.
</blockquote></details>

Here, I was just trying to make the component more flexible, but I could see how this flexibility is not desirable.  I'll remove these as `@Input`.
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/font-size/font-size.component.spec.ts` line 48 at r2](https://reviewable.io/reviews/sillsdev/web-xforge/1862#-NWhaOj79vQt-SjwgXgl:-NWtk0_HDTaPNU8namDQ:bhy9ot6) ([raw file](https://github.com/sillsdev/web-xforge/blob/93750e516bb4faa293e7136987370f916d5ffccb/src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/font-size/font-size.component.spec.ts#L48)):*
<details><summary><i>Previously, RaymondLuong3 (Raymond Luong) wrote…</i></summary><blockquote>

Add the types to these variables whenever you can and when it is not already explicit i.e. const button = new Button()
</blockquote></details>

Will do.

**Review by siltomato — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1862)* status: 2 of 6 files reviewed, 9 unresolved discussions (waiting on @RaymondLuong3)

___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/font-size/font-size.component.spec.ts` line 48 at r2](https://reviewable.io/reviews/sillsdev/web-xforge/1862#-NWhaOj79vQt-SjwgXgl:-NWtmjAz9Azci62Xjzzk:b-896fix) ([raw file](https://github.com/sillsdev/web-xforge/blob/93750e516bb4faa293e7136987370f916d5ffccb/src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/font-size/font-size.component.spec.ts#L48)):*
<details><summary><i>Previously, siltomato wrote…</i></summary><blockquote>

Will do.
</blockquote></details>

Done.

**Review by Nateowami — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1862)* status: 2 of 6 files reviewed, 11 unresolved discussions (waiting on @RaymondLuong3 and @siltomato)

___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/font-size/font-size.stories.ts` line 16 at r8](https://reviewable.io/reviews/sillsdev/web-xforge/1862#-NWtvHLO1V7jy-azVwyb:-NWtvHLO1V7jy-azVwyc:bu6b1j5) ([raw file](https://github.com/sillsdev/web-xforge/blob/a9fd1bd050d04bd934882e49c2e7f778e61378b0/src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/font-size/font-size.stories.ts#L16)):*
> ```XML
>       imports: [CommonModule, UICommonModule]
>     }),
>     componentWrapperDecorator(story => `<div style="margin:10px 20px">${story}</div>`)
> ```

Here's the screenshot Chromatic is taking for a story where the menu is open:



The reason it's cutting it off is because the menu isn't within the element it's screenshotting (it's in the overlay, which is higher in the element tree).

If you change this to `padding: 0 30px 60px;`, I think we can get the desired result:


I don't think margin will fix it, because vertical margin collapses and doesn't end up expanding the storybook-root element.
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/font-size/font-size.stories.ts` line 45 at r8](https://reviewable.io/reviews/sillsdev/web-xforge/1862#-NWty1dz-rLfSqkOMrNj:-NWty1dz-rLfSqkOMrNk:b-xheioe) ([raw file](https://github.com/sillsdev/web-xforge/blob/a9fd1bd050d04bd934882e49c2e7f778e61378b0/src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/font-size/font-size.stories.ts#L45)):*
> ```XML
> export const IncreaseFontNotAllowed: Story = {
>   ...IncreaseFontAllowed,
>   args: { initial: 3 }
> ```

This doesn't appear to work. I can still increase the font size. And the same for several other stories here.

**Review by siltomato — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1862)* status: 2 of 6 files reviewed, 11 unresolved discussions (waiting on @Nateowami and @RaymondLuong3)

___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/font-size/font-size.stories.ts` line 16 at r8](https://reviewable.io/reviews/sillsdev/web-xforge/1862#-NWtvHLO1V7jy-azVwyb:-NWu9aieAkDyvX04E8zg:b-896fix) ([raw file](https://github.com/sillsdev/web-xforge/blob/a9fd1bd050d04bd934882e49c2e7f778e61378b0/src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/font-size/font-size.stories.ts#L16)):*
<details><summary><i>Previously, Nateowami (Nathaniel Paulus) wrote…</i></summary><blockquote>

Here's the screenshot Chromatic is taking for a story where the menu is open:



The reason it's cutting it off is because the menu isn't within the element it's screenshotting (it's in the overlay, which is higher in the element tree).

If you change this to `padding: 0 30px 60px;`, I think we can get the desired result:


I don't think margin will fix it, because vertical margin collapses and doesn't end up expanding the storybook-root element.
</blockquote></details>

Done.
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/font-size/font-size.stories.ts` line 45 at r8](https://reviewable.io/reviews/sillsdev/web-xforge/1862#-NWty1dz-rLfSqkOMrNj:-NWu9bvg6EstKJ5mZ4dn:bgkuvxv) ([raw file](https://github.com/sillsdev/web-xforge/blob/a9fd1bd050d04bd934882e49c2e7f778e61378b0/src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/font-size/font-size.stories.ts#L45)):*
<details><summary><i>Previously, Nateowami (Nathaniel Paulus) wrote…</i></summary><blockquote>

This doesn't appear to work. I can still increase the font size. And the same for several other stories here.
</blockquote></details>

It looks like I broke it when I removed `initial` as a component `@Input`.  Should be fixed now.

**Review by Nateowami — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1862)* status: 2 of 6 files reviewed, 9 unresolved discussions (waiting on @RaymondLuong3)

___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/font-size/font-size.component.scss` line 64 at r4](https://reviewable.io/reviews/sillsdev/web-xforge/1862#-NWhgQbQ5rwR3wmUj-U_:-NXR8M2iBavBec8gHj4E:b-a0t5qo) ([raw file](https://github.com/sillsdev/web-xforge/blob/743f727a111e9137a7ae796d4d507b461ea71aeb/src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/font-size/font-size.component.scss#L64)):*
<details><summary><i>Previously, siltomato wrote…</i></summary><blockquote>

After clicking the increase or decrease button, the clicked button will remain as a visible circle.  This is to imitate the previous mdc behavior.
</blockquote></details>

Precisely imitating the MDC behavior is not one of our goals, and it's likely to give us issues in the future because we'll be too closely coupled to the Material components using methods that aren't officially supported. In some cases I think it's beneficial (for example, having the button remain highlighted while the menu is opened seems useful).

There are more major changes to Material in the near future (they're going to be based on the official MDC components for web, which they currently aren't).

Our strategy is to use them as-is whenever possible, customizing them using officially supported methods when practical, and when necessary using as little CSS as possible to customize them. In this was we hope to reduce the amount of effort needed when updating to a new version, or making changes to how the component works.

I would recommend trying to shave down this file as much as possible.

**Review by siltomato — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1862)* status: 2 of 6 files reviewed, 9 unresolved discussions (waiting on @RaymondLuong3)

___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/font-size/font-size.component.scss` line 64 at r4](https://reviewable.io/reviews/sillsdev/web-xforge/1862#-NWhgQbQ5rwR3wmUj-U_:-NXVcKXn5YNuYp8Txx7n:bmwc7tt) ([raw file](https://github.com/sillsdev/web-xforge/blob/743f727a111e9137a7ae796d4d507b461ea71aeb/src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/font-size/font-size.component.scss#L64)):*
<details><summary><i>Previously, Nateowami (Nathaniel Paulus) wrote…</i></summary><blockquote>

Precisely imitating the MDC behavior is not one of our goals, and it's likely to give us issues in the future because we'll be too closely coupled to the Material components using methods that aren't officially supported. In some cases I think it's beneficial (for example, having the button remain highlighted while the menu is opened seems useful).

There are more major changes to Material in the near future (they're going to be based on the official MDC components for web, which they currently aren't).

Our strategy is to use them as-is whenever possible, customizing them using officially supported methods when practical, and when necessary using as little CSS as possible to customize them. In this was we hope to reduce the amount of effort needed when updating to a new version, or making changes to how the component works.

I would recommend trying to shave down this file as much as possible.
</blockquote></details>

Ok, removed the style.

**Review by Nateowami — COMMENTED** [review]
This looks good when the share button is present (it always is for admins), but not so much when it's absent:



I think this may be related to how Material positions menus: https://material.angular.io/components/menu/overview#customizing-menu-position.

The positioning doesn't need to be perfect, but it looks a little bit broken like this. (Also consider RTL when making any changes to positioning)

> Reviewed 1 of 1 files at r17.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1862#-:-NXkIdFg7Y75sI7N0eq0:b-id2vqt)* status: 3 of 7 files reviewed, 6 unresolved discussions (waiting on @RaymondLuong3)

**Review by siltomato — COMMENTED** [review]
Fixed.  Also, I turned off menu centering on small screens so it doesn't get cut off when the body padding is less and there is no 'Share' button to give it space.

> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1862#-:-NXmM7W9DUJwCNy8ttaT:b-5yejvs)* status: 1 of 10 files reviewed, 6 unresolved discussions (waiting on @Nateowami and @RaymondLuong3)

**Review by RaymondLuong3 — APPROVED** [review]
It looks good. I tested it on mobile and desktop with the share button visible and not visible. I just saw a minor typo in a comment that should be fix. I'm not too knowledgeable about the storybook changes, but they look good from my point of view.

> Reviewed 1 of 1 files at r7, 1 of 1 files at r11, 1 of 2 files at r15, 6 of 6 files at r18, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1862#-:-NXqYe8BAmm0-afpkWPo:b-7kv90n)* status: all files reviewed, 2 unresolved discussions (waiting on @siltomato)

___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/font-size/font-size.component.html` line 10 at r18](https://reviewable.io/reviews/sillsdev/web-xforge/1862#-NXqVIvQ2Vq0w0c6gXi3:-NXqVIvQ2Vq0w0c6gXi4:b-wnohmz) ([raw file](https://github.com/sillsdev/web-xforge/blob/12a16d6765cd890189400d5682ced357aaf57065/src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/font-size/font-size.component.html#L10)):*
> ```HTML
>   <mat-icon>format_size</mat-icon>
> </button>
> <mat-menu #menu="matMenu" class="font-size-menu" [xPosition]="'before'">
> ```

I've never seen the xPosition input before. What does this do?
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/font-size/font-size.component.scss` line 36 at r18](https://reviewable.io/reviews/sillsdev/web-xforge/1862#-NXqVull21ePGKtGxKXx:-NXqVull21ePGKtGxKXy:b-t9j2sj) ([raw file](https://github.com/sillsdev/web-xforge/blob/12a16d6765cd890189400d5682ced357aaf57065/src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/font-size/font-size.component.scss#L36)):*
> ```SCSS
>     }
> 
>     // Make ripple more visible (otherwise it is light green of button hover text)
> ```

typo: Should be on button hover text
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/font-size/font-size.component.ts` line 15 at r2](https://reviewable.io/reviews/sillsdev/web-xforge/1862#-NWhZrS18u5kk8PFXXT8:-NXqWM3w4ftqARZ0jeuJ:bqjc4zv) ([raw file](https://github.com/sillsdev/web-xforge/blob/17c24d8062abb5b647d49c43ff9c91b8d71110c2/src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/font-size/font-size.component.ts#L15)):*
<details><summary><i>Previously, siltomato wrote…</i></summary><blockquote>

If I remove it, my compiler complains
```
error TS2564:  Property 'fontSize' has no initializer and is not definitely assigned in the constructor.
```

I could just set it to `initial`, but I didn't want to confuse the fact that this is done on `ngOnInit()`, which I call in the tests after setting any `min`, `max`, and/or `initial` values.
</blockquote></details>

Ok, that is a good point that we can always expect it to exist after ngOnInit is run. Alternatively it could just be set to a default number, but I'm happy with the bang approach.

**Pull request merged**
