### PR TITLE
SF-1639 Delay machine engine training until after document transaction commit

### PR DESCRIPTION
**Pull request by pmachapman**
This PR fixes a crash that occurs when running `EngineRuntime.BuildRunner.RunAsync()` in Hangfire when connecting to a new project and resource, that occurs because the project document and text documents have not yet been committed to Mongo.

This crash is fixed by starting the machine engine training only after the project and text documents have been committed to Mongo.

The stack trace from the crash is:
```
An exception occurred during performance of the job.
System.Collections.Generic.KeyNotFoundException: The given key 'bleu' was not present in the dictionary.
at
System.Collections.Generic.Dictionary`2.get_Item(TKeykey)at SIL.Machine.WebApi.Services.EngineRuntime.<>c__DisplayClass40_0.<BuildAsync>b__0(Enginee)
SIL.Machine.WebApi.DataAccess.DataAccessExtensions.ConcurrentUpdateAsync[T](IRepository`1repo, Tentity, Action`1changeAction, CancellationTokenct)
SIL.Machine.WebApi.Services.EngineRuntime.BuildAsync(Engineengine, IBuildHandlerbuildHandler, IJobCancellationTokenjobToken)
SIL.Machine.WebApi.Services.EngineRuntime.BuildAsync(Engineengine, IBuildHandlerbuildHandler, IJobCancellationTokenjobToken)
SIL.Machine.WebApi.Services.EngineRuntime.BuildRunner.RunAsync(StringengineId, IJobCancellationTokenjobToken)
System.Runtime.CompilerServices.TaskAwaiter.GetResult() (edited)
```

The crash occurs at https://github.com/sillsdev/machine/blob/v2.5.11/src/SIL.Machine.WebApi/Services/EngineRuntime.cs#L354

---
This change is [Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1431)

### CODE REVIEW

**Review by RaymondLuong3 — APPROVED** [review]
This may be something that a test could be written for, but I think that the comment will be helpful to prevent regressing this, so I'm happy with this as-is. Thanks!

> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1431#-:-N6i7kHx0enJUSw7gisU:bjjjuk3)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @pmachapman)

**Review by pmachapman — COMMENTED** [review]
Yes, I tried to create a unit test, but it would have required rearchitecting of the MemoryConnection class (env.Connection in ParatextSyncRunnerTests points to the IConnection underlying the MemoryConnection object created by MemoryRealtimeService.ConnectAsync(). I thought a comment might be more appropriate, due to the methods' proximity.

Thanks for the code review, Raymond!

> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1431#-:-N6kimN65lGJhGPxagq2:bfrp7e9)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @pmachapman)

**Comment by Nateowami** [comment]
@pmachapman Am I correct in thinking the steps to reproduce the issue are:
1. Connect project with translation suggestions enabled
2. Observe that in about a minute this error is logged to the console: `System.Collections.Generic.KeyNotFoundException: The given key 'bleu' was not present in the dictionary.`

Does it have to be based off of a project or a resource, or does either work? Does it always happen or only sometimes? Having our testers in the loop for changes like this allows us to be more confident the issue is actually fixed, less likely to accidentally introduce a bug, and usually it gets added to regression tests that are run far into the future to prevent a regression. Ideally we should have a Jira issue for this.

**Review by pmachapman — COMMENTED** [review]
Yes, it only happened when connecting to a project for the first time, and enabling translation suggestions for a resource or project that is not yet in Mongo.

Sorry, I wasn't aware of the process, so I created this more to document the bug and solution, and then a Jira issue could be created, and go through the appropriate channels, etc, if it is confirmed as a real bug.

> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1431#-:-N6v51rY0HxTmXnacTs5:bk6wjci)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @pmachapman)

**Pull request merged**
