### PR TITLE
SF-2958 Remove dependency on MediaObserver

### PR DESCRIPTION
**Pull request by RaymondLuong3**
This PR removes the dependency for the MediaObserver from the angular/flex-layout library and replaces it with the BreakpointObserver.

- - -
This change is [Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/2711)

### CODE REVIEW

**Review by kylebuss — CHANGES_REQUESTED** [review]
Nice job on this! Just one minor suggestion.

> Reviewed 6 of 6 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/2711#-:-O6NcXcV5MN29A7tO3Zp:b-lhhlki)* status: all files reviewed, 2 unresolved discussions (waiting on @RaymondLuong3)

___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.spec.ts` line 23 at r2](https://reviewable.io/reviews/sillsdev/web-xforge/2711#-O6NZjgc-kpfVkwbHVT7:-O6NZjgc-kpfVkwbHVT8:bsp1b69) ([raw file](https://github.com/sillsdev/web-xforge/blob/ffc7b0f9d15a9bc9544c7c6a4404d0a53123d0ef/src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.spec.ts#L23)):*
> ```XML
>   WordGraphArc,
>   createRange
> } from '@sillsdev/machine';
> ```

Have you figured out what extension is sorting your imports? I think we need to have that added so the project installs it for everyone.



_Code quote:_
```XML
import {
  InteractiveTranslatorFactory,
  LatinWordDetokenizer,
  LatinWordTokenizer,
  ProgressStatus,
  TranslationSources,
  WordAlignmentMatrix,
  WordGraph,
  WordGraphArc,
  createRange
} from '@sillsdev/machine';
```
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/multi-viewer/multi-viewer.component.ts` line 51 at r2](https://reviewable.io/reviews/sillsdev/web-xforge/2711#-O6NajVJBdkvBFtTG6A4:-O6NajVJBdkvBFtTG6A5:bu6pawg) ([raw file](https://github.com/sillsdev/web-xforge/blob/ffc7b0f9d15a9bc9544c7c6a4404d0a53123d0ef/src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/multi-viewer/multi-viewer.component.ts#L51)):*
> ```XML
>       ([bigger, xs]) => {
>         const isViewportBigger: boolean = bigger.matches;
>         this.maxAvatars = isViewportBigger ? 6 : 3;
> ```

This confused me initially. I was wondering what happens if `width == Breakpoint.SM`. Do we need to assign `const` here?



_Code quote (i):_
```XML
this.maxAvatars = isViewportBigger ? 6 : 3;
```



_Code snippet (ii):_
```XML
//I wonder if the following would work:
([bigger, xs] => {
  this.maxAvatars = bigger.matches ? 6 : xs.matches ? 1 : this.maxAvatars;
}
```

**Review by RaymondLuong3 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/2711)* status: all files reviewed, 2 unresolved discussions (waiting on @kylebuss)

___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.spec.ts` line 23 at r2](https://reviewable.io/reviews/sillsdev/web-xforge/2711#-O6NZjgc-kpfVkwbHVT7:-O6Nr4dyCYFNTomXEDaf:b80on13) ([raw file](https://github.com/sillsdev/web-xforge/blob/ffc7b0f9d15a9bc9544c7c6a4404d0a53123d0ef/src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.spec.ts#L23)):*
<details><summary><i>Previously, kylebuss (Kyle Buss) wrote…</i></summary><blockquote>

Have you figured out what extension is sorting your imports? I think we need to have that added so the project installs it for everyone.
</blockquote></details>

I looked around, and I can't figure out how my editor knows how to rearrange imports. I think it must be prettier since it is configured to update files on save, but even then I couldn't prove that was the case. I'll post a message in slack.
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/multi-viewer/multi-viewer.component.ts` line 51 at r2](https://reviewable.io/reviews/sillsdev/web-xforge/2711#-O6NajVJBdkvBFtTG6A4:-O6NrZEx6a1_hMGo_q2W:bpjukst) ([raw file](https://github.com/sillsdev/web-xforge/blob/ffc7b0f9d15a9bc9544c7c6a4404d0a53123d0ef/src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/multi-viewer/multi-viewer.component.ts#L51)):*
<details><summary><i>Previously, kylebuss (Kyle Buss) wrote…</i></summary><blockquote>

This confused me initially. I was wondering what happens if `width == Breakpoint.SM`. Do we need to assign `const` here?
</blockquote></details>

Small should be the viewport at 576px. If the breakpoint is exactly 576px, the observable would emit false.
There are actually 3 scenarios here. We want to know whether the viewport is greater than small, between small and xsmall, and xsmall or smaller. What you suggested is different from what existed before.

**Review by kylebuss — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/2711#-:-O6OA-ZT934E4uGaga5x:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @RaymondLuong3)

___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/multi-viewer/multi-viewer.component.ts` line 51 at r2](https://reviewable.io/reviews/sillsdev/web-xforge/2711#-O6NajVJBdkvBFtTG6A4:-O6O-SBx7k8gl4E47naz:bqjkpev) ([raw file](https://github.com/sillsdev/web-xforge/blob/ffc7b0f9d15a9bc9544c7c6a4404d0a53123d0ef/src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/multi-viewer/multi-viewer.component.ts#L51)):*
<details><summary><i>Previously, RaymondLuong3 (Raymond Luong) wrote…</i></summary><blockquote>

Small should be the viewport at 576px. If the breakpoint is exactly 576px, the observable would emit false.
There are actually 3 scenarios here. We want to know whether the viewport is greater than small, between small and xsmall, and xsmall or smaller. What you suggested is different from what existed before.
</blockquote></details>

Thanks for clarifying. The chained ternary operator handles the 3 conditions you've mentioned. However, assigning to `const` is probably easier to read in the long run.



_Code snippet:_
```XML
([bigger, xs] => {
  // assigned 3 but if > SM then = 6 else <= XS then = 1 else between XS and SM stay 3.
  this.maxAvatars = bigger.matches ? 6 : xs.matches ? 1 : this.maxAvatars;
}
```

**Review by RaymondLuong3 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/2711)* status: 6 of 7 files reviewed, 1 unresolved discussion (waiting on @kylebuss)

___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/multi-viewer/multi-viewer.component.ts` line 51 at r2](https://reviewable.io/reviews/sillsdev/web-xforge/2711#-O6NajVJBdkvBFtTG6A4:-O6RhvC79tqLsV8XkxKl:b-lr0duf) ([raw file](https://github.com/sillsdev/web-xforge/blob/ffc7b0f9d15a9bc9544c7c6a4404d0a53123d0ef/src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/multi-viewer/multi-viewer.component.ts#L51)):*
<details><summary><i>Previously, kylebuss (Kyle Buss) wrote…</i></summary><blockquote>

Thanks for clarifying. The chained ternary operator handles the 3 conditions you've mentioned. However, assigning to `const` is probably easier to read in the long run.
</blockquote></details>

Thanks, I missed the chained ternary part. I do like the comment that explains what happens so I've added the changes.

**Review by kylebuss — APPROVED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/2711)* status: all files reviewed, 1 unresolved discussion (waiting on @RaymondLuong3)

**Review by kylebuss — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/2711)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @RaymondLuong3)

**Pull request merged**
