### PR TITLE
Replace MDC CSS variables with SCSS variables

### PR DESCRIPTION
**Pull request by Nateowami**
- Updated a number of instances of `@import` to `@use`
- Renamed theme variables to no longer mention MDC

- - -
This change is [Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/2060)

### CODE REVIEW

**Comment by Nateowami** [comment]
This still needs an issue to be created so there can be some steps to test it. It was something I could work on while in flight, which is why I worked on it and didn't create the issue first.

**Review by nigel-wells — APPROVED** [review]
https://jira.sil.org/browse/SF-2236
:lgtm:

> Reviewed 9 of 9 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/2060#-:-NeBgWx35RR4TlQHhxDn:b-7jylnd)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @Nateowami)

**Comment by nigel-wells** [comment]
Agh, sorry I got carried away and merged without looking at the testing tag. I don't believe I have permissions to undo that sorry @Nateowami

**Comment by Nateowami** [comment]
Not that big a deal. We'll just leave it.

**Pull request merged**
