### PR TITLE
SF-2893 Remove RecordRTC

### PR DESCRIPTION
**Pull request by pmachapman**
This PR removes RecordRTC, and replaces it with the built-in MediaRecorder API.

The MediaRecorder API is supported by Firefox 25+, Chrome 49+, and iOS 14+.

- - -
This change is [Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/2638)

### CODE REVIEW

**Review by RaymondLuong3 — COMMENTED** [review]
Nice! I've tried this out and it works. Just Nathaniel's comment about the inverted logic.

> Reviewed 6 of 6 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/2638#-:-O39GN_HCZWlorHS3gex:b7qiaps)* status: all files reviewed, 1 unresolved discussion (waiting on @pmachapman)

**Review by pmachapman — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/2638)* status: 5 of 6 files reviewed, 1 unresolved discussion (waiting on @Nateowami and @RaymondLuong3)

___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-audio-recorder/checking-audio-recorder.component.ts` line 92 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/2638#-O38AMaW-ZXYQQfJfI33:-O39N8xY5sAJgv5UCu0d:bf2kxy1) ([raw file](https://github.com/sillsdev/web-xforge/blob/920031917a897dc9e584fdf88097b7ae9b282b56/src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-audio-recorder/checking-audio-recorder.component.ts#L92)):*
<details><summary><i>Previously, Nateowami (Nathaniel Paulus) wrote…</i></summary><blockquote>

I think you've inverted the check. Since we're checking if recording is *unsupported*, Shouldn't it be:
``` ts
this.navigator.mediaDevices?.getUserMedia == null || typeof MediaRecorder === 'undefined'
```
If you want to make them both a nullish check, rather than typeof, you could do `window.MediaRecorder == null`, but I don't think it's really better or worse than what you have here.
</blockquote></details>

Done. Fixed - thank you for spotting this!

**Review by RaymondLuong3 — APPROVED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/2638)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @pmachapman)

**Review by RaymondLuong3 — APPROVED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/2638)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @pmachapman)

**Pull request merged**
