### PR TITLE
SF-2961 Skip getting draft build when project has no draft

### PR DESCRIPTION
**Pull request by RaymondLuong3**
Even when the project has no pre-translation build, the tab menu service would attempt to get the last pre-translation build. The error would be caught, but it would still log in the console that there was a 404 error. This change skips attempting to get the pre-translation build when the project's draft config has no last selected translation book (the most direct indication that no pre-translation build exists)

- - -
This change is [Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/2713)

### CODE REVIEW

**Review by josephmyers — APPROVED** [review]
I see that your changes do fix the 404 error thrown on the editor screen, so good job on that. I'm a little confused though about Naveen's original steps -- does your change fix the issue he's seeing? Assuming it does, looks good to me

> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/2713#-:-O6OMVEY43WIoEiRxaXy:b-npvtyr)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @RaymondLuong3)

**Review by RaymondLuong3 — COMMENTED** [review]
You're right, this one is not so straight forward. The 404 that was documented was from our app trying to get the last pre-translation builds when the project is not using the drafting feature. The steps in SF-2961 don't really capture that but are somewhat related.
I'll update SF-2961 with acceptance tests that cover the original issue, and the 404 errors logged in the console.

> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/2713#-:-O6S_k0l3tKpplojhwXj:b-icij10)* status: 2 of 4 files reviewed, all discussions resolved (waiting on @josephmyers)

**Review by josephmyers — APPROVED** [review]
Alright, glad I asked!

> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/2713#-:-O6V2H2D4UeF5yui8fHC:b-j74jl4)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @RaymondLuong3)

**Review by Nateowami — CHANGES_REQUESTED** [review]
I have some changes I want to request, but won't have time to finish reviewing before my next meeting. Temporarily blocking.

**Comment by RaymondLuong3** [comment]
@Nateowami mentioned that checking the lastSelectedTranslationBooks may not give us clear confirmation that a project definitely has a draft build. The better way was to look at the project texts and see if any chapters have `hasDraft` set to true. I've updated this PR with the suggested changes.

**Review by Nateowami — DISMISSED** [review]
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/2713)* status: 0 of 5 files reviewed, 1 unresolved discussion (waiting on @josephmyers and @RaymondLuong3)

___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/tabs/editor-tab-menu.service.ts` line 59 at r3](https://reviewable.io/reviews/sillsdev/web-xforge/2713#-O6bLXgg5jwgCOps8a0i:-O6bLXgg5jwgCOps8a0j:b-8cvtr7) ([raw file](https://github.com/sillsdev/web-xforge/blob/9341aefc87acac9c002c8402a22d3c59127f33f4/src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/tabs/editor-tab-menu.service.ts#L59)):*
> ```XML
>           ParatextService.isResource(projectDoc.data.paratextId)
>             ? of(undefined)
>             : this.draftGenerationService.getLastCompletedBuild(projectDoc.id),
> ```

Why are we still getting the build?

**Review by RaymondLuong3 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/2713)* status: 0 of 5 files reviewed, 1 unresolved discussion (waiting on @josephmyers and @Nateowami)

___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/tabs/editor-tab-menu.service.ts` line 59 at r3](https://reviewable.io/reviews/sillsdev/web-xforge/2713#-O6bLXgg5jwgCOps8a0i:-O6beKpf54Ke4QdQMnFG:b-r7spvv) ([raw file](https://github.com/sillsdev/web-xforge/blob/9341aefc87acac9c002c8402a22d3c59127f33f4/src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/tabs/editor-tab-menu.service.ts#L59)):*
<details><summary><i>Previously, Nateowami (Nathaniel Paulus) wrote…</i></summary><blockquote>

Why are we still getting the build?
</blockquote></details>

Thanks, I have made the change to no longer depend on the build now that we can query the texts for a project.

**Comment by RaymondLuong3** [comment]
@Nateowami Can you update your review on this?

**Review by Nateowami — COMMENTED** [review]
> Reviewed 1 of 5 files at r3, 1 of 2 files at r4.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/2713)* status: 2 of 5 files reviewed, all discussions resolved (waiting on @josephmyers)

**Review by josephmyers — CHANGES_REQUESTED** [review]
Good job fixing the two scenarios listed in [the JIRA ticket](https://jira.sil.org/secure/RapidBoard.jspa?rapidView=93&view=detail&selectedIssue=SF-2961#). There's a third, related, that I'm seeing throw a 404, and I've added it to the ticket. We need to make sure we cover this one, too. The call is coming from `draft-generation.component.ts`. Thanks

> Reviewed 2 of 5 files at r3, 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/2713#-:-O7RVpQG2u2NZQYc0yXW:btqw78y)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @RaymondLuong3)

**Review by RaymondLuong3 — COMMENTED** [review]
Thanks. I have found the place to check and added a check to only ask serval for a build when `preTranslate` is enabled and the list of translation books is not null.

> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/2713#-:-O7VoxhiBCxvZAs8DIPZ:b-4rhf4z)* status: 3 of 7 files reviewed, all discussions resolved (waiting on @josephmyers and @Nateowami)

**Review by josephmyers — CHANGES_REQUESTED** [review]
I think this looks okay, just fix the tests!

> Reviewed 4 of 4 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/2713#-:-O7XId1n6B5fF3mN1diA:bs7wmpu)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @RaymondLuong3)

**Review by RaymondLuong3 — COMMENTED** [review]
I have updated the test

> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/2713#-:-O7ZohVaA5Uf_In70vpt:b-frgb1a)* status: 6 of 7 files reviewed, all discussions resolved (waiting on @josephmyers)

**Review by Nateowami — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/2713)* status: 6 of 7 files reviewed, 1 unresolved discussion (waiting on @josephmyers and @RaymondLuong3)

___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/tabs/editor-tab-menu.service.spec.ts` line 123 at r7](https://reviewable.io/reviews/sillsdev/web-xforge/2713#-O7Zs-qvBZOU5__qVGa9:-O7Zs-qvBZOU5__qVGaA:b7txs0f) ([raw file](https://github.com/sillsdev/web-xforge/blob/ea3d22172f262afe12e0a5b55e4382734c272d47/src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/tabs/editor-tab-menu.service.spec.ts#L123)):*
> ```XML
>       expect(items.length).toBe(2);
>       expect(items[0].type).toBe('history');
>       expect(items[0].disabled).toBeFalsy();
> ```

I would think we would be expecting `toBeFalse()`. I can't think of any reason this value should be something like null, undefined, the empty string, or any of the other possible falsy values: https://developer.mozilla.org/en-US/docs/Glossary/Falsy

**Comment by RaymondLuong3** [comment]
I just tried it out, and it appears all the `disabled` values are undefined. That was my initial impression was that the disabled property would not be defined.

**Review by Nateowami — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/2713)* status: 6 of 7 files reviewed, 1 unresolved discussion (waiting on @josephmyers and @RaymondLuong3)

___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/tabs/editor-tab-menu.service.spec.ts` line 123 at r7](https://reviewable.io/reviews/sillsdev/web-xforge/2713#-O7Zs-qvBZOU5__qVGa9:-O7_ccPE-PunpT-PtArP:b2lqwaz) ([raw file](https://github.com/sillsdev/web-xforge/blob/ea3d22172f262afe12e0a5b55e4382734c272d47/src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/tabs/editor-tab-menu.service.spec.ts#L123)):*
<details><summary><i>Previously, Nateowami (Nathaniel Paulus) wrote…</i></summary><blockquote>

I would think we would be expecting `toBeFalse()`. I can't think of any reason this value should be something like null, undefined, the empty string, or any of the other possible falsy values: https://developer.mozilla.org/en-US/docs/Glossary/Falsy
</blockquote></details>

I see. It appears the disabled property only gets set when it's true. Which is a little odd.

**Review by josephmyers — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/2713)* status: all files reviewed, 1 unresolved discussion (waiting on @Nateowami)

___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/tabs/editor-tab-menu.service.spec.ts` line 123 at r7](https://reviewable.io/reviews/sillsdev/web-xforge/2713#-O7Zs-qvBZOU5__qVGa9:-O7bsALA1haxtCFQEAdI:bkvwvwc) ([raw file](https://github.com/sillsdev/web-xforge/blob/ea3d22172f262afe12e0a5b55e4382734c272d47/src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/tabs/editor-tab-menu.service.spec.ts#L123)):*
<details><summary><i>Previously, Nateowami (Nathaniel Paulus) wrote…</i></summary><blockquote>

I see. It appears the disabled property only gets set when it's true. Which is a little odd.
</blockquote></details>

Is it even being used? I don't see usages other than tests -- when are we disabling, not removing, tab options?

**Review by josephmyers — APPROVED** [review]
:lgtm:

> Reviewed 3 of 3 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/2713#-:-O7fSfGg56leNxf0wndS:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @Nateowami)

**Pull request merged**
