### PR TITLE
SF-1159 Hide import questions button when offline

### PR DESCRIPTION
**Pull request by RaymondLuong3**
* avoid making a network request unless a user is online
* query for transcelerator questions when returning online

---
This change is [Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/885)

### CODE REVIEW

**Review by Nateowami — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/885#-:-MNPeaFI4CQYpp7dfxSq:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @RaymondLuong3)

___
*[src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking-overview/checking-overview.component.ts, line 126 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/885#-MNPZLV85kQ6Hy_LGF4i:-MNPZLV85kQ6Hy_LGF4j:b2pynlb) ([raw file](https://github.com/sillsdev/web-xforge/blob/81f36f1c69bcbb07ca3f6ae35c9c65ac27e15d41/src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking-overview/checking-overview.component.ts#L126)):*
> ```XML
>   }
> 
>   get hasTransceleratorQuestions(): boolean {
> ```

The name of this getter isn't really correct. Maybe change the if in the template to `*ngIf="hasTransceleratorQuestions && pwaService.isOnline"`.

**Review by Nateowami — CHANGES_REQUESTED** [review]
Actually I mean to request changes.

> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/885#-:-MNPhRnu5z5eRTAgfClL:b-otd1dv)* status: all files reviewed, 1 unresolved discussion (waiting on @RaymondLuong3)

**Review by RaymondLuong3 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/885)* status: 1 of 3 files reviewed, 1 unresolved discussion (waiting on @Nateowami)

___
*[src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking-overview/checking-overview.component.ts, line 126 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/885#-MNPZLV85kQ6Hy_LGF4i:-MNPiXrl1_sw0jvnnb50:b-44fks2) ([raw file](https://github.com/sillsdev/web-xforge/blob/81f36f1c69bcbb07ca3f6ae35c9c65ac27e15d41/src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking-overview/checking-overview.component.ts#L126)):*
<details><summary><i>Previously, Nateowami (Nathaniel Paulus) wrote…</i></summary><blockquote>

The name of this getter isn't really correct. Maybe change the if in the template to `*ngIf="hasTransceleratorQuestions && pwaService.isOnline"`.
</blockquote></details>

Good thinking.I remember reading that it is good practice to keep logic out of the template, so I changed the name of the property instead.

**Review by Nateowami — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/885#-:-MNPj2xN3fjPNLh0b5FR:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved

**Comment by irahopkinson** [comment]
___
*[src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking-overview/checking-overview.component.ts, line 43 at r2](https://reviewable.io/reviews/sillsdev/web-xforge/885#-MNQu5cl50ywAsA87wnH:-MNQu5cl50ywAsA87wnI:b-i7enwr) ([raw file](https://github.com/sillsdev/web-xforge/blob/c0a6bb02ea39cdab6ac041a877ac322f1811b915/src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking-overview/checking-overview.component.ts#L43)):*
> ```
> private _hasTransceleratorQuestions
> ```
nit style: private properties don't use an underscore in general. We only use an underscore on a private property to distinguish it from an associated public getter/setter that we want to to have the same name.

**Pull request merged**
