### PR TITLE
doc: add section .NET performance profiling

### PR DESCRIPTION
**Pull request by marksvc**
This change is [Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1589)

### CODE REVIEW

**Review by RaymondLuong3 — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1589)* status: all files reviewed, 1 unresolved discussion (waiting on @marksvc)

___
*[`README.md` line 600 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/1589#-NGryiRzBBZwxyGjLFT_:-NGryiS--qI39brncPe6:bqjgdlh) ([raw file](https://github.com/sillsdev/web-xforge/blob/8538f458aeb7457d98a4d26330a27960051ce656/README.md#L600)):*
> ```Markdown
> 
> ```bash
> sudo perf record --pid=$(pgrep SIL.XForge.Scri) -g --timestamp-filename # Then press Ctrl+C when done. Optionally also use --output perf.data-my-report-filename
> ```

Is this intentional, or should it say SIL.XForge.Scripture ?



_Code quote:_
```Markdown
--pid=$(pgrep SIL.XForge.Scri) 
```

**Comment by marksvc** [comment]
*[`README.md` line 600 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/1589#-NGryiRzBBZwxyGjLFT_:-NGxg8Mf2rVTeoT9WLxp:bheferi) ([raw file](https://github.com/sillsdev/web-xforge/blob/8538f458aeb7457d98a4d26330a27960051ce656/README.md#L600)):*
<details><summary><i>Previously, RaymondLuong3 (Raymond Luong) wrote…</i></summary><blockquote>

Is this intentional, or should it say SIL.XForge.Scripture ?
</blockquote></details>

Good catch. It is actually intentional. pgrep seems to have a limit on the number of characters it accepts for the pattern, so I needed to truncate it in this way.

**Review by RaymondLuong3 — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1589)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @marksvc)

___
*[`README.md` line 600 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/1589#-NGryiRzBBZwxyGjLFT_:-NH0RB826Fsmia1XM_j1:b-1inq7h) ([raw file](https://github.com/sillsdev/web-xforge/blob/8538f458aeb7457d98a4d26330a27960051ce656/README.md#L600)):*
<details><summary><i>Previously, marksvc wrote…</i></summary><blockquote>

Good catch. It is actually intentional. pgrep seems to have a limit on the number of characters it accepts for the pattern, so I needed to truncate it in this way. 
</blockquote></details>

Oh, that makes sense. Nice.

**Review by Nateowami — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1589)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @marksvc)

___
*[`README.md` line 600 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/1589#-NGryiRzBBZwxyGjLFT_:-NH0x6hy530p6q548QqD:b-zher5r) ([raw file](https://github.com/sillsdev/web-xforge/blob/8538f458aeb7457d98a4d26330a27960051ce656/README.md#L600)):*
<details><summary><i>Previously, RaymondLuong3 (Raymond Luong) wrote…</i></summary><blockquote>

Oh, that makes sense. Nice.
</blockquote></details>

Can we have a comment of some sort? It makes sense, but everyone that reads it will be thinking it looks wrong.

**Review by Nateowami — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1589)* status: all files reviewed, 1 unresolved discussion (waiting on @marksvc)

**Comment by marksvc** [comment]
*[`README.md` line 600 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/1589#-NGryiRzBBZwxyGjLFT_:-NH61aw125Rfs0PeqSDd:bc3dow) ([raw file](https://github.com/sillsdev/web-xforge/blob/8538f458aeb7457d98a4d26330a27960051ce656/README.md#L600)):*
<details><summary><i>Previously, Nateowami (Nathaniel Paulus) wrote…</i></summary><blockquote>

Can we have a comment of some sort? It makes sense, but everyone that reads it will be thinking it looks wrong.
</blockquote></details>

Good point. How about this, where I truncate it a little more. It will work  the same, but doesn't look as much like a mistake.

**Review by Nateowami — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1589#-:-NIp5R9b1hrn3ghSSrsf:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @marksvc)

**Comment by Nateowami** [comment]
@marksvc I'm disabling auto merge because #1607 is large and probably almost ready to merge. I'm doing some final testing. I'd prefer avoiding rebasing it. In general that isn't much of a concern, but it's a fairly large PR.

**Comment by Nateowami** [comment]
By the way, don't take this as something you need to be watching out for in general. Feel free to enable automerge as you see fit. This is an exceptional/unusual situation.

**Comment by marksvc** [comment]
:+1: Ok no problem. Got it, thanks!

**Pull request merged**
