### PR TITLE
SF-2405 Improve AudioPlayer loading of short audio files in Chromium

### PR DESCRIPTION
**Pull request by callumlaw17**
This PR improves the loading an initialization process of AudioPlayer to ignore any errors which are thrown during the seek which is done to force duration calculation - this seems to occur within Chromium when loading short (less than 1 second) MP3 files.

Replication steps:
1. Using Chrome navigate to Community Checking > Manage Questions
2. Add a question with a short audio file, such as [this one](https://drive.google.com/file/d/1lJ49e7JY8Vu0Pir-uMFIOZCZ_R4BLQUS/view?usp=drive_link)
3. Navigate to Community Checking > Questions & answers
4. Select the question that was just created
5. Note that the play button is crossed out indicating that the audio could not be loaded but if you click on the button the audio 
will play correctly.

This PR increases the time taken to initialize the AudioPlayer as audio loading and the duration calculation are now done sequentially rather than in parallel which meant that some tests had to be updated to wait until the AudioPlayer was initialized before running.

- - -
This change is [Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/2250)

### CODE REVIEW

**Review by Nateowami — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/2250)* status: 0 of 5 files reviewed, 2 unresolved discussions (waiting on @callumlaw17)

___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/shared/audio/audio-player.ts` line 62 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/2250#-NlzDIRa1hYeKwFTcLrr:-NlzDIRa1hYeKwFTcLrs:btumoi9) ([raw file](https://github.com/sillsdev/web-xforge/blob/9614fc2c15b2c1fb9a0135da866c6938759186fe/src/SIL.XForge.Scripture/ClientApp/src/app/shared/audio/audio-player.ts#L62)):*
> ```XML
>     this.audio.addEventListener('error', () => {
>       // Sometimes the duration calculation within audioIsLoaded will throw an error - we can safely ignore this
>       if (this.doingAudioDurationCalculation) {
> ```

I'm not sure we want to suppress errors this broadly. Perhaps we could check:
``` ts
this.audio.error.code === MediaError.MEDIA_ERR_NETWORK && this.audio.error.message === "PIPELINE_ERROR_READ: FFmpegDemuxer: demuxer seek failed"
```
... and only suppress the error if that's true? That would prevent other errors from getting silently lost.
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/shared/audio/audio-player.ts` line 172 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/2250#-NlzDend3Yiv4HADM1r3:-NlzDend3Yiv4HADM1r4:bpnq1hu) ([raw file](https://github.com/sillsdev/web-xforge/blob/9614fc2c15b2c1fb9a0135da866c6938759186fe/src/SIL.XForge.Scripture/ClientApp/src/app/shared/audio/audio-player.ts#L172)):*
> ```XML
> 
>   private audioIsLoaded(): void {
>     // In Chromium the duration of some audio sources aren't known after loading.
> ```

I recall adding this workaround at some point in the past. Have you searched for a better workaround that doesn't have this same problem? It's been several years since I originally did this, and since then the workaround has just been copied.

**Review by callumlaw17 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/2250)* status: 0 of 5 files reviewed, 2 unresolved discussions (waiting on @Nateowami)

___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/shared/audio/audio-player.ts` line 62 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/2250#-NlzDIRa1hYeKwFTcLrr:-NlzPC9I35mlcHfqwlX_:bkjtxtz) ([raw file](https://github.com/sillsdev/web-xforge/blob/9614fc2c15b2c1fb9a0135da866c6938759186fe/src/SIL.XForge.Scripture/ClientApp/src/app/shared/audio/audio-player.ts#L62)):*
<details><summary><i>Previously, Nateowami (Nathaniel Paulus) wrote…</i></summary><blockquote>

I'm not sure we want to suppress errors this broadly. Perhaps we could check:
``` ts
this.audio.error.code === MediaError.MEDIA_ERR_NETWORK && this.audio.error.message === "PIPELINE_ERROR_READ: FFmpegDemuxer: demuxer seek failed"
```
... and only suppress the error if that's true? That would prevent other errors from getting silently lost.
</blockquote></details>

I did consider this but thought it might be a bit fragile if the error message changed.

I think this isn't an issue as I updated it to work sequentially so that we can be confident all errors thrown while `this.doingAudioDurationCalculation` is true are related to that seek (unless I am missing something).
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/shared/audio/audio-player.ts` line 172 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/2250#-NlzDend3Yiv4HADM1r3:-NlzQ6036CWCie2gdIST:bt47z0v) ([raw file](https://github.com/sillsdev/web-xforge/blob/9614fc2c15b2c1fb9a0135da866c6938759186fe/src/SIL.XForge.Scripture/ClientApp/src/app/shared/audio/audio-player.ts#L172)):*
<details><summary><i>Previously, Nateowami (Nathaniel Paulus) wrote…</i></summary><blockquote>

I recall adding this workaround at some point in the past. Have you searched for a better workaround that doesn't have this same problem? It's been several years since I originally did this, and since then the workaround has just been copied.
</blockquote></details>

I did have a look and it seemed that this was still the "recommended" solution as far as I could see.

**Review by Nateowami — COMMENTED** [review]
I'm sorry; I'd completely forgotten about this PR. Just took a look at what still needed to be reviewed, and saw I had started a reply on this one.

> Reviewed 1 of 5 files at r1.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/2250#-:-NnjSIxC4QazWBJqIQU-:bybgevg)* status: 1 of 5 files reviewed, 1 unresolved discussion (waiting on @callumlaw17)

___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/shared/audio/audio-player.ts` line 62 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/2250#-NlzDIRa1hYeKwFTcLrr:-Nm2qf85EG06C-pLOMr-:bmqq0vr) ([raw file](https://github.com/sillsdev/web-xforge/blob/9614fc2c15b2c1fb9a0135da866c6938759186fe/src/SIL.XForge.Scripture/ClientApp/src/app/shared/audio/audio-player.ts#L62)):*
<details><summary><i>Previously, callumlaw17 wrote…</i></summary><blockquote>

I did consider this but thought it might be a bit fragile if the error message changed.

I think this isn't an issue as I updated it to work sequentially so that we can be confident all errors thrown while `this.doingAudioDurationCalculation` is true are related to that seek (unless I am missing something).
</blockquote></details>

That's a very valid point. I think there's probably a middle ground though where we don't ignore every single error for a duration of time, but we also don't require the message to be this exactly. Maybe:
``` ts
this.audio.error.code === MediaError.MEDIA_ERR_NETWORK && this.audio.error.message.includes("PIPELINE_ERROR_READ")
```

**Review by callumlaw17 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/2250)* status: 1 of 5 files reviewed, 1 unresolved discussion (waiting on @Nateowami)

___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/shared/audio/audio-player.ts` line 62 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/2250#-NlzDIRa1hYeKwFTcLrr:-NnkEOt0Dvb0j4jMfeN6:b-q738wr) ([raw file](https://github.com/sillsdev/web-xforge/blob/9614fc2c15b2c1fb9a0135da866c6938759186fe/src/SIL.XForge.Scripture/ClientApp/src/app/shared/audio/audio-player.ts#L62)):*
<details><summary><i>Previously, Nateowami (Nathaniel Paulus) wrote…</i></summary><blockquote>

That's a very valid point. I think there's probably a middle ground though where we don't ignore every single error for a duration of time, but we also don't require the message to be this exactly. Maybe:
``` ts
this.audio.error.code === MediaError.MEDIA_ERR_NETWORK && this.audio.error.message.includes("PIPELINE_ERROR_READ")
```
</blockquote></details>

With a bit more testing it looks as though just changing this to work sequentially is enough to avoid the error. I think that this is may be due to a change in a different commit or upstream software update as I don't believe that this was the case previously. Either way the error is no longer being raised (on this branch, it still is on master) so I have gone ahead and removed the code to handle ignoring it.

**Review by Nateowami — CHANGES_REQUESTED** [review]
> Reviewed 1 of 5 files at r1.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/2250)* status: 2 of 5 files reviewed, 2 unresolved discussions (waiting on @callumlaw17)

___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-answers/checking-question/checking-question.component.spec.ts` line 328 at r2](https://reviewable.io/reviews/sillsdev/web-xforge/2250#-NnpFHqNBhnBKU01mXes:-NnpFHqOCAJIV2LMi3kj:bl5bt0v) ([raw file](https://github.com/sillsdev/web-xforge/blob/04816a20d72f8fc28f626c5cb9d494ad4c533839/src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-answers/checking-question/checking-question.component.spec.ts#L328)):*
> ```XML
>       await this.scriptureAudio.componentInstance.audio?.status$
>         .pipe(takeWhile<AudioStatus>(val => val === AudioStatus.Initializing))
>         .toPromise();
> ```

`toPromise()` is deprecated, which will be apparent if you change the first line to `await (this.scriptureAudio.componentInstance as SingleButtonAudioPlayerComponent).audio?.status$`

And the same elsewhere in this PR. The warnings would show up if the types were specified.

**Review by callumlaw17 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/2250)* status: 2 of 5 files reviewed, 2 unresolved discussions (waiting on @Nateowami)

___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-answers/checking-question/checking-question.component.spec.ts` line 328 at r2](https://reviewable.io/reviews/sillsdev/web-xforge/2250#-NnpFHqNBhnBKU01mXes:-NnpYaat047H4D5Wwr8z:b-896fix) ([raw file](https://github.com/sillsdev/web-xforge/blob/04816a20d72f8fc28f626c5cb9d494ad4c533839/src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-answers/checking-question/checking-question.component.spec.ts#L328)):*
<details><summary><i>Previously, Nateowami (Nathaniel Paulus) wrote…</i></summary><blockquote>

`toPromise()` is deprecated, which will be apparent if you change the first line to `await (this.scriptureAudio.componentInstance as SingleButtonAudioPlayerComponent).audio?.status$`

And the same elsewhere in this PR. The warnings would show up if the types were specified.
</blockquote></details>

Done.

**Review by Nateowami — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r2, 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/2250#-:-NoXbV7K6q5PfnVTVWiJ:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @callumlaw17)

___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/shared/audio/audio-player.ts` line 62 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/2250#-NlzDIRa1hYeKwFTcLrr:-NoXThpe7BLJEiC4JM5_:b-ec019f) ([raw file](https://github.com/sillsdev/web-xforge/blob/9614fc2c15b2c1fb9a0135da866c6938759186fe/src/SIL.XForge.Scripture/ClientApp/src/app/shared/audio/audio-player.ts#L62)):*
<details><summary><i>Previously, callumlaw17 wrote…</i></summary><blockquote>

With a bit more testing it looks as though just changing this to work sequentially is enough to avoid the error. I think that this is may be due to a change in a different commit or upstream software update as I don't believe that this was the case previously. Either way the error is no longer being raised (on this branch, it still is on master) so I have gone ahead and removed the code to handle ignoring it.
</blockquote></details>

Excellent.

**Pull request merged**
