### PR TITLE
Fix GHA workflow to set up .NET version

### PR DESCRIPTION
**Pull request by Nateowami**
It looks like we were checking the version, but not actually doing anything to set it up, so we just got whatever version happened to be installed.

- - -
This change is [Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1611)

### CODE REVIEW

**Review by Nateowami — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1611)* status: 0 of 1 files reviewed, all discussions resolved

___
*[`.github/workflows/build-and-test.yml` line 19 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/1611#-NHVu3wK8aOuGcCt5DFD:-NHVu3wK8aOuGcCt5DFE:bw1qlr) ([raw file](https://github.com/sillsdev/web-xforge/blob/ee74a6c43097b71436824eb4d93f362963334585/.github/workflows/build-and-test.yml#L19)):*
> ```YAML
>         # move to.
>         os: ["ubuntu-20.04", "ubuntu-22.04"]
>         dotnet_version: ["6.0.301"]
> ```

`actions/setup-dotnet@v3` supports syntax like `6.0.x`, but I generally prefer to be very specific about version numbers and manually update them when moving from one version to another.
___
*[`.github/workflows/build-and-test.yml` line 30 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/1611#-NHVuJQsC5aSj4Je4aK8:-NHVuJQsC5aSj4Je4aK9:b-s1yjqn) ([raw file](https://github.com/sillsdev/web-xforge/blob/ee74a6c43097b71436824eb4d93f362963334585/.github/workflows/build-and-test.yml#L30)):*
> ```YAML
> 
>       - name: "Deps: .NET"
>         uses: actions/setup-dotnet@v3
> ```

See https://github.com/actions/setup-dotnet for documentation

**Review by Nateowami — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1611)* status: 0 of 1 files reviewed, all discussions resolved

___
*[`.github/workflows/build-and-test.yml` line 19 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/1611#-NHVu3wK8aOuGcCt5DFD:-NHW-XDwAeTKph7NsdKr:b-faoobc) ([raw file](https://github.com/sillsdev/web-xforge/blob/ee74a6c43097b71436824eb4d93f362963334585/.github/workflows/build-and-test.yml#L19)):*
<details><summary><i>Previously, Nateowami (Nathaniel Paulus) wrote…</i></summary><blockquote>

`actions/setup-dotnet@v3` supports syntax like `6.0.x`, but I generally prefer to be very specific about version numbers and manually update them when moving from one version to another.
</blockquote></details>

Since we can't control the exact version that gets used, I've made this variable.
___
*[`.github/workflows/build-and-test.yml` line 54 at r2](https://reviewable.io/reviews/sillsdev/web-xforge/1611#-NHW-cXJ6UIvIx2hpJK7:-NHW-cXJ6UIvIx2hpJK8:b-7cmuz4) ([raw file](https://github.com/sillsdev/web-xforge/blob/9f2affb8af7e459a872901c1b1db652cdce876df/.github/workflows/build-and-test.yml#L54)):*
> ```YAML
>         run: |
>           set -xueo pipefail
>           [[ $(dotnet --version) == ${{matrix.dotnet_version}} ]]
> ```

This check is being removed because a) the image may come with a newer version, and short of uninstalling first, that's pretty much out of our control, and b) our `.csproj` file specifies `6.0`, and if that's unavailable, there will be errors.

**Review by marksvc — APPROVED** [review]
Good work, thank you.

> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1611#-:-NHW70DCErtnpf9WAalh:bnc1x7s)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @Nateowami)

___
*[`.github/workflows/build-and-test.yml` line 19 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/1611#-NHVu3wK8aOuGcCt5DFD:-NHW5rm14YQt47FjNaK5:bez2wyx) ([raw file](https://github.com/sillsdev/web-xforge/blob/ee74a6c43097b71436824eb4d93f362963334585/.github/workflows/build-and-test.yml#L19)):*
<details><summary><i>Previously, Nateowami (Nathaniel Paulus) wrote…</i></summary><blockquote>

Since we can't control the exact version that gets used, I've made this variable.
</blockquote></details>

(Just for context, in `"6.0.*"`, IIRC the `*` is part of matching in the now-removed `[[ $(dotnet --version) == ${{matrix.dotnet_version}} ]]`.)

I'm somewhat confused about what you're saying. Are you meaning:
- You like to be able to strictly specify and control the version number, like being able to specify, for example, "6.0.2", but
- the setup-dotnet action doesn't _let_ you do that, so you are doing the next best thing, which is "6.0.x"
?

Hmm, it looks like the setup-dotnet does support specifying the patch-level version, tho.
___
*[`.github/workflows/build-and-test.yml` line 30 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/1611#-NHVuJQsC5aSj4Je4aK8:-NHW6xkaA1urzbCDe-rj:b-9755fa) ([raw file](https://github.com/sillsdev/web-xforge/blob/ee74a6c43097b71436824eb4d93f362963334585/.github/workflows/build-and-test.yml#L30)):*
<details><summary><i>Previously, Nateowami (Nathaniel Paulus) wrote…</i></summary><blockquote>

See https://github.com/actions/setup-dotnet for documentation
</blockquote></details>

Thank you.
___
*[`.github/workflows/build-and-test.yml` line 54 at r2](https://reviewable.io/reviews/sillsdev/web-xforge/1611#-NHW-cXJ6UIvIx2hpJK7:-NHW6XloEYDY0r_m4sCZ:bj5d3ja) ([raw file](https://github.com/sillsdev/web-xforge/blob/9f2affb8af7e459a872901c1b1db652cdce876df/.github/workflows/build-and-test.yml#L54)):*
<details><summary><i>Previously, Nateowami (Nathaniel Paulus) wrote…</i></summary><blockquote>

This check is being removed because a) the image may come with a newer version, and short of uninstalling first, that's pretty much out of our control, and b) our `.csproj` file specifies `6.0`, and if that's unavailable, there will be errors.
</blockquote></details>

Does this mean that even when running setup-dotnet for 6.0.x, the `dotnet` command still reports version 7? (and so perhaps setup-dotnet is just making sure the capability for 6.0.x is in place.)

**Review by Nateowami — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1611)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @Nateowami)

___
*[`.github/workflows/build-and-test.yml` line 19 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/1611#-NHVu3wK8aOuGcCt5DFD:-NHW7_Ns6sIOg-3aG4X1:b-52h8c4) ([raw file](https://github.com/sillsdev/web-xforge/blob/ee74a6c43097b71436824eb4d93f362963334585/.github/workflows/build-and-test.yml#L19)):*
> Hmm, it looks like the setup-dotnet does support specifying the patch-level version, tho.

It does, but it's in effect useless, since it may not be the version we end up getting to use, since a newer version of 6.0 might already be installed.
___
*[`.github/workflows/build-and-test.yml` line 54 at r2](https://reviewable.io/reviews/sillsdev/web-xforge/1611#-NHW-cXJ6UIvIx2hpJK7:-NHWCG5O7-1dQ1w3emu0:b-is1xmy) ([raw file](https://github.com/sillsdev/web-xforge/blob/9f2affb8af7e459a872901c1b1db652cdce876df/.github/workflows/build-and-test.yml#L54)):*
<details><summary><i>Previously, marksvc wrote…</i></summary><blockquote>

Does this mean that even when running setup-dotnet for 6.0.x, the `dotnet` command still reports version 7? (and so perhaps setup-dotnet is just making sure the capability for 6.0.x is in place.)
</blockquote></details>

Multiple versions of the .NET SDK could be installed, so if 7.0 is already installed and we install 6.0, we may still get 7.0 when running `dotnet --version`.

**Pull request merged**
