### PR TITLE
Migrator: PtdaSyncAll: test, improve reporting, increment queue count

### PR DESCRIPTION
**Pull request by marksvc**
These depend on unsubmitted PR #764.
I will plan to rebase onto master once the dependency PR is submitted. But someone else can if they beat me to it. 
(Done)

---
This change is [Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/766)

### CODE REVIEW

**Comment by marksvc** [comment]
Some tests added were overseeing an "await to Wait" change that was moved to a prior PR.

**Review by ddaspit — CHANGES_REQUESTED** [review]
> Reviewed 9 of 9 files at r1.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/766)* status: all files reviewed, 4 unresolved discussions (waiting on @marksvc)

___
*[src/Migrations/PtdaSyncAll/Startup.cs, line 57 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/766#-MFAQflD5JFEOlP4MekZ:-MFAQflD5JFEOlP4Mek_:bgonxud) ([raw file](https://github.com/sillsdev/web-xforge/blob/2030c75b45c4fea06c6fe924ccbc04bb4ff59e72/src/Migrations/PtdaSyncAll/Startup.cs#L57)):*
> ```Smalltalk
> 
>             services.AddSFMachine(Configuration);
>             services.AddTransient<IParatextSyncRunner>();
> ```

Is the DI container smart enough to figure out which implementation goes with this interface?
___
*[src/Migrations/PtdaSyncAll/SyncAll.cs, line 45 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/766#-MFAQOxH--QHEw2lT5w0:-MFAQOxH--QHEw2lT5w1:bori2mp) ([raw file](https://github.com/sillsdev/web-xforge/blob/2030c75b45c4fea06c6fe924ccbc04bb4ff59e72/src/Migrations/PtdaSyncAll/SyncAll.cs#L45)):*
> ```Smalltalk
>         public async Task SynchronizeAllProjectsAsync(IWebHost webHost, bool doSynchronizations)
>         {
>             IRealtimeService realtimeService = webHost.Services.GetService<IRealtimeService>();
> ```

It would probably be better to add `SyncAll` to the DI container and inject these dependencies in the constructor. 
___
*[src/Migrations/PtdaSyncAll/SyncAll.cs, line 57 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/766#-MFARAMI7D5gb8G2nLDM:-MFARAMI7D5gb8G2nLDN:bdxmaje) ([raw file](https://github.com/sillsdev/web-xforge/blob/2030c75b45c4fea06c6fe924ccbc04bb4ff59e72/src/Migrations/PtdaSyncAll/SyncAll.cs#L57)):*
> ```Smalltalk
>                 Logger.Log($"{Program.Bullet1} PT project {sfProject.ShortName}, "
>                     + $"PT project id {sfProject.ParatextId}, SF project id {sfProject.Id}.");
>                 IEnumerable<string> projectSfAdminUserIds = sfProject.UserRoles
> ```

This LINQ query is being executed multiple times. It might be better to use `ToList()` or `ToArray()`.
___
*[src/Migrations/PtdaSyncAll/SyncAll.cs, line 61 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/766#-MFARO2L8KiMrDSH30R8:-MFARO2L8KiMrDSH30R9:bdxmaje) ([raw file](https://github.com/sillsdev/web-xforge/blob/2030c75b45c4fea06c6fe924ccbc04bb4ff59e72/src/Migrations/PtdaSyncAll/SyncAll.cs#L61)):*
> ```Smalltalk
>                 if (projectSfAdminUserIds.Count() < 1)
>                 {
>                     IEnumerable<string> projectSfUserIds = sfProject.UserRoles.Select(ur => ur.Key);
> ```

This LINQ query is being executed multiple times. It might be better to use `ToList()` or `ToArray()`.

**Review by ddaspit — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r3.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/766#-:-MFThSPz4Yj1gsnr3jwX:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by irahopkinson — APPROVED** [review]
> Reviewed 2 of 2 files at r4.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/766)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
