### PR TITLE
SF-2379 Allow selection of draft translation books

### PR DESCRIPTION
**Pull request by siltomato**
Adds ability for user to independently select training and translation books.

- - -
This change is [Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/2222)

### CODE REVIEW

**Review by Nateowami — COMMENTED** [review]
> when `draftConfig.alternateTrainingSourceEnabled` is true

I can't think of any reason why this restriction should be in place. It make sense even for a back translation project. You want to select only certain books to be used for training (the ones that are actually of good quality), and you want to select books to have drafted. I don't think there's any relation to whether it's an alternate source.

> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/2222#-:-Nl0jUw7DugWdN76wJjR:b-955zmx)* status: 0 of 8 files reviewed, all discussions resolved (waiting on @pmachapman)

**Review by Nateowami — CHANGES_REQUESTED** [review]
A few comments; haven't reviewed everything yet.

> Reviewed 3 of 8 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/2222#-:-Nl11oIu3kdgB4wr5U4D:b-rfbl1g)* status: 3 of 8 files reviewed, 2 unresolved discussions (waiting on @siltomato)

___
*[`-- commits` line 2 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/2222#-Nl1-O9m047zGu4WcNEj):*
I think you've mentioned the wrong Jira issue. It should be SF-2379. Also, I think the description would be more accurate as something like "Allow selecting which books to translate". That's what's really changing. Previously it was possible to select which books to train on, but all books would be translated. 
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-generation.component.scss` line 145 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/2222#-Nl115sl0lzNWKXNlUsW:-Nl115sl0lzNWKXNlUsX:bam6rgk) ([raw file](https://github.com/sillsdev/web-xforge/blob/a444cfee758d7590c482827683c8daf98afbca0c/src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-generation.component.scss#L145)):*
> ```SCSS
> @include media-breakpoint('<', sm) {
>   // Hide the button icons to save space on mobile
>   .mat-button-base:not(.backout-button) mat-icon {
> ```

Is it really saving space? It looks to me like the buttons are all on their own line, meaning they have plenty of room.

**Review by siltomato — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/2222)* status: 2 of 8 files reviewed, 2 unresolved discussions (waiting on @Nateowami)

___
*[`-- commits` line 2 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/2222#-Nl1-O9m047zGu4WcNEj):*
<details><summary><i>Previously, Nateowami (Nathaniel Paulus) wrote…</i></summary><blockquote>

I think you've mentioned the wrong Jira issue. It should be SF-2379. Also, I think the description would be more accurate as something like "Allow selecting which books to translate". That's what's really changing. Previously it was possible to select which books to train on, but all books would be translated.
</blockquote></details>

Oops... got my signals crossed with the 'resume checking' issue.  Changed referenced jira and description.
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-generation.component.scss` line 145 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/2222#-Nl115sl0lzNWKXNlUsW:-Nl1bfnH7xltW7sofW5J:bdo0pjw) ([raw file](https://github.com/sillsdev/web-xforge/blob/a444cfee758d7590c482827683c8daf98afbca0c/src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-generation.component.scss#L145)):*
<details><summary><i>Previously, Nateowami (Nathaniel Paulus) wrote…</i></summary><blockquote>

Is it really saving space? It looks to me like the buttons are all on their own line, meaning they have plenty of room.
</blockquote></details>

It looks when the draft is queued or in progress, the "Cancel generation" and "Preview last draft" buttons are side-by-side, and there is not enough room in mobile views when those buttons have icons.

Changed the rule to only apply to these buttons.

**Review by siltomato — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/2222)* status: 3 of 8 files reviewed, 2 unresolved discussions (waiting on @Nateowami)

___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-generation-steps/draft-generation-steps.component.html` line 17 at r2](https://reviewable.io/reviews/sillsdev/web-xforge/2222#-Nl3VDVu4OYU7ufaU4pz:-Nl4QtYU9fdic3kmEjIp:bjwoncq) ([raw file](https://github.com/sillsdev/web-xforge/blob/33bd5761fa481d557f2de58e87eec43173892da7/src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-generation-steps/draft-generation-steps.component.html#L17)):*
<details><summary><i>Previously, Nateowami (Nathaniel Paulus) wrote…</i></summary><blockquote>

I think the "select which books to translate" option should be first. I know this is opposite of chronological order, but I think it's a logical order for the user. It's probably the question they are more likely to expect. The first time I saw the option to select training books, I mistakenly thought it was to select which books to translate. Then after asking them what they're trying to translate, ask them which ones are good enough to help with the endeavor.
</blockquote></details>

Makes sense.  Changed.
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-generation-steps/draft-generation-steps.component.html` line 20 at r2](https://reviewable.io/reviews/sillsdev/web-xforge/2222#-Nl3VRRCCeIYmHo7-LA2:-NlA6ioT7Iq2V_wawzrl:b3haplz) ([raw file](https://github.com/sillsdev/web-xforge/blob/33bd5761fa481d557f2de58e87eec43173892da7/src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-generation-steps/draft-generation-steps.component.html#L20)):*
<details><summary><i>Previously, Nateowami (Nathaniel Paulus) wrote…</i></summary><blockquote>

We try to avoid disabling buttons in most situations, since it's not great feedback for the user. Instead, this should be enabled all the time, but if you click it before selecting any books, an error message should appear (probably between the button and the books) saying something like "No books selected. Select which books to translate to continue." It should match the appearance of other such messages. Same for the generate draft button.
</blockquote></details>

Done.  Used notice component outlined 'error' with no icon.
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-generation-steps/draft-generation-steps.component.html` line 38 at r2](https://reviewable.io/reviews/sillsdev/web-xforge/2222#-Nl3W-hE9kQ1DzLr16Qd:-Nl4TfCYA-wtStxbJoTI:blcd5il) ([raw file](https://github.com/sillsdev/web-xforge/blob/33bd5761fa481d557f2de58e87eec43173892da7/src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-generation-steps/draft-generation-steps.component.html#L38)):*
<details><summary><i>Previously, Nateowami (Nathaniel Paulus) wrote…</i></summary><blockquote>

As of right now, the only mat-stroked buttons are in this component. For one reason or another, we haven't used them as our secondary button. I don't dislike them, but I dislike inconsistency. OK, maybe I've grown to dislike them a little, when beside buttons with a very different appearance. I'm looking forward to the "filled tonal" buttons from [the Material v3 spec](https://m3.material.io/components/buttons/guidelines#d6699132-3536-4cca-9460-79b019d6116c). But we could already theme buttons to do almost the same thing now. If we do so, it should be a concerted effort to change how we theme buttons.
</blockquote></details>

Interesting read.  I think I like stroked look for being more recognizable as a button.  To me, the text-only look works better for more optional, dismissable actions like "Learn more", "Dismiss" and "Got it".  Although... being next to a flat/raised/stroked button seems to help the text-only button feel more button-like.  What about the "< Back" button above the stepper to navigate back to the main draft generation screen?  It is currently stroked.  Do you think this needs to be changed to text-only?

One interesting thing mentioned in the m3 design spec is that "each screen should contain a single prominent button for the primary action."  I wonder if we should demote the "Generate new draft" button so that the "Preview draft" button is the single primary action.

On a side note, I'm not sure about the move to full rounded buttons... it makes them look like chips =).

**Review by Nateowami — COMMENTED** [review]
Thanks for your work on this. In my testing it looks good. However, I can't focus well enough to review it, so I'm going to put that off until later.

> Reviewed 1 of 4 files at r3.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/2222#-:-NlAP7qt8aBYvzUpDfr6:bzegdgw)* status: 4 of 8 files reviewed, 2 unresolved discussions (waiting on @siltomato)

___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-generation-steps/draft-generation-steps.component.html` line 38 at r2](https://reviewable.io/reviews/sillsdev/web-xforge/2222#-Nl3W-hE9kQ1DzLr16Qd:-NlAOjcm0ExwTWouR_Dx:bdk43it) ([raw file](https://github.com/sillsdev/web-xforge/blob/33bd5761fa481d557f2de58e87eec43173892da7/src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-generation-steps/draft-generation-steps.component.html#L38)):*
<details><summary><i>Previously, siltomato wrote…</i></summary><blockquote>

Interesting read.  I think I like stroked look for being more recognizable as a button.  To me, the text-only look works better for more optional, dismissable actions like "Learn more", "Dismiss" and "Got it".  Although... being next to a flat/raised/stroked button seems to help the text-only button feel more button-like.  What about the "< Back" button above the stepper to navigate back to the main draft generation screen?  It is currently stroked.  Do you think this needs to be changed to text-only?

One interesting thing mentioned in the m3 design spec is that "each screen should contain a single prominent button for the primary action."  I wonder if we should demote the "Generate new draft" button so that the "Preview draft" button is the single primary action.

On a side note, I'm not sure about the move to full rounded buttons... it makes them look like chips =).
</blockquote></details>

I think you're right about it being less recognizable. Perhaps we should use stroked buttons for now and come up with a secondary button (probably a lighter color) that we can switch to in the future.

I agree the m3 buttons look somewhat like chips, but I chips aren't used all that often, and if the rounded buttons are used throughout, I don't think it will cause that much confusion.
___
*[`src/SIL.XForge.Scripture/ClientApp/src/assets/i18n/non_checking_en.json` line 178 at r3](https://reviewable.io/reviews/sillsdev/web-xforge/2222#-NlAFI539VtFBlZrTny0:-NlAFI539VtFBlZrTny1:b-mpnunr) ([raw file](https://github.com/sillsdev/web-xforge/blob/8b516c97e242e2ff54f0122b7f88f2b0903a25d4/src/SIL.XForge.Scripture/ClientApp/src/assets/i18n/non_checking_en.json#L178)):*
> ```JSON
>     "choose_books_for_training_error": "No books selected. Select training books to continue.",
>     "choose_books_for_training_subheader": "Select books that have been proofed.",
>     "choose_books_for_training": "Choose books for training the generator",
> ```

I don't really like the term "generator" here. Maybe "engine"? In my opinion, generate seems to work fairly well as a verb, but isn't as clear as a noun.

**Review by siltomato — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/2222)* status: 3 of 8 files reviewed, all discussions resolved (waiting on @Nateowami)

___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-generation-steps/draft-generation-steps.component.html` line 38 at r2](https://reviewable.io/reviews/sillsdev/web-xforge/2222#-Nl3W-hE9kQ1DzLr16Qd:-NlP93gKDmNuV0ALf1RT:bn0t75m) ([raw file](https://github.com/sillsdev/web-xforge/blob/33bd5761fa481d557f2de58e87eec43173892da7/src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-generation-steps/draft-generation-steps.component.html#L38)):*
<details><summary><i>Previously, Nateowami (Nathaniel Paulus) wrote…</i></summary><blockquote>

I think you're right about it being less recognizable. Perhaps we should use stroked buttons for now and come up with a secondary button (probably a lighter color) that we can switch to in the future.

I agree the m3 buttons look somewhat like chips, but I chips aren't used all that often, and if the rounded buttons are used throughout, I don't think it will cause that much confusion.
</blockquote></details>

Reverted back to 'stroked' button.
___
*[`src/SIL.XForge.Scripture/ClientApp/src/assets/i18n/non_checking_en.json` line 178 at r3](https://reviewable.io/reviews/sillsdev/web-xforge/2222#-NlAFI539VtFBlZrTny0:-NlP3Thv5l6mDokO15Aq:btr3n7a) ([raw file](https://github.com/sillsdev/web-xforge/blob/8b516c97e242e2ff54f0122b7f88f2b0903a25d4/src/SIL.XForge.Scripture/ClientApp/src/assets/i18n/non_checking_en.json#L178)):*
<details><summary><i>Previously, Nateowami (Nathaniel Paulus) wrote…</i></summary><blockquote>

I don't really like the term "generator" here. Maybe "engine"? In my opinion, generate seems to work fairly well as a verb, but isn't as clear as a noun.
</blockquote></details>

Would 'language model' work?  'Engine' might suffer from the same similar confusing imagery as 'generator'.

**Review by Nateowami — APPROVED** [review]
:lgtm:

> Reviewed 2 of 4 files at r3, 3 of 3 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/2222#-:-NlPz7nVBhocD8VuNHHB:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @siltomato)

___
*[`src/SIL.XForge.Scripture/ClientApp/src/assets/i18n/non_checking_en.json` line 178 at r3](https://reviewable.io/reviews/sillsdev/web-xforge/2222#-NlAFI539VtFBlZrTny0:-NlPkv4o3nHJHWI3BYbs:b9ths63) ([raw file](https://github.com/sillsdev/web-xforge/blob/8b516c97e242e2ff54f0122b7f88f2b0903a25d4/src/SIL.XForge.Scripture/ClientApp/src/assets/i18n/non_checking_en.json#L178)):*
<details><summary><i>Previously, siltomato wrote…</i></summary><blockquote>

Would 'language model' work?  'Engine' might suffer from the same similar confusing imagery as 'generator'.
</blockquote></details>

I think that's better.

**Pull request merged**
