### PR TITLE
SF-1364 Create separate sharing settings for translate tool

### PR DESCRIPTION
**Pull request by Nateowami**
To-do:
- [x] Fix broken front-end test that fails to actually update the project
- [x] Maybe think of some back-end tests to write?

Done:
- Add migration
- Fix some of the back-end logic surrounding when users can be invited

---
This change is [Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1099)

### CODE REVIEW

**Review by Nateowami — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1099)* status: 0 of 45 files reviewed, 1 unresolved discussion (waiting on @Nateowami)

___
*[src/RealtimeServer/scriptureforge/services/sf-project-migrations.ts, line 120 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/1099#-MfekU_DBfiF9G-_EbqN:-MfekU_DBfiF9G-_EbqO:b-oexccu) ([raw file](https://github.com/sillsdev/web-xforge/blob/7e5b98eb2929ff8e6ed09a0ffb9fe799f052aac1/src/RealtimeServer/scriptureforge/services/sf-project-migrations.ts#L120)):*
> ```XML
>     const ops = [];
>     if (doc.data.translateConfig == null) {
>       ops.push({ p: ['translateConfig'], oi: {} });
> ```

Should this actually be necessary? My recollection is that the tests failed without it.

**Review by Nateowami — COMMENTED** [review]
I can't reproduce the link sharing error. Can you provide exact steps?

> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1099#-:-MgCsFMS7D-WzstdlMCU:b-gxbn9i)* status: 40 of 45 files reviewed, 6 unresolved discussions (waiting on @RaymondLuong3)

___
*[src/RealtimeServer/scriptureforge/services/sf-project-migrations.spec.ts, line 133 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/1099#-MftS4ao-ZPRi6k0tzx3:-MgCSyUtClVyAjOk8Sdy:b-qu6n94) ([raw file](https://github.com/sillsdev/web-xforge/blob/7e5b98eb2929ff8e6ed09a0ffb9fe799f052aac1/src/RealtimeServer/scriptureforge/services/sf-project-migrations.spec.ts#L133)):*
<details><summary><i>Previously, RaymondLuong3 (Raymond Luong) wrote…</i></summary><blockquote>

> ```
>       expect(projectDoc.data.translateConfig.shareEnabled).toBeDefined();
>       expect(projectDoc.data.translateConfig.shareLevel).toBeDefined();
> ```
Nit: You could even expect share enabled to be false, and share level to be specific.
</blockquote></details>

Good point. Done.
___
*[src/SIL.XForge.Scripture/ClientApp/src/app/settings/settings.component.html, line 100 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/1099#-MftUK2T6qntPau5-QNc:-MgCT1bF3Kkl2aBt99hB:b-5fzz90) ([raw file](https://github.com/sillsdev/web-xforge/blob/7e5b98eb2929ff8e6ed09a0ffb9fe799f052aac1/src/SIL.XForge.Scripture/ClientApp/src/app/settings/settings.component.html#L100)):*
<details><summary><i>Previously, RaymondLuong3 (Raymond Luong) wrote…</i></summary><blockquote>

> ```
> <mdc-radio id="radio-translateShareLevel-anyone"
> ```
Nit: Not sure if there is a reason that we're mixing kebab case with camel case. I see it in the checking share settings too.
</blockquote></details>

Typically we would use kebab-case for ids. `translateShareLevel` is the name of the form control, and it's being mentioned in the id.
___
*[src/SIL.XForge.Scripture/ClientApp/src/app/shared/share/share-control.component.ts, line 93 at r2](https://reviewable.io/reviews/sillsdev/web-xforge/1099#-MgBciE0CKXB0kr8ZgFR:-MgCVIKV57STbtcIBkfz:b-tocb4m) ([raw file](https://github.com/sillsdev/web-xforge/blob/47e481e6d69db9bb60ef79c258f908808e97276c/src/SIL.XForge.Scripture/ClientApp/src/app/shared/share/share-control.component.ts#L93)):*
<details><summary><i>Previously, RaymondLuong3 (Raymond Luong) wrote…</i></summary><blockquote>

> ```
>   get roles(): ProjectRoleInfo[] {
> ```
Could you add a comment for what this is?
</blockquote></details>

I've changed the name so it should be more descriptive now.
___
*[src/SIL.XForge.Scripture/ClientApp/src/app/shared/share/share-control.component.ts, line 101 at r2](https://reviewable.io/reviews/sillsdev/web-xforge/1099#-MgBcmxxDmmqsA8i2Yol:-MgCVi8T4jMIRrKqEwGA:ba24kbg) ([raw file](https://github.com/sillsdev/web-xforge/blob/47e481e6d69db9bb60ef79c258f908808e97276c/src/SIL.XForge.Scripture/ClientApp/src/app/shared/share/share-control.component.ts#L101)):*
<details><summary><i>Previously, RaymondLuong3 (Raymond Luong) wrote…</i></summary><blockquote>

> ```
> get availableRoles(): string[] {
> ```
Could you add a comment for what this is?
</blockquote></details>

I've renamed the getter above. Do you think it still needs a comment?
___
*[src/SIL.XForge.Scripture/ClientApp/src/app/shared/share/share-control.component.ts, line 113 at r2](https://reviewable.io/reviews/sillsdev/web-xforge/1099#-MgBcvrj2m7MTcBXsG5g:-MgCWgrNCYOnnU_aCF2T:bl7zz5x) ([raw file](https://github.com/sillsdev/web-xforge/blob/47e481e6d69db9bb60ef79c258f908808e97276c/src/SIL.XForge.Scripture/ClientApp/src/app/shared/share/share-control.component.ts#L113)):*
<details><summary><i>Previously, RaymondLuong3 (Raymond Luong) wrote…</i></summary><blockquote>

> ```
>           SF_PROJECT_RIGHTS.hasRight(project, this.userService.currentUserId, SFProjectDomain.Questions, Operation.View)
> ```
This appears to say that only if the current user has the right to view questions can he share this role. Is that correct?
</blockquote></details>

Yes. However, at present I think it will always be true (even a translation observer can view questions). A few lines down we have a similar check.

This check is only done client-side, and right now I think the only limitation is that Community Checkers cannot invite users to be Translation Observers.
___
*[src/SIL.XForge.Scripture/ClientApp/src/app/shared/share/share-control.component.spec.ts, line 278 at r2](https://reviewable.io/reviews/sillsdev/web-xforge/1099#-MgBdySz-MOmxmrUh1ds:-MgChkbb2EU1u9RpJNmB:b-b1ddyi) ([raw file](https://github.com/sillsdev/web-xforge/blob/47e481e6d69db9bb60ef79c258f908808e97276c/src/SIL.XForge.Scripture/ClientApp/src/app/shared/share/share-control.component.spec.ts#L278)):*
<details><summary><i>Previously, RaymondLuong3 (Raymond Luong) wrote…</i></summary><blockquote>

> ```
> expect(env.shareLink).not.toBeNull(); // broken
> ```
Is that comment supposed to be there?
</blockquote></details>

Thanks. Good catch.
___
*[src/SIL.XForge.Scripture/Services/SFProjectService.cs, line 361 at r2](https://reviewable.io/reviews/sillsdev/web-xforge/1099#-MgBhOiN5oGpwroADXs9:-MgChnXeDAYJY7T0qZyT:b-jed8cs) ([raw file](https://github.com/sillsdev/web-xforge/blob/47e481e6d69db9bb60ef79c258f908808e97276c/src/SIL.XForge.Scripture/Services/SFProjectService.cs#L361)):*
<details><summary><i>Previously, RaymondLuong3 (Raymond Luong) wrote…</i></summary><blockquote>

> ```
> Boolean isAdmin 
> ```
Is there a difference between bool and Boolean? If not, let's stick to bool.
</blockquote></details>

Good catch. I didn't even realize C# had two bool types (Java does as well though, so I guess it's not that surprising).

**Review by irahopkinson — CHANGES_REQUESTED** [review]
Wow, there is a lot of work here. This looks close after a few fix-ups.

> Reviewed 38 of 45 files at r1, 2 of 2 files at r2, 5 of 5 files at r3.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1099#-:-MgFdKnGARmZhybp-xof:bhyxjrh)* status: all files reviewed, 11 unresolved discussions (waiting on @Nateowami and @RaymondLuong3)

___
*[src/RealtimeServer/scriptureforge/services/sf-project-migrations.ts, line 117 at r3](https://reviewable.io/reviews/sillsdev/web-xforge/1099#-MgFWteA-Vgp1xWnrtOp:-MgFWteA-Vgp1xWnrtOq:bgnkd77) ([raw file](https://github.com/sillsdev/web-xforge/blob/830c55f1a48d33be45d62a5fda4bcdf8445e8940/src/RealtimeServer/scriptureforge/services/sf-project-migrations.ts#L117)):*
> ```
> migrateDoc
> ```
I don't see that you are migrating the property name change for `checkingShareEnabled` and `checkingShareLevel`?
___
*[src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking.component.ts, line 88 at r3](https://reviewable.io/reviews/sillsdev/web-xforge/1099#-MgFUH6cBYbVUODSkscX:-MgFUH6cBYbVUODSkscY:b-8t08xn) ([raw file](https://github.com/sillsdev/web-xforge/blob/830c55f1a48d33be45d62a5fda4bcdf8445e8940/src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking.component.ts#L88)):*
> ```
> isProjectAdmin
> ```
This should be `private` as it shouldn't be made available to the HTML.
___
*[src/SIL.XForge.Scripture/ClientApp/src/app/shared/share/share-control.component.ts, line 97 at r3](https://reviewable.io/reviews/sillsdev/web-xforge/1099#-MgFaOJv2GOw31ZaoJ1-:-MgFaOJv2GOw31ZaoJ10:bdxji1q) ([raw file](https://github.com/sillsdev/web-xforge/blob/830c55f1a48d33be45d62a5fda4bcdf8445e8940/src/SIL.XForge.Scripture/ClientApp/src/app/shared/share/share-control.component.ts#L97)):*
> ```
> get availableRoles(): string[]
> ```
This looks like it could/should be `private`.
___
*[src/SIL.XForge.Scripture/ClientApp/src/app/shared/share/share-control.component.spec.ts, line 184 at r3](https://reviewable.io/reviews/sillsdev/web-xforge/1099#-MgFb-6E1vozKYJGMs65:-MgFb-6E1vozKYJGMs66:b24n5xi) ([raw file](https://github.com/sillsdev/web-xforge/blob/830c55f1a48d33be45d62a5fda4bcdf8445e8940/src/SIL.XForge.Scripture/ClientApp/src/app/shared/share/share-control.component.spec.ts#L184)):*
> ```
>     env.realtimeService
>       .get<SFProjectDoc>(SFProjectDoc.COLLECTION, 'project01')
>       .submitJson0Op(op => op.set<CheckingShareLevel>(p => p.checkingConfig.shareLevel, CheckingShareLevel.Anyone));
> ```
If you put this an appropriately named method it would be more readable. Here and below.
___
*[src/SIL.XForge.Scripture/Services/ParatextService.cs, line 989 at r3](https://reviewable.io/reviews/sillsdev/web-xforge/1099#-MgFN9vW628HgaYI8bev:-MgFN9vW628HgaYI8bew:bspv6qc) ([raw file](https://github.com/sillsdev/web-xforge/blob/830c55f1a48d33be45d62a5fda4bcdf8445e8940/src/SIL.XForge.Scripture/Services/ParatextService.cs#L989)):*
> ```
> UserRoles.Observer => SFProjectRole.SFObserver,
> ```
If you are keeping things the same, this should be `PTObserver`. Can you explain why we are changing this? If this was meant to stay the same I would recommend you use the rename features of your IDE (in VSCode use F2) so it gets them all changed for you so errors like this don't happen.
___
*[test/SIL.XForge.Scripture.Tests/Services/SFProjectServiceTests.cs, line 176 at r3](https://reviewable.io/reviews/sillsdev/web-xforge/1099#-MgFSJbL-l_MZwujsO9C:-MgFSJbL-l_MZwujsO9D:bgnj8i7) ([raw file](https://github.com/sillsdev/web-xforge/blob/830c55f1a48d33be45d62a5fda4bcdf8445e8940/test/SIL.XForge.Scripture.Tests/Services/SFProjectServiceTests.cs#L176)):*
> ```
> "setup - user should already be a project user"
> ```
nit: this message should really be on the next assert.

**Review by RaymondLuong3 — CHANGES_REQUESTED** [review]
The steps I took were:
1. As project admin, enable link sharing in the translate tool and copy link.
2. Login as a non-paratext user. Paste link into browser.
3. Observe the error message.

In the debugger I identified where the error occurs. I'll leave a comment on that line.

> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1099#-:-MgH50az9e-uNvdSBJok:b7i5fbp)* status: all files reviewed, 8 unresolved discussions (waiting on @Nateowami)

___
*[src/SIL.XForge.Scripture/ClientApp/src/app/shared/share/share-control.component.ts, line 101 at r2](https://reviewable.io/reviews/sillsdev/web-xforge/1099#-MgBcmxxDmmqsA8i2Yol:-MgH5yOdCrnc1xjcvXM3:b-u71qx8) ([raw file](https://github.com/sillsdev/web-xforge/blob/47e481e6d69db9bb60ef79c258f908808e97276c/src/SIL.XForge.Scripture/ClientApp/src/app/shared/share/share-control.component.ts#L101)):*
<details><summary><i>Previously, Nateowami (Nathaniel Paulus) wrote…</i></summary><blockquote>

I've renamed the getter above. Do you think it still needs a comment?
</blockquote></details>

How about renaming this shareableRoles, or userShareableRoles? Then it may not need a commet.
___
*[src/SIL.XForge.Scripture/Services/SFProjectService.cs, line 535 at r3](https://reviewable.io/reviews/sillsdev/web-xforge/1099#-MgH6eGrBL3Z_ZuaOFfg:-MgH6eGrBL3Z_ZuaOFfh:bhmmxv4) ([raw file](https://github.com/sillsdev/web-xforge/blob/830c55f1a48d33be45d62a5fda4bcdf8445e8940/src/SIL.XForge.Scripture/Services/SFProjectService.cs#L535)):*
> ```
>                 bool linkSharing = projectDoc.Data.CheckingConfig.ShareEnabled &&
>                     projectDoc.Data.CheckingConfig.ShareLevel == CheckingShareLevel.Anyone;
> ```
It appears that this is not currently handling link sharing for the translate app. It would be good to write a test for this.

**Review by Nateowami — COMMENTED** [review]
@raymondluong3 I believe in order to reproduce the problem sharing or link sharing for community checking needs to be disabled. That's probably why you were seeing it and I wasn't.

> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1099#-:-MgIWZRACpXgYPiztM2M:b3ciipb)* status: 39 of 45 files reviewed, 7 unresolved discussions (waiting on @irahopkinson and @RaymondLuong3)

___
*[src/RealtimeServer/scriptureforge/services/sf-project-migrations.ts, line 117 at r3](https://reviewable.io/reviews/sillsdev/web-xforge/1099#-MgFWteA-Vgp1xWnrtOp:-MgH84NU292zmB_bkZDY:b-t81wf1) ([raw file](https://github.com/sillsdev/web-xforge/blob/830c55f1a48d33be45d62a5fda4bcdf8445e8940/src/RealtimeServer/scriptureforge/services/sf-project-migrations.ts#L117)):*
<details><summary><i>Previously, irahopkinson (Ira Hopkinson) wrote…</i></summary><blockquote>

> ```
> migrateDoc
> ```
I don't see that you are migrating the property name change for `checkingShareEnabled` and `checkingShareLevel`?
</blockquote></details>

I think you're mixing up the model as it exists in the DB and the JSONRPC data sent from the client to the server.

Here's how the model now looks in the DB:
``` json
  {
    "translationSuggestionsEnabled": true,
    "source": { },
    "shareEnabled": false,
    "shareLevel": "specific"
  },
  "checkingConfig": {
    "checkingEnabled": true,
    "usersSeeEachOthersResponses": true,
    "shareEnabled": false,
    "shareLevel": "specific"
  }
```
Previously it looked about like this:
``` json
  {
    "translationSuggestionsEnabled": true,
    "source": { }
  },
  "checkingConfig": {
    "checkingEnabled": true,
    "usersSeeEachOthersResponses": true,
    "shareEnabled": false,
    "shareLevel": "specific"
  }
```

What has changed is `SFProjectSettings` and `SFProjectService.UpdateSettingsAsync`.
___
*[src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking.component.ts, line 88 at r3](https://reviewable.io/reviews/sillsdev/web-xforge/1099#-MgFUH6cBYbVUODSkscX:-MgH3ISi6Kd8fHTjiIv8:b-896fix) ([raw file](https://github.com/sillsdev/web-xforge/blob/830c55f1a48d33be45d62a5fda4bcdf8445e8940/src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking.component.ts#L88)):*
<details><summary><i>Previously, irahopkinson (Ira Hopkinson) wrote…</i></summary><blockquote>

> ```
> isProjectAdmin
> ```
This should be `private` as it shouldn't be made available to the HTML.
</blockquote></details>

Done.
___
*[src/SIL.XForge.Scripture/ClientApp/src/app/shared/share/share-control.component.ts, line 101 at r2](https://reviewable.io/reviews/sillsdev/web-xforge/1099#-MgBcmxxDmmqsA8i2Yol:-MgHNR1f7Y-2fRLFDbyy:b-896fix) ([raw file](https://github.com/sillsdev/web-xforge/blob/47e481e6d69db9bb60ef79c258f908808e97276c/src/SIL.XForge.Scripture/ClientApp/src/app/shared/share/share-control.component.ts#L101)):*
<details><summary><i>Previously, RaymondLuong3 (Raymond Luong) wrote…</i></summary><blockquote>

How about renaming this shareableRoles, or userShareableRoles? Then it may not need a commet.
</blockquote></details>

Done.
___
*[src/SIL.XForge.Scripture/ClientApp/src/app/shared/share/share-control.component.ts, line 97 at r3](https://reviewable.io/reviews/sillsdev/web-xforge/1099#-MgFaOJv2GOw31ZaoJ1-:-MgHNVPP2dCjIO-6m8YV:b-896fix) ([raw file](https://github.com/sillsdev/web-xforge/blob/830c55f1a48d33be45d62a5fda4bcdf8445e8940/src/SIL.XForge.Scripture/ClientApp/src/app/shared/share/share-control.component.ts#L97)):*
<details><summary><i>Previously, irahopkinson (Ira Hopkinson) wrote…</i></summary><blockquote>

> ```
> get availableRoles(): string[]
> ```
This looks like it could/should be `private`.
</blockquote></details>

Done.
___
*[src/SIL.XForge.Scripture/ClientApp/src/app/shared/share/share-control.component.spec.ts, line 184 at r3](https://reviewable.io/reviews/sillsdev/web-xforge/1099#-MgFb-6E1vozKYJGMs65:-MgHJ9P1AYdXg_qbA0Pk:b-896fix) ([raw file](https://github.com/sillsdev/web-xforge/blob/830c55f1a48d33be45d62a5fda4bcdf8445e8940/src/SIL.XForge.Scripture/ClientApp/src/app/shared/share/share-control.component.spec.ts#L184)):*
<details><summary><i>Previously, irahopkinson (Ira Hopkinson) wrote…</i></summary><blockquote>

> ```
>     env.realtimeService
>       .get<SFProjectDoc>(SFProjectDoc.COLLECTION, 'project01')
>       .submitJson0Op(op => op.set<CheckingShareLevel>(p => p.checkingConfig.shareLevel, CheckingShareLevel.Anyone));
> ```
If you put this an appropriately named method it would be more readable. Here and below.
</blockquote></details>

Done.
___
*[src/SIL.XForge.Scripture/Services/ParatextService.cs, line 989 at r3](https://reviewable.io/reviews/sillsdev/web-xforge/1099#-MgFN9vW628HgaYI8bev:-MgHPtsLD6i2AyOOM83q:b-1cetcx) ([raw file](https://github.com/sillsdev/web-xforge/blob/830c55f1a48d33be45d62a5fda4bcdf8445e8940/src/SIL.XForge.Scripture/Services/ParatextService.cs#L989)):*
<details><summary><i>Previously, irahopkinson (Ira Hopkinson) wrote…</i></summary><blockquote>

> ```
> UserRoles.Observer => SFProjectRole.SFObserver,
> ```
If you are keeping things the same, this should be `PTObserver`. Can you explain why we are changing this? If this was meant to stay the same I would recommend you use the rename features of your IDE (in VSCode use F2) so it gets them all changed for you so errors like this don't happen.
</blockquote></details>

Good catch. I did use VSCode to do the rename, but we also did some manual changes. Somehow this slipped through.
___
*[src/SIL.XForge.Scripture/Services/SFProjectService.cs, line 535 at r3](https://reviewable.io/reviews/sillsdev/web-xforge/1099#-MgH6eGrBL3Z_ZuaOFfg:-MgIWQtxD3QYH7QafxzM:b-3vn575) ([raw file](https://github.com/sillsdev/web-xforge/blob/830c55f1a48d33be45d62a5fda4bcdf8445e8940/src/SIL.XForge.Scripture/Services/SFProjectService.cs#L535)):*
<details><summary><i>Previously, RaymondLuong3 (Raymond Luong) wrote…</i></summary><blockquote>

> ```
>                 bool linkSharing = projectDoc.Data.CheckingConfig.ShareEnabled &&
>                     projectDoc.Data.CheckingConfig.ShareLevel == CheckingShareLevel.Anyone;
> ```
It appears that this is not currently handling link sharing for the translate app. It would be good to write a test for this.
</blockquote></details>

I missed this. Thanks for catching it. I haven't tested it yet or written tests, but I think it's right now.

**Review by Nateowami — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1099)* status: 39 of 45 files reviewed, 7 unresolved discussions (waiting on @irahopkinson and @RaymondLuong3)

___
*[src/SIL.XForge.Scripture/Services/SFProjectService.cs, line 535 at r3](https://reviewable.io/reviews/sillsdev/web-xforge/1099#-MgH6eGrBL3Z_ZuaOFfg:-MgId9P9Dgh66QhgFdK-:bxa8hl6) ([raw file](https://github.com/sillsdev/web-xforge/blob/830c55f1a48d33be45d62a5fda4bcdf8445e8940/src/SIL.XForge.Scripture/Services/SFProjectService.cs#L535)):*
<details><summary><i>Previously, Nateowami (Nathaniel Paulus) wrote…</i></summary><blockquote>

I missed this. Thanks for catching it. I haven't tested it yet or written tests, but I think it's right now.
</blockquote></details>

I've tested it and it seems to work. Still need to write tests.

**Review by irahopkinson — CHANGES_REQUESTED** [review]
It would be good to have the tests that Raymond is asking for. Do you need help from someone with those?

> Reviewed 4 of 6 files at r4.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1099#-:-MgJkIZB3zkdKaVt9coh:b-kl43ci)* status: 43 of 45 files reviewed, 4 unresolved discussions (waiting on @irahopkinson, @Nateowami, and @RaymondLuong3)

___
*[src/RealtimeServer/scriptureforge/services/sf-project-migrations.ts, line 117 at r3](https://reviewable.io/reviews/sillsdev/web-xforge/1099#-MgFWteA-Vgp1xWnrtOp:-MgJggAGATCZk1S4ls2M:b-s3yjeg) ([raw file](https://github.com/sillsdev/web-xforge/blob/830c55f1a48d33be45d62a5fda4bcdf8445e8940/src/RealtimeServer/scriptureforge/services/sf-project-migrations.ts#L117)):*
<details><summary><i>Previously, Nateowami (Nathaniel Paulus) wrote…</i></summary><blockquote>

I think you're mixing up the model as it exists in the DB and the JSONRPC data sent from the client to the server.

Here's how the model now looks in the DB:
``` json
  {
    "translationSuggestionsEnabled": true,
    "source": { },
    "shareEnabled": false,
    "shareLevel": "specific"
  },
  "checkingConfig": {
    "checkingEnabled": true,
    "usersSeeEachOthersResponses": true,
    "shareEnabled": false,
    "shareLevel": "specific"
  }
```
Previously it looked about like this:
``` json
  {
    "translationSuggestionsEnabled": true,
    "source": { }
  },
  "checkingConfig": {
    "checkingEnabled": true,
    "usersSeeEachOthersResponses": true,
    "shareEnabled": false,
    "shareLevel": "specific"
  }
```

What has changed is `SFProjectSettings` and `SFProjectService.UpdateSettingsAsync`.
</blockquote></details>

Sorry for that, you are right, the migration is fine.
___
*[src/SIL.XForge.Scripture/ClientApp/src/app/shared/share/share-control.component.ts, line 97 at r3](https://reviewable.io/reviews/sillsdev/web-xforge/1099#-MgFaOJv2GOw31ZaoJ1-:-MgJh4Qr7c1UE47Ydahs:b-bl7e5d) ([raw file](https://github.com/sillsdev/web-xforge/blob/830c55f1a48d33be45d62a5fda4bcdf8445e8940/src/SIL.XForge.Scripture/ClientApp/src/app/shared/share/share-control.component.ts#L97)):*
<details><summary><i>Previously, Nateowami (Nathaniel Paulus) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Thanks, it should now also be moved below these public ones. Unfortunately the linter currently doesn't tell us about this order for getter/setters.
___
*[src/SIL.XForge.Scripture/Services/SFProjectService.cs, line 517 at r4](https://reviewable.io/reviews/sillsdev/web-xforge/1099#-MgJj5Ef7CsBnnJriyuA:-MgJj5Ef7CsBnnJriyuB:b-z1t5fy) ([raw file](https://github.com/sillsdev/web-xforge/blob/ccf568fc5f8fa2a330518bfe9adf927d06465208/src/SIL.XForge.Scripture/Services/SFProjectService.cs#L517)):*
> ```
> var
> ```
In general, don't use `var` unless its obvious what the type is or required for some other reason. Use the correct type.

**Review by Nateowami — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1099)* status: 43 of 45 files reviewed, 4 unresolved discussions (waiting on @irahopkinson and @RaymondLuong3)

___
*[src/SIL.XForge.Scripture/ClientApp/src/app/shared/share/share-control.component.ts, line 101 at r2](https://reviewable.io/reviews/sillsdev/web-xforge/1099#-MgBcmxxDmmqsA8i2Yol:-MgNPR_9DyeKD8RnuMRI:b-896fix) ([raw file](https://github.com/sillsdev/web-xforge/blob/47e481e6d69db9bb60ef79c258f908808e97276c/src/SIL.XForge.Scripture/ClientApp/src/app/shared/share/share-control.component.ts#L101)):*
<details><summary><i>Previously, Nateowami (Nathaniel Paulus) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Done.
___
*[src/SIL.XForge.Scripture/ClientApp/src/app/shared/share/share-control.component.ts, line 97 at r3](https://reviewable.io/reviews/sillsdev/web-xforge/1099#-MgFaOJv2GOw31ZaoJ1-:-MgNQeqA2xk3cnFEFxfW:b-896fix) ([raw file](https://github.com/sillsdev/web-xforge/blob/830c55f1a48d33be45d62a5fda4bcdf8445e8940/src/SIL.XForge.Scripture/ClientApp/src/app/shared/share/share-control.component.ts#L97)):*
<details><summary><i>Previously, irahopkinson (Ira Hopkinson) wrote…</i></summary><blockquote>

Thanks, it should now also be moved below these public ones. Unfortunately the linter currently doesn't tell us about this order for getter/setters.
</blockquote></details>

Done.
___
*[src/SIL.XForge.Scripture/Services/SFProjectService.cs, line 517 at r4](https://reviewable.io/reviews/sillsdev/web-xforge/1099#-MgJj5Ef7CsBnnJriyuA:-MgNP_MTDHgNgeLR-fXy:b-p19l26) ([raw file](https://github.com/sillsdev/web-xforge/blob/ccf568fc5f8fa2a330518bfe9adf927d06465208/src/SIL.XForge.Scripture/Services/SFProjectService.cs#L517)):*
<details><summary><i>Previously, irahopkinson (Ira Hopkinson) wrote…</i></summary><blockquote>

> ```
> var
> ```
In general, don't use `var` unless its obvious what the type is or required for some other reason. Use the correct type. 
</blockquote></details>

Thanks. Done. I wrote `var` with the intention of changing it afterwards but forgot.

**Review by irahopkinson — COMMENTED** [review]
> Reviewed 1 of 45 files at r1.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1099)* status: 43 of 45 files reviewed, 2 unresolved discussions (waiting on @irahopkinson and @RaymondLuong3)

**Review by Nateowami — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1099)* status: 42 of 45 files reviewed, 2 unresolved discussions (waiting on @irahopkinson and @RaymondLuong3)

___
*[src/SIL.XForge.Scripture/Services/SFProjectService.cs, line 535 at r3](https://reviewable.io/reviews/sillsdev/web-xforge/1099#-MgH6eGrBL3Z_ZuaOFfg:-MgSUC_2EGH3bYdzdIFW:bdpz7ip) ([raw file](https://github.com/sillsdev/web-xforge/blob/830c55f1a48d33be45d62a5fda4bcdf8445e8940/src/SIL.XForge.Scripture/Services/SFProjectService.cs#L535)):*
<details><summary><i>Previously, Nateowami (Nathaniel Paulus) wrote…</i></summary><blockquote>

I've tested it and it seems to work. Still need to write tests.
</blockquote></details>

Tests are now written.

**Review by irahopkinson — COMMENTED** [review]
> Reviewed 1 of 1 files at r7, 2 of 2 files at r8.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1099)* status: 43 of 45 files reviewed, 2 unresolved discussions (waiting on @irahopkinson and @RaymondLuong3)

**Review by RaymondLuong3 — APPROVED** [review]
Nice! From my end this looks ready to go. I see that you have default values for the translate config so we won't have to do a data migration which is nice.

> Reviewed 1 of 1 files at r5, 1 of 1 files at r6.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1099#-:-MgfSgxI-mdFSvqobS41:b-7276d)* status: all files reviewed, 1 unresolved discussion (waiting on @Nateowami)

___
*[src/SIL.XForge.Scripture/Services/SFProjectService.cs, line 536 at r8](https://reviewable.io/reviews/sillsdev/web-xforge/1099#-MgfRWOs91eBXMKtME7L:-MgfRWOs91eBXMKtME7M:bz8hc83) ([raw file](https://github.com/sillsdev/web-xforge/blob/d65f38f0a26a23b359991e52794880bc57e191f4/src/SIL.XForge.Scripture/Services/SFProjectService.cs#L536)):*
> ```Smalltalk
>                     throw new ForbiddenException();
> 
>                 string[] availableRoles = new Dictionary<string, bool> {
> ```

Nit: I see what you are doing here, but maybe is is overly complex. Could you simply use if branching to add the role to a list instead of creating a dictionary with a bool value?

**Review by Nateowami — COMMENTED** [review]
Actually we are doing a data migration, since we also access these values on the front-end.

> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1099#-:-Mgf_p01EAmfnVLUIHCS:b-gkeqsd)* status: all files reviewed, 1 unresolved discussion (waiting on @RaymondLuong3)

___
*[src/SIL.XForge.Scripture/Services/SFProjectService.cs, line 536 at r8](https://reviewable.io/reviews/sillsdev/web-xforge/1099#-MgfRWOs91eBXMKtME7L:-MgfUzQM0VzVBRXbgt9k:b-i67zvd) ([raw file](https://github.com/sillsdev/web-xforge/blob/d65f38f0a26a23b359991e52794880bc57e191f4/src/SIL.XForge.Scripture/Services/SFProjectService.cs#L536)):*
<details><summary><i>Previously, RaymondLuong3 (Raymond Luong) wrote…</i></summary><blockquote>

Nit: I see what you are doing here, but maybe is is overly complex. Could you simply use if branching to add the role to a list instead of creating a dictionary with a bool value?
</blockquote></details>

I think we're planning to add a reviewer role soon. Which means the logic will get even more complicated. We also have similar logic elsewhere, where we do roughly the same thing (and the logic there is even more complicated). Which makes me think that long-term this will be less convoluted.

**Review by Nateowami — COMMENTED** [review]
@irahopkinson Reviewable shows that you're still requesting changes, but I don't see any changes requested. Can you take a look at it again?

> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1099#-:-MgfomGPEgYA10nsVgEC:btn7p1l)* status: all files reviewed, 1 unresolved discussion (waiting on @RaymondLuong3)

**Review by irahopkinson — APPROVED** [review]
Github indicates that its waiting on Raymond's outstanding discussion. Either way I can approve it now that he is happy.
:lgtm: 

> Reviewed 1 of 1 files at r5.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1099#-:-Mghdw3NDrUpv7P0b2rn:bb2zdwe)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @Nateowami)

**Pull request merged**
