### PR TITLE
SF-1552a Multi-cursor

### PR DESCRIPTION
**Pull request by irahopkinson**
- update dependencies
- `npm audit fix`
- add cursors
- improve cursor behavior
- fix cursor colors so that same user has same color

- fix and add tests
- stub out docPresence for the memory-realtime-remote-store

---
This change is [Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1337)

### CODE REVIEW

**Review by Nateowami — DISMISSED** [review]
> Reviewed 13 of 22 files at r1.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1337)* status: 13 of 22 files reviewed, 1 unresolved discussion (waiting on @irahopkinson and @Nateowami)

___
*[`src/RealtimeServer/package.json` line 29 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/1337#-N1ews864c4b6HQ9aei0:-N1ews864c4b6HQ9aei1:b-2z1oi6) ([raw file](https://github.com/sillsdev/web-xforge/blob/24a1d756c7f482d7f9f212026b00dc69bef81f6c/src/RealtimeServer/package.json#L29)):*
> ```JSON
>     "ot-json0": "^1.1.0",
>     "rich-text": "^4.1.0",
>     "sharedb": "^1.9.2",
> ```

Why not install the 2.x branch? I'm guessing you didn't want to go to a new major version for fear of breaking changes, but the release notes for v2 say "BREAKING: Drop Node.js v10 support". We're on Angular 12 which also doesn't support Node.js v10, so we should be fine to go all the way up to v2.2.5.

They released v3.0.0 6 days ago and dropped support for Node v12. We're probably not quite ready to move to that.

**Review by irahopkinson — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1337)* status: 13 of 22 files reviewed, 1 unresolved discussion (waiting on @Nateowami)

___
*[`src/RealtimeServer/package.json` line 29 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/1337#-N1ews864c4b6HQ9aei0:-N1fSw0K1jnnwgJuqKSs:b-uxmflk) ([raw file](https://github.com/sillsdev/web-xforge/blob/24a1d756c7f482d7f9f212026b00dc69bef81f6c/src/RealtimeServer/package.json#L29)):*
<details><summary><i>Previously, Nateowami (Nathaniel Paulus) wrote…</i></summary><blockquote>

Why not install the 2.x branch? I'm guessing you didn't want to go to a new major version for fear of breaking changes, but the release notes for v2 say "BREAKING: Drop Node.js v10 support". We're on Angular 12 which also doesn't support Node.js v10, so we should be fine to go all the way up to v2.2.5.

They released v3.0.0 6 days ago and dropped support for Node v12. We're probably not quite ready to move to that.
</blockquote></details>

At first I went all the way up to v2.2.5 but it broke something (don' remember the details). I thought we would ship something that works first then move up versions from that point.

**Review by Nateowami — COMMENTED** [review]
> Reviewed 1 of 22 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1337)* status: 14 of 22 files reviewed, all discussions resolved (waiting on @Nateowami)

___
*[`src/RealtimeServer/package.json` line 29 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/1337#-N1ews864c4b6HQ9aei0:-N1fzFOqA405J-EId6sg:b-8fx2u7) ([raw file](https://github.com/sillsdev/web-xforge/blob/24a1d756c7f482d7f9f212026b00dc69bef81f6c/src/RealtimeServer/package.json#L29)):*
<details><summary><i>Previously, irahopkinson (Ira Hopkinson) wrote…</i></summary><blockquote>

At first I went all the way up to v2.2.5 but it broke something (don' remember the details). I thought we would ship something that works first then move up versions from that point.
</blockquote></details>

:+1:

**Review by RaymondLuong3 — CHANGES_REQUESTED** [review]
Thanks for your work on this. I have some comments but overall it looks nice and clean.

> Reviewed 8 of 22 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1337#-:-N1iyjT_8PDPvMv-rIb4:b-g08zc3)* status: all files reviewed, 6 unresolved discussions (waiting on @irahopkinson)

___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/shared/text/text-view-model.ts` line 1 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/1337#-N1imizc3m16y5EKDEUp:-N1imizc3m16y5EKDEUq:b-ogr55a) ([raw file](https://github.com/sillsdev/web-xforge/blob/c726a502692ddfaa05fd3f3a3187f5c427f9d107/src/SIL.XForge.Scripture/ClientApp/src/app/shared/text/text-view-model.ts#L1)):*
> ```XML
> import ObjectID from 'bson-objectid';
> ```

In xforge-common/utils.ts we have a function called objectID(). I wonder if we could use that in this file.



_Code quote:_
```XML
import ObjectID from 'bson-objectid';
```
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/shared/text/text-view-model.ts` line 123 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/1337#-N1inDCM3YLzSqMSL2UL:-N1inDCM3YLzSqMSL2UM:b-vn456v) ([raw file](https://github.com/sillsdev/web-xforge/blob/c726a502692ddfaa05fd3f3a3187f5c427f9d107/src/SIL.XForge.Scripture/ClientApp/src/app/shared/text/text-view-model.ts#L123)):*
> ```XML
>   private readonly _segments: Map<string, RangeStatic> = new Map<string, RangeStatic>();
>   private readonly presenceId: string = new ObjectID().toString();
>   private readonly cursorColorStorageKey = 'cursor_color';
> ```

Would this be better as a const at the file level? That way if other classes ever use it, we could expose it.



_Code quote:_
```XML
  private readonly cursorColorStorageKey = 'cursor_color';
```
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/shared/text/text.component.ts` line 603 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/1337#-N1ip6RW1hSB0BHghzF3:-N1ip6RW1hSB0BHghzF4:b-bkqrxw) ([raw file](https://github.com/sillsdev/web-xforge/blob/c726a502692ddfaa05fd3f3a3187f5c427f9d107/src/SIL.XForge.Scripture/ClientApp/src/app/shared/text/text.component.ts#L603)):*
> ```XML
>     if ((source as Sources) !== 'user') return;
>     // Clear the cursor on blurring.
>     if (!range) {
> ```

Nit: This should be if (range == null).



_Code quote:_
```XML
    if (!range) {
```
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/shared/text/text.component.ts` line 609 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/1337#-N1ipV4v3sWJI7A7vT9b:-N1ipV4w7hGV3LLvEDcZ:bsc9hv5) ([raw file](https://github.com/sillsdev/web-xforge/blob/c726a502692ddfaa05fd3f3a3187f5c427f9d107/src/SIL.XForge.Scripture/ClientApp/src/app/shared/text/text.component.ts#L609)):*
> ```XML
>     // In this particular instance, we can send extra information on the presence object. This ability will vary
>     // depending on type.
>     const currentUserDoc = await this.userService.getCurrentUser();
> ```

Add the type to this assignment.



_Code quote:_
```XML
    const currentUserDoc = await this.userService.getCurrentUser();
```
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/shared/text/text.component.ts` line 616 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/1337#-N1ipmoZ324tdOX3CuJ1:-N1ipmoZ324tdOX3CuJ2:b4v8bs9) ([raw file](https://github.com/sillsdev/web-xforge/blob/c726a502692ddfaa05fd3f3a3187f5c427f9d107/src/SIL.XForge.Scripture/ClientApp/src/app/shared/text/text.component.ts#L616)):*
> ```XML
>     };
>     this.viewModel.localPresence?.submit(presenceData, error => {
>       if (error) throw error;
> ```

When would an error come up? I assume when presenceData is somehow invalid?



_Code quote:_
```XML
    this.viewModel.localPresence?.submit(presenceData, error => {
      if (error) throw error;
    });
```
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/shared/text/text.component.spec.ts` line 173 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/1337#-N1iyBIMEC30SXWfINgI:-N1iyBIN4Ytzc6d78Al1:b-2ovrv7) ([raw file](https://github.com/sillsdev/web-xforge/blob/c726a502692ddfaa05fd3f3a3187f5c427f9d107/src/SIL.XForge.Scripture/ClientApp/src/app/shared/text/text.component.spec.ts#L173)):*
> ```XML
>   }));
> 
>   describe('MultiCursor Presence', () => {
> ```

Is there any way to test that the cursors of other users is present on the page when other users exist on the same doc?



_Code quote:_
```XML
  describe('MultiCursor Presence', () => {
```

**Review by irahopkinson — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1337)* status: 20 of 22 files reviewed, 5 unresolved discussions (waiting on @RaymondLuong3)

___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/shared/text/text-view-model.ts` line 1 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/1337#-N1imizc3m16y5EKDEUp:-N1lxxD85MEjH16l8ZqZ:b-376vyb) ([raw file](https://github.com/sillsdev/web-xforge/blob/c726a502692ddfaa05fd3f3a3187f5c427f9d107/src/SIL.XForge.Scripture/ClientApp/src/app/shared/text/text-view-model.ts#L1)):*
<details><summary><i>Previously, RaymondLuong3 (Raymond Luong) wrote…</i></summary><blockquote>

In xforge-common/utils.ts we have a function called objectID(). I wonder if we could use that in this file.
</blockquote></details>

Done. Good catch.
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/shared/text/text-view-model.ts` line 123 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/1337#-N1inDCM3YLzSqMSL2UL:-N1ltJiWDWDBTvqXc1B0:bdge36x) ([raw file](https://github.com/sillsdev/web-xforge/blob/c726a502692ddfaa05fd3f3a3187f5c427f9d107/src/SIL.XForge.Scripture/ClientApp/src/app/shared/text/text-view-model.ts#L123)):*
<details><summary><i>Previously, RaymondLuong3 (Raymond Luong) wrote…</i></summary><blockquote>

Would this be better as a const at the file level? That way if other classes ever use it, we could expose it.
</blockquote></details>

I have an aversion to anything on the global space (probably a hang over from old JS days) which is the only place in this file that you could declare a `const`. Additionally having it a `readonly` property keeps it in the right place for its usage. If we needed it outside this class it could be made `static public`. Do you have a good reason for making it a global const?
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/shared/text/text.component.ts` line 603 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/1337#-N1ip6RW1hSB0BHghzF3:-N1ly98X13ofDbmNl6qH:b-896fix) ([raw file](https://github.com/sillsdev/web-xforge/blob/c726a502692ddfaa05fd3f3a3187f5c427f9d107/src/SIL.XForge.Scripture/ClientApp/src/app/shared/text/text.component.ts#L603)):*
<details><summary><i>Previously, RaymondLuong3 (Raymond Luong) wrote…</i></summary><blockquote>

Nit: This should be if (range == null).
</blockquote></details>

Done.
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/shared/text/text.component.ts` line 609 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/1337#-N1ipV4v3sWJI7A7vT9b:-N1lyU7Z-huvrfcB0r6h:b-896fix) ([raw file](https://github.com/sillsdev/web-xforge/blob/c726a502692ddfaa05fd3f3a3187f5c427f9d107/src/SIL.XForge.Scripture/ClientApp/src/app/shared/text/text.component.ts#L609)):*
<details><summary><i>Previously, RaymondLuong3 (Raymond Luong) wrote…</i></summary><blockquote>

Add the type to this assignment.
</blockquote></details>

Done.
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/shared/text/text.component.ts` line 616 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/1337#-N1ipmoZ324tdOX3CuJ1:-N1luYbz0YltB2JjnITG:bdtq6c6) ([raw file](https://github.com/sillsdev/web-xforge/blob/c726a502692ddfaa05fd3f3a3187f5c427f9d107/src/SIL.XForge.Scripture/ClientApp/src/app/shared/text/text.component.ts#L616)):*
<details><summary><i>Previously, RaymondLuong3 (Raymond Luong) wrote…</i></summary><blockquote>

When would an error come up? I assume when presenceData is somehow invalid?
</blockquote></details>

I don't actually know what conditions could cause an error and the docs don't seem to tell us either. This code was taken from their example and I reasoned should it ever have an error I want a developer to see it throw rather than not do anything.
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/shared/text/text.component.spec.ts` line 173 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/1337#-N1iyBIMEC30SXWfINgI:-N1lvccZ0VAEm_oaLI9Y:bgesfp3) ([raw file](https://github.com/sillsdev/web-xforge/blob/c726a502692ddfaa05fd3f3a3187f5c427f9d107/src/SIL.XForge.Scripture/ClientApp/src/app/shared/text/text.component.spec.ts#L173)):*
<details><summary><i>Previously, RaymondLuong3 (Raymond Luong) wrote…</i></summary><blockquote>

Is there any way to test that the cursors of other users is present on the page when other users exist on the same doc?
</blockquote></details>

Not easily in this PR without doing something hacky to look inside the class. The next PR for multi cursor viewer avatars in the toolbar includes an event emitter that should help to see what is happening to some extent so we can add more tests. Make sure I don't miss any tests in that PR.

**Review by RaymondLuong3 — APPROVED** [review]
@nateowami This looks good from my end. Did you have anything to add?

> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1337#-:-N1ngpBK4F5STExCquIx:bwu23t7)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @irahopkinson)

___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/shared/text/text-view-model.ts` line 123 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/1337#-N1inDCM3YLzSqMSL2UL:-N1nfVfE1EsDmtj0BBmm:b-81jwn7) ([raw file](https://github.com/sillsdev/web-xforge/blob/c726a502692ddfaa05fd3f3a3187f5c427f9d107/src/SIL.XForge.Scripture/ClientApp/src/app/shared/text/text-view-model.ts#L123)):*
<details><summary><i>Previously, irahopkinson (Ira Hopkinson) wrote…</i></summary><blockquote>

I have an aversion to anything on the global space (probably a hang over from old JS days) which is the only place in this file that you could declare a `const`. Additionally having it a `readonly` property keeps it in the right place for its usage. If we needed it outside this class it could be made `static public`. Do you have a good reason for making it a global const?
</blockquote></details>

Ok, I'm happy to keep it local to the class, if we need to access it from another class we can use your suggestion about making it `static`
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/shared/text/text.component.spec.ts` line 173 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/1337#-N1iyBIMEC30SXWfINgI:-N1ng6X7ExI9x9QcVR7p:b62ay1n) ([raw file](https://github.com/sillsdev/web-xforge/blob/c726a502692ddfaa05fd3f3a3187f5c427f9d107/src/SIL.XForge.Scripture/ClientApp/src/app/shared/text/text.component.spec.ts#L173)):*
<details><summary><i>Previously, irahopkinson (Ira Hopkinson) wrote…</i></summary><blockquote>

Not easily in this PR without doing something hacky to look inside the class. The next PR for multi cursor viewer avatars in the toolbar includes an event emitter that should help to see what is happening to some extent so we can add more tests. Make sure I don't miss any tests in that PR.
</blockquote></details>

Ok, sounds good. This PR adds in the capability of showing the presence of other users. It looks like the scenarios we care about are covered, so that's good.

**Review by irahopkinson — COMMENTED** [review]
@nateowami if you wanted to release this PR before my next one I'd make a small adjustment to it before we merge it so the  `PresenceData` structure doesn't change, which could cause problems between users on different versions. If you are happy to release after the next PR then no problem.

> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1337#-:-N1nmWjdBZaORqFQ5Pdx:b-b1x0v6)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @irahopkinson)

**Review by Nateowami — CHANGES_REQUESTED** [review]
@raymondluong3 I haven't reviewed the entire change yet, but if you've reviewed it that's good enough for me.

@irahopkinson As much as possible I'd like to keep master in an always-ready-to-release state, so you might want to go ahead and make that change. Let's hold off on merging for now.

> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1337#-:-N1nlOM2ALbdoCP58NxR:b-5sf0sc)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @irahopkinson)

**Review by irahopkinson — COMMENTED** [review]
I've made the structure change to `Presencedata` now as a separate commit. Ready to merge now once that is reviewed.

> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1337#-:-N1q4M-O9RW4Oek8GftZ:bzckt0b)* status: 19 of 22 files reviewed, all discussions resolved (waiting on @Nateowami and @RaymondLuong3)

**Review by RaymondLuong3 — APPROVED** [review]
> Reviewed 3 of 3 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1337)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @irahopkinson)

**Review by Nateowami — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1337)* status: all files reviewed, 1 unresolved discussion (waiting on @irahopkinson)

___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/shared/text/text-view-model.ts` line 141 at r3](https://reviewable.io/reviews/sillsdev/web-xforge/1337#-N1tqYCa55VgJWRD747d:-N1tqYCa55VgJWRD747e:b-j6ee5o) ([raw file](https://github.com/sillsdev/web-xforge/blob/c416faa9e88437c3c5f711a966ae395c5bd8389e/src/SIL.XForge.Scripture/ClientApp/src/app/shared/text/text-view-model.ts#L141)):*
> ```XML
>     let localCursorColor = localStorage.getItem(this.cursorColorStorageKey);
>     if (localCursorColor == null) {
>       localCursorColor = tinyColor.random().toHexString();
> ```

Based on my testing, this is going to create a random color that can include colors very close to white. How about:
``` ts
tinyColor(({s: 0.7, l: 0.5, h: Math.random() * 360})).toHexString();
```
Saturation and luminance are percentage values; hue is given in degrees from 0 to 360.

Alternatively we could generate and store a random hue and store only that. That would allow us to in the future improve this logic to something better than random to minimize collisions, which are probably very likely.

**Review by Nateowami — COMMENTED** [review]
> Reviewed 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1337)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @irahopkinson)

**Review by irahopkinson — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1337)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @irahopkinson)

___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/shared/text/text-view-model.ts` line 141 at r3](https://reviewable.io/reviews/sillsdev/web-xforge/1337#-N1tqYCa55VgJWRD747d:-N1vEVWK1A7F15Z7CKE1:bq6wsye) ([raw file](https://github.com/sillsdev/web-xforge/blob/c416faa9e88437c3c5f711a966ae395c5bd8389e/src/SIL.XForge.Scripture/ClientApp/src/app/shared/text/text-view-model.ts#L141)):*
<details><summary><i>Previously, Nateowami (Nathaniel Paulus) wrote…</i></summary><blockquote>

Based on my testing, this is going to create a random color that can include colors very close to white. How about:
``` ts
tinyColor(({s: 0.7, l: 0.5, h: Math.random() * 360})).toHexString();
```
Saturation and luminance are percentage values; hue is given in degrees from 0 to 360.

Alternatively we could generate and store a random hue and store only that. That would allow us to in the future improve this logic to something better than random to minimize collisions, which are probably very likely.
</blockquote></details>

Good catch, I hadn't thought about the cursor background getting too close to the text color. I've gone with your first suggestion for now.

On the collision thing, I have thought about that a lot. The current solution is actually more open to collision than I'd like because each user generates their own color and sends that to the other viewers. The advantage of this is it keeps the code relatively simple for ensuring duplicate users have the same color (an important usability feature). A secondary advantage is that if the viewers are talking to each other or sharing screens each viewer sees the same color for the same viewer (this is not part of my design criteria but useful none the less). The disadvantage is that its more open to color collisions (since each device "randomly" chooses a color) and the only way to clear your color is to logout and back in. GDocs doesn't do that, instead each viewer has its own random set of colors and since that's all on the same device the randomness is likely to ok.

After weighing the options I went with the current solution since practically it seems to be ok even if technically its not.

**Pull request merged**
