### PR TITLE
SF-3013 Add pipe to localize numbers

### PR DESCRIPTION
**Pull request by Nateowami**
While I've wanted to do this for quite some time, a major motivation to add this now is the fact that in the near future we are likely to change the estimated draft time to 2.5 hours, and how decimals are shown differs quite significantly between locales.

I've added this pipe in the simplest and most obvious places, but adding it everywhere is not one of the goals.

- - -
This change is [Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/2759)

### CODE REVIEW

**Review by RaymondLuong3 — CHANGES_REQUESTED** [review]
Thanks for adding this. Is there a reason for including the screenshots of the UI for different languages. Does it make sense to include those? If they are generated automatically, they may get updated for every PR which would be annoying. If they are generated manually, I imagine the usefulness would be you have a record of the original state, but then we would have to remember to update it if there is a change.
The functionality looks good. Just a few places where the pipe can be added on the checking overview.

> Reviewed 89 of 89 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/2759#-:-O8DKBn8CMtA7yNAsu-Z:b-5e180t)* status: all files reviewed, 7 unresolved discussions (waiting on @Nateowami)

___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking-overview/checking-overview.component.html` line 181 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/2759#-O8DCu2956CjFEIXrU9d:-O8DCu2956CjFEIXrU9e:b-43ld8o) ([raw file](https://github.com/sillsdev/web-xforge/blob/c941e756cbd60a1496c5961029092da64558586b/src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking-overview/checking-overview.component.html#L181)):*
> ```HTML
>                                 </span>
>                                 <span fxFlex="110px" class="hide-lt-sm" fxLayoutAlign="end center">
>                                   {{ answerCountLabel(questionDoc.getAnswers().length) }}
> ```

You will want to also add the pipe here and throughout this file. Since this will only be visible to translators and admins, it may not be as critical, but for completeness I think it makes sense.



_Code quote:_
```HTML
    {{ answerCountLabel(questionDoc.getAnswers().length) }}
```
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking-overview/checking-overview.component.html` line 254 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/2759#-O8DBsp1EIHivepii9t4:-O8DBsp1EIHivepii9t5:b-7exrr4) ([raw file](https://github.com/sillsdev/web-xforge/blob/c941e756cbd60a1496c5961029092da64558586b/src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking-overview/checking-overview.component.html#L254)):*
> ```HTML
>         <mat-card-content>
>           <span fxFlex>
>             <div class="stat-total">{{ allQuestionsCount | l10nNumber }}</div>
> ```

I know that 



_Code quote:_
```HTML
  <div class="stat-total">{{ allQuestionsCount | l10nNumber }}</div>
```
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/translate/translate-overview/translate-overview.component.html` line 65 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/2759#-O8DDsOX5bsCrX_jVPv2:-O8DDsOX5bsCrX_jVPv3:b-be8ruy) ([raw file](https://github.com/sillsdev/web-xforge/blob/c941e756cbd60a1496c5961029092da64558586b/src/SIL.XForge.Scripture/ClientApp/src/app/translate/translate-overview/translate-overview.component.html#L65)):*
> ```HTML
>         <mat-card-content class="engine-card-content">
>           <div class="engine-card-quality">
>             <div class="engine-card-quality-stars mirror-rtl" [title]="engineConfidence + ' BLEU'">
> ```

Let's add it to the engine confidence too. This will be a decimal number



_Code quote:_
```HTML
[title]="engineConfidence + ' BLEU'"
```
___
*[`src/SIL.XForge.Scripture/ClientApp/src/xforge-common/l10n-number.pipe.ts` line 19 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/2759#-O8DHLp2AecNatEm8l56:-O8DHLp2AecNatEm8l57:b-eflos9) ([raw file](https://github.com/sillsdev/web-xforge/blob/c941e756cbd60a1496c5961029092da64558586b/src/SIL.XForge.Scripture/ClientApp/src/xforge-common/l10n-number.pipe.ts#L19)):*
> ```XML
>   getNumberFormat(): Intl.NumberFormat {
>     if (!this.numberFormat || this.lastLocale !== this.i18n.localeCode) {
>       this.numberFormat = new Intl.NumberFormat(this.i18n.localeCode);
> ```

What is the advantage initializing an Intl.NumberFormat Object over just calling n.toLocaleString? Is that the efficiency comment above. So providing the singleton `L10NumberFormatService` is more efficient than providing a service that calls n.toLocaleString then.



_Code quote:_
```XML
      this.numberFormat = new Intl.NumberFormat(this.i18n.localeCode);
```
___
*[`src/SIL.XForge.Scripture/ClientApp/src/xforge-common/l10n-number.pipe.ts` line 31 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/2759#-O8DERTX4d_PuWUfJRae:-O8DERTX4d_PuWUfJRaf:b-t4eifq) ([raw file](https://github.com/sillsdev/web-xforge/blob/c941e756cbd60a1496c5961029092da64558586b/src/SIL.XForge.Scripture/ClientApp/src/xforge-common/l10n-number.pipe.ts#L31)):*
> ```XML
>   constructor(private readonly formatter: L10nNumberFormatService) {}
> 
>   transform(value: number): string {
> ```

The value type should be number or string



_Code quote:_
```XML
  transform(value: number): string {
```
___
*[`src/SIL.XForge.Scripture/ClientApp/test-results/.last-run.json` line 2 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/2759#-O8DJ8WIA1tKEiU3pEwc:-O8DJ8WJ9fJQg61VQzg3:bzbe37d) ([raw file](https://github.com/sillsdev/web-xforge/blob/c941e756cbd60a1496c5961029092da64558586b/src/SIL.XForge.Scripture/ClientApp/test-results/.last-run.json#L2)):*
> ```JSON
> {
>   "status": "failed",
> ```

What is this for?



_Code quote:_
```JSON
 "status": "failed",
```
___
*[`src/SIL.XForge.Scripture/ClientApp/tests/output/ar/c479f9bad9a40847e396bd44a00ded1f.webm` line 0 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/2759#-O8DJeIj3ALVdmcvyG4l:-O8DJeIj3ALVdmcvyG4m:b-93qrx9) ([raw file](https://github.com/sillsdev/web-xforge/blob/c941e756cbd60a1496c5961029092da64558586b/src/SIL.XForge.Scripture/ClientApp/tests/output/ar/c479f9bad9a40847e396bd44a00ded1f.webm#L0)):*
What is the usefulness of including these screenshots? Are they from Chromatic?

**Comment by RaymondLuong3** [comment]
I wonder if we should add this to the chapter select component. That is one of the major components users will interact with. However, when I update the interface in Paratext, chapter and verse numbers do not get localized, so perhaps we do not need to be concerned with that.

**Review by Nateowami — COMMENTED** [review]
I definitely did not intend to commit the screenshots (and originally opened this without them). Thanks for catching that.

> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/2759#-:-O8DbNJ59dqehiiKK0oA:b-exzaju)* status: 6 of 90 files reviewed, 7 unresolved discussions (waiting on @RaymondLuong3)

___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking-overview/checking-overview.component.html` line 181 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/2759#-O8DCu2956CjFEIXrU9d:-O8De8QcDFNfk5KU_Mqo:b-896fix) ([raw file](https://github.com/sillsdev/web-xforge/blob/c941e756cbd60a1496c5961029092da64558586b/src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking-overview/checking-overview.component.html#L181)):*
<details><summary><i>Previously, RaymondLuong3 (Raymond Luong) wrote…</i></summary><blockquote>

You will want to also add the pipe here and throughout this file. Since this will only be visible to translators and admins, it may not be as critical, but for completeness I think it makes sense.
</blockquote></details>

Done.
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking-overview/checking-overview.component.html` line 254 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/2759#-O8DBsp1EIHivepii9t4:-O8DcGxt8b5j7ZDlwy7Q:b-2c52an) ([raw file](https://github.com/sillsdev/web-xforge/blob/c941e756cbd60a1496c5961029092da64558586b/src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking-overview/checking-overview.component.html#L254)):*
<details><summary><i>Previously, RaymondLuong3 (Raymond Luong) wrote…</i></summary><blockquote>

I know that
</blockquote></details>

What is this supposed to say?
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/translate/translate-overview/translate-overview.component.html` line 65 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/2759#-O8DDsOX5bsCrX_jVPv2:-O8DdXtzEdTjQIbQcssM:bctpdcc) ([raw file](https://github.com/sillsdev/web-xforge/blob/c941e756cbd60a1496c5961029092da64558586b/src/SIL.XForge.Scripture/ClientApp/src/app/translate/translate-overview/translate-overview.component.html#L65)):*
<details><summary><i>Previously, RaymondLuong3 (Raymond Luong) wrote…</i></summary><blockquote>

Let's add it to the engine confidence too. This will be a decimal number
</blockquote></details>

Makes sense. Done.
___
*[`src/SIL.XForge.Scripture/ClientApp/src/xforge-common/l10n-number.pipe.ts` line 19 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/2759#-O8DHLp2AecNatEm8l56:-O8DcNl_9jXKakJJiidk:b-v5wsmy) ([raw file](https://github.com/sillsdev/web-xforge/blob/c941e756cbd60a1496c5961029092da64558586b/src/SIL.XForge.Scripture/ClientApp/src/xforge-common/l10n-number.pipe.ts#L19)):*
<details><summary><i>Previously, RaymondLuong3 (Raymond Luong) wrote…</i></summary><blockquote>

What is the advantage initializing an Intl.NumberFormat Object over just calling n.toLocaleString? Is that the efficiency comment above. So providing the singleton `L10NumberFormatService` is more efficient than providing a service that calls n.toLocaleString then.
</blockquote></details>

Yes, read the linked page for the explanation
___
*[`src/SIL.XForge.Scripture/ClientApp/src/xforge-common/l10n-number.pipe.ts` line 31 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/2759#-O8DERTX4d_PuWUfJRae:-O8DcRbE7LE9N3C_0hcL:b-d86yi3) ([raw file](https://github.com/sillsdev/web-xforge/blob/c941e756cbd60a1496c5961029092da64558586b/src/SIL.XForge.Scripture/ClientApp/src/xforge-common/l10n-number.pipe.ts#L31)):*
<details><summary><i>Previously, RaymondLuong3 (Raymond Luong) wrote…</i></summary><blockquote>

The value type should be number or string
</blockquote></details>

Why? It's inefficient to keep converting strings to numbers, and I can't think of a case where we actually want to do that.
___
*[`src/SIL.XForge.Scripture/ClientApp/test-results/.last-run.json` line 2 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/2759#-O8DJ8WIA1tKEiU3pEwc:-O8Dc_M-673GMq4uMt9a:bza4pnt) ([raw file](https://github.com/sillsdev/web-xforge/blob/c941e756cbd60a1496c5961029092da64558586b/src/SIL.XForge.Scripture/ClientApp/test-results/.last-run.json#L2)):*
<details><summary><i>Previously, RaymondLuong3 (Raymond Luong) wrote…</i></summary><blockquote>

What is this for?
</blockquote></details>

I originally staged files using `git add -u`, which adds tracked files. But then I realized I had missed the new files, so I ran `git add src`, which mistakenly added a ton of files that shouldn't have been added. My apologies.
___
*[`src/SIL.XForge.Scripture/ClientApp/tests/output/ar/c479f9bad9a40847e396bd44a00ded1f.webm` line  at r1](https://reviewable.io/reviews/sillsdev/web-xforge/2759#-O8DJeIj3ALVdmcvyG4l:-O8Dcm7XDX-6YOcyHehi:bo3t602) ([raw file](https://github.com/sillsdev/web-xforge/blob/c941e756cbd60a1496c5961029092da64558586b/src/SIL.XForge.Scripture/ClientApp/tests/output/ar/c479f9bad9a40847e396bd44a00ded1f.webm#L)):*
<details><summary><i>Previously, RaymondLuong3 (Raymond Luong) wrote…</i></summary><blockquote>

What is the usefulness of including these screenshots? Are they from Chromatic?
</blockquote></details>

Accidentally added.

**Review by RaymondLuong3 — CHANGES_REQUESTED** [review]
> Reviewed 85 of 85 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/2759)* status: all files reviewed, 2 unresolved discussions (waiting on @Nateowami)

___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking-overview/checking-overview.component.html` line 254 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/2759#-O8DBsp1EIHivepii9t4:-O8Dk7d80Qh13QRBpfHM:bxjfkx7) ([raw file](https://github.com/sillsdev/web-xforge/blob/c941e756cbd60a1496c5961029092da64558586b/src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking-overview/checking-overview.component.html#L254)):*
<details><summary><i>Previously, Nateowami (Nathaniel Paulus) wrote…</i></summary><blockquote>

What is this supposed to say?
</blockquote></details>

sorry, I didn't mean to publish that.
___
*[`src/SIL.XForge.Scripture/ClientApp/src/xforge-common/l10n-number.pipe.ts` line 19 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/2759#-O8DHLp2AecNatEm8l56:-O8DkqLS8RHEHW5fDf-O:b-8vjrch) ([raw file](https://github.com/sillsdev/web-xforge/blob/c941e756cbd60a1496c5961029092da64558586b/src/SIL.XForge.Scripture/ClientApp/src/xforge-common/l10n-number.pipe.ts#L19)):*
<details><summary><i>Previously, Nateowami (Nathaniel Paulus) wrote…</i></summary><blockquote>

Yes, read the linked page for the explanation
</blockquote></details>

Got it. Nice enhancement.
___
*[`src/SIL.XForge.Scripture/ClientApp/src/xforge-common/l10n-number.pipe.ts` line 31 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/2759#-O8DERTX4d_PuWUfJRae:-O8DkzT86cVHUfpABQt1:b-j4z3x0) ([raw file](https://github.com/sillsdev/web-xforge/blob/c941e756cbd60a1496c5961029092da64558586b/src/SIL.XForge.Scripture/ClientApp/src/xforge-common/l10n-number.pipe.ts#L31)):*
<details><summary><i>Previously, Nateowami (Nathaniel Paulus) wrote…</i></summary><blockquote>

Why? It's inefficient to keep converting strings to numbers, and I can't think of a case where we actually want to do that.
</blockquote></details>

Hmm, maybe it would be best to have the parameter have the `number | string` type, and set a new variable to be `string` type. It seems odd that the `value` parameter is `number`, but then right below we check if it is a string.

**Review by Nateowami — COMMENTED** [review]
> I wonder if we should add this to the chapter select component.

The highest number in a chapter selector would be 150. Using Chromium, none of the locales we support would render anything differently for any number under 1000. In Firefox, Arabic and Nepali would be rendered differently for numbers starting from 0. I don't see a value in changing it unless 1) we knew users wanted it, and 2) we knew they would be using Firefox and would therefore even see a difference.

> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/2759#-:-O8DxDwH6slZ-KSEbJmQ:b-hzjpdx)* status: 89 of 90 files reviewed, 1 unresolved discussion (waiting on @RaymondLuong3)

___
*[`src/SIL.XForge.Scripture/ClientApp/src/xforge-common/l10n-number.pipe.ts` line 31 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/2759#-O8DERTX4d_PuWUfJRae:-O8Dx793CmZsWGsJqpnt:bvvul1r) ([raw file](https://github.com/sillsdev/web-xforge/blob/c941e756cbd60a1496c5961029092da64558586b/src/SIL.XForge.Scripture/ClientApp/src/xforge-common/l10n-number.pipe.ts#L31)):*
<details><summary><i>Previously, RaymondLuong3 (Raymond Luong) wrote…</i></summary><blockquote>

Hmm, maybe it would be best to have the parameter have the `number | string` type, and set a new variable to be `string` type. It seems odd that the `value` parameter is `number`, but then right below we check if it is a string.
</blockquote></details>

Good catch. This was the result of reworking things a couple times.

**Review by RaymondLuong3 — APPROVED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/2759)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @Nateowami)

**Pull request merged**
