### PR TITLE
Move note creation and edit logic into the dialog component

### PR DESCRIPTION
**Pull request by RaymondLuong3**
* create or modify note thread on dialog save
* return boolean on dialog close to indicate if notes need to be refreshed
* update tests

- - -
This change is [Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1525)

### CODE REVIEW

**Review by Nateowami — COMMENTED** [review]
Just tested this and so far it looks good. I haven't reviewed the actual code changes yet.

> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1525#-:-NDdhZKx-qu2sk9lG23m:b-af1qgm)* status: 0 of 4 files reviewed, all discussions resolved

**Review by nigel-wells — CHANGES_REQUESTED** [review]
This seems fine refactoring the code into the dialog. I had other comments but I know this is a work in progress. Probably wouldn't hurt for @nateowami to look over it as well as I know you two have been working together through some of this.

> Reviewed 4 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1525#-:-NEETX_v3JKUwCWOiZLk:bs3bcoz)* status: all files reviewed, 2 unresolved discussions (waiting on @RaymondLuong3)

___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/note-dialog/note-dialog.component.ts` line 352 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/1525#-NEERfKTEJljULvPc0c8:-NEERfKTEJljULvPc0c9:b-pgv6u2) ([raw file](https://github.com/sillsdev/web-xforge/blob/6fdd3c715d9744a37324794470c7dd69fc398ebd/src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/note-dialog/note-dialog.component.ts#L352)):*
> ```XML
>       this.currentNoteContent.trim().length === 0
>     ) {
>       this.dialogRef.close(false);
> ```

Nit: Is `false` relevant as only `true` is handled
Also, should the dialog be closed if nothing was entered or should an error be displayed instead?
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/note-dialog/note-dialog.component.ts` line 384 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/1525#-NEESVLh491BLf-4Kbm8:-NEESVLh491BLf-4Kbm9:bretlwt) ([raw file](https://github.com/sillsdev/web-xforge/blob/6fdd3c715d9744a37324794470c7dd69fc398ebd/src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/note-dialog/note-dialog.component.ts#L384)):*
> ```XML
>         ownerRef: this.userService.currentUserId,
>         notes: [this.noteBeingEdited],
>         position: { start: 0, length: 0 },
> ```

Is this supposed to be relevant to where the note is being placed?

**Review by RaymondLuong3 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1525)* status: all files reviewed, 2 unresolved discussions (waiting on @nigel-wells)

___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/note-dialog/note-dialog.component.ts` line 352 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/1525#-NEERfKTEJljULvPc0c8:-NEb02j32_9F4WJpO7xR:b11csma) ([raw file](https://github.com/sillsdev/web-xforge/blob/6fdd3c715d9744a37324794470c7dd69fc398ebd/src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/note-dialog/note-dialog.component.ts#L352)):*
<details><summary><i>Previously, nigel-wells (Nigel Wells) wrote…</i></summary><blockquote>

Nit: Is `false` relevant as only `true` is handled
Also, should the dialog be closed if nothing was entered or should an error be displayed instead?
</blockquote></details>

Good thinking. False is really not relevant. In Paratext, closing the dialog with nothing entered results in no note saved. Maybe this can be improved, but I don't know if there is a compelling reason to show an error rather than just close the dialog.
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/note-dialog/note-dialog.component.ts` line 384 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/1525#-NEESVLh491BLf-4Kbm8:-NEb0_MQ6-g6i7C4tIyh:b-v7zk4v) ([raw file](https://github.com/sillsdev/web-xforge/blob/6fdd3c715d9744a37324794470c7dd69fc398ebd/src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/note-dialog/note-dialog.component.ts#L384)):*
<details><summary><i>Previously, nigel-wells (Nigel Wells) wrote…</i></summary><blockquote>

Is this supposed to be relevant to where the note is being placed?
</blockquote></details>

That will be added in the future if there is a need for it. For now, we want to get the feature out, and see how people use it so we can get a better idea of what enhancements are needed.

**Review by nigel-wells — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1525#-:-NEc73zRAhHdFj8goG0h:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @RaymondLuong3)

___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/note-dialog/note-dialog.component.ts` line 352 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/1525#-NEERfKTEJljULvPc0c8:-NEc6oBC6BXFl1KNbR1a:b-5sgmf3) ([raw file](https://github.com/sillsdev/web-xforge/blob/6fdd3c715d9744a37324794470c7dd69fc398ebd/src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/note-dialog/note-dialog.component.ts#L352)):*
<details><summary><i>Previously, RaymondLuong3 (Raymond Luong) wrote…</i></summary><blockquote>

Good thinking. False is really not relevant. In Paratext, closing the dialog with nothing entered results in no note saved. Maybe this can be improved, but I don't know if there is a compelling reason to show an error rather than just close the dialog.
</blockquote></details>

I'm happy if you're following how PT does it.
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/note-dialog/note-dialog.component.ts` line 384 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/1525#-NEESVLh491BLf-4Kbm8:-NEc6zadA3zWW_sJuqEI:bqequ6b) ([raw file](https://github.com/sillsdev/web-xforge/blob/6fdd3c715d9744a37324794470c7dd69fc398ebd/src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/note-dialog/note-dialog.component.ts#L384)):*
<details><summary><i>Previously, RaymondLuong3 (Raymond Luong) wrote…</i></summary><blockquote>

That will be added in the future if there is a need for it. For now, we want to get the feature out, and see how people use it so we can get a better idea of what enhancements are needed.
</blockquote></details>

Thanks for confirming - I knew you'd be all over it.

**Pull request merged**
