### PR TITLE
SF-3077 Add UI for mixed training sources

### PR DESCRIPTION
**Pull request by RaymondLuong3**
This PR adds the ability to mix in training data from multiple sources. See the [balsamiq](https://balsamiq.cloud/sghq53/pejrlz8/r5325) for the original design.

No training books selected
Mixed Training No Books Selected

Training books selected
Mixed training current books selected

- - -
This change is [Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/2875)

### CODE REVIEW

**Comment by Nateowami** [comment]
Observations:
- Bulk selecting NT or OT in the top panel doesn't cause the relevant books to update in the bottom panel

**Comment by Nateowami** [comment]
Here are some issues I'm seeing:

**Review by josephmyers — COMMENTED** [review]
We'll also want to add an optional title parameter to the book selection component, which contains the bulk select checkboxes. Then place the project name on the same line as the checkboxes.

> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/2875#-:-ODJHJE94zeXX22MPPCb:b-v8588q)* status: 0 of 14 files reviewed, all discussions resolved

**Comment by Nateowami** [comment]
@RaymondLuong3 I should note that when selecting books in bulk, it seems that the first time yous select them it selects correctly, but then upon unselecting and re-selecting it doesn't.

**Review by RaymondLuong3 — COMMENTED** [review]
Thanks for finding that. I figured out the main issue was that arrays were being passed around by reference rather than by values. I've cleaned it up and now it works. I've also addressed the extra training books notice and the project label for the multi-book-select component.

> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/2875#-:-ODO1E5BBi_P_0IZrSt1:b-m19n3l)* status: 0 of 16 files reviewed, all discussions resolved

**Review by pmachapman — CHANGES_REQUESTED** [review]
I really like the new interface! Just a couple of minor nits.

...and thank you for fixing my frontend/realtimeserver mistakes on SF-2900 :-S

> Reviewed 6 of 14 files at r3, 7 of 16 files at r4, 10 of 10 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/2875#-:-OEHGLIJEoaWtXFA7D9L:b-1h53u2)* status: all files reviewed, 3 unresolved discussions (waiting on @RaymondLuong3)

___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-generation-steps/draft-generation-steps.component.spec.ts` line 162 at r5](https://reviewable.io/reviews/sillsdev/web-xforge/2875#-OEHNviD5sYrZcmgM2xS:-OEHNviD5sYrZcmgM2xT:b-absiox) ([raw file](https://github.com/sillsdev/web-xforge/blob/73d9960ef5b7e9c92a4ec0172e080f1f64d6e0d4/src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-generation-steps/draft-generation-steps.component.spec.ts#L162)):*
> ```XML
>         mockAlternateTrainingSourceProjectDoc
>       );
>       when(mockFeatureFlagService.allowFastTraining).thenReturn(createTestFeatureFlag(false));
> ```

NIT: Should this be removed as it occurs 4 lines below?



_Code quote:_
```XML
when(mockFeatureFlagService.allowFastTraining).thenReturn(createTestFeatureFlag(false));
```
___
*[`src/RealtimeServer/scriptureforge/services/sf-project-migrations.ts` line 419 at r5](https://reviewable.io/reviews/sillsdev/web-xforge/2875#-OEHHc_tCnAMzo6tdPb2:-OEHHc_tCnAMzo6tdPb3:br9rm6k) ([raw file](https://github.com/sillsdev/web-xforge/blob/73d9960ef5b7e9c92a4ec0172e080f1f64d6e0d4/src/RealtimeServer/scriptureforge/services/sf-project-migrations.ts#L419)):*
> ```XML
>     }
> 
>     await submitMigrationOp(SFProjectMigration21.VERSION, doc, ops);
> ```

NIT: This should be:

```ts
await submitMigrationOp(SFProjectMigration22.VERSION, doc, ops);
```



_Code quote:_
```XML
await submitMigrationOp(SFProjectMigration21.VERSION, doc, ops);
```
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-generation-steps/draft-generation-steps.component.ts` line 414 at r5](https://reviewable.io/reviews/sillsdev/web-xforge/2875#-OEHN5q460em_in39fxS:-OEHN5q460em_in39fxT:b-brgo7b) ([raw file](https://github.com/sillsdev/web-xforge/blob/73d9960ef5b7e9c92a4ec0172e080f1f64d6e0d4/src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-generation-steps/draft-generation-steps.component.ts#L414)):*
> ```XML
>     if (previousTrainingRange === '' && trainingScriptureRange != null) {
>       previousTrainingRange =
>         this.activatedProject.projectDoc?.data?.translateConfig.draftConfig.lastSelectedTrainingScriptureRange ?? '';
> ```

NIT: Should this just be `previousTrainingRange = trainingScriptureRange`, or am I misunderstanding the code?



_Code quote:_
```XML
      previousTrainingRange =
        this.activatedProject.projectDoc?.data?.translateConfig.draftConfig.lastSelectedTrainingScriptureRange ?? '';
```

**Review by RaymondLuong3 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/2875)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @RaymondLuong3)

___
*[`src/RealtimeServer/scriptureforge/services/sf-project-migrations.ts` line 419 at r5](https://reviewable.io/reviews/sillsdev/web-xforge/2875#-OEHHc_tCnAMzo6tdPb2:-OEKYlRN2lfc6dqRIMfL:b6zrrk4) ([raw file](https://github.com/sillsdev/web-xforge/blob/73d9960ef5b7e9c92a4ec0172e080f1f64d6e0d4/src/RealtimeServer/scriptureforge/services/sf-project-migrations.ts#L419)):*
<details><summary><i>Previously, pmachapman (Peter Chapman) wrote…</i></summary><blockquote>

NIT: This should be:

```ts
await submitMigrationOp(SFProjectMigration22.VERSION, doc, ops);
```
</blockquote></details>

Good catch!
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-generation-steps/draft-generation-steps.component.ts` line 414 at r5](https://reviewable.io/reviews/sillsdev/web-xforge/2875#-OEHN5q460em_in39fxS:-OEKaZZC1bEhIKgQSRr3:b-ozxfqb) ([raw file](https://github.com/sillsdev/web-xforge/blob/73d9960ef5b7e9c92a4ec0172e080f1f64d6e0d4/src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-generation-steps/draft-generation-steps.component.ts#L414)):*
<details><summary><i>Previously, pmachapman (Peter Chapman) wrote…</i></summary><blockquote>

NIT: Should this just be `previousTrainingRange = trainingScriptureRange`, or am I misunderstanding the code?
</blockquote></details>

Nice. Thanks
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-generation-steps/draft-generation-steps.component.spec.ts` line 162 at r5](https://reviewable.io/reviews/sillsdev/web-xforge/2875#-OEHNviD5sYrZcmgM2xS:-OEKZ9je0o9Yk_YK4vVw:b-896fix) ([raw file](https://github.com/sillsdev/web-xforge/blob/73d9960ef5b7e9c92a4ec0172e080f1f64d6e0d4/src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-generation-steps/draft-generation-steps.component.spec.ts#L162)):*
<details><summary><i>Previously, pmachapman (Peter Chapman) wrote…</i></summary><blockquote>

NIT: Should this be removed as it occurs 4 lines below?
</blockquote></details>

Done.

**Review by pmachapman — APPROVED** [review]
:lgtm:

> Reviewed 3 of 3 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/2875#-:-OEKuYpg831cABGj-Ugk:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @RaymondLuong3)

**Review by pmachapman — APPROVED** [review]
> Reviewed 5 of 5 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/2875)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @RaymondLuong3)

**Pull request merged**
