### PR TITLE
SF-2198 Position single button player with active text

### PR DESCRIPTION
**Pull request by RaymondLuong3**
Before
Single button player before

After
Single button player after

- - -
This change is [Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/2022)

### CODE REVIEW

**Review by josephmyers — CHANGES_REQUESTED** [review]
Overall, looks good. However, I'm not a huge fan of this when there's no scripture audio. Fortunately, the fix is as simple as putting the "align-items" back (see below). But let me know if you were intending this!


> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/2022#-:-Ncup6PH3OeLvijSPMyz:b-4b9gk5)* status: all files reviewed, 1 unresolved discussion (waiting on @RaymondLuong3)

___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-answers/checking-question/checking-question.component.scss` line 11 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/2022#-Ncup-HSADAl7ImhV4mO:-Ncup-HSADAl7ImhV4mP:b-liyo54) ([raw file](https://github.com/sillsdev/web-xforge/blob/8742fb2b04253ff49a1ea9668b586a0e9be84b2c/src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-answers/checking-question/checking-question.component.scss#L11)):*
> ```SCSS
>   display: flex;
>   flex-direction: row;
>   align-items: center;
> ```

Put this back to fix what I described above.

**Review by RaymondLuong3 — COMMENTED** [review]
I like that the text isn't made so small, and also that I can click the entire verse to select it. Thanks for working through the this redesign. Just one minor comment. Then you will have to approve this, since I am the author I cannot approve it.

> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/2022#-:-Ndl6LasBfxgiz69chz-:b-awnz4h)* status: 0 of 2 files reviewed, 2 unresolved discussions (waiting on @josephmyers)

___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-answers/checking-question/checking-question.component.html` line 3 at r2](https://reviewable.io/reviews/sillsdev/web-xforge/2022#-Ndl3mDR5p4aRLe3W8DW:-Ndl3mDR5p4aRLe3W8DX:b-jtnqoy) ([raw file](https://github.com/sillsdev/web-xforge/blob/71e196c5eb9f23735de5c98b2a733509e1900809/src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-answers/checking-question/checking-question.component.html#L3)):*
> ```HTML
> <ng-container *transloco="let t; read: 'checking_questions'">
>   <div>
>     <div class="scripture-audio" [class]="focusedText" *ngIf="scriptureAudioUrl">
> ```

This could be `scriptureAudioUrl != null`



_Code quote:_
```HTML
    <div class="scripture-audio" [class]="focusedText" *ngIf="scriptureAudioUrl">
```
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-answers/checking-question/checking-question.component.scss` line 11 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/2022#-Ncup-HSADAl7ImhV4mO:-Ndl6ITg3QoWRFqcoGvr:b-896fix) ([raw file](https://github.com/sillsdev/web-xforge/blob/82964d03391e7b5574521415cfb0a1264a9871bb/src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-answers/checking-question/checking-question.component.scss#L11)):*
<details><summary><i>Previously, josephmyers wrote…</i></summary><blockquote>

Put this back to fix what I described above.
</blockquote></details>

Done.

**Review by josephmyers — COMMENTED** [review]
> Reviewed 2 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/2022)* status: 0 of 2 files reviewed, 1 unresolved discussion (waiting on @RaymondLuong3)

___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-answers/checking-question/checking-question.component.html` line 3 at r2](https://reviewable.io/reviews/sillsdev/web-xforge/2022#-Ndl3mDR5p4aRLe3W8DW:-NebEQUD6bg9j4ETIbPV:b-896fix) ([raw file](https://github.com/sillsdev/web-xforge/blob/71e196c5eb9f23735de5c98b2a733509e1900809/src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-answers/checking-question/checking-question.component.html#L3)):*
<details><summary><i>Previously, RaymondLuong3 (Raymond Luong) wrote…</i></summary><blockquote>

This could be `scriptureAudioUrl != null`
</blockquote></details>

Done.

**Comment by josephmyers** [comment]
Thanks for reviewing these changes, @RaymondLuong3! Sorry it's taken me so long to get to your comment. I'm actually not sure who can/should approve it at this point. Let me know if you have any more concerns!

**Review by josephmyers — APPROVED** [review]
> Reviewed 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/2022)* status: all files reviewed, 1 unresolved discussion (waiting on @RaymondLuong3)

**Review by RaymondLuong3 — COMMENTED** [review]
Thank you! I think typically we can approve each other's work when we are collaborating.

> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/2022#-:-Ned65nA-boRftBPO03B:b-nfgbsz)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @RaymondLuong3)

**Pull request merged**
