### PR TITLE
Use the to do comment tag icon for the project for new note threads

### PR DESCRIPTION
**Pull request by RaymondLuong3**
* add the noteIcon property to the SFProject
* use the CommentTags of a project to get the to do icon name
* set the noteIcon property at sync time
* set the tagIcon to the project noteIcon on new note threads

- - -
This change is [Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1534)

### CODE REVIEW

**Review by nigel-wells — CHANGES_REQUESTED** [review]
Logically this looks all fine.
I'm not sure if this is opening a can of worms but it seems like we have lots of different names for the same thing which we could tidy up? i.e.
- toDoIcon
- ToDoCommentIcon
- NoteIcon
- toDoTagId
- iconName
- TagIcons
- iconTag (is deleted now)

I think some of these might be inherited by PT but the ones we have control over could be the same

> Reviewed 11 of 11 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1534#-:-NFfm7l_3a3-m30sl7ya:b-wb7a1u)* status: all files reviewed, 1 unresolved discussion (waiting on @RaymondLuong3)

___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/note-dialog/note-dialog.component.ts` line 388 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/1534#-NFfo15ZCERKP_U6lwQ0:-NFfo15ZCERKP_U6lwQ1:b9cq53t) ([raw file](https://github.com/sillsdev/web-xforge/blob/deabbf0fe1c30add03071d100a2fac77d078ba09/src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/note-dialog/note-dialog.component.ts#L388)):*
> ```XML
>         originalSelectedText: this.segmentText,
>         originalContextAfter: '',
>         tagIcon: this.projectProfileDoc!.data!.noteIcon ?? '01flag1',
> ```

Could this use the `defaultNoteThreadIcon()` method to get the fallback string. Easy said than done as that method doesn't return the name on its own - perhaps it should?

**Review by RaymondLuong3 — COMMENTED** [review]
Thanks for looking into that. From your list, I was able to merge iconName and toDoComment icon into noteIcon. There may be more that can be done in the future.

> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1534#-:-NFuIDg58CiaFSpjVR83:bpndwet)* status: all files reviewed, 1 unresolved discussion (waiting on @nigel-wells)

___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/note-dialog/note-dialog.component.ts` line 388 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/1534#-NFfo15ZCERKP_U6lwQ0:-NFuHflR8gO4f4psMIHb:b-896fix) ([raw file](https://github.com/sillsdev/web-xforge/blob/deabbf0fe1c30add03071d100a2fac77d078ba09/src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/note-dialog/note-dialog.component.ts#L388)):*
<details><summary><i>Previously, nigel-wells (Nigel Wells) wrote…</i></summary><blockquote>

Could this use the `defaultNoteThreadIcon()` method to get the fallback string. Easy said than done as that method doesn't return the name on its own - perhaps it should?
</blockquote></details>

Done.

**Review by nigel-wells — COMMENTED** [review]
Thanks for working through renaming all of those - much cleaner. 
I see there is still one instance you kept it as `noteIcon`. Was that because the icon was specific to a note rather than a project icon?

> Reviewed 11 of 11 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1534#-:-NFv5kVh2rT7kw64iyjr:bm3nhzn)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @RaymondLuong3)

**Review by RaymondLuong3 — COMMENTED** [review]
Oh yes, I see it in note-thread-doc.ts. I just missed that one.

> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1534#-:-NGIUhpE6zkNyTZSDwup:b6rmvt3)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @RaymondLuong3)

**Review by nigel-wells — APPROVED** [review]
Thanks for that - much easier to know they all say and refer the same thing now :)

> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1534#-:-NGJ0Y-b5vreycs6v0kN:b-xajdp4)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @RaymondLuong3)

**Pull request merged**
