### PR TITLE
SF-2408 Link to audio timing file information

### PR DESCRIPTION
**Pull request by marksvc**
---
Right now this links to a guide that doesn't exist, so we need to post a guide first. :)

Some proposed initial text for the guide is in the SF-2408 issue description.

This change is [Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/2236)

### CODE REVIEW

**Review by Nateowami — CHANGES_REQUESTED** [review]
> Reviewed 5 of 5 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/2236)* status: all files reviewed, 4 unresolved discussions (waiting on @marksvc)

___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/checking/chapter-audio-dialog/chapter-audio-dialog.component.html` line 69 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/2236#-NlUnUCy7WqCvvGv4TU8:-NlUnUCzD6ppxuidijrs:b-paljn5) ([raw file](https://github.com/sillsdev/web-xforge/blob/35315ed1b3a530626d095fe31d3b8566c5ea1d92/src/SIL.XForge.Scripture/ClientApp/src/app/checking/chapter-audio-dialog/chapter-audio-dialog.component.html#L69)):*
> ```HTML
>   </mat-dialog-content>
>   <mat-dialog-actions>
>     <button mat-button id="help-button" (click)="help()"><i class="material-icons">help</i> Help</button>
> ```

How about using a link instead of a button element? Material supports doing the exact same style of button while still having it be an anchor element. See https://v15.material.angular.io/components/button/overview

From their example:
``` html
<a mat-button href="https://www.google.com/" target="_blank">Link</a>
```
This uses less code, and supports things like Ctrl+Click or middle mouse button for opening in new tab (Yes, we plan to make it open in a new tab, but the user doesn't know that). It means you can preview the URL at the bottom of the page. All the things that links do but buttons don't out of the box.
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/checking/chapter-audio-dialog/chapter-audio-dialog.component.html` line 69 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/2236#-NlUoMAL89XKuAsmBRXI:-NlUoMAL89XKuAsmBRXJ:b-beol3o) ([raw file](https://github.com/sillsdev/web-xforge/blob/35315ed1b3a530626d095fe31d3b8566c5ea1d92/src/SIL.XForge.Scripture/ClientApp/src/app/checking/chapter-audio-dialog/chapter-audio-dialog.component.html#L69)):*
> ```HTML
>   </mat-dialog-content>
>   <mat-dialog-actions>
>     <button mat-button id="help-button" (click)="help()"><i class="material-icons">help</i> Help</button>
> ```

How about internationalizing this?
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/checking/chapter-audio-dialog/chapter-audio-dialog.component.html` line 69 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/2236#-NlUoOelDv2wLXy5TR3P:-NlUoOelDv2wLXy5TR3Q:b-ltzpk4) ([raw file](https://github.com/sillsdev/web-xforge/blob/35315ed1b3a530626d095fe31d3b8566c5ea1d92/src/SIL.XForge.Scripture/ClientApp/src/app/checking/chapter-audio-dialog/chapter-audio-dialog.component.html#L69)):*
> ```HTML
>   </mat-dialog-content>
>   <mat-dialog-actions>
>     <button mat-button id="help-button" (click)="help()"><i class="material-icons">help</i> Help</button>
> ```

Icons should be in the form of `<mat-icon>help</mat-icon>`
___
*[`src/SIL.XForge.Scripture/ClientApp/src/xforge-common/external-url.service.ts` line 38 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/2236#-NlUop43C1pJPXtDsPyY:-NlUop43C1pJPXtDsPyZ:b-2hcvoy) ([raw file](https://github.com/sillsdev/web-xforge/blob/35315ed1b3a530626d095fe31d3b8566c5ea1d92/src/SIL.XForge.Scripture/ClientApp/src/xforge-common/external-url.service.ts#L38)):*
> ```XML
> 
>   get chapterAudioHelpPage(): string {
>     return this.helps + '/scripture-audio';
> ```

I think I'm going to propose a different URL, but still thinking about it.

**Review by Nateowami — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/2236)* status: all files reviewed, 5 unresolved discussions (waiting on @marksvc)

___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/checking/chapter-audio-dialog/chapter-audio-dialog.component.html` line 72 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/2236#-NlUqWw0DdeoZEZ9AsaX:-NlUqWw0DdeoZEZ9AsaY:btk56nz) ([raw file](https://github.com/sillsdev/web-xforge/blob/35315ed1b3a530626d095fe31d3b8566c5ea1d92/src/SIL.XForge.Scripture/ClientApp/src/app/checking/chapter-audio-dialog/chapter-audio-dialog.component.html#L72)):*
> ```HTML
>     <span class="flex-spacer"></span>
>     <div class="uploading" *ngIf="isLoadingAudio">
>       <span>Uploading...</span>
> ```

Looks like this text didn't get localized either.

**Comment by marksvc** [comment]
That's helpful, thank you! I'll plan to do these tomorrow.

**Review by marksvc — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/2236)* status: all files reviewed, 5 unresolved discussions (waiting on @Nateowami)

___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/checking/chapter-audio-dialog/chapter-audio-dialog.component.html` line 69 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/2236#-NlUoOelDv2wLXy5TR3P:-NlVo7lwCUzlSP3_jdrJ:b-896fix) ([raw file](https://github.com/sillsdev/web-xforge/blob/35315ed1b3a530626d095fe31d3b8566c5ea1d92/src/SIL.XForge.Scripture/ClientApp/src/app/checking/chapter-audio-dialog/chapter-audio-dialog.component.html#L69)):*
<details><summary><i>Previously, Nateowami (Nathaniel Paulus) wrote…</i></summary><blockquote>

Icons should be in the form of `<mat-icon>help</mat-icon>`
</blockquote></details>

Done.
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/checking/chapter-audio-dialog/chapter-audio-dialog.component.html` line 69 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/2236#-NlUoMAL89XKuAsmBRXI:-NlVoSJB9DNqd-6YdZHN:b-896fix) ([raw file](https://github.com/sillsdev/web-xforge/blob/35315ed1b3a530626d095fe31d3b8566c5ea1d92/src/SIL.XForge.Scripture/ClientApp/src/app/checking/chapter-audio-dialog/chapter-audio-dialog.component.html#L69)):*
<details><summary><i>Previously, Nateowami (Nathaniel Paulus) wrote…</i></summary><blockquote>

How about internationalizing this?
</blockquote></details>

Done.
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/checking/chapter-audio-dialog/chapter-audio-dialog.component.html` line 69 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/2236#-NlUnUCy7WqCvvGv4TU8:-NlVp4bDBjtamEIEvAA4:b-vlcqs5) ([raw file](https://github.com/sillsdev/web-xforge/blob/35315ed1b3a530626d095fe31d3b8566c5ea1d92/src/SIL.XForge.Scripture/ClientApp/src/app/checking/chapter-audio-dialog/chapter-audio-dialog.component.html#L69)):*
<details><summary><i>Previously, Nateowami (Nathaniel Paulus) wrote…</i></summary><blockquote>

How about using a link instead of a button element? Material supports doing the exact same style of button while still having it be an anchor element. See https://v15.material.angular.io/components/button/overview

From their example:
``` html
<a mat-button href="https://www.google.com/" target="_blank">Link</a>
```
This uses less code, and supports things like Ctrl+Click or middle mouse button for opening in new tab (Yes, we plan to make it open in a new tab, but the user doesn't know that). It means you can preview the URL at the bottom of the page. All the things that links do but buttons don't out of the box.
</blockquote></details>

Thank you. I was hoping to find something like this but didn't look in the right place. 
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/checking/chapter-audio-dialog/chapter-audio-dialog.component.html` line 72 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/2236#-NlUqWw0DdeoZEZ9AsaX:-NlVpGARC7r1eofghXX9:bbda65k) ([raw file](https://github.com/sillsdev/web-xforge/blob/35315ed1b3a530626d095fe31d3b8566c5ea1d92/src/SIL.XForge.Scripture/ClientApp/src/app/checking/chapter-audio-dialog/chapter-audio-dialog.component.html#L72)):*
<details><summary><i>Previously, Nateowami (Nathaniel Paulus) wrote…</i></summary><blockquote>

Looks like this text didn't get localized either.
</blockquote></details>

I'll push another PR with this one.
___
*[`src/SIL.XForge.Scripture/ClientApp/src/xforge-common/external-url.service.ts` line 38 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/2236#-NlUop43C1pJPXtDsPyY:-NlVpek11Vg69DyYhhpA:b-80tlqk) ([raw file](https://github.com/sillsdev/web-xforge/blob/35315ed1b3a530626d095fe31d3b8566c5ea1d92/src/SIL.XForge.Scripture/ClientApp/src/xforge-common/external-url.service.ts#L38)):*
<details><summary><i>Previously, Nateowami (Nathaniel Paulus) wrote…</i></summary><blockquote>

I think I'm going to propose a different URL, but still thinking about it.
</blockquote></details>

Sure.

**Comment by marksvc** [comment]
@Nateowami Is there something I can do to help get the guide posted online?

**Comment by Nateowami** [comment]
@marksvc This is now published, and I've rebased this PR and updated the URL

**Review by Nateowami — CHANGES_REQUESTED** [review]
> Reviewed 4 of 4 files at r2, 1 of 5 files at r4.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/2236)* status: 2 of 6 files reviewed, 3 unresolved discussions (waiting on @marksvc)

___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/checking/chapter-audio-dialog/chapter-audio-dialog.component.html` line 77 at r4](https://reviewable.io/reviews/sillsdev/web-xforge/2236#-O-iYenv5OIn98ej4N6X:-O-iYenv5OIn98ej4N6Y:bapl81v) ([raw file](https://github.com/sillsdev/web-xforge/blob/a643246c655fe8171c06d4db5c532e4feaa5aacb/src/SIL.XForge.Scripture/ClientApp/src/app/checking/chapter-audio-dialog/chapter-audio-dialog.component.html#L77)):*
> ```HTML
>   <mat-dialog-actions>
>     <a mat-button [href]="externalUrlService.chapterAudioHelpPage" target="_blank"
>       ><mat-icon>help</mat-icon> {{ "app.help" | transloco }}</a
> ```

Can you fix the formatting? Having HTML tags unnecessarily span multiple lines makes it harder to read and edit than necessary.
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/checking/chapter-audio-dialog/chapter-audio-dialog.component.html` line 77 at r4](https://reviewable.io/reviews/sillsdev/web-xforge/2236#-O-iYo2M71Ojc0JfGbKN:-O-iYo2M71Ojc0JfGbKO:bnf25d) ([raw file](https://github.com/sillsdev/web-xforge/blob/a643246c655fe8171c06d4db5c532e4feaa5aacb/src/SIL.XForge.Scripture/ClientApp/src/app/checking/chapter-audio-dialog/chapter-audio-dialog.component.html#L77)):*
> ```HTML
>   <mat-dialog-actions>
>     <a mat-button [href]="externalUrlService.chapterAudioHelpPage" target="_blank"
>       ><mat-icon>help</mat-icon> {{ "app.help" | transloco }}</a
> ```

Instead of referencing the string from the app component, can you create a new string for this component? It makes things a lot more maintainable. We had a recent instances where a string was shared like this, and removed from one component, and then broke another component without anyone noticing before it was merged.

I'm guessing you did this in order to try to reduce the amount of translation that needs to be done, but Crowdin handles duplicate strings pretty well, and if any language has this string translated already, we'll get the localization without any translator doing anything.
___
*[`src/SIL.XForge.Scripture/ClientApp/src/xforge-common/external-url.service.ts` line 38 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/2236#-NlUop43C1pJPXtDsPyY:-O-iZNFE9oAFfcaWmf-e:b-bw8e14) ([raw file](https://github.com/sillsdev/web-xforge/blob/35315ed1b3a530626d095fe31d3b8566c5ea1d92/src/SIL.XForge.Scripture/ClientApp/src/xforge-common/external-url.service.ts#L38)):*
<details><summary><i>Previously, marksvc wrote…</i></summary><blockquote>

Sure.
</blockquote></details>

Updated.

**Review by marksvc — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/2236)* status: 2 of 6 files reviewed, 2 unresolved discussions (waiting on @Nateowami)

___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/checking/chapter-audio-dialog/chapter-audio-dialog.component.html` line 77 at r4](https://reviewable.io/reviews/sillsdev/web-xforge/2236#-O-iYenv5OIn98ej4N6X:-O0KgMHH6-pmZggYFl-N:b-896fix) ([raw file](https://github.com/sillsdev/web-xforge/blob/a643246c655fe8171c06d4db5c532e4feaa5aacb/src/SIL.XForge.Scripture/ClientApp/src/app/checking/chapter-audio-dialog/chapter-audio-dialog.component.html#L77)):*
<details><summary><i>Previously, Nateowami (Nathaniel Paulus) wrote…</i></summary><blockquote>

Can you fix the formatting? Having HTML tags unnecessarily span multiple lines makes it harder to read and edit than necessary.
</blockquote></details>

Done.
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/checking/chapter-audio-dialog/chapter-audio-dialog.component.html` line 77 at r4](https://reviewable.io/reviews/sillsdev/web-xforge/2236#-O-iYo2M71Ojc0JfGbKN:-O0Kgvro0_7NHYcMk2uf:b-hm0y2v) ([raw file](https://github.com/sillsdev/web-xforge/blob/a643246c655fe8171c06d4db5c532e4feaa5aacb/src/SIL.XForge.Scripture/ClientApp/src/app/checking/chapter-audio-dialog/chapter-audio-dialog.component.html#L77)):*
<details><summary><i>Previously, Nateowami (Nathaniel Paulus) wrote…</i></summary><blockquote>

Instead of referencing the string from the app component, can you create a new string for this component? It makes things a lot more maintainable. We had a recent instances where a string was shared like this, and removed from one component, and then broke another component without anyone noticing before it was merged.

I'm guessing you did this in order to try to reduce the amount of translation that needs to be done, but Crowdin handles duplicate strings pretty well, and if any language has this string translated already, we'll get the localization without any translator doing anything.
</blockquote></details>

Okay, great. Thanks for the info on that. Done.

**Review by Nateowami — APPROVED** [review]
> Reviewed 3 of 5 files at r4, 2 of 2 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/2236)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @marksvc)

**Pull request merged**
