### PR TITLE
SF-1733 Redirect users viewing a deleted book

### PR DESCRIPTION
**Pull request by nigel-wells**
- Redirect to the translate overview page
- Dismiss all presence data

- - -
This change is [Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1505)

### CODE REVIEW

**Review by RaymondLuong3 — CHANGES_REQUESTED** [review]
I experimented with this and opened the project as a community checker. If the book is deleted during a sync, the page updated to the overview page, which is nice. It doesn't look like that we fixed here, but it was just how it already worked.

> Reviewed 7 of 7 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1505#-:-NCujs9U9IwGBMTOWn1s:bnv5sh7)* status: all files reviewed, 4 unresolved discussions (waiting on @nigel-wells)

___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.ts` line 1024 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/1505#-NCufwJlDgtyIHvpd54k:-NCufwJlDgtyIHvpd54l:bfsgkdc) ([raw file](https://github.com/sillsdev/web-xforge/blob/e82367766dc21de95a42737ac99f584a4bcc807b/src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.ts#L1024)):*
> ```XML
>       this.textDeletedDialogRef = this.dialogService.openMatDialog(TextDeletedDialogComponent);
>       this.textDeletedDialogRef.afterClosed().subscribe(() => {
>         this.router.navigateByUrl('/projects/' + this.projectDoc?.id + '/translate', { replaceUrl: true });
> ```

I would use this.projectDoc!.id. If it were ever to be undefined, we would get an error instead of sending the user to a url that doesn't exist.



_Code quote:_
```XML
'/projects/' + this.projectDoc?.id + '/translate',
```
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/text-deleted-dialog/text-deleted-dialog.component.html` line 1 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/1505#-NCuhGGdAXAv4RAfQTq3:-NCuhGGe1nCPpEdYk1T4:b-p5pi1e) ([raw file](https://github.com/sillsdev/web-xforge/blob/e82367766dc21de95a42737ac99f584a4bcc807b/src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/text-deleted-dialog/text-deleted-dialog.component.html#L1)):*
> ```HTML
> <ng-container *transloco="let t; read: 'text_deleted_dialog'">
> ```

Hey, while you are here, why don't you replace `message-dialog.component.html` with this dialog which is using angular material.



_Code quote:_
```HTML
<ng-container *transloco="let t; read: 'text_deleted_dialog'">
```
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/text-deleted-dialog/text-deleted-dialog.component.ts` line 6 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/1505#-NCuhhueAR9ycECUbgtb:-NCuhhueAR9ycECUbgtc:bt38hr8) ([raw file](https://github.com/sillsdev/web-xforge/blob/e82367766dc21de95a42737ac99f584a4bcc807b/src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/text-deleted-dialog/text-deleted-dialog.component.ts#L6)):*
> ```XML
>   templateUrl: './text-deleted-dialog.component.html'
> })
> export class TextDeletedDialogComponent {}
> ```

We do not need this component if we use the notice service to open the message dialog component.



_Code quote:_
```XML
})
export class TextDeletedDialogComponent {}
```
___
*[`src/SIL.XForge.Scripture/ClientApp/src/assets/i18n/non_checking_en.json` line 270 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/1505#-NCuhq0XCWv7d-sxWks4:-NCuhq0XCWv7d-sxWks5:b-s7sv09) ([raw file](https://github.com/sillsdev/web-xforge/blob/e82367766dc21de95a42737ac99f584a4bcc807b/src/SIL.XForge.Scripture/ClientApp/src/assets/i18n/non_checking_en.json#L270)):*
> ```JSON
>     "not_available_offline": "This text is not available offline. Connect to the Internet to see the text."
>   },
>   "text_deleted_dialog": {
> ```

This text can be moved to the editor component and provided to the message dialog.



_Code quote:_
```JSON
  "text_deleted_dialog": {
    "ok": "OK",
    "text_has_been_deleted": "The book has been deleted or is no longer accessible."
  },
```

**Review by nigel-wells — COMMENTED** [review]
Yes, there appeared to be logic already in place for the checking app - this PR just addresses it for the translate app

> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1505#-:-NCwu4D35Q4QOMbr8DxX:b-hpfwds)* status: 1 of 10 files reviewed, 4 unresolved discussions (waiting on @RaymondLuong3)

___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.ts` line 1024 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/1505#-NCufwJlDgtyIHvpd54k:-NCwupmCBDNIX3Ac7Ecv:b-9lgx6e) ([raw file](https://github.com/sillsdev/web-xforge/blob/e82367766dc21de95a42737ac99f584a4bcc807b/src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.ts#L1024)):*
<details><summary><i>Previously, RaymondLuong3 (Raymond Luong) wrote…</i></summary><blockquote>

I would use this.projectDoc!.id. If it were ever to be undefined, we would get an error instead of sending the user to a url that doesn't exist.
</blockquote></details>

Good point - have updated.
___
*[`src/SIL.XForge.Scripture/ClientApp/src/assets/i18n/non_checking_en.json` line 270 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/1505#-NCuhq0XCWv7d-sxWks4:-NCwz3x44c7L6xe_GQpZ:b-896fix) ([raw file](https://github.com/sillsdev/web-xforge/blob/e82367766dc21de95a42737ac99f584a4bcc807b/src/SIL.XForge.Scripture/ClientApp/src/assets/i18n/non_checking_en.json#L270)):*
<details><summary><i>Previously, RaymondLuong3 (Raymond Luong) wrote…</i></summary><blockquote>

This text can be moved to the editor component and provided to the message dialog.
</blockquote></details>

Done.
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/text-deleted-dialog/text-deleted-dialog.component.html` line 1 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/1505#-NCuhGGdAXAv4RAfQTq3:-NCwz4tW7NVvUULYPgPH:b-896fix) ([raw file](https://github.com/sillsdev/web-xforge/blob/e82367766dc21de95a42737ac99f584a4bcc807b/src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/text-deleted-dialog/text-deleted-dialog.component.html#L1)):*
<details><summary><i>Previously, RaymondLuong3 (Raymond Luong) wrote…</i></summary><blockquote>

Hey, while you are here, why don't you replace `message-dialog.component.html` with this dialog which is using angular material.
</blockquote></details>

Done.
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/text-deleted-dialog/text-deleted-dialog.component.ts` line 6 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/1505#-NCuhhueAR9ycECUbgtb:-NCwz-Q66NrBSGidEngd:b-hos5o) ([raw file](https://github.com/sillsdev/web-xforge/blob/e82367766dc21de95a42737ac99f584a4bcc807b/src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/text-deleted-dialog/text-deleted-dialog.component.ts#L6)):*
<details><summary><i>Previously, RaymondLuong3 (Raymond Luong) wrote…</i></summary><blockquote>

We do not need this component if we use the notice service to open the message dialog component.
</blockquote></details>

Ah, good call - forgot all about that generic message dialog. Done.

**Review by Nateowami — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1505)* status: 1 of 10 files reviewed, 4 unresolved discussions (waiting on @RaymondLuong3)

___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/text-deleted-dialog/text-deleted-dialog.component.ts` line 6 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/1505#-NCuhhueAR9ycECUbgtb:-NCx8cScEf4PDXLnbGzM:btbdws) ([raw file](https://github.com/sillsdev/web-xforge/blob/e82367766dc21de95a42737ac99f584a4bcc807b/src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/text-deleted-dialog/text-deleted-dialog.component.ts#L6)):*
<details><summary><i>Previously, nigel-wells (Nigel Wells) wrote…</i></summary><blockquote>

Ah, good call - forgot all about that generic message dialog. Done.
</blockquote></details>

@nigel-wells Actually would be better to use the `DialogService.message()` method, since `NoticeService.showMessageDialog()` is going to be removed. It's already used a couple places; you can see them for examples.

**Review by RaymondLuong3 — APPROVED** [review]
Nice work. I think this is good to go, but it will depend on PR #1510. If that gets merged in first, things here will need to change.

> Reviewed 7 of 9 files at r2, 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1505#-:-ND4HUdw2zxUs2gib05b:beuver5)* status: all files reviewed, 1 unresolved discussion (waiting on @nigel-wells)

___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.spec.ts` line 156 at r3](https://reviewable.io/reviews/sillsdev/web-xforge/1505#-ND4GA9mDCCVTa3LU-lO:-ND4GA9mDCCVTa3LU-lP:bad9rnl) ([raw file](https://github.com/sillsdev/web-xforge/blob/3af30f75df225fa2a1cb8dd53ab1e0c7d9bed294/src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.spec.ts#L156)):*
> ```XML
>     env.wait();
> 
>     const dialogMessage = spyOn((env.component as any).dialogService, 'message').and.callThrough();
> ```

Instead of using the real dialog service, you could mock the dialog service. Are there advantages in using the real dialog service? Hmm, it looks like that is the convention in this test file. So then this is ok.



_Code quote:_
```XML
    const dialogMessage = spyOn((env.component as any).dialogService, 'message').and.callThrough();
```

**Review by nigel-wells — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1505)* status: all files reviewed, 1 unresolved discussion (waiting on @RaymondLuong3)

___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.spec.ts` line 156 at r3](https://reviewable.io/reviews/sillsdev/web-xforge/1505#-ND4GA9mDCCVTa3LU-lO:-ND4q062Bc-xZZufwyCY:bqrjvzg) ([raw file](https://github.com/sillsdev/web-xforge/blob/3af30f75df225fa2a1cb8dd53ab1e0c7d9bed294/src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.spec.ts#L156)):*
<details><summary><i>Previously, RaymondLuong3 (Raymond Luong) wrote…</i></summary><blockquote>

Instead of using the real dialog service, you could mock the dialog service. Are there advantages in using the real dialog service? Hmm, it looks like that is the convention in this test file. So then this is ok.
</blockquote></details>

I initially did mock it which then broke a bunch of tests assuming it wasn't mocked. Rather than rewrite those I followed the same convention for those tests to fix my one test.
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/text-deleted-dialog/text-deleted-dialog.component.ts` line 6 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/1505#-NCuhhueAR9ycECUbgtb:-ND4qBrSCcU0euAc5DzH:b-gtccxa) ([raw file](https://github.com/sillsdev/web-xforge/blob/e82367766dc21de95a42737ac99f584a4bcc807b/src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/text-deleted-dialog/text-deleted-dialog.component.ts#L6)):*
<details><summary><i>Previously, Nateowami (Nathaniel Paulus) wrote…</i></summary><blockquote>

@nigel-wells Actually would be better to use the `DialogService.message()` method, since `NoticeService.showMessageDialog()` is going to be removed. It's already used a couple places; you can see them for examples.
</blockquote></details>

This is done @nateowami - not sure if you want to merge this in or wait until the other PR is merged and then refactor this one.

**Review by Nateowami — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1505)* status: all files reviewed, 1 unresolved discussion (waiting on @RaymondLuong3)

___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/text-deleted-dialog/text-deleted-dialog.component.ts` line 6 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/1505#-NCuhhueAR9ycECUbgtb:-ND4spi8Bnvhwj-Yza1k:b-xrgzzc) ([raw file](https://github.com/sillsdev/web-xforge/blob/e82367766dc21de95a42737ac99f584a4bcc807b/src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/text-deleted-dialog/text-deleted-dialog.component.ts#L6)):*
<details><summary><i>Previously, nigel-wells (Nigel Wells) wrote…</i></summary><blockquote>

This is done @nateowami - not sure if you want to merge this in or wait until the other PR is merged and then refactor this one.
</blockquote></details>

@nigel-wells `DialogService.message()` is in master already. #1510 doesn't add it; it just changes a bunch of code to start using it.

**Review by RaymondLuong3 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1505)* status: all files reviewed, 2 unresolved discussions (waiting on @nigel-wells and @RaymondLuong3)

___
*[`src/SIL.XForge.Scripture/ClientApp/src/xforge-common/message-dialog/message-dialog.component.html` line 1 at r3](https://reviewable.io/reviews/sillsdev/web-xforge/1505#-ND5-KuU7kKaZPiEVs4P:-ND5-KuU7kKaZPiEVs4Q:b4o9tmy) ([raw file](https://github.com/sillsdev/web-xforge/blob/3af30f75df225fa2a1cb8dd53ab1e0c7d9bed294/src/SIL.XForge.Scripture/ClientApp/src/xforge-common/message-dialog/message-dialog.component.html#L1)):*
> ```HTML
> <h1 mat-dialog-title>{{ message }}</h1>
> ```

Sorry I lead you astray. The changes in message dialog are not needed since it will be removed.

**Review by Nateowami — COMMENTED** [review]
> Reviewed 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1505)* status: all files reviewed, 2 unresolved discussions (waiting on @nigel-wells and @RaymondLuong3)

**Review by Nateowami — DISMISSED** [review]
:lgtm:

> Reviewed 5 of 6 files at r5, 2 of 2 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1505#-:-NEd8et-4KwnNQIGgh4e:bnfp4nl)* status: all files reviewed, 2 unresolved discussions (waiting on @nigel-wells and @RaymondLuong3)

**Review by RaymondLuong3 — DISMISSED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1505)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @nigel-wells)

**Comment by Nateowami** [comment]
@nigel-wells I've dismissed the reviews from Raymond and I. If you send it to the ready to test column, then if it passes we can put the "testing complete" label on it, and it will still reflect the fact that it needs to be reviewed. We don't have to do the review and test in the usual order.

**Review by Nateowami — APPROVED** [review]
@raymondluong3 And I looked at this and approve.

> Reviewed 4 of 4 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1505#-:-NFJlsvc83o3k9sAvibA:b-mu9pt0)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @nigel-wells)

**Pull request merged**
