### PR TITLE
SF-1931 Update to use the new Serval Client

### PR DESCRIPTION
**Pull request by pmachapman**
This Pull Request updates Scripture Forge to use the new Serval.Client library, updates the MachineApiMigrator to now be the ServalMigrator, and updates the frontend to use the latest version of machine.js.

The front-facing API DTO models are kept the same to maintain API compatibility.

- - -
This change is [Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1771)

### CODE REVIEW

**Comment by pmachapman** [comment]
> @pmachapman How can I test this?

Until Serval is live, I think it will be sufficient to test with the existing in-process machine instance.

**Review by RaymondLuong3 — CHANGES_REQUESTED** [review]
Where did you find the documentation for how to use the Serval library? I would like to know where to find that for future reference.
Are we waiting for the Serval server to come online before merging this, or are we expecting that the Serval server is still a ways away and we are just getting this in early?

> Reviewed 20 of 30 files at r1, 25 of 25 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1771#-:-NUNMsty1OQ2gLPI7NxX:bm2ak9v)* status: all files reviewed, 7 unresolved discussions (waiting on @pmachapman)

___
*[`src/SIL.XForge.Scripture/Models/MachineApi.cs` line 8 at r2](https://reviewable.io/reviews/sillsdev/web-xforge/1771#-NUNFZHt0YQXBSyRyCQU:-NUNFZHt0YQXBSyRyCQV:btxylbw) ([raw file](https://github.com/sillsdev/web-xforge/blob/17a6a0b7120922823e7e1137965cc327df0db29d/src/SIL.XForge.Scripture/Models/MachineApi.cs#L8)):*
> ```Smalltalk
> public static class MachineApi
> {
>     public const string HttpClientName = "machine_api";
> ```

Why was this needed?



_Code quote:_
```Smalltalk
   public const string HttpClientName = "machine_api";
```
___
*[`src/SIL.XForge.Scripture/Services/MachineApiService.cs` line 514 at r2](https://reviewable.io/reviews/sillsdev/web-xforge/1771#-NUNJv0i2dFE6f_E5TlC:-NUNJv0i2dFE6f_E5TlD:b-upe25l) ([raw file](https://github.com/sillsdev/web-xforge/blob/17a6a0b7120922823e7e1137965cc327df0db29d/src/SIL.XForge.Scripture/Services/MachineApiService.cs#L514)):*
> ```Smalltalk
>         if (translationResultDto is null)
>         {
>             throw new DataNotFoundException("No translation engine could be retrieved");
> ```

It would be good to add that this is likely because Serval is down to this error message.



_Code quote:_
```Smalltalk
          throw new DataNotFoundException("No translation engine could be retrieved");
```
___
*[`src/SIL.XForge.Scripture/Services/MachineApiService.cs` line 667 at r2](https://reviewable.io/reviews/sillsdev/web-xforge/1771#-NUNLpzI04Fq6XYYM-xk:-NUNLpzI04Fq6XYYM-xl:b3b33iy) ([raw file](https://github.com/sillsdev/web-xforge/blob/17a6a0b7120922823e7e1137965cc327df0db29d/src/SIL.XForge.Scripture/Services/MachineApiService.cs#L667)):*
> ```Smalltalk
>         if (translationSourceList.Contains(TranslationSource.Primary))
>         {
>             translationSources |= TranslationSources.Smt;
> ```

What is the |= operator? How does it work?



_Code quote:_
```Smalltalk
  translationSources |= TranslationSources.Smt;
```
___
*[`src/SIL.XForge.Scripture/Services/MachineAuthorizationHandler.cs` line 23 at r2](https://reviewable.io/reviews/sillsdev/web-xforge/1771#-NUNNr6U82jQjMGFolEp:-NUNNr6U82jQjMGFolEq:b-t2y49x) ([raw file](https://github.com/sillsdev/web-xforge/blob/17a6a0b7120922823e7e1137965cc327df0db29d/src/SIL.XForge.Scripture/Services/MachineAuthorizationHandler.cs#L23)):*
> ```Smalltalk
>     public async Task HandleAsync(AuthorizationHandlerContext context)
>     {
>         string projectId = context.Resource switch
> ```

I find the new syntax hard to understand, mostly because it is my first time seeing this syntax. I'm going to have to train my mind for this type of switch syntax.



_Code quote:_
```Smalltalk
        string projectId = context.Resource switch
        {
            Project project => project.Id,
            Engine engine => engine.Projects.First(),
            _ => null,
        };
```
___
*[`src/SIL.XForge.Scripture/Services/MachineProjectService.cs` line 108 at r2](https://reviewable.io/reviews/sillsdev/web-xforge/1771#-NUNOpGiB5QCn3Qkgbyf:-NUNOpGiB5QCn3Qkgbyg:bweynd2) ([raw file](https://github.com/sillsdev/web-xforge/blob/17a6a0b7120922823e7e1137965cc327df0db29d/src/SIL.XForge.Scripture/Services/MachineProjectService.cs#L108)):*
> ```Smalltalk
>         {
>             // We do not need the returned project secret
>             _ = await CreateServalProjectAsync(project, cancellationToken);
> ```

I think you can remove the assignment altogether.



_Code quote:_
```Smalltalk
       _ = await CreateServalProjectAsync(project, cancellationToken);
```
___
*[`src/SIL.XForge.Scripture/Services/MachineProjectService.cs` line 592 at r2](https://reviewable.io/reviews/sillsdev/web-xforge/1771#-NUNRok_A1f51uokbpXh:-NUNRok_A1f51uokbpXi:bxe3wik) ([raw file](https://github.com/sillsdev/web-xforge/blob/17a6a0b7120922823e7e1137965cc327df0db29d/src/SIL.XForge.Scripture/Services/MachineProjectService.cs#L592)):*
> ```Smalltalk
>                 string checksum = StringUtils.ComputeMd5Hash(textFileData);
>                 ServalCorpusFile? previousCorpusFile = oldCorpusFiles?.FirstOrDefault(c => c.TextId == textId);
>                 if (previousCorpusFile is null || previousCorpusFile.FileChecksum != checksum)
> ```

Is it that we do not need to delete the old corpus files because uploading them creates an updated version on the server?



_Code quote:_
```Smalltalk
                ServalCorpusFile? previousCorpusFile = oldCorpusFiles?.FirstOrDefault(c => c.TextId == textId);
                if (previousCorpusFile is null || previousCorpusFile.FileChecksum != checksum)
```

**Review by pmachapman — COMMENTED** [review]
I think we should merge this before Serval comes online. There will likely be further PRs modifying the Serval implementation in SF to match future API updates to Serval.

For documentation, the source code for Serval and Machine is the documentation I have worked from, as well as Serval's Swagger. I have created a document in the Developer Documentation folder called "Running Serval Locally", which goes through all of the steps to setup Serval locally, if you want to look at this yourself.

As of right now, the latest version of Serval has API changes that are incompatible with the version of Serval.Client that is published, so running Serval locally with SF does not work.

> Dismissed @github-code-scanning[bot] from a discussion.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1771#-:-NUNjReBCAoefXuM9tKw:bxr67h5)* status: all files reviewed, 6 unresolved discussions (waiting on @RaymondLuong3)

___
*[`src/SIL.XForge.Scripture/Models/MachineApi.cs` line 8 at r2](https://reviewable.io/reviews/sillsdev/web-xforge/1771#-NUNFZHt0YQXBSyRyCQU:-NUNmkKaBEb77vtVni_O:b-1plswz) ([raw file](https://github.com/sillsdev/web-xforge/blob/17a6a0b7120922823e7e1137965cc327df0db29d/src/SIL.XForge.Scripture/Models/MachineApi.cs#L8)):*
<details><summary><i>Previously, RaymondLuong3 (Raymond Luong) wrote…</i></summary><blockquote>

Why was this needed?
</blockquote></details>

The named HTTP Client is so that I can use Polly just for HTTP Client requests to Serval. Polly is the library that adds resiliency to our HTTP requests - this is done in MachineServiceCollectionExtensions.cs, lines 77-95.

If we wanted to expand use of Polly to Paratext Registry calls (for example), we would have a different named HTTP Client for that, with its own retry and backoff configuration.
___
*[`src/SIL.XForge.Scripture/Services/MachineApiService.cs` line 514 at r2](https://reviewable.io/reviews/sillsdev/web-xforge/1771#-NUNJv0i2dFE6f_E5TlC:-NUNqq21-eSAP7gB_4-t:bb63fhj) ([raw file](https://github.com/sillsdev/web-xforge/blob/17a6a0b7120922823e7e1137965cc327df0db29d/src/SIL.XForge.Scripture/Services/MachineApiService.cs#L514)):*
<details><summary><i>Previously, RaymondLuong3 (Raymond Luong) wrote…</i></summary><blockquote>

It would be good to add that this is likely because Serval is down to this error message.
</blockquote></details>

I have added additional information to this error string, depending on the feature flag configuration, to hopefully make debugging easier.
___
*[`src/SIL.XForge.Scripture/Services/MachineApiService.cs` line 667 at r2](https://reviewable.io/reviews/sillsdev/web-xforge/1771#-NUNLpzI04Fq6XYYM-xk:-NUNr6kP3XgrspilTYIy:b40wm2w) ([raw file](https://github.com/sillsdev/web-xforge/blob/17a6a0b7120922823e7e1137965cc327df0db29d/src/SIL.XForge.Scripture/Services/MachineApiService.cs#L667)):*
<details><summary><i>Previously, RaymondLuong3 (Raymond Luong) wrote…</i></summary><blockquote>

What is the |= operator? How does it work?
</blockquote></details>

It is a bitwise OR operator.

As the `TranslationSources` enum has the `Flags` attribute, its values step in 1, 2, 4, etc. This means I can add the bit value together with an OR operator to get an enum value that represents multiple flags in one field. I use this to flatten the List<> of a List<> to just a List of the enum (which is what the frontend expects in the DTO).
___
*[`src/SIL.XForge.Scripture/Services/MachineAuthorizationHandler.cs` line 23 at r2](https://reviewable.io/reviews/sillsdev/web-xforge/1771#-NUNNr6U82jQjMGFolEp:-NUNsz1A5DOOq1s9ZHb9:b-ukn766) ([raw file](https://github.com/sillsdev/web-xforge/blob/17a6a0b7120922823e7e1137965cc327df0db29d/src/SIL.XForge.Scripture/Services/MachineAuthorizationHandler.cs#L23)):*
<details><summary><i>Previously, RaymondLuong3 (Raymond Luong) wrote…</i></summary><blockquote>

I find the new syntax hard to understand, mostly because it is my first time seeing this syntax. I'm going to have to train my mind for this type of switch syntax.
</blockquote></details>

Yes, it does take a little while to get used to. This statement is the equivalent of:
```cs
if (context.Resource is Project project)
{
	projectId = project.Id;
}
else if (context.Resource is Engine engine)
{
	projectId = engine.Projects.First();
}
else
{
	projectId = null;
}
```
___
*[`src/SIL.XForge.Scripture/Services/MachineProjectService.cs` line 601 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/1771#-NRdn4rfVECXmlsY-DCv-r1-601:-NUNu2zD7sf5fDY4VJBG:b-896fix) ([raw file](https://github.com/sillsdev/web-xforge/blob/a5e0fb5642ff5ed2a780fc6c4734a4956b66e451/src/SIL.XForge.Scripture/Services/MachineProjectService.cs#L601)):*
<details><summary><i>Previously, github-code-scanning[bot] wrote…</i></summary><blockquote>

## Missing Dispose call on local IDisposable

Disposable 'MemoryStream' is created but not disposed.

[Show more details](https://github.com/sillsdev/web-xforge/security/code-scanning/492)
</blockquote></details>

Done.
___
*[`src/SIL.XForge.Scripture/Services/MachineProjectService.cs` line 108 at r2](https://reviewable.io/reviews/sillsdev/web-xforge/1771#-NUNOpGiB5QCn3Qkgbyf:-NUNtOQZAcbGckMaWmJS:b-170cz6) ([raw file](https://github.com/sillsdev/web-xforge/blob/17a6a0b7120922823e7e1137965cc327df0db29d/src/SIL.XForge.Scripture/Services/MachineProjectService.cs#L108)):*
<details><summary><i>Previously, RaymondLuong3 (Raymond Luong) wrote…</i></summary><blockquote>

I think you can remove the assignment altogether.
</blockquote></details>

Correct - I have removed these. I normally use these as an acknowledgement of "Yes, I know it returns a value, but I do not need the return value." (as opposed to "I forgot to use the return value."), but I think the comment above this line (and the others) describes as much.
___
*[`src/SIL.XForge.Scripture/Services/MachineProjectService.cs` line 592 at r2](https://reviewable.io/reviews/sillsdev/web-xforge/1771#-NUNRok_A1f51uokbpXh:-NUNuXqdD_2v6dqxdg_W:bw29uff) ([raw file](https://github.com/sillsdev/web-xforge/blob/17a6a0b7120922823e7e1137965cc327df0db29d/src/SIL.XForge.Scripture/Services/MachineProjectService.cs#L592)):*
<details><summary><i>Previously, RaymondLuong3 (Raymond Luong) wrote…</i></summary><blockquote>

Is it that we do not need to delete the old corpus files because uploading them creates an updated version on the server?
</blockquote></details>

That comment is out of date, so I have updated it. Thank you for spotting it!

**Review by pmachapman — COMMENTED** [review]
There is now a document in the Developer Documentation folder called "Using Serval with Scripture Forge", which has details on how to use Serval QA with Scripture Forge.

> Dismissed @github-code-scanning[bot] from 3 discussions.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1771#-:-NVWXQAvEyaoGzXbv3VW:b-ivenp8)* status: 33 of 64 files reviewed, 6 unresolved discussions (waiting on @github-code-scanning[bot] and @RaymondLuong3)

**Review by RaymondLuong3 — CHANGES_REQUESTED** [review]
Thanks, the document was helpful to connect to the QAServal. As I was testing it, I found that I wasn't getting many suggestions, but that is probably because I hadn't had many segments trained yet. I have some comments, but mostly syntax related.

> Reviewed 7 of 12 files at r3, 20 of 22 files at r4, 4 of 4 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1771#-:-NVfaQ1uEPM5Trf8clzW:b-ou3qtc)* status: all files reviewed, 9 unresolved discussions (waiting on @pmachapman)

___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/core/translation-engine.service.ts` line 156 at r5](https://reviewable.io/reviews/sillsdev/web-xforge/1771#-NVfKkgT9uoVqq6Zb8z7:-NVfKkgT9uoVqq6Zb8z8:b-4o65cd) ([raw file](https://github.com/sillsdev/web-xforge/blob/594f5ec694f0aff85fec1f7aee544992ea982daf/src/SIL.XForge.Scripture/ClientApp/src/app/core/translation-engine.service.ts#L156)):*
> ```XML
>     }
> 
>     const factory = this.createInteractiveTranslatorFactory(projectRef);
> ```

Add a type here and below.
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/machine-api/remote-translation-engine.ts` line 187 at r5](https://reviewable.io/reviews/sillsdev/web-xforge/1771#-NVfMxWS1YBCv__s9qfc:-NVfMxWS1YBCv__s9qfd:b3s3fw0) ([raw file](https://github.com/sillsdev/web-xforge/blob/594f5ec694f0aff85fec1f7aee544992ea982daf/src/SIL.XForge.Scripture/ClientApp/src/app/machine-api/remote-translation-engine.ts#L187)):*
> ```XML
>   }
> 
>   private *createTranslationSources(sources: TranslationSource[][]): Iterable<TranslationSources> {
> ```

So that's how you use yield in TS. Nice.
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/machine-api/remote-translation-engine.spec.ts` line 230 at r5](https://reviewable.io/reviews/sillsdev/web-xforge/1771#-NVfRXM--Ed7IdwteTcN:-NVfRXM--Ed7IdwteTcO:bg3oinu) ([raw file](https://github.com/sillsdev/web-xforge/blob/594f5ec694f0aff85fec1f7aee544992ea982daf/src/SIL.XForge.Scripture/ClientApp/src/app/machine-api/remote-translation-engine.spec.ts#L230)):*
> ```XML
>           confidences: confidences,
>           phrases: [
>             { sourceSegmentStart: 0, sourceSegmentEnd: 1, targetSegmentCut: 2 },
> ```

What is a targetSegmentCut? And why is it 1 more than sourceSegmentEnd?
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.ts` line 811 at r5](https://reviewable.io/reviews/sillsdev/web-xforge/1771#-NVfRm2y8-58nBKX0EaY:-NVfRm2y8-58nBKX0EaZ:b-fmm3et) ([raw file](https://github.com/sillsdev/web-xforge/blob/594f5ec694f0aff85fec1f7aee544992ea982daf/src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.ts#L811)):*
> ```XML
> 
>     const words = wordIndex === -1 ? suggestion.words : suggestion.words.slice(0, wordIndex + 1);
>     let insertText = this.detokenizer.detokenize(words);
> ```

Add a type here.
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.ts` line 1226 at r5](https://reviewable.io/reviews/sillsdev/web-xforge/1771#-NVfRulp9-4LzVtoVLRh:-NVfRulp9-4LzVtoVLRi:b-l5h6pr) ([raw file](https://github.com/sillsdev/web-xforge/blob/594f5ec694f0aff85fec1f7aee544992ea982daf/src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.ts#L1226)):*
> ```XML
> 
>     const start = performance.now();
>     const translator = await this.interactiveTranslatorFactory?.create(sourceSegment);
> ```

Add types for these
___
*[`src/SIL.XForge.Scripture/Models/MachineApi.cs` line 8 at r2](https://reviewable.io/reviews/sillsdev/web-xforge/1771#-NUNFZHt0YQXBSyRyCQU:-NVfVw8U7dBflJxv3QZM:b-qqkl3l) ([raw file](https://github.com/sillsdev/web-xforge/blob/17a6a0b7120922823e7e1137965cc327df0db29d/src/SIL.XForge.Scripture/Models/MachineApi.cs#L8)):*
<details><summary><i>Previously, pmachapman (Peter Chapman) wrote…</i></summary><blockquote>

The named HTTP Client is so that I can use Polly just for HTTP Client requests to Serval. Polly is the library that adds resiliency to our HTTP requests - this is done in MachineServiceCollectionExtensions.cs, lines 77-95.

If we wanted to expand use of Polly to Paratext Registry calls (for example), we would have a different named HTTP Client for that, with its own retry and backoff configuration.
</blockquote></details>

Ok, that is good to know.
___
*[`src/SIL.XForge.Scripture/Models/MachineApiV2.cs` line 13 at r5](https://reviewable.io/reviews/sillsdev/web-xforge/1771#-NVfWUEq4SCxM0bp3uzW:-NVfWUEq4SCxM0bp3uzX:b-e2rkry) ([raw file](https://github.com/sillsdev/web-xforge/blob/594f5ec694f0aff85fec1f7aee544992ea982daf/src/SIL.XForge.Scripture/Models/MachineApiV2.cs#L13)):*
> ```Smalltalk
>     public const string Namespace = "machine-api/v2";
>     public const string StartBuild = "translation/builds";
>     public const string GetBuild = "translation/builds/{locatorType}:{sfProjectId}.{buildId?}";
> ```

Is the question mark here just to make it easier to see that the build ID can be null?
___
*[`src/SIL.XForge.Scripture/Services/MachineApiService.cs` line 667 at r2](https://reviewable.io/reviews/sillsdev/web-xforge/1771#-NUNLpzI04Fq6XYYM-xk:-NVfYIizEGzt4EmwvEnq:bfm20gt) ([raw file](https://github.com/sillsdev/web-xforge/blob/17a6a0b7120922823e7e1137965cc327df0db29d/src/SIL.XForge.Scripture/Services/MachineApiService.cs#L667)):*
<details><summary><i>Previously, pmachapman (Peter Chapman) wrote…</i></summary><blockquote>

It is a bitwise OR operator.

As the `TranslationSources` enum has the `Flags` attribute, its values step in 1, 2, 4, etc. This means I can add the bit value together with an OR operator to get an enum value that represents multiple flags in one field. I use this to flatten the List<> of a List<> to just a List of the enum (which is what the frontend expects in the DTO).
</blockquote></details>

Ok, I see. I haven't seen bitwise OR since university days
___
*[`src/SIL.XForge.Scripture/Services/MachineProjectService.cs` line 108 at r2](https://reviewable.io/reviews/sillsdev/web-xforge/1771#-NUNOpGiB5QCn3Qkgbyf:-NVfZ1fm6I6CZ3iNAPep:b-x3zbmu) ([raw file](https://github.com/sillsdev/web-xforge/blob/17a6a0b7120922823e7e1137965cc327df0db29d/src/SIL.XForge.Scripture/Services/MachineProjectService.cs#L108)):*
<details><summary><i>Previously, pmachapman (Peter Chapman) wrote…</i></summary><blockquote>

Correct - I have removed these. I normally use these as an acknowledgement of "Yes, I know it returns a value, but I do not need the return value." (as opposed to "I forgot to use the return value."), but I think the comment above this line (and the others) describes as much.
</blockquote></details>

That is a good point. I have forgotten to use return values before, specifically when getting subsets from a list. But the comments seems to be a good alternative.
___
*[`src/SIL.XForge.Scripture/Services/MachineProjectService.cs` line 481 at r5](https://reviewable.io/reviews/sillsdev/web-xforge/1771#-NVfZo032jw8-8nbCEbe:-NVfZo032jw8-8nbCEbf:b1mf9hl) ([raw file](https://github.com/sillsdev/web-xforge/blob/594f5ec694f0aff85fec1f7aee544992ea982daf/src/SIL.XForge.Scripture/Services/MachineProjectService.cs#L481)):*
> ```Smalltalk
>             // We pad the verse number so the string based key comparisons in Machine will be accurate
>             string key = segment.SegmentRef is TextSegmentRef textSegmentRef
>                 ? string.Join('_', textSegmentRef.Keys.Select(k => int.TryParse(k, out int _) ? k.PadLeft(3, '0') : k))
> ```

What would happen if the parsing the integer fails? What would that mean?

**Review by pmachapman — COMMENTED** [review]
If you aren't getting many suggestions, reducing the suggestion confidence to 0 can help, although you will get some rather unusual suggestions.

> Reviewed 1 of 4 files at r5.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1771#-:-NVfpsje5LMs59PMJfs7:b-usyozh)* status: 62 of 64 files reviewed, 6 unresolved discussions (waiting on @RaymondLuong3)

___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/core/translation-engine.service.ts` line 156 at r5](https://reviewable.io/reviews/sillsdev/web-xforge/1771#-NVfKkgT9uoVqq6Zb8z7:-NVfqvGF7SxDZAy7Z9TL:b-8c4czd) ([raw file](https://github.com/sillsdev/web-xforge/blob/594f5ec694f0aff85fec1f7aee544992ea982daf/src/SIL.XForge.Scripture/ClientApp/src/app/core/translation-engine.service.ts#L156)):*
<details><summary><i>Previously, RaymondLuong3 (Raymond Luong) wrote…</i></summary><blockquote>

Add a type here and below.
</blockquote></details>

Thanks - done.
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/machine-api/remote-translation-engine.spec.ts` line 230 at r5](https://reviewable.io/reviews/sillsdev/web-xforge/1771#-NVfRXM--Ed7IdwteTcN:-NVftKK51mP0fgyuYD-j:bdaosex) ([raw file](https://github.com/sillsdev/web-xforge/blob/594f5ec694f0aff85fec1f7aee544992ea982daf/src/SIL.XForge.Scripture/ClientApp/src/app/machine-api/remote-translation-engine.spec.ts#L230)):*
<details><summary><i>Previously, RaymondLuong3 (Raymond Luong) wrote…</i></summary><blockquote>

What is a targetSegmentCut? And why is it 1 more than sourceSegmentEnd?
</blockquote></details>

The target segment cut is where the target segments will be cut off to have a target phrase matching the source phrase.

The +1 is just so any mis-mapping of values will show up in my tests.
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.ts` line 811 at r5](https://reviewable.io/reviews/sillsdev/web-xforge/1771#-NVfRm2y8-58nBKX0EaY:-NVfwTOn9Hm5cz-4DFnz:b-ao4pv0) ([raw file](https://github.com/sillsdev/web-xforge/blob/594f5ec694f0aff85fec1f7aee544992ea982daf/src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.ts#L811)):*
<details><summary><i>Previously, RaymondLuong3 (Raymond Luong) wrote…</i></summary><blockquote>

Add a type here.
</blockquote></details>

Fixed - thanks!
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.ts` line 1226 at r5](https://reviewable.io/reviews/sillsdev/web-xforge/1771#-NVfRulp9-4LzVtoVLRh:-NVfxouK4BZfvqPjG1X0:b-ao4pv0) ([raw file](https://github.com/sillsdev/web-xforge/blob/594f5ec694f0aff85fec1f7aee544992ea982daf/src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.ts#L1226)):*
<details><summary><i>Previously, RaymondLuong3 (Raymond Luong) wrote…</i></summary><blockquote>

Add types for these
</blockquote></details>

Fixed - thanks!
___
*[`src/SIL.XForge.Scripture/Models/MachineApiV2.cs` line 13 at r5](https://reviewable.io/reviews/sillsdev/web-xforge/1771#-NVfWUEq4SCxM0bp3uzW:-NVfyePT0K9YDqYc6vVS:b4ftdvq) ([raw file](https://github.com/sillsdev/web-xforge/blob/594f5ec694f0aff85fec1f7aee544992ea982daf/src/SIL.XForge.Scripture/Models/MachineApiV2.cs#L13)):*
The question makes it optional in the URL route. Also, because a "." is used as a separator, this means that the following paths are valid:

> /machine-api/v2/builds/engine:123
> /machine-api/v2/builds/id:123.456
___
*[`src/SIL.XForge.Scripture/Services/MachineProjectService.cs` line 481 at r5](https://reviewable.io/reviews/sillsdev/web-xforge/1771#-NVfZo032jw8-8nbCEbe:-NVg0fHz3axf4JReidYm:b-gv63nd) ([raw file](https://github.com/sillsdev/web-xforge/blob/594f5ec694f0aff85fec1f7aee544992ea982daf/src/SIL.XForge.Scripture/Services/MachineProjectService.cs#L481)):*
<details><summary><i>Previously, RaymondLuong3 (Raymond Luong) wrote…</i></summary><blockquote>

What would happen if the parsing the integer fails? What would that mean?
</blockquote></details>

It means that the key will be used as-is (the `: k`). This usually happens for Biblical Terms, which have Greek or Hebrew words as the key, or unusual verse numbers like "12a" or "12-13".

Normally the key will be a standard verse number, so it is only padded to three digits.

**Review by RaymondLuong3 — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1771)* status: all files reviewed, 1 unresolved discussion (waiting on @pmachapman)

**Review by pmachapman — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1771)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @pmachapman)

___
*[`src/SIL.XForge.Scripture/Services/MachineProjectService.cs` line 481 at r5](https://reviewable.io/reviews/sillsdev/web-xforge/1771#-NVfZo032jw8-8nbCEbe:-NVzlWr_-NggFiotOLgQ:b-896fix) ([raw file](https://github.com/sillsdev/web-xforge/blob/594f5ec694f0aff85fec1f7aee544992ea982daf/src/SIL.XForge.Scripture/Services/MachineProjectService.cs#L481)):*
<details><summary><i>Previously, RaymondLuong3 (Raymond Luong) wrote…</i></summary><blockquote>

Let's add a comment here so we can that is more clear.
</blockquote></details>

Done.

**Review by pmachapman — COMMENTED** [review]
To release this, we can deploy and test as-is, which will use the in-process machine. Once it is on QA, we will be able to use Serval, first by running the migrator, then by enabling the Serval QA keys and the Serval feature flag (this is all documented in the document in the Developer Documentation folder).

> Reviewed 1 of 3 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1771#-:-NVzlqW112Y4T5_wVFOf:b-3whk28)* status: 62 of 64 files reviewed, all discussions resolved (waiting on @RaymondLuong3)

**Pull request merged**
