### PR TITLE
SF-2039 Convert drawer to Material

### PR DESCRIPTION
**Pull request by Nateowami**
The header is now no longer covered by the drawer when it's open. I don't have a strong opinion on whether this is better or not, but it doesn't seem that there's a good way in Material to have it cover the header.

Before | After
-------|------
 | 

- - -
This change is [Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1868)

### CODE REVIEW

**Review by RaymondLuong3 — CHANGES_REQUESTED** [review]
I like the nice animation when you increase the size of the window and the draw opens. Also, I am amazed you didn't need to update the tests! It's nice when tests are written without specific UI library references.

> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1868#-:-NWJrswbEtVupzCX96Ha:bus1ldw)* status: all files reviewed, 3 unresolved discussions (waiting on @Nateowami)

___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/app.component.html` line 107 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/1868#-NWJoOv53NxWLz2geYJI:-NWJoOv53NxWLz2geYJJ:b2cs11b) ([raw file](https://github.com/sillsdev/web-xforge/blob/acb61cd00da26feab83dc99f07819d97fe71ed65/src/SIL.XForge.Scripture/ClientApp/src/app/app.component.html#L107)):*
> ```HTML
>       (closed)="drawerCollapsed()"
>     >
>       <mdc-select
> ```

While you are in the app component, why not update this to material also? Or is this getting a redesign?
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/app.component.html` line 133 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/1868#-NWJp39cBb5dy3DFQ39g:-NWJp39cBb5dy3DFQ39h:b-ibmia) ([raw file](https://github.com/sillsdev/web-xforge/blob/acb61cd00da26feab83dc99f07819d97fe71ed65/src/SIL.XForge.Scripture/ClientApp/src/app/app.component.html#L133)):*
> ```HTML
>           (click)="translateVisible = !translateVisible"
>         >
>           <mdc-icon svgIcon="translate" class="translate-icon"></mdc-icon>
> ```

This can also be changed to mat-icon
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/app.component.scss` line 233 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/1868#-NWJq8iE0K1UkcDf3Qmt:-NWJq8iE0K1UkcDf3Qmu:b-1qn7z6) ([raw file](https://github.com/sillsdev/web-xforge/blob/acb61cd00da26feab83dc99f07819d97fe71ed65/src/SIL.XForge.Scripture/ClientApp/src/app/app.component.scss#L233)):*
> ```SCSS
> mdc-drawer-content {
>   display: flex;
>   flex-direction: column;
> ```

This can be removed.

**Review by Nateowami — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1868)* status: 2 of 3 files reviewed, 3 unresolved discussions (waiting on @RaymondLuong3)

___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/app.component.html` line 107 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/1868#-NWJoOv53NxWLz2geYJI:-NWJwVgg3yCHZuvphzH7:b-m9p4he) ([raw file](https://github.com/sillsdev/web-xforge/blob/acb61cd00da26feab83dc99f07819d97fe71ed65/src/SIL.XForge.Scripture/ClientApp/src/app/app.component.html#L107)):*
<details><summary><i>Previously, RaymondLuong3 (Raymond Luong) wrote…</i></summary><blockquote>

While you are in the app component, why not update this to material also? Or is this getting a redesign?
</blockquote></details>

There are some edge cases with this select that were slowly worked around over time (specifically they have to do with how long project names are rendered). Also, we've been discussing whether this should be done away with entirely, if we can find a better way of switching projects. So I didn't want to bite off that task if I could avoid it, since it's pretty far from trivial.
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/app.component.html` line 133 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/1868#-NWJp39cBb5dy3DFQ39g:-NWJwq946vjY0yARPkAr:bxtckfq) ([raw file](https://github.com/sillsdev/web-xforge/blob/acb61cd00da26feab83dc99f07819d97fe71ed65/src/SIL.XForge.Scripture/ClientApp/src/app/app.component.html#L133)):*
<details><summary><i>Previously, RaymondLuong3 (Raymond Luong) wrote…</i></summary><blockquote>

This can also be changed to mat-icon
</blockquote></details>

The entire sidebar is in the process of being replaced. See #1825. Also, it's not just a matter of changing `mdc-icon` to `mat-icon`, since this is a custom icon that has to get registered in order to be used. So once that sidebar is replaced, all of this will be irrelevant anyway. My new sidebar design doesn't even use this icon, though that could change.

(This PR is about replacing the drawer, which contains the sidebar).
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/app.component.scss` line 233 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/1868#-NWJq8iE0K1UkcDf3Qmt:-NWJxjHt8TeVg16CO56j:bhe2cxs) ([raw file](https://github.com/sillsdev/web-xforge/blob/acb61cd00da26feab83dc99f07819d97fe71ed65/src/SIL.XForge.Scripture/ClientApp/src/app/app.component.scss#L233)):*
<details><summary><i>Previously, RaymondLuong3 (Raymond Luong) wrote…</i></summary><blockquote>

This can be removed.
</blockquote></details>

Good catch. Not sure how I missed it. Done.

**Review by RaymondLuong3 — APPROVED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1868)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @Nateowami)

___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/app.component.html` line 107 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/1868#-NWJoOv53NxWLz2geYJI:-NWK69EA9aAm5BDgJ2Bm:bathob7) ([raw file](https://github.com/sillsdev/web-xforge/blob/acb61cd00da26feab83dc99f07819d97fe71ed65/src/SIL.XForge.Scripture/ClientApp/src/app/app.component.html#L107)):*
<details><summary><i>Previously, Nateowami (Nathaniel Paulus) wrote…</i></summary><blockquote>

There are some edge cases with this select that were slowly worked around over time (specifically they have to do with how long project names are rendered). Also, we've been discussing whether this should be done away with entirely, if we can find a better way of switching projects. So I didn't want to bite off that task if I could avoid it, since it's pretty far from trivial.
</blockquote></details>

Ok, we should start to think about that because it will be one of the last MDC components in our app and we won't be able to update to angular 15

**Review by Nateowami — COMMENTED** [review]
@RaymondLuong3 I've made some changes to fix support for dynamically changing between RTL and LTR.

This still isn't ready for merging, because it clashes with the current question list drawer. Once Colin's PR to convert that to Material is complete, this should be ready to test and merge.

> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1868#-:-NdhH4TC-_BXxaSE6Prc:b-e8pldt)* status: 0 of 4 files reviewed, all discussions resolved (waiting on @RaymondLuong3)

**Review by Nateowami — COMMENTED** [review]
@RaymondLuong3 Now that the question list conversion to Material is complete, this PR is ready for re-review. I've made a very small change.

> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1868#-:-NdpYinEAM-f8EVwzCB7:b-i4vpgy)* status: 0 of 4 files reviewed, all discussions resolved (waiting on @RaymondLuong3)

___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/app.component.html` line 105 at r3](https://reviewable.io/reviews/sillsdev/web-xforge/1868#-NdpYX6g4INIshY8-4K8:-NdpYX6g4INIshY8-4K9:b-jv4t67) ([raw file](https://github.com/sillsdev/web-xforge/blob/221554b887650054d4b9ace4e8b659acb7b0e1e3/src/SIL.XForge.Scripture/ClientApp/src/app/app.component.html#L105)):*
> ```HTML
>     class="top-app-bar-adjust"
>     [class.top-app-bar-adjust-double]="hasUpdate"
>     [dir]="i18n.direction"
> ```

This was needed in order to make the drawer understand when the UI direction changed and immediately adjust. Without it, you could reload the page and it would detect the correct direction, but the UI would break when switching locales without a page reload.

**Review by RaymondLuong3 — APPROVED** [review]
Thanks. I approve.

> Reviewed 4 of 4 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1868#-:-NdppA6WCoEtyXtxK7-a:bp8sx5k)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @Nateowami)

**Pull request merged**
