### PR TITLE
Memory and Speed Optimizations to the Sync Process

### PR DESCRIPTION
**Pull request by pmachapman**
This Pull Request improves memory use and project sync speed for projects with very large numbers of comments, and many books (i.e. complete canons).

The following changes are included:

 * Changed a regular expression used commonly in sync to compiled (reduced memory allocations)
 * Updated the Realtime Server and sync process to retrieve multiple documents at once (lowers socket use and improves sync speed)
 * Updated use of the Paratext `CommentManager` to:
    - Remove the `CommentManager` from the MRU cache when the sync is completed (frees memory after sync completion)
    - Removed the `ParallelDeserializer` for the `CommentList` data type (considerable reduction to sync memory use with the penalty of a slightly slower [in terms of milliseconds] sync)
 * Suppressed the CodeQL warnings for "Unexpected any. Specify a different type" in `index.ts`

- - -
This change is [Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1716)

### CODE REVIEW

**Review by marksvc — CHANGES_REQUESTED** [review]
Thanks for your work on speeding things up!

> Reviewed 1 of 13 files at r2, 11 of 11 files at r3, 3 of 3 files at r4, 3 of 3 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1716#-:-NP-PpR5-G0eofI9xpgT:bbpw0hm)* status: all files reviewed, 9 unresolved discussions (waiting on @pmachapman)

___
*[`src/SIL.XForge/Realtime/Connection.cs` line 281 at r3](https://reviewable.io/reviews/sillsdev/web-xforge/1716#-NOzvADP5OcstkEc8o1O:-NOzvADP5OcstkEc8o1P:b-bm4spp) ([raw file](https://github.com/sillsdev/web-xforge/blob/c83640a8a78731e6436a99e6e64151f2c757579f/src/SIL.XForge/Realtime/Connection.cs#L281)):*
> ```Smalltalk
>             {
>                 string otTypeName = docConfig.OTTypeName;
>                 return new Document<T>(this, otTypeName, docConfig.CollectionName, id, null);
> ```

What's the reason to specify the optional argument as null rather than omit it here?



_Code quote:_
```Smalltalk
id, null);
```
___
*[`src/SIL.XForge/Realtime/MemoryConnection.cs` line 113 at r3](https://reviewable.io/reviews/sillsdev/web-xforge/1716#-NOzVo2YCkZipRORzo8f:-NOzVo2YCkZipRORzo8g:b-bsleeq) ([raw file](https://github.com/sillsdev/web-xforge/blob/c83640a8a78731e6436a99e6e64151f2c757579f/src/SIL.XForge/Realtime/MemoryConnection.cs#L113)):*
> ```Smalltalk
>         }
> 
>         return await Task.FromResult(docs);
> ```

Why are you using `await` and `Task.FromResult` here instead of just `return docs`?



_Code quote:_
```Smalltalk
 Task.FromResult
```
___
*[`src/SIL.XForge/Realtime/Snapshot.cs` line 5 at r3](https://reviewable.io/reviews/sillsdev/web-xforge/1716#-NOvJVdd1kg4T8duU6KV:-NOvJVdd1kg4T8duU6KW:bbii644) ([raw file](https://github.com/sillsdev/web-xforge/blob/c83640a8a78731e6436a99e6e64151f2c757579f/src/SIL.XForge/Realtime/Snapshot.cs#L5)):*
> ```Smalltalk
> public class Snapshot<T>
> {
>     public string Id { get; set; }
> ```

I'll probably be confused the next time I look at this. Can you add a comment that gives a hint what the Id is, such as whether it's the Id of the document that the snapshot pertains to, or whether it's an Id (uniquely) for the snapshot itself?
___
*[`src/SIL.XForge.Scripture/Services/ParatextService.cs` line 1166 at r4](https://reviewable.io/reviews/sillsdev/web-xforge/1716#-NP-GAq5BS8ABd60l-wT:-NP-GAq5BS8ABd60l-wU:b99qohd) ([raw file](https://github.com/sillsdev/web-xforge/blob/de54b0a02a478cdcb8663a64884c9c8f6aa22015/src/SIL.XForge.Scripture/Services/ParatextService.cs#L1166)):*
> ```Smalltalk
>         // CommentThread.VerseRef calculates the reallocated location, however in Paratext a note can only be
>         // reallocated within the chapter, so for our query, we only need the first location
>         var threads = manager.FindThreads(commentThread => commentThread.Comments[0].VerseRef.BookNum == bookNum, true);
> ```

What is the significance of looking at the Comments[0].VerseRef.BookNum (here and later in the diff) instead of the thread VerseRef.BookNum? Are we going faster by doing this?
___
*[`src/SIL.XForge.Scripture/Services/ParatextSyncRunner.cs` line 1020 at r2](https://reviewable.io/reviews/sillsdev/web-xforge/1716#-NOz_apxCYxtgVeFFonS:-NOz_apxCYxtgVeFFonT:b-e209fz) ([raw file](https://github.com/sillsdev/web-xforge/blob/db2498f9134794d29e382198709794a04d4619a9/src/SIL.XForge.Scripture/Services/ParatextSyncRunner.cs#L1020)):*
> ```Smalltalk
>     /// Fetches all text docs from the database for a book.
>     /// </summary>
>     internal async Task<SortedList<int, IDocument<TextData>>> FetchTextDocsAsync(TextInfo text)
> ```

Maybe this should be named something else now, like.. DocsForBook or something.
And the method comment looks inaccurate now.
___
*[`test/SIL.XForge.Scripture.Tests/Services/ParatextSyncRunnerTests.cs` line 2339 at r3](https://reviewable.io/reviews/sillsdev/web-xforge/1716#-NP-1CMVA_qB0EjIiSfS:-NP-1CMVA_qB0EjIiSfT:b-4w05c2) ([raw file](https://github.com/sillsdev/web-xforge/blob/c83640a8a78731e6436a99e6e64151f2c757579f/test/SIL.XForge.Scripture.Tests/Services/ParatextSyncRunnerTests.cs#L2339)):*
> ```Smalltalk
>         /// Gets the connection to be used with <see cref="SubstituteRealtimeService"/>.
>         /// </summary>
>         public IConnection SubstituteConnection { get; }
> ```

What's your thinking here; this is just to make it very clear that it is a substitute?



_Code quote:_
```Smalltalk
       public IConnection SubstituteConnection { get; }
```

**Review by pmachapman — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1716)* status: all files reviewed, 9 unresolved discussions (waiting on @github-code-scanning[bot] and @marksvc)

___
*[`src/RealtimeServer/common/index.ts` line 6 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/1716#-NOfznPpHwUjO9cjhsMh-r1-6:-NPDvDfw4ABgG3cv7AL_:b-896fix) ([raw file](https://github.com/sillsdev/web-xforge/blob/3a6378e36025453a05396375460ea442b06cf5b0/src/RealtimeServer/common/index.ts#L6)):*
<details><summary><i>Previously, github-code-scanning[bot] wrote…</i></summary><blockquote>

## Unused variable, import, function or class

Unused import Query.

[Show more details](https://github.com/sillsdev/web-xforge/security/code-scanning/475)
</blockquote></details>

Done.
___
*[`src/SIL.XForge/Realtime/Connection.cs` line 281 at r3](https://reviewable.io/reviews/sillsdev/web-xforge/1716#-NOzvADP5OcstkEc8o1O:-NPDvOS0DLZ1E_Ty1fND:b3ox3v5) ([raw file](https://github.com/sillsdev/web-xforge/blob/c83640a8a78731e6436a99e6e64151f2c757579f/src/SIL.XForge/Realtime/Connection.cs#L281)):*
<details><summary><i>Previously, marksvc wrote…</i></summary><blockquote>

What's the reason to specify the optional argument as null rather than omit it here?
</blockquote></details>

`snapshot` is not an optional argument - would you like me to make it one?



_Code quote:_
```Smalltalk
return new Document<T>(this, otTypeName, docConfig.CollectionName, id, null);
```
___
*[`src/SIL.XForge/Realtime/MemoryConnection.cs` line 111 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/1716#-NOfznPpHwUjO9cjhsMp-r1-111:-NPDwIUI2AlafxIea1Tm:b-896fix) ([raw file](https://github.com/sillsdev/web-xforge/blob/3a6378e36025453a05396375460ea442b06cf5b0/src/SIL.XForge/Realtime/MemoryConnection.cs#L111)):*
<details><summary><i>Previously, github-code-scanning[bot] wrote…</i></summary><blockquote>

## Missed opportunity to use Select

This foreach loop immediately [maps its iteration variable to another variable](1) - consider mapping the sequence explicitly using '.Select(...)'.

[Show more details](https://github.com/sillsdev/web-xforge/security/code-scanning/477)
</blockquote></details>

Done.
___
*[`src/SIL.XForge/Realtime/MemoryConnection.cs` line 113 at r3](https://reviewable.io/reviews/sillsdev/web-xforge/1716#-NOzVo2YCkZipRORzo8f:-NPDwLVF8BC07FyStEtr:blnj21o) ([raw file](https://github.com/sillsdev/web-xforge/blob/c83640a8a78731e6436a99e6e64151f2c757579f/src/SIL.XForge/Realtime/MemoryConnection.cs#L113)):*
<details><summary><i>Previously, marksvc wrote…</i></summary><blockquote>

Why are you using `await` and `Task.FromResult` here instead of just `return docs`?
</blockquote></details>

Thank you for spotting that - fixed!



_Code quote:_
```Smalltalk
eturn await Task.FromResult(docs);
```
___
*[`src/SIL.XForge/Realtime/Snapshot.cs` line 5 at r3](https://reviewable.io/reviews/sillsdev/web-xforge/1716#-NOvJVdd1kg4T8duU6KV:-NPDx4A_-sQXqnCDv8OY:bwnitmm) ([raw file](https://github.com/sillsdev/web-xforge/blob/c83640a8a78731e6436a99e6e64151f2c757579f/src/SIL.XForge/Realtime/Snapshot.cs#L5)):*
<details><summary><i>Previously, marksvc wrote…</i></summary><blockquote>

I'll probably be confused the next time I look at this. Can you add a comment that gives a hint what the Id is, such as whether it's the Id of the document that the snapshot pertains to, or whether it's an Id (uniquely) for the snapshot itself?
</blockquote></details>

Great idea. I have added comments to the class.



_Code quote:_
```Smalltalk
ublic class Snapshot<T>
```
___
*[`src/SIL.XForge.Scripture/Services/ParatextService.cs` line 1166 at r4](https://reviewable.io/reviews/sillsdev/web-xforge/1716#-NP-GAq5BS8ABd60l-wT:-NPE-_kB3m73MW7opQ2J:b-7vvd2u) ([raw file](https://github.com/sillsdev/web-xforge/blob/de54b0a02a478cdcb8663a64884c9c8f6aa22015/src/SIL.XForge.Scripture/Services/ParatextService.cs#L1166)):*
<details><summary><i>Previously, marksvc wrote…</i></summary><blockquote>

What is the significance of looking at the Comments[0].VerseRef.BookNum (here and later in the diff) instead of the thread VerseRef.BookNum? Are we going faster by doing this?
</blockquote></details>

Yes it is faster as it does not calculate the reallocated location. I tried to describe the reason why in the comment above - please let me know if I can make the comment clearer.
___
*[`src/SIL.XForge.Scripture/Services/ParatextSyncRunner.cs` line 1020 at r2](https://reviewable.io/reviews/sillsdev/web-xforge/1716#-NOz_apxCYxtgVeFFonS:-NPE1htI-ZUXlwtKNfM4:bcrica4) ([raw file](https://github.com/sillsdev/web-xforge/blob/db2498f9134794d29e382198709794a04d4619a9/src/SIL.XForge.Scripture/Services/ParatextSyncRunner.cs#L1020)):*
<details><summary><i>Previously, marksvc wrote…</i></summary><blockquote>

Maybe this should be named something else now, like.. DocsForBook or something.
And the method comment looks inaccurate now.
</blockquote></details>

Good idea - I have cleaned this up.



_Code quote:_
```Smalltalk
dList<int, IDocument<TextData>> FetchTextDocs(
```
___
*[`test/SIL.XForge.Scripture.Tests/Services/ParatextSyncRunnerTests.cs` line 1492 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/1716#-NOfznPpHwUjO9cjhsMs-r1-1492:-NPE21SN-Usa0jsFOpx_:b-896fix) ([raw file](https://github.com/sillsdev/web-xforge/blob/3a6378e36025453a05396375460ea442b06cf5b0/test/SIL.XForge.Scripture.Tests/Services/ParatextSyncRunnerTests.cs#L1492)):*
<details><summary><i>Previously, github-code-scanning[bot] wrote…</i></summary><blockquote>

## Useless assignment to local variable

This assignment to [ids](1) is useless, since its value is never read.

[Show more details](https://github.com/sillsdev/web-xforge/security/code-scanning/476)
</blockquote></details>

Done.
___
*[`test/SIL.XForge.Scripture.Tests/Services/ParatextSyncRunnerTests.cs` line 2339 at r3](https://reviewable.io/reviews/sillsdev/web-xforge/1716#-NP-1CMVA_qB0EjIiSfS:-NPE3dU60dRIezVAnqqN:b-5pbkjw) ([raw file](https://github.com/sillsdev/web-xforge/blob/c83640a8a78731e6436a99e6e64151f2c757579f/test/SIL.XForge.Scripture.Tests/Services/ParatextSyncRunnerTests.cs#L2339)):*
<details><summary><i>Previously, marksvc wrote…</i></summary><blockquote>

What's your thinking here; this is just to make it very clear that it is a substitute?
</blockquote></details>

I was originally going to have a different `Connection` property, like there is `RealtimeService` and `SubstituteRealtimeService`, but ended up not needing to. I have reverted this - thank you for pointing this out.

**Review by marksvc — CHANGES_REQUESTED** [review]
> Reviewed 4 of 4 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1716)* status: all files reviewed, 4 unresolved discussions (waiting on @github-code-scanning[bot] and @pmachapman)

___
*[`src/SIL.XForge/Realtime/Connection.cs` line 281 at r3](https://reviewable.io/reviews/sillsdev/web-xforge/1716#-NOzvADP5OcstkEc8o1O:-NPJ__is2AoeLRoYrwoj:bkvmuas) ([raw file](https://github.com/sillsdev/web-xforge/blob/b8a77d618f87c1a6bf897ace3674acfaa0f43c53/src/SIL.XForge/Realtime/Connection.cs#L281)):*
<details><summary><i>Previously, pmachapman (Peter Chapman) wrote…</i></summary><blockquote>

`snapshot` is not an optional argument - would you like me to make it one?
</blockquote></details>

Oops. No. I think I was getting it confused with typescript syntax.
___
*[`src/SIL.XForge/Realtime/Snapshot.cs` line 5 at r3](https://reviewable.io/reviews/sillsdev/web-xforge/1716#-NOvJVdd1kg4T8duU6KV:-NPJdLPd04PC7RAn0kjG:buyrutc) ([raw file](https://github.com/sillsdev/web-xforge/blob/b8a77d618f87c1a6bf897ace3674acfaa0f43c53/src/SIL.XForge/Realtime/Snapshot.cs#L5)):*
<details><summary><i>Previously, pmachapman (Peter Chapman) wrote…</i></summary><blockquote>

Great idea. I have added comments to the class.
</blockquote></details>

That's helpful, thank you!
___
*[`src/SIL.XForge.Scripture/Services/ParatextService.cs` line 1166 at r4](https://reviewable.io/reviews/sillsdev/web-xforge/1716#-NP-GAq5BS8ABd60l-wT:-NPJdgYyCN0TRDZZZqnV:bokcdx9) ([raw file](https://github.com/sillsdev/web-xforge/blob/eff23a20e7f0a817b91261c8f5f9794b326f05f7/src/SIL.XForge.Scripture/Services/ParatextService.cs#L1166)):*
<details><summary><i>Previously, pmachapman (Peter Chapman) wrote…</i></summary><blockquote>

Yes it is faster as it does not calculate the reallocated location. I tried to describe the reason why in the comment above - please let me know if I can make the comment clearer.
</blockquote></details>

Oh okay. So `commentThread.VerseRef` is probably considering the set of comments in the thread and determining where the verse ref is in light of any changes that may have been made. I think "reallocated" makes me more think of providing space or resources. Would it be accurate to say something like
```
// CommentThread.VerseRef determines the location of a thread, even if moved. However, in Paratext a note can only be
// relocated within the chapter, so for our query, we only need to look at the first note location.
```

I wonder if you were thinking "relocated"  but you have memory allocation on your mind? :)

(Or maybe there's something else going on here?)

**Review by marksvc — APPROVED** [review]
I did a light test of successfully syncing a project using the branch.

> Reviewed 1 of 1 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1716#-:-NPO-cizDAon88jpdlXR:b-wmpy2e)* status: all files reviewed, 3 unresolved discussions (waiting on @github-code-scanning[bot])

**Comment by marksvc** [comment]
I think I'll let you do the merge so you can choose how your commits are or aren't combined, according to your preference.

**Review by pmachapman — COMMENTED** [review]
> Dismissed @github-code-scanning[bot] from 3 discussions.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1716)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @pmachapman)

**Pull request merged**
