### PR TITLE
Fix catching of errors to be type safe

### PR DESCRIPTION
**Pull request by Nateowami**
This change is [Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1617)

### CODE REVIEW

**Review by RaymondLuong3 — COMMENTED** [review]
I have a couple questions. Thanks for your work on this!

> Reviewed 6 of 6 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1617#-:-NI-TGrM44xQKaqM3G-C:byjptjs)* status: all files reviewed, 2 unresolved discussions (waiting on @Nateowami)

___
*[`src/SIL.XForge.Scripture/ClientApp/src/xforge-common/command.service.ts` line 92 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/1617#-NI-RPEsA6hscq6E9ON3:-NI-RPEsA6hscq6E9ON4:bjs52sf) ([raw file](https://github.com/sillsdev/web-xforge/blob/33fa41bafc673d4aa264fc592b216c8a0f304ff0/src/SIL.XForge.Scripture/ClientApp/src/xforge-common/command.service.ts#L92)):*
> ```XML
>       let data: unknown;
>       if (error instanceof ErrorEvent) {
>         const errorEvent: ErrorEvent = error.error;
> ```

This is probably on purpose, but why is it important to assign errorEvent to `error.error`, and not just `error`?



_Code quote:_
```XML
    const errorEvent: ErrorEvent = error.error;
```
___
*[`src/SIL.XForge.Scripture/ClientApp/src/xforge-common/exception-handling-service.ts` line 217 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/1617#-NI-T1S0EczAqwjsIVKV:-NI-T1S1AsPAwr8jIgvS:b-lxsmby) ([raw file](https://github.com/sillsdev/web-xforge/blob/33fa41bafc673d4aa264fc592b216c8a0f304ff0/src/SIL.XForge.Scripture/ClientApp/src/xforge-common/exception-handling-service.ts#L217)):*
> ```XML
>     const messages = messageKeys
>       .map(key => (hasStringProp(error, key) ? error[key].split('\n')[0] : null))
>       .filter((s): s is string => s != null);
> ```

why is it important to specify the `s is string` type?



_Code quote:_
```XML
      .filter((s): s is string => s != null);
```

**Review by Nateowami — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1617)* status: 4 of 6 files reviewed, 2 unresolved discussions (waiting on @RaymondLuong3)

___
*[`src/SIL.XForge.Scripture/ClientApp/src/xforge-common/command.service.ts` line 92 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/1617#-NI-RPEsA6hscq6E9ON3:-NI0EWol3yBFPZXYtM1D:b-3fauyl) ([raw file](https://github.com/sillsdev/web-xforge/blob/33fa41bafc673d4aa264fc592b216c8a0f304ff0/src/SIL.XForge.Scripture/ClientApp/src/xforge-common/command.service.ts#L92)):*
<details><summary><i>Previously, RaymondLuong3 (Raymond Luong) wrote…</i></summary><blockquote>

This is probably on purpose, but why is it important to assign errorEvent to `error.error`, and not just `error`?
</blockquote></details>

We're making an HTTP request using Angular's `HttpClient`, which, when it fails, produces an `HttpErrorResponse`. Here's what `http.d.ts` says:

```
/**
 * A response that represents an error or failure, either from a
 * non-successful HTTP status, an error while executing the request,
 * or some other failure which occurred during the parsing of the response.
 *
 * Any error returned on the `Observable` response stream will be
 * wrapped in an `HttpErrorResponse` to provide additional context about
 * the state of the HTTP layer when the error occurred. The error property
 * will contain either a wrapped Error object or the error response returned
 * from the server.
 *
 * @publicApi
 */
export declare class HttpErrorResponse extends HttpResponseBase implements Error {
    readonly name = "HttpErrorResponse";
    readonly message: string;
    readonly error: any | null;
    /**
     * Errors are never okay, even when the status code is in the 2xx success range.
     */
    readonly ok = false;
    constructor(init: {
        error?: any;
        headers?: HttpHeaders;
        status?: number;
        statusText?: string;
        url?: string;
    });
}
```

So to summarize: When we catch an error here, we don't know where it came from. And if it came from `HttpClient`, it will be an object with information, and a property called `error` that has the original error.

All that said, I made a mistake, checking if `error instanceof ErrorEvent` rather than `error.error instanceof ErrorEvent`, which I've fixed.
___
*[`src/SIL.XForge.Scripture/ClientApp/src/xforge-common/exception-handling-service.ts` line 217 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/1617#-NI-T1S0EczAqwjsIVKV:-NI0IFcqAjgYl23s1ndU:b-ddcc8j) ([raw file](https://github.com/sillsdev/web-xforge/blob/33fa41bafc673d4aa264fc592b216c8a0f304ff0/src/SIL.XForge.Scripture/ClientApp/src/xforge-common/exception-handling-service.ts#L217)):*
<details><summary><i>Previously, RaymondLuong3 (Raymond Luong) wrote…</i></summary><blockquote>

why is it important to specify the `s is string` type?
</blockquote></details>

This is a [type predicate](https://www.typescriptlang.org/docs/handbook/2/narrowing.html#using-type-predicates), which tells the compiler that when this function returns true, the value is a string, and when it returns false, the value is not a string.

`messageKeys.map(...)` returns an array of type `(string | null)[]`, and then we filter out the nullish values, leaving only string values. But TypeScript won't narrow the type to `string[]` unless we tell it to (it doesn't follow the logic and see that all null values have been filtered out, so all remaining values must be string values). But if we give it a type predicate it will understand and infer that `messages` has a type of `string[]`.

However, while writing this I realized that if the type predicate is removed everything still works; it just infers a type of `(string | null)[]`, which doesn't cause any compilation errors, because on the next line when we read `messages[0]` we use nullish coalescing to handle nullish values. Everything will work correctly, but `messages` may have null values. So I'm adding a specific type definition of `string[]`.

**Review by RaymondLuong3 — APPROVED** [review]
Thanks for this improvement.

> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1617#-:-NI3UE2R3HAau145d7ZT:bab8xg1)* status: all files reviewed, 2 unresolved discussions (waiting on @Nateowami)

___
*[`src/SIL.XForge.Scripture/ClientApp/src/xforge-common/command.service.ts` line 92 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/1617#-NI-RPEsA6hscq6E9ON3:-NI3TaBK7B1q2YCbuGZw:blhl843) ([raw file](https://github.com/sillsdev/web-xforge/blob/33fa41bafc673d4aa264fc592b216c8a0f304ff0/src/SIL.XForge.Scripture/ClientApp/src/xforge-common/command.service.ts#L92)):*
<details><summary><i>Previously, Nateowami (Nathaniel Paulus) wrote…</i></summary><blockquote>

We're making an HTTP request using Angular's `HttpClient`, which, when it fails, produces an `HttpErrorResponse`. Here's what `http.d.ts` says:

```
/**
 * A response that represents an error or failure, either from a
 * non-successful HTTP status, an error while executing the request,
 * or some other failure which occurred during the parsing of the response.
 *
 * Any error returned on the `Observable` response stream will be
 * wrapped in an `HttpErrorResponse` to provide additional context about
 * the state of the HTTP layer when the error occurred. The error property
 * will contain either a wrapped Error object or the error response returned
 * from the server.
 *
 * @publicApi
 */
export declare class HttpErrorResponse extends HttpResponseBase implements Error {
    readonly name = "HttpErrorResponse";
    readonly message: string;
    readonly error: any | null;
    /**
     * Errors are never okay, even when the status code is in the 2xx success range.
     */
    readonly ok = false;
    constructor(init: {
        error?: any;
        headers?: HttpHeaders;
        status?: number;
        statusText?: string;
        url?: string;
    });
}
```

So to summarize: When we catch an error here, we don't know where it came from. And if it came from `HttpClient`, it will be an object with information, and a property called `error` that has the original error.

All that said, I made a mistake, checking if `error instanceof ErrorEvent` rather than `error.error instanceof ErrorEvent`, which I've fixed.
</blockquote></details>

Nice, now it makes sense why we are using `error.error`, it was confusing that we check that `error` was a certain object, and then use its error property.
___
*[`src/SIL.XForge.Scripture/ClientApp/src/xforge-common/exception-handling-service.ts` line 217 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/1617#-NI-T1S0EczAqwjsIVKV:-NI3U1R5C9fO5y_PKoU8:b-gkvjzv) ([raw file](https://github.com/sillsdev/web-xforge/blob/33fa41bafc673d4aa264fc592b216c8a0f304ff0/src/SIL.XForge.Scripture/ClientApp/src/xforge-common/exception-handling-service.ts#L217)):*
<details><summary><i>Previously, Nateowami (Nathaniel Paulus) wrote…</i></summary><blockquote>

This is a [type predicate](https://www.typescriptlang.org/docs/handbook/2/narrowing.html#using-type-predicates), which tells the compiler that when this function returns true, the value is a string, and when it returns false, the value is not a string.

`messageKeys.map(...)` returns an array of type `(string | null)[]`, and then we filter out the nullish values, leaving only string values. But TypeScript won't narrow the type to `string[]` unless we tell it to (it doesn't follow the logic and see that all null values have been filtered out, so all remaining values must be string values). But if we give it a type predicate it will understand and infer that `messages` has a type of `string[]`.

However, while writing this I realized that if the type predicate is removed everything still works; it just infers a type of `(string | null)[]`, which doesn't cause any compilation errors, because on the next line when we read `messages[0]` we use nullish coalescing to handle nullish values. Everything will work correctly, but `messages` may have null values. So I'm adding a specific type definition of `string[]`.
</blockquote></details>

I see, that is useful to know. In the past I would get squiggles in my editor because of things like this.

**Review by Nateowami — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1617)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @Nateowami)

___
*[`src/SIL.XForge.Scripture/ClientApp/src/xforge-common/command.service.ts` line 92 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/1617#-NI-RPEsA6hscq6E9ON3:-NI3W2UFE7Uoa9_-l_Fu:b-y6wypn) ([raw file](https://github.com/sillsdev/web-xforge/blob/33fa41bafc673d4aa264fc592b216c8a0f304ff0/src/SIL.XForge.Scripture/ClientApp/src/xforge-common/command.service.ts#L92)):*
<details><summary><i>Previously, RaymondLuong3 (Raymond Luong) wrote…</i></summary><blockquote>

Nice, now it makes sense why we are using `error.error`, it was confusing that we check that `error` was a certain object, and then use its error property.
</blockquote></details>

Good catch! I didn't even notice it until quite a ways into coming up with an explanation.

**Pull request merged**
