### PR TITLE
Display project short name

### PR DESCRIPTION
**Pull request by irahopkinson**
This change is [Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1107)

### CODE REVIEW

**Review by Nateowami — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1107)* status: 0 of 10 files reviewed, 2 unresolved discussions (waiting on @irahopkinson)

___
*[src/SIL.XForge.Scripture/ClientApp/src/app/app.component.ts, line 73 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/1107#-MfctRUAAC1l5nJD0RiX:-MfctRUAAC1l5nJD0RiY:brgrs4t) ([raw file](https://github.com/sillsdev/web-xforge/blob/1461ef1028c6d5407b1b2a78d892016b788cad22/src/SIL.XForge.Scripture/ClientApp/src/app/app.component.ts#L73)):*
> ```XML
>   hasUpdate: boolean = false;
> 
>   projectLabel: ProjectLabelFn = projectLabel;
> ```

I don't really see how having the type specified is helpful. I would think the entire purpose of writing out the type is so that it can be determined easily by reading the code, but this doesn't actually accomplish that. If I want to find out what the function signature is I would still have to either hover over the property in VSCode, or look up the file where the function is defined.
___
*[src/SIL.XForge.Scripture/ClientApp/src/app/shared/utils.ts, line 42 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/1107#-MfcSa21B84XM80sdjdT:-MfcSa21B84XM80sdjdU:bh39ae8) ([raw file](https://github.com/sillsdev/web-xforge/blob/1461ef1028c6d5407b1b2a78d892016b788cad22/src/SIL.XForge.Scripture/ClientApp/src/app/shared/utils.ts#L42)):*
> ```XML
> 
> export type ProjectLabelFn = (project: SelectableProject) => string;
> export function projectLabel(project: SelectableProject): string {
> ```

Here we're stating that the argument will be a `SelectableProject`.

In `app.component.html` we pass in `projectLabel(projectDoc.data!)`

And then on the next line here we do a null check:
`if (project == null || (!project.shortName && !project.name)) {`

Maybe the function signature should be `projectLabel(project: SelectableProject | undefined): string`?

**Review by irahopkinson — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1107)* status: 0 of 10 files reviewed, 2 unresolved discussions (waiting on @Nateowami)

___
*[src/SIL.XForge.Scripture/ClientApp/src/app/app.component.ts, line 73 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/1107#-MfctRUAAC1l5nJD0RiX:-MfqLkBmEFie_6NxsVNo:b-k4ztoz) ([raw file](https://github.com/sillsdev/web-xforge/blob/1461ef1028c6d5407b1b2a78d892016b788cad22/src/SIL.XForge.Scripture/ClientApp/src/app/app.component.ts#L73)):*
<details><summary><i>Previously, Nateowami (Nathaniel Paulus) wrote…</i></summary><blockquote>

I don't really see how having the type specified is helpful. I would think the entire purpose of writing out the type is so that it can be determined easily by reading the code, but this doesn't actually accomplish that. If I want to find out what the function signature is I would still have to either hover over the property in VSCode, or look up the file where the function is defined.
</blockquote></details>

Thanks for the feedback as I was in 2 minds when I added the function type. When I first did the assignment `projectLabel = projectLabel;` it looked odd so I added the type so you could see that it is a function assignment (not so you could tell what the signature is). Its simpler without it.
___
*[src/SIL.XForge.Scripture/ClientApp/src/app/shared/utils.ts, line 42 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/1107#-MfcSa21B84XM80sdjdT:-MfqMIJN-QXGpfKBU-kM:b-896fix) ([raw file](https://github.com/sillsdev/web-xforge/blob/1461ef1028c6d5407b1b2a78d892016b788cad22/src/SIL.XForge.Scripture/ClientApp/src/app/shared/utils.ts#L42)):*
<details><summary><i>Previously, Nateowami (Nathaniel Paulus) wrote…</i></summary><blockquote>

Here we're stating that the argument will be a `SelectableProject`.

In `app.component.html` we pass in `projectLabel(projectDoc.data!)`

And then on the next line here we do a null check:
`if (project == null || (!project.shortName && !project.name)) {`

Maybe the function signature should be `projectLabel(project: SelectableProject | undefined): string`?
</blockquote></details>

Done.

**Review by Nateowami — APPROVED** [review]
:lgtm:

> Reviewed 6 of 10 files at r1, 2 of 2 files at r2, 3 of 3 files at r3.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1107#-:-Mg8VQ624pSdEgXX4saE:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @irahopkinson)

___
*[src/SIL.XForge.Scripture/ClientApp/src/app/app.component.html, line 164 at r3](https://reviewable.io/reviews/sillsdev/web-xforge/1107#-Mg8Uc524DFxupsMVRI1:-Mg8Uc524DFxupsMVRI2:bydh8cj) ([raw file](https://github.com/sillsdev/web-xforge/blob/34ff9b7ae356d4c432a26abacc9a26d986b20bfc/src/SIL.XForge.Scripture/ClientApp/src/app/app.component.html#L164)):*
> ```HTML
>           <mdc-list>
>             <mdc-list-item *ngFor="let projectDoc of projectDocs" [value]="projectDoc.id">{{
>               projectLabel(projectDoc.data!)
> ```

I think this no longer needs the non-null assertion operator (`!`).

**Review by irahopkinson — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1107)* status: 10 of 11 files reviewed, 1 unresolved discussion (waiting on @Nateowami)

___
*[src/SIL.XForge.Scripture/ClientApp/src/app/app.component.html, line 164 at r3](https://reviewable.io/reviews/sillsdev/web-xforge/1107#-Mg8Uc524DFxupsMVRI1:-Mg8z93C253qb6DsuGxx:bb6un1j) ([raw file](https://github.com/sillsdev/web-xforge/blob/34ff9b7ae356d4c432a26abacc9a26d986b20bfc/src/SIL.XForge.Scripture/ClientApp/src/app/app.component.html#L164)):*
<details><summary><i>Previously, Nateowami (Nathaniel Paulus) wrote…</i></summary><blockquote>

I think this no longer needs the non-null assertion operator (`!`).
</blockquote></details>

Done

**Pull request merged**
