### PR TITLE
SF-2194 Chapter Audio Close Button

### PR DESCRIPTION
**Pull request by josephmyers**
This change is [Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/2014)

### CODE REVIEW

**Review by RaymondLuong3 — CHANGES_REQUESTED** [review]
Nice work. I think the close button makes sense, rather than a delete button. Also, you might want to pause work on this until PR #2003 is merged since I have also done some work to pause the audio when the audio player is hidden.
What is the plan for the delete audio UI? I assume it will be moved elsewhere?

> Reviewed 6 of 6 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/2014#-:-Ncd5y_528NyKBq8P8R3:bqybcsd)* status: all files reviewed, 4 unresolved discussions (waiting on @josephmyers)

___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking.component.ts` line 1188 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/2014#-Ncd5Z2w2sJCblAKvpCB:-Ncd5Z2w2sJCblAKvpCC:b-mrr68u) ([raw file](https://github.com/sillsdev/web-xforge/blob/62ccf7ff94267c43e0ae023eb83dfaebbc7bbd29/src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking.component.ts#L1188)):*
> ```XML
> 
>   hideChapterAudio(): void {
>     this.chapterAudio?.pause();
> ```

You can move this into the `CheckingScriptureAudioPlayerComponent`, then it would be the responsibility of the class to stop the audio when the close button is clicked.



_Code quote:_
```XML
    this.chapterAudio?.pause();
```
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking.component.spec.ts` line 139 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/2014#-Ncd41m39Ea6dZQCmm_c:-Ncd41m39Ea6dZQCmm_d:b-8d6tg) ([raw file](https://github.com/sillsdev/web-xforge/blob/62ccf7ff94267c43e0ae023eb83dfaebbc7bbd29/src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking.component.spec.ts#L139)):*
> ```XML
>       CheckingCommentsComponent,
>       CheckingComponent,
>       CheckingScriptureAudioPlayerComponent,
> ```

Nice work figuring out that you needed to declare the scripture audio player. I couldn't figure that out when I tried.



_Code quote:_
```XML
   CheckingScriptureAudioPlayerComponent,
```
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking.component.spec.ts` line 1679 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/2014#-Ncd4KRy3Ksg3ghpLyOz:-Ncd4KRy3Ksg3ghpLyP-:b-apkub3) ([raw file](https://github.com/sillsdev/web-xforge/blob/62ccf7ff94267c43e0ae023eb83dfaebbc7bbd29/src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking.component.spec.ts#L1679)):*
> ```XML
>       env.fixture.detectChanges();
> 
>       expect(env.component.chapterAudio).not.toBe(undefined);
> ```

You can write toBeDefined(). It reads better than checking not undefined.



_Code quote:_
```XML
  expect(env.component.chapterAudio).not.toBe(undefined);
```
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking.component.spec.ts` line 1687 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/2014#-Ncd4ZJ39bJeTn-teNt3:-Ncd4ZJ39bJeTn-teNt4:b2nreh6) ([raw file](https://github.com/sillsdev/web-xforge/blob/62ccf7ff94267c43e0ae023eb83dfaebbc7bbd29/src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking.component.spec.ts#L1687)):*
> ```XML
>       env.fixture.detectChanges();
> 
>       expect(env.component.chapterAudio).not.toBe(undefined);
> ```

Same as above.



_Code quote:_
```XML
      expect(env.component.chapterAudio).not.toBe(undefined);
```

**Review by josephmyers — COMMENTED** [review]
The delete feature is available from "Manage questions" on Checking Overview, and the design doc never mentions putting it here. I also wanted to keep just what's necessary on this page, but I could go either way. We don't really know the user's preferred workflow yet.

> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/2014#-:-NcuHdqg1gzyBoZZ1T13:bcqjupc)* status: 2 of 6 files reviewed, 3 unresolved discussions (waiting on @RaymondLuong3)

___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking.component.ts` line 1188 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/2014#-Ncd5Z2w2sJCblAKvpCB:-NcuGtln-qMgDgxXHu1N:bi78xuh) ([raw file](https://github.com/sillsdev/web-xforge/blob/62ccf7ff94267c43e0ae023eb83dfaebbc7bbd29/src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking.component.ts#L1188)):*
<details><summary><i>Previously, RaymondLuong3 (Raymond Luong) wrote…</i></summary><blockquote>

You can move this into the `CheckingScriptureAudioPlayerComponent`, then it would be the responsibility of the class to stop the audio when the close button is clicked.
</blockquote></details>

Sure, that makes sense!
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking.component.spec.ts` line 1679 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/2014#-Ncd4KRy3Ksg3ghpLyOz:-NcuHLKL26aQYqE30pZt:b-896fix) ([raw file](https://github.com/sillsdev/web-xforge/blob/62ccf7ff94267c43e0ae023eb83dfaebbc7bbd29/src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking.component.spec.ts#L1679)):*
<details><summary><i>Previously, RaymondLuong3 (Raymond Luong) wrote…</i></summary><blockquote>

You can write toBeDefined(). It reads better than checking not undefined.
</blockquote></details>

Done.
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking.component.spec.ts` line 1687 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/2014#-Ncd4ZJ39bJeTn-teNt3:-NcuHM_b5D9EGWw5ZF7e:b-896fix) ([raw file](https://github.com/sillsdev/web-xforge/blob/62ccf7ff94267c43e0ae023eb83dfaebbc7bbd29/src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking.component.spec.ts#L1687)):*
<details><summary><i>Previously, RaymondLuong3 (Raymond Luong) wrote…</i></summary><blockquote>

Same as above.
</blockquote></details>

Done.

**Review by RaymondLuong3 — CHANGES_REQUESTED** [review]
Aha, I had a feeling that it was odd to allow a user to delete their audio data so easily. I'm glad to just have a close icon on the main scripture audio screen. Just a couple minor comments.

> Reviewed 5 of 5 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/2014#-:-Nd19nS52kkbMbdc580c:be4329j)* status: all files reviewed, 1 unresolved discussion (waiting on @josephmyers)

___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking.component.spec.ts` line 38 at r2](https://reviewable.io/reviews/sillsdev/web-xforge/2014#-Nd19HG311CCn62MI5n2:-Nd19HG46DaK49_Hhn0u:b-hghite) ([raw file](https://github.com/sillsdev/web-xforge/blob/db743446e3aca2e6ecd161d8696f3e11c60fbae0/src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking.component.spec.ts#L38)):*
> ```XML
> import { first } from 'rxjs/operators';
> import { TextAudioDoc } from 'src/app/core/models/text-audio-doc';
> import { AudioPlayerComponent } from 'src/app/shared/audio/audio-player/audio-player.component';
> ```

You will want to update this to relative paths. And the one above this too.



_Code quote:_
```XML
import { AudioPlayerComponent } from 'src/app/shared/audio/audio-player/audio-player.component';
```

**Review by josephmyers — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/2014)* status: all files reviewed, 1 unresolved discussion (waiting on @RaymondLuong3)

___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking.component.spec.ts` line 38 at r2](https://reviewable.io/reviews/sillsdev/web-xforge/2014#-Nd19HG311CCn62MI5n2:-Nd4qdk17EpwhUpJIajB:b-896fix) ([raw file](https://github.com/sillsdev/web-xforge/blob/db743446e3aca2e6ecd161d8696f3e11c60fbae0/src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking.component.spec.ts#L38)):*
<details><summary><i>Previously, RaymondLuong3 (Raymond Luong) wrote…</i></summary><blockquote>

You will want to update this to relative paths. And the one above this too.
</blockquote></details>

Done.

**Review by RaymondLuong3 — APPROVED** [review]
:lgtm: 

> Reviewed 5 of 5 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/2014#-:-Nd8YNmqEcOp60NAwaVI:bg7igkv)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @josephmyers)

**Review by RaymondLuong3 — APPROVED** [review]
> Reviewed 3 of 3 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/2014)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @josephmyers)

**Review by RaymondLuong3 — APPROVED** [review]
> Reviewed 3 of 3 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/2014)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @josephmyers)

**Pull request merged**
