### PR TITLE
SF-2438 Localize error message strings in chapter audio dialog

### PR DESCRIPTION
**Pull request by RaymondLuong3**
This was broken in PR #2237 on the audio upload dialog.

- - -
This change is [Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/2278)

### CODE REVIEW

**Review by Nateowami — COMMENTED** [review]
Can you look at the branch `fix/chapter-audio-i18n-types` for an improvement that I think will make these localization strings easier to work with in the template?

> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/2278#-:-NndaVrj6NT4noYJkBCs:b4cgpc8)* status: 0 of 3 files reviewed, 1 unresolved discussion (waiting on @RaymondLuong3)

___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/checking/chapter-audio-dialog/chapter-audio-dialog.component.ts` line 68 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/2278#-NndSQd7An8km-L2ZJpD:-NndSQd7An8km-L2ZJpE:bdijc4k) ([raw file](https://github.com/sillsdev/web-xforge/blob/9c065f35802d34fd6ef098965f4e77d01897678c/src/SIL.XForge.Scripture/ClientApp/src/app/checking/chapter-audio-dialog/chapter-audio-dialog.component.ts#L68)):*
> ```XML
>   private _audioBlob?: string;
>   private _audioErrorText?: I18nKey;
>   private _timingErrorText?: I18nKey;
> ```

These variable names are misleading, and some of the getters that use them are misleading. They're not the text themselves, only the key.

**Comment by RaymondLuong3** [comment]
Thanks! That looks like a good solution. There are some test case failures that I will work through.

**Review by RaymondLuong3 — COMMENTED** [review]
Ok, I've applied your changes and I think the keys are handled much better this way.

> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/2278#-:-NneqiVM6s62uu6IZOdh:b-ug0iwi)* status: 0 of 4 files reviewed, all discussions resolved (waiting on @Nateowami)

___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/checking/chapter-audio-dialog/chapter-audio-dialog.component.ts` line 68 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/2278#-NndSQd7An8km-L2ZJpD:-Nneqf1k2lBfIrQJS9CL:bb6un1j) ([raw file](https://github.com/sillsdev/web-xforge/blob/9c065f35802d34fd6ef098965f4e77d01897678c/src/SIL.XForge.Scripture/ClientApp/src/app/checking/chapter-audio-dialog/chapter-audio-dialog.component.ts#L68)):*
<details><summary><i>Previously, Nateowami (Nathaniel Paulus) wrote…</i></summary><blockquote>

These variable names are misleading, and some of the getters that use them are misleading. They're not the text themselves, only the key.
</blockquote></details>

Done

**Review by Nateowami — APPROVED** [review]
:lgtm:

> Reviewed 3 of 4 files at r2, 1 of 1 files at r3, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/2278#-:-Nnf8S_L7zz1eTBJBKto:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @RaymondLuong3)

___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/checking/chapter-audio-dialog/chapter-audio-dialog.component.spec.ts` line 201 at r2](https://reviewable.io/reviews/sillsdev/web-xforge/2278#-NnetAQz0Q69uHpK1kse:-NnetAQz0Q69uHpK1ksf:b6d829d) ([raw file](https://github.com/sillsdev/web-xforge/blob/c998376bc3caef3096f00a07b70e2fa23d6db5bf/src/SIL.XForge.Scripture/ClientApp/src/app/checking/chapter-audio-dialog/chapter-audio-dialog.component.spec.ts#L201)):*
> ```XML
>     await env.wait();
> 
>     expect(env.component.timingErrorMessageKey).toContain('zero_segments');
> ```

`toContain()` makes a lot more sense when you're testing for a localized string in the DOM (since there are often spaces padding the text), but if we're checking a localization string, it seems like it should be `toBe()`

**Pull request merged**
