### PR TITLE
Add Mongo databases cleanup script

### PR DESCRIPTION
**Pull request by irahopkinson**
This has already been run on QA and Live. It might not make our QA Mongo more stable but it is worth a try and the cleanup was overdue anyway.

---
This change is [Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1255)

### CODE REVIEW

**Review by RaymondLuong3 — APPROVED** [review]
This script removes all the databases in our mongo that SFv2 does not use, is that correct? I remember seeing lots of project specific databases in mongo for projects in SFv1.

> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1255#-:-MxBhct757M1VkeSTOQz:b-mku0y9)* status: all files reviewed, 1 unresolved discussion (waiting on @irahopkinson)

___
*[mongodb/databases/dropDBNonSF.mongodb, line 12 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/1255#-MxBhUktAqKc15TbljSo:-MxBhUku3HEv80l6PUk9:b7j99pt) ([raw file](https://github.com/sillsdev/web-xforge/blob/369a2a14cb98e9b8d9d7cb396ddcc25bc82691da/mongodb/databases/dropDBNonSF.mongodb#L12)):*
> ```
>   db.dropDatabase();
> });
> dbs;
> ```

I remember there was a reason for adding this line at the end. What was it?



_Code quote:_
```
dbs;
```

**Review by Nateowami — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1255)* status: all files reviewed, 1 unresolved discussion (waiting on @RaymondLuong3)

___
*[mongodb/databases/dropDBNonSF.mongodb, line 12 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/1255#-MxBhUktAqKc15TbljSo:-MxBibZg5P6VM0vMjfN8:b-eg4kri) ([raw file](https://github.com/sillsdev/web-xforge/blob/369a2a14cb98e9b8d9d7cb396ddcc25bc82691da/mongodb/databases/dropDBNonSF.mongodb#L12)):*
<details><summary><i>Previously, RaymondLuong3 (Raymond Luong) wrote…</i></summary><blockquote>

I remember there was a reason for adding this line at the end. What was it?
</blockquote></details>

If run in VSCode with the MongoDB extension, the last expression gets shown in the "playground result" pane. So it's like logging it, but not to the console.

**Review by irahopkinson — COMMENTED** [review]
Yes, and No. We had cleaned up all the SFv1 projects. Those projects that were removed actually all belong to LF (despite them all starting with `sf_` which is legacy since SF was created first and LF just used the same code). LF is no longer using either of our Mongo instances since theirs is now in the K8 pod.

> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1255#-:-MxCjKv55krvRt3v9Zd3:bh6yp3i)* status: all files reviewed, 1 unresolved discussion (waiting on @Nateowami and @RaymondLuong3)

___
*[mongodb/databases/dropDBNonSF.mongodb, line 12 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/1255#-MxBhUktAqKc15TbljSo:-MxCjvFx0KBoiNIHd-j0:b-4z1fbi) ([raw file](https://github.com/sillsdev/web-xforge/blob/5d0ec850a255e5bf1997e8ea18ef918ae16bf266/mongodb/databases/dropDBNonSF.mongodb#L12)):*
<details><summary><i>Previously, Nateowami (Nathaniel Paulus) wrote…</i></summary><blockquote>

If run in VSCode with the MongoDB extension, the last expression gets shown in the "playground result" pane. So it's like logging it, but not to the console.
</blockquote></details>

Right, the first run will show all the DBs that existed in the results pane. A second run will just show the 6 in the whitelist (so you know that it worked).

**Review by RaymondLuong3 — APPROVED** [review]
Ok, I wasn't aware that LF projects had moved out of mongo, but that's good to know that now mongo won't be cluttered with outdated databases.

> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1255#-:-MxFqApr8tO9WRhlSdNR:b-k6clae)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @irahopkinson)

**Pull request merged**
