### PR TITLE
SF-886 update translated help files

### PR DESCRIPTION
**Pull request by irahopkinson**
* idata???.js and idata???.new.js
* toc???.js and toc???.new.js
* add menu title translations
* add csproj to sln (VSCode now finds issues)

---
This change is [Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/782)

### CODE REVIEW

**Review by RaymondLuong3 — CHANGES_REQUESTED** [review]
A few blocking comments. I have not tried this out locally.

> Reviewed 4 of 4 files at r1.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/782#-:-MGKPuoT1Hf0tQkRh7uh:b-bzgmph)* status: all files reviewed, 7 unresolved discussions (waiting on @irahopkinson)

___
*[src/Help/UpdateHelp/Program.cs, line 39 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/782#-MGKD6XQCl-2RVni3C7h:-MGKD6XQCl-2RVni3C7i:b-8pujuw) ([raw file](https://github.com/sillsdev/web-xforge/blob/708f3d0516156f5807ef036cb1ca8d1f1b1942a6/src/Help/UpdateHelp/Program.cs#L39)):*
> ```
>         string target = "es";
> ```
This could be a command line argument instead so the code doesn't need to be changed to run the program. Or it could read the name of the current directory.
___
*[src/Help/UpdateHelp/Program.cs, line 110 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/782#-MGKExmD9oEbyz8HYJD3:-MGKExmD9oEbyz8HYJD4:b-cmv2hy) ([raw file](https://github.com/sillsdev/web-xforge/blob/708f3d0516156f5807ef036cb1ca8d1f1b1942a6/src/Help/UpdateHelp/Program.cs#L110)):*
> ```
> Directory.GetFiles(sourcePath, "*.htm",
> ```
Is that supposed to be `html` ?
___
*[src/Help/UpdateHelp/Program.cs, line 111 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/782#-MGKEraR7CKEAfLFjRLW:-MGKEraR7CKEAfLFjRLX:b-l2u789) ([raw file](https://github.com/sillsdev/web-xforge/blob/708f3d0516156f5807ef036cb1ca8d1f1b1942a6/src/Help/UpdateHelp/Program.cs#L111)):*
> ```
> The are {files.Length}
> ```
typo
___
*[src/Help/UpdateHelp/Program.cs, line 206 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/782#-MGKHn9mCQuyZrSi20Fv:-MGKHn9mCQuyZrSi20Fw:bd4f0f5) ([raw file](https://github.com/sillsdev/web-xforge/blob/708f3d0516156f5807ef036cb1ca8d1f1b1942a6/src/Help/UpdateHelp/Program.cs#L206)):*
> ```
> The are {files.Length} 
> ```
Typo.
___
*[src/Help/UpdateHelp/Program.cs, line 208 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/782#-MGKKJoI7eYM7Yr3kg4s:-MGKKJoI7eYM7Yr3kg4t:bkkzqwd) ([raw file](https://github.com/sillsdev/web-xforge/blob/708f3d0516156f5807ef036cb1ca8d1f1b1942a6/src/Help/UpdateHelp/Program.cs#L208)):*
> ```
> Func<string, string> topicTextInIdata = topicName => $"<topic name=\\\"{topicName}\\\"";
> ```
Will it ever be possible for the text not to contain something like `<topic name="someName" that we should guard against?
___
*[src/Help/UpdateHelp/Program.cs, line 241 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/782#-MGKO5nb1pmlYGynrkJB:-MGKO5nb1pmlYGynrkJC:b-l3emt5) ([raw file](https://github.com/sillsdev/web-xforge/blob/708f3d0516156f5807ef036cb1ca8d1f1b1942a6/src/Help/UpdateHelp/Program.cs#L241)):*
> ```
> The are {files.Length}
> ```
Typo
___
*[src/Help/UpdateHelp/Program.cs, line 254 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/782#-MGKOXmNAEYOPYomEPJA:-MGKOXmNAEYOPYomEPJB:b-p71rgz) ([raw file](https://github.com/sillsdev/web-xforge/blob/708f3d0516156f5807ef036cb1ca8d1f1b1942a6/src/Help/UpdateHelp/Program.cs#L254)):*
> ```
> if (doWrite)
> ```
Nit: This could be up higher in the method

**Review by irahopkinson — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/782)* status: 3 of 4 files reviewed, 4 unresolved discussions (waiting on @RaymondLuong3)

___
*[src/Help/UpdateHelp/Program.cs, line 39 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/782#-MGKD6XQCl-2RVni3C7h:-MGrB12C1Tk39TxAIJFx:b-896fix) ([raw file](https://github.com/sillsdev/web-xforge/blob/708f3d0516156f5807ef036cb1ca8d1f1b1942a6/src/Help/UpdateHelp/Program.cs#L39)):*
<details><summary><i>Previously, RaymondLuong3 (Raymond Luong) wrote…</i></summary><blockquote>

> ```
>         string target = "es";
> ```
This could be a command line argument instead so the code doesn't need to be changed to run the program. Or it could read the name of the current directory.
</blockquote></details>

Done.
___
*[src/Help/UpdateHelp/Program.cs, line 110 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/782#-MGKExmD9oEbyz8HYJD3:-MGrB617-9Ygh20kLYnA:b-p3fgtn) ([raw file](https://github.com/sillsdev/web-xforge/blob/708f3d0516156f5807ef036cb1ca8d1f1b1942a6/src/Help/UpdateHelp/Program.cs#L110)):*
<details><summary><i>Previously, RaymondLuong3 (Raymond Luong) wrote…</i></summary><blockquote>

> ```
> Directory.GetFiles(sourcePath, "*.htm",
> ```
Is that supposed to be `html` ?
</blockquote></details>

No, they are definitely `htm` files from RoboHelp. Windows file extensions are usually only 3 characters.
___
*[src/Help/UpdateHelp/Program.cs, line 111 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/782#-MGKEraR7CKEAfLFjRLW:-MGrBVXf2_pcX1dkesOq:b-896fix) ([raw file](https://github.com/sillsdev/web-xforge/blob/708f3d0516156f5807ef036cb1ca8d1f1b1942a6/src/Help/UpdateHelp/Program.cs#L111)):*
<details><summary><i>Previously, RaymondLuong3 (Raymond Luong) wrote…</i></summary><blockquote>

> ```
> The are {files.Length}
> ```
typo
</blockquote></details>

Done.
___
*[src/Help/UpdateHelp/Program.cs, line 206 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/782#-MGKHn9mCQuyZrSi20Fv:-MGrBW8H5aEDCUOM3OG-:b-896fix) ([raw file](https://github.com/sillsdev/web-xforge/blob/708f3d0516156f5807ef036cb1ca8d1f1b1942a6/src/Help/UpdateHelp/Program.cs#L206)):*
<details><summary><i>Previously, RaymondLuong3 (Raymond Luong) wrote…</i></summary><blockquote>

> ```
> The are {files.Length} 
> ```
Typo.
</blockquote></details>

Done.
___
*[src/Help/UpdateHelp/Program.cs, line 208 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/782#-MGKKJoI7eYM7Yr3kg4s:-MGrCDqmAiqQu6aM0dLw:b25zgej) ([raw file](https://github.com/sillsdev/web-xforge/blob/708f3d0516156f5807ef036cb1ca8d1f1b1942a6/src/Help/UpdateHelp/Program.cs#L208)):*
<details><summary><i>Previously, RaymondLuong3 (Raymond Luong) wrote…</i></summary><blockquote>

> ```
> Func<string, string> topicTextInIdata = topicName => $"<topic name=\\\"{topicName}\\\"";
> ```
Will it ever be possible for the text not to contain something like `<topic name="someName" that we should guard against?
</blockquote></details>

There might be but we can cross that bridge should we ever come to it.
___
*[src/Help/UpdateHelp/Program.cs, line 241 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/782#-MGKO5nb1pmlYGynrkJB:-MGrBkK27mqcRLib-yJh:b-896fix) ([raw file](https://github.com/sillsdev/web-xforge/blob/708f3d0516156f5807ef036cb1ca8d1f1b1942a6/src/Help/UpdateHelp/Program.cs#L241)):*
<details><summary><i>Previously, RaymondLuong3 (Raymond Luong) wrote…</i></summary><blockquote>

> ```
> The are {files.Length}
> ```
Typo
</blockquote></details>

Done.
___
*[src/Help/UpdateHelp/Program.cs, line 254 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/782#-MGKOXmNAEYOPYomEPJA:-MGrBlr_1ZCEpD-TD0To:b4bkam0) ([raw file](https://github.com/sillsdev/web-xforge/blob/708f3d0516156f5807ef036cb1ca8d1f1b1942a6/src/Help/UpdateHelp/Program.cs#L254)):*
<details><summary><i>Previously, RaymondLuong3 (Raymond Luong) wrote…</i></summary><blockquote>

> ```
> if (doWrite)
> ```
Nit: This could be up higher in the method
</blockquote></details>

It kinda could be but for debugging purposes it is more useful here. Doing the write only when needed means I can exercise and check all other code when not in write mode.

**Review by ddaspit — CHANGES_REQUESTED** [review]
> Reviewed 2 of 4 files at r1, 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/782)* status: all files reviewed, 10 unresolved discussions (waiting on @irahopkinson and @RaymondLuong3)

___
*[src/Help/UpdateHelp/Program.cs, line 111 at r2](https://reviewable.io/reviews/sillsdev/web-xforge/782#-MGrISce5TdGB7MVbkmQ:-MGrISce5TdGB7MVbkmR:bygngju) ([raw file](https://github.com/sillsdev/web-xforge/blob/93a7e26d26210b0a9732139125c095ea604d63e8/src/Help/UpdateHelp/Program.cs#L111)):*
> ```Smalltalk
>                 string[] files = Directory.GetFiles(sourcePath, "*.htm", SearchOption.AllDirectories);
>                 Console.WriteLine($"There are {files.Length} HTML source files.");
>                 string heading;
> ```

These variables should be declared in scope.
___
*[src/Help/UpdateHelp/Program.cs, line 156 at r2](https://reviewable.io/reviews/sillsdev/web-xforge/782#-MGrJFjQDR5x9yk39BUs:-MGrJFjQDR5x9yk39BUt:bi0xfex) ([raw file](https://github.com/sillsdev/web-xforge/blob/93a7e26d26210b0a9732139125c095ea604d63e8/src/Help/UpdateHelp/Program.cs#L156)):*
> ```Smalltalk
>                     ExtractJsonStringsAndKeys(property.Name, property.Value, targetMenuItems);
>                 foreach (var targetMenuItem in targetMenuItems)
>                     if (sourceMenuItems.ContainsKey(targetMenuItem.Key))
> ```

You could use `TryGetValue` instead of `ContainsKey` and indexer access.
___
*[src/Help/UpdateHelp/Program.cs, line 206 at r2](https://reviewable.io/reviews/sillsdev/web-xforge/782#-MGrKM1r00pPXDsvX6FJ:-MGrKM1r00pPXDsvX6FK:b-s2859d) ([raw file](https://github.com/sillsdev/web-xforge/blob/93a7e26d26210b0a9732139125c095ea604d63e8/src/Help/UpdateHelp/Program.cs#L206)):*
> ```Smalltalk
>                 string[] files = Directory.GetFiles(sourcePath, "idata???.js");
>                 Console.WriteLine($"There are {files.Length} idata source files.");
>                 XDocument doc;
> ```

This can be declared in scope.
___
*[src/Help/UpdateHelp/Program.cs, line 241 at r2](https://reviewable.io/reviews/sillsdev/web-xforge/782#-MGrKWeK7iYoJUWXeIc_:-MGrKWeK7iYoJUWXeIca:b-s2859d) ([raw file](https://github.com/sillsdev/web-xforge/blob/93a7e26d26210b0a9732139125c095ea604d63e8/src/Help/UpdateHelp/Program.cs#L241)):*
> ```Smalltalk
>                 string[] files = Directory.GetFiles(sourcePath, "toc???.js");
>                 Console.WriteLine($"There are {files.Length} toc source files.");
>                 XDocument doc;
> ```

This can be declared in scope.
___
*[src/Help/UpdateHelp/Program.cs, line 311 at r2](https://reviewable.io/reviews/sillsdev/web-xforge/782#-MGrKtl2CG0g1owcB3JW:-MGrKtl2CG0g1owcB3JX:bb9md0q) ([raw file](https://github.com/sillsdev/web-xforge/blob/93a7e26d26210b0a9732139125c095ea604d63e8/src/Help/UpdateHelp/Program.cs#L311)):*
> ```Smalltalk
>                 string attr1 = element.Attribute(attr1Name).Value;
>                 string attr2 = element.Attribute(att2Name).Value;
>                 if (attr2ByAttr1.ContainsKey(attr1))
> ```

You could use `TryGetValue` here.
___
*[src/Help/UpdateHelp/UpdateHelp.csproj, line 6 at r2](https://reviewable.io/reviews/sillsdev/web-xforge/782#-MGrLEZ12ZcNq-T2heI4:-MGrLEZ12ZcNq-T2heI5:b-pb11b8) ([raw file](https://github.com/sillsdev/web-xforge/blob/93a7e26d26210b0a9732139125c095ea604d63e8/src/Help/UpdateHelp/UpdateHelp.csproj#L6)):*
> ```XML
>     <OutputType>Exe</OutputType>
>     <TargetFramework>netcoreapp3.1</TargetFramework>
>     <RuntimeIdentifiers>win-x64;linux-x64</RuntimeIdentifiers>
> ```

It is usually not necessary to define the `RuntimeIdentifiers`.

**Review by RaymondLuong3 — APPROVED** [review]
> Reviewed 2 of 2 files at r3.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/782)* status: all files reviewed, 6 unresolved discussions (waiting on @ddaspit)

**Review by ddaspit — APPROVED** [review]
:lgtm:

> Reviewed 1 of 4 files at r1.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/782#-:-MGv0hJ2E0wCjt6ySuut:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
