### PR TITLE
SF-1262 - Clean up local beta site data

### PR DESCRIPTION
**Pull request by nigel-wells**
- Clear local storage
 - Delete indexDB data

---
This change is [Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1018)

### CODE REVIEW

**Review by irahopkinson — APPROVED** [review]
Looks good, with one non-blocking question.

> Reviewed 4 of 4 files at r1.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1018#-:-MYOOat61KcIKwwL2bo0:b7lzbu7)* status: all files reviewed, 1 unresolved discussion (waiting on @nigel-wells)

___
*[src/SIL.XForge.Scripture/ClientApp/src/xforge-common/beta-migration/beta-migration.component.ts, line 72 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/1018#-MYOMfcg2s76eSfpDes8:-MYOMfcmAYInhvMOTkUG:b-deej6k) ([raw file](https://github.com/sillsdev/web-xforge/blob/45185c31d191ff900dc83e48cec53b62943089fd/src/SIL.XForge.Scripture/ClientApp/src/xforge-common/beta-migration/beta-migration.component.ts#L72)):*
> ```
>         this.localSettings.clear();
>         await this.offlineStore.deleteDB();
> ```
The other 2 places we do this in the other order. I'm guessing (by looking at the method names but without looking into each method) that makes better sense than this order? Is this order change needed for some reason?

**Review by nigel-wells — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1018)* status: all files reviewed, 1 unresolved discussion (waiting on @irahopkinson)

___
*[src/SIL.XForge.Scripture/ClientApp/src/xforge-common/beta-migration/beta-migration.component.ts, line 72 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/1018#-MYOMfcg2s76eSfpDes8:-MYOYkdKBFSsLVWEoHgl:b-k36p1i) ([raw file](https://github.com/sillsdev/web-xforge/blob/45185c31d191ff900dc83e48cec53b62943089fd/src/SIL.XForge.Scripture/ClientApp/src/xforge-common/beta-migration/beta-migration.component.ts#L72)):*
<details><summary><i>Previously, irahopkinson (Ira Hopkinson) wrote…</i></summary><blockquote>

> ```
>         this.localSettings.clear();
>         await this.offlineStore.deleteDB();
> ```
The other 2 places we do this in the other order. I'm guessing (by looking at the method names but without looking into each method) that makes better sense than this order? Is this order change needed for some reason?
</blockquote></details>

Yes I had received an error (warning?) when it was the other way around. Thinking about it now I think I tried switching them at the same time I moved the `onlineInvoke` call to happen prior to clearing data - which of course failed to authenticate with the bankend when there was no access token any more to use! It could very well work fine the other way around the same as the `auth-service.ts` file has them.

**Review by nigel-wells — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1018)* status: 3 of 4 files reviewed, 1 unresolved discussion (waiting on @irahopkinson)

___
*[src/SIL.XForge.Scripture/ClientApp/src/xforge-common/beta-migration/beta-migration.component.ts, line 72 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/1018#-MYOMfcg2s76eSfpDes8:-MYRKoPwAOsi2YBcx4B2:b-h16c0y) ([raw file](https://github.com/sillsdev/web-xforge/blob/45185c31d191ff900dc83e48cec53b62943089fd/src/SIL.XForge.Scripture/ClientApp/src/xforge-common/beta-migration/beta-migration.component.ts#L72)):*
<details><summary><i>Previously, nigel-wells (Nigel Wells) wrote…</i></summary><blockquote>

Yes I had received an error (warning?) when it was the other way around. Thinking about it now I think I tried switching them at the same time I moved the `onlineInvoke` call to happen prior to clearing data - which of course failed to authenticate with the bankend when there was no access token any more to use! It could very well work fine the other way around the same as the `auth-service.ts` file has them.
</blockquote></details>

Have switching them around and still works fine so have pushed it through.

**Review by irahopkinson — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1018#-:-MYT6t9A1tbE7PxkJAwB:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @nigel-wells)

**Pull request merged**
