### PR TITLE
SF-1320a Detect when project data is out of sync with the hg repo

### PR DESCRIPTION
**Pull request by RaymondLuong3**
* compare the data version to the version of the hg repo
* if out of sync, skip pushing any changes
* do not allow editing text in a project that is out of sync
* add method to Paratext service to report the hg repo revision

Out_of_sync_warning

---
This change is [Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1039)

### CODE REVIEW

**Comment by marksvc** [comment]
:eyes:

**Review by marksvc — CHANGES_REQUESTED** [review]
I have so far just examined the C# files.

> Reviewed 9 of 14 files at r1.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1039#-:-M_blSMO5ongURVHqwUF:b2ecbhq)* status: 9 of 14 files reviewed, 6 unresolved discussions (waiting on @RaymondLuong3)

___
*[src/RealtimeServer/scriptureforge/models/sync.ts, line 6 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/1039#-M_awxP47Lb_rJ2zWhkL:-M_awxP47Lb_rJ2zWhkM:b-mluiip) ([raw file](https://github.com/sillsdev/web-xforge/blob/38e2ea902a1af673f074c496814a1d1feb41e5ff/src/RealtimeServer/scriptureforge/models/sync.ts#L6)):*
> ```XML
>   lastSyncSuccessful?: boolean;
>   dateLastSuccessfulSync?: string;
>   dataInSync?: boolean;
> ```

How about a comment, like 

/** PT project data from the last Send/Receive operation was incorporated into the SF project docs. */

This will be true: The latest PT project data in the local repo was incorporated into the SF project.
This will be true: PT project data from the revision specified in Sync.SyncedToRepositoryVersion , was incorporated into the SF project.

After doing a synchronize, one could edit SF project text docs, and so in a sense the SF project's data would no longer be "in sync" with the PT project. 
And there could be remote changes by PT users that we have not fetched yet, and so we aren't "in sync" in that sense. 
But we can be "in sync" in the sense that the SF data has absorbed everything from PT that our local PT repo knows about.
___
*[src/SIL.XForge.Scripture/Models/Sync.cs, line 11 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/1039#-M_axSoi9z_3Ibia5B3v:-M_axSoi9z_3Ibia5B3w:b-3f0ei) ([raw file](https://github.com/sillsdev/web-xforge/blob/38e2ea902a1af673f074c496814a1d1feb41e5ff/src/SIL.XForge.Scripture/Models/Sync.cs#L11)):*
> ```Smalltalk
>         public bool? LastSyncSuccessful { get; set; }
>         public DateTime? DateLastSuccessfulSync { get; set; }
>         public string SyncedToRepositoryVersion { get; set; }
> ```

This may be obvious now, but let's put in a comment for our future selves. Maybe something like

/// <summary>
/// The SF project was last successfully synchronized with PT project data at this PT project repository commit on the PT project repo server.
/// </summary>

That's wordy, but I think it contains a picture of what happened, and answers some questions one might have about what's meant here.

I noticed that you sometimes use the terminology "shared revision", and I think by that you are meaning a commit that is "public", and so one that is on the remote PT repo server. "shared" is being used to mean "mutually held" or "mutually known". I think 'shared' can be a bit confusing; it might be interpreted to mean something that SF has and sends out (which would be a "shared revision", but commits on the PT repo server wouldn't be included in the definition).
The wordy "on the PT project repo server" makes it very clear that the revision in question is one that is also on the server.
___
*[src/SIL.XForge.Scripture/Services/HgWrapper.cs, line 31 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/1039#-M_b4Q5I2SpzYHfRPWx1:-M_b4Q5I2SpzYHfRPWx2:b-y5rbne) ([raw file](https://github.com/sillsdev/web-xforge/blob/38e2ea902a1af673f074c496814a1d1feb41e5ff/src/SIL.XForge.Scripture/Services/HgWrapper.cs#L31)):*
> ```Smalltalk
>         }
> 
>         public static string GetLastPublicRevision(string repository)
> ```

I think this will benefit from some explanation. How about

/// <summary>
/// Most recent revision id of a commit from the last push or pull with the PT repo server.
/// </summary>

Would it ever be that we would pull from the repo server, but not checkout that commit? And so the commit of the last pull may not match the commit that is currently checked out? Maybe this would only happen if SendReceive() itself failed, or we did something manually via SSH?
___
*[src/SIL.XForge.Scripture/Services/ParatextService.cs, line 611 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/1039#-M_b66RtAiV-4GwIZFGt:-M_b66RtAiV-4GwIZFGu:b-iuycvj) ([raw file](https://github.com/sillsdev/web-xforge/blob/38e2ea902a1af673f074c496814a1d1feb41e5ff/src/SIL.XForge.Scripture/Services/ParatextService.cs#L611)):*
> ```
> GetLatestSharedVersion
> ```

Hmm. I wonder if I don't understand the intent of the naming here. 

~~Might this communicate better if it was named something like GetProjectRepositoryRevision(). Or GetRevisionOfProjectRepository(). ?~~

Now that I'm getting a bit more familiar with the terminology that is being used, I think we could leave the method name as is, but give an explanatory comment. Perhaps similar to my recommendation for the GetLastPublicRevision() method, such as:

/// <summary>
/// Most recent revision id of a commit from the last push or pull with the PT repo server. 
/// </summary>
___
*[test/SIL.XForge.Scripture.Tests/Services/ParatextServiceTests.cs, line 755 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/1039#-M_bkoaF2KzXjAXaonSj:-M_bkoaF2KzXjAXaonSk:b-z83png) ([raw file](https://github.com/sillsdev/web-xforge/blob/38e2ea902a1af673f074c496814a1d1feb41e5ff/test/SIL.XForge.Scripture.Tests/Services/ParatextServiceTests.cs#L755)):*
> ```Smalltalk
>                 Service.ScrTextCollection = MockScrTextCollection;
>                 Service.SharingLogicWrapper = MockSharingLogicWrapper;
>                 Service.HgHelper = MockHgWrapper;
> ```

(There might be more to do here? What's with the Wrapper to Helper change?)
___
*[test/SIL.XForge.Scripture.Tests/Services/ParatextSyncRunnerTests.cs, line 39 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/1039#-M_bHoHe7XNKIoFg-THA:-M_bHoHe7XNKIoFg-THB:b3sneqn) ([raw file](https://github.com/sillsdev/web-xforge/blob/38e2ea902a1af673f074c496814a1d1feb41e5ff/test/SIL.XForge.Scripture.Tests/Services/ParatextSyncRunnerTests.cs#L39)):*
> ```Smalltalk
>             await env.Runner.RunAsync("project01", "user03", false);
>             env.VerifyProjectSync(false);
>         }
> ```

How about also here Assert.That(project.Sync.DataInSync, Is.True); ?

**Review by marksvc — CHANGES_REQUESTED** [review]
> Reviewed 5 of 14 files at r1.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1039)* status: all files reviewed, 8 unresolved discussions (waiting on @RaymondLuong3)

___
*[src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.spec.ts, line 750 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/1039#-M_fbgum17fZ7SMYIq9j:-M_fbgunCFIgyqj-gHBd:b-v0pj6j) ([raw file](https://github.com/sillsdev/web-xforge/blob/38e2ea902a1af673f074c496814a1d1feb41e5ff/src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.spec.ts#L750)):*
> ```XML
>       env.setDataInSync('project01', false);
>       expect(env.component.canEdit).toBe(false);
>       expect(env.outOfSyncWarning).not.toBeNull();
> ```

Let's expect the opposite of this above the setDataInSync() line. 
___
*[src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.spec.ts, line 1443 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/1039#-M_fcWm3B-lykujo9725:-M_fcWm3B-lykujo9726:b-8l9bj8) ([raw file](https://github.com/sillsdev/web-xforge/blob/38e2ea902a1af673f074c496814a1d1feb41e5ff/src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.spec.ts#L1443)):*
> ```
> !
> ```

It required a ! for dataInSync here?

**Review by RaymondLuong3 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1039)* status: 8 of 14 files reviewed, 8 unresolved discussions (waiting on @marksvc)

___
*[src/RealtimeServer/scriptureforge/models/sync.ts, line 6 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/1039#-M_awxP47Lb_rJ2zWhkL:-M_fy1NJCY3NuEwmfJCy:bvtqsgd) ([raw file](https://github.com/sillsdev/web-xforge/blob/38e2ea902a1af673f074c496814a1d1feb41e5ff/src/RealtimeServer/scriptureforge/models/sync.ts#L6)):*
<details><summary><i>Previously, marksvc wrote…</i></summary><blockquote>

How about a comment, like 

/** PT project data from the last Send/Receive operation was incorporated into the SF project docs. */

This will be true: The latest PT project data in the local repo was incorporated into the SF project.
This will be true: PT project data from the revision specified in Sync.SyncedToRepositoryVersion , was incorporated into the SF project.

After doing a synchronize, one could edit SF project text docs, and so in a sense the SF project's data would no longer be "in sync" with the PT project. 
And there could be remote changes by PT users that we have not fetched yet, and so we aren't "in sync" in that sense. 
But we can be "in sync" in the sense that the SF data has absorbed everything from PT that our local PT repo knows about.


</blockquote></details>

In sync means that our sf data is aware and has absorbed the data in the local project hg repo. I've added the comment.
___
*[src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.spec.ts, line 750 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/1039#-M_fbgum17fZ7SMYIq9j:-M_fz-nI4Fxr-OOWMRrC:b-896fix) ([raw file](https://github.com/sillsdev/web-xforge/blob/38e2ea902a1af673f074c496814a1d1feb41e5ff/src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.spec.ts#L750)):*
<details><summary><i>Previously, marksvc wrote…</i></summary><blockquote>

Let's expect the opposite of this above the setDataInSync() line. 
</blockquote></details>

Done.
___
*[src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.spec.ts, line 1443 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/1039#-M_fcWm3B-lykujo9725:-M_fz0XI2nL4XLpDTKjE:b-blz59p) ([raw file](https://github.com/sillsdev/web-xforge/blob/38e2ea902a1af673f074c496814a1d1feb41e5ff/src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.spec.ts#L1443)):*
<details><summary><i>Previously, marksvc wrote…</i></summary><blockquote>

> ```
> !
> ```

It required a ! for dataInSync here?
</blockquote></details>

Since dataInSync can be a string or undefined, here I assert that I am setting a property of the string type. At least that's what intellisense tells me.
___
*[src/SIL.XForge.Scripture/Models/Sync.cs, line 11 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/1039#-M_axSoi9z_3Ibia5B3v:-M_fzNIt165wQyh-tDfY:bdmwwgo) ([raw file](https://github.com/sillsdev/web-xforge/blob/38e2ea902a1af673f074c496814a1d1feb41e5ff/src/SIL.XForge.Scripture/Models/Sync.cs#L11)):*
<details><summary><i>Previously, marksvc wrote…</i></summary><blockquote>

This may be obvious now, but let's put in a comment for our future selves. Maybe something like

/// <summary>
/// The SF project was last successfully synchronized with PT project data at this PT project repository commit on the PT project repo server.
/// </summary>

That's wordy, but I think it contains a picture of what happened, and answers some questions one might have about what's meant here.

I noticed that you sometimes use the terminology "shared revision", and I think by that you are meaning a commit that is "public", and so one that is on the remote PT repo server. "shared" is being used to mean "mutually held" or "mutually known". I think 'shared' can be a bit confusing; it might be interpreted to mean something that SF has and sends out (which would be a "shared revision", but commits on the PT repo server wouldn't be included in the definition).
The wordy "on the PT project repo server" makes it very clear that the revision in question is one that is also on the server.


</blockquote></details>

I like the term send/receive server. That is the wording in Paratext for the server.
___
*[src/SIL.XForge.Scripture/Services/HgWrapper.cs, line 31 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/1039#-M_b4Q5I2SpzYHfRPWx1:-M_fzVSN0jP7ap61UVWI:b-v4cbu1) ([raw file](https://github.com/sillsdev/web-xforge/blob/38e2ea902a1af673f074c496814a1d1feb41e5ff/src/SIL.XForge.Scripture/Services/HgWrapper.cs#L31)):*
<details><summary><i>Previously, marksvc wrote…</i></summary><blockquote>

I think this will benefit from some explanation. How about

/// <summary>
/// Most recent revision id of a commit from the last push or pull with the PT repo server.
/// </summary>

Would it ever be that we would pull from the repo server, but not checkout that commit? And so the commit of the last pull may not match the commit that is currently checked out? Maybe this would only happen if SendReceive() itself failed, or we did something manually via SSH?


</blockquote></details>

It is possible if we explicitly change the commit that we have checked out. I suppose an error could happen in mercurial itself that prevents us from updating to the 'tip' revision. May be quite an edge case.
___
*[src/SIL.XForge.Scripture/Services/ParatextService.cs, line 611 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/1039#-M_b66RtAiV-4GwIZFGt:-M_g-FI77yIgUezjSXpV:b-896fix) ([raw file](https://github.com/sillsdev/web-xforge/blob/38e2ea902a1af673f074c496814a1d1feb41e5ff/src/SIL.XForge.Scripture/Services/ParatextService.cs#L611)):*
<details><summary><i>Previously, marksvc wrote…</i></summary><blockquote>

> ```
> GetLatestSharedVersion
> ```

Hmm. I wonder if I don't understand the intent of the naming here. 

~~Might this communicate better if it was named something like GetProjectRepositoryRevision(). Or GetRevisionOfProjectRepository(). ?~~

Now that I'm getting a bit more familiar with the terminology that is being used, I think we could leave the method name as is, but give an explanatory comment. Perhaps similar to my recommendation for the GetLastPublicRevision() method, such as:

/// <summary>
/// Most recent revision id of a commit from the last push or pull with the PT repo server. 
/// </summary>
</blockquote></details>

Done.
___
*[test/SIL.XForge.Scripture.Tests/Services/ParatextServiceTests.cs, line 755 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/1039#-M_bkoaF2KzXjAXaonSj:-M_g-G2-8tiVAlCpZlvq:bdi9tq5) ([raw file](https://github.com/sillsdev/web-xforge/blob/38e2ea902a1af673f074c496814a1d1feb41e5ff/test/SIL.XForge.Scripture.Tests/Services/ParatextServiceTests.cs#L755)):*
<details><summary><i>Previously, marksvc wrote…</i></summary><blockquote>

(There might be more to do here? What's with the Wrapper to Helper change?)
</blockquote></details>

HgWrapper has static methods we can call. There is a name collision in ParatextService when we name a property HgWrapper.
___
*[test/SIL.XForge.Scripture.Tests/Services/ParatextSyncRunnerTests.cs, line 39 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/1039#-M_bHoHe7XNKIoFg-THA:-M_g01Mm8hmnn3dEhp4Q:b-896fix) ([raw file](https://github.com/sillsdev/web-xforge/blob/38e2ea902a1af673f074c496814a1d1feb41e5ff/test/SIL.XForge.Scripture.Tests/Services/ParatextSyncRunnerTests.cs#L39)):*
<details><summary><i>Previously, marksvc wrote…</i></summary><blockquote>

How about also here Assert.That(project.Sync.DataInSync, Is.True); ?
</blockquote></details>

Done.

**Review by marksvc — APPROVED** [review]
Thanks for your work on this. I also tested it locally. I posted the details in the issue. It looks like it's doing what the PR intends.

> Reviewed 6 of 6 files at r2.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1039#-:-M_gBkCwD51WfOjMRKbf:b-z22rzg)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @RaymondLuong3)

___
*[src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.spec.ts, line 1443 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/1039#-M_fcWm3B-lykujo9725:-M_g9eUf6VeNQ8SOHRCd:bavx84e) ([raw file](https://github.com/sillsdev/web-xforge/blob/38e2ea902a1af673f074c496814a1d1feb41e5ff/src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.spec.ts#L1443)):*
<details><summary><i>Previously, RaymondLuong3 (Raymond Luong) wrote…</i></summary><blockquote>

Since dataInSync can be a string or undefined, here I assert that I am setting a property of the string type. At least that's what intellisense tells me.
</blockquote></details>

Hmm, ok, thanks.
___
*[src/SIL.XForge.Scripture/Models/Sync.cs, line 11 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/1039#-M_axSoi9z_3Ibia5B3v:-M_gA0Io175FR5qKDupg:b-vs1pr4) ([raw file](https://github.com/sillsdev/web-xforge/blob/38e2ea902a1af673f074c496814a1d1feb41e5ff/src/SIL.XForge.Scripture/Models/Sync.cs#L11)):*
<details><summary><i>Previously, RaymondLuong3 (Raymond Luong) wrote…</i></summary><blockquote>

I like the term send/receive server. That is the wording in Paratext for the server.
</blockquote></details>

Looks good.

**Comment by marksvc** [comment]
:ship:

**Pull request merged**
