### PR TITLE
SF-1165a Update sharedb beta to prepare for future upgrade

### PR DESCRIPTION
**Pull request by RaymondLuong3**
In order to upgrade to sharedb v1.0.0 from the beta sharedb, we need to update to v1.0.0-beta.31 and allow users' browsers to update. This beta will be forward compatible to the v1.0.0 release. See [sharedb beta client compatibility](https://github.com/share/sharedb/wiki/Upgrading-to-sharedb@1.0.0-from-1.0.0-beta#beta-client-compatibility)

---
This change is [Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/897)

### CODE REVIEW

**Review by irahopkinson — CHANGES_REQUESTED** [review]
Sorry about the other files because I reset `master`. You'll need to move this branch.

> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/897#-:-MOpLuurEgNLkMbL7f1P:bqyqut7)* status: 1 of 24 files reviewed, 1 unresolved discussion (waiting on @RaymondLuong3)

___
*[src/SIL.XForge.Scripture/ClientApp/package.json, line 68 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/897#-MOpKr4r72R7H3jFgGbB:-MOpKr4r72R7H3jFgGbC:b-ei8yu7) ([raw file](https://github.com/sillsdev/web-xforge/blob/1d038409349e9ef638b919415982393301204418/src/SIL.XForge.Scripture/ClientApp/package.json#L68)):*
> ```
> "sharedb": "^1.0.0-beta.31",
> ```
This change is not sufficient. It is used in the realtime server as well, run `npm list sharedb` to see. See my earlier Slack message about how to properly update both. And you should have corresponding `package-lock.json` file changes as well which you should have if you had installed and tested this change. You also should check what other related items might need updating as well by looking through the changelog from sharedb v1.0.0-beta.23 onwards.

**Review by RaymondLuong3 — COMMENTED** [review]
No problem. It's sorted out now.

> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/897#-:-MOqvMv9CsPqiJk041El:b-y0dtb9)* status: 0 of 4 files reviewed, 1 unresolved discussion (waiting on @irahopkinson)

___
*[src/SIL.XForge.Scripture/ClientApp/package.json, line 68 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/897#-MOpKr4r72R7H3jFgGbB:-MOqvQ5C3zEeEe8Ar5nb:b-6vmoe4) ([raw file](https://github.com/sillsdev/web-xforge/blob/1d038409349e9ef638b919415982393301204418/src/SIL.XForge.Scripture/ClientApp/package.json#L68)):*
<details><summary><i>Previously, irahopkinson (Ira Hopkinson) wrote…</i></summary><blockquote>

> ```
> "sharedb": "^1.0.0-beta.31",
> ```
This change is not sufficient. It is used in the realtime server as well, run `npm list sharedb` to see. See my earlier Slack message about how to properly update both. And you should have corresponding `package-lock.json` file changes as well which you should have if you had installed and tested this change. You also should check what other related items might need updating as well by looking through the changelog from sharedb v1.0.0-beta.23 onwards.
</blockquote></details>

Thanks for the tip. I wondered why it didn't seem to have affected the lock file. I notice now that in the lock file the version of sharedb is 1.5.2 but I expected to see 1.0.0-beta.31. I tested and everything seems to work. I will see if I can figure our what is going on.

**Review by RaymondLuong3 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/897)* status: 0 of 4 files reviewed, 1 unresolved discussion (waiting on @irahopkinson)

___
*[src/SIL.XForge.Scripture/ClientApp/package.json, line 68 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/897#-MOpKr4r72R7H3jFgGbB:-MOr6ubtE9UmvTkswKf0:b-cxmnra) ([raw file](https://github.com/sillsdev/web-xforge/blob/1d038409349e9ef638b919415982393301204418/src/SIL.XForge.Scripture/ClientApp/package.json#L68)):*
<details><summary><i>Previously, RaymondLuong3 (Raymond Luong) wrote…</i></summary><blockquote>

Thanks for the tip. I wondered why it didn't seem to have affected the lock file. I notice now that in the lock file the version of sharedb is 1.5.2 but I expected to see 1.0.0-beta.31. I tested and everything seems to work. I will see if I can figure our what is going on.
</blockquote></details>

Ok, I explicitly set the version to 1.0.0-beta.31, and in my testing the update just worked. From the sharedb changelog, it doesn't appear that any breaking changes were made.

**Comment by RaymondLuong3** [comment]
Anyone available should take up this issue so that we can ship it to users in preparation for upgrading to sharedb v1.0.0.

**Review by irahopkinson — CHANGES_REQUESTED** [review]
> Reviewed 6 of 7 files at r2, 3 of 3 files at r3.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/897)* status: all files reviewed, 1 unresolved discussion (waiting on @RaymondLuong3)

___
*[src/SIL.XForge.Scripture/ClientApp/package-lock.json, line 0 at r3](https://reviewable.io/reviews/sillsdev/web-xforge/897#-MQyqb2h6xYOTq-7qwI0:-MQyqb2h6xYOTq-7qwI1:b-pwaovw) ([raw file](https://github.com/sillsdev/web-xforge/blob/73a3eeddc89677686a5bb98c7b2c553c722f1dbc/src/SIL.XForge.Scripture/ClientApp/package-lock.json#L0)):*
This file needs updating after the rebase. `npm i` in each folder and then `npm install realtime-server` in the `ClientApp` folder.

**Review by irahopkinson — APPROVED** [review]
:lgtm:

> Reviewed 1 of 4 files at r4, 3 of 3 files at r5.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/897#-:-MQyuPqODTUYgXO5VdU7:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved

___
*[src/SIL.XForge.Scripture/ClientApp/package-lock.json, line  at r3](https://reviewable.io/reviews/sillsdev/web-xforge/897#-MQyqb2h6xYOTq-7qwI0:-MQyuMSLAeGLrs93ZQYx:bb6un1j) ([raw file](https://github.com/sillsdev/web-xforge/blob/73a3eeddc89677686a5bb98c7b2c553c722f1dbc/src/SIL.XForge.Scripture/ClientApp/package-lock.json#L)):*
<details><summary><i>Previously, irahopkinson (Ira Hopkinson) wrote…</i></summary><blockquote>

This file needs updating after the rebase. `npm i` in each folder and then `npm install realtime-server` in the `ClientApp` folder.
</blockquote></details>

Done

**Pull request merged**
