### PR TITLE
Add some nullable annotations

### PR DESCRIPTION
**Pull request by marksvc**
**Stack**:
- #1521
- #1520 ⮜

⚠️ *Part of a stack created by [spr](https://github.com/ejoffe/spr). Do not merge manually using the UI - doing so may have unexpected results.*

- - -
This change is [Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1520)

### CODE REVIEW

**Review by RaymondLuong3 — APPROVED** [review]
> Reviewed 9 of 9 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1520)* status: all files reviewed, 1 unresolved discussion (waiting on @marksvc)

___
*[`src/SIL.XForge.Scripture/Services/JwtTokenHelper.cs` line 27 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/1520#-NDUatRiBfrAWnSMIZjJ:-NDUatRiBfrAWnSMIZjK:bgtro8o) ([raw file](https://github.com/sillsdev/web-xforge/blob/aa03439b3de15a0ca0a43c18fc7a809629364ae7/src/SIL.XForge.Scripture/Services/JwtTokenHelper.cs#L27)):*
> ```Smalltalk
> 
>         /// <summary> Get the Paratext username from the access token stored in the UserSecret. </summary>
>         public string? GetParatextUsername(UserSecret userSecret)
> ```

This makes it explicit whether a string is nullable? Is that correct. So in this case, the Paratext Username can be null.



_Code quote:_
```Smalltalk
 public string? GetParatextUsername(UserSecret userSecret)
```

**Review by Nateowami — COMMENTED** [review]
> Reviewed 4 of 4 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1520)* status: all files reviewed, 1 unresolved discussion (waiting on @marksvc)

**Comment by Nateowami** [comment]
@marksvc And just after merging I realized this was created with spr and wasn't supposed to be merged.

**Review by marksvc — COMMENTED** [review]
@nateowami Actually in this case it is fine. The second PR in the series was dependent on this one being merged first, but they weren't associated in such a way that they should be merged together, or not merged until all reviewed. 

> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1520#-:-NEbOazwCto69kmMJk4C:b-3paip)* status: all files reviewed, 1 unresolved discussion

___
*[`src/SIL.XForge.Scripture/Services/JwtTokenHelper.cs` line 27 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/1520#-NDUatRiBfrAWnSMIZjJ:-NEbO2qL6sXGiMU54T5N:b-rt2elv) ([raw file](https://github.com/sillsdev/web-xforge/blob/aa03439b3de15a0ca0a43c18fc7a809629364ae7/src/SIL.XForge.Scripture/Services/JwtTokenHelper.cs#L27)):*
<details><summary><i>Previously, RaymondLuong3 (Raymond Luong) wrote…</i></summary><blockquote>

This makes it explicit whether a string is nullable? Is that correct. So in this case, the Paratext Username can be null.
</blockquote></details>

Right! So type `string` means it will be a string but not null, and `string?` means it could be either a string or null.
The method returns `null` if, say, `userSecret == null`, and so we can specify that `GetParatextUsername()` returns `string?` to help callers know what to do with the potentially-null result.

**Pull request merged**
