### PR TITLE
SF-1743c sync: ensure correct revision is checked out when sync starts

### PR DESCRIPTION
**Pull request by marksvc**
- The SF synchronize process records if 'DataInSync' at the end. The
next time SF synchronizes, it considers 'DataInSync' as part of
determining if it is safe to write data. If SF is abruptly terminated
during synchronize, we may not set 'DataInSync' to false when we would
have, resulting in the next sync incorrectly thinking it can safely
write data.
- This commit changes the behaviour. At the beginning of each
synchronize, set the local hg repository to the revision that we know
we last successfully imported from, and consider that we are always
'in sync', and so can safely write data. This is to make the
synchronize process more resilient against problems that occur during
its operation.
- The current hg repo revision is now being logged, in addition to the
latest shared/public revision, to identify possible problems in how we
use these.

- - -
This change is [Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1521)

### CODE REVIEW

**Review by RaymondLuong3 — CHANGES_REQUESTED** [review]
Essentially, we set the local hg repo to where we know we have synchronized to, so even if we crash before we commit changes to the text docs (any becoming out of sync), we still always write data to the repo before send/receive, and this is ok because as long as the base is the expected one, Paratext will be able to merge local changes during send/receives so that we never get into the scenario of accidentally overwrite data. Is that correct.

> Reviewed 7 of 7 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1521#-:-NEl3iErCTvSIXHn0pfx:b8p3l9r)* status: all files reviewed, 9 unresolved discussions (waiting on @marksvc)

___
*[`src/SIL.XForge.Scripture/Services/HgWrapper.cs` line 120 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/1521#-NEl6mhy7TvbvDWRuvA2:-NEl6mhy7TvbvDWRuvA3:b-3c2x95) ([raw file](https://github.com/sillsdev/web-xforge/blob/9f5006768b1110da55a5e23440b556bc2cb62c3f/src/SIL.XForge.Scripture/Services/HgWrapper.cs#L120)):*
> ```Smalltalk
>         public void Update(string repositoryPath, string rev)
>         {
>             Hg.Default.Update(repositoryPath, rev);
> ```

This will update even if there are uncommitted changes, is that correct?



_Code quote:_
```Smalltalk
            Hg.Default.Update(repositoryPath, rev);
```
___
*[`src/SIL.XForge.Scripture/Services/ParatextService.cs` line 1333 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/1521#-NEl7Px08kM56Iu6fPE8:-NEl7Px08kM56Iu6fPE9:b1vs4ae) ([raw file](https://github.com/sillsdev/web-xforge/blob/9f5006768b1110da55a5e23440b556bc2cb62c3f/src/SIL.XForge.Scripture/Services/ParatextService.cs#L1333)):*
> ```Smalltalk
>         }
> 
>         /// <summary>Returns the currently revision of the hg repo that a user accesses for a project PT id.</summary>
> ```

Maybe a better name is Returns the current revision of the local hg repo for a given project id.



_Code quote:_
```Smalltalk
mary>Returns the currently revision of the hg repo that a user accesses for a project PT id.
```
___
*[`src/SIL.XForge.Scripture/Services/ParatextService.cs` line 1338 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/1521#-NEl7nHtBkYsnYhi9gxS:-NEl7nHtBkYsnYhi9gxT:b-dr6091) ([raw file](https://github.com/sillsdev/web-xforge/blob/9f5006768b1110da55a5e23440b556bc2cb62c3f/src/SIL.XForge.Scripture/Services/ParatextService.cs#L1338)):*
> ```Smalltalk
>             if (IsResource(projectPTId))
>             {
>                 throw new InvalidOperationException("Can not query a resource for an hg repo revision.");
> ```

Is this because the hg repo is different than a project repo?
Typo: Cannot is one word.



_Code quote:_
```Smalltalk
"Can not query a resource for an hg repo revision.")
```
___
*[`src/SIL.XForge.Scripture/Services/ParatextService.cs` line 1349 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/1521#-NEl89Zp0hJbH46LPImp:-NEl89Zp0hJbH46LPImq:b-uh4lge) ([raw file](https://github.com/sillsdev/web-xforge/blob/9f5006768b1110da55a5e23440b556bc2cb62c3f/src/SIL.XForge.Scripture/Services/ParatextService.cs#L1349)):*
> ```Smalltalk
>             if (IsResource(projectPTId))
>             {
>                 throw new InvalidOperationException("Can not query a resource for an hg repo revision.");
> ```

Typo: Cannot is one word.



_Code quote:_
```Smalltalk
         throw new InvalidOperationException("Can not query a resource for an hg repo revision.");
```
___
*[`src/SIL.XForge.Scripture/Services/ParatextService.cs` line 1359 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/1521#-NEl8M-8A914oAIaAR9M:-NEl8M-8A914oAIaAR9N:bbmv7o2) ([raw file](https://github.com/sillsdev/web-xforge/blob/9f5006768b1110da55a5e23440b556bc2cb62c3f/src/SIL.XForge.Scripture/Services/ParatextService.cs#L1359)):*
> ```Smalltalk
>             {
>                 throw new Exception(
>                     $"SetRepoToRevision failed to set repo for project PT id {projectPTId} to revision {desiredRevision}, as resulting revision is {currentRepoRev}."
> ```

Do you mean "the" resulting revision?



_Code quote:_
```Smalltalk
}, as resulting revision 
```
___
*[`src/SIL.XForge.Scripture/Services/ParatextSyncRunner.cs` line 49 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/1521#-NEl9LoOD80tUU__2Hk7:-NEl9LoOD80tUU__2Hk8:b-4fwmme) ([raw file](https://github.com/sillsdev/web-xforge/blob/9f5006768b1110da55a5e23440b556bc2cb62c3f/src/SIL.XForge.Scripture/Services/ParatextSyncRunner.cs#L49)):*
> ```Smalltalk
>     /// where data is coming from or going to when fetching or syncing.
>     /// <code>
>     /// Diagram showing a high-level look at the order of data being transmitted:
> ```

Nice diagram :)



_Code quote:_
```Smalltalk
   /// Diagram showing a high-level look at the order of data being transmitted:
```
___
*[`src/SIL.XForge.Scripture/Services/ParatextSyncRunner.cs` line 178 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/1521#-NElA3JxB0SBWyrG_N9U:-NElA3JxB0SBWyrG_N9V:brigeou) ([raw file](https://github.com/sillsdev/web-xforge/blob/9f5006768b1110da55a5e23440b556bc2cb62c3f/src/SIL.XForge.Scripture/Services/ParatextSyncRunner.cs#L178)):*
> ```Smalltalk
>                         $"Setting hg repo to last imported hg repo rev of {_projectDoc.Data.Sync.SyncedToRepositoryVersion}."
>                     );
>                     this._paratextService.SetRepoToRevision(
> ```

Nit: No need for `this`



_Code quote:_
```Smalltalk
this._paratextService
```
___
*[`src/SIL.XForge.Scripture/Services/ParatextSyncRunner.cs` line 1504 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/1521#-NElA_jo5rl5bu8Z51MG:-NElA_jo5rl5bu8Z51MH:b-2xy9xe) ([raw file](https://github.com/sillsdev/web-xforge/blob/9f5006768b1110da55a5e23440b556bc2cb62c3f/src/SIL.XForge.Scripture/Services/ParatextSyncRunner.cs#L1504)):*
> ```Smalltalk
>                 Log($"{prefix}In-sync info: Is resource. {dbInfo}");
>             }
>             else if (!this._paratextService.LocalProjectDirExists(projectPTId))
> ```

Nit: no need for `this`



_Code quote:_
```Smalltalk
this._paratextService.
```
___
*[`test/SIL.XForge.Scripture.Tests/Services/ParatextServiceTests.cs` line 3165 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/1521#-NElBJna621CYYhBl3zd:-NElBJna621CYYhBl3ze:ba35bht) ([raw file](https://github.com/sillsdev/web-xforge/blob/9f5006768b1110da55a5e23440b556bc2cb62c3f/test/SIL.XForge.Scripture.Tests/Services/ParatextServiceTests.cs#L3165)):*
> ```Smalltalk
>             string projectPTId = env.SetupProject(env.Project01, associatedPtUser);
>             string rev = "some-desired-revision";
>             env.MockHgWrapper.GetRepoRevision(Arg.Any<string>()).Returns(rev);
> ```

You could use the repository path instead of Arg.Any<string> if you want to be extra sure.



_Code quote:_
```Smalltalk
 env.MockHgWrapper.GetRepoRevision(Arg.Any<string>()).Returns(rev);
```

**Review by marksvc — COMMENTED** [review]
That's right. Each time we are going to synchronize data between SF and PT Archives, which happens thru the local hg repo, we first set the local hg repo to the known-good state. The known-good state is the state that it was in when we last imported from it. Because at the beginning of a Sync, the local hg repo is in the state that it was when we last imported from it, we will always start out our Sync as an  "in sync" situation, and can dump the SF DB text right into the local hg repo, which is effectively applying just SF changes. ParatextData.dll then uses hg to push the repo to PT Archives, and then it's up to PT Archives to decide how to merge and flag PT-conflicts. 

We'll find more things to fix, but I think this will be less likely to have problems.

> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1521#-:-NElGo0T4fc3obkZzqQo:bm2pg1b)* status: all files reviewed, 7 unresolved discussions (waiting on @RaymondLuong3)

___
*[`src/SIL.XForge.Scripture/Services/HgWrapper.cs` line 120 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/1521#-NEl6mhy7TvbvDWRuvA2:-NElJ-IE3TPpr9uhTVF9:b-ezkl53) ([raw file](https://github.com/sillsdev/web-xforge/blob/9f5006768b1110da55a5e23440b556bc2cb62c3f/src/SIL.XForge.Scripture/Services/HgWrapper.cs#L120)):*
Right. And the uncommitted, tracked changes will be discarded. The API doc says it "Does an update, using --clean option". 
The hg docs say of `hg update` `--clean`, 
> With the -C/--clean option, uncommitted changes are discarded and the working directory is updated to the requested changeset.

Here is an example:
```bash
$ hg status
M existing-file.txt
? new-file.txt
$ hg update --clean 'head()'
1 files updated, 0 files merged, 0 files removed, 0 files unresolved
$ hg status
? new-file.txt
```
In this example, we see that the changes to the modified file, `existing-file.txt`, were discarded. We also see that the untracked file, new-file.txt, was left alone and not removed. 

It may be worth also deleting untracked files. I suspect that the potential for a problem from that is low, but it may be a good thing to do in followup.
___
*[`src/SIL.XForge.Scripture/Services/ParatextService.cs` line 1333 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/1521#-NEl7Px08kM56Iu6fPE8:-NElM-054i4iA3yMGG_o:bhhpfct) ([raw file](https://github.com/sillsdev/web-xforge/blob/9f5006768b1110da55a5e23440b556bc2cb62c3f/src/SIL.XForge.Scripture/Services/ParatextService.cs#L1333)):*
<details><summary><i>Previously, RaymondLuong3 (Raymond Luong) wrote…</i></summary><blockquote>

Maybe a better name is Returns the current revision of the local hg repo for a given project id.
</blockquote></details>

Yes! I want to give a clue as to why  `userSecret` is one of the parameters. How about "Returns the current revision of the local hg repo for a given project PT id, accessed using a given user."?
___
*[`src/SIL.XForge.Scripture/Services/ParatextService.cs` line 1338 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/1521#-NEl7nHtBkYsnYhi9gxS:-NElOMNo7xU2gY0Gsi3U:bwrixjo) ([raw file](https://github.com/sillsdev/web-xforge/blob/9f5006768b1110da55a5e23440b556bc2cb62c3f/src/SIL.XForge.Scripture/Services/ParatextService.cs#L1338)):*
<details><summary><i>Previously, RaymondLuong3 (Raymond Luong) wrote…</i></summary><blockquote>

Is this because the hg repo is different than a project repo?
Typo: Cannot is one word.
</blockquote></details>

It's because a resource _isn't_ stored in a local hg repo! There is no .hg folder. I chose to make `GetRepoRevision()` reject requests for resources so that the method can always return a hg revision, rather than returning special case results.
___
*[`src/SIL.XForge.Scripture/Services/ParatextService.cs` line 1349 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/1521#-NEl89Zp0hJbH46LPImp:-NElP3gW1cGdBgse69kK:b-vuj8ut) ([raw file](https://github.com/sillsdev/web-xforge/blob/9f5006768b1110da55a5e23440b556bc2cb62c3f/src/SIL.XForge.Scripture/Services/ParatextService.cs#L1349)):*
<details><summary><i>Previously, RaymondLuong3 (Raymond Luong) wrote…</i></summary><blockquote>

Typo: Cannot is one word.
</blockquote></details>

Thank you :)
___
*[`src/SIL.XForge.Scripture/Services/ParatextService.cs` line 1359 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/1521#-NEl8M-8A914oAIaAR9M:-NElPGR_DeRltwIvIvts:b-896fix) ([raw file](https://github.com/sillsdev/web-xforge/blob/9f5006768b1110da55a5e23440b556bc2cb62c3f/src/SIL.XForge.Scripture/Services/ParatextService.cs#L1359)):*
<details><summary><i>Previously, RaymondLuong3 (Raymond Luong) wrote…</i></summary><blockquote>

Do you mean "the" resulting revision?
</blockquote></details>

Done.
___
*[`src/SIL.XForge.Scripture/Services/ParatextSyncRunner.cs` line 49 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/1521#-NEl9LoOD80tUU__2Hk7:-NElPJBU09eaoKFbsrgp:b-vuj8ut) ([raw file](https://github.com/sillsdev/web-xforge/blob/9f5006768b1110da55a5e23440b556bc2cb62c3f/src/SIL.XForge.Scripture/Services/ParatextSyncRunner.cs#L49)):*
<details><summary><i>Previously, RaymondLuong3 (Raymond Luong) wrote…</i></summary><blockquote>

Nice diagram :)
</blockquote></details>

Thank you :)
___
*[`test/SIL.XForge.Scripture.Tests/Services/ParatextServiceTests.cs` line 3165 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/1521#-NElBJna621CYYhBl3zd:-NElUHxt4BoTeYmOjwrH:b-jpslh8) ([raw file](https://github.com/sillsdev/web-xforge/blob/9f5006768b1110da55a5e23440b556bc2cb62c3f/test/SIL.XForge.Scripture.Tests/Services/ParatextServiceTests.cs#L3165)):*
<details><summary><i>Previously, RaymondLuong3 (Raymond Luong) wrote…</i></summary><blockquote>

You could use the repository path instead of Arg.Any<string> if you want to be extra sure.
</blockquote></details>

Done. I did the same to the following test as well, but then decided to leave it as is so that it more likely continues returning the specific bad value even if other parts of the system change (like if we we start using "blah" instead of "target" in the directory path).

**Review by RaymondLuong3 — APPROVED** [review]
How can we make it easy for the users to test this? In the past, I created a branch that contains code to make the sync fail in a particular way. Then I tell the testers to fail a sync using the branch. After the failure, I get the testers to checking out good branch. What do you think of that?

> Reviewed 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1521#-:-NEvkqlyEcMlkCHgtgtS:b-3nm09g)* status: all files reviewed, 2 unresolved discussions (waiting on @marksvc)

___
*[`src/SIL.XForge.Scripture/Services/HgWrapper.cs` line 120 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/1521#-NEl6mhy7TvbvDWRuvA2:-NEvlBHT9cpO373Ldup4:b-3jmj82) ([raw file](https://github.com/sillsdev/web-xforge/blob/9f5006768b1110da55a5e23440b556bc2cb62c3f/src/SIL.XForge.Scripture/Services/HgWrapper.cs#L120)):*
<details><summary><i>Previously, marksvc wrote…</i></summary><blockquote>

Right. And the uncommitted, tracked changes will be discarded. The API doc says it "Does an update, using --clean option". 
The hg docs say of `hg update` `--clean`, 
> With the -C/--clean option, uncommitted changes are discarded and the working directory is updated to the requested changeset.

Here is an example:
```bash
$ hg status
M existing-file.txt
? new-file.txt
$ hg update --clean 'head()'
1 files updated, 0 files merged, 0 files removed, 0 files unresolved
$ hg status
? new-file.txt
```
In this example, we see that the changes to the modified file, `existing-file.txt`, were discarded. We also see that the untracked file, new-file.txt, was left alone and not removed. 

It may be worth also deleting untracked files. I suspect that the potential for a problem from that is low, but it may be a good thing to do in followup.
</blockquote></details>

Nice, that is important that we can update to a new revision, even with a dirty working tree. I think the untracked files could be an issue, but right now I can't think of how. Maybe leave a comment that this does not clean up untracked files.
___
*[`src/SIL.XForge.Scripture/Services/ParatextService.cs` line 1333 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/1521#-NEl7Px08kM56Iu6fPE8:-NEvkMDq8vXbtMz1HY_c:b-83sjo4) ([raw file](https://github.com/sillsdev/web-xforge/blob/9f5006768b1110da55a5e23440b556bc2cb62c3f/src/SIL.XForge.Scripture/Services/ParatextService.cs#L1333)):*
<details><summary><i>Previously, marksvc wrote…</i></summary><blockquote>

Yes! I want to give a clue as to why  `userSecret` is one of the parameters. How about "Returns the current revision of the local hg repo for a given project PT id, accessed using a given user."?
</blockquote></details>

Nice.
___
*[`src/SIL.XForge.Scripture/Services/ParatextService.cs` line 1338 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/1521#-NEl7nHtBkYsnYhi9gxS:-NEvkQAe4F78ajVktwX0:bkddfm8) ([raw file](https://github.com/sillsdev/web-xforge/blob/9f5006768b1110da55a5e23440b556bc2cb62c3f/src/SIL.XForge.Scripture/Services/ParatextService.cs#L1338)):*
<details><summary><i>Previously, marksvc wrote…</i></summary><blockquote>

It's because a resource _isn't_ stored in a local hg repo! There is no .hg folder. I chose to make `GetRepoRevision()` reject requests for resources so that the method can always return a hg revision, rather than returning special case results.
</blockquote></details>

Ah, ok. I didn't know that. Great.
___
*[`test/SIL.XForge.Scripture.Tests/Services/ParatextServiceTests.cs` line 3165 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/1521#-NElBJna621CYYhBl3zd:-NEvkjj79GOHW7X2PXW2:b-83sjo4) ([raw file](https://github.com/sillsdev/web-xforge/blob/9f5006768b1110da55a5e23440b556bc2cb62c3f/test/SIL.XForge.Scripture.Tests/Services/ParatextServiceTests.cs#L3165)):*
<details><summary><i>Previously, marksvc wrote…</i></summary><blockquote>

Done. I did the same to the following test as well, but then decided to leave it as is so that it more likely continues returning the specific bad value even if other parts of the system change (like if we we start using "blah" instead of "target" in the directory path).
</blockquote></details>

Nice.

**Review by marksvc — COMMENTED** [review]
I put some more work into writing an acceptance tests to simulate the problem. I wrote a test that pulls content from ~/Paratext8Projects/... into the repo in /var/lib/scriptureforge/... . In this way, it simulates advancing SF's Paratext project repo, but without the content being imported into SF. 

Good point about using another branch. A similar test to the above can be done by having SF kill its process right after running SendReceive (and then Sync in SF again without having SF killing its process). I also wrote up how to do that. but I directed testers to the other method, which is something they should be able to do on future versions of SF without needing to use a then-old branch. These are written up in a jira comment.

> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1521#-:-NEwdjo57uVSumKSlSvj:b-2aeckg)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @marksvc)

___
*[`src/SIL.XForge.Scripture/Services/HgWrapper.cs` line 120 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/1521#-NEl6mhy7TvbvDWRuvA2:-NEw2jWmBtYk1-SO0R_Z:b-896fix) ([raw file](https://github.com/sillsdev/web-xforge/blob/9f5006768b1110da55a5e23440b556bc2cb62c3f/src/SIL.XForge.Scripture/Services/HgWrapper.cs#L120)):*
<details><summary><i>Previously, RaymondLuong3 (Raymond Luong) wrote…</i></summary><blockquote>

Nice, that is important that we can update to a new revision, even with a dirty working tree. I think the untracked files could be an issue, but right now I can't think of how. Maybe leave a comment that this does not clean up untracked files.
</blockquote></details>

Done.

**Comment by Nateowami** [comment]
@marksvc Can you change the commit message to something easier to understand than "set repo rev"? Maybe something about what problem is solved? When I read this I think "Wait, don't we already store the revision of the Paratext repo?" If the answer is "not always" then maybe the description should be something like "Fix repo revision not always being set during sync" or something.

**Comment by marksvc** [comment]
@Nateowami How about this one? Also, don't miss the "sync: " part of the commit message, which indicates what area this patch is for.

**Comment by marksvc** [comment]
@Nateowami That has advantages. Changing it to that.

**Review by Nateowami — COMMENTED** [review]
> Reviewed 1 of 1 files at r3, 4 of 4 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1521)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @marksvc)

**Pull request merged**
