### PR TITLE
SF-1233 Add offline video

### PR DESCRIPTION
**Pull request by irahopkinson**
- also lazy load images

@nigel-wells do you still have your copywriter to check this content?

image

---
This change is [Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/988)

### CODE REVIEW

**Review by nigel-wells — COMMENTED** [review]
Yes @irahopkinson I'll flick it through to Josh to take a look at.

> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/988#-:-MWLKNUp5uCeDNpH-2Yd:b-sbfq4u)* status: 0 of 5 files reviewed, all discussions resolved

**Review by nigel-wells — COMMENTED** [review]
Suggested wording from Josh:
1. Cut the title to just 'Working Offline' 
2. Consider chancing 'anyone' to 'users' in intro sentence so it's a bit more specific and on-theme. 
2b. I'd add a comma for more emphasis on offline in intro sentence: 'can keep working, even while offline' 
3. Is the 'online.' at end of first point actually meant to be 'offline'? 
4. Probably ad a comma to second point, 'Answering questions, including recording an audio answer while offline.' 
5. The 'to' language in third point feels odd to me. I'd go with 'Installing the app on your device'. 
6. Could potentially tidy up the last point by rewording to 'Automatically saving updated answers once you're back online.' 
7. Consider changing all instances of 'while offline' to 'when offline', or potentially removing the 'while' altogether in the instances where it could work (e.g., second point, 'Answering questions including recording an audio answer, offline', etc). 

> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/988#-:-MWMJ7Jn8UPfCxwW8Luq:b-pgy3wy)* status: 0 of 5 files reviewed, all discussions resolved

**Review by irahopkinson — COMMENTED** [review]
Thanks, I liked and made all those changes and updated the snapshot. On his item 3 it was meant to be 'online' so that means the intent was unclear, so I've reworded point 1.

> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/988#-:-MWMYm3gCbQu448lZ5fI:boxqiri)* status: 0 of 5 files reviewed, all discussions resolved

**Review by nigel-wells — APPROVED** [review]
> Reviewed 5 of 5 files at r1.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/988)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @irahopkinson)

**Pull request merged**
