### PR TITLE
Update all translation files from Crowdin

### PR DESCRIPTION
**Pull request by Nateowami**
This change is [Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/2462)

### CODE REVIEW

**Review by RaymondLuong3 — APPROVED** [review]
:lgtm:

> Reviewed 22 of 22 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/2462#-:-Ny7LlJA2jA_hW0QN1or:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @Nateowami)

___
*[`src/SIL.XForge.Scripture/ClientApp/src/assets/i18n/non_checking_ar.json` line 522 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/2462#-Ny7LwXb2O0dXdV2YGQh:-Ny7LwXc2Z5KZYuHCR3F:bthh5kw) ([raw file](https://github.com/sillsdev/web-xforge/blob/f1331c4f09acd5c6661ed6c870aed60b9562e850/src/SIL.XForge.Scripture/ClientApp/src/assets/i18n/non_checking_ar.json#L522)):*
> ```JSON
>     "trained_segments": "شرائح مُدرَّبة",
>     "training": "التدريب...",
>     "training_unavailable": "Training is temporary unavailable",
> ```

Not a blocker, but this typo should be fixed.



_Code quote:_
```JSON
    "training_unavailable": "Training is temporary unavailable",
```

**Comment by Nateowami** [comment]
@RaymondLuong3 Opened #2463 to fix the spelling.

**Comment by Nateowami** [comment]
Updated

**Review by pmachapman — APPROVED** [review]
:lgtm_strong: 

> Reviewed 1 of 2 files at r3, 11 of 11 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/2462#-:-NySDKo3C0AwFajIRDMh:b-uwkowd)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @Nateowami)

___
*[`src/SIL.XForge.Scripture/ClientApp/src/assets/i18n/checking_lo.json` line 29 at r3](https://reviewable.io/reviews/sillsdev/web-xforge/2462#gh-1608631530:-NySDfp0E2QT4a5z9gx0:bb6un1j) ([raw file](https://github.com/sillsdev/web-xforge/blob/aafa8f530bf0ad25fb28b141f49b121b806653d2/src/SIL.XForge.Scripture/ClientApp/src/assets/i18n/checking_lo.json#L29)):*
<details><summary><i>Previously, Nateowami (Nathaniel Paulus) wrote…</i></summary><blockquote>

Test team pointed out this problem.
</blockquote></details>

Done
___
*[`src/SIL.XForge.Scripture/ClientApp/src/assets/i18n/non_checking_ar.json` line 522 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/2462#-Ny7LwXb2O0dXdV2YGQh:-NySDcfb321ZgTuQ-wAS:bb6un1j) ([raw file](https://github.com/sillsdev/web-xforge/blob/f1331c4f09acd5c6661ed6c870aed60b9562e850/src/SIL.XForge.Scripture/ClientApp/src/assets/i18n/non_checking_ar.json#L522)):*
<details><summary><i>Previously, RaymondLuong3 (Raymond Luong) wrote…</i></summary><blockquote>

Not a blocker, but this typo should be fixed.
</blockquote></details>

Done

**Pull request merged**
