### PR TITLE
Cleanup after PR #804

### PR DESCRIPTION
**Pull request by irahopkinson**
* get issue email from environment
* fix up unneeded async
* add checkbox label tag and align vertically

**Note:** This change is non-functional and doesn't need merging until after the migration.

---
This change is [Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/806)

### CODE REVIEW

**Review by Nateowami — APPROVED** [review]
Just one suggestion, then :lgtm:

> Reviewed 6 of 6 files at r1.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/806#-:-MHQwVl4-nuZaRG0fxs9:b-5eid02)* status: all files reviewed, 1 unresolved discussion (waiting on @irahopkinson)

___
*[src/SIL.XForge.Scripture/ClientApp/src/assets/i18n/non_checking_en.json, line 166 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/806#-MHQy4sT93_4YFNbNA8t:-MHQy4sT93_4YFNbNA8u:b-tkksa7) ([raw file](https://github.com/sillsdev/web-xforge/blob/e24487117d6e0a6ee5a64e01a819d2f63a9080d8/src/SIL.XForge.Scripture/ClientApp/src/assets/i18n/non_checking_en.json#L166)):*
> ```JSON
>     "synchronize_project": "Synchronize {{ projectName }} with Paratext",
>     "your_project_is_being_synchronized": "Your project is being synchronized...",
>     "sync_is_disabled": "Synchronization for this project needed to be disabled, so it is not available at this time. Please contact {{ email }} to discuss what needs done so project synchronization can be enabled again."
> ```

How about changing "needs done" to "needs to be done"?

**Review by irahopkinson — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/806)* status: 5 of 6 files reviewed, all discussions resolved (waiting on @Nateowami)

___
*[src/SIL.XForge.Scripture/ClientApp/src/assets/i18n/non_checking_en.json, line 166 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/806#-MHQy4sT93_4YFNbNA8t:-MHR9k27DhzM9_Keg4WV:b-370f7b) ([raw file](https://github.com/sillsdev/web-xforge/blob/e24487117d6e0a6ee5a64e01a819d2f63a9080d8/src/SIL.XForge.Scripture/ClientApp/src/assets/i18n/non_checking_en.json#L166)):*
<details><summary><i>Previously, Nateowami (Nathaniel Paulus) wrote…</i></summary><blockquote>

How about changing "needs done" to "needs to be done"?
</blockquote></details>

Done. Thanks for that, I wanted to change it but thought it must have been some acceptable North American phrasing.

**Review by Nateowami — COMMENTED** [review]
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/806)* status: :shipit: complete! all files reviewed, all discussions resolved

___
*[src/SIL.XForge.Scripture/ClientApp/src/assets/i18n/non_checking_en.json, line 166 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/806#-MHQy4sT93_4YFNbNA8t:-MHRBGqyER-E2C6cJzvk:b-edemtc) ([raw file](https://github.com/sillsdev/web-xforge/blob/e24487117d6e0a6ee5a64e01a819d2f63a9080d8/src/SIL.XForge.Scripture/ClientApp/src/assets/i18n/non_checking_en.json#L166)):*
<details><summary><i>Previously, irahopkinson (Ira Hopkinson) wrote…</i></summary><blockquote>

Done. Thanks for that, I wanted to change it but thought it must have been some acceptable North American phrasing.
</blockquote></details>

It's common, but not correct (at least not in my opinion).

**Review by marksvc — APPROVED** [review]
I approve. Thanks for cleaning up after me :)

> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/806#-:-MHRYpSC8mC0vQ1tkZbj:b-rp72za)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
