### PR TITLE
Skip books during sync-all migration that cannot be cloned

### PR DESCRIPTION
**Pull request by RaymondLuong3**
Because it is not necessary to clone new books for the sync all migration step, books that cannot be cloned will be skipped over. These books will be safely added during the clone all migration step.

---
This change is [Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/798)

### CODE REVIEW

**Review by RaymondLuong3 — COMMENTED** [review]
I have made a comment on the code I have changed from `ParatextSyncRunner.cs`

> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/798#-:-MGtEC47AdREyBrZl9bY:benru73)* status: 0 of 2 files reviewed, all discussions resolved

___
*[src/Migrations/PtdaSyncAll/PtdaSyncRunner.cs, line 171 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/798#-MGtDpJ3EA8OwIxYdmM0:-MGtDpJ3EA8OwIxYdmM1:b4hptru) ([raw file](https://github.com/sillsdev/web-xforge/blob/88cf1d9044212ef92a3f19f71a8f94ae2d6ed1b5/src/Migrations/PtdaSyncAll/PtdaSyncRunner.cs#L171)):*
> ```
> if (newChapters != null)
> ```
This null check was added.
___
*[src/Migrations/PtdaSyncAll/PtdaSyncRunner.cs, line 253 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/798#-MGtE4zA0bPyEOhQX7WT:-MGtE4zA0bPyEOhQX7WU:b2u06rp) ([raw file](https://github.com/sillsdev/web-xforge/blob/88cf1d9044212ef92a3f19f71a8f94ae2d6ed1b5/src/Migrations/PtdaSyncAll/PtdaSyncRunner.cs#L253)):*
> ```
> try
> ```
This try/catch block was added.

**Review by marksvc — CHANGES_REQUESTED** [review]
I approve, minus comment. Thanks!

> Reviewed 2 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/798#-:-MGtUZ2R930ST8hHTdtx:bpkcg7w)* status: all files reviewed, 1 unresolved discussion (waiting on @RaymondLuong3)

___
*[src/Migrations/PtdaSyncAll/PtdaSyncRunner.cs, line 168 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/798#-MGtNNhE33xjwER9ShkV:-MGtNNhE33xjwER9ShkW:b-9jxp1j) ([raw file](https://github.com/sillsdev/web-xforge/blob/88cf1d9044212ef92a3f19f71a8f94ae2d6ed1b5/src/Migrations/PtdaSyncAll/PtdaSyncRunner.cs#L168)):*
> ```
> newChapters
> ```
This could throw a null dereference exception. Let's move the `if (newChapters !=null)` up above `if (hasSource)`. 
I see that would skip doing `SyncOrCloneBookUsxAsync(..,TextType.Source,...)` in the next line, but that should be okay since we don't allow editing the source/mother book text.

**Review by irahopkinson — APPROVED** [review]
Looks good but see my comment on the try/catch.

> Reviewed 3 of 5 files at r2, 2 of 2 files at r3.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/798#-:-MGwD2VO-jD8LDAQEYHY:b-anzqqo)* status: all files reviewed, 1 unresolved discussion (waiting on @marksvc)

___
*[src/Migrations/PtdaSyncAll/PtdaSyncRunner.cs, line 168 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/798#-MGtNNhE33xjwER9ShkV:-MGwANbQ409pNhTRjm3j:b-896fix) ([raw file](https://github.com/sillsdev/web-xforge/blob/88cf1d9044212ef92a3f19f71a8f94ae2d6ed1b5/src/Migrations/PtdaSyncAll/PtdaSyncRunner.cs#L168)):*
<details><summary><i>Previously, marksvc wrote…</i></summary><blockquote>

> ```
> newChapters
> ```
This could throw a null dereference exception. Let's move the `if (newChapters !=null)` up above `if (hasSource)`. 
I see that would skip doing `SyncOrCloneBookUsxAsync(..,TextType.Source,...)` in the next line, but that should be okay since we don't allow editing the source/mother book text. 
</blockquote></details>

Done.
___
*[src/Migrations/PtdaSyncAll/PtdaSyncRunner.cs, line 171 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/798#-MGtDpJ3EA8OwIxYdmM0:-MGwAS8q5AtUF_7MopcG:b7hdy42) ([raw file](https://github.com/sillsdev/web-xforge/blob/88cf1d9044212ef92a3f19f71a8f94ae2d6ed1b5/src/Migrations/PtdaSyncAll/PtdaSyncRunner.cs#L171)):*
<details><summary><i>Previously, RaymondLuong3 (Raymond Luong) wrote…</i></summary><blockquote>

> ```
> if (newChapters != null)
> ```
This null check was added.
</blockquote></details>

Yep, I moved it up as Mark suggested above and LGTM.com noticed too.
___
*[src/Migrations/PtdaSyncAll/PtdaSyncRunner.cs, line 253 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/798#-MGtE4zA0bPyEOhQX7WT:-MGwAjOrCY-iOgKT2eMf:b4u3nem) ([raw file](https://github.com/sillsdev/web-xforge/blob/88cf1d9044212ef92a3f19f71a8f94ae2d6ed1b5/src/Migrations/PtdaSyncAll/PtdaSyncRunner.cs#L253)):*
<details><summary><i>Previously, RaymondLuong3 (Raymond Luong) wrote…</i></summary><blockquote>

> ```
> try
> ```
This try/catch block was added.
</blockquote></details>

Although the try/catch gives more info, it is not necessary and will take longer. We could just make the `else` contain `return null;` only (comment out the `CloneBookUsxAsync` call).
___
*[src/Migrations/PtdaSyncAll/PtdaSyncRunner.cs, line 250 at r3](https://reviewable.io/reviews/sillsdev/web-xforge/798#-MGwBWwnBFXBH5F-a4-h:-MGwBWwnBFXBH5F-a4-i:b2hacvu) ([raw file](https://github.com/sillsdev/web-xforge/blob/f0e3c530706724490bb875925b6f7a13eaa44011/src/Migrations/PtdaSyncAll/PtdaSyncRunner.cs#L250)):*
> ```
> SyncBookUsxAsync
> ```
This also gets books but would need a bit of refactoring if we wanted to stop it doing that. Given all the errors so far where specifically for `CloneBookUsxAsync` I think we can leave this unless we encounter another issue.

**Review by irahopkinson — APPROVED** [review]
> Dismissed @marksvc from a discussion.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/798)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by marksvc — APPROVED** [review]
I approve. See discussions.

> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/798#-:-MGyPbnm4jAHY_eSr307:b-snfz3h)* status: :shipit: complete! all files reviewed, all discussions resolved

___
*[src/Migrations/PtdaSyncAll/PtdaSyncRunner.cs, line 253 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/798#-MGtE4zA0bPyEOhQX7WT:-MGyOjcS0Dne5XeTlmhj:bj2lxvo) ([raw file](https://github.com/sillsdev/web-xforge/blob/88cf1d9044212ef92a3f19f71a8f94ae2d6ed1b5/src/Migrations/PtdaSyncAll/PtdaSyncRunner.cs#L253)):*
<details><summary><i>Previously, irahopkinson (Ira Hopkinson) wrote…</i></summary><blockquote>

Although the try/catch gives more info, it is not necessary and will take longer. We could just make the `else` contain `return null;` only (comment out the `CloneBookUsxAsync` call).
</blockquote></details>

Hmm, that's true, isn't it. If we don't need to clone XXA because it will be taken care of when we later clone with PTDD, then we also don't need to clone a missing EPH or RUT. 
I think I am a proponent of keeping the Clone..() call in here, for maximal consistency with how projects were syncing with PTDA in SF, and in case there are side effects that I can't think of. 
___
*[src/Migrations/PtdaSyncAll/PtdaSyncRunner.cs, line 250 at r3](https://reviewable.io/reviews/sillsdev/web-xforge/798#-MGwBWwnBFXBH5F-a4-h:-MGyNlNj9ul28rXGaf6p:b6nbx8a) ([raw file](https://github.com/sillsdev/web-xforge/blob/f0e3c530706724490bb875925b6f7a13eaa44011/src/Migrations/PtdaSyncAll/PtdaSyncRunner.cs#L250)):*
<details><summary><i>Previously, irahopkinson (Ira Hopkinson) wrote…</i></summary><blockquote>

> ```
> SyncBookUsxAsync
> ```
This also gets books but would need a bit of refactoring if we wanted to stop it doing that. Given all the errors so far where specifically for `CloneBookUsxAsync` I think we can leave this unless we encounter another issue.
</blockquote></details>

Yeah, it's possible that we could have a similar problem running SyncBookUsxAsync(), depending on what the list of books in SF and in PT are, for a project. But we will probably get away with not having to help SyncBookUsxAsync().

**Pull request merged**
