### PR TITLE
SF-2662 Use project-specified font in question dialog

### PR DESCRIPTION
**Pull request by Nateowami**
This is a followup to the recently-merged font support: https://github.com/sillsdev/web-xforge/pull/2346

The main part of this change is just passing around the project doc to components that are going to render a chapter.

- - -
This change is [Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/2398)

### CODE REVIEW

**Review by pmachapman — CHANGES_REQUESTED** [review]
Looks good - just a couple of really minor nits.

> Reviewed 7 of 7 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/2398#-:-Nu_GjzQ2VtfM1Q6OJEm:bel6z1n)* status: all files reviewed, 2 unresolved discussions (waiting on @Nateowami)

___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/checking/question-dialog/question-dialog.component.ts` line 17 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/2398#-Nu_GuwC08JH1E1xI4Ob:-Nu_GuwC08JH1E1xI4Oc:b-dk31by) ([raw file](https://github.com/sillsdev/web-xforge/blob/3e5b5c025759fdbe12eda7141339517a5a116d8e/src/SIL.XForge.Scripture/ClientApp/src/app/checking/question-dialog/question-dialog.component.ts#L17)):*
> ```XML
> import { SubscriptionDisposable } from 'xforge-common/subscription-disposable';
> import { XFValidators } from 'xforge-common/xfvalidators';
> import { SFProjectProfileDoc } from 'src/app/core/models/sf-project-profile-doc';
> ```

NIT: Are you able to make this a relative path (and then move down the import order), like the others?



_Code quote:_
```XML
import { SFProjectProfileDoc } from 'src/app/core/models/sf-project-profile-doc';
```
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/checking/question-dialog/question-dialog.service.spec.ts` line 202 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/2398#-Nu_HVS0DDIFsQYB9Lsm:-Nu_HVS0DDIFsQYB9Lsn:bihsjmg) ([raw file](https://github.com/sillsdev/web-xforge/blob/3e5b5c025759fdbe12eda7141339517a5a116d8e/src/SIL.XForge.Scripture/ClientApp/src/app/checking/question-dialog/question-dialog.service.spec.ts#L202)):*
> ```XML
>       data: this.testProject
>     });
>     this.projectDoc = this.realtimeService.get<SFProjectDoc>(SFProjectDoc.COLLECTION, 'project01');
> ```

NIT: Would you be able to change this to `this.PROJECT01`, like the `addSnapshot` above?



_Code quote:_
```XML
'project01'
```

**Review by Nateowami — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/2398)* status: 5 of 7 files reviewed, 2 unresolved discussions (waiting on @pmachapman)

___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/checking/question-dialog/question-dialog.component.ts` line 17 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/2398#-Nu_GuwC08JH1E1xI4Ob:-Nu_O9BSECr4HbuI2sQF:boiekll) ([raw file](https://github.com/sillsdev/web-xforge/blob/3e5b5c025759fdbe12eda7141339517a5a116d8e/src/SIL.XForge.Scripture/ClientApp/src/app/checking/question-dialog/question-dialog.component.ts#L17)):*
<details><summary><i>Previously, pmachapman (Peter Chapman) wrote…</i></summary><blockquote>

NIT: Are you able to make this a relative path (and then move down the import order), like the others?
</blockquote></details>

I've made it relative. The import was added using a quick fix (as I normally do). It's annoying that our convention conflicts with what the quick fix does. Is there some way we can change that? Or should we consider reversing our convention?

I don't understand what you mean about import order. The linter doesn't complain about the order I have here.
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/checking/question-dialog/question-dialog.service.spec.ts` line 202 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/2398#-Nu_HVS0DDIFsQYB9Lsm:-Nu_OUPT9-Trb04lFP9B:b6dm5pb) ([raw file](https://github.com/sillsdev/web-xforge/blob/3e5b5c025759fdbe12eda7141339517a5a116d8e/src/SIL.XForge.Scripture/ClientApp/src/app/checking/question-dialog/question-dialog.service.spec.ts#L202)):*
<details><summary><i>Previously, pmachapman (Peter Chapman) wrote…</i></summary><blockquote>

NIT: Would you be able to change this to `this.PROJECT01`, like the `addSnapshot` above?
</blockquote></details>

Thanks. This happened because I updated the test in `question-dialog.component.spec.ts` first, and then copied my changes from there to this file.

**Review by pmachapman — COMMENTED** [review]
> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/2398)* status: all files reviewed, 1 unresolved discussion (waiting on @Nateowami)

___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/checking/question-dialog/question-dialog.component.ts` line 17 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/2398#-Nu_GuwC08JH1E1xI4Ob:-Nu_T_6Z-Z8v4jpMv3MS:bw49cf9) ([raw file](https://github.com/sillsdev/web-xforge/blob/3e5b5c025759fdbe12eda7141339517a5a116d8e/src/SIL.XForge.Scripture/ClientApp/src/app/checking/question-dialog/question-dialog.component.ts#L17)):*
<details><summary><i>Previously, Nateowami (Nathaniel Paulus) wrote…</i></summary><blockquote>

I've made it relative. The import was added using a quick fix (as I normally do). It's annoying that our convention conflicts with what the quick fix does. Is there some way we can change that? Or should we consider reversing our convention?

I don't understand what you mean about import order. The linter doesn't complain about the order I have here.
</blockquote></details>

Apologies - I meant running Organize Imports in VS Code (`Shift + Alt+ O` I think). The linter isn't as strict as it should be regarding the alphabetical order of imports.

**Review by Nateowami — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/2398)* status: 6 of 7 files reviewed, 1 unresolved discussion (waiting on @pmachapman)

___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/checking/question-dialog/question-dialog.component.ts` line 17 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/2398#-Nu_GuwC08JH1E1xI4Ob:-Nu_UBk084sKqSR-sP1D:b473cxr) ([raw file](https://github.com/sillsdev/web-xforge/blob/3e5b5c025759fdbe12eda7141339517a5a116d8e/src/SIL.XForge.Scripture/ClientApp/src/app/checking/question-dialog/question-dialog.component.ts#L17)):*
<details><summary><i>Previously, pmachapman (Peter Chapman) wrote…</i></summary><blockquote>

Apologies - I meant running Organize Imports in VS Code (`Shift + Alt+ O` I think). The linter isn't as strict as it should be regarding the alphabetical order of imports.
</blockquote></details>

I was not aware that feature existed. Is there a way to make it automatic?

**Review by pmachapman — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/2398)* status: 6 of 7 files reviewed, 1 unresolved discussion (waiting on @Nateowami)

___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/checking/question-dialog/question-dialog.component.ts` line 17 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/2398#-Nu_GuwC08JH1E1xI4Ob:-Nu_TyXJ4gs1vMv5eIVD:b-jeaewu) ([raw file](https://github.com/sillsdev/web-xforge/blob/3e5b5c025759fdbe12eda7141339517a5a116d8e/src/SIL.XForge.Scripture/ClientApp/src/app/checking/question-dialog/question-dialog.component.ts#L17)):*
> Is there some way we can change that? Or should we consider reversing our convention?
I am not sure. Maybe reversing the convention will help when code gets relocated?

> I was not aware that feature existed. Is there a way to make it automatic?

I didn't think so, but apparently you can! See https://dev.to/shanesc/how-to-sort-and-cleanup-imports-on-save-in-vs-code-52p1

I will look into this and create a PR to change this config for the project.

**Review by pmachapman — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/2398#-:-Nu_WrUW4zza8PI5aF0v:bnfp4nl)* status: all files reviewed (commit messages unreviewed), all discussions resolved (waiting on @Nateowami)

**Review by pmachapman — APPROVED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/2398)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @Nateowami)

**Pull request merged**
