### PR TITLE
SF-2865 Fix autodraft open on nav when mobile view with source

### PR DESCRIPTION
**Pull request by siltomato**
This PR fixes issue where 'Auto Draft' tab was not being selected when navigating from draft generation page in mobile view with a source text.

- - -
This change is [Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/2614)

### CODE REVIEW

**Review by pmachapman — CHANGES_REQUESTED** [review]
Just one nit!

> Reviewed 5 of 5 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/2614#-:-O2vEShs0TX4pWojXTry:b-q95gvj)* status: all files reviewed, 1 unresolved discussion (waiting on @siltomato)

___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/shared/text/text-view-model.ts` line 136 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/2614#-O2vEoTK4GDhuLVPzTVd:-O2vEoTK4GDhuLVPzTVe:b44a5ey) ([raw file](https://github.com/sillsdev/web-xforge/blob/43fa59a39f4095d071a489de2f170752e9875190/src/SIL.XForge.Scripture/ClientApp/src/app/shared/text/text-view-model.ts#L136)):*
> ```XML
>    */
>   private _embeddedElements: Map<string, EmbedPosition> = new Map<string, EmbedPosition>();
> ```

NIT: This is no longer referenced, so can be removed.



_Code quote:_
```XML
private readonly destroyRef: DestroyRef
```

**Review by siltomato — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/2614)* status: 3 of 5 files reviewed, all discussions resolved (waiting on @pmachapman)

___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/shared/text/text-view-model.ts` line 136 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/2614#-O2vEoTK4GDhuLVPzTVd:-O2ydKb1AdEpLUBk4kac:b-896fix) ([raw file](https://github.com/sillsdev/web-xforge/blob/43fa59a39f4095d071a489de2f170752e9875190/src/SIL.XForge.Scripture/ClientApp/src/app/shared/text/text-view-model.ts#L136)):*
<details><summary><i>Previously, pmachapman (Peter Chapman) wrote…</i></summary><blockquote>

NIT: This is no longer referenced, so can be removed.
</blockquote></details>

Done.

**Review by pmachapman — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/2614#-:-O3U9RTGEdVUkWvIU6Mz:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @siltomato)

**Review by pmachapman — APPROVED** [review]
> Reviewed 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/2614)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @siltomato)

**Pull request merged**
