### PR TITLE
SF-2860 Users notified when offline on My Projects page

### PR DESCRIPTION
**Pull request by kylebuss**
My Projects page will not download all the necessary data for projects to be accessed offline (texts, notes, questions).
"Offline Access" will display on the Projects card once data is accessible in the IndexedDB.

- - -
This change is [Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/2621)

### CODE REVIEW

**Review by pmachapman — CHANGES_REQUESTED** [review]
Some feedback - notably this change breaks my ability to open projects that I already have cached offline.

Watching the video attached to the issue, I wonder whether this PR should also extend what data is being cached (i.e. cache questions, notes, and biblical terms too)?

> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/2621#-:-O2w2Rli4MGqVRCfZcQ2:b-xumjzo)* status: all files reviewed, 2 unresolved discussions (waiting on @kylebuss)

___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/my-projects/my-projects.component.html` line 19 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/2621#-O2w5bU3AeyY-s0sn79B:-O2w5bU3AeyY-s0sn79C:b-gos1l7) ([raw file](https://github.com/sillsdev/web-xforge/blob/58ba47eb0a392ae2e267c2110554c06419decc2d/src/SIL.XForge.Scripture/ClientApp/src/app/my-projects/my-projects.component.html#L19)):*
> ```HTML
>       icon="cloud_off"
>       [type]="userHasProjects ? 'info' : 'error'"
>       *ngIf="(isOnline | async) === false && userIsPTUser"
> ```

I think this looks a bit odd when the user has no projects, is a PT user, and is offline - see https://www.chromatic.com/test?appId=644bffe327c540a62f0fd260&id=66a411eba790a48176a242fa

Maybe if we change the logic to be:

```
*ngIf="(isOnline | async) === false && userIsPTUser && !userHasProjects"
```

it may fix it?

This will be an exceptionally uncommon use case though.



_Code quote:_
```HTML
*ngIf="(isOnline | async) === false && userIsPTUser"
```
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/my-projects/my-projects.component.html` line 41 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/2621#-O2w6Q_B-osw--LYyPUF:-O2w6Q_B-osw--LYyPUG:b-fv8gy2) ([raw file](https://github.com/sillsdev/web-xforge/blob/58ba47eb0a392ae2e267c2110554c06419decc2d/src/SIL.XForge.Scripture/ClientApp/src/app/my-projects/my-projects.component.html#L41)):*
> ```HTML
>         appRouterLink="/projects/{{ projectDoc.id }}"
>         mat-flat-button
>         [disabled]="(isOnline | async) === false"
> ```

This blocks me from opening projects that I already have offline access to. This will be a big problem for our users.

Is it possible to only disable the button if the project's texts were not cached?

One way would be to query the texts collection in IndexedDB for a count of all documents starting the `{projectId}:`, and seeing if this count is greater than or equal to the number of chapters in the project?

If that doesn't work, you could modify the `CacheService` to record what projects it has cached successfully? You could store it in a JSON array in localStorage (be aware of localStorage size limitations), or create another data type for Indexed DB for the cache service and have it record it there (this may bee too messy?), or even modify `RealtimeOfflineData` to store an `isCached` flag in IndexedDB for each document type.

There are a few ways... I can discuss further if you like.



_Code quote:_
```HTML
[disabled]="(isOnline | async) === false"
```

**Review by kylebuss — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/2621)* status: all files reviewed, 2 unresolved discussions (waiting on @pmachapman)

___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/my-projects/my-projects.component.html` line 19 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/2621#-O2w5bU3AeyY-s0sn79B:-O2ybAIS8Ud_wOt2OLXP:bcrdx8l) ([raw file](https://github.com/sillsdev/web-xforge/blob/58ba47eb0a392ae2e267c2110554c06419decc2d/src/SIL.XForge.Scripture/ClientApp/src/app/my-projects/my-projects.component.html#L19)):*
<details><summary><i>Previously, pmachapman (Peter Chapman) wrote…</i></summary><blockquote>

I think this looks a bit odd when the user has no projects, is a PT user, and is offline - see https://www.chromatic.com/test?appId=644bffe327c540a62f0fd260&id=66a411eba790a48176a242fa

Maybe if we change the logic to be:

```
*ngIf="(isOnline | async) === false && userIsPTUser && !userHasProjects"
```

it may fix it?

This will be an exceptionally uncommon use case though.
</blockquote></details>

Good catch! I'll fix this as the first message should only appear if the user has connected projects.
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/my-projects/my-projects.component.html` line 41 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/2621#-O2w6Q_B-osw--LYyPUF:-O2ybV7d8ZAJsqouu4oP:b-2690w7) ([raw file](https://github.com/sillsdev/web-xforge/blob/58ba47eb0a392ae2e267c2110554c06419decc2d/src/SIL.XForge.Scripture/ClientApp/src/app/my-projects/my-projects.component.html#L41)):*
<details><summary><i>Previously, pmachapman (Peter Chapman) wrote…</i></summary><blockquote>

This blocks me from opening projects that I already have offline access to. This will be a big problem for our users.

Is it possible to only disable the button if the project's texts were not cached?

One way would be to query the texts collection in IndexedDB for a count of all documents starting the `{projectId}:`, and seeing if this count is greater than or equal to the number of chapters in the project?

If that doesn't work, you could modify the `CacheService` to record what projects it has cached successfully? You could store it in a JSON array in localStorage (be aware of localStorage size limitations), or create another data type for Indexed DB for the cache service and have it record it there (this may bee too messy?), or even modify `RealtimeOfflineData` to store an `isCached` flag in IndexedDB for each document type.

There are a few ways... I can discuss further if you like.
</blockquote></details>

We can talk more on this as there were some bigger questions between resolving the issue in the short-term vs. what improvements we will need to make in the long-term. I should have time today after 3PM US Central time. Maybe you, me, and Raymond hop on a call? Or perhaps during planning tonight?

**Comment by Nateowami** [comment]
I don't think this is the way we should be handling this. As much as possible, we want functionality to remain available offline. In general, if a project has been opened while online, it can be opened offline. We have been allowing project switching offline from the very beginning; I don't think anything has really changed with the new projects page. What we do need to do is better handle projects that haven't been loaded offline.

**Review by pmachapman — COMMENTED** [review]
Not a proper review - just a couple of nits I noticed. I will wait for your signal before making a full review.

Also, to help keep the code reviews clean, are you able to rebase the branch instead of merge?

> Reviewed all commit messages.
> Dismissed @github-advanced-security[bot] from 12 discussions.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/2621#-:-O4HeRFC8ekDOuF9DlsX:b-f6u33s)* status: 0 of 6 files reviewed, 4 unresolved discussions (waiting on @kylebuss)

___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/my-projects/my-projects.component.ts` line 15 at r4](https://reviewable.io/reviews/sillsdev/web-xforge/2621#-O4He6IN2bt01u70BYuN:-O4He6IN2bt01u70BYuO:b6f144i) ([raw file](https://github.com/sillsdev/web-xforge/blob/0c206ea7edb20fdb8f930f501d215f8e6432e391/src/SIL.XForge.Scripture/ClientApp/src/app/my-projects/my-projects.component.ts#L15)):*
> ```XML
> import { SFUserProjectsService } from 'xforge-common/user-projects.service';
> import { UserService } from 'xforge-common/user.service';
> import { RealtimeQuery } from '../../xforge-common/models/realtime-query';
> ```

NIT: Remove `../../`



_Code quote:_
```XML
import { RealtimeQuery } from '../../xforge-common/models/realtime-query';
```
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/my-projects/my-projects.component.spec.ts` line 27 at r4](https://reviewable.io/reviews/sillsdev/web-xforge/2621#-O4HeEZM2O_b7Cn-6F_j:-O4HeEZN66NRNx3e16SE:b6f144i) ([raw file](https://github.com/sillsdev/web-xforge/blob/0c206ea7edb20fdb8f930f501d215f8e6432e391/src/SIL.XForge.Scripture/ClientApp/src/app/my-projects/my-projects.component.spec.ts#L27)):*
> ```XML
> import { SFUserProjectsService } from 'xforge-common/user-projects.service';
> import { UserService } from 'xforge-common/user.service';
> import { RealtimeQuery } from '../../xforge-common/models/realtime-query';
> ```

NIT: Remove `../../`



_Code quote:_
```XML
import { RealtimeQuery } from '../../xforge-common/models/realtime-query';
```

**Comment by kylebuss** [comment]
@pmachapman I will work on the nits you mentioned. I am also cleaning up the storyboard issues.

**Review by kylebuss — COMMENTED** [review]
I don't know why it is showing changes on files that I didn't touch? Otherwise, @pmachapman  this is ready for a full review.

> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/2621#-:-O4Loks12oVIaiYMkquG:b-2qyola)* status: 0 of 11 files reviewed, 4 unresolved discussions (waiting on @github-advanced-security[bot] and @pmachapman)

___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/my-projects/my-projects.component.spec.ts` line 12 at r6](https://reviewable.io/reviews/sillsdev/web-xforge/2621#gh-1718545070:-O4LocLvAzuaQioP1vla:b-896fix) ([raw file](https://github.com/sillsdev/web-xforge/blob/eb239ac1fb2e5dff605ff5e2257d0e19c533028d/src/SIL.XForge.Scripture/ClientApp/src/app/my-projects/my-projects.component.spec.ts#L12)):*
<details><summary><i>Previously, github-advanced-security[bot] wrote…</i></summary><blockquote>

## Unused variable, import, function or class

Unused import createTestProjectUserConfig.

[Show more details](https://github.com/sillsdev/web-xforge/security/code-scanning/846)
</blockquote></details>

Done.
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/my-projects/my-projects.stories.ts` line 27 at r7](https://reviewable.io/reviews/sillsdev/web-xforge/2621#gh-1718560666:-O4LoeZLEW17_ivlhB9N:b-896fix) ([raw file](https://github.com/sillsdev/web-xforge/blob/3f5a23e4ed9f196c1f72fe4fd12e4761aff41205/src/SIL.XForge.Scripture/ClientApp/src/app/my-projects/my-projects.stories.ts#L27)):*
<details><summary><i>Previously, github-advanced-security[bot] wrote…</i></summary><blockquote>

## Unused variable, import, function or class

Unused import CheckingQuestionsService.

[Show more details](https://github.com/sillsdev/web-xforge/security/code-scanning/847)
</blockquote></details>

Done.
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/my-projects/my-projects.component.html` line 19 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/2621#-O2w5bU3AeyY-s0sn79B:-O4La-9jAShxML0t4PL8:b-698bvp) ([raw file](https://github.com/sillsdev/web-xforge/blob/58ba47eb0a392ae2e267c2110554c06419decc2d/src/SIL.XForge.Scripture/ClientApp/src/app/my-projects/my-projects.component.html#L19)):*
<details><summary><i>Previously, kylebuss (Kyle Buss) wrote…</i></summary><blockquote>

Good catch! I'll fix this as the first message should only appear if the user has connected projects.
</blockquote></details>

This code was removed.
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/my-projects/my-projects.component.html` line 41 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/2621#-O2w6Q_B-osw--LYyPUF:-O4L_wwz2s0B6KUHiCcF:b-698bvp) ([raw file](https://github.com/sillsdev/web-xforge/blob/58ba47eb0a392ae2e267c2110554c06419decc2d/src/SIL.XForge.Scripture/ClientApp/src/app/my-projects/my-projects.component.html#L41)):*
<details><summary><i>Previously, kylebuss (Kyle Buss) wrote…</i></summary><blockquote>

We can talk more on this as there were some bigger questions between resolving the issue in the short-term vs. what improvements we will need to make in the long-term. I should have time today after 3PM US Central time. Maybe you, me, and Raymond hop on a call? Or perhaps during planning tonight?
</blockquote></details>

This code was removed.

**Comment by kylebuss** [comment]
@pmachapman I think this is finally ready for a full review. Sorry for the commits mess.

**Review by pmachapman — CHANGES_REQUESTED** [review]
Some nits, but my main concern is regarding how intense this is when you have access to multiple large projects. I think we need to find a more lightweight "good enough" way of determining if a project can be accessed (at least partially) offline.

> Reviewed 1 of 6 files at r2, 10 of 10 files at r8, all commit messages.
> Dismissed @github-advanced-security[bot] from 2 discussions.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/2621#-:-O4hBBHx7kJdLV8ITSym:b-mcz8ei)* status: all files reviewed, 5 unresolved discussions (waiting on @kylebuss)

___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/my-projects/my-projects.component.ts` line 23 at r8](https://reviewable.io/reviews/sillsdev/web-xforge/2621#-O4g2ZMS7PBRxFOfSCPC:-O4g2ZMS7PBRxFOfSCPD:b1gows1) ([raw file](https://github.com/sillsdev/web-xforge/blob/7d0ba15876b60bbb678b039aae011af4936cafbf/src/SIL.XForge.Scripture/ClientApp/src/app/my-projects/my-projects.component.ts#L23)):*
> ```XML
> import { PermissionsService } from '../core/permissions.service';
> import { SFProjectService } from '../core/sf-project.service';
> import { RealtimeQuery } from '../../xforge-common/models/realtime-query';
> ```

NIT: Remove the `../../`



_Code quote:_
```XML
import { RealtimeQuery } from '../../xforge-common/models/realtime-query';
```
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/my-projects/my-projects.component.ts` line 129 at r8](https://reviewable.io/reviews/sillsdev/web-xforge/2621#-O4gS-eTC-X6FZP3w0I7:-O4gS-eTC-X6FZP3w0I8:b-272xi4) ([raw file](https://github.com/sillsdev/web-xforge/blob/7d0ba15876b60bbb678b039aae011af4936cafbf/src/SIL.XForge.Scripture/ClientApp/src/app/my-projects/my-projects.component.ts#L129)):*
> ```XML
>     const isTranslateAccessible = this.permissions.canAccessTranslate(sfProject);
>     const isCheckingAccessible = this.permissions.canAccessCommunityChecking(sfProject) ?? false;
>     const isOfflineAccessible = this.userProjectsService.checkProjectTextsLoaded(sfProject);
> ```

I don't think checking for every text is the right way. This is quite computationally and memory expensive, and results in a slow display of project offline status (see https://youtu.be/KW_fSdmh2AU).

Is there another way to check whether or not we some the documents for a project without actually loading them all?

The memory usage in my browser on the my-projects page was (and it hadn't even finished loading everything):


And the realtime server ballooned to:


I think these values are way too high. If you like, I can add you to a bunch of projects I have on dev so you can test with a lot of data?



_Code quote:_
```XML
const isOfflineAccessible = this.userProjectsService.checkProjectTextsLoaded(sfProject);
```
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/my-projects/my-projects.component.spec.ts` line 27 at r8](https://reviewable.io/reviews/sillsdev/web-xforge/2621#-O4h9x3e7jYpzMDJ2Pnk:-O4h9x3e7jYpzMDJ2Pnl:b1gows1) ([raw file](https://github.com/sillsdev/web-xforge/blob/7d0ba15876b60bbb678b039aae011af4936cafbf/src/SIL.XForge.Scripture/ClientApp/src/app/my-projects/my-projects.component.spec.ts#L27)):*
> ```XML
> import { SFUserProjectsService } from 'xforge-common/user-projects.service';
> import { UserService } from 'xforge-common/user.service';
> import { RealtimeQuery } from '../../xforge-common/models/realtime-query';
> ```

NIT: Remove the `../../`



_Code quote:_
```XML
import { RealtimeQuery } from '../../xforge-common/models/realtime-query';
```
___
*[`src/SIL.XForge.Scripture/ClientApp/src/xforge-common/user-projects.service.ts` line 188 at r8](https://reviewable.io/reviews/sillsdev/web-xforge/2621#-O4g8OyT2mUSQThJ3FET:-O4g8OyT2mUSQThJ3FEU:b-116i3s) ([raw file](https://github.com/sillsdev/web-xforge/blob/7d0ba15876b60bbb678b039aae011af4936cafbf/src/SIL.XForge.Scripture/ClientApp/src/xforge-common/user-projects.service.ts#L188)):*
> ```XML
>           const projectProfile = this.projectDocs.get(project.id);
> 
>           if (projectProfile != null && (await this.permissionsService.canAccessTranslate(project))) {
> ```

NIT: You do not need to `await` this.



_Code quote:_
```XML
if (projectProfile != null && (await this.permissionsService.canAccessTranslate(project))) {
```
___
*[`src/SIL.XForge.Scripture/ClientApp/src/xforge-common/user-projects.service.ts` line 193 at r8](https://reviewable.io/reviews/sillsdev/web-xforge/2621#-O4g8K0s6EhASkupjPXk:-O4g8K0s6EhASkupjPXl:b-116i3s) ([raw file](https://github.com/sillsdev/web-xforge/blob/7d0ba15876b60bbb678b039aae011af4936cafbf/src/SIL.XForge.Scripture/ClientApp/src/xforge-common/user-projects.service.ts#L193)):*
> ```XML
>           }
> 
>           if (project != null && (await this.permissionsService.canAccessCommunityChecking(project))) {
> ```

NIT: You do not need to `await` this.



_Code quote:_
```XML
if (project != null && (await this.permissionsService.canAccessCommunityChecking(project))) {
```

**Review by kylebuss — COMMENTED** [review]
Updated user-project-service.ts to use OfflineStore to check for texts.

> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/2621#-:-O4laRoxD0dYqHvyR5iX:bnbgx3w)* status: 7 of 11 files reviewed, 1 unresolved discussion (waiting on @pmachapman)

___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/my-projects/my-projects.component.ts` line 129 at r8](https://reviewable.io/reviews/sillsdev/web-xforge/2621#-O4gS-eTC-X6FZP3w0I7:-O4lacDu6dFgOCXpBNht:b-896fix) ([raw file](https://github.com/sillsdev/web-xforge/blob/7d0ba15876b60bbb678b039aae011af4936cafbf/src/SIL.XForge.Scripture/ClientApp/src/app/my-projects/my-projects.component.ts#L129)):*
<details><summary><i>Previously, pmachapman (Peter Chapman) wrote…</i></summary><blockquote>

I don't think checking for every text is the right way. This is quite computationally and memory expensive, and results in a slow display of project offline status (see https://youtu.be/KW_fSdmh2AU).

Is there another way to check whether or not we some the documents for a project without actually loading them all?

The memory usage in my browser on the my-projects page was (and it hadn't even finished loading everything):


And the realtime server ballooned to:


I think these values are way too high. If you like, I can add you to a bunch of projects I have on dev so you can test with a lot of data?
</blockquote></details>

Done.

**Review by pmachapman — CHANGES_REQUESTED** [review]
That runs a lot leaner!

Just one bug I noticed - if you visit a project for the first time, then navigate back to the my projects page, the "Offline Access" indicator does not display until the page refreshes. See https://youtu.be/4Vq0r2-Z6Mo

> Reviewed 4 of 4 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/2621#-:-O4mYSii0GPhBQEu713T:b-tspl3s)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @kylebuss)

**Review by kylebuss — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/2621)* status: 9 of 11 files reviewed, 1 unresolved discussion (waiting on @pmachapman)

___
*[`src/SIL.XForge.Scripture/ClientApp/src/xforge-common/user-projects.service.ts` line 103 at r9](https://reviewable.io/reviews/sillsdev/web-xforge/2621#-O4pFCg-3znFNPZotVhk:-O4pFCg-3znFNPZotVhl:b2wdsnw) ([raw file](https://github.com/sillsdev/web-xforge/blob/6cf2ffca7a6a2e3edc3be0124065ee31ed623ad3/src/SIL.XForge.Scripture/ClientApp/src/xforge-common/user-projects.service.ts#L103)):*
> ```XML
>       }
>       return;
>     }
> ```

This was causing the bug you observed. No changes to the project list were detected so we simply returned to the page without checking/updating for texts.



_Code quote:_
```XML
    if (removedProjectsCount === 0 && docFetchPromises.length === 0) {
      if (currentProjectIds.length === 0) {
        // Provide an initial empty set of projects if the user has no projects.
        this._projectDocs$.next([]);
        this._userConfigDocs$.next([]);
      }
      return;
    }
```

**Review by pmachapman — APPROVED** [review]
:lgtm: Good work!

> Reviewed 2 of 2 files at r10, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/2621#-:-O4rSI69D2EOxbVLCXJ0:b-pv0wtg)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @kylebuss)

**Comment by Nateowami** [comment]
I'm somewhat concerned about the idea of showing "Offline Access" at this point. In general, projects should just work offline, but there are a large number of cases where it doesn't work smoothly. I would rather give no assurances than something that might be a false assurance that it will work offline.

In my testing, it also doesn't seem to be behaving quite correctly, because I visited a project's overview page (which loads all chapters for that project), waited, and returned to the my projects page, and it still didn't indicate that it would work offline.

I also can't reproduce the problem as stated in the issue. I went on QA, turned of my connection, and attempted to load a resource I had most likely never loaded into IndexedDB. I didn't get an error, but it kept trying to load forever. This isn't the right behavior either, but it seems the fix would be to tell the user this project can't be displayed offline. We already have logic to do that, which sometimes works, but evidently doesn't in this case.

**Comment by kylebuss** [comment]
@Nateowami I've removed the code that will display the "Offline Access" on the My Projects page. The Edit & Review and Questions & Answers will display the message that the "texts are not available offline" if they have not been loaded into the IndexedDB.

**Review by pmachapman — COMMENTED** [review]
> Reviewed 4 of 4 files at r11, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/2621)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @kylebuss)

**Pull request merged**
