### PR TITLE
SF-2270 Select custom source text for pre-translation drafting

### PR DESCRIPTION
**Pull request by pmachapman**
This PR enables support for selecting an "alternate source" for pre-translation drafting.

This feature in particular is required for Mother Tongue drafting support.

Once the alternate source is selected in Settings, it will be synced when pre-translation draft build is started by the user in Scripture Forge.

- - -
This change is [Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/2122)

### CODE REVIEW

**Review by siltomato — CHANGES_REQUESTED** [review]
A lot of work for a dropdown box, right =)?  The business logic is above my head, so this was a nice intro for me.
I made some notes on just a few minor questions.

> Reviewed 26 of 26 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/2122#-:-NhDxzA36os_K6KdSOso:b-tsd3mv)* status: all files reviewed, 4 unresolved discussions (waiting on @pmachapman)

___
*[`src/RealtimeServer/scriptureforge/services/sf-project-migrations.ts` line 261 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/2122#-NhDulkV4l7MBXd_xHau:-NhDulkV4l7MBXd_xHav:b-b58aw6) ([raw file](https://github.com/sillsdev/web-xforge/blob/1807fe33de0687775d5157dbc7a0f2d5a7e964ca/src/RealtimeServer/scriptureforge/services/sf-project-migrations.ts#L261)):*
> ```XML
>   migrateOp(_op: RawOp): void {
>     //do nothing
>   }
> ```

I see this as as no-op in all the migration files.  Not something important for this PR, but I wonder if `Migration` could be made into an abstract class to implement this default behavior so it doesn't need to be repeated everywhere.



_Code quote:_
```XML
  migrateOp(_op: RawOp): void {
    //do nothing
  }
```
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/settings/settings.component.ts` line 288 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/2122#-NhChpcN-lgS9S0qAtuD:-NhChpcO4bzGGlt8ayTk:b2xo4jb) ([raw file](https://github.com/sillsdev/web-xforge/blob/1807fe33de0687775d5157dbc7a0f2d5a7e964ca/src/SIL.XForge.Scripture/ClientApp/src/app/settings/settings.component.ts#L288)):*
> ```XML
> 
>     // Check if the pre-translation alternate source project needs to be updated
>     if ((newValue.alternateSourceParatextId ?? null) !== (this.previousFormValues.alternateSourceParatextId ?? null)) {
> ```

Is the `?? null` here for normalizing possible values of `undefined` and `null`?  The type for `alternateSourceParatextId` is `string | undefined`.
___
*[`src/SIL.XForge.Scripture/Models/TranslateConfig.cs` line 10 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/2122#-NhDXEcBCIcbG_xiU9EG:-NhDXEcBCIcbG_xiU9EH:bnmrutv) ([raw file](https://github.com/sillsdev/web-xforge/blob/1807fe33de0687775d5157dbc7a0f2d5a7e964ca/src/SIL.XForge.Scripture/Models/TranslateConfig.cs#L10)):*
> ```Smalltalk
>     public int? DefaultNoteTagId { get; set; }
>     public bool PreTranslate { get; set; }
>     public DraftConfig DraftConfig { get; set; } = new DraftConfig();
> ```

Out of curiosity, why did you choose to initialize DraftConfig?
___
*[`src/SIL.XForge.Scripture/Services/SFProjectService.cs` line 263 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/2122#-NhCniPH6OZqgEx1HmXb:-NhCniPH6OZqgEx1HmXc:b-kiac6i) ([raw file](https://github.com/sillsdev/web-xforge/blob/1807fe33de0687775d5157dbc7a0f2d5a7e964ca/src/SIL.XForge.Scripture/Services/SFProjectService.cs#L263)):*
> ```Smalltalk
>         bool unsetAlternateSourceProject = settings.AlternateSourceParatextId == ProjectSettingValueUnset;
> 
>         // Get the list of projects of settings the source or alternate source
> ```

In this comment, is this supposed to be: "Get the list of projects for setting the source or alternate source"?

**Review by pmachapman — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/2122)* status: 25 of 26 files reviewed, 4 unresolved discussions (waiting on @siltomato)

___
*[`src/RealtimeServer/scriptureforge/services/sf-project-migrations.ts` line 261 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/2122#-NhDulkV4l7MBXd_xHau:-NhSq_o356rtWABPucmA:by0r83e) ([raw file](https://github.com/sillsdev/web-xforge/blob/1807fe33de0687775d5157dbc7a0f2d5a7e964ca/src/RealtimeServer/scriptureforge/services/sf-project-migrations.ts#L261)):*
<details><summary><i>Previously, siltomato wrote…</i></summary><blockquote>

I see this as as no-op in all the migration files.  Not something important for this PR, but I wonder if `Migration` could be made into an abstract class to implement this default behavior so it doesn't need to be repeated everywhere.
</blockquote></details>

Good idea. I will create a PR to do this later today across SF as I think it would be out of scope for this PR.
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/settings/settings.component.ts` line 288 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/2122#-NhChpcN-lgS9S0qAtuD:-NhSrRWb3cf9qPTqEceX:byytgwy) ([raw file](https://github.com/sillsdev/web-xforge/blob/1807fe33de0687775d5157dbc7a0f2d5a7e964ca/src/SIL.XForge.Scripture/ClientApp/src/app/settings/settings.component.ts#L288)):*
<details><summary><i>Previously, siltomato wrote…</i></summary><blockquote>

Is the `?? null` here for normalizing possible values of `undefined` and `null`?  The type for `alternateSourceParatextId` is `string | undefined`.
</blockquote></details>

Yes, it is. Somehow values across the component are set to `null` by the frontend. (I had to fix a similar bug in #2119)
___
*[`src/SIL.XForge.Scripture/Models/TranslateConfig.cs` line 10 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/2122#-NhDXEcBCIcbG_xiU9EG:-NhSrqHj432BMqDEH2MC:b-y1su6b) ([raw file](https://github.com/sillsdev/web-xforge/blob/1807fe33de0687775d5157dbc7a0f2d5a7e964ca/src/SIL.XForge.Scripture/Models/TranslateConfig.cs#L10)):*
<details><summary><i>Previously, siltomato wrote…</i></summary><blockquote>

Out of curiosity, why did you choose to initialize DraftConfig?
</blockquote></details>

I set it to resolve the Resharper warning "Non-nullable property 'DraftConfig' is not initialized in any execution path", which corresponds to the C# warning CS8618 "Non-nullable property 'DraftConfig' must contain a non-null value when exiting constructor. Consider declaring the property as nullable."

The C# warning would display if the project had `#nullable enable` wanting context - we currently just use the `#nullable annotations` context until the code base is at such a point where we can enable the warnings.
___
*[`src/SIL.XForge.Scripture/Services/SFProjectService.cs` line 263 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/2122#-NhCniPH6OZqgEx1HmXb:-NhSu7tm-tGUSOcw1Xvu:blg2h3k) ([raw file](https://github.com/sillsdev/web-xforge/blob/1807fe33de0687775d5157dbc7a0f2d5a7e964ca/src/SIL.XForge.Scripture/Services/SFProjectService.cs#L263)):*
<details><summary><i>Previously, siltomato wrote…</i></summary><blockquote>

In this comment, is this supposed to be: "Get the list of projects for setting the source or alternate source"?
</blockquote></details>

Done. Yes, thank you! :-)

**Review by pmachapman — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/2122)* status: 24 of 26 files reviewed, 2 unresolved discussions (waiting on @siltomato)

___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/settings/settings.component.ts` line 288 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/2122#-NhChpcN-lgS9S0qAtuD:-NhTJ1Ek4SejK6zi95ck:b-bb6t5n) ([raw file](https://github.com/sillsdev/web-xforge/blob/1807fe33de0687775d5157dbc7a0f2d5a7e964ca/src/SIL.XForge.Scripture/ClientApp/src/app/settings/settings.component.ts#L288)):*
<details><summary><i>Previously, siltomato wrote…</i></summary><blockquote>

If this is the case, should the types be changed to reflect null as a possible value?
</blockquote></details>

Done. I have also changed `sourceParatextId` and `hideCommunityCheckingText` as these too use the coalesce.
___
*[`src/SIL.XForge.Scripture/Models/TranslateConfig.cs` line 10 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/2122#-NhDXEcBCIcbG_xiU9EG:-NhTFBm1CsCeRfT4xMgy:b6siyux) ([raw file](https://github.com/sillsdev/web-xforge/blob/1807fe33de0687775d5157dbc7a0f2d5a7e964ca/src/SIL.XForge.Scripture/Models/TranslateConfig.cs#L10)):*
<details><summary><i>Previously, siltomato wrote…</i></summary><blockquote>

Why shouldn't it be declared nullable instead of assigning it?  Not that this would necessarily be correct... just wanting to know your thoughts.
</blockquote></details>

I did try this initially (as not all projects will have pre-translation drafting), but the frontend code ended up being mired in questions mark operators.

The `DraftConfig` object will also be used to store the chapter numbers and custom configuration, so I thought I might was well just have it non-nullable (and created by the migration)

**Review by siltomato — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/2122)* status: all files reviewed, 1 unresolved discussion (waiting on @pmachapman)

___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/core/models/sf-project-settings.ts` line 19 at r3](https://reviewable.io/reviews/sillsdev/web-xforge/2122#-NhTOK1K-sYTVrFatzH8:-NhTOK1K-sYTVrFatzH9:bn9yd9t) ([raw file](https://github.com/sillsdev/web-xforge/blob/24b6984bae52fb0d8dc96d8029673734feabedad/src/SIL.XForge.Scripture/ClientApp/src/app/core/models/sf-project-settings.ts#L19)):*
> ```XML
>   checkingAnswerExport?: CheckingAnswerExport;
>   hideCommunityCheckingText?: boolean | null;
> }
> ```

I suspect that it is the angular FormControl that is setting these values to null.  Since that is the likely culprit, do you think we should add `null` as a possible value for all these types?
___
*[`src/SIL.XForge.Scripture/Models/TranslateConfig.cs` line 10 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/2122#-NhDXEcBCIcbG_xiU9EG:-NhTL4-L1FGwtx5rI1K6:bz32tb6) ([raw file](https://github.com/sillsdev/web-xforge/blob/1807fe33de0687775d5157dbc7a0f2d5a7e964ca/src/SIL.XForge.Scripture/Models/TranslateConfig.cs#L10)):*
<details><summary><i>Previously, pmachapman (Peter Chapman) wrote…</i></summary><blockquote>

I did try this initially (as not all projects will have pre-translation drafting), but the frontend code ended up being mired in questions mark operators.

The `DraftConfig` object will also be used to store the chapter numbers and custom configuration, so I thought I might was well just have it non-nullable (and created by the migration)
</blockquote></details>

Ok, makes sense.  Thanks for the explanation.

**Review by pmachapman — COMMENTED** [review]
Thanks for your work reviewing this. I've also added a fix for a bug I noticed when I was testing the settings component `null` changes where an alternate source project could be deleted accidentally.

> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/2122#-:-NhTbqLwBPkKunqW6w55:b-artjd)* status: 22 of 26 files reviewed, 1 unresolved discussion (waiting on @siltomato)

___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/core/models/sf-project-settings.ts` line 19 at r3](https://reviewable.io/reviews/sillsdev/web-xforge/2122#-NhTOK1K-sYTVrFatzH8:-NhTWvpm3qah2ZVTNnW0:b-a35gkw) ([raw file](https://github.com/sillsdev/web-xforge/blob/24b6984bae52fb0d8dc96d8029673734feabedad/src/SIL.XForge.Scripture/ClientApp/src/app/core/models/sf-project-settings.ts#L19)):*
<details><summary><i>Previously, siltomato wrote…</i></summary><blockquote>

I suspect that it is the angular FormControl that is setting these values to null.  Since that is the likely culprit, do you think we should add `null` as a possible value for all these types?
</blockquote></details>

Done. Sounds good. I have added the coalesce operators where necessary too.

**Review by siltomato — CHANGES_REQUESTED** [review]
> Reviewed 4 of 4 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/2122)* status: all files reviewed, 1 unresolved discussion (waiting on @pmachapman)

___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/settings/settings.component.ts` line 315 at r4](https://reviewable.io/reviews/sillsdev/web-xforge/2122#-NhTjDiD52KWiQC3SZs8:-NhTjDiD52KWiQC3SZs9:bbbwlxx) ([raw file](https://github.com/sillsdev/web-xforge/blob/5195a51783f3325c7030e43b2d8d459e6cd87c3c/src/SIL.XForge.Scripture/ClientApp/src/app/settings/settings.component.ts#L315)):*
> ```XML
>       return;
>     }
>     if ((newValue.checkingEnabled ?? null) !== (this.previousFormValues.checkingEnabled ?? null)) {
> ```

Would it be worth creating a helper function for this type of comparison?

Something like:
```ts
private settingChanged(from: SFProjectSettings, to: SFProjectSettings, prop: keyof SFProjectSettings): boolean {
  return (from[prop] ?? null) !== (to[prop] ?? null);
}
```
Or terser but not pure:
```ts
private settingChanged(newValue: SFProjectSettings, prop: keyof SFProjectSettings): boolean {
  return (newValue[prop] ?? null) !== (this.previousFormValues[prop] ?? null);
}
```

**Review by pmachapman — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/2122)* status: all files reviewed, 1 unresolved discussion (waiting on @siltomato)

___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/settings/settings.component.ts` line 315 at r4](https://reviewable.io/reviews/sillsdev/web-xforge/2122#-NhTjDiD52KWiQC3SZs8:-NhTvHMX4CLzEJGczTcW:b63fzt) ([raw file](https://github.com/sillsdev/web-xforge/blob/5195a51783f3325c7030e43b2d8d459e6cd87c3c/src/SIL.XForge.Scripture/ClientApp/src/app/settings/settings.component.ts#L315)):*
<details><summary><i>Previously, siltomato wrote…</i></summary><blockquote>

Would it be worth creating a helper function for this type of comparison?

Something like:
```ts
private settingChanged(from: SFProjectSettings, to: SFProjectSettings, prop: keyof SFProjectSettings): boolean {
  return (from[prop] ?? null) !== (to[prop] ?? null);
}
```
Or terser but not pure:
```ts
private settingChanged(newValue: SFProjectSettings, prop: keyof SFProjectSettings): boolean {
  return (newValue[prop] ?? null) !== (this.previousFormValues[prop] ?? null);
}
```
</blockquote></details>

I've chosen the terser option, as it matchings `this.updateSetting()`. I've also tweaked some of the method headers to use `keyof SFProjectSettings` in a more modern TypeScript style.

**Review by siltomato — APPROVED** [review]
Looks great, thanks for your patience!

> Reviewed 1 of 1 files at r5, 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/2122#-:-NhTyz1m-NoB2X-L6GnX:b-920khr)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @pmachapman)

___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/settings/settings.component.ts` line 315 at r4](https://reviewable.io/reviews/sillsdev/web-xforge/2122#-NhTjDiD52KWiQC3SZs8:-NhTygMQE-1uP3lsZbfj:bq8fmo3) ([raw file](https://github.com/sillsdev/web-xforge/blob/5195a51783f3325c7030e43b2d8d459e6cd87c3c/src/SIL.XForge.Scripture/ClientApp/src/app/settings/settings.component.ts#L315)):*
<details><summary><i>Previously, pmachapman (Peter Chapman) wrote…</i></summary><blockquote>

I've chosen the terser option, as it matchings `this.updateSetting()`. I've also tweaked some of the method headers to use `keyof SFProjectSettings` in a more modern TypeScript style.
</blockquote></details>

Cool, looks good.

**Review by siltomato — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/2122#-:-NhdXDBP1B_2xHtrUlEI:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @pmachapman)

**Review by siltomato — CHANGES_REQUESTED** [review]
The changes look good, but I need help understanding what a draft for a no-source book means.  How can a draft translation be done if there is nothing to translate from?

> Reviewed 6 of 7 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/2122#-:-Ni0IOge23CeK8-Ahw4f:b-s7rsac)* status: 29 of 30 files reviewed, 1 unresolved discussion (waiting on @pmachapman)

___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-generation-steps/draft-generation-steps.component.ts` line 32 at r8](https://reviewable.io/reviews/sillsdev/web-xforge/2122#-Ni0JhwY4BT0QFmNEplX:-Ni0JhwY4BT0QFmNEplY:b-z6yjxe) ([raw file](https://github.com/sillsdev/web-xforge/blob/1cf41f693ebdd31ee287c5c1f36f707905ae022e/src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-generation-steps/draft-generation-steps.component.ts#L32)):*
> ```XML
>       switchMap(doc => {
>         // See if there is an alternate project set
>         let sourceProjectId: string | undefined = doc?.data?.translateConfig.draftConfig?.alternateSource?.projectRef;
> ```

Optional chaining `?` not needed after `draftConfig`

**Review by pmachapman — COMMENTED** [review]
The modification to this PR is not for a no source book, but just when a chapter is missing in the source (but is present in the alternate source). The change requested in testing was to bring the UI in line to the translate editor where the source does not display if it is not present.

If `no-source` is not a helpful class name, I can change it, if you like?

> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/2122#-:-Ni0lgzVCS11xyJfeFgP:b2qhymq)* status: 27 of 30 files reviewed, 1 unresolved discussion (waiting on @siltomato)

___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-generation-steps/draft-generation-steps.component.ts` line 32 at r8](https://reviewable.io/reviews/sillsdev/web-xforge/2122#-Ni0JhwY4BT0QFmNEplX:-Ni0nWx5-Z4hrkOZw0Qh:bb1gepz) ([raw file](https://github.com/sillsdev/web-xforge/blob/1cf41f693ebdd31ee287c5c1f36f707905ae022e/src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-generation-steps/draft-generation-steps.component.ts#L32)):*
<details><summary><i>Previously, siltomato wrote…</i></summary><blockquote>

Optional chaining `?` not needed after `draftConfig`
</blockquote></details>

Thank you! My IDE's intellisense misled me!

**Review by siltomato — CHANGES_REQUESTED** [review]
Ok, I think I understand.  The draft is done with the alternate source, but displayed with project source (which may not have a source book that the alternate source used for drafting had)?

Would it be possible to include a comment on the `hasSource` field to describe this rationale?

> Reviewed 1 of 7 files at r8, 2 of 2 files at r9, 1 of 1 files at r10, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/2122#-:-Ni0pjfo7Of8wqIHKMPL:bixbqz8)* status: all files reviewed, 1 unresolved discussion (waiting on @pmachapman)

___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-viewer/draft-viewer.component.ts` line 45 at r9](https://reviewable.io/reviews/sillsdev/web-xforge/2122#-Ni0rI2N885zRSC_j-Qz:-Ni0rI2N885zRSC_j-R-:b-tyek82) ([raw file](https://github.com/sillsdev/web-xforge/blob/21d9a25d157da68b9581cc611035f92255a2b958/src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-viewer/draft-viewer.component.ts#L45)):*
> ```XML
>   isOnline = this.onlineStatusService.isOnline;
> 
>   hasSource = false;
> ```

A comment may be helpful here as suggested in summary.  Also, do you think a name change to something like `bookHasSource` may be less ambiguous?

**Review by pmachapman — COMMENTED** [review]
> Would it be possible to include a comment on the `hasSource` field to describe this rationale?

No problem. Let me know if the comment is clearer or has made it murkier.

> The draft is done with the alternate source, but displayed with project source (which may not have a source book that the alternate source used for drafting had)?

Yes.

> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/2122#-:-Ni0thlOAuvH1r6tQx-G:b-ql14uo)* status: 29 of 31 files reviewed, 1 unresolved discussion (waiting on @siltomato)

___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-viewer/draft-viewer.component.ts` line 45 at r9](https://reviewable.io/reviews/sillsdev/web-xforge/2122#-Ni0rI2N885zRSC_j-Qz:-Ni0tRRY3U3iwVc9uMWe:bnhb3u4) ([raw file](https://github.com/sillsdev/web-xforge/blob/21d9a25d157da68b9581cc611035f92255a2b958/src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-viewer/draft-viewer.component.ts#L45)):*
<details><summary><i>Previously, siltomato wrote…</i></summary><blockquote>

A comment may be helpful here as suggested in summary.  Also, do you think a name change to something like `bookHasSource` may be less ambiguous?
</blockquote></details>

Great idea - I have renamed it.

**Review by siltomato — CHANGES_REQUESTED** [review]
I made a couple suggestions below that clarified the comments a bit in my reading.

> Reviewed 2 of 2 files at r11, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/2122#-:-Ni0ze7r1tvPpOvJayuo:be7jd6c)* status: all files reviewed, 2 unresolved discussions (waiting on @pmachapman)

___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-viewer/draft-viewer.component.ts` line 45 at r11](https://reviewable.io/reviews/sillsdev/web-xforge/2122#-Ni0z0GC4PKXw6F2VRKd:-Ni0z0GC4PKXw6F2VRKe:b5grsd7) ([raw file](https://github.com/sillsdev/web-xforge/blob/cfc22a7eb2b2b9b621e4c870925d397f1bbf4c07/src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-viewer/draft-viewer.component.ts#L45)):*
> ```XML
>   isOnline = this.onlineStatusService.isOnline;
> 
>   // This is so the source is hidden when it is missing (like the translate editor).
> ```

This is so the source is hidden when it is missing (behavior consistent with the translate editor).
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-viewer/draft-viewer.component.ts` line 47 at r11](https://reviewable.io/reviews/sillsdev/web-xforge/2122#-Ni0we269PC3b0MsHTwb:-Ni0we269PC3b0MsHTwc:b-7t411z) ([raw file](https://github.com/sillsdev/web-xforge/blob/cfc22a7eb2b2b9b621e4c870925d397f1bbf4c07/src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-viewer/draft-viewer.component.ts#L47)):*
> ```XML
>   // This is so the source is hidden when it is missing (like the translate editor).
>   // Note: When an alternate source is specified, that is used instead, so the source is then just used for display.
>   bookHasSource = false;
> ```

...so the source is then just used for display, and may not include some books contained in the alternate source.

**Review by pmachapman — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/2122)* status: 30 of 31 files reviewed, 2 unresolved discussions (waiting on @siltomato)

___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-viewer/draft-viewer.component.ts` line 45 at r11](https://reviewable.io/reviews/sillsdev/web-xforge/2122#-Ni0z0GC4PKXw6F2VRKd:-Ni11jQrDjzcb6t3OXlt:b-896fix) ([raw file](https://github.com/sillsdev/web-xforge/blob/cfc22a7eb2b2b9b621e4c870925d397f1bbf4c07/src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-viewer/draft-viewer.component.ts#L45)):*
<details><summary><i>Previously, siltomato wrote…</i></summary><blockquote>

This is so the source is hidden when it is missing (behavior consistent with the translate editor).
</blockquote></details>

Done.
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-viewer/draft-viewer.component.ts` line 47 at r11](https://reviewable.io/reviews/sillsdev/web-xforge/2122#-Ni0we269PC3b0MsHTwb:-Ni11jrX44F2uS8FBIQf:bf3cw9g) ([raw file](https://github.com/sillsdev/web-xforge/blob/cfc22a7eb2b2b9b621e4c870925d397f1bbf4c07/src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-viewer/draft-viewer.component.ts#L47)):*
<details><summary><i>Previously, siltomato wrote…</i></summary><blockquote>

...so the source is then just used for display, and may not include some books contained in the alternate source.
</blockquote></details>

Done. With some wording tweaks.

**Review by siltomato — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r12, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/2122#-:-Ni134HY0N9KxCMzlBCb:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @pmachapman)

___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-viewer/draft-viewer.component.ts` line 47 at r11](https://reviewable.io/reviews/sillsdev/web-xforge/2122#-Ni0we269PC3b0MsHTwb:-Ni12uKO0wfouuOm18BC:bdu5b1i) ([raw file](https://github.com/sillsdev/web-xforge/blob/cfc22a7eb2b2b9b621e4c870925d397f1bbf4c07/src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-viewer/draft-viewer.component.ts#L47)):*
<details><summary><i>Previously, pmachapman (Peter Chapman) wrote…</i></summary><blockquote>

Done. With some wording tweaks.
</blockquote></details>

Much better, thanks!

**Pull request merged**
