### PR TITLE
SF-1771 Add help links to footer

### PR DESCRIPTION
**Pull request by nigel-wells**
- Added Help and Community Support links to the home footer
- Adjusted how footer link margins work responsively

- - -
This change is [Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1544)

### CODE REVIEW

**Review by Nateowami — COMMENTED** [review]
> Reviewed 4 of 6 files at r1.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1544)* status: 4 of 6 files reviewed, 1 unresolved discussion (waiting on @nigel-wells)

___
*[`src/SIL.XForge.Scripture/wwwroot/scss/_footer.scss` line 1 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/1544#-NEd8s3iD-mrD1IMcg2Y:-NEd8s3iD-mrD1IMcg2Z:b-vt1akj) ([raw file](https://github.com/sillsdev/web-xforge/blob/0423eff53db664e61b08368d92dace5b52d3cd12/src/SIL.XForge.Scripture/wwwroot/scss/_footer.scss#L1)):*
> ```SCSS
> $linksBreakpoint: 995px;
> ```

What if the strings are localized and end up significantly longer? Does using a specific breakpoint work in that case? I would hope the links would flow dynamically based on their size.

**Review by nigel-wells — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1544)* status: 3 of 6 files reviewed, 1 unresolved discussion (waiting on @Nateowami)

___
*[`src/SIL.XForge.Scripture/wwwroot/scss/_footer.scss` line 1 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/1544#-NEd8s3iD-mrD1IMcg2Y:-NEhF0mX3DfUONV-tGjW:b-gdt1tf) ([raw file](https://github.com/sillsdev/web-xforge/blob/0423eff53db664e61b08368d92dace5b52d3cd12/src/SIL.XForge.Scripture/wwwroot/scss/_footer.scss#L1)):*
<details><summary><i>Previously, Nateowami (Nathaniel Paulus) wrote…</i></summary><blockquote>

What if the strings are localized and end up significantly longer? Does using a specific breakpoint work in that case? I would hope the links would flow dynamically based on their size.
</blockquote></details>

It did break on to two lines for other languages. I've adjusted it again so that the 2 lines are left aligned on desktop but centered on tablet and below. If it wraps on desktop then I decided to keep the links together rather than wrapping under the copyright text - I think it looks ok but let me know what you think. On tablet and below it works fine.

**Review by Nateowami — COMMENTED** [review]
I mostly reviewed this but ran out of time for the last file (the actual CSS change). Functionally looks good. One suggested code change.

> Reviewed 1 of 6 files at r1, 1 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1544#-:-NEiRufm6hBSv2RTzEqf:b-dw9gvx)* status: 5 of 6 files reviewed, 1 unresolved discussion (waiting on @nigel-wells)

___
*[`src/SIL.XForge.Scripture/Pages/Shared/Components/Footer/Default.cshtml` line 9 at r2](https://reviewable.io/reviews/sillsdev/web-xforge/1544#-NEiQhuzE18BVTZa4Yh3:-NEiQhuzE18BVTZa4Yh4:b-2vlol2) ([raw file](https://github.com/sillsdev/web-xforge/blob/390e44e085781222e0309399a70fb76b57c35b94/src/SIL.XForge.Scripture/Pages/Shared/Components/Footer/Default.cshtml#L9)):*
> ```razor
> 
> @{
>     var requestCulture = Context.Features.Get<IRequestCultureFeature>();
> ```

It took me a bit to understand the `.Count() > 0` part (not that that's a confusing concept, but it's hard to work out the context it's in).

I think this can be simplified a bit:
``` csharp
    var requestCulture = Context.Features.Get<IRequestCultureFeature>();
    var locale = LocOptions.Value.SupportedUICultures.Where(c =>
    SharedResource.Cultures[c.IetfLanguageTag].Tags.Contains(@requestCulture.RequestCulture.UICulture.Name)
    ).Select(c => SharedResource.Cultures[c.IetfLanguageTag]).First();
    var helps = "https://help.scriptureforge.org/" + (locale.Helps ?? "en");
```

**Review by nigel-wells — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1544)* status: 5 of 6 files reviewed, 1 unresolved discussion (waiting on @Nateowami)

___
*[`src/SIL.XForge.Scripture/Pages/Shared/Components/Footer/Default.cshtml` line 9 at r2](https://reviewable.io/reviews/sillsdev/web-xforge/1544#-NEiQhuzE18BVTZa4Yh3:-NFBU6iu8EV48aPpP08y:bckm0sk) ([raw file](https://github.com/sillsdev/web-xforge/blob/0a9d16d7aaa9c610723bf63fbcbd065ba0fe9eb2/src/SIL.XForge.Scripture/Pages/Shared/Components/Footer/Default.cshtml#L9)):*
> var locale = LocOptions.Value.SupportedUICultures.Where(c =>
>     SharedResource.Cultures[c.IetfLanguageTag].Tags.Contains(@requestCulture.RequestCulture.UICulture.Name)
>     ).Select(c => SharedResource.Cultures[c.IetfLanguageTag]).First();
>     var helps = "https://help.scriptureforge.org/" + (locale.Helps ?? "en");
That works better - thanks.

**Review by Nateowami — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1544#-:-NFBUue-7vNs4thGWzIV:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @nigel-wells)

**Pull request merged**
