### PR TITLE
SF-1107 Access answer audio through cache

### PR DESCRIPTION
**Pull request by RaymondLuong3**
* The answers component loads audio content through the cache
* Audio cache gets updated anytime local audio is uploaded
* When browser or add-to-homescreen is re-opened it will play cached answers

---
This change is [Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/848)

### CODE REVIEW

**Review by nigel-wells — CHANGES_REQUESTED** [review]
Looking good - just a couple of thoughts below.

> Reviewed 6 of 6 files at r1.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/848#-:-MKHYbSw6I5DAX_djqf_:bt9vnej)* status: all files reviewed, 4 unresolved discussions (waiting on @RaymondLuong3)

___
*[src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-answers/checking-answers.component.ts, line 134 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/848#-MKHTqsA0L4rkhUimNOy:-MKHTqsA0L4rkhUimNOz:b-6z0oai) ([raw file](https://github.com/sillsdev/web-xforge/blob/b88ac0f01df9274d2dee820fae893aeae1db69b7/src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-answers/checking-answers.component.ts#L134)):*
> ```XML
>   answersHighlightStatus: Map<string, boolean> = new Map<string, boolean>();
>   questionUrl?: string;
>   answerUrls: { [answerId: string]: string } = {};
> ```

Perhaps we could use a `Map` instead as that is what we tend to use throughout the rest of our codebase
___
*[src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-answers/checking-answers.component.ts, line 332 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/848#-MKHSsy81RHU2k6wSeXd:-MKHSsy81RHU2k6wSeXe:bcqugi5) ([raw file](https://github.com/sillsdev/web-xforge/blob/b88ac0f01df9274d2dee820fae893aeae1db69b7/src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-answers/checking-answers.component.ts#L332)):*
> ```XML
>       return;
>     }
>     const blob = await this.questionDoc.getFileContents(FileType.Audio, this.questionDoc.data.dataId);
> ```

With the above check no longer looking at `data.audioUrl` for `null` then we'll want to add it in here or potentially move `this.answerUrls()` further up
___
*[src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-answers/checking-answers.component.ts, line 348 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/848#-MKHUW3Z1HSIGhoQ2E_7:-MKHUW3Z1HSIGhoQ2E_8:b-fd7ecf) ([raw file](https://github.com/sillsdev/web-xforge/blob/b88ac0f01df9274d2dee820fae893aeae1db69b7/src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-answers/checking-answers.component.ts#L348)):*
> ```XML
>       const audio: Blob | undefined = await this.questionDoc.getFileContents(FileType.Audio, answer.dataId);
>       // default to the answer's audioUrl to show the audio unavailable icon when offline and audio is not cached
>       this.answerUrls[answer.dataId] = audio == null ? answer.audioUrl : URL.createObjectURL(audio);
> ```

What do you think of the idea of having one collection of file URLs and their source? This way it could work for audio files, question files, and potentially anything else in the future i.e. attachments. You could then have one function that does these checks which are mostly the same as the question ones above.
___
*[src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-audio-player/checking-audio-player.component.ts, line 52 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/848#-MKHVKrT5ooW-ML4CsJE:-MKHVKrT5ooW-ML4CsJF:b6kng8k) ([raw file](https://github.com/sillsdev/web-xforge/blob/b88ac0f01df9274d2dee820fae893aeae1db69b7/src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-audio-player/checking-audio-player.component.ts#L52)):*
> ```XML
> 
>     this.audio.addEventListener('error', () => {
>       this.localUrlError = isLocalBlobUrl(this.audio.src) ? true : false;
> ```

What are the instances where the `HTMLAudioElement` would emit an error? Couldn't an error still happen even if it happens to be locally cached?

**Review by RaymondLuong3 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/848)* status: all files reviewed, 4 unresolved discussions (waiting on @nigel-wells)

___
*[src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-answers/checking-answers.component.ts, line 134 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/848#-MKHTqsA0L4rkhUimNOy:-MKaMgwd4C6XEV89R1Qy:b-g32f8b) ([raw file](https://github.com/sillsdev/web-xforge/blob/b88ac0f01df9274d2dee820fae893aeae1db69b7/src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-answers/checking-answers.component.ts#L134)):*
<details><summary><i>Previously, nigel-wells (Nigel Wells) wrote…</i></summary><blockquote>

Perhaps we could use a `Map` instead as that is what we tend to use throughout the rest of our codebase
</blockquote></details>

Ok, I've made a revision to use a map. Good thinking.
___
*[src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-answers/checking-answers.component.ts, line 332 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/848#-MKHSsy81RHU2k6wSeXd:-MKaMmVT2-jawYdQgQIq:b6f9fb9) ([raw file](https://github.com/sillsdev/web-xforge/blob/b88ac0f01df9274d2dee820fae893aeae1db69b7/src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-answers/checking-answers.component.ts#L332)):*
<details><summary><i>Previously, nigel-wells (Nigel Wells) wrote…</i></summary><blockquote>

With the above check no longer looking at `data.audioUrl` for `null` then we'll want to add it in here or potentially move `this.answerUrls()` further up
</blockquote></details>

It seems that we do want to call `getFileContents()` regardless of whether `audioUrl` is or is not null so that indexedDB can be updated.
___
*[src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-answers/checking-answers.component.ts, line 348 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/848#-MKHUW3Z1HSIGhoQ2E_7:-MKaNDx05tkPEX9hFHhc:b-fgd6yg) ([raw file](https://github.com/sillsdev/web-xforge/blob/b88ac0f01df9274d2dee820fae893aeae1db69b7/src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-answers/checking-answers.component.ts#L348)):*
<details><summary><i>Previously, nigel-wells (Nigel Wells) wrote…</i></summary><blockquote>

What do you think of the idea of having one collection of file URLs and their source? This way it could work for audio files, question files, and potentially anything else in the future i.e. attachments. You could then have one function that does these checks which are mostly the same as the question ones above.
</blockquote></details>

That's a good idea. I'll make the refactor.
___
*[src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-audio-player/checking-audio-player.component.ts, line 52 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/848#-MKHVKrT5ooW-ML4CsJE:-MKaNMdp0b85ZA9un9gX:bnu64ty) ([raw file](https://github.com/sillsdev/web-xforge/blob/b88ac0f01df9274d2dee820fae893aeae1db69b7/src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-audio-player/checking-audio-player.component.ts#L52)):*
<details><summary><i>Previously, nigel-wells (Nigel Wells) wrote…</i></summary><blockquote>

What are the instances where the `HTMLAudioElement` would emit an error? Couldn't an error still happen even if it happens to be locally cached?
</blockquote></details>

I can't say that I know the full list of things that will cause the error event, but this is primarily so that we can set `localUrlError`. If we care about errors coming from content on the server, that can be added later.

**Review by nigel-wells — APPROVED** [review]
Yes I like what you've done there - looks much cleaner now as well. Just one minor non blocking point.

> Reviewed 3 of 3 files at r2.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/848#-:-MKbQ-Or5WztM0lH02yC:bnu30kc)* status: all files reviewed, 2 unresolved discussions (waiting on @RaymondLuong3)

___
*[src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-answers/checking-answers.component.ts, line 326 at r2](https://reviewable.io/reviews/sillsdev/web-xforge/848#-MKbNOD05V0tGLeldbIQ:-MKbNOD17imuBx-REQGG:b-1g51pm) ([raw file](https://github.com/sillsdev/web-xforge/blob/a00a1647ac39eefa84638e249e9aa827129e64e7/src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-answers/checking-answers.component.ts#L326)):*
> ```XML
> 
>   getFileSource(url: string | undefined): string | undefined {
>     if (url == null || url === '') {
> ```

Perhaps these checks can simply be part of the `if` statement below. `undefined` is already the case if nothing was found in `this.flieSources.has()` so no need to return it specifically
___
*[src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-audio-player/checking-audio-player.component.ts, line 52 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/848#-MKHVKrT5ooW-ML4CsJE:-MKbPFq60wCcnBYWlL7I:b-epykql) ([raw file](https://github.com/sillsdev/web-xforge/blob/b88ac0f01df9274d2dee820fae893aeae1db69b7/src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-audio-player/checking-audio-player.component.ts#L52)):*
<details><summary><i>Previously, RaymondLuong3 (Raymond Luong) wrote…</i></summary><blockquote>

I can't say that I know the full list of things that will cause the error event, but this is primarily so that we can set `localUrlError`. If we care about errors coming from content on the server, that can be added later.
</blockquote></details>

Ah right, sorry, I thought you were changing an existing `error` check but this is new code that you've introduced.

**Review by RaymondLuong3 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/848)* status: 5 of 6 files reviewed, 2 unresolved discussions (waiting on @nigel-wells)

___
*[src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-answers/checking-answers.component.ts, line 326 at r2](https://reviewable.io/reviews/sillsdev/web-xforge/848#-MKbNOD05V0tGLeldbIQ:-MKebo84BrwsugG0JvFP:b-896fix) ([raw file](https://github.com/sillsdev/web-xforge/blob/a00a1647ac39eefa84638e249e9aa827129e64e7/src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-answers/checking-answers.component.ts#L326)):*
<details><summary><i>Previously, nigel-wells (Nigel Wells) wrote…</i></summary><blockquote>

Perhaps these checks can simply be part of the `if` statement below. `undefined` is already the case if nothing was found in `this.flieSources.has()` so no need to return it specifically
</blockquote></details>

Done.
___
*[src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-audio-player/checking-audio-player.component.ts, line 52 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/848#-MKHVKrT5ooW-ML4CsJE:-MKebotK1Cmk23txm08L:b-coeb0f) ([raw file](https://github.com/sillsdev/web-xforge/blob/b88ac0f01df9274d2dee820fae893aeae1db69b7/src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-audio-player/checking-audio-player.component.ts#L52)):*
<details><summary><i>Previously, nigel-wells (Nigel Wells) wrote…</i></summary><blockquote>

Ah right, sorry, I thought you were changing an existing `error` check but this is new code that you've introduced.
</blockquote></details>

Not a problem :)

**Pull request merged**
