### PR TITLE
SF-2017 Convert suggestions component to Material

### PR DESCRIPTION
**Pull request by josephmyers**
- - -
This change is [Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1856)

### CODE REVIEW

**Comment by josephmyers** [comment]
I added a basic storybook test to the existing ones, but I notice there are no unit tests for this component. This could be due to the pretty beefy TextComponent @Input. I'm not sure how to initialize one of those for use in Storybook; however, I can create a test spec, if desired.

**Review by Nateowami — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1856)* status: all files reviewed, 3 unresolved discussions (waiting on @josephmyers and @RaymondLuong3)

___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/suggestions.component.scss` line 62 at r2](https://reviewable.io/reviews/sillsdev/web-xforge/1856#-NWDkzZg3FConCjdxBXp:-NWDxR1--VAP2_5_DU3o:b8w9j6l) ([raw file](https://github.com/sillsdev/web-xforge/blob/df3d8395d375ef9e91625af74765bc892901975a/src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/suggestions.component.scss#L62)):*
<details><summary><i>Previously, RaymondLuong3 (Raymond Luong) wrote…</i></summary><blockquote>

There is a lighterTextColor defined in ClientApp/src/_variables.scss. Might that be what you need? I like the higher contrast of that too. If not, you can define a new color there and import it here.
</blockquote></details>

Also, avoid using transparency to set the color of text. Some typefaces (e.g. for Arabic) have overlapping glyphs that look bad when the color is transparent.

**Review by josephmyers — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1856)* status: 1 of 4 files reviewed, 3 unresolved discussions (waiting on @RaymondLuong3)

___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/suggestions.component.scss` line 62 at r2](https://reviewable.io/reviews/sillsdev/web-xforge/1856#-NWDkzZg3FConCjdxBXp:-NWFpdfR6rTV_qPvmjfD:b-896fix) ([raw file](https://github.com/sillsdev/web-xforge/blob/df3d8395d375ef9e91625af74765bc892901975a/src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/suggestions.component.scss#L62)):*
<details><summary><i>Previously, Nateowami (Nathaniel Paulus) wrote…</i></summary><blockquote>

Also, avoid using transparency to set the color of text. Some typefaces (e.g. for Arabic) have overlapping glyphs that look bad when the color is transparent.



</blockquote></details>

Done.
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/suggestions.component.ts` line 83 at r2](https://reviewable.io/reviews/sillsdev/web-xforge/1856#-NWDm2Yx3Sz8zNp7DC2U:-NWFpxUVE-RvPmJq9CVQ:b-896fix) ([raw file](https://github.com/sillsdev/web-xforge/blob/df3d8395d375ef9e91625af74765bc892901975a/src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/suggestions.component.ts#L83)):*
<details><summary><i>Previously, RaymondLuong3 (Raymond Luong) wrote…</i></summary><blockquote>

Add a type here.
</blockquote></details>

Done.
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/suggestions.stories.ts` line 45 at r2](https://reviewable.io/reviews/sillsdev/web-xforge/1856#-NWDmC7L8uDmuP_wj9DQ:-NWFq35m5O0yxih5V3k6:b-896fix) ([raw file](https://github.com/sillsdev/web-xforge/blob/df3d8395d375ef9e91625af74765bc892901975a/src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/suggestions.stories.ts#L45)):*
<details><summary><i>Previously, RaymondLuong3 (Raymond Luong) wrote…</i></summary><blockquote>

Add a type here.
</blockquote></details>

Done.

**Review by Nateowami — CHANGES_REQUESTED** [review]
> Reviewed 1 of 3 files at r3.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1856)* status: 2 of 4 files reviewed, 5 unresolved discussions (waiting on @josephmyers and @RaymondLuong3)

___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/suggestions.component.ts` line 82 at r3](https://reviewable.io/reviews/sillsdev/web-xforge/1856#-NWI9IRi5NfA-GPmg706:-NWI9IRi5NfA-GPmg707:b-tw6a6) ([raw file](https://github.com/sillsdev/web-xforge/blob/659d1e75a435d3cfc0beef8ccb88521abe36e045/src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/suggestions.component.ts#L82)):*
> ```XML
> 
>   private setSelectedIndex(index: number): void {
>     if (this.list != null) {
> ```

How about:
``` ts
    const option: MatListOption | undefined = this.list?.options.get(index);
    if (option != null) option.selected = true;
```
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/suggestions.stories.ts` line 39 at r3](https://reviewable.io/reviews/sillsdev/web-xforge/1856#-NWI8b7C-avtxwMu1l7m:-NWI8b7C-avtxwMu1l7n:b-7xwvxo) ([raw file](https://github.com/sillsdev/web-xforge/blob/659d1e75a435d3cfc0beef8ccb88521abe36e045/src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/suggestions.stories.ts#L39)):*
> ```XML
> };
> 
> export const DefaultHasFirstSelected: Story = {
> ```

As far as I can tell, DefaultHasFirstSelected is exactly identical to Default, except that a play function has been added. Is there a reason to not just add the play function to default?

**Review by josephmyers — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1856)* status: 2 of 4 files reviewed, 5 unresolved discussions (waiting on @Nateowami and @RaymondLuong3)

___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/suggestions.component.ts` line 82 at r3](https://reviewable.io/reviews/sillsdev/web-xforge/1856#-NWI9IRi5NfA-GPmg706:-NWIIfkD1vHzUk0TUHcb:b-896fix) ([raw file](https://github.com/sillsdev/web-xforge/blob/659d1e75a435d3cfc0beef8ccb88521abe36e045/src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/suggestions.component.ts#L82)):*
<details><summary><i>Previously, Nateowami (Nathaniel Paulus) wrote…</i></summary><blockquote>

How about:
``` ts
    const option: MatListOption | undefined = this.list?.options.get(index);
    if (option != null) option.selected = true;
```
</blockquote></details>

Done.
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/suggestions.stories.ts` line 39 at r3](https://reviewable.io/reviews/sillsdev/web-xforge/1856#-NWI8b7C-avtxwMu1l7m:-NWIIqW36qe-TQT6_bAZ:b-896fix) ([raw file](https://github.com/sillsdev/web-xforge/blob/659d1e75a435d3cfc0beef8ccb88521abe36e045/src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/suggestions.stories.ts#L39)):*
<details><summary><i>Previously, Nateowami (Nathaniel Paulus) wrote…</i></summary><blockquote>

As far as I can tell, DefaultHasFirstSelected is exactly identical to Default, except that a play function has been added. Is there a reason to not just add the play function to default? 
</blockquote></details>

Done.

**Review by Nateowami — APPROVED** [review]
> Reviewed 1 of 3 files at r2, 1 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1856)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @josephmyers)

**Review by Nateowami — APPROVED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1856)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @josephmyers)

**Pull request merged**
