### PR TITLE
SF-2805 Only add source tabs if user can access the source

### PR DESCRIPTION
**Pull request by josephmyers**
This change is [Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/2724)

### CODE REVIEW

**Review by RaymondLuong3 — CHANGES_REQUESTED** [review]
> Reviewed 4 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/2724)* status: all files reviewed, 2 unresolved discussions (waiting on @josephmyers)

___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/core/permissions.service.ts` line 39 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/2724#-O769KamCEPjq36LuY--:-O769KamCEPjq36LuY-0:byqqcex) ([raw file](https://github.com/sillsdev/web-xforge/blob/b277444196c10c8710ec20d11cdba94bf38230b9/src/SIL.XForge.Scripture/ClientApp/src/app/core/permissions.service.ts#L39)):*
> ```XML
>   }
> 
>   async isUserOnProject(projectId: string): Promise<boolean> {
> ```

This could be a private method, but I can see how it would be useful for the future.
Oh, I do see that we are using this. I imagine we are just interested if the user is on the project and not if the user has permission to see the text. Wait, what would happen if the user does not have access to see the text? Would the source panel disappear. Then would this bug be possible again?



_Code quote:_
```XML
  async isUserOnProject(projectId: string): Promise<boolean> {
```
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/core/permissions.service.ts` line 41 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/2724#-O769WKC4B242AlXwaEB:-O769WKC4B242AlXwaEC:b-qcjc0e) ([raw file](https://github.com/sillsdev/web-xforge/blob/b277444196c10c8710ec20d11cdba94bf38230b9/src/SIL.XForge.Scripture/ClientApp/src/app/core/permissions.service.ts#L41)):*
> ```XML
>   async isUserOnProject(projectId: string): Promise<boolean> {
>     const currentUserDoc = await this.userService.getCurrentUser();
>     const userOnProject: boolean =
> ```

Nit: You could just return this without assigning it.



_Code quote:_
```XML
    const userOnProject: boolean =
```

**Review by josephmyers — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/2724)* status: 3 of 4 files reviewed, 1 unresolved discussion (waiting on @RaymondLuong3)

___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/core/permissions.service.ts` line 39 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/2724#-O769KamCEPjq36LuY--:-O76ei_6D8k1FTHM7HAi:b-ptxsxa) ([raw file](https://github.com/sillsdev/web-xforge/blob/b277444196c10c8710ec20d11cdba94bf38230b9/src/SIL.XForge.Scripture/ClientApp/src/app/core/permissions.service.ts#L39)):*
<details><summary><i>Previously, RaymondLuong3 (Raymond Luong) wrote…</i></summary><blockquote>

This could be a private method, but I can see how it would be useful for the future.
Oh, I do see that we are using this. I imagine we are just interested if the user is on the project and not if the user has permission to see the text. Wait, what would happen if the user does not have access to see the text? Would the source panel disappear. Then would this bug be possible again?
</blockquote></details>

Is it possible to be on a project and not able to view text? I'm not aware of a way to do this, but maybe I'm missing something?

**Review by RaymondLuong3 — APPROVED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/2724)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @josephmyers)

___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/core/permissions.service.ts` line 39 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/2724#-O769KamCEPjq36LuY--:-O7ACWkoBsG3laRXNZ7O:bdvcuq8) ([raw file](https://github.com/sillsdev/web-xforge/blob/b277444196c10c8710ec20d11cdba94bf38230b9/src/SIL.XForge.Scripture/ClientApp/src/app/core/permissions.service.ts#L39)):*
<details><summary><i>Previously, josephmyers wrote…</i></summary><blockquote>

Is it possible to be on a project and not able to view text? I'm not aware of a way to do this, but maybe I'm missing something?
</blockquote></details>

When a source text does not exist for a book, then the source panel disappears. So I tested this out, but I did not see any issues. It looks like it is working well.

**Comment by Nateowami** [comment]
Your use of the plural "tabs" in the title has me somewhat concerned. Does this mean the entire tab group will not be available? Or does it mean don't show the source tab, but do provide the tab group (so the draft and other things can still be opened)?

**Comment by josephmyers** [comment]
The group is still added, for sure, but I'm seeing now that the unit test names are misleading (not my introduction, but I didn't make it better). They indicate the groups, but they're testing the tabs. I'll make a followup PR. Thanks

**Pull request merged**
