### PR TITLE
Allow tools to connect to the ShareDB server locally

### PR DESCRIPTION
**Pull request by ddaspit**
- includes a script to revert text docs to a previous version

---
This change is [Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1058)

### CODE REVIEW

**Review by Nateowami — APPROVED** [review]
:lgtm:

> Reviewed 1 of 4 files at r1, 1 of 1 files at r2, 2 of 2 files at r3, 2 of 2 files at r5.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1058#-:-MbK2i2I9k7OaJ5uNBei:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ddaspit)

___
*[src/RealtimeServer/common/web-socket-stream-listener.ts, line 11 at r3](https://reviewable.io/reviews/sillsdev/web-xforge/1058#-MbK1n7SEHyLDAeyzgET:-MbK1n7T4yRhanwLDETO:bpgcqqz) ([raw file](https://github.com/sillsdev/web-xforge/blob/e2439320a07413cf04a592791e63716a1f3aacb7/src/RealtimeServer/common/web-socket-stream-listener.ts#L11)):*
> ```XML
> 
> function isLocalRequest(request: http.IncomingMessage): boolean {
>   const addr = request.connection.remoteAddress;
> ```

I'm assuming this can't be spoofed. I don't actually know that to be the case though.

**Review by irahopkinson — APPROVED** [review]
:lgtm: 

> Reviewed 1 of 4 files at r1, 1 of 1 files at r2, 2 of 2 files at r3, 2 of 2 files at r5.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1058#-:-MbK1r4r-4rD0dy0WOFd:bg7igkv)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ddaspit)

**Comment by Nateowami** [comment]
@irahopkinson Is it intentional that this was not squashed? (Just want to make sure I'm not missing part of the strategy).

**Review by ddaspit — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1058)* status: :shipit: complete! all files reviewed, all discussions resolved

___
*[src/RealtimeServer/common/web-socket-stream-listener.ts, line 11 at r3](https://reviewable.io/reviews/sillsdev/web-xforge/1058#-MbK1n7SEHyLDAeyzgET:-MbKE4nv6dGtAR7Bhf93:b-canfxy) ([raw file](https://github.com/sillsdev/web-xforge/blob/e2439320a07413cf04a592791e63716a1f3aacb7/src/RealtimeServer/common/web-socket-stream-listener.ts#L11)):*
<details><summary><i>Previously, Nateowami (Nathaniel Paulus) wrote…</i></summary><blockquote>

I'm assuming this can't be spoofed. I don't actually know that to be the case though.
</blockquote></details>

This is the raw socket remote address, which you shouldn't be able to spoof.

**Comment by irahopkinson** [comment]
@Nateowami when there is more than one author on a PR I only squash as much as I can for each author and then do a merge commit in order to keep all the authors attribution.

**Pull request merged**
