### PR TITLE
SF-2158 Support for uploading large audio files

### PR DESCRIPTION
**Pull request by pmachapman**
This Pull Request:
 * Allows audio file uploads of up to ~300MB (can be changed to any larger value as required)
 * Changes the audio upload endpoint to stream incoming data to a temporary file to allow large file upload support
 * Updated MP3 checking and audio file conversion to use the file path directly

- - -
This change is [Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1973)

### CODE REVIEW

**Comment by josephmyers** [comment]
The code looks good, but is there any way to test this? There's a good bit going on in the SFProjectsUploadController, and it'd be nice if I could test this out some. It'd also be nice to have some automated tests for it, though I understand if that's too difficult.

**Comment by josephmyers** [comment]
I just ran through your AC steps from JIRA, and I'm a little confused. I can't determine the difference your branch is making. I'm able to upload large audio files on both master and your branch.

Now, I do notice that refreshing the page makes the audio unavailable. But this happens on both branches, as well.

image

**Review by josephmyers — APPROVED** [review]
Thinking about this again, though I'm unable to see this broken on master, it's still working on this branch. So I don't see a reason to hold this up. I just wanted to make it clear that large files seem to be working for me before these changes

> Reviewed 7 of 7 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1973#-:-NaBOT_l-SEbnOLJ5aD7:b-eu40ej)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @pmachapman)

**Comment by pmachapman** [comment]
Uploading large files fails quietly on master with the following error in .NET (which is not displayed in the browser console). Logging out then logging back after uploading using the master branch shows "Audio Unavailable"

```
info: Microsoft.AspNetCore.Mvc.ViewFeatures.Filters.AutoValidateAntiforgeryTokenAuthorizationFilter[1]
      Antiforgery token validation failed. Unable to read the antiforgery request token from the posted form.
      Microsoft.AspNetCore.Antiforgery.AntiforgeryValidationException: Unable to read the antiforgery request token from the posted form.
       ---> Microsoft.AspNetCore.Server.Kestrel.Core.BadHttpRequestException: Request body too large. The max request body size is 100000000 bytes.
         at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.Http1ContentLengthMessageBody.OnReadStarting()
         at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.MessageBody.TryStartAsync()
         at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.Http1ContentLengthMessageBody.ReadAsyncInternal(CancellationToken cancellationToken)
         at System.Runtime.CompilerServices.PoolingAsyncValueTaskMethodBuilder`1.StateMachineBox`1.System.Threading.Tasks.Sources.IValueTaskSource<TResult>.GetResult(Int16 token)
         at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpRequestStream.ReadAsyncInternal(Memory`1 destination, CancellationToken cancellationToken)
         at Microsoft.AspNetCore.WebUtilities.BufferedReadStream.EnsureBufferedAsync(Int32 minCount, CancellationToken cancellationToken)
         at Microsoft.AspNetCore.WebUtilities.MultipartReaderStream.ReadAsync(Byte[] buffer, Int32 offset, Int32 count, CancellationToken cancellationToken)
         at Microsoft.AspNetCore.WebUtilities.StreamHelperExtensions.DrainAsync(Stream stream, ArrayPool`1 bytePool, Nullable`1 limit, CancellationToken cancellationToken)
         at Microsoft.AspNetCore.WebUtilities.MultipartReader.ReadNextSectionAsync(CancellationToken cancellationToken)
         at Microsoft.AspNetCore.Http.Features.FormFeature.InnerReadFormAsync(CancellationToken cancellationToken)
         at Microsoft.AspNetCore.Antiforgery.DefaultAntiforgeryTokenStore.GetRequestTokensAsync(HttpContext httpContext)
         --- End of inner exception stack trace ---
         at Microsoft.AspNetCore.Antiforgery.DefaultAntiforgeryTokenStore.GetRequestTokensAsync(HttpContext httpContext)
         at Microsoft.AspNetCore.Antiforgery.DefaultAntiforgery.ValidateRequestAsync(HttpContext httpContext)
         at Microsoft.AspNetCore.Mvc.ViewFeatures.Filters.ValidateAntiforgeryTokenAuthorizationFilter.OnAuthorizationAsync(AuthorizationFilterContext context)
info: Microsoft.AspNetCore.Mvc.RazorPages.Infrastructure.PageActionInvoker[3]
      Authorization failed for the request at filter 'Microsoft.AspNetCore.Mvc.ViewFeatures.Filters.AutoValidateAntiforgeryTokenAuthorizationFilter'.
```

**Comment by josephmyers** [comment]
Good enough for me. Thanks!

**Pull request merged**
