### PR TITLE
SF-1249 Disallow inviting checkers when checking is disabled

### PR DESCRIPTION
**Pull request by Nateowami**
This change is [Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1049)

### CODE REVIEW

**Review by irahopkinson — CHANGES_REQUESTED** [review]
This seems important enough of a change to have some tests. Also the current tests are failing.

> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1049#-:-MaWoHoV0jE38Xw34NyP:b9fculw)* status: all files reviewed, 1 unresolved discussion (waiting on @Nateowami)

___
*[src/SIL.XForge.Scripture/ClientApp/src/app/shared/share/share-control.component.ts, line 106 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/1049#-MaWok-xCU1uwRnjddNI:-MaWok-xCU1uwRnjddNJ:b-yrimtb) ([raw file](https://github.com/sillsdev/web-xforge/blob/f0b2da4250d49454dc0df94f2932e2d101ba8c56/src/SIL.XForge.Scripture/ClientApp/src/app/shared/share/share-control.component.ts#L106)):*
> ```
> .filter(r => r.canBeShared).filter(
> ```
Can't this be done with one pass through the filter or is it more efficient to go through twice?

**Review by Nateowami — COMMENTED** [review]
Fixing the tests for this turned out to be massively more difficult than anticipated. I still need to modify the tests a bit to cover this change better, but now at least they're not broken.

> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1049#-:-MaaiNWF7t4vVE9V9G7I:b-mtrtpp)* status: 0 of 4 files reviewed, 1 unresolved discussion (waiting on @irahopkinson)

___
*[src/SIL.XForge.Scripture/ClientApp/src/app/shared/share/share-control.component.ts, line 106 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/1049#-MaWok-xCU1uwRnjddNI:-MaagYpq3CuvuyW1nDg4:b-1fqv7f) ([raw file](https://github.com/sillsdev/web-xforge/blob/f0b2da4250d49454dc0df94f2932e2d101ba8c56/src/SIL.XForge.Scripture/ClientApp/src/app/shared/share/share-control.component.ts#L106)):*
<details><summary><i>Previously, irahopkinson (Ira Hopkinson) wrote…</i></summary><blockquote>

> ```
> .filter(r => r.canBeShared).filter(
> ```
Can't this be done with one pass through the filter or is it more efficient to go through twice?
</blockquote></details>

Syntactically it was a little simpler than a multi-line complex boolean expression. But after some changes I've made it a one-liner.

**Review by irahopkinson — CHANGES_REQUESTED** [review]
> Reviewed 4 of 4 files at r2.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1049)* status: all files reviewed, 1 unresolved discussion (waiting on @Nateowami)

___
*[src/SIL.XForge.Scripture/ClientApp/src/app/shared/share/share-control.component.ts, line 106 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/1049#-MaWok-xCU1uwRnjddNI:-Mapy87P6QllBKMuF6QU:bq0m9tp) ([raw file](https://github.com/sillsdev/web-xforge/blob/f0b2da4250d49454dc0df94f2932e2d101ba8c56/src/SIL.XForge.Scripture/ClientApp/src/app/shared/share/share-control.component.ts#L106)):*
<details><summary><i>Previously, Nateowami (Nathaniel Paulus) wrote…</i></summary><blockquote>

Syntactically it was a little simpler than a multi-line complex boolean expression. But after some changes I've made it a one-liner.
</blockquote></details>

Hmm... it was easier to read before, I think you'd best put it back the way it was, sorry for asking.

**Review by Nateowami — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1049)* status: 3 of 4 files reviewed, 1 unresolved discussion (waiting on @irahopkinson)

___
*[src/SIL.XForge.Scripture/ClientApp/src/app/shared/share/share-control.component.ts, line 106 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/1049#-MaWok-xCU1uwRnjddNI:-Maq2pzT6GM0qRO21-vr:b-896fix) ([raw file](https://github.com/sillsdev/web-xforge/blob/f0b2da4250d49454dc0df94f2932e2d101ba8c56/src/SIL.XForge.Scripture/ClientApp/src/app/shared/share/share-control.component.ts#L106)):*
<details><summary><i>Previously, irahopkinson (Ira Hopkinson) wrote…</i></summary><blockquote>

Hmm... it was easier to read before, I think you'd best put it back the way it was, sorry for asking.
</blockquote></details>

Done.

**Review by irahopkinson — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1049)* status: 3 of 4 files reviewed, 1 unresolved discussion (waiting on @irahopkinson and @Nateowami)

___
*[src/SIL.XForge.Scripture/ClientApp/src/app/shared/share/share-control.component.ts, line 106 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/1049#-MaWok-xCU1uwRnjddNI:-Maq4ehz7IIB6zyQhdeV:bjuqxu7) ([raw file](https://github.com/sillsdev/web-xforge/blob/f0b2da4250d49454dc0df94f2932e2d101ba8c56/src/SIL.XForge.Scripture/ClientApp/src/app/shared/share/share-control.component.ts#L106)):*
<details><summary><i>Previously, Nateowami (Nathaniel Paulus) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Actually the second filter also takes care of the `project == null` case so it was better all-round originally.

**Review by irahopkinson — COMMENTED** [review]
> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1049)* status: all files reviewed, 1 unresolved discussion (waiting on @Nateowami)

**Review by irahopkinson — APPROVED** [review]
:lgtm: 

> Reviewed 1 of 1 files at r4.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1049#-:-Maq5XfX7PfWx0KAlIf9:bg7igkv)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @Nateowami)

___
*[src/SIL.XForge.Scripture/ClientApp/src/app/shared/share/share-control.component.ts, line 106 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/1049#-MaWok-xCU1uwRnjddNI:-Maq5Pd47d6-dYyTG8B2:b-7bcogx) ([raw file](https://github.com/sillsdev/web-xforge/blob/f0b2da4250d49454dc0df94f2932e2d101ba8c56/src/SIL.XForge.Scripture/ClientApp/src/app/shared/share/share-control.component.ts#L106)):*
<details><summary><i>Previously, irahopkinson (Ira Hopkinson) wrote…</i></summary><blockquote>

Actually the second filter also takes care of the `project == null` case so it was better all-round originally.
</blockquote></details>

I've just fixed it my self after doing a prod build to check.

**Pull request merged**
