### PR TITLE
SF-2008 Justified share dialog buttons without reversing the row direction

### PR DESCRIPTION
**Pull request by josephmyers**
This change is [Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1874)

### CODE REVIEW

**Review by RaymondLuong3 — APPROVED** [review]
> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1874)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @josephmyers)

**Review by nigel-wells — CHANGES_REQUESTED** [review]
> Reviewed 1 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1874)* status: all files reviewed, 2 unresolved discussions (waiting on @josephmyers)

___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/shared/share/share-dialog.component.scss` line 51 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/1874#-NWj4g6yCaAZaaqKqvZq:-NWj4g6yCaAZaaqKqvZr:bqyqyv7) ([raw file](https://github.com/sillsdev/web-xforge/blob/719324cc55de64b3dec884f1e98df5fb6685b34c/src/SIL.XForge.Scripture/ClientApp/src/app/shared/share/share-dialog.component.scss#L51)):*
> ```SCSS
>   }
> }
> div[mat-dialog-actions] {
> ```

As mentioned in Slack, try removing the encapsulation rule on the component in order to stop having these CSS rules leaking out to the rest of the app. You'll need to check mobile viewport as I believe it was added specifically to address a scrolling issue.
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/shared/share/share-dialog.component.scss` line 53 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/1874#-NWj4ym43mT2WNEY6Qmx:-NWj4ym43mT2WNEY6Qmy:bv3lsl0) ([raw file](https://github.com/sillsdev/web-xforge/blob/719324cc55de64b3dec884f1e98df5fb6685b34c/src/SIL.XForge.Scripture/ClientApp/src/app/shared/share/share-dialog.component.scss#L53)):*
> ```SCSS
> div[mat-dialog-actions] {
>   display: flex;
>   flex-direction: row-reverse; /* This was done so the share button would receive the focus */
> ```

This will likely still be required as per my comment on Slack.

**Review by Nateowami — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1874)* status: all files reviewed, 2 unresolved discussions (waiting on @josephmyers and @nigel-wells)

___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/shared/share/share-dialog.component.scss` line 53 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/1874#-NWj4ym43mT2WNEY6Qmx:-NWj9ULo9_Ujq1DscMz6:bpj6q0w) ([raw file](https://github.com/sillsdev/web-xforge/blob/719324cc55de64b3dec884f1e98df5fb6685b34c/src/SIL.XForge.Scripture/ClientApp/src/app/shared/share/share-dialog.component.scss#L53)):*
<details><summary><i>Previously, nigel-wells (Nigel Wells) wrote…</i></summary><blockquote>

This will likely still be required as per my comment on Slack.
</blockquote></details>

I don't see the comment in Slack you're referring to.

**Comment by josephmyers** [comment]
> > _[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1874)_ status: all files reviewed, 2 unresolved discussions (waiting on @josephmyers and @nigel-wells)
> 
> _[`src/SIL.XForge.Scripture/ClientApp/src/app/shared/share/share-dialog.component.scss` line 53 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/1874#-NWj4ym43mT2WNEY6Qmx:-NWj9ULo9_Ujq1DscMz6:bpj6q0w) ([raw file](https://github.com/sillsdev/web-xforge/blob/719324cc55de64b3dec884f1e98df5fb6685b34c/src/SIL.XForge.Scripture/ClientApp/src/app/shared/share/share-dialog.component.scss#L53)):_
> 
> Previously, nigel-wells (Nigel Wells) wrote…
> I don't see the comment in Slack you're referring to.

We were messaging privately. I believe this is the relevant bit from Nigel:
"Thanks for checking in on this. It looks like encapsulation: ViewEncapsulation.None has been set on the ShareDialogComponent which is why the styles are leaking out to the rest of the app. From looking at the history of the commit that introduced it the fix was related to a scrollbar on mobile. I'd actually check to see if any of that is needed any more. The share dialog work had a heap of refactoring going on so it likely isn't actually required."

**Comment by josephmyers** [comment]
For mobile, I'm not seeing any scrolling at all. The current version of the dialog, at least, can fit on one screen for all the devices I tested. With regards to focus, I am seeing the following behavior, with and without the "row-reverse":
image
So after tapping the button to open the dialog, the focus remains on the button, not within the dialog. Tapping in the dialog turns that button back to its normal black. Maybe this is what the original code was trying to fix?

If it is, I can do so now. I've messed around with cdkFocusInitial before (as I mentioned to you), and it doesn't seem to work here, but maybe some other things here is preventing it.

**Review by nigel-wells — COMMENTED** [review]
Can you try with removing `encapsulation: ViewEncapsulation.None` from `share-dialog.compone.ts` as that is the reason the CSS rules are affecting other parts of the app as well as where you *may* see an issue with scrolling.

> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1874#-:-NWjjx9421N_RQDZ2xG8:b-ldh3nn)* status: all files reviewed, 2 unresolved discussions (waiting on @josephmyers)

**Comment by josephmyers** [comment]
> Can you try with removing `encapsulation: ViewEncapsulation.None` from `share-dialog.compone.ts` as that is the reason the CSS rules are affecting other parts of the app as well as where you _may_ see an issue with scrolling.
> 
> > _[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1874#-:-NWjjx9421N_RQDZ2xG8:b-ldh3nn)_ status: all files reviewed, 2 unresolved discussions (waiting on @josephmyers)

Removing that line also fixes the bug, and I believe it's better design overall. Looks like Nathaniel made [that change ](https://github.com/sillsdev/web-xforge/pull/1342)last year to fix another bug, this one caused by MDC and Material not playing nice together. Maybe as we move more to Material, this code becomes unnecessary?

**Review by Nateowami — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1874)* status: all files reviewed, 2 unresolved discussions (waiting on @josephmyers and @nigel-wells)

___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/shared/share/share-dialog.component.scss` line 53 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/1874#-NWj4ym43mT2WNEY6Qmx:-NWjmRjR3QfpPoL9MsB6:b441yg2) ([raw file](https://github.com/sillsdev/web-xforge/blob/719324cc55de64b3dec884f1e98df5fb6685b34c/src/SIL.XForge.Scripture/ClientApp/src/app/shared/share/share-dialog.component.scss#L53)):*
<details><summary><i>Previously, josephmyers wrote…</i></summary><blockquote>

We were messaging privately. I believe this is the relevant bit from Nigel:
"Thanks for checking in on this. It looks like encapsulation: ViewEncapsulation.None has been set on the ShareDialogComponent which is why the styles are leaking out to the rest of the app. From looking at the history of the commit that introduced it the fix was related to a scrollbar on mobile. I'd actually check to see if any of that is needed any more. The share dialog work had a heap of refactoring going on so it likely isn't actually required."

</blockquote></details>

I believe the reason I did so at the time was because `::ng-deep` is deprecated. However, it was the wrong choice. Reversing it would be an improvement.

**Review by nigel-wells — CHANGES_REQUESTED** [review]
> Reviewed 1 of 2 files at r2, 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1874)* status: all files reviewed, 2 unresolved discussions (waiting on @josephmyers)

___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/shared/share/share-dialog.component.scss` line 6 at r3](https://reviewable.io/reviews/sillsdev/web-xforge/1874#-NWk9elf9VsHakjAEV1f:-NWk9elf9VsHakjAEV1g:b-k38nkl) ([raw file](https://github.com/sillsdev/web-xforge/blob/71fa837ef09105f352d258cec1390ef38ca7c567/src/SIL.XForge.Scripture/ClientApp/src/app/shared/share/share-dialog.component.scss#L6)):*
> ```SCSS
>   margin-bottom: 0.25em;
>   display: flex;
>   align-items: center;
> ```

Was this still supposed to change or are we changing all dialogs to have the title centered?

**Review by josephmyers — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1874)* status: all files reviewed (commit messages unreviewed), 2 unresolved discussions (waiting on @nigel-wells)

___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/shared/share/share-dialog.component.scss` line 51 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/1874#-NWj4g6yCaAZaaqKqvZq:-NWkPJwNEJA0QKl_vBRT:b-896fix) ([raw file](https://github.com/sillsdev/web-xforge/blob/719324cc55de64b3dec884f1e98df5fb6685b34c/src/SIL.XForge.Scripture/ClientApp/src/app/shared/share/share-dialog.component.scss#L51)):*
<details><summary><i>Previously, nigel-wells (Nigel Wells) wrote…</i></summary><blockquote>

As mentioned in Slack, try removing the encapsulation rule on the component in order to stop having these CSS rules leaking out to the rest of the app. You'll need to check mobile viewport as I believe it was added specifically to address a scrolling issue.
</blockquote></details>

Done.
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/shared/share/share-dialog.component.scss` line 6 at r3](https://reviewable.io/reviews/sillsdev/web-xforge/1874#-NWk9elf9VsHakjAEV1f:-NWkPR_u3q--IIFlXjd0:bnt67hr) ([raw file](https://github.com/sillsdev/web-xforge/blob/71fa837ef09105f352d258cec1390ef38ca7c567/src/SIL.XForge.Scripture/ClientApp/src/app/shared/share/share-dialog.component.scss#L6)):*
<details><summary><i>Previously, nigel-wells (Nigel Wells) wrote…</i></summary><blockquote>

Was this still supposed to change or are we changing all dialogs to have the title centered?
</blockquote></details>

Nathaniel and I noticed this during a Forge. If we are interpreting the intent correctly, we can align the title and X button with centering, instead of manual negative margins.

**Review by Nateowami — COMMENTED** [review]
> Reviewed 1 of 2 files at r3.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1874)* status: all files reviewed (commit messages unreviewed), 2 unresolved discussions (waiting on @nigel-wells)

**Review by Nateowami — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1874#-:-NWnLPM87PB1Izb-mOmM:bnfp4nl)* status: all files reviewed (commit messages unreviewed), 2 unresolved discussions (waiting on @nigel-wells)

**Review by nigel-wells — APPROVED** [review]
Just one non-blocking comment below around the margin.

> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1874#-:-NWoNBOmB64nSiFdVDts:b-iy1iog)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @josephmyers)

___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/shared/share/share-dialog.component.scss` line 6 at r3](https://reviewable.io/reviews/sillsdev/web-xforge/1874#-NWk9elf9VsHakjAEV1f:-NWoMdp22jvzK6l1olWi:b-oqjqos) ([raw file](https://github.com/sillsdev/web-xforge/blob/71fa837ef09105f352d258cec1390ef38ca7c567/src/SIL.XForge.Scripture/ClientApp/src/app/shared/share/share-dialog.component.scss#L6)):*
<details><summary><i>Previously, Nateowami (Nathaniel Paulus) wrote…</i></summary><blockquote>

@nigel-wells This centers the items in the title (heading and close button) vertically.

This is cleaner than setting `margin-top: -4px;` on the button.
</blockquote></details>

The `margin-top` wasn't so much around centering the two elements but reducing some of the space between the title and the sharing options which are caused by the material UI button. Moving it up allowed that space to reduce a little. If you center it then there will be more space above the heading now. I'm ok if you guys are happy with how it now looks (I've not checked it out) but those were my reasons.

**Comment by Nateowami** [comment]
An unintended styling changes slipped through in this PR; I have a fix in #1895

**Pull request merged**
