### PR TITLE
SF-1506 Support USFM tag va - verse number alternate

### PR DESCRIPTION
**Pull request by marksvc**
- Note that it will look differently depending on whether it's part of
a verse number or in the middle of a verse text.

---

**Stack**:
- #1297
- #1289
- #1288
- #1287
- #1286
- #1278 ⮜

⚠️ *Part of a stack created by [spr](https://github.com/ejoffe/spr). Do not merge manually using the UI - doing so may have unexpected results.*

---
This change is [Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1278)

### CODE REVIEW

**Comment by marksvc** [comment]
va-tag
Here is a screenshot of it in SF.

**Review by RaymondLuong3 — COMMENTED** [review]
I do see what Ira mentioned about the invalid formatting. I get this on verse 2 when I have text formatted like this: \v 2 \va 1b,3\va* Text in verse 2 \va 2\va* alternate verse text.


> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1278#-:-Myxi38W5iwTnYpKWM_s:b-i93p7u)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @marksvc)

**Review by marksvc — COMMENTED** [review]
@raymondluong3 I'm having trouble causing the error. I tried using exactly 
```
\v 2 \va 1b,3\va* Text in verse 2 \va 2\va* alternate verse text.
```
but that is not causing the error. I haven't tried it on develop, only  master. Is the above exactly what you find gives you an error? I notice that the text is slightly different than what's in the screenshot above.

> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1278#-:-MzMIMPA01aReRqwI7Lt:b-n9r6wk)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @marksvc)

**Review by RaymondLuong3 — COMMENTED** [review]
I added you to Scripture Forge Testing project. See if you get the error when you connect to that project.

> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1278#-:-MzMXbWvAhgupADIki1H:boqjj05)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @marksvc)

**Review by RaymondLuong3 — APPROVED** [review]
Thanks for the explanation.

> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1278#-:-Mz_vAI021DUiL46MW5S:b-wsvas3)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @marksvc)

**Pull request merged**
