### PR TITLE
DBL Resource Support

### PR DESCRIPTION
**Pull request by pmachapman**
- Support for source projects to be DBL resources
- DBL resources are displayed in the "Based on" translation drop down, below other projects
- Added model changes for book permissions for both source and target projects
- Implemented book permissions for source projects when they are resources

---
This change is [Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/836)

### CODE REVIEW

**Review by jasonleenaylor — COMMENTED** [review]
> Reviewed 31 of 40 files at r1, 1 of 4 files at r2.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/836)* status: 32 of 40 files reviewed, all discussions resolved (waiting on @ddaspit)

___
*[src/RealtimeServer/scriptureforge/services/sf-project-migrations.spec.ts, line 42 at r2](https://reviewable.io/reviews/sillsdev/web-xforge/836#-MJUpl4FDopnCpZ7lezS:-MJUpl4FDopnCpZ7lezT:b-bl1718) ([raw file](https://github.com/sillsdev/web-xforge/blob/de0f2f85e1cb399b10f8bdf6dc25e2f81e5a333b/src/RealtimeServer/scriptureforge/services/sf-project-migrations.spec.ts#L42)):*
> ```XML
>           { bookNum: 41, chapters: [{ number: 1 }, { number: 2, isValid: true }], hasSource: false }
>         ],
>         userRoles: { user01: SFProjectRole.ParatextTranslator, user02: SFProjectRole.ParatextConsultant }
> ```

Do you think testing the Administrator role could be useful?
___
*[src/SIL.XForge.Scripture/ClientApp/src/app/connect-project/connect-project.component.ts, line 122 at r2](https://reviewable.io/reviews/sillsdev/web-xforge/836#-MJUqpWQDOygQ1iV2T2g:-MJUqpWQDOygQ1iV2T2h:b-e05nra) ([raw file](https://github.com/sillsdev/web-xforge/blob/de0f2f85e1cb399b10f8bdf6dc25e2f81e5a333b/src/SIL.XForge.Scripture/ClientApp/src/app/connect-project/connect-project.component.ts#L122)):*
> ```
>        paratextProjects = paratextProjects?.concat(paratextResources) ?? paratextResources;
> ```
I didn't see any tests adjusted to cover this. I think there ought to be one.
___
*[src/SIL.XForge.Scripture/ClientApp/src/app/settings/settings.component.spec.ts, line 209 at r2](https://reviewable.io/reviews/sillsdev/web-xforge/836#-MJUrVykE9hHyM35Mukl:-MJUrVykE9hHyM35Mukm:b-kuqtv3) ([raw file](https://github.com/sillsdev/web-xforge/blob/de0f2f85e1cb399b10f8bdf6dc25e2f81e5a333b/src/SIL.XForge.Scripture/ClientApp/src/app/settings/settings.component.spec.ts#L209)):*
> ```
> []
> ```
I'd like to see one of the tests in this file return a resource and verify that it is correctly merged into the projects list.
___
*[src/SIL.XForge.Scripture/Models/TextInfo.cs, line 37 at r2](https://reviewable.io/reviews/sillsdev/web-xforge/836#-MJUseXpC9IF9qymj89l:-MJUseXpC9IF9qymj89m:b-v12lxl) ([raw file](https://github.com/sillsdev/web-xforge/blob/de0f2f85e1cb399b10f8bdf6dc25e2f81e5a333b/src/SIL.XForge.Scripture/Models/TextInfo.cs#L37)):*
> ```
>  
> ```
some whitespace issue here.
___
*[src/SIL.XForge.Scripture/Services/ParatextService.cs, line 208 at r2](https://reviewable.io/reviews/sillsdev/web-xforge/836#-MJUu9woDO9wv4nBqiB-:-MJUu9woDO9wv4nBqiB0:b-ipab47) ([raw file](https://github.com/sillsdev/web-xforge/blob/de0f2f85e1cb399b10f8bdf6dc25e2f81e5a333b/src/SIL.XForge.Scripture/Services/ParatextService.cs#L208)):*
> ```
>  && !(sourcePtProject is ParatextResource))
> ```
I think the comment about skipping the sync for resources belongs here, instead of above. (or both I guess)
___
*[src/SIL.XForge.Scripture/Services/ParatextService.cs, line 570 at r2](https://reviewable.io/reviews/sillsdev/web-xforge/836#-MJUupn_4zcHWCivs_PQ:-MJUupnaEFls9Oo_UwCs:b-pt4bv7) ([raw file](https://github.com/sillsdev/web-xforge/blob/de0f2f85e1cb399b10f8bdf6dc25e2f81e5a333b/src/SIL.XForge.Scripture/Services/ParatextService.cs#L570)):*
<details><summary><i alt="summary">Quoted 24 lines of code…</i></summary>

> ```
>                     if (source is ParatextResource resource)
>                     {
>                         if (resource.InstallableResource != null)
>                         {
>                             // Install the resource if it is missing or out of date
>                             if (!resource.IsInstalled
>                                 || resource.AvailableRevision > resource.InstalledRevision
>                                 || resource.InstallableResource.IsNewerThanCurrentlyInstalled())
>                             {
>                                 resource.InstallableResource.Install();
>                                 sourceNeedsCloned = true;
>                             }
>                             // Extract the resource to the source directory
>                             if (sourceNeedsCloned)
>                             {
>                                 string path = Path.Combine(SyncDir, target.ParatextId, TextTypeUtils.DirectoryName(Models.TextType.Source));
>                                 _fileSystemService.CreateDirectory(path);
>                                 resource.InstallableResource.ExtractToDirectory(path);
>                             }
>                         }
>                         else
>                         {
>                             _logger.LogWarning($"The installable resource is not available for {source.ParatextId}");
>                         }
> ```
</details>


A cursory glance makes me think this code is a duplicate of above. Could this go into a method?

**Review by pmachapman — COMMENTED** [review]
Fixed the dereferenced variable

> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/836#-:-MJVWgzx9Bqd0E0ZsZPp:b-wa0v5q)* status: 32 of 40 files reviewed, all discussions resolved (waiting on @ddaspit)

___
*[src/RealtimeServer/scriptureforge/services/sf-project-migrations.spec.ts, line 42 at r2](https://reviewable.io/reviews/sillsdev/web-xforge/836#-MJUpl4FDopnCpZ7lezS:-MJV1vg75i-DgS9aayTv:b-hc14m0) ([raw file](https://github.com/sillsdev/web-xforge/blob/de0f2f85e1cb399b10f8bdf6dc25e2f81e5a333b/src/RealtimeServer/scriptureforge/services/sf-project-migrations.spec.ts#L42)):*
<details><summary><i>Previously, jasonleenaylor (Jason Naylor) wrote…</i></summary><blockquote>

Do you think testing the Administrator role could be useful?
</blockquote></details>

Yes - I'll test for Observer as well.
___
*[src/SIL.XForge.Scripture/ClientApp/src/app/connect-project/connect-project.component.ts, line 122 at r2](https://reviewable.io/reviews/sillsdev/web-xforge/836#-MJUqpWQDOygQ1iV2T2g:-MJV9SA46K6Ka0oNu8jD:b-qv4czt) ([raw file](https://github.com/sillsdev/web-xforge/blob/de0f2f85e1cb399b10f8bdf6dc25e2f81e5a333b/src/SIL.XForge.Scripture/ClientApp/src/app/connect-project/connect-project.component.ts#L122)):*
<details><summary><i>Previously, jasonleenaylor (Jason Naylor) wrote…</i></summary><blockquote>

> ```
>        paratextProjects = paratextProjects?.concat(paratextResources) ?? paratextResources;
> ```
I didn't see any tests adjusted to cover this. I think there ought to be one.
</blockquote></details>

Yes, there should...added.
___
*[src/SIL.XForge.Scripture/ClientApp/src/app/settings/settings.component.spec.ts, line 209 at r2](https://reviewable.io/reviews/sillsdev/web-xforge/836#-MJUrVykE9hHyM35Mukl:-MJV9OLj9-bL2FTzvti4:b-biz16c) ([raw file](https://github.com/sillsdev/web-xforge/blob/de0f2f85e1cb399b10f8bdf6dc25e2f81e5a333b/src/SIL.XForge.Scripture/ClientApp/src/app/settings/settings.component.spec.ts#L209)):*
<details><summary><i>Previously, jasonleenaylor (Jason Naylor) wrote…</i></summary><blockquote>

> ```
> []
> ```
I'd like to see one of the tests in this file return a resource and verify that it is correctly merged into the projects list.
</blockquote></details>

Good idea - added.
___
*[src/SIL.XForge.Scripture/Models/TextInfo.cs, line 37 at r2](https://reviewable.io/reviews/sillsdev/web-xforge/836#-MJUseXpC9IF9qymj89l:-MJV2grpCVDWicvMNswI:bfrtr06) ([raw file](https://github.com/sillsdev/web-xforge/blob/de0f2f85e1cb399b10f8bdf6dc25e2f81e5a333b/src/SIL.XForge.Scripture/Models/TextInfo.cs#L37)):*
<details><summary><i>Previously, jasonleenaylor (Jason Naylor) wrote…</i></summary><blockquote>

> ```
>  
> ```
some whitespace issue here.
</blockquote></details>

Good spotting... :-)
___
*[src/SIL.XForge.Scripture/Services/ParatextService.cs, line 208 at r2](https://reviewable.io/reviews/sillsdev/web-xforge/836#-MJUu9woDO9wv4nBqiB-:-MJV49E35MOh7svN1D1u:bh1yf32) ([raw file](https://github.com/sillsdev/web-xforge/blob/de0f2f85e1cb399b10f8bdf6dc25e2f81e5a333b/src/SIL.XForge.Scripture/Services/ParatextService.cs#L208)):*
<details><summary><i>Previously, jasonleenaylor (Jason Naylor) wrote…</i></summary><blockquote>

> ```
>  && !(sourcePtProject is ParatextResource))
> ```
I think the comment about skipping the sync for resources belongs here, instead of above. (or both I guess)
</blockquote></details>

This block is to sync a source project (not a resource), so doesn't need the comment. The comment is in a block above, as that where the workaround is to get sync working if you can't access the resource.
___
*[src/SIL.XForge.Scripture/Services/ParatextService.cs, line 570 at r2](https://reviewable.io/reviews/sillsdev/web-xforge/836#-MJUupn_4zcHWCivs_PQ:-MJV5OBY8ev9JmMAOz5a:b-c643m0) ([raw file](https://github.com/sillsdev/web-xforge/blob/de0f2f85e1cb399b10f8bdf6dc25e2f81e5a333b/src/SIL.XForge.Scripture/Services/ParatextService.cs#L570)):*
<details><summary><i>Previously, jasonleenaylor (Jason Naylor) wrote…</i></summary><blockquote>

> ```
>                     if (source is ParatextResource resource)
>                     {
>                         if (resource.InstallableResource != null)
>                         {
>                             // Install the resource if it is missing or out of date
>                             if (!resource.IsInstalled
>                                 || resource.AvailableRevision > resource.InstalledRevision
>                                 || resource.InstallableResource.IsNewerThanCurrentlyInstalled())
>                             {
>                                 resource.InstallableResource.Install();
>                                 sourceNeedsCloned = true;
>                             }
>                             // Extract the resource to the source directory
>                             if (sourceNeedsCloned)
>                             {
>                                 string path = Path.Combine(SyncDir, target.ParatextId, TextTypeUtils.DirectoryName(Models.TextType.Source));
>                                 _fileSystemService.CreateDirectory(path);
>                                 resource.InstallableResource.ExtractToDirectory(path);
>                             }
>                         }
>                         else
>                         {
>                             _logger.LogWarning($"The installable resource is not available for {source.ParatextId}");
>                         }
> ```

A cursory glance makes me think this code is a duplicate of above. Could this go into a method?
</blockquote></details>

The two blocks are subtly different in their juggling of the target and source projects - I attempted to refactor but the result looked far worse, unfortunately.

**Review by jasonleenaylor — COMMENTED** [review]
> Reviewed 1 of 4 files at r3.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/836)* status: 29 of 40 files reviewed, all discussions resolved (waiting on @ddaspit and @jasonleenaylor)

___
*[src/SIL.XForge.Scripture/Services/ParatextService.cs, line 570 at r2](https://reviewable.io/reviews/sillsdev/web-xforge/836#-MJUupn_4zcHWCivs_PQ:-MJXgR2P69an_eKIkmd8:bqrfan2) ([raw file](https://github.com/sillsdev/web-xforge/blob/de0f2f85e1cb399b10f8bdf6dc25e2f81e5a333b/src/SIL.XForge.Scripture/Services/ParatextService.cs#L570)):*
<details><summary><i>Previously, pmachapman (Peter Chapman) wrote…</i></summary><blockquote>

The two blocks are subtly different in their juggling of the target and source projects - I attempted to refactor but the result looked far worse, unfortunately.
</blockquote></details>

Understood.

**Review by ddaspit — CHANGES_REQUESTED** [review]
> Reviewed 32 of 40 files at r1, 4 of 4 files at r2, 4 of 4 files at r3.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/836)* status: all files reviewed, 9 unresolved discussions (waiting on @pmachapman)

___
*[src/RealtimeServer/scriptureforge/services/sf-project-migrations.spec.ts, line 35 at r3](https://reviewable.io/reviews/sillsdev/web-xforge/836#-MJz8c9m5bxG4GPSuzQE:-MJz8c9nCkhjCFgw4-TY:b247d3g) ([raw file](https://github.com/sillsdev/web-xforge/blob/aa1974be96901aeb444435891da71154e2acae8b/src/RealtimeServer/scriptureforge/services/sf-project-migrations.spec.ts#L35)):*
> ```XML
>   describe('version 2', () => {
>     it('migrates docs', async () => {
>       const env = new TestEnvironment(0);
> ```

I think this should be version `1` not `0`.
___
*[src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.ts, line 185 at r3](https://reviewable.io/reviews/sillsdev/web-xforge/836#-MJzAoEcBOXgOxnW5x7l:-MJzAoEcBOXgOxnW5x7m:b-e9k4sp) ([raw file](https://github.com/sillsdev/web-xforge/blob/aa1974be96901aeb444435891da71154e2acae8b/src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.ts#L185)):*
> ```XML
>       return false;
>     } else {
>       let sourcePermission =
> ```

I think this can be simplified to:
```
const sourcePermission = this.text.sourcePermissions[this.userService.currentUserId] ?? TextInfoPermission.None;
```
Optional chaining on `text` should be necessary, because of the null check for `this.text` earlier. Checking for undefined shouldn't be necessary, because we have strict null checking turned on. If it is possible for `sourcePermissions` to be undefined (which I don't think it is), then it should be marked as optional in the model.
___
*[src/SIL.XForge.Scripture/Services/ParatextService.cs, line 169 at r3](https://reviewable.io/reviews/sillsdev/web-xforge/836#-MJzE4SG6hRlsIWyp0Mi:-MJzE4SG6hRlsIWyp0Mj:b-t4tw5d) ([raw file](https://github.com/sillsdev/web-xforge/blob/aa1974be96901aeb444435891da71154e2acae8b/src/SIL.XForge.Scripture/Services/ParatextService.cs#L169)):*
> ```Smalltalk
>             {
>                 // See if this is a resource
>                 var resources = this.GetResourcesInternal(userSecret, true);
> ```

Please specify the type unless it is explicit in the assignment. This makes the code more readable.
___
*[src/SIL.XForge.Scripture/Services/ParatextService.cs, line 536 at r3](https://reviewable.io/reviews/sillsdev/web-xforge/836#-MJzSXqy2ehMOzJO_QoD:-MJzSXqy2ehMOzJO_QoE:b-4t7nip) ([raw file](https://github.com/sillsdev/web-xforge/blob/aa1974be96901aeb444435891da71154e2acae8b/src/SIL.XForge.Scripture/Services/ParatextService.cs#L536)):*
> ```Smalltalk
>                     sourceNeedsCloned = true;
>                 }
>                 if (sourceNeedsCloned || source is ParatextResource)
> ```

This code seems very similar to the code for target projects. I think it makes sense to pull this code into a method.
___
*[src/SIL.XForge.Scripture/Services/ParatextSyncRunner.cs, line 200 at r3](https://reviewable.io/reviews/sillsdev/web-xforge/836#-MJzWrXO127JvBk7LStI:-MJzWrXO127JvBk7LStJ:b-68ag82) ([raw file](https://github.com/sillsdev/web-xforge/blob/aa1974be96901aeb444435891da71154e2acae8b/src/SIL.XForge.Scripture/Services/ParatextSyncRunner.cs#L200)):*
> ```Smalltalk
>                     await _projectDoc.SubmitJson0OpAsync(op =>
>                     {
>                         // Calculate the book and source permissions
> ```

This code should probably be pulled out of the the lambda since it makes async calls.
___
*[src/SIL.XForge.Scripture/Services/ParatextSyncRunner.cs, line 233 at r3](https://reviewable.io/reviews/sillsdev/web-xforge/836#-MJzXDoH0SXnufAYLkpp:-MJzXDoH0SXnufAYLkpq:b8vhigp) ([raw file](https://github.com/sillsdev/web-xforge/blob/aa1974be96901aeb444435891da71154e2acae8b/src/SIL.XForge.Scripture/Services/ParatextSyncRunner.cs#L233)):*
> ```Smalltalk
>                                         if (userSecret != null)
>                                         {
>                                             if (!(userSecret.ParatextTokens?.ValidateLifetime() ?? false))
> ```

I think it would make sense to move this code inside of the `ParatextService` so that the `ParatextSyncRunner` doesn't need to know about things like refreshing the access token or Paratext implementation details like `InstallableDBLResource`.
___
*[src/SIL.XForge.Scripture/Services/SFInstallableDBLResource.cs, line 87 at r3](https://reviewable.io/reviews/sillsdev/web-xforge/836#-MJzY9Pt-CkvBoaUk0bI:-MJzY9Pt-CkvBoaUk0bJ:b-15r3bi) ([raw file](https://github.com/sillsdev/web-xforge/blob/aa1974be96901aeb444435891da71154e2acae8b/src/SIL.XForge.Scripture/Services/SFInstallableDBLResource.cs#L87)):*
> ```Smalltalk
>         /// This is a convenience constructor for unit tests.
>         /// </remarks>
>         internal SFInstallableDBLResource(UserSecret userSecret, ParatextOptions paratextOptions, ISFRESTClientFactory restClientFactory, IFileSystemService fileSystemService, IJwtTokenHelper jwtTokenHelper)
> ```

These lines are really long. We try to keep lines to 120 characters or less.
___
*[src/SIL.XForge.Scripture/Services/SFInstallableDBLResource.cs, line 680 at r3](https://reviewable.io/reviews/sillsdev/web-xforge/836#-MJzZcsu4rxvP-M1wrCq:-MJzZcsu4rxvP-M1wrCr:b-qnlqx3) ([raw file](https://github.com/sillsdev/web-xforge/blob/aa1974be96901aeb444435891da71154e2acae8b/src/SIL.XForge.Scripture/Services/SFInstallableDBLResource.cs#L680)):*
> ```Smalltalk
>                 if (cachedValue == null)
>                 {
>                     cachedValue = StringUtils.DecryptStringFromBase64(this._paratextOptions.ResourcePasswordBase64, this._paratextOptions.ResourcePasswordHash);
> ```

I don't think we need keep the password encrypted. We don't keep any of the other secrets encrypted.
___
*[src/SIL.XForge.Scripture/Services/SFProjectService.cs, line 80 at r3](https://reviewable.io/reviews/sillsdev/web-xforge/836#-MJz_HNv1qkqGL0SrUIs:-MJz_HNv1qkqGL0SrUIt:b-jn6z8l) ([raw file](https://github.com/sillsdev/web-xforge/blob/aa1974be96901aeb444435891da71154e2acae8b/src/SIL.XForge.Scripture/Services/SFProjectService.cs#L80)):*
> ```Smalltalk
>                 {
>                     // If it is not a project, see if there is a matching resource
>                     var resources = this._paratextService.GetResources(userSecret);
> ```

Please specify the type unless it is explicit in the assignment.

**Review by ddaspit — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/836)* status: all files reviewed, 10 unresolved discussions (waiting on @pmachapman)

___
*[src/SIL.XForge.Scripture/ClientApp/src/app/connect-project/connect-project.component.ts, line 120 at r3](https://reviewable.io/reviews/sillsdev/web-xforge/836#-MJzhW0X0ifU4ECEiXNB:-MJzhW0X0ifU4ECEiXNC:b-9cjuig) ([raw file](https://github.com/sillsdev/web-xforge/blob/aa1974be96901aeb444435891da71154e2acae8b/src/SIL.XForge.Scripture/ClientApp/src/app/connect-project/connect-project.component.ts#L120)):*
> ```XML
>       let paratextProjects = this.projects.filter(p => p.paratextId !== paratextId);
>       // Merge the resources collection with the projects collection
>       const paratextResources = await this.paratextService.getResources().toPromise();
> ```

It would be better to call this in the `populateProjectList` method and save the results to a field. The current code will hit the backend every time the user selects a different target project.

**Review by pmachapman — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/836)* status: 26 of 40 files reviewed, 10 unresolved discussions (waiting on @ddaspit and @jasonleenaylor)

___
*[src/RealtimeServer/scriptureforge/services/sf-project-migrations.spec.ts, line 35 at r3](https://reviewable.io/reviews/sillsdev/web-xforge/836#-MJz8c9m5bxG4GPSuzQE:-MK1Js3jBFOGl1hRt3R_:bahyt4r) ([raw file](https://github.com/sillsdev/web-xforge/blob/aa1974be96901aeb444435891da71154e2acae8b/src/RealtimeServer/scriptureforge/services/sf-project-migrations.spec.ts#L35)):*
<details><summary><i>Previously, ddaspit (Damien Daspit) wrote…</i></summary><blockquote>

I think this should be version `1` not `0`.
</blockquote></details>

Yes, it should - changed.
___
*[src/SIL.XForge.Scripture/ClientApp/src/app/connect-project/connect-project.component.ts, line 120 at r3](https://reviewable.io/reviews/sillsdev/web-xforge/836#-MJzhW0X0ifU4ECEiXNB:-MK1KuYkD7sp9m0QjZMn:beyglve) ([raw file](https://github.com/sillsdev/web-xforge/blob/aa1974be96901aeb444435891da71154e2acae8b/src/SIL.XForge.Scripture/ClientApp/src/app/connect-project/connect-project.component.ts#L120)):*
<details><summary><i>Previously, ddaspit (Damien Daspit) wrote…</i></summary><blockquote>

It would be better to call this in the `populateProjectList` method and save the results to a field. The current code will hit the backend every time the user selects a different target project.
</blockquote></details>

Sound good - changed.
___
*[src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.ts, line 185 at r3](https://reviewable.io/reviews/sillsdev/web-xforge/836#-MJzAoEcBOXgOxnW5x7l:-MK1LpnC-qasuwDZSqXh:bzi9nvv) ([raw file](https://github.com/sillsdev/web-xforge/blob/aa1974be96901aeb444435891da71154e2acae8b/src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.ts#L185)):*
<details><summary><i>Previously, ddaspit (Damien Daspit) wrote…</i></summary><blockquote>

I think this can be simplified to:
```
const sourcePermission = this.text.sourcePermissions[this.userService.currentUserId] ?? TextInfoPermission.None;
```
Optional chaining on `text` should be necessary, because of the null check for `this.text` earlier. Checking for undefined shouldn't be necessary, because we have strict null checking turned on. If it is possible for `sourcePermissions` to be undefined (which I don't think it is), then it should be marked as optional in the model.
</blockquote></details>

Yeah, that was super clunky...I have fixed it.
___
*[src/SIL.XForge.Scripture/Services/ParatextService.cs, line 570 at r2](https://reviewable.io/reviews/sillsdev/web-xforge/836#-MJUupn_4zcHWCivs_PQ:-MK1om97Cg5ipHBPL7OW:b-fumanz) ([raw file](https://github.com/sillsdev/web-xforge/blob/de0f2f85e1cb399b10f8bdf6dc25e2f81e5a333b/src/SIL.XForge.Scripture/Services/ParatextService.cs#L570)):*
<details><summary><i>Previously, jasonleenaylor (Jason Naylor) wrote…</i></summary><blockquote>

Understood.
</blockquote></details>

It has been refactored into a method, and removed, so if target resource support is needed in the future, it can be easily added in.
___
*[src/SIL.XForge.Scripture/Services/ParatextService.cs, line 169 at r3](https://reviewable.io/reviews/sillsdev/web-xforge/836#-MJzE4SG6hRlsIWyp0Mi:-MK1TBGmCgOvKCYYRelV:bb1e4ou) ([raw file](https://github.com/sillsdev/web-xforge/blob/aa1974be96901aeb444435891da71154e2acae8b/src/SIL.XForge.Scripture/Services/ParatextService.cs#L169)):*
<details><summary><i>Previously, ddaspit (Damien Daspit) wrote…</i></summary><blockquote>

Please specify the type unless it is explicit in the assignment. This makes the code more readable.
</blockquote></details>

No problem - done.
___
*[src/SIL.XForge.Scripture/Services/ParatextService.cs, line 536 at r3](https://reviewable.io/reviews/sillsdev/web-xforge/836#-MJzSXqy2ehMOzJO_QoD:-MK1ogtb4O2-aglb4cSk:b-9a9j14) ([raw file](https://github.com/sillsdev/web-xforge/blob/aa1974be96901aeb444435891da71154e2acae8b/src/SIL.XForge.Scripture/Services/ParatextService.cs#L536)):*
<details><summary><i>Previously, ddaspit (Damien Daspit) wrote…</i></summary><blockquote>

This code seems very similar to the code for target projects. I think it makes sense to pull this code into a method.
</blockquote></details>

I've pulled it into a method, and removed the target implementation. It will be straight forward to add it back in for target projects if/when required using this new method.
___
*[src/SIL.XForge.Scripture/Services/ParatextSyncRunner.cs, line 200 at r3](https://reviewable.io/reviews/sillsdev/web-xforge/836#-MJzWrXO127JvBk7LStI:-MK1dRTw0fA8LGvq1XaJ:bubif1k) ([raw file](https://github.com/sillsdev/web-xforge/blob/aa1974be96901aeb444435891da71154e2acae8b/src/SIL.XForge.Scripture/Services/ParatextSyncRunner.cs#L200)):*
<details><summary><i>Previously, ddaspit (Damien Daspit) wrote…</i></summary><blockquote>

This code should probably be pulled out of the the lambda since it makes async calls.
</blockquote></details>

Yes, it should. Done.
___
*[src/SIL.XForge.Scripture/Services/ParatextSyncRunner.cs, line 233 at r3](https://reviewable.io/reviews/sillsdev/web-xforge/836#-MJzXDoH0SXnufAYLkpp:-MK1dJgy7PivOSlk4TBH:b-x58axv) ([raw file](https://github.com/sillsdev/web-xforge/blob/aa1974be96901aeb444435891da71154e2acae8b/src/SIL.XForge.Scripture/Services/ParatextSyncRunner.cs#L233)):*
<details><summary><i>Previously, ddaspit (Damien Daspit) wrote…</i></summary><blockquote>

I think it would make sense to move this code inside of the `ParatextService` so that the `ParatextSyncRunner` doesn't need to know about things like refreshing the access token or Paratext implementation details like `InstallableDBLResource`.
</blockquote></details>

I've refactored it into the ParatextService
___
*[src/SIL.XForge.Scripture/Services/SFInstallableDBLResource.cs, line 87 at r3](https://reviewable.io/reviews/sillsdev/web-xforge/836#-MJzY9Pt-CkvBoaUk0bI:-MK1WaQ9CuwQYx_8EmnU:b-jlsz1i) ([raw file](https://github.com/sillsdev/web-xforge/blob/aa1974be96901aeb444435891da71154e2acae8b/src/SIL.XForge.Scripture/Services/SFInstallableDBLResource.cs#L87)):*
<details><summary><i>Previously, ddaspit (Damien Daspit) wrote…</i></summary><blockquote>

These lines are really long. We try to keep lines to 120 characters or less.
</blockquote></details>

I've gone through this file, and tried to make it a bit clearer and with shorter lines.
___
*[src/SIL.XForge.Scripture/Services/SFInstallableDBLResource.cs, line 680 at r3](https://reviewable.io/reviews/sillsdev/web-xforge/836#-MJzZcsu4rxvP-M1wrCq:-MK1MQ03AFisXK_JcWwV:bgtk2oz) ([raw file](https://github.com/sillsdev/web-xforge/blob/aa1974be96901aeb444435891da71154e2acae8b/src/SIL.XForge.Scripture/Services/SFInstallableDBLResource.cs#L680)):*
<details><summary><i>Previously, ddaspit (Damien Daspit) wrote…</i></summary><blockquote>

I don't think we need keep the password encrypted. We don't keep any of the other secrets encrypted.
</blockquote></details>

Yes, we don't need to, but I did it this way to maintain Paratext compatibility - if Paratext changes, it should be easy to update our end, as the code is similar enough to see where to update.
___
*[src/SIL.XForge.Scripture/Services/SFProjectService.cs, line 80 at r3](https://reviewable.io/reviews/sillsdev/web-xforge/836#-MJz_HNv1qkqGL0SrUIs:-MK1Ssnp3Me8kyITlpDB:bb1e4ou) ([raw file](https://github.com/sillsdev/web-xforge/blob/aa1974be96901aeb444435891da71154e2acae8b/src/SIL.XForge.Scripture/Services/SFProjectService.cs#L80)):*
<details><summary><i>Previously, ddaspit (Damien Daspit) wrote…</i></summary><blockquote>

Please specify the type unless it is explicit in the assignment.
</blockquote></details>

No problem - done.

**Review by ddaspit — COMMENTED** [review]
> Reviewed 14 of 14 files at r4.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/836)* status: :shipit: complete! all files reviewed, all discussions resolved

___
*[src/SIL.XForge.Scripture/Services/SFInstallableDBLResource.cs, line 680 at r3](https://reviewable.io/reviews/sillsdev/web-xforge/836#-MJzZcsu4rxvP-M1wrCq:-MK3O-sHBkm1rpZ4r6Gx:b-r9sz8) ([raw file](https://github.com/sillsdev/web-xforge/blob/aa1974be96901aeb444435891da71154e2acae8b/src/SIL.XForge.Scripture/Services/SFInstallableDBLResource.cs#L680)):*
<details><summary><i>Previously, pmachapman (Peter Chapman) wrote…</i></summary><blockquote>

Yes, we don't need to, but I did it this way to maintain Paratext compatibility - if Paratext changes, it should be easy to update our end, as the code is similar enough to see where to update.
</blockquote></details>

That's fine.

**Review by ddaspit — COMMENTED** [review]
All of the changes look good.

> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/836#-:-MK3OLpA7JjZOGNZTLbM:bygto5d)* status: :shipit: complete! all files reviewed, all discussions resolved

**Comment by irahopkinson** [comment]
Closed in favour of PR #867.

**Pull request closed without merging**
