### PR TITLE
SF-1526a notes: improve conflict diff colouring

### PR DESCRIPTION
**Pull request by marksvc**
**Stack**:
- #1311
- #1308
- #1307
- #1306
- #1305
- #1304 ⮜

⚠️ *Part of a stack created by [spr](https://github.com/ejoffe/spr). Do not merge manually using the UI - doing so may have unexpected results.*

---
This change is [Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1304)

### CODE REVIEW

**Review by Nateowami — COMMENTED** [review]
I'm really confused by how spr stacks work. This PR shows that it has the logging changes, which have already been merged. Maybe it didn't get merged correctly or something? I'm also not clear what problem they solve. I thought it was to assist with reviewing distinct sets of changes that depend on each other (e.g. "I changed x, and then I changed y, and the y change depends on change x, but should be reviewed separately"), which is a problem I've occasionally had in the past, but I can't tell that any of the changes in the stack are related to each other. But since they aren't all one commit ahead of master, I can't reason with any degree of certainty that they're all independent changes that aren't related to each other.

> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1304#-:-N-_AvFy5aZA8OONWSsT:bzgasok)* status: 0 of 3 files reviewed, all discussions resolved

**Review by Nateowami — COMMENTED** [review]
Looks mostly good, but a couple questions.

> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1304#-:-N-_MQPf7zx3TIULE9oP:b9q7zqr)* status: all files reviewed, 1 unresolved discussion (waiting on @marksvc)

___
*[src/SIL.XForge.Scripture/ClientApp/src/_usx.scss, line 404 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/1304#-N-_KLGPDns1XNN7iDQh:-N-_KLGPDns1XNN7iDQi:b-rov8kq) ([raw file](https://github.com/sillsdev/web-xforge/blob/392a21799b7e6c911737389bcac7af402bdbbe29/src/SIL.XForge.Scripture/ClientApp/src/_usx.scss#L404)):*
> ```SCSS
> .note-content {
>   .conflict-text-older {
>     background-color: #ffc0cb;
> ```

These colors are accurate in Firefox but not Chromium. Chromium does something weird with colors, and I don't know what it is. Just FYI.
___
*[src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/note-dialog/note-dialog.component.ts, line 132 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/1304#-N-_Kwtt4SCzS4oStrmH:-N-_Kwtt4SCzS4oStrmI:bgdrbq2) ([raw file](https://github.com/sillsdev/web-xforge/blob/392a21799b7e6c911737389bcac7af402bdbbe29/src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/note-dialog/note-dialog.component.ts#L132)):*
> ```XML
> 
>   parseNote(content: string | undefined): string {
>     const replace = new Map<RegExp, string>();
> ```

Did using an XML parser not end up working?

**Comment by marksvc** [comment]
> I'm really confused by how spr stacks work. This PR shows that it has the logging changes, which have already been merged. Maybe it didn't get merged correctly or something? 

@Nateowami , I'm sorry for the confusion. I re-ran spr and fixed it. Each of the spr PRs should just contain one commit. 

> I'm also not clear what problem they solve. I thought it was to assist with reviewing distinct sets of changes that depend on each other (e.g. "I changed x, and then I changed y, and the y change depends on change x, but should be reviewed separately"), which is a problem I've occasionally had in the past, but I can't tell that any of the changes in the stack are related to each other. 

That's one helpful use for spr. Another is it lets me keep working on top of my previous work, with significantly less fiddling. 

In this situation, 5 of the 6 commits are related to, or work toward, improving note conflict display. One is a more generic fix, but which is a prerequisite (#1303), one refactors from a test service to a mock service (#1305), and does so so that later commits can test something in notes. I didn't put "SF-1526" in the subjects of those two commits, since they weren't really accomplishing the bug/feature of SF-1526. 
Three of the other commits are 
- SF-1526a, where I apply diff colouring based on the diff indications in the data,
- SF-1526b, where I add new properties to the model, and cause sync to detect and apply updates to these properties, and
- SF-1526c, where I take the data that's now in the model, and use it in displaying conflict notes with more of their conflict information. 

The 6th commit is less related, but it's a tidy-up that I did when working on the above, that doesn't need to muddy the diffs for the reviews of the above. 

So in this case, there is a significant relationship among the commits. But I have also used spr with less-related commits to let me continue working linearly and propose multiple changes with significantly less branch management.

**Comment by marksvc** [comment]
(Oh, I realized that in your comment you may have been referring to the 3 commits that were (incorrectly together) in this PR when you said, "the changes in the stack". Sorry for the confusion.)

**Review by Nateowami — COMMENTED** [review]
Thanks; that's helpful. I'll add some comments to some of the individual PRs.

> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1304#-:-N-_ZF7710qTalDs-23w:b-4fmnxc)* status: all files reviewed, 1 unresolved discussion (waiting on @marksvc)

**Comment by Nateowami** [comment]
> (Oh, I realized that in your comment you may have been referring to the 3 commits that were (incorrectly together) in this PR when you said, "the changes in the stack". Sorry for the confusion.)

Nope, you were right the first time. :smile:

**Review by marksvc — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1304)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @marksvc)

___
*[src/SIL.XForge.Scripture/ClientApp/src/_usx.scss, line 404 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/1304#-N-_KLGPDns1XNN7iDQh:-N-ydQUh9mK01mYOPJGR:b2nnles) ([raw file](https://github.com/sillsdev/web-xforge/blob/8ff6df85c3bf760b28c826b1e848de7a49e48a43/src/SIL.XForge.Scripture/ClientApp/src/_usx.scss#L404)):*
<details><summary><i>Previously, Nateowami (Nathaniel Paulus) wrote…</i></summary><blockquote>

These colors are accurate in Firefox but not Chromium. Chromium does something weird with colors, and I don't know what it is. Just FYI.
</blockquote></details>

Can you explain more about what you mean? I am looking at the conflict colours in FX and Chromium and the celouring appears to be the same. Maybe you are meaning (1) FX accurately portrays the colour codes that are specified in CSS, but Chromium does not, and so be careful since Chromium may not be giving what is asked for? Or maybe you're meaning (2) The content looks the right way in FX but not in Chromium. 
Or.. ?

Here is a screenshot of Chromium and Firefox showing the same dialog.


___
*[src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/note-dialog/note-dialog.component.ts, line 132 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/1304#-N-_Kwtt4SCzS4oStrmH:-N-yfCKNCrPLXLvZPbcG:b-x3sb1j) ([raw file](https://github.com/sillsdev/web-xforge/blob/8ff6df85c3bf760b28c826b1e848de7a49e48a43/src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/note-dialog/note-dialog.component.ts#L132)):*
<details><summary><i>Previously, Nateowami (Nathaniel Paulus) wrote…</i></summary><blockquote>

Did using an XML parser not end up working?
</blockquote></details>

I found that a problem at hand (removing the wrong closing tag) was solved by doing it a different way. 
And the replacements here were working fine and not giving motivation to look into more elaborate parsing options. 
So, I did end up using some XML parsing for something in one of the later commits, but not yet for this.

**Review by Nateowami — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1304)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @marksvc)

___
*[src/SIL.XForge.Scripture/ClientApp/src/_usx.scss, line 404 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/1304#-N-_KLGPDns1XNN7iDQh:-N-yrk7HC9eyj4I8xm2_:b4upw5z) ([raw file](https://github.com/sillsdev/web-xforge/blob/8ff6df85c3bf760b28c826b1e848de7a49e48a43/src/SIL.XForge.Scripture/ClientApp/src/_usx.scss#L404)):*
<details><summary><i>Previously, marksvc wrote…</i></summary><blockquote>

Can you explain more about what you mean? I am looking at the conflict colours in FX and Chromium and the celouring appears to be the same. Maybe you are meaning (1) FX accurately portrays the colour codes that are specified in CSS, but Chromium does not, and so be careful since Chromium may not be giving what is asked for? Or maybe you're meaning (2) The content looks the right way in FX but not in Chromium. 
Or.. ?

Here is a screenshot of Chromium and Firefox showing the same dialog.



</blockquote></details>

What I meant is that if you sample the actual colors displayed in the browser they're not the same between Chromium and Firefox, and it appears Chromium has the wrong colors.

However, using the color picker on the screenshot you posted, they are the same colors. I wonder if Chromium tries to detect something about a monitor and then modify the colors to make them appear more accurate on screen? I don't know. That might explain why it happens on my machine but doesn't appear to happen on yours.

In this case I can't actually tell a difference between the colors, but in some cases I can detect a fairly substantial difference in color between the browsers on the same machine.

To be clear, I'm not asking for any change to be made here.

**Pull request merged**
