### PR TITLE
SF-2640 Warn when font unsupported

### PR DESCRIPTION
**Pull request by Nateowami**
Problem  | Project | Resource
---------|---------|---------
Fallback |  | 
Graphite |  | 

- - -
This change is [Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/2548)

### CODE REVIEW

**Comment by josephmyers** [comment]
image

If the selected font isn't present in the fallbacks, the message is messed up. I had just picked a font in PT at random. So we need a fallback for the fallbacks?

**Review by Nateowami — COMMENTED** [review]
:facepalm: Thanks for catching that.

> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/2548#-:-O0Mm3DdDjT5lACrOaFj:bjoxljm)* status: 0 of 12 files reviewed, all discussions resolved (waiting on @josephmyers)

**Review by Nateowami — COMMENTED** [review]
Should be fixed now.

> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/2548#-:-O0MmI2a2bhDjS3FUKuJ:bql6urd)* status: 0 of 12 files reviewed, all discussions resolved (waiting on @josephmyers)

**Comment by josephmyers** [comment]
image

The other thing I'm seeing is the "graphite" message showing in Firefox. Are we intending that to be an informational message, or is something the matter?

**Review by josephmyers — CHANGES_REQUESTED** [review]
> Reviewed 12 of 12 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/2548)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @Nateowami)

**Comment by Nateowami** [comment]
You can use dev tools to show what fonts were used for particular elements:


Additionally, using text that is in the script Awami Nastaliq is intended for would make it much more apparent. You can get example text with most (all?) SIL font downloads.

**Comment by Nateowami** [comment]
Yes, it is intended to be shown in all browsers. I don't want the limitations to be hidden. If it works on the admin's machine, but not other users, we don't want to hide that fact.

**Comment by josephmyers** [comment]
I see, good point. However, it does leave open the following questions. If you show that warning in the case above, users will wonder if there's something wrong, e.g. "Is the font actually working correctly?" "How do I know if my browser supports Graphite?" This is a lot to expect from them.

Now you _could_ show an additional message putting their concerns to rest, e.g. "Your browser fully supports this font," in the case where it's working and the warning is still shown.

**Comment by Nateowami** [comment]
There is exactly one font we support that requires Graphite. And users of these writing systems tend to be acutely aware that Graphite is required to render their writing system, and that it's not supported in most systems.

**Review by josephmyers — APPROVED** [review]
> Reviewed 6 of 6 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/2548)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @Nateowami)

**Pull request merged**
