### PR TITLE
SF-2709 Various UX cleanup to draft generation

### PR DESCRIPTION
**Pull request by josephmyers**
- Rewrote auto-draft instructions to be more concise
- Linked help page
- Only showing NLLB notice if the language is not supported
- Removed sync notice
- Removed cards and dividers when sensible

- - -
This change is [Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/2439)

### CODE REVIEW

**Review by Nateowami — COMMENTED** [review]
Good work. I know this isn't ready for review, but I added some comments about localization and styling.

> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/2439#-:-NwpzgHqE382q18xdY0-:b48rrv7)* status: 0 of 4 files reviewed, 2 unresolved discussions (waiting on @josephmyers)

___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-generation.component.html` line 25 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/2439#-Nwpw9YxC8P-BG6CgV_h:-Nwpw9YxC8P-BG6CgV_i:bk4g8vd) ([raw file](https://github.com/sillsdev/web-xforge/blob/3fc2fa2cde1083958672e2ed0b78ad6d88dca0e1/src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-generation.component.html#L25)):*
> ```HTML
>     <p>
>       {{ t("instructions_help") }}
>       <a href="https://help.scriptureforge.org/generating-drafts">{{ t("instructions_help_link") }}</a
> ```

This is not the right way to localize this.
- There's no guarantee that the order is the same in other languages
- Localizers in Crowdin won't know these strings go together, so they won't form them into a logical sentence.

Instead do something like:
``` json
{
  "instructions_help": "For more information, { 1 } see the help site{ 2 }."
}
```

And then in the template:
``` html
<ng-container *ngFor="let i of i18n.interpolate('draft_generation.instructions_help')">
  <ng-container *ngIf="i.id == null">{{ i.text }}</ng-container>
  <a *ngIf="i.id === 1" href="https://help.scriptureforge.org/generating-drafts" target="_blank">{{ i.text }}</a>
</ng-container>
```

Another option that would work here (but is less flexible) is `I18nService.translateTextAroundTemplateTags`. There are examples of this in our codebase.
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-generation.component.scss` line 25 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/2439#-Nwpy52E6_DEoPgcEW2Y:-Nwpy52E6_DEoPgcEW2Z:b951abd) ([raw file](https://github.com/sillsdev/web-xforge/blob/3fc2fa2cde1083958672e2ed0b78ad6d88dca0e1/src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-generation.component.scss#L25)):*
> ```SCSS
> 
> .text-header {
>   margin-block-end: -1em;
> ```

It looks to me like there's a lot of extra work to make paragraphs not behave like paragraphs, and make divs behave like paragraphs. I think it's a lot simpler if you work with HTML elements instead of against them:
``` html
    <p>
      <b>{{ t("instructions_keep_in_mind") }}</b>
      <br />
      {{ t("instructions_keep_in_mind_subtext") }}
    </p>
```

**Review by josephmyers — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/2439)* status: 0 of 10 files reviewed, all discussions resolved (waiting on @Nateowami)

___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-generation.component.html` line 25 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/2439#-Nwpw9YxC8P-BG6CgV_h:-Nwqu-AVEdRZEpfCLAav:bnputky) ([raw file](https://github.com/sillsdev/web-xforge/blob/3fc2fa2cde1083958672e2ed0b78ad6d88dca0e1/src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-generation.component.html#L25)):*
<details><summary><i>Previously, Nateowami (Nathaniel Paulus) wrote…</i></summary><blockquote>

This is not the right way to localize this.
- There's no guarantee that the order is the same in other languages
- Localizers in Crowdin won't know these strings go together, so they won't form them into a logical sentence.

Instead do something like:
``` json
{
  "instructions_help": "For more information, { 1 } see the help site{ 2 }."
}
```

And then in the template:
``` html
<ng-container *ngFor="let i of i18n.interpolate('draft_generation.instructions_help')">
  <ng-container *ngIf="i.id == null">{{ i.text }}</ng-container>
  <a *ngIf="i.id === 1" href="https://help.scriptureforge.org/generating-drafts" target="_blank">{{ i.text }}</a>
</ng-container>
```

Another option that would work here (but is less flexible) is `I18nService.translateTextAroundTemplateTags`. There are examples of this in our codebase.
</blockquote></details>

Done. Thanks
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-generation.component.scss` line 25 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/2439#-Nwpy52E6_DEoPgcEW2Y:-Nwqu8_L3ct6cRdN9zH4:b-896fix) ([raw file](https://github.com/sillsdev/web-xforge/blob/3fc2fa2cde1083958672e2ed0b78ad6d88dca0e1/src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-generation.component.scss#L25)):*
<details><summary><i>Previously, Nateowami (Nathaniel Paulus) wrote…</i></summary><blockquote>

It looks to me like there's a lot of extra work to make paragraphs not behave like paragraphs, and make divs behave like paragraphs. I think it's a lot simpler if you work with HTML elements instead of against them:
``` html
    <p>
      <b>{{ t("instructions_keep_in_mind") }}</b>
      <br />
      {{ t("instructions_keep_in_mind_subtext") }}
    </p>
```
</blockquote></details>

Done.

**Review by Nateowami — CHANGES_REQUESTED** [review]
Good work. Partially reviewed.

It's kind of hard to see that this card is a card. The shadow on the left is getting cut off.



Add the class `mat-elevation-z20` and you'll see what I mean (the clip on the left is part of the page, not how I took the screenshot):


I think the card may be better with a class of `mat-elevation-z2`.

> Reviewed 8 of 10 files at r2.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/2439#-:-NwtwI7UBiHKZpVFj8z-:b-o875gx)* status: 8 of 10 files reviewed, 3 unresolved discussions (waiting on @josephmyers)

___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-generation.component.html` line 40 at r2](https://reviewable.io/reviews/sillsdev/web-xforge/2439#-NwtsqTz6sP4ypZyq81j:-Nwtsi_g6bf4ybTh2QjT:b-5yqkeu) ([raw file](https://github.com/sillsdev/web-xforge/blob/f3249d889a7a558a478937f954c97595a51861ed/src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-generation.component.html#L40)):*
> ```HTML
>     </p>
> 
>     <app-notice *ngIf="isBackTranslationMode && !isTargetLanguageSupported" type="primary" class="requirements">
> ```

Instead of a notice, how about making this a warning?


___
*[`src/SIL.XForge.Scripture/ClientApp/src/assets/i18n/non_checking_en.json` line 173 at r2](https://reviewable.io/reviews/sillsdev/web-xforge/2439#-NwtrFYoCVMPZyK5tQro:-NwtrFYoCVMPZyK5tQrp:bgeewym) ([raw file](https://github.com/sillsdev/web-xforge/blob/f3249d889a7a558a478937f954c97595a51861ed/src/SIL.XForge.Scripture/ClientApp/src/assets/i18n/non_checking_en.json#L173)):*
> ```JSON
>     "offline_message": "Draft generation is not available when offline.",
>     "or": "or",
> ```

"or" is no longer used, and there's an empty line here.
___
*[`src/SIL.XForge.Scripture/ClientApp/src/assets/i18n/non_checking_en.json` line 182 at r2](https://reviewable.io/reviews/sillsdev/web-xforge/2439#-NwtvV4U66sK5rmsoVfa:-NwtvV4U66sK5rmsoVfb:b6xxmxv) ([raw file](https://github.com/sillsdev/web-xforge/blob/f3249d889a7a558a478937f954c97595a51861ed/src/SIL.XForge.Scripture/ClientApp/src/assets/i18n/non_checking_en.json#L182)):*
> ```JSON
>     "report_problem": "Report problem",
>     "sign_up_for_drafting": "Sign up for drafting",
>     "suggested_workflow": "A suggested workflow is to draft and edit one book before generating a draft for the next book.",
> ```

suggested_workflow is no longer used.

**Review by josephmyers — COMMENTED** [review]
Thanks, done. Also shifted it over a tiny bit.

> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/2439#-:-NxBNaojABhrwCaHAc4Z:bezjiq1)* status: 7 of 10 files reviewed, 2 unresolved discussions (waiting on @Nateowami)

___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-generation.component.html` line 40 at r2](https://reviewable.io/reviews/sillsdev/web-xforge/2439#-NwtsqTz6sP4ypZyq81j:-NxBOg_C75aajUfoQGzL:b-29rdiu) ([raw file](https://github.com/sillsdev/web-xforge/blob/f3249d889a7a558a478937f954c97595a51861ed/src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-generation.component.html#L40)):*
<details><summary><i>Previously, Nateowami (Nathaniel Paulus) wrote…</i></summary><blockquote>

Instead of a notice, how about making this a warning?


</blockquote></details>

Done. This makes sense
___
*[`src/SIL.XForge.Scripture/ClientApp/src/assets/i18n/non_checking_en.json` line 173 at r2](https://reviewable.io/reviews/sillsdev/web-xforge/2439#-NwtrFYoCVMPZyK5tQro:-NxBOl1r9lhE8S5KyzUu:b-896fix) ([raw file](https://github.com/sillsdev/web-xforge/blob/f3249d889a7a558a478937f954c97595a51861ed/src/SIL.XForge.Scripture/ClientApp/src/assets/i18n/non_checking_en.json#L173)):*
<details><summary><i>Previously, Nateowami (Nathaniel Paulus) wrote…</i></summary><blockquote>

"or" is no longer used, and there's an empty line here.
</blockquote></details>

Done.
___
*[`src/SIL.XForge.Scripture/ClientApp/src/assets/i18n/non_checking_en.json` line 182 at r2](https://reviewable.io/reviews/sillsdev/web-xforge/2439#-NwtvV4U66sK5rmsoVfa:-NxBOmPGApIvIz3ntqbF:b-896fix) ([raw file](https://github.com/sillsdev/web-xforge/blob/f3249d889a7a558a478937f954c97595a51861ed/src/SIL.XForge.Scripture/ClientApp/src/assets/i18n/non_checking_en.json#L182)):*
<details><summary><i>Previously, Nateowami (Nathaniel Paulus) wrote…</i></summary><blockquote>

suggested_workflow is no longer used.
</blockquote></details>

Done.

**Comment by Nateowami** [comment]
I have no option to create a new draft here:

**Comment by josephmyers** [comment]
Superseded by SF-2726

**Pull request closed without merging**
