### PR TITLE
SF-1574 SF-1575 Disable multicursor presence when readonly

### PR DESCRIPTION
**Pull request by irahopkinson**
This change is [Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1376)

### CODE REVIEW

**Review by Nateowami — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1376)* status: all files reviewed, 1 unresolved discussion (waiting on @irahopkinson)

___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/shared/text/text-view-model.ts` line 123 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/1376#-N2r8hcV3Q6MCYqTXo6_:-N2r8hcV3Q6MCYqTXo6a:bbt5eph) ([raw file](https://github.com/sillsdev/web-xforge/blob/0bf588d3b50c56ce94b6d0f42a139e8566e8165e/src/SIL.XForge.Scripture/ClientApp/src/app/shared/text/text-view-model.ts#L123)):*
> ```XML
> export class TextViewModel {
>   readonly cursorColor: string;
>   enablePresenceReceive: boolean = false;
> ```

Does this also disable sending presence? In my testing I was able to select text as a community checker, and a translator would see the selection show up in the editor.

**Review by irahopkinson — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1376)* status: 2 of 3 files reviewed, all discussions resolved (waiting on @RaymondLuong3)

___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/shared/text/text-view-model.ts` line 123 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/1376#-N2r8hcV3Q6MCYqTXo6_:-N2tIznr5pAisi8dCJIf:b-z33dkb) ([raw file](https://github.com/sillsdev/web-xforge/blob/0bf588d3b50c56ce94b6d0f42a139e8566e8165e/src/SIL.XForge.Scripture/ClientApp/src/app/shared/text/text-view-model.ts#L123)):*
<details><summary><i>Previously, Nateowami (Nathaniel Paulus) wrote…</i></summary><blockquote>

Does this also disable sending presence? In my testing I was able to select text as a community checker, and a translator would see the selection show up in the editor.
</blockquote></details>

No, this is only the presence receive in the view model. Line 611 in `text.component.ts` disables the send.

**Comment by irahopkinson** [comment]
*[`src/SIL.XForge.Scripture/ClientApp/src/app/shared/text/text-view-model.ts` line 123 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/1376#-N2r8hcV3Q6MCYqTXo6_:-N2tKo71DB_KztXZ2QPB:bkd4z5f) ([raw file](https://github.com/sillsdev/web-xforge/blob/0bf588d3b50c56ce94b6d0f42a139e8566e8165e/src/SIL.XForge.Scripture/ClientApp/src/app/shared/text/text-view-model.ts#L123)):*
<details><summary><i>Previously, irahopkinson (Ira Hopkinson) wrote…</i></summary><blockquote>

No, this is only the presence receive in the view model. Line 611 in `text.component.ts` disables the send.
</blockquote></details>

I just tried with a _Community Checker_ and a project _Administrator_ and don't see an issue when either select text in the **Checking** tool nor in the **Translate** editor tool.

**Review by Nateowami — COMMENTED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1376)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @irahopkinson)

**Pull request merged**
