### PR TITLE
SF-2792 Restore 40px size for icon buttons

### PR DESCRIPTION
**Pull request by josephmyers**
Before
Reviewable
After
Reviewable

Before
Reviewable
After
Reviewable

This change is [Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/2530)

### CODE REVIEW

**Comment by Nateowami** [comment]
Why? I can see a reason for doing it on the checking page, where we have a lot of icon buttons competing for space, but I don't really see a reason for trying to do this everywhere else.

**Comment by josephmyers** [comment]
Consistency, for one, assuming that's a priority. This impacts the top bar, as well (it is tough to notice, but the top bar icons are all off-centered from the avatar). Secondly, the assumption that many of our components have been laid out as 40px and changing that may have unintended side-effects, like the ones I've fixed here.

**Review by Nateowami — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/2530)* status: 0 of 3 files reviewed, 2 unresolved discussions (waiting on @josephmyers)

___
*[`src/SIL.XForge.Scripture/ClientApp/src/styles.scss` line 61 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/2530#-O-i_P2O3Ur6AcoDNhrf:-O-i_P2O3Ur6AcoDNhrg:bfldbx6) ([raw file](https://github.com/sillsdev/web-xforge/blob/298a0454c2a788a5475660b1b88b678f10f53518/src/SIL.XForge.Scripture/ClientApp/src/styles.scss#L61)):*
> ```SCSS
> button.mdc-icon-button {
>   transition: color 0.15s;
>   --mdc-icon-button-state-layer-size: 40px !important;
> ```

Is this really the right way to do it? Generally if you're having to use `!important` it's an indication that something is not designed very well. Is there not a way to set the size using Material's theme support? Maybe by setting density? We need to work on improving out Material, and soon we'll be doing the Material V3 upgrade. So if we're not working with Material the way it's designed to be used, we're giving ourselves more work.
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking-overview/checking-overview.component.scss` line 15 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/2530#-O-iaLmq8fy6jL7qFSbO:-O-iaLmq8fy6jL7qFSbP:bquu5fr) ([raw file](https://github.com/sillsdev/web-xforge/blob/298a0454c2a788a5475660b1b88b678f10f53518/src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking-overview/checking-overview.component.scss#L15)):*
> ```SCSS
> }
> 
> #add-question-button {
> ```

This really should probably be a FAB on mobile. The current implementation is a misuse of a regular Material button. Otherwise we're going to keep doing "fixes" like this.

**Review by josephmyers — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/2530)* status: 0 of 3 files reviewed, 2 unresolved discussions (waiting on @Nateowami)

___
*[`src/SIL.XForge.Scripture/ClientApp/src/styles.scss` line 61 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/2530#-O-i_P2O3Ur6AcoDNhrf:-O-j5ElB5c70o0IyhDtn:b-9ri9hr) ([raw file](https://github.com/sillsdev/web-xforge/blob/298a0454c2a788a5475660b1b88b678f10f53518/src/SIL.XForge.Scripture/ClientApp/src/styles.scss#L61)):*
<details><summary><i>Previously, Nateowami (Nathaniel Paulus) wrote…</i></summary><blockquote>

Is this really the right way to do it? Generally if you're having to use `!important` it's an indication that something is not designed very well. Is there not a way to set the size using Material's theme support? Maybe by setting density? We need to work on improving out Material, and soon we'll be doing the Material V3 upgrade. So if we're not working with Material the way it's designed to be used, we're giving ourselves more work.
</blockquote></details>

Very possibly. The current thing I'm confused about is why our `styles.scss` is being applied before the theme code.

This seems to me like the root problem, as in my mind our styles would overwrite the theme, which would make `!important` unneeded. I'm looking into this more
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking-overview/checking-overview.component.scss` line 15 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/2530#-O-iaLmq8fy6jL7qFSbO:-O-j6IUn4bi8h4dTDsbJ:bnftcpa) ([raw file](https://github.com/sillsdev/web-xforge/blob/298a0454c2a788a5475660b1b88b678f10f53518/src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking-overview/checking-overview.component.scss#L15)):*
<details><summary><i>Previously, Nateowami (Nathaniel Paulus) wrote…</i></summary><blockquote>

This really should probably be a FAB on mobile. The current implementation is a misuse of a regular Material button. Otherwise we're going to keep doing "fixes" like this.
</blockquote></details>

I think it was done like that to leverage the darker styling, and I don't know a place where we're doing this the "right way." To achieve the same look but with a `mat-icon-button`, we'd likely have to do a nontrivial amount of custom styling. Whoever designed this initially judged that it'd be easier to maintain the way it is now, and imho I think they were probably right.

**Review by josephmyers — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/2530)* status: 0 of 3 files reviewed, 2 unresolved discussions (waiting on @Nateowami)

___
*[`src/SIL.XForge.Scripture/ClientApp/src/styles.scss` line 61 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/2530#-O-i_P2O3Ur6AcoDNhrf:-O-jFERbALYhC2XhW7aI:b-9yn3qy) ([raw file](https://github.com/sillsdev/web-xforge/blob/298a0454c2a788a5475660b1b88b678f10f53518/src/SIL.XForge.Scripture/ClientApp/src/styles.scss#L61)):*
<details><summary><i>Previously, josephmyers wrote…</i></summary><blockquote>

Very possibly. The current thing I'm confused about is why our `styles.scss` is being applied before the theme code.

This seems to me like the root problem, as in my mind our styles would overwrite the theme, which would make `!important` unneeded. I'm looking into this more
</blockquote></details>

I saw `"styles": ["src/styles.scss", "src/material-styles.scss"],` and it really got my hopes up. Unfortunately, swapping the order here didn't solve it...

**Review by josephmyers — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/2530)* status: 0 of 3 files reviewed, 2 unresolved discussions (waiting on @Nateowami)

___
*[`src/SIL.XForge.Scripture/ClientApp/src/styles.scss` line 61 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/2530#-O-i_P2O3Ur6AcoDNhrf:-O-jMAwc6hGv4ZKj07xC:bq4s5u5) ([raw file](https://github.com/sillsdev/web-xforge/blob/298a0454c2a788a5475660b1b88b678f10f53518/src/SIL.XForge.Scripture/ClientApp/src/styles.scss#L61)):*
<details><summary><i>Previously, josephmyers wrote…</i></summary><blockquote>

I saw `"styles": ["src/styles.scss", "src/material-styles.scss"],` and it really got my hopes up. Unfortunately, swapping the order here didn't solve it...
</blockquote></details>

Figured it out. Thanks for pushing me on this

**Review by Nateowami — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/2530)* status: 0 of 3 files reviewed, 2 unresolved discussions (waiting on @josephmyers)

___
*[`src/SIL.XForge.Scripture/ClientApp/src/styles.scss` line 61 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/2530#-O-i_P2O3Ur6AcoDNhrf:-O-kwnDQ2Vx5pF11eDTh:b-3bai8z) ([raw file](https://github.com/sillsdev/web-xforge/blob/298a0454c2a788a5475660b1b88b678f10f53518/src/SIL.XForge.Scripture/ClientApp/src/styles.scss#L61)):*
<details><summary><i>Previously, josephmyers wrote…</i></summary><blockquote>

Figured it out. Thanks for pushing me on this
</blockquote></details>

This is probably a good change, but it's not what I was suggesting, which is setting the density to get the size down to 40px. It looks like a density of `-2` will achieve that. See https://v17.material.angular.io/guide/mdc-migration#theming
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking-overview/checking-overview.component.scss` line 15 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/2530#-O-iaLmq8fy6jL7qFSbO:-O-koy0n-iN6xkd35VqC:b-h22u1t) ([raw file](https://github.com/sillsdev/web-xforge/blob/298a0454c2a788a5475660b1b88b678f10f53518/src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking-overview/checking-overview.component.scss#L15)):*
> To achieve the same look but with a `mat-icon-button`, we'd likely have to do a nontrivial amount of custom styling.

That's why I was suggesting a FAB:
``` html
<button mat-mini-fab color="primary"><mat-icon>post_add</mat-icon></button>
```
It will require adding this to `material-styles.scss` because it was omitted during the upgrade:
``` scss
@include mat.fab-theme($material-app-theme);
```
That does result in this ugly shadow clipping:


But putting a z-index of even 1 on the button fixes it.

**Review by josephmyers — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/2530)* status: 0 of 6 files reviewed, 2 unresolved discussions (waiting on @Nateowami)

___
*[`src/SIL.XForge.Scripture/ClientApp/src/styles.scss` line 61 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/2530#-O-i_P2O3Ur6AcoDNhrf:-O-n4mBn-7Am2aHPVSPI:b-pqrxxc) ([raw file](https://github.com/sillsdev/web-xforge/blob/298a0454c2a788a5475660b1b88b678f10f53518/src/SIL.XForge.Scripture/ClientApp/src/styles.scss#L61)):*
<details><summary><i>Previously, Nateowami (Nathaniel Paulus) wrote…</i></summary><blockquote>

This is probably a good change, but it's not what I was suggesting, which is setting the density to get the size down to 40px. It looks like a density of `-2` will achieve that. See https://v17.material.angular.io/guide/mdc-migration#theming
</blockquote></details>

Ok, I can do this instead. For what it's worth, I'm wondering why they're pushing for this new way. Why is this better than setting the width and height directly? A downside of this is that it makes our rules harder to find and interpret, i.e. settings from us are shown in the dev tools as originating from one of our files, but this isn't.
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking-overview/checking-overview.component.scss` line 15 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/2530#-O-iaLmq8fy6jL7qFSbO:-O-nbcfs5VAzYi5avsR0:b-896fix) ([raw file](https://github.com/sillsdev/web-xforge/blob/298a0454c2a788a5475660b1b88b678f10f53518/src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking-overview/checking-overview.component.scss#L15)):*
<details><summary><i>Previously, Nateowami (Nathaniel Paulus) wrote…</i></summary><blockquote>

> To achieve the same look but with a `mat-icon-button`, we'd likely have to do a nontrivial amount of custom styling.

That's why I was suggesting a FAB:
``` html
<button mat-mini-fab color="primary"><mat-icon>post_add</mat-icon></button>
```
It will require adding this to `material-styles.scss` because it was omitted during the upgrade:
``` scss
@include mat.fab-theme($material-app-theme);
```
That does result in this ugly shadow clipping:


But putting a z-index of even 1 on the button fixes it.
</blockquote></details>

Done.

**Review by Nateowami — COMMENTED** [review]
> Reviewed 1 of 5 files at r3.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/2530)* status: 1 of 6 files reviewed, 2 unresolved discussions (waiting on @josephmyers)

___
*[`src/SIL.XForge.Scripture/ClientApp/src/styles.scss` line 61 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/2530#-O-i_P2O3Ur6AcoDNhrf:-O-q4A6y9wD0Z8kbe7XE:bwid9sz) ([raw file](https://github.com/sillsdev/web-xforge/blob/298a0454c2a788a5475660b1b88b678f10f53518/src/SIL.XForge.Scripture/ClientApp/src/styles.scss#L61)):*
> For what it's worth, I'm wondering why they're pushing for this new way.

I don't think it's new. I think it's about flexibility.
___
*[`src/SIL.XForge.Scripture/ClientApp/src/styles.scss` line 15 at r3](https://reviewable.io/reviews/sillsdev/web-xforge/2530#-O-q3z1J4VIgOhu-oAyH:-O-q3z1K0PcmshEHYWr1:b330ozt) ([raw file](https://github.com/sillsdev/web-xforge/blob/4782ac72248221e30dc89bc2f7f883de9b87b9f0/src/SIL.XForge.Scripture/ClientApp/src/styles.scss#L15)):*
> ```SCSS
>   margin: 0;
>   font-family: Roboto, sans-serif;
>   @include mat.icon-button-density(-2);
> ```

I don't understand why are you doing this here instead of in `material-styles.scss`. Why not configure the size to be denser from the very beginning?

**Review by josephmyers — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/2530)* status: 0 of 6 files reviewed, 2 unresolved discussions (waiting on @Nateowami)

___
*[`src/SIL.XForge.Scripture/ClientApp/src/styles.scss` line 61 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/2530#-O-i_P2O3Ur6AcoDNhrf:-O0DLFte--wRWGkbS6Bi:b-896fix) ([raw file](https://github.com/sillsdev/web-xforge/blob/298a0454c2a788a5475660b1b88b678f10f53518/src/SIL.XForge.Scripture/ClientApp/src/styles.scss#L61)):*
<details><summary><i>Previously, Nateowami (Nathaniel Paulus) wrote…</i></summary><blockquote>

> For what it's worth, I'm wondering why they're pushing for this new way.

I don't think it's new. I think it's about flexibility.
</blockquote></details>

Done.
___
*[`src/SIL.XForge.Scripture/ClientApp/src/styles.scss` line 15 at r3](https://reviewable.io/reviews/sillsdev/web-xforge/2530#-O-q3z1J4VIgOhu-oAyH:-O0DLGsD5ocC9qiFYSfh:b-896fix) ([raw file](https://github.com/sillsdev/web-xforge/blob/4782ac72248221e30dc89bc2f7f883de9b87b9f0/src/SIL.XForge.Scripture/ClientApp/src/styles.scss#L15)):*
<details><summary><i>Previously, Nateowami (Nathaniel Paulus) wrote…</i></summary><blockquote>

I don't understand why are you doing this here instead of in `material-styles.scss`. Why not configure the size to be denser from the very beginning?
</blockquote></details>

Done.

**Review by Nateowami — CHANGES_REQUESTED** [review]
> Reviewed 1 of 3 files at r1, 2 of 5 files at r3, 1 of 2 files at r4.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/2530)* status: 4 of 6 files reviewed, 3 unresolved discussions (waiting on @josephmyers)

___
*[`src/SIL.XForge.Scripture/ClientApp/src/styles.scss` line 3 at r4](https://reviewable.io/reviews/sillsdev/web-xforge/2530#-O0FfbAE-w4jWZgd1Ihl:-O0FfbAE-w4jWZgd1Ihm:b4crqol) ([raw file](https://github.com/sillsdev/web-xforge/blob/f5cdc093f0b94101b8f0f1a9958568f92a1b79e4/src/SIL.XForge.Scripture/ClientApp/src/styles.scss#L3)):*
> ```SCSS
> @use 'sass:map';
> @use 'variables';
> @use '@angular/material' as mat;
> ```

Should not be here anymore.
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking-overview/checking-overview.component.html` line 10 at r4](https://reviewable.io/reviews/sillsdev/web-xforge/2530#-O0Ffq4b66-f53tUBnhq:-O0Ffq4b66-f53tUBnhr:baky71r) ([raw file](https://github.com/sillsdev/web-xforge/blob/f5cdc093f0b94101b8f0f1a9958568f92a1b79e4/src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking-overview/checking-overview.component.html#L10)):*
> ```HTML
>       </button>
>       <button
>         *ngIf="!isLoading && !isScreenSmall"
> ```

Subscribing to viewport size changes is a lot of work just to show/hide elements. Consider `class="hide-lt-sm"`
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking-overview/checking-overview.component.html` line 20 at r4](https://reviewable.io/reviews/sillsdev/web-xforge/2530#-O0Fg8VXAzKx85jh2HOP:-O0Fg8VXAzKx85jh2HOQ:b-eayrzo) ([raw file](https://github.com/sillsdev/web-xforge/blob/f5cdc093f0b94101b8f0f1a9958568f92a1b79e4/src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking-overview/checking-overview.component.html#L20)):*
> ```HTML
>       </button>
>       <button
>         *ngIf="!isLoading && isScreenSmall"
> ```

Consider `class="hide-gt-sm"`

**Review by josephmyers — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/2530)* status: 2 of 6 files reviewed, 2 unresolved discussions (waiting on @Nateowami)

___
*[`src/SIL.XForge.Scripture/ClientApp/src/styles.scss` line 3 at r4](https://reviewable.io/reviews/sillsdev/web-xforge/2530#-O0FfbAE-w4jWZgd1Ihl:-O0HYEiq1RIH_pzJaK7r:b-896fix) ([raw file](https://github.com/sillsdev/web-xforge/blob/f5cdc093f0b94101b8f0f1a9958568f92a1b79e4/src/SIL.XForge.Scripture/ClientApp/src/styles.scss#L3)):*
<details><summary><i>Previously, Nateowami (Nathaniel Paulus) wrote…</i></summary><blockquote>

Should not be here anymore.
</blockquote></details>

Done.
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking-overview/checking-overview.component.html` line 10 at r4](https://reviewable.io/reviews/sillsdev/web-xforge/2530#-O0Ffq4b66-f53tUBnhq:-O0HZgi5-L6CO1ytbwkh:b-896fix) ([raw file](https://github.com/sillsdev/web-xforge/blob/f5cdc093f0b94101b8f0f1a9958568f92a1b79e4/src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking-overview/checking-overview.component.html#L10)):*
<details><summary><i>Previously, Nateowami (Nathaniel Paulus) wrote…</i></summary><blockquote>

Subscribing to viewport size changes is a lot of work just to show/hide elements. Consider `class="hide-lt-sm"`
</blockquote></details>

Done.
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking-overview/checking-overview.component.html` line 20 at r4](https://reviewable.io/reviews/sillsdev/web-xforge/2530#-O0Fg8VXAzKx85jh2HOP:-O0HdDRn5mcXKiPWYBvP:b-896fix) ([raw file](https://github.com/sillsdev/web-xforge/blob/f5cdc093f0b94101b8f0f1a9958568f92a1b79e4/src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking-overview/checking-overview.component.html#L20)):*
<details><summary><i>Previously, Nateowami (Nathaniel Paulus) wrote…</i></summary><blockquote>

Consider `class="hide-gt-sm"`
</blockquote></details>

Done.

**Review by Nateowami — CHANGES_REQUESTED** [review]
> Reviewed 1 of 2 files at r4, 2 of 3 files at r5.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/2530)* status: 5 of 6 files reviewed, 1 unresolved discussion (waiting on @josephmyers)

___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking-overview/checking-overview.component.ts` line 71 at r5](https://reviewable.io/reviews/sillsdev/web-xforge/2530#-O0L11vk8OC35eoxFtU5:-O0L11vk8OC35eoxFtU6:bp9pwqo) ([raw file](https://github.com/sillsdev/web-xforge/blob/b4ced742cbf6a420bc596b508bf0a0d086bc2df2/src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking-overview/checking-overview.component.ts#L71)):*
> ```XML
>     readonly featureFlagsService: FeatureFlagService,
>     private readonly breakpointObserver: BreakpointObserver,
>     private readonly mediaBreakpointService: MediaBreakpointService
> ```

These should be removed.

**Review by Nateowami — APPROVED** [review]
> Reviewed 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/2530)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @josephmyers)

**Review by Nateowami — APPROVED** [review]
> Reviewed 3 of 3 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/2530)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @josephmyers)

**Pull request merged**
