### PR TITLE
SF-2175 Recover from build status 'Faulted'

### PR DESCRIPTION
**Pull request by siltomato**
- A build job state of `Faulted` will now result in a warning shown to user with a prompt to start a new build.

- - -
This change is [Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1996)

### CODE REVIEW

**Review by RaymondLuong3 — CHANGES_REQUESTED** [review]
@pmachapman It looks like Colin was thinking on the same lines that we were and decided that we should not offer the ability to cancel a build until it is active or pending. I think we can still merge your changes, or you will have to update your changes to reflect that cancel build will never be called until the build is uploaded or active.

> Reviewed 8 of 8 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1996#-:-NdbULP43HQoY93sdFll:bm410r8)* status: all files reviewed, 2 unresolved discussions (waiting on @Nateowami, @pmachapman, and @siltomato)

___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-generation.component.ts` line 172 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/1996#-NdbS5vuCH_zSScpDIu_:-NdbS5vuCH_zSScpDIua:b-ttlrym) ([raw file](https://github.com/sillsdev/web-xforge/blob/982537b0d84800a821253c32ae0f014397af1473/src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-generation.component.ts#L172)):*
> ```XML
>   }
> 
>   pollBuild(): void {
> ```

Looks like pollBuild can be made private.



_Code quote:_
```XML
  pollBuild(): void {
```
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-generation.component.ts` line 194 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/1996#-NdbToElD4H0iKvr7cQy:-NdbToElD4H0iKvr7cQz:bgqkcxm) ([raw file](https://github.com/sillsdev/web-xforge/blob/982537b0d84800a821253c32ae0f014397af1473/src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-generation.component.ts#L194)):*
> ```XML
>   }
> 
>   cancelBuild(): void {
> ```

cancelBuild can be made private.



_Code quote:_
```XML
  cancelBuild(): void {
```

**Review by RaymondLuong3 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1996)* status: all files reviewed, 3 unresolved discussions (waiting on @Nateowami, @pmachapman, and @siltomato)

___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-generation.component.ts` line 7 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/1996#-NdbVxC01lmkguGxh3qU:-NdbVxC01lmkguGxh3qV:b-1qep5q) ([raw file](https://github.com/sillsdev/web-xforge/blob/982537b0d84800a821253c32ae0f014397af1473/src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-generation.component.ts#L7)):*
> ```XML
> import { Observable, of, Subscription } from 'rxjs';
> import { map, switchMap, tap } from 'rxjs/operators';
> import { BuildDto } from 'src/app/machine-api/build-dto';
> ```

Change this to a relative path.



_Code quote:_
```XML
import { BuildDto } from 'src/app/machine-api/build-dto';
```

**Review by pmachapman — CHANGES_REQUESTED** [review]
Yes, it definitely appears we were thinking along the same lines.

I have merged #1991, and have stripped any of frontend code I added in from #2038 to make this PR and my PR more complimentary.

> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1996#-:-NdbsHvNBRTCoAcXAIsv:b-wz7iar)* status: all files reviewed, 6 unresolved discussions (waiting on @Nateowami and @siltomato)

___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-generation.ts` line 29 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/1996#-NdbtU-H9nw1iMvU4u4q:-NdbtU-H9nw1iMvU4u4r:b-sp0aql) ([raw file](https://github.com/sillsdev/web-xforge/blob/982537b0d84800a821253c32ae0f014397af1473/src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-generation.ts#L29)):*
> ```XML
>     providedIn: 'root',
>     factory: () => ({
>       pollRate: 1000 * 10 // Default to 10 seconds
> ```

We should write this as `10_000`, as we have elsewhere to show time periods in milliseconds (i.e in `pwa.service.ts` and `page-not-found.component.ts`.



_Code quote:_
```XML
1000 * 10
```
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-generation.service.ts` line 108 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/1996#-NdbrUGX4c5auccmcjEK:-NdbrUGX4c5auccmcjEL:b-xvijhj) ([raw file](https://github.com/sillsdev/web-xforge/blob/982537b0d84800a821253c32ae0f014397af1473/src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-generation.service.ts#L108)):*
> ```XML
>    * Cancels any pretranslation builds for the specified project.
>    * Build can be canceled if its state is `Active` or `Pending`.
>    * A `Queued` build is uploading to serval and cannot yet be canceled (attempt will result in 404).
> ```

#1991 has been merged, which means that jobs can now be cancelled during the upload to Serval.
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-generation.service.ts` line 114 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/1996#-NdbrelsClFaF7EFYJU2:-NdbrelsClFaF7EFYJU3:b-60ajw1) ([raw file](https://github.com/sillsdev/web-xforge/blob/982537b0d84800a821253c32ae0f014397af1473/src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-generation.service.ts#L114)):*
> ```XML
>     return this.httpClient
>       .post<void>(`translation/pretranslations/cancel`, JSON.stringify(projectId))
>       .pipe(map(res => res.data));
> ```

The 404 code is still important to catch and not throw as it does denote that the job is not running on Serval (and the bug where this occurs mid-upload has been fixed in master).

**Review by Nateowami — COMMENTED** [review]
> Reviewed 3 of 8 files at r1.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1996)* status: all files reviewed, 6 unresolved discussions (waiting on @siltomato)

___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-generation.component.ts` line 7 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/1996#-NdbVxC01lmkguGxh3qU:-NdexvRH6WEw97tkLCWE:bu17uc9) ([raw file](https://github.com/sillsdev/web-xforge/blob/982537b0d84800a821253c32ae0f014397af1473/src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-generation.component.ts#L7)):*
<details><summary><i>Previously, RaymondLuong3 (Raymond Luong) wrote…</i></summary><blockquote>

Change this to a relative path.
</blockquote></details>

@siltomato
I can't remember what the rationale was, but several years back we decided to standardize on relative imports of other files (`../../something` rather than absolute imports (`src/some/place`).

More recently I've been thinking if we used absolute imports, then it would be possible to move a file without the imports in the file itself breaking. Imports of that file would still need to be updated, but it would be an easy process, because if you moved it to `src/some/place/component.ts`, you could update all the imports to that exact string. VS Code can do automatic import updates when moving a file, so it may not be that big a deal.

Anyway, starting to wonder if we made the wrong choice, but it's hard to know because I don't remember the original reasoning.

Searching our code base, I see 27 absolute imports, and 710 relative imports.

Anyway, as of now our unwritten rule is to use relative imports for consistency.

**Review by siltomato — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1996)* status: 4 of 8 files reviewed, 6 unresolved discussions (waiting on @Nateowami, @pmachapman, and @RaymondLuong3)

___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-generation.ts` line 29 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/1996#-NdbtU-H9nw1iMvU4u4q:-NdfFcAB7Ih9rZtohlnW:b-896fix) ([raw file](https://github.com/sillsdev/web-xforge/blob/982537b0d84800a821253c32ae0f014397af1473/src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-generation.ts#L29)):*
<details><summary><i>Previously, pmachapman (Peter Chapman) wrote…</i></summary><blockquote>

We should write this as `10_000`, as we have elsewhere to show time periods in milliseconds (i.e in `pwa.service.ts` and `page-not-found.component.ts`.
</blockquote></details>

Done.
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-generation.component.ts` line 7 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/1996#-NdbVxC01lmkguGxh3qU:-NdfFr4A8giwwIvsL2cK:b-gjlbkt) ([raw file](https://github.com/sillsdev/web-xforge/blob/982537b0d84800a821253c32ae0f014397af1473/src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-generation.component.ts#L7)):*
<details><summary><i>Previously, Nateowami (Nathaniel Paulus) wrote…</i></summary><blockquote>

@siltomato
I can't remember what the rationale was, but several years back we decided to standardize on relative imports of other files (`../../something` rather than absolute imports (`src/some/place`).

More recently I've been thinking if we used absolute imports, then it would be possible to move a file without the imports in the file itself breaking. Imports of that file would still need to be updated, but it would be an easy process, because if you moved it to `src/some/place/component.ts`, you could update all the imports to that exact string. VS Code can do automatic import updates when moving a file, so it may not be that big a deal.

Anyway, starting to wonder if we made the wrong choice, but it's hard to know because I don't remember the original reasoning.

Searching our code base, I see 27 absolute imports, and 710 relative imports.

Anyway, as of now our unwritten rule is to use relative imports for consistency.
</blockquote></details>

No problem.  I'll try to remember that when adding the import from intellisense.
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-generation.component.ts` line 172 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/1996#-NdbS5vuCH_zSScpDIu_:-NdfGzv87gwZtWZ8Cwkk:b-896fix) ([raw file](https://github.com/sillsdev/web-xforge/blob/982537b0d84800a821253c32ae0f014397af1473/src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-generation.component.ts#L172)):*
<details><summary><i>Previously, RaymondLuong3 (Raymond Luong) wrote…</i></summary><blockquote>

Looks like pollBuild can be made private.
</blockquote></details>

Done.
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-generation.component.ts` line 194 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/1996#-NdbToElD4H0iKvr7cQy:-NdfH-GD-nj3YyOC8M_X:b-896fix) ([raw file](https://github.com/sillsdev/web-xforge/blob/982537b0d84800a821253c32ae0f014397af1473/src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-generation.component.ts#L194)):*
<details><summary><i>Previously, RaymondLuong3 (Raymond Luong) wrote…</i></summary><blockquote>

cancelBuild can be made private.
</blockquote></details>

Done.
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-generation.service.ts` line 108 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/1996#-NdbrUGX4c5auccmcjEK:-NdfhBRjDZXrNXTHdNLp:b-98t8wf) ([raw file](https://github.com/sillsdev/web-xforge/blob/982537b0d84800a821253c32ae0f014397af1473/src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-generation.service.ts#L108)):*
<details><summary><i>Previously, pmachapman (Peter Chapman) wrote…</i></summary><blockquote>

#1991 has been merged, which means that jobs can now be cancelled during the upload to Serval.
</blockquote></details>

Cool... reverted UI restriction.
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-generation.service.ts` line 114 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/1996#-NdbrelsClFaF7EFYJU2:-NdfimFo3sx0CzxSRpQQ:b-896fix) ([raw file](https://github.com/sillsdev/web-xforge/blob/982537b0d84800a821253c32ae0f014397af1473/src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-generation.service.ts#L114)):*
<details><summary><i>Previously, pmachapman (Peter Chapman) wrote…</i></summary><blockquote>

The 404 code is still important to catch and not throw as it does denote that the job is not running on Serval (and the bug where this occurs mid-upload has been fixed in master).
</blockquote></details>

Done.

**Review by pmachapman — COMMENTED** [review]
> Reviewed 4 of 4 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1996)* status: all files reviewed, 3 unresolved discussions (waiting on @RaymondLuong3)

**Comment by Nateowami** [comment]
@pmachapman Did you mean to approve this PR, or dismiss your previous request for changes? Right now you're still shown as requesting changes to the PR, though I think all requested changes were addressed.

**Review by pmachapman — COMMENTED** [review]
All my points were sorted. I thought GitHub would clear the red cross next to my name...

> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1996#-:-NdgM8I-43yYfgtKCrrZ:b5a6a75)* status: all files reviewed, 3 unresolved discussions (waiting on @RaymondLuong3)

**Review by RaymondLuong3 — CHANGES_REQUESTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1996)* status: all files reviewed, 3 unresolved discussions (waiting on @siltomato)

___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-generation.component.ts` line 172 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/1996#-NdbS5vuCH_zSScpDIu_:-NdgOHXdEB-zlu1hMwNE:b-dfk91o) ([raw file](https://github.com/sillsdev/web-xforge/blob/982537b0d84800a821253c32ae0f014397af1473/src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-generation.component.ts#L172)):*
<details><summary><i>Previously, siltomato wrote…</i></summary><blockquote>

Done.
</blockquote></details>

You will want to move the private methods below the public ones.
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-generation.component.ts` line 194 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/1996#-NdbToElD4H0iKvr7cQy:-NdgOLM92edMYCPDqYWq:b-q64pkt) ([raw file](https://github.com/sillsdev/web-xforge/blob/982537b0d84800a821253c32ae0f014397af1473/src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-generation.component.ts#L194)):*
<details><summary><i>Previously, siltomato wrote…</i></summary><blockquote>

Done.
</blockquote></details>

See above.
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-generation.component.ts` line 251 at r2](https://reviewable.io/reviews/sillsdev/web-xforge/1996#-NdgOWxl5cTThoLb1Wj0:-NdgOWxl5cTThoLb1Wj1:b-f4v6q2) ([raw file](https://github.com/sillsdev/web-xforge/blob/c68d5576fc7162d2985459aec3a73a9f512daade/src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-generation.component.ts#L251)):*
> ```XML
> 
>   canCancel(job?: BuildDto): boolean {
>     return !job || this.isDraftInProgress(job);
> ```

Can we make this `job == null || this.isDraftInProgress`



_Code quote:_
```XML
return !job || this.isDraftInProgress(job);
```

**Comment by Nateowami** [comment]
@pmachapman You can either approve, or you can dismiss your own review:

**Comment by pmachapman** [comment]
> @pmachapman You can either approve, or you can dismiss your own review:
> 
> 

@Nateowami I don't have that option?

image

**Review by siltomato — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1996)* status: 7 of 8 files reviewed, 3 unresolved discussions (waiting on @pmachapman and @RaymondLuong3)

___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-generation.component.ts` line 172 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/1996#-NdbS5vuCH_zSScpDIu_:-NdgWtkYEW9yIt-mgMmY:b-896fix) ([raw file](https://github.com/sillsdev/web-xforge/blob/982537b0d84800a821253c32ae0f014397af1473/src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-generation.component.ts#L172)):*
<details><summary><i>Previously, RaymondLuong3 (Raymond Luong) wrote…</i></summary><blockquote>

You will want to move the private methods below the public ones.
</blockquote></details>

Done.
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-generation.component.ts` line 194 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/1996#-NdbToElD4H0iKvr7cQy:-NdgWsuZEagqShlCPsDh:b-896fix) ([raw file](https://github.com/sillsdev/web-xforge/blob/982537b0d84800a821253c32ae0f014397af1473/src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-generation.component.ts#L194)):*
<details><summary><i>Previously, RaymondLuong3 (Raymond Luong) wrote…</i></summary><blockquote>

See above.
</blockquote></details>

Done.
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-generation.component.ts` line 251 at r2](https://reviewable.io/reviews/sillsdev/web-xforge/1996#-NdgOWxl5cTThoLb1Wj0:-NdgWrbq9vPhLvJKyZCR:b-896fix) ([raw file](https://github.com/sillsdev/web-xforge/blob/c68d5576fc7162d2985459aec3a73a9f512daade/src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-generation.component.ts#L251)):*
<details><summary><i>Previously, RaymondLuong3 (Raymond Luong) wrote…</i></summary><blockquote>

Can we make this `job == null || this.isDraftInProgress`
</blockquote></details>

Done.

**Review by RaymondLuong3 — APPROVED** [review]
You should update the title of this PR now. Other than that, I approve. Good job.

> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1996#-:-NdgfaG6511tEGRZF8pE:b-txa2gk)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @siltomato)

**Review by siltomato — COMMENTED** [review]
Done.

> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1996#-:-Ndgg9xD-HjUEQfUiPFI:b-896fix)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @siltomato)

**Review by pmachapman — APPROVED** [review]
:lgtm:

> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1996#-:-NdhNbXF6S1jZECmcVJ9:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @siltomato)

**Pull request merged**
