### PR TITLE
SF-2143 Adjust 503 error page wording

### PR DESCRIPTION
**Pull request by marksvc**
commit-id:08981ddd

- - -
This change is [Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1986)

### CODE REVIEW

**Comment by marksvc** [comment]
Current/previous 503 error page:

image

Proposed/new 503 error page:

image

And with a narrow viewport:

image

**Comment by marksvc** [comment]
Oops, need to test a bit more about whether existing SF sessions can indeed keep working or if they get this error page. Marked as draft.

**Review by Nateowami — COMMENTED** [review]
1. It appears a bunch of unrelated commits were added to this PR.
2. For the error message, let's keep it short and simple.

My suggestion would be:
``` diff
                 <div class="content">
                     <h1>Scripture Forge</h1>
                     <h2>Is not available right now</h2>
-                    <p>
-                        Scripture Forge is likely being upgraded so we can add new features. Unfortunately we needed to
-                        switch it off today to do that.
-                    </p>
                     <p>
                         Please
                         <a
                             href="https://community.scripture.software.sil.org/t/scripture-forge-announcements/1776"
                             target="_blank"
                             >check here for announcements</a
                         >
-                        of scheduled upgrades.
+                        of scheduled maintenance or upgrades.
                     </p>
                 </div>
```

The message about existing sessions seems irrelevant to me, since even if it was true, it would just mean you wouldn't see this page. "For those not seeing this message, the site should be working fine."

> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1986#-:-NaxHm55CDT2VieZzKBq:b-1hzop4)* status: 0 of 5 files reviewed, all discussions resolved

**Comment by marksvc** [comment]
SF sessions can keep working offline, unless they access the site root directly, which an issue has been made about at https://jira.sil.org/browse/SF-2182.

**Comment by marksvc** [comment]
@Nateowami Hey, I bet the bunch of commits are there because of the re-write of master! There is a note in this PR's history saying "Nateowami force-pushed the master branch from 9ed6a99 to c38c5f0 last week".

**Comment by marksvc** [comment]
New version:

image

image

**Comment by Nateowami** [comment]
@marksvc I like it. Though I think left-align is better than aligning to the center, even on mobile.

**Comment by marksvc** [comment]
Here is with text left-aligned. I tried moving the logo to the left as well and it didn't look too good imo. 

image

**Comment by Nateowami** [comment]
Looks good (I was mainly meaning the paragraph should be left aligned; I agree with keeping the icon centralized, and I could go either way with the "unavailable" title).

**Comment by marksvc** [comment]
image

image

**Review by Nateowami — APPROVED** [review]
:lgtm:

> Reviewed 4 of 5 files at r4, 1 of 1 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1986#-:-NbuWEgUBvBUgdGH0AUL:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @marksvc)

**Pull request merged**
