### PR TITLE
SF-2196 Chapter Audio Matches Original Design

### PR DESCRIPTION
**Pull request by nigel-wells**
* Adjusted CSS on buttons, slider, and text
* Created Storybook for the audio player

This change just covers the audio player that appears over the text.

**BEFORE**
image

**AFTER**
image

- - -
This change is [Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/2016)

### CODE REVIEW

**Review by RaymondLuong3 — CHANGES_REQUESTED** [review]
It looks good. And thanks for the story. Just a minor comment then it is good to go.

> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/2016#-:-NcZGBExEDlYL-Z_JdUf:bwrnvkx)* status: all files reviewed, 1 unresolved discussion (waiting on @josephmyers and @nigel-wells)

___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-scripture-audio-player/checking-scripture-audio-player.stories.ts` line 27 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/2016#-NcZFDTs6ekWjR-lLoXb:-NcZFDTt5W61W5IcyNun:b-onq3kp) ([raw file](https://github.com/sillsdev/web-xforge/blob/bc96f29700faeadf2c8ac160fa142e9ce1e03838/src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-scripture-audio-player/checking-scripture-audio-player.stories.ts#L27)):*
> ```XML
> 
> const meta: Meta = {
>   title: 'Checking/Text/Scripture Audio Player',
> ```

I'm not quite sure if it belongs in a Text folder. The component is at the root checking level in the folder and is used from the Checking Component. Also, since we may be hiding the text panel, the player may not be associated with text. What do you think about the path 'Checking/Scripture Audio/Scripture Audio Player'



_Code quote:_
```XML
  title: 'Checking/Text/Scripture Audio Player',
```

**Review by RaymondLuong3 — COMMENTED** [review]
Oh yes, while you are hear, how about updating the icons to mirror when the language is in RTL


> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/2016#-:-NcZRSk31WyywR8c8fs7:bl2pmm4)* status: all files reviewed, 1 unresolved discussion (waiting on @josephmyers and @nigel-wells)

**Review by nigel-wells — COMMENTED** [review]
Thanks for the reminder @RaymondLuong3  - done!

> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/2016#-:-Nc_8ejc1ZYznEwIoe5h:by7nr8g)* status: 2 of 4 files reviewed, 1 unresolved discussion (waiting on @josephmyers and @RaymondLuong3)

___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-scripture-audio-player/checking-scripture-audio-player.stories.ts` line 27 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/2016#-NcZFDTs6ekWjR-lLoXb:-Nc_9s287iexosX0r3CS:bgnofxv) ([raw file](https://github.com/sillsdev/web-xforge/blob/bc96f29700faeadf2c8ac160fa142e9ce1e03838/src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-scripture-audio-player/checking-scripture-audio-player.stories.ts#L27)):*
<details><summary><i>Previously, RaymondLuong3 (Raymond Luong) wrote…</i></summary><blockquote>

I'm not quite sure if it belongs in a Text folder. The component is at the root checking level in the folder and is used from the Checking Component. Also, since we may be hiding the text panel, the player may not be associated with text. What do you think about the path 'Checking/Scripture Audio/Scripture Audio Player'
</blockquote></details>

Good point. I've changed it to be `Checking/Scripture Audio`. Confusingly there is another story called `Components/Checking Audio` which is our main audio player used in questions and answers. We should look to consolidate these once the scripture audio is closer to MVP as there is another PR out which needs to be merged before we consider renaming the `Checking Audio` title` to something more applicable.

**Review by RaymondLuong3 — APPROVED** [review]
:lgtm: 

> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/2016#-:-NccWCKJEGuYzW9L_p97:bg7igkv)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @josephmyers)

**Pull request merged**
