### PR TITLE
SF-1573 disable multi-cursor presence when offline

### PR DESCRIPTION
**Pull request by irahopkinson**
This change is [Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1378)

### CODE REVIEW

**Review by nigel-wells — COMMENTED** [review]
This PR seems fine, however it feels like the relevant avatar isn't appearing when I'd expect it to. I expected it to show when both users were on the same book and chapter. I could only ever see the avatar of someone else after navigating to another chapter +/- 1 from the chapter the other user was actually on - it's not 100% that rule but close.

> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1378#-:-N2yDhDW8e6lUrRIZGfv:bnnhds6)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @irahopkinson)

**Review by irahopkinson — COMMENTED** [review]
Are you talking about when its offline or online. Can you post re-pro steps of what you found?

> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1378#-:-N2zdpevAfVPDEKot6Cg:b-8db85e)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @irahopkinson)

**Review by nigel-wells — COMMENTED** [review]
Online mode. Offline appeared to be ok as the presence disappeared as expected.

My test was:
* Admin shares project with a user via shareable link as a "View Translation"
* Both users logged in at the same time via different browsers (Admin on Chrome, Translator on Edge both on Windows 11)
* Both users viewing Matthew 1
* Neither user can see the other avatar
* Admin navigates to chapter 2 - neither user can see the other avatar
* Translator navigates to chapter 2 - neither user can see the other avatar
* Translator navigates back to chapter 1 - now the translator sees the avatar for admin even though admin is still on chapter 2

> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1378#-:-N32p4YzDDEysrxSW8Of:bpjkh1f)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @irahopkinson)

**Comment by Nateowami** [comment]
@irahopkinson See our tester notes for May 25. I think they found the same thing Nigel is seeing.

**Review by irahopkinson — COMMENTED** [review]
@nigel-wells OK so out of scope for this PR but good to address.

Given that you shared as _View Translation_ then the user would normally be a view-only (unless they also had a PT account and some access to the project in PT) so the viewer avatar now only shows if the users can edit, i.e. both users would need edit access to see each others viewer avatar and cursor. I think the last item is covered by issue SF-1572.

> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1378#-:-N32svU137_B7kQ5FwWE:b-e0qbkb)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @irahopkinson)

**Review by irahopkinson — COMMENTED** [review]
@nateowami can you send me a link to that testers notes doc in Slack.

> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1378#-:-N32uQY5A64MaxzDMOMQ:b-omi2ne)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @irahopkinson)

**Review by nigel-wells — APPROVED** [review]
All under control then - I won't hold up this PR.

> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1378#-:-N33KVoL5rVajy9C_g-m:b-2ul113)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @irahopkinson)

**Pull request merged**
