### PR TITLE
SF-2441 Focus draft tab on draft nav

### PR DESCRIPTION
**Pull request by siltomato**
- Editor looks for URL query param `draft-active=true` to focus the draft tab.
- Modified `updateAutoDraftTabVisibility()` to only add a draft tab to 'source' if one isn't already in the tab state for either 'source' or 'target'.
- Removes 'draft-active' query string from url when another tab from 'source' is selected.

- - -
This change is [Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/2486)

### CODE REVIEW

**Comment by Nateowami** [comment]
This is working great; thanks. Are there still changes coming that make it a draft PR?

**Review by Nateowami — COMMENTED** [review]
> Reviewed 2 of 4 files at r1, 1 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/2486)* status: 2 of 5 files reviewed, 1 unresolved discussion (waiting on @siltomato)

___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.ts` line 1332 at r2](https://reviewable.io/reviews/sillsdev/web-xforge/2486#-Nyg_Twx51G7uNQfxy21:-Nyg_Twx51G7uNQfxy22:bi2bygt) ([raw file](https://github.com/sillsdev/web-xforge/blob/3dd2e3848a8d62546c84329d51f99f792d4667e1/src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.ts#L1332)):*
> ```XML
>           .subscribe(() => {
>             this.router.navigate([], {
>               queryParams: { 'draft-active': null },
> ```

Good catch. I was about to comment this when I saw you had updated the PR. However, I tested this locally *before* you made the update, and it worked. It seems like it shouldn't have...

Also, if you wanted to keep paramKey as a variable, you should be able to do that with ` queryParams: { [paramKey]: null },`

**Review by siltomato — COMMENTED** [review]
I added the query param to router link in `DraftPreviewBooksComponent`.  Is there another place it needs to be added?

> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/2486#-:-Nyg__do4GL8hJOHyR71:b-ml08b2)* status: 2 of 5 files reviewed, all discussions resolved (waiting on @Nateowami)

___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.ts` line 1332 at r2](https://reviewable.io/reviews/sillsdev/web-xforge/2486#-Nyg_Twx51G7uNQfxy21:-Nyg_xxe1Ywtq4zOVuoE:b-egvqe0) ([raw file](https://github.com/sillsdev/web-xforge/blob/3dd2e3848a8d62546c84329d51f99f792d4667e1/src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.ts#L1332)):*
<details><summary><i>Previously, Nateowami (Nathaniel Paulus) wrote…</i></summary><blockquote>

Good catch. I was about to comment this when I saw you had updated the PR. However, I tested this locally *before* you made the update, and it worked. It seems like it shouldn't have...

Also, if you wanted to keep paramKey as a variable, you should be able to do that with ` queryParams: { [paramKey]: null },`
</blockquote></details>

Ah, cool, nice one.  I'll have to remember that!

**Review by Nateowami — COMMENTED** [review]
> I added the query param to router link in `DraftPreviewBooksComponent`. Is there another place it needs to be added?

No; that's the only place, at least for now.

> Reviewed 1 of 4 files at r1, 1 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/2486#-:-NygbULv4YYI0zXMj1pS:b-vkxqa4)* status: 4 of 5 files reviewed, 1 unresolved discussion (waiting on @siltomato)

___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.spec.ts` line 3826 at r2](https://reviewable.io/reviews/sillsdev/web-xforge/2486#-Nygb6kf7YhsPzRzy06o:-Nygb6kf7YhsPzRzy06p:bmz8p0n) ([raw file](https://github.com/sillsdev/web-xforge/blob/3dd2e3848a8d62546c84329d51f99f792d4667e1/src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.spec.ts#L3826)):*
> ```XML
> 
>       env.component.tabState.tabs$.pipe(take(1)).subscribe(tabs => {
>         expect(tabs.filter(tab => tab.type === 'draft')[0]?.isSelected).toBe(true);
> ```

Filtering an array and taking the first result is the same as Array.find. This could just be:
``` ts
expect(tabs.find(tab => tab.type === 'draft')?.isSelected).toBe(true);
```

(Same below)

Also, having expectations only in a subscription makes it difficult to be certain your expectations actually run.

**Review by Nateowami — APPROVED** [review]
:lgtm:

I've commented some things that could be improved, but I'd be happy to merge as-is after I do a bit more testing.

> Reviewed 1 of 4 files at r1.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/2486#-:-NygbyCwE5TDdvf0c2TI:bbnx55l)* status: all files reviewed, 1 unresolved discussion (waiting on @siltomato)

**Review by Nateowami — APPROVED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/2486)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @siltomato)

**Review by siltomato — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/2486)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @siltomato)

___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.spec.ts` line 3826 at r2](https://reviewable.io/reviews/sillsdev/web-xforge/2486#-Nygb6kf7YhsPzRzy06o:-NygfGhv6SvHEeH6PTos:b-30vee2) ([raw file](https://github.com/sillsdev/web-xforge/blob/3dd2e3848a8d62546c84329d51f99f792d4667e1/src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.spec.ts#L3826)):*
<details><summary><i>Previously, Nateowami (Nathaniel Paulus) wrote…</i></summary><blockquote>

Filtering an array and taking the first result is the same as Array.find. This could just be:
``` ts
expect(tabs.find(tab => tab.type === 'draft')?.isSelected).toBe(true);
```

(Same below)

Also, having expectations only in a subscription makes it difficult to be certain your expectations actually run.
</blockquote></details>

Good catch.  Fixed.  What's the best way to not run in the subscription?

**Review by Nateowami — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/2486)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @siltomato)

___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.spec.ts` line 3826 at r2](https://reviewable.io/reviews/sillsdev/web-xforge/2486#-Nygb6kf7YhsPzRzy06o:-NygjrNcC4ORx6RXaso6:bu8g0tl) ([raw file](https://github.com/sillsdev/web-xforge/blob/3dd2e3848a8d62546c84329d51f99f792d4667e1/src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.spec.ts#L3826)):*
<details><summary><i>Previously, siltomato wrote…</i></summary><blockquote>

Good catch.  Fixed.  What's the best way to not run in the subscription?
</blockquote></details>

One option would be awaiting a promise. But it's not critical. Do you want to just go ahead and merge it? It can be tested after merging. This is the final piece of the puzzle for next week's release.

**Review by siltomato — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/2486)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @siltomato)

___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.spec.ts` line 3826 at r2](https://reviewable.io/reviews/sillsdev/web-xforge/2486#-Nygb6kf7YhsPzRzy06o:-NygkIwmAg0Cdy5YAULf:b-80tlqk) ([raw file](https://github.com/sillsdev/web-xforge/blob/3dd2e3848a8d62546c84329d51f99f792d4667e1/src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.spec.ts#L3826)):*
<details><summary><i>Previously, Nateowami (Nathaniel Paulus) wrote…</i></summary><blockquote>

One option would be awaiting a promise. But it's not critical. Do you want to just go ahead and merge it? It can be tested after merging. This is the final piece of the puzzle for next week's release.
</blockquote></details>

Sure.

**Pull request merged**
