### PR TITLE
SF-3108 Do not allow generating drafts in draft wizard when offline

### PR DESCRIPTION
**Pull request by RaymondLuong3**
The draft wizard cannot be opened offline, but if the user goes offline while the draft wizard is open, then the user can proceed and generate a draft that will fail. This PR prevents the user from advancing steps if the internet connection drops and shows a message to the user.

image

- - -
This change is [Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/2893)

### CODE REVIEW

**Comment by Nateowami** [comment]
There's a near infinite number of ways the connection can connect and disconnect. I'm not sure it's necessary to prevent going to the next step. Maybe just prevent the final "generate draft" button on the final step?

**Review by RaymondLuong3 — COMMENTED** [review]
That is a good point. I was thinking that it would be more robust by letter the user know before advancing steps if they are offline, but the stepper seems to work find offline so it is just the last step that needs an internet connection to work. I've made the update you suggested.

> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/2893#-:-ODhBI-jD_wUxclIyg7b:b-67dlzb)* status: 0 of 2 files reviewed, all discussions resolved

**Comment by Nateowami** [comment]
In almost all cases where functionality is not available offline, we opt to inform the user and disable associated buttons. Here are some examples:







I can't think of any good reason to diverge from that in this case. We do have at least a couple cases where we use a toast, such as User Menu > Edit name icon. However, in that case it's because there isn't a good place to put a persistent notice.

**Comment by Nateowami** [comment]
I think just above the generate button would make the most sense.

**Comment by RaymondLuong3** [comment]
That might not be a good idea since it needs to be duplicated on every step, and if we add steps, you'll need to remember to offline message.

**Comment by Nateowami** [comment]
> Unless you meant just on the final step.

That is what I was thinking.

> That also requires putting it on multiple steps since there are 3 possibilities of the final step.

I didn't realize that was still the case. I think that's changing as soon as #2787 is merged. Maybe put this on hold until that's done?

**Comment by Nateowami** [comment]
Or feel free to pick a different temporary solution.

**Comment by RaymondLuong3** [comment]
I think this PR doesn't have to be put on hold. Once #2787 is merged we can update this message.

**Comment by Nateowami** [comment]
Can you at least drop it down below the stepper so it's close to the button it most pertains to? Right now it's rather far away and easy to miss.

**Comment by RaymondLuong3** [comment]
It doesn't work nicely below the stepper. Since the stepper also includes the buttons, the offline message goes below the buttons and is out of view on some pages. If the user scrolls, they will see it.
image

**Comment by Nateowami** [comment]
Isn't it just as easy to lose it above the fold though?

**Comment by Nateowami** [comment]
Maybe just merge? I don't think it's even worth testing.

**Comment by RaymondLuong3** [comment]
I think that is true, the offline message could be out of view above or below the stepper. I do like that the text is closer to the buttons below the stepper. I've updated it accordingly.
Yes, we can merge it without testing.

**Review by Nateowami — APPROVED** [review]
:lgtm:

> Reviewed 1 of 2 files at r2, 2 of 3 files at r3, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/2893#-:-ODx0VflDVSBWhNLy4SG:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @RaymondLuong3)

**Pull request merged**
