### PR TITLE
SF-1701 Allow archiving and republishing questions in bulk

### PR DESCRIPTION
**Pull request by Nateowami**
This adds the ability to bulk archive and publish questions at the book or chapter level (rather than archiving or republishing questions only individually). A bulk operation will result in the user being prompted with a question like "Are you sure you want to archive all the questions in Genesis 4?"

Tests coming.

- - -
This change is [Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1550)

### CODE REVIEW

**Review by RaymondLuong3 — CHANGES_REQUESTED** [review]
It looks to be working. Just a couple minor suggestions.

> Reviewed 4 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1550#-:-NF9sHRkBMWBwexRssL1:b-9wcmy)* status: all files reviewed, 3 unresolved discussions (waiting on @Nateowami)

___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking-overview/checking-overview.component.html` line 48 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/1550#-NF9mWLp3GlNa32Vb0tb:-NF9mWLp3GlNa32Vb0tc:biwvyop) ([raw file](https://github.com/sillsdev/web-xforge/blob/04966ca63899425af8292e4ff3edeb33bb3494c7/src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking-overview/checking-overview.component.html#L48)):*
> ```HTML
>               <button
>                 mat-icon-button
>                 (click)="$event.stopPropagation(); setArchiveStatusForQuestionsInBook(text, true)"
> ```

Why is this necessary?



_Code quote:_
```HTML
$event.stopPropagation();
```
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking-overview/checking-overview.component.ts` line 315 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/1550#-NF9pNxK2RJGWUHcL5ZD:-NF9pNxK2RJGWUHcL5ZE:b-slup6n) ([raw file](https://github.com/sillsdev/web-xforge/blob/04966ca63899425af8292e4ff3edeb33bb3494c7/src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking-overview/checking-overview.component.ts#L315)):*
> ```XML
>   }
> 
>   async confirmArchiveQuestions(archive: boolean, scope: string): Promise<boolean> {
> ```

This can be a private method.



_Code quote:_
```XML
 async confirmArchiveQuestions(archive: boolean, scope: string): Promise<boolean> {
```
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking-overview/checking-overview.component.ts` line 338 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/1550#-NF9nwK9DSpoXBRjpNlz:-NF9nwK9DSpoXBRjpNm-:bou4jm0) ([raw file](https://github.com/sillsdev/web-xforge/blob/04966ca63899425af8292e4ff3edeb33bb3494c7/src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking-overview/checking-overview.component.ts#L338)):*
> ```XML
>     if (await this.confirmArchiveQuestions(archive, this.i18n.localizeBook(text.bookNum) + ' ' + chapter.number)) {
>       for (const questionDoc of this.getQuestionDocs(this.getTextDocIdType(text.bookNum, chapter.number), !archive)) {
>         if (questionDoc.data?.isArchived !== archive) this.setQuestionArchiveStatus(questionDoc, archive);
> ```

We might want to assert that `questionDoc.data` exists, and looking at `this.getQuestionDocs` that is a good assumption.



_Code quote:_
```XML
 if (questionDoc.data?.isArchived !== archive) this.setQuestionArchiveStatus(questionDoc, archive);
```

**Review by Nateowami — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1550)* status: all files reviewed, 3 unresolved discussions (waiting on @RaymondLuong3)

___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking-overview/checking-overview.component.html` line 48 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/1550#-NF9mWLp3GlNa32Vb0tb:-NFA5FqY8rMtpkc2knKj:bqk9rhw) ([raw file](https://github.com/sillsdev/web-xforge/blob/04966ca63899425af8292e4ff3edeb33bb3494c7/src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking-overview/checking-overview.component.html#L48)):*
<details><summary><i>Previously, RaymondLuong3 (Raymond Luong) wrote…</i></summary><blockquote>

Why is this necessary?
</blockquote></details>

The button is within a list item that is itself clickable. So clicking the button also causes the tree to expand or collapse if this isn't here. Maybe I should create a method so we can do`archiveBookButtonClicked($event, ...)` and then within that method call `event.stopPropagation()` with a comment explaining the reason? The unfortunate result of that would be four separate methods:
- `archiveBookButtonClicked`
- `archiveChapterButtonClicked`
- `republishBookButtonClicked`
- `republishChapterButtonClicked`

Or maybe we could have a single method, if someone can thinking of a better naming scheme than `archiveOrPublishButtonClicked(true, text, chapter)`, with `chapter` being optional, and the first argument specifying whether the questions should be archived or republished.

**Review by RaymondLuong3 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1550)* status: all files reviewed, 3 unresolved discussions (waiting on @Nateowami)

___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking-overview/checking-overview.component.html` line 48 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/1550#-NF9mWLp3GlNa32Vb0tb:-NFEtwdwDpj-qayAQZ_g:b-4bdmnv) ([raw file](https://github.com/sillsdev/web-xforge/blob/04966ca63899425af8292e4ff3edeb33bb3494c7/src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking-overview/checking-overview.component.html#L48)):*
<details><summary><i>Previously, Nateowami (Nathaniel Paulus) wrote…</i></summary><blockquote>

The button is within a list item that is itself clickable. So clicking the button also causes the tree to expand or collapse if this isn't here. Maybe I should create a method so we can do`archiveBookButtonClicked($event, ...)` and then within that method call `event.stopPropagation()` with a comment explaining the reason? The unfortunate result of that would be four separate methods:
- `archiveBookButtonClicked`
- `archiveChapterButtonClicked`
- `republishBookButtonClicked`
- `republishChapterButtonClicked`

Or maybe we could have a single method, if someone can thinking of a better naming scheme than `archiveOrPublishButtonClicked(true, text, chapter)`, with `chapter` being optional, and the first argument specifying whether the questions should be archived or republished.
</blockquote></details>

Hmm, good work figuring that out. I think it is ok, but might be worth a comment, since it is still in MDC, we want to remember what that is there for. I do like when we do not have to overload a method with too many flags and optional arguments.

**Review by Nateowami — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1550)* status: 1 of 4 files reviewed, 2 unresolved discussions (waiting on @RaymondLuong3)

___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking-overview/checking-overview.component.html` line 48 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/1550#-NF9mWLp3GlNa32Vb0tb:-NFG1-AI8gWeW1zsWSuy:b-896fix) ([raw file](https://github.com/sillsdev/web-xforge/blob/04966ca63899425af8292e4ff3edeb33bb3494c7/src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking-overview/checking-overview.component.html#L48)):*
<details><summary><i>Previously, RaymondLuong3 (Raymond Luong) wrote…</i></summary><blockquote>

Hmm, good work figuring that out. I think it is ok, but might be worth a comment, since it is still in MDC, we want to remember what that is there for. I do like when we do not have to overload a method with too many flags and optional arguments.
</blockquote></details>

Done.
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking-overview/checking-overview.component.ts` line 315 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/1550#-NF9pNxK2RJGWUHcL5ZD:-NFG1FJ83jaQb1-DT9Px:b-896fix) ([raw file](https://github.com/sillsdev/web-xforge/blob/04966ca63899425af8292e4ff3edeb33bb3494c7/src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking-overview/checking-overview.component.ts#L315)):*
<details><summary><i>Previously, RaymondLuong3 (Raymond Luong) wrote…</i></summary><blockquote>

This can be a private method.
</blockquote></details>

Done.
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking-overview/checking-overview.component.ts` line 338 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/1550#-NF9nwK9DSpoXBRjpNlz:-NFGZmrWEDU8_O3gt9f9:b-896fix) ([raw file](https://github.com/sillsdev/web-xforge/blob/04966ca63899425af8292e4ff3edeb33bb3494c7/src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking-overview/checking-overview.component.ts#L338)):*
<details><summary><i>Previously, RaymondLuong3 (Raymond Luong) wrote…</i></summary><blockquote>

We might want to assert that `questionDoc.data` exists, and looking at `this.getQuestionDocs` that is a good assumption.
</blockquote></details>

Done.

**Review by RaymondLuong3 — APPROVED** [review]
Good work. I think this will be helpful as we get more users on the community checking tool.

> Reviewed 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1550#-:-NFL46j15hlZOxWYCMpy:b-j27snj)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @Nateowami)

**Comment by Nateowami** [comment]
@RaymondLuong3 Sorry I've taken so long to create the tests for this. I've just added them and it can be reviewed again.

**Review by RaymondLuong3 — CHANGES_REQUESTED** [review]
Nice work, just one blocking comment.

> Reviewed 4 of 4 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1550#-:-NHQUMHT5TqbNBFI-lDy:b-bjoatt)* status: all files reviewed, 3 unresolved discussions (waiting on @Nateowami)

___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking-overview/checking-overview.component.spec.ts` line 436 at r3](https://reviewable.io/reviews/sillsdev/web-xforge/1550#-NHQURJy-Z8y12XDQ54r:-NHQURJy-Z8y12XDQ54s:b5b92s) ([raw file](https://github.com/sillsdev/web-xforge/blob/bf2720a41a1f74f5e33eb505b7590fc998084545/src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking-overview/checking-overview.component.spec.ts#L436)):*
> ```XML
>       // VERIFY CORRECT SETUP
> 
>       // expect two books with published questions
> ```

I like that I do not have to guess what is happening, but I find I rely on the comments more than actually trying to understand the test. Normally I would advocate for fewer comments and clearer code, but in this case with the challenge of knowing what row corresponds to what, the comments are a nice addition.



_Code quote:_
```XML
      // expect two books with published questions
```
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking-overview/checking-overview.component.spec.ts` line 471 at r3](https://reviewable.io/reviews/sillsdev/web-xforge/1550#-NHQSxDQ29F877jnhRGa:-NHQSxDQ29F877jnhRGb:bj1806e) ([raw file](https://github.com/sillsdev/web-xforge/blob/bf2720a41a1f74f5e33eb505b7590fc998084545/src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking-overview/checking-overview.component.spec.ts#L471)):*
> ```XML
>       // will be 3. It seems to remember that the book was expanded, even after all questions in that book are archived,
>       // so when they get republished and the book shows up in the list again, the books is expanded. Technically this
>       // is probably a bug, but it's hard to imagine why anyone would care.
> ```

I think that is a good assumption.



_Code quote:_
```XML
      // is probably a bug, but it's hard to imagine why anyone would care.
```
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking-overview/checking-overview.component.spec.ts` line 974 at r3](https://reviewable.io/reviews/sillsdev/web-xforge/1550#-NHQU1F-82lx_39qLnKZ:-NHQU1F-82lx_39qLnK_:b-giy2pu) ([raw file](https://github.com/sillsdev/web-xforge/blob/bf2720a41a1f74f5e33eb505b7590fc998084545/src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking-overview/checking-overview.component.spec.ts#L974)):*
> ```XML
>   }
> 
>   getPublishedQuestionsCountByRow(row: number): string {
> ```

This name could be more clear that it is the question count text. Same below.



_Code quote:_
```XML
  getPublishedQuestionsCountByRow(row: number): string {
```

**Review by Nateowami — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1550)* status: all files reviewed, 3 unresolved discussions (waiting on @RaymondLuong3)

___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking-overview/checking-overview.component.spec.ts` line 974 at r3](https://reviewable.io/reviews/sillsdev/web-xforge/1550#-NHQU1F-82lx_39qLnKZ:-NHQWYdzEi8hCs1MxBmy:b40n4lk) ([raw file](https://github.com/sillsdev/web-xforge/blob/bf2720a41a1f74f5e33eb505b7590fc998084545/src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking-overview/checking-overview.component.spec.ts#L974)):*
<details><summary><i>Previously, RaymondLuong3 (Raymond Luong) wrote…</i></summary><blockquote>

This name could be more clear that it is the question count text. Same below.
</blockquote></details>

I don't quite understand. Are you suggesting a name such as `getPublishedQuestionCountTextByRow`?

**Review by Nateowami — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1550)* status: all files reviewed, 2 unresolved discussions (waiting on @RaymondLuong3)

___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking-overview/checking-overview.component.spec.ts` line 436 at r3](https://reviewable.io/reviews/sillsdev/web-xforge/1550#-NHQURJy-Z8y12XDQ54r:-NHQWfdaAu8wGRTGCHGL:b-2o6il8) ([raw file](https://github.com/sillsdev/web-xforge/blob/bf2720a41a1f74f5e33eb505b7590fc998084545/src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking-overview/checking-overview.component.spec.ts#L436)):*
<details><summary><i>Previously, RaymondLuong3 (Raymond Luong) wrote…</i></summary><blockquote>

I like that I do not have to guess what is happening, but I find I rely on the comments more than actually trying to understand the test. Normally I would advocate for fewer comments and clearer code, but in this case with the challenge of knowing what row corresponds to what, the comments are a nice addition.
</blockquote></details>

I usually have a very hard time following tests, because it's hard to imagine what is going on (much more difficult than following our actual business logic).

Perhaps this is a problem with how we write our tests, and we should write them more like:
``` ts
expect(env.publishedBooks).toEqual(['Matthew', 'Mark']);
env.clickPublishedBook('Matthew');
```
Rather than:
``` ts
expect(env.textRows.length).toEqual(2);
env.simulateRowClick(0);
```
That would require a little more work in our test environment, but it would probably make the tests a lot easier to read, and in so doing I think reduce the amount of time struggling with tests.

**Review by RaymondLuong3 — APPROVED** [review]
:lgtm: 

> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1550#-:-NHQxx1C08i01XkHG7ho:bg7igkv)* status: all files reviewed, 1 unresolved discussion (waiting on @Nateowami)

___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking-overview/checking-overview.component.spec.ts` line 436 at r3](https://reviewable.io/reviews/sillsdev/web-xforge/1550#-NHQURJy-Z8y12XDQ54r:-NHQxbV58als_TBKU6bC:b-ejjnrf) ([raw file](https://github.com/sillsdev/web-xforge/blob/bf2720a41a1f74f5e33eb505b7590fc998084545/src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking-overview/checking-overview.component.spec.ts#L436)):*
<details><summary><i>Previously, Nateowami (Nathaniel Paulus) wrote…</i></summary><blockquote>

I usually have a very hard time following tests, because it's hard to imagine what is going on (much more difficult than following our actual business logic).

Perhaps this is a problem with how we write our tests, and we should write them more like:
``` ts
expect(env.publishedBooks).toEqual(['Matthew', 'Mark']);
env.clickPublishedBook('Matthew');
```
Rather than:
``` ts
expect(env.textRows.length).toEqual(2);
env.simulateRowClick(0);
```
That would require a little more work in our test environment, but it would probably make the tests a lot easier to read, and in so doing I think reduce the amount of time struggling with tests.
</blockquote></details>

Yes, it was unfortunate it was written this way, but I do not think it is worth the effort to change it now.

**Pull request merged**
