### PR TITLE
SF-2208 Display a warning when less than 10 verses translated

### PR DESCRIPTION
**Pull request by pmachapman**
When less than 10 verse pairs are in a source and target text, Machine will not be able to generated a BLEU score for Translation Suggestions.

This Pull Request displays a message on the Translate Overview screen when there are less than 10 verse pairs in the source and target texts, and if translation suggestions are enabled.

- - -
This change is [Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/2029)

### CODE REVIEW

**Review by RaymondLuong3 — CHANGES_REQUESTED** [review]
> Reviewed 5 of 5 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/2029)* status: all files reviewed, 5 unresolved discussions (waiting on @pmachapman)

___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/core/models/text-doc.ts` line 44 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/2029#-Nd6tVfVC2_zjZfxEGck:-Nd6tVfVC2_zjZfxEGcl:bln5wf5) ([raw file](https://github.com/sillsdev/web-xforge/blob/2c782a2bfb7348cbe865217cb62276247c46f530/src/SIL.XForge.Scripture/ClientApp/src/app/core/models/text-doc.ts#L44)):*
> ```XML
>   static readonly INDEX_PATHS = TEXT_INDEX_PATHS;
> 
>   getSegmentCount(): { translated: number; blank: number } {
> ```

I wonder if we could make use of this to count translated segments



_Code quote:_
```XML
  getSegmentCount(): { translated: number; blank: number } {
```
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/core/models/text-doc.ts` line 71 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/2029#-Nd6v3TVAPDtS7AQ6CYq:-Nd6v3TVAPDtS7AQ6CYr:bs9w4pi) ([raw file](https://github.com/sillsdev/web-xforge/blob/2c782a2bfb7348cbe865217cb62276247c46f530/src/SIL.XForge.Scripture/ClientApp/src/app/core/models/text-doc.ts#L71)):*
> ```XML
>   }
> 
>   getTranslatedVerses(): string[] {
> ```

I think a better name for this is getNonEmptyVerses() since this applies to the text doc, which may be a resource or source text, and translated may not make sense in that context.



_Code quote:_
```XML
  getTranslatedVerses(): string[] {
```
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/core/models/text-doc.ts` line 74 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/2029#-Nd6sVY2ENzgImCK1uig:-Nd6sVY2ENzgImCK1uih:b-d3emk9) ([raw file](https://github.com/sillsdev/web-xforge/blob/2c782a2bfb7348cbe865217cb62276247c46f530/src/SIL.XForge.Scripture/ClientApp/src/app/core/models/text-doc.ts#L74)):*
> ```XML
>     let verses: string[] = [];
>     if (this.data != null && this.data.ops != null) {
>       for (let i = 0; i < this.data.ops.length; i++) {
> ```

You can make use of 'for (const op: DeltaOperation of this.data.ops) {'



_Code quote:_
```XML
      for (let i = 0; i < this.data.ops.length; i++) {
```
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/translate/translate-overview/translate-overview.component.html` line 68 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/2029#-Nd6zBMvAzRpHb02gRZf:-Nd6zBMw3FiIcrvpMKI7:b-3b3d01) ([raw file](https://github.com/sillsdev/web-xforge/blob/2c782a2bfb7348cbe865217cb62276247c46f530/src/SIL.XForge.Scripture/ClientApp/src/app/translate/translate-overview/translate-overview.component.html#L68)):*
> ```HTML
>         </div>
>         <div *ngIf="showCannotTrainEngineMessage || !canTrainSuggestions" class="translation-suggestions-info">
>           {{ showCannotTrainEngineMessage ? t("cannot_train_suggestion_engine") : t("not_enough_verses_translated") }}
> ```

I'm not sure this is the most useful place to put this information. I would think putting it next to the `enable translation suggestions` checkbox in the settings page would make more sense. Or as warning text in the translation settings dialog. If there is good reason to put it here, let me know.



_Code quote:_
```HTML
   {{ showCannotTrainEngineMessage ? t("cannot_train_suggestion_engine") : t("not_enough_verses_translated") }}
```
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/translate/translate-overview/translate-overview.component.ts` line 225 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/2029#-Nd6um0hApYcEcfx73QL:-Nd6um0hApYcEcfx73QM:b6tczlq) ([raw file](https://github.com/sillsdev/web-xforge/blob/2c782a2bfb7348cbe865217cb62276247c46f530/src/SIL.XForge.Scripture/ClientApp/src/app/translate/translate-overview/translate-overview.component.ts#L225)):*
> ```XML
>         const targetTranslatedVerses: string[] = chapterText.getTranslatedVerses();
>         const sourceTranslatedVerses: string[] = sourceChapterText.getTranslatedVerses();
>         this.segmentPairs += targetTranslatedVerses.filter(item => sourceTranslatedVerses.includes(item)).length;
> ```

I wonder if we should put this into TextDoc, and create a method called getTranslatedSegmentPairs(sourceText). If we were for sure going to use that in more than one spot, I would say let's do that. Not a blocker.



_Code quote:_
```XML
        // Get the intersect of the source and target translated verses arrays
        // i.e. The verses with data that both texts have in common
        const targetTranslatedVerses: string[] = chapterText.getTranslatedVerses();
        const sourceTranslatedVerses: string[] = sourceChapterText.getTranslatedVerses();
        this.segmentPairs += targetTranslatedVerses.filter(item => sourceTranslatedVerses.includes(item)).length;
```

**Review by RaymondLuong3 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/2029)* status: all files reviewed, 5 unresolved discussions (waiting on @pmachapman)

___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/core/models/text-doc.ts` line 44 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/2029#-Nd6tVfVC2_zjZfxEGck:-Nd6zfS45tfhctWf9fz4:b-pacs14) ([raw file](https://github.com/sillsdev/web-xforge/blob/2c782a2bfb7348cbe865217cb62276247c46f530/src/SIL.XForge.Scripture/ClientApp/src/app/core/models/text-doc.ts#L44)):*
<details><summary><i>Previously, RaymondLuong3 (Raymond Luong) wrote…</i></summary><blockquote>

I wonder if we could make use of this to count translated segments
</blockquote></details>

Nevermind, I see we still have to get the number of overlapping verses.

**Review by pmachapman — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/2029)* status: all files reviewed, 4 unresolved discussions (waiting on @RaymondLuong3)

___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/core/models/text-doc.ts` line 71 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/2029#-Nd6v3TVAPDtS7AQ6CYq:-Nd7-mEIDjE7qfkFsSo5:b-nrcyn8) ([raw file](https://github.com/sillsdev/web-xforge/blob/2c782a2bfb7348cbe865217cb62276247c46f530/src/SIL.XForge.Scripture/ClientApp/src/app/core/models/text-doc.ts#L71)):*
<details><summary><i>Previously, RaymondLuong3 (Raymond Luong) wrote…</i></summary><blockquote>

I think a better name for this is getNonEmptyVerses() since this applies to the text doc, which may be a resource or source text, and translated may not make sense in that context.
</blockquote></details>

Done. Thanks - I struggled to name this function in a meaningful way.
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/core/models/text-doc.ts` line 74 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/2029#-Nd6sVY2ENzgImCK1uig:-Nd70NscCLJn7Xt-I1b7:b-ioxi27) ([raw file](https://github.com/sillsdev/web-xforge/blob/2c782a2bfb7348cbe865217cb62276247c46f530/src/SIL.XForge.Scripture/ClientApp/src/app/core/models/text-doc.ts#L74)):*
<details><summary><i>Previously, RaymondLuong3 (Raymond Luong) wrote…</i></summary><blockquote>

You can make use of 'for (const op: DeltaOperation of this.data.ops) {'
</blockquote></details>

Done. Thank you!
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/translate/translate-overview/translate-overview.component.html` line 68 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/2029#-Nd6zBMvAzRpHb02gRZf:-Nd71JKh0nJqJDP-T6ng:bcizm7u) ([raw file](https://github.com/sillsdev/web-xforge/blob/2c782a2bfb7348cbe865217cb62276247c46f530/src/SIL.XForge.Scripture/ClientApp/src/app/translate/translate-overview/translate-overview.component.html#L68)):*
<details><summary><i>Previously, RaymondLuong3 (Raymond Luong) wrote…</i></summary><blockquote>

I'm not sure this is the most useful place to put this information. I would think putting it next to the `enable translation suggestions` checkbox in the settings page would make more sense. Or as warning text in the translation settings dialog. If there is good reason to put it here, let me know.
</blockquote></details>

It took me a while to figure out where to put this message. I chose this spot because of its existing use for a warning message, the pre-existing logic on this page that iterates over every text, and because this is where a user will end up:

1) Right after the connect the project (and if they checked "Enabled Translation Suggestions" there they would need to know this message).
2) When the user wants to retrain the model. The state that any edit actions the user will have made to the source or target prior to retraining will affect this message.

The only case that really isn't covered is the checking of Enable Translation Suggestions after a project has been connected to, which you have highlighted. I am not too keen on duplicating the messaging, but if you think it is important, I can.

I really wish we had a form of unified message tray or subsystem. We now have various subcomponents (Translation Suggestions, Pre-Translation, Biblical Terms) that need to notify the user of various errors and warnings.

Perhaps we should correct this after this PR through a new PR/ticket that attempts to make the existing errors/notifications like this a bit more accessible rather than lurking on whatever pages they are displayed in?
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/translate/translate-overview/translate-overview.component.ts` line 225 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/2029#-Nd6um0hApYcEcfx73QL:-Nd70nxL9oUzeMZOzSCE:b2ztbqs) ([raw file](https://github.com/sillsdev/web-xforge/blob/2c782a2bfb7348cbe865217cb62276247c46f530/src/SIL.XForge.Scripture/ClientApp/src/app/translate/translate-overview/translate-overview.component.ts#L225)):*
<details><summary><i>Previously, RaymondLuong3 (Raymond Luong) wrote…</i></summary><blockquote>

I wonder if we should put this into TextDoc, and create a method called getTranslatedSegmentPairs(sourceText). If we were for sure going to use that in more than one spot, I would say let's do that. Not a blocker.
</blockquote></details>

I think if we use it again, it should be refactored. I don't think it needs to now, as the method would really only contain the `filter(includes())` intersect.

**Review by RaymondLuong3 — APPROVED** [review]
:lgtm: 

> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/2029#-:-Nd7Cx4X9k_7-ho1ll9d:bg7igkv)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @pmachapman)

___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/translate/translate-overview/translate-overview.component.html` line 68 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/2029#-Nd6zBMvAzRpHb02gRZf:-Nd7CKsk1Y9ypStRBfb-:bffbewh) ([raw file](https://github.com/sillsdev/web-xforge/blob/2c782a2bfb7348cbe865217cb62276247c46f530/src/SIL.XForge.Scripture/ClientApp/src/app/translate/translate-overview/translate-overview.component.html#L68)):*
<details><summary><i>Previously, pmachapman (Peter Chapman) wrote…</i></summary><blockquote>

It took me a while to figure out where to put this message. I chose this spot because of its existing use for a warning message, the pre-existing logic on this page that iterates over every text, and because this is where a user will end up:

1) Right after the connect the project (and if they checked "Enabled Translation Suggestions" there they would need to know this message).
2) When the user wants to retrain the model. The state that any edit actions the user will have made to the source or target prior to retraining will affect this message.

The only case that really isn't covered is the checking of Enable Translation Suggestions after a project has been connected to, which you have highlighted. I am not too keen on duplicating the messaging, but if you think it is important, I can.

I really wish we had a form of unified message tray or subsystem. We now have various subcomponents (Translation Suggestions, Pre-Translation, Biblical Terms) that need to notify the user of various errors and warnings.

Perhaps we should correct this after this PR through a new PR/ticket that attempts to make the existing errors/notifications like this a bit more accessible rather than lurking on whatever pages they are displayed in?
</blockquote></details>

I see, so having it on that page does make sense. I also would rather not have duplicated messages. I think that the this will probably serve us in the 80-90% of cases, so I am happy with this.

**Pull request merged**
