### PR TITLE
SF-1802 Throw exception when registry returns error fetching project

### PR DESCRIPTION
**Pull request by Nateowami**
The tests on this are unfortunately failing. I opened the PR knowing this was the case.

Please see the linked issue for an explanation of the problem at hand and what this is trying to solve.

This change is [Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1575)

### CODE REVIEW

**Comment by marksvc** [comment]
I am working on it.

**Comment by marksvc** [comment]
@Nateowami I fixed the tests, and also made the status code propagate down to IsRegisteredAsync() so it can be inspected. Unfortunately, a 404 code doesn't definitively indicate that the project is not registered, so we may want to use additional means to check that. 

More information was posted to jira.

I am ready for this PR to be marked as not a Draft, and continue to be processed for merging.
It's fine if my name falls off the commit I added.

**Review by Nateowami — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1575)* status: 0 of 2 files reviewed, 1 unresolved discussion (waiting on @Nateowami)

___
*[`src/SIL.XForge.Scripture/Services/ParatextService.cs` line 1730 at r2](https://reviewable.io/reviews/sillsdev/web-xforge/1575#-NHbf95c4if5qjaQl41H:-NHbf95c4if5qjaQl41I:b8yexzx) ([raw file](https://github.com/sillsdev/web-xforge/blob/1daf23094e06472d9c31c25a91c54323f12f0476/src/SIL.XForge.Scripture/Services/ParatextService.cs#L1730)):*
> a PT-type system identifier

I spent a long time trying to figure out what this means, and I still can't figure it out. If you do know, I think this comment should explain better. And if you don't know, perhaps you could write the comment in such a way that the reader can understand that?

**Review by marksvc — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1575)* status: 0 of 2 files reviewed, 1 unresolved discussion (waiting on @Nateowami)

___
*[`src/SIL.XForge.Scripture/Services/ParatextService.cs` line 1730 at r2](https://reviewable.io/reviews/sillsdev/web-xforge/1575#-NHbf95c4if5qjaQl41H:-NLS_fbf1pDfLI1Egfuq:bi1se2q) ([raw file](https://github.com/sillsdev/web-xforge/blob/1daf23094e06472d9c31c25a91c54323f12f0476/src/SIL.XForge.Scripture/Services/ParatextService.cs#L1730)):*
I'm sorry about that :)
So at https://registry-dev.paratext.org/developer/index.html#!/Projects/get_projects_project_id_identification_systemId_system_type_text , you can query the "identification_systemId" using a project id code. But there are different _types_ of project id code, such as dbl, Biblica, Paratext, etc. If we ask the system, "Please give me the Paratext id code for this project", and the PT Registry _has_ the project registered, but the ID code(s) in PT Registry for the project do not include an ID code that is a Paratext-type id code, then PT Registry will return 404, according to the API:

> The project with the given ID does not exist or the authenticated user is not authorised to view it, or it has no system identifier with the indicated type.

Running into this situation in our application may not be common any time soon. But because our SF API comment says under what conditions a true or false will be returned, and because this PR regards correctly distinguishing between different failure conditions, it may serve us to spell out the requirements for knowing if a project is registered.

I had a few go's at revising the comment. In the end I have it collapsed down to some of its original wording, which I think captures it enough.

**Review by marksvc — APPROVED** [review]
> Reviewed 1 of 2 files at r4, 1 of 1 files at r5, 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1575)* status: all files reviewed, 4 unresolved discussions (waiting on @github-code-scanning[bot] and @Nateowami)

___
*[`test/SIL.XForge.Scripture.Tests/Services/ParatextServiceTests.cs` line 3265 at r4](https://reviewable.io/reviews/sillsdev/web-xforge/1575#-NFzICm0apN2l6yNWU0K-r4-3265:-NLSoM_S4Maek_mRZYO2:bb6un1j) ([raw file](https://github.com/sillsdev/web-xforge/blob/bfec68f488bf1ce8ce118aa9051eb4bd0af76ac8/test/SIL.XForge.Scripture.Tests/Services/ParatextServiceTests.cs#L3265)):*
<details><summary><i>Previously, github-code-scanning[bot] wrote…</i></summary><blockquote>

## Missed 'readonly' opportunity

Field 'UnauthorizedHttpResponseMessage' can be 'readonly'.

[Show more details](https://github.com/sillsdev/web-xforge/security/code-scanning/450)
</blockquote></details>

Done
___
*[`test/SIL.XForge.Scripture.Tests/Services/ParatextServiceTests.cs` line 3272 at r4](https://reviewable.io/reviews/sillsdev/web-xforge/1575#-NFzICm0apN2l6yNWU0K-r4-3272:-NLSoQGJ6AReP5aHkkNG:b-896fix) ([raw file](https://github.com/sillsdev/web-xforge/blob/bfec68f488bf1ce8ce118aa9051eb4bd0af76ac8/test/SIL.XForge.Scripture.Tests/Services/ParatextServiceTests.cs#L3272)):*
<details><summary><i>Previously, github-code-scanning[bot] wrote…</i></summary><blockquote>

## Missed 'readonly' opportunity

Field 'NotFoundHttpResponseMessage' can be 'readonly'.

[Show more details](https://github.com/sillsdev/web-xforge/security/code-scanning/449)
</blockquote></details>

Done.

**Comment by marksvc** [comment]
FWIW, I approve these changes. Though they are largely my own :)

**Review by Nateowami — COMMENTED** [review]
:lgtm:

> Reviewed 1 of 2 files at r4, 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1575#-:-NM77gVe1bU4laoYoi_z:bnfp4nl)* status: all files reviewed, 3 unresolved discussions (waiting on @github-code-scanning[bot])

**Pull request merged**
