### PR TITLE
Add index to sf_project_secrets.shareKeys.key

### PR DESCRIPTION
**Pull request by pmachapman**
This PR adds an index to the `shareKeys.key` field of `sf_project_secrets`.

This index will speed up checking for share keys when users attempt to log in via a share key.

When running this PR, you will see a new index appear in the `sf_project_secrets` collection:
image

- - -
This change is [Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/2531)

### CODE REVIEW

**Comment by nigel-wells** [comment]
@pmachapman is there another half to this PR for how the frontend handles this? I'm getting errors on the users page as well as the share dialog. I've cleared all local data by logging out and back in. I've also completely removed `sf_project_secrets` in case that assumed no old data was there.

**Comment by pmachapman** [comment]
>@pmachapman is there another half to this PR for how the frontend handles this?

No, not at all. This is purely a backend change. Something else might be a miss - have you run the [cleaning procedure](https://github.com/sillsdev/web-xforge/wiki/Cleaning)?

**Comment by nigel-wells** [comment]
Yes I had done cleanup. I also tried switching projects in case there was bad data but that didn't help either.

I was able to resolve the issue by completely dropping the `xforge` DB from Mongo. Bit excessive but maybe I did have some bad data in there.

It is working as I'd expect now. It wouldn't hurt to get another dev to checkout the branch just to confirm it was a me problem and nothing more serious. @Nateowami are you able to see if it works ok for you?

**Comment by nigel-wells** [comment]
@josephmyers do you mind doing a sanity test on this as well please just to confirm that the issue I encountered was only related to me.

**Review by josephmyers — APPROVED** [review]
Yep, I can see the index without dropping the db.

> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/2531#-:-O0vUwYy9uPVaOUXKmrB:b-ozacle)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @nigel-wells)

**Pull request merged**
