### PR TITLE
Make Angular compiler strict

### PR DESCRIPTION
**Pull request by irahopkinson**
- no compile errors except in prod build
- fixes for prod build
- needed to disable "strictInputTypes"
- helps VSCode checks

---
This change is [Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1045)

### CODE REVIEW

**Comment by marksvc** [comment]
:eyes:

**Review by marksvc — CHANGES_REQUESTED** [review]
Thanks for working thru all these changes. I'm glad for us to turn on these additional strict checks.

I tested the change by compiling the frontend and backend, and logged into SF without relevant problems.

> Reviewed 20 of 20 files at r1.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1045#-:-Ma5mUphDWHdaSXCfQkj:bovh2vm)* status: all files reviewed, 3 unresolved discussions (waiting on @irahopkinson)

___
*[src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-answers/checking-comments/checking-comments.component.ts, line 191 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/1045#-Ma5YKbADFain74f7ALU:-Ma5YKbADFain74f7ALV:b-gnyuky) ([raw file](https://github.com/sillsdev/web-xforge/blob/14151efef5f4b99fef6942c5b7e7e4fb79783bbb/src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-answers/checking-comments/checking-comments.component.ts#L191)):*
> ```
> submit(text: String): void {
> ```

What's with capitalizing the S in string? And what's with text.toString() below?

I tried un-doing these and ran my linters and compiler but it was still okay. 

(Maybe this was residue after fiddling with something else and un-doing most of it?)
___
*[src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking-overview/checking-overview.component.html, line 75 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/1045#-Ma5eZIBCfeyPokgdvP6:-Ma5eZIBCfeyPokgdvP7:b-ekejdf) ([raw file](https://github.com/sillsdev/web-xforge/blob/14151efef5f4b99fef6942c5b7e7e4fb79783bbb/src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking-overview/checking-overview.component.html#L75)):*
> ```HTML
>             <ng-container *ngIf="itemVisible[getTextDocId(text.bookNum, chapter.number)]">
>               <mdc-list-item
>                 *ngFor="let questionDoc of getQuestionDocs(getTextDocIdType(text.bookNum, chapter.number))"
> ```

Hmm. Interesting that that was working before. If I examined the javascript that it was compiled down to maybe it would explain why. 
It looks like we were passing a string that was getting used as a TextDocId.
___
*[src/SIL.XForge.Scripture/ClientApp/src/app/scripture-chooser-dialog/scripture-chooser-dialog.component.ts, line 186 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/1045#-Ma5aE7J4CYk43f8fnjw:-Ma5aE7J4CYk43f8fnjx:b-shih0v) ([raw file](https://github.com/sillsdev/web-xforge/blob/14151efef5f4b99fef6942c5b7e7e4fb79783bbb/src/SIL.XForge.Scripture/ClientApp/src/app/scripture-chooser-dialog/scripture-chooser-dialog.component.ts#L186)):*
> ```XML
>   }
> 
>   getNumOrNaN(num: number | undefined): number {
> ```

It looks like in JavaScript, `+undefined` is NaN and `+null` is 0. 

What is the purpose for this method? Was it to call nulls NaN instead of 0?

I would have thought the `+` in the template html file was converting strings to numbers, but clearly not in cases where they are now being passed to `getNumOrNan()` since this method takes a number|undefined, not a string.
___
*[src/SIL.XForge.Scripture/ClientApp/src/app/shared/text/text.component.ts, line 402 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/1045#-Ma5jjW56DxJIEsJFteA:-Ma5jjW56DxJIEsJFteB:b-1k6uv3) ([raw file](https://github.com/sillsdev/web-xforge/blob/14151efef5f4b99fef6942c5b7e7e4fb79783bbb/src/SIL.XForge.Scripture/ClientApp/src/app/shared/text/text.component.ts#L402)):*
> ```XML
> 
>   onContentChanged(delta: DeltaStatic, source: string): void {
>     this.viewModel.update(delta, source as Sources);
> ```

Hmm. So what was the problem here? 
Was it that quill was firing events, and quill's type specification for its source argument was `string`, and so not tight enough to confirm to `Sources`, and so we needed to specify our receiving type as `string`? Undoing this and just re-compiling doesn't produce any errors about it.

I feel a little uncomfortable receiving an arbitrary string and passing it on `as Sources`. But in the target method it looks like it should be okay.

**Review by Nateowami — CHANGES_REQUESTED** [review]
> Reviewed 3 of 20 files at r1.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1045)* status: all files reviewed, 4 unresolved discussions (waiting on @irahopkinson and @marksvc)

___
*[src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-answers/checking-comments/checking-comments.component.ts, line 191 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/1045#-Ma5ampAE0MgIklqkBf2:-Ma5ampAE0MgIklqkBf3:bjxdymt) ([raw file](https://github.com/sillsdev/web-xforge/blob/14151efef5f4b99fef6942c5b7e7e4fb79783bbb/src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-answers/checking-comments/checking-comments.component.ts#L191)):*
> ```XML
>   }
> 
>   submit(text: String): void {
> ```

Why are we using `String` rather than `string`? This discrepancy is caused by these lines in `checking-comment-form.component.ts`:
```
@Output() save: EventEmitter<String> = new EventEmitter<String>();
@Output() cancel: EventEmitter<Boolean> = new EventEmitter<Boolean>();
```
Unless there's a reason, I would think we should change these to `EventEmitter<string>` and `EventEmitter<boolean>`.
___
*[src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking-overview/checking-overview.component.html, line 75 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/1045#-Ma5eZIBCfeyPokgdvP6:-Ma5sXcL3DOz2YhNFxi3:bt5mish) ([raw file](https://github.com/sillsdev/web-xforge/blob/14151efef5f4b99fef6942c5b7e7e4fb79783bbb/src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking-overview/checking-overview.component.html#L75)):*
<details><summary><i>Previously, marksvc wrote…</i></summary><blockquote>

Hmm. Interesting that that was working before. If I examined the javascript that it was compiled down to maybe it would explain why. 
It looks like we were passing a string that was getting used as a TextDocId.

</blockquote></details>

Ditto. I tried and couldn't figure out what was going on here.
___
*[src/SIL.XForge.Scripture/ClientApp/src/app/scripture-chooser-dialog/scripture-chooser-dialog.component.ts, line 186 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/1045#-Ma5aE7J4CYk43f8fnjw:-Ma5wZn27Y_Q2N2-EWug:bhn02xc) ([raw file](https://github.com/sillsdev/web-xforge/blob/14151efef5f4b99fef6942c5b7e7e4fb79783bbb/src/SIL.XForge.Scripture/ClientApp/src/app/scripture-chooser-dialog/scripture-chooser-dialog.component.ts#L186)):*
<details><summary><i>Previously, marksvc wrote…</i></summary><blockquote>

It looks like in JavaScript, `+undefined` is NaN and `+null` is 0. 

What is the purpose for this method? Was it to call nulls NaN instead of 0?

I would have thought the `+` in the template html file was converting strings to numbers, but clearly not in cases where they are now being passed to `getNumOrNan()` since this method takes a number|undefined, not a string.
</blockquote></details>

`+undefined` is `NaN` in JavaScript, but the type checker isn't willing for us to do that, since it looks like a mistake. The error is "Object is possibly 'undefined'." on `data.input?.verseNum`.

**Review by irahopkinson — COMMENTED** [review]
@marksvc you will only see the errors if you compile for production, i.e. `ng build --prod` (remember to remove the `dist` folder afterwards).

We could go further by removing the `"strictInputTypes": false` setting (this backs things off a little from the full `strictTemplates`) but this is enough one PR.

> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1045#-:-Ma862Oh3eW0coxF-Nwp:buj5rr6)* status: all files reviewed, 2 unresolved discussions (waiting on @marksvc and @Nateowami)

___
*[src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-answers/checking-comments/checking-comments.component.ts, line 191 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/1045#-Ma5YKbADFain74f7ALU:-Ma86wWkAyIyFCXMoabU:btf1gc4) ([raw file](https://github.com/sillsdev/web-xforge/blob/14151efef5f4b99fef6942c5b7e7e4fb79783bbb/src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-answers/checking-comments/checking-comments.component.ts#L191)):*
<details><summary><i>Previously, marksvc wrote…</i></summary><blockquote>

> ```
> submit(text: String): void {
> ```

What's with capitalizing the S in string? And what's with text.toString() below?

I tried un-doing these and ran my linters and compiler but it was still okay. 

(Maybe this was residue after fiddling with something else and un-doing most of it?)
</blockquote></details>

After a while of fixing errors I just got into the pattern of making it comply with what it was asking for. I forgot to go back to this one and check the underlying cause. Fixed now.
___
*[src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-answers/checking-comments/checking-comments.component.ts, line 191 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/1045#-Ma5ampAE0MgIklqkBf2:-Ma88HcZ1iBPcDecyEA_:bqdfm83) ([raw file](https://github.com/sillsdev/web-xforge/blob/14151efef5f4b99fef6942c5b7e7e4fb79783bbb/src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-answers/checking-comments/checking-comments.component.ts#L191)):*
<details><summary><i>Previously, Nateowami (Nathaniel Paulus) wrote…</i></summary><blockquote>

Why are we using `String` rather than `string`? This discrepancy is caused by these lines in `checking-comment-form.component.ts`:
```
@Output() save: EventEmitter<String> = new EventEmitter<String>();
@Output() cancel: EventEmitter<Boolean> = new EventEmitter<Boolean>();
```
Unless there's a reason, I would think we should change these to `EventEmitter<string>` and `EventEmitter<boolean>`.
</blockquote></details>

Thanks for finding those. Fixed now.
___
*[src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking-overview/checking-overview.component.html, line 75 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/1045#-Ma5eZIBCfeyPokgdvP6:-Ma88Y9D3gNnRB8IPwPB:b-8lge0o) ([raw file](https://github.com/sillsdev/web-xforge/blob/14151efef5f4b99fef6942c5b7e7e4fb79783bbb/src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking-overview/checking-overview.component.html#L75)):*
<details><summary><i>Previously, Nateowami (Nathaniel Paulus) wrote…</i></summary><blockquote>

Ditto. I tried and couldn't figure out what was going on here.
</blockquote></details>

Yes indeed. Who says it was working before??? …but I guess it must have been. I investigated... in the `getQuestionDocs` method, for the first argument `textDocId` you are meant to pass it a `TextDocId` but the only thing it does with it is convert it to a string. The `toString` function of `TextDocId` returns the results of `getTextDocId`  so if you pass a string in of the ID it can use it as is in JS. I think we might have been lucky that this one hasn't bitten us before now since it just happened to work.
___
*[src/SIL.XForge.Scripture/ClientApp/src/app/scripture-chooser-dialog/scripture-chooser-dialog.component.ts, line 186 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/1045#-Ma5aE7J4CYk43f8fnjw:-Ma8A6dUDVynXAzEbrsU:b-s7oq48) ([raw file](https://github.com/sillsdev/web-xforge/blob/14151efef5f4b99fef6942c5b7e7e4fb79783bbb/src/SIL.XForge.Scripture/ClientApp/src/app/scripture-chooser-dialog/scripture-chooser-dialog.component.ts#L186)):*
<details><summary><i>Previously, Nateowami (Nathaniel Paulus) wrote…</i></summary><blockquote>

`+undefined` is `NaN` in JavaScript, but the type checker isn't willing for us to do that, since it looks like a mistake. The error is "Object is possibly 'undefined'." on `data.input?.verseNum`.
</blockquote></details>

Yeah, this is just making it explicit (and hopefully more readable) and now the type checker is happy too.
___
*[src/SIL.XForge.Scripture/ClientApp/src/app/shared/text/text.component.ts, line 402 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/1045#-Ma5jjW56DxJIEsJFteA:-Ma8Aixy7j8Y6mRXNWgU:bim6kv1) ([raw file](https://github.com/sillsdev/web-xforge/blob/14151efef5f4b99fef6942c5b7e7e4fb79783bbb/src/SIL.XForge.Scripture/ClientApp/src/app/shared/text/text.component.ts#L402)):*
<details><summary><i>Previously, marksvc wrote…</i></summary><blockquote>

Hmm. So what was the problem here? 
Was it that quill was firing events, and quill's type specification for its source argument was `string`, and so not tight enough to confirm to `Sources`, and so we needed to specify our receiving type as `string`? Undoing this and just re-compiling doesn't produce any errors about it.

I feel a little uncomfortable receiving an arbitrary string and passing it on `as Sources`. But in the target method it looks like it should be okay. 
</blockquote></details>

Just another type checking issue `string !== "api" | "user" | "silent" (Sources)`. Now it is explicit that we are casting a string to another type (Sources). It was doing this before but now we are declaring it explicitly and its not hidden in the HTML.

**Review by marksvc — APPROVED** [review]
> Reviewed 3 of 7 files at r2.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1045)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @irahopkinson)

___
*[src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-answers/checking-comments/checking-comments.component.ts, line 191 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/1045#-Ma5YKbADFain74f7ALU:-Ma9__qs2fQ33HuA5aVl:b-g6llej) ([raw file](https://github.com/sillsdev/web-xforge/blob/14151efef5f4b99fef6942c5b7e7e4fb79783bbb/src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-answers/checking-comments/checking-comments.component.ts#L191)):*
<details><summary><i>Previously, irahopkinson (Ira Hopkinson) wrote…</i></summary><blockquote>

After a while of fixing errors I just got into the pattern of making it comply with what it was asking for. I forgot to go back to this one and check the underlying cause. Fixed now.
</blockquote></details>

Makes sense. Thanks.
___
*[src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking-overview/checking-overview.component.html, line 75 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/1045#-Ma5eZIBCfeyPokgdvP6:-Ma9a1W3EqUJWAHkhhc8:b-t5x7cj) ([raw file](https://github.com/sillsdev/web-xforge/blob/14151efef5f4b99fef6942c5b7e7e4fb79783bbb/src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking-overview/checking-overview.component.html#L75)):*
>  but the only thing it does with it is convert it to a string

Yes, I see that now. Interesting.

**Pull request merged**
