### PR TITLE
Tell the user and redirect if project is not found

### PR DESCRIPTION
**Pull request by marksvc**
- Rather than sit at a blank page with a progress bar that keeps going
forever.
- Report to bugsnag so we can keep an eye on this happening.

-----

Animation showing behaviour when the user is in fact not on any project:

bad-project-id

Animation showing behaviour when the user is on a project (i.e. another project):

bad-project-id-have-project

---
This change is [Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/927)

### CODE REVIEW

**Review by RaymondLuong3 — CHANGES_REQUESTED** [review]
That's an improvement. Just one blocking comment.

> Reviewed 2 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/927#-:-MR_qoq_2x-uPbXf24QT:b-70z8ev)* status: all files reviewed, 1 unresolved discussion (waiting on @marksvc)

___
*[src/SIL.XForge.Scripture/ClientApp/src/app/project/project.component.ts, line 70 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/927#-MR_qczd8WhKdYty1CT5:-MR_qczd8WhKdYty1CT6:b6ompov) ([raw file](https://github.com/sillsdev/web-xforge/blob/ed01ee177ed20742e17ec5d196a5e62591944a71/src/SIL.XForge.Scripture/ClientApp/src/app/project/project.component.ts#L70)):*
<details><summary><i alt="summary">Quoted 4 lines of code…</i></summary>

> ```
>           const message: string =
>             `There was a problem finding a project (${projectDoc.id}) or user specific ` +
>             `information for the project (${projectUserConfigDoc.id}). Maybe there was a typo in the URL you ` +
>             `specified. Maybe you tried to access a project that is no longer available.`;
> ```
</details>

This should be internationalized. I would also add question marks at the ends of the questions in this sentence.

**Review by marksvc — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/927)* status: all files reviewed, 1 unresolved discussion (waiting on @RaymondLuong3)

___
*[src/SIL.XForge.Scripture/ClientApp/src/app/project/project.component.ts, line 70 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/927#-MR_qczd8WhKdYty1CT5:-MRaQDE63tKWrp81p0TC:b-3dbdxy) ([raw file](https://github.com/sillsdev/web-xforge/blob/ed01ee177ed20742e17ec5d196a5e62591944a71/src/SIL.XForge.Scripture/ClientApp/src/app/project/project.component.ts#L70)):*
<details><summary><i>Previously, RaymondLuong3 (Raymond Luong) wrote…</i></summary><blockquote>

> ```
>           const message: string =
>             `There was a problem finding a project (${projectDoc.id}) or user specific ` +
>             `information for the project (${projectUserConfigDoc.id}). Maybe there was a typo in the URL you ` +
>             `specified. Maybe you tried to access a project that is no longer available.`;
> ```
This should be internationalized. I would also add question marks at the ends of the questions in this sentence.
</blockquote></details>

Thank you for the reminder! 
I didn't mean for those to be questions, but pointing out potential things that may have gone wrong. I worded it a bit differently in a revision.
I also removed the project user config doc ID since I don't think that is going to help the user, and we can probably get this via other means if needed.

**Review by RaymondLuong3 — APPROVED** [review]
Looks good now. Thanks.

> Reviewed 3 of 3 files at r2.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/927#-:-MRbL1iq-C4imXz8JVjO:b1tng6n)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by irahopkinson — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/927)* status: all files reviewed, 1 unresolved discussion (waiting on @marksvc)

___
*[src/SIL.XForge.Scripture/ClientApp/src/app/project/project.component.spec.ts, line 121 at r2](https://reviewable.io/reviews/sillsdev/web-xforge/927#-MRdCqjA3JyUcptDOiUA:-MRdCqjB8ATMiEwbqz3r:b-czo7z7) ([raw file](https://github.com/sillsdev/web-xforge/blob/d6b0c663d32e4938e9addffdb0d50b658dbcabb1/src/SIL.XForge.Scripture/ClientApp/src/app/project/project.component.spec.ts#L121)):*
> ```
> do not navigate when project does not exist
> ```
Your solution looks really good and a great improvement. This test bothers me a bit in that we were specifically testing against what you have just made it do. It kinda seems like its was that way to prevent some other bug. Do you know why it was there? Or at least looked at git blame to see who added it?

**Review by marksvc — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/927)* status: all files reviewed, 1 unresolved discussion (waiting on @irahopkinson)

___
*[src/SIL.XForge.Scripture/ClientApp/src/app/project/project.component.spec.ts, line 121 at r2](https://reviewable.io/reviews/sillsdev/web-xforge/927#-MRdCqjA3JyUcptDOiUA:-MRv6UzZ9DJ0CuEk7J4w:bzgv050) ([raw file](https://github.com/sillsdev/web-xforge/blob/d6b0c663d32e4938e9addffdb0d50b658dbcabb1/src/SIL.XForge.Scripture/ClientApp/src/app/project/project.component.spec.ts#L121)):*
<details><summary><i>Previously, irahopkinson (Ira Hopkinson) wrote…</i></summary><blockquote>

> ```
> do not navigate when project does not exist
> ```
Your solution looks really good and a great improvement. This test bothers me a bit in that we were specifically testing against what you have just made it do. It kinda seems like its was that way to prevent some other bug. Do you know why it was there? Or at least looked at git blame to see who added it?
</blockquote></details>

Thank you. 
Good point. I used git blame today to find why this test was written. It was part of a solution to SF-629, to stop an infinite loop. I did some testing and found that the SF-629 issue is not occurring. I suspect something else has helped prevent the infinite loop in the mean time. 

I did observe that the code before the SF-629 fix had used `this.userService.setCurrentProjectId();` right before navigating to /projects, and so I have re-introduced that. 

I did not _extensively_ bang on SF-629, but I did go thru the steps a several times, and with a couple scenarios, and did not observe the problem behaviour.

I commented in SF-629, and I mention it also in an update to my commit message.

**Review by irahopkinson — APPROVED** [review]
:lgtm:

> Reviewed 3 of 3 files at r3.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/927#-:-MRxTWEs28Hz0hk2cBEQ:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved

___
*[src/SIL.XForge.Scripture/ClientApp/src/app/project/project.component.spec.ts, line 121 at r2](https://reviewable.io/reviews/sillsdev/web-xforge/927#-MRdCqjA3JyUcptDOiUA:-MRxSld08W3SyJbEULD9:b-3r6swj) ([raw file](https://github.com/sillsdev/web-xforge/blob/d6b0c663d32e4938e9addffdb0d50b658dbcabb1/src/SIL.XForge.Scripture/ClientApp/src/app/project/project.component.spec.ts#L121)):*
<details><summary><i>Previously, marksvc wrote…</i></summary><blockquote>

Thank you. 
Good point. I used git blame today to find why this test was written. It was part of a solution to SF-629, to stop an infinite loop. I did some testing and found that the SF-629 issue is not occurring. I suspect something else has helped prevent the infinite loop in the mean time. 

I did observe that the code before the SF-629 fix had used `this.userService.setCurrentProjectId();` right before navigating to /projects, and so I have re-introduced that. 

I did not _extensively_ bang on SF-629, but I did go thru the steps a several times, and with a couple scenarios, and did not observe the problem behaviour.

I commented in SF-629, and I mention it also in an update to my commit message. 
</blockquote></details>

Excellent, thanks for looking into that.

**Pull request merged**
