### PR TITLE
SF-1152 Fix prompting when reimporting question with changed reference

### PR DESCRIPTION
**Pull request by Nateowami**
Previously, when reimporting questions, if the verse reference had changed, the user was not prompted to confirm reimporting the question.

---
This change is [Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/881)

### CODE REVIEW

**Review by RaymondLuong3 — CHANGES_REQUESTED** [review]
Just one comment.

> Reviewed 2 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/881#-:-MN0F1Rn2kIXEkdEsSgJ:b-cc91uw)* status: all files reviewed, 1 unresolved discussion (waiting on @Nateowami)

___
*[src/SIL.XForge.Scripture/ClientApp/src/app/checking/import-questions-dialog/import-questions-dialog.component.ts, line 321 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/881#-MN0EIfG2_QRHIbEuH7p:-MN0EIfG2_QRHIbEuH7q:b-johfw2) ([raw file](https://github.com/sillsdev/web-xforge/blob/3712c63edfcc7127b8c35a5e0f1f44c7c3eb970c/src/SIL.XForge.Scripture/ClientApp/src/app/checking/import-questions-dialog/import-questions-dialog.component.ts#L321)):*
> ```
>   private verseRefDataDiffers(a: VerseRefData, b: VerseRefData): boolean {
>     return toVerseRef(a).BBBCCCVVV !== toVerseRef(b).BBBCCCVVV || a.verse !== b.verse;
>   }
> ```
The return could be simplified to `return !toVerseRef(a).equals(toVerseRef(b))`

**Review by RaymondLuong3 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/881)* status: all files reviewed, 2 unresolved discussions (waiting on @Nateowami)

___
*[src/SIL.XForge.Scripture/ClientApp/src/app/checking/import-questions-dialog/import-questions-dialog.component.spec.ts, line 228 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/881#-MN0FQ298SaN2omHL38C:-MN0FQ298SaN2omHL38D:bdpsm9k) ([raw file](https://github.com/sillsdev/web-xforge/blob/3712c63edfcc7127b8c35a5e0f1f44c7c3eb970c/src/SIL.XForge.Scripture/ClientApp/src/app/checking/import-questions-dialog/import-questions-dialog.component.spec.ts#L228)):*
> ```
> expect(env.submitJson0OpCalled).toBe(true);
> ```
To improve this, this could be `env.transceleratorQuestionsUpdated` and have it record the `transceleratorQuestionId` of the question that was updated.

**Review by Nateowami — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/881)* status: 0 of 2 files reviewed, 2 unresolved discussions (waiting on @RaymondLuong3)

___
*[src/SIL.XForge.Scripture/ClientApp/src/app/checking/import-questions-dialog/import-questions-dialog.component.ts, line 321 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/881#-MN0EIfG2_QRHIbEuH7p:-MN0HiKP4tcu41tazc67:b-i21bbo) ([raw file](https://github.com/sillsdev/web-xforge/blob/3712c63edfcc7127b8c35a5e0f1f44c7c3eb970c/src/SIL.XForge.Scripture/ClientApp/src/app/checking/import-questions-dialog/import-questions-dialog.component.ts#L321)):*
<details><summary><i>Previously, RaymondLuong3 (Raymond Luong) wrote…</i></summary><blockquote>

> ```
>   private verseRefDataDiffers(a: VerseRefData, b: VerseRefData): boolean {
>     return toVerseRef(a).BBBCCCVVV !== toVerseRef(b).BBBCCCVVV || a.verse !== b.verse;
>   }
> ```
The return could be simplified to `return !toVerseRef(a).equals(toVerseRef(b))`
</blockquote></details>

Thanks. Done.
___
*[src/SIL.XForge.Scripture/ClientApp/src/app/checking/import-questions-dialog/import-questions-dialog.component.spec.ts, line 228 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/881#-MN0FQ298SaN2omHL38C:-MN0KGKN5FqL0LVjYBno:b4kh76r) ([raw file](https://github.com/sillsdev/web-xforge/blob/3712c63edfcc7127b8c35a5e0f1f44c7c3eb970c/src/SIL.XForge.Scripture/ClientApp/src/app/checking/import-questions-dialog/import-questions-dialog.component.spec.ts#L228)):*
<details><summary><i>Previously, RaymondLuong3 (Raymond Luong) wrote…</i></summary><blockquote>

> ```
> expect(env.submitJson0OpCalled).toBe(true);
> ```
To improve this, this could be `env.transceleratorQuestionsUpdated` and have it record the `transceleratorQuestionId` of the question that was updated.
</blockquote></details>

Thanks for the suggestion. I made a similar change. What do you think?

**Review by RaymondLuong3 — APPROVED** [review]
This is good to go.

> Reviewed 2 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/881#-:-MN0Mjv39GFJOy4wVday:b-ptbamt)* status: :shipit: complete! all files reviewed, all discussions resolved

___
*[src/SIL.XForge.Scripture/ClientApp/src/app/checking/import-questions-dialog/import-questions-dialog.component.spec.ts, line 228 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/881#-MN0FQ298SaN2omHL38C:-MN0MfeK3Ve6-PPdMCtK:b-83sjoh) ([raw file](https://github.com/sillsdev/web-xforge/blob/3712c63edfcc7127b8c35a5e0f1f44c7c3eb970c/src/SIL.XForge.Scripture/ClientApp/src/app/checking/import-questions-dialog/import-questions-dialog.component.spec.ts#L228)):*
<details><summary><i>Previously, Nateowami (Nathaniel Paulus) wrote…</i></summary><blockquote>

Thanks for the suggestion. I made a similar change. What do you think?
</blockquote></details>

Nice!

**Pull request merged**
