### PR TITLE
SF-1699 Avoid deleting embeds when backspacing or deleting word

### PR DESCRIPTION
**Pull request by RaymondLuong3**
* add handler when user presses ctrl + backspace or ctrl + delete
* delete characters up to the next space
* only delete characters when word is adjacent to an embed

- - -
This change is [Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1533)

### CODE REVIEW

**Review by RaymondLuong3 — COMMENTED** [review]
I was tempted to disable the backspace word feature completely, rather than try to support it since it is not critical. But here is what we can do.

> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1533#-:-NE7uTo_CYny231susrc:bqyu4v3)* status: 0 of 2 files reviewed, all discussions resolved

**Review by nigel-wells — CHANGES_REQUESTED** [review]
Nice one working this through - I didn't even know about that shortcut.

> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1533#-:-NE97y7V8teJFesS8zzt:bmcbg39)* status: all files reviewed, 5 unresolved discussions (waiting on @RaymondLuong3)

___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/shared/text/text.component.ts` line 999 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/1533#-NE93zGS-tNuTjJtbhST:-NE93zGS-tNuTjJtbhSU:bebhcxz) ([raw file](https://github.com/sillsdev/web-xforge/blob/aadade785f031e94c03dc31e81f3c63711c0de01/src/SIL.XForge.Scripture/ClientApp/src/app/shared/text/text.component.ts#L999)):*
> ```XML
> 
>     // only process the word range if the op is a string insert
>     if (typeof lastOp === 'string') {
> ```

Could return `undefined` here if not a `string` rather than later
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/shared/text/text.component.ts` line 1029 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/1533#-NE9484B0nfJDBbKHQbN:-NE9484B0nfJDBbKHQbO:bebhcxz) ([raw file](https://github.com/sillsdev/web-xforge/blob/aadade785f031e94c03dc31e81f3c63711c0de01/src/SIL.XForge.Scripture/ClientApp/src/app/shared/text/text.component.ts#L1029)):*
> ```XML
> 
>     // only process the word range if the op is a string insert
>     if (typeof firstOp === 'string') {
> ```

Could return `undefined` here if not a `string` rather than later
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/shared/text/text.component.spec.ts` line 2599 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/1533#-NE97fvk5QtS6NDEMiLK:-NE97fvk5QtS6NDEMiLL:b6urgku) ([raw file](https://github.com/sillsdev/web-xforge/blob/aadade785f031e94c03dc31e81f3c63711c0de01/src/SIL.XForge.Scripture/ClientApp/src/app/shared/text/text.component.spec.ts#L2599)):*
> ```XML
>   it('can backspace a word at a time', fakeAsync(() => {
>     const { env, segmentRange }: { env: TestEnvironment; segmentRange: RangeStatic } = basicSimpleText();
>     let initialText = 'quick brown fox';
> ```

Is it possible to combine the 3 checks in to a while loop with the string slowly diminishing rather than repeating the same test with a different string?
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/shared/text/text.component.spec.ts` line 2647 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/1533#-NE97rl9DvzCUvcyD0Oi:-NE97rl9DvzCUvcyD0Oj:b-ido17d) ([raw file](https://github.com/sillsdev/web-xforge/blob/aadade785f031e94c03dc31e81f3c63711c0de01/src/SIL.XForge.Scripture/ClientApp/src/app/shared/text/text.component.spec.ts#L2647)):*
> ```XML
>   it('can delete a word at a time', fakeAsync(() => {
>     const { env, segmentRange }: { env: TestEnvironment; segmentRange: RangeStatic } = basicSimpleText();
>     let initialText = 'quick brown fox';
> ```

As per my other comment
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/shared/text/text.component.spec.ts` line 3300 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/1533#-NE97BOlDUd6Uw-k-X9-:-NE97BOlDUd6Uw-k-X90:btfor2l) ([raw file](https://github.com/sillsdev/web-xforge/blob/aadade785f031e94c03dc31e81f3c63711c0de01/src/SIL.XForge.Scripture/ClientApp/src/app/shared/text/text.component.spec.ts#L3300)):*
> ```XML
> 
>   /** Crudely find backspace word handler. */
>   quillHandleBackspaceWord(range: RangeStatic): void {
> ```

Could these methods be combined into one where you pass the key code and the handle name?

Out of interest, why do we need to locate the handler to call? Are we not able to position the cursor and trigger an event and Quill will handler it?

**Review by RaymondLuong3 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1533)* status: all files reviewed, 5 unresolved discussions (waiting on @nigel-wells)

___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/shared/text/text.component.ts` line 999 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/1533#-NE93zGS-tNuTjJtbhST:-NEC4-vK5Q8xAhnqmoZB:b-896fix) ([raw file](https://github.com/sillsdev/web-xforge/blob/aadade785f031e94c03dc31e81f3c63711c0de01/src/SIL.XForge.Scripture/ClientApp/src/app/shared/text/text.component.ts#L999)):*
<details><summary><i>Previously, nigel-wells (Nigel Wells) wrote…</i></summary><blockquote>

Could return `undefined` here if not a `string` rather than later
</blockquote></details>

Done.
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/shared/text/text.component.ts` line 1029 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/1533#-NE9484B0nfJDBbKHQbN:-NEC49DZ2vxmydW6a1iQ:b-896fix) ([raw file](https://github.com/sillsdev/web-xforge/blob/aadade785f031e94c03dc31e81f3c63711c0de01/src/SIL.XForge.Scripture/ClientApp/src/app/shared/text/text.component.ts#L1029)):*
<details><summary><i>Previously, nigel-wells (Nigel Wells) wrote…</i></summary><blockquote>

Could return `undefined` here if not a `string` rather than later
</blockquote></details>

Done.
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/shared/text/text.component.spec.ts` line 2599 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/1533#-NE97fvk5QtS6NDEMiLK:-NECF4R194Hpfoo2bjZf:broa0cf) ([raw file](https://github.com/sillsdev/web-xforge/blob/aadade785f031e94c03dc31e81f3c63711c0de01/src/SIL.XForge.Scripture/ClientApp/src/app/shared/text/text.component.spec.ts#L2599)):*
<details><summary><i>Previously, nigel-wells (Nigel Wells) wrote…</i></summary><blockquote>

Is it possible to combine the 3 checks in to a while loop with the string slowly diminishing rather than repeating the same test with a different string?
</blockquote></details>

I used a for loop that takes an array of the expected results and runs the set of tests for each expected result.
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/shared/text/text.component.spec.ts` line 2647 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/1533#-NE97rl9DvzCUvcyD0Oi:-NECF4CMB6buI-EGA2WT:b-896fix) ([raw file](https://github.com/sillsdev/web-xforge/blob/aadade785f031e94c03dc31e81f3c63711c0de01/src/SIL.XForge.Scripture/ClientApp/src/app/shared/text/text.component.spec.ts#L2647)):*
<details><summary><i>Previously, nigel-wells (Nigel Wells) wrote…</i></summary><blockquote>

As per my other comment
</blockquote></details>

Done.
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/shared/text/text.component.spec.ts` line 3300 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/1533#-NE97BOlDUd6Uw-k-X9-:-NECEiIb3379SYtrXybx:b7m5n8p) ([raw file](https://github.com/sillsdev/web-xforge/blob/aadade785f031e94c03dc31e81f3c63711c0de01/src/SIL.XForge.Scripture/ClientApp/src/app/shared/text/text.component.spec.ts#L3300)):*
<details><summary><i>Previously, nigel-wells (Nigel Wells) wrote…</i></summary><blockquote>

Could these methods be combined into one where you pass the key code and the handle name?

Out of interest, why do we need to locate the handler to call? Are we not able to position the cursor and trigger an event and Quill will handler it?
</blockquote></details>

They can be, so I merged the two together. Unfortunately, I have not been able to find a way to trigger the keyboard binding. Both Mark and I have tried to trigger it with an event, but we have not found a way to do this yet.

**Review by nigel-wells — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1533#-:-NEDBQBr7II5Er2iwqi-:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @RaymondLuong3)

___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/shared/text/text.component.spec.ts` line 2599 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/1533#-NE97fvk5QtS6NDEMiLK:-NED7eIzCuJpyzq06uAJ:b2w0hzs) ([raw file](https://github.com/sillsdev/web-xforge/blob/aadade785f031e94c03dc31e81f3c63711c0de01/src/SIL.XForge.Scripture/ClientApp/src/app/shared/text/text.component.spec.ts#L2599)):*
<details><summary><i>Previously, RaymondLuong3 (Raymond Luong) wrote…</i></summary><blockquote>

I used a for loop that takes an array of the expected results and runs the set of tests for each expected result.
</blockquote></details>

Great, that saved a heap of code :)
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/shared/text/text.component.spec.ts` line 3300 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/1533#-NE97BOlDUd6Uw-k-X9-:-NEDAvD3AnRSJdAHXEC2:bvzbvob) ([raw file](https://github.com/sillsdev/web-xforge/blob/aadade785f031e94c03dc31e81f3c63711c0de01/src/SIL.XForge.Scripture/ClientApp/src/app/shared/text/text.component.spec.ts#L3300)):*
<details><summary><i>Previously, RaymondLuong3 (Raymond Luong) wrote…</i></summary><blockquote>

They can be, so I merged the two together. Unfortunately, I have not been able to find a way to trigger the keyboard binding. Both Mark and I have tried to trigger it with an event, but we have not found a way to do this yet.
</blockquote></details>

Thanks for the merge. That's a shame there isn't a way to trigger events like this - I guess we've always found a way around it. We can revisit it if one of us manages to find the secret ingredient.

**Pull request merged**
