### PR TITLE
SF-2567 Remove In-Process Machine

### PR DESCRIPTION
**Pull request by pmachapman**
This PR completely removes the old in-process machine.

SIL.Machine is retained for one utility method: `HasSentenceEnding()`

- - -
This change is [Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/2350)

### CODE REVIEW

**Review by marksvc — COMMENTED** [review]
I know this is draft, but FWIW here are some comments on the first half of the files.

> Reviewed 15 of 33 files at r1.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/2350#-:-NrCB9gQ46wG1fJDwyfn:b38z7xc)* status: 13 of 33 files reviewed, 9 unresolved discussions (waiting on @github-advanced-security[bot] and @pmachapman)

___
*[`src/SIL.XForge.Scripture/Models/ServalEngineDto.cs` line 3 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/2350#-NrBrOnVEHCKfIHrf8Hn:-NrBrOnVEHCKfIHrf8Ho:bezb0zn) ([raw file](https://github.com/sillsdev/web-xforge/blob/e5930c8ef42147eceb980a4be55d4aa8289f82fa/src/SIL.XForge.Scripture/Models/ServalEngineDto.cs#L3)):*
> ```Smalltalk
> namespace SIL.XForge.Scripture.Models;
> 
> public class ServalEngineDto : ServalResourceDto
> ```

Sometimes I go look at a class definition when I wonder, "What is this class for? What is it used for? What is the meaning of these fields?", and sometimes I find that we have a class defined with no explanation about what it is or why it's there. We may not need to be terribly strict about this, but if you leave at least about a sentence of explanation on classes you define, it will help me some day when I forget what it is and go looking at it :). 

Does "Dto" mean "Data transfer object"?

`IsShared` looks like it could use illumination in a comment, for example. Is it shared among projects at Serval? Is it shared between SF and Serval? Is it shared by projects at SF? 

I recognize that if I spend time working in an area of code, I will become familiar with its classes and how they are passed around. So I don't want to be too pedantic about asking for comments :). But I know they are helpful to me when I go looking. 
___
*[`src/SIL.XForge.Scripture/Services/MachineApiService.cs` line 190 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/2350#-NrBy9sP9u2q6673AMGE:-NrBy9sQA8R8K7gdCdDH:bifgy8e) ([raw file](https://github.com/sillsdev/web-xforge/blob/db1dea23e15e14893c82183f6c545790ed5f42f9/src/SIL.XForge.Scripture/Services/MachineApiService.cs#L190)):*
> ```Smalltalk
>     )
>     {
>         ServalBuildDto? buildDto = null;
> ```

What's with removing `?`?
___
*[`src/SIL.XForge.Scripture/Services/MachineApiService.cs` line 673 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/2350#-NrC7ZNt-Uh0Pijwkspk:-NrC7ZNt-Uh0Pijwkspl:b-razxmz) ([raw file](https://github.com/sillsdev/web-xforge/blob/e5930c8ef42147eceb980a4be55d4aa8289f82fa/src/SIL.XForge.Scripture/Services/MachineApiService.cs#L673)):*
> ```Smalltalk
> 
>         string translationEngineId = await GetTranslationIdAsync(sfProjectId, preTranslate: false);
>         if (string.IsNullOrWhiteSpace(translationEngineId)) { }
> ```

This `if` check can probably be removed. The id won't be returned as null or empty iirc.
___
*[`src/SIL.XForge.Scripture/Services/MachineApiService.cs` line 734 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/2350#-NrC8xbK7jjJwzHvmzID:-NrC8xbK7jjJwzHvmzIE:bisjwoi) ([raw file](https://github.com/sillsdev/web-xforge/blob/e5930c8ef42147eceb980a4be55d4aa8289f82fa/src/SIL.XForge.Scripture/Services/MachineApiService.cs#L734)):*
> ```Smalltalk
>             catch (Exception e)
>             {
>                 ProcessServalApiException(e);
> ```

Sometimes after this you do `throw;` and sometimes you don't. I haven't understood why one or the other. I'm okay if it's intentional, but FYI in case there were some mistakes there.

Hmm, and I see that the Process..Exception() method itself throws under most, but not all, circumstances.
___
*[`src/SIL.XForge.Scripture/Services/MachineApiService.cs` line 785 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/2350#-NrC725R2y-AI5tZSILp:-NrC725R2y-AI5tZSILq:bzdif8m) ([raw file](https://github.com/sillsdev/web-xforge/blob/db1dea23e15e14893c82183f6c545790ed5f42f9/src/SIL.XForge.Scripture/Services/MachineApiService.cs#L785)):*
> ```Smalltalk
> 
>         // This will be null if Serval is down, or if all feature flags are false
>         if (buildDto is null)
> ```

I noticed that a couple times above, and once below, you removed this sort of check. FYI if that was a mistake.

**Review by pmachapman — COMMENTED** [review]
> Dismissed @github-advanced-security[bot] from 5 discussions.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/2350)* status: 11 of 33 files reviewed, 4 unresolved discussions (waiting on @github-advanced-security[bot] and @marksvc)

___
*[`src/SIL.XForge.Scripture/Models/ServalEngineDto.cs` line 3 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/2350#-NrBrOnVEHCKfIHrf8Hn:-NrCWsyMB_mF59dRx53Y:b-dkgcob) ([raw file](https://github.com/sillsdev/web-xforge/blob/e5930c8ef42147eceb980a4be55d4aa8289f82fa/src/SIL.XForge.Scripture/Models/ServalEngineDto.cs#L3)):*
I have added some class comments. Let me know if they are not clear.

> Does "Dto" mean "Data transfer object"?
Yes.

> `IsShared` looks like it could use illumination in a comment, for example. Is it shared among projects at Serval? Is it shared between SF and Serval? Is it shared by projects at SF?

This is a remnant of the model from the in-process machine. To keep compatibility with the v3 frontend code, I have retained it and marked it obsolete.
___
*[`src/SIL.XForge.Scripture/Services/MachineApiService.cs` line 190 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/2350#-NrBy9sP9u2q6673AMGE:-NrCZwUGEOy2K0dOAON9:b-jriqio) ([raw file](https://github.com/sillsdev/web-xforge/blob/db1dea23e15e14893c82183f6c545790ed5f42f9/src/SIL.XForge.Scripture/Services/MachineApiService.cs#L190)):*
<details><summary><i>Previously, marksvc wrote…</i></summary><blockquote>

What's with removing `?`?
</blockquote></details>

A mistake when cleaning up. Thanks for spotting it!
___
*[`src/SIL.XForge.Scripture/Services/MachineApiService.cs` line 673 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/2350#-NrC7ZNt-Uh0Pijwkspk:-NrCa7SE15v1LFHgfPZh:b-896fix) ([raw file](https://github.com/sillsdev/web-xforge/blob/e5930c8ef42147eceb980a4be55d4aa8289f82fa/src/SIL.XForge.Scripture/Services/MachineApiService.cs#L673)):*
<details><summary><i>Previously, marksvc wrote…</i></summary><blockquote>

This `if` check can probably be removed. The id won't be returned as null or empty iirc.
</blockquote></details>

Done.
___
*[`src/SIL.XForge.Scripture/Services/MachineApiService.cs` line 734 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/2350#-NrC8xbK7jjJwzHvmzID:-NrCaF91-NOMhiH-u5i-:b-baeuo5) ([raw file](https://github.com/sillsdev/web-xforge/blob/e5930c8ef42147eceb980a4be55d4aa8289f82fa/src/SIL.XForge.Scripture/Services/MachineApiService.cs#L734)):*
<details><summary><i>Previously, marksvc wrote…</i></summary><blockquote>

Sometimes after this you do `throw;` and sometimes you don't. I haven't understood why one or the other. I'm okay if it's intentional, but FYI in case there were some mistakes there.

Hmm, and I see that the Process..Exception() method itself throws under most, but not all, circumstances.
</blockquote></details>

Yes. This was a frustrating one for me. If it wasn't for the fact that three of the methods require the 408 and the return, I would not need the additional throw.

Even then, when I did try having only `throws` in the `ProcessServalApiException` method, the pre-compiler still required the `throw;` afterwards.

Perhaps I was trying to be too smart with code reuse, but the other alternative is to write these out long form, which I am not too keen on, unless you think it would be beneficial of course.
___
*[`src/SIL.XForge.Scripture/Services/MachineApiService.cs` line 785 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/2350#-NrC725R2y-AI5tZSILp:-NrC_LcICeFc2Z5rdwmT:b-21gscs) ([raw file](https://github.com/sillsdev/web-xforge/blob/db1dea23e15e14893c82183f6c545790ed5f42f9/src/SIL.XForge.Scripture/Services/MachineApiService.cs#L785)):*
<details><summary><i>Previously, marksvc wrote…</i></summary><blockquote>

I noticed that a couple times above, and once below, you removed this sort of check. FYI if that was a mistake.
</blockquote></details>

A lot of the null checks were because the previous logic would ignore errors form Serval and just pass the request onto the in-process machine.

Now, these should throw errors, as there is no other system to pass the request to.

**Review by pmachapman — COMMENTED** [review]
> Dismissed @github-advanced-security[bot] from 6 discussions.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/2350)* status: 9 of 33 files reviewed, 4 unresolved discussions (waiting on @github-advanced-security[bot] and @marksvc)

**Review by marksvc — CHANGES_REQUESTED** [review]
Here is another chunk of review. 

My lack of familiarity with these areas have not always allowed me to do a thoughtful consideration of the changes and how things will work going forward. But I am at least reading over and considering the changes that are being proposed, and making comments where something may not seem quite right.

> Reviewed 8 of 33 files at r1, 4 of 9 files at r2, 4 of 6 files at r3.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/2350#-:-NrbKdZA4gJi5x3CfiwR:becrwez)* status: 19 of 33 files reviewed, 5 unresolved discussions (waiting on @pmachapman)

___
*[`src/SIL.XForge.Scripture/Models/ServalEngineDto.cs` line 3 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/2350#-NrBrOnVEHCKfIHrf8Hn:-Nrb0Noo0gVBvrpsJovo:b-9755fn) ([raw file](https://github.com/sillsdev/web-xforge/blob/e5930c8ef42147eceb980a4be55d4aa8289f82fa/src/SIL.XForge.Scripture/Models/ServalEngineDto.cs#L3)):*
<details><summary><i>Previously, pmachapman (Peter Chapman) wrote…</i></summary><blockquote>

I have added some class comments. Let me know if they are not clear.

> Does "Dto" mean "Data transfer object"?
Yes.

> `IsShared` looks like it could use illumination in a comment, for example. Is it shared among projects at Serval? Is it shared between SF and Serval? Is it shared by projects at SF?

This is a remnant of the model from the in-process machine. To keep compatibility with the v3 frontend code, I have retained it and marked it obsolete.
</blockquote></details>

Thank you!
___
*[`src/SIL.XForge.Scripture/Services/MachineProjectService.cs` line 102 at r3](https://reviewable.io/reviews/sillsdev/web-xforge/2350#-Nrb2MGl9RCEOzISIHhl:-Nrb2MGl9RCEOzISIHhm:b-ld0upk) ([raw file](https://github.com/sillsdev/web-xforge/blob/d0550f0eb3148a6979310c9b6eed462abb487938/src/SIL.XForge.Scripture/Services/MachineProjectService.cs#L102)):*
> ```Smalltalk
>         // After ensuring that the source and target language tags are present
>         if (
>             !string.IsNullOrWhiteSpace(project.TranslateConfig.Source!.WritingSystem.Tag)
> ```

I've learned that when we make assumptions and assert not-null via `!`, it can lead to crashes. I suppose it wouldn't be all that different of behaviour to check if Source is not null and throw an Exception, but we can at least be a bit more explicit and intentional in the code by checking the value and defining a specific response behaviour (such as throwing). Do you think that would be a waste? Would that be worthwhile? What's your thinking on that?
___
*[`src/SIL.XForge.Scripture/Services/MachineProjectService.cs` line 896 at r3](https://reviewable.io/reviews/sillsdev/web-xforge/2350#-Nrb4lyGBf_15HdjyEL4:-Nrb4lyGBf_15HdjyEL5:b-l5z4y8) ([raw file](https://github.com/sillsdev/web-xforge/blob/d0550f0eb3148a6979310c9b6eed462abb487938/src/SIL.XForge.Scripture/Services/MachineProjectService.cs#L896)):*
> ```Smalltalk
>             // Hebrew word as the key, or because the verse number is unusual (i.e. 12a or 12-13). Usually the key is
>             // a standard verse number, so will be at most in the hundreds.
>             // We also strip characters from the key that will corrupt the line
> ```

It seems like this comment would be more helpful up in SFTextSegment.SegmentRef, do you think?
___
*[`src/SIL.XForge.Scripture/Services/SFTextCorpusFactory.cs` line 21 at r3](https://reviewable.io/reviews/sillsdev/web-xforge/2350#-NrbHiMH6sEe0EEI3RzK:-NrbHiMH6sEe0EEI3RzL:bv8k2hj) ([raw file](https://github.com/sillsdev/web-xforge/blob/d0550f0eb3148a6979310c9b6eed462abb487938/src/SIL.XForge.Scripture/Services/SFTextCorpusFactory.cs#L21)):*
> ```Smalltalk
> /// <summary>
> /// This class represents a Machine text corpus for a SF project. It is used during batch training of the Machine
> /// translation engine.
> ```

Looks like we may need to revise the comment, too?
___
*[`test/SIL.XForge.Scripture.Tests/Services/MachineApiServiceTests.cs` line 1183 at r3](https://reviewable.io/reviews/sillsdev/web-xforge/2350#-NrbTxTV9BV4i6CnmuK3:-NrbTxTV9BV4i6CnmuK4:b-yhmin5) ([raw file](https://github.com/sillsdev/web-xforge/blob/c6c30257c91b7c7e9b82b389e956deb8a3f328dc/test/SIL.XForge.Scripture.Tests/Services/MachineApiServiceTests.cs#L1183)):*
> ExecutesApiAndInProcess

I wasn't sure if the "ExecutesApi" part would still be relevant. But I'll point it out in case. 
___
*[`test/SIL.XForge.Scripture.Tests/Services/MachineApiServiceTests.cs` line 1833 at r3](https://reviewable.io/reviews/sillsdev/web-xforge/2350#-NrbVQfc61DNCP7W7ZKf:-NrbVQfc61DNCP7W7ZKg:bn79tu9) ([raw file](https://github.com/sillsdev/web-xforge/blob/c6c30257c91b7c7e9b82b389e956deb8a3f328dc/test/SIL.XForge.Scripture.Tests/Services/MachineApiServiceTests.cs#L1833)):*
> ```Smalltalk
> 
>     [Test]
>     public async Task StartBuildAsync_ServalTranslationEngineRecreationErrorsDoNotCrashIfInProcess()
> ```

I didn't see around here if there is a test for the serval translation engine recreation error being propagated / crashing, in the new Serval-only world. If that's significant.

**Review by pmachapman — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/2350)* status: 17 of 33 files reviewed, 4 unresolved discussions (waiting on @marksvc)

___
*[`src/SIL.XForge.Scripture/Services/MachineProjectService.cs` line 102 at r3](https://reviewable.io/reviews/sillsdev/web-xforge/2350#-Nrb2MGl9RCEOzISIHhl:-NrbtsCb5L6XIaj3x57X:b3dnzai) ([raw file](https://github.com/sillsdev/web-xforge/blob/d0550f0eb3148a6979310c9b6eed462abb487938/src/SIL.XForge.Scripture/Services/MachineProjectService.cs#L102)):*
<details><summary><i>Previously, marksvc wrote…</i></summary><blockquote>

I've learned that when we make assumptions and assert not-null via `!`, it can lead to crashes. I suppose it wouldn't be all that different of behaviour to check if Source is not null and throw an Exception, but we can at least be a bit more explicit and intentional in the code by checking the value and defining a specific response behaviour (such as throwing). Do you think that would be a waste? Would that be worthwhile? What's your thinking on that?
</blockquote></details>

I have changed it to use `?.`, as that will mean an empty string is returned by the method, which will be interpreted as a missing source or target language.

I think that is OK, given this code will only be executed from the frontend or sync runner when the source is specified.
___
*[`src/SIL.XForge.Scripture/Services/MachineProjectService.cs` line 896 at r3](https://reviewable.io/reviews/sillsdev/web-xforge/2350#-Nrb4lyGBf_15HdjyEL4:-NrbvQdo1SkYMMUM2n44:b-ydonir) ([raw file](https://github.com/sillsdev/web-xforge/blob/d0550f0eb3148a6979310c9b6eed462abb487938/src/SIL.XForge.Scripture/Services/MachineProjectService.cs#L896)):*
<details><summary><i>Previously, marksvc wrote…</i></summary><blockquote>

It seems like this comment would be more helpful up in SFTextSegment.SegmentRef, do you think?
</blockquote></details>

Done. Good idea.
___
*[`src/SIL.XForge.Scripture/Services/SFTextCorpusFactory.cs` line 21 at r3](https://reviewable.io/reviews/sillsdev/web-xforge/2350#-NrbHiMH6sEe0EEI3RzK:-NrbvrQR7_VUW7rn5BnV:boyexb3) ([raw file](https://github.com/sillsdev/web-xforge/blob/d0550f0eb3148a6979310c9b6eed462abb487938/src/SIL.XForge.Scripture/Services/SFTextCorpusFactory.cs#L21)):*
<details><summary><i>Previously, marksvc wrote…</i></summary><blockquote>

Looks like we may need to revise the comment, too?
</blockquote></details>

Done. Thanks!
___
*[`test/SIL.XForge.Scripture.Tests/Services/MachineApiServiceTests.cs` line 1183 at r3](https://reviewable.io/reviews/sillsdev/web-xforge/2350#-NrbTxTV9BV4i6CnmuK3:-Nrbw2NUB93yxgY_viEt:b-2c3sur) ([raw file](https://github.com/sillsdev/web-xforge/blob/c6c30257c91b7c7e9b82b389e956deb8a3f328dc/test/SIL.XForge.Scripture.Tests/Services/MachineApiServiceTests.cs#L1183)):*
<details><summary><i>Previously, marksvc wrote…</i></summary><blockquote>

> ExecutesApiAndInProcess

I wasn't sure if the "ExecutesApi" part would still be relevant. But I'll point it out in case.
</blockquote></details>

The ExecutesApi part should be covered by the corresponding `_Success` tests (the data is all mocked from the API Client).
___
*[`test/SIL.XForge.Scripture.Tests/Services/MachineApiServiceTests.cs` line 1833 at r3](https://reviewable.io/reviews/sillsdev/web-xforge/2350#-NrbVQfc61DNCP7W7ZKf:-NrbxBg215MbqkMq0b22:by3n4us) ([raw file](https://github.com/sillsdev/web-xforge/blob/c6c30257c91b7c7e9b82b389e956deb8a3f328dc/test/SIL.XForge.Scripture.Tests/Services/MachineApiServiceTests.cs#L1833)):*
<details><summary><i>Previously, marksvc wrote…</i></summary><blockquote>

I didn't see around here if there is a test for the serval translation engine recreation error being propagated / crashing, in the new Serval-only world. If that's significant.
</blockquote></details>

Done. Good thinking.

**Review by marksvc — APPROVED** [review]
> Reviewed 3 of 33 files at r1, 1 of 9 files at r2, 1 of 6 files at r3, 7 of 9 files at r4, 4 of 4 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/2350)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @pmachapman)

**Pull request merged**
