### PR TITLE
SF-1022 Update question verseRefs in scripture panel when edited remo…

### PR DESCRIPTION
**Pull request by RaymondLuong3**
…tely
* Subscribe to changes to a questionDoc to know have the most up to date verse ref.
* Update question refs data on any question doc has changed

Previously the question icon and highlight do not update in real time on a checker user if an admin edits a question's verse ref. This change keeps the checking questions component's knowledge of the activeQuestionVerseRef up to date.

---
This change is [Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/814)

### CODE REVIEW

**Review by nigel-wells — CHANGES_REQUESTED** [review]
Nice one - just one query around the subscription.

> Reviewed 3 of 3 files at r1.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/814#-:-MIHjeK1-CTxxPBgJz0x:bmtnap6)* status: all files reviewed, 1 unresolved discussion (waiting on @RaymondLuong3)

___
*[src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-questions/checking-questions.component.ts, line 266 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/814#-MIHhcoW6AAQK1yC9Tvd:-MIHhcoW6AAQK1yC9Tve:b-8bdjo3) ([raw file](https://github.com/sillsdev/web-xforge/blob/61b10e5a939651d82af11416059005938d9558b3/src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-questions/checking-questions.component.ts#L266)):*
<details><summary><i alt="summary">Quoted 7 lines of code…</i></summary>

> ```
> on != null) {
>             this.questionDocSubscription.unsubscribe();
>           }
>           this.questionDocSubscription = questionDoc.remoteChanges$.subscribe(
>             () =>
>               (this._activeQuestionVerseRef =
>                 questionDoc.data == null
> ```
</details>

I wonder if this would better sit in the main `CheckingComponent` including refactoring `_activeQuestionVerseRef ` to be stored there as well as this will also then allow the subscription can be disposed off. You can probably use an existing subscription as well to trigger the update of this value. You might need to wait until `SF-978` is merged as that includes a subscription from `questionsQuery.remoteDocChanges$` which includes the document that changed.

**Review by RaymondLuong3 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/814)* status: 0 of 3 files reviewed, 1 unresolved discussion (waiting on @nigel-wells)

___
*[src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-questions/checking-questions.component.ts, line 266 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/814#-MIHhcoW6AAQK1yC9Tvd:-MIQ-osI9KB17Q5Po03S:b86e385) ([raw file](https://github.com/sillsdev/web-xforge/blob/61b10e5a939651d82af11416059005938d9558b3/src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-questions/checking-questions.component.ts#L266)):*
<details><summary><i>Previously, nigel-wells (Nigel Wells) wrote…</i></summary><blockquote>

> ```
> on != null) {
>             this.questionDocSubscription.unsubscribe();
>           }
>           this.questionDocSubscription = questionDoc.remoteChanges$.subscribe(
>             () =>
>               (this._activeQuestionVerseRef =
>                 questionDoc.data == null
> ```
I wonder if this would better sit in the main `CheckingComponent` including refactoring `_activeQuestionVerseRef ` to be stored there as well as this will also then allow the subscription can be disposed off. You can probably use an existing subscription as well to trigger the update of this value. You might need to wait until `SF-978` is merged as that includes a subscription from `questionsQuery.remoteDocChanges$` which includes the document that changed.
</blockquote></details>

Ok, that makes sense. I've moved `_activeQuestionVerseRef` to the checking component. This gets updated whenever a question doc is changed and when a change occurs to the question doc.

**Review by nigel-wells — CHANGES_REQUESTED** [review]
Yes that's is starting to look better thanks.

> Reviewed 1 of 2 files at r2, 2 of 2 files at r3.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/814#-:-MIQdp72-g9UWBarjYaq:blqe5t6)* status: all files reviewed, 3 unresolved discussions (waiting on @RaymondLuong3)

___
*[src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking.component.ts, line 82 at r3](https://reviewable.io/reviews/sillsdev/web-xforge/814#-MIQcsB81xBG5VrKeIGP:-MIQcsB81xBG5VrKeIGQ:b5v1oij) ([raw file](https://github.com/sillsdev/web-xforge/blob/ea8780af89fb88a5b3487fa2a4ead2e3d32d5ce3/src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking.component.ts#L82)):*
> ```XML
>   };
>   questionVerseRefs: VerseRef[] = [];
>   _activeQuestionVerseRef?: VerseRef;
> ```

Can be private
___
*[src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking.component.ts, line 635 at r3](https://reviewable.io/reviews/sillsdev/web-xforge/814#-MIQdY-jETMcchgp3AMs:-MIQdY-jETMcchgp3AMt:bgi5rt8) ([raw file](https://github.com/sillsdev/web-xforge/blob/ea8780af89fb88a5b3487fa2a4ead2e3d32d5ce3/src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking.component.ts#L635)):*
> ```XML
>     this.book = questionDoc.data == null ? undefined : questionDoc.data.verseRef.bookNum;
>     this.chapter = this.questionsPanel.activeQuestionChapter;
>     this._activeQuestionVerseRef = questionDoc.data == null ? undefined : toVerseRef(questionDoc.data.verseRef);
> ```

Perhaps create a private function where you pass the `questionDoc` to do this logic and further up to avoid duplication
___
*[src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-questions/checking-questions.component.ts, line 266 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/814#-MIHhcoW6AAQK1yC9Tvd:-MIQcJe6EzZfCoeySAqL:b5995l6) ([raw file](https://github.com/sillsdev/web-xforge/blob/61b10e5a939651d82af11416059005938d9558b3/src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-questions/checking-questions.component.ts#L266)):*
<details><summary><i>Previously, RaymondLuong3 (Raymond Luong) wrote…</i></summary><blockquote>

Ok, that makes sense. I've moved `_activeQuestionVerseRef` to the checking component. This gets updated whenever a question doc is changed and when a change occurs to the question doc.
</blockquote></details>

Great. Looks like you can remove `questionDocSubscription` now as it isn't being used?

**Review by RaymondLuong3 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/814)* status: all files reviewed, 3 unresolved discussions (waiting on @nigel-wells)

___
*[src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking.component.ts, line 82 at r3](https://reviewable.io/reviews/sillsdev/web-xforge/814#-MIQcsB81xBG5VrKeIGP:-MIUv8a53A-9E6oKEkAQ:b-896fix) ([raw file](https://github.com/sillsdev/web-xforge/blob/ea8780af89fb88a5b3487fa2a4ead2e3d32d5ce3/src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking.component.ts#L82)):*
<details><summary><i>Previously, nigel-wells (Nigel Wells) wrote…</i></summary><blockquote>

Can be private
</blockquote></details>

Done.
___
*[src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking.component.ts, line 635 at r3](https://reviewable.io/reviews/sillsdev/web-xforge/814#-MIQdY-jETMcchgp3AMs:-MIUv9e43B353o2WQRpB:b-896fix) ([raw file](https://github.com/sillsdev/web-xforge/blob/ea8780af89fb88a5b3487fa2a4ead2e3d32d5ce3/src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking.component.ts#L635)):*
<details><summary><i>Previously, nigel-wells (Nigel Wells) wrote…</i></summary><blockquote>

Perhaps create a private function where you pass the `questionDoc` to do this logic and further up to avoid duplication
</blockquote></details>

Done.
___
*[src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-questions/checking-questions.component.ts, line 266 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/814#-MIHhcoW6AAQK1yC9Tvd:-MIUv2al7zRwNrjD3fUn:b-ekfkdf) ([raw file](https://github.com/sillsdev/web-xforge/blob/61b10e5a939651d82af11416059005938d9558b3/src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-questions/checking-questions.component.ts#L266)):*
<details><summary><i>Previously, nigel-wells (Nigel Wells) wrote…</i></summary><blockquote>

Great. Looks like you can remove `questionDocSubscription` now as it isn't being used?
</blockquote></details>

Good catch, I missed that than. Done.

**Review by nigel-wells — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r4.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/814#-:-MIW51a519iGTMVfr3bD:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
