### PR TITLE
Chapter and Book Permissions

### PR DESCRIPTION
**Pull request by pmachapman**
* Chapter permissions added to the model
 * Chapter and book permissions are loaded from Paratext
 * Chapter and book permissions are used to only sync what a user is allow to write to
 * Users can only edit chapters that they have permission to edit
 * Added Chapter and Book permission migrator

---
This change is [Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/888)

### CODE REVIEW

**Review by ddaspit — COMMENTED** [review]
This PR is difficult to review right now, because it includes all of the changes for the source/target splitting. It would be great if this could be rebased on the recent merged changes.

> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/888#-:-MO5DZudDECr5jplnSsC:b-cawdq4)* status: 0 of 81 files reviewed, all discussions resolved

**Comment by irahopkinson** [comment]
@pmachapman I just changed the base of this PR to `develop` so once you rebase your changes there then Damien can review it.

**Review by ddaspit — CHANGES_REQUESTED** [review]
> Reviewed 23 of 23 files at r1.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/888)* status: all files reviewed, 14 unresolved discussions (waiting on @pmachapman)

___
*[src/Migrations/SourceTargetSplitting/ObjectMigrator.cs, line 392 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/888#-MOAbgSlENv52LVX8aXD:-MOAbgSmEaGjZMkyuSwZ:bdjwnry) ([raw file](https://github.com/sillsdev/web-xforge/blob/b2c70a75ebfc1dd4396374ab393f8be33c354e25/src/Migrations/SourceTargetSplitting/ObjectMigrator.cs#L392)):*
> ```Smalltalk
>         {
>             // Get the existing projects from MongoDB
>             List<SFProject> existingProjects = this._realtimeService.QuerySnapshots<SFProject>().ToList();
> ```

This should be `ToListAsync`.
___
*[src/Migrations/SourceTargetSplitting/ObjectMigrator.cs, line 402 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/888#-MOAcQcf1CKtFcvEBZyM:-MOAcQcf1CKtFcvEBZyN:b-kgt3yv) ([raw file](https://github.com/sillsdev/web-xforge/blob/b2c70a75ebfc1dd4396374ab393f8be33c354e25/src/Migrations/SourceTargetSplitting/ObjectMigrator.cs#L402)):*
> ```Smalltalk
>             // Get every user id and username from the user secrets
>             Dictionary<string, string> userMapping = this._userSecrets.Query()
>                 .ToDictionary(u => u.Id, u => this._paratextService.GetParatextUsername(u));
> ```

This LINQ query should end in an async call, so the Mongo query is async instead of blocking. We haven't implemented `ToDictionaryAsync` yet, but you can implement it. Check out the implementation of `ToListAsync` in `DataAccessExtensions`. Otherwise call `ToListAsync` first, then call `ToDictionary`.
___
*[src/Migrations/SourceTargetSplitting/ObjectMigrator.cs, line 451 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/888#-MOAdVz733dzRryaBBT9:-MOAdVz733dzRryaBBTA:b-4y0alq) ([raw file](https://github.com/sillsdev/web-xforge/blob/b2c70a75ebfc1dd4396374ab393f8be33c354e25/src/Migrations/SourceTargetSplitting/ObjectMigrator.cs#L451)):*
> ```Smalltalk
> 
>                         // Calculate the book permissions
>                         foreach ((string uid, string role) in project.UserRoles)
> ```

It looks like you only need to iterate through the keys. The role is not used.
___
*[src/Migrations/SourceTargetSplitting/ObjectMigrator.cs, line 455 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/888#-MOAdNuU2q2SAog4q-aH:-MOAdNuU2q2SAog4q-aI:bfhswnl) ([raw file](https://github.com/sillsdev/web-xforge/blob/b2c70a75ebfc1dd4396374ab393f8be33c354e25/src/Migrations/SourceTargetSplitting/ObjectMigrator.cs#L455)):*
> ```Smalltalk
>                             // See if the user is in the project members list
>                             userMapping.TryGetValue(uid, out string? userName);
>                             if (string.IsNullOrWhiteSpace(userName))
> ```

Is there some reason why you don't call `TryGetValue` in the if statement? Is it possible for the user name to be an empty string?
___
*[src/Migrations/SourceTargetSplitting/ObjectMigrator.cs, line 497 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/888#-MOAdujL6Tp9Qb__S9Vh:-MOAdujL6Tp9Qb__S9Vi:b-4y0alq) ([raw file](https://github.com/sillsdev/web-xforge/blob/b2c70a75ebfc1dd4396374ab393f8be33c354e25/src/Migrations/SourceTargetSplitting/ObjectMigrator.cs#L497)):*
> ```Smalltalk
> 
>                             // Calculate the chapter permissions
>                             foreach ((string uid, string role) in project.UserRoles)
> ```

It looks like you only need to iterate through the keys. The role is not used.
___
*[src/Migrations/SourceTargetSplitting/ObjectMigrator.cs, line 501 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/888#-MOAdwuD5PMIxVZF1sJj:-MOAdwuD5PMIxVZF1sJk:bfhswnl) ([raw file](https://github.com/sillsdev/web-xforge/blob/b2c70a75ebfc1dd4396374ab393f8be33c354e25/src/Migrations/SourceTargetSplitting/ObjectMigrator.cs#L501)):*
> ```Smalltalk
>                                 // See if the user is in the project members list
>                                 userMapping.TryGetValue(uid, out string? userName);
>                                 if (string.IsNullOrWhiteSpace(userName))
> ```

Is there some reason why you don't call `TryGetValue` in the if statement? Is it possible for the user name to be an empty string?
___
*[src/Migrations/SourceTargetSplitting/ObjectMigrator.cs, line 525 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/888#-MOAe0nb6SyB-UcNgihS:-MOAe0nb6SyB-UcNgihT:bgo6d2k) ([raw file](https://github.com/sillsdev/web-xforge/blob/b2c70a75ebfc1dd4396374ab393f8be33c354e25/src/Migrations/SourceTargetSplitting/ObjectMigrator.cs#L525)):*
> ```Smalltalk
>                                 await projectDoc.SubmitJson0OpAsync(op =>
>                                 {
>                                     op.Set(pd => pd.Texts[i].Chapters[j].Permissions, chapterPermissions);
> ```

This could turn into a lot of little ops. I think it would be better to aggregate all of the changes into a single op for the project. I think it would make the migration faster.
___
*[src/Migrations/SourceTargetSplitting/ObjectMigrator.cs, line 618 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/888#-MOAeLyI6pwYBzcoMcL_:-MOAeLyI6pwYBzcoMcLa:bbdw8y0) ([raw file](https://github.com/sillsdev/web-xforge/blob/b2c70a75ebfc1dd4396374ab393f8be33c354e25/src/Migrations/SourceTargetSplitting/ObjectMigrator.cs#L618)):*
> ```Smalltalk
> 
>                 // Load the source project from the target project's source directory (it is not moved in test mode)
>                 ScrText? scrText = this.SourceScrTextCollection.FindById("admin", targetId);
> ```

Is there some reason why you needed to add the `this`? Generally, our coding style is not to use `this`.
___
*[src/SIL.XForge.Scripture/Services/ParatextService.cs, line 336 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/888#-MOAV_d5BGikMTsjGyH4:-MOAV_d5BGikMTsjGyH5:b-4y0alq) ([raw file](https://github.com/sillsdev/web-xforge/blob/b2c70a75ebfc1dd4396374ab393f8be33c354e25/src/SIL.XForge.Scripture/Services/ParatextService.cs#L336)):*
> ```Smalltalk
>             if (project.ParatextId.Length == SFInstallableDblResource.ResourceIdentifierLength)
>             {
>                 foreach ((string uid, string role) in project.UserRoles)
> ```

It looks like you only need to iterate through the keys. The role is not used.
___
*[src/SIL.XForge.Scripture/Services/ParatextService.cs, line 345 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/888#-MOAVuMH6WyAhtZTAHon:-MOAVuMH6WyAhtZTAHoo:bwsp192) ([raw file](https://github.com/sillsdev/web-xforge/blob/b2c70a75ebfc1dd4396374ab393f8be33c354e25/src/SIL.XForge.Scripture/Services/ParatextService.cs#L345)):*
> ```Smalltalk
>                 // Get the mapping for paratext users ids to names from the registry
>                 string response = await CallApiAsync(_registryClient, userSecret, HttpMethod.Get,
>                 $"projects/{project.ParatextId}/members");
> ```

This should be indented.
___
*[src/SIL.XForge.Scripture/Services/ParatextService.cs, line 354 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/888#-MOAWlis-PRKg7eOBAHN:-MOAWlis-PRKg7eOBAHO:b-kgt3yv) ([raw file](https://github.com/sillsdev/web-xforge/blob/b2c70a75ebfc1dd4396374ab393f8be33c354e25/src/SIL.XForge.Scripture/Services/ParatextService.cs#L354)):*
> ```Smalltalk
>                 Dictionary<string, string> userMapping = this._realtimeService.QuerySnapshots<User>()
>                         .Where(u => paratextMapping.Keys.Contains(u.ParatextId))
>                         .ToDictionary(u => u.Id, u => paratextMapping[u.ParatextId]);
> ```

This LINQ query should end in an async call, so the Mongo query is async instead of blocking. We haven't implemented `ToDictionaryAsync` yet, but you can implement it. Check out the implementation of `ToListAsync` in `DataAccessExtensions`. Otherwise call `ToListAsync` first, then call `ToDictionary`.
___
*[src/SIL.XForge.Scripture/Services/ParatextService.cs, line 360 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/888#-MOAYJlJBBmt5I6jYGsA:-MOAYJlJBBmt5I6jYGsB:b-4y0alq) ([raw file](https://github.com/sillsdev/web-xforge/blob/b2c70a75ebfc1dd4396374ab393f8be33c354e25/src/SIL.XForge.Scripture/Services/ParatextService.cs#L360)):*
> ```Smalltalk
> 
>                 // Calculate the project and resource permissions
>                 foreach ((string uid, string role) in project.UserRoles)
> ```

It looks like you only need to iterate through the keys. The role is not used.
___
*[src/SIL.XForge.Scripture/Services/ParatextService.cs, line 364 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/888#-MOAXlQuEM4HUQ_iijjY:-MOAXlQuEM4HUQ_iijjZ:bfhswnl) ([raw file](https://github.com/sillsdev/web-xforge/blob/b2c70a75ebfc1dd4396374ab393f8be33c354e25/src/SIL.XForge.Scripture/Services/ParatextService.cs#L364)):*
> ```Smalltalk
>                     // See if the user is in the project members list
>                     userMapping.TryGetValue(uid, out string userName);
>                     if (string.IsNullOrWhiteSpace(userName))
> ```

Is there some reason why you don't call `TryGetValue` in the if statement? Is it possible for the user name to be an empty string?
___
*[src/SIL.XForge.Scripture/Services/ParatextSyncRunner.cs, line 641 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/888#-MOAZXUGC0GomCXs79QL:-MOAZXUGC0GomCXs79QM:b-xsyhln) ([raw file](https://github.com/sillsdev/web-xforge/blob/b2c70a75ebfc1dd4396374ab393f8be33c354e25/src/SIL.XForge.Scripture/Services/ParatextSyncRunner.cs#L641)):*
> ```Smalltalk
>             public int GetHashCode(Dictionary<TKey, TValue> obj)
>             {
>                 throw new NotImplementedException();
> ```

I know that in this case you can probably get away without implementing this method. Since `ParatextSyncRunner` doesn't "know" the implementation of the method that the `DictionaryComparer` is being passed to, it would be better if the class adheres to the contract that the method is expecting. It shouldn't be hard to implement.

**Review by pmachapman — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/888)* status: 17 of 24 files reviewed, 14 unresolved discussions (waiting on @ddaspit)

___
*[src/Migrations/SourceTargetSplitting/ObjectMigrator.cs, line 392 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/888#-MOAbgSlENv52LVX8aXD:-MOSZjKE0e4Cnsp_ccn4:bm2kv8j) ([raw file](https://github.com/sillsdev/web-xforge/blob/b2c70a75ebfc1dd4396374ab393f8be33c354e25/src/Migrations/SourceTargetSplitting/ObjectMigrator.cs#L392)):*
<details><summary><i>Previously, ddaspit (Damien Daspit) wrote…</i></summary><blockquote>

This should be `ToListAsync`.
</blockquote></details>

Yes it should - changed.
___
*[src/Migrations/SourceTargetSplitting/ObjectMigrator.cs, line 402 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/888#-MOAcQcf1CKtFcvEBZyM:-MOScE299qnp-PaZqsU_:b-jr7nhy) ([raw file](https://github.com/sillsdev/web-xforge/blob/b2c70a75ebfc1dd4396374ab393f8be33c354e25/src/Migrations/SourceTargetSplitting/ObjectMigrator.cs#L402)):*
<details><summary><i>Previously, ddaspit (Damien Daspit) wrote…</i></summary><blockquote>

This LINQ query should end in an async call, so the Mongo query is async instead of blocking. We haven't implemented `ToDictionaryAsync` yet, but you can implement it. Check out the implementation of `ToListAsync` in `DataAccessExtensions`. Otherwise call `ToListAsync` first, then call `ToDictionary`.
</blockquote></details>

I have implemented a ToDictionaryAsync() based on the ToListAsync() implementation.
___
*[src/Migrations/SourceTargetSplitting/ObjectMigrator.cs, line 451 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/888#-MOAdVz733dzRryaBBT9:-MOScwROBj3d85qeBTNY:b-a2ujfl) ([raw file](https://github.com/sillsdev/web-xforge/blob/b2c70a75ebfc1dd4396374ab393f8be33c354e25/src/Migrations/SourceTargetSplitting/ObjectMigrator.cs#L451)):*
<details><summary><i>Previously, ddaspit (Damien Daspit) wrote…</i></summary><blockquote>

It looks like you only need to iterate through the keys. The role is not used.
</blockquote></details>

Changed.
___
*[src/Migrations/SourceTargetSplitting/ObjectMigrator.cs, line 455 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/888#-MOAdNuU2q2SAog4q-aH:-MOSgOjC8uMcSAXhZXrl:b-qpzkxn) ([raw file](https://github.com/sillsdev/web-xforge/blob/b2c70a75ebfc1dd4396374ab393f8be33c354e25/src/Migrations/SourceTargetSplitting/ObjectMigrator.cs#L455)):*
<details><summary><i>Previously, ddaspit (Damien Daspit) wrote…</i></summary><blockquote>

Is there some reason why you don't call `TryGetValue` in the if statement? Is it possible for the user name to be an empty string?
</blockquote></details>

Potentially if there were issues with the JWT token - the TryGetValue will only check the key. I've moved the TryGetValue into the if condition.
___
*[src/Migrations/SourceTargetSplitting/ObjectMigrator.cs, line 497 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/888#-MOAdujL6Tp9Qb__S9Vh:-MOSh_poEdxSNjC7sLdd:b-a2ujfl) ([raw file](https://github.com/sillsdev/web-xforge/blob/b2c70a75ebfc1dd4396374ab393f8be33c354e25/src/Migrations/SourceTargetSplitting/ObjectMigrator.cs#L497)):*
<details><summary><i>Previously, ddaspit (Damien Daspit) wrote…</i></summary><blockquote>

It looks like you only need to iterate through the keys. The role is not used.
</blockquote></details>

Changed.
___
*[src/Migrations/SourceTargetSplitting/ObjectMigrator.cs, line 501 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/888#-MOAdwuD5PMIxVZF1sJj:-MOShapY0zXhVTmS8_ML:btwvf17) ([raw file](https://github.com/sillsdev/web-xforge/blob/b2c70a75ebfc1dd4396374ab393f8be33c354e25/src/Migrations/SourceTargetSplitting/ObjectMigrator.cs#L501)):*
<details><summary><i>Previously, ddaspit (Damien Daspit) wrote…</i></summary><blockquote>

Is there some reason why you don't call `TryGetValue` in the if statement? Is it possible for the user name to be an empty string?
</blockquote></details>

I've moved the TryGetValue into the if condition.
___
*[src/Migrations/SourceTargetSplitting/ObjectMigrator.cs, line 525 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/888#-MOAe0nb6SyB-UcNgihS:-MOSkoQi4nfYtD0KdNLT:bptq48s) ([raw file](https://github.com/sillsdev/web-xforge/blob/b2c70a75ebfc1dd4396374ab393f8be33c354e25/src/Migrations/SourceTargetSplitting/ObjectMigrator.cs#L525)):*
<details><summary><i>Previously, ddaspit (Damien Daspit) wrote…</i></summary><blockquote>

This could turn into a lot of little ops. I think it would be better to aggregate all of the changes into a single op for the project. I think it would make the migration faster.
</blockquote></details>

I have rewritten them into one SubmitJson0OpAsync(), if that's what you were meaning?
___
*[src/Migrations/SourceTargetSplitting/ObjectMigrator.cs, line 618 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/888#-MOAeLyI6pwYBzcoMcL_:-MOSlBZZEv9klX81Y3Hx:bqdxc00) ([raw file](https://github.com/sillsdev/web-xforge/blob/b2c70a75ebfc1dd4396374ab393f8be33c354e25/src/Migrations/SourceTargetSplitting/ObjectMigrator.cs#L618)):*
<details><summary><i>Previously, ddaspit (Damien Daspit) wrote…</i></summary><blockquote>

Is there some reason why you needed to add the `this`? Generally, our coding style is not to use `this`.
</blockquote></details>

A habit from regular use of StyleCop. I've removed it in this case to de-clutter the branch, and can strip it everywhere else if you want me to?
___
*[src/SIL.XForge.Scripture/Services/ParatextService.cs, line 336 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/888#-MOAV_d5BGikMTsjGyH4:-MOSnT_O-7e2MExiPuJX:b-a2ujfl) ([raw file](https://github.com/sillsdev/web-xforge/blob/b2c70a75ebfc1dd4396374ab393f8be33c354e25/src/SIL.XForge.Scripture/Services/ParatextService.cs#L336)):*
<details><summary><i>Previously, ddaspit (Damien Daspit) wrote…</i></summary><blockquote>

It looks like you only need to iterate through the keys. The role is not used.
</blockquote></details>

Changed.
___
*[src/SIL.XForge.Scripture/Services/ParatextService.cs, line 345 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/888#-MOAVuMH6WyAhtZTAHon:-MOSi18I1JnvarX7htOB:bt2vr1b) ([raw file](https://github.com/sillsdev/web-xforge/blob/b2c70a75ebfc1dd4396374ab393f8be33c354e25/src/SIL.XForge.Scripture/Services/ParatextService.cs#L345)):*
<details><summary><i>Previously, ddaspit (Damien Daspit) wrote…</i></summary><blockquote>

This should be indented.
</blockquote></details>

Fixed.
___
*[src/SIL.XForge.Scripture/Services/ParatextService.cs, line 354 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/888#-MOAWlis-PRKg7eOBAHN:-MOSnnyw2rOZakt5xvrm:b-16yjsa) ([raw file](https://github.com/sillsdev/web-xforge/blob/b2c70a75ebfc1dd4396374ab393f8be33c354e25/src/SIL.XForge.Scripture/Services/ParatextService.cs#L354)):*
<details><summary><i>Previously, ddaspit (Damien Daspit) wrote…</i></summary><blockquote>

This LINQ query should end in an async call, so the Mongo query is async instead of blocking. We haven't implemented `ToDictionaryAsync` yet, but you can implement it. Check out the implementation of `ToListAsync` in `DataAccessExtensions`. Otherwise call `ToListAsync` first, then call `ToDictionary`.
</blockquote></details>

Changed to ToDictionaryAsync().
___
*[src/SIL.XForge.Scripture/Services/ParatextService.cs, line 360 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/888#-MOAYJlJBBmt5I6jYGsA:-MOSnc0OBDwnUwn0E9VO:b-a2ujfl) ([raw file](https://github.com/sillsdev/web-xforge/blob/b2c70a75ebfc1dd4396374ab393f8be33c354e25/src/SIL.XForge.Scripture/Services/ParatextService.cs#L360)):*
<details><summary><i>Previously, ddaspit (Damien Daspit) wrote…</i></summary><blockquote>

It looks like you only need to iterate through the keys. The role is not used.
</blockquote></details>

Changed.
___
*[src/SIL.XForge.Scripture/Services/ParatextService.cs, line 364 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/888#-MOAXlQuEM4HUQ_iijjY:-MOSnfu-DnRdN14X3y-l:btwvf17) ([raw file](https://github.com/sillsdev/web-xforge/blob/b2c70a75ebfc1dd4396374ab393f8be33c354e25/src/SIL.XForge.Scripture/Services/ParatextService.cs#L364)):*
<details><summary><i>Previously, ddaspit (Damien Daspit) wrote…</i></summary><blockquote>

Is there some reason why you don't call `TryGetValue` in the if statement? Is it possible for the user name to be an empty string?
</blockquote></details>

I've moved the TryGetValue into the if condition.
___
*[src/SIL.XForge.Scripture/Services/ParatextSyncRunner.cs, line 641 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/888#-MOAZXUGC0GomCXs79QL:-MOSuHUo1z7L2WHwmmfj:bz1dnnh) ([raw file](https://github.com/sillsdev/web-xforge/blob/b2c70a75ebfc1dd4396374ab393f8be33c354e25/src/SIL.XForge.Scripture/Services/ParatextSyncRunner.cs#L641)):*
<details><summary><i>Previously, ddaspit (Damien Daspit) wrote…</i></summary><blockquote>

I know that in this case you can probably get away without implementing this method. Since `ParatextSyncRunner` doesn't "know" the implementation of the method that the `DictionaryComparer` is being passed to, it would be better if the class adheres to the contract that the method is expecting. It shouldn't be hard to implement.
</blockquote></details>

I've implemented a GetHashCode() using the Key and Value individually, as the default .Net implementation uses GetHashCode() in the ValueType underlying the generic KeyValuePair, which only uses the Key.

**Review by ddaspit — COMMENTED** [review]
@irahopkinson and I discussed the change to mark each update with the last user that edited a chapter. We want to defer this change to a subsequent PR. We have a different implementation in mind that will add too much complication to this PR. Please rollback all of the changes you made to support this except the changes to `ParatextService.PutBookText`. That code will be useful in the subsequent PR.

> Reviewed 18 of 18 files at r2.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/888#-:-MOp708Z1C53x6V_tpQp:b68anyk)* status: all files reviewed, 1 unresolved discussion (waiting on @pmachapman)

___
*[src/Migrations/SourceTargetSplitting/ObjectMigrator.cs, line 618 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/888#-MOAeLyI6pwYBzcoMcL_:-MOp0AIR4wHfzVLhzVQW:bn8vewg) ([raw file](https://github.com/sillsdev/web-xforge/blob/b2c70a75ebfc1dd4396374ab393f8be33c354e25/src/Migrations/SourceTargetSplitting/ObjectMigrator.cs#L618)):*
<details><summary><i>Previously, pmachapman (Peter Chapman) wrote…</i></summary><blockquote>

A habit from regular use of StyleCop. I've removed it in this case to de-clutter the branch, and can strip it everywhere else if you want me to?
</blockquote></details>

You don't have to worry about cleaning up all uses.
___
*[src/SIL.XForge.Scripture/Services/ParatextService.cs, line 481 at r2](https://reviewable.io/reviews/sillsdev/web-xforge/888#-MOpD6UzEDfzrcXu1xXQ:-MOpD6UzEDfzrcXu1xXR:bg323ls) ([raw file](https://github.com/sillsdev/web-xforge/blob/a035cca27b28d4a562f08d327947d06022083380/src/SIL.XForge.Scripture/Services/ParatextService.cs#L481)):*
> ```Smalltalk
>                 // If we don't have chapter authors, update only what we have permission for
>                 // This is the same check ScrText.PutText() will use to block the Put action with a SafetyCheckException
>                 if (scrText.Permissions.CanEdit(bookNum, 0))
> ```

To be safe, we want to throw an exception here if we don't have permission to write the book, so that the sync fails. The mongo data and the USFM data could get out-of-sync and cause issues.

**Review by pmachapman — COMMENTED** [review]
Done - I've rolled it back, and preserved the logic in PutBookText for future use.

> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/888#-:-MOrrQvm2DJRz02FafWj:b-fp607o)* status: 17 of 24 files reviewed, 1 unresolved discussion (waiting on @ddaspit)

___
*[src/SIL.XForge.Scripture/Services/ParatextService.cs, line 481 at r2](https://reviewable.io/reviews/sillsdev/web-xforge/888#-MOpD6UzEDfzrcXu1xXQ:-MOr_lyF0spD5Lpc5saT:b-n6wl9y) ([raw file](https://github.com/sillsdev/web-xforge/blob/a035cca27b28d4a562f08d327947d06022083380/src/SIL.XForge.Scripture/Services/ParatextService.cs#L481)):*
<details><summary><i>Previously, ddaspit (Damien Daspit) wrote…</i></summary><blockquote>

To be safe, we want to throw an exception here if we don't have permission to write the book, so that the sync fails. The mongo data and the USFM data could get out-of-sync and cause issues.
</blockquote></details>

Done. I am calling ScrText.PutText(), and letting Paratext throw the error (which it does).

**Review by ddaspit — APPROVED** [review]
:lgtm:

> Reviewed 7 of 13 files at r3.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/888#-:-MP3AzEt2BN57UjKwa9s:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
