### PR TITLE
SF-1177 Show progress as source and target projects combined on sync

### PR DESCRIPTION
**Pull request by RaymondLuong3**
When a source project exists, the progress represents the entirety of synchronizing both the source and target projects.

* extract the sync progress bar into its own component
* sync progress automatically detects if a source project exists and updates accordingly
* sync progress is implemented as an angular material component
* add theming to angular material component

---
This change is [Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/923)

### CODE REVIEW

**Review by irahopkinson — CHANGES_REQUESTED** [review]
Thanks, this is definetley an improvement on what we had. A couple of further improvements:
* You should make this change for connect project as well
* I would prefer the progress went back to indeterminant between syncs, i.e. after syncing the source and while its setting up sync for the target

> Reviewed 2 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/923#-:-MRItJeIEW8ofUwnJtUV:b14evsj)* status: all files reviewed, 1 unresolved discussion (waiting on @RaymondLuong3)

___
*[src/SIL.XForge.Scripture/ClientApp/src/app/sync/sync.component.ts, line 128 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/923#-MRIvpDa98jg4Xay7vzO:-MRIvpDa98jg4Xay7vzP:b-isfcbs) ([raw file](https://github.com/sillsdev/web-xforge/blob/3b1f07a688206d1d5aec6fa9078427ed64a22803/src/SIL.XForge.Scripture/ClientApp/src/app/sync/sync.component.ts#L128)):*
> ```
> if (this.projectDoc?.data?.translateConfig.translationSuggestionsEnabled != null) {
> ```
Doesn't `translationSuggestionsEnabled` need to be defined and true? So the above could be `if (this.projectDoc?.data?.translateConfig?.translationSuggestionsEnabled) {`?

**Review by RaymondLuong3 — COMMENTED** [review]
I have moved the sync-progress bar into its own component so that it can be used in both the connect-project component and the sync component without having to manually set up listening to the status. I've also taken the suggestion about showing indeterminate between source and target synchronizing.

> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/923#-:-MRWa4poESnojLZz_O4M:b-rs5b8z)* status: 0 of 15 files reviewed, 1 unresolved discussion (waiting on @irahopkinson)

___
*[src/SIL.XForge.Scripture/ClientApp/src/material-styles.scss, line 6 at r2](https://reviewable.io/reviews/sillsdev/web-xforge/923#-MRWaq_TDMQKCwWJiuxI:-MRWaq_TDMQKCwWJiuxJ:bb9scmi) ([raw file](https://github.com/sillsdev/web-xforge/blob/78bb1b63b0c1fe07f0dcb8ccc6a4c66aa5de0779/src/SIL.XForge.Scripture/ClientApp/src/material-styles.scss#L6)):*
> ```
> $greyDark: mat-palette($mat-gray, 800);
> $greenLight: mat-palette($mat-light-green, 300);
> ```
This is not 100% identical to the colors current in our app, but is very close. The docs didn't indicate that you could use a palette other than the specified ones on the material design site, which is where these come from.
___
*[src/SIL.XForge.Scripture/ClientApp/src/app/sync/sync.component.ts, line 128 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/923#-MRIvpDa98jg4Xay7vzO:-MRWaficEmXgk5gxN9fW:b-ydxxpv) ([raw file](https://github.com/sillsdev/web-xforge/blob/3b1f07a688206d1d5aec6fa9078427ed64a22803/src/SIL.XForge.Scripture/ClientApp/src/app/sync/sync.component.ts#L128)):*
<details><summary><i>Previously, irahopkinson (Ira Hopkinson) wrote…</i></summary><blockquote>

> ```
> if (this.projectDoc?.data?.translateConfig.translationSuggestionsEnabled != null) {
> ```
Doesn't `translationSuggestionsEnabled` need to be defined and true? So the above could be `if (this.projectDoc?.data?.translateConfig?.translationSuggestionsEnabled) {`?
</blockquote></details>

That's a good point. I have moved  that check to the sync-progress component.

**Review by irahopkinson — CHANGES_REQUESTED** [review]
Thanks for pulling the sync progress bar into its own component to get us DRY-er. This is all looking good - just a few things to cleanup before merge.

> Reviewed 15 of 15 files at r2.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/923#-:-MRY5TnX3fRHJcIap0bu:bk88ru1)* status: all files reviewed, 10 unresolved discussions (waiting on @RaymondLuong3)

___
*[src/SIL.XForge.Scripture/ClientApp/angular.json, line 41 at r2](https://reviewable.io/reviews/sillsdev/web-xforge/923#-MRXlCY85CNziBWlfnau:-MRXlCY85CNziBWlfnav:bq23hby) ([raw file](https://github.com/sillsdev/web-xforge/blob/78bb1b63b0c1fe07f0dcb8ccc6a4c66aa5de0779/src/SIL.XForge.Scripture/ClientApp/angular.json#L41)):*
> ```JSON
>               },
>               "src/styles.scss",
>               "src/material-styles.scss"
> ```

This needs to be added to the test build config below also.
___
*[src/SIL.XForge.Scripture/ClientApp/src/material-styles.scss, line 6 at r2](https://reviewable.io/reviews/sillsdev/web-xforge/923#-MRWaq_TDMQKCwWJiuxI:-MRXtjrnCJHXvgBliMbq:buv2b0) ([raw file](https://github.com/sillsdev/web-xforge/blob/78bb1b63b0c1fe07f0dcb8ccc6a4c66aa5de0779/src/SIL.XForge.Scripture/ClientApp/src/material-styles.scss#L6)):*
<details><summary><i>Previously, RaymondLuong3 (Raymond Luong) wrote…</i></summary><blockquote>

> ```
> $greyDark: mat-palette($mat-gray, 800);
> $greenLight: mat-palette($mat-light-green, 300);
> ```
This is not 100% identical to the colors current in our app, but is very close. The docs didn't indicate that you could use a palette other than the specified ones on the material design site, which is where these come from.
</blockquote></details>

I'm not finding the green color close enough but that doesn't have to hold this up. If you are not going to fix it here, please create and publish another issue to sort out Material colors. Make it priority major.
___
*[src/SIL.XForge.Scripture/ClientApp/src/app/connect-project/connect-project.component.ts, line 190 at r2](https://reviewable.io/reviews/sillsdev/web-xforge/923#-MRYDPXO5mDgii5dBka9:-MRYDPXO5mDgii5dBkaA:b5566x6) ([raw file](https://github.com/sillsdev/web-xforge/blob/78bb1b63b0c1fe07f0dcb8ccc6a4c66aa5de0779/src/SIL.XForge.Scripture/ClientApp/src/app/connect-project/connect-project.component.ts#L190)):*
> ```
> this.state = 'connecting';
> ```
I'm not understanding why this needed to move further down in the logic. Can you explain?
___
*[src/SIL.XForge.Scripture/ClientApp/src/app/sync/sync.component.ts, line 19 at r2](https://reviewable.io/reviews/sillsdev/web-xforge/923#-MRY7ZK01Z0EElzlUntE:-MRY7ZK1220pfHTaB-VU:bewjzyl) ([raw file](https://github.com/sillsdev/web-xforge/blob/78bb1b63b0c1fe07f0dcb8ccc6a4c66aa5de0779/src/SIL.XForge.Scripture/ClientApp/src/app/sync/sync.component.ts#L19)):*
> ```
> OnDestroy
> ```
This should be removed now that it is no longer used.
___
*[src/SIL.XForge.Scripture/ClientApp/src/app/sync/sync.component.ts, line 78 at r2](https://reviewable.io/reviews/sillsdev/web-xforge/923#-MRY9xUhCtrZNlQkwAeW:-MRY9xUi44FWR_KYqduq:b7mz0fo) ([raw file](https://github.com/sillsdev/web-xforge/blob/78bb1b63b0c1fe07f0dcb8ccc6a4c66aa5de0779/src/SIL.XForge.Scripture/ClientApp/src/app/sync/sync.component.ts#L78)):*
> ```
> if (this.projectDoc?.data != null && this.projectDoc.data.sync.lastSyncSuccessful) {
> ```
This can be simplified to `if (this.projectDoc?.data?.sync.lastSyncSuccessful) {`.
___
*[src/SIL.XForge.Scripture/ClientApp/src/app/sync/sync.component.ts, line 82 at r2](https://reviewable.io/reviews/sillsdev/web-xforge/923#-MRYAPCE1lFCEnGbWU49:-MRYAPCE1lFCEnGbWU4A:b6qr2oo) ([raw file](https://github.com/sillsdev/web-xforge/blob/78bb1b63b0c1fe07f0dcb8ccc6a4c66aa5de0779/src/SIL.XForge.Scripture/ClientApp/src/app/sync/sync.component.ts#L82)):*
> ```
> this.projectDoc?.data != null
> ```
This can be checked in the very first `if` so it wouldn't be needed here or in the second `if`.
___
*[src/SIL.XForge.Scripture/ClientApp/src/app/sync/sync.component.ts, line 144 at r2](https://reviewable.io/reviews/sillsdev/web-xforge/923#-MRY7oeaCKQJxbSIuZRz:-MRY7oeaCKQJxbSIuZS-:b8u29ul) ([raw file](https://github.com/sillsdev/web-xforge/blob/78bb1b63b0c1fe07f0dcb8ccc6a4c66aa5de0779/src/SIL.XForge.Scripture/ClientApp/src/app/sync/sync.component.ts#L144)):*
> ```
>  if (this.projectDoc?.data != null) {
> ```
nit: the usual pattern for methods is check anomalies first and exit. This pattern means the normal code below is not indented inside an `if`. It also means if after some normal code you have to check further anomalies you also don't have to indent the following normal code again. This makes normal code flow easier to read. In many methods the further indent is not needed anyway but we still follow the pattern. I don't see a good reason to change away from that pattern here.
___
*[src/SIL.XForge.Scripture/ClientApp/src/app/sync/sync.component.spec.ts, line 93 at r2](https://reviewable.io/reviews/sillsdev/web-xforge/923#-MRYCZVk8GqB_SPZVFUT:-MRYCZVk8GqB_SPZVFUU:b-a3ryxx) ([raw file](https://github.com/sillsdev/web-xforge/blob/d6b0c663d32e4938e9addffdb0d50b658dbcabb1/src/SIL.XForge.Scripture/ClientApp/src/app/sync/sync.component.spec.ts#L93)):*
> ```
>     expect(env.syncMessage.textContent).toContain('Your project is being synchronized');
>     expect(env.logInButton).toBeNull();
>     expect(env.syncButton).toBeNull();
> ```
These look like checks that should remain?
___
*[src/SIL.XForge.Scripture/ClientApp/src/app/sync/sync-progress/sync-progress.component.ts, line 39 at r2](https://reviewable.io/reviews/sillsdev/web-xforge/923#-MRY4Yoj7BbbdD_eh1iQ:-MRY4Yoj7BbbdD_eh1iR:boywyh9) ([raw file](https://github.com/sillsdev/web-xforge/blob/78bb1b63b0c1fe07f0dcb8ccc6a4c66aa5de0779/src/SIL.XForge.Scripture/ClientApp/src/app/sync/sync-progress/sync-progress.component.ts#L39)):*
> ```
> isProgressDeterminate
> ```
This probably needs a better name. Anything starting with `is` I expect to be boolean. It's certainly hard to read in the tests. Maybe `progressBarMode` or just `mode`?
___
*[src/SIL.XForge.Scripture/ClientApp/src/app/sync/sync-progress/sync-progress.component.ts, line 41 at r2](https://reviewable.io/reviews/sillsdev/web-xforge/923#-MRXwheX2R0kumnX8sWf:-MRXwheX2R0kumnX8sWg:b-20dvl0) ([raw file](https://github.com/sillsdev/web-xforge/blob/78bb1b63b0c1fe07f0dcb8ccc6a4c66aa5de0779/src/SIL.XForge.Scripture/ClientApp/src/app/sync/sync-progress/sync-progress.component.ts#L41)):*
> ```
> const sourceSyncCompleted = this.sourceProjectDoc?.data != null && this.sourceProjectDoc.data.sync.queuedCount < 1;
> ```
I think this can be simplified to `const sourceSyncCompleted = this.sourceProjectDoc?.data.sync.queuedCount < 1;`?
___
*[src/SIL.XForge.Scripture/ClientApp/src/app/sync/sync-progress/sync-progress.component.spec.ts, line 15 at r2](https://reviewable.io/reviews/sillsdev/web-xforge/923#-MRXyDml3CQKM-drots3:-MRXyDml3CQKM-drots4:b-9a6l3e) ([raw file](https://github.com/sillsdev/web-xforge/blob/78bb1b63b0c1fe07f0dcb8ccc6a4c66aa5de0779/src/SIL.XForge.Scripture/ClientApp/src/app/sync/sync-progress/sync-progress.component.spec.ts#L15)):*
> ```XML
> import { SF_TYPE_REGISTRY } from '../../core/models/sf-type-registry';
> import { SFProjectService } from '../../core/sf-project.service';
> ```

nit: This blank line should be removed.

**Review by RaymondLuong3 — COMMENTED** [review]
Yea, it was a significant amount of work, but in the end I think it's worth it.

> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/923#-:-MR_twy72RPRnHHgOwcn:b-vkb15p)* status: all files reviewed, 9 unresolved discussions (waiting on @irahopkinson)

___
*[src/SIL.XForge.Scripture/ClientApp/angular.json, line 41 at r2](https://reviewable.io/reviews/sillsdev/web-xforge/923#-MRXlCY85CNziBWlfnau:-MR_u8Uz1h0N2iEVA5T9:b-896fix) ([raw file](https://github.com/sillsdev/web-xforge/blob/78bb1b63b0c1fe07f0dcb8ccc6a4c66aa5de0779/src/SIL.XForge.Scripture/ClientApp/angular.json#L41)):*
<details><summary><i>Previously, irahopkinson (Ira Hopkinson) wrote…</i></summary><blockquote>

This needs to be added to the test build config below also.
</blockquote></details>

Done.
___
*[src/SIL.XForge.Scripture/ClientApp/src/material-styles.scss, line 6 at r2](https://reviewable.io/reviews/sillsdev/web-xforge/923#-MRWaq_TDMQKCwWJiuxI:-MR_uDVf2GA28lV-4MDs:bygcwma) ([raw file](https://github.com/sillsdev/web-xforge/blob/78bb1b63b0c1fe07f0dcb8ccc6a4c66aa5de0779/src/SIL.XForge.Scripture/ClientApp/src/material-styles.scss#L6)):*
<details><summary><i>Previously, irahopkinson (Ira Hopkinson) wrote…</i></summary><blockquote>

I'm not finding the green color close enough but that doesn't have to hold this up. If you are not going to fix it here, please create and publish another issue to sort out Material colors. Make it priority major.
</blockquote></details>

Ok, I'll open up another card since it will require more reading of docs to get it right.
___
*[src/SIL.XForge.Scripture/ClientApp/src/app/connect-project/connect-project.component.ts, line 190 at r2](https://reviewable.io/reviews/sillsdev/web-xforge/923#-MRYDPXO5mDgii5dBka9:-MR_uglV1xmE9fl4w4HV:b-l84rdx) ([raw file](https://github.com/sillsdev/web-xforge/blob/78bb1b63b0c1fe07f0dcb8ccc6a4c66aa5de0779/src/SIL.XForge.Scripture/ClientApp/src/app/connect-project/connect-project.component.ts#L190)):*
<details><summary><i>Previously, irahopkinson (Ira Hopkinson) wrote…</i></summary><blockquote>

> ```
> this.state = 'connecting';
> ```
I'm not understanding why this needed to move further down in the logic. Can you explain?
</blockquote></details>

In order for the sync-progress component to work properly it needs a `projectDoc` so moving `this.state = connecting` down ensures that we have a projectDoc when the `sync-progress` component gets initialized.
___
*[src/SIL.XForge.Scripture/ClientApp/src/app/sync/sync.component.ts, line 19 at r2](https://reviewable.io/reviews/sillsdev/web-xforge/923#-MRY7ZK01Z0EElzlUntE:-MR_vPnuDXSCcshctc58:b-896fix) ([raw file](https://github.com/sillsdev/web-xforge/blob/78bb1b63b0c1fe07f0dcb8ccc6a4c66aa5de0779/src/SIL.XForge.Scripture/ClientApp/src/app/sync/sync.component.ts#L19)):*
<details><summary><i>Previously, irahopkinson (Ira Hopkinson) wrote…</i></summary><blockquote>

> ```
> OnDestroy
> ```
This should be removed now that it is no longer used.
</blockquote></details>

Done.
___
*[src/SIL.XForge.Scripture/ClientApp/src/app/sync/sync.component.ts, line 78 at r2](https://reviewable.io/reviews/sillsdev/web-xforge/923#-MRY9xUhCtrZNlQkwAeW:-MR_vSszALmAfcWRc3tU:b-896fix) ([raw file](https://github.com/sillsdev/web-xforge/blob/78bb1b63b0c1fe07f0dcb8ccc6a4c66aa5de0779/src/SIL.XForge.Scripture/ClientApp/src/app/sync/sync.component.ts#L78)):*
<details><summary><i>Previously, irahopkinson (Ira Hopkinson) wrote…</i></summary><blockquote>

> ```
> if (this.projectDoc?.data != null && this.projectDoc.data.sync.lastSyncSuccessful) {
> ```
This can be simplified to `if (this.projectDoc?.data?.sync.lastSyncSuccessful) {`.
</blockquote></details>

Done.
___
*[src/SIL.XForge.Scripture/ClientApp/src/app/sync/sync.component.ts, line 82 at r2](https://reviewable.io/reviews/sillsdev/web-xforge/923#-MRYAPCE1lFCEnGbWU49:-MR_vTtW7tcs-RXsp9_J:b-896fix) ([raw file](https://github.com/sillsdev/web-xforge/blob/78bb1b63b0c1fe07f0dcb8ccc6a4c66aa5de0779/src/SIL.XForge.Scripture/ClientApp/src/app/sync/sync.component.ts#L82)):*
<details><summary><i>Previously, irahopkinson (Ira Hopkinson) wrote…</i></summary><blockquote>

> ```
> this.projectDoc?.data != null
> ```
This can be checked in the very first `if` so it wouldn't be needed here or in the second `if`.
</blockquote></details>

Done.
___
*[src/SIL.XForge.Scripture/ClientApp/src/app/sync/sync.component.ts, line 144 at r2](https://reviewable.io/reviews/sillsdev/web-xforge/923#-MRY7oeaCKQJxbSIuZRz:-MR_vUp39yJwlJwE3RgZ:b-5einqz) ([raw file](https://github.com/sillsdev/web-xforge/blob/78bb1b63b0c1fe07f0dcb8ccc6a4c66aa5de0779/src/SIL.XForge.Scripture/ClientApp/src/app/sync/sync.component.ts#L144)):*
<details><summary><i>Previously, irahopkinson (Ira Hopkinson) wrote…</i></summary><blockquote>

> ```
>  if (this.projectDoc?.data != null) {
> ```
nit: the usual pattern for methods is check anomalies first and exit. This pattern means the normal code below is not indented inside an `if`. It also means if after some normal code you have to check further anomalies you also don't have to indent the following normal code again. This makes normal code flow easier to read. In many methods the further indent is not needed anyway but we still follow the pattern. I don't see a good reason to change away from that pattern here.
</blockquote></details>

Sometimes I just need a reminder. I completely agree that it makes the code just a bit cleaner.
___
*[src/SIL.XForge.Scripture/ClientApp/src/app/sync/sync.component.spec.ts, line 93 at r2](https://reviewable.io/reviews/sillsdev/web-xforge/923#-MRYCZVk8GqB_SPZVFUT:-MR_w1vi9v-IvhYO58Cn:bop3tgc) ([raw file](https://github.com/sillsdev/web-xforge/blob/d6b0c663d32e4938e9addffdb0d50b658dbcabb1/src/SIL.XForge.Scripture/ClientApp/src/app/sync/sync.component.spec.ts#L93)):*
<details><summary><i>Previously, irahopkinson (Ira Hopkinson) wrote…</i></summary><blockquote>

> ```
>     expect(env.syncMessage.textContent).toContain('Your project is being synchronized');
>     expect(env.logInButton).toBeNull();
>     expect(env.syncButton).toBeNull();
> ```
These look like checks that should remain?
</blockquote></details>

Done. I was too fast in my deleting.
___
*[src/SIL.XForge.Scripture/ClientApp/src/app/sync/sync-progress/sync-progress.component.ts, line 39 at r2](https://reviewable.io/reviews/sillsdev/web-xforge/923#-MRY4Yoj7BbbdD_eh1iQ:-MR_w3_LCh1HzuPEwDL1:b-896fix) ([raw file](https://github.com/sillsdev/web-xforge/blob/78bb1b63b0c1fe07f0dcb8ccc6a4c66aa5de0779/src/SIL.XForge.Scripture/ClientApp/src/app/sync/sync-progress/sync-progress.component.ts#L39)):*
<details><summary><i>Previously, irahopkinson (Ira Hopkinson) wrote…</i></summary><blockquote>

> ```
> isProgressDeterminate
> ```
This probably needs a better name. Anything starting with `is` I expect to be boolean. It's certainly hard to read in the tests. Maybe `progressBarMode` or just `mode`?
</blockquote></details>

Done.
___
*[src/SIL.XForge.Scripture/ClientApp/src/app/sync/sync-progress/sync-progress.component.ts, line 41 at r2](https://reviewable.io/reviews/sillsdev/web-xforge/923#-MRXwheX2R0kumnX8sWf:-MR_w43n0x7ZTMfTn-Ck:b-jwz0sw) ([raw file](https://github.com/sillsdev/web-xforge/blob/78bb1b63b0c1fe07f0dcb8ccc6a4c66aa5de0779/src/SIL.XForge.Scripture/ClientApp/src/app/sync/sync-progress/sync-progress.component.ts#L41)):*
<details><summary><i>Previously, irahopkinson (Ira Hopkinson) wrote…</i></summary><blockquote>

> ```
> const sourceSyncCompleted = this.sourceProjectDoc?.data != null && this.sourceProjectDoc.data.sync.queuedCount < 1;
> ```
I think this can be simplified to `const sourceSyncCompleted = this.sourceProjectDoc?.data.sync.queuedCount < 1;`?
</blockquote></details>

Unfortunately that gives an error saying that null cannot be compared to a number.

**Review by irahopkinson — DISMISSED** [review]
Definitely worth it. This is good to go once the theme issue is created and published.

> Reviewed 6 of 6 files at r3.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/923#-:-MRhJIjP3E1dy2QbjBTh:b1l6wv4)* status: all files reviewed, 1 unresolved discussion (waiting on @RaymondLuong3)

___
*[src/SIL.XForge.Scripture/ClientApp/src/material-styles.scss, line 6 at r2](https://reviewable.io/reviews/sillsdev/web-xforge/923#-MRWaq_TDMQKCwWJiuxI:-MRhJwP9C054CFjGj1pj:b-806gq8) ([raw file](https://github.com/sillsdev/web-xforge/blob/78bb1b63b0c1fe07f0dcb8ccc6a4c66aa5de0779/src/SIL.XForge.Scripture/ClientApp/src/material-styles.scss#L6)):*
<details><summary><i>Previously, RaymondLuong3 (Raymond Luong) wrote…</i></summary><blockquote>

Ok, I'll open up another card since it will require more reading of docs to get it right.
</blockquote></details>

Still waiting for this issue...

**Review by RaymondLuong3 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/923)* status: all files reviewed, 1 unresolved discussion (waiting on @irahopkinson)

___
*[src/SIL.XForge.Scripture/ClientApp/src/material-styles.scss, line 6 at r2](https://reviewable.io/reviews/sillsdev/web-xforge/923#-MRWaq_TDMQKCwWJiuxI:-MRuFV1o8lF3N4G_iH2Z:by2v8ve) ([raw file](https://github.com/sillsdev/web-xforge/blob/78bb1b63b0c1fe07f0dcb8ccc6a4c66aa5de0779/src/SIL.XForge.Scripture/ClientApp/src/material-styles.scss#L6)):*
<details><summary><i>Previously, irahopkinson (Ira Hopkinson) wrote…</i></summary><blockquote>

Still waiting for this issue...
</blockquote></details>

Opened SF-1184.

**Review by Nateowami — APPROVED** [review]
:lgtm:

> Reviewed 9 of 15 files at r2, 6 of 6 files at r3.
> Dismissed @irahopkinson from a discussion.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/923#-:-MRunyN6B-wZ_C2bT0HC:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
