### PR TITLE
SF-2818 Move instructions out of placeholder for open resource tab

### PR DESCRIPTION
**Pull request by marksvc**
The lengthy placeholder text was getting cut off on mobile viewports.
This moves the instructive placeholder text above the input box, and
uses a smaller placeholder text.

A Storybook has been introduced for the dialog as it has a number of
states and messages.

------

I tried a couple things, and considered how to re-use `createTestParatextProject()` from editor-tab-add-resource-dialog.component.spec.ts. In the end I chose to duplicate it into editor-tab-add-resource-dialog.stories.ts, with a code comment referencing the other location. I can pursue an alternate approach if desired. 

Here is a screenshot from Storybook of the dialog on a small phone. The "Select a Paratext project or DBL resource." text was adjusted slightly and moved out of the placeholder area to be shown above the input box. The input box now has a new, small placeholder saying "Project or resource". I chose not to use hint text as a number of other (error) messages are already displayed below the input box.

image

You might notice in other Storybook stories that the (existing) error messages below the input box have their first line indented. I fiddled with this but did not quickly find a pleasant way to alleviate this.

- - -
This change is [Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/2806)

### CODE REVIEW

**Review by RaymondLuong3 — CHANGES_REQUESTED** [review]
Nice work. I have some minor suggestions, but other than that, it looks to be a good solution.

> Reviewed 4 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/2806#-:-O9GMgSACjphjvJ5X08O:b-hku6c5)* status: all files reviewed, 3 unresolved discussions (waiting on @marksvc)

___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/tabs/editor-tab-add-resource-dialog/editor-tab-add-resource-dialog.component.scss` line 27 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/2806#-O9GKcoh6YVA_uYIf3pZ:-O9GKcoh6YVA_uYIf3p_:boyscug) ([raw file](https://github.com/sillsdev/web-xforge/blob/f7651029c425502b646f3bb99e5dd214c232cfa7/src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/tabs/editor-tab-add-resource-dialog/editor-tab-add-resource-dialog.component.scss#L27)):*
> ```SCSS
> .instruction {
>   margin-bottom: 1em;
> }
> ```

Instead of adding margin to a specific element, it is better to make the parent element a flex container and give a standard gap between child elements.



_Code quote:_
```SCSS
.instruction {
  margin-bottom: 1em;
}
```
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/tabs/editor-tab-add-resource-dialog/editor-tab-add-resource-dialog.stories.ts` line 13 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/2806#-O9GL0t96x1mKvzRtdgn:-O9GL0t96x1mKvzRtdgo:b-3rqzf7) ([raw file](https://github.com/sillsdev/web-xforge/blob/f7651029c425502b646f3bb99e5dd214c232cfa7/src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/tabs/editor-tab-add-resource-dialog/editor-tab-add-resource-dialog.stories.ts#L13)):*
> ```XML
> import { I18nStoryModule } from '../../../../../xforge-common/i18n-story.module';
> import { OnlineStatusService } from '../../../../../xforge-common/online-status.service';
> import { XForgeCommonModule } from '../../../../../xforge-common/xforge-common.module';
> ```

You can use absolute paths for this.



_Code quote:_
```XML
import { I18nStoryModule } from '../../../../../xforge-common/i18n-story.module';
import { OnlineStatusService } from '../../../../../xforge-common/online-status.service';
import { XForgeCommonModule } from '../../../../../xforge-common/xforge-common.module';
```
___
*[`src/SIL.XForge.Scripture/ClientApp/src/assets/i18n/non_checking_en.json` line 507 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/2806#-O9GMX59C35GHKaABfsY:-O9GMX59C35GHKaABfsZ:b6csvic) ([raw file](https://github.com/sillsdev/web-xforge/blob/f7651029c425502b646f3bb99e5dd214c232cfa7/src/SIL.XForge.Scripture/ClientApp/src/assets/i18n/non_checking_en.json#L507)):*
> ```JSON
>     "loading": "Loading",
>     "placeholder_loading": "{{ editor_add_tab_resource_dialog.loading }}...",
>     "placeholder_ready": "Select a Paratext project or DBL resource.",
> ```

We should probably remove the "placeholder" part from the key.



_Code quote:_
```JSON
    "placeholder_ready": "Select a Paratext project or DBL resource.",
```

**Review by marksvc — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/2806)* status: all files reviewed, 3 unresolved discussions (waiting on @RaymondLuong3)

___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/tabs/editor-tab-add-resource-dialog/editor-tab-add-resource-dialog.component.scss` line 27 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/2806#-O9GKcoh6YVA_uYIf3pZ:-O9HBMX70LE0_XRx5Iee:be7qhbd) ([raw file](https://github.com/sillsdev/web-xforge/blob/f7651029c425502b646f3bb99e5dd214c232cfa7/src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/tabs/editor-tab-add-resource-dialog/editor-tab-add-resource-dialog.component.scss#L27)):*
<details><summary><i>Previously, RaymondLuong3 (Raymond Luong) wrote…</i></summary><blockquote>

Instead of adding margin to a specific element, it is better to make the parent element a flex container and give a standard gap between child elements.
</blockquote></details>

Thank you! Done.
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/tabs/editor-tab-add-resource-dialog/editor-tab-add-resource-dialog.stories.ts` line 13 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/2806#-O9GL0t96x1mKvzRtdgn:-O9HC80JAq9BHkE6mdCg:b-896fix) ([raw file](https://github.com/sillsdev/web-xforge/blob/f7651029c425502b646f3bb99e5dd214c232cfa7/src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/tabs/editor-tab-add-resource-dialog/editor-tab-add-resource-dialog.stories.ts#L13)):*
<details><summary><i>Previously, RaymondLuong3 (Raymond Luong) wrote…</i></summary><blockquote>

You can use absolute paths for this.
</blockquote></details>

Done.
___
*[`src/SIL.XForge.Scripture/ClientApp/src/assets/i18n/non_checking_en.json` line 507 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/2806#-O9GMX59C35GHKaABfsY:-O9HCatrE3FWJRbwqHoZ:bmg28hl) ([raw file](https://github.com/sillsdev/web-xforge/blob/f7651029c425502b646f3bb99e5dd214c232cfa7/src/SIL.XForge.Scripture/ClientApp/src/assets/i18n/non_checking_en.json#L507)):*
<details><summary><i>Previously, RaymondLuong3 (Raymond Luong) wrote…</i></summary><blockquote>

We should probably remove the "placeholder" part from the key.
</blockquote></details>

How about this?

**Comment by marksvc** [comment]
Updated screenshot:

image

**Review by RaymondLuong3 — APPROVED** [review]
:lgtm: 

> Reviewed 4 of 4 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/2806#-:-O9HO6NH5s_idpNLEL3M:bg7igkv)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @marksvc)

**Comment by Nateowami** [comment]
As a general rule, it should always be possible to tell what a form field is for without the placeholder, because the placeholder disappears after there is input. That's less of an issues for a form with one field, but still not great. In the worst cases, I've had to fill out form fields where there is no indication at all for what each field is after it has input. It's not a good experience.

**Pull request merged**
