### PR TITLE
SF-1175b Allow manual selection in project select

### PR DESCRIPTION
**Pull request by RaymondLuong3**
* the project input is valid if the name is that of a selectable project
* also disable component when parent element is offline

---
This change is [Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/929)

### CODE REVIEW

**Review by irahopkinson — COMMENTED** [review]
Thanks for this - nice improvement. My only comment is non-blocking because I don't understand and so you can merge yourself if you are confident with your answer.

> Reviewed 3 of 3 files at r1.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/929#-:-MRdJT4X-L8qHtQerKoM:bu8ly3k)* status: all files reviewed, 1 unresolved discussion (waiting on @RaymondLuong3)

___
*[src/SIL.XForge.Scripture/ClientApp/src/app/project-select/project-select.component.ts, line 67 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/929#-MRdJDKn0UF_8hWztX3c:-MRdJDKn0UF_8hWztX3d:be9nn9i) ([raw file](https://github.com/sillsdev/web-xforge/blob/32f614b73d64a00de036ba085bc9d443b06f1847/src/SIL.XForge.Scripture/ClientApp/src/app/project-select/project-select.component.ts#L67)):*
> ```
> p[0].name.toLowerCase() === this.paratextIdControl.value.toLocaleLowerCase()
> ```
Can you explain why we are comparing with 2 different lower case methods?

**Review by Nateowami — COMMENTED** [review]
Just one question, then :lgtm:

> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/929#-:-MRgNsn18YEUrWLNfpTX:btsrg7g)* status: all files reviewed, 2 unresolved discussions (waiting on @RaymondLuong3)

___
*[src/SIL.XForge.Scripture/ClientApp/src/app/project-select/project-select.component.ts, line 99 at r2](https://reviewable.io/reviews/sillsdev/web-xforge/929#-MRgLofT8kclOOfKmhyW:-MRgLofT8kclOOfKmhyX:bsug1ot) ([raw file](https://github.com/sillsdev/web-xforge/blob/74929e8720891866737a36d021949a4e8a6e6b1e/src/SIL.XForge.Scripture/ClientApp/src/app/project-select/project-select.component.ts#L99)):*
> ```XML
>     if (value) {
>       this.paratextIdControl.disable();
>     } else if (this.paratextIdControl.disabled) {
> ```

What's the purpose of this change? If the idea is that we shouldn't call `enable()` unless it's disabled, I would think we also shouldn't call `disable()` unless it's enabled.

**Review by RaymondLuong3 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/929)* status: 2 of 3 files reviewed, 2 unresolved discussions (waiting on @irahopkinson and @Nateowami)

___
*[src/SIL.XForge.Scripture/ClientApp/src/app/project-select/project-select.component.ts, line 67 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/929#-MRdJDKn0UF_8hWztX3c:-MRgUlsMCsCJhryEdZCB:bygmw0f) ([raw file](https://github.com/sillsdev/web-xforge/blob/32f614b73d64a00de036ba085bc9d443b06f1847/src/SIL.XForge.Scripture/ClientApp/src/app/project-select/project-select.component.ts#L67)):*
<details><summary><i>Previously, irahopkinson (Ira Hopkinson) wrote…</i></summary><blockquote>

> ```
> p[0].name.toLowerCase() === this.paratextIdControl.value.toLocaleLowerCase()
> ```
Can you explain why we are comparing with 2 different lower case methods?
</blockquote></details>

Good question. I was copying the use case in `filterGroups` which turned out to be an oversight.
___
*[src/SIL.XForge.Scripture/ClientApp/src/app/project-select/project-select.component.ts, line 99 at r2](https://reviewable.io/reviews/sillsdev/web-xforge/929#-MRgLofT8kclOOfKmhyW:-MRgUzhuEqQ08MPGhCir:b73j5b8) ([raw file](https://github.com/sillsdev/web-xforge/blob/74929e8720891866737a36d021949a4e8a6e6b1e/src/SIL.XForge.Scripture/ClientApp/src/app/project-select/project-select.component.ts#L99)):*
<details><summary><i>Previously, Nateowami (Nathaniel Paulus) wrote…</i></summary><blockquote>

What's the purpose of this change? If the idea is that we shouldn't call `enable()` unless it's disabled, I would think we also shouldn't call `disable()` unless it's enabled.
</blockquote></details>

Yes, I agree. I left a comment so that you can grieve with me when I found out the reason this is needed.

**Review by Nateowami — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/929#-:-MRh24a_6Yga3c7qr9sF:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved

___
*[src/SIL.XForge.Scripture/ClientApp/src/app/project-select/project-select.component.ts, line 99 at r2](https://reviewable.io/reviews/sillsdev/web-xforge/929#-MRgLofT8kclOOfKmhyW:-MRh-xClAkjvgYIV_23N:b-a51jpq) ([raw file](https://github.com/sillsdev/web-xforge/blob/74929e8720891866737a36d021949a4e8a6e6b1e/src/SIL.XForge.Scripture/ClientApp/src/app/project-select/project-select.component.ts#L99)):*
<details><summary><i>Previously, RaymondLuong3 (Raymond Luong) wrote…</i></summary><blockquote>

Yes, I agree. I left a comment so that you can grieve with me when I found out the reason this is needed.
</blockquote></details>

Could it be moved up one line? There doesn't seem like a good place to put it, but I think it's less likely to get accidentally separated from the line it pertains to.

**Review by irahopkinson — APPROVED** [review]
> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/929)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @RaymondLuong3)

**Pull request merged**
