### PR TITLE
Update translate link to "Edit & review"

### PR DESCRIPTION
**Pull request by Nateowami**
There are definitely arguments for "translate" over "edit", but there doesn't seem to be a clear consensus, except that both "edit" and "translate" are preferable to "draft", and the changing of the icon.

Here's how it looks now:

- - -
This change is [Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/2233)

### CODE REVIEW

**Review by Nateowami — COMMENTED** [review]
Good catch. Done.

> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/2233#-:-NlTrwV0CFtaCVZayV1J:boj1qgt)* status: 2 of 5 files reviewed, all discussions resolved (waiting on @pmachapman)

**Review by pmachapman — APPROVED** [review]
:lgtm:

> Reviewed 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/2233#-:-NlTtIKI0DWNaBobQOZw:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @Nateowami)

**Comment by pmachapman** [comment]
@Nateowami Actually - one query before merging. The pencil is flipped in Arabic. Is that OK?

**Review by Nateowami — COMMENTED** [review]
Good catch once again. I thought I already fixed that, but that's because I'd already done this change on a different branch.

The pencil should not be flipped, though ideally it would be shown on the left instead of the right. Not a trivial change though, so better to just not flip the icon.

> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/2233#-:-NlTyT1qCMmwXBOnczF9:b15xwez)* status: 4 of 5 files reviewed, all discussions resolved (waiting on @pmachapman)

**Review by pmachapman — APPROVED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/2233)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @Nateowami)

**Review by pmachapman — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/2233)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @Nateowami)

**Pull request merged**
