### PR TITLE
SF-2322 Display copyright banner for translations that request it

### PR DESCRIPTION
**Pull request by pmachapman**
Some translations specifically request that a copyright banner is displayed above the text in Paratext.

This PR updates Scripture Forge so that translations that request a copyright notice to be displayed have the copyright notice of their specification displayed. Because this message is stored in the Project's Settings, it is not localized.

- - -
This change is [Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/2161)

### CODE REVIEW

**Review by RaymondLuong3 — CHANGES_REQUESTED** [review]
This is good. Someone mentioned during my webinar that the ESV had copyright limitations, so I'm glad to see this notice being introduced to keep us from getting into trouble.

> Reviewed 12 of 12 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/2161#-:-NiaAEFW6BBXYoVQxgnf:b-lku8p7)* status: all files reviewed, 3 unresolved discussions (waiting on @pmachapman)

___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.html` line 98 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/2161#-Nia9lDJBF2SKKy43-o_:-Nia9lDJBF2SKKy43-oa:b-jeuf4q) ([raw file](https://github.com/sillsdev/web-xforge/blob/b52d7eb690393cc90b759c0958674fa3a8c235b6/src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.html#L98)):*
> ```HTML
>         <div *ngIf="!isUsfmValid && hasEditRight" class="formatting-invalid-warning">
>           <mat-icon>warning</mat-icon> {{ t("cannot_edit_chapter_formatting_invalid") }}
>         </div>
> ```

Hmm, I had some fun with this and used our notice component. How does this look? 




_Code snippet:_
```HTML
        <app-notice *ngIf="hasSourceCopyrightBanner" icon="copyright" type="warning" outline="true">
          <div>
            {{ sourceCopyrightBanner }}
            <span class="copyright-more-info" (click)="showCopyrightNotice('source')">{{ t("more_info") }}</span>
          </div>
        </app-notice>
```
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.scss` line 138 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/2161#-NiaA6EQDqvlXhpjpWCd:-NiaA6EQDqvlXhpjpWCe:b-ycq02r) ([raw file](https://github.com/sillsdev/web-xforge/blob/b52d7eb690393cc90b759c0958674fa3a8c235b6/src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.scss#L138)):*
> ```SCSS
> }
> 
> .copyright-more-info:hover {
> ```

You can actually combine this into the style above.



_Code snippet:_
```SCSS
.copyright-more-info {
  cursor: pointer;
  font-weight: bold;
  &:hover {
    text-decoration: underline;
  }
}
```
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.ts` line 1092 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/2161#-Nia2c_WDQ5CqW7g79bt:-Nia2c_WDQ5CqW7g79bu:b-fmm3et) ([raw file](https://github.com/sillsdev/web-xforge/blob/b52d7eb690393cc90b759c0958674fa3a8c235b6/src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.ts#L1092)):*
> ```XML
> 
>   showCopyrightNotice(textType: TextType): void {
>     let copyrightNotice =
> ```

Add a type here.

**Review by pmachapman — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/2161)* status: 8 of 12 files reviewed, 3 unresolved discussions (waiting on @RaymondLuong3)

___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.html` line 98 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/2161#-Nia9lDJBF2SKKy43-o_:-NiawhH80z7nzNRDspRm:bt66a4t) ([raw file](https://github.com/sillsdev/web-xforge/blob/b52d7eb690393cc90b759c0958674fa3a8c235b6/src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.html#L98)):*
<details><summary><i>Previously, RaymondLuong3 (Raymond Luong) wrote…</i></summary><blockquote>

Hmm, I had some fun with this and used our notice component. How does this look? 

</blockquote></details>

Done. Thank you! That looks a lot better!
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.scss` line 138 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/2161#-NiaA6EQDqvlXhpjpWCd:-NiaHSBpDIH-8T8k_zwz:b-896fix) ([raw file](https://github.com/sillsdev/web-xforge/blob/b52d7eb690393cc90b759c0958674fa3a8c235b6/src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.scss#L138)):*
<details><summary><i>Previously, RaymondLuong3 (Raymond Luong) wrote…</i></summary><blockquote>

You can actually combine this into the style above.
</blockquote></details>

Done.
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.ts` line 1092 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/2161#-Nia2c_WDQ5CqW7g79bt:-Niaq9JUES1WQ97E1Nr6:b-896fix) ([raw file](https://github.com/sillsdev/web-xforge/blob/b52d7eb690393cc90b759c0958674fa3a8c235b6/src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.ts#L1092)):*
<details><summary><i>Previously, RaymondLuong3 (Raymond Luong) wrote…</i></summary><blockquote>

Add a type here.
</blockquote></details>

Done.

**Review by RaymondLuong3 — COMMENTED** [review]
> Reviewed 4 of 4 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/2161)* status: all files reviewed, 2 unresolved discussions (waiting on @pmachapman)

**Review by RaymondLuong3 — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/2161)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @pmachapman)

**Pull request merged**
