### PR TITLE
SF-2443 Apply draft in editor draft tab

### PR DESCRIPTION
**Pull request by siltomato**
Rebase included removal of 'sendAllSegments', which was being checked to determine if 'legacy' draft fetch should be used.

- - -
This change is [Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/2452)

### CODE REVIEW

**Review by pmachapman — APPROVED** [review]
:lgtm: Just a couple of nits.

I will approve in case we want to merge this ASAP, and we can always deal with the nits later (they do not affect functionality)..

> Reviewed 18 of 18 files at r1.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/2452#-:-Nxnl2EUB-gMJHAk-I6r:bvx5n38)* status: 16 of 18 files reviewed, 3 unresolved discussions (waiting on @Nateowami and @siltomato)

___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-viewer/draft-viewer.service.ts` line 4 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/2452#-NxnjGSz82u4rpwOOoJK:-NxnjGSz82u4rpwOOoJL:bb3xfak) ([raw file](https://github.com/sillsdev/web-xforge/blob/6dcc6c4cb652417fc2eed08df139d0970e8c5ffe/src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-viewer/draft-viewer.service.ts#L4)):*
> ```XML
> import { VerseRef } from '@sillsdev/scripture';
> import { DeltaOperation, DeltaStatic } from 'quill';
> import { TextDocId } from 'src/app/core/models/text-doc';
> ```

NIT: This should be a relative path.



_Code quote:_
```XML
import { TextDocId } from 'src/app/core/models/text-doc';
```
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.ts` line 227 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/2452#-Nxnj9jmDzvm63o3lPL5:-Nxnj9jmDzvm63o3lPL6:b-sk9r2d) ([raw file](https://github.com/sillsdev/web-xforge/blob/082c2c9d8679f0cbbdb7956ac282380c75889805/src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.ts#L227)):*
> ```XML
>   private trainingSub?: Subscription;
>   private projectDataChangesSub?: Subscription;
>   private clickSubs: Map<string, Subscription[]> = new Map<string, Subscription[]>();
> ```

NIT: We can remove the feature flag service from the component and the spec file.



_Code quote:_
```XML
readonly featureFlags: FeatureFlagService,
```
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor-draft/editor-draft.component.ts` line 28 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/2452#-Nxnjk-c59MqXPix1fEM:-Nxnjk-c59MqXPix1fEN:bbjl80d) ([raw file](https://github.com/sillsdev/web-xforge/blob/6dcc6c4cb652417fc2eed08df139d0970e8c5ffe/src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor-draft/editor-draft.component.ts#L28)):*
> ```XML
> } from 'rxjs';
> import { SFProjectService } from 'src/app/core/sf-project.service';
> import { isString } from 'src/type-utils';
> ```

NIT: These should be relative paths.



_Code quote:_
```XML
import { SFProjectService } from 'src/app/core/sf-project.service';
import { isString } from 'src/type-utils';
```

**Review by pmachapman — APPROVED** [review]
Also, I had to review again for Reviewable to show the correct changes in the second commit :-/

> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/2452#-:-NxnlfvTBdDTQuCaKSqR:bea9dq5)* status: all files reviewed, 3 unresolved discussions (waiting on @Nateowami and @siltomato)

**Review by siltomato — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/2452)* status: 14 of 18 files reviewed, all discussions resolved (waiting on @Nateowami and @pmachapman)

___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-viewer/draft-viewer.service.ts` line 4 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/2452#-NxnjGSz82u4rpwOOoJK:-NxotHLEAqm2RKneBOYa:b-896fix) ([raw file](https://github.com/sillsdev/web-xforge/blob/e4a4380366ea2d69646add720d897edd79a0fd78/src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-viewer/draft-viewer.service.ts#L4)):*
<details><summary><i>Previously, pmachapman (Peter Chapman) wrote…</i></summary><blockquote>

NIT: This should be a relative path.
</blockquote></details>

Done.
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.ts` line 227 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/2452#-Nxnj9jmDzvm63o3lPL5:-NxouJLa8CB6uqQT-tX7:b-896fix) ([raw file](https://github.com/sillsdev/web-xforge/blob/a50eb714e43446d0054e60592f82b9df380bf778/src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.ts#L227)):*
<details><summary><i>Previously, pmachapman (Peter Chapman) wrote…</i></summary><blockquote>

NIT: We can remove the feature flag service from the component and the spec file.
</blockquote></details>

Done.
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor-draft/editor-draft.component.ts` line 28 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/2452#-Nxnjk-c59MqXPix1fEM:-NxotfVRB188KgTw0Zm3:b-896fix) ([raw file](https://github.com/sillsdev/web-xforge/blob/e4a4380366ea2d69646add720d897edd79a0fd78/src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor-draft/editor-draft.component.ts#L28)):*
<details><summary><i>Previously, pmachapman (Peter Chapman) wrote…</i></summary><blockquote>

NIT: These should be relative paths.
</blockquote></details>

Done.

**Review by pmachapman — APPROVED** [review]
:lgtm:

> Reviewed 4 of 4 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/2452#-:-NxoxZN9CHTUPN5177pH:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @Nateowami)

**Review by siltomato — COMMENTED** [review]
Added fix for failing test, and added an additional test that is the positive version of the failing test (to ensure that the fix for the failing test is correctly testing).

> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/2452#-:-NxpCfRX6HvgpwVDAvIg:bm3nqnh)* status: 18 of 19 files reviewed, all discussions resolved (waiting on @Nateowami)

**Review by pmachapman — APPROVED** [review]
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/2452)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @Nateowami)

**Pull request merged**
