### PR TITLE
dev: clean up and update ansible, upgrade to mongo 8

### PR DESCRIPTION
**Pull request by marksvc**
- **dev: clean up workstation ansible files**
- **dev: improve dev server ansible playbook file naming**
- **dev: delint ansible**
- **dev: remove more ansible lint**
- **dev: incorporate dep ansible into dev-server playbook**
- **dev: omit dotnet pkg repo key and source**
- **dev: update mongodb ansible**
- **dev: ansible: upgrade mongo from 7 to 8**

- - -
This change is [Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/2921)

### CODE REVIEW

**Comment by marksvc** [comment]
dotnet packages for Ubuntu 22.04+ are now maintained in the official, Ubuntu repositories.

This PR can be squashed into a single commit with only the subject and no body.

**Review by pmachapman — CHANGES_REQUESTED** [review]
Just one question!

> Reviewed 17 of 17 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/2921#-:-OEQpqwk1iVhSV-1Q0zs:b-w58e4u)* status: all files reviewed, 1 unresolved discussion (waiting on @marksvc)

___
*[`.gitmodules` line 8 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/2921#-OEQn17q9gPbvFzfl1TQ:-OEQn17q9gPbvFzfl1TR:bqv9qke) ([raw file](https://github.com/sillsdev/web-xforge/blob/a13bb9491b1bbdfd28bc0baae6ae4989a921eb4e/.gitmodules#L8)):*
> ```gitconfig
> 	path = deploy/roles/apache_config
> 	url = https://github.com/saygoweb/ansible-role-apache.git
> 	branch = master-our
> ```

Is it possible to just delete `.gitmodules`, instead of clearing it?



_Code quote:_
```gitconfig
[submodule "deploy/roles_common"]
	path = deploy/roles_common
	url = https://github.com/sillsdev/ops-ansible-common-roles
	branch = master
[submodule "deploy/roles/apache_config"]
	path = deploy/roles/apache_config
	url = https://github.com/saygoweb/ansible-role-apache.git
	branch = master-our
```

**Comment by marksvc** [comment]
I was wondering if that would happen automatically, but I guess not.

**Review by pmachapman — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/2921#-:-OEkRqOlDCmFmUo3tQIN:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @marksvc)

**Pull request merged**
