### PR TITLE
SF-2052 File and Corpora Patching for Serval

### PR DESCRIPTION
**Pull request by pmachapman**
This Pull Requests updates to the latest Serval Client, and utilizes its new feature to patch the files and corpora, rather than delete then recreate the corpora each time.

I have also taken the opportunity to clean up the use of status codes for the unit tests, and remove an unused class that was previously used in testing Serval integration before Serval Client was created.

- - -
This change is [Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1885)

### CODE REVIEW

**Review by marksvc — COMMENTED** [review]
I'm not familiar with this area of the program. Maybe I shouldn't have picked up this PR to review it :).
The MachineProjectService.cs change makes sense. But as I look over the MachineProjectServiceTests.cs file, I don't think I can very meaningfully say good or bad to the various changes, such as moving around between CreateAsync, DeleteAsync, UpdateCorpuAsync, and GetCorpusAsync.

> Reviewed 6 of 6 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1885#-:-NXSB-_7786gUPKRsFD8:b-yccjus)* status: all files reviewed, 2 unresolved discussions (waiting on @pmachapman)

___
*[`test/SIL.XForge.Scripture.Tests/Services/MachineProjectServiceTests.cs` line 148 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/1885#-NXS-HOdD_6eW4S0_lwh:-NXS-HOdD_6eW4S0_lwi:bgy044o) ([raw file](https://github.com/sillsdev/web-xforge/blob/c00196da55e1a85812788a6626d5ad83c7404cc5/test/SIL.XForge.Scripture.Tests/Services/MachineProjectServiceTests.cs#L148)):*
> ```Smalltalk
>             .CreateAsync(Arg.Any<IEnumerable<string>>(), Arg.Any<TextCorpusType>())
>             .Returns(TestEnvironment.MockTextCorpus);
>         await env.ProjectSecrets.UpdateAsync(
> ```

What's the significance of adding this?
___
*[`test/SIL.XForge.Scripture.Tests/Services/MachineProjectServiceTests.cs` line 493 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/1885#-NXS3JdsAp1fa4fnCrLx:-NXS3JdsAp1fa4fnCrLy:bulpfq4) ([raw file](https://github.com/sillsdev/web-xforge/blob/c00196da55e1a85812788a6626d5ad83c7404cc5/test/SIL.XForge.Scripture.Tests/Services/MachineProjectServiceTests.cs#L493)):*
> ```Smalltalk
>         bool actual = await env.Service.SyncProjectCorporaAsync(User01, Project02, CancellationToken.None);
>         Assert.IsTrue(actual);
>         await env.DataFilesClient.ReceivedWithAnyArgs(1).DeleteAsync(string.Empty, CancellationToken.None);
> ```

Hmm. I was surprised that we called Delete, instead of Updating instead.
___
*[`test/SIL.XForge.Scripture.Tests/Services/MachineProjectServiceTests.cs` line 601 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/1885#-NXS6N6G6_rNZJZvaPCK:-NXS6N6G6_rNZJZvaPCL:b4dgqwa) ([raw file](https://github.com/sillsdev/web-xforge/blob/c00196da55e1a85812788a6626d5ad83c7404cc5/test/SIL.XForge.Scripture.Tests/Services/MachineProjectServiceTests.cs#L601)):*
> ```Smalltalk
>         // The 404 exception was logged
>         Assert.That(
>             env.MockLogger.LogEvents.Count(
> ```

(And FYI that other parts of this API let you do things like
```cs
env.MockLogger.AssertHasEvent(predicate, "Should have logged exception.");
```
and
```cs
env.MockLogger.AssertEventCount(predicate, 1, "Should have logged exception.");
```
. Which.. isn't too different to what you did, but FYI that that's there, too.)

**Comment by marksvc** [comment]
Actually, maybe if we go over it on the phone then I might be able to understand enough to give an assessment of the rest of the patch.

**Review by pmachapman — COMMENTED** [review]
Happy to meet any time Monday your time (or later in the week) to discuss. I have updated to match some of your feedback in the meantime.

> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1885#-:-NXg8B8160yPACIKgl4P:b-dwfa68)* status: all files reviewed, 2 unresolved discussions (waiting on @marksvc)

___
*[`test/SIL.XForge.Scripture.Tests/Services/MachineProjectServiceTests.cs` line 148 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/1885#-NXS-HOdD_6eW4S0_lwh:-NXg0dc07r9Au01JsPh9:bwnj7qz) ([raw file](https://github.com/sillsdev/web-xforge/blob/c00196da55e1a85812788a6626d5ad83c7404cc5/test/SIL.XForge.Scripture.Tests/Services/MachineProjectServiceTests.cs#L148)):*
<details><summary><i>Previously, marksvc wrote…</i></summary><blockquote>

What's the significance of adding this?
</blockquote></details>

The previous execution flow for updating Serval was:

1. Build the list of files for the new corpus, and upload any new files, or delete the upload any changed files
2. Get the old corpus so we can see what files are not in the new list
3. Delete the files that are not in the new list

Steps 2 and 3 were performed in the body of `MachineProjectService.SyncProjectCorporaAsync()`.

This workflow is now performed inside `MachineProjectService.UploadNewCorpusFilesAsync()`, where the files are added or updated directly, and only deleted when they are missing. The missing status is determined by comparing the new list of files for the corpora with the old list we load from ProjectSecrets. Because of that, we no longer call `GetCorpusAsync()`.
___
*[`test/SIL.XForge.Scripture.Tests/Services/MachineProjectServiceTests.cs` line 493 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/1885#-NXS3JdsAp1fa4fnCrLx:-NXg7aCl22hGO99SH5cD:b-57d1u3) ([raw file](https://github.com/sillsdev/web-xforge/blob/c00196da55e1a85812788a6626d5ad83c7404cc5/test/SIL.XForge.Scripture.Tests/Services/MachineProjectServiceTests.cs#L493)):*
<details><summary><i>Previously, marksvc wrote…</i></summary><blockquote>

Hmm. I was surprised that we called Delete, instead of Updating instead.
</blockquote></details>

I have clean up this test so that it only calls Update(). Delete was being called due to a fileId outside the scope of the test not being removed from the project secret when I was preparing that.
___
*[`test/SIL.XForge.Scripture.Tests/Services/MachineProjectServiceTests.cs` line 601 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/1885#-NXS6N6G6_rNZJZvaPCK:-NXg84hs-tniIZzBJvX-:b-5cs5cb) ([raw file](https://github.com/sillsdev/web-xforge/blob/c00196da55e1a85812788a6626d5ad83c7404cc5/test/SIL.XForge.Scripture.Tests/Services/MachineProjectServiceTests.cs#L601)):*
<details><summary><i>Previously, marksvc wrote…</i></summary><blockquote>

(And FYI that other parts of this API let you do things like
```cs
env.MockLogger.AssertHasEvent(predicate, "Should have logged exception.");
```
and
```cs
env.MockLogger.AssertEventCount(predicate, 1, "Should have logged exception.");
```
. Which.. isn't too different to what you did, but FYI that that's there, too.)
</blockquote></details>

Thank you - that is much cleaner than what I did. I have updated the assertion.

**Review by marksvc — COMMENTED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1885)* status: all files reviewed, 1 unresolved discussion (waiting on @pmachapman)

___
*[`test/SIL.XForge.Scripture.Tests/Services/MachineProjectServiceTests.cs` line 493 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/1885#-NXS3JdsAp1fa4fnCrLx:-NXkhs-IE2XeH5pQikBo:b-1xf9ie) ([raw file](https://github.com/sillsdev/web-xforge/blob/c00196da55e1a85812788a6626d5ad83c7404cc5/test/SIL.XForge.Scripture.Tests/Services/MachineProjectServiceTests.cs#L493)):*
<details><summary><i>Previously, pmachapman (Peter Chapman) wrote…</i></summary><blockquote>

I have clean up this test so that it only calls Update(). Delete was being called due to a fileId outside the scope of the test not being removed from the project secret when I was preparing that.
</blockquote></details>

Ah, okay.

**Review by pmachapman — COMMENTED** [review]
I have updated the unit test scaffolding to hopefully be easier to understand. I also was able to reduce the amount of test setup code - it will probably be better to read the code file rather than the diff to review.

> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1885#-:-NXmOxuA64s4e7M2YqSY:b-4fipjr)* status: 5 of 6 files reviewed, 1 unresolved discussion (waiting on @marksvc)

**Review by marksvc — COMMENTED** [review]
> Reviewed 1 of 1 files at r3, 1 of 1 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1885)* status: all files reviewed, 1 unresolved discussion (waiting on @pmachapman)

___
*[`src/SIL.XForge.Scripture/Services/MachineProjectService.cs` line 423 at r9](https://reviewable.io/reviews/sillsdev/web-xforge/1885#-NXqzdI_CyXPLmH4IhU0:-NXqzdI_CyXPLmH4IhU1:b-5w0jn1) ([raw file](https://github.com/sillsdev/web-xforge/blob/c261f418bb67420e11b27d4827223d02b852f849/src/SIL.XForge.Scripture/Services/MachineProjectService.cs#L423)):*
> ```Smalltalk
> 
>                 // Delete the old corpus
>                 await _translationEnginesClient.DeleteCorpusAsync(
> ```

So do we never delete a corpus now? Only files in it?

**Review by pmachapman — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1885)* status: all files reviewed, 1 unresolved discussion (waiting on @marksvc)

___
*[`src/SIL.XForge.Scripture/Services/MachineProjectService.cs` line 423 at r9](https://reviewable.io/reviews/sillsdev/web-xforge/1885#-NXqzdI_CyXPLmH4IhU0:-NXrATQP39ODnt2-k4vF:b-9wdi06) ([raw file](https://github.com/sillsdev/web-xforge/blob/c261f418bb67420e11b27d4827223d02b852f849/src/SIL.XForge.Scripture/Services/MachineProjectService.cs#L423)):*
<details><summary><i>Previously, marksvc wrote…</i></summary><blockquote>

So do we never delete a corpus now? Only files in it?
</blockquote></details>

Yes, correct.

**Review by marksvc — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1885)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @pmachapman)

**Comment by marksvc** [comment]
@pmachapman I can't remember if this is a PR that is supposed to be held back for something else, so I'll let you do the merging.

**Pull request merged**
