### PR TITLE
SF-2810 Add tooltips to CC answers

### PR DESCRIPTION
**Pull request by josephmyers**
This change is [Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/2558)

### CODE REVIEW

**Review by pmachapman — CHANGES_REQUESTED** [review]
If this isn't morphing the PR, would you be able to add tooltips to the Play/Stop button and Delete button in the same answer audio area? I also noticed that the Add Questions dialog Audio button (and Play/Stop and Delete buttons) also do not have tooltips.

If you think this is morphing the PR, I am happy to approve (the good looks great and the tooltips are a big improvement), but I thought it might be worth considering doing since you are already working in this area.

> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/2558#-:-O0kubyk0AmU70GBJ1Xs:b6am62y)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @josephmyers)

**Review by josephmyers — COMMENTED** [review]
It's not really morphing, but I do somewhat disagree that we should add those. Play/Stop/Delete are all really clear and accepted icons, and we're not doing anything weird with them where tooltips would add much. I think it's telling that the issue reporter (Ravi) did not request those. And the other usage of the single button audio player, above, also has gone without tooltips for its existence.

So I'd rather we push this on. But I'm open to your suggestions!

> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/2558#-:-O0mQTr23KVrGmZ3WvXD:b-1sw4x2)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @josephmyers)

**Review by pmachapman — APPROVED** [review]
:lgtm: No problem!

> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/2558#-:-O0pATcdBPFQ_OZKYZPY:b-f36c5q)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @josephmyers)

**Review by pmachapman — APPROVED** [review]
> Reviewed 4 of 4 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/2558)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @josephmyers)

**Pull request merged**
