### PR TITLE
SF-2822 Create 'user comment count' report script

### PR DESCRIPTION
**Pull request by siltomato**
This PR creates ts-node script `report-user-comments.ts` that takes a project and time window and outputs a TSV file summarizing note thread counts by user and book/chapter.

Note: Testing will be done by reviewer instead of test team.

- - -
This change is [Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/2564)

### CODE REVIEW

**Review by siltomato — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/2564)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @github-advanced-security[bot])

___
*[`scripts/db_tools/report-user-comments.ts` line 75 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/2564#gh-1663014909:-O0tWllaEq6q0kNnGncs:b-896fix) ([raw file](https://github.com/sillsdev/web-xforge/blob/6093e5301f0c11a8239372d864438a7ad0645a42/scripts/db_tools/report-user-comments.ts#L75)):*
<details><summary><i>Previously, github-advanced-security[bot] wrote…</i></summary><blockquote>

## Unused variable, import, function or class

Unused variable conn.

[Show more details](https://github.com/sillsdev/web-xforge/security/code-scanning/827)
</blockquote></details>

Done.

**Comment by Nateowami** [comment]
In my testing, both locally and on live, this does not count comments created in Scripture Forge. I'm getting blank output.

**Review by siltomato — COMMENTED** [review]
I wasn't accounting for the 'note_threads' collection storing the date as a date string instead of a timestamp.

> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/2564#-:-O0ul-dN9RavkIB3aRKz:bwh0puc)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @github-advanced-security[bot])

**Review by pmachapman — CHANGES_REQUESTED** [review]
Code looks good - just one question:

Is the script supposed to count all notes (i.e. notes created in Paratext and SF), or just notes created in SF?

Currently this script counts all notes, whether created in SF or PT. To filter just notes created or edited in SF, you will need to add the following to the `$match`:
```
'notes.editable': { $eq: true }
```

> Reviewed 1 of 1 files at r3, all commit messages.
> Dismissed @github-advanced-security[bot] from a discussion.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/2564#-:-O1F0ftk4LbV2275POl7:b-b5rl5y)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @siltomato)

**Review by siltomato — COMMENTED** [review]
Good question.  @Nateowami, can you clarify this point?

> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/2564#-:-O1HmIyC5RS7v4Bj6CoE:b-r1jdzh)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @siltomato)

**Review by siltomato — COMMENTED** [review]
Made change to allow time in date 'from' and to' args.  This will allow easier month-to-month reporting, as 'T00:00' (start-of-day) for 1st day of month can be used as the end date of the range instead of needing to determine the month length.

> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/2564#-:-O1HqMVU8_PCgF1ryLNv:b-nxo3vy)* status: 0 of 1 files reviewed, all discussions resolved (waiting on @pmachapman)

**Review by siltomato — COMMENTED** [review]
Modified report to group results by year then month then user.  This should allow an easy month-by-month breakdown as desired by Biblica.  To see the monthly breakdown from the project's start, the report can be run with no date range.

If this format is acceptable, I'll update the 'user edit count' script to have the same grouping.

> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/2564#-:-O1JI8KxBjo69v_FGK_f:b-mg71mr)* status: 0 of 1 files reviewed, all discussions resolved (waiting on @pmachapman)

**Review by pmachapman — CHANGES_REQUESTED** [review]
Just a couple of comments (and a re-asking of the question above).

> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/2564#-:-O2aKOs7A8B2QeL4Y_c8:b8612h4)* status: all files reviewed, 3 unresolved discussions (waiting on @siltomato)

___
*[`scripts/db_tools/report-user-comments.ts` line 87 at r3](https://reviewable.io/reviews/sillsdev/web-xforge/2564#-O2aDNI50h7aWEyizAgw:-O2aDNI50h7aWEyizAgx:b-zvzx3) ([raw file](https://github.com/sillsdev/web-xforge/blob/2913a80a2fd39cc9aaffae345edf37aea2d633a7/scripts/db_tools/report-user-comments.ts#L87)):*
> ```XML
>         );
>       }
> ```

You do not use this connection to the Realtime server, so this can be removed (and the corresponding `ws.close()`).



_Code quote:_
```XML
const ws = createWS(this.connectionConfig);
```
___
*[`scripts/db_tools/report-user-comments.ts` line 229 at r3](https://reviewable.io/reviews/sillsdev/web-xforge/2564#-O2aJr9H5E-dQKVdRenX:-O2aJr9H5E-dQKVdRenY:bxdtpk9) ([raw file](https://github.com/sillsdev/web-xforge/blob/2913a80a2fd39cc9aaffae345edf37aea2d633a7/scripts/db_tools/report-user-comments.ts#L229)):*
> ```XML
>             }
>           })
>         }
> ```

Can you change this check to be `>=`?

I ran the script with the following arguments, and it returned no results (I had a note created at `2023-06-19T10:53:05.5240883+00:00`):
```sh
./report-user-comments.ts --project LTP --from 2023-06-19T10:53:05 --to 2023-06-19T10:53:05
```

(Using `--from 2023-06-19T10:53:05 --to 2023-06-19T10:53:06` worked correctly):



_Code quote:_
```XML
if (argv.from && argv.to && new Date(argv.from) > new Date(argv.to)) {
```
___
*[`scripts/db_tools/report-user-comments.ts` line 279 at r3](https://reviewable.io/reviews/sillsdev/web-xforge/2564#-O2aJyRtEOpF8OPeb6JF:-O2aJyRtEOpF8OPeb6JG:b-rwfzbv) ([raw file](https://github.com/sillsdev/web-xforge/blob/2913a80a2fd39cc9aaffae345edf37aea2d633a7/scripts/db_tools/report-user-comments.ts#L279)):*
> ```XML
>       }
>     ]);
>   }
> ```

Is the script supposed to count all notes (i.e. notes created in Paratext and SF), or just notes created in SF?

Currently this script counts all notes, whether created in SF or PT. To filter just notes created or edited in SF, you will need to add the following to the `$match`:

```
'notes.editable': { $eq: true }
```



_Code quote:_
```XML
$match: {
```

**Comment by pmachapman** [comment]
@siltomato  Reviewable misplaced all of my comments :-/ Please refer to the code quotes for the lines I am actually referring to.

**Review by siltomato — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/2564)* status: 0 of 1 files reviewed, 3 unresolved discussions (waiting on @pmachapman)

___
*[`scripts/db_tools/report-user-comments.ts` line 87 at r3](https://reviewable.io/reviews/sillsdev/web-xforge/2564#-O2aDNI50h7aWEyizAgw:-O3Iy7xw1GMF-sh8WHeB:b-896fix) ([raw file](https://github.com/sillsdev/web-xforge/blob/2913a80a2fd39cc9aaffae345edf37aea2d633a7/scripts/db_tools/report-user-comments.ts#L87)):*
<details><summary><i>Previously, pmachapman (Peter Chapman) wrote…</i></summary><blockquote>

You do not use this connection to the Realtime server, so this can be removed (and the corresponding `ws.close()`).
</blockquote></details>

Done.
___
*[`scripts/db_tools/report-user-comments.ts` line 229 at r3](https://reviewable.io/reviews/sillsdev/web-xforge/2564#-O2aJr9H5E-dQKVdRenX:-O3JYgAF58bOUIfqZ1mI:b-896fix) ([raw file](https://github.com/sillsdev/web-xforge/blob/2913a80a2fd39cc9aaffae345edf37aea2d633a7/scripts/db_tools/report-user-comments.ts#L229)):*
<details><summary><i>Previously, pmachapman (Peter Chapman) wrote…</i></summary><blockquote>

Can you change this check to be `>=`?

I ran the script with the following arguments, and it returned no results (I had a note created at `2023-06-19T10:53:05.5240883+00:00`):
```sh
./report-user-comments.ts --project LTP --from 2023-06-19T10:53:05 --to 2023-06-19T10:53:05
```

(Using `--from 2023-06-19T10:53:05 --to 2023-06-19T10:53:06` worked correctly):
</blockquote></details>

Done.
___
*[`scripts/db_tools/report-user-comments.ts` line 279 at r3](https://reviewable.io/reviews/sillsdev/web-xforge/2564#-O2aJyRtEOpF8OPeb6JF:-O3J0kQEDA3yFSlsIAb5:btwkn1g) ([raw file](https://github.com/sillsdev/web-xforge/blob/2913a80a2fd39cc9aaffae345edf37aea2d633a7/scripts/db_tools/report-user-comments.ts#L279)):*
<details><summary><i>Previously, pmachapman (Peter Chapman) wrote…</i></summary><blockquote>

Is the script supposed to count all notes (i.e. notes created in Paratext and SF), or just notes created in SF?

Currently this script counts all notes, whether created in SF or PT. To filter just notes created or edited in SF, you will need to add the following to the `$match`:

```
'notes.editable': { $eq: true }
```
</blockquote></details>

After verifying with Nathaniel, the verdict is that it should count all notes.

**Review by pmachapman — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/2564#-:-O3U5FSPEOcMp1zhuum7:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @siltomato)

**Pull request merged**
