### PR TITLE
SF-2278 Display book selection for draft training (UI only)

### PR DESCRIPTION
**Pull request by siltomato**
When user selects to generate a draft, the user is now shown pre-generation steps in which he will select books for training.

This pull request just implements the initial UI concept.  The selected books are not currently sent to the API with the draft request.

- - -
This change is [Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/2120)

### CODE REVIEW

**Review by pmachapman — CHANGES_REQUESTED** [review]
> Reviewed 16 of 16 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/2120)* status: all files reviewed, 6 unresolved discussions (waiting on @siltomato)

___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/shared/book-multi-select/book-multi-select.component.html` line 4 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/2120#-NgpB3xb9Kid3rtaDXSY:-NgpB3xb9Kid3rtaDXSZ:bzi5dyt) ([raw file](https://github.com/sillsdev/web-xforge/blob/0b93480e77c84c3001517fbefa019461a5fb6fd4/src/SIL.XForge.Scripture/ClientApp/src/app/shared/book-multi-select/book-multi-select.component.html#L4)):*
> ```HTML
>   <mat-chip *ngFor="let book of bookOptions" [selected]="book.selected" (click)="!readonly && toggleSelection(book)">
>     {{ book.name }}
>   </mat-chip>
> ```

Are we able to have the chips act like filter chips? Solid background and a checkmark if enabled, hollow and no checkmark if not enabled? See https://github.com/material-components/material-web/blob/main/docs/components/chip.md (I realize that Angular Material does not support a filter chip out of the box)



_Code quote:_
```HTML
  <mat-chip *ngFor="let book of bookOptions" [selected]="book.selected" (click)="!readonly && toggleSelection(book)">
    {{ book.name }}
  </mat-chip>
```
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/shared/book-multi-select/book-multi-select.component.scss` line 3 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/2120#-Ngp54snEbUW-NcZdLeE:-Ngp54snEbUW-NcZdLeF:b-izzdey) ([raw file](https://github.com/sillsdev/web-xforge/blob/0b93480e77c84c3001517fbefa019461a5fb6fd4/src/SIL.XForge.Scripture/ClientApp/src/app/shared/book-multi-select/book-multi-select.component.scss#L3)):*
> ```SCSS
> @use 'src/variables' as vars;
> 
> .mat-chip.mat-standard-chip {
> ```

Could we have `cursor: pointer` for the chips? My browser just shows an arrow which doesn't make me think I can click on them.



_Code quote:_
```SCSS
.mat-chip.mat-standard-chip {
```
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-generation.component.spec.ts` line 126 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/2120#-Ngp98zj8jpNpbZRrJzw:-Ngp98zj8jpNpbZRrJzx:bt817ln) ([raw file](https://github.com/sillsdev/web-xforge/blob/0b93480e77c84c3001517fbefa019461a5fb6fd4/src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-generation.component.spec.ts#L126)):*
> ```XML
>           { provide: OnlineStatusService, useValue: mockOnlineStatusService }
>         ],
>         schemas: [NO_ERRORS_SCHEMA] // Ignore errors from unknown child components
> ```

I'm not sure why this is necessary? I removed this and the tests ran perfectly.



_Code quote:_
```XML
schemas: [NO_ERRORS_SCHEMA] // Ignore errors from unknown child components
```
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-generation.component.spec.ts` line 304 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/2120#-Ngp6Hhw-fCxGXHFhVDM:-Ngp6Hhw-fCxGXHFhVDN:b2ixj93) ([raw file](https://github.com/sillsdev/web-xforge/blob/0b93480e77c84c3001517fbefa019461a5fb6fd4/src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-generation.component.spec.ts#L304)):*
> ```XML
>       });
> 
>       env.component['startBuild']();
> ```

Should we just make `startBuild()` public? I don't see any reason why it has to be private, given we are using it in unit tests, and we are not publishing this component via npm, etc.

I'm interested on your thoughts on why you keep it private and call it this way (I noticed you also did this for `checkForPreTranslations()` in editor.component.ts).



_Code quote:_
```XML
env.component['startBuild']();
```
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-generation-steps/draft-generation-steps.component.html` line 24 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/2120#-Ngp5dWY5QKS7g_owSF4:-Ngp5dWY5QKS7g_owSF5:blxu7sa) ([raw file](https://github.com/sillsdev/web-xforge/blob/0b93480e77c84c3001517fbefa019461a5fb6fd4/src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-generation-steps/draft-generation-steps.component.html#L24)):*
> ```HTML
>       [selectedBooks]="selectedBooks"
>       (bookSelect)="onBookSelect($event)"
>     ></app-book-multi-select>
> ```

I am not sure of the value of having these selectable on this final review step? For example, clicking on them removes the ship, but you cannot add it back without going back to t the step.

Does it work if we have this step entirely read only (we wouldn't need any checkboxes to at like a filter chip)? The color might have to be different for the chips on this step, though?



_Code quote:_
```HTML
    <app-book-multi-select
      [availableBooks]="selectedBooks"
      [selectedBooks]="selectedBooks"
      (bookSelect)="onBookSelect($event)"
    ></app-book-multi-select>
```
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-generation-steps/draft-generation-steps.component.ts` line 30 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/2120#-Ngp4iv3EHHCiy39wiTC:-Ngp4iv4CT7-2k40CKZe:b-mvehnq) ([raw file](https://github.com/sillsdev/web-xforge/blob/0b93480e77c84c3001517fbefa019461a5fb6fd4/src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-generation-steps/draft-generation-steps.component.ts#L30)):*
> ```XML
>         this.selectedBooks = books;
>       })
>     );
> ```

Could we please build this list from the source project's books, not the target project's books?



_Code quote:_
```XML
    this.availableBooks$ = this.activatedProject.projectDoc$.pipe(
      map(doc => doc?.data?.texts.map(t => t.bookNum) ?? []),
      tap((books: number[]) => {
        // Initially select all books
        this.selectedBooks = books;
      })
    );
```

**Review by siltomato — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/2120)* status: 9 of 16 files reviewed, 6 unresolved discussions (waiting on @pmachapman)

___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/shared/book-multi-select/book-multi-select.component.html` line 4 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/2120#-NgpB3xb9Kid3rtaDXSY:-Ngr76k50qrdjsJuHBP2:b-aoswsp) ([raw file](https://github.com/sillsdev/web-xforge/blob/0b93480e77c84c3001517fbefa019461a5fb6fd4/src/SIL.XForge.Scripture/ClientApp/src/app/shared/book-multi-select/book-multi-select.component.html#L4)):*
<details><summary><i>Previously, pmachapman (Peter Chapman) wrote…</i></summary><blockquote>

Are we able to have the chips act like filter chips? Solid background and a checkmark if enabled, hollow and no checkmark if not enabled? See https://github.com/material-components/material-web/blob/main/docs/components/chip.md (I realize that Angular Material does not support a filter chip out of the box)
</blockquote></details>

Cool, I like that.  It looks like something very close to this will be available once we upgrade angular: https://material.angular.io/components/chips/overview#static-chips
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/shared/book-multi-select/book-multi-select.component.scss` line 3 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/2120#-Ngp54snEbUW-NcZdLeE:-Ngsujo_3_0hAebe2uMm:b-896fix) ([raw file](https://github.com/sillsdev/web-xforge/blob/0b93480e77c84c3001517fbefa019461a5fb6fd4/src/SIL.XForge.Scripture/ClientApp/src/app/shared/book-multi-select/book-multi-select.component.scss#L3)):*
<details><summary><i>Previously, pmachapman (Peter Chapman) wrote…</i></summary><blockquote>

Could we have `cursor: pointer` for the chips? My browser just shows an arrow which doesn't make me think I can click on them.
</blockquote></details>

Done.
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-generation.component.spec.ts` line 126 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/2120#-Ngp98zj8jpNpbZRrJzw:-Ngr7i5Y4_uWY36iAqOj:b-jzg2jq) ([raw file](https://github.com/sillsdev/web-xforge/blob/0b93480e77c84c3001517fbefa019461a5fb6fd4/src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-generation.component.spec.ts#L126)):*
<details><summary><i>Previously, pmachapman (Peter Chapman) wrote…</i></summary><blockquote>

I'm not sure why this is necessary? I removed this and the tests ran perfectly.
</blockquote></details>

It was to prevent console errors regarding angular not recognizing the markup for child components, like:
`NG0304: 'app-draft-generation-steps' is not a known element...`

I didn't want to mock their dependencies, since I'm not testing more than the stepper existence here, but it's not a big deal to do so.  Changed.
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-generation.component.spec.ts` line 304 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/2120#-Ngp6Hhw-fCxGXHFhVDM:-NgsxyqZ5oo24sannESk:bqw98r7) ([raw file](https://github.com/sillsdev/web-xforge/blob/0b93480e77c84c3001517fbefa019461a5fb6fd4/src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-generation.component.spec.ts#L304)):*
<details><summary><i>Previously, pmachapman (Peter Chapman) wrote…</i></summary><blockquote>

Should we just make `startBuild()` public? I don't see any reason why it has to be private, given we are using it in unit tests, and we are not publishing this component via npm, etc.

I'm interested on your thoughts on why you keep it private and call it this way (I noticed you also did this for `checkForPreTranslations()` in editor.component.ts).
</blockquote></details>

Yes, this is an interesting question for me.  Unit testing in general is not a well understood area for me, and I often struggle with both conceptually what makes a good test and the actual test implementation.

I've read various testing philosophies and opinions, but I haven't yet digested them with enough practice to gain discernment in this area.

I've read some thoughts on only unit testing public methods, but then I think, "I'd really like a test on this private method."  Then I wonder why the method is private anyway.  Did I make it so just because I didn't call it in the template?  Choosing access modifiers seems more clear in services than components.

And then, assuming an access modifier is correct (hypothetically... not in the method you mentioned), should it be changed to public for the sake of testing, or (if it really is private implementation detail), should it not be tested directly at all?

Sorry for the rambling, I'm trying to work these things out in my head, and I greatly value the thoughts of you all who have much more experience with designing and writing automated tests.

I went ahead and made `startBuild()` public.
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-generation-steps/draft-generation-steps.component.html` line 24 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/2120#-Ngp5dWY5QKS7g_owSF4:-Ngtk5nz3FGfdk3VZVcM:byqrbof) ([raw file](https://github.com/sillsdev/web-xforge/blob/0b93480e77c84c3001517fbefa019461a5fb6fd4/src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-generation-steps/draft-generation-steps.component.html#L24)):*
<details><summary><i>Previously, pmachapman (Peter Chapman) wrote…</i></summary><blockquote>

I am not sure of the value of having these selectable on this final review step? For example, clicking on them removes the ship, but you cannot add it back without going back to t the step.

Does it work if we have this step entirely read only (we wouldn't need any checkboxes to at like a filter chip)? The color might have to be different for the chips on this step, though?
</blockquote></details>

Good idea.  Not sure what would make a good read-only color that doesn't look disabled, but doesn't invite interaction.  If you prefer a different color than what I chose, let me know.
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-generation-steps/draft-generation-steps.component.ts` line 30 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/2120#-Ngp4iv3EHHCiy39wiTC:-NgtHoD0ExtH6pmRwb-r:b-wq0r2k) ([raw file](https://github.com/sillsdev/web-xforge/blob/0b93480e77c84c3001517fbefa019461a5fb6fd4/src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-generation-steps/draft-generation-steps.component.ts#L30)):*
<details><summary><i>Previously, pmachapman (Peter Chapman) wrote…</i></summary><blockquote>

Could we please build this list from the source project's books, not the target project's books?
</blockquote></details>

Ah, yes, it makes sense that available books would come from the source project.

In regard to initial selection, would it be reasonable to initialize with the selection from the previous draft if available?  And if that selection is not stored, initially select books from the target project that have texts?

**Review by pmachapman — CHANGES_REQUESTED** [review]
> Reviewed 7 of 7 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/2120)* status: all files reviewed, 1 unresolved discussion (waiting on @siltomato)

___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/shared/book-multi-select/book-multi-select.component.html` line 4 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/2120#-NgpB3xb9Kid3rtaDXSY:-Ngtwboh-v5ihJjOfJIX:b-1faunj) ([raw file](https://github.com/sillsdev/web-xforge/blob/0b93480e77c84c3001517fbefa019461a5fb6fd4/src/SIL.XForge.Scripture/ClientApp/src/app/shared/book-multi-select/book-multi-select.component.html#L4)):*
<details><summary><i>Previously, siltomato wrote…</i></summary><blockquote>

Cool, I like that.  It looks like something very close to this will be available once we upgrade angular: https://material.angular.io/components/chips/overview#static-chips
</blockquote></details>

Could we add the checkmark now? If it makes it too cluttered, we can skip this.

This code worked for me:
```html
<mat-chip-list [multiple]="true" class="book-multi-select" [class.readonly]="readonly">
  <mat-chip *ngFor="let book of bookOptions" [selected]="book.selected" (click)="!readonly && toggleSelection(book)">
    <mat-icon *ngIf="book.selected && !readonly">check</mat-icon>
    {{ book.name }}
  </mat-chip>
</mat-chip-list>
```

**Review by siltomato — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/2120)* status: 14 of 16 files reviewed, 1 unresolved discussion (waiting on @pmachapman)

___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/shared/book-multi-select/book-multi-select.component.html` line 4 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/2120#-NgpB3xb9Kid3rtaDXSY:-Ngv057i9A12aSPFXNMt:b62rhyy) ([raw file](https://github.com/sillsdev/web-xforge/blob/0b93480e77c84c3001517fbefa019461a5fb6fd4/src/SIL.XForge.Scripture/ClientApp/src/app/shared/book-multi-select/book-multi-select.component.html#L4)):*
<details><summary><i>Previously, pmachapman (Peter Chapman) wrote…</i></summary><blockquote>

Could we add the checkmark now? If it makes it too cluttered, we can skip this.

This code worked for me:
```html
<mat-chip-list [multiple]="true" class="book-multi-select" [class.readonly]="readonly">
  <mat-chip *ngFor="let book of bookOptions" [selected]="book.selected" (click)="!readonly && toggleSelection(book)">
    <mat-icon *ngIf="book.selected && !readonly">check</mat-icon>
    {{ book.name }}
  </mat-chip>
</mat-chip-list>
```

</blockquote></details>

Nice.  Added.

**Review by pmachapman — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/2120#-:-NgvHJhD5co1FVzwfurq:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @siltomato)

**Review by pmachapman — APPROVED** [review]
> Reviewed 7 of 7 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/2120)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @siltomato)

**Pull request merged**
