### PR TITLE
SF-2269 Add sign-up link for pre-translation project approval

### PR DESCRIPTION
**Pull request by siltomato**
Adds a pre-translation requirement to have the `TranslateConfig.PreTranslate` flag set.  Otherwise, a sign-up link is displayed.

- - -
This change is [Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/2160)

### CODE REVIEW

**Review by RaymondLuong3 — CHANGES_REQUESTED** [review]
I will note that if you are on this page and you just enabled the forward translation drafting, the alert message does not actually update. The User needs to navigate away and back.

> Reviewed 6 of 6 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/2160#-:-NiaMzM_3EM99gDWOfNp:b8prsm5)* status: all files reviewed, 5 unresolved discussions (waiting on @pmachapman and @siltomato)

___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-generation.component.html` line 28 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/2160#-NiaUpbd5NilBjCH_YiD:-NiaUpbd5NilBjCH_YiE:bsyr2uy) ([raw file](https://github.com/sillsdev/web-xforge/blob/b361ce3aa14bd9b4483e89038b33e9d978843e3a/src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-generation.component.html#L28)):*
> ```HTML
>           <transloco
>             *ngIf="!isTargetLanguageSupported && targetLanguageDisplayName"
>             key="draft_generation.criteria_project_language_not_in_nllb_with_language"
> ```

Good catch with the negative version of the string here.
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-generation.component.html` line 81 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/2160#-NiaLz2N0f8X5cKBFqIw:-NiaLz2N0f8X5cKBFqIx:b-penl8v) ([raw file](https://github.com/sillsdev/web-xforge/blob/b361ce3aa14bd9b4483e89038b33e9d978843e3a/src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-generation.component.html#L81)):*
> ```HTML
>           <h3>{{ t("info_alert_approval_needed_header") }}</h3>
>           <p>
>             <transloco
> ```

Hmm, is it because there is a param that you need to provide that you can't just use the existing localizer in this template and need to declare a new transloco tag?



_Code quote:_
```HTML
            <transloco
```
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/pretranslation-signup-url.service.ts` line 20 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/2160#-NiaRP-6-viJai4uxAJm:-NiaRP-6-viJai4uxAJn:b-9p76kv) ([raw file](https://github.com/sillsdev/web-xforge/blob/b361ce3aa14bd9b4483e89038b33e9d978843e3a/src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/pretranslation-signup-url.service.ts#L20)):*
> ```XML
>     providedIn: 'root',
>     factory: () => ({
>       baseLink: 'https://app.smartsheet.com/b/form/305798a45a664d8585ac74e72241d8cc',
> ```

Is this sensitive at all? It seems odd to have the hardcoded link here, but I'm not aware of any issues this might pose.



_Code quote:_
```XML
      baseLink: 'https://app.smartsheet.com/b/form/305798a45a664d8585ac74e72241d8cc',
```
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/pretranslation-signup-url.service.spec.ts` line 30 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/2160#-NiaSTen-l-LJIjXQPGP:-NiaSTen-l-LJIjXQPGQ:b3yixh8) ([raw file](https://github.com/sillsdev/web-xforge/blob/b361ce3aa14bd9b4483e89038b33e9d978843e3a/src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/pretranslation-signup-url.service.spec.ts#L30)):*
> ```XML
>       const mockUserDoc: UserDoc = { data: { name: 'John', email: 'john@example.com' } } as UserDoc;
>       const mockProjectDoc: SFProjectProfileDoc = {
>         data: { shortName: 'project', writingSystem: { tag: 'en' } }
> ```

I notice that the form asks for the 3 letter ISO code, but writingSystem tags are aften in 2-letter format. Is it flexible, or we can decide to omit pre-filling the ISO code and let the user do that.



_Code quote:_
```XML
        data: { shortName: 'project', writingSystem: { tag: 'en' } }
```
___
*[`src/SIL.XForge.Scripture/ClientApp/src/assets/i18n/non_checking_en.json` line 126 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/2160#-NiaTvzNCglLiEV-iD9X:-NiaTvzNCglLiEV-iD9Y:b-abpvwf) ([raw file](https://github.com/sillsdev/web-xforge/blob/b361ce3aa14bd9b4483e89038b33e9d978843e3a/src/SIL.XForge.Scripture/ClientApp/src/assets/i18n/non_checking_en.json#L126)):*
> ```JSON
>     "criteria_forward_translation_drafting_enabled": "Forward translation drafting is enabled.",
>     "criteria_pretranslation_approved": "Your project is approved for pre-translation drafting.",
>     "criteria_pretranslation_not_approved": "Your project is not approved for pre-translation drafting.",
> ```

I'm not a big fan of including the negative version of every criteria string since each one will have to be translated, and it is double the effort for essentially the same string. But I see that is already part of this file, so I'll let it slide.



_Code quote:_
```JSON
    "criteria_pretranslation_approved": "Your project is approved for pre-translation drafting.",
    "criteria_pretranslation_not_approved": "Your project is not approved for pre-translation drafting.",
```

**Review by RaymondLuong3 — CHANGES_REQUESTED** [review]
Just one comment about to fix

> Reviewed 4 of 4 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/2160#-:-Niep1prBuJx9irOe9jW:b-jv9y37)* status: all files reviewed, 1 unresolved discussion (waiting on @pmachapman and @siltomato)

___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-generation.component.html` line 81 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/2160#-NiaLz2N0f8X5cKBFqIw:-Nien-C41c6SHfh1SaIX:b-1cgri4) ([raw file](https://github.com/sillsdev/web-xforge/blob/b361ce3aa14bd9b4483e89038b33e9d978843e3a/src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-generation.component.html#L81)):*
<details><summary><i>Previously, siltomato wrote…</i></summary><blockquote>

The `<transloco>` component is part of [`ngx-transloco-markup`](https://github.com/dscheerens/ngx-transloco-markup), which is a 3rd party plugin for transloco introduced [in this PR](https://github.com/sillsdev/web-xforge/pull/2138).  One feature of this plugin is that it allows use of links without splitting translations or using `innerHTML`.

So, the translation file can have the link as something like: `"visit [link:sfUrl]Scripture Forge[/link] to see wonderful stuff"`.
</blockquote></details>

Ok, I see that now. Thanks for the explanation
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-generation.component.ts` line 131 at r2](https://reviewable.io/reviews/sillsdev/web-xforge/2160#-NienMp3EKWMRwNYGxVE:-NienMp3EKWMRwNYGxVF:b2ly1eg) ([raw file](https://github.com/sillsdev/web-xforge/blob/fc6c0a22b79b0feb97917d4c46f5a8a85049c3a3/src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-generation.component.ts#L131)):*
> ```XML
>             this.isTargetLanguageSupported = this.nllbService.isNllbLanguage(this.targetLanguage);
>             this.isSourceAndTargetDifferent = translateConfig?.source?.writingSystem.tag !== this.targetLanguage;
>             this.isPreTranslationApproved = false && (translateConfig?.preTranslate ?? false);
> ```

Why did you add the false && to this line?



_Code quote:_
```XML
            this.isPreTranslationApproved = false && (translateConfig?.preTranslate ?? false);
```
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/pretranslation-signup-url.service.spec.ts` line 30 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/2160#-NiaSTen-l-LJIjXQPGP:-NienwOHC_3EkopnZz-w:b2qagg4) ([raw file](https://github.com/sillsdev/web-xforge/blob/b361ce3aa14bd9b4483e89038b33e9d978843e3a/src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/pretranslation-signup-url.service.spec.ts#L30)):*
<details><summary><i>Previously, siltomato wrote…</i></summary><blockquote>

Ah, yes, good point.  Do we have the code stored in 3-letter form anywhere?  If not, I'll omit that info from the query string.
</blockquote></details>

Ok, I see that the 3 letter code is stored when you got it. Paratext says it is the 3 letter ISO code on the Paratext settings, so this should work.

**Review by siltomato — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/2160)* status: 4 of 6 files reviewed, 1 unresolved discussion (waiting on @pmachapman and @RaymondLuong3)

___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-generation.component.ts` line 131 at r2](https://reviewable.io/reviews/sillsdev/web-xforge/2160#-NienMp3EKWMRwNYGxVE:-NiesviO1UMy4BykFjO3:bsqlsi5) ([raw file](https://github.com/sillsdev/web-xforge/blob/fc6c0a22b79b0feb97917d4c46f5a8a85049c3a3/src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-generation.component.ts#L131)):*
<details><summary><i>Previously, RaymondLuong3 (Raymond Luong) wrote…</i></summary><blockquote>

Why did you add the false && to this line?
</blockquote></details>

Oops!  I set that for testing and forgot to take it out.  Removed.

**Review by RaymondLuong3 — APPROVED** [review]
Great. Let's get this to testing.

> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/2160#-:-NifB6JX8H3vdEk3SxK5:b-d2t7gi)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @pmachapman)

**Review by siltomato — COMMENTED** [review]
- Changed so that back translations do not require sign-up form approval.
- Adjusted queue depth message (from rebase) to not be specific to back translations.

> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/2160#-:-NjTvFYj40WeWy_FNeMk:bmmo5y3)* status: 2 of 6 files reviewed, all discussions resolved (waiting on @RaymondLuong3)

**Review by RaymondLuong3 — APPROVED** [review]
Nice, I think not requiring back translation approval for NMT drafting will be nice, and will keep our capacity to focus on forward translations high. Hopefully that turns out to be true.

> Reviewed 4 of 4 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/2160#-:-NjiOO1KEUV00nS-qs-a:b-v90otu)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @siltomato)

**Pull request merged**
