### PR TITLE
SF-2388 Update to RxJS 7

### PR DESCRIPTION
**Pull request by Nateowami**
Based on my testing, I think we need to upgrade to RxJS 7 before upgrading ngx-quill, before upgrading to Angular 16. We need to update RxJS at some point one way or another. Unfortunately there are a number of breaking changes. See https://rxjs.dev/6-to-7-change-summary

- - -
This change is [Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/2217)

### CODE REVIEW

**Review by siltomato — CHANGES_REQUESTED** [review]
Looks good.  Just a few possible code simplifications and one thing unrelated to this PR.

> Reviewed 15 of 15 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/2217#-:-NlPnQT45qWJE71UEimq:bcp3oqd)* status: all files reviewed, 5 unresolved discussions (waiting on @Nateowami and @RaymondLuong3)

___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking-overview/checking-overview.component.spec.ts` line 1240 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/2217#-NlPNYU_-OAXf7UXAFMT:-NlPNYU_-OAXf7UXAFMU:b-8doojo) ([raw file](https://github.com/sillsdev/web-xforge/blob/605f52dbf94017ff5ea563ecaaec47d657ba96c7/src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking-overview/checking-overview.component.spec.ts#L1240)):*
> ```XML
>     // timeout before emitting changes again. That 1000 ms timeout will get left in the queue, but if we wait past that
>     // time, we don't have to do discardPeriodicTasks() to flush the queue.
>     tick(2000);
> ```

Nice technique.
___
*[`src/SIL.XForge.Scripture/ClientApp/src/xforge-common/auth.service.ts` line 167 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/2217#-NlPfu630_CdTVFwjtIe:-NlPfu630_CdTVFwjtIf:b-9zw9u1) ([raw file](https://github.com/sillsdev/web-xforge/blob/605f52dbf94017ff5ea563ecaaec47d657ba96c7/src/SIL.XForge.Scripture/ClientApp/src/xforge-common/auth.service.ts#L167)):*
> ```XML
>     }
>     return Promise.resolve(state.anonymousUser);
>   }
> ```

Could this be rewritten as:
```ts
get isLoggedInUserAnonymous(): Promise<boolean> {
  return firstValueFrom(
    this.loggedInState$.pipe(
      map(state => state.anonymousUser)
    )
  );
}
```

... and similar for below.
___
*[`src/SIL.XForge.Scripture/ClientApp/src/xforge-common/auth.service.ts` line 169 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/2217#-NlPgMGLANmigDdj946f:-NlPgMGLANmigDdj946g:b-msu9bf) ([raw file](https://github.com/sillsdev/web-xforge/blob/605f52dbf94017ff5ea563ecaaec47d657ba96c7/src/SIL.XForge.Scripture/ClientApp/src/xforge-common/auth.service.ts#L169)):*
> ```XML
>   }
> 
>   get isLoggedIn(): Promise<boolean> {
> ```

Possibly rewrite as above.
___
*[`src/SIL.XForge.Scripture/ClientApp/src/xforge-common/auth.service.ts` line 186 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/2217#-NlPgS1z9EPc1g3P0Pq7:-NlPgS1z9EPc1g3P0Pq8:b-msu9bf) ([raw file](https://github.com/sillsdev/web-xforge/blob/605f52dbf94017ff5ea563ecaaec47d657ba96c7/src/SIL.XForge.Scripture/ClientApp/src/xforge-common/auth.service.ts#L186)):*
> ```XML
>   }
> 
>   get isNewlyLoggedIn(): Promise<boolean> {
> ```

Possibly rewrite as above.
___
*[`src/SIL.XForge.Scripture/ClientApp/src/xforge-common/auth.service.ts` line 208 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/2217#-NlPghkB7VAlA1L6mUXC:-NlPghkB7VAlA1L6mUXD:b-cc9ko) ([raw file](https://github.com/sillsdev/web-xforge/blob/605f52dbf94017ff5ea563ecaaec47d657ba96c7/src/SIL.XForge.Scripture/ClientApp/src/xforge-common/auth.service.ts#L208)):*
> ```XML
> 
>   get loggedInState$(): Observable<LoginResult> {
>     return this._loggedInState$.asObservable().pipe(filter(state => state != null)) as Observable<LoginResult>;
> ```

Could use `filterNullish()` here and omit the type assertion.
___
*[`src/SIL.XForge.Scripture/ClientApp/src/xforge-common/auth.service.ts` line 277 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/2217#-NlPj3e7DW57Gnd7-3fK:-NlPj3e7DW57Gnd7-3fL:b-nsqlro) ([raw file](https://github.com/sillsdev/web-xforge/blob/605f52dbf94017ff5ea563ecaaec47d657ba96c7/src/SIL.XForge.Scripture/ClientApp/src/xforge-common/auth.service.ts#L277)):*
> ```XML
>     if (signUp || this.isJoining) {
>       if (signUp) auth0Parameters.mode = 'signUp';
>       auth0Parameters.login_hint = locale ?? ui_locales;
> ```

I know this is outside the scope of this PR, but this no-bracket `if (signUp)` statement is ambiguous whether `auth0Parameters.login_hint` assignment is intended to be included within the above condition.

**Review by Nateowami — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/2217)* status: all files reviewed, 5 unresolved discussions (waiting on @RaymondLuong3 and @siltomato)

___
*[`src/SIL.XForge.Scripture/ClientApp/src/xforge-common/auth.service.ts` line 167 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/2217#-NlPfu630_CdTVFwjtIe:-NlPuzXb-eNmvw8aEg6E:b-wh38el) ([raw file](https://github.com/sillsdev/web-xforge/blob/605f52dbf94017ff5ea563ecaaec47d657ba96c7/src/SIL.XForge.Scripture/ClientApp/src/xforge-common/auth.service.ts#L167)):*
<details><summary><i>Previously, siltomato wrote…</i></summary><blockquote>

Could this be rewritten as:
```ts
get isLoggedInUserAnonymous(): Promise<boolean> {
  return firstValueFrom(
    this.loggedInState$.pipe(
      map(state => state.anonymousUser)
    )
  );
}
```

... and similar for below.
</blockquote></details>

Is that actually equivalent? It looks like you've dropped a filter for `loggedInState$` value not being nullish.

Also, I'd prefer to touch as little as possible in a PR like this. There's a lot of potential for _really tricky_ things to break in this PR (the tests were hard to figure out, for example), and if something does break, and we bisect and find this commit was at fault, it would be convenient if the number of changes within it are as few as possible. So I like this change, but I think it should be done separately.

**Review by RaymondLuong3 — APPROVED** [review]
> Reviewed 3 of 15 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/2217)* status: all files reviewed, 7 unresolved discussions (waiting on @Nateowami and @siltomato)

___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/machine-api/remote-translation-engine.ts` line 40 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/2217#-NlPp4hY4ZYT7kcBTGW9:-NlPp4hY4ZYT7kcBTGWA:b-ddhznd) ([raw file](https://github.com/sillsdev/web-xforge/blob/605f52dbf94017ff5ea563ecaaec47d657ba96c7/src/SIL.XForge.Scripture/ClientApp/src/app/machine-api/remote-translation-engine.ts#L40)):*
> ```XML
> 
>   async translate(segment: string): Promise<TranslationResult> {
>     const response = await lastValueFrom(
> ```

This is neat. Is there a reason for not using `firstValueFrom`? In this case, I imagine it does not matter since the request will emit a value just once, but maybe you know something I could learn from.
___
*[`src/SIL.XForge.Scripture/ClientApp/src/xforge-common/auth.service.ts` line 167 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/2217#-NlPfu630_CdTVFwjtIe:-NlPtb62Ahu51B5h9QOm:b-am0tsj) ([raw file](https://github.com/sillsdev/web-xforge/blob/605f52dbf94017ff5ea563ecaaec47d657ba96c7/src/SIL.XForge.Scripture/ClientApp/src/xforge-common/auth.service.ts#L167)):*
<details><summary><i>Previously, Nateowami (Nathaniel Paulus) wrote…</i></summary><blockquote>

Is that actually equivalent? It looks like you've dropped a filter for `loggedInState$` value not being nullish.

Also, I'd prefer to touch as little as possible in a PR like this. There's a lot of potential for _really tricky_ things to break in this PR (the tests were hard to figure out, for example), and if something does break, and we bisect and find this commit was at fault, it would be convenient if the number of changes within it are as few as possible. So I like this change, but I think it should be done separately.
</blockquote></details>

Does firstValueFrom resolve if the loggedInState$ has emitted? I see, it is a BehaviourSubject. Then this should work since firstValueFrom should see `loggedInState` emit the moment it subscribes to it.
I agree with Nathaniel, we can come back to make this change at a different time and try to keep this PR with just the changes needed to upgrade to rxjs 7
___
*[`src/SIL.XForge.Scripture/ClientApp/src/xforge-common/auth.service.ts` line 277 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/2217#-NlPj3e7DW57Gnd7-3fK:-NlPqrnw7o3Mxtfw2mrE:bsz8ym2) ([raw file](https://github.com/sillsdev/web-xforge/blob/605f52dbf94017ff5ea563ecaaec47d657ba96c7/src/SIL.XForge.Scripture/ClientApp/src/xforge-common/auth.service.ts#L277)):*
<details><summary><i>Previously, siltomato wrote…</i></summary><blockquote>

I know this is outside the scope of this PR, but this no-bracket `if (signUp)` statement is ambiguous whether `auth0Parameters.login_hint` assignment is intended to be included within the above condition.
</blockquote></details>

When I look at this, I see the no bracket conditional clearly, and anything below that is not included in the conditional. But I've trained myself to see that.
___
*[`src/SIL.XForge.Scripture/ClientApp/src/xforge-common/sharedb-realtime-remote-store.ts` line 244 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/2217#-NlPspfn-UroL7GtNHna:-NlPspfoBolNRrUjQMS4:bt29g5j) ([raw file](https://github.com/sillsdev/web-xforge/blob/605f52dbf94017ff5ea563ecaaec47d657ba96c7/src/SIL.XForge.Scripture/ClientApp/src/xforge-common/sharedb-realtime-remote-store.ts#L244)):*
> ```XML
> 
>   constructor(private readonly doc: Doc) {
>     this.idle$ = fromEvent(this.doc, 'no write pending').pipe(map(() => undefined));
> ```

I was about to suggest using mapTo, but I see that it will be deprecated in version 9. It's nice that editors tell you that now.

**Review by siltomato — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/2217)* status: all files reviewed, 5 unresolved discussions (waiting on @Nateowami and @RaymondLuong3)

___
*[`src/SIL.XForge.Scripture/ClientApp/src/xforge-common/auth.service.ts` line 167 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/2217#-NlPfu630_CdTVFwjtIe:-NlQBv9X-pW59HSeCwf-:bz3gi51) ([raw file](https://github.com/sillsdev/web-xforge/blob/605f52dbf94017ff5ea563ecaaec47d657ba96c7/src/SIL.XForge.Scripture/ClientApp/src/xforge-common/auth.service.ts#L167)):*
<details><summary><i>Previously, RaymondLuong3 (Raymond Luong) wrote…</i></summary><blockquote>

Does firstValueFrom resolve if the loggedInState$ has emitted? I see, it is a BehaviourSubject. Then this should work since firstValueFrom should see `loggedInState` emit the moment it subscribes to it.
I agree with Nathaniel, we can come back to make this change at a different time and try to keep this PR with just the changes needed to upgrade to rxjs 7
</blockquote></details>

The suggested code uses `loggedInState$` (not `_loggedInState$`), which is already filtered for not being nullish.

Totally get not wanting to change it with this PR... just wanted to make a note so it's not forgotten if valuable.
___
*[`src/SIL.XForge.Scripture/ClientApp/src/xforge-common/auth.service.ts` line 208 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/2217#-NlPghkB7VAlA1L6mUXC:-NlQGlBM3gIgMUjx6wfh:bh2tdzi) ([raw file](https://github.com/sillsdev/web-xforge/blob/605f52dbf94017ff5ea563ecaaec47d657ba96c7/src/SIL.XForge.Scripture/ClientApp/src/xforge-common/auth.service.ts#L208)):*
<details><summary><i>Previously, siltomato wrote…</i></summary><blockquote>

Could use `filterNullish()` here and omit the type assertion.
</blockquote></details>

Another item outside the scope of the current PR.
___
*[`src/SIL.XForge.Scripture/ClientApp/src/xforge-common/auth.service.ts` line 277 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/2217#-NlPj3e7DW57Gnd7-3fK:-NlQDcPp10KE28lLe_l5:b-ohsnld) ([raw file](https://github.com/sillsdev/web-xforge/blob/605f52dbf94017ff5ea563ecaaec47d657ba96c7/src/SIL.XForge.Scripture/ClientApp/src/xforge-common/auth.service.ts#L277)):*
<details><summary><i>Previously, RaymondLuong3 (Raymond Luong) wrote…</i></summary><blockquote>

When I look at this, I see the no bracket conditional clearly, and anything below that is not included in the conditional. But I've trained myself to see that.
</blockquote></details>

Yes, I agree that what it actually does is clear upon inspection, but the lack of braces may introduce uncertainty what the original intention was.  For terminating statements like `throw`, `return`, and such, the no-brace `if` seems harmless, but maybe it would be better practice to add the braces in cases like above.

Another item outside the scope of the current PR.

**Review by Nateowami — COMMENTED** [review]
This is ready for re-review

> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/2217#-:-Nm2haE7072kieHDZDwv:b-kcwujf)* status: 12 of 16 files reviewed, 2 unresolved discussions (waiting on @RaymondLuong3 and @siltomato)

___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/machine-api/remote-translation-engine.ts` line 40 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/2217#-NlPp4hY4ZYT7kcBTGW9:-Nm2fQpi2AOyNUojIbYM:b-p70uv0) ([raw file](https://github.com/sillsdev/web-xforge/blob/605f52dbf94017ff5ea563ecaaec47d657ba96c7/src/SIL.XForge.Scripture/ClientApp/src/app/machine-api/remote-translation-engine.ts#L40)):*
<details><summary><i>Previously, RaymondLuong3 (Raymond Luong) wrote…</i></summary><blockquote>

This is neat. Is there a reason for not using `firstValueFrom`? In this case, I imagine it does not matter since the request will emit a value just once, but maybe you know something I could learn from.
</blockquote></details>

Not really. The documentation for the observable returned leaves a lot lacking in my opinion. It should be the only value emitted, so I figured by taking the last value, we're sort of asserting the observable completes.
___
*[`src/SIL.XForge.Scripture/ClientApp/src/xforge-common/auth.service.ts` line 167 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/2217#-NlPfu630_CdTVFwjtIe:-Nm2gWuh-_LGMSY3PVHK:b-896fix) ([raw file](https://github.com/sillsdev/web-xforge/blob/605f52dbf94017ff5ea563ecaaec47d657ba96c7/src/SIL.XForge.Scripture/ClientApp/src/xforge-common/auth.service.ts#L167)):*
<details><summary><i>Previously, siltomato wrote…</i></summary><blockquote>

The suggested code uses `loggedInState$` (not `_loggedInState$`), which is already filtered for not being nullish.

Totally get not wanting to change it with this PR... just wanted to make a note so it's not forgotten if valuable.
</blockquote></details>

Done.
___
*[`src/SIL.XForge.Scripture/ClientApp/src/xforge-common/auth.service.ts` line 169 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/2217#-NlPgMGLANmigDdj946f:-Nm2gY-uAvfDgaNDuJvL:b-896fix) ([raw file](https://github.com/sillsdev/web-xforge/blob/605f52dbf94017ff5ea563ecaaec47d657ba96c7/src/SIL.XForge.Scripture/ClientApp/src/xforge-common/auth.service.ts#L169)):*
<details><summary><i>Previously, siltomato wrote…</i></summary><blockquote>

Possibly rewrite as above.
</blockquote></details>

Done.
___
*[`src/SIL.XForge.Scripture/ClientApp/src/xforge-common/auth.service.ts` line 186 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/2217#-NlPgS1z9EPc1g3P0Pq7:-Nm2gYreA-GWxOt2ClRw:b-896fix) ([raw file](https://github.com/sillsdev/web-xforge/blob/605f52dbf94017ff5ea563ecaaec47d657ba96c7/src/SIL.XForge.Scripture/ClientApp/src/xforge-common/auth.service.ts#L186)):*
<details><summary><i>Previously, siltomato wrote…</i></summary><blockquote>

Possibly rewrite as above.
</blockquote></details>

Done.
___
*[`src/SIL.XForge.Scripture/ClientApp/src/xforge-common/auth.service.ts` line 208 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/2217#-NlPghkB7VAlA1L6mUXC:-Nm2h-yiDyeGUbuoICQi:b-896fix) ([raw file](https://github.com/sillsdev/web-xforge/blob/605f52dbf94017ff5ea563ecaaec47d657ba96c7/src/SIL.XForge.Scripture/ClientApp/src/xforge-common/auth.service.ts#L208)):*
<details><summary><i>Previously, siltomato wrote…</i></summary><blockquote>

Another item outside the scope of the current PR.
</blockquote></details>

Done.

**Review by siltomato — APPROVED** [review]
:lgtm:

> Reviewed 3 of 4 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/2217#-:-Nm6vMaS3RZaSTBc7oBo:bnfp4nl)* status: all files reviewed, 3 unresolved discussions (waiting on @Nateowami and @RaymondLuong3)

**Comment by Nateowami** [comment]
@siltomato Do you have an idea for how this should be tested? My thought was to merge, and if a full regression run still passes, that's as good of testing as we're going to get.

**Review by siltomato — APPROVED** [review]
Makes sense to me.

> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/2217#-:-Nm8NJ742egxNjNai8wb:b-a7ljwd)* status: all files reviewed, 3 unresolved discussions (waiting on @Nateowami and @RaymondLuong3)

**Review by Nateowami — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/2217)* status: all files reviewed, 2 unresolved discussions (waiting on @github-advanced-security[bot] and @RaymondLuong3)

___
*[`src/SIL.XForge.Scripture/ClientApp/src/xforge-common/auth.service.ts` line 20 at r2](https://reviewable.io/reviews/sillsdev/web-xforge/2217#gh-1431898212:-NmA4Unb4ZquLVGTsm_N:b-896fix) ([raw file](https://github.com/sillsdev/web-xforge/blob/69bf3b2b388df2abbba554b755b830d972054812/src/SIL.XForge.Scripture/ClientApp/src/xforge-common/auth.service.ts#L20)):*
<details><summary><i>Previously, github-advanced-security[bot] wrote…</i></summary><blockquote>

## Unused variable, import, function or class

Unused import take.

[Show more details](https://github.com/sillsdev/web-xforge/security/code-scanning/688)
</blockquote></details>

Done.

**Pull request merged**
