### PR TITLE
SF-1762 Add basic RTL support to home pages

### PR DESCRIPTION
**Pull request by Nateowami**
- Set text direction on body element
- Set direction to ltr on pages that are not localized (privacy and terms)
- Fix some padding to work in both ltr and rtl
- Rotate quote icon depending on text direction
- Fix positioning and direction of green arrow

Note that this does not fix everything on the home page, or any other page. On the home page the following areas still need work:
- The section with items "Works with Paratext", "Flexible", "User Engagement"
- The footer.

The learn more page will also need work.

I also added a little spacing between the "log in" and "sign up" buttons.

- - -
This change is [Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1523)

### CODE REVIEW

**Review by RaymondLuong3 — CHANGES_REQUESTED** [review]
Just one minor thing, and then it's good to go.

> Reviewed 7 of 7 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1523#-:-NDi7JPD9clyE5wpyMqF:b-gvws6x)* status: all files reviewed, 1 unresolved discussion (waiting on @Nateowami)

___
*[`src/SIL.XForge.Scripture/wwwroot/scss/_layout.scss` line 127 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/1523#-NDi6Vs_5x35ePOl5L9-:-NDi6Vs_5x35ePOl5L90:b-705318) ([raw file](https://github.com/sillsdev/web-xforge/blob/7f44d63f664d97aa98f57a5be49fe070bc3d47e9/src/SIL.XForge.Scripture/wwwroot/scss/_layout.scss#L127)):*
> ```SCSS
> 
> body[dir='rtl'] .section-title .title::after {
>   border-width: 20px 20px 20px 0;
> ```

There should be another line to make the arrow work
```
@include media-breakpoint-down(sm) {
  border-width: 12px 12px 12px 0
}
```



_Code quote:_
```SCSS
  border-width: 20px 20px 20px 0;
```

**Review by Nateowami — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1523)* status: 5 of 8 files reviewed, 1 unresolved discussion (waiting on @RaymondLuong3)

___
*[`src/SIL.XForge.Scripture/wwwroot/scss/_layout.scss` line 127 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/1523#-NDi6Vs_5x35ePOl5L9-:-NDiDGwd6PDBKIRyfTRq:boj1qgt) ([raw file](https://github.com/sillsdev/web-xforge/blob/7f44d63f664d97aa98f57a5be49fe070bc3d47e9/src/SIL.XForge.Scripture/wwwroot/scss/_layout.scss#L127)):*
<details><summary><i>Previously, RaymondLuong3 (Raymond Luong) wrote…</i></summary><blockquote>

There should be another line to make the arrow work
```
@include media-breakpoint-down(sm) {
  border-width: 12px 12px 12px 0
}
```

</blockquote></details>

Good catch. Done.

**Review by RaymondLuong3 — CHANGES_REQUESTED** [review]
> Reviewed 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1523)* status: all files reviewed, 3 unresolved discussions (waiting on @Nateowami)

___
*[`mongodb/Texts/TextsWithLotsOfEdits.mongodb` line 2 at r2](https://reviewable.io/reviews/sillsdev/web-xforge/1523#-NDiEsEW0OLK4BHzlLLG:-NDiEsEW0OLK4BHzlLLH:byzn5au) ([raw file](https://github.com/sillsdev/web-xforge/blob/d5a489c6160cf95473cbc91fccd342de948e302a/mongodb/Texts/TextsWithLotsOfEdits.mongodb#L2)):*
> ```
> use('xforge')
> ```

Did you mean to include this file in this commit?
___
*[`mongodb/Texts/TextsWithLotsOfEdits.mongodb` line 3 at r2](https://reviewable.io/reviews/sillsdev/web-xforge/1523#-NDiExaP9DIeFpzvER2-:-NDiExaP9DIeFpzvER20:bxw9wuo) ([raw file](https://github.com/sillsdev/web-xforge/blob/d5a489c6160cf95473cbc91fccd342de948e302a/mongodb/Texts/TextsWithLotsOfEdits.mongodb#L3)):*
> ```
> use('xforge')
> 
> // const project = db.sf_projects.findOne({shortName: 'BART'})
> ```

Maybe better to not specifically include this value.



_Code quote:_
```
'BART'})
```
___
*[`mongodb/Texts/TextsWithLotsOfEdits.mongodb` line 12 at r2](https://reviewable.io/reviews/sillsdev/web-xforge/1523#-NDiF3qn2__y5dAMnG26:-NDiF3qn2__y5dAMnG27:bjpj3yx) ([raw file](https://github.com/sillsdev/web-xforge/blob/d5a489c6160cf95473cbc91fccd342de948e302a/mongodb/Texts/TextsWithLotsOfEdits.mongodb#L12)):*
> ```
>   // find ops on this project that were created by a user
>   {$match: {
>     d: /^5e870017e0120c4c875b3b43:/,
> ```

We should not use this value.



_Code quote:_
```
: /^5e870017e0120c4c875b3b43:/,
```

**Review by Nateowami — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1523)* status: 7 of 8 files reviewed, 3 unresolved discussions (waiting on @Nateowami and @RaymondLuong3)

___
*[`mongodb/Texts/TextsWithLotsOfEdits.mongodb` line 2 at r2](https://reviewable.io/reviews/sillsdev/web-xforge/1523#-NDiEsEW0OLK4BHzlLLG:-NDid3YeASC4KGYOuUu7:bww98wo) ([raw file](https://github.com/sillsdev/web-xforge/blob/d5a489c6160cf95473cbc91fccd342de948e302a/mongodb/Texts/TextsWithLotsOfEdits.mongodb#L2)):*
<details><summary><i>Previously, RaymondLuong3 (Raymond Luong) wrote…</i></summary><blockquote>

Did you mean to include this file in this commit?
</blockquote></details>

Oops, no, I did not mean to include this.

**Review by RaymondLuong3 — APPROVED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1523)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @Nateowami)

**Pull request merged**
