### PR TITLE
SF-2659 Fix errors from training occurring after a project is deleted

### PR DESCRIPTION
**Pull request by pmachapman**
If a project is created with translation suggestions enabled, then the project is deleted, the training job will crash with one of the following errors:

- System.NullReferenceException /opt/buildagent/work/ee130f1d7ff31933/src/SIL.XForge.Scripture/Services/SFTextCorpusFactory.cs:56
- System.NullReferenceException /opt/buildagent/work/ee130f1d7ff31933/src/SIL.XForge.Scripture/Services/MachineProjectService.cs:147
- System.ArgumentNullException /opt/buildagent/work/ee130f1d7ff31933/src/SIL.XForge.Scripture/Services/MachineProjectService.cs:974
- SIL.XForge.Services.DataNotFoundException /opt/buildagent/work/ee130f1d7ff31933/src/SIL.XForge.Scripture/Services/MachineProjectService.cs:68
- SIL.XForge.Services.DataNotFoundException /opt/buildagent/work/ee130f1d7ff31933/src/SIL.XForge.Scripture/Services/MachineProjectService.cs:96

These errors do not result in an error that is visible to the user, but these errors are logged in bugsnag. This state has occurred since [SF-2647](https://jira.sil.org/browse/SF-2647) was merged into master/sf-qa.

- - -
This change is [Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/2392)

### CODE REVIEW

**Review by nigel-wells — CHANGES_REQUESTED** [review]
Just one tweak I think needed here.
I looked at the fix in SF-2467 - I don't follow how this error would suddenly get introduced as a result of setting the attribute in Quill?

> Reviewed 2 of 3 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/2392#-:-NvoFN7eCuw-XEcag97W:bhzl251)* status: all files reviewed, 3 unresolved discussions (waiting on @pmachapman)

___
*[`src/SIL.XForge.Scripture/Services/MachineProjectService.cs` line 137 at r2](https://reviewable.io/reviews/sillsdev/web-xforge/2392#-Nvo6XFy9--aFrd7gagP:-Nvo6XFy9--aFrd7gagQ:b4yrlu2) ([raw file](https://github.com/sillsdev/web-xforge/blob/738f9f0d9ed29c39a2c3f90522155e00d00c51d5/src/SIL.XForge.Scripture/Services/MachineProjectService.cs#L137)):*
> ```Smalltalk
> 
>                 // This error can occur if the project is deleted while the build is running
>                 if (projectDoc.Data is null)
> ```

This is the fix isn't it? I just want to get it clear in my head the situation.

Further up we asserted that `projectDoc.IsLoaded` was true. Is this in the event that it is deleted while we wait on `TranslationEngineExistsAsync`? How long does `TranslationEngineExistsAsync` typically take to respond out of interest?
___
*[`src/SIL.XForge.Scripture/Services/MachineProjectService.cs` line 153 at r2](https://reviewable.io/reviews/sillsdev/web-xforge/2392#-Nvo6I6bEpg3YZUm7Yc1:-Nvo6I6bEpg3YZUm7Yc2:baebdi4) ([raw file](https://github.com/sillsdev/web-xforge/blob/738f9f0d9ed29c39a2c3f90522155e00d00c51d5/src/SIL.XForge.Scripture/Services/MachineProjectService.cs#L153)):*
> ```Smalltalk
> 
>                 // This error can occur if the project is deleted while the build is running
>                 if (projectDoc.Data is null)
> ```

I assume this is a duplication that isn't needed? Otherwise, how does the `Data` suddenly become null?

**Review by pmachapman — COMMENTED** [review]
Sorry it was SF-2647. I have corrected it.

> Dismissed @github-advanced-security[bot] from a discussion.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/2392#-:-Nw1YTwQ1V0Afzg0KLbB:b-hwirza)* status: all files reviewed, 2 unresolved discussions (waiting on @nigel-wells)

___
*[`src/SIL.XForge.Scripture/Services/MachineProjectService.cs` line 137 at r2](https://reviewable.io/reviews/sillsdev/web-xforge/2392#-Nvo6XFy9--aFrd7gagP:-Nw1_36A9esbdlCBzqKh:b-dc3bh1) ([raw file](https://github.com/sillsdev/web-xforge/blob/738f9f0d9ed29c39a2c3f90522155e00d00c51d5/src/SIL.XForge.Scripture/Services/MachineProjectService.cs#L137)):*
> Is this in the event that it is deleted while we wait on `TranslationEngineExistsAsync`?

Yes.

> How long does `TranslationEngineExistsAsync` typically take to respond out of interest?

In  my tests it is 10's of milliseconds.
___
*[`src/SIL.XForge.Scripture/Services/MachineProjectService.cs` line 153 at r2](https://reviewable.io/reviews/sillsdev/web-xforge/2392#-Nvo6I6bEpg3YZUm7Yc1:-Nw1_oka9YGoHqAFwFGf:bnhrceq) ([raw file](https://github.com/sillsdev/web-xforge/blob/738f9f0d9ed29c39a2c3f90522155e00d00c51d5/src/SIL.XForge.Scripture/Services/MachineProjectService.cs#L153)):*
<details><summary><i>Previously, nigel-wells (Nigel Wells) wrote…</i></summary><blockquote>

I assume this is a duplication that isn't needed? Otherwise, how does the `Data` suddenly become null?
</blockquote></details>

It seems that the object was deleted between the loading of the object from the realtime server, and the execution of this line - see https://app.bugsnag.com/sil-international/scripture-forge-v2-plus/errors/660795b3b9414a00083444b1

**Review by nigel-wells — CHANGES_REQUESTED** [review]
Thanks for that. Are there any side effects from deleting files from Serval that might flow back and delete a project? Or it is just coincidence that SF-2647 caused it?

> Reviewed 2 of 3 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/2392#-:-Nw2UldDDfgUO56wvxPX:b-q3pl3m)* status: 2 of 3 files reviewed, 1 unresolved discussion (waiting on @pmachapman)

___
*[`src/SIL.XForge.Scripture/Services/MachineProjectService.cs` line 137 at r2](https://reviewable.io/reviews/sillsdev/web-xforge/2392#-Nvo6XFy9--aFrd7gagP:-Nw2TW2X9GoPjhUQMaY_:b-zcjvte) ([raw file](https://github.com/sillsdev/web-xforge/blob/738f9f0d9ed29c39a2c3f90522155e00d00c51d5/src/SIL.XForge.Scripture/Services/MachineProjectService.cs#L137)):*
<details><summary><i>Previously, pmachapman (Peter Chapman) wrote…</i></summary><blockquote>

> Is this in the event that it is deleted while we wait on `TranslationEngineExistsAsync`?

Yes.

> How long does `TranslationEngineExistsAsync` typically take to respond out of interest?

In  my tests it is 10's of milliseconds.
</blockquote></details>

Thanks
___
*[`src/SIL.XForge.Scripture/Services/MachineProjectService.cs` line 153 at r2](https://reviewable.io/reviews/sillsdev/web-xforge/2392#-Nvo6I6bEpg3YZUm7Yc1:-Nw2Szob2tMmxeYB9ttZ:blxfnub) ([raw file](https://github.com/sillsdev/web-xforge/blob/738f9f0d9ed29c39a2c3f90522155e00d00c51d5/src/SIL.XForge.Scripture/Services/MachineProjectService.cs#L153)):*
<details><summary><i>Previously, pmachapman (Peter Chapman) wrote…</i></summary><blockquote>

It seems that the object was deleted between the loading of the object from the realtime server, and the execution of this line - see https://app.bugsnag.com/sil-international/scripture-forge-v2-plus/errors/660795b3b9414a00083444b1
</blockquote></details>

So a project is getting deleted while we `await projectDoc.SubmitJson0OpAsync`? That's seems like incredibly bad timing. Is there a possibility that `await projectDoc.SubmitJson0OpAsync` is what is causing `projectDoc.Data` to become null?

**Review by pmachapman — COMMENTED** [review]
> Are there any side effects from deleting files from Serval that might flow back and delete a project?

No, not at all.

> Or it is just coincidence that SF-2647 caused it?

It is not a coincidence - SF-2647 split the sync/connect from the build. Previously a connect to project had not completed until its first build had started. This made connects take a vey long time, as individual text files are uploaded for each chapter for SMT builds. SF-2647 means that the UI is notified that the project has connected and then hangfire starts the process of creating the first build (all while the user can access or delete the project via the frontend)

On QA, projects were being created then deleted rapidly (via automation I believe). In that timeframe, the build was trying to get underway, and so getting the rug pulled out from under its feet by the project being deleted mid-upload to Serval.

> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/2392#-:-Nw2ctr36Or2WACKDem8:b1df151)* status: 2 of 3 files reviewed, 1 unresolved discussion (waiting on @nigel-wells)

___
*[`src/SIL.XForge.Scripture/Services/MachineProjectService.cs` line 153 at r2](https://reviewable.io/reviews/sillsdev/web-xforge/2392#-Nvo6I6bEpg3YZUm7Yc1:-Nw2e0eA7qeR6zvvzEfk:b9hzco0) ([raw file](https://github.com/sillsdev/web-xforge/blob/738f9f0d9ed29c39a2c3f90522155e00d00c51d5/src/SIL.XForge.Scripture/Services/MachineProjectService.cs#L153)):*
<details><summary><i>Previously, nigel-wells (Nigel Wells) wrote…</i></summary><blockquote>

So a project is getting deleted while we `await projectDoc.SubmitJson0OpAsync`? That's seems like incredibly bad timing. Is there a possibility that `await projectDoc.SubmitJson0OpAsync` is what is causing `projectDoc.Data` to become null?
</blockquote></details>

It is not so much that `SubmitJson0OpAsync` is causing Data to be set to null, but more then that operation returns it gets the updated copy from the realtime server. If the doc has been deleted, the realtime server returns null, and so the Data is updated with the new correct value. (See `Document<T>.UpdateFromSnapshot()`)

**Review by nigel-wells — APPROVED** [review]
Gotcha - thanks for the extra info!
:lgtm:

> Reviewed 1 of 3 files at r3.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/2392#-:-Nw2gGF4-6qIc-3M7Gmn:b9g5k2s)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @pmachapman)

___
*[`src/SIL.XForge.Scripture/Services/MachineProjectService.cs` line 153 at r2](https://reviewable.io/reviews/sillsdev/web-xforge/2392#-Nvo6I6bEpg3YZUm7Yc1:-Nw2gmdu1llClGvTDdQl:b-9i9y3w) ([raw file](https://github.com/sillsdev/web-xforge/blob/738f9f0d9ed29c39a2c3f90522155e00d00c51d5/src/SIL.XForge.Scripture/Services/MachineProjectService.cs#L153)):*
<details><summary><i>Previously, pmachapman (Peter Chapman) wrote…</i></summary><blockquote>

It is not so much that `SubmitJson0OpAsync` is causing Data to be set to null, but more then that operation returns it gets the updated copy from the realtime server. If the doc has been deleted, the realtime server returns null, and so the Data is updated with the new correct value. (See `Document<T>.UpdateFromSnapshot()`)
</blockquote></details>

I see - and understand better now with your other explanation as well as to how this is actually caused.

**Pull request merged**
