### PR TITLE
SF-2016 Convert 'write status' component to material

### PR DESCRIPTION
**Pull request by siltomato**
This change is [Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1863)

### CODE REVIEW

**Review by RaymondLuong3 — COMMENTED** [review]
I'm getting warning icons appearing when I change settings on the settings page. I wonder if it has to do with updating the formGroup type from untypedFormGroup. Are you seeing this too?

> Reviewed 5 of 5 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1863#-:-NWE-PVX0HX26myn6l3Y:bfvqb2u)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @siltomato)

**Review by siltomato — COMMENTED** [review]
I've not been able to reproduce that.  Anything specific I need to do to reproduce?

> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1863#-:-NWE3lEsBimXMnWZYERl:b-ockcow)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @siltomato)

**Review by Nateowami — COMMENTED** [review]
@RaymondLuong3 This branch is behind master, which has had a model change recently, so I would not be surprised to see an error. Does the network tab or the backend output show any errors?

> Reviewed 4 of 5 files at r1.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1863#-:-NWE5T8zDDWA7Q9CObmF:byj0y3i)* status: all files reviewed, 1 unresolved discussion (waiting on @siltomato)

___
*[`src/SIL.XForge.Scripture/ClientApp/src/xforge-common/write-status/write-status.component.html` line 8 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/1863#-NWE504ZBHLTcH-8dcfT:-NWE504ZBHLTcH-8dcfU:b-u72qr5) ([raw file](https://github.com/sillsdev/web-xforge/blob/267bdfc32d7c10560723f960a33a43c33ffeb431/src/SIL.XForge.Scripture/ClientApp/src/xforge-common/write-status/write-status.component.html#L8)):*
> ```HTML
> ></mat-spinner>
> <mat-icon *ngIf="state === ElementState.Submitted && !formGroup?.errors" class="check-icon">done</mat-icon>
> <mat-icon *ngIf="state === ElementState.Error && !formGroup?.errors" class="error-icon" color="warn">error</mat-icon>
> ```

Wouldn't it make more sense to set `color="error"`? As far as I can tell at present warn and error are the same color, but if we update the theme they may not be.

**Review by RaymondLuong3 — COMMENTED** [review]
Ok, yes it looks like the model changes was the culprit. It is working fine now.

> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1863#-:-NWEF4ZlAB3z5P4Wt14J:b-e3cxzg)* status: all files reviewed, 1 unresolved discussion (waiting on @siltomato)

**Review by siltomato — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1863)* status: 4 of 5 files reviewed, 1 unresolved discussion (waiting on @Nateowami and @RaymondLuong3)

___
*[`src/SIL.XForge.Scripture/ClientApp/src/xforge-common/write-status/write-status.component.html` line 8 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/1863#-NWE504ZBHLTcH-8dcfT:-NWEP8VO3ZnkfNnQxXgp:bpbr6la) ([raw file](https://github.com/sillsdev/web-xforge/blob/267bdfc32d7c10560723f960a33a43c33ffeb431/src/SIL.XForge.Scripture/ClientApp/src/xforge-common/write-status/write-status.component.html#L8)):*
<details><summary><i>Previously, Nateowami (Nathaniel Paulus) wrote…</i></summary><blockquote>

Wouldn't it make more sense to set `color="error"`? As far as I can tell at present warn and error are the same color, but if we update the theme they may not be.
</blockquote></details>

`color="error"` makes more sense to me.  I didn't see it as a valid option to assign to the `color` property which is supposed to be of type `ThemePalette`, but it works.
`type ThemePalette = 'primary' | 'accent' | 'warn' | undefined;`

**Review by Nateowami — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1863)* status: 4 of 5 files reviewed, 1 unresolved discussion (waiting on @RaymondLuong3 and @siltomato)

___
*[`src/SIL.XForge.Scripture/ClientApp/src/xforge-common/write-status/write-status.component.html` line 8 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/1863#-NWE504ZBHLTcH-8dcfT:-NWET5zE73vv7g5hfuKy:b-4wujik) ([raw file](https://github.com/sillsdev/web-xforge/blob/267bdfc32d7c10560723f960a33a43c33ffeb431/src/SIL.XForge.Scripture/ClientApp/src/xforge-common/write-status/write-status.component.html#L8)):*
<details><summary><i>Previously, siltomato wrote…</i></summary><blockquote>

`color="error"` makes more sense to me.  I didn't see it as a valid option to assign to the `color` property which is supposed to be of type `ThemePalette`, but it works.
`type ThemePalette = 'primary' | 'accent' | 'warn' | undefined;`
</blockquote></details>

Hmm. It's a bit strange that it works then. I wasn't looking at the docs and was rather just seeing what worked. I can't find where this is clearly defined, but all the examples show only primary, accent, and warn. So maybe better to stick to a clearly defined one that we know will continue to work.

Sorry; I may have inadvertently mislead you.

**Review by siltomato — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1863)* status: 4 of 5 files reviewed, 1 unresolved discussion (waiting on @Nateowami and @RaymondLuong3)

**Review by siltomato — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1863)* status: 4 of 5 files reviewed, 1 unresolved discussion (waiting on @Nateowami and @RaymondLuong3)

___
*[`src/SIL.XForge.Scripture/ClientApp/src/xforge-common/write-status/write-status.component.html` line 8 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/1863#-NWE504ZBHLTcH-8dcfT:-NWFxkZM9abP4cG1HAxu:bxmf2s) ([raw file](https://github.com/sillsdev/web-xforge/blob/267bdfc32d7c10560723f960a33a43c33ffeb431/src/SIL.XForge.Scripture/ClientApp/src/xforge-common/write-status/write-status.component.html#L8)):*
<details><summary><i>Previously, Nateowami (Nathaniel Paulus) wrote…</i></summary><blockquote>

Hmm. It's a bit strange that it works then. I wasn't looking at the docs and was rather just seeing what worked. I can't find where this is clearly defined, but all the examples show only primary, accent, and warn. So maybe better to stick to a clearly defined one that we know will continue to work.

Sorry; I may have inadvertently mislead you.
</blockquote></details>

No prob.  I changed it back.

**Review by Nateowami — APPROVED** [review]
:lgtm:

> Reviewed 1 of 5 files at r1, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1863#-:-NWGOqLHCPzCuh7lUAeV:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @siltomato)

**Pull request merged**
