### PR TITLE
SF-1873 Add messages to sync progress

### PR DESCRIPTION
**Pull request by kylebuss**
This PR adds sync messages to the sync progress component to provide the user with better visibility into the status of where the sync is at.

- - -
This change is [Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/2837)

### CODE REVIEW

**Comment by kylebuss** [comment]
*[`src/SIL.XForge.Scripture/Models/ProgressState.cs` line 10 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/2837#-OAwpoDY0S80OirxzXV1:-OAwpoDY0S80OirxzXV2:bwjgsf1) ([raw file](https://github.com/sillsdev/web-xforge/blob/564282578bdac13be2f86566ef401fce29344e69/src/SIL.XForge.Scripture/Models/ProgressState.cs#L10)):*
> ```Smalltalk
>     public double ProgressValue { get; set; }
>     public int SyncPhase { get; set; }
>     public double SyncProgress { get; set; }
> ```

Just realized, I could format the `stage_phase_progress` string on the back-end in the `ProgressString` if that would be preferred?



_Code quote:_
```Smalltalk
    public int SyncPhase { get; set; }
    public double SyncProgress { get; set; }
```

**Review by RaymondLuong3 — CHANGES_REQUESTED** [review]
I like the feel of this update. It makes me think that I can see into the things that are being updated. Nice touch! I have some comments. Let me know if you would like to pair to discuss some of this.

> Reviewed 7 of 7 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/2837#-:-OAxPbghAYOXV7aN-vBJ:bugcejz)* status: all files reviewed, 6 unresolved discussions (waiting on @kylebuss)

___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/sync/sync-progress/sync-progress.component.ts` line 18 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/2837#-OAxE7cgBsvOIUxA4NAF:-OAxE7cgBsvOIUxA4NAG:b5a7mgy) ([raw file](https://github.com/sillsdev/web-xforge/blob/564282578bdac13be2f86566ef401fce29344e69/src/SIL.XForge.Scripture/ClientApp/src/app/sync/sync-progress/sync-progress.component.ts#L18)):*
> ```XML
>     public progressValue: number,
>     public progressString?: string,
>     public syncPhase?: number,
> ```

The syncPhase property should be and enum type similar to the SyncPhase enum in `ParatextSyncRunner`.



_Code quote:_
```XML
    public syncPhase?: number,
```
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/sync/sync-progress/sync-progress.component.ts` line 31 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/2837#-OAxBNvp99jpmX2A04l5:-OAxBNvq8sIVq7I1URe2:bljp5pt) ([raw file](https://github.com/sillsdev/web-xforge/blob/564282578bdac13be2f86566ef401fce29344e69/src/SIL.XForge.Scripture/ClientApp/src/app/sync/sync-progress/sync-progress.component.ts#L31)):*
> ```XML
>   @Output() inProgress: EventEmitter<boolean> = new EventEmitter<boolean>();
> 
>   private progressPercent$ = new BehaviorSubject<number>(0);
> ```

This private field should be put with the others below the public fields.



_Code quote:_
```XML
  private progressPercent$ = new BehaviorSubject<number>(0);
```
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/sync/sync-progress/sync-progress.component.ts` line 35 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/2837#-OAxC3xxDQtZNariaQVn:-OAxC3xxDQtZNariaQVo:b-ud8bpl) ([raw file](https://github.com/sillsdev/web-xforge/blob/564282578bdac13be2f86566ef401fce29344e69/src/SIL.XForge.Scripture/ClientApp/src/app/sync/sync-progress/sync-progress.component.ts#L35)):*
> ```XML
>   syncProgress: number | undefined;
>   stagePercentage: string = '0.0';
>   projectType: string = '';
> ```

We have a `TextType` type which can by either source or target. It is not quite the same thing here, but FYI.



_Code quote:_
```XML
  projectType: string = '';
```
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/sync/sync-progress/sync-progress.component.ts` line 132 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/2837#-OAxKAUOAEpePJ2BSNVR:-OAxKAUOAEpePJ2BSNVS:bcar7lo) ([raw file](https://github.com/sillsdev/web-xforge/blob/564282578bdac13be2f86566ef401fce29344e69/src/SIL.XForge.Scripture/ClientApp/src/app/sync/sync-progress/sync-progress.component.ts#L132)):*
> ```XML
>     this.syncProgress = progressState.syncProgress != null ? Math.floor(progressState.syncProgress) : 0;
>     this.stagePercentage =
>       progressState.syncProgress != null ? ((progressState.syncProgress - this.syncProgress) * 100).toFixed(2) : '0.00';
> ```

I would not use decimals for the progress. Integers if better here.



_Code quote:_
```XML
    this.stagePercentage =
      progressState.syncProgress != null ? ((progressState.syncProgress - this.syncProgress) * 100).toFixed(2) : '0.00';
```
___
*[`src/SIL.XForge.Scripture/ClientApp/src/assets/i18n/non_checking_en.json` line 529 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/2837#-OAxFJ7N9VaezT7yOi7z:-OAxFJ7N9VaezT7yOi8-:bj53l9e) ([raw file](https://github.com/sillsdev/web-xforge/blob/564282578bdac13be2f86566ef401fce29344e69/src/SIL.XForge.Scripture/ClientApp/src/assets/i18n/non_checking_en.json#L529)):*
> ```JSON
>     "supported_back_translation_languages_dialog_header": "Supported Back Translation Languages"
>   },
>   "sync": {
> ```

I think this is too fine-grained and not likely to be as helpful as it could be, but I can see that these align nicely with the expected output from the backend. I don't like how tightly coupled this is to the expected report from the backend since it means that any changes to the backend reported will require front-end translations to handle it.
What do you think about just adding a since label for each SyncPhase and for the ones that benefit from a percentage value, we can include that. So then the stages keys would look like `stage_0, stage_1`, etc. I am open to discussion
___
*[`src/SIL.XForge.Scripture/Models/ProgressState.cs` line 9 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/2837#-OAxF1vB15gzjhUGbeMZ:-OAxF1vB15gzjhUGbeM_:b-qtgyrh) ([raw file](https://github.com/sillsdev/web-xforge/blob/564282578bdac13be2f86566ef401fce29344e69/src/SIL.XForge.Scripture/Models/ProgressState.cs#L9)):*
> ```Smalltalk
>     public string? ProgressString { get; set; }
>     public double ProgressValue { get; set; }
>     public int SyncPhase { get; set; }
> ```

I wonder if this should be the SyncPhase enum type? int is probably fine here.



_Code quote:_
```Smalltalk
   public int SyncPhase { get; set; }
```
___
*[`src/SIL.XForge.Scripture/Models/ProgressState.cs` line 10 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/2837#-OAwpoDY0S80OirxzXV1:-OAxEjk95JZXs_t2vepL:b-irqbv7) ([raw file](https://github.com/sillsdev/web-xforge/blob/564282578bdac13be2f86566ef401fce29344e69/src/SIL.XForge.Scripture/Models/ProgressState.cs#L10)):*
<details><summary><i>Previously, kylebuss (Kyle Buss) wrote…</i></summary><blockquote>

Just realized, I could format the `stage_phase_progress` string on the back-end in the `ProgressString` if that would be preferred?
</blockquote></details>

If we leave this as is, I think it gives us some flexibility in how we report things to the user (i.e. if we wanted to skip some reporting steps). I am happy to leave it as is.

**Review by kylebuss — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/2837)* status: 2 of 8 files reviewed, 5 unresolved discussions (waiting on @RaymondLuong3)

___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/sync/sync-progress/sync-progress.component.ts` line 18 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/2837#-OAxE7cgBsvOIUxA4NAF:-OAyACd-0ZbGSjpWhxtQ:b-896fix) ([raw file](https://github.com/sillsdev/web-xforge/blob/564282578bdac13be2f86566ef401fce29344e69/src/SIL.XForge.Scripture/ClientApp/src/app/sync/sync-progress/sync-progress.component.ts#L18)):*
<details><summary><i>Previously, RaymondLuong3 (Raymond Luong) wrote…</i></summary><blockquote>

The syncPhase property should be and enum type similar to the SyncPhase enum in `ParatextSyncRunner`.
</blockquote></details>

Done.
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/sync/sync-progress/sync-progress.component.ts` line 31 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/2837#-OAxBNvp99jpmX2A04l5:-OAxpDpd1S7OQDhOuQdL:b-i3q08r) ([raw file](https://github.com/sillsdev/web-xforge/blob/564282578bdac13be2f86566ef401fce29344e69/src/SIL.XForge.Scripture/ClientApp/src/app/sync/sync-progress/sync-progress.component.ts#L31)):*
<details><summary><i>Previously, RaymondLuong3 (Raymond Luong) wrote…</i></summary><blockquote>

This private field should be put with the others below the public fields.
</blockquote></details>

Done moved above `syncProgress` observables that rely on it being initialized.
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/sync/sync-progress/sync-progress.component.ts` line 132 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/2837#-OAxKAUOAEpePJ2BSNVR:-OAyAFvYBI_bpvV-4-p0:b-896fix) ([raw file](https://github.com/sillsdev/web-xforge/blob/564282578bdac13be2f86566ef401fce29344e69/src/SIL.XForge.Scripture/ClientApp/src/app/sync/sync-progress/sync-progress.component.ts#L132)):*
<details><summary><i>Previously, RaymondLuong3 (Raymond Luong) wrote…</i></summary><blockquote>

I would not use decimals for the progress. Integers if better here.
</blockquote></details>

Done.
___
*[`src/SIL.XForge.Scripture/ClientApp/src/assets/i18n/non_checking_en.json` line 529 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/2837#-OAxFJ7N9VaezT7yOi7z:-OAyAGoNADG_pHfGdthJ:bcq7k73) ([raw file](https://github.com/sillsdev/web-xforge/blob/564282578bdac13be2f86566ef401fce29344e69/src/SIL.XForge.Scripture/ClientApp/src/assets/i18n/non_checking_en.json#L529)):*
<details><summary><i>Previously, RaymondLuong3 (Raymond Luong) wrote…</i></summary><blockquote>

I think this is too fine-grained and not likely to be as helpful as it could be, but I can see that these align nicely with the expected output from the backend. I don't like how tightly coupled this is to the expected report from the backend since it means that any changes to the backend reported will require front-end translations to handle it.
What do you think about just adding a since label for each SyncPhase and for the ones that benefit from a percentage value, we can include that. So then the stages keys would look like `stage_0, stage_1`, etc. I am open to discussion
</blockquote></details>

Done That was a concern of mine as well. I've cleaned it up a bit, let me know what you think!

**Review by RaymondLuong3 — CHANGES_REQUESTED** [review]
> Reviewed 6 of 6 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/2837)* status: all files reviewed, 4 unresolved discussions (waiting on @kylebuss)

___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/sync/sync-progress/sync-progress.component.ts` line 31 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/2837#-OAxBNvp99jpmX2A04l5:-OAyIES_7s6rL35u_wer:b9qxiic) ([raw file](https://github.com/sillsdev/web-xforge/blob/564282578bdac13be2f86566ef401fce29344e69/src/SIL.XForge.Scripture/ClientApp/src/app/sync/sync-progress/sync-progress.component.ts#L31)):*
<details><summary><i>Previously, kylebuss (Kyle Buss) wrote…</i></summary><blockquote>

Done moved above `syncProgress` observables that rely on it being initialized.
</blockquote></details>

Oh yes, that's right. Can you move it above the comment for `syncProgressPercent$`
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/sync/sync-progress/sync-progress.component.ts` line 149 at r2](https://reviewable.io/reviews/sillsdev/web-xforge/2837#-OAyHRvf-OV88qnq_ZRk:-OAyHRvf-OV88qnq_ZRl:b91ugx8) ([raw file](https://github.com/sillsdev/web-xforge/blob/e8f05f19256e97c0133b65d899ea572c5a945b18/src/SIL.XForge.Scripture/ClientApp/src/app/sync/sync-progress/sync-progress.component.ts#L149)):*
> ```XML
>     this.phasePercentage =
>       progressState.syncProgress != null ? Math.round((progressState.syncProgress - this.syncProgress) * 100) : 0;
>     console.log(progressState.syncPhase);
> ```

This should be removed?



_Code quote:_
```XML
    console.log(progressState.syncPhase);
```
___
*[`src/SIL.XForge.Scripture/ClientApp/src/assets/i18n/non_checking_en.json` line 529 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/2837#-OAxFJ7N9VaezT7yOi7z:-OAyIl2iDrjMVIwa1Olb:b-qik144) ([raw file](https://github.com/sillsdev/web-xforge/blob/564282578bdac13be2f86566ef401fce29344e69/src/SIL.XForge.Scripture/ClientApp/src/assets/i18n/non_checking_en.json#L529)):*
<details><summary><i>Previously, kylebuss (Kyle Buss) wrote…</i></summary><blockquote>

Done That was a concern of mine as well. I've cleaned it up a bit, let me know what you think!
</blockquote></details>

Nice. That looks much better.
___
*[`src/SIL.XForge.Scripture/ClientApp/src/assets/i18n/non_checking_en.json` line 536 at r2](https://reviewable.io/reviews/sillsdev/web-xforge/2837#-OAyGw9P6zxu-r2IG_04:-OAyGw9P6zxu-r2IG_05:b5i55c2) ([raw file](https://github.com/sillsdev/web-xforge/blob/e8f05f19256e97c0133b65d899ea572c5a945b18/src/SIL.XForge.Scripture/ClientApp/src/assets/i18n/non_checking_en.json#L536)):*
> ```JSON
>     "log_in_to_paratext": "Log in to Paratext",
>     "never_been_synced": "Never been synced",
>     "phase_1": "Connecting to {{projectType}} project",
> ```

This should be starting at phase_0 just to keep it in line with the phases on the backend. No need to modify it to start at 1. Also, you can lowercase the `percent`



_Code quote:_
```JSON
    "phase_1": "Connecting to {{projectType}} project",
```
___
*[`src/SIL.XForge.Scripture/ClientApp/src/assets/i18n/non_checking_en.json` line 541 at r2](https://reviewable.io/reviews/sillsdev/web-xforge/2837#-OAyHBOU6SnMYVpM_diT:-OAyHBOU6SnMYVpM_diU:b-hrcbo8) ([raw file](https://github.com/sillsdev/web-xforge/blob/e8f05f19256e97c0133b65d899ea572c5a945b18/src/SIL.XForge.Scripture/ClientApp/src/assets/i18n/non_checking_en.json#L541)):*
> ```JSON
>     "phase_2_Percent": "Checking Paratext updates to biblical terms {{progressPercent}}%",
>     "phase_3": "Update Paratext biblical terms",
>     "phase_3_Percent": "Update Paratext biblical terms {{progressPercent}}%",
> ```

Nit: You should keep the language consistent (i.e. us 'Updating ...")



_Code quote:_
```JSON
    "phase_2": "Update {{projectType}} Paratext books and notes",
    "phase_2_Percent": "Checking Paratext updates to biblical terms {{progressPercent}}%",
    "phase_3": "Update Paratext biblical terms",
    "phase_3_Percent": "Update Paratext biblical terms {{progressPercent}}%",
```

**Review by kylebuss — COMMENTED** [review]
Thanks. Code updated.

> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/2837#-:-OB0dQcu4N3R1uqnBqnO:b-f1hl96)* status: all files reviewed, 3 unresolved discussions (waiting on @RaymondLuong3)

___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/sync/sync-progress/sync-progress.component.ts` line 31 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/2837#-OAxBNvp99jpmX2A04l5:-OB0ZzNz9t1nscu8j1mw:b-896fix) ([raw file](https://github.com/sillsdev/web-xforge/blob/564282578bdac13be2f86566ef401fce29344e69/src/SIL.XForge.Scripture/ClientApp/src/app/sync/sync-progress/sync-progress.component.ts#L31)):*
<details><summary><i>Previously, RaymondLuong3 (Raymond Luong) wrote…</i></summary><blockquote>

Oh yes, that's right. Can you move it above the comment for `syncProgressPercent$`
</blockquote></details>

Done.
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/sync/sync-progress/sync-progress.component.ts` line 149 at r2](https://reviewable.io/reviews/sillsdev/web-xforge/2837#-OAyHRvf-OV88qnq_ZRk:-OB0_2oO8oTQUUSG5s3v:b-896fix) ([raw file](https://github.com/sillsdev/web-xforge/blob/e8f05f19256e97c0133b65d899ea572c5a945b18/src/SIL.XForge.Scripture/ClientApp/src/app/sync/sync-progress/sync-progress.component.ts#L149)):*
<details><summary><i>Previously, RaymondLuong3 (Raymond Luong) wrote…</i></summary><blockquote>

This should be removed?
</blockquote></details>

Done.
___
*[`src/SIL.XForge.Scripture/ClientApp/src/assets/i18n/non_checking_en.json` line 536 at r2](https://reviewable.io/reviews/sillsdev/web-xforge/2837#-OAyGw9P6zxu-r2IG_04:-OB0a25KCcoOsWt0gtAw:b-896fix) ([raw file](https://github.com/sillsdev/web-xforge/blob/e8f05f19256e97c0133b65d899ea572c5a945b18/src/SIL.XForge.Scripture/ClientApp/src/assets/i18n/non_checking_en.json#L536)):*
<details><summary><i>Previously, RaymondLuong3 (Raymond Luong) wrote…</i></summary><blockquote>

This should be starting at phase_0 just to keep it in line with the phases on the backend. No need to modify it to start at 1. Also, you can lowercase the `percent`
</blockquote></details>

Done.

**Comment by Nateowami** [comment]
This is great. A couple issues I see:

I'm seeing this logged to the console during a sync:
```
Missing translation for 'sync.phase_4'
Missing translation for 'sync.phase_5'
Missing translation for 'sync.phase_6'
```

It's a little bit odd that there are two messages, one above the progress indicator, and one below. Perhaps the detailed message should be moved up to replace "Your project is being synchronized..."? Also, it would be nice if it indicated _which_ project is syncing. It may seem obvious, but syncing projects syncs the source as well, and there's no clear indication of that.

**Review by RaymondLuong3 — APPROVED** [review]
I like the way that looks. This is a sweet improvement. I am not seeing any console errors on this current iteration. :shipit: 

> Reviewed 5 of 5 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/2837#-:-OB6JeFN0QmgBwHoVMQ0:b-nnzdy2)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @kylebuss)

**Pull request merged**
