### PR TITLE
SF-2692 Fix warning messages for translators on the generate draft page

### PR DESCRIPTION
**Pull request by kylebuss**
Fixed the warning message that displays when Drafting as a Translator to contact Paratext Adminstrator rather than provide a link to the Settings Page.

**There are 4 cases:**
1. No training source
2. Training language is the same as source language
3. Alternate training source is different from source language.
4. Additional training source is different from alternate training source.

- - -
This change is [Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/2581)

### CODE REVIEW

**Review by RaymondLuong3 — CHANGES_REQUESTED** [review]
Nice work. Happy to see these changes. The tests are sufficient.

Your PR titles are getting better. The message should describe what was done to the code instead of describing the problem. In this case, you could say "Fix warning messages for translators on the generate draft page" or "Hide settings link on warning messages for translators"

> Reviewed 4 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/2581#-:-O1St1boCwENmVA8POaa:bx6uxi5)* status: all files reviewed, 8 unresolved discussions (waiting on @kylebuss)

___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-generation.component.ts` line 207 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/2581#-O1Svoof3Wc3d2y5evu8:-O1Svoof3Wc3d2y5evu9:b-55lnco) ([raw file](https://github.com/sillsdev/web-xforge/blob/15a970d02b1da3007fade26c1d91def9a73d83c8/src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-generation.component.ts#L207)):*
> ```XML
>   get isProjectAdmin(): boolean {
>     const userId = this.authService.currentUserId;
>     if (userId) {
> ```

Nit: When doing a check, be as explicit as you can. In this case, you can check `if (userId != null)`. Here, the loose not equal operator will check if the id is null or undefined.



_Code quote:_
```XML
    if (userId) {
```
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-generation.component.spec.ts` line 165 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/2581#-O1TAAUgEkM_eH8USqGQ:-O1TAAUgEkM_eH8USqGR:b-oowt5a) ([raw file](https://github.com/sillsdev/web-xforge/blob/15a970d02b1da3007fade26c1d91def9a73d83c8/src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-generation.component.spec.ts#L165)):*
> ```XML
>               }
>             }
>           },
> ```

It would make sense to add the user roles here. You can use the following:



_Code snippet:_
```XML
userRoles: { 'user01': SFProjectRole.ParatextAdministrator, 'user02', SFprojectRole.ParatextTranslator }
```
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-generation.component.spec.ts` line 598 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/2581#-O1T8f0j6c8sn6NRMJlN:-O1T8f0j6c8sn6NRMJlO:b-8u2hkq) ([raw file](https://github.com/sillsdev/web-xforge/blob/15a970d02b1da3007fade26c1d91def9a73d83c8/src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-generation.component.spec.ts#L598)):*
> ```XML
>     describe('source text missing', () => {
>       it('should show warning with settings link when source text is missing AND target language is supported, user is Paratext Admin', () => {
>         let projectDoc: SFProjectProfileDoc = {
> ```

There is opportunity to clean up the test setup here. I would create a static method in the `TestEnvironment` class called `initProject(currentUserId: string)` and move this initialization code there. I recommend refactoring this setup out of the `TestEnvironment.setup` method. Then, you can create an instance of TestEnvironment like this: 



_Code quote (i):_
```XML
        let projectDoc: SFProjectProfileDoc = {
```



_Code snippet (ii):_
```XML
const env = new TestEnvironment(() => TestEnvironment.initProject('user01'));
```
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-generation.component.spec.ts` line 600 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/2581#-O1T8I3j5O61EeJWxjBT:-O1T8I3j5O61EeJWxjBU:bewrfai) ([raw file](https://github.com/sillsdev/web-xforge/blob/15a970d02b1da3007fade26c1d91def9a73d83c8/src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-generation.component.spec.ts#L600)):*
> ```XML
>         let projectDoc: SFProjectProfileDoc = {
>           data: createTestProjectProfile({
>             userRoles: { user01: 'pt_administrator' }
> ```

You can use the `SFProjectRole.ParatextAdministrator` here and below.



_Code quote:_
```XML
'pt_administrator'
```
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-generation.component.spec.ts` line 606 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/2581#-O1T3rIbAnCZ9e56YUIF:-O1T3rIbAnCZ9e56YUIG:b-iqgbuk) ([raw file](https://github.com/sillsdev/web-xforge/blob/15a970d02b1da3007fade26c1d91def9a73d83c8/src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-generation.component.spec.ts#L606)):*
> ```XML
>           mockAuthService = jasmine.createSpyObj<AuthService>([], {
>             currentUserId: 'user01',
>             currentUserRoles: [SystemRole.None]
> ```

This should be `SystemRole.User` since a user will always have a system  role.



_Code quote:_
```XML
[SystemRole.None]
```
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-generation.component.spec.ts` line 680 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/2581#-O1T4OJ669YCr_ZsYc7-:-O1T4OJ669YCr_ZsYc70:b-q64pkt) ([raw file](https://github.com/sillsdev/web-xforge/blob/15a970d02b1da3007fade26c1d91def9a73d83c8/src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-generation.component.spec.ts#L680)):*
> ```XML
>           mockAuthService = jasmine.createSpyObj<AuthService>([], {
>             currentUserId: 'user01',
>             currentUserRoles: [SystemRole.None]
> ```

See above.



_Code quote:_
```XML
[SystemRole.None]
```
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-generation.component.spec.ts` line 709 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/2581#-O1T4lLb0-n6klrF1U44:-O1T4lLb0-n6klrF1U45:b-ya81ng) ([raw file](https://github.com/sillsdev/web-xforge/blob/15a970d02b1da3007fade26c1d91def9a73d83c8/src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-generation.component.spec.ts#L709)):*
> ```XML
>           mockAuthService = jasmine.createSpyObj<AuthService>([], {
>             currentUserId: 'user01',
>             currentUserRoles: [SystemRole.None]
> ```

Same as above



_Code quote:_
```XML
[SystemRole.None]
```
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-generation.component.spec.ts` line 821 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/2581#-O1T4srMDFnwSuqDlIz1:-O1T4srMDFnwSuqDlIz2:b-ya81ng) ([raw file](https://github.com/sillsdev/web-xforge/blob/15a970d02b1da3007fade26c1d91def9a73d83c8/src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-generation.component.spec.ts#L821)):*
> ```XML
>           mockAuthService = jasmine.createSpyObj<AuthService>([], {
>             currentUserId: 'user01',
>             currentUserRoles: [SystemRole.None]
> ```

Same as above



_Code quote:_
```XML
 [SystemRole.None]
```

**Comment by kylebuss** [comment]
@RaymondLuong3 code review suggestions have been applied.

**Review by RaymondLuong3 — CHANGES_REQUESTED** [review]
Excellent. I am glad to see more reuseable logic consolidated whenever possible. Just one more blocking comment.

> Reviewed 1 of 2 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/2581#-:-O1XoRH7AH07F-GWoIMh:bej3zyk)* status: all files reviewed, 3 unresolved discussions (waiting on @kylebuss)

___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-generation.component.spec.ts` line 172 at r3](https://reviewable.io/reviews/sillsdev/web-xforge/2581#-O1XnU0VEp535C7jtMWW:-O1XnU0VEp535C7jtMWX:b-a4ox2x) ([raw file](https://github.com/sillsdev/web-xforge/blob/c542e2391f58ddf77186ed2be55b64157deb5aa5/src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-generation.component.spec.ts#L172)):*
> ```XML
>     }
> 
>     static initProject(currentUserId: string, initializeUser: boolean): void {
> ```

You'll want to remove the second parameter. Because there is never a scenario for our app to not have a reference to a current user, we should always initialize the user, even if a test does not require it.



_Code quote:_
```XML
    static initProject(currentUserId: string, initializeUser: boolean): void {
```
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-generation.component.spec.ts` line 202 at r3](https://reviewable.io/reviews/sillsdev/web-xforge/2581#-O1Xnq3Z4syKJE_ZWsUA:-O1Xnq3Z4syKJE_ZWsUB:b-kr8z7z) ([raw file](https://github.com/sillsdev/web-xforge/blob/c542e2391f58ddf77186ed2be55b64157deb5aa5/src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-generation.component.spec.ts#L202)):*
> ```XML
>           currentUserId,
>           currentUserRoles: [SystemRole.User]
>         });
> ```

You will see that a test fails if you make the change i asked for above. This needs updated so the spy object AuthService has a stubbed method called 'requestParatextCredentialsUpdate`



_Code quote (i):_
```XML
        mockAuthService = jasmine.createSpyObj<AuthService>([], {
          currentUserId,
          currentUserRoles: [SystemRole.User]
        });
```



_Code snippet (ii):_
```XML
jasmine.createSpyObj<AuthService>(['requestParatextCredentialUpdate']
```

**Comment by kylebuss** [comment]
Removed duplication of `mockAuthService` and added stub method into `initProject`

**Review by RaymondLuong3 — APPROVED** [review]
:lgtm: 

> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/2581#-:-O1YB1u6De36wqc-zGH2:bg7igkv)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @kylebuss)

**Pull request merged**
