### PR TITLE
Change "user edit counts" report to group data by year, then month, then user, then chapter

### PR DESCRIPTION
**Pull request by siltomato**
This grouping will make it easier for Biblica to see month-by-month updates.  The net word edits counts may be different from the old script due to the new grouping of version ops.

To view the net word diffs in the console, add `--log-diff` flag when executing script.

- - -
This change is [Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/2585)

### CODE REVIEW

**Comment by Nateowami** [comment]
@siltomato For two of the three projects I ran this on, I'm getting `MongoServerError: Exceeded memory limit for $group, but didn't allow external sort. Pass allowDiskUse:true to opt in.`

**Review by pmachapman — CHANGES_REQUESTED** [review]
I have recreated the error for projects with a very large number of edits, and can confirm it does not occur on master. I can PM you the project short name.

> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/2585#-:-O2bKUrp25-HUcgXeIQD:b-e5omzj)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @siltomato)

**Review by siltomato — COMMENTED** [review]
Reworked the script to move the grouping and sorting to be after the query.

> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/2585#-:-O3KTqeZBZN7FQuKWk6K:b-qs8k2c)* status: 0 of 1 files reviewed, all discussions resolved (waiting on @pmachapman)

**Review by pmachapman — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/2585#-:-O3U0wAK60xyGFc_ZcR7:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @siltomato)

**Pull request merged**
