### PR TITLE
SF-1622 Restart Realtime Server

### PR DESCRIPTION
**Pull request by nigel-wells**
Implements a simple scheduled check to the realtime server to see if the server is not null and attempts to restart it if required.

**Acceptance tests**
1. Start a sync
2. Kill the realtime server node process
3. Observe SF displays the broken offline icon on the avatar
4. Wait for one minute
5. Observe SF has come back online

- - -
This change is [Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/2343)

### CODE REVIEW

**Review by josephmyers — APPROVED** [review]
Reviewed and tested. Looks good! (Do the one GH bot comment)

> Reviewed 6 of 6 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/2343#-:-Nr4Hpns7kUkhaP8L8n5:bwpnfo4)* status: all files reviewed, 1 unresolved discussion (waiting on @nigel-wells and @pmachapman)

**Review by pmachapman — CHANGES_REQUESTED** [review]
Looks good - just one comment from me:

The Hangfire successful job list gets flooded with "RealtimeService.CheckIfRunning". One thing we could do is implement a `DeleteOnSucceess` job filter, do delete these jobs on success:

```cs
public class DeleteOnSuccess : JobFilterAttribute, IElectStateFilter
{
    public void OnStateElection(ElectStateContext context)
    {
        if (context.CandidateState.Name == SucceededState.StateName)
        {
            context.CandidateState = new DeletedState
            {
                Reason = "Deleted automatically when succeeded.",
            };
        }
    }
}
```

And:
```cs
    [DeleteOnSuccess]
    public void CheckIfRunning()
    {
        if (!Server.IsServerRunning())
            RestartServer();
    }
```

Source: https://www.bfcamara.com/posts/hide-succeeded-jobs-in-hangfire-dashboard/

> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/2343#-:-Nr6tGrh0v3UWBHTweW3:bge5q3h)* status: all files reviewed, 1 unresolved discussion (waiting on @nigel-wells)

**Review by nigel-wells — COMMENTED** [review]
Thanks guys. I've added that in Peter and fixed up that property Joseph.

> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/2343#-:-Nr8kU7GAmRKJc5bdrtB:b-u6lvja)* status: 4 of 7 files reviewed, 1 unresolved discussion (waiting on @github-advanced-security[bot] and @josephmyers)

___
*[`test/SIL.XForge.Tests/Realtime/RealtimeServiceTests.cs` line 289 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/2343#gh-1495142585:-Nr8fZA--sVaDSvLBx7_:b-896fix) ([raw file](https://github.com/sillsdev/web-xforge/blob/c4a0cee01904a2c554d4b9cce95a500bce3f9240/test/SIL.XForge.Tests/Realtime/RealtimeServiceTests.cs#L289)):*
<details><summary><i>Previously, github-advanced-security[bot] wrote…</i></summary><blockquote>

## Missed 'readonly' opportunity

Field 'ExceptionHandler' can be 'readonly'.

[Show more details](https://github.com/sillsdev/web-xforge/security/code-scanning/737)
</blockquote></details>

Done.

**Review by pmachapman — APPROVED** [review]
:lgtm: Thank you, Nigel!

> Reviewed 3 of 3 files at r2, all commit messages.
> Dismissed @github-advanced-security[bot] from a discussion.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/2343#-:-Nr980uJ61wW_qCcJ968:byu9b4s)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @nigel-wells)

**Pull request merged**
