### PR TITLE
Update to PT9 logo

### PR DESCRIPTION
**Pull request by irahopkinson**
- an equivalent change has already been made in Auth0.

---
This change is [Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1066)

### CODE REVIEW

**Review by Nateowami — COMMENTED** [review]
Is there a reason `paratext_logo.png` was not removed? I don't see anything using it anymore.

> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1066#-:-Mbq9hff7gkiplRsa8fZ:bocny35)* status: 0 of 4 files reviewed, all discussions resolved

**Review by irahopkinson — COMMENTED** [review]
Yes, nothing is using it anymore in the new code but I wanted to avoid a user that still has a previous version in the browser getting an error when it asked for the file.

> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1066#-:-MbqFOQb4y5SBXY9mi_g:b-zdn8yo)* status: 0 of 4 files reviewed, all discussions resolved

**Review by irahopkinson — COMMENTED** [review]
Maybe that's being overly cautious.

> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1066#-:-MbqFpjR2agLo8SUg4TJ:b-r7720x)* status: 0 of 4 files reviewed, all discussions resolved

**Review by Nateowami — APPROVED** [review]
Actually I think that's a good reason. But the challenge then is to remember to remove it later. So I could see either way.

Let's :shipit: 

> Reviewed 4 of 4 files at r1.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1066#-:-MbqGavw7-TvlhFB_YJH:b-8zcwcj)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @irahopkinson)

**Pull request merged**
