### PR TITLE
SF-1972 Sync Speed Improvements

### PR DESCRIPTION
**Pull request by pmachapman**
This Pull Request:
 * Ensures that only the books that can be edited in Scripture Forge are updated in the Paratext repository on sync
 * Parses the Paratext revisions to see what is changed, and only updates Scripture Forge's data in the areas that received changes
 * Adds a RepoInfo tool to explain what has changed in each revision in a Paratext repository

These changes will help improve sync speed for larger projects, with a minimal improvement for small projects.

- - -
This change is [Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1845)

### CODE REVIEW

**Review by RaymondLuong3 — CHANGES_REQUESTED** [review]
I started to look through these changes and I think this will be a benefit to our sync process. It adds a bit more logic, but we benefit for a more efficient sync, at least when pulling PT changes into SF. I'll finish the review off when I get in tomorrow.

> Reviewed 8 of 13 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1845#-:-NW9ma7rDD-UXwpeCVZf:b-w73r3e)* status: 8 of 13 files reviewed, 5 unresolved discussions (waiting on @pmachapman)

___
*[`src/SIL.XForge.Scripture/Models/ParatextSyncResults.cs` line 47 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/1845#-NW9ftvL5Dd2DzQuCPBd:-NW9ftvL5Dd2DzQuCPBe:b-1aij30) ([raw file](https://github.com/sillsdev/web-xforge/blob/235f698c45efde59c1011d1adac8e8e65ff425d3/src/SIL.XForge.Scripture/Models/ParatextSyncResults.cs#L47)):*
> ```Smalltalk
>     /// <param name="bookNum">The book number.</param>
>     /// <returns><c>true</c> if the book should be updated; otherwise, <c>false</c>.</returns>
>     public bool UpdateBook(int bookNum) => ProjectChanged || IsResource || Books.Contains(bookNum);
> ```

The reason we want to update the book if it is a resource is because resources can be updated in the DBL, is that right?
___
*[`src/SIL.XForge.Scripture/Services/ParatextDataHelper.cs` line 37 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/1845#-NW9htVG0WJdtXAYqGmG:-NW9htVG0WJdtXAYqGmH:b-qvc7y) ([raw file](https://github.com/sillsdev/web-xforge/blob/235f698c45efde59c1011d1adac8e8e65ff425d3/src/SIL.XForge.Scripture/Services/ParatextDataHelper.cs#L37)):*
> ```Smalltalk
>         return revisions
>             .Select(revision => new RevisionChangeInfo(versionedText, revision))
>             .SelectMany(summary => summary.FilesChanged)
> ```

This is my first time seeing the RevisionChangeInfo and I'm so glad it exists for this purpose!
___
*[`src/SIL.XForge.Scripture/Services/ParatextService.cs` line 583 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/1845#-NW9j1cP1n0HBd5JxBYK:-NW9j1cP1n0HBd5JxBYL:b-j7961g) ([raw file](https://github.com/sillsdev/web-xforge/blob/235f698c45efde59c1011d1adac8e8e65ff425d3/src/SIL.XForge.Scripture/Services/ParatextService.cs#L583)):*
> ```Smalltalk
>     {
>         // Parse the sync results
>         foreach (SendReceiveResult result in srResults ?? Array.Empty<SendReceiveResult>())
> ```

In this case, we can just check if srResults is null, and return right away if it is.
___
*[`src/SIL.XForge.Scripture/Services/ParatextService.cs` line 624 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/1845#-NW9jetZCq66lM4my5cC:-NW9jetZCq66lM4my5cD:b-81umq3) ([raw file](https://github.com/sillsdev/web-xforge/blob/235f698c45efde59c1011d1adac8e8e65ff425d3/src/SIL.XForge.Scripture/Services/ParatextService.cs#L624)):*
> ```Smalltalk
>                     case ProjectFileType.NoteTags:
>                         // Notes have changed
>                         syncResults.NotesChanged = true;
> ```

Will this have unintended consequences if we mark notes changed and do not mark permissions changed if they were both changed in the same revision?
___
*[`src/SIL.XForge.Scripture/Services/ParatextSyncRunner.cs` line 625 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/1845#-NW9l5TJ018cHwyLeqqQ:-NW9l5TJ018cHwyLeqqR:b-g3ijvy) ([raw file](https://github.com/sillsdev/web-xforge/blob/235f698c45efde59c1011d1adac8e8e65ff425d3/src/SIL.XForge.Scripture/Services/ParatextSyncRunner.cs#L625)):*
> ```Smalltalk
>             bool hasSource = sourceBooks.Contains(bookNum);
>             int textIndex = _projectDoc.Data.Texts.FindIndex(t => t.BookNum == bookNum);
>             if (!syncResults.UpdateBook(bookNum) && textIndex > -1)
> ```

I don't quite understand why we update hasSource on a book when the sync results do not indicate a change for a particular book? I must be understanding this wrong.

**Review by pmachapman — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1845)* status: 6 of 13 files reviewed, 4 unresolved discussions (waiting on @RaymondLuong3)

___
*[`src/SIL.XForge.Scripture/Models/ParatextSyncResults.cs` line 47 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/1845#-NW9ftvL5Dd2DzQuCPBd:-NWA0S3A23z9J7ZwNGCh:b5guqn4) ([raw file](https://github.com/sillsdev/web-xforge/blob/235f698c45efde59c1011d1adac8e8e65ff425d3/src/SIL.XForge.Scripture/Models/ParatextSyncResults.cs#L47)):*
<details><summary><i>Previously, RaymondLuong3 (Raymond Luong) wrote…</i></summary><blockquote>

The reason we want to update the book if it is a resource is because resources can be updated in the DBL, is that right?
</blockquote></details>

It always returns true for resources, because more complex logic is used to determine if a resource should be updated, and because they come from the DBL and so the Mercurial log cannot be checked. I have added a comment to help explain.
___
*[`src/SIL.XForge.Scripture/Services/ParatextService.cs` line 583 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/1845#-NW9j1cP1n0HBd5JxBYK:-NWA28SZ5aqPd9nRoJ06:b-896fix) ([raw file](https://github.com/sillsdev/web-xforge/blob/235f698c45efde59c1011d1adac8e8e65ff425d3/src/SIL.XForge.Scripture/Services/ParatextService.cs#L583)):*
<details><summary><i>Previously, RaymondLuong3 (Raymond Luong) wrote…</i></summary><blockquote>

In this case, we can just check if srResults is null, and return right away if it is.
</blockquote></details>

Done.
___
*[`src/SIL.XForge.Scripture/Services/ParatextService.cs` line 624 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/1845#-NW9jetZCq66lM4my5cC:-NWA2IvL3koC0wNsYigd:b-z6iqsf) ([raw file](https://github.com/sillsdev/web-xforge/blob/235f698c45efde59c1011d1adac8e8e65ff425d3/src/SIL.XForge.Scripture/Services/ParatextService.cs#L624)):*
<details><summary><i>Previously, RaymondLuong3 (Raymond Luong) wrote…</i></summary><blockquote>

Will this have unintended consequences if we mark notes changed and do not mark permissions changed if they were both changed in the same revision?
</blockquote></details>

No, as I iterate over every file in each revision, and so as different files are updated, both cases in the switch statement will execute.
___
*[`src/SIL.XForge.Scripture/Services/ParatextSyncRunner.cs` line 625 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/1845#-NW9l5TJ018cHwyLeqqQ:-NWA2y4YD2DeExo3xUwr:b3ou3dn) ([raw file](https://github.com/sillsdev/web-xforge/blob/235f698c45efde59c1011d1adac8e8e65ff425d3/src/SIL.XForge.Scripture/Services/ParatextSyncRunner.cs#L625)):*
<details><summary><i>Previously, RaymondLuong3 (Raymond Luong) wrote…</i></summary><blockquote>

I don't quite understand why we update hasSource on a book when the sync results do not indicate a change for a particular book? I must be understanding this wrong.
</blockquote></details>

Because `syncResults` only has details on what books have changed in the target project's sync. The earlier sync of the source project may have added or removed a book that was already in the target project and not updated in this sync of the target project.

**Review by RaymondLuong3 — CHANGES_REQUESTED** [review]
> Reviewed 5 of 13 files at r1, 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1845)* status: all files reviewed, 7 unresolved discussions (waiting on @pmachapman)

___
*[`src/SIL.XForge.Scripture/Models/ParatextSyncResults.cs` line 47 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/1845#-NW9ftvL5Dd2DzQuCPBd:-NWDXuWg-yPpulDujbNu:b-o0mul1) ([raw file](https://github.com/sillsdev/web-xforge/blob/235f698c45efde59c1011d1adac8e8e65ff425d3/src/SIL.XForge.Scripture/Models/ParatextSyncResults.cs#L47)):*
<details><summary><i>Previously, pmachapman (Peter Chapman) wrote…</i></summary><blockquote>

It always returns true for resources, because more complex logic is used to determine if a resource should be updated, and because they come from the DBL and so the Mercurial log cannot be checked. I have added a comment to help explain.
</blockquote></details>

Ok, that makes sense. Thanks for the comment.
___
*[`src/SIL.XForge.Scripture/Services/ParatextService.cs` line 624 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/1845#-NW9jetZCq66lM4my5cC:-NWDYDsLCpwOnuKvzaIU:byiyv8d) ([raw file](https://github.com/sillsdev/web-xforge/blob/235f698c45efde59c1011d1adac8e8e65ff425d3/src/SIL.XForge.Scripture/Services/ParatextService.cs#L624)):*
<details><summary><i>Previously, pmachapman (Peter Chapman) wrote…</i></summary><blockquote>

No, as I iterate over every file in each revision, and so as different files are updated, both cases in the switch statement will execute.
</blockquote></details>

Oh yes that is right. Each file will only trigger one of the cases, so this is the right approach.
___
*[`src/SIL.XForge.Scripture/Services/ParatextSyncRunner.cs` line 625 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/1845#-NW9l5TJ018cHwyLeqqQ:-NWDYliP9arTb-fOiWwT:b-446vun) ([raw file](https://github.com/sillsdev/web-xforge/blob/235f698c45efde59c1011d1adac8e8e65ff425d3/src/SIL.XForge.Scripture/Services/ParatextSyncRunner.cs#L625)):*
<details><summary><i>Previously, pmachapman (Peter Chapman) wrote…</i></summary><blockquote>

Because `syncResults` only has details on what books have changed in the target project's sync. The earlier sync of the source project may have added or removed a book that was already in the target project and not updated in this sync of the target project.
</blockquote></details>

Ah, yes that is right. Could you add a comment since that isn't so easy to understand?
___
*[`test/SIL.XForge.Scripture.Tests/Services/ParatextSyncRunnerTests.cs` line 331 at r2](https://reviewable.io/reviews/sillsdev/web-xforge/1845#-NWD_ehr3X5CGXuvA1Ji:-NWD_ehr3X5CGXuvA1Jj:b-ivskwu) ([raw file](https://github.com/sillsdev/web-xforge/blob/16207ebb020bea6f2db7d2c78ffcd9575d4d7169/test/SIL.XForge.Scripture.Tests/Services/ParatextSyncRunnerTests.cs#L331)):*
> ```Smalltalk
> 
>         await env.ParatextService
>             .DidNotReceive()
> ```

It might be cleaner just to assert DidNotReceive generically instead of testing every combination.
___
*[`tools/RepoInfo/Program.cs` line 4 at r2](https://reviewable.io/reviews/sillsdev/web-xforge/1845#-NWDfW3N4bLWfezHpF9Y:-NWDfW3N4bLWfezHpF9Z:bmfxva3) ([raw file](https://github.com/sillsdev/web-xforge/blob/16207ebb020bea6f2db7d2c78ffcd9575d4d7169/tools/RepoInfo/Program.cs#L4)):*
> ```Smalltalk
>  * Paratext Repository Information Tool
>  *
>  * Usage: REPOINFO [CSV] projectpath
> ```

Nice work! I like that I can see the revision and it gives me a visual representation of which files changed. I noticed that for me to run the program, I used `dotnet run projectpath`. How do you get it to run by specifying the project repo? Maybe the solution file takes care of that? Or does this need to be updated?
___
*[`tools/RepoInfo/Program.cs` line 8 at r2](https://reviewable.io/reviews/sillsdev/web-xforge/1845#-NWDfyPN3bTe23oxQAZm:-NWDfyPN3bTe23oxQAZn:bctjeaj) ([raw file](https://github.com/sillsdev/web-xforge/blob/16207ebb020bea6f2db7d2c78ffcd9575d4d7169/tools/RepoInfo/Program.cs#L8)):*
> ```Smalltalk
>  * Examples:
>  *  - Display the repository information in the console:
>  *      REPOINFO /var/lib/scriptureforge/sync/59e59e2dce4bb5c863c683c0c4647008dd9767d4
> ```

Add `target` to the end of the example project path. Without it, the program cannot locate the settings.xml. I might be better to remove the paratextId and use a mock value like <paratext-id>
___
*[`tools/RepoInfo/Program.cs` line 38 at r2](https://reviewable.io/reviews/sillsdev/web-xforge/1845#-NWDbdFv-a5YAm8ufACk:-NWDbdFv-a5YAm8ufACl:b-uvrl9n) ([raw file](https://github.com/sillsdev/web-xforge/blob/16207ebb020bea6f2db7d2c78ffcd9575d4d7169/tools/RepoInfo/Program.cs#L38)):*
> ```Smalltalk
> 
> // Get the project path, and CSV from the command line arguments
> // Allow the arguments to be in any order
> ```

It can save some logic to specify a specific order. I'm not sure there is much advantage being able to add arguments in any order.

**Review by pmachapman — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1845)* status: 7 of 13 files reviewed, 5 unresolved discussions (waiting on @RaymondLuong3)

___
*[`src/SIL.XForge.Scripture/Services/ParatextSyncRunner.cs` line 625 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/1845#-NW9l5TJ018cHwyLeqqQ:-NWEDITIBlau5riH70Bq:bl4qz57) ([raw file](https://github.com/sillsdev/web-xforge/blob/235f698c45efde59c1011d1adac8e8e65ff425d3/src/SIL.XForge.Scripture/Services/ParatextSyncRunner.cs#L625)):*
<details><summary><i>Previously, RaymondLuong3 (Raymond Luong) wrote…</i></summary><blockquote>

Ah, yes that is right. Could you add a comment since that isn't so easy to understand?
</blockquote></details>

Good idea - done. Let me know if my description is not clear.
___
*[`test/SIL.XForge.Scripture.Tests/Services/ParatextSyncRunnerTests.cs` line 331 at r2](https://reviewable.io/reviews/sillsdev/web-xforge/1845#-NWD_ehr3X5CGXuvA1Ji:-NWEFLfl9ZzjK-Ca7PlS:b-6btubk) ([raw file](https://github.com/sillsdev/web-xforge/blob/16207ebb020bea6f2db7d2c78ffcd9575d4d7169/test/SIL.XForge.Scripture.Tests/Services/ParatextSyncRunnerTests.cs#L331)):*
<details><summary><i>Previously, RaymondLuong3 (Raymond Luong) wrote…</i></summary><blockquote>

It might be cleaner just to assert DidNotReceive generically instead of testing every combination.
</blockquote></details>

Yes - good idea. Cleaned up.
___
*[`tools/RepoInfo/Program.cs` line 4 at r2](https://reviewable.io/reviews/sillsdev/web-xforge/1845#-NWDfW3N4bLWfezHpF9Y:-NWEI4yC1hK_sBtsRk3P:bz9ne0i) ([raw file](https://github.com/sillsdev/web-xforge/blob/16207ebb020bea6f2db7d2c78ffcd9575d4d7169/tools/RepoInfo/Program.cs#L4)):*
<details><summary><i>Previously, RaymondLuong3 (Raymond Luong) wrote…</i></summary><blockquote>

Nice work! I like that I can see the revision and it gives me a visual representation of which files changed. I noticed that for me to run the program, I used `dotnet run projectpath`. How do you get it to run by specifying the project repo? Maybe the solution file takes care of that? Or does this need to be updated?
</blockquote></details>

The comment was based on it being a compiled EXE - I have updated it to use dotnet run, and made a code fix so that it correctly outputs the data when run this way.
___
*[`tools/RepoInfo/Program.cs` line 8 at r2](https://reviewable.io/reviews/sillsdev/web-xforge/1845#-NWDfyPN3bTe23oxQAZm:-NWEIvRzBlgJrRKqtsBT:bb6un1j) ([raw file](https://github.com/sillsdev/web-xforge/blob/16207ebb020bea6f2db7d2c78ffcd9575d4d7169/tools/RepoInfo/Program.cs#L8)):*
<details><summary><i>Previously, RaymondLuong3 (Raymond Luong) wrote…</i></summary><blockquote>

Add `target` to the end of the example project path. Without it, the program cannot locate the settings.xml. I might be better to remove the paratextId and use a mock value like <paratext-id>
</blockquote></details>

Done
___
*[`tools/RepoInfo/Program.cs` line 38 at r2](https://reviewable.io/reviews/sillsdev/web-xforge/1845#-NWDbdFv-a5YAm8ufACk:-NWEIwrr4LCd9wr_pj2S:b9xqgwv) ([raw file](https://github.com/sillsdev/web-xforge/blob/16207ebb020bea6f2db7d2c78ffcd9575d4d7169/tools/RepoInfo/Program.cs#L38)):*
<details><summary><i>Previously, RaymondLuong3 (Raymond Luong) wrote…</i></summary><blockquote>

It can save some logic to specify a specific order. I'm not sure there is much advantage being able to add arguments in any order.
</blockquote></details>

If possible, I would like to keep the ability to add arguments in any order - I did it because I would write the path then remember to add CSV (Windows Command Prompt is not as nice as Bash for editing your command).

**Review by RaymondLuong3 — APPROVED** [review]
:lgtm:

> Reviewed 6 of 6 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1845#-:-NWhJtrV7CHVv5sF_XW4:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @pmachapman)

___
*[`tools/RepoInfo/Program.cs` line 38 at r2](https://reviewable.io/reviews/sillsdev/web-xforge/1845#-NWDbdFv-a5YAm8ufACk:-NWhJkWFE6RSCVMJt5wP:b-h9srk6) ([raw file](https://github.com/sillsdev/web-xforge/blob/16207ebb020bea6f2db7d2c78ffcd9575d4d7169/tools/RepoInfo/Program.cs#L38)):*
<details><summary><i>Previously, pmachapman (Peter Chapman) wrote…</i></summary><blockquote>

If possible, I would like to keep the ability to add arguments in any order - I did it because I would write the path then remember to add CSV (Windows Command Prompt is not as nice as Bash for editing your command).
</blockquote></details>

That's a good point.

**Comment by Nateowami** [comment]
@pmachapman I'm now merging this because:
a) There isn't nearly as much on master right now that hasn't made it to live, so I'm less concerned about piling on more work
b) The test team has developed a much broader set of sync tests, which will be run on QA. So this will get pretty thoroughly tested before deployment to live.

**Pull request merged**
