### PR TITLE
Reintroduce mongodb-core

### PR DESCRIPTION
**Pull request by marksvc**
* Needed for running backend.
* Based on a larger fix Ira had demonstrated

---
This change is [Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/449)

### CODE REVIEW

**Comment by Nateowami** [comment]
I checked out this commit and it worked, but then I switched back to master, ran npm install in both locations, and it still works. What error does this solve?

**Comment by jasonleenaylor** [comment]
@nateowami This is the mystery. The build machine seems happy without this change, but neither Mark, Dina, or myself could successfully build until we included mongodb-core as a dependency. I suspect it somehow is getting cached once it is installed? The build machine had it because of Ira's PR maybe? In any case without it most of us can't build.

**Comment by Nateowami** [comment]
I've deleted both of my `node_modules` folders and installed them again, and it still works. I'm happy to merge this if it fixes it for people, but I can't reproduce the problem.

**Comment by jasonleenaylor** [comment]
@Nateowami like I said, it is still a bit of a mystery. @irahopkinson thought it was necessary, and Mark and I found it to be. But @ddaspit and TeamCity didn't seem to need it. I think we should merge it and then see if anyone complains later.

**Pull request merged**
