### PR TITLE
Update all translation files from Crowdin

### PR DESCRIPTION
**Pull request by Nateowami**
This change is [Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1014)

### CODE REVIEW

**Review by RaymondLuong3 — CHANGES_REQUESTED** [review]
> Reviewed 14 of 18 files at r1.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1014)* status: 14 of 18 files reviewed, 1 unresolved discussion (waiting on @Nateowami)

___
*[src/SIL.XForge.Scripture/ClientApp/src/assets/i18n/non_checking_az.json, line 160 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/1014#-MXsTfXl3KHGT1WaANvE:-MXsTfXl3KHGT1WaANvF:b-fika0x) ([raw file](https://github.com/sillsdev/web-xforge/blob/044e0b8295384b6866f59b7d25caf508daad3318/src/SIL.XForge.Scripture/ClientApp/src/assets/i18n/non_checking_az.json#L160)):*
> ```
>     "choose_the_paratext_project": "Choose the Paratext project or Digital Bible Library resource that your project is based on.",
> ```
It looks like the original strings have been updated, but the translations have not been done. That was my doing. Unfortunately, this overwrites the previous version of the translated string. Would it be possible to omit merging these files for the time being so the previously translated strings are still present?

**Review by Nateowami — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1014)* status: 14 of 18 files reviewed, 1 unresolved discussion (waiting on @RaymondLuong3)

___
*[src/SIL.XForge.Scripture/ClientApp/src/assets/i18n/non_checking_az.json, line 160 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/1014#-MXsTfXl3KHGT1WaANvE:-MXsndjdBv0iPYksstJs:b-8wiu14) ([raw file](https://github.com/sillsdev/web-xforge/blob/044e0b8295384b6866f59b7d25caf508daad3318/src/SIL.XForge.Scripture/ClientApp/src/assets/i18n/non_checking_az.json#L160)):*
<details><summary><i>Previously, RaymondLuong3 (Raymond Luong) wrote…</i></summary><blockquote>

> ```
>     "choose_the_paratext_project": "Choose the Paratext project or Digital Bible Library resource that your project is based on.",
> ```
It looks like the original strings have been updated, but the translations have not been done. That was my doing. Unfortunately, this overwrites the previous version of the translated string. Would it be possible to omit merging these files for the time being so the previously translated strings are still present?
</blockquote></details>

Indeed. That's unfortunate. When updating files in Crowdin there's an option to keep existing translations, but that must not have been checked when this file was updated (I know I've made that mistake myself, so it's not very surprising).

**Review by Nateowami — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1014)* status: 13 of 14 files reviewed, 1 unresolved discussion (waiting on @RaymondLuong3)

___
*[src/SIL.XForge.Scripture/ClientApp/src/assets/i18n/non_checking_az.json, line 160 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/1014#-MXsTfXl3KHGT1WaANvE:-MXstI3J83K2pua3hijA:b-896fix) ([raw file](https://github.com/sillsdev/web-xforge/blob/044e0b8295384b6866f59b7d25caf508daad3318/src/SIL.XForge.Scripture/ClientApp/src/assets/i18n/non_checking_az.json#L160)):*
<details><summary><i>Previously, Nateowami (Nathaniel Paulus) wrote…</i></summary><blockquote>

Indeed. That's unfortunate. When updating files in Crowdin there's an option to keep existing translations, but that must not have been checked when this file was updated (I know I've made that mistake myself, so it's not very surprising).
</blockquote></details>

Done.

**Review by RaymondLuong3 — APPROVED** [review]
This just needs a rebase and then it is good to go.

> Reviewed 5 of 5 files at r2.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1014#-:-MY6nB4Z3uNlF0BiJ7zv:b9fzito)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @Nateowami)

**Pull request merged**
