### PR TITLE
SF-1815 Improve adding notes in mobile view for reviewer users

### PR DESCRIPTION
**Pull request by nigel-wells**
- Added bottom sheet to appear on mobile for specific viewports

image

- - -
This change is [Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1672)

### CODE REVIEW

**Review by Nateowami — COMMENTED** [review]
> Reviewed 4 of 6 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1672)* status: all files reviewed, 4 unresolved discussions (waiting on @nigel-wells)

___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.html` line 125 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/1672#-NMZC6rcAio24TNO5F-1:-NMZC6rcAio24TNO5F-2:b6px7kn) ([raw file](https://github.com/sillsdev/web-xforge/blob/e8b823157815ec0d699ffbd0df08e3722df78bf8/src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.html#L125)):*
> ```HTML
>             (showChange)="showSuggestions = $event"
>           ></app-suggestions>
>           <ng-template #fabBottomSheet>
> ```

FAB stands for "floating action button". Why is it used in this context?

**Review by RaymondLuong3 — COMMENTED** [review]
In my brief testing, I found that if a user cancels adding a note, the verse remains selected, but the bottom sheet is not available. Actually, this happens to the FAB in standard desktop view also, so it is not new. In the Bible app, the bottom sheet remains open, when a user chooses and option, but then cancels. I imagine that is probably the better option. What do you think?

> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1672#-:-NM_bchv5s14J-mV0Mjo:bb6zdw5)* status: all files reviewed, 4 unresolved discussions (waiting on @nigel-wells)

**Review by nigel-wells — COMMENTED** [review]
The visibility of the bottom sheet logic is the same as the desktop FAB. If someone closes the insert note modal, and we decide to keep the verse highlighted, then I think the FAB or bottom sheet should show again otherwise we should unselect the segment when the modal is closed. I'm more in favor of unselecting the segment.

Is that what you meant?

> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1672#-:-NM_dIn75HXOdVnDerRA:b94je18)* status: all files reviewed, 3 unresolved discussions (waiting on @Nateowami and @RaymondLuong3)

___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.html` line 125 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/1672#-NMZC6rcAio24TNO5F-1:-NM_c_D72LzI1iHUWO5C:by69k00) ([raw file](https://github.com/sillsdev/web-xforge/blob/e8b823157815ec0d699ffbd0df08e3722df78bf8/src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.html#L125)):*
<details><summary><i>Previously, Nateowami (Nathaniel Paulus) wrote…</i></summary><blockquote>

FAB stands for "floating action button". Why is it used in this context?
</blockquote></details>

I guess I felt it was still related to the FAB but it happens to be a bottom sheet on mobile. It is still technically floating above the editor if that helps justify it ;) I can rename it if you prefer to separate the two definitions.
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.ts` line 408 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/1672#-NM_Bd4h-EhUhSlmDsD8:-NM_bQBzBRcnyqowanwi:bhmyxmg) ([raw file](https://github.com/sillsdev/web-xforge/blob/e8b823157815ec0d699ffbd0df08e3722df78bf8/src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.ts#L408)):*
<details><summary><i>Previously, RaymondLuong3 (Raymond Luong) wrote…</i></summary><blockquote>

Oh boy, when I first read `lt-lg` I understood it as "larger than large". I thought, that can't be right! Now I understand that is "less than large".
</blockquote></details>

Yeah, I can see how that could be read either way!
___
*[`src/SIL.XForge.Scripture/ClientApp/src/assets/i18n/non_checking_en.json` line 87 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/1672#-NM_Cva60SDtX1ySYv--:-NM_cT_iE88p2elF_cAX:bhountn) ([raw file](https://github.com/sillsdev/web-xforge/blob/e8b823157815ec0d699ffbd0df08e3722df78bf8/src/SIL.XForge.Scripture/ClientApp/src/assets/i18n/non_checking_en.json#L87)):*
<details><summary><i>Previously, RaymondLuong3 (Raymond Luong) wrote…</i></summary><blockquote>

Instead of add comment, you can use `insert_note` a few lines below. So far I have been trying to avoid using the word "comment" and reserving that to describe the Paratext data model. In SF, the word "note" is being used exclusively. Hopefully that differentiation is effective.
</blockquote></details>

Good point - changed.

**Review by RaymondLuong3 — COMMENTED** [review]
Yes, I think the behaviour should be updated, and unselecting the verse if a user cancels is also a good option. Is that something you want to do here, or would it be better to open a new card?

> Reviewed 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1672#-:-NMa4zqKC8gkYOYpgHQd:b-qmip85)* status: all files reviewed, 1 unresolved discussion (waiting on @Nateowami)

**Review by nigel-wells — COMMENTED** [review]
I've added an update to this branch to unselect the verse once the note dialog is opened

> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1672#-:-NMaJ311Crr1FICPutmk:b8l03sm)* status: 4 of 6 files reviewed, 1 unresolved discussion (waiting on @Nateowami and @RaymondLuong3)

**Review by RaymondLuong3 — APPROVED** [review]
:lgtm: 

> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1672#-:-NMe4Sy420l2-tSKGKFN:bg7igkv)* status: all files reviewed, 1 unresolved discussion (waiting on @Nateowami)

**Pull request merged**
