### PR TITLE
GA build test

### PR DESCRIPTION
**Pull request by irahopkinson**
- does a production build

---
This change is [Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1048)

### CODE REVIEW

**Review by jasonleenaylor — COMMENTED** [review]
> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1048)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @irahopkinson)

___
*[.github/workflows/ci.yml, line 22 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/1048#-MaWNK8yEUoPLPQG988S:-MaWNK8yEUoPLPQG988T:b-4ad6ci) ([raw file](https://github.com/sillsdev/web-xforge/blob/135d0171d241e59048c19d20ec6b0aa8c3c2842f/.github/workflows/ci.yml#L22)):*
> ```
> windows-latest
> ```
I guess it doesn't hurt.

**Comment by jasonleenaylor** [comment]
___
*[.github/workflows/ci.yml, line 25 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/1048#-MaWO0od6hREZyP1cKAo:-MaWO0od6hREZyP1cKAp:br1tzzt) ([raw file](https://github.com/sillsdev/web-xforge/blob/135d0171d241e59048c19d20ec6b0aa8c3c2842f/.github/workflows/ci.yml#L25)):*
> ```
> actions/checkout@v2
> ```
Just FYI more paranoid people than me prefer to use a specific commit sha instead of the version. I don't feel like big enough of a target to worry about it.

**Review by irahopkinson — COMMENTED** [review]
Some more helpful explanation of this PR: I recently added Angular compiler options to make things stricter and fixed a number of issues found that may or may not have been bugs but the strictness checks only occur during a production build. We use to have TC do a production build to check everything would work properly but it makes TC take way too long since it runs after all the tests. By doing it in GA it will run in parallel with the TC tests and finish at about the same time.

> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1048#-:-MaX4PNo9sO-txAtbTZk:b-grneq)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @irahopkinson)

___
*[.github/workflows/ci.yml, line 22 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/1048#-MaWNK8yEUoPLPQG988S:-MaX-Kc35LjqKQCsZ1tf:b2u0wru) ([raw file](https://github.com/sillsdev/web-xforge/blob/fb324237604792a49709f6a0899b0d211b87a0ec/.github/workflows/ci.yml#L22)):*
<details><summary><i>Previously, jasonleenaylor (Jason Naylor) wrote…</i></summary><blockquote>

> ```
> windows-latest
> ```
I guess it doesn't hurt.
</blockquote></details>

Yeah, since these run in parallel I thought I would like to know if it didn't build for some reason since we use both OSes for development.
___
*[.github/workflows/ci.yml, line 25 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/1048#-MaWO0od6hREZyP1cKAo:-MaX2ARr5c551BkBmj2G:bwc9bh0) ([raw file](https://github.com/sillsdev/web-xforge/blob/fb324237604792a49709f6a0899b0d211b87a0ec/.github/workflows/ci.yml#L25)):*
<details><summary><i>Previously, jasonleenaylor (Jason Naylor) wrote…</i></summary><blockquote>

> ```
> actions/checkout@v2
> ```
Just FYI more paranoid people than me prefer to use a specific commit sha instead of the version. I don't feel like big enough of a target to worry about it.
</blockquote></details>

At this point I'm not seeing the concern. We are only using this action to check if a production build compiles with no errors - we aren't using the build from here. Additionally we aren't using any external actions.

**Review by jasonleenaylor — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1048)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @irahopkinson)

**Review by marksvc — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1048)* status: all files reviewed, 2 unresolved discussions (waiting on @irahopkinson)

___
*[.github/workflows/ci.yml, line 5 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/1048#-MaZZJDV1xZSveQFtPdx:-MaZZGO0-Qrc3z0m7DyP:bdsep1v) ([raw file](https://github.com/sillsdev/web-xforge/blob/fb324237604792a49709f6a0899b0d211b87a0ec/.github/workflows/ci.yml#L5)):*
> ```YAML
> # See: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions
> 
> name: Node.js CI
> ```

Nit: You might name this "Frontend and RealtimeServer" or "Angular and RealtimeServer" or similar since it's doing more than just building the RealtimeServer node application. 
This job could also be extended to do a production build of the dotnet backend application, and so just naming it "Production build" would be a reasonable name for now, until that extra part is added in. 
___
*[.github/workflows/ci.yml, line 32 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/1048#-MaZZts60avYt8XD_tLU:-MaZZts60avYt8XD_tLV:bl88sqa) ([raw file](https://github.com/sillsdev/web-xforge/blob/fb324237604792a49709f6a0899b0d211b87a0ec/.github/workflows/ci.yml#L32)):*
> ```
>       - run: cd src/RealtimeServer && npm ci
>       - run: cd src/SIL.XForge.Scripture/ClientApp && npm ci
>       - run: cd src/SIL.XForge.Scripture/ClientApp && npx ng build --prod
> ```
I find that Github Actions uses the command as the title in the collapsible set of log items it displays. But it can be made quite pretty if you do something like this instead, where it will instead display the `name` value in the collapsible log titles:

```yaml
- name: Build RealtimeServer
  run: cd src/RealtimeServer && npm ci
- name: Build Frontend
  run: |
    set -xueo pipefail
    cd src/SIL.XForge.Scripture/ClientApp
    npm ci
    npx ng build --prod
```

**Review by irahopkinson — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1048)* status: 0 of 1 files reviewed, all discussions resolved (waiting on @jasonleenaylor)

___
*[.github/workflows/ci.yml, line 5 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/1048#-MaZZJDV1xZSveQFtPdx:-Mac7wMx8QTdDxfwSiuE:b-qatwl0) ([raw file](https://github.com/sillsdev/web-xforge/blob/fb324237604792a49709f6a0899b0d211b87a0ec/.github/workflows/ci.yml#L5)):*
<details><summary><i>Previously, marksvc wrote…</i></summary><blockquote>

Nit: You might name this "Frontend and RealtimeServer" or "Angular and RealtimeServer" or similar since it's doing more than just building the RealtimeServer node application. 
This job could also be extended to do a production build of the dotnet backend application, and so just naming it "Production build" would be a reasonable name for now, until that extra part is added in. 
</blockquote></details>

Thanks for spotting this. I copied the file from another repo and forgot to update the top.
___
*[.github/workflows/ci.yml, line 32 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/1048#-MaZZts60avYt8XD_tLU:-Mac88RFB0daHRH2G7EZ:b-74qkcb) ([raw file](https://github.com/sillsdev/web-xforge/blob/fb324237604792a49709f6a0899b0d211b87a0ec/.github/workflows/ci.yml#L32)):*
<details><summary><i>Previously, marksvc wrote…</i></summary><blockquote>

> ```
>       - run: cd src/RealtimeServer && npm ci
>       - run: cd src/SIL.XForge.Scripture/ClientApp && npm ci
>       - run: cd src/SIL.XForge.Scripture/ClientApp && npx ng build --prod
> ```
I find that Github Actions uses the command as the title in the collapsible set of log items it displays. But it can be made quite pretty if you do something like this instead, where it will instead display the `name` value in the collapsible log titles:

```yaml
- name: Build RealtimeServer
  run: cd src/RealtimeServer && npm ci
- name: Build Frontend
  run: |
    set -xueo pipefail
    cd src/SIL.XForge.Scripture/ClientApp
    npm ci
    npx ng build --prod
```


</blockquote></details>

Good idea, I've updated this. Unfortunately we can't use `set -xueo pipefail` as that doesn't work in Windows.

**Pull request merged**
