### PR TITLE
Switch from lodash to lodash-es to shrink builds

### PR DESCRIPTION
**Pull request by Nateowami**
This shrinks the production build from 2.42 MB to 2.34 MB and reduces some of the build warnings.

---
This change is [Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/916)

### CODE REVIEW

**Review by irahopkinson — CHANGES_REQUESTED** [review]
> Reviewed 27 of 27 files at r1.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/916)* status: all files reviewed, 1 unresolved discussion (waiting on @Nateowami)

___
*[src/SIL.XForge.Scripture/ClientApp/src/app/app.component.ts, line 10 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/916#-MQyw81N98018RCnSK83:-MQyw81O7Dc3obWnUvNz:b2wpb4s) ([raw file](https://github.com/sillsdev/web-xforge/blob/3fd123f89257c25a6661165841a230fa620d1bf1/src/SIL.XForge.Scripture/ClientApp/src/app/app.component.ts#L10)):*
> ```
> { cloneDeep } from 'lodash-es';
> ```
This is a different style to most of the others, e.g. in other places we do `cloneDeep from 'lodash-es/cloneDeep';`. We should figure out what the right way is for the new optimiser and make these all consistent. I vaguely recall this is the right way as it gives just one module (instead of all the sub-modules) and lets the optimiser figure the rest out. Can you confirm?

**Review by Nateowami — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/916)* status: all files reviewed, 1 unresolved discussion (waiting on @irahopkinson)

___
*[src/SIL.XForge.Scripture/ClientApp/src/app/app.component.ts, line 10 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/916#-MQyw81N98018RCnSK83:-MQz198F2OfHXbogw8_n:b-44lfp7) ([raw file](https://github.com/sillsdev/web-xforge/blob/3fd123f89257c25a6661165841a230fa620d1bf1/src/SIL.XForge.Scripture/ClientApp/src/app/app.component.ts#L10)):*
<details><summary><i>Previously, irahopkinson (Ira Hopkinson) wrote…</i></summary><blockquote>

> ```
> { cloneDeep } from 'lodash-es';
> ```
This is a different style to most of the others, e.g. in other places we do `cloneDeep from 'lodash-es/cloneDeep';`. We should figure out what the right way is for the new optimiser and make these all consistent. I vaguely recall this is the right way as it gives just one module (instead of all the sub-modules) and lets the optimiser figure the rest out. Can you confirm?
</blockquote></details>

Indeed. I believe the `module from 'lodash/module'` format helped keep all of lodash from having to be pulled in by the compiler. However, with the ES modules, the tree shaker can work with `{ module} from 'lodash-es';` just fine. I ran an experiment with all the imports one way, and one the other, and there was no perceptible difference in any of the final bundle sizes (both build logs say "2.34 MB", which isn't as precise as could be hoped for). Before the change to `lodash-es` though, I think it would have made a difference.

My guess would be that this single import was previously single handedly increasing our bundle size.

**Review by irahopkinson — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/916#-:-MQzQlxH2uJr6JHEvTBT:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved

___
*[src/SIL.XForge.Scripture/ClientApp/src/app/app.component.ts, line 10 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/916#-MQyw81N98018RCnSK83:-MQzQJjPD54q4zMEeVft:b-h65xfo) ([raw file](https://github.com/sillsdev/web-xforge/blob/3fd123f89257c25a6661165841a230fa620d1bf1/src/SIL.XForge.Scripture/ClientApp/src/app/app.component.ts#L10)):*
<details><summary><i>Previously, Nateowami (Nathaniel Paulus) wrote…</i></summary><blockquote>

Indeed. I believe the `module from 'lodash/module'` format helped keep all of lodash from having to be pulled in by the compiler. However, with the ES modules, the tree shaker can work with `{ module} from 'lodash-es';` just fine. I ran an experiment with all the imports one way, and one the other, and there was no perceptible difference in any of the final bundle sizes (both build logs say "2.34 MB", which isn't as precise as could be hoped for). Before the change to `lodash-es` though, I think it would have made a difference.

My guess would be that this single import was previously single handedly increasing our bundle size.
</blockquote></details>

Good to know, thanks for that. Would you mind sharing this finding with the team.

**Review by Nateowami — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/916)* status: :shipit: complete! all files reviewed, all discussions resolved

___
*[src/SIL.XForge.Scripture/ClientApp/src/app/app.component.ts, line 10 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/916#-MQyw81N98018RCnSK83:-MR1giKNAtzI4QKMcre5:b-896fix) ([raw file](https://github.com/sillsdev/web-xforge/blob/3fd123f89257c25a6661165841a230fa620d1bf1/src/SIL.XForge.Scripture/ClientApp/src/app/app.component.ts#L10)):*
<details><summary><i>Previously, irahopkinson (Ira Hopkinson) wrote…</i></summary><blockquote>

Good to know, thanks for that. Would you mind sharing this finding with the team.
</blockquote></details>

Done.

**Pull request merged**
