### PR TITLE
SF-1626 Prompt for contact if last sync was failure

### PR DESCRIPTION
**Pull request by marksvc**
commit-id:b4ff72a3

---
This change is [Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1411)

### CODE REVIEW

**Review by RaymondLuong3 — APPROVED** [review]
Good thinking. That means we should be able to get active projects going again quicker.

> Reviewed 5 of 5 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1411#-:-N5aRNCe9RtOvV6R_TQb:b-bggom2)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @marksvc)

**Review by Nateowami — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1411)* status: all files reviewed, 1 unresolved discussion (waiting on @marksvc)

___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/sync/sync.component.ts` line 108 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/1411#-N5abUtXDB7gMfiMR5Ie:-N5abUtXDB7gMfiMR5If:bkoiqgi) ([raw file](https://github.com/sillsdev/web-xforge/blob/f4cd3a2373c38a9494931ac22c5e106a326f8f57/src/SIL.XForge.Scripture/ClientApp/src/app/sync/sync.component.ts#L108)):*
> ```XML
> 
>   get showSyncFailureSupportMessage(): boolean {
>     return !this.projectDoc?.data?.sync.lastSyncSuccessful ?? false;
> ```

`this.projectDoc?.data?.sync.lastSyncSuccessful` can be `true`, `false`, or `undefined`. It's then negated using the logical not operator (`!`) which leaves either `true` or `false`. But then the nullish coalescing operator (`??`) is used, as though it could be undefined still.

**Review by marksvc — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1411)* status: 3 of 5 files reviewed, 1 unresolved discussion (waiting on @Nateowami and @RaymondLuong3)

___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/sync/sync.component.ts` line 108 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/1411#-N5abUtXDB7gMfiMR5Ie:-N5bKkP6-vDLhvUcxb6f:b-wxydnu) ([raw file](https://github.com/sillsdev/web-xforge/blob/f4cd3a2373c38a9494931ac22c5e106a326f8f57/src/SIL.XForge.Scripture/ClientApp/src/app/sync/sync.component.ts#L108)):*
<details><summary><i>Previously, Nateowami (Nathaniel Paulus) wrote…</i></summary><blockquote>

`this.projectDoc?.data?.sync.lastSyncSuccessful` can be `true`, `false`, or `undefined`. It's then negated using the logical not operator (`!`) which leaves either `true` or `false`. But then the nullish coalescing operator (`??`) is used, as though it could be undefined still.
</blockquote></details>

Thank you. I think what I want here for the desired logic is actually
```ts
return !(this.projectDoc?.data?.sync.lastSyncSuccessful ?? true);
```
But I've had to think about it enough that I'm going to just spell it out.

**Review by Nateowami — CHANGES_REQUESTED** [review]
Sorry to leave a second review with lots more requested changes than my first one. My first review was rushed because I thought it was going to show the message whenever the project data wasn't fully loaded, resulting in a flash of the message before it gets hidden. And the merge button was already green, and I was concerned it would get merged before I had time to finish a review. 

> Reviewed 4 of 5 files at r1, 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1411#-:-N5cHqJbCgkEnQckBGUV:b-ckrt49)* status: all files reviewed, 4 unresolved discussions (waiting on @marksvc)

___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/sync/sync.component.html` line 60 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/1411#-N5ae9at9X5RXKE7cc4V:-N5ae9at9X5RXKE7cc4W:bj8gb1) ([raw file](https://github.com/sillsdev/web-xforge/blob/f4cd3a2373c38a9494931ac22c5e106a326f8f57/src/SIL.XForge.Scripture/ClientApp/src/app/sync/sync.component.html#L60)):*
> ```HTML
>       </div>
>     </mat-card>
>     <span
> ```



This really looks out of place aesthetically. Can you change the color (perhaps use a `mat-hint`), left-align the text, set max width to 40 or so ems, and centralize the container (e.g. by setting `align-items: center` on the flex container)?

That makes it look more like this:

___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/sync/sync.component.html` line 63 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/1411#-N5afX4MAal-wGdkpgw7:-N5afX4MAal-wGdkpgw8:b-h1w3nf) ([raw file](https://github.com/sillsdev/web-xforge/blob/f4cd3a2373c38a9494931ac22c5e106a326f8f57/src/SIL.XForge.Scripture/ClientApp/src/app/sync/sync.component.html#L63)):*
> ```HTML
>       *ngIf="showSyncFailureSupportMessage"
>       id="syncFailureSupport-message"
>       class="syncFailureSupport-text"
> ```

Using both a class and an ID is kind of redundant. If you need an ID for the sake of the tests, you might as well just use it in the CSS selector too. Unless there's some reason I'm not thinking of.

Also, I think the mix of camel case and kebab case doesn't follow our typical style. There's one other place in this file that we do that, but besides that the only place where this is done is on the settings page for the IDs of the radio buttons, where it arguably makes more sense. The typical style for this would be all kebab case.
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/sync/sync.component.ts` line 108 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/1411#-N5abUtXDB7gMfiMR5Ie:-N5abzaSAdFE9ptf9nC7:b5w4e68) ([raw file](https://github.com/sillsdev/web-xforge/blob/f4cd3a2373c38a9494931ac22c5e106a326f8f57/src/SIL.XForge.Scripture/ClientApp/src/app/sync/sync.component.ts#L108)):*
<details><summary><i>Previously, marksvc wrote…</i></summary><blockquote>

Thank you. I think what I want here for the desired logic is actually
```ts
return !(this.projectDoc?.data?.sync.lastSyncSuccessful ?? true);
```
But I've had to think about it enough that I'm going to just spell it out.
</blockquote></details>

Wouldn't `this.projectDoc?.data?.sync.lastSyncSuccessful === false` be simpler? I think we use that form a lot of places. When it's nullish it's going to be false. 
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/sync/sync.component.spec.ts` line 231 at r2](https://reviewable.io/reviews/sillsdev/web-xforge/1411#-N5cH8QH0EhS-WkU7F2Y:-N5cH8QH0EhS-WkU7F2Z:b-a9ofi2) ([raw file](https://github.com/sillsdev/web-xforge/blob/dc445c6dec890af29cedd7df9bd1553cb4cd7c19/src/SIL.XForge.Scripture/ClientApp/src/app/sync/sync.component.spec.ts#L231)):*
> ```XML
>   private isOnline: BehaviorSubject<boolean>;
> 
>   constructor(args: syncComponentTestConstructorArgs = {}) {
> ```

The style we're using is to always capitalize types, even if they have a minor use. That just makes them easier to identify. It took me a bit to figure out this wasn't a variable name.

Making the arguments named is an important improvement though. Calling methods with lots of unnamed arguments gets very confusing.

**Review by marksvc — COMMENTED** [review]
It's okay :). Thanks for reviewing.

> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1411#-:-N5lhAK_DIo1jIMoUjye:b-4awygn)* status: all files reviewed, 4 unresolved discussions (waiting on @Nateowami)

___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/sync/sync.component.html` line 60 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/1411#-N5ae9at9X5RXKE7cc4V:-N5lh8OtB3GzSZeoOZKn:bmg28hl) ([raw file](https://github.com/sillsdev/web-xforge/blob/f4cd3a2373c38a9494931ac22c5e106a326f8f57/src/SIL.XForge.Scripture/ClientApp/src/app/sync/sync.component.html#L60)):*
<details><summary><i>Previously, Nateowami (Nathaniel Paulus) wrote…</i></summary><blockquote>



This really looks out of place aesthetically. Can you change the color (perhaps use a `mat-hint`), left-align the text, set max width to 40 or so ems, and centralize the container (e.g. by setting `align-items: center` on the flex container)?

That makes it look more like this:


</blockquote></details>

How about this?
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/sync/sync.component.html` line 63 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/1411#-N5afX4MAal-wGdkpgw7:-N5gXyyv2jWaVt0eCohz:b-53fe90) ([raw file](https://github.com/sillsdev/web-xforge/blob/f4cd3a2373c38a9494931ac22c5e106a326f8f57/src/SIL.XForge.Scripture/ClientApp/src/app/sync/sync.component.html#L63)):*
<details><summary><i>Previously, Nateowami (Nathaniel Paulus) wrote…</i></summary><blockquote>

Using both a class and an ID is kind of redundant. If you need an ID for the sake of the tests, you might as well just use it in the CSS selector too. Unless there's some reason I'm not thinking of.

Also, I think the mix of camel case and kebab case doesn't follow our typical style. There's one other place in this file that we do that, but besides that the only place where this is done is on the settings page for the IDs of the radio buttons, where it arguably makes more sense. The typical style for this would be all kebab case.
</blockquote></details>

Thank you. I guess I copied the one wrong example :). Fixed.
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/sync/sync.component.ts` line 108 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/1411#-N5abUtXDB7gMfiMR5Ie:-N5gPNkz7gN4SpWz0gDF:b-3p8ebc) ([raw file](https://github.com/sillsdev/web-xforge/blob/f4cd3a2373c38a9494931ac22c5e106a326f8f57/src/SIL.XForge.Scripture/ClientApp/src/app/sync/sync.component.ts#L108)):*
<details><summary><i>Previously, Nateowami (Nathaniel Paulus) wrote…</i></summary><blockquote>

Wouldn't `this.projectDoc?.data?.sync.lastSyncSuccessful === false` be simpler? I think we use that form a lot of places. When it's nullish it's going to be false. 
</blockquote></details>

I'm not sure I'm comfortable comparing a left-side null or undefined to a right-side boolean. I've probably done it in other places without thinking about it. I'll give it a go. 
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/sync/sync.component.spec.ts` line 231 at r2](https://reviewable.io/reviews/sillsdev/web-xforge/1411#-N5cH8QH0EhS-WkU7F2Y:-N5gWnTG9d0GF-RMgHus:b-pmq36x) ([raw file](https://github.com/sillsdev/web-xforge/blob/dc445c6dec890af29cedd7df9bd1553cb4cd7c19/src/SIL.XForge.Scripture/ClientApp/src/app/sync/sync.component.spec.ts#L231)):*
<details><summary><i>Previously, Nateowami (Nathaniel Paulus) wrote…</i></summary><blockquote>

The style we're using is to always capitalize types, even if they have a minor use. That just makes them easier to identify. It took me a bit to figure out this wasn't a variable name.

Making the arguments named is an important improvement though. Calling methods with lots of unnamed arguments gets very confusing.
</blockquote></details>

Oops. Thanks. Done.

**Review by Nateowami — CHANGES_REQUESTED** [review]
> Reviewed 4 of 4 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1411)* status: all files reviewed, 4 unresolved discussions (waiting on @marksvc)

___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/sync/sync.component.html` line 60 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/1411#-N5ae9at9X5RXKE7cc4V:-N5mEdCF4y-z-YrJkxOU:beh4vhj) ([raw file](https://github.com/sillsdev/web-xforge/blob/f4cd3a2373c38a9494931ac22c5e106a326f8f57/src/SIL.XForge.Scripture/ClientApp/src/app/sync/sync.component.html#L60)):*
<details><summary><i>Previously, marksvc wrote…</i></summary><blockquote>

How about this?
</blockquote></details>

This looks a lot better.
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/sync/sync.component.scss` line 61 at r3](https://reviewable.io/reviews/sillsdev/web-xforge/1411#-N5ltc5p10AL8zWjZFVO:-N5ltc5p10AL8zWjZFVP:b-aasgy4) ([raw file](https://github.com/sillsdev/web-xforge/blob/3cbd9f5d09517098d13c86c69680eba5e0852bb8/src/SIL.XForge.Scripture/ClientApp/src/app/sync/sync.component.scss#L61)):*
> ```SCSS
> #sync-failure-support-message {
>   padding: 1rem;
>   color: grey;
> ```

I don't think we want to set this to a hard-coded color. For consistency it would be better to use a variable and specify a color we're already using. This color is slightly lighter than the color `mat-hint` uses.

For what it's worth, setting the color to gray is actually better than using an RGBA color like `rgba(0,0,0,.6)`, which is what's used by `mat-hint`, because the transparency can cause problems with some scripts, such as Arabic, which can have overlapping glyphs that start to look really bad if you use a transparent color. I'm not sure when specifying grey colors via transparency became an accepted thing. In the near future we're going to want change all our transparent text colors to not use transparency. That's one more reason why we would want to define our colors in as few places as possible and then just reference them.

I think you're right in thinking this is misusing mat-hint though, as it looks like it's intended to be used with a form field.

But it doesn't look like we've defined a variable for this anywhere, so this is kind of a pre-existing issue, and doesn't have to be solved in this PR.

(It took actually writing this comment for me to realize mat-hint is actually probably the wrong thing to use).
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/sync/sync.component.scss` line 62 at r3](https://reviewable.io/reviews/sillsdev/web-xforge/1411#-N5lt9P09Bc7FpSI_SCh:-N5lt9P09Bc7FpSI_SCi:beu3tx3) ([raw file](https://github.com/sillsdev/web-xforge/blob/3cbd9f5d09517098d13c86c69680eba5e0852bb8/src/SIL.XForge.Scripture/ClientApp/src/app/sync/sync.component.scss#L62)):*
> ```SCSS
>   padding: 1rem;
>   color: grey;
>   text-align: left;
> ```

This is superfluous. I did say "left-align the text", but that is what happens by default. Sorry; I could have been more clear. When a RTL UI language is selected this needs to not be set in order to have it automatically change text direction.
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/sync/sync.component.scss` line 64 at r3](https://reviewable.io/reviews/sillsdev/web-xforge/1411#-N5lt0HbBTuCnoAWml08:-N5lt0Hc1R2W_aFgZoJl:b-ike5py) ([raw file](https://github.com/sillsdev/web-xforge/blob/3cbd9f5d09517098d13c86c69680eba5e0852bb8/src/SIL.XForge.Scripture/ClientApp/src/app/sync/sync.component.scss#L64)):*
> ```SCSS
>   text-align: left;
>   max-width: 40rem;
>   align-self: center;
> ```

Setting `align-self` on all the children doesn't make much sense. It would make a lot more sense to just set `align-items` on the parent element.
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/sync/sync.component.ts` line 108 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/1411#-N5abUtXDB7gMfiMR5Ie:-N5mEW0g3x3HtcP9KzGG:b-u6i4yf) ([raw file](https://github.com/sillsdev/web-xforge/blob/f4cd3a2373c38a9494931ac22c5e106a326f8f57/src/SIL.XForge.Scripture/ClientApp/src/app/sync/sync.component.ts#L108)):*
<details><summary><i>Previously, marksvc wrote…</i></summary><blockquote>

I'm not sure I'm comfortable comparing a left-side null or undefined to a right-side boolean. I've probably done it in other places without thinking about it. I'll give it a go. 
</blockquote></details>

I don't see a problem with it. I think this is a pattern we use a lot of places. The condition will always be false if it's nullish. If we were using weak equality (`==`) then it would be somewhat concerning because it can lead to type coercion.

**Comment by marksvc** [comment]
Screenshots of the component when thin and wide. (With pieces on that are normally conditional.)

sync-page-thin

sync-page-wide

**Review by Nateowami — CHANGES_REQUESTED** [review]
A few changes requested. I think they should be fairly simple. Thanks for your work on this.

> Reviewed 4 of 4 files at r4.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1411#-:-N5pqoOt4pGarftlL7Hj:b-brg3ew)* status: all files reviewed (commit messages unreviewed), 2 unresolved discussions (waiting on @marksvc)

___
*[`src/SIL.XForge.Scripture/ClientApp/src/_variables.scss` line 21 at r4](https://reviewable.io/reviews/sillsdev/web-xforge/1411#-N5pq1DlAoCl4dDVQ1tz:-N5pq1DlAoCl4dDVQ1u-:b-3c5qn5) ([raw file](https://github.com/sillsdev/web-xforge/blob/048ac001c22f3aedd83f7cb86fb0e59ced4dc607/src/SIL.XForge.Scripture/ClientApp/src/_variables.scss#L21)):*
> ```SCSS
> $border-color: rgba(0, 0, 0, 0.12);
> /* A text color that stands out less. */
> $subtleTextColor: $greyLight;
> ```

Could we go with `#666666` instead? That will exactly match what mat-hint does (`rgba(0,0,0,.6)`) on a white background, which is nice for consistency. More importantly, it meets contrast rules for visual accessibility: https://webaim.org/resources/contrastchecker/, which `$greyLight` does not. I have good eyes and even I feel this color is a little too light.
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/sync/sync.component.scss` line 61 at r3](https://reviewable.io/reviews/sillsdev/web-xforge/1411#-N5ltc5p10AL8zWjZFVO:-N5poyXI7uZzY7KnM-qp:b8pr492) ([raw file](https://github.com/sillsdev/web-xforge/blob/3cbd9f5d09517098d13c86c69680eba5e0852bb8/src/SIL.XForge.Scripture/ClientApp/src/app/sync/sync.component.scss#L61)):*
<details><summary><i>Previously, marksvc wrote…</i></summary><blockquote>

I made a variable in _variables.scss for the subtle text colour. I am having it use another colour that is already used, tho for things like border lines ($greyLight). I'm not sure if this is fitting what you are thinking. We can chat more about it.

BTW I see that _variable.scss has a mix of snake_case, kebab-case, and lowerCamelCase. I went with the more dominant lowerCamelCase, tho I wonder if kebab-case would have been the appropriate choice?
</blockquote></details>

It would be good for us to clean up the style of the variables at some point, but they're already inconsistent, so I wouldn't worry about it too much.
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/sync/sync.component.scss` line 64 at r3](https://reviewable.io/reviews/sillsdev/web-xforge/1411#-N5lt0HbBTuCnoAWml08:-N5pleZP-BtUKtD8gEM6:bo5s2dh) ([raw file](https://github.com/sillsdev/web-xforge/blob/3cbd9f5d09517098d13c86c69680eba5e0852bb8/src/SIL.XForge.Scripture/ClientApp/src/app/sync/sync.component.scss#L64)):*
<details><summary><i>Previously, marksvc wrote…</i></summary><blockquote>

Ok I re-worked items to fit into that. How's this? 
</blockquote></details>

I think unnecessary nesting of rules in SCSS greatly harms maintainability. I know it's common in our project, but I don't think it's a good idea (I've experienced trouble interpreting it and refactoring it). I've also read articles that argue it's an anti-pattern (though I'm hesitant to hang my argument on "I found people who agree with me" since that's not much of an argument).

In CSS the way you would write this (i.e., basically the only way you *can* do it) is:
``` css
.base-container {
  align-items: center;
}
.sync-card {
  /* more styles go here */
}
```
SCSS *allows* you to nest the rules, like this:
``` scss
.base-container {
  align-items: center;
  .sync-card {
    /* more styles go here */
  }
}
```
Which compiles to:
``` css
.base-container {
  align-items: center;
}
.base-container .sync-card {
  /* more styles go here */
}
```
Sometimes this is *very* useful and makes it easier to write rules without being so redundant. But there's zero benefit that I know of to using it if you don't have a reason to do so. It does make it harder to tell what the full rule is though, harder to refactor, and produces larger output that is *slightly* slower for the CSS engine to match to elements (that last point is probably more academic than practical).

It also doesn't make much sense to nest an ID selector under something, since IDs are unique anyway.

**Review by marksvc — COMMENTED** [review]
I changed the variable name to lighterTextColor, since #666666 seems close to the normal text colour.

> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1411#-:-N5qQd2mEdFUXHFFdA9r:b-xabohi)* status: all files reviewed (commit messages unreviewed), 2 unresolved discussions (waiting on @Nateowami)

___
*[`src/SIL.XForge.Scripture/ClientApp/src/_variables.scss` line 21 at r4](https://reviewable.io/reviews/sillsdev/web-xforge/1411#-N5pq1DlAoCl4dDVQ1tz:-N5qOGYh5b2Q_hNT7qFM:b-896fix) ([raw file](https://github.com/sillsdev/web-xforge/blob/048ac001c22f3aedd83f7cb86fb0e59ced4dc607/src/SIL.XForge.Scripture/ClientApp/src/_variables.scss#L21)):*
<details><summary><i>Previously, Nateowami (Nathaniel Paulus) wrote…</i></summary><blockquote>

Could we go with `#666666` instead? That will exactly match what mat-hint does (`rgba(0,0,0,.6)`) on a white background, which is nice for consistency. More importantly, it meets contrast rules for visual accessibility: https://webaim.org/resources/contrastchecker/, which `$greyLight` does not. I have good eyes and even I feel this color is a little too light.
</blockquote></details>

Done.
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/sync/sync.component.scss` line 64 at r3](https://reviewable.io/reviews/sillsdev/web-xforge/1411#-N5lt0HbBTuCnoAWml08:-N5qOsmT2jKIPqLaXt1S:b-896fix) ([raw file](https://github.com/sillsdev/web-xforge/blob/3cbd9f5d09517098d13c86c69680eba5e0852bb8/src/SIL.XForge.Scripture/ClientApp/src/app/sync/sync.component.scss#L64)):*
<details><summary><i>Previously, Nateowami (Nathaniel Paulus) wrote…</i></summary><blockquote>

I think unnecessary nesting of rules in SCSS greatly harms maintainability. I know it's common in our project, but I don't think it's a good idea (I've experienced trouble interpreting it and refactoring it). I've also read articles that argue it's an anti-pattern (though I'm hesitant to hang my argument on "I found people who agree with me" since that's not much of an argument).

In CSS the way you would write this (i.e., basically the only way you *can* do it) is:
``` css
.base-container {
  align-items: center;
}
.sync-card {
  /* more styles go here */
}
```
SCSS *allows* you to nest the rules, like this:
``` scss
.base-container {
  align-items: center;
  .sync-card {
    /* more styles go here */
  }
}
```
Which compiles to:
``` css
.base-container {
  align-items: center;
}
.base-container .sync-card {
  /* more styles go here */
}
```
Sometimes this is *very* useful and makes it easier to write rules without being so redundant. But there's zero benefit that I know of to using it if you don't have a reason to do so. It does make it harder to tell what the full rule is though, harder to refactor, and produces larger output that is *slightly* slower for the CSS engine to match to elements (that last point is probably more academic than practical).

It also doesn't make much sense to nest an ID selector under something, since IDs are unique anyway.
</blockquote></details>

Done.

**Pull request merged**
