### PR TITLE
Update to Angular 12

### PR DESCRIPTION
**Pull request by irahopkinson**
This change is [Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1141)

### CODE REVIEW

**Review by RaymondLuong3 — COMMENTED** [review]
> Reviewed 11 of 11 files at r1, 7 of 7 files at r2.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1141)* status: 10 of 53 files reviewed, all discussions resolved (waiting on @RaymondLuong3)

**Review by marksvc — DISMISSED** [review]
> Reviewed 2 of 47 files at r6, 1 of 11 files at r7, 15 of 19 files at r8, 2 of 22 files at r9, 4 of 21 files at r10, 1 of 7 files at r11, 1 of 10 files at r13.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1141)* status: 30 of 97 files reviewed, 1 unresolved discussion (waiting on @irahopkinson, @marksvc, and @RaymondLuong3)

___
*[scripts/db_tools/text-doc-history.js, line 27 at r17](https://reviewable.io/reviews/sillsdev/web-xforge/1141#-N0CdZFU1tLssfjkgypY:-N0CdZFU1tLssfjkgypZ:b-vtlayy) ([raw file](https://github.com/sillsdev/web-xforge/blob/dc30d6032af7b4f8f45374336a778a6f27ff4891/scripts/db_tools/text-doc-history.js#L27)):*
> ```JavaScript
>   const ws = new WebSocket(connectionConfig.wsConnectionString);
>   const conn = new ShareDB.Connection(ws);
>   const client = await MongoClient.connect(connectionConfig.dbLocation);
> ```

I am having a hard time finding where this is the correct direction. What I find so far when searching is saying to _add_ `useUnifiedTopology: true`. Can you explain more?

(Here and in index.ts)



_Code quote:_
```JavaScript
  const client = await MongoClient.connect(connectionConfig.dbLocation);
```
___
*[src/SIL.XForge.Scripture/ClientApp/.husky/pre-commit, line 2 at r17](https://reviewable.io/reviews/sillsdev/web-xforge/1141#-N0Cz-vLBNjd8fvto0c0:-N0Cz-vM82UqYJmWfeeS:b4imr2b) ([raw file](https://github.com/sillsdev/web-xforge/blob/dc30d6032af7b4f8f45374336a778a6f27ff4891/src/SIL.XForge.Scripture/ClientApp/.husky/pre-commit#L2)):*
> ```
> #!/bin/sh
> . "$(dirname "$0")/_/husky.sh"
> ```

Hmm, okay.



_Code quote:_
```
)/_/h
```
___
*[src/SIL.XForge.Scripture/ClientApp/src/app/shared/text/drag-and-drop.ts, line 148 at r17](https://reviewable.io/reviews/sillsdev/web-xforge/1141#-N0D-xkR80j4djLGNcoX:-N0D-xkR80j4djLGNcoY:bog2ati) ([raw file](https://github.com/sillsdev/web-xforge/blob/dc30d6032af7b4f8f45374336a778a6f27ff4891/src/SIL.XForge.Scripture/ClientApp/src/app/shared/text/drag-and-drop.ts#L148)):*
> ```XML
> 
>     let element: Element = targetElement;
>     while (element.localName !== 'usx-segment' && element.parentElement != null) {
> ```

Thank you. Did you find that thru new lint rules?



_Code quote:_
```XML
 !== 'u
```

**Review by Nateowami — CHANGES_REQUESTED** [review]
> Reviewed 4 of 11 files at r1, 2 of 47 files at r6, 3 of 11 files at r7, 16 of 19 files at r8, 11 of 22 files at r9, 15 of 21 files at r10, 2 of 7 files at r11, 5 of 10 files at r12, 6 of 10 files at r13, 1 of 6 files at r14, 6 of 15 files at r15, 8 of 13 files at r16, 3 of 4 files at r17, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1141)* status: 83 of 97 files reviewed, 8 unresolved discussions (waiting on @irahopkinson, @marksvc, @Nateowami, and @RaymondLuong3)

___
*[scripts/db_tools/text-doc-history.js, line 27 at r17](https://reviewable.io/reviews/sillsdev/web-xforge/1141#-N0CKNUD4hGu_67Y4PSX:-N0CKNUD4hGu_67Y4PSY:bwsbvij) ([raw file](https://github.com/sillsdev/web-xforge/blob/aaebfae328fcc28f3efd08c13a718a1b443dbacf/scripts/db_tools/text-doc-history.js#L27)):*
> ```JavaScript
>   const ws = new WebSocket(connectionConfig.wsConnectionString);
>   const conn = new ShareDB.Connection(ws);
>   const client = await MongoClient.connect(connectionConfig.dbLocation, { useUnifiedTopology: true });
> ```

Why is `useUnifiedTopology` being removed? I can't find much about it. I saw some documentation saying it would be the default in the future, so maybe it is now? If that's the case, then I would think we would remove it everywhere it's used. There are still two places where we set `useUnifiedTopology: true`.
___
*[src/SIL.XForge.Scripture/ClientApp/.browserslistrc, line 7 at r17](https://reviewable.io/reviews/sillsdev/web-xforge/1141#-N0CRn6u2Hk-_g-rC7RM:-N0CRn6u2Hk-_g-rC7RN:bu2hpcd) ([raw file](https://github.com/sillsdev/web-xforge/blob/dc30d6032af7b4f8f45374336a778a6f27ff4891/src/SIL.XForge.Scripture/ClientApp/.browserslistrc#L7)):*
> ```Browserslist
> # For IE 9-11 support, please remove 'not' from the last line of the file and adjust as needed
> 
> last 1 Chrome version
> ```

Surely we'd support at the very least two versions? Browsers aren't updated instantly. Also, this is way more strict than our `supportedBrowser()` function.
___
*[src/SIL.XForge.Scripture/ClientApp/src/styles.scss, line 125 at r17](https://reviewable.io/reviews/sillsdev/web-xforge/1141#-N0Bo2WD2J4wG0lEfa1b:-N0Bo2WD2J4wG0lEfa1c:b-v2efw9) ([raw file](https://github.com/sillsdev/web-xforge/blob/dc30d6032af7b4f8f45374336a778a6f27ff4891/src/SIL.XForge.Scripture/ClientApp/src/styles.scss#L125)):*
> ```SCSS
> }
> .mat-button {
>   text-transform: uppercase;
> ```

This should be removed in light of the rule above:
``` scss
.mdc-button {
  text-transform: initial; // no uppercase labels as we move to @angular/material
}
```
___
*[src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/suggestions-settings-dialog.component.html, line 35 at r17](https://reviewable.io/reviews/sillsdev/web-xforge/1141#-N0CQIwq0RNlvO5z-Cty:-N0CQIwq0RNlvO5z-Ctz:b32lioi) ([raw file](https://github.com/sillsdev/web-xforge/blob/dc30d6032af7b4f8f45374336a778a6f27ff4891/src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/suggestions-settings-dialog.component.html#L35)):*
> ```HTML
>         [max]="100"
>         [(ngModel)]="confidenceThreshold"
>         (input)="confidenceThreshold = $event.value ?? 0"
> ```

If we're using an event listener, should we really be using `[(ngModel)]`, which is supposed to be two-way?
___
*[src/SIL.XForge.Scripture/ClientApp/src/typings/process.d.ts, line 1 at r17](https://reviewable.io/reviews/sillsdev/web-xforge/1141#-N0CnxOfBk8AKMgXMpwh:-N0CnxOfBk8AKMgXMpwi:b-eurkta) ([raw file](https://github.com/sillsdev/web-xforge/blob/dc30d6032af7b4f8f45374336a778a6f27ff4891/src/SIL.XForge.Scripture/ClientApp/src/typings/process.d.ts#L1)):*
> ```XML
> declare module 'process' {}
> ```

What does this do?
___
*[src/SIL.XForge.Scripture/ClientApp/src/xforge-common/route.directive.ts, line 46 at r17](https://reviewable.io/reviews/sillsdev/web-xforge/1141#-N0CEF_hAIv1c2xmMtPD:-N0CEF_hAIv1c2xmMtPE:b68nhnk) ([raw file](https://github.com/sillsdev/web-xforge/blob/dc30d6032af7b4f8f45374336a778a6f27ff4891/src/SIL.XForge.Scripture/ClientApp/src/xforge-common/route.directive.ts#L46)):*
> ```XML
>   @HostListener('mouseup', ['$event'])
>   onMouseUp(event: MouseEvent) {
>     // if it's the middle mouse button (but not a tag, because preventDefault doesn't stop it from opening a new tab)
> ```

Why was the word "an" removed from this comment? I think the meaning of the sentence is different without it, and doesn't make sense. If the entire comment was removed I would assume it was no longer correct, but it's still here but with a different meaning.
___
*[src/SIL.XForge.Scripture/ClientApp/src/xforge-common/system-administration/sa-projects.component.html, line 45 at r17](https://reviewable.io/reviews/sillsdev/web-xforge/1141#-N0BtYMt-_f1mEfZazwC:-N0BtYMt-_f1mEfZazwD:b3tu3sh) ([raw file](https://github.com/sillsdev/web-xforge/blob/dc30d6032af7b4f8f45374336a778a6f27ff4891/src/SIL.XForge.Scripture/ClientApp/src/xforge-common/system-administration/sa-projects.component.html#L45)):*
> ```HTML
>       <ng-container matColumnDef="syncDisabled">
>         <td mat-cell *matCellDef="let row">
>           
> ```

Why are these comments still here?

**Review by Nateowami — CHANGES_REQUESTED** [review]
> Reviewed 1 of 10 files at r12, 1 of 10 files at r13, 3 of 15 files at r15, 4 of 13 files at r16, 1 of 4 files at r17.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1141)* status: 93 of 97 files reviewed, 9 unresolved discussions (waiting on @irahopkinson, @marksvc, @Nateowami, and @RaymondLuong3)

___
*[src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/suggestions-settings-dialog.component.scss, line 19 at r17](https://reviewable.io/reviews/sillsdev/web-xforge/1141#-N0DFQE06EdNIpajiIcP:-N0DFQE06EdNIpajiIcQ:bjiuukc) ([raw file](https://github.com/sillsdev/web-xforge/blob/dc30d6032af7b4f8f45374336a778a6f27ff4891/src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/suggestions-settings-dialog.component.scss#L19)):*
> ```SCSS
> 
> mat-slider.mat-slider-horizontal ::ng-deep {
>   display: flex;
> ```

What's the purpose of `display: flex` here, as opposed to e.g. `width: 100%`? Is there a scenario this is fixing that I haven't noticed?

**Review by irahopkinson — COMMENTED** [review]
I've fixed a bunch of those and responded to the rest.

> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1141#-:-N0TiTm4ApPp-jWulK4A:b-gt2w6a)* status: 7 of 99 files reviewed, 9 unresolved discussions (waiting on @marksvc, @Nateowami, and @RaymondLuong3)

___
*[`scripts/db_tools/text-doc-history.js` line 27 at r17](https://reviewable.io/reviews/sillsdev/web-xforge/1141#-N0CKNUD4hGu_67Y4PSX:-N0TWI5K7x0k4ANI4dmZ:ba0tx24) ([raw file](https://github.com/sillsdev/web-xforge/blob/aaebfae328fcc28f3efd08c13a718a1b443dbacf/scripts/db_tools/text-doc-history.js#L27)):*
<details><summary><i>Previously, Nateowami (Nathaniel Paulus) wrote…</i></summary><blockquote>

Why is `useUnifiedTopology` being removed? I can't find much about it. I saw some documentation saying it would be the default in the future, so maybe it is now? If that's the case, then I would think we would remove it everywhere it's used. There are still two places where we set `useUnifiedTopology: true`.
</blockquote></details>

In the updated client you can no longer set it to false, default is true. I've added a commit to fix up the other 2 places in scripts. Its possible those scripts didn't exist when I first made this change or I just missed them.
___
*[`scripts/db_tools/text-doc-history.js` line 27 at r17](https://reviewable.io/reviews/sillsdev/web-xforge/1141#-N0CdZFU1tLssfjkgypY:-N0TWU6o8UD7rupt-6-i:b-zdo8ms) ([raw file](https://github.com/sillsdev/web-xforge/blob/dc30d6032af7b4f8f45374336a778a6f27ff4891/scripts/db_tools/text-doc-history.js#L27)):*
<details><summary><i>Previously, marksvc wrote…</i></summary><blockquote>

I am having a hard time finding where this is the correct direction. What I find so far when searching is saying to _add_ `useUnifiedTopology: true`. Can you explain more?

(Here and in index.ts)
</blockquote></details>

In the updated client you can no longer set it to false, default is true.
___
*[`src/SIL.XForge.Scripture/ClientApp/.browserslistrc` line 7 at r17](https://reviewable.io/reviews/sillsdev/web-xforge/1141#-N0CRn6u2Hk-_g-rC7RM:-N0TWzqp0mjOJjw4ijvC:buohdz4) ([raw file](https://github.com/sillsdev/web-xforge/blob/dc30d6032af7b4f8f45374336a778a6f27ff4891/src/SIL.XForge.Scripture/ClientApp/.browserslistrc#L7)):*
<details><summary><i>Previously, Nateowami (Nathaniel Paulus) wrote…</i></summary><blockquote>

Surely we'd support at the very least two versions? Browsers aren't updated instantly. Also, this is way more strict than our `supportedBrowser()` function.
</blockquote></details>

This is just set to what Angular is happy with.
___
*[`src/SIL.XForge.Scripture/ClientApp/src/styles.scss` line 125 at r17](https://reviewable.io/reviews/sillsdev/web-xforge/1141#-N0Bo2WD2J4wG0lEfa1b:-N0Thffr-ArwJt8ond3c:b-pjksk1) ([raw file](https://github.com/sillsdev/web-xforge/blob/dc30d6032af7b4f8f45374336a778a6f27ff4891/src/SIL.XForge.Scripture/ClientApp/src/styles.scss#L125)):*
<details><summary><i>Previously, Nateowami (Nathaniel Paulus) wrote…</i></summary><blockquote>

This should be removed in light of the rule above:
``` scss
.mdc-button {
  text-transform: initial; // no uppercase labels as we move to @angular/material
}
```
</blockquote></details>

Good catch, removed. I think another addition after my initial changes that I missed in rebasing. Mark listed a bunch of places where this showed up on the SF-1401 issue. They are all fixed now.
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/shared/text/drag-and-drop.ts` line 148 at r17](https://reviewable.io/reviews/sillsdev/web-xforge/1141#-N0D-xkR80j4djLGNcoX:-N0TXJsJEHRJ0MRhNIAS:b-5pem6d) ([raw file](https://github.com/sillsdev/web-xforge/blob/dc30d6032af7b4f8f45374336a778a6f27ff4891/src/SIL.XForge.Scripture/ClientApp/src/app/shared/text/drag-and-drop.ts#L148)):*
<details><summary><i>Previously, marksvc wrote…</i></summary><blockquote>

Thank you. Did you find that thru new lint rules?
</blockquote></details>

Yes, the new `eqeqeq` rule which I had thought we were already using but alas no, not quite implemented properly until now.
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/suggestions-settings-dialog.component.html` line 35 at r17](https://reviewable.io/reviews/sillsdev/web-xforge/1141#-N0CQIwq0RNlvO5z-Cty:-N0TXtXPBe9oV5aPR8ld:bjp533j) ([raw file](https://github.com/sillsdev/web-xforge/blob/dc30d6032af7b4f8f45374336a778a6f27ff4891/src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/suggestions-settings-dialog.component.html#L35)):*
<details><summary><i>Previously, Nateowami (Nathaniel Paulus) wrote…</i></summary><blockquote>

If we're using an event listener, should we really be using `[(ngModel)]`, which is supposed to be two-way?
</blockquote></details>

I believe there are some events that `(input)` captures that `[(ngModel)]` does not that we need here.
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/suggestions-settings-dialog.component.scss` line 19 at r17](https://reviewable.io/reviews/sillsdev/web-xforge/1141#-N0DFQE06EdNIpajiIcP:-N0TYR_h-eApmO871dAK:b8bnthb) ([raw file](https://github.com/sillsdev/web-xforge/blob/dc30d6032af7b4f8f45374336a778a6f27ff4891/src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/suggestions-settings-dialog.component.scss#L19)):*
<details><summary><i>Previously, Nateowami (Nathaniel Paulus) wrote…</i></summary><blockquote>

What's the purpose of `display: flex` here, as opposed to e.g. `width: 100%`? Is there a scenario this is fixing that I haven't noticed?
</blockquote></details>

Err... don't honestly remember. If you tried some scenarios and didn't find an issue then lets change it to `width: 100%`, is that correct?
___
*[`src/SIL.XForge.Scripture/ClientApp/src/typings/process.d.ts` line 1 at r17](https://reviewable.io/reviews/sillsdev/web-xforge/1141#-N0CnxOfBk8AKMgXMpwh:-N0TYxBm5rSz9SmtObBY:bbzwa5r) ([raw file](https://github.com/sillsdev/web-xforge/blob/dc30d6032af7b4f8f45374336a778a6f27ff4891/src/SIL.XForge.Scripture/ClientApp/src/typings/process.d.ts#L1)):*
<details><summary><i>Previously, Nateowami (Nathaniel Paulus) wrote…</i></summary><blockquote>

What does this do?
</blockquote></details>

This declares `process` as a valid module so that calls like `process.argv` in `revert-docs.js` compile ok. If we wanted to be stricter we would declare the things we use in the `{}` however there are so many valid ones on `process` that I didn't bother.
___
*[`src/SIL.XForge.Scripture/ClientApp/src/xforge-common/route.directive.ts` line 46 at r17](https://reviewable.io/reviews/sillsdev/web-xforge/1141#-N0CEF_hAIv1c2xmMtPD:-N0T_L151h6gVI33FjiJ:b-lifjcb) ([raw file](https://github.com/sillsdev/web-xforge/blob/dc30d6032af7b4f8f45374336a778a6f27ff4891/src/SIL.XForge.Scripture/ClientApp/src/xforge-common/route.directive.ts#L46)):*
<details><summary><i>Previously, Nateowami (Nathaniel Paulus) wrote…</i></summary><blockquote>

Why was the word "an" removed from this comment? I think the meaning of the sentence is different without it, and doesn't make sense. If the entire comment was removed I would assume it was no longer correct, but it's still here but with a different meaning.
</blockquote></details>

Whoops, good catch, I assumed a typo without looking closely enough. I've tried to make the meaning more obvious now. 
___
*[`src/SIL.XForge.Scripture/ClientApp/src/xforge-common/system-administration/sa-projects.component.html` line 45 at r17](https://reviewable.io/reviews/sillsdev/web-xforge/1141#-N0BtYMt-_f1mEfZazwC:-N0TaFraAXnxMbAtnkPc:btquzjz) ([raw file](https://github.com/sillsdev/web-xforge/blob/dc30d6032af7b4f8f45374336a778a6f27ff4891/src/SIL.XForge.Scripture/ClientApp/src/xforge-common/system-administration/sa-projects.component.html#L45)):*
<details><summary><i>Previously, Nateowami (Nathaniel Paulus) wrote…</i></summary><blockquote>

Why are these comments still here?
</blockquote></details>

Good catch, removed.

**Review by Nateowami — APPROVED** [review]
> Reviewed 1 of 1 files at r44, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1141)* status: 95 of 99 files reviewed, 2 unresolved discussions (waiting on @irahopkinson, @marksvc, @Nateowami, and @RaymondLuong3)

**Review by irahopkinson — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1141)* status: 95 of 99 files reviewed, 2 unresolved discussions (waiting on @marksvc, @Nateowami, and @RaymondLuong3)

___
*[`src/SIL.XForge.Scripture/ClientApp/.browserslistrc` line 7 at r17](https://reviewable.io/reviews/sillsdev/web-xforge/1141#-N0CRn6u2Hk-_g-rC7RM:-N0YuT90-6zk_iyIp7aj:b-9egrwj) ([raw file](https://github.com/sillsdev/web-xforge/blob/dc30d6032af7b4f8f45374336a778a6f27ff4891/src/SIL.XForge.Scripture/ClientApp/.browserslistrc#L7)):*
<details><summary><i>Previously, Nateowami (Nathaniel Paulus) wrote…</i></summary><blockquote>

Was this file created by Angular?
</blockquote></details>

Yes, I created a brand new NG12 project were it does create this file and then copied the contents from that. You can read about it here https://angular.io/guide/browser-support.
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/suggestions-settings-dialog.component.scss` line 19 at r17](https://reviewable.io/reviews/sillsdev/web-xforge/1141#-N0DFQE06EdNIpajiIcP:-N0YtqRY74hZgDYymIkq:b-896fix) ([raw file](https://github.com/sillsdev/web-xforge/blob/dc30d6032af7b4f8f45374336a778a6f27ff4891/src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/suggestions-settings-dialog.component.scss#L19)):*
<details><summary><i>Previously, Nateowami (Nathaniel Paulus) wrote…</i></summary><blockquote>

Yes, from what I can tell, replacing:
``` scss
display: flex;
flex-direction: column;
padding: 0;
```
with:
``` scss
width: 100%;
```
works fine.
</blockquote></details>

Done.

**Review by Nateowami — COMMENTED** [review]
> Dismissed @marksvc from a discussion.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1141)* status: 95 of 99 files reviewed, all discussions resolved (waiting on @marksvc, @Nateowami, and @RaymondLuong3)

**Review by Nateowami — COMMENTED** [review]
@irahopkinson I think I'll let you merge this how you think best, rather than trying to do it myself.

> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1141#-:-N0YyG_D2rOSez21ANvv:b-3dvd1h)* status: 95 of 99 files reviewed, all discussions resolved (waiting on @marksvc, @Nateowami, and @RaymondLuong3)

**Pull request merged**
