### PR TITLE
Add script to monitor Paratext registry server

### PR DESCRIPTION
**Pull request by Nateowami**
This change is [Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/2428)

### CODE REVIEW

**Review by marksvc — APPROVED** [review]
So, I approve. But you will want to look at my modifications. It is working on my computer.

> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/2428#-:-Nw6IjTX298hUBgAWVr7:b81fnz3)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @Nateowami)

**Comment by marksvc** [comment]
Or, maybe it's having trouble refreshing tokens for me? Investigating.

**Comment by marksvc** [comment]
Okay, it seems to be refreshing and storing tokens successfully.

**Comment by marksvc** [comment]
@Nateowami

**Review by Nateowami — COMMENTED** [review]
It doesn't properly handle 502 responses, which sometimes happen, but I'm going to merge anyway.

> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/2428#-:-NweqetLC1IIyQYFIrVV:bo2zlhx)* status: 0 of 1 files reviewed, all discussions resolved (waiting on @marksvc)

**Pull request merged**
