### PR TITLE
SF-3076 Simplify guest role sharing settings

### PR DESCRIPTION
**Pull request by pmachapman**
This PR updates the sharing functionality to be configured via a simplified interface in Settings.

To achieve this, the following modifications were made to the Scripture Forge codebase:

 * Implementation of a `rolePermissions` property in `sf_project` (similar to `userPermissions` but per role).
 * Sharing of default rights-by-role via the JSON file `rightsByRole.json` which is loaded into TypeScript (in the RealtimeServer and Frontend) and C# (dotnet backend).
 * Implementation of `SFProjectRole` and `Operation` in C# to allow permissions to be strongly typed.
    * _**Note:** I am considering a future PR that will use DefinitelyTyped to have these data structures defined just once (in C#) then autogenerated as TypeScript enums. To stop this PR growing any further, I have not included that in this PR._
 * Sharing code between `ShareDialogComponent` and `ShareControlComponent` via `ShareBaseComponent`.
 * Organization of the MongoDB migration scripts into the directory `mongodb/Migrations/`
 * Improved test coverage of related code, and fixed erroneous Realtime Server unit tests.

These changes have made this PR considerably larger than originally envisaged, but the goal is a simplification and unification of permission calculations which should make future PRs with permissions simpler.

**Notes**

 * Before running this code, you will need to run the MongoDB migration script `mongodb/Migrations/20241127-AddCreatedByRoleToShareKeys.mongodb`

**Design Mock Up**

image

- - -
This change is [Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/2858)

### CODE REVIEW

**Review by kylebuss — CHANGES_REQUESTED** [review]
Excellent work on this Peter. This will be a nice addition once it's finished. I had a couple small comments for you to look at.

> Reviewed 34 of 52 files at r1, 32 of 32 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/2858#-:-ODDEY3d5Fmpf4IbCk0U:bbvjp9j)* status: all files reviewed, 8 unresolved discussions (waiting on @pmachapman)

___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/shared/share/share-base.component.ts` line 9 at r2](https://reviewable.io/reviews/sillsdev/web-xforge/2858#-ODCvuYaAa8Oy31_BQBp:-ODCvuYaAa8Oy31_BQBq:b-uxdwe4) ([raw file](https://github.com/sillsdev/web-xforge/blob/871c5583fda58dc988944ffcc304e1685d867e44/src/SIL.XForge.Scripture/ClientApp/src/app/shared/share/share-base.component.ts#L9)):*
> ```XML
> import { SF_PROJECT_ROLES } from '../../core/models/sf-project-role-info';
> 
> export abstract class ShareBaseComponent extends SubscriptionDisposable {
> ```

Do we have a Jira issue or a plan for tracking/refactoring where we've use `SubscriptionDisposable` to `DestroyRef`?



_Code quote:_
```XML
extends SubscriptionDisposable
```
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/shared/share/share-dialog.component.ts` line 137 at r2](https://reviewable.io/reviews/sillsdev/web-xforge/2858#-ODCyk8v4G3vZCtsXUXD:-ODCyk8v4G3vZCtsXUXE:b-brd8b5) ([raw file](https://github.com/sillsdev/web-xforge/blob/871c5583fda58dc988944ffcc304e1685d867e44/src/SIL.XForge.Scripture/ClientApp/src/app/shared/share/share-dialog.component.ts#L137)):*
> ```XML
>       canShare &&
>       ((this.shareRole === SFProjectRole.CommunityChecker && this.projectDoc?.data?.checkingConfig.checkingEnabled) ||
>         this.shareRole !== SFProjectRole.CommunityChecker)
> ```

This check seems unnecessary as `canShare` is already handling share permissions.



_Code quote:_
```XML
      ((this.shareRole === SFProjectRole.CommunityChecker && this.projectDoc?.data?.checkingConfig.checkingEnabled) ||
        this.shareRole !== SFProjectRole.CommunityChecker)
```
___
*[`src/SIL.XForge.Scripture/Services/SFProjectService.cs` line 1498 at r2](https://reviewable.io/reviews/sillsdev/web-xforge/2858#-ODD8awJ8dgvPnfJYWOq:-ODD8awJ8dgvPnfJYWOr:b6daa3p) ([raw file](https://github.com/sillsdev/web-xforge/blob/871c5583fda58dc988944ffcc304e1685d867e44/src/SIL.XForge.Scripture/Services/SFProjectService.cs#L1498)):*
> ```Smalltalk
>         {
>             await projectDoc.SubmitJson0OpAsync(op => op.Set(p => p.RolePermissions[role], permissions));
>         }
> ```

We should add a check if Community Checking is disabled and Community Checkers were previously permitted to share that we unset that settings permission. NOTE: This may need to occur where we are updating the settings instead of here in the code.



_Code quote:_
```Smalltalk
        else
        {
            await projectDoc.SubmitJson0OpAsync(op => op.Set(p => p.RolePermissions[role], permissions));
        }
```

**Review by pmachapman — COMMENTED** [review]
> Dismissed @github-advanced-security[bot] from 5 discussions.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/2858)* status: all files reviewed, 3 unresolved discussions (waiting on @kylebuss and @Nateowami)

___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/shared/share/share-base.component.ts` line 9 at r2](https://reviewable.io/reviews/sillsdev/web-xforge/2858#-ODCvuYaAa8Oy31_BQBp:-ODDStJYC4BbryFtr6Hl:blwk8jv) ([raw file](https://github.com/sillsdev/web-xforge/blob/871c5583fda58dc988944ffcc304e1685d867e44/src/SIL.XForge.Scripture/ClientApp/src/app/shared/share/share-base.component.ts#L9)):*
<details><summary><i>Previously, kylebuss (Kyle Buss) wrote…</i></summary><blockquote>

Do we have a Jira issue or a plan for tracking/refactoring where we've use `SubscriptionDisposable` to `DestroyRef`?
</blockquote></details>

No, not that I am aware of. @Nateowami might have an idea?
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/shared/share/share-dialog.component.ts` line 137 at r2](https://reviewable.io/reviews/sillsdev/web-xforge/2858#-ODCyk8v4G3vZCtsXUXD:-ODDWZbD5KZEI9QUBSrV:b-wmvxvv) ([raw file](https://github.com/sillsdev/web-xforge/blob/871c5583fda58dc988944ffcc304e1685d867e44/src/SIL.XForge.Scripture/ClientApp/src/app/shared/share/share-dialog.component.ts#L137)):*
<details><summary><i>Previously, kylebuss (Kyle Buss) wrote…</i></summary><blockquote>

This check seems unnecessary as `canShare` is already handling share permissions.
</blockquote></details>

This part of the if condition is checking whether the role that the user wants to be shared can be shared. i.e. we only want to invite users as Community checkers if Community Checking is enabled in the project settings.
___
*[`src/SIL.XForge.Scripture/Services/SFProjectService.cs` line 1498 at r2](https://reviewable.io/reviews/sillsdev/web-xforge/2858#-ODD8awJ8dgvPnfJYWOq:-ODDWzKI5JVu2bnqNLjW:bqaeqdd) ([raw file](https://github.com/sillsdev/web-xforge/blob/871c5583fda58dc988944ffcc304e1685d867e44/src/SIL.XForge.Scripture/Services/SFProjectService.cs#L1498)):*
<details><summary><i>Previously, kylebuss (Kyle Buss) wrote…</i></summary><blockquote>

We should add a check if Community Checking is disabled and Community Checkers were previously permitted to share that we unset that settings permission. NOTE: This may need to occur where we are updating the settings instead of here in the code.
</blockquote></details>

This property is unrelated to community checking. `SFProjectService.CheckShareKeyValidity()` contains the check you are referring to, via the roles returned by `SFProjectService.GetAvailableRoles()`

The permission that will currently be set via this endpoint is `SF_PROJECT_RIGHTS.joinRight(SFProjectDomain.UserInvites, Operation.Create)` (see `SettingsComponent.updateSharingSetting()`). Although, an admin could add any permission they have and grant it to another user.

**Review by kylebuss — CHANGES_REQUESTED** [review]
> Reviewed 6 of 6 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/2858)* status: all files reviewed, 2 unresolved discussions (waiting on @Nateowami and @pmachapman)

___
*[`src/SIL.XForge.Scripture/Services/SFProjectService.cs` line 1498 at r2](https://reviewable.io/reviews/sillsdev/web-xforge/2858#-ODD8awJ8dgvPnfJYWOq:-ODGrNSLA3qRnNzp1KIQ:b60b1gz) ([raw file](https://github.com/sillsdev/web-xforge/blob/871c5583fda58dc988944ffcc304e1685d867e44/src/SIL.XForge.Scripture/Services/SFProjectService.cs#L1498)):*
<details><summary><i>Previously, pmachapman (Peter Chapman) wrote…</i></summary><blockquote>

This property is unrelated to community checking. `SFProjectService.CheckShareKeyValidity()` contains the check you are referring to, via the roles returned by `SFProjectService.GetAvailableRoles()`

The permission that will currently be set via this endpoint is `SF_PROJECT_RIGHTS.joinRight(SFProjectDomain.UserInvites, Operation.Create)` (see `SettingsComponent.updateSharingSetting()`). Although, an admin could add any permission they have and grant it to another user.
</blockquote></details>

This was probably the wrong place in the code to address the scenario that I was thinking of.

Here are the steps:

1. Navigate to the settings page.
2. Enable Community Checking.
3. Enable Allow Community Checkers to invite others.
4. Disable Community Checking.
5. Enable Community Checking.
6. Observe that Allow Community Checkers to invite others is still enabled.

I would expect us to remove the "Allow Community Checkers to invite others" permission if we disable Community Checking all together.

**Review by Nateowami — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/2858)* status: all files reviewed, 2 unresolved discussions (waiting on @kylebuss and @pmachapman)

___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/shared/share/share-base.component.ts` line 9 at r2](https://reviewable.io/reviews/sillsdev/web-xforge/2858#-ODCvuYaAa8Oy31_BQBp:-ODHGuOT1hxEXMIoURok:b-ba2hm) ([raw file](https://github.com/sillsdev/web-xforge/blob/871c5583fda58dc988944ffcc304e1685d867e44/src/SIL.XForge.Scripture/ClientApp/src/app/shared/share/share-base.component.ts#L9)):*
<details><summary><i>Previously, pmachapman (Peter Chapman) wrote…</i></summary><blockquote>

No, not that I am aware of. @Nateowami might have an idea?
</blockquote></details>

No, there isn't. I kind of look at deprecations as self-documenting and generally not being urgent (though it's always nice when they get addressed).

The reason I marked it as deprecated was because I wanted it to no longer get used for new components. I'm guessing it's used here because this was ported from something already using it.

**Comment by kylebuss** [comment]
*[`src/SIL.XForge.Scripture/ClientApp/src/app/shared/share/share-base.component.ts` line 9 at r2](https://reviewable.io/reviews/sillsdev/web-xforge/2858#-ODCvuYaAa8Oy31_BQBp:-ODHQQlVDPzmSksGfhUG:bt45lcg) ([raw file](https://github.com/sillsdev/web-xforge/blob/871c5583fda58dc988944ffcc304e1685d867e44/src/SIL.XForge.Scripture/ClientApp/src/app/shared/share/share-base.component.ts#L9)):*
<details><summary><i>Previously, Nateowami wrote…</i></summary><blockquote>

No, there isn't. I kind of look at deprecations as self-documenting and generally not being urgent (though it's always nice when they get addressed).

The reason I marked it as deprecated was because I wanted it to no longer get used for new components. I'm guessing it's used here because this was ported from something already using it.
</blockquote></details>

Yes, it was ported over. Thanks for explaining why and how to proceed!

**Review by pmachapman — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/2858)* status: all files reviewed, 1 unresolved discussion (waiting on @kylebuss)

___
*[`src/SIL.XForge.Scripture/Services/SFProjectService.cs` line 1498 at r2](https://reviewable.io/reviews/sillsdev/web-xforge/2858#-ODD8awJ8dgvPnfJYWOq:-ODIA_x84t5OkELhvyqN:bowlvjb) ([raw file](https://github.com/sillsdev/web-xforge/blob/871c5583fda58dc988944ffcc304e1685d867e44/src/SIL.XForge.Scripture/Services/SFProjectService.cs#L1498)):*
<details><summary><i>Previously, kylebuss (Kyle Buss) wrote…</i></summary><blockquote>

This was probably the wrong place in the code to address the scenario that I was thinking of.

Here are the steps:

1. Navigate to the settings page.
2. Enable Community Checking.
3. Enable Allow Community Checkers to invite others.
4. Disable Community Checking.
5. Enable Community Checking.
6. Observe that Allow Community Checkers to invite others is still enabled.

I would expect us to remove the "Allow Community Checkers to invite others" permission if we disable Community Checking all together.
</blockquote></details>

This is by design. I wanted the user's settings to remain in the background when community checking is disabled, so any accidental disabling then re-enabling does not affect the stored sharing settings.

**Review by kylebuss — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/2858#-:-ODIQxDY6GMj1-oBOE5H:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @pmachapman)

**Pull request merged**
