### PR TITLE
SF-1433 Highlight combined verse segments

### PR DESCRIPTION
**Pull request by RaymondLuong3**
* move getVerseSegments method to text-view-model
* move verseSlug to shared utils
* filter for question verses for a given chapter in checking-text component

highlight combined verses

---
This change is [Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1180)

### CODE REVIEW

**Review by Nateowami — COMMENTED** [review]
Just a few comments on a few files. Review barely started.

> Reviewed 2 of 9 files at r1.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1180#-:-Mnd2lz_24O7MS5WBL6Z:b-eibgkj)* status: 2 of 9 files reviewed, 2 unresolved discussions (waiting on @Nateowami and @RaymondLuong3)

___
*[src/SIL.XForge.Scripture/ClientApp/src/app/shared/utils.ts, line 5 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/1180#-MncuNBDBexFfaRRUGUV:-MncuNBE8uXIytHCsLhY:b-twpv9e) ([raw file](https://github.com/sillsdev/web-xforge/blob/7b04dca4e97321d8ae2a2f4f6f310606faf1bcf6/src/SIL.XForge.Scripture/ClientApp/src/app/shared/utils.ts#L5)):*
> ```XML
> 
> // Regular expression for getting the verse from a segment ref
> export const VERSE_FROM_SEGMENT_REF_REGEX = /verse_[0-9]+_([0-9]+-*[0-9]*)[/]*/;
> ```

`[0-9]` can be simplified to `\d` ("d" for "digit").
Shouldn't `-*` be `-?`?
And what is `[/]*`?
___
*[src/SIL.XForge.Scripture/ClientApp/src/app/shared/utils.ts, line 48 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/1180#-Mncl2XlAmZXuvBC-Fob:-Mncl2XlAmZXuvBC-Foc:b-9dpbr9) ([raw file](https://github.com/sillsdev/web-xforge/blob/7b04dca4e97321d8ae2a2f4f6f310606faf1bcf6/src/SIL.XForge.Scripture/ClientApp/src/app/shared/utils.ts#L48)):*
> ```XML
>     return 'verse_' + verse.chapterNum + '_' + verse.verse;
>   }
>   return 'verse_' + verse.chapterNum + '_' + verse.verseNum;
> ```

This could be just `'verse_' + verse.chapterNum + '_' + (verse.verse || verse.verseNum)`

Or if we're [falsy](https://developer.mozilla.org/en-US/docs/Glossary/Falsy)-averse it could be `'verse_' + verse.chapterNum + '_' + (verse.verse == null ? verse.verseNum : verse.verse)`

Or perhaps this is a deliberate stylistic choice? I personally find these easier to read, but that preference may not be shared by everyone.

**Review by Nateowami — COMMENTED** [review]
> Reviewed 5 of 9 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1180)* status: 7 of 9 files reviewed, 2 unresolved discussions (waiting on @Nateowami and @RaymondLuong3)

___
*[src/SIL.XForge.Scripture/ClientApp/src/app/shared/utils.ts, line 5 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/1180#-MncuNBDBexFfaRRUGUV:-MngTL9a1yc7H3sJDo8V:bxe764w) ([raw file](https://github.com/sillsdev/web-xforge/blob/7b04dca4e97321d8ae2a2f4f6f310606faf1bcf6/src/SIL.XForge.Scripture/ClientApp/src/app/shared/utils.ts#L5)):*
<details><summary><i>Previously, Nateowami (Nathaniel Paulus) wrote…</i></summary><blockquote>

`[0-9]` can be simplified to `\d` ("d" for "digit").
Shouldn't `-*` be `-?`?
And what is `[/]*`?
</blockquote></details>

What we discussed: `verse_\d+_(\d+-?\d*)`

**Review by RaymondLuong3 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1180)* status: 5 of 9 files reviewed, 2 unresolved discussions (waiting on @Nateowami)

___
*[src/SIL.XForge.Scripture/ClientApp/src/app/shared/utils.ts, line 5 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/1180#-MncuNBDBexFfaRRUGUV:-Mnm3bUd8Pm-VkGUSX9k:b-rxfqgf) ([raw file](https://github.com/sillsdev/web-xforge/blob/7b04dca4e97321d8ae2a2f4f6f310606faf1bcf6/src/SIL.XForge.Scripture/ClientApp/src/app/shared/utils.ts#L5)):*
<details><summary><i>Previously, Nateowami (Nathaniel Paulus) wrote…</i></summary><blockquote>

What we discussed: `verse_\d+_(\d+-?\d*)`
</blockquote></details>

Thanks. I learned more about regex's from this.
___
*[src/SIL.XForge.Scripture/ClientApp/src/app/shared/utils.ts, line 48 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/1180#-Mncl2XlAmZXuvBC-Fob:-Mnm3iW207pYNisUs5Ml:buxf1ex) ([raw file](https://github.com/sillsdev/web-xforge/blob/7b04dca4e97321d8ae2a2f4f6f310606faf1bcf6/src/SIL.XForge.Scripture/ClientApp/src/app/shared/utils.ts#L48)):*
<details><summary><i>Previously, Nateowami (Nathaniel Paulus) wrote…</i></summary><blockquote>

This could be just `'verse_' + verse.chapterNum + '_' + (verse.verse || verse.verseNum)`

Or if we're [falsy](https://developer.mozilla.org/en-US/docs/Glossary/Falsy)-averse it could be `'verse_' + verse.chapterNum + '_' + (verse.verse == null ? verse.verseNum : verse.verse)`

Or perhaps this is a deliberate stylistic choice? I personally find these easier to read, but that preference may not be shared by everyone.
</blockquote></details>

I wondered if I might be overly condensing this operation, but I'm glad that you mentioned this is clearer in the condensed syntax. That's the affirmation I needed.

**Review by Nateowami — APPROVED** [review]
:lgtm:

> Reviewed 2 of 9 files at r1, 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1180#-:-Mo10CDnA59cUuCSS2YV:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @RaymondLuong3)

___
*[src/SIL.XForge.Scripture/ClientApp/src/app/shared/text/text.component.spec.ts, line 940 at r2](https://reviewable.io/reviews/sillsdev/web-xforge/1180#-Mo0w2gz97jIe2vX_KAi:-Mo0w2gz97jIe2vX_KAj:b-he4kyo) ([raw file](https://github.com/sillsdev/web-xforge/blob/b2d670b8cbcd842c7f4953cd1707155c9619e8b1/src/SIL.XForge.Scripture/ClientApp/src/app/shared/text/text.component.spec.ts#L940)):*
> ```XML
> 
>   get quillEditor(): HTMLElement {
>     return document.getElementsByClassName('ql-container')[0] as HTMLElement;
> ```

nit: This could be `document.querySelector('.ql-container')`, which is arguably simpler. But I'm merging without it. Just mentioning what comes to mind.

**Pull request merged**
