### PR TITLE
Integrate new Scripture Forge Logo

### PR DESCRIPTION
**Pull request by nigel-wells**
* Updated Razor and app headers to include logo with updated SF font
* Updated SVG files to include white for the people in the device rather than cut-outs
* Updated multi-devices.svg to include green color to work better on white background
* Updated all images used by the PWA manifest
* Updated favicon.ico

There are two files that I haven't replaced as I'm not sure where they are being used if at all. I figured if we leave them there and discover some logos not updated then we can update them. If all logos get updated then we can safely remove these files.
* images/logo-sf.svg
* images/logo-sf-white.svg

- - -
This change is [Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/2230)

### CODE REVIEW

**Review by Nateowami — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/2230)* status: 0 of 22 files reviewed, 1 unresolved discussion (waiting on @nigel-wells)

___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/app.component.scss` line 77 at r2](https://reviewable.io/reviews/sillsdev/web-xforge/2230#-NlLvb5C9qsOurqhsbSY:-NlLvb5C9qsOurqhsbSZ:bej9zk3) ([raw file](https://github.com/sillsdev/web-xforge/blob/69caf6d7b6643b1c73465b295db15a272d5cabe0/src/SIL.XForge.Scripture/ClientApp/src/app/app.component.scss#L77)):*
> ```SCSS
>     img {
>       @include media-breakpoint-up(sm, variables.$grid-breakpoints) {
>         margin-left: 8px;
> ```

Maybe `margin-inline-start`? Or increase padding of parent? This doesn't work in RTL.

**Review by nigel-wells — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/2230)* status: 0 of 22 files reviewed, 1 unresolved discussion (waiting on @Nateowami)

___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/app.component.scss` line 77 at r2](https://reviewable.io/reviews/sillsdev/web-xforge/2230#-NlLvb5C9qsOurqhsbSY:-NlLxd0IEUKdbSe_5hMO:bb6un1j) ([raw file](https://github.com/sillsdev/web-xforge/blob/69caf6d7b6643b1c73465b295db15a272d5cabe0/src/SIL.XForge.Scripture/ClientApp/src/app/app.component.scss#L77)):*
<details><summary><i>Previously, Nateowami (Nathaniel Paulus) wrote…</i></summary><blockquote>

Maybe `margin-inline-start`? Or increase padding of parent? This doesn't work in RTL.
</blockquote></details>

Done

**Comment by Nateowami** [comment]
I just pushed a commit that losslessly compresses the PNG images. In the best case, one of the icons shrunk to 28.4% of its previous size. Most are around 1/3 of their previous size.

**Review by Nateowami — APPROVED** [review]

**Review by Nateowami — COMMENTED** [review]
:lgtm:

> Reviewed 3 of 22 files at r4.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/2230#-:-NlQzbcD4bNuFqp9KNgy:bnfp4nl)* status: 3 of 22 files reviewed, all discussions resolved

**Pull request merged**
