### PR TITLE
sync: Add operational logging messages

### PR DESCRIPTION
**Pull request by marksvc**
- To help diagnose the events that lead to problem situations.
- We can trim this down if needed.
- Output information about swallowed exceptions.
- The Log() method gets the project SF Id and user SF Id from the
object instance. But it can also be passed Ids to use (which is useful
in InitAsync(), where _projectDoc and _userSecret may not be set yet.
Otherwise it can fall back to "unknown", such as if we weren't given a
valid user id.
- Specifically specify the ParatextSyncRunner and EngineRuntime as
allowed for "Information" logging. This is redundant with "SIL" on the
line above, but if we remove "SIL" then (1) this makes it clear what
was something that was intended to be logged, and (2) it will be easy
to retain the logging of these.

---
This change is [Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1106)

### CODE REVIEW

**Comment by marksvc** [comment]
I need to revise this based on semmle's report.

**Review by RaymondLuong3 — CHANGES_REQUESTED** [review]
I would like to trim this down, it appears to be excessive the information we are logging. But otherwise it is an improvement in my books from our limited logging we did have.

> Reviewed 6 of 6 files at r1.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1106#-:-Mfn-fMf66TWgM9IU1pv:bqkf84p)* status: all files reviewed, 11 unresolved discussions (waiting on @marksvc)

___
*[src/SIL.XForge.Scripture/Services/ParatextService.cs, line 844 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/1106#-Mfmtq7QAAuHTZOcFLSO:-Mfmtq7R-_4-20veff0b:bfqumgv) ([raw file](https://github.com/sillsdev/web-xforge/blob/4b829b982a5908f0c7829f0748f4ecd22f4aec2d/src/SIL.XForge.Scripture/Services/ParatextService.cs#L844)):*
> ```
>   _logger.LogInformation("Not backing up a DBL resource.");
> ```
This doesn't seem necessary to me. It will appear every time we sync a source.
___
*[src/SIL.XForge.Scripture/Services/ParatextSyncRunner.cs, line 127 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/1106#-MfmvA8w4LgmzH-S5U1y:-MfmvA8w4LgmzH-S5U1z:b-ak4fxk) ([raw file](https://github.com/sillsdev/web-xforge/blob/4b829b982a5908f0c7829f0748f4ecd22f4aec2d/src/SIL.XForge.Scripture/Services/ParatextSyncRunner.cs#L127)):*
> ```
> Log($"RunAsync: A local PT repo backup exists.");
> ```
We can remove this. We want to be alerted only if a backup didn't exist.
___
*[src/SIL.XForge.Scripture/Services/ParatextSyncRunner.cs, line 169 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/1106#-Mfmw-fd3tNzq1GLYeoS:-Mfmw-fd3tNzq1GLYeoT:bpdkdi2) ([raw file](https://github.com/sillsdev/web-xforge/blob/4b829b982a5908f0c7829f0748f4ecd22f4aec2d/src/SIL.XForge.Scripture/Services/ParatextSyncRunner.cs#L169)):*
<details><summary><i alt="summary">Quoted 8 lines of code…</i></summary>

> ```
>                 if (isDataInSync)
>                 {
>                     Log($"RunAsync: Updating texts and questions,answers,comments in local PT repo working dir, since data in sync.");
>                 }
>                 else
>                 {
>                     Log($"RunAsync: Not writing texts and questions,answers,comments to local PT repo working dir, since data not in sync.");
>                 }
> ```
</details>

This isn't necessary since just above we log info about not being in sync.
___
*[src/SIL.XForge.Scripture/Services/ParatextSyncRunner.cs, line 207 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/1106#-MfmwO90BtAVZO8LhOgx:-MfmwO90BtAVZO8LhOgy:b-x2cx3) ([raw file](https://github.com/sillsdev/web-xforge/blob/4b829b982a5908f0c7829f0748f4ecd22f4aec2d/src/SIL.XForge.Scripture/Services/ParatextSyncRunner.cs#L207)):*
> ```
>    await _paratextService.SendReceiveAsync(_userSecret, targetParatextId, progress, token);
> ```
You can add a log after send/receive so we know if it finished successfully or if we get an exception.
___
*[src/SIL.XForge.Scripture/Services/ParatextSyncRunner.cs, line 268 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/1106#-MfmwwfR9bTYgf63APv3:-MfmwwfR9bTYgf63APv4:bynjdmd) ([raw file](https://github.com/sillsdev/web-xforge/blob/4b829b982a5908f0c7829f0748f4ecd22f4aec2d/src/SIL.XForge.Scripture/Services/ParatextSyncRunner.cs#L268)):*
> ```
>  Log($"Updating user access list to resource.");
> ```
We can skip this, we have a log if we hit an exception here.
___
*[src/SIL.XForge.Scripture/Services/ParatextSyncRunner.cs, line 307 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/1106#-Mfmx6GPEKIvsRvqmDVx:-Mfmx6GPEKIvsRvqmDVy:bk77c9e) ([raw file](https://github.com/sillsdev/web-xforge/blob/4b829b982a5908f0c7829f0748f4ecd22f4aec2d/src/SIL.XForge.Scripture/Services/ParatextSyncRunner.cs#L307)):*
> ```
>  Log($"RunAsync: Updating SF DB texts,questions,answers,comments.");
> ```
Skip this too.
___
*[src/SIL.XForge.Scripture/Services/ParatextSyncRunner.cs, line 777 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/1106#-MfmyLE07Tmc_jknOPJ2:-MfmyLE07Tmc_jknOPJ3:b-ktfxk7) ([raw file](https://github.com/sillsdev/web-xforge/blob/4b829b982a5908f0c7829f0748f4ecd22f4aec2d/src/SIL.XForge.Scripture/Services/ParatextSyncRunner.cs#L777)):*
> ```
>  Log($"CompleteSync: Sync was not successful. Rolling back local PT repo.");
> ```
The line below is already enough. we can remove this.
___
*[src/SIL.XForge.Scripture/Services/ParatextSyncRunner.cs, line 781 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/1106#-MfmxztkE_Igw2HRrGaI:-MfmxztkE_Igw2HRrGaJ:b-l1ogvs) ([raw file](https://github.com/sillsdev/web-xforge/blob/4b829b982a5908f0c7829f0748f4ecd22f4aec2d/src/SIL.XForge.Scripture/Services/ParatextSyncRunner.cs#L781)):*
<details><summary><i alt="summary">Quoted 4 lines of code…</i></summary>

> ```
>             else if (!successful)
>             {
>                 Log($"CompleteSync: Sync was not successful. But we don't think we can roll back the local PT repo, so not doing that.");
>             }
> ```
</details>

We can remove this since we already log if we have a backup to roll back to.
___
*[src/SIL.XForge.Scripture/Services/ParatextSyncRunner.cs, line 885 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/1106#-MfmzH7K20f1RDf1XwmH:-MfmzH7K20f1RDf1XwmI:b-h5h9iw) ([raw file](https://github.com/sillsdev/web-xforge/blob/4b829b982a5908f0c7829f0748f4ecd22f4aec2d/src/SIL.XForge.Scripture/Services/ParatextSyncRunner.cs#L885)):*
> ```
> Log($"CompleteSync: Committing transaction to SF DB.");
> ```
Not necessary.
___
*[src/SIL.XForge.Scripture/Services/ParatextSyncRunner.cs, line 901 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/1106#-MfmypaG74tguUeIhh9A:-MfmypaG74tguUeIhh9B:b-uvwylb) ([raw file](https://github.com/sillsdev/web-xforge/blob/4b829b982a5908f0c7829f0748f4ecd22f4aec2d/src/SIL.XForge.Scripture/Services/ParatextSyncRunner.cs#L901)):*
> ```
>       Log($"CompleteSync: Not backing up a local resource.");
> ```
We can skip this line since it will appear every sync with a source.
___
*[src/SIL.XForge.Scripture/Services/ParatextSyncRunner.cs, line 906 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/1106#-Mfmz7kt6XfkFO8lSMqj:-Mfmz7kt6XfkFO8lSMqk:bklf3yy) ([raw file](https://github.com/sillsdev/web-xforge/blob/4b829b982a5908f0c7829f0748f4ecd22f4aec2d/src/SIL.XForge.Scripture/Services/ParatextSyncRunner.cs#L906)):*
> ```
>      Log($"CompleteSync: Not committing transaction to SF DB after failed synchronization attempt. Rolling back SF DB transaction.");
> ```
I don't think this is necessary.

**Review by marksvc — COMMENTED** [review]
I trimmed a bit more, and abbreviated some of the lines.
A successful sync of a project with a based-on project went from 25 lines of log to 16 lines of log with this change. 
(Not including the log-context lines, like `info: SIL.XForge.Scripture.Services.ParatextSyncRunner[0]`)

> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1106#-:-MfnC8lxEepnP3ofqyXV:b-ew94zf)* status: 4 of 6 files reviewed, 11 unresolved discussions (waiting on @RaymondLuong3)

___
*[src/SIL.XForge.Scripture/Services/ParatextService.cs, line 844 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/1106#-Mfmtq7QAAuHTZOcFLSO:-Mfn4ntzARyz0Vbw12d1:b-896fix) ([raw file](https://github.com/sillsdev/web-xforge/blob/4b829b982a5908f0c7829f0748f4ecd22f4aec2d/src/SIL.XForge.Scripture/Services/ParatextService.cs#L844)):*
<details><summary><i>Previously, RaymondLuong3 (Raymond Luong) wrote…</i></summary><blockquote>

> ```
>   _logger.LogInformation("Not backing up a DBL resource.");
> ```
This doesn't seem necessary to me. It will appear every time we sync a source.
</blockquote></details>

Done.
___
*[src/SIL.XForge.Scripture/Services/ParatextSyncRunner.cs, line 127 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/1106#-MfmvA8w4LgmzH-S5U1y:-Mfn4x664FKWVdE499z9:b-896fix) ([raw file](https://github.com/sillsdev/web-xforge/blob/4b829b982a5908f0c7829f0748f4ecd22f4aec2d/src/SIL.XForge.Scripture/Services/ParatextSyncRunner.cs#L127)):*
<details><summary><i>Previously, RaymondLuong3 (Raymond Luong) wrote…</i></summary><blockquote>

> ```
> Log($"RunAsync: A local PT repo backup exists.");
> ```
We can remove this. We want to be alerted only if a backup didn't exist.
</blockquote></details>

Done.
___
*[src/SIL.XForge.Scripture/Services/ParatextSyncRunner.cs, line 169 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/1106#-Mfmw-fd3tNzq1GLYeoS:-Mfn59m414FPKC192QmI:b440olz) ([raw file](https://github.com/sillsdev/web-xforge/blob/4b829b982a5908f0c7829f0748f4ecd22f4aec2d/src/SIL.XForge.Scripture/Services/ParatextSyncRunner.cs#L169)):*
<details><summary><i>Previously, RaymondLuong3 (Raymond Luong) wrote…</i></summary><blockquote>

> ```
>                 if (isDataInSync)
>                 {
>                     Log($"RunAsync: Updating texts and questions,answers,comments in local PT repo working dir, since data in sync.");
>                 }
>                 else
>                 {
>                     Log($"RunAsync: Not writing texts and questions,answers,comments to local PT repo working dir, since data not in sync.");
>                 }
> ```
This isn't necessary since just above we log info about not being in sync.
</blockquote></details>

Good point, thank you. Done.
___
*[src/SIL.XForge.Scripture/Services/ParatextSyncRunner.cs, line 207 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/1106#-MfmwO90BtAVZO8LhOgx:-MfnC65yAsc3vBx_1Vwi:b-896fix) ([raw file](https://github.com/sillsdev/web-xforge/blob/4b829b982a5908f0c7829f0748f4ecd22f4aec2d/src/SIL.XForge.Scripture/Services/ParatextSyncRunner.cs#L207)):*
<details><summary><i>Previously, RaymondLuong3 (Raymond Luong) wrote…</i></summary><blockquote>

> ```
>    await _paratextService.SendReceiveAsync(_userSecret, targetParatextId, progress, token);
> ```
You can add a log after send/receive so we know if it finished successfully or if we get an exception.
</blockquote></details>

Done.
___
*[src/SIL.XForge.Scripture/Services/ParatextSyncRunner.cs, line 268 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/1106#-MfmwwfR9bTYgf63APv3:-Mfn6mqd5VYw82a7i3QK:b-ujxtet) ([raw file](https://github.com/sillsdev/web-xforge/blob/4b829b982a5908f0c7829f0748f4ecd22f4aec2d/src/SIL.XForge.Scripture/Services/ParatextSyncRunner.cs#L268)):*
<details><summary><i>Previously, RaymondLuong3 (Raymond Luong) wrote…</i></summary><blockquote>

> ```
>  Log($"Updating user access list to resource.");
> ```
We can skip this, we have a log if we hit an exception here.
</blockquote></details>

Hmm. Okay. 
___
*[src/SIL.XForge.Scripture/Services/ParatextSyncRunner.cs, line 307 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/1106#-Mfmx6GPEKIvsRvqmDVx:-Mfn6sTV2pwEYNvp4jya:b-qu29r7) ([raw file](https://github.com/sillsdev/web-xforge/blob/4b829b982a5908f0c7829f0748f4ecd22f4aec2d/src/SIL.XForge.Scripture/Services/ParatextSyncRunner.cs#L307)):*
<details><summary><i>Previously, RaymondLuong3 (Raymond Luong) wrote…</i></summary><blockquote>

> ```
>  Log($"RunAsync: Updating SF DB texts,questions,answers,comments.");
> ```
Skip this too.
</blockquote></details>

Oh. This is a key step tho hey. I guess we can just assume that it happened, unless there was an exception.
Done.
___
*[src/SIL.XForge.Scripture/Services/ParatextSyncRunner.cs, line 777 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/1106#-MfmyLE07Tmc_jknOPJ2:-Mfn7hZQ3_xgG7HFzqag:b-896fix) ([raw file](https://github.com/sillsdev/web-xforge/blob/4b829b982a5908f0c7829f0748f4ecd22f4aec2d/src/SIL.XForge.Scripture/Services/ParatextSyncRunner.cs#L777)):*
<details><summary><i>Previously, RaymondLuong3 (Raymond Luong) wrote…</i></summary><blockquote>

> ```
>  Log($"CompleteSync: Sync was not successful. Rolling back local PT repo.");
> ```
The line below is already enough. we can remove this.
</blockquote></details>

Done.
___
*[src/SIL.XForge.Scripture/Services/ParatextSyncRunner.cs, line 781 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/1106#-MfmxztkE_Igw2HRrGaI:-Mfn81Vj2PSb3RUwfz6O:byr4flj) ([raw file](https://github.com/sillsdev/web-xforge/blob/4b829b982a5908f0c7829f0748f4ecd22f4aec2d/src/SIL.XForge.Scripture/Services/ParatextSyncRunner.cs#L781)):*
<details><summary><i>Previously, RaymondLuong3 (Raymond Luong) wrote…</i></summary><blockquote>

> ```
>             else if (!successful)
>             {
>                 Log($"CompleteSync: Sync was not successful. But we don't think we can roll back the local PT repo, so not doing that.");
>             }
> ```
We can remove this since we already log if we have a backup to roll back to.
</blockquote></details>

Right.
___
*[src/SIL.XForge.Scripture/Services/ParatextSyncRunner.cs, line 885 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/1106#-MfmzH7K20f1RDf1XwmH:-Mfn8dAx2GpYdV6tJktU:b-896fix) ([raw file](https://github.com/sillsdev/web-xforge/blob/4b829b982a5908f0c7829f0748f4ecd22f4aec2d/src/SIL.XForge.Scripture/Services/ParatextSyncRunner.cs#L885)):*
<details><summary><i>Previously, RaymondLuong3 (Raymond Luong) wrote…</i></summary><blockquote>

> ```
> Log($"CompleteSync: Committing transaction to SF DB.");
> ```
Not necessary.
</blockquote></details>

Done.
___
*[src/SIL.XForge.Scripture/Services/ParatextSyncRunner.cs, line 901 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/1106#-MfmypaG74tguUeIhh9A:-Mfn8AS6-Dj6pQ8w3VCn:b-896fix) ([raw file](https://github.com/sillsdev/web-xforge/blob/4b829b982a5908f0c7829f0748f4ecd22f4aec2d/src/SIL.XForge.Scripture/Services/ParatextSyncRunner.cs#L901)):*
<details><summary><i>Previously, RaymondLuong3 (Raymond Luong) wrote…</i></summary><blockquote>

> ```
>       Log($"CompleteSync: Not backing up a local resource.");
> ```
We can skip this line since it will appear every sync with a source.
</blockquote></details>

Done.
___
*[src/SIL.XForge.Scripture/Services/ParatextSyncRunner.cs, line 906 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/1106#-Mfmz7kt6XfkFO8lSMqj:-Mfn8iN4-8ybgW9CjlWs:b-896fix) ([raw file](https://github.com/sillsdev/web-xforge/blob/4b829b982a5908f0c7829f0748f4ecd22f4aec2d/src/SIL.XForge.Scripture/Services/ParatextSyncRunner.cs#L906)):*
<details><summary><i>Previously, RaymondLuong3 (Raymond Luong) wrote…</i></summary><blockquote>

> ```
>      Log($"CompleteSync: Not committing transaction to SF DB after failed synchronization attempt. Rolling back SF DB transaction.");
> ```
I don't think this is necessary.
</blockquote></details>

Done.

**Review by RaymondLuong3 — APPROVED** [review]
I see that our coverage drops in both ParatextService and ParatextSyncRunner. That likely means we don't cover many paths and the result is that the additional logging won't be executed. I don't imagine this to hurt us, but good to keep in mind that the coverage in these files could be improved.

> Reviewed 2 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1106#-:-Mfo7sFNE9WoSG2RDLTu:bonvm5r)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @marksvc)

**Pull request merged**
