### PR TITLE
SF-1136 Indicate in Paratext Notes when responses are audio-only

### PR DESCRIPTION
**Pull request by RaymondLuong3**
Questions or answers that are audio without any texts would appear as blank in Paratext. This adds a place holder for that situation in Paratext notes.
Audio_only_response

---
This change is [Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/876)

### CODE REVIEW

**Comment by marksvc** [comment]
:eyes:

**Review by marksvc — APPROVED** [review]
> Reviewed 2 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/876)* status: :shipit: complete! all files reviewed, all discussions resolved

___
*[src/SIL.XForge.Scripture/Services/ParatextNotesMapper.cs, line 93 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/876#-MMWNus30_sLQl-Pn2xM:-MMWNus30_sLQl-Pn2xN:b6u6vws) ([raw file](https://github.com/sillsdev/web-xforge/blob/77fa60e6d900ca52dfe5501cadc65a4d7f47995b/src/SIL.XForge.Scripture/Services/ParatextNotesMapper.cs#L93)):*
> ```
> - audio-only question -
> ```
Hmm, I wonder if this should be localized, and how we would know what language to localize it into. Maybe it's safest to just leave it as English. Maybe a better solution is to provide a token (and this could be the token), and Paratext sees the token and shows a localized string in place of the token, according to the UI language the Paratext user is using.

**Review by RaymondLuong3 — COMMENTED** [review]
@irahopkinson Mark has a good point. I forgot about localizing this. I assume that there is not already a marker that Paratext recognizes. Is it ok for it to be in English?

> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/876#-:-MMX_JFX0F9Yo6etE7aM:bgv97ni)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by irahopkinson — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/876)* status: all files reviewed, 1 unresolved discussion (waiting on @RaymondLuong3)

___
*[src/SIL.XForge.Scripture/Services/ParatextNotesMapper.cs, line 93 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/876#-MMWNus30_sLQl-Pn2xM:-MMYU3Kv1_PzEH3sSBWU:bcthd87) ([raw file](https://github.com/sillsdev/web-xforge/blob/77fa60e6d900ca52dfe5501cadc65a4d7f47995b/src/SIL.XForge.Scripture/Services/ParatextNotesMapper.cs#L93)):*
<details><summary><i>Previously, marksvc wrote…</i></summary><blockquote>

> ```
> - audio-only question -
> ```
Hmm, I wonder if this should be localized, and how we would know what language to localize it into. Maybe it's safest to just leave it as English. Maybe a better solution is to provide a token (and this could be the token), and Paratext sees the token and shows a localized string in place of the token, according to the UI language the Paratext user is using.

</blockquote></details>

Good spotting @marksvc. This string (and below) should be localised into the UI language of the person doing the sync. It's the next best solution without requiring a corresponding change in Paratext.

@marksvc "better solution" is likely the right thing to do, but we don't yet have the relationship with Paratext where we could ask for this kind of change in Paratext. Also what would people who have an older version of Paratext without this change see?

**Review by marksvc — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/876)* status: all files reviewed, 1 unresolved discussion (waiting on @irahopkinson)

___
*[src/SIL.XForge.Scripture/Services/ParatextNotesMapper.cs, line 93 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/876#-MMWNus30_sLQl-Pn2xM:-MMabOXA2imXVe31dxjN:bhp7dnq) ([raw file](https://github.com/sillsdev/web-xforge/blob/77fa60e6d900ca52dfe5501cadc65a4d7f47995b/src/SIL.XForge.Scripture/Services/ParatextNotesMapper.cs#L93)):*
Thanks. 

>  Also what would people who have an older version of Paratext without this change see?

I suppose the token, which could be something reasonable, like the above. Unfortunately only in one language, until they upgrade to a supporting version of Paratext.

But at present, we can just have SF place a localized audio-only message. Although, if, say, a Korean-speaking person were to sync questions and answers, and English-speaking colleagues looked at the result in their Paratext, it might cause confusion. (Tho conversely, a single-language token could for now be similarly confusing.)

I wonder if PT projects have a lingua franca. When questions and answers are written, are they written in the minority language? A trade or majority language? 
When translators on a project communicate, what language do they use? I speculate that a team with a Korean and a German might not use Korean or German. If the have settled on French for a common language to communicate, maybe somehow "audio-only question" should be represented in French.

Ideas without a quick solution. I'm fine if we leave Raymond's work as an English token or if we localize it into something.

**Review by irahopkinson — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/876)* status: all files reviewed, 1 unresolved discussion (waiting on @marksvc)

___
*[src/SIL.XForge.Scripture/Services/ParatextNotesMapper.cs, line 93 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/876#-MMWNus30_sLQl-Pn2xM:-MMcqXPj8-mmfuS_-p4x:by27syu) ([raw file](https://github.com/sillsdev/web-xforge/blob/77fa60e6d900ca52dfe5501cadc65a4d7f47995b/src/SIL.XForge.Scripture/Services/ParatextNotesMapper.cs#L93)):*
<details><summary><i>Previously, marksvc wrote…</i></summary><blockquote>

Thanks. 

>  Also what would people who have an older version of Paratext without this change see?

I suppose the token, which could be something reasonable, like the above. Unfortunately only in one language, until they upgrade to a supporting version of Paratext.

But at present, we can just have SF place a localized audio-only message. Although, if, say, a Korean-speaking person were to sync questions and answers, and English-speaking colleagues looked at the result in their Paratext, it might cause confusion. (Tho conversely, a single-language token could for now be similarly confusing.)

I wonder if PT projects have a lingua franca. When questions and answers are written, are they written in the minority language? A trade or majority language? 
When translators on a project communicate, what language do they use? I speculate that a team with a Korean and a German might not use Korean or German. If the have settled on French for a common language to communicate, maybe somehow "audio-only question" should be represented in French.

Ideas without a quick solution. I'm fine if we leave Raymond's work as an English token or if we localize it into something.



</blockquote></details>

@marksvc yes some good thoughts there and yes no easy solution. We are unlikely to suit every situation with what we can do at the moment so lets try to hit the most common situation. That is why I suggested using the UI langauge of the the sync-er since they want the notes in PT and presumably at least they a can read that language. It also means it is in control of the user where as leaving it in English gives no control whatsoever. In your scenario above where there is a Korean and a German on the project we can at least give them the work-around of changing the UI language to say English (or whatever is their common language) before a sync.

**Review by marksvc — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/876)* status: all files reviewed, 1 unresolved discussion (waiting on @irahopkinson)

___
*[src/SIL.XForge.Scripture/Services/ParatextNotesMapper.cs, line 93 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/876#-MMWNus30_sLQl-Pn2xM:-MMq98H75OP6yWM4uR_b:brxp9sq) ([raw file](https://github.com/sillsdev/web-xforge/blob/77fa60e6d900ca52dfe5501cadc65a4d7f47995b/src/SIL.XForge.Scripture/Services/ParatextNotesMapper.cs#L93)):*
<details><summary><i>Previously, irahopkinson (Ira Hopkinson) wrote…</i></summary><blockquote>

@marksvc yes some good thoughts there and yes no easy solution. We are unlikely to suit every situation with what we can do at the moment so lets try to hit the most common situation. That is why I suggested using the UI langauge of the the sync-er since they want the notes in PT and presumably at least they a can read that language. It also means it is in control of the user where as leaving it in English gives no control whatsoever. In your scenario above where there is a Korean and a German on the project we can at least give them the work-around of changing the UI language to say English (or whatever is their common language) before a sync.
</blockquote></details>

Sounds good.

**Review by RaymondLuong3 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/876)* status: 0 of 4 files reviewed, 1 unresolved discussion (waiting on @irahopkinson and @marksvc)

___
*[src/SIL.XForge.Scripture/Services/ParatextNotesMapper.cs, line 93 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/876#-MMWNus30_sLQl-Pn2xM:-MMqT0FgAEAI-c9X12he:bvkrrif) ([raw file](https://github.com/sillsdev/web-xforge/blob/77fa60e6d900ca52dfe5501cadc65a4d7f47995b/src/SIL.XForge.Scripture/Services/ParatextNotesMapper.cs#L93)):*
<details><summary><i>Previously, marksvc wrote…</i></summary><blockquote>

Sounds good.
</blockquote></details>

Ok, I've localized the audio-string into the UI language of the sync'er user. The other languages need to be translated, but otherwise it is good to go.

**Review by marksvc — CHANGES_REQUESTED** [review]
Good. One comment.

> Reviewed 4 of 4 files at r2.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/876#-:-MMqeXlVBfBV1J2fcNCV:b-606alf)* status: all files reviewed, 2 unresolved discussions (waiting on @irahopkinson and @RaymondLuong3)

___
*[src/SIL.XForge.Scripture/Resources/SharedResource.resx, line 121 at r2](https://reviewable.io/reviews/sillsdev/web-xforge/876#-MMqeBCU9BhlFJHktgFt:-MMqeBCU9BhlFJHktgFu:buch0rc) ([raw file](https://github.com/sillsdev/web-xforge/blob/0c9ed681fa964121bd1abab52ee8d365051a1440/src/SIL.XForge.Scripture/Resources/SharedResource.resx#L121)):*
I think in the comment for this and the next one, we should mention something like 

> {0} will be replaced with the name of the site, such as "Scripture Forge".

so that translators can do better knowing the context, and also how they might need to move the {0} in their translated string.

**Review by RaymondLuong3 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/876)* status: all files reviewed, 2 unresolved discussions (waiting on @irahopkinson and @marksvc)

___
*[src/SIL.XForge.Scripture/Resources/SharedResource.resx, line 121 at r2](https://reviewable.io/reviews/sillsdev/web-xforge/876#-MMqeBCU9BhlFJHktgFt:-MMrLn7Z43kUeMYjPLrs:b-8d0lqt) ([raw file](https://github.com/sillsdev/web-xforge/blob/0c9ed681fa964121bd1abab52ee8d365051a1440/src/SIL.XForge.Scripture/Resources/SharedResource.resx#L121)):*
<details><summary><i>Previously, marksvc wrote…</i></summary><blockquote>

I think in the comment for this and the next one, we should mention something like 

> {0} will be replaced with the name of the site, such as "Scripture Forge".

so that translators can do better knowing the context, and also how they might need to move the {0} in their translated string.
</blockquote></details>

I'm not sure that is necessary. The other resources do not mention the params that come in, and I wonder if that is left out on purpose - maybe so it doesn't distract translators - so translations are strictly based on the text that is visible.

**Review by marksvc — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/876)* status: all files reviewed, 1 unresolved discussion (waiting on @irahopkinson)

___
*[src/SIL.XForge.Scripture/Resources/SharedResource.resx, line 121 at r2](https://reviewable.io/reviews/sillsdev/web-xforge/876#-MMqeBCU9BhlFJHktgFt:-MMv9yNs2v-_YiC6yDrQ:b-sgr8am) ([raw file](https://github.com/sillsdev/web-xforge/blob/0c9ed681fa964121bd1abab52ee8d365051a1440/src/SIL.XForge.Scripture/Resources/SharedResource.resx#L121)):*
<details><summary><i>Previously, RaymondLuong3 (Raymond Luong) wrote…</i></summary><blockquote>

I'm not sure that is necessary. The other resources do not mention the params that come in, and I wonder if that is left out on purpose - maybe so it doesn't distract translators - so translations are strictly based on the text that is visible.
</blockquote></details>

Hmmm. Okay. I'll need to learn more.

**Review by irahopkinson — CHANGES_REQUESTED** [review]
> Reviewed 2 of 4 files at r2.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/876)* status: all files reviewed, 1 unresolved discussion (waiting on @marksvc)

___
*[src/SIL.XForge.Scripture/Services/ParatextNotesMapper.cs, line 93 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/876#-MMWNus30_sLQl-Pn2xM:-MN3euUq3aUDiKqumHoW:b-a1ja7) ([raw file](https://github.com/sillsdev/web-xforge/blob/77fa60e6d900ca52dfe5501cadc65a4d7f47995b/src/SIL.XForge.Scripture/Services/ParatextNotesMapper.cs#L93)):*
<details><summary><i>Previously, RaymondLuong3 (Raymond Luong) wrote…</i></summary><blockquote>

Ok, I've localized the audio-string into the UI language of the sync'er user. The other languages need to be translated, but otherwise it is good to go.
</blockquote></details>

Can you explain why you added the site name into the comment? It doesn't seem necessary to me since we don't add it for ordinary questions or answers - is there some situation or clarification I'm missing that is specific to an audio only question or answer?

**Review by RaymondLuong3 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/876)* status: all files reviewed, 1 unresolved discussion (waiting on @irahopkinson)

___
*[src/SIL.XForge.Scripture/Services/ParatextNotesMapper.cs, line 93 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/876#-MMWNus30_sLQl-Pn2xM:-MN4GEf8DT5VeNIwN7Hu:b-ym3jxj) ([raw file](https://github.com/sillsdev/web-xforge/blob/77fa60e6d900ca52dfe5501cadc65a4d7f47995b/src/SIL.XForge.Scripture/Services/ParatextNotesMapper.cs#L93)):*
<details><summary><i>Previously, irahopkinson (Ira Hopkinson) wrote…</i></summary><blockquote>

Can you explain why you added the site name into the comment? It doesn't seem necessary to me since we don't add it for ordinary questions or answers - is there some situation or clarification I'm missing that is specific to an audio only question or answer?
</blockquote></details>

I put myself in the shoes of a user on Paratext. They may not be aware the project is on SF, so they'll come across this note, and be confused what `- audio-only question -` really means. I added it so that there is less chance of confusion of where this note came from.

**Review by irahopkinson — APPROVED** [review]
Remember to upload the localisation files to crowdin when you merge this.

> Reviewed 2 of 4 files at r2.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/876#-:-MN4PqfE2S798F62Rcvv:b-8zrplq)* status: :shipit: complete! all files reviewed, all discussions resolved

___
*[src/SIL.XForge.Scripture/Services/ParatextNotesMapper.cs, line 93 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/876#-MMWNus30_sLQl-Pn2xM:-MN4PF6h4vaAXmqfU8_J:b-12a3k8) ([raw file](https://github.com/sillsdev/web-xforge/blob/77fa60e6d900ca52dfe5501cadc65a4d7f47995b/src/SIL.XForge.Scripture/Services/ParatextNotesMapper.cs#L93)):*
<details><summary><i>Previously, RaymondLuong3 (Raymond Luong) wrote…</i></summary><blockquote>

I put myself in the shoes of a user on Paratext. They may not be aware the project is on SF, so they'll come across this note, and be confused what `- audio-only question -` really means. I added it so that there is less chance of confusion of where this note came from.
</blockquote></details>

Ok, there is no harm here so lets merge this as is. But you didn't really answer my question. What about text-based questions and answers? Doesn't confusion already exist for them? What makes audio-only different?

**Review by RaymondLuong3 — COMMENTED** [review]
Good reminder. Thanks

> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/876#-:-MN4yNHV6yJMgOkPnRjr:be4hwgb)* status: :shipit: complete! all files reviewed, all discussions resolved

___
*[src/SIL.XForge.Scripture/Services/ParatextNotesMapper.cs, line 93 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/876#-MMWNus30_sLQl-Pn2xM:-MN4yPrM9heJEd-pKJ5m:b-cdnzuv) ([raw file](https://github.com/sillsdev/web-xforge/blob/77fa60e6d900ca52dfe5501cadc65a4d7f47995b/src/SIL.XForge.Scripture/Services/ParatextNotesMapper.cs#L93)):*
<details><summary><i>Previously, irahopkinson (Ira Hopkinson) wrote…</i></summary><blockquote>

Ok, there is no harm here so lets merge this as is. But you didn't really answer my question. What about text-based questions and answers? Doesn't confusion already exist for them? What makes audio-only different?
</blockquote></details>

Good question. IMO, a Paratext Note with a question text and answer text can have value without being familiar with SF, but a audio question or audio response without familiarity with SF is problematic.

**Pull request merged**
