### PR TITLE
SF-1042 - Design nice site unavailable page

### PR DESCRIPTION
**Pull request by nigel-wells**
- Created a template for a server 5xx page

I wasn't sure where this was to sit in our repository so let me know if it should be placed somewhere else.

---
This change is [Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/781)

### CODE REVIEW

**Review by irahopkinson — COMMENTED** [review]
I'm ok with the animation. @nateowami what are you concern about with CPU usage?
The icon and text could be smaller on mobile.

> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/781#-:-MFi7m_y8rymsJ00FWcJ:b8hn9c1)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @irahopkinson and @Nateowami)

___
*[src/SIL.XForge.Scripture/ErrorPages/503.html, line 203 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/781#-MFi3V3N7ymZXR_LRznd:-MFi7faP2ujQ0eCZFe9g:b-2huo3i) ([raw file](https://github.com/sillsdev/web-xforge/blob/edaeccd4f5793ccddfd5f6e717588d53efe8c73b/src/SIL.XForge.Scripture/ErrorPages/503.html#L203)):*
<details><summary><i>Previously, Nateowami (Nathaniel Paulus) wrote…</i></summary><blockquote>

Might asking the user to wait until the next day be excessive? Perhaps "in a few hours," "later," or "soon"? Or direct them to the community site for status updates?

Also, will this message only be shown when the site is down for maintenance, or any time the server responds with 5xx? I just shut down the scriptureforge-web-app service on qa momentarily, and my testing shows that we respond with 503 Service Unavailable.

Also, while I'm not super concerned about this in the short term with the current planned downtime, how do we intend to handle users using Scripture Forge while it is down? Do we tell them (incorrectly) that they are offline? Are they going to be seeing errors? I haven't looked into it; just wondering.
</blockquote></details>

That looks good. Did you see my comment in SF-1042? I think if we change the paragraph wording and add the link in the comment then we are good to go. The current wording assumes its is down because we are upgrading. "SF is likely being upgraded so... Please check here for announcements of scheduled upgrades." With the link they can check if there is scheduled work, if not there is a problem and we would like to hear from them.

**Review by nigel-wells — COMMENTED** [review]
Oh real @nateowami ? I understood CSS animations where not intensive at all. I know the old school jQuery ones - especially ones working with parallax - are very intensive. I was just trying to create a little bit of interest to an ordinary page - happy to remove if it's going to cause performance and lag issues.

> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/781#-:-MFi95U9449BsZUbCsbj:b-6cjupg)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @Nateowami)

**Review by nigel-wells — COMMENTED** [review]
Yes you are quite right - it's the mix of the animation and the `blur` effect on the background text. Crazy! must be because its full screen animation as my CPU drops considerably going down to mobile. Well spotted - I'll remove it.

> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/781#-:-MFiDISh21_ntEmn0hxA:btu4f1v)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @Nateowami)

**Review by irahopkinson — COMMENTED** [review]
It does pop my CPU utilization up from 4% to 8% the whole time the page is open in Chrome or Firefox.

> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/781#-:-MFiDKVT8htPMoRNEvVG:b-a9p4aw)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @Nateowami)

**Review by nigel-wells — COMMENTED** [review]
I've made the various changes as requested.

> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/781#-:-MFiH_6CBTy6GlfNyk3K:bjsbdlc)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @irahopkinson and @Nateowami)

___
*[src/SIL.XForge.Scripture/ErrorPages/503.html, line 203 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/781#-MFi3V3N7ymZXR_LRznd:-MFiHau-0S-3TGw120FC:bc8zcbl) ([raw file](https://github.com/sillsdev/web-xforge/blob/edaeccd4f5793ccddfd5f6e717588d53efe8c73b/src/SIL.XForge.Scripture/ErrorPages/503.html#L203)):*
<details><summary><i>Previously, irahopkinson (Ira Hopkinson) wrote…</i></summary><blockquote>

That looks good. Did you see my comment in SF-1042? I think if we change the paragraph wording and add the link in the comment then we are good to go. The current wording assumes its is down because we are upgrading. "SF is likely being upgraded so... Please check here for announcements of scheduled upgrades." With the link they can check if there is scheduled work, if not there is a problem and we would like to hear from them.
</blockquote></details>

I believe in Cloudflare you can set whatever page you want for whatever server response code which means we could have multiple variations with slightly different messages i.e. this one for `503` and another for `500`.

For those already using the app I don't believe they will be affected as the service worker should keep them happily working away in offline mode as they can't access the backend. Those who have never logged in (and don't have the service worker installed yet) will get this new page returned from Cloudflare.

**Review by irahopkinson — COMMENTED** [review]
:lgtm: I'll let @nateowami sign off on this.

> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/781#-:-MFiVOAwCE2bQpIrI11j:bbx4vsc)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @irahopkinson and @Nateowami)

**Pull request merged**
