### PR TITLE
SF-2153 Add i18n to pre-translation draft UI

### PR DESCRIPTION
**Pull request by siltomato**
This PR adds i18n support to the draft generation page, draft viewer page, and a button on the editor page.

**Added `ngx-transloco-markup` and `ngx-transloco-markup-router-link` npm packages**
- Allows use of tags in translation strings (with existence of corresponding transpiler)
  - Added transpiler for `<em>` tags
- Allows use of external links and router links without splitting translations or using innerHTML
- Uses `<transloco></transloco>` tags and doesn't interfere with existing `*transloco` directive

- - -
This change is [Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/2138)

### CODE REVIEW

**Review by pmachapman — CHANGES_REQUESTED** [review]
Looks good - just some minor feedback!

 * The "Generate draft" menu item in the sidebar is not localized
 * Running `npm ls @ngneat/transloco` shows that transloco 3.2 is installed, while the version required for the version of ngx-transloco-markup is ^4. Based on the matrix at https://www.npmjs.com/package/ngx-transloco-markup#angular-version-compatibility-matrix we either need to downgrade ngx-transloco-markup or upgrade @ngneat/transloco?

> Reviewed 17 of 17 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/2138#-:-NhY4hecBsca07pAQPFV:bmr9cbp)* status: all files reviewed, 3 unresolved discussions (waiting on @siltomato)

___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.html` line 37 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/2138#-NhY8y8zEL_QlnYA7kSb:-NhY8y8zEL_QlnYA7kSc:b-70kgud) ([raw file](https://github.com/sillsdev/web-xforge/blob/9426fae8a726825874124ea769e1b340b8f1d7a4/src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.html#L37)):*
> ```HTML
>         <ng-container *ngIf="showPreviewDraft">
>           <div class="toolbar-separator"></div>
>           <button mat-stroked-button title="Preview draft" class="preview-draft-button" (click)="goToDraftPreview()">
> ```

This tooltip should be the same localized value as the button text.



_Code quote:_
```HTML
"Preview draft"
```
___
*[`src/SIL.XForge.Scripture/ClientApp/src/assets/i18n/non_checking_en.json` line 146 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/2138#-NhYB4OyCYif3Ze5UDSj:-NhYB4OyCYif3Ze5UDSk:bjxkn5f) ([raw file](https://github.com/sillsdev/web-xforge/blob/9426fae8a726825874124ea769e1b340b8f1d7a4/src/SIL.XForge.Scripture/ClientApp/src/assets/i18n/non_checking_en.json#L146)):*
> ```JSON
>     "generate_back_translation_drafts": "Generate back translation drafts",
>     "generate_draft_button": "Generate draft",
>     "generate_draft_detail": "Click [em]\"Generate draft\"[/em] to start the process of generating a back translation draft. This will take at least a few hours.",
> ```

Should this be: `{{ draft_generation.generate_draft_button}}`, or would that make localization harder? (both here and elsewhere below...)

Is it impractical to have it so it says `{{ draft_generation.generate_new_draft_button}}` if the "Generate new draft" button is visible?



_Code quote:_
```JSON
Generate draft
```
___
*[`src/SIL.XForge.Scripture/ClientApp/src/assets/i18n/non_checking_en.json` line 195 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/2138#-NhYBkLt6WqK_mDUI2_g:-NhYBkLt6WqK_mDUI2_h:b-h0uzn0) ([raw file](https://github.com/sillsdev/web-xforge/blob/9426fae8a726825874124ea769e1b340b8f1d7a4/src/SIL.XForge.Scripture/ClientApp/src/assets/i18n/non_checking_en.json#L195)):*
> ```JSON
>     "offline_message": "Draft preview is not available while offline.",
>     "select_apply_to_project": "Select [em]\"Apply to project\"[/em] for each chapter that you want to overwrite with the draft text.",
>     "select_edit": "Select [em]\"Edit\"[/em] to go to the editor page for this chapter.",
> ```

Should these the localized to `{{ draft_viewer.apply_to_project}}` and `{{ draft_viewer.edit}}`, or would that make localization harder?



_Code quote:_
```JSON
    "select_apply_to_project": "Select [em]\"Apply to project\"[/em] for each chapter that you want to overwrite with the draft text.",
    "select_edit": "Select [em]\"Edit\"[/em] to go to the editor page for this chapter.",
```

**Review by siltomato — COMMENTED** [review]
Good catch.  Looks like transloco v4 was just to support angular 13+ with no other breaking changes listed, so I'll just upgrade transloco to v4.

> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/2138#-:-NhbVH3eDEhk_iOKTdET:b9qaasz)* status: 10 of 17 files reviewed, 3 unresolved discussions (waiting on @pmachapman)

___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.html` line 37 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/2138#-NhY8y8zEL_QlnYA7kSb:-NhbXyv4Ckd2zIkacmwR:b-896fix) ([raw file](https://github.com/sillsdev/web-xforge/blob/9426fae8a726825874124ea769e1b340b8f1d7a4/src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.html#L37)):*
<details><summary><i>Previously, pmachapman (Peter Chapman) wrote…</i></summary><blockquote>

This tooltip should be the same localized value as the button text.
</blockquote></details>

Done.
___
*[`src/SIL.XForge.Scripture/ClientApp/src/assets/i18n/non_checking_en.json` line 146 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/2138#-NhYB4OyCYif3Ze5UDSj:-Nhbc_967X0WhPq7tjn6:b-ol9l4l) ([raw file](https://github.com/sillsdev/web-xforge/blob/9426fae8a726825874124ea769e1b340b8f1d7a4/src/SIL.XForge.Scripture/ClientApp/src/assets/i18n/non_checking_en.json#L146)):*
<details><summary><i>Previously, pmachapman (Peter Chapman) wrote…</i></summary><blockquote>

Should this be: `{{ draft_generation.generate_draft_button}}`, or would that make localization harder? (both here and elsewhere below...)

Is it impractical to have it so it says `{{ draft_generation.generate_new_draft_button}}` if the "Generate new draft" button is visible?
</blockquote></details>

Nice! Done.
___
*[`src/SIL.XForge.Scripture/ClientApp/src/assets/i18n/non_checking_en.json` line 195 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/2138#-NhYBkLt6WqK_mDUI2_g:-Nhc1dVuCh_wxAk0sZ2W:b-896fix) ([raw file](https://github.com/sillsdev/web-xforge/blob/9426fae8a726825874124ea769e1b340b8f1d7a4/src/SIL.XForge.Scripture/ClientApp/src/assets/i18n/non_checking_en.json#L195)):*
<details><summary><i>Previously, pmachapman (Peter Chapman) wrote…</i></summary><blockquote>

Should these the localized to `{{ draft_viewer.apply_to_project}}` and `{{ draft_viewer.edit}}`, or would that make localization harder?
</blockquote></details>

Done.

**Review by pmachapman — CHANGES_REQUESTED** [review]
Looks good! Just one thing - are you able to localize the "Generate draft" menu item in the sidebar?

> Reviewed 7 of 7 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/2138#-:-NhdMTUI97s_ips4f4UE:b-pcthz5)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @siltomato)

**Review by siltomato — COMMENTED** [review]
Done.

> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/2138#-:-NhdTjSk3pAVRHHPvOGz:b-896fix)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @siltomato)

**Review by pmachapman — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/2138#-:-NhdUfAD-j7b7b_yjOk8:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @siltomato)

**Pull request merged**
