### PR TITLE
SF-2398 Make tooltips for icon buttons in checking area consistent

### PR DESCRIPTION
**Pull request by Nateowami**
Before there was a mix of tool tips, no tool tips, different types of tool tips (hover text, versus Material).

- No tool tip on "Add question" button when the text is shown
- Tool tip on "Play chapter" is shown, but not for pause. If you've already hit play, it should be pretty obvious what the button is for.

https://github.com/sillsdev/web-xforge/assets/6140710/ec544509-2301-41dd-a802-739937a23db1

- - -
This change is [Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/2223)

### CODE REVIEW

**Review by Nateowami — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/2223)* status: 0 of 4 files reviewed, 2 unresolved discussions

___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking.component.html` line 98 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/2223#-Nl0hSXX4Whmwk9kmqvE:-Nl0hSXX4Whmwk9kmqvF:b2htkr8) ([raw file](https://github.com/sillsdev/web-xforge/blob/519e71756e662cabd84e006973b5e21eae59f15e/src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking.component.html#L98)):*
> ```HTML
>                 </button>
>                 <button
>                   *ngIf="canCreateScriptureAudio && !chapterHasAudio"
> ```

I also made the chapter audio button always present. I think it's a terrible UX to make it disappear once you've added audio.
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/font-size/font-size.component.html` line 16 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/2223#-Nl0hDKj0nTsAH1btNrO:-Nl0hDKk0kIk6yhYwdXa:b-sbw8h2) ([raw file](https://github.com/sillsdev/web-xforge/blob/519e71756e662cabd84e006973b5e21eae59f15e/src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/font-size/font-size.component.html#L16)):*
> ```HTML
>       (click)="adjustFontSize($event, -1)"
>       [disabled]="fontSize === min"
>       title="Decrease font size"
> ```

These tool tips weren't localized, and I didn't think they provided much value. I thought having a tool tip on the button that opens the text size picker was more useful.

**Review by RaymondLuong3 — COMMENTED** [review]
I notice there are a number of other toolbar buttons that do not user the mat-tool-tip. The previous and next chapter in the chapter select uses the native tool tip, and the configure translation suggestions settings button uses the same.

> Reviewed 4 of 4 files at r1, 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/2223#-:-Nl4WpsT9AcmIlY0hxq3:bpv4k1s)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @Nateowami)

**Review by Nateowami — COMMENTED** [review]
Yes, I've noticed the same thing. In this case, I just wanted to address the area I thought was most important, and move us towards using mat-tooltips over titles (which require you to pause for about half a second, which makes them much harder to discover).

Personally I think the previous and next buttons are better without a tool tip (I prefer to use them sparingly, when the meaning isn't completely obvious). I wouldn't have put one on the play icon if it wasn't right beside other icons that have them.

> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/2223#-:-Nl4bOtN5a0dUGhbnIIU:b6r3ra6)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @Nateowami)

**Review by RaymondLuong3 — APPROVED** [review]
Sure, that makes sense. If you are happy with it than let's merge it.

> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/2223#-:-Nl516cMAS5AT1Gv45gB:b-7wixt8)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @Nateowami)

**Comment by Nateowami** [comment]
Sorry. I merged this without thinking.

**Pull request merged**
