### PR TITLE
Sync: Return unmodified USX if no chapter deltas

### PR DESCRIPTION
**Pull request by marksvc**
This is a draft since I want to do some local testing still.
The projects that triggered the problem were probably from a much older SF version than the current.

---
This change is [Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/797)

### CODE REVIEW

**Review by RaymondLuong3 — COMMENTED** [review]
I get an error when I try to connect to a project using this branch. 
```
      Failed to process the job '5f592126f37138278cea74c8': an exception occurred. Retry attempt 1 of 10 will be performed in 00:00:31.
Autofac.Core.DependencyResolutionException: An error occurred during the activation of a particular registration. See the inner exception for details. Registration: Activator = DeltaUsxMapper (ReflectionActivator), Services = [SIL.XForge.Scripture.Services.IDeltaUsxMapper], Lifetime = Autofac.Core.Lifetime.CurrentScopeLifetime, Sharing = None, Ownership = OwnedByLifetimeScope ---> None of the constructors found with 'Autofac.Core.Activators.Reflection.DefaultConstructorFinder' on type 'SIL.XForge.Scripture.Services.DeltaUsxMapper' can be invoked with the available services and parameters:
Cannot resolve parameter 'Microsoft.Extensions.Logging.ILogger logger' of constructor 'Void .ctor(SIL.XForge.Scripture.Services.IGuidService, Microsoft.Extensions.Logging.ILogger)'. (See inner exception for details.)
 ---> Autofac.Core.DependencyResolutionException: None of the constructors found with 'Autofac.Core.Activators.Reflection.DefaultConstructorFinder' on type 'SIL.XForge.Scripture.Services.DeltaUsxMapper' can be invoked with the available services and parameters:
Cannot resolve parameter 'Microsoft.Extensions.Logging.ILogger logger' of constructor 'Void .ctor(SIL.XForge.Scripture.Services.IGuidService, Microsoft.Extensions.Logging.ILogger)'.
```

> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/797#-:-MGoA-iY1UNUZhfVMFEm:b-7939o)* status: 0 of 2 files reviewed, all discussions resolved

**Comment by marksvc** [comment]
The exception caught and handled can be triggered editing the project doc for Ruth and changing texts to only have a 1st chapter (by deleting chapters 2 onwards). Then edit the texts doc for the project's Ruth 1 and delete all the values in the ops array. Then Synchronize in SF.

Another IndexOutOfBounds can be triggered if we have text docs in the SF DB, but a projectdoc texts[n].chapters array does not have all the chapters (eg if you delete all but the first, or all of them).
It does not occur from deleting all the texts documents in the SF DB. Instead, ParatextSyncRunner crashes because dbChapterDocs doesnt have key '1', before getting to ToUsx().
Similarly, it does not occur by deleting just the Genesis 2 text doc from the SF DB.

**Comment by marksvc** [comment]
**Whoever pushes this, please do it at a time when you can smoke-test doing a Synchronization on SF Live.**

**Comment by marksvc** [comment]
No teamcity check? :/

**Review by RaymondLuong3 — APPROVED** [review]
I think this is the right way to go. It looks like users will not be able to edit text on books with chapters missing from the project's TextInfo because the translate app will show the "Invalid formatting" error. So this should correctly overwrite any data in the text doc with what is retrieved from the PT send/receive server.

> Reviewed 2 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/797#-:-MGowbyWDuBLpA9bP-e2:bii2jgf)* status: all files reviewed, 1 unresolved discussion (waiting on @marksvc)

___
*[test/SIL.XForge.Scripture.Tests/Services/DeltaUsxMapperTests.cs, line 844 at r2](https://reviewable.io/reviews/sillsdev/web-xforge/797#-MGovyXn5kMvu-nP736g:-MGovyXn5kMvu-nP736h:b-uc4f0g) ([raw file](https://github.com/sillsdev/web-xforge/blob/d422dfd9244af12ece607e8adc4c234c781fce3d/test/SIL.XForge.Scripture.Tests/Services/DeltaUsxMapperTests.cs#L844)):*
> ```
> public void ToUsx_MismatchNoChaptersNoUsxChange()
> ```
There could also be a test for _logger.Received().Warning().

**Review by ddaspit — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/797)* status: all files reviewed, 2 unresolved discussions (waiting on @marksvc)

___
*[src/SIL.XForge.Scripture/Services/DeltaUsxMapper.cs, line 445 at r2](https://reviewable.io/reviews/sillsdev/web-xforge/797#-MGr0lwmCxuwOX2BKgBD:-MGr0lwmCxuwOX2BKgBE:b-qm6hs8) ([raw file](https://github.com/sillsdev/web-xforge/blob/d422dfd9244af12ece607e8adc4c234c781fce3d/src/SIL.XForge.Scripture/Services/DeltaUsxMapper.cs#L445)):*
> ```Smalltalk
>                     if (usxHasChapters)
>                     {
>                         Logger.LogWarning("ToUsx() received a chapterDeltas with no chapters, and USX with chapters. "
> ```

Since this could be caused by an unknown bug elsewhere in the code, it would probably be good to report this error to Bugsnag, so that we would know if it is still happening.

**Review by marksvc — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/797)* status: all files reviewed, 2 unresolved discussions (waiting on @ddaspit and @RaymondLuong3)

___
*[src/SIL.XForge.Scripture/Services/DeltaUsxMapper.cs, line 445 at r2](https://reviewable.io/reviews/sillsdev/web-xforge/797#-MGr0lwmCxuwOX2BKgBD:-MGt8Fj6174Qs0Rl1rEg:b-896fix) ([raw file](https://github.com/sillsdev/web-xforge/blob/d422dfd9244af12ece607e8adc4c234c781fce3d/src/SIL.XForge.Scripture/Services/DeltaUsxMapper.cs#L445)):*
<details><summary><i>Previously, ddaspit (Damien Daspit) wrote…</i></summary><blockquote>

Since this could be caused by an unknown bug elsewhere in the code, it would probably be good to report this error to Bugsnag, so that we would know if it is still happening.
</blockquote></details>

Done.
___
*[test/SIL.XForge.Scripture.Tests/Services/DeltaUsxMapperTests.cs, line 844 at r2](https://reviewable.io/reviews/sillsdev/web-xforge/797#-MGovyXn5kMvu-nP736g:-MGt7Sd88VtHe8fJT_6w:bbod10n) ([raw file](https://github.com/sillsdev/web-xforge/blob/d422dfd9244af12ece607e8adc4c234c781fce3d/test/SIL.XForge.Scripture.Tests/Services/DeltaUsxMapperTests.cs#L844)):*
<details><summary><i>Previously, RaymondLuong3 (Raymond Luong) wrote…</i></summary><blockquote>

> ```
> public void ToUsx_MismatchNoChaptersNoUsxChange()
> ```
There could also be a test for _logger.Received().Warning().
</blockquote></details>

I did add a test that this message gets included in the report to bugsnag. I won't plan on also testing for LogWarning unless you think I should.

**Review by RaymondLuong3 — APPROVED** [review]
This looks good to me. I'll let @ddaspit check off on it.

> Reviewed 2 of 2 files at r3.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/797#-:-MGtB84tCaBh4xsI7GcW:b-nwgbu8)* status: all files reviewed, 1 unresolved discussion (waiting on @ddaspit)

**Comment by marksvc** [comment]
Oops. I was going to merge this earlier today so I had time to deal with anything that might go wrong, rather than at the end of the day. We aren't in a rush to get this merged, tho.

**Review by ddaspit — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/797#-:-MGv10Fw9lgnQlqFiY1r:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved

**Comment by irahopkinson** [comment]
@marksvc I'm glad you didn't merge this as I have and I almost forgot to set the version number back to v3.0.3-Beta rather than 3.1.0-Beta which is what we want after the migration. I also squashed the commits to make it easy to do some git-foo today.

**Comment by marksvc** [comment]
Oop. Thanks for catching that. Thanks for your help, Ira.

**Pull request merged**
