### PR TITLE
SF-2129 Add Health Endpoint

### PR DESCRIPTION
**Pull request by pmachapman**
This Pull Request adds a `/health-check/` endpoint, accessible only from localhost, that can be used with the NodePing Agent. This will enable use to improve monitoring of Scripture Forge.

To test this, use http://localhost:5000/swagger/index.html. No authentication is necessary due to the localhost restriction.

Documentation is available in the document "Health endpoint" in the shared drive.

- - -
This change is [Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1946)

### CODE REVIEW

**Review by RaymondLuong3 — CHANGES_REQUESTED** [review]
Nice work. I tried this out on Swagger, but I couldn't get it to return success. It showed that my real-time server was down. What should I do to get the health check working? I started the app with `dotnet run`


> Reviewed 4 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1946#-:-NZlCwYN-DHyBE1qxMHw:b-5t24bl)* status: all files reviewed, 4 unresolved discussions (waiting on @pmachapman)

___
*[`src/SIL.XForge.Scripture/Controllers/HealthController.cs` line 139 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/1946#-NZlCIwJ2iwRxiuZdVoE:-NZlCIwJ2iwRxiuZdVoF:b32ogsx) ([raw file](https://github.com/sillsdev/web-xforge/blob/e1ce2f8727c8908ed8e9c6d239c3530d0da77317/src/SIL.XForge.Scripture/Controllers/HealthController.cs#L139)):*
> ```Smalltalk
>         else
>         {
>             return Ok(response);
> ```

The final return would never get hit from what I can tell since the OK response will always return.

**Review by pmachapman — COMMENTED** [review]
I am not sure why that is happening - what does the first project in your MongoDB `sf_projects` collection look like?

> Dismissed @github-code-scanning[bot] from 3 discussions.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1946#-:-NZwAJzG9DUzdonjrFDh:brcribo)* status: all files reviewed, 1 unresolved discussion (waiting on @RaymondLuong3)

___
*[`src/SIL.XForge.Scripture/Controllers/HealthController.cs` line 139 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/1946#-NZlCIwJ2iwRxiuZdVoE:-NZw9uhT8yih76SsLmHG:b6h29w3) ([raw file](https://github.com/sillsdev/web-xforge/blob/e1ce2f8727c8908ed8e9c6d239c3530d0da77317/src/SIL.XForge.Scripture/Controllers/HealthController.cs#L139)):*
<details><summary><i>Previously, RaymondLuong3 (Raymond Luong) wrote…</i></summary><blockquote>

The final return would never get hit from what I can tell since the OK response will always return.
</blockquote></details>

The final return returns the status codes in the `if else` blocks above this `else`. I could just change this line to `statusCode = 200` if you think that's clear - I chose the `Ok(response)` as it made my tests look a little clearer when checking for success.

**Review by RaymondLuong3 — APPROVED** [review]
Ah, you were on to it. The first entry in the `sf_projects` collection was a deleted project that was left over somehow. So the data was null. I removed it from my mongo, and the health endpoint works now. I also see that it is working. I will point out that the message from the serval health endpoint says `the circuit is now open and is not allowing calls` doesn't make a whole lot of sense to me. Do we have control over that message?

> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1946#-:-N_00gAT9PNQQErOlYs5:b-yodn16)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @pmachapman)

___
*[`src/SIL.XForge.Scripture/Controllers/HealthController.cs` line 139 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/1946#-NZlCIwJ2iwRxiuZdVoE:-N_-zdin0W3bfB63vRrE:bsgzc03) ([raw file](https://github.com/sillsdev/web-xforge/blob/2ce4c6e2a73b90f3eb7579ba6c5c5a6cd7573b23/src/SIL.XForge.Scripture/Controllers/HealthController.cs#L139)):*
<details><summary><i>Previously, pmachapman (Peter Chapman) wrote…</i></summary><blockquote>

The final return returns the status codes in the `if else` blocks above this `else`. I could just change this line to `statusCode = 200` if you think that's clear - I chose the `Ok(response)` as it made my tests look a little clearer when checking for success.
</blockquote></details>

Ah yes, you are right. I got hung up on the fact that the else block returned the OK response.

**Review by pmachapman — COMMENTED** [review]
That error message is generated by Polly. I originally was going to have an entire stack trace, but then realized that will be on Bugsnag, so all I need to present is the error message, and the developer who is looking into it can view the complete details there.

> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1946#-:-N_0CW-m0QBBPmkGpbuD:b-wotspk)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @pmachapman)

**Pull request merged**
