### PR TITLE
SF-1363 Cursor in translate tool follows cursor in another browser window and causes glitchy behavior

### PR DESCRIPTION
**Pull request by nigel-wells**
* Only update translate suggestion confidence data for remote updates

There are likely still cases which may not seem ideal i.e. each browser will still rely on whichever browser submitted the last ops. If a reload takes place it will load the last op which may have been from the other browser. If we fully want these independent then we could look at saving in local storage.

See [SF-1363](https://jira.sil.org/browse/SF-1363) for acceptance tests

- - -
This change is [Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/2311)

### CODE REVIEW

**Review by pmachapman — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/2311)* status: all files reviewed, 4 unresolved discussions (waiting on @nigel-wells)

___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.ts` line 689 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/2311#-NpS5wV7EdntunBoSw0H:-NpS5wV7EdntunBoSw0I:b-xz7jmq) ([raw file](https://github.com/sillsdev/web-xforge/blob/d091943b609e77cb386cc1997857f2ce507ad611/src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.ts#L689)):*
> ```XML
>           }
>           this.projectUserConfigChangesSub = this.projectUserConfigDoc.remoteChanges$.subscribe(() => {
>             if (this.projectUserConfigDoc != null && this.projectUserConfigDoc.data != null) {
> ```

nit: This could be:
```ts
if (this.projectUserConfigDoc?.data != null) {
```



_Code quote:_
```XML
if (this.projectUserConfigDoc != null && this.projectUserConfigDoc.data != null) {
```
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.ts` line 1770 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/2311#-NpS7ojm51Pl2yCRND30:-NpS7ojm51Pl2yCRND31:bbmqy5m) ([raw file](https://github.com/sillsdev/web-xforge/blob/d091943b609e77cb386cc1997857f2ce507ad611/src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.ts#L1770)):*
> ```XML
>     this.loadTranslateSuggesterConfidence();
> 
>     if (this.projectUserConfigDoc != null && this.projectUserConfigDoc.data != null) {
> ```

nit: Might as well fix this one too...
```ts
if (this.projectUserConfigDoc?.data != null) {
```



_Code quote:_
```XML
if (this.projectUserConfigDoc != null && this.projectUserConfigDoc.data != null) {
```
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.ts` line 1785 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/2311#-NpS68li-Zb3eOUAWIiB:-NpS68li-Zb3eOUAWIiC:b-xz7jmq) ([raw file](https://github.com/sillsdev/web-xforge/blob/d091943b609e77cb386cc1997857f2ce507ad611/src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.ts#L1785)):*
> ```XML
> 
>   private loadTranslateSuggesterConfidence(): void {
>     if (this.projectUserConfigDoc != null && this.projectUserConfigDoc.data != null) {
> ```

nit: This could be:
```ts
if (this.projectUserConfigDoc?.data != null) {
```



_Code quote:_
```XML
if (this.projectUserConfigDoc != null && this.projectUserConfigDoc.data != null) {
```
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.spec.ts` line 208 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/2311#-NpS96NO7bYYmYOjBuTW:-NpS96NO7bYYmYOjBuTX:b2k8eoy) ([raw file](https://github.com/sillsdev/web-xforge/blob/d091943b609e77cb386cc1997857f2ce507ad611/src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.spec.ts#L208)):*
> ```XML
>   }));
> 
>   it('remote user config should not change segment', fakeAsync(() => {
> ```

I was going to ask if there was an inverse to this test, then I realised the inverse is probably `'selected segment checksum unset on server'`.

**Review by nigel-wells — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/2311)* status: 1 of 2 files reviewed, 1 unresolved discussion (waiting on @pmachapman)

___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.ts` line 689 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/2311#-NpS5wV7EdntunBoSw0H:-NpXAk3i0I-0bIEtji3k:b-6moq87) ([raw file](https://github.com/sillsdev/web-xforge/blob/d091943b609e77cb386cc1997857f2ce507ad611/src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.ts#L689)):*
<details><summary><i>Previously, pmachapman (Peter Chapman) wrote…</i></summary><blockquote>

nit: This could be:
```ts
if (this.projectUserConfigDoc?.data != null) {
```
</blockquote></details>

Done.  That's what happens when I copy and paste code :)
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.spec.ts` line 208 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/2311#-NpS96NO7bYYmYOjBuTW:-NpXB1HrCrqn48mgOlag:bb25ijt) ([raw file](https://github.com/sillsdev/web-xforge/blob/d091943b609e77cb386cc1997857f2ce507ad611/src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.spec.ts#L208)):*
<details><summary><i>Previously, pmachapman (Peter Chapman) wrote…</i></summary><blockquote>

I was going to ask if there was an inverse to this test, then I realised the inverse is probably `'selected segment checksum unset on server'`.
</blockquote></details>

Yep, and funnily enough, that was the only test that initially failed.

**Review by pmachapman — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/2311#-:-NpXHZzPEdUKsHRZuPS2:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @nigel-wells)

**Review by pmachapman — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/2311)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @nigel-wells)

**Pull request merged**
