### PR TITLE
SF-2351 Improve user guidance on draft generation page

### PR DESCRIPTION
**Pull request by siltomato**
Implemented changes described here: https://docs.google.com/document/d/13m-qOWjeuHoi_3X0M7SjhIaZAK41sfSVggS7KyLkPac/edit

- - -
This change is [Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/2194)

### CODE REVIEW

**Review by Nateowami — CHANGES_REQUESTED** [review]
> Reviewed 7 of 12 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/2194)* status: 7 of 12 files reviewed, 5 unresolved discussions (waiting on @siltomato)

___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-generation.component.html` line 14 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/2194#-NkOE3-98PkIc90zPiA5:-NkOE3-98PkIc90zPiA6:b-ipijbf) ([raw file](https://github.com/sillsdev/web-xforge/blob/06f7d16dd1fb0d3886021200ebd20d7a51909f74/src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-generation.component.html#L14)):*
> ```HTML
> 
>     <div *ngIf="isBackTranslationMode" class="requirements">
>       <p>{{ t("back_translation_requirement") }}</p>
> ```

Do you think it might make more sense to link from the statement about only some languages being supported, rather than the statement about the language being supported?

___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-generation.component.html` line 26 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/2194#-NkO8_Lj-tMruSCrwjwz:-NkO8_Lj-tMruSCrwjx-:bljdilk) ([raw file](https://github.com/sillsdev/web-xforge/blob/06f7d16dd1fb0d3886021200ebd20d7a51909f74/src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-generation.component.html#L26)):*
> ```HTML
>             ></transloco>
>             <transloco
>               *ngIf="!isTargetLanguageSupported && !targetLanguageDisplayName"
> ```

Why would `targetLanguageDisplayName` be undefined? It seems unfortunate to have so many different strings to localize when it seems two should be sufficient.
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-generation.component.scss` line 69 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/2194#-NkOB7G7AE8NcZ77xYmY:-NkOB7G7AE8NcZ77xYmZ:b3o6yni) ([raw file](https://github.com/sillsdev/web-xforge/blob/06f7d16dd1fb0d3886021200ebd20d7a51909f74/src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-generation.component.scss#L69)):*
> ```SCSS
> }
> 
> .warning {
> ```

While I like this appearance, it's duplicating the exact purpose of the notice component. 





I like this look on this one better than on our notice component, but I don't like redundancy because it ends up making things inconsistent and we have more things to maintain.
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/supported-back-translation-languages-dialog/supported-back-translation-languages-dialog.component.html` line 4 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/2194#-NkOGyXlEGg43PPmLqx0:-NkOGyXlEGg43PPmLqx1:b-z0zenp) ([raw file](https://github.com/sillsdev/web-xforge/blob/06f7d16dd1fb0d3886021200ebd20d7a51909f74/src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/supported-back-translation-languages-dialog/supported-back-translation-languages-dialog.component.html#L4)):*
> ```HTML
>   <h1>
>     {{ t("supported_back_translation_languages_dialog_header") }}
>     <a mat-dialog-close class="close-dialog-link"><mat-icon>close</mat-icon></a>
> ```

Can you not just use an icon button like we do everywhere else? This results in more code and less consistency.
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/supported-back-translation-languages-dialog/supported-back-translation-languages-dialog.component.scss` line 1 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/2194#-NkOKQP00Lz2sFHKBGSI:-NkOKQP00Lz2sFHKBGSJ:b-fx6u6y) ([raw file](https://github.com/sillsdev/web-xforge/blob/06f7d16dd1fb0d3886021200ebd20d7a51909f74/src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/supported-back-translation-languages-dialog/supported-back-translation-languages-dialog.component.scss#L1)):*
> ```SCSS
> @use 'src/xforge-common/media-breakpoints/breakpoints' as *;
> ```

This entire component is much more complicated than necessary. It looks like you didn't use any of the dialog-related Material directives and then had to work around layout issues that came up because of that. If you change the template to:

``` html
<ng-container *transloco="let t; read: 'supported_back_translation_languages_dialog'">
  <h2 mat-dialog-title>
    {{ t("supported_back_translation_languages_dialog_header") }}
    <button mat-icon-button mat-dialog-close><mat-icon>close</mat-icon></button>
  </h2>

  <mat-dialog-content>
    <div *ngFor="let language of supportedLanguages">
      <span class="code">({{ language.iso639_2t }})</span>
      <span class="name">{{ getLanguageDisplayName(language) }}</span>
    </div>
  </mat-dialog-content>
</ng-container>
```
Then the CSS can just be:

```
.mat-dialog-title {
  display: flex;
  justify-content: space-between;
  gap: 10px; //  not sure this is really needed
}

mat-dialog-content {
  display: grid;
  width: 70vw; // this rule is annoying; for some reason it doesn't try to hog enough space without it
  grid-template-columns: repeat(auto-fit, minmax(190px, 1fr));
  gap: 1em;
  > * {
    display: flex;
    column-gap: 0.5em;
  }
}

.code {
  font-family: monospace;
  color: #777;
}
```

In order to get the close button to look right, I had to import `MatLegacyButtonModule` to `SupportedBackTranslationLanguagesDialogComponent`. There should be a way to do it without the legacy version, but I don't want to spend forever tying to optimize this. 

It also produces a dialog that scrolls vertically (much more normal) and looks more like our other dialogs:

**Review by siltomato — COMMENTED** [review]
Thanks for reworking the dialog using css grid.  That was a great idea.

> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/2194#-:-NkRGkcU8bRIiDhLEU74:b-rf5dq2)* status: 3 of 12 files reviewed, 2 unresolved discussions (waiting on @Nateowami)

___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-generation.component.html` line 14 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/2194#-NkOE3-98PkIc90zPiA5:-NkQzrig9rnhIfvPTbwh:bhmy9cx) ([raw file](https://github.com/sillsdev/web-xforge/blob/06f7d16dd1fb0d3886021200ebd20d7a51909f74/src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-generation.component.html#L14)):*
<details><summary><i>Previously, Nateowami (Nathaniel Paulus) wrote…</i></summary><blockquote>

Do you think it might make more sense to link from the statement about only some languages being supported, rather than the statement about the language being supported?

</blockquote></details>

Yes, that is much better, thanks.
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-generation.component.html` line 26 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/2194#-NkO8_Lj-tMruSCrwjwz:-NkRDEOT-kx6R24_S0Xj:b8y45s) ([raw file](https://github.com/sillsdev/web-xforge/blob/06f7d16dd1fb0d3886021200ebd20d7a51909f74/src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-generation.component.html#L26)):*
<details><summary><i>Previously, Nateowami (Nathaniel Paulus) wrote…</i></summary><blockquote>

Why would `targetLanguageDisplayName` be undefined? It seems unfortunate to have so many different strings to localize when it seems two should be sufficient.
</blockquote></details>

Good point.  It seems like I had a case where it could have been undefined at some point, but it looks like the browser `Intl.DisplayNames` just returns the language code as a fallback.

Removed the cases for undefined `targetLanguageDisplayName`.
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-generation.component.scss` line 69 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/2194#-NkOB7G7AE8NcZ77xYmY:-NkR3OxFBUda4K4sFCj1:bl9gw8k) ([raw file](https://github.com/sillsdev/web-xforge/blob/06f7d16dd1fb0d3886021200ebd20d7a51909f74/src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-generation.component.scss#L69)):*
<details><summary><i>Previously, Nateowami (Nathaniel Paulus) wrote…</i></summary><blockquote>

While I like this appearance, it's duplicating the exact purpose of the notice component. 





I like this look on this one better than on our notice component, but I don't like redundancy because it ends up making things inconsistent and we have more things to maintain.
</blockquote></details>

Ok, cool, I didn't know about the notice component.  Changed warnings to use notice component.  

Should I adjust the notice component style (in a different PR)?
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/supported-back-translation-languages-dialog/supported-back-translation-languages-dialog.component.html` line 4 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/2194#-NkOGyXlEGg43PPmLqx0:-NkRA26NAEn44U8nMLWV:b-a2ujfl) ([raw file](https://github.com/sillsdev/web-xforge/blob/06f7d16dd1fb0d3886021200ebd20d7a51909f74/src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/supported-back-translation-languages-dialog/supported-back-translation-languages-dialog.component.html#L4)):*
<details><summary><i>Previously, Nateowami (Nathaniel Paulus) wrote…</i></summary><blockquote>

Can you not just use an icon button like we do everywhere else? This results in more code and less consistency.
</blockquote></details>

Changed.
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/supported-back-translation-languages-dialog/supported-back-translation-languages-dialog.component.scss` line 1 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/2194#-NkOKQP00Lz2sFHKBGSI:-NkR9_T86zeNVrUGjTuO:b111w91) ([raw file](https://github.com/sillsdev/web-xforge/blob/06f7d16dd1fb0d3886021200ebd20d7a51909f74/src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/supported-back-translation-languages-dialog/supported-back-translation-languages-dialog.component.scss#L1)):*
<details><summary><i>Previously, Nateowami (Nathaniel Paulus) wrote…</i></summary><blockquote>

This entire component is much more complicated than necessary. It looks like you didn't use any of the dialog-related Material directives and then had to work around layout issues that came up because of that. If you change the template to:

``` html
<ng-container *transloco="let t; read: 'supported_back_translation_languages_dialog'">
  <h2 mat-dialog-title>
    {{ t("supported_back_translation_languages_dialog_header") }}
    <button mat-icon-button mat-dialog-close><mat-icon>close</mat-icon></button>
  </h2>

  <mat-dialog-content>
    <div *ngFor="let language of supportedLanguages">
      <span class="code">({{ language.iso639_2t }})</span>
      <span class="name">{{ getLanguageDisplayName(language) }}</span>
    </div>
  </mat-dialog-content>
</ng-container>
```
Then the CSS can just be:

```
.mat-dialog-title {
  display: flex;
  justify-content: space-between;
  gap: 10px; //  not sure this is really needed
}

mat-dialog-content {
  display: grid;
  width: 70vw; // this rule is annoying; for some reason it doesn't try to hog enough space without it
  grid-template-columns: repeat(auto-fit, minmax(190px, 1fr));
  gap: 1em;
  > * {
    display: flex;
    column-gap: 0.5em;
  }
}

.code {
  font-family: monospace;
  color: #777;
}
```

In order to get the close button to look right, I had to import `MatLegacyButtonModule` to `SupportedBackTranslationLanguagesDialogComponent`. There should be a way to do it without the legacy version, but I don't want to spend forever tying to optimize this. 

It also produces a dialog that scrolls vertically (much more normal) and looks more like our other dialogs:

</blockquote></details>

Very nice!  I like the grid version much better.  Changed.

**Review by Nateowami — COMMENTED** [review]
> Reviewed 4 of 7 files at r2.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/2194)* status: 7 of 12 files reviewed, 1 unresolved discussion (waiting on @siltomato)

___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-generation.component.html` line 14 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/2194#-NkOE3-98PkIc90zPiA5:-NkRMoJg2ajfEG_KzNnH:brrbiu2) ([raw file](https://github.com/sillsdev/web-xforge/blob/06f7d16dd1fb0d3886021200ebd20d7a51909f74/src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-generation.component.html#L14)):*
<details><summary><i>Previously, siltomato wrote…</i></summary><blockquote>

Yes, that is much better, thanks.
</blockquote></details>

The notice component also has a basic informational notice style that would make sense to use here: https://644bffe327c540a62f0fd260-dkmomlqqer.chromatic.com/?path=/story/utility-notice--outline

Storybook is intended (among other things) to serve as a library of components to make things like this discoverable. In practice we don't have it organized that well, and not all components are in it, but this one is.
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-generation.component.html` line 26 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/2194#-NkO8_Lj-tMruSCrwjwz:-NkRLNoU9MP-orVxPSSj:by43bv7) ([raw file](https://github.com/sillsdev/web-xforge/blob/06f7d16dd1fb0d3886021200ebd20d7a51909f74/src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-generation.component.html#L26)):*
<details><summary><i>Previously, siltomato wrote…</i></summary><blockquote>

Good point.  It seems like I had a case where it could have been undefined at some point, but it looks like the browser `Intl.DisplayNames` just returns the language code as a fallback.

Removed the cases for undefined `targetLanguageDisplayName`.
</blockquote></details>

Thanks. I like this simplification.
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-generation.component.scss` line 69 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/2194#-NkOB7G7AE8NcZ77xYmY:-NkRLRdODMu26r-rwLjW:b-i4nxki) ([raw file](https://github.com/sillsdev/web-xforge/blob/06f7d16dd1fb0d3886021200ebd20d7a51909f74/src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-generation.component.scss#L69)):*
<details><summary><i>Previously, siltomato wrote…</i></summary><blockquote>

Ok, cool, I didn't know about the notice component.  Changed warnings to use notice component.  

Should I adjust the notice component style (in a different PR)?
</blockquote></details>

I think that would be good, but yes, in a separate PR. And please update Storybook with whatever changes you make. It really shines for showing visual changes.

**Review by Nateowami — COMMENTED** [review]
Just tested the latest version of this branch (7794af8138bce19c1024d3efcf864c8819cb1efe) and it is willing to let me draft a back translation for a project that is not actually a back translation.

> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/2194#-:-NkWoYgk9V1Bc07ls3ep:b-lqztld)* status: 6 of 12 files reviewed, all discussions resolved

**Review by Nateowami — COMMENTED** [review]
The nav menu item should not be there if forward translation drafting is not available. I thought that was already clear.

Additionally, I don't think it should act like you have a back translation when you don't. This is a more minor point, since no one should really see it, but from a testing perspective, if I go to a project that is not a back translation, and it tells me it is, it looks like there's a problem. It's a weird failure mode that looks like something is probably broken.

> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/2194#-:-NkWvQ_92PDXAO2aCaYO:b-m994ih)* status: 6 of 12 files reviewed, all discussions resolved

**Review by Nateowami — COMMENTED** [review]
> Reviewed 1 of 7 files at r2, 3 of 3 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/2194)* status: 10 of 13 files reviewed, 2 unresolved discussions (waiting on @github-advanced-security[bot] and @siltomato)

___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/shared/project-router.guard.ts` line 18 at r5](https://reviewable.io/reviews/sillsdev/web-xforge/2194#-NkYGAGj1P2MH2vNrJgM:-NkYGAGj1P2MH2vNrJgN:bzvhxo) ([raw file](https://github.com/sillsdev/web-xforge/blob/13f87577e12744c7dd6ec64c02dd541cdd64ae7c/src/SIL.XForge.Scripture/ClientApp/src/app/shared/project-router.guard.ts#L18)):*
> ```XML
> abstract class RouterGuard implements CanActivate {
>   constructor(
>     protected authGuard: AuthGuard,
> ```

Why has this entire file been reformatted in a different way than Prettier formats?

**Review by Nateowami — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/2194)* status: 11 of 13 files reviewed, 4 unresolved discussions (waiting on @github-advanced-security[bot] and @siltomato)

___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-generation.component.spec.ts` line 434 at r5](https://reviewable.io/reviews/sillsdev/web-xforge/2194#-NkYiVjtDIR8dri0qA3_:-NkYiVjtDIR8dri0qA3a:bav23dk) ([raw file](https://github.com/sillsdev/web-xforge/blob/13f87577e12744c7dd6ec64c02dd541cdd64ae7c/src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-generation.component.spec.ts#L434)):*
> ```XML
>           projectId$: of('testProjectId'),
>           projectDoc$: of({
>             data: {
> ```

This isn't a full project, but the type system isn't complaining. I'm not sure why.

You could consider something like:
``` ts
import { createTestProjectProfile } from 'realtime-server/lib/esm/scriptureforge/models/sf-project-test-data';

data: createTestProjectProfile(
  // .. whatever properties here are significant to the test
)
```
This would create a full project object, which reduces the chances for the component to try to access a property on the project that the test data does not include.

**Review by siltomato — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/2194)* status: 11 of 13 files reviewed, 1 unresolved discussion (waiting on @github-advanced-security[bot] and @Nateowami)

___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/shared/project-router.guard.ts` line 18 at r5](https://reviewable.io/reviews/sillsdev/web-xforge/2194#-NkYGAGj1P2MH2vNrJgM:-NkYsA2Q9xRtvbL5T32i:bjrntht) ([raw file](https://github.com/sillsdev/web-xforge/blob/13f87577e12744c7dd6ec64c02dd541cdd64ae7c/src/SIL.XForge.Scripture/ClientApp/src/app/shared/project-router.guard.ts#L18)):*
<details><summary><i>Previously, Nateowami (Nathaniel Paulus) wrote…</i></summary><blockquote>

Why has this entire file been reformatted in a different way than Prettier formats?
</blockquote></details>

Not sure why my editor was doing that.  Fixed.
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-generation.component.spec.ts` line 434 at r5](https://reviewable.io/reviews/sillsdev/web-xforge/2194#-NkYiVjtDIR8dri0qA3_:-NkYrz4C49pexGchk7Gk:b8exoju) ([raw file](https://github.com/sillsdev/web-xforge/blob/13f87577e12744c7dd6ec64c02dd541cdd64ae7c/src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-generation.component.spec.ts#L434)):*
<details><summary><i>Previously, Nateowami (Nathaniel Paulus) wrote…</i></summary><blockquote>

This isn't a full project, but the type system isn't complaining. I'm not sure why.

You could consider something like:
``` ts
import { createTestProjectProfile } from 'realtime-server/lib/esm/scriptureforge/models/sf-project-test-data';

data: createTestProjectProfile(
  // .. whatever properties here are significant to the test
)
```
This would create a full project object, which reduces the chances for the component to try to access a property on the project that the test data does not include.
</blockquote></details>

Thanks, that is very helpful.  Changed!

**Review by Nateowami — APPROVED** [review]
> Reviewed 1 of 2 files at r6, 1 of 1 files at r7, 2 of 2 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/2194)* status: all files reviewed, 1 unresolved discussion (waiting on @github-advanced-security[bot])

**Comment by Nateowami** [comment]
@siltomato I'm concerned you might be duplicating my efforts on #2204. Are you available to talk?

**Review by siltomato — COMMENTED** [review]
Rolled back my changes (identical to yours).

> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/2194#-:-Nkb5mM_1QA6HJTXRykT:b757ldo)* status: 13 of 15 files reviewed, all discussions resolved (waiting on @Nateowami)

**Review by Nateowami — APPROVED** [review]
:lgtm:

> Reviewed 3 of 3 files at r10, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/2194#-:-NkbHZH28I1Csqctowxw:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @siltomato)

___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/app.component.spec.ts` line 401 at r10](https://reviewable.io/reviews/sillsdev/web-xforge/2194#-NkbHU6o1a5wPBue5Q1J:-NkbHU6o1a5wPBue5Q1K:b-28lyu4) ([raw file](https://github.com/sillsdev/web-xforge/blob/3fded0932c34530396ac6ec26f1e6d363ee8d1fb/src/SIL.XForge.Scripture/ClientApp/src/app/app.component.spec.ts#L401)):*
> ```XML
>     }
>     when(mockedFeatureFlagService.showNmtDrafting).thenReturn({
>       enabled: false,
> ```

I have a followup for this that is cleaner, but let's merge this for now and deal with that later.

**Pull request merged**
