### PR TITLE
audio: localize Uploading string

### PR DESCRIPTION
**Pull request by marksvc**
This change is [Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/2237)

### CODE REVIEW

**Review by nigel-wells — COMMENTED** [review]
> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/2237)* status: all files reviewed, 1 unresolved discussion (waiting on @marksvc)

___
*[`src/SIL.XForge.Scripture/ClientApp/src/assets/i18n/checking_en.json` line 233 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/2237#-NlW5HQ93ZPsXUqEVtgO:-NlW5HQ93ZPsXUqEVtgP:b-cyxveo) ([raw file](https://github.com/sillsdev/web-xforge/blob/5f6fdf1fca846ccb11f387e03d176f6ed8cfa163/src/SIL.XForge.Scripture/ClientApp/src/assets/i18n/checking_en.json#L233)):*
> ```JSON
>     "upload_failed": "The audio file could not be uploaded. Please try again or use a different file.",
>     "upload_timing_file": "Upload Timing File",
>     "uploading": "Uploading...",
> ```

I'm sure its fine, but would we include the `...` in the translate file or is that part of the template file? Any thoughts @Nateowami ?

**Review by Nateowami — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/2237)* status: all files reviewed, 2 unresolved discussions (waiting on @marksvc and @nigel-wells)

___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/checking/chapter-audio-dialog/chapter-audio-dialog.component.html` line 70 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/2237#-NlW6J0j3bmfzUzITDw3:-NlW6J0j3bmfzUzITDw4:bxvrkvu) ([raw file](https://github.com/sillsdev/web-xforge/blob/5f6fdf1fca846ccb11f387e03d176f6ed8cfa163/src/SIL.XForge.Scripture/ClientApp/src/app/checking/chapter-audio-dialog/chapter-audio-dialog.component.html#L70)):*
> ```HTML
>   <mat-dialog-actions>
>     <div class="uploading" *ngIf="isLoadingAudio">
>       <span>{{ t("chapter_audio_dialog.uploading") }}</span>
> ```

This entire file hasn't been localized quite correctly; the first line should be:
``` html
<ng-container *transloco="let t; read: 'chapter_audio_dialog'">
```

And then it wouldn't be necessary to specify the namespace for every single string.
___
*[`src/SIL.XForge.Scripture/ClientApp/src/assets/i18n/checking_en.json` line 233 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/2237#-NlW5HQ93ZPsXUqEVtgO:-NlW5uY0AEoxX3alJ-cp:bx5a44j) ([raw file](https://github.com/sillsdev/web-xforge/blob/5f6fdf1fca846ccb11f387e03d176f6ed8cfa163/src/SIL.XForge.Scripture/ClientApp/src/assets/i18n/checking_en.json#L233)):*
<details><summary><i>Previously, nigel-wells (Nigel Wells) wrote…</i></summary><blockquote>

I'm sure its fine, but would we include the `...` in the translate file or is that part of the template file? Any thoughts @Nateowami ?
</blockquote></details>

It should be part of the localization, so that if another language doesn't use ellipses, or uses something else instead, it will be possible to use something else.

**Review by Nateowami — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/2237)* status: 1 of 2 files reviewed, 2 unresolved discussions (waiting on @marksvc and @nigel-wells)

___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/checking/chapter-audio-dialog/chapter-audio-dialog.component.html` line 70 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/2237#-NlW6J0j3bmfzUzITDw3:-Nl_9bMg1Gf5eWNdAf2m:b-r19e9r) ([raw file](https://github.com/sillsdev/web-xforge/blob/5f6fdf1fca846ccb11f387e03d176f6ed8cfa163/src/SIL.XForge.Scripture/ClientApp/src/app/checking/chapter-audio-dialog/chapter-audio-dialog.component.html#L70)):*
<details><summary><i>Previously, Nateowami (Nathaniel Paulus) wrote…</i></summary><blockquote>

This entire file hasn't been localized quite correctly; the first line should be:
``` html
<ng-container *transloco="let t; read: 'chapter_audio_dialog'">
```

And then it wouldn't be necessary to specify the namespace for every single string.
</blockquote></details>

@nigel-wells I've gone ahead and made this change.

**Review by nigel-wells — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/2237#-:-NleqLKB5_LwE1YFlaGr:bnfp4nl)* status: all files reviewed, 2 unresolved discussions (waiting on @Nateowami)

___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/checking/chapter-audio-dialog/chapter-audio-dialog.component.html` line 70 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/2237#-NlW6J0j3bmfzUzITDw3:-NleqGVU0lOKil6ewP36:b-ucfknh) ([raw file](https://github.com/sillsdev/web-xforge/blob/5f6fdf1fca846ccb11f387e03d176f6ed8cfa163/src/SIL.XForge.Scripture/ClientApp/src/app/checking/chapter-audio-dialog/chapter-audio-dialog.component.html#L70)):*
<details><summary><i>Previously, Nateowami (Nathaniel Paulus) wrote…</i></summary><blockquote>

@nigel-wells I've gone ahead and made this change.
</blockquote></details>

Thanks!
___
*[`src/SIL.XForge.Scripture/ClientApp/src/assets/i18n/checking_en.json` line 233 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/2237#-NlW5HQ93ZPsXUqEVtgO:-NleqK1gBQII7awpuGAe:b32w1t) ([raw file](https://github.com/sillsdev/web-xforge/blob/5f6fdf1fca846ccb11f387e03d176f6ed8cfa163/src/SIL.XForge.Scripture/ClientApp/src/assets/i18n/checking_en.json#L233)):*
<details><summary><i>Previously, Nateowami (Nathaniel Paulus) wrote…</i></summary><blockquote>

It should be part of the localization, so that if another language doesn't use ellipses, or uses something else instead, it will be possible to use something else.
</blockquote></details>

Ok

**Pull request merged**
