### PR TITLE
Clone and Sync progress indeterminate until non-zero

### PR DESCRIPTION
**Pull request by irahopkinson**
This has bothered me for a while particularly on the clone (Connect Project) where the progress stays on 0% for about a minute.

---
This change is [Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/860)

### CODE REVIEW

**Review by RaymondLuong3 — APPROVED** [review]
Just the other day I thought my internet connection was bad while downloading an android app because the progress was 0% for almost a minute. I approve.

> Reviewed 5 of 5 files at r1.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/860#-:-MLDtzDj5SwQ_dkJJkXP:bhmj13t)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by Nateowami — APPROVED** [review]
:lgtm: Just one note.

> Reviewed 5 of 5 files at r1.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/860#-:-MLELHZ485R-UQYvjb_t:bwr1dul)* status: :shipit: complete! all files reviewed, all discussions resolved

___
*[src/SIL.XForge.Scripture/ClientApp/src/app/connect-project/connect-project.component.ts, line 69 at r2](https://reviewable.io/reviews/sillsdev/web-xforge/860#-MLEHGTm79zrfNNaXECv:-MLEHGTm79zrfNNaXECw:bmn7rvq) ([raw file](https://github.com/sillsdev/web-xforge/blob/ff15ec72bb0b6980f8cd3a2fb3f77ee8e2aff071/src/SIL.XForge.Scripture/ClientApp/src/app/connect-project/connect-project.component.ts#L69)):*
> ```XML
> 
>   get isProgressDeterminate(): boolean {
>     return this.connectProgress != null && this.connectProgress > 0;
> ```

Technically `this.connectProgress != null` is redundant, as `null` and `undefined` are not greater than 0. I suppose an argument could be made that it's useful to be more specific, even when it's redundant.

Same in the sync component.

**Comment by irahopkinson** [comment]
___
*[src/SIL.XForge.Scripture/ClientApp/src/app/connect-project/connect-project.component.ts, line 69 at r2](https://reviewable.io/reviews/sillsdev/web-xforge/860#-MLEHGTm79zrfNNaXECv:-MLMeIHaBxDlHYUaZ6_2:b-y5wx6b) ([raw file](https://github.com/sillsdev/web-xforge/blob/ff15ec72bb0b6980f8cd3a2fb3f77ee8e2aff071/src/SIL.XForge.Scripture/ClientApp/src/app/connect-project/connect-project.component.ts#L69)):*
<details><summary><i>Previously, Nateowami (Nathaniel Paulus) wrote…</i></summary><blockquote>

Technically `this.connectProgress != null` is redundant, as `null` and `undefined` are not greater than 0. I suppose an argument could be made that it's useful to be more specific, even when it's redundant.

Same in the sync component.
</blockquote></details>

BTW, I forgot to say that I left this explicit because it should be more understandable what is being checked and I'm pretty sure the TS compiler (and if not that then the optimizer) will just simplify it to what you suggested in JS anyway.

**Review by Nateowami — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/860)* status: :shipit: complete! all files reviewed, all discussions resolved

___
*[src/SIL.XForge.Scripture/ClientApp/src/app/connect-project/connect-project.component.ts, line 69 at r2](https://reviewable.io/reviews/sillsdev/web-xforge/860#-MLEHGTm79zrfNNaXECv:-MLOELe1BJnOVuXU_lyp:b-9a1g77) ([raw file](https://github.com/sillsdev/web-xforge/blob/ff15ec72bb0b6980f8cd3a2fb3f77ee8e2aff071/src/SIL.XForge.Scripture/ClientApp/src/app/connect-project/connect-project.component.ts#L69)):*
<details><summary><i>Previously, irahopkinson (Ira Hopkinson) wrote…</i></summary><blockquote>

BTW, I forgot to say that I left this explicit because it should be more understandable what is being checked and I'm pretty sure the TS compiler (and if not that then the optimizer) will just simplify it to what you suggested in JS anyway.
</blockquote></details>

I ran `ng build --configuration=production` and opened `dist/main-es2015.a59ebec3801afcd776d0.js`, and found:
```
null!=this.connectProgress&&this.connectProgress>0
```
So it looks like it doesn't actually get optimized out.

Not that that's actually that significant, and I can certainly see why you would write it more redundantly. I just thought it was interesting to note.

**Pull request merged**
