### PR TITLE
SF-1832 SF-1845 Display Training Progress on the Translate Overview page

### PR DESCRIPTION
**Pull request by pmachapman**
Currently when retraining a model, the Translate Overview page does not display translation progress beyond a progress bar. The lack of detailed feedback can cause the user to think that training is stuck, or if it has failed, no real feedback of this failure is communicated to the user.

To address this, this Pull Request:
 * Refactors the Training Progress popup to be a reusable component (9db65522211a3d59a38dd36ac9f751881b6319c3)
 * Adds the Training Progress popup to the Translate Overview page (b012cfb0e43154fb6f40fc9d7f17092a2f58276e)
 * Fixes flickering on the Training Progress spinner as training progresses (b012cfb0e43154fb6f40fc9d7f17092a2f58276e)
 * Updates machine.js to 2.3.0
 * Implements the DTO models removed in machine.js 2.3.0
 * Implements the `RemoteTranslationEngine` removed from machine.js 2.3.0
 * Adds support for `RemoteTranslationEngine` instances to be shared across components

- - -
This change is [Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1662)

### CODE REVIEW

**Comment by Nateowami** [comment]
When I train a project I see the progress, and it's not indeterminate. Does this only happen when the feature flag is turned on?

**Comment by pmachapman** [comment]
> When I train a project I see the progress, and it's not indeterminate. Does this only happen when the feature flag is turned on?

Sorry I realise that was a fault of my process during testing of the Machine API changes - it starts indeterminate, then proceeds as normal. My debugger use and rapid clicking to the Scripture screen caused me to think it was indeterminate longer than it truly is. I have updated the description.

**Review by nigel-wells — CHANGES_REQUESTED** [review]
Nice to see this feedback on the overview page. My main comment below is to see if you can move all the logic into the new component rather than having similar logic in each component that wants to display this new one.

Also, I think the box that appears could do with a border as the white blends in too much with the other white which causes some unwanted effects if it is on top of something else:


> Reviewed 11 of 12 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1662#-:-NLc91411QA1CMKWX-s5:b-49l8sv)* status: 11 of 12 files reviewed, 5 unresolved discussions (waiting on @pmachapman)

___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.html` line 139 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/1662#-NLc8lPhAug9FiVWU8E4:-NLc8lPhAug9FiVWU8E5:blxugkr) ([raw file](https://github.com/sillsdev/web-xforge/blob/d96971c45b73a6489492781989e8489b99f4ab57/src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.html#L139)):*
> ```HTML
>     [(showTrainingProgress)]="showTrainingProgress"
>     (trainingProgressClosed)="trainingProgressClosed = $event"
>   ></app-training-progress>
> ```

See other comment - hoping we can just pass the project ID and the component will take care of the messages and other logic.



_Suggestion:_
```HTML
  <app-training-progress
    [trainingPercentage]="trainingPercentage"
    [trainingMessage]="trainingMessage"
    [(showTrainingProgress)]="showTrainingProgress"
    (trainingProgressClosed)="trainingProgressClosed = $event"










  ></app-training-progress>
```
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/translate/training-progress/training-progress.component.html` line 1 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/1662#-NLc7Hw--nQJM-WFtxmy:-NLc7Hw--nQJM-WFtxmz:b-8vj6rm) ([raw file](https://github.com/sillsdev/web-xforge/blob/d96971c45b73a6489492781989e8489b99f4ab57/src/SIL.XForge.Scripture/ClientApp/src/app/translate/training-progress/training-progress.component.html#L1)):*
> ```HTML
> <ng-container *transloco="let t; read: 'editor'">
> ```

It would be good to move/create translations under its own section in `non_checking_en.json` rather than piggybacking off another components translations.
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/translate/training-progress/training-progress.component.scss` line 4 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/1662#-NLc6V2X7xdJ172qd9K-:-NLc6V2X7xdJ172qd9K0:b-ru2v0p) ([raw file](https://github.com/sillsdev/web-xforge/blob/d96971c45b73a6489492781989e8489b99f4ab57/src/SIL.XForge.Scripture/ClientApp/src/app/translate/training-progress/training-progress.component.scss#L4)):*
> ```SCSS
> 
> @import 'src/variables';
> @import 'bootstrap/scss/mixins/breakpoints';
> ```

Doesn't look like you're using any breakpoint mixins
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/translate/translate-overview/translate-overview.component.html` line 85 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/1662#-NLc8RrcBiJkxfAdhOrB:-NLc8RrcBiJkxfAdhOrC:blxugkr) ([raw file](https://github.com/sillsdev/web-xforge/blob/d96971c45b73a6489492781989e8489b99f4ab57/src/SIL.XForge.Scripture/ClientApp/src/app/translate/translate-overview/translate-overview.component.html#L85)):*
> ```HTML
>     [(showTrainingProgress)]="showTrainingProgress"
>     (trainingProgressClosed)="trainingProgressClosed = $event"
>   ></app-training-progress>
> ```

See other comment - hoping we can just pass the project ID and the component will take care of the messages and other logic.



_Code quote:_
```HTML
  <app-training-progress
    [trainingPercentage]="trainingPercentage"
    [trainingMessage]="trainingMessage"
    [(showTrainingProgress)]="showTrainingProgress"
    (trainingProgressClosed)="trainingProgressClosed = $event"
  ></app-training-progress>
```
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/translate/translate-overview/translate-overview.component.ts` line 260 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/1662#-NLc7t689lbczPgVdNCx:-NLc7t689lbczPgVdNCy:b-j7oh5y) ([raw file](https://github.com/sillsdev/web-xforge/blob/d96971c45b73a6489492781989e8489b99f4ab57/src/SIL.XForge.Scripture/ClientApp/src/app/translate/translate-overview/translate-overview.component.ts#L260)):*
> ```XML
>         this.trainingMessage = progress.message;
>         this.isTraining = true;
>       });
> ```

Can all of this, as well as the similar lines in the editor component, be moved into the new translate progress component. This will make it easier to manage going forward and will make it easier to implement as  you'd only need one @Input for the project ID?



_Code quote:_
```XML
    this.trainingSub = this.translationEngine
      .listenForTrainingStatus()
      .pipe(
        tap({
          error: () => {
            // error while listening
            this.isTraining = false;
            this.showTrainingProgress = false;
            this.trainingCompletedTimeout = undefined;
            this.trainingProgressClosed = false;
          },
          complete: () => {
            // training completed successfully
            this.isTraining = false;
            if (this.trainingProgressClosed) {
              this.noticeService.show(translate('editor.training_completed_successfully'));
              this.trainingProgressClosed = false;
            } else {
              this.trainingMessage = translate('editor.completed_successfully');
              this.trainingCompletedTimeout = setTimeout(() => {
                this.showTrainingProgress = false;
                this.trainingCompletedTimeout = undefined;
              }, 5000);
            }

            this.updateEngineStats();
          }
        }),
        repeat(),
        filter(progress => progress.percentCompleted > 0),
        retryWhen(errors => errors.pipe(delayWhen(() => timer(30000))))
      )
      .subscribe(progress => {
        if (!this.trainingProgressClosed) {
          this.showTrainingProgress = true;
        }
        if (this.trainingCompletedTimeout != null) {
          clearTimeout(this.trainingCompletedTimeout);
          this.trainingCompletedTimeout = undefined;
        }
        this.trainingPercentage = Math.round(progress.percentCompleted * 100);
        // ToDo: internationalize message
        this.trainingMessage = progress.message;
        this.isTraining = true;
      });
```

**Review by pmachapman — COMMENTED** [review]
I have added a border, but I am not sure if it looks better? I don't mind whether it is with or without a border.


> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1662#-:-NLs6nQ2C3IFMoQFF4qp:bmgnu8m)* status: 3 of 44 files reviewed, 5 unresolved discussions (waiting on @input and @nigel-wells)

___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.html` line 139 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/1662#-NLc8lPhAug9FiVWU8E4:-NLwoCHoA-PDncAE7Aw9:b-6d0i0z) ([raw file](https://github.com/sillsdev/web-xforge/blob/d96971c45b73a6489492781989e8489b99f4ab57/src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.html#L139)):*
<details><summary><i>Previously, nigel-wells (Nigel Wells) wrote…</i></summary><blockquote>

See other comment - hoping we can just pass the project ID and the component will take care of the messages and other logic.
</blockquote></details>

The component syntax has been simplified to just one attribute - the project id.



_Code quote:_
```HTML
<app-training-progress [projectId]="projectId"></app-training-progress>
```
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/translate/training-progress/training-progress.component.html` line 1 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/1662#-NLc7Hw--nQJM-WFtxmy:-NLsGkfJ75SuHbHYJpAP:bkryv0t) ([raw file](https://github.com/sillsdev/web-xforge/blob/d96971c45b73a6489492781989e8489b99f4ab57/src/SIL.XForge.Scripture/ClientApp/src/app/translate/training-progress/training-progress.component.html#L1)):*
<details><summary><i>Previously, nigel-wells (Nigel Wells) wrote…</i></summary><blockquote>

It would be good to move/create translations under its own section in `non_checking_en.json` rather than piggybacking off another components translations.
</blockquote></details>

Moved to a new `"training_progress"` section.
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/translate/training-progress/training-progress.component.scss` line 4 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/1662#-NLc6V2X7xdJ172qd9K-:-NLsHBWpERXU2UQDKSYF:b-233jw0) ([raw file](https://github.com/sillsdev/web-xforge/blob/d96971c45b73a6489492781989e8489b99f4ab57/src/SIL.XForge.Scripture/ClientApp/src/app/translate/training-progress/training-progress.component.scss#L4)):*
<details><summary><i>Previously, nigel-wells (Nigel Wells) wrote…</i></summary><blockquote>

Doesn't look like you're using any breakpoint mixins
</blockquote></details>

Removed - thank you!
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/translate/translate-overview/translate-overview.component.html` line 85 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/1662#-NLc8RrcBiJkxfAdhOrB:-NLwoJ6eBaZlc43rvb4s:b-896fix) ([raw file](https://github.com/sillsdev/web-xforge/blob/d96971c45b73a6489492781989e8489b99f4ab57/src/SIL.XForge.Scripture/ClientApp/src/app/translate/translate-overview/translate-overview.component.html#L85)):*
<details><summary><i>Previously, nigel-wells (Nigel Wells) wrote…</i></summary><blockquote>

See other comment - hoping we can just pass the project ID and the component will take care of the messages and other logic.
</blockquote></details>

Done.
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/translate/translate-overview/translate-overview.component.ts` line 260 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/1662#-NLc7t689lbczPgVdNCx:-NLwoL-Z-2BSPntYahep:b-6ncwvl) ([raw file](https://github.com/sillsdev/web-xforge/blob/d96971c45b73a6489492781989e8489b99f4ab57/src/SIL.XForge.Scripture/ClientApp/src/app/translate/translate-overview/translate-overview.component.ts#L260)):*
<details><summary><i>Previously, nigel-wells (Nigel Wells) wrote…</i></summary><blockquote>

Can all of this, as well as the similar lines in the editor component, be moved into the new translate progress component. This will make it easier to manage going forward and will make it easier to implement as  you'd only need one @Input for the project ID?
</blockquote></details>

I have reworked the component to do this. This required the update to machine.js that was in PR #1663, so I have rebased this PR on top of that, and closed that PR.

Unfortunately, that does mean there is a bit more for you to review now.

**Review by Nateowami — COMMENTED** [review]
I think adding the `mat-card` class may accomplish the same thing while giving it an appearance that is more in line with the rest of the rest of our Material theme. You might even be able to make it a `mat-card`. See https://material.angular.io/components/card/overview


> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1662#-:-NM1RiBhAOEQ99dOa3Wq:b-u1z5ah)* status: 3 of 44 files reviewed, 5 unresolved discussions (waiting on @input and @nigel-wells)

**Review by pmachapman — COMMENTED** [review]
Thank you - that looks much, much better. Refactoring as a `mat-card` did not work so well (the padding caused layout problems), so I had added the class as suggested.

> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1662#-:-NM1XPnZ-TEqO3VPEVdI:b-xq48kb)* status: 3 of 44 files reviewed, 5 unresolved discussions (waiting on @input and @nigel-wells)

**Review by nigel-wells — CHANGES_REQUESTED** [review]
Happy with how that looks using the mat-card styles.
@pmachapman which are the main parts I need to review for the machine API code you've migrated across? Your other PR just says you've ported across what was removed from the machine.js library so I assume I don't need to review anything that was already working fine before?

> Reviewed 16 of 24 files at r2, 12 of 16 files at r3, 8 of 9 files at r4, 2 of 2 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1662#-:-NMQohyKBHUkybqL0ZXD:bi8jo3r)* status: 41 of 44 files reviewed, 4 unresolved discussions (waiting on @pmachapman)

___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.html` line 139 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/1662#-NLc8lPhAug9FiVWU8E4:-NMQXTu7Bnvz_gr7eAyV:basd7g2) ([raw file](https://github.com/sillsdev/web-xforge/blob/d96971c45b73a6489492781989e8489b99f4ab57/src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.html#L139)):*
<details><summary><i>Previously, pmachapman (Peter Chapman) wrote…</i></summary><blockquote>

The component syntax has been simplified to just one attribute - the project id.
</blockquote></details>

Looks good - just what I was hoping for :)
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.ts` line 107 at r5](https://reviewable.io/reviews/sillsdev/web-xforge/1662#-NMQg3xo4ifu0Fkt0Zgf:-NMQg3xo4ifu0Fkt0Zgg:b85yo74) ([raw file](https://github.com/sillsdev/web-xforge/blob/0a52c12cfe4179b743f1a595afb9394be859365c/src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.ts#L107)):*
> ```XML
>   isProjectAdmin: boolean = false;
>   metricsSession?: TranslateMetricsSession;
>   projectId: string = '';
> ```

Can this be changed to a getter and the id then taken from `this.projectDoc.id`
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/translate/training-progress/training-progress.component.ts` line 41 at r5](https://reviewable.io/reviews/sillsdev/web-xforge/1662#-NMQhWAJ6cvFGItCgvSf:-NMQhWAJ6cvFGItCgvSg:b9dv759) ([raw file](https://github.com/sillsdev/web-xforge/blob/0a52c12cfe4179b743f1a595afb9394be859365c/src/SIL.XForge.Scripture/ClientApp/src/app/translate/training-progress/training-progress.component.ts#L41)):*
> ```XML
> 
>   ngOnInit(): void {
>     this.subscribe(this.activatedRoute.params.pipe(map(params => params['projectId'])), async projectId => {
> ```

Is this needed as you have already passed in the project ID through the @Input
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/translate/training-progress/training-progress.component.ts` line 53 at r5](https://reviewable.io/reviews/sillsdev/web-xforge/1662#-NMQiCiJ69Yt9NW5bXjg:-NMQiCiJ69Yt9NW5bXjh:bpo885c) ([raw file](https://github.com/sillsdev/web-xforge/blob/0a52c12cfe4179b743f1a595afb9394be859365c/src/SIL.XForge.Scripture/ClientApp/src/app/translate/training-progress/training-progress.component.ts#L53)):*
> ```XML
>         this.projectDataChangesSub.unsubscribe();
>       }
>       this.projectDataChangesSub = this.projectDoc.remoteChanges$.subscribe(() => {
> ```

If there is indeed no reason for getting the project ID from the `ActiveRoute` then you could extend the `SubscriptionDisposable` class which will then take care of disposing of the subscribe for you.
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/translate/translate-overview/translate-overview.component.ts` line 260 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/1662#-NLc7t689lbczPgVdNCx:-NMQjuab7Qr4rwsZJb-_:b-vb1x9r) ([raw file](https://github.com/sillsdev/web-xforge/blob/d96971c45b73a6489492781989e8489b99f4ab57/src/SIL.XForge.Scripture/ClientApp/src/app/translate/translate-overview/translate-overview.component.ts#L260)):*
<details><summary><i>Previously, pmachapman (Peter Chapman) wrote…</i></summary><blockquote>

I have reworked the component to do this. This required the update to machine.js that was in PR #1663, so I have rebased this PR on top of that, and closed that PR.

Unfortunately, that does mean there is a bit more for you to review now.
</blockquote></details>

All good - nice to see you were able to make this work.
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/translate/translate-overview/translate-overview.component.ts` line 52 at r5](https://reviewable.io/reviews/sillsdev/web-xforge/1662#-NMQjpNE4Ym1MIgK4QB-:-NMQjpNF1uIisP6aLmm6:b-uoekkj) ([raw file](https://github.com/sillsdev/web-xforge/blob/0a52c12cfe4179b743f1a595afb9394be859365c/src/SIL.XForge.Scripture/ClientApp/src/app/translate/translate-overview/translate-overview.component.ts#L52)):*
> ```XML
>   overallProgress = new Progress();
>   trainingPercentage: number = 0;
>   projectId: string = '';
> ```

As per other comment, change into a getter.

**Review by pmachapman — COMMENTED** [review]
The only changes from machine.js were merging [WebApiClient](https://github.com/sillsdev/machine.js/blob/6f328ec438af9a536398d65faf784933bf6fd316/src/web-api/web-api-client.ts) and [RemoteTranslationEngine](https://github.com/sillsdev/machine.js/blob/6f328ec438af9a536398d65faf784933bf6fd316/src/translation/remote-translation-engine.ts) into the new, 2.3 compatible [RemoteTranslationEngine](https://github.com/sillsdev/web-xforge/blob/0a52c12cfe4179b743f1a595afb9394be859365c/src/SIL.XForge.Scripture/ClientApp/src/app/machine-api/remote-translation-engine.spec.ts), 
And in remote-translation-engine.ts changing:
```ts
  listenForTrainingStatus(projectId: string): Observable<ProgressStatus> {
    return this.getEngine(projectId).pipe(mergeMap((e) => this.pollBuildProgress('engine', e.id, 0)));
  }
```
to:
```ts
  listenForTrainingStatus(): Observable<ProgressStatus> {
    if (this.trainingStatus$ == null) {
      this.trainingStatus$ = this.getEngine(this.projectId).pipe(
        mergeMap(e => this.pollBuildProgress('engine', e.id, 0)),
        share()
      );
    }
    return this.trainingStatus$;
  }
```
Ensuring my use of `share()` and the observable `private trainingStatus$?: Observable<ProgressStatus>;` is done correctly would be helpful, as my knowledge of TypeScript is not as good as my C# knowledge, as well as perhaps making sure I amde no obvious mistakes when I carried across all of the functionality from [machine.js 2.2.3](https://github.com/sillsdev/machine.js/commit/6f328ec438af9a536398d65faf784933bf6fd316) (see specifically [web-api-client.ts](https://github.com/sillsdev/machine.js/blob/6f328ec438af9a536398d65faf784933bf6fd316/src/web-api/web-api-client.ts) and [remote-translation-engine.ts](https://github.com/sillsdev/machine.js/blob/6f328ec438af9a536398d65faf784933bf6fd316/src/translation/remote-translation-engine.ts))

> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1662#-:-NMR-c1t4Bzb1vN8oFTK:b-4sy8qu)* status: 41 of 44 files reviewed, 4 unresolved discussions (waiting on @input and @nigel-wells)

___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.ts` line 107 at r5](https://reviewable.io/reviews/sillsdev/web-xforge/1662#-NMQg3xo4ifu0Fkt0Zgf:-NMR3_mhDHkfVBwLam67:b-p28vw7) ([raw file](https://github.com/sillsdev/web-xforge/blob/0a52c12cfe4179b743f1a595afb9394be859365c/src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.ts#L107)):*
<details><summary><i>Previously, nigel-wells (Nigel Wells) wrote…</i></summary><blockquote>

Can this be changed to a getter and the id then taken from `this.projectDoc.id`
</blockquote></details>

Excellent idea - thank you. Fixed.

Note: I needed to update `TrainingProgressComponent` to `subscribe()` to the projectId in `ngOnInit()` for this to work.
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/translate/training-progress/training-progress.component.ts` line 41 at r5](https://reviewable.io/reviews/sillsdev/web-xforge/1662#-NMQhWAJ6cvFGItCgvSf:-NMR6Ea49J2v3wirEivm:b-mlve77) ([raw file](https://github.com/sillsdev/web-xforge/blob/0a52c12cfe4179b743f1a595afb9394be859365c/src/SIL.XForge.Scripture/ClientApp/src/app/translate/training-progress/training-progress.component.ts#L41)):*
<details><summary><i>Previously, nigel-wells (Nigel Wells) wrote…</i></summary><blockquote>

Is this needed as you have already passed in the project ID through the @Input
</blockquote></details>

No, it isn't. Removed - thanks!
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/translate/training-progress/training-progress.component.ts` line 53 at r5](https://reviewable.io/reviews/sillsdev/web-xforge/1662#-NMQiCiJ69Yt9NW5bXjg:-NMRG03k0fAnc0V439Xh:b-9880hq) ([raw file](https://github.com/sillsdev/web-xforge/blob/0a52c12cfe4179b743f1a595afb9394be859365c/src/SIL.XForge.Scripture/ClientApp/src/app/translate/training-progress/training-progress.component.ts#L53)):*
<details><summary><i>Previously, nigel-wells (Nigel Wells) wrote…</i></summary><blockquote>

If there is indeed no reason for getting the project ID from the `ActiveRoute` then you could extend the `SubscriptionDisposable` class which will then take care of disposing of the subscribe for you.
</blockquote></details>

When the `projectDoc` variable changes, when the projectId is set I need to unsubscribe before subscribing to the new object, unless I misunderstand how this works?
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/translate/translate-overview/translate-overview.component.ts` line 52 at r5](https://reviewable.io/reviews/sillsdev/web-xforge/1662#-NMQjpNE4Ym1MIgK4QB-:-NMRArFS0LZZ-80kpG8B:b-896fix) ([raw file](https://github.com/sillsdev/web-xforge/blob/0a52c12cfe4179b743f1a595afb9394be859365c/src/SIL.XForge.Scripture/ClientApp/src/app/translate/translate-overview/translate-overview.component.ts#L52)):*
<details><summary><i>Previously, nigel-wells (Nigel Wells) wrote…</i></summary><blockquote>

As per other comment, change into a getter.
</blockquote></details>

Done.

**Review by nigel-wells — CHANGES_REQUESTED** [review]
I've not specifically used `share()` before from RXJS but it does sound like what you'd want. I see we've only used it in one other place on the front end and that is in `translation-engine.service.ts`

> Reviewed 2 of 24 files at r2, 1 of 9 files at r4, 4 of 5 files at r6, 3 of 3 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1662#-:-NM_p8fPC30r59aE-lL8:b-rzxagk)* status: all files reviewed, 3 unresolved discussions (waiting on @pmachapman)

___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/translate/training-progress/training-progress.component.ts` line 53 at r5](https://reviewable.io/reviews/sillsdev/web-xforge/1662#-NMQiCiJ69Yt9NW5bXjg:-NM_q2YCEV_eymR7CUrT:b-9qzu74) ([raw file](https://github.com/sillsdev/web-xforge/blob/0a52c12cfe4179b743f1a595afb9394be859365c/src/SIL.XForge.Scripture/ClientApp/src/app/translate/training-progress/training-progress.component.ts#L53)):*
<details><summary><i>Previously, pmachapman (Peter Chapman) wrote…</i></summary><blockquote>

When the `projectDoc` variable changes, when the projectId is set I need to unsubscribe before subscribing to the new object, unless I misunderstand how this works?
</blockquote></details>

Yes, you'll need to unsubscribe from what is there. Do you need to subscribe to `projectId$` - couldn't you just see if `projectId` is != `this.projectDoc?.id`? The end result is all the same but hopefully with les subscriptions going on. 

Initially I was thinking that you wouldn't really have to account for `projectId` changing at all after the first init but I see the parent components are setup in a way that it may change if the route is changed so what you have for subscribing and unsubscribing is fine.
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/translate/training-progress/training-progress.component.spec.ts` line 36 at r7](https://reviewable.io/reviews/sillsdev/web-xforge/1662#-NM_wDCJ800jT86PbaJ0:-NM_wDCJ800jT86PbaJ1:benfur7) ([raw file](https://github.com/sillsdev/web-xforge/blob/da7ce8fe56e1046b7ab7b7efbc998deaad6e594b/src/SIL.XForge.Scripture/ClientApp/src/app/translate/training-progress/training-progress.component.spec.ts#L36)):*
> ```XML
> const mockedI18nService = mock(I18nService);
> 
> describe('TrainingProgressComponent', () => {
> ```

Can you add a test to assert the component closes after training is completed
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/translate/training-progress/training-progress.component.spec.ts` line 100 at r7](https://reviewable.io/reviews/sillsdev/web-xforge/1662#-NM_vIwP8APYfOxBgQCh:-NM_vIwP8APYfOxBgQCi:b-g7u5e1) ([raw file](https://github.com/sillsdev/web-xforge/blob/da7ce8fe56e1046b7ab7b7efbc998deaad6e594b/src/SIL.XForge.Scripture/ClientApp/src/app/translate/training-progress/training-progress.component.spec.ts#L100)):*
> ```XML
>   constructor() {
>     when(mockedPwaService.onlineStatus$).thenReturn(of(true));
>     when(mockedActivatedRoute.params).thenReturn(of({ projectId: 'project01' }));
> ```

This can be removed now can't it?

**Review by pmachapman — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1662)* status: 44 of 45 files reviewed, 3 unresolved discussions (waiting on @nigel-wells)

___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/translate/training-progress/training-progress.component.ts` line 53 at r5](https://reviewable.io/reviews/sillsdev/web-xforge/1662#-NMQiCiJ69Yt9NW5bXjg:-NMaF5wSEyH2Rf5e5SD3:b-t4p9sc) ([raw file](https://github.com/sillsdev/web-xforge/blob/0a52c12cfe4179b743f1a595afb9394be859365c/src/SIL.XForge.Scripture/ClientApp/src/app/translate/training-progress/training-progress.component.ts#L53)):*
<details><summary><i>Previously, nigel-wells (Nigel Wells) wrote…</i></summary><blockquote>

Yes, you'll need to unsubscribe from what is there. Do you need to subscribe to `projectId$` - couldn't you just see if `projectId` is != `this.projectDoc?.id`? The end result is all the same but hopefully with les subscriptions going on. 

Initially I was thinking that you wouldn't really have to account for `projectId` changing at all after the first init but I see the parent components are setup in a way that it may change if the route is changed so what you have for subscribing and unsubscribing is fine.
</blockquote></details>

Yes, I need to subscribe to projectId to see if the project changes, and the projectDoc (set when projectId changes), to ensure if translationSuggestionsEnabled changes, that is reflected in the component.
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/translate/training-progress/training-progress.component.spec.ts` line 36 at r7](https://reviewable.io/reviews/sillsdev/web-xforge/1662#-NM_wDCJ800jT86PbaJ0:-NMaFLW68csmRZiSQ1BF:b6ukza6) ([raw file](https://github.com/sillsdev/web-xforge/blob/da7ce8fe56e1046b7ab7b7efbc998deaad6e594b/src/SIL.XForge.Scripture/ClientApp/src/app/translate/training-progress/training-progress.component.spec.ts#L36)):*
<details><summary><i>Previously, nigel-wells (Nigel Wells) wrote…</i></summary><blockquote>

Can you add a test to assert the component closes after training is completed
</blockquote></details>

Great idea! Done.
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/translate/training-progress/training-progress.component.spec.ts` line 100 at r7](https://reviewable.io/reviews/sillsdev/web-xforge/1662#-NM_vIwP8APYfOxBgQCh:-NMaJQKZ2ZpOzNlTKhsj:b1v5mzv) ([raw file](https://github.com/sillsdev/web-xforge/blob/da7ce8fe56e1046b7ab7b7efbc998deaad6e594b/src/SIL.XForge.Scripture/ClientApp/src/app/translate/training-progress/training-progress.component.spec.ts#L100)):*
<details><summary><i>Previously, nigel-wells (Nigel Wells) wrote…</i></summary><blockquote>

This can be removed now can't it?
</blockquote></details>

Yes - thanks! I have stripped out as much as I can.

**Review by nigel-wells — APPROVED** [review]
> Reviewed 1 of 1 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1662)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @pmachapman)

___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/translate/training-progress/training-progress.component.ts` line 53 at r5](https://reviewable.io/reviews/sillsdev/web-xforge/1662#-NMQiCiJ69Yt9NW5bXjg:-NMaWxdr4sBAQUIaUZzt:b-p8c5ja) ([raw file](https://github.com/sillsdev/web-xforge/blob/0a52c12cfe4179b743f1a595afb9394be859365c/src/SIL.XForge.Scripture/ClientApp/src/app/translate/training-progress/training-progress.component.ts#L53)):*
<details><summary><i>Previously, pmachapman (Peter Chapman) wrote…</i></summary><blockquote>

Yes, I need to subscribe to projectId to see if the project changes, and the projectDoc (set when projectId changes), to ensure if translationSuggestionsEnabled changes, that is reflected in the component.
</blockquote></details>

But you'd know the project changed because `projectId !== this.projectDoc?.id`? I'll resolve this and let you make the call - the end result is the same :)
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/translate/training-progress/training-progress.component.spec.ts` line 100 at r7](https://reviewable.io/reviews/sillsdev/web-xforge/1662#-NM_vIwP8APYfOxBgQCh:-NMaWKwK2VN8BE0wMtTI:b-pknp17) ([raw file](https://github.com/sillsdev/web-xforge/blob/da7ce8fe56e1046b7ab7b7efbc998deaad6e594b/src/SIL.XForge.Scripture/ClientApp/src/app/translate/training-progress/training-progress.component.spec.ts#L100)):*
<details><summary><i>Previously, pmachapman (Peter Chapman) wrote…</i></summary><blockquote>

Yes - thanks! I have stripped out as much as I can.
</blockquote></details>

Ha, well done, you got rid of heaps!

**Pull request merged**
