### PR TITLE
SF-1798 Switch off drag and drop

### PR DESCRIPTION
**Pull request by marksvc**
Text can be dragged in the quill editor to move it. Doing this without
problems required handling a number of cases around embedded elements,
formatting, and non-verse-related areas, and has continued to require
fixing special cases. Drag-and-drop may also not be an important
activity for users to be doing while drafting Scripture one verse at a
time in the editor.

This commit removes the drag-and-drop functionality from the quill
editor, and continues preventing the browser from performing its own
drag-and-drop.

editor.component.spec.ts tests some functionality of 'update note
thread anchors when multiple edits within a verse', where undoing a
drag-and-drop, and so handling multiple ops at a time, works
correctly. I chose to leave this as is.

commit-id:02cdbe41

- - -
This change is [Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1724)

Video showing new behaviour:

[no-drag.webm](https://user-images.githubusercontent.com/7265309/222220549-87a1895b-0ff7-4d0e-8ab2-3a9edd12792b.webm)

### CODE REVIEW

**Review by RaymondLuong3 — CHANGES_REQUESTED** [review]
It is too bad to see all this hard work go, but I think it is for the better. Thanks for your work, just a couple minor comments.

> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1724#-:-NPcoHcgECnMMH4AMqqJ:b81x96l)* status: all files reviewed, 2 unresolved discussions (waiting on @marksvc)

___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/shared/text/drag-and-drop.ts` line 3 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/1724#-NPcljdc1MmHZpj7ihkX:-NPcljddE4SRAy9kGXL4:b-gajv1w) ([raw file](https://github.com/sillsdev/web-xforge/blob/31969ae4a3ebf160803df740acad02f00dd93a5c/src/SIL.XForge.Scripture/ClientApp/src/app/shared/text/drag-and-drop.ts#L3)):*
> ```XML
> import Quill from 'quill';
> 
> /** Drag-and-drop module for Quill. Unit test(s) can be found in text.component.spec.ts.*/
> ```

This might need to be more descriptive since now it acts more as drag and drop prevention



_Code quote:_
```XML
Drag-and-drop module for Quill
```
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/shared/text/text.component.spec.ts` line 482 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/1724#-NPcnQIp0XQf9qCZiLpd:-NPcnQIp0XQf9qCZiLpe:b-m6ftyb) ([raw file](https://github.com/sillsdev/web-xforge/blob/31969ae4a3ebf160803df740acad02f00dd93a5c/src/SIL.XForge.Scripture/ClientApp/src/app/shared/text/text.component.spec.ts#L482)):*
> ```XML
> 
>   describe('drag-and-drop', () => {
>     it('inserts externally introduced data in the right place, without formatting or line breaks', fakeAsync(() => {
> ```

This could use some updating



_Code quote:_
```XML
inserts externally introduced data in the right place, 
```

**Review by marksvc — COMMENTED** [review]
Thank you.

> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1724#-:-NPwnnPPBgzFOiyFRc6V:b-9755fa)* status: all files reviewed, 2 unresolved discussions (waiting on @RaymondLuong3)

___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/shared/text/drag-and-drop.ts` line 3 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/1724#-NPcljdc1MmHZpj7ihkX:-NPwnMiM26L1ZqxOgZ2H:b-896fix) ([raw file](https://github.com/sillsdev/web-xforge/blob/31969ae4a3ebf160803df740acad02f00dd93a5c/src/SIL.XForge.Scripture/ClientApp/src/app/shared/text/drag-and-drop.ts#L3)):*
<details><summary><i>Previously, RaymondLuong3 (Raymond Luong) wrote…</i></summary><blockquote>

This might need to be more descriptive since now it acts more as drag and drop prevention
</blockquote></details>

Done.
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/shared/text/text.component.spec.ts` line 482 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/1724#-NPcnQIp0XQf9qCZiLpd:-NPwngku7Ws0NcmHmvzT:by9bmic) ([raw file](https://github.com/sillsdev/web-xforge/blob/31969ae4a3ebf160803df740acad02f00dd93a5c/src/SIL.XForge.Scripture/ClientApp/src/app/shared/text/text.component.spec.ts#L482)):*
<details><summary><i>Previously, RaymondLuong3 (Raymond Luong) wrote…</i></summary><blockquote>

This could use some updating
</blockquote></details>

Ha. Indeed. Thank you.

**Comment by Nateowami** [comment]
@marksvc @RaymondLuong3 How did Raymond "Reviewed 2 of 2 files at r2, all commit messages." when there are three files, and there were three at the time of the review?

**Review by RaymondLuong3 — APPROVED** [review]
That's kind of strange. It's possible that on the second revision which did not touch `text.component.ts`, that file was not counted as one needing to be reviewed. But that's just a guess.

> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1724#-:-NQQnFzODXIeN1hP5FLJ:b-l8f7i2)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @marksvc)

**Comment by marksvc** [comment]
I don't know, @Nateowami . That's confusing :)

**Pull request merged**
