### PR TITLE
SF-3036 Add attach audio component

### PR DESCRIPTION
**Pull request by RaymondLuong3**
The attach audio feature is in multiple places. This PR creates an attach audio component that can be reused for recording questions, answers and the coming-soon audio comment feature.

- - -
This change is [Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/2795)

### CODE REVIEW

**Review by kylebuss — CHANGES_REQUESTED** [review]
Awesome work Raymond! It doesn't fail the test but there are a number of NG0303 and NG0304 errors in the `checking.component.spec.ts`, You should just need to add the `AttachAudioComponent` to the declarations to resolve it.

> Reviewed 12 of 13 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/2795#-:-O8vx4Pu9GxhD4vAPOC9:b-k7aw0e)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @RaymondLuong3)

**Review by RaymondLuong3 — COMMENTED** [review]
Thanks for catching that. I've updated the spec with the additional declaration.

> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/2795#-:-O8wH4QJ1z9Joj9eU8fV:b-e2usdx)* status: 13 of 14 files reviewed, all discussions resolved (waiting on @kylebuss)

**Review by kylebuss — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/2795#-:-O8wH9i5B-QMuTMbWZs0:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @RaymondLuong3)

**Review by Nateowami — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/2795)* status: all files reviewed, 1 unresolved discussion (waiting on @RaymondLuong3)

___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/checking/attach-audio/attach-audio.component.ts` line 10 at r3](https://reviewable.io/reviews/sillsdev/web-xforge/2795#-O9MRznI5y6h0bQVYffi:-O9MRznI5y6h0bQVYffj:bdaij7v) ([raw file](https://github.com/sillsdev/web-xforge/blob/8599ab00a969855e6cc5979a01471b85eee05d02/src/SIL.XForge.Scripture/ClientApp/src/app/checking/attach-audio/attach-audio.component.ts#L10)):*
> ```XML
>   styleUrl: './attach-audio.component.scss'
> })
> export class AttachAudioComponent {
> ```

Is there a good reason this component isn't standalone?

**Comment by RaymondLuong3** [comment]
It could probably be made stand alone. I would prefer to do that in a separate task and have testers finish testing this since it is holding up the next change to add the audio comment.

**Pull request merged**
