### PR TITLE
SF-2768 Join component supresses unknown errors

### PR DESCRIPTION
**Pull request by nigel-wells**
* Make the error handler async
* Remove redundant test
* Update tests to return expected response codes
* Use error handler on unknown join errors

For testing an unknown error you can create a share key, expiry it, and then comment out `key_expired` as a known error code. I'm not sure of an easier way to do this for the test team.

As error dialogs are now async there will need to be a good amount of testing to make sure there aren't any side effects that need to be tidied up for existing errors.

- - -
This change is [Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/2572)

### CODE REVIEW

**Review by RaymondLuong3 — CHANGES_REQUESTED** [review]
Nice work. I can confirm that joining errors are handled as expected. Just a couple minor comments.

> Reviewed 6 of 6 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/2572#-:-O13tDGI0u4lvCCLUrCJ:b-dzynka)* status: all files reviewed, 3 unresolved discussions (waiting on @nigel-wells)

___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/join/join.component.ts` line 180 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/2572#-O13syWv0pmtUnCMFVo2:-O13syWv0pmtUnCMFVo3:b4zv9sq) ([raw file](https://github.com/sillsdev/web-xforge/blob/4ff211948c924d4dd07a286bca922454ff46c2b3/src/SIL.XForge.Scripture/ClientApp/src/app/join/join.component.ts#L180)):*
> ```XML
>   }
> 
>   private async handleErrorJoining(error: any): Promise<void> {
> ```

Nit: I like the name "handleJoiningError" better



_Code quote:_
```XML
  private async handleErrorJoining(error: any): Promise<void> {
```
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/join/join.component.spec.ts` line 98 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/2572#-O13Bu8M9mNQCh6M3bvZ:-O13Bu8M9mNQCh6M3bv_:b-cofln2) ([raw file](https://github.com/sillsdev/web-xforge/blob/4ff211948c924d4dd07a286bca922454ff46c2b3/src/SIL.XForge.Scripture/ClientApp/src/app/join/join.component.spec.ts#L98)):*
> ```XML
>     new TestEnvironment({ callback, isLoggedIn: true });
> 
>     verify(mockedDialogService.message(anything())).once();
> ```

Add a line here to verify that `handleError` is not called on mockedErrorHandler.
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/join/join.component.spec.ts` line 173 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/2572#-O13BdU43NYKfxbhdk_0:-O13BdU57zx15Dwmks2L:b-8nkxnp) ([raw file](https://github.com/sillsdev/web-xforge/blob/4ff211948c924d4dd07a286bca922454ff46c2b3/src/SIL.XForge.Scripture/ClientApp/src/app/join/join.component.spec.ts#L173)):*
> ```XML
>       new TestEnvironment({ callback });
> 
>       verify(mockedDialogService.message(anything())).once();
> ```

Add a line here to verify that `mockedErrorHandler.handleError` is not called when the error type is known.

**Review by nigel-wells — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/2572)* status: 4 of 6 files reviewed, 2 unresolved discussions (waiting on @RaymondLuong3)

___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/join/join.component.ts` line 180 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/2572#-O13syWv0pmtUnCMFVo2:-O1ESN8-CzTehDEAvzpk:b-896fix) ([raw file](https://github.com/sillsdev/web-xforge/blob/4ff211948c924d4dd07a286bca922454ff46c2b3/src/SIL.XForge.Scripture/ClientApp/src/app/join/join.component.ts#L180)):*
<details><summary><i>Previously, RaymondLuong3 (Raymond Luong) wrote…</i></summary><blockquote>

Nit: I like the name "handleJoiningError" better
</blockquote></details>

Done.
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/join/join.component.spec.ts` line 98 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/2572#-O13Bu8M9mNQCh6M3bvZ:-O1ETdk1745QdPqZYUvW:b-896fix) ([raw file](https://github.com/sillsdev/web-xforge/blob/4ff211948c924d4dd07a286bca922454ff46c2b3/src/SIL.XForge.Scripture/ClientApp/src/app/join/join.component.spec.ts#L98)):*
<details><summary><i>Previously, RaymondLuong3 (Raymond Luong) wrote…</i></summary><blockquote>

Add a line here to verify that `handleError` is not called on mockedErrorHandler.
</blockquote></details>

Done.
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/join/join.component.spec.ts` line 173 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/2572#-O13BdU43NYKfxbhdk_0:-O1ETeTmAElDC1gXykeE:b-896fix) ([raw file](https://github.com/sillsdev/web-xforge/blob/4ff211948c924d4dd07a286bca922454ff46c2b3/src/SIL.XForge.Scripture/ClientApp/src/app/join/join.component.spec.ts#L173)):*
<details><summary><i>Previously, RaymondLuong3 (Raymond Luong) wrote…</i></summary><blockquote>

Add a line here to verify that `mockedErrorHandler.handleError` is not called when the error type is known.
</blockquote></details>

Done.

**Review by RaymondLuong3 — APPROVED** [review]
This looks good and works as expected in my testing. How do you think testers should verify this fix? Perhaps you will want to create a different branch that creates an expired share key and has the `link_expired` known error removed, and then show that the suppressed error is shown?
I'll let you move the issue into testing when you create acceptance tests for this.

> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/2572#-:-O1IPC-909Aq8_Mxyk1T:bnobzx8)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @nigel-wells)

**Review by nigel-wells — COMMENTED** [review]
Good thinking about creating another branch for that specific test - I've pushed it through to `fix/report-unknown-errors-joining-testing` and will update the acceptance tests with this.

> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/2572#-:-O1J5tSH9PKNjjKFvc8c:buuvpcz)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @nigel-wells)

**Pull request merged**
