### PR TITLE
Migrator: PtdaSyncAll: Run synchronizations asynchronously 

### PR DESCRIPTION
**Pull request by marksvc**
Commit "Migrator: Run synchronizations asynchronously" is ready for review, tho depends on unmerged code.
Another commit is part of this PR but shouldn't be: Dependency commit "Migrator: Make PtdaSyncAll sync all" is PR #739.

---
This change is [Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/764)

### CODE REVIEW

**Comment by marksvc** [comment]
This PR was rebased on master and now contains only the changes for review.

**Comment by marksvc** [comment]
I added some more work but then decided to make a new PR of them, at #766. If you think this PR should be reporting more or different information, it might be addressed in the other PR.

**Review by ddaspit — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/764#-:-MF8sYmR2cDMPohQJ3JQ:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by irahopkinson — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/764)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
