### PR TITLE
SF-1565a Cancel input when invalid selection

### PR DESCRIPTION
**Pull request by marksvc**
- Although we adjust selections after the fact to be valid, if a user
starts to make a selection, and begins typing text before letting go
of the mouse, we end up replacing the selection with the new input.
This can allow selecting over verse numbers and losing
those verse numbers.
- Listen for 'beforeinput' and cancel processing the input if the
selection is not valid.

---

**Stack**:
- #1406
- #1405
- #1402
- #1401
- #1400
- #1395
- #1393 ⮜

⚠️ *Part of a stack created by [spr](https://github.com/ejoffe/spr). Do not merge manually using the UI - doing so may have unexpected results.*

---
This change is [Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1393)

### CODE REVIEW

**Review by RaymondLuong3 — CHANGES_REQUESTED** [review]
Nice work. I have a few minor comments.

> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1393#-:-N4DUTLzBjT6CSVqArfH:bnyhgvc)* status: all files reviewed, 4 unresolved discussions (waiting on @marksvc)

___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/shared/text/text.component.ts` line 1002 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/1393#-N4DPoA82CyFxPFkEh7N:-N4DPoA9Ey7Le6RRzyZU:b65g0ks) ([raw file](https://github.com/sillsdev/web-xforge/blob/9b85eb36ddeb10813a5cd1a6aa5ab6c83e8b822e/src/SIL.XForge.Scripture/ClientApp/src/app/shared/text/text.component.ts#L1002)):*
> ```XML
>     } else if (!this.multiSegmentSelection) {
>       // selections outside of the text chooser dialog are not permitted to extend across segments
>       let newStart: number = Math.max(sel.index, this._segment.range.index);
> ```

Are we positive that if a user makes a selection, that `this._segment` is the right segment (i.e. the segment where the selection started? I'm not sure the `this._segment` gets updated until after the selection changes event fires.



_Code quote:_
```XML
this._segment.range.index
```
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/shared/text/text.component.ts` line 1031 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/1393#-N4DPWk333cho0ZHfw7S:-N4DPWk333cho0ZHfw7T:b-fty5v9) ([raw file](https://github.com/sillsdev/web-xforge/blob/9b85eb36ddeb10813a5cd1a6aa5ab6c83e8b822e/src/SIL.XForge.Scripture/ClientApp/src/app/shared/text/text.component.ts#L1031)):*
> ```XML
> 
>     if (sel.index !== newSel.index || sel.length !== newSel.length) {
>       return false;
> ```

This could be combined with what is above.



_Code quote:_
```XML
    if (sel.index !== newSel.index || sel.length !== newSel.length) {
      return false;
    }
```
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/shared/text/text.component.spec.ts` line 2484 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/1393#-N4DUO1z9kWmVfbgd2Jd:-N4DUO1z9kWmVfbgd2Je:b-jukvxq) ([raw file](https://github.com/sillsdev/web-xforge/blob/9b85eb36ddeb10813a5cd1a6aa5ab6c83e8b822e/src/SIL.XForge.Scripture/ClientApp/src/app/shared/text/text.component.spec.ts#L2484)):*
> ```XML
>     expect(originalSegmentText).withContext('setup').toEqual(`quick brown fox`);
> 
>     const beforeinputEvent: InputEvent = new InputEvent('beforeinput', {
> ```

nit: input should be uppercase



_Code quote:_
```XML
const beforeinputEvent
```
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/shared/text/text.component.spec.ts` line 2492 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/1393#-N4DTp-j5vk_01xzwzL_:-N4DTp-j5vk_01xzwzLa:b-oqa4di) ([raw file](https://github.com/sillsdev/web-xforge/blob/9b85eb36ddeb10813a5cd1a6aa5ab6c83e8b822e/src/SIL.XForge.Scripture/ClientApp/src/app/shared/text/text.component.spec.ts#L2492)):*
> ```XML
> 
>     // SUT
>     const cancelled: boolean = !env.component.editor?.container.dispatchEvent(beforeinputEvent);
> ```

I'm curious how dispatching this event results in false. Does it somehow return whether beforeInputEvent.preventDefault() is called?



_Code quote:_
```XML
    const cancelled: boolean = !env.component.editor?.container.dispatchEvent(beforeinputEvent);
```

**Comment by marksvc** [comment]
*[`src/SIL.XForge.Scripture/ClientApp/src/app/shared/text/text.component.ts` line 1002 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/1393#-N4DPoA82CyFxPFkEh7N:-N4SxaMlB5KykEruDYkX:bkhrrcp) ([raw file](https://github.com/sillsdev/web-xforge/blob/9b85eb36ddeb10813a5cd1a6aa5ab6c83e8b822e/src/SIL.XForge.Scripture/ClientApp/src/app/shared/text/text.component.ts#L1002)):*
<details><summary><i>Previously, RaymondLuong3 (Raymond Luong) wrote…</i></summary><blockquote>

Are we positive that if a user makes a selection, that `this._segment` is the right segment (i.e. the segment where the selection started? I'm not sure the `this._segment` gets updated until after the selection changes event fires.
</blockquote></details>

If I do some debugging, I can see that we are in text.component update(), where we might do tryChangeSegment(). Then we call adjustSelection(), which then gets us here to conformToValidSelectionForCurrentSegment().
I observe that I don't seem to get here until I release the mouse button from creating a selection, and when here, this._segment has a `ref` of the segment where I started making my selection. So it seems fine in practice. 

Another way to get here is from isValidSelectionForCurrentSegment(), from onBeforeInput(). 
If I start a selection and make the selection go from one segment to another, and type a letter, before releasing the mouse button, then in conformToValidSelectionFocRurrentSegment() I see that this._segment has `ref` of the starting segment. It looks like first we do come to text.component onSelectionChanged(), which calls update(), which can tryChangeSegment(), updating this._segment.
Actually, I do see that sometimes the this._segment isn't the starting segment, but I think it may be depending on some logic in a call `segmentRef = this.viewModel.getSegmentRef(selection);`, where it uses some logic to decide which segment in a given selection is 'the segment'. I haven't studied it closely.

So, it seems to be good regarding this_segment being a good segment for the situation.

**Comment by marksvc** [comment]
I added a function that returns a type `{env:TestEnvironment; segmentRef:string}`. This type isn't being fully used until followup commits.

**Review by RaymondLuong3 — APPROVED** [review]
I'll note that we generally want the test coverage to increase on PR's, but it may do so once the PR is squashed. Otherwise I approve.

> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1393#-:-N4TU9aEA9LNhCO0pSgk:b-bnbcy8)* status: all files reviewed, 1 unresolved discussion (waiting on @marksvc)

___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/shared/text/text.component.ts` line 1002 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/1393#-N4DPoA82CyFxPFkEh7N:-N4TSwsX-Fka5vmfBYbZ:b-e0hwh5) ([raw file](https://github.com/sillsdev/web-xforge/blob/9b85eb36ddeb10813a5cd1a6aa5ab6c83e8b822e/src/SIL.XForge.Scripture/ClientApp/src/app/shared/text/text.component.ts#L1002)):*
<details><summary><i>Previously, marksvc wrote…</i></summary><blockquote>

If I do some debugging, I can see that we are in text.component update(), where we might do tryChangeSegment(). Then we call adjustSelection(), which then gets us here to conformToValidSelectionForCurrentSegment().
I observe that I don't seem to get here until I release the mouse button from creating a selection, and when here, this._segment has a `ref` of the segment where I started making my selection. So it seems fine in practice. 

Another way to get here is from isValidSelectionForCurrentSegment(), from onBeforeInput(). 
If I start a selection and make the selection go from one segment to another, and type a letter, before releasing the mouse button, then in conformToValidSelectionFocRurrentSegment() I see that this._segment has `ref` of the starting segment. It looks like first we do come to text.component onSelectionChanged(), which calls update(), which can tryChangeSegment(), updating this._segment.
Actually, I do see that sometimes the this._segment isn't the starting segment, but I think it may be depending on some logic in a call `segmentRef = this.viewModel.getSegmentRef(selection);`, where it uses some logic to decide which segment in a given selection is 'the segment'. I haven't studied it closely.

So, it seems to be good regarding this_segment being a good segment for the situation. 


</blockquote></details>

So if a user makes a selection and types a letter before they release the mouse, calling conformToValidSelectionForCurrentSegment() correctly interprets this._segment? If so, then that is great!

**Review by marksvc — COMMENTED** [review]
Followup commits aren't necessarily going to change this. I looked closer at the codecov report. It does look not very optimal, saying 
> + Hits        13012    13022      +10     
> + Misses       4535     4527       -8     
> - Partials      652      669      +17     

in at least its original report. I see that the edited, existing lines that are yellow or red are 
situations of checking if basic pieces are null, in which case we give up processing (presumably to handle the situation of the component still getting loaded up). There is a line in the report that stands out as significant, which is that `if (!this.isValidSelectionForCurrentSegment(sel)) {` is yellow, indicating that only one side of the branch was tested. That's something I also picked up on and fixed earlier when considering the unit tests from our discussion. I see that in my local code coverage report, that line is green now (tho I have some followup applied, which could potentially be impacting it). 

> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1393#-:-N4TiFWr1sw5uGhqY7z0:bsw7v07)* status: all files reviewed, 1 unresolved discussion (waiting on @RaymondLuong3)

___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/shared/text/text.component.ts` line 1002 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/1393#-N4DPoA82CyFxPFkEh7N:-N4TkAxxCNJS3c2xaWUp:b-plqpn4) ([raw file](https://github.com/sillsdev/web-xforge/blob/9b85eb36ddeb10813a5cd1a6aa5ab6c83e8b822e/src/SIL.XForge.Scripture/ClientApp/src/app/shared/text/text.component.ts#L1002)):*
> So if a user makes a selection and types a letter before they release the mouse, calling conformToValidSelectionForCurrentSegment() correctly interprets this._segment? If so, then that is great!

Yes. Or rather, it "has and uses a helpful value for this._segment".

**Review by RaymondLuong3 — APPROVED** [review]
Thanks for looking into it.

> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1393#-:-N4U9sex5Ni1a8N4yWxr:b-k6hqqf)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @marksvc)

**Comment by marksvc** [comment]
@RaymondLuong3 I decided to roll some adjustments back into this change, that I'd like you to have a look at before I move this along. Thanks!

**Review by RaymondLuong3 — APPROVED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1393)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @marksvc)

**Pull request merged**
