### PR TITLE
SF-2616 Add support to download a draft as a zip file

### PR DESCRIPTION
**Pull request by pmachapman**
This PR adds support for downloading all of the draft USFM files for a project as a zip file.

Please see the Balsamiq UI mockup and the Google Doc linked to the JIRA ticket for the change specifications.

- - -
This change is [Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/2490)

### CODE REVIEW

**Review by nigel-wells — CHANGES_REQUESTED** [review]
Looks and works great. Some things to consider - could be a follow up PR if needed.

> Reviewed 11 of 11 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/2490#-:-NyxEjVtDOXhj9YZm9ta:b-rxgrh0)* status: all files reviewed, 9 unresolved discussions (waiting on @pmachapman)

___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-generation.component.html` line 240 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/2490#-Nyx5xTj9Q-n4dj4WCX5:-Nyx5xTj9Q-n4dj4WCX6:b-bw5fv2) ([raw file](https://github.com/sillsdev/web-xforge/blob/a2edac0c3aa431980ef1d66f6ec668ce106d31db/src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-generation.component.html#L240)):*
> ```HTML
>                   <mat-card-actions>
>                     <button
>                       *ngIf="hasDraftBooksAvailable"
> ```

Just a note that this logic would offer some good improvements to the message that appears here. If the draft is complete, but no drafts are available, our message should inform that to the user. Otherwise we'll say it is ready and they can preview the draft but have no books or buttons to click on. They'll also get a 
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-generation.component.ts` line 246 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/2490#-Nyx54Le0V6_K_2mAMww:-Nyx54Le0V6_K_2mAMwx:bqf9e0q) ([raw file](https://github.com/sillsdev/web-xforge/blob/a2edac0c3aa431980ef1d66f6ec668ce106d31db/src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-generation.component.ts#L246)):*
> ```XML
> 
>             this.hasDraftBooksAvailable =
>               projectDoc?.data?.texts?.some(t => t.chapters?.some(c => c.hasDraft)) ?? false;
> ```

Sanity check, is this updated and the interface updated after a webhook is triggered or will the user need to refresh before seeing the download button?
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-generation.component.ts` line 352 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/2490#-NywsIC71j-VkYy0GhY7:-NywsIC71j-VkYy0GhY8:b-reh6pp) ([raw file](https://github.com/sillsdev/web-xforge/blob/a2edac0c3aa431980ef1d66f6ec668ce106d31db/src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-generation.component.ts#L352)):*
> ```XML
>         if (usfm != null) {
>           const fileName: string =
>             bookNum.toString().padStart(2, '0') + Canon.bookNumberToId(bookNum) + projectShortName + '.sfm';
> ```

Similar to this one - probably not a timestamp though. Use an underscore to separate each part to make it more readable. One of my examples looks like `41MRKMPPN` which requires paying more attention to read it vs `41_MRK_MPPN`
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-generation.component.ts` line 365 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/2490#-Nyx4lU88vAQHJXwKEUh:-Nyx4lU88vAQHJXwKEUi:bt8uv66) ([raw file](https://github.com/sillsdev/web-xforge/blob/a2edac0c3aa431980ef1d66f6ec668ce106d31db/src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-generation.component.ts#L365)):*
> ```XML
>       this.downloadBooksTotal = 0;
>       this.downloadBooksProgress = 0;
>       this.noticeService.showError(translate('draft_generation.info_alert_no_books_to_download'));
> ```

Is this state even possible as wasn't this proven by `hasDraftBooksAvailable`? Would this occur on a connection issue with Serval? If so, we should have a different message.
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-generation.component.ts` line 370 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/2490#-Nyx4ZMF0ze-D4L5yNCw:-Nyx4ZMF0ze-D4L5yNCx:bezcdsj) ([raw file](https://github.com/sillsdev/web-xforge/blob/a2edac0c3aa431980ef1d66f6ec668ce106d31db/src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-generation.component.ts#L370)):*
> ```XML
> 
>     // Download the zip file
>     const filename: string = projectDoc.data.shortName + '.zip';
> ```

I see JoEllen suggested some ideas for this filename and I agree that it should be more than just shortname so as to not confuse it with future downloads on the same project. JoEllen suggested including the source and target. Maybe a timestamp from Serval to provide more context?
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-generation.component.spec.ts` line 1466 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/2490#-Nyx8b14DGk2aLvcXCOO:-Nyx8b14DGk2aLvcXCOP:bbkqgx0) ([raw file](https://github.com/sillsdev/web-xforge/blob/a2edac0c3aa431980ef1d66f6ec668ce106d31db/src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-generation.component.spec.ts#L1466)):*
> ```XML
>   });
> 
>   describe('download draft button', () => {
> ```

Have a test that the button appears after a remote update on the doc for `hasDraft`
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-generation.component.spec.ts` line 1473 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/2490#-Nyx8BYd1WZeHcsmFDjs:-Nyx8BYd1WZeHcsmFDjt:b6w53r9) ([raw file](https://github.com/sillsdev/web-xforge/blob/a2edac0c3aa431980ef1d66f6ec668ce106d31db/src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-generation.component.spec.ts#L1473)):*
> ```XML
>       env.fixture.detectChanges();
> 
>       expect(env.getElementByTestId('download-button')).not.toBe(null);
> ```

Create a getter for the element in `TestEnvironment`
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-generation.component.spec.ts` line 1504 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/2490#-Nyx8LAP4pitlYb03GWF:-Nyx8LAP4pitlYb03GWG:b6w53r9) ([raw file](https://github.com/sillsdev/web-xforge/blob/a2edac0c3aa431980ef1d66f6ec668ce106d31db/src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-generation.component.spec.ts#L1504)):*
> ```XML
>       env.fixture.detectChanges();
> 
>       expect(env.getElementByTestId('download-spinner')).not.toBe(null);
> ```

Create a getter for the element in `TestEnvironment`
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-generation.service.ts` line 205 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/2490#-NyxE1mu7WW3i0_afjYs:-NyxE1mu7WW3i0_afjYt:b-ozbefl) ([raw file](https://github.com/sillsdev/web-xforge/blob/a2edac0c3aa431980ef1d66f6ec668ce106d31db/src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-generation.service.ts#L205)):*
> ```XML
>    * @param projectId The SF project id for the target translation.
>    * @param book The book number.
>    * @param chapter The chapter number.
> ```

Can you add a note that passing `0` returns all chapters if that is the logic
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-generation.service.ts` line 222 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/2490#-NyxDZ0S8cnxQgw19a2C:-NyxDZ0S8cnxQgw19a2D:b-9fuzf7) ([raw file](https://github.com/sillsdev/web-xforge/blob/a2edac0c3aa431980ef1d66f6ec668ce106d31db/src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-generation.service.ts#L222)):*
> ```XML
>           }
> 
>           this.noticeService.showError(translate('draft_generation.temporarily_unavailable'));
> ```

Similar to my other points, this message should be mixed with the other one. If this state occurs then the user will see this error message followed up with the next one about no books available.

**Review by pmachapman — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/2490)* status: 3 of 12 files reviewed, 8 unresolved discussions (waiting on @nigel-wells)

___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-generation.component.html` line 257 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/2490#gh-1617521240:-Nz-wUSa7szBMmKKNiyc:b7kpp7z) ([raw file](https://github.com/sillsdev/web-xforge/blob/a2edac0c3aa431980ef1d66f6ec668ce106d31db/src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-generation.component.html#L257)):*
> Use outlined icon (I think this balances with the + icon better)

Done.

> Remove the spinner from within the icon (was there a reason it was inside the icon)?

I have moved it outside the mat-icon.
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-generation.component.ts` line 246 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/2490#-Nyx54Le0V6_K_2mAMww:-Nz0Pp9003cvtiW7zYRF:b-ahfryb) ([raw file](https://github.com/sillsdev/web-xforge/blob/a2edac0c3aa431980ef1d66f6ec668ce106d31db/src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-generation.component.ts#L246)):*
<details><summary><i>Previously, nigel-wells (Nigel Wells) wrote…</i></summary><blockquote>

Sanity check, is this updated and the interface updated after a webhook is triggered or will the user need to refresh before seeing the download button?
</blockquote></details>

Done. It now updates when the webhook finishes. Good sanity check!
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-generation.component.ts` line 352 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/2490#-NywsIC71j-VkYy0GhY7:-Nz-xAYJ7Cq5J6wNLfpS:bnjc0ut) ([raw file](https://github.com/sillsdev/web-xforge/blob/a2edac0c3aa431980ef1d66f6ec668ce106d31db/src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-generation.component.ts#L352)):*
<details><summary><i>Previously, nigel-wells (Nigel Wells) wrote…</i></summary><blockquote>

Similar to this one - probably not a timestamp though. Use an underscore to separate each part to make it more readable. One of my examples looks like `41MRKMPPN` which requires paying more attention to read it vs `41_MRK_MPPN`
</blockquote></details>

I have followed the standard format for filenames used by Paratext 9 (have a look at your My Paratext 9 Projects directory and Nathaniel's comment). I think adding underscores will make it harder to use if for example the user wants to copy-paste them files directly into the Paratext project directory rather than import via Paratext.
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-generation.component.ts` line 365 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/2490#-Nyx4lU88vAQHJXwKEUh:-Nz-xU0wEi8GvNs5kiFK:byedem7) ([raw file](https://github.com/sillsdev/web-xforge/blob/a2edac0c3aa431980ef1d66f6ec668ce106d31db/src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-generation.component.ts#L365)):*
<details><summary><i>Previously, nigel-wells (Nigel Wells) wrote…</i></summary><blockquote>

Is this state even possible as wasn't this proven by `hasDraftBooksAvailable`? Would this occur on a connection issue with Serval? If so, we should have a different message.
</blockquote></details>

Yes, it would be a connection issue, or some other really unexpected issue. Updated - let me know if the wording works for you.
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-generation.component.ts` line 370 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/2490#-Nyx4ZMF0ze-D4L5yNCw:-Nz-yzBd3ReYsaMTiL-8:b-6ox7zr) ([raw file](https://github.com/sillsdev/web-xforge/blob/a2edac0c3aa431980ef1d66f6ec668ce106d31db/src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-generation.component.ts#L370)):*
<details><summary><i>Previously, nigel-wells (Nigel Wells) wrote…</i></summary><blockquote>

I see JoEllen suggested some ideas for this filename and I agree that it should be more than just shortname so as to not confuse it with future downloads on the same project. JoEllen suggested including the source and target. Maybe a timestamp from Serval to provide more context?
</blockquote></details>

I think JoEllen's comments were about the SFM files (which I think should be named using the standard Paratext format). The point still stands for the zip file though - updated. Let me know if the naming format makes sense.
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-generation.component.spec.ts` line 1466 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/2490#-Nyx8b14DGk2aLvcXCOO:-Nz10Lo34S--4BVOAy4a:bylueij) ([raw file](https://github.com/sillsdev/web-xforge/blob/a2edac0c3aa431980ef1d66f6ec668ce106d31db/src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-generation.component.spec.ts#L1466)):*
<details><summary><i>Previously, nigel-wells (Nigel Wells) wrote…</i></summary><blockquote>

Have a test that the button appears after a remote update on the doc for `hasDraft`
</blockquote></details>

Done. It took a bit more work than I thought!
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-generation.component.spec.ts` line 1473 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/2490#-Nyx8BYd1WZeHcsmFDjs:-Nz0IFC28Lo_erqoHaFN:b-896fix) ([raw file](https://github.com/sillsdev/web-xforge/blob/a2edac0c3aa431980ef1d66f6ec668ce106d31db/src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-generation.component.spec.ts#L1473)):*
<details><summary><i>Previously, nigel-wells (Nigel Wells) wrote…</i></summary><blockquote>

Create a getter for the element in `TestEnvironment`
</blockquote></details>

Done.
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-generation.component.spec.ts` line 1504 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/2490#-Nyx8LAP4pitlYb03GWF:-Nz0IGJyEEXyqkyRHKKj:b-896fix) ([raw file](https://github.com/sillsdev/web-xforge/blob/a2edac0c3aa431980ef1d66f6ec668ce106d31db/src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-generation.component.spec.ts#L1504)):*
<details><summary><i>Previously, nigel-wells (Nigel Wells) wrote…</i></summary><blockquote>

Create a getter for the element in `TestEnvironment`
</blockquote></details>

Done.
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-generation.service.ts` line 205 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/2490#-NyxE1mu7WW3i0_afjYs:-Nz0IP-g67ZH1j95F-zF:b35wj2g) ([raw file](https://github.com/sillsdev/web-xforge/blob/a2edac0c3aa431980ef1d66f6ec668ce106d31db/src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-generation.service.ts#L205)):*
<details><summary><i>Previously, nigel-wells (Nigel Wells) wrote…</i></summary><blockquote>

Can you add a note that passing `0` returns all chapters if that is the logic
</blockquote></details>

Done. Good point.
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-generation.service.ts` line 222 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/2490#-NyxDZ0S8cnxQgw19a2C:-Nz0IWzT-fNn2v6tITRd:by3n4us) ([raw file](https://github.com/sillsdev/web-xforge/blob/a2edac0c3aa431980ef1d66f6ec668ce106d31db/src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-generation.service.ts#L222)):*
<details><summary><i>Previously, nigel-wells (Nigel Wells) wrote…</i></summary><blockquote>

Similar to my other points, this message should be mixed with the other one. If this state occurs then the user will see this error message followed up with the next one about no books available.
</blockquote></details>

Done. Good thinking.

**Review by nigel-wells — APPROVED** [review]
:lgtm:

> Reviewed 9 of 9 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/2490#-:-Nz1Bd9qCnVEVFfdYrhB:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @pmachapman)

___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/machine-api/build-dto.ts` line 16 at r2](https://reviewable.io/reviews/sillsdev/web-xforge/2490#-Nz19fVh74aszHE3EQYA:-Nz19fVh74aszHE3EQYB:b-kky361) ([raw file](https://github.com/sillsdev/web-xforge/blob/a84345425b94d194e6f3cb67288b477e31dee4d4/src/SIL.XForge.Scripture/ClientApp/src/app/machine-api/build-dto.ts#L16)):*
> ```XML
>   buildId: string;
>   corporaIds?: string[];
>   dateFinished?: string;
> ```

Did you change this just for the filename or was it always a string?
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-generation.component.ts` line 352 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/2490#-NywsIC71j-VkYy0GhY7:-Nz175v68-TDGrf1olLR:b-ip9lwh) ([raw file](https://github.com/sillsdev/web-xforge/blob/a2edac0c3aa431980ef1d66f6ec668ce106d31db/src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-generation.component.ts#L352)):*
<details><summary><i>Previously, pmachapman (Peter Chapman) wrote…</i></summary><blockquote>

I have followed the standard format for filenames used by Paratext 9 (have a look at your My Paratext 9 Projects directory and Nathaniel's comment). I think adding underscores will make it harder to use if for example the user wants to copy-paste them files directly into the Paratext project directory rather than import via Paratext.
</blockquote></details>

Ah yes, good thinking to follow the PT naming format. Happy with that.

**Review by pmachapman — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/2490)* status: all files reviewed, 1 unresolved discussion (waiting on @nigel-wells)

___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/machine-api/build-dto.ts` line 16 at r2](https://reviewable.io/reviews/sillsdev/web-xforge/2490#-Nz19fVh74aszHE3EQYA:-Nz1C-J5EuB7kGfa4oli:b-o4jpnm) ([raw file](https://github.com/sillsdev/web-xforge/blob/a84345425b94d194e6f3cb67288b477e31dee4d4/src/SIL.XForge.Scripture/ClientApp/src/app/machine-api/build-dto.ts#L16)):*
<details><summary><i>Previously, nigel-wells (Nigel Wells) wrote…</i></summary><blockquote>

Did you change this just for the filename or was it always a string?
</blockquote></details>

It was always a string. I only found it out when writing this code and realised that I was getting errors using Date functions on it.

**Pull request merged**
