### PR TITLE
doc: add section Cleaning

### PR DESCRIPTION
**Pull request by marksvc**
This change is [Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1641)

### CODE REVIEW

**Review by pmachapman — COMMENTED** [review]
Do we want to document this for Windows as well? Apart from the path naming differences, the delete obj directories command looks like:

`FOR /F "tokens=*" %G IN ('DIR /B /AD /S obj') DO RMDIR /S /Q "%G"`

> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1641#-:-NJGv2Uz-NaEVxCaF9uO:b-sytada)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @marksvc)

___
*[`README.md` line 576 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/1641#-NJGuQ1p4RkkaDhD9PQF:-NJGuQ1p4RkkaDhD9PQG:b-3fddq9) ([raw file](https://github.com/sillsdev/web-xforge/blob/7a833fdacac8e92d10e7f5bac48730ac7457e26e/README.md#L576)):*
> ```Markdown
> ## Cleaning
> 
> After updating or swiching branches, some of these cleaning steps may be helpful.
> ```

Typo: switching



_Code quote:_
```Markdown
swiching
```

**Review by pmachapman — CHANGES_REQUESTED** [review]
Just the typo and question on whether we want Windows equivalents for the commands?

**Review by marksvc — COMMENTED** [review]
Thanks for the suggestion, and for your patience :). I think it's a good idea to document it for Windows. I adjusted the command so it doesn't assume `web-xforge` is in a particular place, which will also help with use on Windows (if `cd src/RealtimeServer && npm ci && ...` runs on Windows at all?). I wasn't sure if I should repeat the block of commands for Windows, but I put in the `FOR ...` command afterward at least. Feel free to further improve this as desired.

> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1641#-:-NKyq8_Y3r_bUP40_AN6:b-lmkngi)* status: 0 of 1 files reviewed, all discussions resolved (waiting on @pmachapman)

**Review by pmachapman — APPROVED** [review]
I think that's perfect - the dev should be able to figure out the `cd` statement on their own (it will work the same on windows, except the line breaks). Windows' command line syntax is...antiquated :-) :lgtm:

> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1641#-:-NKyt4zICGQNPPd0VyV4:b7ol3gk)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @marksvc)

**Pull request merged**
