### PR TITLE
SF-575 Fix unread badge glitch

### PR DESCRIPTION
**Pull request by RaymondLuong3**
This change is [Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/322)

### CODE REVIEW

**Comment by Nateowami** [comment]
@jasonleenaylor Reviewable shows you were going to say something but haven't edited your review in an hour. I'll hold off merging for a while in case you have suggestions/objections.

**Comment by marksvc** [comment]
(I've been working on how we might do this same fix but without setting width to 85%)

**Comment by marksvc** [comment]
85% seemed more eyeballed rather than computed. I had a go at positioning them a different way, which I put up at https://github.com/sillsdev/web-xforge/commit/96a42e06000fea622f7da4b05b0a10760df4f00f
I don't object to this PR going thru, but I was reading flexbox documentation today and wanted to try fixing it without 85% :-)
The flexbox-fix doesn't preserve the icon transition, but if it's thought that this approach is preferred, we can probably figure out how to get that back in.

**Comment by marksvc** [comment]
(Ok so 7a8fb09 preserves the icon transition. (Tho it looks slightly odder, going out to the right))

**Comment by RaymondLuong3** [comment]
I am ok with either change.

**Comment by irahopkinson** [comment]
@nigel-wells would you mind reviewing this? Not so much this solution but Mark's solution as well. Is Mark's solution, even though more complex, a better direction to go in?

**Pull request merged**
