### PR TITLE
SF-2678 Use the source for training when the alternate source is set

### PR DESCRIPTION
**Pull request by pmachapman**
This change is [Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/2407)

### CODE REVIEW

**Review by Nateowami — COMMENTED** [review]
> Reviewed 29 of 35 files at r1, 1 of 4 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/2407)* status: 30 of 35 files reviewed, 2 unresolved discussions (waiting on @nigel-wells and @pmachapman)

___
*[`src/SIL.XForge.Scripture/Services/MachineProjectService.cs` line 571 at r3](https://reviewable.io/reviews/sillsdev/web-xforge/2407#-NvEzHhG0Rocp3puzn6L:-NvEzHhG0Rocp3puzn6M:b-asjgdk) ([raw file](https://github.com/sillsdev/web-xforge/blob/a659ca969be32d013b77d8c367a929e00998fe1a/src/SIL.XForge.Scripture/Services/MachineProjectService.cs#L571)):*
> ```Smalltalk
> 
>         // See if there is an alternate source to use for drafting
>         bool useAlternateSource =
> ```

I thought I was following everything up to this point, but now I am lost. What I expected to see and what I actually see is different. What I was expecting (pseudo code) is something like:
```
trainingSource = alternateTrainingSourceEnabled ? alternateTrainingSource : source
draftingSource = alternateDraftingSourceEnabled ? alternateDraftingSource : source
```
I think I'm going to need to get on a call to sort through this.

**Review by nigel-wells — CHANGES_REQUESTED** [review]
Well that makes the head spin! Perhaps its the first time I've had a good think through the whole process but it does seem like we should have a flow chart generated in a Google Doc (or Balsamiq) somewhere to help follow the paths. Also, if it's hard for us to explain then our UI is probably going to reflect that and make it really difficult for users to get "right". We could have a session at some stage to consider this and try mock something up in Balsamiq.

> Reviewed 31 of 35 files at r1, 4 of 4 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/2407#-:-NvFc5HtEMIwtC1FY9Ip:b7xpk0b)* status: all files reviewed, 5 unresolved discussions (waiting on @pmachapman)

___
*[`src/RealtimeServer/scriptureforge/services/sf-project-migrations.spec.ts` line 409 at r3](https://reviewable.io/reviews/sillsdev/web-xforge/2407#-NvFTNHB8KX4JUyC20MV:-NvFTNHB8KX4JUyC20MW:b-mhajb5) ([raw file](https://github.com/sillsdev/web-xforge/blob/a659ca969be32d013b77d8c367a929e00998fe1a/src/RealtimeServer/scriptureforge/services/sf-project-migrations.spec.ts#L409)):*
> ```XML
>     });
> 
>     it('sets alternateSourceEnabled to true when an alternate source is present', async () => {
> ```

Can you also test the inverse when `alternateSourceEnabled` is `true` but there is no alternate source set.
___
*[`src/SIL.XForge.Scripture/Services/MachineProjectService.cs` line 574 at r3](https://reviewable.io/reviews/sillsdev/web-xforge/2407#-NvFWV58A35C-rT7cdNN:-NvFWFPG1acHP6J1M4Xn:bb5zab9) ([raw file](https://github.com/sillsdev/web-xforge/blob/a659ca969be32d013b77d8c367a929e00998fe1a/src/SIL.XForge.Scripture/Services/MachineProjectService.cs#L574)):*
> ```Smalltalk
>             project.TranslateConfig.DraftConfig.AlternateSourceEnabled
>             && project.TranslateConfig.DraftConfig.AlternateSource is not null
>             && preTranslate;
> ```

This is the first time you've also checked pre translation. Is this needed and, if so, should it be checked in other places as well?
___
*[`test/SIL.XForge.Scripture.Tests/Services/MachineProjectServiceTests.cs` line 1603 at r3](https://reviewable.io/reviews/sillsdev/web-xforge/2407#-NvFaZZc2Rtsdd0sMFxd:-NvFaZZc2Rtsdd0sMFxe:b-kzrqjp) ([raw file](https://github.com/sillsdev/web-xforge/blob/a659ca969be32d013b77d8c367a929e00998fe1a/test/SIL.XForge.Scripture.Tests/Services/MachineProjectServiceTests.cs#L1603)):*
> ```Smalltalk
> 
>     [Test]
>     public async Task SyncProjectCorporaAsync_SynchronizesTheAlternateSource()
> ```

I think I've somewhat followed this far. Do we need a test to check if alternative source is enabled, but there is no alternate training source so use the reference for the source, has actually happened?

**Review by pmachapman — COMMENTED** [review]
Yes, the UI is a problem...it has evolved too incrementally and needs a real clean up. Nathaniel has started a Balsamiq on this: "Drafting settings"

> Dismissed @github-advanced-security[bot] from a discussion.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/2407#-:-NvTY3j4-tpBxyRJemG0:b-urd6bo)* status: all files reviewed, 4 unresolved discussions (waiting on @Nateowami and @nigel-wells)

___
*[`src/RealtimeServer/scriptureforge/services/sf-project-migrations.spec.ts` line 409 at r3](https://reviewable.io/reviews/sillsdev/web-xforge/2407#-NvFTNHB8KX4JUyC20MV:-NvTYovn5kCQNvUv7a7y:bqjxsux) ([raw file](https://github.com/sillsdev/web-xforge/blob/a659ca969be32d013b77d8c367a929e00998fe1a/src/RealtimeServer/scriptureforge/services/sf-project-migrations.spec.ts#L409)):*
<details><summary><i>Previously, nigel-wells (Nigel Wells) wrote…</i></summary><blockquote>

Can you also test the inverse when `alternateSourceEnabled` is `true` but there is no alternate source set.
</blockquote></details>

The first test "adds alternateSourceEnabled to draftConfig" covers the inverse, unless I am missing something?
___
*[`src/SIL.XForge.Scripture/Services/MachineProjectService.cs` line 571 at r3](https://reviewable.io/reviews/sillsdev/web-xforge/2407#-NvEzHhG0Rocp3puzn6L:-NvTLdJ00ini2cwYFqlY:bksfmcn) ([raw file](https://github.com/sillsdev/web-xforge/blob/a659ca969be32d013b77d8c367a929e00998fe1a/src/SIL.XForge.Scripture/Services/MachineProjectService.cs#L571)):*
<details><summary><i>Previously, Nateowami (Nathaniel Paulus) wrote…</i></summary><blockquote>

I thought I was following everything up to this point, but now I am lost. What I expected to see and what I actually see is different. What I was expecting (pseudo code) is something like:
```
trainingSource = alternateTrainingSourceEnabled ? alternateTrainingSource : source
draftingSource = alternateDraftingSourceEnabled ? alternateDraftingSource : source
```
I think I'm going to need to get on a call to sort through this.
</blockquote></details>

In its simplest terms, we could express the logic that way (see the truth table below), but I was hampered by a couple of factors:

 * The support for sendAllSegments (i.e. SFTextCorpusFactory), and the retaining support for text file uploads
 * Knowledge of the mixSource PR (SF-2615 - https://github.com/sillsdev/web-xforge/pull/2394)
 * Deletion of the second corpus when only one corpus is in use (Serval will use all corpora unless we removed this second corpus)

My goal is when Serval supports translating non-Scripture segments in Paratext zip files, I will be able to greatly simplify the logic in this method. Until then I am a little hamstrung, and my attempts to simplify kept failing for edge cases.

```
+---------------------------+--------------------------------+
| trainOn (Training Source) | preTranslate (Drafting Source) |
+---------------------------+--------------------------------+
| Reference Source          | Reference Source               | <--- Both should be one corpus.
| Reference Source          | Alternate Source               |
| Alternate Training Source | Alternate Source               |
| Alternate Training Source | Reference Source               |
+---------------------------+--------------------------------+

```
___
*[`src/SIL.XForge.Scripture/Services/MachineProjectService.cs` line 574 at r3](https://reviewable.io/reviews/sillsdev/web-xforge/2407#-NvFWV58A35C-rT7cdNN:-NvTMFEQ-zsuFAGV3SKI:bq4t5eo) ([raw file](https://github.com/sillsdev/web-xforge/blob/a659ca969be32d013b77d8c367a929e00998fe1a/src/SIL.XForge.Scripture/Services/MachineProjectService.cs#L574)):*
<details><summary><i>Previously, nigel-wells (Nigel Wells) wrote…</i></summary><blockquote>

This is the first time you've also checked pre translation. Is this needed and, if so, should it be checked in other places as well?
</blockquote></details>

No, as these two Boolean values will only be true when pre-translating. The only other place it needed to be checked was the logic that deletes a secondary corpus if it is present (line 741), and just one source is used; and the additional training data section. (line 821).
___
*[`test/SIL.XForge.Scripture.Tests/Services/MachineProjectServiceTests.cs` line 1603 at r3](https://reviewable.io/reviews/sillsdev/web-xforge/2407#-NvFaZZc2Rtsdd0sMFxd:-NvTU-UXE7a3K5Hlwusd:b-jsrqj9) ([raw file](https://github.com/sillsdev/web-xforge/blob/a659ca969be32d013b77d8c367a929e00998fe1a/test/SIL.XForge.Scripture.Tests/Services/MachineProjectServiceTests.cs#L1603)):*
<details><summary><i>Previously, nigel-wells (Nigel Wells) wrote…</i></summary><blockquote>

I think I've somewhat followed this far. Do we need a test to check if alternative source is enabled, but there is no alternate training source so use the reference for the source, has actually happened?
</blockquote></details>

Done. Great idea.

**Review by nigel-wells — CHANGES_REQUESTED** [review]
Thanks - we can continue the discussion outside of this.

> Reviewed 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/2407#-:-NvZrj2w25w8hLu2oOpd:bx3pkxb)* status: all files reviewed, 2 unresolved discussions (waiting on @Nateowami and @pmachapman)

___
*[`src/RealtimeServer/scriptureforge/services/sf-project-migrations.spec.ts` line 409 at r3](https://reviewable.io/reviews/sillsdev/web-xforge/2407#-NvFTNHB8KX4JUyC20MV:-NvZtEoPDIV-UjWQdRdc:b4c5fxk) ([raw file](https://github.com/sillsdev/web-xforge/blob/a659ca969be32d013b77d8c367a929e00998fe1a/src/RealtimeServer/scriptureforge/services/sf-project-migrations.spec.ts#L409)):*
<details><summary><i>Previously, pmachapman (Peter Chapman) wrote…</i></summary><blockquote>

The first test "adds alternateSourceEnabled to draftConfig" covers the inverse, unless I am missing something?
</blockquote></details>

This is fine - fresh eyes are a wonderful thing!
___
*[`src/SIL.XForge.Scripture/Services/MachineProjectService.cs` line 574 at r3](https://reviewable.io/reviews/sillsdev/web-xforge/2407#-NvFWV58A35C-rT7cdNN:-NvZwFzZ5J1mN8MCinLs:b8wr6dz) ([raw file](https://github.com/sillsdev/web-xforge/blob/a659ca969be32d013b77d8c367a929e00998fe1a/src/SIL.XForge.Scripture/Services/MachineProjectService.cs#L574)):*
<details><summary><i>Previously, pmachapman (Peter Chapman) wrote…</i></summary><blockquote>

No, as these two Boolean values will only be true when pre-translating. The only other place it needed to be checked was the logic that deletes a secondary corpus if it is present (line 741), and just one source is used; and the additional training data section. (line 821).
</blockquote></details>

So in places like `MachineApiService.cs::StartPreTranslationBuildAsync:785` we can assume the pretranslation setting as that is the purpose of this API request?

**Review by pmachapman — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/2407)* status: all files reviewed, 2 unresolved discussions (waiting on @Nateowami and @nigel-wells)

___
*[`src/SIL.XForge.Scripture/Services/MachineProjectService.cs` line 574 at r3](https://reviewable.io/reviews/sillsdev/web-xforge/2407#-NvFWV58A35C-rT7cdNN:-NvcsTXj7yRYWq5dRps2:b-gtak4w) ([raw file](https://github.com/sillsdev/web-xforge/blob/a659ca969be32d013b77d8c367a929e00998fe1a/src/SIL.XForge.Scripture/Services/MachineProjectService.cs#L574)):*
<details><summary><i>Previously, nigel-wells (Nigel Wells) wrote…</i></summary><blockquote>

So in places like `MachineApiService.cs::StartPreTranslationBuildAsync:785` we can assume the pretranslation setting as that is the purpose of this API request?
</blockquote></details>

Yes - this method will only be used for pre-translation, and sets `preTranslate` to `true` for the call to `MachineProjectService.BuildProjectForBackgroundJobAsync()`.

**Review by nigel-wells — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/2407#-:-NveAZbc7LOaKO-zdoTG:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @Nateowami)

___
*[`src/SIL.XForge.Scripture/Services/MachineProjectService.cs` line 574 at r3](https://reviewable.io/reviews/sillsdev/web-xforge/2407#-NvFWV58A35C-rT7cdNN:-NveAW8v8YXkDrIIDGgp:bdfi23i) ([raw file](https://github.com/sillsdev/web-xforge/blob/a659ca969be32d013b77d8c367a929e00998fe1a/src/SIL.XForge.Scripture/Services/MachineProjectService.cs#L574)):*
<details><summary><i>Previously, pmachapman (Peter Chapman) wrote…</i></summary><blockquote>

Yes - this method will only be used for pre-translation, and sets `preTranslate` to `true` for the call to `MachineProjectService.BuildProjectForBackgroundJobAsync()`.
</blockquote></details>

Thanks for confirming - happy for this to move along to the testers.

**Pull request merged**
