### PR TITLE
SF-2027 Update checking overview to display chapters with scripture audio

### PR DESCRIPTION
**Pull request by nigel-wells**
- Moved book archive into an ellipse menu
- Added edit/delete audio to the menu
- Display audio icon in the panel chapter

**Note:** Editing will need to be added after SF-2026 is merged

image

- - -
This change is [Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1992)

### CODE REVIEW

**Comment by Nateowami** [comment]
@nigel-wells FYI, for the sake of brevity, I like to omit the ` - ` from the commit message. Usually there's space for it, but for many commits it's difficult to squeeze a commit message into a reasonable size, so any extra characters are to be avoided. And then for consistency, I just leave it out of all commit messages.

**Comment by Nateowami** [comment]
@nigel-wells The titles of SF-2026 and SF-2027 are virtually identical. The changes introduced in this PR are not what I expected from the title. Even looking at the descriptions I can't tell how they differ.

**Review by josephmyers — CHANGES_REQUESTED** [review]
This looks really good. Couple minor comments

> Reviewed 5 of 5 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1992#-:-NbJHiT3EYyOuxbmABdf:b-n4n04c)* status: all files reviewed, 2 unresolved discussions (waiting on @nigel-wells)

___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking-overview/checking-overview.component.html` line 43 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/1992#-NbJIsps3U1IQSLU3Qs4:-NbJIsps3U1IQSLU3Qs5:bn468np) ([raw file](https://github.com/sillsdev/web-xforge/blob/38463bb8b576c085d1f6573d8f164eb4df4c1513/src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking-overview/checking-overview.component.html#L43)):*
> ```HTML
>             <span fxFlex>{{ getBookName(text) }}</span>
>             <span fxFlex="110px" fxShow fxHide.xs fxLayoutAlign="end center" class="questions-count">
>               {{ questionCountLabel(bookQuestionCount(text)) }}
> ```

What do you think about showing "0 questions" for books with audio and no questions? To me, it looks a little funny without it.
___
*[`src/SIL.XForge.Scripture/ClientApp/src/assets/i18n/non_checking_en.json` line 30 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/1992#-NbJJ5Ey7RrM_dX4-s5C:-NbJJ5Ey7RrM_dX4-s5D:b5ru1j2) ([raw file](https://github.com/sillsdev/web-xforge/blob/38463bb8b576c085d1f6573d8f164eb4df4c1513/src/SIL.XForge.Scripture/ClientApp/src/assets/i18n/non_checking_en.json#L30)):*
> ```JSON
>     "confirm_bulk_archive": "Are you sure you want to archive all the questions in {{ scope }}?",
>     "confirm_bulk_republish": "Are you sure you want to republish all the questions in {{ scope }}?",
>     "confirm_delete_chapter_audio": "Are you sure you want to delete chapter audio and timing data for {{ book }} chapter {{ chapter }}?",
> ```

Can we remove the word "chapter" here?

**Review by nigel-wells — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1992)* status: 3 of 5 files reviewed, 2 unresolved discussions (waiting on @josephmyers)

___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking-overview/checking-overview.component.html` line 43 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/1992#-NbJIsps3U1IQSLU3Qs4:-NbSF_sUAUCmt4UzMoeT:b-wf4xim) ([raw file](https://github.com/sillsdev/web-xforge/blob/38463bb8b576c085d1f6573d8f164eb4df4c1513/src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking-overview/checking-overview.component.html#L43)):*
<details><summary><i>Previously, josephmyers wrote…</i></summary><blockquote>

What do you think about showing "0 questions" for books with audio and no questions? To me, it looks a little funny without it.
</blockquote></details>

Yep, that works.
___
*[`src/SIL.XForge.Scripture/ClientApp/src/assets/i18n/non_checking_en.json` line 30 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/1992#-NbJJ5Ey7RrM_dX4-s5C:-NbSE1Uo8r1lMfAvuCNl:b-896fix) ([raw file](https://github.com/sillsdev/web-xforge/blob/38463bb8b576c085d1f6573d8f164eb4df4c1513/src/SIL.XForge.Scripture/ClientApp/src/assets/i18n/non_checking_en.json#L30)):*
<details><summary><i>Previously, josephmyers wrote…</i></summary><blockquote>

Can we remove the word "chapter" here?
</blockquote></details>

Done.

**Review by josephmyers — APPROVED** [review]
> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1992)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @nigel-wells)

**Pull request merged**
