### PR TITLE
SF-1226 Allow deleting inactive source projects

### PR DESCRIPTION
**Pull request by RaymondLuong3**
* Source projects referenced but inactive can be deleted
* Delete reference from projects when an inactive source project is deleted
* Remove unreliable form validation from settings page since runtime
 form validation causes endless recursion if we correctly call
 updateValueAndValidity on the form

---
This change is [Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/990)

### CODE REVIEW

**Review by irahopkinson — CHANGES_REQUESTED** [review]
Thanks for your work on this. A couple of issues to work through.

> Reviewed 7 of 8 files at r1.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/990#-:-MWTDnzj7aQwQreCzC46:bzfs32j)* status: 7 of 8 files reviewed, 4 unresolved discussions (waiting on @RaymondLuong3)

___
*[src/SIL.XForge.Scripture/ClientApp/src/app/settings/settings.component.ts, line 166 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/990#-MWTD3qm4Sv4-1VkwXbr:-MWTD3qm4Sv4-1VkwXbs:b-ytyf0) ([raw file](https://github.com/sillsdev/web-xforge/blob/41a5f945766d518d7bf5267a00e7d9a208f9f2cf/src/SIL.XForge.Scripture/ClientApp/src/app/settings/settings.component.ts#L166)):*
> ```
> onFormValueChanges
> ```
I'm not sure if the problem is in here but possible given all the changes. If I add 2 projects and then make one based on the other it shows I can't delete the source project. Good so far. However, if I then disable suggestions in the target I still can't delete the source when I should now be able to.
___
*[src/SIL.XForge.Scripture/ClientApp/src/app/settings/settings.component.ts, line 260 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/990#-MWT1VCPBI23FIzswlze:-MWT1VCPBI23FIzswlzf:b-p7lpix) ([raw file](https://github.com/sillsdev/web-xforge/blob/41a5f945766d518d7bf5267a00e7d9a208f9f2cf/src/SIL.XForge.Scripture/ClientApp/src/app/settings/settings.component.ts#L260)):*
> ```
> && sourceProjectExists
> ```
Checking this here doesn't fix the underlying issue that the project still has a reference to a source that no longer exists. See my comment below for `SFProjectService.cs`.
___
*[src/SIL.XForge.Scripture/ClientApp/src/app/settings/settings.component.spec.ts, line 324 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/990#-MWSyM7R5FRH-bp6lf1W:-MWSyM7R5FRH-bp6lf1X:bauzgp0) ([raw file](https://github.com/sillsdev/web-xforge/blob/41a5f945766d518d7bf5267a00e7d9a208f9f2cf/src/SIL.XForge.Scripture/ClientApp/src/app/settings/settings.component.spec.ts#L324)):*
> ```
> component.form.get('sourceParatextId')!.value
> ```
This should be a property of `env`.
___
*[src/SIL.XForge.Scripture/Services/SFProjectService.cs, line 510 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/990#-MWSzLGi91plV8T_86Mp:-MWSzLGi91plV8T_86Mq:b8pea7y) ([raw file](https://github.com/sillsdev/web-xforge/blob/41a5f945766d518d7bf5267a00e7d9a208f9f2cf/src/SIL.XForge.Scripture/Services/SFProjectService.cs#L510)):*
> ```
> bool includeInactive
> ```
This feels like you are working harder than you need to. Wouldn't it be better that when a project is deleted it ensures all references to itself are removed then? Are you sure its not already doing that?

**Review by RaymondLuong3 — COMMENTED** [review]
I have tested the project deletion and it should be good now. Thanks for the suggestion to delete references to a source project when the source is deleted. It is much cleaner. For some reason reviewable isn't showing the comments that I see in the github discussion, but I think I have address the issues you pointed out.

> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/990#-:-MWaKMKk0ZJ_qncmtend:bkurznw)* status: 0 of 4 files reviewed, all discussions resolved

**Review by irahopkinson — CHANGES_REQUESTED** [review]
> Reviewed 7 of 8 files at r1.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/990)* status: 1 of 4 files reviewed, 4 unresolved discussions (waiting on @irahopkinson and @RaymondLuong3)

**Review by irahopkinson — CHANGES_REQUESTED** [review]
Its functionally good now. Just 2 refactors to cleanup code.

> Reviewed 4 of 7 files at r2.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/990#-:-MWcY-v-3cXFPS4vpPUD:bajwzrt)* status: all files reviewed, 2 unresolved discussions (waiting on @RaymondLuong3)

___
*[src/SIL.XForge.Scripture/ClientApp/src/app/settings/settings.component.ts, line 166 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/990#-MWTD3qm4Sv4-1VkwXbr:-MWcXiAW-kxHKa5XqMIi:bb6un1j) ([raw file](https://github.com/sillsdev/web-xforge/blob/41a5f945766d518d7bf5267a00e7d9a208f9f2cf/src/SIL.XForge.Scripture/ClientApp/src/app/settings/settings.component.ts#L166)):*
<details><summary><i>Previously, irahopkinson (Ira Hopkinson) wrote…</i></summary><blockquote>

> ```
> onFormValueChanges
> ```
I'm not sure if the problem is in here but possible given all the changes. If I add 2 projects and then make one based on the other it shows I can't delete the source project. Good so far. However, if I then disable suggestions in the target I still can't delete the source when I should now be able to.
</blockquote></details>

Done
___
*[src/SIL.XForge.Scripture/ClientApp/src/app/settings/settings.component.ts, line 260 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/990#-MWT1VCPBI23FIzswlze:-MWcTcnw3sEZgyTukIPE:bb6un1j) ([raw file](https://github.com/sillsdev/web-xforge/blob/41a5f945766d518d7bf5267a00e7d9a208f9f2cf/src/SIL.XForge.Scripture/ClientApp/src/app/settings/settings.component.ts#L260)):*
<details><summary><i>Previously, irahopkinson (Ira Hopkinson) wrote…</i></summary><blockquote>

> ```
> && sourceProjectExists
> ```
Checking this here doesn't fix the underlying issue that the project still has a reference to a source that no longer exists. See my comment below for `SFProjectService.cs`.
</blockquote></details>

Done
___
*[src/SIL.XForge.Scripture/Services/SFProjectService.cs, line 510 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/990#-MWSzLGi91plV8T_86Mp:-MWcTXns4jHjAQzitxVv:bb6un1j) ([raw file](https://github.com/sillsdev/web-xforge/blob/41a5f945766d518d7bf5267a00e7d9a208f9f2cf/src/SIL.XForge.Scripture/Services/SFProjectService.cs#L510)):*
<details><summary><i>Previously, irahopkinson (Ira Hopkinson) wrote…</i></summary><blockquote>

> ```
> bool includeInactive
> ```
This feels like you are working harder than you need to. Wouldn't it be better that when a project is deleted it ensures all references to itself are removed then? Are you sure its not already doing that?
</blockquote></details>

Done
___
*[src/SIL.XForge.Scripture/Services/SFProjectService.cs, line 521 at r2](https://reviewable.io/reviews/sillsdev/web-xforge/990#-MWcSH4i-qZz5CIUGj__:-MWcSH4i-qZz5CIUGj_a:b-xzs7i9) ([raw file](https://github.com/sillsdev/web-xforge/blob/38d1e5fd9d6ac95932f43d7f883e4b76b1b4566f/src/SIL.XForge.Scripture/Services/SFProjectService.cs#L521)):*
> ```
> GetProjectWithReferenceToSource(projectId, false).Length > 0
> ```
See my comment below about this method. Here you don't even need the list of projects - just that any exist. I'd put the original code back but remember to add the `p.TranslateConfig.TranslationSuggestionsEnabled` check.
___
*[src/SIL.XForge.Scripture/Services/SFProjectService.cs, line 759 at r2](https://reviewable.io/reviews/sillsdev/web-xforge/990#-MWcRpkl3ZujlBnGFCQn:-MWcRpkl3ZujlBnGFCQo:b6c8rt5) ([raw file](https://github.com/sillsdev/web-xforge/blob/38d1e5fd9d6ac95932f43d7f883e4b76b1b4566f/src/SIL.XForge.Scripture/Services/SFProjectService.cs#L759)):*
> ```
> GetProjectWithReferenceToSource
> ```
This method is doing 2 distinct tasks that don't need to be in the same method and make it harder to understand the method. Just use this for the list of projects in `DeleteProjectAsync`.

**Review by irahopkinson — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/990)* status: all files reviewed, 2 unresolved discussions (waiting on @RaymondLuong3)

___
*[src/SIL.XForge.Scripture/ClientApp/src/app/settings/settings.component.spec.ts, line 324 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/990#-MWSyM7R5FRH-bp6lf1W:-MWcYGZ68XcUBC0oRd_I:ba3dfob) ([raw file](https://github.com/sillsdev/web-xforge/blob/41a5f945766d518d7bf5267a00e7d9a208f9f2cf/src/SIL.XForge.Scripture/ClientApp/src/app/settings/settings.component.spec.ts#L324)):*
<details><summary><i>Previously, irahopkinson (Ira Hopkinson) wrote…</i></summary><blockquote>

> ```
> component.form.get('sourceParatextId')!.value
> ```
This should be a property of `env`.
</blockquote></details>

Removed

**Review by RaymondLuong3 — COMMENTED** [review]
I'm glad it works now and that it was relatively minor to delete references to source projects.

> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/990#-:-MWdtw1L8bLmW0HNQBtB:b-zcjddl)* status: 3 of 4 files reviewed, 2 unresolved discussions (waiting on @irahopkinson)

___
*[src/SIL.XForge.Scripture/Services/SFProjectService.cs, line 521 at r2](https://reviewable.io/reviews/sillsdev/web-xforge/990#-MWcSH4i-qZz5CIUGj__:-MWdtuyk6e1ChO-5GRWs:b-896fix) ([raw file](https://github.com/sillsdev/web-xforge/blob/38d1e5fd9d6ac95932f43d7f883e4b76b1b4566f/src/SIL.XForge.Scripture/Services/SFProjectService.cs#L521)):*
<details><summary><i>Previously, irahopkinson (Ira Hopkinson) wrote…</i></summary><blockquote>

> ```
> GetProjectWithReferenceToSource(projectId, false).Length > 0
> ```
See my comment below about this method. Here you don't even need the list of projects - just that any exist. I'd put the original code back but remember to add the `p.TranslateConfig.TranslationSuggestionsEnabled` check.
</blockquote></details>

Done.
___
*[src/SIL.XForge.Scripture/Services/SFProjectService.cs, line 759 at r2](https://reviewable.io/reviews/sillsdev/web-xforge/990#-MWcRpkl3ZujlBnGFCQn:-MWdtuBJ4yKgt8LK9EiB:b-896fix) ([raw file](https://github.com/sillsdev/web-xforge/blob/38d1e5fd9d6ac95932f43d7f883e4b76b1b4566f/src/SIL.XForge.Scripture/Services/SFProjectService.cs#L759)):*
<details><summary><i>Previously, irahopkinson (Ira Hopkinson) wrote…</i></summary><blockquote>

> ```
> GetProjectWithReferenceToSource
> ```
This method is doing 2 distinct tasks that don't need to be in the same method and make it harder to understand the method. Just use this for the list of projects in `DeleteProjectAsync`.
</blockquote></details>

Done.

**Pull request merged**
