### PR TITLE
Show conflict note icon and note on blank segments

### PR DESCRIPTION
**Pull request by RaymondLuong3**
- Notes on blank segments will now appear
- show notes attached related segments in poetry
- Specifically handle conflict notes by setting the icon on the thread

image

---
This change is [Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1041)

### CODE REVIEW

**Comment by marksvc** [comment]
:eyes:

**Review by marksvc — CHANGES_REQUESTED** [review]
Thanks for your work on this.

> Reviewed 5 of 5 files at r1.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1041#-:-Ma4ktDv7HUTCH2lvNvx:b7tt6m2)* status: all files reviewed, 8 unresolved discussions (waiting on @RaymondLuong3)

___
*[src/SIL.XForge.Scripture/ClientApp/src/app/shared/text/text.component.ts, line 480 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/1041#-Ma4aU1bDq_s-5KQ0eu5:-Ma4aU1bDq_s-5KQ0eu6:b-8lom6u) ([raw file](https://github.com/sillsdev/web-xforge/blob/4623030134eac1f93b5e08dee64bc7c54f629954/src/SIL.XForge.Scripture/ClientApp/src/app/shared/text/text.component.ts#L480)):*
> ```XML
>   }
> 
>   toggleInlineFormat(verseRef: VerseRef, selectedText: string, formatName: string, format: any): void {
> ```

There's loops, and if's, and empty strings, and failures to match, and math, and the earlier change on what to do if `text !== ''`. It's a good time for unit tests, but I won't ask for that to be squeezed into your day today. :)
___
*[src/SIL.XForge.Scripture/ClientApp/src/app/shared/text/text.component.ts, line 500 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/1041#-Ma4Yodc9csSxV6gO2QV:-Ma4Yodc9csSxV6gO2QW:b-85u6lg) ([raw file](https://github.com/sillsdev/web-xforge/blob/4623030134eac1f93b5e08dee64bc7c54f629954/src/SIL.XForge.Scripture/ClientApp/src/app/shared/text/text.component.ts#L500)):*
> ```XML
>         }
>       } else {
>         const start = text.indexOf(selectedText);
> ```

BTW I observe in the javascript console that "some string".indexOf('') returns 0. 
___
*[src/SIL.XForge.Scripture/ClientApp/src/app/shared/text/text.component.ts, line 512 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/1041#-Ma4_8106Gc-Lrq7mxEH:-Ma4_8106Gc-Lrq7mxEI:b-82pi63) ([raw file](https://github.com/sillsdev/web-xforge/blob/4623030134eac1f93b5e08dee64bc7c54f629954/src/SIL.XForge.Scripture/ClientApp/src/app/shared/text/text.component.ts#L512)):*
> ```XML
> 
>     if (noteRange == null) {
>       return;
> ```

If the selectedText is not in the verse at all, perhaps we should just set start=0 and put the note at the beginning? Or what's the thinking behind just returning? Maybe it's a program error or data inconsistency that this situation would happen?
___
*[src/SIL.XForge.Scripture/ClientApp/src/app/shared/text/text.component.ts, line 515 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/1041#-Ma4_dJK4aWXpeGYOn3D:-Ma4_dJK4aWXpeGYOn3E:b4cem4e) ([raw file](https://github.com/sillsdev/web-xforge/blob/4623030134eac1f93b5e08dee64bc7c54f629954/src/SIL.XForge.Scripture/ClientApp/src/app/shared/text/text.component.ts#L515)):*
> ```
> selectedText?
> ```

It doesn't look like this can be null, as it's passed in as just `string`.  Maybe you instead here would want to do the following perhaps?

```js
= selectedText.length > 0 ? selectedText.length : 1;
```

(Or similar. minimum(.., ..).)

I see in the next line you account for similar, so you can probably collapse these together into one.
___
*[src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.ts, line 482 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/1041#-Ma4dN3L3wRMjFnlkRXp:-Ma4dN3L3wRMjFnlkRXq:bfi6zko) ([raw file](https://github.com/sillsdev/web-xforge/blob/4623030134eac1f93b5e08dee64bc7c54f629954/src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.ts#L482)):*
> ```XML
>         }
> 
>         // reset note icon was blank or is newly blank
> ```

I am having trouble understanding this comment. Maybe you mean, "Toggle the note icon display on and off, to get it to show, if the verse (segment?) was blank or is newly blank."  ?
___
*[src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.ts, line 486 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/1041#-Ma4cDAW7qbDX_RN1ekU:-Ma4cDAW7qbDX_RN1ekV:bj3ly29) ([raw file](https://github.com/sillsdev/web-xforge/blob/4623030134eac1f93b5e08dee64bc7c54f629954/src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.ts#L486)):*
> ```
>   this.bookNum === n.data.verseRef.bookNum &&
> ```

It looks like the verseSlug will contain the chapter number. Does this bookNum check help us in addition to that? 
___
*[src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.ts, line 489 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/1041#-Ma4cXrY-iMBoeuUeYc_:-Ma4cXrY-iMBoeuUeYca:b-wc9j91) ([raw file](https://github.com/sillsdev/web-xforge/blob/4623030134eac1f93b5e08dee64bc7c54f629954/src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.ts#L489)):*
> ```
> threadDocs[0];
> ```

Why are you grabbing the 0th thread doc and working with that? What about the other ones?
___
*[src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.ts, line 494 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/1041#-Ma4d5BW6zDLlcWU9m3R:-Ma4d5BW6zDLlcWU9m3S:b-ks12d7) ([raw file](https://github.com/sillsdev/web-xforge/blob/4623030134eac1f93b5e08dee64bc7c54f629954/src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.ts#L494)):*
> ```XML
>           if (
>             segment?.range.length === 1 &&
>             delta.ops[0].retain === segment?.range.index &&
> ```

I'll ask you about this in chat.
___
*[src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.ts, line 497 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/1041#-Ma4d8cM4P_mXgI2VsRZ:-Ma4d8cM4P_mXgI2VsR_:b3o3wzv) ([raw file](https://github.com/sillsdev/web-xforge/blob/4623030134eac1f93b5e08dee64bc7c54f629954/src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.ts#L497)):*
> ```XML
>             (delta.ops[1].insert != null || delta.ops[1].delete != null)
>           ) {
>             this.toggleNoteThreadVerses(false);
> ```

Let's make a comment about what we're doing and why here.
___
*[src/SIL.XForge.Scripture/Services/ParatextService.cs, line 1101 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/1041#-Ma4I2WrAMtXwRAoT59V:-Ma4I2WsEwDw75-A1Chg:b-pimn4c) ([raw file](https://github.com/sillsdev/web-xforge/blob/4623030134eac1f93b5e08dee64bc7c54f629954/src/SIL.XForge.Scripture/Services/ParatextService.cs#L1101)):*
> ```Smalltalk
>         {
>             CommentTag tag = comment.TagsAdded == null || comment.TagsAdded.Length == 0
>                 ? comment.Type == NoteType.Conflict ? CommentTag.ConflictTag : null
> ```

Let's introduce some parentheses or use `if`s to make this more clear, rather than nesting the ternaries within one another without parens.

**Review by RaymondLuong3 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1041)* status: 2 of 5 files reviewed, 8 unresolved discussions (waiting on @marksvc)

___
*[src/SIL.XForge.Scripture/ClientApp/src/app/shared/text/text.component.ts, line 480 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/1041#-Ma4aU1bDq_s-5KQ0eu5:-Ma57ofd7iSamc3FIqDv:b-pu7iqe) ([raw file](https://github.com/sillsdev/web-xforge/blob/4623030134eac1f93b5e08dee64bc7c54f629954/src/SIL.XForge.Scripture/ClientApp/src/app/shared/text/text.component.ts#L480)):*
<details><summary><i>Previously, marksvc wrote…</i></summary><blockquote>

There's loops, and if's, and empty strings, and failures to match, and math, and the earlier change on what to do if `text !== ''`. It's a good time for unit tests, but I won't ask for that to be squeezed into your day today. :)
</blockquote></details>

There are 3 scenarios in the loop. The first is not expected, but just covers the case that a range is null. The second covers the case that a blank segment should be used as the segment for a note without selected text. The third covers the case where selected text is found in the segment text. Scenario two and three are unit tested. If none of this is matched, then default to put the note at the beginning of the verse.
___
*[src/SIL.XForge.Scripture/ClientApp/src/app/shared/text/text.component.ts, line 500 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/1041#-Ma4Yodc9csSxV6gO2QV:-Ma58cKz83RfhDHd9d-J:bdbwltg) ([raw file](https://github.com/sillsdev/web-xforge/blob/4623030134eac1f93b5e08dee64bc7c54f629954/src/SIL.XForge.Scripture/ClientApp/src/app/shared/text/text.component.ts#L500)):*
<details><summary><i>Previously, marksvc wrote…</i></summary><blockquote>

BTW I observe in the javascript console that "some string".indexOf('') returns 0. 
</blockquote></details>

Strange, I did a search and couldn't find that print statement in the code.
___
*[src/SIL.XForge.Scripture/ClientApp/src/app/shared/text/text.component.ts, line 512 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/1041#-Ma4_8106Gc-Lrq7mxEH:-Ma58pMU6ibrTfYcI7KB:b2mh80g) ([raw file](https://github.com/sillsdev/web-xforge/blob/4623030134eac1f93b5e08dee64bc7c54f629954/src/SIL.XForge.Scripture/ClientApp/src/app/shared/text/text.component.ts#L512)):*
<details><summary><i>Previously, marksvc wrote…</i></summary><blockquote>

If the selectedText is not in the verse at all, perhaps we should just set start=0 and put the note at the beginning? Or what's the thinking behind just returning? Maybe it's a program error or data inconsistency that this situation would happen?
</blockquote></details>

If a range is not found, then we have nowhere to put the note. This is not expected to happen, it's just we have to acknowledge that getSegmentRange can return undefined.
___
*[src/SIL.XForge.Scripture/ClientApp/src/app/shared/text/text.component.ts, line 515 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/1041#-Ma4_dJK4aWXpeGYOn3D:-Ma59F3P3E5P2IfBxGbf:bbvvsky) ([raw file](https://github.com/sillsdev/web-xforge/blob/4623030134eac1f93b5e08dee64bc7c54f629954/src/SIL.XForge.Scripture/ClientApp/src/app/shared/text/text.component.ts#L515)):*
<details><summary><i>Previously, marksvc wrote…</i></summary><blockquote>

> ```
> selectedText?
> ```

It doesn't look like this can be null, as it's passed in as just `string`.  Maybe you instead here would want to do the following perhaps?

```js
= selectedText.length > 0 ? selectedText.length : 1;
```

(Or similar. minimum(.., ..).)

I see in the next line you account for similar, so you can probably collapse these together into one.
</blockquote></details>

I've made some changes to simplify this.
___
*[src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.ts, line 482 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/1041#-Ma4dN3L3wRMjFnlkRXp:-Ma59Hs9EaaDA9fBQMgW:bv4kgw7) ([raw file](https://github.com/sillsdev/web-xforge/blob/4623030134eac1f93b5e08dee64bc7c54f629954/src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.ts#L482)):*
<details><summary><i>Previously, marksvc wrote…</i></summary><blockquote>

I am having trouble understanding this comment. Maybe you mean, "Toggle the note icon display on and off, to get it to show, if the verse (segment?) was blank or is newly blank."  ?
</blockquote></details>

I moved the comment.
___
*[src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.ts, line 486 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/1041#-Ma4cDAW7qbDX_RN1ekU:-Ma59QLP9ZY5-WzG_wuB:b-c3ozjs) ([raw file](https://github.com/sillsdev/web-xforge/blob/4623030134eac1f93b5e08dee64bc7c54f629954/src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.ts#L486)):*
<details><summary><i>Previously, marksvc wrote…</i></summary><blockquote>

> ```
>   this.bookNum === n.data.verseRef.bookNum &&
> ```

It looks like the verseSlug will contain the chapter number. Does this bookNum check help us in addition to that? 
</blockquote></details>

Yea, a segment doesn't contain information about which book it belongs to. So to filter for notes in this specific book, that needs to be explicit.
___
*[src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.ts, line 489 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/1041#-Ma4cXrY-iMBoeuUeYc_:-Ma59ib731TOp0TZz-N8:b-qvelso) ([raw file](https://github.com/sillsdev/web-xforge/blob/4623030134eac1f93b5e08dee64bc7c54f629954/src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.ts#L489)):*
<details><summary><i>Previously, marksvc wrote…</i></summary><blockquote>

> ```
> threadDocs[0];
> ```

Why are you grabbing the 0th thread doc and working with that? What about the other ones?
</blockquote></details>

I've updated the logic so I hope it is more clear now.
___
*[src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.ts, line 494 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/1041#-Ma4d5BW6zDLlcWU9m3R:-Ma59tTi08C248ePNgEz:b3jlf0l) ([raw file](https://github.com/sillsdev/web-xforge/blob/4623030134eac1f93b5e08dee64bc7c54f629954/src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.ts#L494)):*
<details><summary><i>Previously, marksvc wrote…</i></summary><blockquote>

I'll ask you about this in chat.
</blockquote></details>

We only want to recalculate notes for display when a blank segment with a note is edited.
___
*[src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.ts, line 497 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/1041#-Ma4d8cM4P_mXgI2VsRZ:-Ma5A53e59ApTsirGw-H:b-896fix) ([raw file](https://github.com/sillsdev/web-xforge/blob/4623030134eac1f93b5e08dee64bc7c54f629954/src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.ts#L497)):*
<details><summary><i>Previously, marksvc wrote…</i></summary><blockquote>

Let's make a comment about what we're doing and why here.
</blockquote></details>

Done.
___
*[src/SIL.XForge.Scripture/Services/ParatextService.cs, line 1101 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/1041#-Ma4I2WrAMtXwRAoT59V:-Ma5A5ybBIIZ9dFCns0w:b-896fix) ([raw file](https://github.com/sillsdev/web-xforge/blob/4623030134eac1f93b5e08dee64bc7c54f629954/src/SIL.XForge.Scripture/Services/ParatextService.cs#L1101)):*
<details><summary><i>Previously, marksvc wrote…</i></summary><blockquote>

Let's introduce some parentheses or use `if`s to make this more clear, rather than nesting the ternaries within one another without parens.
</blockquote></details>

Done.

**Review by marksvc — APPROVED** [review]
> Reviewed 3 of 3 files at r2.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1041)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @RaymondLuong3)

___
*[src/SIL.XForge.Scripture/ClientApp/src/app/shared/text/text.component.ts, line 500 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/1041#-Ma4Yodc9csSxV6gO2QV:-Ma5QrFXAkPOEuXhojh6:bnmgcxz) ([raw file](https://github.com/sillsdev/web-xforge/blob/4623030134eac1f93b5e08dee64bc7c54f629954/src/SIL.XForge.Scripture/ClientApp/src/app/shared/text/text.component.ts#L500)):*
<details><summary><i>Previously, RaymondLuong3 (Raymond Luong) wrote…</i></summary><blockquote>

Strange, I did a search and couldn't find that print statement in the code.
</blockquote></details>

Oh no, I'm sorry :). When I was looking at this earlier I was wondering, "Well what will be the output of indexOf() if the argument is the empty string?", and I found that the answer is 0, which seems like a good thing to happen here. So I was just saying. 
But I see now that we won't actually encounter that here anyway, since `if (selectedText === '')` is handled just above this block.
___
*[src/SIL.XForge.Scripture/ClientApp/src/app/shared/text/text.component.ts, line 512 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/1041#-Ma4_8106Gc-Lrq7mxEH:-Ma5RnkY49kaIHA-MEFC:bspl6fg) ([raw file](https://github.com/sillsdev/web-xforge/blob/4623030134eac1f93b5e08dee64bc7c54f629954/src/SIL.XForge.Scripture/ClientApp/src/app/shared/text/text.component.ts#L512)):*
<details><summary><i>Previously, RaymondLuong3 (Raymond Luong) wrote…</i></summary><blockquote>

If a range is not found, then we have nowhere to put the note. This is not expected to happen, it's just we have to acknowledge that getSegmentRange can return undefined.
</blockquote></details>

Hmm. Okay. I'm understanding it a bit more now on my second look.
___
*[src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.ts, line 489 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/1041#-Ma4cXrY-iMBoeuUeYc_:-Ma5Tu8vAqzu-kaDydDv:b-lijbrj) ([raw file](https://github.com/sillsdev/web-xforge/blob/4623030134eac1f93b5e08dee64bc7c54f629954/src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.ts#L489)):*
<details><summary><i>Previously, RaymondLuong3 (Raymond Luong) wrote…</i></summary><blockquote>

I've updated the logic so I hope it is more clear now.
</blockquote></details>

Is this because threadDocs will never have length >1, and so you just grab the 0th item after doing the filter?
Or because the 0th item is the note, and items 1,2,3,etc are something else?
___
*[src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.ts, line 489 at r2](https://reviewable.io/reviews/sillsdev/web-xforge/1041#-Ma5Vx6e1CVBpxbrYvnp:-Ma5Vx6e1CVBpxbrYvnq:b-v9w2xs) ([raw file](https://github.com/sillsdev/web-xforge/blob/c4565f41eecf1d53e04bae3e66f2ccdb74f264ce/src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.ts#L489)):*
> ```
>  if (segmentHasNote) {
> ```

I like having the variable name used here, as that documents/explains what the meaning is of what is being examined.

**Review by RaymondLuong3 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1041)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @RaymondLuong3)

___
*[src/SIL.XForge.Scripture/ClientApp/src/app/shared/text/text.component.ts, line 500 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/1041#-Ma4Yodc9csSxV6gO2QV:-Mdd6EuzCE1EC5J0AtPe:b1kkhww) ([raw file](https://github.com/sillsdev/web-xforge/blob/4623030134eac1f93b5e08dee64bc7c54f629954/src/SIL.XForge.Scripture/ClientApp/src/app/shared/text/text.component.ts#L500)):*
<details><summary><i>Previously, marksvc wrote…</i></summary><blockquote>

Oh no, I'm sorry :). When I was looking at this earlier I was wondering, "Well what will be the output of indexOf() if the argument is the empty string?", and I found that the answer is 0, which seems like a good thing to happen here. So I was just saying. 
But I see now that we won't actually encounter that here anyway, since `if (selectedText === '')` is handled just above this block.
</blockquote></details>

That's right, we handle the specific case when the selected text is the empty string. In that case, we try to match a blank segment, and default to the start of the verse if no blank segments are found. This is only temporary until we begin to implement the better way of storing the location of a note.
___
*[src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.ts, line 489 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/1041#-Ma4cXrY-iMBoeuUeYc_:-Mdd7Nt-3zZynI0HQRvu:b-85gu97) ([raw file](https://github.com/sillsdev/web-xforge/blob/4623030134eac1f93b5e08dee64bc7c54f629954/src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.ts#L489)):*
<details><summary><i>Previously, marksvc wrote…</i></summary><blockquote>

Is this because threadDocs will never have length >1, and so you just grab the 0th item after doing the filter?
Or because the 0th item is the note, and items 1,2,3,etc are something else?
</blockquote></details>

Oh that is true. It's possible there is more than one thread doc for a given verse. I'll adjust it so we are checking that any of the docs in threadDocs is not null, then the segment has a note.

**Review by RaymondLuong3 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1041)* status: 4 of 5 files reviewed, all discussions resolved (waiting on @marksvc)

___
*[src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.ts, line 489 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/1041#-Ma4cXrY-iMBoeuUeYc_:-MddDHLL60vJD_mhNoBv:b-3lhj22) ([raw file](https://github.com/sillsdev/web-xforge/blob/4623030134eac1f93b5e08dee64bc7c54f629954/src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.ts#L489)):*
<details><summary><i>Previously, RaymondLuong3 (Raymond Luong) wrote…</i></summary><blockquote>

Oh that is true. It's possible there is more than one thread doc for a given verse. I'll adjust it so we are checking that any of the docs in threadDocs is not null, then the segment has a note.
</blockquote></details>

Oh, looks like checking that the data is not null is already done on the filter step. I removed referencing the 0th element since it is not necessary.

**Comment by irahopkinson** [comment]
@raymondluong3 Thanks for getting this merged. Its past time to update `develop` with `master` however master has moved so much it may be simpler to rebase develop rather than merge master into develop - up to you.

**Pull request merged**
