### PR TITLE
SF-2788 Reduce calls to the Paratext Registry

### PR DESCRIPTION
**Pull request by pmachapman**
This PR reduces calls to the Paratext Registry by combining:

 * `ParatextService.GetProjectRolesAsync()`
 * `ParatextService.GetParatextUsernameMappingAsync()`

Into `ParatextService.GetUsersAsync()`, and by passings the list of users from the Registry to `ParatextNotesMapper`, rather than having `ParatextNotesMapper` request the list of users from the Registry again.

I have also added a second commit that checks whether a project is registered, and if so, uses just that project's meta data and license to retrieve the repositories from the PT archives server.

- - -
This change is [Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/2529)

### CODE REVIEW

**Review by pmachapman — COMMENTED** [review]
> Dismissed @github-advanced-security[bot] from a discussion.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/2529)* status: 0 of 12 files reviewed, all discussions resolved (waiting on @github-advanced-security[bot])

**Review by nigel-wells — CHANGES_REQUESTED** [review]
Looks like I didn't push these comments through the other day when I hit issues trying to test. I'm pushing them now - still to finish further testing.

> Reviewed 9 of 12 files at r1, 1 of 3 files at r2, 4 of 4 files at r3, 7 of 7 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/2529#-:-O0qRQ1EChRZgobSln8J:bcxldey)* status: all files reviewed, 4 unresolved discussions (waiting on @pmachapman)

___
*[`src/SIL.XForge.Scripture/Services/JwtInternetSharedRepositorySource.cs` line 243 at r3](https://reviewable.io/reviews/sillsdev/web-xforge/2529#-O0g3pZC797ap6r-21vR:-O0g3pZC797ap6r-21vS:b-2dhka2) ([raw file](https://github.com/sillsdev/web-xforge/blob/88f1179fcb89944a7d6b66cc1d2f82f10ed36dc0/src/SIL.XForge.Scripture/Services/JwtInternetSharedRepositorySource.cs#L243)):*
> ```Smalltalk
>     }
> 
>     private JObject? GetJsonObject(string cgiCall)
> ```

Can the fetching, handling, and logging of this be merged with that in `JArray` above? Seems like they both doing the same thing and we just need to return something different so long as  nothing was thrown.
___
*[`src/SIL.XForge.Scripture/Services/ParatextService.cs` line 626 at r3](https://reviewable.io/reviews/sillsdev/web-xforge/2529#-O0g8_0MBa11K4Q1KNaq:-O0g8_0MBa11K4Q1KNar:ba9sa6b) ([raw file](https://github.com/sillsdev/web-xforge/blob/88f1179fcb89944a7d6b66cc1d2f82f10ed36dc0/src/SIL.XForge.Scripture/Services/ParatextService.cs#L626)):*
> ```Smalltalk
>         if (IsResource(project.ParatextId))
>         {
>             // Resources don't have project members or roles
> ```

nit  can we add a return here rather than having to read the rest of the code to see if something else of importance is going to happen.
___
*[`src/SIL.XForge.Scripture/Services/ParatextService.cs` line 647 at r3](https://reviewable.io/reviews/sillsdev/web-xforge/2529#-O0gBCPH-B1t4skzi3iW:-O0gBCPH-B1t4skzi3iX:bng9ch4) ([raw file](https://github.com/sillsdev/web-xforge/blob/9f48f1101f3729977251faa92818261b0f52f262/src/SIL.XForge.Scripture/Services/ParatextService.cs#L647)):*
> ```Smalltalk
>             );
> 
>             WarnIfNonuniqueValues(
> ```

Have you ruled out that this is no longer a possibility? I'm not really sure what scenario it was trying to log but it was done for a reason. Maybe it relates to our duplicate account issue when we do an automatic merge with Auth0 accounts which leaves redundant SF users but 2x PT IDs?
___
*[`test/SIL.XForge.Scripture.Tests/Services/ParatextNotesMapperTests.cs` line 337 at r3](https://reviewable.io/reviews/sillsdev/web-xforge/2529#-O0gEcjAEJWu3ppzHuvY:-O0gEcjAEJWu3ppzHuvZ:b-3rqox1) ([raw file](https://github.com/sillsdev/web-xforge/blob/88f1179fcb89944a7d6b66cc1d2f82f10ed36dc0/test/SIL.XForge.Scripture.Tests/Services/ParatextNotesMapperTests.cs#L337)):*
> ```Smalltalk
>         var env = new TestEnvironment();
>         env.SetParatextProjectRoles(false);
>         env.InitMapper(false, false);
> ```

Why no longer testing if this is `true`?

**Review by pmachapman — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/2529)* status: all files reviewed, 3 unresolved discussions (waiting on @nigel-wells)

___
*[`src/SIL.XForge.Scripture/Services/JwtInternetSharedRepositorySource.cs` line 243 at r3](https://reviewable.io/reviews/sillsdev/web-xforge/2529#-O0g3pZC797ap6r-21vR:-O0uddYF0gKDA0LWFBjM:bvrodpa) ([raw file](https://github.com/sillsdev/web-xforge/blob/88f1179fcb89944a7d6b66cc1d2f82f10ed36dc0/src/SIL.XForge.Scripture/Services/JwtInternetSharedRepositorySource.cs#L243)):*
<details><summary><i>Previously, nigel-wells (Nigel Wells) wrote…</i></summary><blockquote>

Can the fetching, handling, and logging of this be merged with that in `JArray` above? Seems like they both doing the same thing and we just need to return something different so long as  nothing was thrown.
</blockquote></details>

Done. Thank you for spotting that - I have made it a generic.
___
*[`src/SIL.XForge.Scripture/Services/ParatextService.cs` line 626 at r3](https://reviewable.io/reviews/sillsdev/web-xforge/2529#-O0g8_0MBa11K4Q1KNaq:-O0uhYAO4qWnrs8khoBt:b-usgxts) ([raw file](https://github.com/sillsdev/web-xforge/blob/88f1179fcb89944a7d6b66cc1d2f82f10ed36dc0/src/SIL.XForge.Scripture/Services/ParatextService.cs#L626)):*
<details><summary><i>Previously, nigel-wells (Nigel Wells) wrote…</i></summary><blockquote>

nit  can we add a return here rather than having to read the rest of the code to see if something else of importance is going to happen.
</blockquote></details>

Done. I have added a return at the end of each block of the `if...else` to prevent any potential future problems with logic added after the `if` block.
___
*[`src/SIL.XForge.Scripture/Services/ParatextService.cs` line 647 at r3](https://reviewable.io/reviews/sillsdev/web-xforge/2529#-O0gBCPH-B1t4skzi3iW:-O0uj7rxAGhy7jEHJVHA:b-ckz25t) ([raw file](https://github.com/sillsdev/web-xforge/blob/9f48f1101f3729977251faa92818261b0f52f262/src/SIL.XForge.Scripture/Services/ParatextService.cs#L647)):*
I checked the production database, and there were no occurrences of users with duplicate paratextIds. I also grepped the journal (since April), and the error is not present in the journal.

QA has two duplicate users, dating back to 2021, which should be removed (one of them is an account created by you). I will need your help to clean these up.

The code was added in 2022 - https://github.com/sillsdev/web-xforge/pull/1314. See the comment from Ira:

> I presume this is a temporary addition to find a specific issue and will be reverted once resolved.
___
*[`test/SIL.XForge.Scripture.Tests/Services/ParatextNotesMapperTests.cs` line 337 at r3](https://reviewable.io/reviews/sillsdev/web-xforge/2529#-O0gEcjAEJWu3ppzHuvY:-O0utGYx4ogqKJ8U-oJ3:b-w3wb31) ([raw file](https://github.com/sillsdev/web-xforge/blob/88f1179fcb89944a7d6b66cc1d2f82f10ed36dc0/test/SIL.XForge.Scripture.Tests/Services/ParatextNotesMapperTests.cs#L337)):*
<details><summary><i>Previously, nigel-wells (Nigel Wells) wrote…</i></summary><blockquote>

Why no longer testing if this is `true`?
</blockquote></details>

Because in the original test, it incorrectly relied on their being inconsistent output from the mock Paratext API to not map "user03" to "PT User 3". This was a test setup issue, and so when I corrected the mock registry to output consistent information, the test failed.

As the test is testing what happens when a Paratext user is not on the project, I updated the `twoPtUsersOnProject` argument for `InitMapper()` to be `false`, and so only "user01" is the only Paratext user.

**Review by nigel-wells — APPROVED** [review]
:lgtm:

> Reviewed 5 of 5 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/2529#-:-O0vJUXjCugzA6SVc29V:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @pmachapman)

___
*[`src/SIL.XForge.Scripture/Services/ParatextService.cs` line 647 at r3](https://reviewable.io/reviews/sillsdev/web-xforge/2529#-O0gBCPH-B1t4skzi3iW:-O0vIx7X-NF8f5FIgVQn:b-olgmsw) ([raw file](https://github.com/sillsdev/web-xforge/blob/9f48f1101f3729977251faa92818261b0f52f262/src/SIL.XForge.Scripture/Services/ParatextService.cs#L647)):*
<details><summary><i>Previously, pmachapman (Peter Chapman) wrote…</i></summary><blockquote>

I checked the production database, and there were no occurrences of users with duplicate paratextIds. I also grepped the journal (since April), and the error is not present in the journal.

QA has two duplicate users, dating back to 2021, which should be removed (one of them is an account created by you). I will need your help to clean these up.

The code was added in 2022 - https://github.com/sillsdev/web-xforge/pull/1314. See the comment from Ira:

> I presume this is a temporary addition to find a specific issue and will be reverted once resolved.
</blockquote></details>

Happy with this as discussed.

**Pull request merged**
