### PR TITLE
Sync: Allow projects to have their synchronization disabled

### PR DESCRIPTION
**Pull request by marksvc**
So, I don't really need to expose a backend API method of `GetSyncDisabled`, do I. But then, do I need `SetSyncDisabled`? I'm a bit foggy in remembering how this is supposed to work.

---
This change is [Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/804)

### CODE REVIEW

**Comment by marksvc** [comment]
I removed the GetSyncDisabled backend API and functionality. 
Is limiting setting syncDisabled adequately secured?

**Review by RaymondLuong3 — CHANGES_REQUESTED** [review]
Good work on this. And lots of tests added for this feature too. Just a couple blocking comments.

> Reviewed 17 of 17 files at r1.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/804#-:-MHMoc8g9q5kAegH4z4d:b-ol7xi8)* status: all files reviewed, 3 unresolved discussions (waiting on @marksvc)

___
*[src/SIL.XForge/Services/ProjectService.cs, line 144 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/804#-MHMh_6q7wc-27Qoeel3:-MHMh_6rCa9YxrSzTjPb:biz29aw) ([raw file](https://github.com/sillsdev/web-xforge/blob/ca26b0c148c5d41073b2f78d5abdd4f62535de9b/src/SIL.XForge/Services/ProjectService.cs#L144)):*
> ```
> if (systemRole != SystemRole.SystemAdmin)
> ```
Instead of passing in the role, this should check the role in the `User.Role`.
___
*[src/SIL.XForge.Scripture/ClientApp/src/assets/i18n/non_checking_en.json, line 166 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/804#-MHMlOLR5KCOEBoEbr4M:-MHMlOLS8o8hT3xlrEhj:b-ai6zyb) ([raw file](https://github.com/sillsdev/web-xforge/blob/ca26b0c148c5d41073b2f78d5abdd4f62535de9b/src/SIL.XForge.Scripture/ClientApp/src/assets/i18n/non_checking_en.json#L166)):*
> ```
> Scripture Forge web site administrators
> ```
It would be more useful to provide an email here.
___
*[src/SIL.XForge.Scripture/Services/SyncService.cs, line 29 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/804#-MHMo-0n76MaEnzfJpg8:-MHMo-0n76MaEnzfJpg9:bokolu0) ([raw file](https://github.com/sillsdev/web-xforge/blob/ca26b0c148c5d41073b2f78d5abdd4f62535de9b/src/SIL.XForge.Scripture/Services/SyncService.cs#L29)):*
<details><summary><i alt="summary">Quoted 4 lines of code…</i></summary>

> ```
> if (projectDoc.Data.SyncDisabled)
>                 {
>                     throw new ForbiddenException();
>                 }
> ```
</details>

That is smart to check this on the backend for the sync service.

**Review by marksvc — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/804)* status: all files reviewed, 2 unresolved discussions (waiting on @RaymondLuong3)

___
*[src/SIL.XForge/Services/ProjectService.cs, line 144 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/804#-MHMh_6q7wc-27Qoeel3:-MHNLs6G2VMTwd34dvZw:bhtc5c1) ([raw file](https://github.com/sillsdev/web-xforge/blob/ca26b0c148c5d41073b2f78d5abdd4f62535de9b/src/SIL.XForge/Services/ProjectService.cs#L144)):*
<details><summary><i>Previously, RaymondLuong3 (Raymond Luong) wrote…</i></summary><blockquote>

> ```
> if (systemRole != SystemRole.SystemAdmin)
> ```
Instead of passing in the role, this should check the role in the `User.Role`.
</blockquote></details>

Let's chat more about this. This follows the pattern of other SystemAdmin checks in both ProjectService.cs  and in UserService.cs. And also significant is the difference between a user's SF SystemRole and a project role; here I want to check that the user has a SF site SystemRole. Let's connect in chat and you can explain some more of what you mean, if you still think it should be changed.
___
*[src/SIL.XForge.Scripture/ClientApp/src/assets/i18n/non_checking_en.json, line 166 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/804#-MHMlOLR5KCOEBoEbr4M:-MHNNWTn2V6f82sa1jKN:b-l549tz) ([raw file](https://github.com/sillsdev/web-xforge/blob/ca26b0c148c5d41073b2f78d5abdd4f62535de9b/src/SIL.XForge.Scripture/ClientApp/src/assets/i18n/non_checking_en.json#L166)):*
<details><summary><i>Previously, RaymondLuong3 (Raymond Luong) wrote…</i></summary><blockquote>

> ```
> Scripture Forge web site administrators
> ```
It would be more useful to provide an email here.
</blockquote></details>

Done. Tho I'm not certain this is the best email address to use. The page at https://help.scriptureforge.org/en/Overview/Get_More_Help.htm says that email to the issues email address is publicly visible.

**Review by marksvc — COMMENTED** [review]
I tried cherry-picking this commit to master. It applied cleanly. Setting syncDisabled works well and stops the Synchronization button. 

> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/804#-:-MHNS_xfASrFKuA1k3AE:bf1xtev)* status: 16 of 17 files reviewed, 2 unresolved discussions (waiting on @RaymondLuong3)

**Review by RaymondLuong3 — APPROVED** [review]
This looks all good now. Thanks for the work.

> Reviewed 2 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/804#-:-MHNdiAz3PbvhMPtvEGK:b-duqok3)* status: :shipit: complete! all files reviewed, all discussions resolved

___
*[src/SIL.XForge/Services/ProjectService.cs, line 144 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/804#-MHMh_6q7wc-27Qoeel3:-MHNdHs64KDGN2REwZX6:bsyx7ro) ([raw file](https://github.com/sillsdev/web-xforge/blob/ca26b0c148c5d41073b2f78d5abdd4f62535de9b/src/SIL.XForge/Services/ProjectService.cs#L144)):*
<details><summary><i>Previously, marksvc wrote…</i></summary><blockquote>

Let's chat more about this. This follows the pattern of other SystemAdmin checks in both ProjectService.cs  and in UserService.cs. And also significant is the difference between a user's SF SystemRole and a project role; here I want to check that the user has a SF site SystemRole. Let's connect in chat and you can explain some more of what you mean, if you still think it should be changed.
</blockquote></details>

Hey, you're right. Thanks for bringing up the point about how the `UserService` and `ProjectService` do the same thing and pass in the systemRole.

**Comment by marksvc** [comment]
I think it's better to put this right onto master, rather than as a hotfix to sf-live. We won't actually use the functionality until stage1 and stage2 migration is complete. Tho it might be useful to hotfix against sf-qa, depending on just what we plan to release tomorrow.

**Review by irahopkinson — COMMENTED** [review]
@marksvc I've mentioned 4 things below but they didn't need to hold up this PR nor the migration. Good job on getting this in. I'll add a separate PR to fix these but they are non-functional changes so it can merge after the migration.

> Reviewed 15 of 17 files at r1, 2 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/804#-:-MHPxGXR1aSDIcO6tC4R:b-4x31wh)* status: :shipit: complete! all files reviewed, all discussions resolved

___
*[src/SIL.XForge.Scripture/ClientApp/src/assets/i18n/non_checking_en.json, line 166 at r3](https://reviewable.io/reviews/sillsdev/web-xforge/804#-MHPsBBh78zAbFKRVlcF:-MHPsBBiB_Q61DYcbIeZ:b-n4z5bp) ([raw file](https://github.com/sillsdev/web-xforge/blob/2caf2d4b1e2aeda2077af49efd2ae89f7070327f/src/SIL.XForge.Scripture/ClientApp/src/assets/i18n/non_checking_en.json#L166)):*
> ```
> scriptureforgeissues@sil.org
> ```
Use `environment` to deliver this rather than an immediate string.
___
*[src/SIL.XForge.Scripture/ClientApp/src/xforge-common/project.service.ts, line 90 at r3](https://reviewable.io/reviews/sillsdev/web-xforge/804#-MHPsXYW8as4iQX-tYXE:-MHPsXYW8as4iQX-tYXF:b-jzsx8r) ([raw file](https://github.com/sillsdev/web-xforge/blob/2caf2d4b1e2aeda2077af49efd2ae89f7070327f/src/SIL.XForge.Scripture/ClientApp/src/xforge-common/project.service.ts#L90)):*
> ```
> async 
> ```
This `async` is not necessary if you `return this.onlineInvoke(...` like the examples above. Remove it.
___
*[src/SIL.XForge.Scripture/ClientApp/src/xforge-common/system-administration/sa-projects.component.html, line 55 at r3](https://reviewable.io/reviews/sillsdev/web-xforge/804#-MHPuBfAEoOtZFuSKkl3:-MHPuBfAEoOtZFuSKkl4:b-8bau7t) ([raw file](https://github.com/sillsdev/web-xforge/blob/2caf2d4b1e2aeda2077af49efd2ae89f7070327f/src/SIL.XForge.Scripture/ClientApp/src/xforge-common/system-administration/sa-projects.component.html#L55)):*
> ```
> Sync Disabled
> ```
Should be enclosed in `<label>` tags.
___
*[src/SIL.XForge.Scripture/ClientApp/src/xforge-common/system-administration/sa-projects.component.ts, line 116 at r3](https://reviewable.io/reviews/sillsdev/web-xforge/804#-MHPuXjp8L2F8xZghSpo:-MHPuXjp8L2F8xZghSpp:b-s18cnt) ([raw file](https://github.com/sillsdev/web-xforge/blob/2caf2d4b1e2aeda2077af49efd2ae89f7070327f/src/SIL.XForge.Scripture/ClientApp/src/xforge-common/system-administration/sa-projects.component.ts#L116)):*
> ```
> async 
> ```
This is unnecessary because it is already returning a promise. Remove it.

**Review by marksvc — COMMENTED** [review]
Thanks for your comments, and cleaning up the various parts. Makes sense about the async methods. 
Thanks. 

> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/804#-:-MHRZd0M9XtOfLuh2L7J:b-p8clu9)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
