### PR TITLE
SF-893 Block bold, italic, underline in Scripture editor

### PR DESCRIPTION
**Pull request by marksvc**
---
More discussion is on the issue itself.

---
This change is [Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/631)

### CODE REVIEW

**Comment by Nateowami** [comment]
Just to be clear, is italic, bold, and underline an exhaustive list of styles users might be able to apply via the keyboard, or is it just the ones we're targeting?

**Comment by marksvc** [comment]
It's the ones I know to address. I tried CTRL-S for strikethru, which didn't do anything. 
There's probably more formatting a user might be able to do. The issue didn't elaborate. I'll raise this in chat.

**Comment by Nateowami** [comment]
Looking into this a bit more, it appears the keybindings would be dependent on the browser and locale. I wonder if it might be possible to hook into Quill to intercept an incoming delta produced by the user, and if it applies a format in the delta, then tell Quill to ignore the user input?

This PR would probably fix it in most situations, but if we can be more platform-agnostic and deal with it in a more general way that might be preferable.

**Comment by marksvc** [comment]
Yeah that would be good. I am closing this PR and I wrote up some notes in the issue.

**Pull request closed without merging**
