### PR TITLE
Add spacing around buttons

### PR DESCRIPTION
**Pull request by Nateowami**
Checking overview

Answer question form

Import questions dialog

Create/edit question dialog

MdcDialog automatically spaces buttons by 8px when buttons have the `mdcDialogButton` directive.

---
This change is [Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/869)

### CODE REVIEW

**Review by nigel-wells — COMMENTED** [review]
Nice. Just one non blocking comment

> Reviewed 5 of 5 files at r1.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/869#-:-MLtl5_o0mFlwnZ-B-yM:b-dy0ojj)* status: all files reviewed, 1 unresolved discussion (waiting on @Nateowami)

___
*[src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking-overview/checking-overview.component.scss, line 5 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/869#-MLtkencE47fRcwIJfas:-MLtkendCdcvmkYnhvA_:b-x5hufc) ([raw file](https://github.com/sillsdev/web-xforge/blob/4ad095062cf4a4477b78482252339125726b6af9/src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking-overview/checking-overview.component.scss#L5)):*
> ```SCSS
> 
> #import-btn {
>   margin-right: $button-spacing;
> ```

I wonder if we should keep it generic and apply the same rule of `button:not(:first-child)` so that if any other buttons get added here then the rule applies to them as well

**Review by nigel-wells — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/869#-:-MLtlDqxDwIDF_S1Ft1E:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @Nateowami)

**Review by Nateowami — COMMENTED** [review]
Done.

> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/869#-:-MLtvs695w3m_iiNL0Fa:b-896fix)* status: 4 of 6 files reviewed, 1 unresolved discussion (waiting on @nigel-wells)

___
*[src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking-overview/checking-overview.component.scss, line 5 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/869#-MLtkencE47fRcwIJfas:-MLtv_pC0VkMdypILUVD:bftlt8s) ([raw file](https://github.com/sillsdev/web-xforge/blob/4ad095062cf4a4477b78482252339125726b6af9/src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking-overview/checking-overview.component.scss#L5)):*
<details><summary><i>Previously, nigel-wells (Nigel Wells) wrote…</i></summary><blockquote>

I wonder if we should keep it generic and apply the same rule of `button:not(:first-child)` so that if any other buttons get added here then the rule applies to them as well
</blockquote></details>

Done. I considered doing this on a site-wide basis, but there are some places that aren't so simple (such as where the button is within a div, so the selector doesn't work properly).

**Review by nigel-wells — APPROVED** [review]
> Reviewed 2 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/869)* status: all files reviewed, 1 unresolved discussion (waiting on @Nateowami)

___
*[src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking-overview/checking-overview.component.scss, line 5 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/869#-MLtkencE47fRcwIJfas:-MLtwdSSEn4PgmVilNdv:bojm5yv) ([raw file](https://github.com/sillsdev/web-xforge/blob/4ad095062cf4a4477b78482252339125726b6af9/src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking-overview/checking-overview.component.scss#L5)):*
<details><summary><i>Previously, Nateowami (Nathaniel Paulus) wrote…</i></summary><blockquote>

Done. I considered doing this on a site-wide basis, but there are some places that aren't so simple (such as where the button is within a div, so the selector doesn't work properly).
</blockquote></details>

Yep there are always edge cases so I'm happy with doing it on a case by cases basis.

**Review by Nateowami — COMMENTED** [review]
> Dismissed @nigel-wells from a discussion.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/869)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @Nateowami)

**Pull request merged**
