### PR TITLE
SF-1216a Allow users to create note threads

### PR DESCRIPTION
**Pull request by RaymondLuong3**
* allow note create for admins and translators and pt reviewers
* update note dialog to accepts input
* show segment text as the selected text for a new note
* add button to create a note in the editor component
* handle note dialog result when dialog closes
* discard result if note content is empty
* add button styling on mat-flat-button

- - -
This change is [Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1482)

### CODE REVIEW

**Review by Nateowami — CHANGES_REQUESTED** [review]
> Reviewed 13 of 13 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1482)* status: all files reviewed, 14 unresolved discussions (waiting on @RaymondLuong3)

___
*[`src/SIL.XForge.Scripture/ClientApp/src/material-styles.scss` line 91 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/1482#-NBnlSq87Z2kHpdnckAw:-NBnlSq87Z2kHpdnckAx:b-92f8jh) ([raw file](https://github.com/sillsdev/web-xforge/blob/8dfd9fb7554b808ca24c9d01993a4f7b2b48ce48/src/SIL.XForge.Scripture/ClientApp/src/material-styles.scss#L91)):*
> ```SCSS
> }
> 
> .mat-flat-button {
> ```

This can be removed. Use `color="primary"` on each `mat-flat-button` on the buttons and it will set the style by default.
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/core/sf-project.service.ts` line 148 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/1482#-NBnmACdCgIQZe4PTD9F:-NBnmACdCgIQZe4PTD9G:bb3c0f5) ([raw file](https://github.com/sillsdev/web-xforge/blob/8dfd9fb7554b808ca24c9d01993a4f7b2b48ce48/src/SIL.XForge.Scripture/ClientApp/src/app/core/sf-project.service.ts#L148)):*
> ```XML
>   }
> 
>   async createNoteThread(id: string, noteThread: NoteThread): Promise<void> {
> ```

Could we rename this `projectId`?



_Code quote:_
```XML
id
```
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.ts` line 790 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/1482#-NBnrXru6YN31SBGcKr3:-NBnrXru6YN31SBGcKr4:b-hobtw3) ([raw file](https://github.com/sillsdev/web-xforge/blob/8dfd9fb7554b808ca24c9d01993a4f7b2b48ce48/src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.ts#L790)):*
> ```XML
>       }
>     );
>     dialogRef.afterClosed().subscribe(async result => {
> ```

Consider awaiting `toPromise()`
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.spec.ts` line 2339 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/1482#-NBnvkqg4-TUyXReYpRG:-NBnvkqg4-TUyXReYpRH:b-dp6scb) ([raw file](https://github.com/sillsdev/web-xforge/blob/8dfd9fb7554b808ca24c9d01993a4f7b2b48ce48/src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.spec.ts#L2339)):*
> ```XML
>       const noteVerseRef: VerseRef = (arg2 as MatDialogConfig).data!.verseRef;
>       expect(noteVerseRef.toString()).toEqual('MAT 1:1');
>       env.mockNoteDialogRef.close$.next('close');
> ```

This should be `env.mockNoteDialogRef.close('close');
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.spec.ts` line 2369 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/1482#-NBnw_I05O7XwkgtSR9a:-NBnw_I05O7XwkgtSR9b:b7dpy5d) ([raw file](https://github.com/sillsdev/web-xforge/blob/8dfd9fb7554b808ca24c9d01993a4f7b2b48ce48/src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.spec.ts#L2369)):*
> ```XML
>       env.setSelectionAndInsertNote('verse_1_4');
> 
>       env.mockNoteDialogRef.close$.next({ verseRef, note, position, selectedText });
> ```

How about `env.mockNoteDialogRef.close({ verseRef, note, position, selectedText })`?
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/note-dialog/note-dialog.component.html` line 44 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/1482#-NBnw-wW5pYinD58hpG_:-NBnw-wW5pYinD58hpGa:b-xr35yo) ([raw file](https://github.com/sillsdev/web-xforge/blob/8dfd9fb7554b808ca24c9d01993a4f7b2b48ce48/src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/note-dialog/note-dialog.component.html#L44)):*
> ```HTML
>   </mat-dialog-content>
>   <mat-dialog-actions fxLayoutAlign="end">
>     <button mat-button class="close-button" [mat-dialog-close]="'close'">{{ t("close") }}</button>
> ```

How about `[mat-dialog-close]="undefined"`?
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/note-dialog/note-dialog.component.html` line 45 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/1482#-NBnwBG12diorhEnEDtX:-NBnwBG12diorhEnEDtY:b3a7qb3) ([raw file](https://github.com/sillsdev/web-xforge/blob/8dfd9fb7554b808ca24c9d01993a4f7b2b48ce48/src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/note-dialog/note-dialog.component.html#L45)):*
> ```HTML
>   <mat-dialog-actions fxLayoutAlign="end">
>     <button mat-button class="close-button" [mat-dialog-close]="'close'">{{ t("close") }}</button>
>     <button mat-flat-button class="save-button" (click)="submit()">{{ t("save") }}</button>
> ```

How about `color="primary"`?
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/note-dialog/note-dialog.component.ts` line 64 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/1482#-NBnyi7w2vDHM5xA5ABL:-NBnyi7xA6z8YqsJft5z:b-ow1b6u) ([raw file](https://github.com/sillsdev/web-xforge/blob/8dfd9fb7554b808ca24c9d01993a4f7b2b48ce48/src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/note-dialog/note-dialog.component.ts#L64)):*
> ```XML
> 
>   async ngOnInit(): Promise<void> {
>     if (this.threadId == null) {
> ```

Please add a comment to this method mentioning that it should be refactored later to await fewer things in series (a lot of the awaits could be in parallel).
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/note-dialog/note-dialog.component.ts` line 119 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/1482#-NBnzcLD-bPt21nWD8IH:-NBnzcLD-bPt21nWD8II:b-2x3wz3) ([raw file](https://github.com/sillsdev/web-xforge/blob/8dfd9fb7554b808ca24c9d01993a4f7b2b48ce48/src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/note-dialog/note-dialog.component.ts#L119)):*
> ```XML
>   get verseRef(): string {
>     if (this.threadDoc?.data == null) {
>       if (this.data.verseRef == null) {
> ```

Can you create a getter for the verse ref, so the logic for "it can come from the dialog data, or the thread doc" is all in once place?
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/note-dialog/note-dialog.component.ts` line 189 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/1482#-NBnzokQEaPKdgxMIEUw:-NBnzokQEaPKdgxMIEUx:b91ugwr) ([raw file](https://github.com/sillsdev/web-xforge/blob/8dfd9fb7554b808ca24c9d01993a4f7b2b48ce48/src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/note-dialog/note-dialog.component.ts#L189)):*
> ```XML
>   }
>   /*
>   private get textDocId(): string {
> ```

This should be removed.
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/note-dialog/note-dialog.component.ts` line 289 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/1482#-NBo-1dY4buvCGvsR1Xg:-NBo-1dY4buvCGvsR1Xh:bskx01q) ([raw file](https://github.com/sillsdev/web-xforge/blob/8dfd9fb7554b808ca24c9d01993a4f7b2b48ce48/src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/note-dialog/note-dialog.component.ts#L289)):*
> ```XML
> 
>   submit(): void {
>     if (this.currentNote == null || this.currentNote.length === 0) {
> ```

Can we check for white space?
``` ts
this.currentNote.trim().length === 0
```
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/note-dialog/note-dialog.component.ts` line 304 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/1482#-NBo-l-98ApR-mOi4qgJ:-NBo-l-98ApR-mOi4qgK:b-74xrws) ([raw file](https://github.com/sillsdev/web-xforge/blob/8dfd9fb7554b808ca24c9d01993a4f7b2b48ce48/src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/note-dialog/note-dialog.component.ts#L304)):*
> ```XML
>     const note: Note = {
>       dataId: objectId(),
>       threadId: '',
> ```

Can you add a comment explaining why this is an empty string?
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/note-dialog/note-dialog.component.ts` line 310 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/1482#-NBo0QtRBphfJqVYSv_b:-NBo0QtRBphfJqVYSv_c:b-waffrs) ([raw file](https://github.com/sillsdev/web-xforge/blob/8dfd9fb7554b808ca24c9d01993a4f7b2b48ce48/src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/note-dialog/note-dialog.component.ts#L310)):*
> ```XML
>       dateModified: currentDate,
>       conflictType: NoteConflictType.DefaultValue,
>       extUserId: '',
> ```

Should this really be empty? Can you add a comment explaining ownerRef and extUserId?
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/note-dialog/note-dialog.component.spec.ts` line 769 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/1482#-NBo3p2kCWgEbktwyE3U:-NBo3p2kCWgEbktwyE3V:b-xzu6j2) ([raw file](https://github.com/sillsdev/web-xforge/blob/8dfd9fb7554b808ca24c9d01993a4f7b2b48ce48/src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/note-dialog/note-dialog.component.spec.ts#L769)):*
> ```XML
>       .afterClosed()
>       .pipe(first())
>       .subscribe(result => (this.dialogResult = result));
> ```

You can probably just do `afterClosed().toPromise()`.

**Review by RaymondLuong3 — COMMENTED** [review]
I'll wait until we get your feature flag service submitted, then I'll rebase this on top of that.

> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1482#-:-NBxPHZ1Ep9Ms93LsJok:bvjds22)* status: all files reviewed, 14 unresolved discussions (waiting on @Nateowami)

___
*[`src/SIL.XForge.Scripture/ClientApp/src/material-styles.scss` line 91 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/1482#-NBnlSq87Z2kHpdnckAw:-NBx5l8a7JplkvLN47I0:b-896fix) ([raw file](https://github.com/sillsdev/web-xforge/blob/8dfd9fb7554b808ca24c9d01993a4f7b2b48ce48/src/SIL.XForge.Scripture/ClientApp/src/material-styles.scss#L91)):*
<details><summary><i>Previously, Nateowami (Nathaniel Paulus) wrote…</i></summary><blockquote>

This can be removed. Use `color="primary"` on each `mat-flat-button` on the buttons and it will set the style by default.
</blockquote></details>

Done.
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/core/sf-project.service.ts` line 148 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/1482#-NBnmACdCgIQZe4PTD9F:-NBx7BV-CFnlyPUqynGU:b-896fix) ([raw file](https://github.com/sillsdev/web-xforge/blob/8dfd9fb7554b808ca24c9d01993a4f7b2b48ce48/src/SIL.XForge.Scripture/ClientApp/src/app/core/sf-project.service.ts#L148)):*
<details><summary><i>Previously, Nateowami (Nathaniel Paulus) wrote…</i></summary><blockquote>

Could we rename this `projectId`?
</blockquote></details>

Done.
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.ts` line 790 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/1482#-NBnrXru6YN31SBGcKr3:-NBx8FQH2-sp3_zO7lBn:bkoke9u) ([raw file](https://github.com/sillsdev/web-xforge/blob/8dfd9fb7554b808ca24c9d01993a4f7b2b48ce48/src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.ts#L790)):*
<details><summary><i>Previously, Nateowami (Nathaniel Paulus) wrote…</i></summary><blockquote>

Consider awaiting `toPromise()`
</blockquote></details>

I like it. Done.
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.spec.ts` line 2339 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/1482#-NBnvkqg4-TUyXReYpRG:-NBx8sRFAKt3ZuGHyM2_:b-9fmn3c) ([raw file](https://github.com/sillsdev/web-xforge/blob/8dfd9fb7554b808ca24c9d01993a4f7b2b48ce48/src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.spec.ts#L2339)):*
<details><summary><i>Previously, Nateowami (Nathaniel Paulus) wrote…</i></summary><blockquote>

This should be `env.mockNoteDialogRef.close('close');
</blockquote></details>

Good suggestion. Done.
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.spec.ts` line 2369 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/1482#-NBnw_I05O7XwkgtSR9a:-NBx9U_PCC-vEpYpOgmk:b-896fix) ([raw file](https://github.com/sillsdev/web-xforge/blob/8dfd9fb7554b808ca24c9d01993a4f7b2b48ce48/src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.spec.ts#L2369)):*
<details><summary><i>Previously, Nateowami (Nathaniel Paulus) wrote…</i></summary><blockquote>

How about `env.mockNoteDialogRef.close({ verseRef, note, position, selectedText })`?
</blockquote></details>

Done.
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/note-dialog/note-dialog.component.html` line 44 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/1482#-NBnw-wW5pYinD58hpG_:-NBx9avLBBU7kchcplmd:b-896fix) ([raw file](https://github.com/sillsdev/web-xforge/blob/8dfd9fb7554b808ca24c9d01993a4f7b2b48ce48/src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/note-dialog/note-dialog.component.html#L44)):*
<details><summary><i>Previously, Nateowami (Nathaniel Paulus) wrote…</i></summary><blockquote>

How about `[mat-dialog-close]="undefined"`?
</blockquote></details>

Done.
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/note-dialog/note-dialog.component.html` line 45 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/1482#-NBnwBG12diorhEnEDtX:-NBx9bqi3Pu_53grSN-w:b-896fix) ([raw file](https://github.com/sillsdev/web-xforge/blob/8dfd9fb7554b808ca24c9d01993a4f7b2b48ce48/src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/note-dialog/note-dialog.component.html#L45)):*
<details><summary><i>Previously, Nateowami (Nathaniel Paulus) wrote…</i></summary><blockquote>

How about `color="primary"`?
</blockquote></details>

Done.
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/note-dialog/note-dialog.component.ts` line 64 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/1482#-NBnyi7w2vDHM5xA5ABL:-NBx9pB_4kXR-WbBRQ4W:b-896fix) ([raw file](https://github.com/sillsdev/web-xforge/blob/8dfd9fb7554b808ca24c9d01993a4f7b2b48ce48/src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/note-dialog/note-dialog.component.ts#L64)):*
<details><summary><i>Previously, Nateowami (Nathaniel Paulus) wrote…</i></summary><blockquote>

Please add a comment to this method mentioning that it should be refactored later to await fewer things in series (a lot of the awaits could be in parallel).
</blockquote></details>

Done.
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/note-dialog/note-dialog.component.ts` line 119 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/1482#-NBnzcLD-bPt21nWD8IH:-NBxDKTq4ovYmIeDV4JQ:bug0558) ([raw file](https://github.com/sillsdev/web-xforge/blob/8dfd9fb7554b808ca24c9d01993a4f7b2b48ce48/src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/note-dialog/note-dialog.component.ts#L119)):*
<details><summary><i>Previously, Nateowami (Nathaniel Paulus) wrote…</i></summary><blockquote>

Can you create a getter for the verse ref, so the logic for "it can come from the dialog data, or the thread doc" is all in once place?
</blockquote></details>

Good thinking. done.
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/note-dialog/note-dialog.component.ts` line 189 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/1482#-NBnzokQEaPKdgxMIEUw:-NBxDi1x9PR3hl8fWg-b:b-896fix) ([raw file](https://github.com/sillsdev/web-xforge/blob/8dfd9fb7554b808ca24c9d01993a4f7b2b48ce48/src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/note-dialog/note-dialog.component.ts#L189)):*
<details><summary><i>Previously, Nateowami (Nathaniel Paulus) wrote…</i></summary><blockquote>

This should be removed.
</blockquote></details>

Done.
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/note-dialog/note-dialog.component.ts` line 289 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/1482#-NBo-1dY4buvCGvsR1Xg:-NBxDnJSEvMLRY9MsDsO:b-896fix) ([raw file](https://github.com/sillsdev/web-xforge/blob/8dfd9fb7554b808ca24c9d01993a4f7b2b48ce48/src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/note-dialog/note-dialog.component.ts#L289)):*
<details><summary><i>Previously, Nateowami (Nathaniel Paulus) wrote…</i></summary><blockquote>

Can we check for white space?
``` ts
this.currentNote.trim().length === 0
```
</blockquote></details>

Done.
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/note-dialog/note-dialog.component.ts` line 304 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/1482#-NBo-l-98ApR-mOi4qgJ:-NBxE3Rp6k8o11sSz_n_:b-896fix) ([raw file](https://github.com/sillsdev/web-xforge/blob/8dfd9fb7554b808ca24c9d01993a4f7b2b48ce48/src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/note-dialog/note-dialog.component.ts#L304)):*
<details><summary><i>Previously, Nateowami (Nathaniel Paulus) wrote…</i></summary><blockquote>

Can you add a comment explaining why this is an empty string?
</blockquote></details>

Done.
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/note-dialog/note-dialog.component.ts` line 310 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/1482#-NBo0QtRBphfJqVYSv_b:-NBxF8XR6QeR8S5X_b3P:b-896fix) ([raw file](https://github.com/sillsdev/web-xforge/blob/8dfd9fb7554b808ca24c9d01993a4f7b2b48ce48/src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/note-dialog/note-dialog.component.ts#L310)):*
<details><summary><i>Previously, Nateowami (Nathaniel Paulus) wrote…</i></summary><blockquote>

Should this really be empty? Can you add a comment explaining ownerRef and extUserId?
</blockquote></details>

Done.
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/note-dialog/note-dialog.component.spec.ts` line 769 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/1482#-NBo3p2kCWgEbktwyE3U:-NBxFaLwCkcT15aJVbBl:b-896fix) ([raw file](https://github.com/sillsdev/web-xforge/blob/8dfd9fb7554b808ca24c9d01993a4f7b2b48ce48/src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/note-dialog/note-dialog.component.spec.ts#L769)):*
<details><summary><i>Previously, Nateowami (Nathaniel Paulus) wrote…</i></summary><blockquote>

You can probably just do `afterClosed().toPromise()`.
</blockquote></details>

Done.

**Review by Nateowami — CHANGES_REQUESTED** [review]
> Reviewed 10 of 10 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1482)* status: all files reviewed, 2 unresolved discussions (waiting on @RaymondLuong3)

___
*[`src/RealtimeServer/scriptureforge/models/note.ts` line 14 at r2](https://reviewable.io/reviews/sillsdev/web-xforge/1482#-NBy-v2V-y5z_tJmCC15:-NBy-v2V-y5z_tJmCC16:bwpgjuq) ([raw file](https://github.com/sillsdev/web-xforge/blob/7d716217e8ce8e3da2f279f6caea0493b76b2c3d/src/RealtimeServer/scriptureforge/models/note.ts#L14)):*
> ```XML
>    * At the moment, this is the same as the owner ref.
>    */
>   extUserId: string;
> ```

Even after our conversation, and reading this comment, I still have no idea what this property actually does. What I recall hearing is that this property would start out as the SF user ID, and upon syncing would be rewritten to be the Paratext user ID. Is that correct?

If it is, then it seems quite odd, since there's also an ownerRef to store the SF user ID. Or is this property going to be written to Paratext? Can we add arbitrary metadata to Paratext notes? I assumed we would store some type of note ID on the note in Paratext, and then map that note ID to a note in SF, and thereby derive all the information about the note (such as the SF user that created it).
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/note-dialog/note-dialog.component.ts` line 189 at r2](https://reviewable.io/reviews/sillsdev/web-xforge/1482#-NBxz3Qw8bZsTeT6Tmqo:-NBxz3QxDJ1RkLRo_1WV:b-hxmj1t) ([raw file](https://github.com/sillsdev/web-xforge/blob/7d716217e8ce8e3da2f279f6caea0493b76b2c3d/src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/note-dialog/note-dialog.component.ts#L189)):*
> ```XML
> 
>   private get verseRef(): VerseRef | undefined {
>     if (this.threadDoc?.data == null) {
> ```

What about `return this.threadDoc?.data?.verseRef ?? this.data.verseRef`?

**Review by RaymondLuong3 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1482)* status: 7 of 15 files reviewed, 2 unresolved discussions (waiting on @Nateowami)

___
*[`src/RealtimeServer/scriptureforge/models/note.ts` line 14 at r2](https://reviewable.io/reviews/sillsdev/web-xforge/1482#-NBy-v2V-y5z_tJmCC15:-NCSL3Di80hgPfvt2Tgb:b-gzsud) ([raw file](https://github.com/sillsdev/web-xforge/blob/1548b5856e346a4c142ca4a3761614e1f1744dc8/src/RealtimeServer/scriptureforge/models/note.ts#L14)):*
<details><summary><i>Previously, Nateowami (Nathaniel Paulus) wrote…</i></summary><blockquote>

Even after our conversation, and reading this comment, I still have no idea what this property actually does. What I recall hearing is that this property would start out as the SF user ID, and upon syncing would be rewritten to be the Paratext user ID. Is that correct?

If it is, then it seems quite odd, since there's also an ownerRef to store the SF user ID. Or is this property going to be written to Paratext? Can we add arbitrary metadata to Paratext notes? I assumed we would store some type of note ID on the note in Paratext, and then map that note ID to a note in SF, and thereby derive all the information about the note (such as the SF user that created it).
</blockquote></details>

This will always be the SF user Id that created the note. Since the SF user may not have a paratext account, the external user id references the SF user. At the moment, this is not so important, but it is possible that in the future, we may add a role where it makes sense for ownerRef to be a paratext user, but the extUserId will help us keep track of the SF user that create the note.
I might have misled you in our initial conversation.
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/note-dialog/note-dialog.component.ts` line 189 at r2](https://reviewable.io/reviews/sillsdev/web-xforge/1482#-NBxz3Qw8bZsTeT6Tmqo:-NCSJ5DFBA5N5zgOR8uf:bm88cdl) ([raw file](https://github.com/sillsdev/web-xforge/blob/1548b5856e346a4c142ca4a3761614e1f1744dc8/src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/note-dialog/note-dialog.component.ts#L189)):*
<details><summary><i>Previously, Nateowami (Nathaniel Paulus) wrote…</i></summary><blockquote>

What about `return this.threadDoc?.data?.verseRef ?? this.data.verseRef`?
</blockquote></details>

Unfortunately `this.threadDoc.data.verseRef` is of the type `VerseRefData` which is different from `VerseRef` so what you provided would not work since we want the return type to be `VerseRef`.

**Review by Nateowami — COMMENTED** [review]
I'm thinking maybe you didn't see my changes in 5a8f48e878ee87190ddbd1aacb841d61cb498001? You had mentioned last week that in the interest of getting the PR merged more quickly I might consider making changes to this PR to make note creation dependent on the feature flag. I went ahead and did that, and this latest change reverted that. If that's not the case, then I don't understand the rationale behind some of these changes.

> Reviewed 2 of 9 files at r3.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1482#-:-NCSn3fr47Yr5Raj7qxO:bce3d3d)* status: 9 of 16 files reviewed, 1 unresolved discussion (waiting on @Nateowami)

**Review by RaymondLuong3 — COMMENTED** [review]
You are right, I did miss 5a8f48e. I have moved it back to that commit, and then rebased on the latest master.

> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1482#-:-NCVZ30h1DawV2PnxCK4:b-ldoqc1)* status: 5 of 16 files reviewed, 1 unresolved discussion (waiting on @Nateowami)

**Review by Nateowami — APPROVED** [review]
:lgtm:

> Reviewed 3 of 11 files at r4, 8 of 8 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1482#-:-NCVlobh-KxORVopAbjs:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @RaymondLuong3)

___
*[`src/RealtimeServer/scriptureforge/models/note.ts` line 14 at r2](https://reviewable.io/reviews/sillsdev/web-xforge/1482#-NBy-v2V-y5z_tJmCC15:-NCVm17x3oX5KbQsnxti:b-ucfkn4) ([raw file](https://github.com/sillsdev/web-xforge/blob/1548b5856e346a4c142ca4a3761614e1f1744dc8/src/RealtimeServer/scriptureforge/models/note.ts#L14)):*
<details><summary><i>Previously, RaymondLuong3 (Raymond Luong) wrote…</i></summary><blockquote>

This will always be the SF user Id that created the note. Since the SF user may not have a paratext account, the external user id references the SF user. At the moment, this is not so important, but it is possible that in the future, we may add a role where it makes sense for ownerRef to be a paratext user, but the extUserId will help us keep track of the SF user that create the note.
I might have misled you in our initial conversation.
</blockquote></details>

Thanks.

**Review by Nateowami — APPROVED** [review]
> Reviewed 8 of 8 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1482)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @RaymondLuong3)

**Pull request merged**
