### PR TITLE
Add Code launcher for SourceTargetSplitting

### PR DESCRIPTION
**Pull request by marksvc**
This change is [Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/944)

### CODE REVIEW

**Review by RaymondLuong3 — COMMENTED** [review]
I checked out the branch and ran the migrator. It started up the server, but never closed it (or at least it wasn't closed after 5 minutes). It doesn't mean there's anything wrong with this change, but I wonder if you're seeing the same thing.

> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/944#-:-MT7pxyJ5yJVPZCvNvIk:b-yc0o6g)* status: 0 of 2 files reviewed, all discussions resolved

**Review by irahopkinson — CHANGES_REQUESTED** [review]
This is a useful branch - I'll probably use it myself. If it had been earlier in the life of the migrator I might have merged it. However as soon as we finish with the migrator on Live I would want to revert this change so we don't have clutter for things we are no longer using. How about we just keep the branch and rebase it as necessary until we are done with the migrator? You could close this PR or make it a draft.

> Reviewed 2 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/944#-:-MT9U0_v0ekVOAidFeWi:b-sok0ht)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by marksvc — COMMENTED** [review]
@raymondluong3  No I don't recall it doing that. But most of my migrator-runs were in Terminal rather than from VSCode. 

> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/944#-:-MTldd2i8hWLfIKV9RkW:b-jf3mh3)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by marksvc — COMMENTED** [review]
@irahopkinson  Ok. I'll make the PR a draft.

> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/944#-:-MTle-gMEd2WWtJaqWTV:b-81aw9d)* status: :shipit: complete! all files reviewed, all discussions resolved

**Comment by Nateowami** [comment]
@marksvc Is there a reason to keep this PR around? If it's just for the sake of the branch, a branch can exist without a corresponding PR.

**Comment by marksvc** [comment]
Looks like this is old now. Closing.

**Pull request closed without merging**
