### PR TITLE
SF-2486 Show the correct username for notes created in Paratext

### PR DESCRIPTION
**Pull request by pmachapman**
**Problem Synopsis**
Currently, Scripture Forge shows a note's owner as the note author. This is problematic for notes created in Paratext, as `Note.OwnerRef` will be the user who synced the note, not the user who created the note.

**Solution**
Re-implement `<app-owner>` in the Note Dialog Component, and calculate the user name.

**User Name Calculation**
The name calculation logic in `NoteDialogComponent.getNoteUserNameAsync()` could be represented as these rules (matching the new unit tests):

1. **If** the note was created by the currently logged in user **Then** Show "Me"
2. **If** the note has not been synced **Then** Show the SF note owner's name
3. **If** the currently logged in user is a checking user **Then** Show the SF note owner's name
4. **If** the note was created in Scripture Forge **Then** Show the note owner's name
5. **If** the note was created in Scripture Forge **And** we do not have a matching user record **Then** Show the PT user's name
6. **If** the note was created in Scripture Forge **And** we do not have an SF user or PT user **Then** Show "Unknown author"
7. **If** the note was created in Paratext **And** we have a matching user record **Then** Show the SF user's name
8. **If** the note was created in Paratext **And** we do not have a matching user record **Then** Show the PT user's name

**Additional Bug Fixed**
While debugging this issue, it was noticed that the `ParatextUserProfile.SfUserId` property was not being updated on sync. This was occurring because the `ParatextUserProfile` object being modified in `ParatextSyncRunner.GetCurrentProjectPTUsers()` was a reference to the same object in `SFProject.ParatextUsers` loaded from ShareDB. This meant that the property changed checks for `ParatextUserProfile` in `ParatextSyncRunner.CompleteSync()` were checking against the same object that had been modified (and not updating ShareDB).

- - -
This change is [Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/2320)

### CODE REVIEW

**Review by RaymondLuong3 — CHANGES_REQUESTED** [review]
Thanks for fix! I'm glad to see that there was no corruption in the data. I think the logic you provided for what to show is accurate. One thing to keep in mind is that sf_observers and commenters are not allowed to see the PT users on a project. You mentioned checker users, but community checker users cannot see note threads. I haven't tested the fix yet, I'll do that tomorrow.

> Reviewed 2 of 2 files at r1, 4 of 4 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/2320#-:-NpbT1lo7h8XzpC8f4UW:b-30jeys)* status: all files reviewed, 4 unresolved discussions (waiting on @pmachapman)

___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/note-dialog/note-dialog.component.ts` line 437 at r2](https://reviewable.io/reviews/sillsdev/web-xforge/2320#-NpbN3yP4CqJwaYI_I6q:-NpbN3yQ2nceyfnlKnlB:b-a65k42) ([raw file](https://github.com/sillsdev/web-xforge/blob/022de67838ed0b38e4d79278688d8abe2d291a90/src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/note-dialog/note-dialog.component.ts#L437)):*
> ```XML
> 
>     if (
>       syncUser == null || // There is no sync user (not synced yet or the current user is a checking user)
> ```

In this case, I think the sync user is null because the note has not been synced or the current user does not have access to see the PT user (commenters cannot see PT user names unless the user has an SF account, IIRC).
Is that what this comment is trying to say?



_Code quote:_
```XML
    if (
      syncUser == null || // There is no sync user (not synced yet or the current user is a checking user)
```
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/note-dialog/note-dialog.component.ts` line 446 at r2](https://reviewable.io/reviews/sillsdev/web-xforge/2320#-NpbOFIT66YMby2RyKSb:-NpbOFIU4HXEv1QuHc_4:b8p7u90) ([raw file](https://github.com/sillsdev/web-xforge/blob/022de67838ed0b38e4d79278688d8abe2d291a90/src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/note-dialog/note-dialog.component.ts#L446)):*
> ```XML
>             syncUser?.username ?? // Fallback to the sync user
>             translate('checking.unknown_author'); // An "unknown author" (there is no sync user)
>     } else {
> ```

Nit: You don't need to have the else statement, it is implied.



_Code quote:_
```XML
    } else {
```
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/note-dialog/note-dialog.component.spec.ts` line 639 at r2](https://reviewable.io/reviews/sillsdev/web-xforge/2320#-NpbOaSq0pduuKvnkDqR:-NpbOaSq0pduuKvnkDqS:bky4tre) ([raw file](https://github.com/sillsdev/web-xforge/blob/022de67838ed0b38e4d79278688d8abe2d291a90/src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/note-dialog/note-dialog.component.spec.ts#L639)):*
> ```XML
>   }));
> 
>   it('shows the SF note owner name if the user is a checking user', fakeAsync(() => {
> ```

By checking user, do you mean commenter or sf_observer? Community checkers never see these note threads.



_Code quote:_
```XML
  it('shows the SF note owner name if the user is a checking user', fakeAsync(() => {
```
___
*[`src/SIL.XForge.Scripture/Services/ParatextSyncRunner.cs` line 2054 at r2](https://reviewable.io/reviews/sillsdev/web-xforge/2320#-NpbQAoO7XkTLU3O4A8m:-NpbQAoO7XkTLU3O4A8n:bwlbdp2) ([raw file](https://github.com/sillsdev/web-xforge/blob/022de67838ed0b38e4d79278688d8abe2d291a90/src/SIL.XForge.Scripture/Services/ParatextSyncRunner.cs#L2054)):*
> ```Smalltalk
>                 if (profile.SFUserId is null)
>                 {
>                     paratextUsers[username] = new ParatextUserProfile
> ```

Nice bug fix. Was there a way we could get a test for this?



_Code quote:_
```Smalltalk
                   paratextUsers[username] = new ParatextUserProfile
```

**Review by RaymondLuong3 — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/2320)* status: all files reviewed, 3 unresolved discussions (waiting on @pmachapman)

___
*[`src/SIL.XForge.Scripture/Services/ParatextSyncRunner.cs` line 2051 at r3](https://reviewable.io/reviews/sillsdev/web-xforge/2320#-Npv0Yhs0ilOgTzDcm3v:-Npv0Yhs0ilOgTzDcm3w:b-trh1qg) ([raw file](https://github.com/sillsdev/web-xforge/blob/614a24933499881ecd69a178919887fd97f5265f/src/SIL.XForge.Scripture/Services/ParatextSyncRunner.cs#L2051)):*
> ```Smalltalk
>             {
>                 // If we do not have the SF user id, replace the entity so that the saving in CompleteSync() will not
>                 // read this modified object from projectDoc.Data, and think that there are no changes.
> ```

This comment is a little confusing with the double negative. Maybe a simpler message would be "If we do not have the SF user Id set, add the SF user Id to be stored when CompleteSync is called"



_Code quote:_
```Smalltalk
                // If we do not have the SF user id, replace the entity so that the saving in CompleteSync() will not
                // read this modified object from projectDoc.Data, and think that there are no changes.
```

**Review by pmachapman — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/2320)* status: all files reviewed, 3 unresolved discussions (waiting on @RaymondLuong3)

___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/note-dialog/note-dialog.component.ts` line 437 at r2](https://reviewable.io/reviews/sillsdev/web-xforge/2320#-NpbN3yP4CqJwaYI_I6q:-NppfVAL3tdv2O8aoR5s:bmj1p02) ([raw file](https://github.com/sillsdev/web-xforge/blob/022de67838ed0b38e4d79278688d8abe2d291a90/src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/note-dialog/note-dialog.component.ts#L437)):*
<details><summary><i>Previously, RaymondLuong3 (Raymond Luong) wrote…</i></summary><blockquote>

In this case, I think the sync user is null because the note has not been synced or the current user does not have access to see the PT user (commenters cannot see PT user names unless the user has an SF account, IIRC).
Is that what this comment is trying to say?
</blockquote></details>

Yes. I have tried to clarify the comment. Please let me know if it is clearer.
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/note-dialog/note-dialog.component.ts` line 446 at r2](https://reviewable.io/reviews/sillsdev/web-xforge/2320#-NpbOFIT66YMby2RyKSb:-Npph1RY5_0yiMzoUy1P:b-896fix) ([raw file](https://github.com/sillsdev/web-xforge/blob/022de67838ed0b38e4d79278688d8abe2d291a90/src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/note-dialog/note-dialog.component.ts#L446)):*
<details><summary><i>Previously, RaymondLuong3 (Raymond Luong) wrote…</i></summary><blockquote>

Nit: You don't need to have the else statement, it is implied.
</blockquote></details>

Done.
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/note-dialog/note-dialog.component.spec.ts` line 639 at r2](https://reviewable.io/reviews/sillsdev/web-xforge/2320#-NpbOaSq0pduuKvnkDqR:-NpphQvvDbxt-A8IlTw4:b-le98o5) ([raw file](https://github.com/sillsdev/web-xforge/blob/022de67838ed0b38e4d79278688d8abe2d291a90/src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/note-dialog/note-dialog.component.spec.ts#L639)):*
<details><summary><i>Previously, RaymondLuong3 (Raymond Luong) wrote…</i></summary><blockquote>

By checking user, do you mean commenter or sf_observer? Community checkers never see these note threads.
</blockquote></details>

Done. I meant commenter. Thanks!
___
*[`src/SIL.XForge.Scripture/Services/ParatextSyncRunner.cs` line 2054 at r2](https://reviewable.io/reviews/sillsdev/web-xforge/2320#-NpbQAoO7XkTLU3O4A8m:-Nppcu4d6250owUC-zBY:bm3z9xc) ([raw file](https://github.com/sillsdev/web-xforge/blob/022de67838ed0b38e4d79278688d8abe2d291a90/src/SIL.XForge.Scripture/Services/ParatextSyncRunner.cs#L2054)):*
<details><summary><i>Previously, RaymondLuong3 (Raymond Luong) wrote…</i></summary><blockquote>

Nice bug fix. Was there a way we could get a test for this?
</blockquote></details>

I tried to create a regression test on `master`, but because the `MemoryRepository` does not serialize objects out of memory, the faulty implementation that updates `SFUserId` updates the object in the repository (because it was passed by reference via the `SFMemoryRealtimeService`), and the regression test passes on `master`. For reference, here was the test:
```cs
[Test]
public async Task RunAsync_UpdatesParatextUserProfile()
{
    // Set up the test environment
    var env = new TestEnvironment();

    // Set up the project and users
    env.SetupSFData(false, false, false, false);

    // Set up the username mappings
    env.SetupNoteChanges("data01", "thread01");

    // Verify that the project does not have the SFUserId set
    var project = env.GetProject();
    Assert.AreEqual("User 1", project.ParatextUsers.First().Username);
    Assert.IsNull(project.ParatextUsers.First().SFUserId);

    // SUT
    await env.Runner.RunAsync("project01", "user01", "project01", false, CancellationToken.None);

    // Validate that SFUserId was set
    project = env.GetProject();
    Assert.AreEqual("User 1", project.ParatextUsers.First().Username);
    Assert.IsNotNull(project.ParatextUsers.First().SFUserId);
}
```
___
*[`src/SIL.XForge.Scripture/Services/ParatextSyncRunner.cs` line 2051 at r3](https://reviewable.io/reviews/sillsdev/web-xforge/2320#-Npv0Yhs0ilOgTzDcm3v:-NpzdKuk6rDEc8s-HAyl:b-s7a025) ([raw file](https://github.com/sillsdev/web-xforge/blob/614a24933499881ecd69a178919887fd97f5265f/src/SIL.XForge.Scripture/Services/ParatextSyncRunner.cs#L2051)):*
<details><summary><i>Previously, RaymondLuong3 (Raymond Luong) wrote…</i></summary><blockquote>

This comment is a little confusing with the double negative. Maybe a simpler message would be "If we do not have the SF user Id set, add the SF user Id to be stored when CompleteSync is called"
</blockquote></details>

Done. Hopefully this is clearer.

**Review by RaymondLuong3 — APPROVED** [review]
It looks good on my end. You may be the best one to create acceptance tests for this since you know the full scope of the problem. I'll let you do that and move this to "ready to test"

> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/2320#-:-Npzv6TD89TZE324VrOd:bnkw5fd)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @pmachapman)

___
*[`src/SIL.XForge.Scripture/Services/ParatextSyncRunner.cs` line 2054 at r2](https://reviewable.io/reviews/sillsdev/web-xforge/2320#-NpbQAoO7XkTLU3O4A8m:-NpzuiVc8TTt632hApKJ:b-yio4eg) ([raw file](https://github.com/sillsdev/web-xforge/blob/022de67838ed0b38e4d79278688d8abe2d291a90/src/SIL.XForge.Scripture/Services/ParatextSyncRunner.cs#L2054)):*
<details><summary><i>Previously, pmachapman (Peter Chapman) wrote…</i></summary><blockquote>

I tried to create a regression test on `master`, but because the `MemoryRepository` does not serialize objects out of memory, the faulty implementation that updates `SFUserId` updates the object in the repository (because it was passed by reference via the `SFMemoryRealtimeService`), and the regression test passes on `master`. For reference, here was the test:
```cs
[Test]
public async Task RunAsync_UpdatesParatextUserProfile()
{
    // Set up the test environment
    var env = new TestEnvironment();

    // Set up the project and users
    env.SetupSFData(false, false, false, false);

    // Set up the username mappings
    env.SetupNoteChanges("data01", "thread01");

    // Verify that the project does not have the SFUserId set
    var project = env.GetProject();
    Assert.AreEqual("User 1", project.ParatextUsers.First().Username);
    Assert.IsNull(project.ParatextUsers.First().SFUserId);

    // SUT
    await env.Runner.RunAsync("project01", "user01", "project01", false, CancellationToken.None);

    // Validate that SFUserId was set
    project = env.GetProject();
    Assert.AreEqual("User 1", project.ParatextUsers.First().Username);
    Assert.IsNotNull(project.ParatextUsers.First().SFUserId);
}
```
</blockquote></details>

Thanks for figuring that one out. I am happy if we do not have a test, but know why we cannot have one that tests this behaviour.

**Review by pmachapman — COMMENTED** [review]
Sounds good. I have created the acceptance test, and fixed a bug found when writing and executing the test.

> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/2320#-:-Nq-8uVZ9oIFrYf0PnAR:b-bvoj55)* status: 5 of 6 files reviewed, all discussions resolved (waiting on @RaymondLuong3)

**Review by RaymondLuong3 — APPROVED** [review]
> Reviewed 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/2320)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @pmachapman)

**Review by pmachapman — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/2320)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @pmachapman)

**Review by RaymondLuong3 — APPROVED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/2320)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @pmachapman)

**Pull request merged**
