### PR TITLE
SF-1236 Fix interaction between beta and non beta servers

### PR DESCRIPTION
**Pull request by Nateowami**
When the non-beta site initiated a sync it gets added to a queue. Then the wrong process picked up the task.

---
This change is [Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1004)

### CODE REVIEW

**Review by nigel-wells — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1004)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @Nateowami)

___
*[src/SIL.XForge.Scripture/Startup.cs, line 137 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/1004#-MXadsRoCQKuCX98jGrO:-MXadsRp0oXsLGVPM1d7:by7um6l) ([raw file](https://github.com/sillsdev/web-xforge/blob/61845c9bf0dbf65d90954c481ecc6f05ea3c2e61/src/SIL.XForge.Scripture/Startup.cs#L137)):*
> ```Smalltalk
>             if (!Environment.EnvironmentName.EndsWith("Beta"))
>             {
>                 services.AddSFDataAccess(Configuration);
> ```

I had trouble running through the acceptance tests from SF-1156 without this running. I was unable to start up dotnet using this command:
```
 dotnet run --start-ng-serve=listen --enable-beta-realtime-server=yes --environment=DevelopmentBeta
```
How important is it to have that disabled? It isn't the end of the world if we can't run it as, once we go live, the realtime server won't be loaded on beta. We only need the realtime server running on beta in order to get some data loaded in order to test. If need be I can just enable this to get some data loaded and then revert the code and attempt the rest of the tests.

**Review by irahopkinson — APPROVED** [review]
> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1004)* status: all files reviewed, 1 unresolved discussion (waiting on @nigel-wells)

___
*[src/SIL.XForge.Scripture/Startup.cs, line 137 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/1004#-MXadsRoCQKuCX98jGrO:-MXbWpOSA4VgKyAdZqcU:bz79yr9) ([raw file](https://github.com/sillsdev/web-xforge/blob/61845c9bf0dbf65d90954c481ecc6f05ea3c2e61/src/SIL.XForge.Scripture/Startup.cs#L137)):*
<details><summary><i>Previously, nigel-wells (Nigel Wells) wrote…</i></summary><blockquote>

I had trouble running through the acceptance tests from SF-1156 without this running. I was unable to start up dotnet using this command:
```
 dotnet run --start-ng-serve=listen --enable-beta-realtime-server=yes --environment=DevelopmentBeta
```
How important is it to have that disabled? It isn't the end of the world if we can't run it as, once we go live, the realtime server won't be loaded on beta. We only need the realtime server running on beta in order to get some data loaded in order to test. If need be I can just enable this to get some data loaded and then revert the code and attempt the rest of the tests.
</blockquote></details>

This probably doesn't need to work anymore because SF-1228 is now merged, right?

**Review by Nateowami — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1004)* status: all files reviewed, 1 unresolved discussion (waiting on @nigel-wells)

___
*[src/SIL.XForge.Scripture/Startup.cs, line 137 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/1004#-MXadsRoCQKuCX98jGrO:-MXbYc9KDJ7DiZFrRzGU:b5kxx4r) ([raw file](https://github.com/sillsdev/web-xforge/blob/61845c9bf0dbf65d90954c481ecc6f05ea3c2e61/src/SIL.XForge.Scripture/Startup.cs#L137)):*
<details><summary><i>Previously, irahopkinson (Ira Hopkinson) wrote…</i></summary><blockquote>

This probably doesn't need to work anymore because SF-1228 is now merged, right?
</blockquote></details>

It's pretty important that it not be running or it will pick up the sync tasks from the queue. However, we could make starting it conditional on the `--enable-beta-realtime-server` flag. Would that solve the issue?

**Review by irahopkinson — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1004)* status: all files reviewed, 1 unresolved discussion (waiting on @nigel-wells)

___
*[src/SIL.XForge.Scripture/Startup.cs, line 137 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/1004#-MXadsRoCQKuCX98jGrO:-MXbZZih2NrzozkK_TLz:b-upq1rh) ([raw file](https://github.com/sillsdev/web-xforge/blob/61845c9bf0dbf65d90954c481ecc6f05ea3c2e61/src/SIL.XForge.Scripture/Startup.cs#L137)):*
<details><summary><i>Previously, Nateowami (Nathaniel Paulus) wrote…</i></summary><blockquote>

It's pretty important that it not be running or it will pick up the sync tasks from the queue. However, we could make starting it conditional on the `--enable-beta-realtime-server` flag. Would that solve the issue?
</blockquote></details>

As I understand it the flag was only useful for testing before we merged in the redirect code in SF-1228. After that I don't think the flag is useful anymore. Perhaps @nigel-wells can confirm this?

**Review by marksvc — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1004)* status: all files reviewed, 1 unresolved discussion (waiting on @nigel-wells)

___
*[src/SIL.XForge.Scripture/Startup.cs, line 137 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/1004#-MXadsRoCQKuCX98jGrO:-MXc4JAZ5-rXN7ihV7Kl:bjql9lk) ([raw file](https://github.com/sillsdev/web-xforge/blob/61845c9bf0dbf65d90954c481ecc6f05ea3c2e61/src/SIL.XForge.Scripture/Startup.cs#L137)):*
<details><summary><i>Previously, irahopkinson (Ira Hopkinson) wrote…</i></summary><blockquote>

As I understand it the flag was only useful for testing before we merged in the redirect code in SF-1228. After that I don't think the flag is useful anymore. Perhaps @nigel-wells can confirm this?
</blockquote></details>

I think I am ok with modifying the code so that Beta just never uses the realtime server. I might want it to work some time in the next 48 hours but if so I can just fiddle with this file, or make this area honour --enable-beta-realtime-server=yes. 
I can imagine I might want it to be possible on QA, but haven't decided yet if I really do :)

**Review by nigel-wells — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1004)* status: all files reviewed, 1 unresolved discussion (waiting on @marksvc and @Nateowami)

___
*[src/SIL.XForge.Scripture/Startup.cs, line 137 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/1004#-MXadsRoCQKuCX98jGrO:-MXcp3za-mHRgr1Njgo7:bnbpsk8) ([raw file](https://github.com/sillsdev/web-xforge/blob/61845c9bf0dbf65d90954c481ecc6f05ea3c2e61/src/SIL.XForge.Scripture/Startup.cs#L137)):*
<details><summary><i>Previously, marksvc wrote…</i></summary><blockquote>

I think I am ok with modifying the code so that Beta just never uses the realtime server. I might want it to work some time in the next 48 hours but if so I can just fiddle with this file, or make this area honour --enable-beta-realtime-server=yes. 
I can imagine I might want it to be possible on QA, but haven't decided yet if I really do :)
</blockquote></details>

@irahopkinson as this PR is disabling a number of other services for beta we need to retest that the migration still works as expected. I think I'll just work around it as I only need to get test data in to indexdb and then it hopefully won't be an issue any more. One other thought I had was to perhaps not initiate syncs when running from the beta environment.

**Review by Nateowami — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1004)* status: all files reviewed, 1 unresolved discussion (waiting on @nigel-wells)

___
*[src/SIL.XForge.Scripture/Startup.cs, line 137 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/1004#-MXadsRoCQKuCX98jGrO:-MXcsm5S3S69hSbJWyJA:belgj07) ([raw file](https://github.com/sillsdev/web-xforge/blob/61845c9bf0dbf65d90954c481ecc6f05ea3c2e61/src/SIL.XForge.Scripture/Startup.cs#L137)):*
> One other thought I had was to perhaps not initiate syncs when running from the beta environment.

That's what this PR is doing. A library called Hangfire is handling the queue by putting jobs in MongoDB and then reading them out of the DB. This line which has been made conditional results in a call to `services.AddDataAccess()` which results in a call to `services.AddHangfire()`. It's quite possible we could disable just the Hangfire part by passing in a boolean value called something like `enableBackgroundJobs`. But I don't know what other types of issues that might cause. We might for example have code that would try to add jobs and then crash because the services for doing that have not been added. Just disabling this one line caused things to break, which necessitated the changes farther down in the file. With some testing we might be able to work out whether doing that would leave things broken or not. But perhaps that's no easier than testing it the way it is? I'm really not sure how involved testing it is.

**Review by nigel-wells — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1004)* status: all files reviewed, 1 unresolved discussion (waiting on @marksvc and @Nateowami)

___
*[src/SIL.XForge.Scripture/Startup.cs, line 137 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/1004#-MXadsRoCQKuCX98jGrO:-MXeEOKrDe65pv7dkk3W:b-g9y7zy) ([raw file](https://github.com/sillsdev/web-xforge/blob/6efcc88777c53dbd6801f8dc7dffc58460bc0d76/src/SIL.XForge.Scripture/Startup.cs#L137)):*
<details><summary><i>Previously, Nateowami (Nathaniel Paulus) wrote…</i></summary><blockquote>

> One other thought I had was to perhaps not initiate syncs when running from the beta environment.

That's what this PR is doing. A library called Hangfire is handling the queue by putting jobs in MongoDB and then reading them out of the DB. This line which has been made conditional results in a call to `services.AddDataAccess()` which results in a call to `services.AddHangfire()`. It's quite possible we could disable just the Hangfire part by passing in a boolean value called something like `enableBackgroundJobs`. But I don't know what other types of issues that might cause. We might for example have code that would try to add jobs and then crash because the services for doing that have not been added. Just disabling this one line caused things to break, which necessitated the changes farther down in the file. With some testing we might be able to work out whether doing that would leave things broken or not. But perhaps that's no easier than testing it the way it is? I'm really not sure how involved testing it is.
</blockquote></details>

I've tested this out (I enabled `services.AddSFDataAccess(Configuration);` so I could add some offline data on beta and then disabled it again as per your PR). My test data from indexdb came across, however, I have discovered another bug which I'll create a card for.

**Review by Nateowami — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1004)* status: all files reviewed, 1 unresolved discussion (waiting on @nigel-wells)

___
*[src/SIL.XForge.Scripture/Startup.cs, line 137 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/1004#-MXadsRoCQKuCX98jGrO:-MXhSQuN7o1Z44X4QkqV:bw4s2c6) ([raw file](https://github.com/sillsdev/web-xforge/blob/6efcc88777c53dbd6801f8dc7dffc58460bc0d76/src/SIL.XForge.Scripture/Startup.cs#L137)):*
<details><summary><i>Previously, nigel-wells (Nigel Wells) wrote…</i></summary><blockquote>

I've tested this out (I enabled `services.AddSFDataAccess(Configuration);` so I could add some offline data on beta and then disabled it again as per your PR). My test data from indexdb came across, however, I have discovered another bug which I'll create a card for.
</blockquote></details>

@nigel-wells is that other bug SF-1251? If so, I don't think that needs to hold up this PR.

Would making these changes be conditional on `--enable-beta-realtime-server` be helpful?

**Review by marksvc — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1004)* status: all files reviewed, 1 unresolved discussion (waiting on @nigel-wells)

___
*[src/SIL.XForge.Scripture/Startup.cs, line 137 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/1004#-MXadsRoCQKuCX98jGrO:-MXhjOsq6CSbBUh7a6Y6:b-5oi38b) ([raw file](https://github.com/sillsdev/web-xforge/blob/6efcc88777c53dbd6801f8dc7dffc58460bc0d76/src/SIL.XForge.Scripture/Startup.cs#L137)):*
> I've tested this out (I enabled `services.AddSFDataAccess(Configuration);` so I could add some offline data on beta and then disabled it again as per your PR). My test data from indexdb came across, ...

Nigel, when testing the migration, I have been able to run pwaTest or pwaTestBeta, to get the app with service worker loaded into my browser. Then I can shut down the SF backend and I am able to edit data offline using the SF frontend at beta.localhost. I haven't tried that yet with this PR, but I'm surprised to hear that you were needing to enable something in the C# so you could use the frontend to add into indexeddb. Perhaps when I use this PR I'll quickly see why.

**Review by marksvc — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1004)* status: all files reviewed, 1 unresolved discussion (waiting on @nigel-wells)

___
*[src/SIL.XForge.Scripture/Startup.cs, line 137 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/1004#-MXadsRoCQKuCX98jGrO:-MXhjmbb3F00KjOwnVWO:byggyqy) ([raw file](https://github.com/sillsdev/web-xforge/blob/6efcc88777c53dbd6801f8dc7dffc58460bc0d76/src/SIL.XForge.Scripture/Startup.cs#L137)):*
<details><summary><i>Previously, marksvc wrote…</i></summary><blockquote>

> I've tested this out (I enabled `services.AddSFDataAccess(Configuration);` so I could add some offline data on beta and then disabled it again as per your PR). My test data from indexdb came across, ...

Nigel, when testing the migration, I have been able to run pwaTest or pwaTestBeta, to get the app with service worker loaded into my browser. Then I can shut down the SF backend and I am able to edit data offline using the SF frontend at beta.localhost. I haven't tried that yet with this PR, but I'm surprised to hear that you were needing to enable something in the C# so you could use the frontend to add into indexeddb. Perhaps when I use this PR I'll quickly see why.

</blockquote></details>

Nigel, it looks like you have a Blocking disposition on this comment thread. But I'm a bit confused about what it is that needs to be changed. Are you thinking that before this PR is merged, there needs to be more testing? Are you thinking that rather than just turn off `services.AddSFDataAccess(Configuration);` based on whether `!Environment.EnvironmentName.EndsWith("Beta")`, that we should include consideration of `--enable-beta-realtime-server`?

**Review by nigel-wells — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1004)* status: all files reviewed, 1 unresolved discussion (waiting on @marksvc and @Nateowami)

___
*[src/SIL.XForge.Scripture/Startup.cs, line 137 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/1004#-MXadsRoCQKuCX98jGrO:-MXho-ce7Ic5tB-NoTox:b-z6hca) ([raw file](https://github.com/sillsdev/web-xforge/blob/6efcc88777c53dbd6801f8dc7dffc58460bc0d76/src/SIL.XForge.Scripture/Startup.cs#L137)):*
<details><summary><i>Previously, marksvc wrote…</i></summary><blockquote>

Nigel, it looks like you have a Blocking disposition on this comment thread. But I'm a bit confused about what it is that needs to be changed. Are you thinking that before this PR is merged, there needs to be more testing? Are you thinking that rather than just turn off `services.AddSFDataAccess(Configuration);` based on whether `!Environment.EnvironmentName.EndsWith("Beta")`, that we should include consideration of `--enable-beta-realtime-server`?  
</blockquote></details>

Sorry for any confusion guys I thought had set this as approved without any changes required? While I was testing it turns out that my initial step in SF-1156 - `dotnet run --start-ng-serve=listen --enable-beta-realtime-server=yes --environment=DevelopmentBeta` isn't actually required which is what was causing an issue when trying to run this PR without `services.AddSFDataAccess(Configuration);` being executed. Running `dotnet run --start-ng-serve=listen --environment=Development` was enough to also let the beta site work which is all I needed to get some offline data loaded in. I'm happy for this to be merged.

**Review by marksvc — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1004)* status: all files reviewed, 1 unresolved discussion (waiting on @nigel-wells)

___
*[src/SIL.XForge.Scripture/Startup.cs, line 137 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/1004#-MXadsRoCQKuCX98jGrO:-MXhnC7Y0BtIcqfNpD6q:b847qm) ([raw file](https://github.com/sillsdev/web-xforge/blob/6efcc88777c53dbd6801f8dc7dffc58460bc0d76/src/SIL.XForge.Scripture/Startup.cs#L137)):*
<details><summary><i>Previously, nigel-wells (Nigel Wells) wrote…</i></summary><blockquote>

Sorry for any confusion guys I thought had set this as approved without any changes required? While I was testing it turns out that my initial step in SF-1156 - `dotnet run --start-ng-serve=listen --enable-beta-realtime-server=yes --environment=DevelopmentBeta` isn't actually required which is what was causing an issue when trying to run this PR without `services.AddSFDataAccess(Configuration);` being executed. Running `dotnet run --start-ng-serve=listen --environment=Development` was enough to also let the beta site work which is all I needed to get some offline data loaded in. I'm happy for this to be merged.
</blockquote></details>

Okay, great.

**Review by nigel-wells — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1004)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @Nateowami)

**Pull request merged**
