### PR TITLE
Add script and workflow to fetch translations from Crowdin

### PR DESCRIPTION
**Pull request by Nateowami**
This change is [Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/2866)

### CODE REVIEW

**Comment by Nateowami** [comment]
This is an attempt to create a script to update from Crowdin, and to auto commit and create a PR. See https://github.com/sillsdev/web-xforge/pull/2867, which was created by this workflow.

However, it's not possible to merge that PR, because the PR was pushed by a bot.

There are several potential workarounds, and I'm still looking into them.

**Review by pmachapman — CHANGES_REQUESTED** [review]
We just need some handling of non-success API results from the CrowdIn API, and this should be good to go.

> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/2866#-:-ODClXzJ9jNjwkl6g743:b-pr03l2)* status: all files reviewed, 8 unresolved discussions (waiting on @Nateowami)

___
*[`.github/workflows/update-localizations.yml` line 36 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/2866#-ODCxzGf4vH0zkDlO-_g:-ODCxzGf4vH0zkDlO-_h:bn8xz36) ([raw file](https://github.com/sillsdev/web-xforge/blob/24c2a3f0016357635922e46a5fb30a902fba6790/.github/workflows/update-localizations.yml#L36)):*
> ```YAML
>           body: Automated update of files by GitHub action
>           branch: i18n/update
>           base: master
> ```

Should we consider using the GH CLI rather than a third party GHA? You would likely need to make the commit via `git` in the Deno script, then something like:
```yml
  steps:
    - name: Create Pull Request
      run: gh pr create -B master -H i18n/update --title 'Update all translation files from Crowdin' --body 'Automated update of files by GitHub action'
      env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
```

See https://docs.github.com/en/actions/writing-workflows/choosing-what-your-workflow-does/using-github-cli-in-workflows

I guess I am nervous about third party GHAs and the potential of its developer either killing the GHA, or the developer's account getting hacked and something unexpected being injected into the PR.

If you don't think its a problem, or a very low risk, then cool. I just thought I'd raise it for discussion.



_Code quote:_
```YAML
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v7
        with:
          commit-message: Update all translation files from Crowdin
          title: Update all translation files from Crowdin
          body: Automated update of files by GitHub action
          branch: i18n/update
          base: master
```
___
*[`scripts/update_from_crowdin.mts` line 19 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/2866#-ODCpmlz2A7PJHUPGBfq:-ODCpmlz2A7PJHUPGBfr:b5ie64i) ([raw file](https://github.com/sillsdev/web-xforge/blob/24c2a3f0016357635922e46a5fb30a902fba6790/scripts/update_from_crowdin.mts#L19)):*
> ```TypeScript
>   });
> 
>   const buildResponseBody = await response.json();
> ```

Can we `throw` (or `console.error('...'); Deno.exit(1);`) if the status code is other than 200? 



_Code quote:_
```TypeScript
  const buildResponseBody = await response.json();
```
___
*[`scripts/update_from_crowdin.mts` line 32 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/2866#-ODCojqNEbo5fBJxNsW1:-ODCojqNEbo5fBJxNsW2:bi9smwy) ([raw file](https://github.com/sillsdev/web-xforge/blob/24c2a3f0016357635922e46a5fb30a902fba6790/scripts/update_from_crowdin.mts#L32)):*
> ```TypeScript
>       { headers: { Authorization: `Bearer ${apiKey}` } }
>     );
> ```

Can we have a `throw` if the status code is other than 200? Otherwise, the loop will keep going forever.
___
*[`scripts/update_from_crowdin.mts` line 35 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/2866#-ODCp2DH5G--gCnynd7-:-ODCp2DH5G--gCnynd70:b9dmnpw) ([raw file](https://github.com/sillsdev/web-xforge/blob/24c2a3f0016357635922e46a5fb30a902fba6790/scripts/update_from_crowdin.mts#L35)):*
> ```TypeScript
>     const buildStatusBody = await buildStatusResponse.json();
> 
>     if (buildStatusBody.data.status === "finished") {
> ```

Can we handle error status values like `"canceled"` or `"failed"`, and `throw` if these occur? Otherwise the loop will go forever.

See https://support.crowdin.com/developer/api/v2/#tag/Translations/operation/api.projects.translations.builds.get for status values.



_Code quote:_
```TypeScript
if (buildStatusBody.data.status === "finished") {
```
___
*[`scripts/update_from_crowdin.mts` line 50 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/2866#-ODCrc6kD7yoAn9dz_vN:-ODCrc6lDv_VwPYHDTvr:b-gddj3u) ([raw file](https://github.com/sillsdev/web-xforge/blob/24c2a3f0016357635922e46a5fb30a902fba6790/scripts/update_from_crowdin.mts#L50)):*
> ```TypeScript
>   );
> 
>   const buildDownloadBody = await buildDownloadResponse.json();
> ```

Can we `throw` if the status code is other than 200? 



_Code quote:_
```TypeScript
  const buildDownloadBody = await buildDownloadResponse.json();
```
___
*[`scripts/update_from_crowdin.mts` line 56 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/2866#-ODCuQNnE7kxx7hDvpjB:-ODCuQNnE7kxx7hDvpjC:b-gddj3u) ([raw file](https://github.com/sillsdev/web-xforge/blob/24c2a3f0016357635922e46a5fb30a902fba6790/scripts/update_from_crowdin.mts#L56)):*
> ```TypeScript
>   console.log("Downloading the build:");
>   console.log(buildUrl);
>   const downloadResponse = await fetch(buildUrl);
> ```

Can we `throw` if the status code is other than 200? 



_Code quote:_
```TypeScript
  const downloadResponse = await fetch(buildUrl);
```
___
*[`scripts/update_from_crowdin.mts` line 58 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/2866#-ODCuRbD61SPsQzlh2BT:-ODCuRbD61SPsQzlh2BU:b5c6hhz) ([raw file](https://github.com/sillsdev/web-xforge/blob/24c2a3f0016357635922e46a5fb30a902fba6790/scripts/update_from_crowdin.mts#L58)):*
> ```TypeScript
>   const downloadResponse = await fetch(buildUrl);
>   const arrayBuffer = await downloadResponse.arrayBuffer();
>   const buffer = new Uint8Array(arrayBuffer);
> ```

NIT: You could replace this with:
```ts
const buffer = await downloadResponse.bytes();
```



_Code quote:_
```TypeScript
  const arrayBuffer = await downloadResponse.arrayBuffer();
  const buffer = new Uint8Array(arrayBuffer);
```
___
*[`scripts/update_from_crowdin.mts` line 77 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/2866#-ODCsFrg5Y18Xo-wg865:-ODCsFrg5Y18Xo-wg866:b-apsl4d) ([raw file](https://github.com/sillsdev/web-xforge/blob/24c2a3f0016357635922e46a5fb30a902fba6790/scripts/update_from_crowdin.mts#L77)):*
> ```TypeScript
>   } else {
>     const errorString = new TextDecoder().decode(stderr);
>     console.error("Extraction failed:", errorString);
> ```

Won't we want to `Deno.exit(1)` if we are having an error here?



_Code quote:_
```TypeScript
console.error("Extraction failed:", errorString);
```

**Review by Nateowami — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/2866)* status: 0 of 2 files reviewed, 7 unresolved discussions (waiting on @pmachapman)

___
*[`.github/workflows/update-localizations.yml` line 36 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/2866#-ODCxzGf4vH0zkDlO-_g:-ODD3dpF-KnqZt4xYCo4:bi84lm5) ([raw file](https://github.com/sillsdev/web-xforge/blob/24c2a3f0016357635922e46a5fb30a902fba6790/.github/workflows/update-localizations.yml#L36)):*
<details><summary><i>Previously, pmachapman (Peter Chapman) wrote…</i></summary><blockquote>

Should we consider using the GH CLI rather than a third party GHA? You would likely need to make the commit via `git` in the Deno script, then something like:
```yml
  steps:
    - name: Create Pull Request
      run: gh pr create -B master -H i18n/update --title 'Update all translation files from Crowdin' --body 'Automated update of files by GitHub action'
      env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
```

See https://docs.github.com/en/actions/writing-workflows/choosing-what-your-workflow-does/using-github-cli-in-workflows

I guess I am nervous about third party GHAs and the potential of its developer either killing the GHA, or the developer's account getting hacked and something unexpected being injected into the PR.

If you don't think its a problem, or a very low risk, then cool. I just thought I'd raise it for discussion.
</blockquote></details>

If you look at the history of this branch, I actually started with this approach and found this action to make things much, much cleaner. This action seems to me to be quite well maintained and documented. However, it might make sense to pin it to a particular commit.
___
*[`scripts/update_from_crowdin.mts` line 19 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/2866#-ODCpmlz2A7PJHUPGBfq:-ODD9eQQCXdzCZ3oYzuJ:b-896fix) ([raw file](https://github.com/sillsdev/web-xforge/blob/24c2a3f0016357635922e46a5fb30a902fba6790/scripts/update_from_crowdin.mts#L19)):*
<details><summary><i>Previously, pmachapman (Peter Chapman) wrote…</i></summary><blockquote>

Can we `throw` (or `console.error('...'); Deno.exit(1);`) if the status code is other than 200?
</blockquote></details>

Done.
___
*[`scripts/update_from_crowdin.mts` line 32 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/2866#-ODCojqNEbo5fBJxNsW1:-ODD9frMC61GdDVM-YBO:b-896fix) ([raw file](https://github.com/sillsdev/web-xforge/blob/24c2a3f0016357635922e46a5fb30a902fba6790/scripts/update_from_crowdin.mts#L32)):*
<details><summary><i>Previously, pmachapman (Peter Chapman) wrote…</i></summary><blockquote>

Can we have a `throw` if the status code is other than 200? Otherwise, the loop will keep going forever.
</blockquote></details>

Done.
___
*[`scripts/update_from_crowdin.mts` line 35 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/2866#-ODCp2DH5G--gCnynd7-:-ODD9jVS6RpqcooAPaFE:b-896fix) ([raw file](https://github.com/sillsdev/web-xforge/blob/24c2a3f0016357635922e46a5fb30a902fba6790/scripts/update_from_crowdin.mts#L35)):*
<details><summary><i>Previously, pmachapman (Peter Chapman) wrote…</i></summary><blockquote>

Can we handle error status values like `"canceled"` or `"failed"`, and `throw` if these occur? Otherwise the loop will go forever.

See https://support.crowdin.com/developer/api/v2/#tag/Translations/operation/api.projects.translations.builds.get for status values.
</blockquote></details>

Done.
___
*[`scripts/update_from_crowdin.mts` line 50 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/2866#-ODCrc6kD7yoAn9dz_vN:-ODD9o5Z54B2Z97tqiwi:b-896fix) ([raw file](https://github.com/sillsdev/web-xforge/blob/24c2a3f0016357635922e46a5fb30a902fba6790/scripts/update_from_crowdin.mts#L50)):*
<details><summary><i>Previously, pmachapman (Peter Chapman) wrote…</i></summary><blockquote>

Can we `throw` if the status code is other than 200?
</blockquote></details>

Done.
___
*[`scripts/update_from_crowdin.mts` line 56 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/2866#-ODCuQNnE7kxx7hDvpjB:-ODD9oxC0o-HNtBYh8YE:b-896fix) ([raw file](https://github.com/sillsdev/web-xforge/blob/24c2a3f0016357635922e46a5fb30a902fba6790/scripts/update_from_crowdin.mts#L56)):*
<details><summary><i>Previously, pmachapman (Peter Chapman) wrote…</i></summary><blockquote>

Can we `throw` if the status code is other than 200?
</blockquote></details>

Done.
___
*[`scripts/update_from_crowdin.mts` line 58 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/2866#-ODCuRbD61SPsQzlh2BT:-ODD70NHDXA8UcOinUNP:bd81x52) ([raw file](https://github.com/sillsdev/web-xforge/blob/24c2a3f0016357635922e46a5fb30a902fba6790/scripts/update_from_crowdin.mts#L58)):*
<details><summary><i>Previously, pmachapman (Peter Chapman) wrote…</i></summary><blockquote>

NIT: You could replace this with:
```ts
const buffer = await downloadResponse.bytes();
```
</blockquote></details>

Nice improvement; thanks
___
*[`scripts/update_from_crowdin.mts` line 77 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/2866#-ODCsFrg5Y18Xo-wg865:-ODD72Li6xerkpvNBlfu:bbb5p08) ([raw file](https://github.com/sillsdev/web-xforge/blob/24c2a3f0016357635922e46a5fb30a902fba6790/scripts/update_from_crowdin.mts#L77)):*
<details><summary><i>Previously, pmachapman (Peter Chapman) wrote…</i></summary><blockquote>

Won't we want to `Deno.exit(1)` if we are having an error here?
</blockquote></details>

It's better to throw an error so the try/catch/finally block at the end can clean up. But yes, we should handle failure properly.

**Review by pmachapman — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/2866#-:-ODDBXqO6vO27TqUQqhq:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @Nateowami)

**Pull request merged**
