### PR TITLE
Update to latest version of Machine

### PR DESCRIPTION
**Pull request by ddaspit**
- fixes a crash in Machine that can occur when training some projects

---
This change is [Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/933)

### CODE REVIEW

**Review by RaymondLuong3 — CHANGES_REQUESTED** [review]
Looks good. I'm glad some of the API has been given more descriptive names. Just a few comments.

> Reviewed 7 of 7 files at r1.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/933#-:-MS8xJRt3LjMdlWtMuga:bv3a3qq)* status: all files reviewed, 4 unresolved discussions (waiting on @ddaspit)

___
*[src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.spec.ts, line 1484 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/933#-MS8s2vDBxNe8sIfoSlU:-MS8s2vDBxNe8sIfoSlV:b-8taz2f) ([raw file](https://github.com/sillsdev/web-xforge/blob/8ea12a28df3c6b162737e9358e249891966e613e/src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.spec.ts#L1484)):*
> ```
>     keyEvent.key = str.substring(0, 1);
>     keyEvent.initEvent('keyup', true, true);
> ```
Seems strange that we were only dispatching an event for the first char of the string.
___
*[src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.spec.ts, line 1522 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/933#-MS8xA3W4Ij9pFGTe3nt:-MS8xA3X4SS5MFBikpNh:b8nuj4) ([raw file](https://github.com/sillsdev/web-xforge/blob/44abdc67f4a68059ea7a6bc63e0e0f58b3e615d5/src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.spec.ts#L1522)):*
> ```
>       if (targetWord === 'source') {
>         targetWord = 'target';
>       }
> ```
Why is it necessary to change to word to be 'target'?
___
*[src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.spec.ts, line 1532 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/933#-MS8wyiA9RPzycYaDAIl:-MS8wyiA9RPzycYaDAIm:bndhk2c) ([raw file](https://github.com/sillsdev/web-xforge/blob/44abdc67f4a68059ea7a6bc63e0e0f58b3e615d5/src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.spec.ts#L1532)):*
> ```
> new WordGraphArc(i, i + 1, -11, ['versa'], alignment, createRange(i, i + 1), [TranslationSources.Smt], [0.4])
> ```
Is that supposed to be `['verse']` ?
___
*[src/SIL.XForge.Scripture/Services/SFScriptureText.cs, line 37 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/933#-MS8w3Pp5lI0LSCel2bj:-MS8w3Pp5lI0LSCel2bk:b-6e5f2t) ([raw file](https://github.com/sillsdev/web-xforge/blob/44abdc67f4a68059ea7a6bc63e0e0f58b3e615d5/src/SIL.XForge.Scripture/Services/SFScriptureText.cs#L37)):*
> ```
>  public string SortKey => Id;
> ```
Where is this being used?

**Review by ddaspit — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/933)* status: 6 of 7 files reviewed, 4 unresolved discussions (waiting on @RaymondLuong3)

___
*[src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.spec.ts, line 1484 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/933#-MS8s2vDBxNe8sIfoSlU:-MSB-6Yv9BqT1Y_F2ra3:bic8ipe) ([raw file](https://github.com/sillsdev/web-xforge/blob/8ea12a28df3c6b162737e9358e249891966e613e/src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.spec.ts#L1484)):*
<details><summary><i>Previously, RaymondLuong3 (Raymond Luong) wrote…</i></summary><blockquote>

> ```
>     keyEvent.key = str.substring(0, 1);
>     keyEvent.initEvent('keyup', true, true);
> ```
Seems strange that we were only dispatching an event for the first char of the string.
</blockquote></details>

We were only ever passing a single character to `typeCharacters`, so it was fine. I updated one of the calls to `typeCharacters` to pass a string with multiple characters, so I changed the code so it could handle that.
___
*[src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.spec.ts, line 1522 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/933#-MS8xA3W4Ij9pFGTe3nt:-MSB-dib6WkPbXP8SolO:bev950x) ([raw file](https://github.com/sillsdev/web-xforge/blob/44abdc67f4a68059ea7a6bc63e0e0f58b3e615d5/src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.spec.ts#L1522)):*
<details><summary><i>Previously, RaymondLuong3 (Raymond Luong) wrote…</i></summary><blockquote>

> ```
>       if (targetWord === 'source') {
>         targetWord = 'target';
>       }
> ```
Why is it necessary to change to word to be 'target'?
</blockquote></details>

This code is simulating the translation of the segment. Our translation is basically replace `source` with `target`.
___
*[src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.spec.ts, line 1532 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/933#-MS8wyiA9RPzycYaDAIl:-MSB-ukQE3Hpz2SFe0gh:b-j9bn21) ([raw file](https://github.com/sillsdev/web-xforge/blob/44abdc67f4a68059ea7a6bc63e0e0f58b3e615d5/src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.spec.ts#L1532)):*
<details><summary><i>Previously, RaymondLuong3 (Raymond Luong) wrote…</i></summary><blockquote>

> ```
> new WordGraphArc(i, i + 1, -11, ['versa'], alignment, createRange(i, i + 1), [TranslationSources.Smt], [0.4])
> ```
Is that supposed to be `['verse']` ?
</blockquote></details>

It is correct. `versa` is the translation for `verse`.
___
*[src/SIL.XForge.Scripture/Services/SFScriptureText.cs, line 37 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/933#-MS8w3Pp5lI0LSCel2bj:-MSB04QOBOAvEuEsKhrQ:bj8bhsu) ([raw file](https://github.com/sillsdev/web-xforge/blob/44abdc67f4a68059ea7a6bc63e0e0f58b3e615d5/src/SIL.XForge.Scripture/Services/SFScriptureText.cs#L37)):*
<details><summary><i>Previously, RaymondLuong3 (Raymond Luong) wrote…</i></summary><blockquote>

> ```
>  public string SortKey => Id;
> ```
Where is this being used?
</blockquote></details>

This is an implementation of a Machine interface. Machine uses this property internally.

**Review by RaymondLuong3 — APPROVED** [review]
It needs a rebase and then :lgtm: 

> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/933#-:-MSEGbP22cQqGRiV56n9:b5aoabo)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by irahopkinson — APPROVED** [review]
> Reviewed 2 of 2 files at r3.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/933)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ddaspit)

**Pull request merged**
