### PR TITLE
SF-1691 Show indication in menu when sync has failed

### PR DESCRIPTION
**Pull request by Nateowami**
This is done in hope that projects that have had a sync failure are more likely to notice and reach out to us.

- - -
This change is [Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1475)

### CODE REVIEW

**Comment by marksvc** [comment]
*[`src/SIL.XForge.Scripture/ClientApp/src/app/app.component.spec.ts` line 398 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/1475#-N9gw39T-3BZzlrTwbTI:-N9gw39T-3BZzlrTwbTJ:bejn9zc) ([raw file](https://github.com/sillsdev/web-xforge/blob/ab4b6cfe93cbc55601c42aa0b9061dc25a1ea109/src/SIL.XForge.Scripture/ClientApp/src/app/app.component.spec.ts#L398)):*
> ```XML
>     expect(env.lastSyncFailedBadge).toBeNull();
> 
>     env.setLastSyncSuccessful('project02', false);
> ```

I don't know why the DOM's badge doesn't seem to be updating from how the code is querying it, when the last-sync setting is changed. But one way that can work is to check if the icon has class mat-badge-hidden, as demonstrated in fix/SF-1691-sync-failure-badge-idea1. Then we can 
- explicitly set last-sync-successful to true
- assert that the badge is not shown
- set last-sync-successful to false (on the same project)
- assert that the badge is shown

What do you think of doing it that way?



_Code quote:_
```XML
project02
```

**Review by Nateowami — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1475)* status: 0 of 5 files reviewed, 1 unresolved discussion (waiting on @marksvc)

___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/app.component.spec.ts` line 398 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/1475#-N9gw39T-3BZzlrTwbTI:-N9hvG5e57M_MB-kFrJG:b-i21bbo) ([raw file](https://github.com/sillsdev/web-xforge/blob/ab4b6cfe93cbc55601c42aa0b9061dc25a1ea109/src/SIL.XForge.Scripture/ClientApp/src/app/app.component.spec.ts#L398)):*
<details><summary><i>Previously, marksvc wrote…</i></summary><blockquote>

I don't know why the DOM's badge doesn't seem to be updating from how the code is querying it, when the last-sync setting is changed. But one way that can work is to check if the icon has class mat-badge-hidden, as demonstrated in fix/SF-1691-sync-failure-badge-idea1. Then we can 
- explicitly set last-sync-successful to true
- assert that the badge is not shown
- set last-sync-successful to false (on the same project)
- assert that the badge is shown

What do you think of doing it that way?
</blockquote></details>

Thanks. Done.

**Review by marksvc — APPROVED** [review]
> Reviewed 4 of 5 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1475)* status: all files reviewed, 2 unresolved discussions (waiting on @Nateowami)

___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/app.component.scss` line 231 at r2](https://reviewable.io/reviews/sillsdev/web-xforge/1475#-NA5mBO81xkNp1ElUEnQ:-NA5mBO81xkNp1ElUEnR:b-gru8gy) ([raw file](https://github.com/sillsdev/web-xforge/blob/7c48368b43a54677c464b0f7f10d257f4a911687/src/SIL.XForge.Scripture/ClientApp/src/app/app.component.scss#L231)):*
> ```SCSS
> }
> 
> ::ng-deep #sync-icon .mat-badge-content {
> ```

When I looked this up, the two pages I looked at both mentioned that ::ng-deep is deprecated, so it might work against us to be introducing it at this stage.



_Code quote:_
```SCSS
::ng-deep 
```
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/app.component.ts` line 532 at r2](https://reviewable.io/reviews/sillsdev/web-xforge/1475#-NA5mZSO3J9uAtUXdKAx:-NA5mZSO3J9uAtUXdKAy:bdwfl2m) ([raw file](https://github.com/sillsdev/web-xforge/blob/7c48368b43a54677c464b0f7f10d257f4a911687/src/SIL.XForge.Scripture/ClientApp/src/app/app.component.ts#L532)):*
> ```XML
> 
>   get lastSyncFailed(): boolean {
>     return this.selectedProjectDoc?.data?.sync.lastSyncSuccessful === false;
> ```

Haha, so we query if `lastSyncSuccessful`. Then we reverse it for `lastSyncFailed()`. Then in the html we reverse it to know if the sync was successful, to know if matBadgeHidden should be true. You might consider if this should instead start out as `get lastSyncSuccessful():boolean`. 
It's ok.

Oh nevermind, then that complicates the situation where there has not yet been a synchronization. Whereas the way the code is written in this PR, we can just return false for that situation. So `lastSyncFailed()` has that advantage. 



_Code quote:_
```XML
  get lastSyncFailed(): boolean {
    return this.selectedProjectDoc?.data?.sync.lastSyncSuccessful === false;
```

**Review by Nateowami — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1475)* status: all files reviewed, 2 unresolved discussions (waiting on @marksvc)

___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/app.component.scss` line 231 at r2](https://reviewable.io/reviews/sillsdev/web-xforge/1475#-NA5mBO81xkNp1ElUEnQ:-NA61trECsHHVxB8jozq:bt09dda) ([raw file](https://github.com/sillsdev/web-xforge/blob/7c48368b43a54677c464b0f7f10d257f4a911687/src/SIL.XForge.Scripture/ClientApp/src/app/app.component.scss#L231)):*
<details><summary><i>Previously, marksvc wrote…</i></summary><blockquote>

When I looked this up, the two pages I looked at both mentioned that ::ng-deep is deprecated, so it might work against us to be introducing it at this stage.
</blockquote></details>

I know, but I'm not aware of a good alternative. We're a couple versions behind the latest Angular release, so even if they remove it tomorrow (and I think there would be an uproar if they did), there would still be a couple version before it would reach us.
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/app.component.ts` line 532 at r2](https://reviewable.io/reviews/sillsdev/web-xforge/1475#-NA5mZSO3J9uAtUXdKAx:-NA61jfg0nCEVtWfsk9F:bc6fsp2) ([raw file](https://github.com/sillsdev/web-xforge/blob/7c48368b43a54677c464b0f7f10d257f4a911687/src/SIL.XForge.Scripture/ClientApp/src/app/app.component.ts#L532)):*
<details><summary><i>Previously, marksvc wrote…</i></summary><blockquote>

Haha, so we query if `lastSyncSuccessful`. Then we reverse it for `lastSyncFailed()`. Then in the html we reverse it to know if the sync was successful, to know if matBadgeHidden should be true. You might consider if this should instead start out as `get lastSyncSuccessful():boolean`. 
It's ok.

Oh nevermind, then that complicates the situation where there has not yet been a synchronization. Whereas the way the code is written in this PR, we can just return false for that situation. So `lastSyncFailed()` has that advantage. 
</blockquote></details>

Yes. Failed and successful are not collectively exhaustive. We show the badge if it's known to have failed. Which is when `lastSyncSuccessful === false`.

**Pull request merged**
