### PR TITLE
SF-3049 Fix sync error when user no longer on back translation

### PR DESCRIPTION
**Pull request by kylebuss**
This PR checks that a user is still on a back translation project before continuing the Sync process. If the user is no longer found on the project an error will be thrown and dialog message displayed to the user.

- - -
This change is [Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/2822)

### CODE REVIEW

**Review by RaymondLuong3 — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/2822)* status: all files reviewed, 1 unresolved discussion (waiting on @kylebuss)

___
*[`src/SIL.XForge.Scripture/Services/ParatextService.cs` line 810 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/2822#-OA4W0Fh18CHsreIhHPR:-OA4W0Fh18CHsreIhHPS:b-c7nf50) ([raw file](https://github.com/sillsdev/web-xforge/blob/09d57bb5060219d5c724cb22235e9eea743b8e89/src/SIL.XForge.Scripture/Services/ParatextService.cs#L810)):*
> ```Smalltalk
>             // on project with permission to sync or return an error to UI
>             if (!users.Select(u => u.Id).ToList().Contains(userSecret.Id))
>                 throw new ForbiddenException();
> ```

Would it be simple to add a test to show that this exception is thrown when the user is not on the project? It would be worth doing if it was not too difficult.



_Code quote:_
```Smalltalk
            if (!users.Select(u => u.Id).ToList().Contains(userSecret.Id))
                throw new ForbiddenException();
```

**Review by kylebuss — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/2822)* status: all files reviewed, 1 unresolved discussion (waiting on @RaymondLuong3)

___
*[`src/SIL.XForge.Scripture/Services/ParatextService.cs` line 810 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/2822#-OA4W0Fh18CHsreIhHPR:-OAI-e8yDBtnzMu0n0_J:bn5pk62) ([raw file](https://github.com/sillsdev/web-xforge/blob/09d57bb5060219d5c724cb22235e9eea743b8e89/src/SIL.XForge.Scripture/Services/ParatextService.cs#L810)):*
<details><summary><i>Previously, RaymondLuong3 (Raymond Luong) wrote…</i></summary><blockquote>

Would it be simple to add a test to show that this exception is thrown when the user is not on the project? It would be worth doing if it was not too difficult.
</blockquote></details>

I did add one test to the `ParatextSyncRunnerTests.cs` to test when the project is a Back Translation and the user is no longer on the project. I can add an additional test to the `ParatextServiceTests.cs` if you think we need it?

**Comment by RaymondLuong3** [comment]
Yes, the test you added does not actually test the code you added in ParatextService.

**Review by kylebuss — COMMENTED** [review]
Test added.

> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/2822#-:-OAJktry4yG6X1SB9t51:b-65kv61)* status: 2 of 3 files reviewed, 1 unresolved discussion (waiting on @RaymondLuong3)

**Review by RaymondLuong3 — APPROVED** [review]
Nice work!

> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/2822#-:-OAJxsnf4Jxfmw_j8jsV:bdtx8r6)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @kylebuss)

**Pull request merged**
