### PR TITLE
doc: add section on invalidating refresh tokens

### PR DESCRIPTION
**Pull request by marksvc**
This change is [Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1643)

### CODE REVIEW

**Comment by marksvc** [comment]
@Nateowami Hmm, this was composed before our discussion of manual wrapping in the .md file. Are you wanting individual paragraphs to be on the same line, rather than broken apart with newlines as in this PR?

**Comment by Nateowami** [comment]
I'm concerned our README is getting unweildy. Originally it provided basic documentation, but as we start to add lengthy sections on increasingly obscure topics, I think it may be time to create a developer documentation folder and have individual files there.

**Comment by pmachapman** [comment]
> I'm concerned our README is getting unwieldy.

Do we want to keep developer information like this in a [GitHub wiki](https://docs.github.com/en/communities/documenting-your-project-with-wikis/about-wikis)?

Other projects I have forked have used a `/Documentation/` folder, with multiple md files, but I have found that approach to be difficult to find information in, unless that information automatically is published to a static website.

**Comment by Nateowami** [comment]
That is a good point. Given that there are multiple options with pros and cons, I don't want this to hold up this PR (or #1641). Let's get this into the README for now, and decide how we want to handle documentation going forward.

Regardless of what we choose, as long as it's in a standard format like Markdown, I think we can easily change our minds later. I like the GitHub wiki idea.

**Review by pmachapman — APPROVED** [review]
Looks good! As per the PR discussion, the README is the best place for this info until there is a wiki or other system.

**Pull request merged**
