### PR TITLE
SF-2916 Change display name label on join component

### PR DESCRIPTION
**Pull request by nigel-wells**
Settled on option one as it gave more room for the text to grow in other languages.

**Option One**
Screenshot 2024-08-13 151557

**Option Two**
Screenshot 2024-08-13 151614

**Option Three**
Screenshot 2024-08-13 151638

- - -
This change is [Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/2672)

### CODE REVIEW

**Review by josephmyers — CHANGES_REQUESTED** [review]
Option 1 looks fine, thanks for throwing all these out. I do think having the second line busies things up to where people could easily miss it, and I wonder if we could avoid that. What if we did something like this:



> Reviewed 1 of 2 files at r1, 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/2672#-:-O4DQB3s5i1LCXX_3s8t:b6ofbgi)* status: all files reviewed, 1 unresolved discussion (waiting on @nigel-wells)

___
*[`src/SIL.XForge.Scripture/ClientApp/src/assets/i18n/checking_en.json` line 350 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/2672#-O4DQK8Q7B4FpDI_mbVf:-O4DQK8Q7B4FpDI_mbVg:b-ozdujk) ([raw file](https://github.com/sillsdev/web-xforge/blob/0807ac0f17fb434ee1cf35e09297689ee6d9ca21/src/SIL.XForge.Scripture/ClientApp/src/assets/i18n/checking_en.json#L350)):*
> ```JSON
>     "project_link_is_invalid": "The project link is invalid. Please contact the person who sent you the link and ask for a new one.",
>     "role_not_found": "The role you were assigned on this project is no longer available. Please contact the person who sent you the link and ask for a new one.",
>     "your_name": "Your name"
> ```

I do like Option 1 best, but I think this should say "Your display name"

As it is, it seems like it could contradict the instructions above

**Review by nigel-wells — COMMENTED** [review]
I like you're thinking. How about we move "join" on to its own line so that the project name can stand out on its own as the most important thing:


> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/2672#-:-O4E4npvBCMyTr7kauea:bvjmz6a)* status: 1 of 4 files reviewed, 1 unresolved discussion (waiting on @josephmyers)

___
*[`src/SIL.XForge.Scripture/ClientApp/src/assets/i18n/checking_en.json` line 350 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/2672#-O4DQK8Q7B4FpDI_mbVf:-O4E228rDTRIlpVLxmz7:bb6un1j) ([raw file](https://github.com/sillsdev/web-xforge/blob/0807ac0f17fb434ee1cf35e09297689ee6d9ca21/src/SIL.XForge.Scripture/ClientApp/src/assets/i18n/checking_en.json#L350)):*
<details><summary><i>Previously, josephmyers wrote…</i></summary><blockquote>

I do like Option 1 best, but I think this should say "Your display name"

As it is, it seems like it could contradict the instructions above
</blockquote></details>

Done

**Review by josephmyers — APPROVED** [review]
:lgtm:

Awesome, thanks

> Reviewed 4 of 4 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/2672#-:-O4END7bACvbma9m0yRY:bsdl95b)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @nigel-wells)

**Review by josephmyers — CHANGES_REQUESTED** [review]
I just saw that the story "Join with share key:Offline Notice When Joining" story revealed a potential offline issue from these changes. Can you look into it?

> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/2672#-:-O4EOXnxAtsfq7HHFl8L:b-nwwzm7)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @nigel-wells)

**Comment by Nateowami** [comment]
I really like the direction this went where the amount of text before the input was reduced/optimized to be less of a wall of text.

However, I really don't like the phrase "Your display name". The phrase "display name" seems to me like a developer term. I'm guessing you were trying to avoid "Your name", since that seems to imply it needs to be their real name. What about just "Name"?

**Comment by nigel-wells** [comment]
I've updated the strings to be "Name"

**Comment by nigel-wells** [comment]
I've pushed through an update to the storybook as well. The Story is a bit of an odd one and the state probably isn't "real" as you have to bee online to even load the Join page but the error is occurring as if it hasn't really loaded yet. I've improved it though.

**Review by josephmyers — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r4, 2 of 2 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/2672#-:-O4cS2AX2gpdA59PrWcA:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @nigel-wells)

**Pull request merged**
