### PR TITLE
dev: add attach to realtime server

### PR DESCRIPTION
**Pull request by marksvc**
commit-id:c1504a7d

- - -
This change is [Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1559)

### CODE REVIEW

**Review by nigel-wells — CHANGES_REQUESTED** [review]
I'll need you to run this through with me as I couldn't get it working. I also stumbled upon some code Ira added into `RealtimeServiceCollectionExtensions.cs` which lets you start the Realtime Server with inspection enabled. I wonder if this would be a good flag to be switched on along with your changes above as this lets you debug the Realtime Server right from the start rather than attaching at a later point in time.

> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1559#-:-NFMQvHO9gDZRNND-dCA:b-r18abm)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @marksvc)

**Comment by marksvc** [comment]
This is working well for me on my machine. I'm not sure if it's very meaningful to leave in the `options.TimeoutMS = -1`, but I left it.

**Comment by marksvc** [comment]
It's been re-worked.

**Review by nigel-wells — APPROVED** [review]
Thanks for working through this - its working great. Thanks for tidying up the README as well to make it clear which backend is being tested.

:lgtm:

> Reviewed 1 of 3 files at r2, 5 of 5 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1559#-:-NFetYk-7XNLyjezNgU_:bvdlqjg)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @marksvc)

**Pull request merged**
