### PR TITLE
SF 2072 Replace MDC buttons with Material in checking component

### PR DESCRIPTION
**Pull request by spark005**
Checked this with buttons that are in the questions and answers. Let me know if code is incorrect

- - -
This change is [Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1987)

### CODE REVIEW

**Review by Nateowami — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1987)* status: 0 of 1 files reviewed, 2 unresolved discussions (waiting on @spark005)

___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking.component.html` line 120 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/1987#-NasW-zjAWD8Nltng2wF:-NasW-zjAWD8Nltng2wG:b-vcp9m6) ([raw file](https://github.com/sillsdev/web-xforge/blob/f93a01086b18fe8cfca4bd4397fd5dd87fe916cf/src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking.component.html#L120)):*
> ```HTML
>                       class="add-question-button"
>                     >
>                       <mdc-icon class="mirror-rtl">post_add</mdc-icon> <span>{{ t("add_question") }}</span>
> ```

This should be replaced with a Material icon.
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking.component.html` line 185 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/1987#-NasVxvT9jjsPcPDIab4:-NasVxvU7PpXM08qtGeK:b-zf6jmj) ([raw file](https://github.com/sillsdev/web-xforge/blob/f93a01086b18fe8cfca4bd4397fd5dd87fe916cf/src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking.component.html#L185)):*
> ```HTML
>         <div *ngIf="projectDoc" id="project-navigation">
>           <button mat-button *ngIf="!this.isDrawerPermanent" type="button" (click)="toggleDrawer()">
>             <span class="mdc-button__label">{{ t("view_questions") }}</span>
> ```

This use of MDC should be removed.

**Review by Nateowami — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1987)* status: 0 of 1 files reviewed, 2 unresolved discussions (waiting on @spark005)

___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking.component.html` line 185 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/1987#-NasVxvT9jjsPcPDIab4:-NasXcB64hlpQuLj13Pg:bldg0fb) ([raw file](https://github.com/sillsdev/web-xforge/blob/f93a01086b18fe8cfca4bd4397fd5dd87fe916cf/src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking.component.html#L185)):*
<details><summary><i>Previously, Nateowami (Nathaniel Paulus) wrote…</i></summary><blockquote>

This use of MDC should be removed.
</blockquote></details>

I looked into why this span with the `mdc-button__label` class exists, and I can't find any good reason. I think it was a mistake and can be removed.

**Review by Nateowami — CHANGES_REQUESTED** [review]
Thanks for your work on this. There are a couple more things to address.

Also, could you update the pull request title? It should contain the issue first, and then a description of what is fixed.

> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1987#-:-Nax5YFE-1zuXG2jdRq_:b-bkeor6)* status: 0 of 1 files reviewed, 2 unresolved discussions (waiting on @spark005)

___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking.component.html` line 120 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/1987#-NasW-zjAWD8Nltng2wF:-NavyOtP8OiOhXpQqusN:by0sohu) ([raw file](https://github.com/sillsdev/web-xforge/blob/f93a01086b18fe8cfca4bd4397fd5dd87fe916cf/src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking.component.html#L120)):*
<details><summary><i>Previously, Nateowami (Nathaniel Paulus) wrote…</i></summary><blockquote>

This should be replaced with a Material icon.
</blockquote></details>

The class name `mat-icon-rtl-mirror` is wrong. Maybe you were tying to add two class names? I'm not sure why this would need a `mat-icon` class.
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking.component.html` line 185 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/1987#-NasVxvT9jjsPcPDIab4:-NavyICS7SWkhdGCKss6:b-4udzyv) ([raw file](https://github.com/sillsdev/web-xforge/blob/f93a01086b18fe8cfca4bd4397fd5dd87fe916cf/src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking.component.html#L185)):*
<details><summary><i>Previously, Nateowami (Nathaniel Paulus) wrote…</i></summary><blockquote>

I looked into why this span with the `mdc-button__label` class exists, and I can't find any good reason. I think it was a mistake and can be removed.
</blockquote></details>

The whole span should be removed. As far as I can tell it is completely unnecessary.

**Comment by spark005** [comment]
Screen Shot 2023-08-03 at 9 22 32 PM
The documentation used `mat-icon-rtl-mirror` so thats why I had it like that

I also had problems with the image disappearing but I messaged you in slack with more details on that

**Review by Nateowami — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1987)* status: 0 of 1 files reviewed, 2 unresolved discussions (waiting on @spark005)

___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking.component.html` line 120 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/1987#-NasW-zjAWD8Nltng2wF:-Nb17Uxs82AxDm9YQD63:b2mx7r8) ([raw file](https://github.com/sillsdev/web-xforge/blob/f93a01086b18fe8cfca4bd4397fd5dd87fe916cf/src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking.component.html#L120)):*
<details><summary><i>Previously, Nateowami (Nathaniel Paulus) wrote…</i></summary><blockquote>

The class name `mat-icon-rtl-mirror` is wrong. Maybe you were tying to add two class names? I'm not sure why this would need a `mat-icon` class.
</blockquote></details>

Let's avoid using `fontIcon`, as it's not something we use anywhere else. 

I wasn't aware `mat-icon-rtl-mirror` existed. Good job finding that. We have a different class, `mirror-rtl` that should be used instead, because it's what we've been using everywhere else, and for other reasons I won't go into (in certain situations they would work differently). It's defined in `src/SIL.XForge.Scripture/ClientApp/src/styles.scss`.

Also, if you could link to documentation in the future instead of screenshots that would be great. It took me a couple minutes to find the documentation you were looking at.
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking.component.html` line 112 at r3](https://reviewable.io/reviews/sillsdev/web-xforge/1987#-Nb1ABRJD6BGIJ4HluSk:-Nb1ABRK7tJHAgnXpcYZ:buh2kl9) ([raw file](https://github.com/sillsdev/web-xforge/blob/19f7ab353a1475b9ec4867b6c8b8496d8f3452ef/src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking.component.html#L112)):*
> ```HTML
>                       (click)="questionDialog()"
>                       class="add-question-button"
>                     ></button>
> ```

This button (shown on smaller screens because of `fxShow.lt-xl`) never shows up because it is implemented completely wrong. See https://v14.material.angular.io/components/button/overview for examples of how an icon button should be done. For example:
``` html
<button mat-icon-button>
  <mat-icon>home</mat-icon>
</button>
```
I think `icon="post_add"` is the MDC way of specifying the icon.

**Review by Nateowami — APPROVED** [review]
Looks good.
:lgtm:

> Reviewed 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1987#-:-NbRuisW8koD0-ehshIS:b-saczm2)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @spark005)

**Pull request merged**
