### PR TITLE
SF-2130 Integrate AudioPlayer into Existing Components

### PR DESCRIPTION
**Pull request by nigel-wells**
- Deleted old audio component and renamed new audio component
- Adapted some tests to wait for a newly introduced timer
- Wait for audio to finish init phase before displaying
- Adjusted audio ready events depending on source being a blob

- - -
This change is [Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1999)

### CODE REVIEW

**Comment by josephmyers** [comment]
[bug.zip](https://github.com/sillsdev/web-xforge/files/12308021/bug.zip)

I'm seeing an issue with recordings. It's weird, since that's what you just fixed. Maybe our machines are behaving differently? Are you on Windows and Chrome?

**Review by josephmyers — CHANGES_REQUESTED** [review]
Thanks for your work on this. Just a couple things (see attachment above)

> Reviewed 17 of 17 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1999#-:-NbS68e0-dh1NLlZSdH-:bhy9858)* status: all files reviewed, 3 unresolved discussions (waiting on @nigel-wells)

___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-audio-player/checking-audio-player.component.spec.ts` line 16 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/1999#-NbS267i9At-HdCqyMuE:-NbS267i9At-HdCqyMuF:blgfauv) ([raw file](https://github.com/sillsdev/web-xforge/blob/c71ede2ca5b4a4dd9b74b0d1b6e868bb42e2ce15/src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-audio-player/checking-audio-player.component.spec.ts#L16)):*
> ```XML
> import { CheckingAudioPlayerComponent } from './checking-audio-player.component';
> 
> describe('CheckingAudioPlayerComponent', () => {
> ```

A couple days, you mentioned that you thought the tests weren't fully aligned with how we're using the data. I haven't seen any new or modified tests so far, but now would be a good time to fill in those gaps. Would you be willing to do so?
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/shared/audio/audio-player.ts` line 27 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/1999#-NbS3Zyt9jKdXG3_uoU9:-NbS3Zyt9jKdXG3_uoUA:b-qew8e4) ([raw file](https://github.com/sillsdev/web-xforge/blob/c71ede2ca5b4a4dd9b74b0d1b6e868bb42e2ce15/src/SIL.XForge.Scripture/ClientApp/src/app/shared/audio/audio-player.ts#L27)):*
> ```XML
>   readonly finishedPlaying$: EventEmitter<void> = new EventEmitter<void>();
> 
>   constructor(source: string, private readonly pwaService: PwaService) {
> ```

Maybe the recording issue is coming from here?
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/shared/audio/audio-player-base/audio-player-base.component.ts` line 12 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/1999#-NbS3tFP75TFpqk9FfFi:-NbS3tFP75TFpqk9FfFj:b-k39k86) ([raw file](https://github.com/sillsdev/web-xforge/blob/c71ede2ca5b4a4dd9b74b0d1b6e868bb42e2ce15/src/SIL.XForge.Scripture/ClientApp/src/app/shared/audio/audio-player-base/audio-player-base.component.ts#L12)):*
> ```XML
> export abstract class AudioPlayerBaseComponent extends SubscriptionDisposable implements OnDestroy {
>   readonly isAudioAvailable$: BehaviorSubject<boolean> = new BehaviorSubject<boolean>(false);
>   isAudioInitComplete: boolean = false;
> ```

Let's make this field private with a public getter. I wouldn't want that publicly changeable.

**Review by nigel-wells — COMMENTED** [review]
Always appreciate others testing things slightly differently - the video was very helpful!
I've made an adjustment to the method we use for recording audio which provides much be reliable results for getting the duration - I found this from looking through similar issues in the RecordRTC repo. Give it a go now and let me know if you can still break it.

> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1999#-:-NbSgtHKDQfwtvkoKAWU:b-chmeib)* status: 15 of 18 files reviewed, 3 unresolved discussions (waiting on @josephmyers)

___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-audio-player/checking-audio-player.component.spec.ts` line 16 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/1999#-NbS267i9At-HdCqyMuE:-NbSMdGTCnQXDwrLhYkd:b-394nzl) ([raw file](https://github.com/sillsdev/web-xforge/blob/c71ede2ca5b4a4dd9b74b0d1b6e868bb42e2ce15/src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-audio-player/checking-audio-player.component.spec.ts#L16)):*
<details><summary><i>Previously, josephmyers wrote…</i></summary><blockquote>

A couple days, you mentioned that you thought the tests weren't fully aligned with how we're using the data. I haven't seen any new or modified tests so far, but now would be a good time to fill in those gaps. Would you be willing to do so?
</blockquote></details>

The tests we have already cover blobs and physical files as a source so I felt nothing new needed to be introduced. The app appears to always use blobs now. We could add another test for the sake of aligning more with the app but I don't think coverage would improve as a result? 
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/shared/audio/audio-player.ts` line 27 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/1999#-NbS3Zyt9jKdXG3_uoU9:-NbShDcEBZiU1Lv3zBgt:b-v0uu9y) ([raw file](https://github.com/sillsdev/web-xforge/blob/c71ede2ca5b4a4dd9b74b0d1b6e868bb42e2ce15/src/SIL.XForge.Scripture/ClientApp/src/app/shared/audio/audio-player.ts#L27)):*
<details><summary><i>Previously, josephmyers wrote…</i></summary><blockquote>

Maybe the recording issue is coming from here?
</blockquote></details>

I adjusted the recording type in the end - hopefully that does the trick.
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/shared/audio/audio-player-base/audio-player-base.component.ts` line 12 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/1999#-NbS3tFP75TFpqk9FfFi:-NbSNC1p2-iEpVeM4uaF:b-ax0l67) ([raw file](https://github.com/sillsdev/web-xforge/blob/c71ede2ca5b4a4dd9b74b0d1b6e868bb42e2ce15/src/SIL.XForge.Scripture/ClientApp/src/app/shared/audio/audio-player-base/audio-player-base.component.ts#L12)):*
<details><summary><i>Previously, josephmyers wrote…</i></summary><blockquote>

Let's make this field private with a public getter. I wouldn't want that publicly changeable.
</blockquote></details>

But I'm a lazy programmer by default :) Done.

**Review by josephmyers — CHANGES_REQUESTED** [review]
That got it! Good job

> Reviewed 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1999#-:-Nbmkgor5ueExTtPko3w:b-3tl5p0)* status: all files reviewed, 2 unresolved discussions (waiting on @nigel-wells)

___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-audio-player/checking-audio-player.component.spec.ts` line 16 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/1999#-NbS267i9At-HdCqyMuE:-NbmW_kk8n0k2EYkILas:b-d52y9k) ([raw file](https://github.com/sillsdev/web-xforge/blob/c71ede2ca5b4a4dd9b74b0d1b6e868bb42e2ce15/src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-audio-player/checking-audio-player.component.spec.ts#L16)):*
<details><summary><i>Previously, nigel-wells (Nigel Wells) wrote…</i></summary><blockquote>

The tests we have already cover blobs and physical files as a source so I felt nothing new needed to be introduced. The app appears to always use blobs now. We could add another test for the sake of aligning more with the app but I don't think coverage would improve as a result? 
</blockquote></details>

Maybe I'm missing something. I only see one test for a blob at this level, and it's testing a failure case (not helping much in isolation). Now, I added blob tests at the add audio dialog level, but that's not related to this. All the tests here, except the one, appear to be testing files (e.g. "http://localhost:9876/assets/audio/test-audio-player.webm").

Ironically, there is another test in this file that says it tests blobs, but I don't think it does. It was changed, three years ago, to be the exact same as the test below it, which tests "preloaded audio." See the blame on line 83. So I think fixing that test would be a good start. If you want to do more testing, great, but I won't push for more.
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-audio-recorder/checking-audio-recorder.component.ts` line 119 at r2](https://reviewable.io/reviews/sillsdev/web-xforge/1999#-Nbmhk38CKeatq33Luot:-Nbmhk38CKeatq33Luou:b-v4f9w2) ([raw file](https://github.com/sillsdev/web-xforge/blob/5a5264db9e8a6abb1752f92a8445eedff24aad7e/src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-audio-recorder/checking-audio-recorder.component.ts#L119)):*
> ```XML
>       recorderType: RecordRTC.MediaStreamRecorder
>     };
>     // Fallback for devices not supporting the native Media Recording API i.e. Safari/iOS
> ```

Whoah! This fix is crazy. Can we add a test for this? I want to make sure the bug case I was seeing is covered, so we don't reintroduce it down the road. By that, I mean when this bug was in there, there should have been a test failing. That there wasn't indicates we have a gap in coverage. Can you do this?

**Review by nigel-wells — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1999)* status: 13 of 18 files reviewed, 2 unresolved discussions (waiting on @josephmyers)

___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-audio-player/checking-audio-player.component.spec.ts` line 16 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/1999#-NbS267i9At-HdCqyMuE:-NcPUobu7qg2yqbmHfgI:bgxoq6d) ([raw file](https://github.com/sillsdev/web-xforge/blob/c71ede2ca5b4a4dd9b74b0d1b6e868bb42e2ce15/src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-audio-player/checking-audio-player.component.spec.ts#L16)):*
<details><summary><i>Previously, josephmyers wrote…</i></summary><blockquote>

Maybe I'm missing something. I only see one test for a blob at this level, and it's testing a failure case (not helping much in isolation). Now, I added blob tests at the add audio dialog level, but that's not related to this. All the tests here, except the one, appear to be testing files (e.g. "http://localhost:9876/assets/audio/test-audio-player.webm").

Ironically, there is another test in this file that says it tests blobs, but I don't think it does. It was changed, three years ago, to be the exact same as the test below it, which tests "preloaded audio." See the blame on line 83. So I think fixing that test would be a good start. If you want to do more testing, great, but I won't push for more.
</blockquote></details>

Yeah, you're right. I've changed the one to use a blob file and then created another similar variation of the "can play" test to also use a blob
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-audio-recorder/checking-audio-recorder.component.ts` line 119 at r2](https://reviewable.io/reviews/sillsdev/web-xforge/1999#-Nbmhk38CKeatq33Luot:-NcQ-Rf4BU1Z-FIN7bE6:b-thjkhe) ([raw file](https://github.com/sillsdev/web-xforge/blob/5a5264db9e8a6abb1752f92a8445eedff24aad7e/src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-audio-recorder/checking-audio-recorder.component.ts#L119)):*
<details><summary><i>Previously, josephmyers wrote…</i></summary><blockquote>

Whoah! This fix is crazy. Can we add a test for this? I want to make sure the bug case I was seeing is covered, so we don't reintroduce it down the road. By that, I mean when this bug was in there, there should have been a test failing. That there wasn't indicates we have a gap in coverage. Can you do this?
</blockquote></details>

Good thinking - I've adapted one of the tests to check for this scenario

**Review by josephmyers — APPROVED** [review]
> Reviewed 5 of 5 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1999)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @nigel-wells)

**Pull request merged**
