### PR TITLE
SF-2749 Refactor scrolling to active verse

### PR DESCRIPTION
**Pull request by josephmyers**
- - -
This change is [Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/2596)

### CODE REVIEW

**Review by RaymondLuong3 — CHANGES_REQUESTED** [review]
It looks like you could have created a new input variable on `checking-text.component` and have the `checking.component` provide an observable that emits when the splitter is resized. It would make it so that `scrollToVerse()` is not the responsibility of the parent component. Unless you had a reason to want the parent component to have more control over the scrolling in the `checking-text.component`?

> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/2596#-:-O2QVhLIBT7DILXGcleZ:bk9rqcj)* status: all files reviewed, 2 unresolved discussions (waiting on @josephmyers)

___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking.component.ts` line 1419 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/2596#-O2QUWbl4FiCqzknSbnX:-O2QUWbl4FiCqzknSbnY:b-xz82q8) ([raw file](https://github.com/sillsdev/web-xforge/blob/f70526e210aad7f36f4b6b5ef5236cacd3ab568e/src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking.component.ts#L1419)):*
> ```XML
> 
>   private scrollTo(y: number): void {
>     const editor = this.scripturePanel?.textComponent?.editor?.container.querySelector('.ql-editor');
> ```

Nit: Add a type here.



_Code quote:_
```XML
    const editor
```
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking.component.ts` line 1425 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/2596#-O2QUZ4RCoOwvlQcZmTR:-O2QUZ4RCoOwvlQcZmTS:bo4ctfg) ([raw file](https://github.com/sillsdev/web-xforge/blob/f70526e210aad7f36f4b6b5ef5236cacd3ab568e/src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking.component.ts#L1425)):*
> ```XML
>   }
> 
>   onSplitterResized(): void {
> ```

Move this method above the private methods



_Code quote:_
```XML
  onSplitterResized(): void {
```

**Review by RaymondLuong3 — COMMENTED** [review]
I found a bug where creating a question in the dialog and the editor does not scroll to the verse that is highlighted. I think that is another reason for `checking-text.component` to have responsibility of scrolling.

> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/2596#-:-O2QY_xJ1u3Y0QMkKwEV:bbtabs3)* status: all files reviewed, 2 unresolved discussions (waiting on @josephmyers)

**Review by josephmyers — COMMENTED** [review]
I do agree it'd be preferred to host scrolling in the original class. I'll look into this some more, but I'm not confident we'll be able to cover all cases.

I'm also not seeing the bug you're reporting. Below is a video of your steps working. What are you doing differently?

[fix.mp4](https://files.reviewableusercontent.io/images/reviewable/43733878/HLJf8N4BX1qHLBPb0NsYaFgZ/fix.mp4)

> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/2596#-:-O2TEFqW4sabV3uQRqg4:bk8785i)* status: 1 of 3 files reviewed, 1 unresolved discussion (waiting on @RaymondLuong3)

___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking.component.ts` line 1425 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/2596#-O2QUZ4RCoOwvlQcZmTR:-O2TGigV6MDpR0NHkTlj:b-896fix) ([raw file](https://github.com/sillsdev/web-xforge/blob/f70526e210aad7f36f4b6b5ef5236cacd3ab568e/src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking.component.ts#L1425)):*
<details><summary><i>Previously, RaymondLuong3 (Raymond Luong) wrote…</i></summary><blockquote>

Move this method above the private methods
</blockquote></details>

Done.

**Review by josephmyers — COMMENTED** [review]
So there are two significant downsides to putting the scrolling back in `checking-text`.

The first is that there is double-scrolling any time changing the question also resizes the splitter. This is because we don't have all the detailed information about the splitter in `checking-text` like we do in `checking`, where the latter could make better decisions about only scrolling exactly once.

The second is that bug SF-2806 is back, because we no longer know the status of the chapter audio player.

Both of these could be fixed if we sent a number of other items to `checking-text`, but I wonder if you still think it's worth it. I'm pushing [a second branch](https://github.com/sillsdev/web-xforge/tree/fix/SF-2749-alt) with these changes, and I'll keep brainstorming other ways to solve this.

> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/2596#-:-O2TSirU6O1VmujgzWxE:b-o4wun7)* status: 1 of 3 files reviewed, 1 unresolved discussion (waiting on @RaymondLuong3)

**Review by josephmyers — COMMENTED** [review]
For example, what if we moved the scrolling logic itself back to `checking-text` as public methods? That would help clear away bloat from `checking`

> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/2596#-:-O2T_fV32QzkavPSHdAy:b8gvs2f)* status: 1 of 3 files reviewed, 1 unresolved discussion (waiting on @RaymondLuong3)

**Review by RaymondLuong3 — APPROVED** [review]
Sorry, what I meant for the bug was when the question dialog is open, updating the verse in the verse reference input boxes does not scroll to the highlighted verse. Did you see that? Actually, I see it in your video that the highlighted verse is not scrolled to. I think you mentioned you saw that at our stand-up meeting.

> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/2596#-:-O2VMSiEDGf_q9k3DCGl:b-yqr042)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @josephmyers)

**Review by RaymondLuong3 — CHANGES_REQUESTED** [review]
Sorry, accidentally approved.

> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/2596#-:-O2VNHFZ1Jl8RscfpVIc:bog6swa)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @josephmyers)

**Review by josephmyers — COMMENTED** [review]
Alright, I will continue working on it today

> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/2596#-:-O2XDfwE87jmX2hwDmY8:b-gu1kqs)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @josephmyers)

**Review by josephmyers — COMMENTED** [review]
I was able to get everything moved back into `checking-text`, including bugfixes, on the second branch; however, the double scrolling is still present, and I don't see a way around it. `checking-text` has no way to tell if it should scroll immediately or wait til the splitter is resized. I guess it's better than being bugged.

> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/2596#-:-O2YZpkR4qcz0ecO72CM:b643bx)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @josephmyers)

**Review by RaymondLuong3 — CHANGES_REQUESTED** [review]
Sorry, accidentally approved... again

> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/2596#-:-O2_lwhH14BxqmfcSERM:b-j6jy2e)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @josephmyers)

**Review by josephmyers — COMMENTED** [review]
I pushed them to `fix/SF-2749-alt`, because it's essentially a separate way of doing the task. You can switch over to it locally or [view the changes on Github](https://github.com/sillsdev/web-xforge/compare/master...fix/SF-2749-alt).

> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/2596#-:-O2bHSWl63l9MNL7HnwX:bb63ro9)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @josephmyers)

**Review by RaymondLuong3 — CHANGES_REQUESTED** [review]
I like it. I tested it out and the scrolling works as I would expect. The double scrolling behaviour is not ideal, but I don't think it is a big issue. Can you get those changes into this PR so I can do a proper review?

> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/2596#-:-O2eW3XV626Pv52GXuHc:by1uwdp)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @josephmyers)

**Review by RaymondLuong3 — CHANGES_REQUESTED** [review]
Thanks for the work on this. The last verse in the chapter seems to be highlighted correctly and the scroll will show the verse, even when there are answers and comments. I see the double scroll behaviour when the verse is first scrolled to, then the text container is shrunk to make room for answers, then the verse is again strolled into view. I think that is acceptable.

Let's move this to testers.

> Reviewed 6 of 6 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/2596#-:-O3-B6A_8cxeT2s0_dz3:b-z3kjuy)* status: all files reviewed, 3 unresolved discussions (waiting on @josephmyers)

___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking.component.ts` line 74 at r3](https://reviewable.io/reviews/sillsdev/web-xforge/2596#-O3-7wGZ6P8CxeEE2uKG:-O3-7wGZ6P8CxeEE2uKH:ba6xw9b) ([raw file](https://github.com/sillsdev/web-xforge/blob/f2a635c56f2cd4d7f37a0d8dc65660a0d358259c/src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking.component.ts#L74)):*
> ```XML
>   @ViewChild(CheckingQuestionsComponent) questionsList?: CheckingQuestionsComponent;
>   @ViewChild('splitter') splitComponent?: SplitComponent;
>   @ViewChild('splitContainer') splitContainerElement?: ElementRef; //todo revisit
> ```

Can this be removed?



_Code quote:_
```XML
 //todo revisit
```
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking.component.ts` line 1034 at r3](https://reviewable.io/reviews/sillsdev/web-xforge/2596#-O3-8P3v2ph_GJUc5MPU:-O3-8P3v2ph_GJUc5MPV:b422zw8) ([raw file](https://github.com/sillsdev/web-xforge/blob/f2a635c56f2cd4d7f37a0d8dc65660a0d358259c/src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking.component.ts#L1034)):*
> ```XML
> 
>     const verseStr: string | undefined = getVerseStrFromSegmentRef(segmentRef);
>     if (verseStr) {
> ```

Nit: Be explicit here and write verseStr != null



_Code quote:_
```XML
 if (verseStr) {
```
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-text/checking-text.component.ts` line 38 at r3](https://reviewable.io/reviews/sillsdev/web-xforge/2596#-O3-98vQC_Av0L_KpvV-:-O3-98vQC_Av0L_KpvV0:b8yv5si) ([raw file](https://github.com/sillsdev/web-xforge/blob/f2a635c56f2cd4d7f37a0d8dc65660a0d358259c/src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-text/checking-text.component.ts#L38)):*
> ```XML
> 
>   ngAfterViewInit(): void {
>     if (this.resizableContainer) {
> ```

Nit: Be explicit for this and use this.resizeableContainer != null



_Code quote:_
```XML
    if (this.resizableContainer) {
```

**Comment by RaymondLuong3** [comment]
Since the changes I requested were so minor, I thought I would move it to testing and @josephmyers can make the changes. I didn't want to delay testing another day since the requested changes would not affect the testing outcome.

**Comment by Nateowami** [comment]
@RaymondLuong3 Makes sense

**Review by josephmyers — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/2596)* status: all files reviewed, 1 unresolved discussion (waiting on @RaymondLuong3)

___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking.component.ts` line 74 at r3](https://reviewable.io/reviews/sillsdev/web-xforge/2596#-O3-7wGZ6P8CxeEE2uKG:-O3AKdgV1AStUBn2AYbZ:byom7f3) ([raw file](https://github.com/sillsdev/web-xforge/blob/608c6823bebb209b10c06077033d8e8aaaccc090/src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking.component.ts#L74)):*
<details><summary><i>Previously, RaymondLuong3 (Raymond Luong) wrote…</i></summary><blockquote>

Can this be removed?
</blockquote></details>

Yes, it doesn't appear that we can remove it easily

**Review by RaymondLuong3 — APPROVED** [review]
> Reviewed 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/2596)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @josephmyers)

**Pull request merged**
