### PR TITLE
SF-2945 Add question record button to question icons

### PR DESCRIPTION
**Pull request by RaymondLuong3**
The PR adds the record question button in the place where administrators can update questions.

image

- - -
This change is [Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/2721)

### CODE REVIEW

**Review by Nateowami — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/2721)* status: 0 of 5 files reviewed, all discussions resolved

___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking.component.spec.ts` line 141 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/2721#-O6i8lVUDz4-xpMwo1fq:-O6i8lVUDz4-xpMwo1fr:bow236m) ([raw file](https://github.com/sillsdev/web-xforge/blob/b246b497aac3cbe875174e903c0311a7901b3082/src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking.component.spec.ts#L141)):*
> ```XML
> ];
> 
> fdescribe('CheckingComponent', () => {
> ```

This is what is failing the build.

**Review by nigel-wells — CHANGES_REQUESTED** [review]
Nice to be able to start using the component :)

> Reviewed 5 of 5 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/2721#-:-O6sp8V03YeSq8v6GYFc:bdljvtc)* status: all files reviewed, 2 unresolved discussions (waiting on @RaymondLuong3)

___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-answers/checking-answers.component.ts` line 394 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/2721#-O6snKgm1T6IZzhztK36:-O6snKgm1T6IZzhztK37:b3c4tvu) ([raw file](https://github.com/sillsdev/web-xforge/blob/b246b497aac3cbe875174e903c0311a7901b3082/src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-answers/checking-answers.component.ts#L394)):*
> ```XML
>     if (this.questionDoc?.data == null) return;
>     const dialogRef: MatDialogRef<AudioRecorderDialogComponent, AudioRecorderDialogResult> =
>       this.dialogService.openMatDialog(AudioRecorderDialogComponent);
> ```

This needs to start the countdown on open
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-answers/checking-answers.component.ts` line 396 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/2721#-O6soAql372zOZaululH:-O6soAql372zOZaululI:b81oo3k) ([raw file](https://github.com/sillsdev/web-xforge/blob/b246b497aac3cbe875174e903c0311a7901b3082/src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-answers/checking-answers.component.ts#L396)):*
> ```XML
>       this.dialogService.openMatDialog(AudioRecorderDialogComponent);
>     const result: AudioRecorderDialogResult | undefined = await firstValueFrom(dialogRef.afterClosed());
>     if (result != null && result.audio.fileName != null && result.audio.blob != null) {
> ```

nit  can remove the first `result != null` and just change the first condition to `result?.audio.fileName`

**Review by RaymondLuong3 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/2721)* status: 2 of 6 files reviewed, 1 unresolved discussion (waiting on @nigel-wells)

___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking.component.spec.ts` line 141 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/2721#-O6i8lVUDz4-xpMwo1fq:-O6va6q6AoEp4UUKR0Yy:bss4a2b) ([raw file](https://github.com/sillsdev/web-xforge/blob/b246b497aac3cbe875174e903c0311a7901b3082/src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking.component.spec.ts#L141)):*
<details><summary><i>Previously, Nateowami (Nathaniel Paulus) wrote…</i></summary><blockquote>

This is what is failing the build.
</blockquote></details>

Removed.
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-answers/checking-answers.component.ts` line 394 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/2721#-O6snKgm1T6IZzhztK36:-O6va9gD7_yDqwmRSFSG:b-896fix) ([raw file](https://github.com/sillsdev/web-xforge/blob/b246b497aac3cbe875174e903c0311a7901b3082/src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-answers/checking-answers.component.ts#L394)):*
<details><summary><i>Previously, nigel-wells (Nigel Wells) wrote…</i></summary><blockquote>

This needs to start the countdown on open
</blockquote></details>

Done.
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-answers/checking-answers.component.ts` line 396 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/2721#-O6soAql372zOZaululH:-O6vaBn-6G7zFG8lqDP0:b-896fix) ([raw file](https://github.com/sillsdev/web-xforge/blob/b246b497aac3cbe875174e903c0311a7901b3082/src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-answers/checking-answers.component.ts#L396)):*
<details><summary><i>Previously, nigel-wells (Nigel Wells) wrote…</i></summary><blockquote>

nit  can remove the first `result != null` and just change the first condition to `result?.audio.fileName`
</blockquote></details>

Done.

**Review by nigel-wells — CHANGES_REQUESTED** [review]
Something else I noticed we missed when we did all that `absolute` positioning is the countdown is now off center - do you mind tweaking that in this PR?


> Reviewed 4 of 4 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/2721#-:-O6xfx-d6rjcb0Sq2REr:b-1mm5f4)* status: all files reviewed, 1 unresolved discussion (waiting on @RaymondLuong3)

___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-answers/checking-answers.component.ts` line 394 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/2721#-O6snKgm1T6IZzhztK36:-O6xfH8PEQJzStaiIEPH:b8kh0pm) ([raw file](https://github.com/sillsdev/web-xforge/blob/b246b497aac3cbe875174e903c0311a7901b3082/src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-answers/checking-answers.component.ts#L394)):*
<details><summary><i>Previously, RaymondLuong3 (Raymond Luong) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Thanks. Can you add ` as AudioRecorderDialogData` as well.
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/shared/audio-recorder-dialog/audio-recorder-dialog.component.spec.ts` line 140 at r2](https://reviewable.io/reviews/sillsdev/web-xforge/2721#-O6xfVwiB13lYAVvuDOS:-O6xfVwiB13lYAVvuDOT:bcwfsdk) ([raw file](https://github.com/sillsdev/web-xforge/blob/e1c9e662fa2440a7b99a31a46c58357f8af17f96/src/SIL.XForge.Scripture/ClientApp/src/app/shared/audio-recorder-dialog/audio-recorder-dialog.component.spec.ts#L140)):*
> ```XML
>   });
> 
>   it('can show countdown', async () => {
> ```

This was added as a story instead due to not wanting too many async tests to slow down the running of tests.

**Comment by Nateowami** [comment]
@nigel-wells Don't you think this makes it look like recording audio as an answer? I don't really like having these icons on a separate line. To me they don't feel connected to the question.

**Comment by nigel-wells** [comment]
@Nateowami the design in balsamq was done with a mobile first design for community checking
image
As a question will vary in length, and could wrap many lines, even if we inline them with the question they may still not fit. Even the old links were on the same line but they were right aligned. Turning them into icons and right aligned looked really silly on desktop.

These icons are also only visible for admins.

Your point is still very valid though in how we separate the question and related button icons from the answer button while also trying to minimize vertical height. As they are admin only buttons, and admin is more likely to be on a larger screen, we could add some more spacing between the buttons and the add answer button. We could consider moving the icons a little closer to the question as well.

**Review by RaymondLuong3 — COMMENTED** [review]
I have added a tooltip to the button. The other buttons on that line also have tooltips. This does not fix the issue that on mobile it looks ambiguous whether the record will add audio as an answer or to the question, but given that this is only visible to administrators (and translators with permission) who are likely on desktop, I think this should reduce any confusion.



> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/2721#-:-O75bZ7c6kS294keARGw:b-8t1q3n)* status: 3 of 7 files reviewed, 1 unresolved discussion (waiting on @nigel-wells)

___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-answers/checking-answers.component.ts` line 394 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/2721#-O6snKgm1T6IZzhztK36:-O75_lui9RHcgJhJpvjG:b-896fix) ([raw file](https://github.com/sillsdev/web-xforge/blob/b246b497aac3cbe875174e903c0311a7901b3082/src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-answers/checking-answers.component.ts#L394)):*
<details><summary><i>Previously, nigel-wells (Nigel Wells) wrote…</i></summary><blockquote>

Thanks. Can you add ` as AudioRecorderDialogData` as well.
</blockquote></details>

Done.
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/shared/audio-recorder-dialog/audio-recorder-dialog.component.spec.ts` line 140 at r2](https://reviewable.io/reviews/sillsdev/web-xforge/2721#-O6xfVwiB13lYAVvuDOS:-O75_myQ17bz64XRpJgt:b-594r7i) ([raw file](https://github.com/sillsdev/web-xforge/blob/e1c9e662fa2440a7b99a31a46c58357f8af17f96/src/SIL.XForge.Scripture/ClientApp/src/app/shared/audio-recorder-dialog/audio-recorder-dialog.component.spec.ts#L140)):*
<details><summary><i>Previously, nigel-wells (Nigel Wells) wrote…</i></summary><blockquote>

This was added as a story instead due to not wanting too many async tests to slow down the running of tests.
</blockquote></details>

Right, I even remember reviewing that now. Removed.

**Review by nigel-wells — COMMENTED** [review]
Thanks for that - good to keep it consistent with the other tooltips as well.

Not sure if you saw my note about the countdown being off center. I've pushed through a fix for this to your branch so that it can go to the testers now.

:lgtm:

> Reviewed 4 of 4 files at r3.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/2721#-:-O77EKLb0ipjENEEn4P6:b-rgr0pt)* status: 6 of 7 files reviewed, all discussions resolved (waiting on @RaymondLuong3)

**Review by nigel-wells — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/2721#-:-O77HCgGC-2KS4tjSi0F:bnfp4nl)* status: 6 of 7 files reviewed, all discussions resolved (waiting on @RaymondLuong3)

**Review by josephmyers — CHANGES_REQUESTED** [review]
Can you also fix the spacing for community checkers (not admin's)? Sorry to hold this up, but it's related. It's currently only 4px, but we need another 8px (though when adding it we need to consider the other scenarios and layouts, too):



> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/2721#-:-O7Cii3rCriCxzNm5l7E:bjjg0or)* status: 6 of 7 files reviewed, all discussions resolved (waiting on @nigel-wells)

**Review by RaymondLuong3 — COMMENTED** [review]
Thanks for noticing that. From what I can tell, it has been quite tight for some time. I've updated it to separate the question from answer area which had the 12px spacing you wanted.



> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/2721#-:-O7FJlwE-m3nohblaK9s:bv27gd3)* status: 5 of 8 files reviewed, all discussions resolved (waiting on @nigel-wells)

**Review by josephmyers — APPROVED** [review]
Yes, it's quite a finicky area, for sure. I've run through a number of different scenarios on desktop and mobile, and although we can nitpick about spacing here and there (given the screen sizes we're dealing with), I think this is a solid improvement. 

> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/2721#-:-O7Rof3V0aEkjlgy-WnE:b-l0ap0c)* status: 5 of 8 files reviewed, all discussions resolved (waiting on @nigel-wells)

**Review by nigel-wells — APPROVED** [review]
> Reviewed 1 of 1 files at r5, 2 of 2 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/2721)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @RaymondLuong3)

**Pull request merged**
