### PR TITLE
SF-2144 Add backout commits tool

### PR DESCRIPTION
**Pull request by RaymondLuong3**
This tool connects to the realtime server, runs the backout operation on a list of projects, then updates the syncedToRepositoryVersion on the project.

TODO: We probably want to automatically perform a sync so that the data in Paratext gets fixed. This shouldn't be too difficult sync we already have the connection to the realtime server.

This change is [Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1972)

### CODE REVIEW

**Review by pmachapman — CHANGES_REQUESTED** [review]
Looks good, and it worked when I ran it - just a couple of minor bugs and issues.

To test this on my Windows PC, I ran the following in a Bash shell:
```
ASPNETCORE_ENVIRONMENT=Development MACHINE_NAME=THEBENDS PROJECT_ROOT_DIR=d:/var/lib/scriptureforge/sync PROJECT_IDS=648f6491ba42eb9f1644a43e RUN_MODE=true dotnet run
```

> Reviewed 11 of 11 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1972#-:-N_jgKDH5Gj97UAima_f:bscyoed)* status: all files reviewed, 8 unresolved discussions (waiting on @RaymondLuong3)

___
*[`src/Migrations/BackoutCommits/build-production` line 22 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/1972#-N_jdRWlDWBbBc-XxFvC:-N_jdRWlDWBbBc-XxFvD:b7siz3m) ([raw file](https://github.com/sillsdev/web-xforge/blob/7dcbd40b530363b15a5c897131679525ea2a9455/src/Migrations/BackoutCommits/build-production#L22)):*
> ```
> outputProductName="backout-commits-$(date '+%Y%m%d%H%M%S')"
> outputDir="bin/${outputProductName}"
> dotnet publish --runtime "linux-x64" -o "${outputDir}"
> ```

When running the script, I get the warning: `warning NETSDK1179: One of '--self-contained' or '--no-self-contained' options are require
d when '--runtime' is used.`

Based on the [old behavior](https://learn.microsoft.com/en-us/dotnet/core/compatibility/sdk/6.0/runtimeidentifier-self-contained), I think we should add the argument `--self-contained`?
___
*[`src/Migrations/BackoutCommits/ISFProjectTool.cs` line 6 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/1972#-N_jgvk68GH6vZub_8uS:-N_jgvk68GH6vZub_8uT:b3dpwuf) ([raw file](https://github.com/sillsdev/web-xforge/blob/7dcbd40b530363b15a5c897131679525ea2a9455/src/Migrations/BackoutCommits/ISFProjectTool.cs#L6)):*
> ```Smalltalk
> namespace BackoutCommits;
> 
> public interface ISFProjectTool
> ```

This interface should implement `IDisposable`(or even `IDisposableAsync` if you wanted to as well), i.e.
```cs
public interface ISFProjectTool : IDisposable
```

You could then remove `void Dispose();`, and have .NET correctly dispose the implementing class on GC.
___
*[`src/Migrations/BackoutCommits/Program.cs` line 69 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/1972#-N_jl51kC58SEsE0A91A:-N_jl51kC58SEsE0A91B:bbcj84) ([raw file](https://github.com/sillsdev/web-xforge/blob/7dcbd40b530363b15a5c897131679525ea2a9455/src/Migrations/BackoutCommits/Program.cs#L69)):*
> ```Smalltalk
>         program.projectRootDir = Environment.GetEnvironmentVariable("PROJECT_ROOT_DIR");
>         Logger.Log($"Project root dir: {program.projectRootDir}");
>         IEnumerable<string> projectIds = projectIdsString.Split(' ');
> ```

Should we throw an error if any of these environment variables are not specified?
___
*[`src/Migrations/BackoutCommits/Program.cs` line 170 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/1972#-N_jpNFI7NOQ6dnFiaaI:-N_jpNFI7NOQ6dnFiaaJ:b-ghajnz) ([raw file](https://github.com/sillsdev/web-xforge/blob/7dcbd40b530363b15a5c897131679525ea2a9455/src/Migrations/BackoutCommits/Program.cs#L170)):*
> ```Smalltalk
>             {
>                 Logger.Log("  >  Dry run, no files will be changed.");
>                 break;
> ```

Instead of breaking on a dry run, should we just echo the commands? It might help with debugging if we get stuck.
___
*[`src/Migrations/BackoutCommits/Program.cs` line 183 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/1972#-N_jrcw29O6jQZqwKiSH:-N_jrcw29O6jQZqwKiSI:b-85e4km) ([raw file](https://github.com/sillsdev/web-xforge/blob/7dcbd40b530363b15a5c897131679525ea2a9455/src/Migrations/BackoutCommits/Program.cs#L183)):*
> ```Smalltalk
>         }
>         Logger.Log(">  Successfully backed out problem commits.");
>         string currentId = await RunCommandAsync("hg", $"id --debug -i", projectDir);
> ```

We should trim this value, i.e. 
```cs
string currentId = (await RunCommandAsync("hg", $"id --debug -i", projectDir)).Trim();
```
When I ran the program, my syncedToRepositoryVersion was changed from "5dfa56d0cda6d427dc95fc348e08b4f9437a5f0e" to "5dfa56d0cda6d427dc95fc348e08b4f9437a5f0e`\n`"
___
*[`src/Migrations/BackoutCommits/Program.cs` line 185 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/1972#-N_jrDuv6f0-GB9uwLfR:-N_jrDuv6f0-GB9uwLfS:b-b1idd1) ([raw file](https://github.com/sillsdev/web-xforge/blob/7dcbd40b530363b15a5c897131679525ea2a9455/src/Migrations/BackoutCommits/Program.cs#L185)):*
> ```Smalltalk
>         string currentId = await RunCommandAsync("hg", $"id --debug -i", projectDir);
>         Logger.Log($">  Current commit id: {currentId}");
>         await projectTool.UpdateProjectRepositoryVersionAsync(projectDoc, currentId);
> ```

Should this be executed on a dry run?
___
*[`src/Migrations/BackoutCommits/SFProjectTool.cs` line 46 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/1972#-N_ji2hO8hpip105fs0Q:-N_ji2hO8hpip105fs0R:b-t7vbsi) ([raw file](https://github.com/sillsdev/web-xforge/blob/7dcbd40b530363b15a5c897131679525ea2a9455/src/Migrations/BackoutCommits/SFProjectTool.cs#L46)):*
> ```Smalltalk
>     public void Dispose()
>     {
>         realtimeServiceConnection?.Dispose();
> ```

`Dispose()` should be implemented like the pattern specified by Microsoft: https://learn.microsoft.com/en-us/dotnet/standard/garbage-collection/implementing-dispose#implement-the-dispose-pattern (see the example `BaseClassWithFinalizer`)
___
*[`src/Migrations/BackoutCommits/Startup.cs` line 67 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/1972#-N_jjOEU4dsV-UvAMdS1:-N_jjOEU4dsV-UvAMdS2:bkq9rgf) ([raw file](https://github.com/sillsdev/web-xforge/blob/7dcbd40b530363b15a5c897131679525ea2a9455/src/Migrations/BackoutCommits/Startup.cs#L67)):*
> ```Smalltalk
>                 {
>                     return new ProgramLogger(thisProcess.Id);
>                 }
> ```

Not a change, but just an FYI. I find that using statements look cleaner than using blocks for situations like this, i.e.:
```cs
using Process thisProcess = Process.GetCurrentProcess();
return new ProgramLogger(thisProcess.Id);
```
But it's just personal preference I think...



_Code quote:_
```Smalltalk
                using (Process thisProcess = Process.GetCurrentProcess())
                {
                    return new ProgramLogger(thisProcess.Id);
                }
```

**Review by RaymondLuong3 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1972)* status: all files reviewed, 8 unresolved discussions (waiting on @pmachapman)

___
*[`src/Migrations/BackoutCommits/build-production` line 22 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/1972#-N_jdRWlDWBbBc-XxFvC:-N_nyTvK4JuAi1PBXNBV:boj1qgt) ([raw file](https://github.com/sillsdev/web-xforge/blob/7dcbd40b530363b15a5c897131679525ea2a9455/src/Migrations/BackoutCommits/build-production#L22)):*
<details><summary><i>Previously, pmachapman (Peter Chapman) wrote…</i></summary><blockquote>

When running the script, I get the warning: `warning NETSDK1179: One of '--self-contained' or '--no-self-contained' options are require
d when '--runtime' is used.`

Based on the [old behavior](https://learn.microsoft.com/en-us/dotnet/core/compatibility/sdk/6.0/runtimeidentifier-self-contained), I think we should add the argument `--self-contained`?
</blockquote></details>

Good catch. Done.
___
*[`src/Migrations/BackoutCommits/ISFProjectTool.cs` line 6 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/1972#-N_jgvk68GH6vZub_8uS:-N_nyjaH6Fc-bekilRnp:b-707hxv) ([raw file](https://github.com/sillsdev/web-xforge/blob/7dcbd40b530363b15a5c897131679525ea2a9455/src/Migrations/BackoutCommits/ISFProjectTool.cs#L6)):*
<details><summary><i>Previously, pmachapman (Peter Chapman) wrote…</i></summary><blockquote>

This interface should implement `IDisposable`(or even `IDisposableAsync` if you wanted to as well), i.e.
```cs
public interface ISFProjectTool : IDisposable
```

You could then remove `void Dispose();`, and have .NET correctly dispose the implementing class on GC.
</blockquote></details>

Yes, that is good. It looks like I would not need to specify the Dispose method in the interface now.
___
*[`src/Migrations/BackoutCommits/Program.cs` line 69 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/1972#-N_jl51kC58SEsE0A91A:-N_nzs7f7ywlQEN6MtMg:bl8bdb5) ([raw file](https://github.com/sillsdev/web-xforge/blob/7dcbd40b530363b15a5c897131679525ea2a9455/src/Migrations/BackoutCommits/Program.cs#L69)):*
<details><summary><i>Previously, pmachapman (Peter Chapman) wrote…</i></summary><blockquote>

Should we throw an error if any of these environment variables are not specified?
</blockquote></details>

I think we could. Done.
___
*[`src/Migrations/BackoutCommits/Program.cs` line 170 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/1972#-N_jpNFI7NOQ6dnFiaaI:-N_o0C_G-XkO_AUD9dFJ:b34g50s) ([raw file](https://github.com/sillsdev/web-xforge/blob/7dcbd40b530363b15a5c897131679525ea2a9455/src/Migrations/BackoutCommits/Program.cs#L170)):*
<details><summary><i>Previously, pmachapman (Peter Chapman) wrote…</i></summary><blockquote>

Instead of breaking on a dry run, should we just echo the commands? It might help with debugging if we get stuck.
</blockquote></details>

Yes, good call. I'll log the backout command.
___
*[`src/Migrations/BackoutCommits/Program.cs` line 183 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/1972#-N_jrcw29O6jQZqwKiSH:-N_o0HaH36E_4ld_ie5P:b-lsxawc) ([raw file](https://github.com/sillsdev/web-xforge/blob/7dcbd40b530363b15a5c897131679525ea2a9455/src/Migrations/BackoutCommits/Program.cs#L183)):*
<details><summary><i>Previously, pmachapman (Peter Chapman) wrote…</i></summary><blockquote>

We should trim this value, i.e. 
```cs
string currentId = (await RunCommandAsync("hg", $"id --debug -i", projectDir)).Trim();
```
When I ran the program, my syncedToRepositoryVersion was changed from "5dfa56d0cda6d427dc95fc348e08b4f9437a5f0e" to "5dfa56d0cda6d427dc95fc348e08b4f9437a5f0e`\n`"
</blockquote></details>

Yes, I discovered that too. Done.
___
*[`src/Migrations/BackoutCommits/Program.cs` line 185 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/1972#-N_jrDuv6f0-GB9uwLfR:-N_o0K4gBhwM8JfoRkD9:b-viwntl) ([raw file](https://github.com/sillsdev/web-xforge/blob/7dcbd40b530363b15a5c897131679525ea2a9455/src/Migrations/BackoutCommits/Program.cs#L185)):*
<details><summary><i>Previously, pmachapman (Peter Chapman) wrote…</i></summary><blockquote>

Should this be executed on a dry run?
</blockquote></details>

Nope, good catch.
___
*[`src/Migrations/BackoutCommits/SFProjectTool.cs` line 46 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/1972#-N_ji2hO8hpip105fs0Q:-N_oFCpcDSvx5XZJ4CjB:bectkt0) ([raw file](https://github.com/sillsdev/web-xforge/blob/7dcbd40b530363b15a5c897131679525ea2a9455/src/Migrations/BackoutCommits/SFProjectTool.cs#L46)):*
<details><summary><i>Previously, pmachapman (Peter Chapman) wrote…</i></summary><blockquote>

`Dispose()` should be implemented like the pattern specified by Microsoft: https://learn.microsoft.com/en-us/dotnet/standard/garbage-collection/implementing-dispose#implement-the-dispose-pattern (see the example `BaseClassWithFinalizer`)
</blockquote></details>

Ok, I think I have it working with SFProjectTool with a finalizer.
___
*[`src/Migrations/BackoutCommits/Startup.cs` line 67 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/1972#-N_jjOEU4dsV-UvAMdS1:-N_o0dzi5M5POZt-sVpp:beqry3w) ([raw file](https://github.com/sillsdev/web-xforge/blob/7dcbd40b530363b15a5c897131679525ea2a9455/src/Migrations/BackoutCommits/Startup.cs#L67)):*
<details><summary><i>Previously, pmachapman (Peter Chapman) wrote…</i></summary><blockquote>

Not a change, but just an FYI. I find that using statements look cleaner than using blocks for situations like this, i.e.:
```cs
using Process thisProcess = Process.GetCurrentProcess();
return new ProgramLogger(thisProcess.Id);
```
But it's just personal preference I think...
</blockquote></details>

I am in favour of that too. This was copied from another file.

**Review by pmachapman — CHANGES_REQUESTED** [review]
> Reviewed 6 of 6 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1972)* status: all files reviewed, 1 unresolved discussion (waiting on @RaymondLuong3)

___
*[`src/Migrations/BackoutCommits/Program.cs` line 71 at r2](https://reviewable.io/reviews/sillsdev/web-xforge/1972#-NaEIFUE-ptz2pxUP5Sz:-NaEIFUFCYFooHva7y9A:b-imz2iw) ([raw file](https://github.com/sillsdev/web-xforge/blob/061362bc09a5bf8e8fe47ccccc07503acb959a19/src/Migrations/BackoutCommits/Program.cs#L71)):*
> ```Smalltalk
>             string.IsNullOrWhiteSpace(program.machineName)
>             || string.IsNullOrWhiteSpace(projectIdsString)
>             || string.IsNullOrWhiteSpace(program.machineName)
> ```

Should this be `program.projectRootDir`?



_Code quote:_
```Smalltalk
program.machineName
```

**Review by pmachapman — APPROVED** [review]
:lgtm: - awesome - thank you for all of your work on this @RaymondLuong3!

> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1972#-:-NaIefU10dTDc1h3PCGI:b-2qmkw2)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @RaymondLuong3)

**Pull request merged**
