### PR TITLE
SF-1924 PT comments on SF community checking answers lost after sync

### PR DESCRIPTION
**Pull request by pmachapman**
**Overview**

Comments made in Paratext to Answers exported to Paratext from Scripture Forge were being lost on sync if a newer comment was made in Scripture Forge. This occurred because there was no accurate tracking of comments being deleted. To address that, this PR adds a deleted flag to Comments and Answers that is set when these are deleted, as opposed to the previous behavior which was the removal of the comment or answer from the question document.

**Changes in this Pull Request**

 - Rename `tagsAdded` XML tag to `tagAdded` to conform to Paratext Comments XML tag name
 - Fixed bug where the comment was incorrectly seen as modified when  no change had occurred
 - Add a `deleted` flag to answers and comments
 - Fixed a bug where comments created in Paratext are deleted when a newer comment is added in Scripture Forge
 - When an answer is deleted in SF that has Paratext comments, those comments will remain as their own notes in Paratext

**Known Issues**

 - Updating or deleting a comment or answer in Paratext will be reverted by Scripture Forge on sync
 - Resolving the note corresponding to the question in Paratext will be reverted by Scripture Forge on sync
 - Answers and comments that have been synced then deleted before this PR is merged will not be deleted from Paratext

- - -
This change is [Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1776)

### CODE REVIEW

**Review by RaymondLuong3 — CHANGES_REQUESTED** [review]
Nice work. This must have been something that was overlooked. Maybe we did not expect PT users to comment on community checking answers in Paratext. But it makes more sense to support it if we can, rather than make the assumption that PT users will not want to add their comments to community checking answers in PT. I checked this branch out and it appears to work as expected.

> Reviewed 22 of 22 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1776#-:-NSHqTU3AKsNBMilKvgh:btlaccx)* status: all files reviewed, 9 unresolved discussions (waiting on @pmachapman)

___
*[`src/RealtimeServer/scriptureforge/services/question-migrations.ts` line 11 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/1776#-NSHc_NLA246twxWfeEv:-NSHc_NM0L1nnO-Ucp1P:bgonhcz) ([raw file](https://github.com/sillsdev/web-xforge/blob/3e043b3cb36cda4a5ce15089899c5d25596be9c8/src/RealtimeServer/scriptureforge/services/question-migrations.ts#L11)):*
> ```XML
>     const ops: Op[] = [];
>     for (let i = 0; i < doc.data.answers.length; i++) {
>       if (doc.data.answers[i].deleted === undefined) {
> ```

We typically have been using `deleted == null` to cover both the case of deleted being undefined or null.



_Code quote:_
```XML
doc.data.answers[i].deleted === undefined) 
```
___
*[`src/RealtimeServer/scriptureforge/services/question-migrations.spec.ts` line 25 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/1776#-NSHdLbu1OppN7mV2KPM:-NSHdLbu1OppN7mV2KPN:b-3i2we5) ([raw file](https://github.com/sillsdev/web-xforge/blob/3e043b3cb36cda4a5ce15089899c5d25596be9c8/src/RealtimeServer/scriptureforge/services/question-migrations.spec.ts#L25)):*
> ```XML
> 
>       let questionDoc = await fetchDoc(conn, QUESTIONS_COLLECTION, 'question01');
>       expect(questionDoc.data.answers[0].comments[0].deleted).toBe(false);
> ```

We should also check that both answers should have `deleted: false` set.



_Code quote:_
```XML
      expect(questionDoc.data.answers[0].comments[0].deleted).toBe(false);
      expect(questionDoc.data.answers[0].comments[1].deleted).toBe(true);
      expect(questionDoc.data.answers[1].comments[0].deleted).toBe(false);
      expect(questionDoc.data.answers[1].comments[1].deleted).toBe(false);
```
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking.component.ts` line 896 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/1776#-NSHhvdL3_dTHKNHl-2q:-NSHhvdL3_dTHKNHl-2r:b-xz82q8) ([raw file](https://github.com/sillsdev/web-xforge/blob/3e043b3cb36cda4a5ce15089899c5d25596be9c8/src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking.component.ts#L896)):*
> ```XML
>     const answerIndex = this.getAnswerIndex(answer);
>     if (answerIndex >= 0) {
>       const commentLength = activeQuestionDoc.data!.answers[answerIndex].comments.length;
> ```

Nit: Add a type here.



_Code quote:_
```XML
 const commentLength = activeQuestionDoc.data!.answers[answerIndex].comments.length;
```
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-answers/checking-answers.component.ts` line 228 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/1776#-NSHiIaT9fqX9g93YG5E:-NSHiIaT9fqX9g93YG5F:bwqrr9x) ([raw file](https://github.com/sillsdev/web-xforge/blob/3e043b3cb36cda4a5ce15089899c5d25596be9c8/src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-answers/checking-answers.component.ts#L228)):*
> ```XML
>       return [];
>     }
>     return this._questionDoc.data.answers.filter(answer => !answer.deleted);
> ```

I see this is a fairly common change. What do you think about creating a helper function. Or better yet, you could include this helper function in the `QuestionDoc` class so you could simply call `questionDoc.activeAnswers`.



_Code quote (i):_
```XML
   return this._questionDoc.data.answers.filter(answer => !answer.deleted);
```



_Code snippet (ii):_
```XML
get activeAnswers(): Answer[] {
  return this.data?.answers.filter(answer => !answer.deleted) ?? [];
}
```
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-answers/checking-comments/checking-comments.component.ts` line 147 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/1776#-NSHhBR3ChXwdE3O9JUg:-NSHhBR3ChXwdE3O9JUh:b-k1ggz4) ([raw file](https://github.com/sillsdev/web-xforge/blob/3e043b3cb36cda4a5ce15089899c5d25596be9c8/src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-answers/checking-comments/checking-comments.component.ts#L147)):*
> ```XML
>           return;
>         }
>         const commentsLength = this.answer.comments.filter(comment => !comment.deleted).length;
> ```

Nit: add a type here.



_Code quote:_
```XML
 const commentsLength = this.answer.comments.filter(comment => !comment.deleted).length;
```
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-questions/checking-questions.component.ts` line 257 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/1776#-NSHhpQt1y3mgQwslLdR:-NSHhpQt1y3mgQwslLdS:b-k1ggz4) ([raw file](https://github.com/sillsdev/web-xforge/blob/3e043b3cb36cda4a5ce15089899c5d25596be9c8/src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-questions/checking-questions.component.ts#L257)):*
> ```XML
>               op.add(puc => puc.answerRefsRead, answer.dataId);
>             }
>             const comments = sortBy(
> ```

Nit: add a type here.



_Code quote:_
```XML
            const comments = sortBy(
              answer.comments.filter(c => !c.deleted),
              c => c.dateCreated
            );
```
___
*[`src/SIL.XForge.Scripture/Services/ParatextNotesMapper.cs` line 288 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/1776#-NSHn0QJ9veRW-tYO3bN:-NSHn0QJ9veRW-tYO3bO:bl3mfew) ([raw file](https://github.com/sillsdev/web-xforge/blob/3e043b3cb36cda4a5ce15089899c5d25596be9c8/src/SIL.XForge.Scripture/Services/ParatextNotesMapper.cs#L288)):*
> ```Smalltalk
>         switch (comment.Deleted)
>         {
>             case true when oldCommentElems.TryGetValue(key, out XElement oldCommentElem):
> ```

I'm curious why you used a switch here instead of just an if/else if. Is there an advantage?



_Code quote:_
```Smalltalk
            case true when oldCommentElems.TryGetValue(key, out XElement oldCommentElem):
                commentsToDelete.Add(oldCommentElem);
                break;
```
___
*[`test/SIL.XForge.Scripture.Tests/Services/ParatextNotesMapperTests.cs` line 682 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/1776#-NSHpBxR6A-HtMJMCnot:-NSHpBxR6A-HtMJMCnou:b-fy6wov) ([raw file](https://github.com/sillsdev/web-xforge/blob/3e043b3cb36cda4a5ce15089899c5d25596be9c8/test/SIL.XForge.Scripture.Tests/Services/ParatextNotesMapperTests.cs#L682)):*
> ```Smalltalk
> 
>     [Test]
>     public async Task GetNotesChangelistAsync_DoesDeleteParatextNotes()
> ```

Is this supposed to say "DoesNotDeleteParatextNotes"



_Code quote:_
```Smalltalk
    [Test]
    public async Task GetNotesChangelistAsync_DoesDeleteParatextNotes()
```
___
*[`test/SIL.XForge.Scripture.Tests/Services/ParatextNotesMapperTests.cs` line 754 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/1776#-NSHoVBH2vhChwBEvdIE:-NSHoVBH2vhChwBEvdIF:b-l0tftt) ([raw file](https://github.com/sillsdev/web-xforge/blob/3e043b3cb36cda4a5ce15089899c5d25596be9c8/test/SIL.XForge.Scripture.Tests/Services/ParatextNotesMapperTests.cs#L754)):*
> ```Smalltalk
>                         <thread id=""ANSWER_answer06"">
>                             <selection verseRef=""MAT 1:1"" startPos=""0"" selectedText="""" />
>                             <comment user=""PT User 1"" extUser=""user04"" date=""2019-01-05T08:00:00.0000000+00:00"">
> ```

You should be able to remove this since comments in PT would not have an extUser set.



_Code quote:_
```Smalltalk
extUser=""user04""
```

**Review by RaymondLuong3 — CHANGES_REQUESTED** [review]
> Reviewed 12 of 14 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1776)* status: 24 of 26 files reviewed, 4 unresolved discussions (waiting on @pmachapman)

___
*[`src/RealtimeServer/common/services/project-data-service.ts` line 153 at r2](https://reviewable.io/reviews/sillsdev/web-xforge/1776#-NSO_mbhDCVqD8cSAcNs:-NSO_mbhDCVqD8cSAcNt:b-49wxt1) ([raw file](https://github.com/sillsdev/web-xforge/blob/e65337db2479090c5c1bb248a27e34272f1e80d0/src/RealtimeServer/common/services/project-data-service.ts#L153)):*
> ```XML
>         const oldEntity = this.deepGet(entityPath, oldDoc);
> 
>         // Changing the deleted property should be treated as a delete operation
> ```

Hmm, this is an interesting case. Theoretically the operation is more of an update, but to keep things consistent, we should be treating this as a delete operation. I think this is a fair way to do this.



_Code quote:_
```XML
        // Changing the deleted property should be treated as a delete operation
```
___
*[`src/RealtimeServer/common/services/project-data-service.spec.ts` line 249 at r2](https://reviewable.io/reviews/sillsdev/web-xforge/1776#-NSObXkeA8D1h_rWUh03:-NSObXkf7pe9u71AKH6F:b-fngm3d) ([raw file](https://github.com/sillsdev/web-xforge/blob/e65337db2479090c5c1bb248a27e34272f1e80d0/src/RealtimeServer/common/services/project-data-service.spec.ts#L249)):*
> ```XML
>   });
> 
>   it('handles updates to the deleted property as delete operations', async () => {
> ```

This shows that it works to delete the data, but doesn't show that when delete is not allowed, that a delete operation will cause a permission denied error. Would it be hard to add that test case?



_Code quote:_
```XML
 it('handles updates to the deleted property as delete operations', async () => {
```
___
*[`src/RealtimeServer/common/services/project-data-service.spec.ts` line 258 at r2](https://reviewable.io/reviews/sillsdev/web-xforge/1776#-NSObBu7Dasn8vJoSwNK:-NSObBu7Dasn8vJoSwNL:bu3du6c) ([raw file](https://github.com/sillsdev/web-xforge/blob/e65337db2479090c5c1bb248a27e34272f1e80d0/src/RealtimeServer/common/services/project-data-service.spec.ts#L258)):*
> ```XML
>         ops
>           .add(d => d.children, { id: 'sub04', ownerRef: 'user', children: [] })
>           .insert(d => d.children[1].children, 0, { id: 'sub05', ownerRef: 'user' })
> ```

What is the purpose of setting the properties on `d.children[1]` Would it not make more sense to set it on `d.children[0]`? Or maybe I'm not quite understanding the structure of the test data.



_Code quote:_
```XML
.insert(d => d.children[1].children
```
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/checking/import-questions-dialog/import-questions-dialog.component.ts` line 461 at r2](https://reviewable.io/reviews/sillsdev/web-xforge/1776#-NSOZtnh2kC6hpt75ktr:-NSOZtnh2kC6hpt75kts:b-167koc) ([raw file](https://github.com/sillsdev/web-xforge/blob/e65337db2479090c5c1bb248a27e34272f1e80d0/src/SIL.XForge.Scripture/ClientApp/src/app/checking/import-questions-dialog/import-questions-dialog.component.ts#L461)):*
> ```XML
>         change.sfVersionOfQuestion!.data!.text,
>       after: this.referenceForDisplay(change.question) + ' ' + change.question.text,
>       answerCount: change.sfVersionOfQuestion?.getAnswers?.().length || 0,
> ```

The `getAnswers()` call shouldn't need the null check.



_Code quote:_
```XML
change.sfVersionOfQuestion?.getAnswers?.().length 
```
___
*[`src/SIL.XForge.Scripture/Services/ParatextNotesMapper.cs` line 288 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/1776#-NSHn0QJ9veRW-tYO3bN:-NSOc0FF-475aKYGlxSB:bm5uk03) ([raw file](https://github.com/sillsdev/web-xforge/blob/3e043b3cb36cda4a5ce15089899c5d25596be9c8/src/SIL.XForge.Scripture/Services/ParatextNotesMapper.cs#L288)):*
<details><summary><i>Previously, pmachapman (Peter Chapman) wrote…</i></summary><blockquote>

No real benefit - my IDE suggested it, and I thought it looked clearer than the `if` block I wrote:

```csharp
        if (comment.Deleted && oldCommentElems.TryGetValue(key, out XElement oldCommentElem))
        {
            commentsToDelete.Add(oldCommentElem);
        }
        else if (!comment.Deleted && IsCommentNewOrChanged(oldCommentElems, key, commentElem, setCheckingTag))
        {
            threadElem.Add(commentElem);
        }
```

I think using a switch is much more defendable if I had multiple blocks in the `if` statement, and all of them dependent on the value of one variable.

If you think the `if` block is clearer, I can happily revert it to that.
</blockquote></details>

Oh neat, ok. I'll keep that in mind that this is also a valid way to write it. If your editor suggested it then someone thinks it is a better way to write it.

**Review by pmachapman — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1776)* status: 24 of 26 files reviewed, 3 unresolved discussions (waiting on @RaymondLuong3)

___
*[`src/RealtimeServer/common/services/project-data-service.spec.ts` line 249 at r2](https://reviewable.io/reviews/sillsdev/web-xforge/1776#-NSObXkeA8D1h_rWUh03:-NSggF3f2BCB6PHYkkN5:b-7ok6fb) ([raw file](https://github.com/sillsdev/web-xforge/blob/e65337db2479090c5c1bb248a27e34272f1e80d0/src/RealtimeServer/common/services/project-data-service.spec.ts#L249)):*
<details><summary><i>Previously, RaymondLuong3 (Raymond Luong) wrote…</i></summary><blockquote>

This shows that it works to delete the data, but doesn't show that when delete is not allowed, that a delete operation will cause a permission denied error. Would it be hard to add that test case?
</blockquote></details>

Good idea - I have added an additional test case.
___
*[`src/RealtimeServer/common/services/project-data-service.spec.ts` line 258 at r2](https://reviewable.io/reviews/sillsdev/web-xforge/1776#-NSObBu7Dasn8vJoSwNK:-NSgb3lnAfCDZSXQ53dP:b-g58m8s) ([raw file](https://github.com/sillsdev/web-xforge/blob/e65337db2479090c5c1bb248a27e34272f1e80d0/src/RealtimeServer/common/services/project-data-service.spec.ts#L258)):*
<details><summary><i>Previously, RaymondLuong3 (Raymond Luong) wrote…</i></summary><blockquote>

What is the purpose of setting the properties on `d.children[1]` Would it not make more sense to set it on `d.children[0]`? Or maybe I'm not quite understanding the structure of the test data.
</blockquote></details>

I copied a previous test, but you are right - it doesn't make much sense. I have changed it to use `d.children[0]`.
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/checking/import-questions-dialog/import-questions-dialog.component.ts` line 461 at r2](https://reviewable.io/reviews/sillsdev/web-xforge/1776#-NSOZtnh2kC6hpt75ktr:-NSgjRm9-mWfCbEUQEv8:b-c6bknt) ([raw file](https://github.com/sillsdev/web-xforge/blob/e65337db2479090c5c1bb248a27e34272f1e80d0/src/SIL.XForge.Scripture/ClientApp/src/app/checking/import-questions-dialog/import-questions-dialog.component.ts#L461)):*
<details><summary><i>Previously, RaymondLuong3 (Raymond Luong) wrote…</i></summary><blockquote>

The `getAnswers()` call shouldn't need the null check.
</blockquote></details>

I did it to fix some tests that were breaking, but have fixed the data for those tests instead.

**Review by RaymondLuong3 — APPROVED** [review]
:lgtm: 

> Reviewed 1 of 14 files at r2, 4 of 4 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1776#-:-NSl9PAMAdkhR5R2KGWZ:bg7igkv)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @pmachapman)

**Pull request merged**
