### PR TITLE
SF-1509 Skip pushing book text if project is not editable

### PR DESCRIPTION
**Pull request by RaymondLuong3**
* prevent pushing changes if project is not editable
* add the editable property to SFProject
* prevent users from editing projects that are not editable
* check and update editable property on sync
* also consolidate project settings access methods like full name and is left to right

Editor project text not editable

---
This change is [Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1264)

### CODE REVIEW

**Review by Nateowami — CHANGES_REQUESTED** [review]
Mostly reviewed. Looks pretty good. Just a couple comments.

> Reviewed 28 of 30 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1264#-:-My9aXV66vVvzLLw-7HZ:b-tf0ncc)* status: 28 of 30 files reviewed, 4 unresolved discussions (waiting on @Nateowami and @RaymondLuong3)

___
*[src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.spec.ts, line 848 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/1264#-My9QkmYCyQ84b4M9V_U:-My9QkmZAG3FWsofvH7H:b-mb55gh) ([raw file](https://github.com/sillsdev/web-xforge/blob/e6a7ac3544da3d8c435e3eb31d6610896f455346/src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.spec.ts#L848)):*
> ```XML
>       env.setupProject({ editable: false });
>       env.setProjectUserConfig();
>       // env.updateParams({ projectId: 'notEditableProj', bookId: 'GEN' });
> ```

Why is this line here but commented out?
___
*[src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.spec.ts, line 853 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/1264#-My9QqVoCckzwkZuf7xh:-My9QqVpDsp6ZaxrGNbd:b906aju) ([raw file](https://github.com/sillsdev/web-xforge/blob/e6a7ac3544da3d8c435e3eb31d6610896f455346/src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.spec.ts#L853)):*
> ```XML
>       expect(env.bookName).toEqual('Matthew');
>       expect(env.component.projectTextNotEditable).toBe(true);
>       expect(env.component.canEdit).toBe(false);
> ```

Maybe also check for message saying it's not editable?
___
*[src/SIL.XForge.Scripture/Services/ParatextService.cs, line 618 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/1264#-My9SG2mDvAHM7FEiFPe:-My9SG2mDvAHM7FEiFPf:bf8t9wt) ([raw file](https://github.com/sillsdev/web-xforge/blob/e6a7ac3544da3d8c435e3eb31d6610896f455346/src/SIL.XForge.Scripture/Services/ParatextService.cs#L618)):*
> ```Smalltalk
>             {
>                 FullName = scrText.FullName,
>                 IsRightToLeft = scrText?.RightToLeft ?? false,
> ```

I think this optional chaining (or whatever it's called) is superfluous. If `scrText` is null we'll already have thrown by the line above. Maybe it should be `scrText.RightToLeft ?? false`?
___
*[src/SIL.XForge.Scripture/Services/ParatextService.cs, line 651 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/1264#-My9V1F48Fp_2EMzKbbC:-My9V1F48Fp_2EMzKbbD:b-9idopn) ([raw file](https://github.com/sillsdev/web-xforge/blob/e6a7ac3544da3d8c435e3eb31d6610896f455346/src/SIL.XForge.Scripture/Services/ParatextService.cs#L651)):*
> ```Smalltalk
>                 string username = GetParatextUsername(userSecret);
>                 ScrText scrText = ScrTextCollection.FindById(username, projectId);
>                 if (!scrText.Settings.Editable)
> ```

It seems like the name PutBookText would be actually doing the putting of the book text, and it would be the responsibility of the caller to check whether we should actually be putting the book text. But it could be the case that this is simpler, and the other way wouldn't work well. However, since we do PutBookText in a loop, it would probably be more efficient to have a single check of whether the project is editable, on the outside of the loop. Or maybe this is the best way to do it. In which case maybe the documentation for the method should be updated?

**Review by Nateowami — COMMENTED** [review]
> Reviewed 2 of 30 files at r1.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1264)* status: all files reviewed, 5 unresolved discussions (waiting on @RaymondLuong3)

___
*[test/SIL.XForge.Scripture.Tests/Services/ParatextServiceTests.cs, line 564 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/1264#-MyFfkpb6k46dCnsLZ5P:-MyFfkpb6k46dCnsLZ5Q:b-ukfnln) ([raw file](https://github.com/sillsdev/web-xforge/blob/e6a7ac3544da3d8c435e3eb31d6610896f455346/test/SIL.XForge.Scripture.Tests/Services/ParatextServiceTests.cs#L564)):*
> ```Smalltalk
>             string logMessage = string.Format("{0} updated {1} in {2}.", env.User01,
>                     Canon.BookNumberToEnglishName(ruthBookNum), env.ProjectScrText.Name);
>             env.MockLogger.AssertNoEvent((LogEvent logEvent) => logEvent != null);
> ```

Can you explain what this assertion does? I don't understand it.

**Review by Nateowami — COMMENTED** [review]
I just rebased in the hopes of getting LGTM to do the C# build properly.

> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1264#-:-MyFggkp-CuaBitX_JKm:br9wqio)* status: 28 of 30 files reviewed, 5 unresolved discussions (waiting on @Nateowami and @RaymondLuong3)

**Review by Nateowami — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1264)* status: all files reviewed, 5 unresolved discussions (waiting on @RaymondLuong3)

___
*[src/SIL.XForge.Scripture/Services/ParatextService.cs, line 618 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/1264#-My9SG2mDvAHM7FEiFPe:-MyFrPz3D_PYSokKpZwH:bksk3uo) ([raw file](https://github.com/sillsdev/web-xforge/blob/e6a7ac3544da3d8c435e3eb31d6610896f455346/src/SIL.XForge.Scripture/Services/ParatextService.cs#L618)):*
<details><summary><i>Previously, Nateowami (Nathaniel Paulus) wrote…</i></summary><blockquote>

I think this optional chaining (or whatever it's called) is superfluous. If `scrText` is null we'll already have thrown by the line above. Maybe it should be `scrText.RightToLeft ?? false`?
</blockquote></details>

Wow, LGTM and I noticed the *exact* same thing. It's complaining "Variable scrText may be null here (`scrText.FullName`) as suggested by this null check (`scrText?.RightToLeft`)."

**Review by RaymondLuong3 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1264)* status: all files reviewed, 2 unresolved discussions (waiting on @Nateowami)

___
*[src/SIL.XForge.Scripture/Services/ParatextService.cs, line 618 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/1264#-My9SG2mDvAHM7FEiFPe:-MyJPJ6J2Rfv8a3OM79t:bbsbqe5) ([raw file](https://github.com/sillsdev/web-xforge/blob/e6a7ac3544da3d8c435e3eb31d6610896f455346/src/SIL.XForge.Scripture/Services/ParatextService.cs#L618)):*
<details><summary><i>Previously, Nateowami (Nathaniel Paulus) wrote…</i></summary><blockquote>

If the ScrText is null, should the method just return null instead of a ParatextSettings with incorrect values? Or throw an exception? `IsRightToLeft` and `Editable` are bool, which are non-nullable. What happens when we set them to null here? Is it a no-op? In which case they remain at their default values?
</blockquote></details>

Good thinking. I'll set it to return null if we do not have a defined `scrText`
___
*[src/SIL.XForge.Scripture/Services/ParatextSyncRunner.cs, line 178 at r3](https://reviewable.io/reviews/sillsdev/web-xforge/1264#-MyJ1H1g0eYlGJprwQUo:-MyJPUWZ01kUNQ3txen5:b-f5x0vr) ([raw file](https://github.com/sillsdev/web-xforge/blob/90ad25001c7bf7ea9222d6ec5d6fe7e9ea6372a1/src/SIL.XForge.Scripture/Services/ParatextSyncRunner.cs#L178)):*
<details><summary><i>Previously, Nateowami (Nathaniel Paulus) wrote…</i></summary><blockquote>

Did you check whether notes can be updated when the project is not editable?
</blockquote></details>

Yes I did. We can edit and create notes when a project is not editable.

**Review by Nateowami — APPROVED** [review]
:lgtm:

> Reviewed 3 of 3 files at r5, 2 of 2 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1264#-:-MyJZksR1KFkUBjzJEw_:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @RaymondLuong3)

___
*[src/SIL.XForge.Scripture/Services/ParatextSyncRunner.cs, line 178 at r3](https://reviewable.io/reviews/sillsdev/web-xforge/1264#-MyJ1H1g0eYlGJprwQUo:-MyJX90g767N9QVnk-MV:b-8fx2u7) ([raw file](https://github.com/sillsdev/web-xforge/blob/90ad25001c7bf7ea9222d6ec5d6fe7e9ea6372a1/src/SIL.XForge.Scripture/Services/ParatextSyncRunner.cs#L178)):*
<details><summary><i>Previously, RaymondLuong3 (Raymond Luong) wrote…</i></summary><blockquote>

Yes I did. We can edit and create notes when a project is not editable.
</blockquote></details>

:+1:

**Pull request merged**
