### PR TITLE
Add Mongo query to find common sync failure reasons

### PR DESCRIPTION
**Pull request by Nateowami**
The out put of this script can be seen at team drive > Metrics directory > Sync failure stats file > Error messages tab of the spreadsheet.

- - -
This change is [Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/2642)

### CODE REVIEW

**Review by pmachapman — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/2642)* status: all files reviewed, 1 unresolved discussion (waiting on @Nateowami)

___
*[`mongodb/SyncMetrics/FindCommonSyncFailureReasons.mongodb` line 73 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/2642#-O3AABHq5L7ZOMVPzwdh:-O3AABHrE6Pk5NO1QVU9:b-dw2n0n) ([raw file](https://github.com/sillsdev/web-xforge/blob/a5054c94a66faf9d36bbd56c8e601202672a712c/mongodb/SyncMetrics/FindCommonSyncFailureReasons.mongodb#L73)):*
> ```
>   )[0];
>   const lastSeenString = new Date(mostRecent.dateStarted).toISOString().slice(0, -1);
>   console.log(`${count}\t${lastSeenString}\t${mostRecent.projectRef}\t${message}`);
> ```

I ran this locally, but it failed when checking for a `knownErrorMessage` that was not present in my `sync_metrics`:

```
TypeError: Cannot read properties of undefined (reading 'dateStarted')
```

To recreate this, add a value to the `knownErrorMessages` array that is gibberish, then run the query script.

To fix it, I wrapped these lines in an `if` statement:

```
  if (mostRecent != null) {
    const lastSeenString = new Date(mostRecent.dateStarted).toISOString().slice(0, -1);
    console.log(`${count}\t${lastSeenString}\t${mostRecent.projectRef}\t${message}`);
  }
```



_Code quote:_
```
  const lastSeenString = new Date(mostRecent.dateStarted).toISOString().slice(0, -1);
  console.log(`${count}\t${lastSeenString}\t${mostRecent.projectRef}\t${message}`);
```

**Review by Nateowami — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/2642)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @pmachapman)

___
*[`mongodb/SyncMetrics/FindCommonSyncFailureReasons.mongodb` line 73 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/2642#-O3AABHq5L7ZOMVPzwdh:-O3DnIAu0F3fRnZcrG1n:bd0jggz) ([raw file](https://github.com/sillsdev/web-xforge/blob/a5054c94a66faf9d36bbd56c8e601202672a712c/mongodb/SyncMetrics/FindCommonSyncFailureReasons.mongodb#L73)):*
<details><summary><i>Previously, pmachapman (Peter Chapman) wrote…</i></summary><blockquote>

I ran this locally, but it failed when checking for a `knownErrorMessage` that was not present in my `sync_metrics`:

```
TypeError: Cannot read properties of undefined (reading 'dateStarted')
```

To recreate this, add a value to the `knownErrorMessages` array that is gibberish, then run the query script.

To fix it, I wrapped these lines in an `if` statement:

```
  if (mostRecent != null) {
    const lastSeenString = new Date(mostRecent.dateStarted).toISOString().slice(0, -1);
    console.log(`${count}\t${lastSeenString}\t${mostRecent.projectRef}\t${message}`);
  }
```
</blockquote></details>

Thanks for catching that. Done.

**Review by Nateowami — COMMENTED** [review]
I've also deleted `FindCurrentSyncErrors.mongodb` because it served the same purpose, but doesn't work nearly as well.

> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/2642#-:-O3Do75C5S_ZqtV-bsrQ:bp8lpa)* status: 0 of 2 files reviewed, 1 unresolved discussion (waiting on @pmachapman)

**Review by pmachapman — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/2642#-:-O3Twg6WC35x9Djul4zT:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @Nateowami)

**Pull request merged**
