### PR TITLE
Create 404 page for the back end

### PR DESCRIPTION
**Pull request by Nateowami**
The page redirects to the home page after 10 seconds. If the user is logged in, then after redirecting to the home page it should redirect to projects.

---
This change is [Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1026)

### CODE REVIEW

**Review by nigel-wells — APPROVED** [review]
Looking good - some very minor comments but nothing that needs to hold anything up.

> Reviewed 7 of 8 files at r1.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1026#-:-MZLKbPE5Aml-aKfwjub:b-mfdkk4)* status: 7 of 8 files reviewed, 3 unresolved discussions (waiting on @Nateowami)

___
*[src/SIL.XForge.Scripture/Startup.cs, line 197 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/1026#-MZLKHEs0-4lxBStrDYv:-MZLKHEs0-4lxBStrDYw:b-for3on) ([raw file](https://github.com/sillsdev/web-xforge/blob/83d1dd7fcc5427f0726d8cd618c6d24f75e3ca08/src/SIL.XForge.Scripture/Startup.cs#L197)):*
> ```
> app.UseStatusCodePagesWithReExecute("/Status{0}");
> ```
Perhaps we could store these in a `system` folder or something to separate them from the main pages in use? We may decide to add other  response pages in the future.
___
*[src/SIL.XForge.Scripture/Pages/Status404.cshtml, line 4 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/1026#-MZLIu4c7ZqH0J9AYjV2:-MZLIu4c7ZqH0J9AYjV3:b7sjt9v) ([raw file](https://github.com/sillsdev/web-xforge/blob/83d1dd7fcc5427f0726d8cd618c6d24f75e3ca08/src/SIL.XForge.Scripture/Pages/Status404.cshtml#L4)):*
> ```razor
> @model Status404Model
> 
> @section css {
> ```

nit: Perhaps we could add a meta `RenderSection` as well so that it appears further up in the rendered HTML
___
*[src/SIL.XForge.Scripture/wwwroot/scss/_404.scss, line 1 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/1026#-MZLIMxO5hk1pGq7O2Nj:-MZLIMxO5hk1pGq7O2Nk:b-ek6zgq) ([raw file](https://github.com/sillsdev/web-xforge/blob/83d1dd7fcc5427f0726d8cd618c6d24f75e3ca08/src/SIL.XForge.Scripture/wwwroot/scss/_404.scss#L1)):*
> ```SCSS
> #redirect-progress-bar {
> ```

Perhaps have `max-width` set to 500px or something as it looks a little large on desktop

**Review by nigel-wells — COMMENTED** [review]
> Reviewed 1 of 8 files at r1.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1026)* status: all files reviewed, 3 unresolved discussions (waiting on @Nateowami)

**Review by Nateowami — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1026)* status: 3 of 9 files reviewed, 2 unresolved discussions (waiting on @nigel-wells)

___
*[src/SIL.XForge.Scripture/Startup.cs, line 197 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/1026#-MZLKHEs0-4lxBStrDYv:-MZOA1g3CELd76EkxIKP:bhgbzdl) ([raw file](https://github.com/sillsdev/web-xforge/blob/83d1dd7fcc5427f0726d8cd618c6d24f75e3ca08/src/SIL.XForge.Scripture/Startup.cs#L197)):*
<details><summary><i>Previously, nigel-wells (Nigel Wells) wrote…</i></summary><blockquote>

> ```
> app.UseStatusCodePagesWithReExecute("/Status{0}");
> ```
Perhaps we could store these in a `system` folder or something to separate them from the main pages in use? We may decide to add other  response pages in the future.
</blockquote></details>

I put it in a `Status` folder. There's also a 503 page, but as far as I can tell that's served up by Apache when our .NET server is unavailable, so it's not a Razor page.
___
*[src/SIL.XForge.Scripture/wwwroot/scss/_404.scss, line 1 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/1026#-MZLIMxO5hk1pGq7O2Nj:-MZOBReR4q_KL-bo-cCi:b-896fix) ([raw file](https://github.com/sillsdev/web-xforge/blob/83d1dd7fcc5427f0726d8cd618c6d24f75e3ca08/src/SIL.XForge.Scripture/wwwroot/scss/_404.scss#L1)):*
<details><summary><i>Previously, nigel-wells (Nigel Wells) wrote…</i></summary><blockquote>

Perhaps have `max-width` set to 500px or something as it looks a little large on desktop
</blockquote></details>

Done.
___
*[src/SIL.XForge.Scripture/Pages/Status404.cshtml, line 4 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/1026#-MZLIu4c7ZqH0J9AYjV2:-MZOBNry6yIRUGKwol38:b-896fix) ([raw file](https://github.com/sillsdev/web-xforge/blob/83d1dd7fcc5427f0726d8cd618c6d24f75e3ca08/src/SIL.XForge.Scripture/Pages/Status404.cshtml#L4)):*
<details><summary><i>Previously, nigel-wells (Nigel Wells) wrote…</i></summary><blockquote>

nit: Perhaps we could add a meta `RenderSection` as well so that it appears further up in the rendered HTML
</blockquote></details>

Done.

**Review by nigel-wells — APPROVED** [review]
> Reviewed 6 of 6 files at r2.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1026)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @Nateowami)

**Review by nigel-wells — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1026#-:-MZPCtMgA4pFQq8weQkZ:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @Nateowami)

**Pull request merged**
