### PR TITLE
SF-2226 Report Pre-Translation job upload errors on the Generate Draft screen

### PR DESCRIPTION
**Pull request by pmachapman**
When an error occurs during the uploading of the pre-translation corpus, this PR reports these errors to the user on the pre-translation "Generate Draft" screen and allows them to re-generate the draft.

- - -
This change is [Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/2038)

### CODE REVIEW

**Comment by Nateowami** [comment]
@pmachapman How does this relate to / affect #1996?

**Review by pmachapman — COMMENTED** [review]
This PR is complimentary to #1996 - it provides fault information to the frontend when the fault occurs during the upload to SErval.

> Dismissed @github-code-scanning[bot] from 3 discussions.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/2038#-:-Ndbpvx75pD1vEvdNOrc:bug6bkt)* status: 0 of 12 files reviewed, all discussions resolved (waiting on @github-code-scanning[bot])

**Review by RaymondLuong3 — CHANGES_REQUESTED** [review]
Since these changes do not change the front end, I assume that the front end already has a way to display the error message? Is that correct? How would the error message be localized, or is it only supposed to be useful for developers? Did you want to add the `PreTranslationErrorMessage` property to the front-end `sf-project-secrets.ts` model?

> Reviewed 1 of 12 files at r1, 11 of 11 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/2038#-:-NdgWhQv5xjW2oBtrgLN:bntabek)* status: all files reviewed, 1 unresolved discussion (waiting on @pmachapman)

___
*[`src/SIL.XForge.Scripture/Services/MachineApiService.cs` line 461 at r3](https://reviewable.io/reviews/sillsdev/web-xforge/2038#-NdgTzCe7NJ5EI36bjg8:-NdgTzCfBWWSnWWuwR5w:brsrltb) ([raw file](https://github.com/sillsdev/web-xforge/blob/64deac60084578ca4678e69ef519a05b7ae4c4cc/src/SIL.XForge.Scripture/Services/MachineApiService.cs#L461)):*
> ```Smalltalk
>             )
>         )
>         {
> ```

I find it hard to understand when if statements get complex like this. Can we simplify this by assigning the statements to variables? 



_Code quote:_
```Smalltalk
        if (
            (await _projectSecrets.TryGetAsync(sfProjectId)).TryResult(out SFProjectSecret projectSecret)
            && (
                projectSecret.ServalData?.PreTranslationQueuedAt is not null
                || !string.IsNullOrWhiteSpace(projectSecret.ServalData?.PreTranslationErrorMessage)
            )
        )
        {
```

**Review by pmachapman — COMMENTED** [review]
No the front end does not display the error. I can't think of a way to localize it - at this time it will only be readable by us in the database. There is no `sf-project-secrets.ts` model as these values are not meant to be accessible directly via the frontend.

There is nothing to stop the frontend displaying this value though in future if we want to. I am not sure if we want to yet, except perhaps only to power users (i.e. when the ability for users to specify custom NMT parameters is added later down the track)

> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/2038#-:-NdhUjFYDmYeJE2l7ZDo:bcpjb50)* status: 11 of 12 files reviewed, 1 unresolved discussion (waiting on @RaymondLuong3)

___
*[`src/SIL.XForge.Scripture/Services/MachineApiService.cs` line 461 at r3](https://reviewable.io/reviews/sillsdev/web-xforge/2038#-NdgTzCe7NJ5EI36bjg8:-NdhVZfZCmw75n2Sh-yH:b-sas0tt) ([raw file](https://github.com/sillsdev/web-xforge/blob/64deac60084578ca4678e69ef519a05b7ae4c4cc/src/SIL.XForge.Scripture/Services/MachineApiService.cs#L461)):*
<details><summary><i>Previously, RaymondLuong3 (Raymond Luong) wrote…</i></summary><blockquote>

I find it hard to understand when if statements get complex like this. Can we simplify this by assigning the statements to variables?
</blockquote></details>

You are right...that is a shocker. Is it clearer now?

**Review by RaymondLuong3 — APPROVED** [review]
Thanks for your work. I updated the acceptance test for the testers with what I was seeing. If it needs to be changed, you should leave a comment.

> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/2038#-:-NdptcNO3fzn2yC0iKxW:b1dqwxu)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @pmachapman)

**Pull request merged**
