### PR TITLE
SF-1382 Fail gracefully when projects or resources can't be loaded

### PR DESCRIPTION
**Pull request by Nateowami**
Connect project page and settings page have been changed to handle errors when fetching projects or resources.

Tests have only been fixed to compile and are failing, but I think the rest of it is pretty much ready for review and manual testing. It's working in my tests.

You can rewrite `getResources()` in `paratext.service.ts` to be `return Promise.reject(new Error('Unreasonable error'))` and that will simulate an actual failure.

---
This change is [Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1121)

### CODE REVIEW

**Review by irahopkinson — CHANGES_REQUESTED** [review]
Thanks for getting this done so quickly. It would be good to check we don't introduce another bug though, are you happy with the code coverage of your changes?

> Reviewed 11 of 11 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1121#-:-MgnONoT45dy7XBw_FDc:b-1x9w1m)* status: all files reviewed, 5 unresolved discussions (waiting on @Nateowami)

___
*[src/SIL.XForge.Scripture/ClientApp/src/app/connect-project/connect-project.component.ts, line 41 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/1121#-Mgn8S4sE-h8VJu4MF_d:-Mgn8S4sE-h8VJu4MF_e:b-lbwva0) ([raw file](https://github.com/sillsdev/web-xforge/blob/61a52840deef4792aa87e89f7118e7ca2a2d7f2b/src/SIL.XForge.Scripture/ClientApp/src/app/connect-project/connect-project.component.ts#L41)):*
> ```
> resourceLoadingFailed = false;
> ```
This is set here only once but `populateProjectList` is potentially called every time we come online. Additionally this assignment is not strictly correct and therefore I wonder if it will cause us issues, however it may not so feel free to disagree. At this point `resourceLoadingFailed` is undefined since we haven't tried to load resources yet. It only becomes false once we successfully load resources. A more useful variable might be `haveResourcesLoaded` which is undefined before any call to the promise to get resources and is set true or false when the promise resolves.
___
*[src/SIL.XForge.Scripture/ClientApp/src/app/connect-project/connect-project.component.ts, line 219 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/1121#-MgnA3vED9m3OJc1mNXN:-MgnA3vED9m3OJc1mNXO:b-sqoulm) ([raw file](https://github.com/sillsdev/web-xforge/blob/61a52840deef4792aa87e89f7118e7ca2a2d7f2b/src/SIL.XForge.Scripture/ClientApp/src/app/connect-project/connect-project.component.ts#L219)):*
> ```
>     this.paratextService
>       .getResources()
> ```
So this call should keep our loading projects and resources in parallel but we no longer await this promise before calling `this.loadingFinished()` below. Would it work to assign the promise to a const and then await it before calling `this.loadingFinished()`?
___
*[src/SIL.XForge.Scripture/ClientApp/src/app/connect-project/connect-project.component.spec.ts, line 66 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/1121#-MgnBrov2twLcW97xGVG:-MgnBrov2twLcW97xGVH:b-4rbxyf) ([raw file](https://github.com/sillsdev/web-xforge/blob/61a52840deef4792aa87e89f7118e7ca2a2d7f2b/src/SIL.XForge.Scripture/ClientApp/src/app/connect-project/connect-project.component.spec.ts#L66)):*
> ```
> env.setupProjectsResources
> ```
Nice cleanup.
___
*[src/SIL.XForge.Scripture/ClientApp/src/app/core/paratext.service.ts, line 34 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/1121#-MgnCRFU9rfIxHHCIY7w:-MgnCRFU9rfIxHHCIY7x:b-nhr44n) ([raw file](https://github.com/sillsdev/web-xforge/blob/61a52840deef4792aa87e89f7118e7ca2a2d7f2b/src/SIL.XForge.Scripture/ClientApp/src/app/core/paratext.service.ts#L34)):*
> ```
> getResources()
> ```
Good cleanup after the SF-1374 #1120 change.
___
*[src/SIL.XForge.Scripture/ClientApp/src/app/settings/settings.component.ts, line 54 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/1121#-MgnIEvQ6p_35r9Jrc-v:-MgnIEvQ6p_35r9Jrc-w:b-ovww56) ([raw file](https://github.com/sillsdev/web-xforge/blob/61a52840deef4792aa87e89f7118e7ca2a2d7f2b/src/SIL.XForge.Scripture/ClientApp/src/app/settings/settings.component.ts#L54)):*
> ```
>   projectLoadingFailed = false;
>   resourceLoadingFailed = false;
>   mainSettingsLoaded = false;
> ```
I have the same concern for these variables as outlined in `connect-project.component.ts`.
___
*[src/SIL.XForge.Scripture/ClientApp/src/app/settings/settings.component.ts, line 132 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/1121#-MgnJAph7kI7_Wzh0Xrz:-MgnJAph7kI7_Wzh0Xs-:b-n3mr2m) ([raw file](https://github.com/sillsdev/web-xforge/blob/61a52840deef4792aa87e89f7118e7ca2a2d7f2b/src/SIL.XForge.Scripture/ClientApp/src/app/settings/settings.component.ts#L132)):*
> ```
> const mainSettingsPromise = Promise.all([
> ```
This now gets everything called in parallel but its harder to read and understand. It's fine for this PR but I'm thinking about better ways to do this. I found this article helpful https://medium.com/@vcarl/handling-errors-with-async-await-and-promises-cd2fea534f08 and you may want to apply some of its good learning to this PR.
___
*[src/SIL.XForge.Scripture/ClientApp/src/app/settings/settings.component.ts, line 163 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/1121#-MgnHUks7ywvA9eniKDP:-MgnHUks7ywvA9eniKDQ:b-6yleh0) ([raw file](https://github.com/sillsdev/web-xforge/blob/61a52840deef4792aa87e89f7118e7ca2a2d7f2b/src/SIL.XForge.Scripture/ClientApp/src/app/settings/settings.component.ts#L163)):*
> ```
>         this.updateSettingsInfo();
>         this.updateNonSelectableProjects();
>         this.updateFormEnabled();
> ```
Since we have these do we still need them above when we get the projectDoc? I don't feel like we should need them in both places, but perhaps I'm missing something that needs to happen as soon as we get the projectDoc?

**Review by Nateowami — COMMENTED** [review]
I still want to write tests for this. When I first opened the PR I just got the tests to compile but no pass. Later in the day I got them passing, but I haven't written new ones yet, as I ran out of time in the day.

> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1121#-:-Mgprq7EDDWw9hOq30iG:b-y2wtra)* status: 8 of 11 files reviewed, 5 unresolved discussions (waiting on @irahopkinson)

___
*[src/SIL.XForge.Scripture/ClientApp/src/app/connect-project/connect-project.component.ts, line 41 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/1121#-Mgn8S4sE-h8VJu4MF_d:-Mgpf_EP4Z_je5X2GBGT:bgalhll) ([raw file](https://github.com/sillsdev/web-xforge/blob/61a52840deef4792aa87e89f7118e7ca2a2d7f2b/src/SIL.XForge.Scripture/ClientApp/src/app/connect-project/connect-project.component.ts#L41)):*
<details><summary><i>Previously, irahopkinson (Ira Hopkinson) wrote…</i></summary><blockquote>

> ```
> resourceLoadingFailed = false;
> ```
This is set here only once but `populateProjectList` is potentially called every time we come online. Additionally this assignment is not strictly correct and therefore I wonder if it will cause us issues, however it may not so feel free to disagree. At this point `resourceLoadingFailed` is undefined since we haven't tried to load resources yet. It only becomes false once we successfully load resources. A more useful variable might be `haveResourcesLoaded` which is undefined before any call to the promise to get resources and is set true or false when the promise resolves.
</blockquote></details>

There are three possible states for the loading of resources to be in: not loaded yet, succeeded, or failed. This variable is *only* interested in whether we are in the last state. I've renamed it to `showResourcesLoadingFailedMessage`, which should make it more clear what it is intended for and prevent accidental misuse of it in the future.
___
*[src/SIL.XForge.Scripture/ClientApp/src/app/connect-project/connect-project.component.ts, line 219 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/1121#-MgnA3vED9m3OJc1mNXN:-MgpfV0k9f2-FSFs8In7:b9q61qr) ([raw file](https://github.com/sillsdev/web-xforge/blob/61a52840deef4792aa87e89f7118e7ca2a2d7f2b/src/SIL.XForge.Scripture/ClientApp/src/app/connect-project/connect-project.component.ts#L219)):*
<details><summary><i>Previously, irahopkinson (Ira Hopkinson) wrote…</i></summary><blockquote>

> ```
>     this.paratextService
>       .getResources()
> ```
So this call should keep our loading projects and resources in parallel but we no longer await this promise before calling `this.loadingFinished()` below. Would it work to assign the promise to a const and then await it before calling `this.loadingFinished()`?
</blockquote></details>

I've reworked this a bit.
___
*[src/SIL.XForge.Scripture/ClientApp/src/app/core/paratext.service.ts, line 34 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/1121#-MgnCRFU9rfIxHHCIY7w:-MgpgTc30UJnYBtN1JuR:b-8fgfgd) ([raw file](https://github.com/sillsdev/web-xforge/blob/61a52840deef4792aa87e89f7118e7ca2a2d7f2b/src/SIL.XForge.Scripture/ClientApp/src/app/core/paratext.service.ts#L34)):*
<details><summary><i>Previously, irahopkinson (Ira Hopkinson) wrote…</i></summary><blockquote>

> ```
> getResources()
> ```
Good cleanup after the SF-1374 #1120 change.
</blockquote></details>

The deconstructing syntax (`map(([paratextId, [shortName, projectName]]) => ({`) was hard to get right, but due to an incorrect generic type on the `http.get()` call, it was impossible to get right.

Before I touched this code the first time we were sending back an array of objects, where each object was all information we had about a resource. That was a ton of data to send over the network, so I changed it to an object mapping Paratext IDs to project names. Somehow I was able to satisfy the type system while still having mismatched types.

When I added in the short names I didn't catch the mistake and couldn't get the type system happy.
___
*[src/SIL.XForge.Scripture/ClientApp/src/app/settings/settings.component.ts, line 54 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/1121#-MgnIEvQ6p_35r9Jrc-v:-MgphqqI8Nidi4cnBBmR:b-kisr3x) ([raw file](https://github.com/sillsdev/web-xforge/blob/61a52840deef4792aa87e89f7118e7ca2a2d7f2b/src/SIL.XForge.Scripture/ClientApp/src/app/settings/settings.component.ts#L54)):*
<details><summary><i>Previously, irahopkinson (Ira Hopkinson) wrote…</i></summary><blockquote>

> ```
>   projectLoadingFailed = false;
>   resourceLoadingFailed = false;
>   mainSettingsLoaded = false;
> ```
I have the same concern for these variables as outlined in `connect-project.component.ts`.
</blockquote></details>

Once again we're only concerned with whether we are in the failed state. These variables are used only to determine which error messages to show, and whether to disable the based-on project select.

I can't rename them to `showProjectLoadingFailedMessage` and `showResourceLoadingFailedMessage`, because the logic we use with them is slightly more complicated (we have three error messages, depending on whether one, the other, or both are true, and if they're both true we disable the based-on project select).

`mainSettingsLoaded` is slightly different as it's used to determine when form field should be enabled. But it still only needs to tell us one thing; whether or not the main settings have been loaded yet.

While in some cases it's useful to have three states for a variable, I think when possible it's better to have just two. If a boolean variable has three states and someone mistakenly assumes it only has two because it's boolean, then it could lead to missing a necessary check. This pitfall is avoided if we keep to just two possible states.
___
*[src/SIL.XForge.Scripture/ClientApp/src/app/settings/settings.component.ts, line 132 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/1121#-MgnJAph7kI7_Wzh0Xrz:-MgrTiHa4JcblOqSbVh7:bav2be4) ([raw file](https://github.com/sillsdev/web-xforge/blob/61a52840deef4792aa87e89f7118e7ca2a2d7f2b/src/SIL.XForge.Scripture/ClientApp/src/app/settings/settings.component.ts#L132)):*
<details><summary><i>Previously, irahopkinson (Ira Hopkinson) wrote…</i></summary><blockquote>

> ```
> const mainSettingsPromise = Promise.all([
> ```
This now gets everything called in parallel but its harder to read and understand. It's fine for this PR but I'm thinking about better ways to do this. I found this article helpful https://medium.com/@vcarl/handling-errors-with-async-await-and-promises-cd2fea534f08 and you may want to apply some of its good learning to this PR.
</blockquote></details>

Thanks. I've taken a look at it. I have some ideas for how this may be simplified.
___
*[src/SIL.XForge.Scripture/ClientApp/src/app/settings/settings.component.ts, line 163 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/1121#-MgnHUks7ywvA9eniKDP:-MgrT_aEDY5GdF8rNcR_:bw66wq0) ([raw file](https://github.com/sillsdev/web-xforge/blob/61a52840deef4792aa87e89f7118e7ca2a2d7f2b/src/SIL.XForge.Scripture/ClientApp/src/app/settings/settings.component.ts#L163)):*
<details><summary><i>Previously, irahopkinson (Ira Hopkinson) wrote…</i></summary><blockquote>

> ```
>         this.updateSettingsInfo();
>         this.updateNonSelectableProjects();
>         this.updateFormEnabled();
> ```
Since we have these do we still need them above when we get the projectDoc? I don't feel like we should need them in both places, but perhaps I'm missing something that needs to happen as soon as we get the projectDoc?
</blockquote></details>

I've changed this significantly. Let me know if it's still confusing.

**Review by Nateowami — COMMENTED** [review]
I've added a test for the connect project page. The settings page is more complicated and the tests for that still need to be written.

> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1121#-:-Mgriz1IADLn45dQjk_C:b-ld1wqe)* status: 8 of 11 files reviewed, 5 unresolved discussions (waiting on @irahopkinson)

**Review by Nateowami — COMMENTED** [review]
Basic tests are now present. I would like to flesh them out a bit more, but I don't think that needs to hold this up.

> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1121#-:-MgwZIEK0e2XpCdwXvoJ:b-fy3os1)* status: 9 of 11 files reviewed, all discussions resolved (waiting on @irahopkinson)

**Review by irahopkinson — APPROVED** [review]
:lgtm: thanks for this nice UX improvement.

> Reviewed 1 of 1 files at r3, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1121#-:-Mgx46UUBhwx1zIjtBDw:b-qljpor)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @Nateowami)

**Comment by Nateowami** [comment]
@irahopkinson Should I open a hotfix for qa or live?

**Pull request merged**
