### PR TITLE
SF-3030 Update to Angular 18

### PR DESCRIPTION
**Pull request by kylebuss**
This PR provides updates to Angular 18. When pulling/merging this request `npm ci` will need to be ran in the console for both ClientApp.

`@storybook/test` and `@storybook/testing-library` are not combined into `@storybook/test` and a number of spec files required updates to `import` and `providers` this update followed the guide [here](https://storybook.js.org/docs/configure/upgrading).

This update has introduced control flow warnings on `@for` loops to ensure tracking is done on a unique key. More can be read [here](https://angular.dev/errors/NG0955).

Angular Material adds support for M3, to maintain M2 compatibility this update required a few `.scss` changes. To learn more about material functions here's the [guide](https://angular-material.dev/articles/updating-to-angular-material-18#conclusion) I used.

Additional packages/dependencies that were updated to be compatible with Angular 18:

- ngx-cookie-service
- ngx-quill
- @angular-eslint
- @types/jest (added)
- @types/node
- @typescript-eslint
- typescript

- - -
This change is [Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/2804)

### CODE REVIEW

**Review by Nateowami — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/2804)* status: 0 of 24 files reviewed, 1 unresolved discussion (waiting on @kylebuss)

___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-answers/checking-comments/checking-comments.stories.ts` line 4 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/2804#-O9FhSIn9S0g28AQLrzq:-O9FhSIn9S0g28AQLrzr:b-biuexe) ([raw file](https://github.com/sillsdev/web-xforge/blob/58daa69f5facecbec6fbb053b04cea0daaa460b0/src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-answers/checking-comments/checking-comments.stories.ts#L4)):*
> ```XML
> import { Meta, moduleMetadata, StoryObj } from '@storybook/angular';
> import { expect } from '@storybook/test';
> import { within } from '@storybook/test';
> ```

I'm surprised this didn't get auto-formatted on save to only import once, and I'm seeing a lot of reformatting that doesn't seem necessary.

**Review by kylebuss — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/2804)* status: 0 of 24 files reviewed, 1 unresolved discussion (waiting on @Nateowami)

___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-answers/checking-comments/checking-comments.stories.ts` line 4 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/2804#-O9FhSIn9S0g28AQLrzq:-O9G9EVp6v9ibRwz6bts:b-i9d9hr) ([raw file](https://github.com/sillsdev/web-xforge/blob/58daa69f5facecbec6fbb053b04cea0daaa460b0/src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-answers/checking-comments/checking-comments.stories.ts#L4)):*
<details><summary><i>Previously, Nateowami wrote…</i></summary><blockquote>

I'm surprised this didn't get auto-formatted on save to only import once, and I'm seeing a lot of reformatting that doesn't seem necessary.
</blockquote></details>

I'll fix the import statements. The update combined `@storybook/jest` and `@storybook/testing-library` into `@storybook/test` which is why some of the stories looked like this. 

The automerge tool also did the reformatting you're observing. The only file I had to fix was the `font-size.stories.ts`.

**Comment by Nateowami** [comment]
What's the automerge tool?

**Review by kylebuss — COMMENTED** [review]
Sorry, [automigrate](https://storybook.js.org/docs/configure/upgrading#automigrate-script) `npx storybook@latest automigrate` which ran when I performed the update `npx storybook@latest upgrade`.

> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/2804#-:-O9GEHQWATVg-SdqPmIR:bgx9hfk)* status: 0 of 24 files reviewed, 1 unresolved discussion (waiting on @Nateowami)

**Review by RaymondLuong3 — COMMENTED** [review]
> Reviewed 14 of 24 files at r1, 8 of 8 files at r2, 68 of 68 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/2804)* status: all files reviewed, 3 unresolved discussions (waiting on @kylebuss and @Nateowami)

___
*[`src/SIL.XForge.Scripture/ClientApp/tsconfig.json` line 10 at r3](https://reviewable.io/reviews/sillsdev/web-xforge/2804#-O9W-nkw2UJYevPLg4fR:-O9W-nkw2UJYevPLg4fS:bwnbsam) ([raw file](https://github.com/sillsdev/web-xforge/blob/233520eb0128ded35b65b20ae7f323fd44de4020/src/SIL.XForge.Scripture/ClientApp/tsconfig.json#L10)):*
> ```jsonc
>     "strictNullChecks": false,
>     "noImplicitAny": false,
>     "noImplicitReturns": false,
> ```

Any reason for turning off no implicit returns?



_Code quote:_
```jsonc
    "noImplicitReturns": false,
```
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-answers/checking-comments/checking-comments.component.html` line 2 at r3](https://reviewable.io/reviews/sillsdev/web-xforge/2804#-O9W0omQEmFpYUxLMpaV:-O9W0omQEmFpYUxLMpaW:b-sub09e) ([raw file](https://github.com/sillsdev/web-xforge/blob/233520eb0128ded35b65b20ae7f323fd44de4020/src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-answers/checking-comments/checking-comments.component.html#L2)):*
> ```HTML
> <ng-container *transloco="let t; read: 'checking_comments'">
>   @for (comment of getSortedComments(); track $index; let i = $index) {
> ```

I read the `@for` article about duplicate keys. Is that what is going on here? Wouldn't it be better to track a unique property within a comment? Such as comment.dataId?



_Code quote:_
```HTML
  @for (comment of getSortedComments(); track $index; let i = $index) {
```

**Review by kylebuss — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/2804)* status: all files reviewed, 2 unresolved discussions (waiting on @Nateowami and @RaymondLuong3)

___
*[`src/SIL.XForge.Scripture/ClientApp/tsconfig.json` line 10 at r3](https://reviewable.io/reviews/sillsdev/web-xforge/2804#-O9W-nkw2UJYevPLg4fR:-O9WEEZVDe-7vQpLnCM5:b-i5x8ru) ([raw file](https://github.com/sillsdev/web-xforge/blob/233520eb0128ded35b65b20ae7f323fd44de4020/src/SIL.XForge.Scripture/ClientApp/tsconfig.json#L10)):*
<details><summary><i>Previously, RaymondLuong3 (Raymond Luong) wrote…</i></summary><blockquote>

Any reason for turning off no implicit returns?
</blockquote></details>

Yes, we have 25-30 functions that throw `error TS7030: Not all code paths return a value.` because they have `return;`. I meant to say something about this as I didn't know if it was in scope for this change or something we want to address separately. 
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-answers/checking-comments/checking-comments.component.html` line 2 at r3](https://reviewable.io/reviews/sillsdev/web-xforge/2804#-O9W0omQEmFpYUxLMpaV:-O9WFsJhEL0NOS24r4CF:b-2eq2qv) ([raw file](https://github.com/sillsdev/web-xforge/blob/233520eb0128ded35b65b20ae7f323fd44de4020/src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-answers/checking-comments/checking-comments.component.html#L2)):*
<details><summary><i>Previously, RaymondLuong3 (Raymond Luong) wrote…</i></summary><blockquote>

I read the `@for` article about duplicate keys. Is that what is going on here? Wouldn't it be better to track a unique property within a comment? Such as comment.dataId?
</blockquote></details>

I think normally, yes, using `comment.dataId` would be preferred. However, because we are using `let i = $index` and `i` is used in the loop I think it makes more sense to track on `$index` here.

**Review by Nateowami — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/2804)* status: all files reviewed, 2 unresolved discussions (waiting on @kylebuss and @RaymondLuong3)

___
*[`src/SIL.XForge.Scripture/ClientApp/tsconfig.json` line 10 at r3](https://reviewable.io/reviews/sillsdev/web-xforge/2804#-O9W-nkw2UJYevPLg4fR:-O9WKZL6ELIqjUfx0yy-:b-6qxd71) ([raw file](https://github.com/sillsdev/web-xforge/blob/233520eb0128ded35b65b20ae7f323fd44de4020/src/SIL.XForge.Scripture/ClientApp/tsconfig.json#L10)):*
<details><summary><i>Previously, kylebuss (Kyle Buss) wrote…</i></summary><blockquote>

Yes, we have 25-30 functions that throw `error TS7030: Not all code paths return a value.` because they have `return;`. I meant to say something about this as I didn't know if it was in scope for this change or something we want to address separately.
</blockquote></details>

I assume they could be changed to `return undefined;`? It should be easy to do a global find and replace of `return;` to `return undefined;` (if we want to do that).

**Review by RaymondLuong3 — CHANGES_REQUESTED** [review]
Nice work getting past all the hurdles to make this upgrade. Well done. I just noticed a small UI related glitch related to the offline icon. It should be an easy fix. I think we should send this to testers for a surface level inspection.


> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/2804#-:-O9Whrjn5iZ8Hg4A2MqV:b-n94if4)* status: all files reviewed, 1 unresolved discussion (waiting on @kylebuss)

___
*[`src/SIL.XForge.Scripture/ClientApp/tsconfig.json` line 10 at r3](https://reviewable.io/reviews/sillsdev/web-xforge/2804#-O9W-nkw2UJYevPLg4fR:-O9Wffox5mAEKFMjAz1t:b-3x561r) ([raw file](https://github.com/sillsdev/web-xforge/blob/233520eb0128ded35b65b20ae7f323fd44de4020/src/SIL.XForge.Scripture/ClientApp/tsconfig.json#L10)):*
<details><summary><i>Previously, Nateowami wrote…</i></summary><blockquote>

I assume they could be changed to `return undefined;`? It should be easy to do a global find and replace of `return;` to `return undefined;` (if we want to do that).
</blockquote></details>

That's reasonable. I'm OK either we make that change or not.
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-answers/checking-comments/checking-comments.component.html` line 2 at r3](https://reviewable.io/reviews/sillsdev/web-xforge/2804#-O9W0omQEmFpYUxLMpaV:-O9WfoAq1Mp7zgtKz2Wp:b-x2m55b) ([raw file](https://github.com/sillsdev/web-xforge/blob/233520eb0128ded35b65b20ae7f323fd44de4020/src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-answers/checking-comments/checking-comments.component.html#L2)):*
<details><summary><i>Previously, kylebuss (Kyle Buss) wrote…</i></summary><blockquote>

I think normally, yes, using `comment.dataId` would be preferred. However, because we are using `let i = $index` and `i` is used in the loop I think it makes more sense to track on `$index` here.
</blockquote></details>

That is probably reasonable to do that. I haven't seen `track $index` until this PR. I'll keep note of that possiblity.

**Review by kylebuss — COMMENTED** [review]
Good catch. There is a good chance there's a number of little things like this we will start finding!

> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/2804#-:-O9WjPg9CRFoxDa4ESM-:bvsl4hc)* status: all files reviewed, 1 unresolved discussion (waiting on @kylebuss)

___
*[`src/SIL.XForge.Scripture/ClientApp/tsconfig.json` line 10 at r3](https://reviewable.io/reviews/sillsdev/web-xforge/2804#-O9W-nkw2UJYevPLg4fR:-O9Wiy7H8Q5fEY8RAI61:be0dyb9) ([raw file](https://github.com/sillsdev/web-xforge/blob/233520eb0128ded35b65b20ae7f323fd44de4020/src/SIL.XForge.Scripture/ClientApp/tsconfig.json#L10)):*
<details><summary><i>Previously, RaymondLuong3 (Raymond Luong) wrote…</i></summary><blockquote>

That's reasonable. I'm OK either we make that change or not.
</blockquote></details>

I can make the change now. I was thinking it was in a lot more places originally.

**Review by kylebuss — COMMENTED** [review]
Resolved `noImplicitReturns` errors and offline indicator display.

> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/2804#-:-O9Wsr2y7-jcFjDeDcyO:b-bexzmw)* status: 87 of 102 files reviewed, all discussions resolved (waiting on @RaymondLuong3)

**Review by Nateowami — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/2804)* status: 87 of 102 files reviewed, all discussions resolved (waiting on @RaymondLuong3)

___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-answers/checking-comments/checking-comments.component.html` line 2 at r3](https://reviewable.io/reviews/sillsdev/web-xforge/2804#-O9W0omQEmFpYUxLMpaV:-O9Xb266C0FYxoKA0kNZ:bmf0o1s) ([raw file](https://github.com/sillsdev/web-xforge/blob/233520eb0128ded35b65b20ae7f323fd44de4020/src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-answers/checking-comments/checking-comments.component.html#L2)):*
<details><summary><i>Previously, RaymondLuong3 (Raymond Luong) wrote…</i></summary><blockquote>

That is probably reasonable to do that. I haven't seen `track $index` until this PR. I'll keep note of that possiblity.
</blockquote></details>

Isn't it potentially possible for the a comment to come over the realtime server that change the index of some of the comments, making them no longer track correctly?

**Comment by kylebuss** [comment]
*[`src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-answers/checking-comments/checking-comments.component.html` line 2 at r3](https://reviewable.io/reviews/sillsdev/web-xforge/2804#-O9W0omQEmFpYUxLMpaV:-O9ZJSV_A_V4IzEvMBY4:bk0nlre) ([raw file](https://github.com/sillsdev/web-xforge/blob/233520eb0128ded35b65b20ae7f323fd44de4020/src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-answers/checking-comments/checking-comments.component.html#L2)):*
<details><summary><i>Previously, Nateowami wrote…</i></summary><blockquote>

Isn't it potentially possible for the a comment to come over the realtime server that change the index of some of the comments, making them no longer track correctly?
</blockquote></details>

Good point. I'd rather not risk finding out if this is a possibility. It looks like `$index` should only be used on static collections, so I updated/reverted the loops that I could to not use it.

**Review by RaymondLuong3 — APPROVED** [review]
> Reviewed 15 of 15 files at r4, 3 of 3 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/2804)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @kylebuss)

___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-answers/checking-comments/checking-comments.component.html` line 2 at r3](https://reviewable.io/reviews/sillsdev/web-xforge/2804#-O9W0omQEmFpYUxLMpaV:-O9k1zX56-CCq8tlJP97:b-1p2l4p) ([raw file](https://github.com/sillsdev/web-xforge/blob/233520eb0128ded35b65b20ae7f323fd44de4020/src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-answers/checking-comments/checking-comments.component.html#L2)):*
<details><summary><i>Previously, kylebuss (Kyle Buss) wrote…</i></summary><blockquote>

Good point. I'd rather not risk finding out if this is a possibility. It looks like `$index` should only be used on static collections, so I updated/reverted the loops that I could to not use it.
</blockquote></details>

From my understanding, the index of a comment would not change since we are getting the comments sorted... well if a user created a comment offline and the come online, then the index of the comments could change. Ok, let's stick with the existing behaviour and not do too much on update PRs like this.

**Comment by RaymondLuong3** [comment]
I am still seeing the offline icon not being positioned correctly. That should be a quick fix, so I'll leave this in the ready to test column.

**Review by kylebuss — COMMENTED** [review]
@RaymondLuong3, not sure what I was looking at before as I should have compared to QA. The offline indicator should now be showing in the correct spot.

> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/2804#-:-O9kMzxg7WsyOldDUFZP:b-78chcc)* status: 100 of 102 files reviewed, all discussions resolved (waiting on @RaymondLuong3)

**Review by RaymondLuong3 — CHANGES_REQUESTED** [review]
Yes, the test you added does not actually test the code you added in ParatextService.
Update: Sorry, this was posted in the wrong thread.

> Reviewed 3 of 3 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/2804#-:-OAIxetJAkUT_5io3rgb:bthfbqn)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @kylebuss)

**Review by RaymondLuong3 — APPROVED** [review]
Great work. Let's merge it and see what merge conflicts we get ;)

> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/2804#-:-OAJ63eM-yHbN59vEman:bljgzee)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @kylebuss)

**Pull request merged**
