### PR TITLE
SF-1664 Reword project settings page

### PR DESCRIPTION
**Pull request by Nateowami**
- - -
This change is [Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1455)

### CODE REVIEW

**Review by RaymondLuong3 — CHANGES_REQUESTED** [review]
You will want to make some changes to the connect project page also. At least change the "Specific users" radio button to be "Email invitations only". But adding the sharing subgroup to make the connect project page consistent would also be good.

> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1455#-:-N8ZSdbjB-Res89Vbe7a:bmeq3rn)* status: all files reviewed, 2 unresolved discussions (waiting on @Nateowami)

___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/settings/settings.component.scss` line 129 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/1455#-N8ZQ7D29k-fjFxEfBv1:-N8ZQ7D29k-fjFxEfBv2:b4yl5m6) ([raw file](https://github.com/sillsdev/web-xforge/blob/79e874cee6a6f2aed221a1a1198336de56cecc9c/src/SIL.XForge.Scripture/ClientApp/src/app/settings/settings.component.scss#L129)):*
> ```SCSS
> }
> 
> .mat-card-content {
> ```

This could be merged into the definition below.



_Code quote:_
```SCSS
.mat-card-content {
  margin: 0;
}
```
___
*[`src/SIL.XForge.Scripture/ClientApp/src/assets/i18n/non_checking_en.json` line 228 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/1455#-N8ZRuVO8pwsbC0FNnsC:-N8ZRuVO8pwsbC0FNnsD:b-6byrcc) ([raw file](https://github.com/sillsdev/web-xforge/blob/79e874cee6a6f2aed221a1a1198336de56cecc9c/src/SIL.XForge.Scripture/ClientApp/src/assets/i18n/non_checking_en.json#L228)):*
> ```JSON
>     "tools": "Tools",
>     "translate": "Translation Settings",
>     "translation_suggestions_require_source_text": "Note: Translation suggestions are only available if you select a source text.",
> ```

How about changing the wording to be "Note: Translation suggestions are only available if a source text is selected."



_Code quote:_
```JSON
    "translation_suggestions_require_source_text": "Note: Translation suggestions are only available if you select a source text.",
```

**Review by Nateowami — COMMENTED** [review]
> You will want to make some changes to the connect project page also. At least change the "Specific users" radio button to be "Email invitations only".

That's not actually on the connect project page.

> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1455#-:-N8ZVcyC4d3q6JzNrAQ6:b-r0s1gs)* status: 1 of 3 files reviewed, 2 unresolved discussions (waiting on @RaymondLuong3)

___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/settings/settings.component.scss` line 129 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/1455#-N8ZQ7D29k-fjFxEfBv1:-N8ZVrPb9BE2IRuvWnG2:boj1qgt) ([raw file](https://github.com/sillsdev/web-xforge/blob/79e874cee6a6f2aed221a1a1198336de56cecc9c/src/SIL.XForge.Scripture/ClientApp/src/app/settings/settings.component.scss#L129)):*
<details><summary><i>Previously, RaymondLuong3 (Raymond Luong) wrote…</i></summary><blockquote>

This could be merged into the definition below.
</blockquote></details>

Good catch. Done.
___
*[`src/SIL.XForge.Scripture/ClientApp/src/assets/i18n/non_checking_en.json` line 228 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/1455#-N8ZRuVO8pwsbC0FNnsC:-N8ZW52J7saPYrQd3JVu:bsc5eh0) ([raw file](https://github.com/sillsdev/web-xforge/blob/79e874cee6a6f2aed221a1a1198336de56cecc9c/src/SIL.XForge.Scripture/ClientApp/src/assets/i18n/non_checking_en.json#L228)):*
<details><summary><i>Previously, RaymondLuong3 (Raymond Luong) wrote…</i></summary><blockquote>

How about changing the wording to be "Note: Translation suggestions are only available if a source text is selected."
</blockquote></details>

Good suggestion; I like it. Done.

**Review by RaymondLuong3 — APPROVED** [review]
That's right. Good checking.

> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1455#-:-N8ZZlHL-0On4lFHIa5Z:b-y5wtah)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @Nateowami)

**Comment by Nateowami** [comment]
The testers found this issue where the checkbox text overflows the page. This appears to be caused by material and not our own styling. It could be fixed using CSS, but it ends up looking weird to have the text wrapping by a checkbox, and I think the wording I gave it was kind of long for a checkbox anyway, so I reworded it:
Old | New
------|------
 | settings_overflow_a

Personally I think that's still clear enough, especially with the description that comes after it.

**Review by RaymondLuong3 — APPROVED** [review]
:lgtm: 

> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1455#-:-N8dSrPg0uKuwD1578Pz:bg7igkv)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @Nateowami)

**Pull request merged**
