### PR TITLE
SF-1730 ci: improve GHA frontend test output

### PR DESCRIPTION
**Pull request by marksvc**
- The test output from `npm run test:tc` in GHA shows a lot of
`##teamcity` messages that are not very easy to manually read.
- When running in GHA, use karma-mocha-reporter for easier to read
frontend unit test output.
- Introduce new `test:gha` frontend target, and modify some `:tc`
suffixes to `:ci` where they are not specific to TeamCity but used on
GHA.
- Retaining `:tc` suffixes to ease migration.

- - -
This change is [Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1595)

### CODE REVIEW

**Comment by marksvc** [comment]
This will fail the TeamCity build until corresponding changes are made in the TeamCity job configuration.

**Review by Nateowami — COMMENTED** [review]
> This will fail the TeamCity build until corresponding changes are made in the TeamCity job configuration.

Why? It looks like it's failing due to `13:20:45     npm ERR! Missing script: "test:tc"`, but it doesn't look like you removed that script.

> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1595#-:-NGNZD0ECCXCf5ejLRCY:b-a1j9xo)* status: 0 of 6 files reviewed, all discussions resolved

**Comment by marksvc** [comment]
I did change the name in RealtimeServer from test:tc to test:ci. I am putting some :tc targets back in to ease migration.

**Review by Nateowami — APPROVED** [review]
:lgtm: Thanks for your work on this. The output is going to be so much easier to read.

> Reviewed 3 of 6 files at r1, 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1595#-:-NH_cBWd-CV9USonpQi2:bgnwtdd)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @marksvc)

**Pull request merged**
