### PR TITLE
Update the test package reference to use the latest 2.1

### PR DESCRIPTION
**Pull request by jasonleenaylor**
This change is [Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/405)

### CODE REVIEW

**Comment by Nateowami** [comment]
Looks like the BOM was removed, which isn't shown in Reviewable. Not sure the reason for that.

Also, I'm not sure how to understand this: `(2.1.1,2.2)`. How do I test this? Is there some equivalent of `npm install` for .NET?

**Comment by jasonleenaylor** [comment]
@Nateowami 
https://docs.microsoft.com/en-us/nuget/consume-packages/package-references-in-project-files

**Comment by jasonleenaylor** [comment]
Note: In my further work I've changed this to remove a warning. I should update this PR accordingly.

**Comment by Nateowami** [comment]
I did some reading and now I think I understand how to read the version range. It looks as if you modified the PR to *include* the affected version in the version range. If that was necessary it would seem to indicate that we'd still be on the old version, which would defeat the purpose of the PR. Perhaps I'm missing something.

Also, looks like the removal of the BOM was reverted.

I'm not sure how to test this locally. Perhaps `dotnet run` updates dependencies? I don't know, and even if it does, I doubt it would do anything in this case, since the new version range includes the currently installed version.

I've added a space that got dropped since I think it would be re-added as soon as an automated process writes to the file.

Perhaps someone with prior experience with C# and .NET should review this.

**Pull request merged**
