### PR TITLE
SF-2205 Remove mdc-typography class from body element

### PR DESCRIPTION
**Pull request by Nateowami**
This change is [Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/2017)

### CODE REVIEW

**Review by Nateowami — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/2017)* status: 0 of 3 files reviewed, 1 unresolved discussion

___
*[`src/SIL.XForge.Scripture/ClientApp/src/styles.scss` line 41 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/2017#-NcV5D_09jGoZl8ObCC5:-NcV5D_09jGoZl8ObCC6:blbjsci) ([raw file](https://github.com/sillsdev/web-xforge/blob/1de91d5df9549a2b228bbbd2eeb4bf336c0eaa12/src/SIL.XForge.Scripture/ClientApp/src/styles.scss#L41)):*
> ```SCSS
> body {
>   margin: 0;
>   font-family: Roboto, sans-serif;
> ```

As far as I could tell, this font family rule is the only thing that was being specified due to the `mdc-typography` class on the body element.

**Review by nigel-wells — CHANGES_REQUESTED** [review]
> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/2017)* status: all files reviewed, 1 unresolved discussion (waiting on @Nateowami)

___
*[`src/SIL.XForge.Scripture/ClientApp/src/styles.scss` line 40 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/2017#-NcVBpDk6oDQkEAIcBCf:-NcVBpDk6oDQkEAIcBCg:b-liwoi9) ([raw file](https://github.com/sillsdev/web-xforge/blob/1de91d5df9549a2b228bbbd2eeb4bf336c0eaa12/src/SIL.XForge.Scripture/ClientApp/src/styles.scss#L40)):*
> ```SCSS
> 
> body {
>   margin: 0;
> ```

`margin: 0` appears to already be getting set by Storybook so this can be removed

**Review by Nateowami — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/2017)* status: all files reviewed, 1 unresolved discussion (waiting on @nigel-wells)

___
*[`src/SIL.XForge.Scripture/ClientApp/src/styles.scss` line 40 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/2017#-NcVBpDk6oDQkEAIcBCf:-NcVLUPC9jmpBGmhYePg:b-mb0ekb) ([raw file](https://github.com/sillsdev/web-xforge/blob/1de91d5df9549a2b228bbbd2eeb4bf336c0eaa12/src/SIL.XForge.Scripture/ClientApp/src/styles.scss#L40)):*
<details><summary><i>Previously, nigel-wells (Nigel Wells) wrote…</i></summary><blockquote>

`margin: 0` appears to already be getting set by Storybook so this can be removed
</blockquote></details>

We're not setting it for the sake of Storybook. We're setting it for the sake of the app itself. Remove this and we get a 8px margin around the entire app.

**Review by nigel-wells — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/2017#-:-NcVMklO6udLUVlH9vpW:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @Nateowami)

___
*[`src/SIL.XForge.Scripture/ClientApp/src/styles.scss` line 40 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/2017#-NcVBpDk6oDQkEAIcBCf:-NcVMgvoD5yvCDyUHxgt:bnpbsht) ([raw file](https://github.com/sillsdev/web-xforge/blob/1de91d5df9549a2b228bbbd2eeb4bf336c0eaa12/src/SIL.XForge.Scripture/ClientApp/src/styles.scss#L40)):*
<details><summary><i>Previously, Nateowami (Nathaniel Paulus) wrote…</i></summary><blockquote>

We're not setting it for the sake of Storybook. We're setting it for the sake of the app itself. Remove this and we get a 8px margin around the entire app.
</blockquote></details>

Ah, pretty good reason to leave it in then :)

**Pull request merged**
