### PR TITLE
Add script to update supported font list

### PR DESCRIPTION
**Pull request by Nateowami**
I wrote this script a couple months ago when I first added support for SIL fonts, but it was low quality and just enough to work. I've cleaned it up and changed the font service to import the data from a JSON file.

The intended workflow is that this script can be run, and if any changes result, those changes can be committed to update the repo.

- - -
This change is [Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/2505)

### CODE REVIEW

**Review by pmachapman — CHANGES_REQUESTED** [review]
I like how this is more maintainable for font updates.

Just one addition:

Can you please add a line `COPY ../SIL.XForge.Scripture/fonts.json /src/SIL.XForge.Scripture/fonts.json` into the section **# Build the Angular Frontend** in the Dockerfile?

This will make sure that the file is copied to the Docker image.

> Reviewed 5 of 5 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/2505#-:-Nze2vArEaeggkl49_2N:b-6fesl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @Nateowami)

**Review by Nateowami — COMMENTED** [review]
Done.

> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/2505#-:-NzeCfcMBPMt-M0G-S63:b-896fix)* status: 5 of 6 files reviewed, all discussions resolved (waiting on @pmachapman)

**Comment by Nateowami** [comment]
Maybe I should have made it a sibling file of the font service (which I considered), just so it wouldn't need to be separately copied. Opinion?

**Review by pmachapman — APPROVED** [review]
> Maybe I should have made it a sibling file of the font service (which I considered), just so it wouldn't need to be separately copied. Opinion?

I think it is great where it is as it is really a configuration file, and if we need it in C# land, it is there.

:lgtm: 

> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/2505#-:-NzeLaV11k96sylLZI7r:bkbtffb)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @Nateowami)

**Pull request merged**
