### PR TITLE
SF-2179 Refreshing scripture audio when timing data changes

### PR DESCRIPTION
**Pull request by josephmyers**
This change is [Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1998)

### CODE REVIEW

**Review by nigel-wells — CHANGES_REQUESTED** [review]
This appears to work well. I did have an issue where, after the changes were detected and I clicked the chapter play button, the audio wasn't available? This may be related to other bugs were in the process of fixing though.

> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1998#-:-NbSLjhqCwr7RhFk5nnB:br6iuuf)* status: all files reviewed, 1 unresolved discussion (waiting on @josephmyers)

___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-answers/checking-question/checking-question.component.ts` line 117 at r2](https://reviewable.io/reviews/sillsdev/web-xforge/1998#-NbSLP4y9Cwgc-x9_Xo2:-NbSLP4y9Cwgc-x9_Xo3:b34xk59) ([raw file](https://github.com/sillsdev/web-xforge/blob/7bd4b108a7594aecbe8531ad2694d98666d6d28e/src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-answers/checking-question/checking-question.component.ts#L117)):*
> ```XML
>       );
> 
>       this.projectService.queryAudioText(projectId).then(audioQuery => {
> ```

Probably only need to do this if the projectId actually changes. If it does change then we should unsubscribe from the previous remote changes as well.

**Review by josephmyers — COMMENTED** [review]
Yeah, I haven't seen that. If you see it again, definitely create a bug for it. Or I don't mind holding this one up for it, too

> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1998#-:-NbSUr4m91NmS19rPgI7:b-bdd650)* status: 1 of 2 files reviewed, 1 unresolved discussion (waiting on @nigel-wells)

___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-answers/checking-question/checking-question.component.ts` line 117 at r2](https://reviewable.io/reviews/sillsdev/web-xforge/1998#-NbSLP4y9Cwgc-x9_Xo2:-NbSYbfVAWRuM5fe2Y1D:b-s82pfp) ([raw file](https://github.com/sillsdev/web-xforge/blob/7bd4b108a7594aecbe8531ad2694d98666d6d28e/src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-answers/checking-question/checking-question.component.ts#L117)):*
<details><summary><i>Previously, nigel-wells (Nigel Wells) wrote…</i></summary><blockquote>

Probably only need to do this if the projectId actually changes. If it does change then we should unsubscribe from the previous remote changes as well.
</blockquote></details>

I added the unsubscribe, but I was seeing the projectId diff check cause bugs when switching between questions of different chapters but same book. Maybe I'm misunderstanding

**Review by nigel-wells — CHANGES_REQUESTED** [review]
Once we get the other PRs merged in we can comb over everything and come up with a final list of things we want to fix/improve. 

> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1998#-:-NbSZxqr8gAxdtuloXd_:b4kh98h)* status: all files reviewed, 1 unresolved discussion (waiting on @josephmyers)

___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-answers/checking-question/checking-question.component.ts` line 117 at r2](https://reviewable.io/reviews/sillsdev/web-xforge/1998#-NbSLP4y9Cwgc-x9_Xo2:-NbS_QSk5CmNlPb_Xj42:b-yi31ls) ([raw file](https://github.com/sillsdev/web-xforge/blob/7bd4b108a7594aecbe8531ad2694d98666d6d28e/src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-answers/checking-question/checking-question.component.ts#L117)):*
<details><summary><i>Previously, josephmyers wrote…</i></summary><blockquote>

I added the unsubscribe, but I was seeing the projectId diff check cause bugs when switching between questions of different chapters but same book. Maybe I'm misunderstanding
</blockquote></details>

What sort of bugs? I guess `updateScriptureAudio()` may need to be run again if the question changes. Otherwise it seems like we're unsubscribing and then re-subscribing to exactly the same thing.

**Review by josephmyers — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1998)* status: all files reviewed, 1 unresolved discussion (waiting on @nigel-wells)

___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-answers/checking-question/checking-question.component.ts` line 117 at r2](https://reviewable.io/reviews/sillsdev/web-xforge/1998#-NbSLP4y9Cwgc-x9_Xo2:-NbS_riIBUiHJSLNUZAs:b-b75yke) ([raw file](https://github.com/sillsdev/web-xforge/blob/7bd4b108a7594aecbe8531ad2694d98666d6d28e/src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-answers/checking-question/checking-question.component.ts#L117)):*
<details><summary><i>Previously, nigel-wells (Nigel Wells) wrote…</i></summary><blockquote>

What sort of bugs? I guess `updateScriptureAudio()` may need to be run again if the question changes. Otherwise it seems like we're unsubscribing and then re-subscribing to exactly the same thing.
</blockquote></details>

It just wasn't working. I was swapping between Mark 3 and 4, one with audio and one without, and the player wasn't refreshing. It was showing the play button until you refreshed the page.

The only way we're subbing and unsubbing from the same thing is if projectService is returning the same query object every time. But this class doesn't know that.

**Comment by josephmyers** [comment]
@nigel-wells Feel free to make the changes you want. I may be misunderstanding what you're getting at, and I don't want to waste your time going back and forth.

**Review by nigel-wells — COMMENTED** [review]
I've created a new branch `bug/SF-2179-refresh-audio-player-b` with what I was thinking. It seems to work ok - it has broken a test though. Feel free to use, build upon, or discard if you feel I've missed something.

> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1998#-:-NbSo1SkAkkeQoVAUfBE:b-30vc0b)* status: all files reviewed, 1 unresolved discussion (waiting on @josephmyers)

**Review by nigel-wells — APPROVED** [review]
> Reviewed 1 of 1 files at r4, 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1998)* status: all files reviewed, 1 unresolved discussion (waiting on @josephmyers)

___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-answers/checking-question/checking-question.component.spec.ts` line 142 at r5](https://reviewable.io/reviews/sillsdev/web-xforge/1998#-NbpxA1ABB5yvzZGoJFV:-NbpxA1ABB5yvzZGoJFW:bvvll3t) ([raw file](https://github.com/sillsdev/web-xforge/blob/1e65b81ae48b2534272ab7c634bcd9896a83b006/src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-answers/checking-question/checking-question.component.spec.ts#L142)):*
> ```XML
>     const env = new TestEnvironment();
>     await env.wait();
>     await env.wait();
> ```

Non blocking but it would be great to have a comment as to why this needs to be run twice as it looks odd :)

**Review by josephmyers — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1998)* status: all files reviewed, 1 unresolved discussion (waiting on @nigel-wells)

___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-answers/checking-question/checking-question.component.spec.ts` line 142 at r5](https://reviewable.io/reviews/sillsdev/web-xforge/1998#-NbpxA1ABB5yvzZGoJFV:-NbqxPoDBoURNeaQrdq0:bturvfl) ([raw file](https://github.com/sillsdev/web-xforge/blob/1e65b81ae48b2534272ab7c634bcd9896a83b006/src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-answers/checking-question/checking-question.component.spec.ts#L142)):*
<details><summary><i>Previously, nigel-wells (Nigel Wells) wrote…</i></summary><blockquote>

Non blocking but it would be great to have a comment as to why this needs to be run twice as it looks odd :)
</blockquote></details>

I'm actually not sure why it's required. A single, longer wait didn't work, and I tried lots of other things, too. I'm gonna go ahead and merge in as is. If we want to come back and refactor it later, we can absolutely do that.

**Pull request merged**
