### PR TITLE
SF-2991 Display informative error message when sync fails due to permissions issue

### PR DESCRIPTION
**Pull request by kylebuss**
In the event a sync fails due to a user who no longer has permission to sync a project we want to inform the user to contact the project administrator. This change passes an error code that can be read by the front-end when the notification of the sync completes. It will display a different sync error message and dialog message than the default.

- - -
This change is [Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/2794)

### CODE REVIEW

**Review by RaymondLuong3 — CHANGES_REQUESTED** [review]
Thanks for the improvement. I have some suggestions. I think the approach is right.

> Reviewed 10 of 10 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/2794#-:-O8sExweBZiQurMJWRFu:b-lsm4vq)* status: all files reviewed, 8 unresolved discussions (waiting on @kylebuss)

___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/sync/sync.component.ts` line 99 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/2794#-O8sATdp4tkAIr4S5YPt:-O8sATdp4tkAIr4S5YPu:b552kqp) ([raw file](https://github.com/sillsdev/web-xforge/blob/61884b63ec2d38743becaa57f9e9a741cb3bf680/src/SIL.XForge.Scripture/ClientApp/src/app/sync/sync.component.ts#L99)):*
> ```XML
>           this.previousLastSyncDate = this.lastSyncDate;
>         } else {
>           if (this.projectDoc.data.sync.lastSyncErrorCode === USER_PERMISSIONS_SYNC_ERROR_CODE) {
> ```

This can be an else if



_Code quote:_
```XML
        } else {
          if (this.projectDoc.data.sync.lastSyncErrorCode === USER_PERMISSIONS_SYNC_ERROR_CODE) {
```
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/sync/sync.component.ts` line 128 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/2794#-O8sBqRy6QVLePv-a-e7:-O8sBqRy6QVLePv-a-e8:bo4fq6t) ([raw file](https://github.com/sillsdev/web-xforge/blob/61884b63ec2d38743becaa57f9e9a741cb3bf680/src/SIL.XForge.Scripture/ClientApp/src/app/sync/sync.component.ts#L128)):*
> ```XML
>     const projectName: string = this.projectDoc?.data?.name ?? '';
>     if (this.projectDoc?.data?.sync.lastSyncErrorCode === USER_PERMISSIONS_SYNC_ERROR_CODE)
>       return this.i18n.translateAndInsertTags('sync.sync_user_permissions_failure_message', { projectName });
> ```

Let's revert this change. It is not that helpful since we already have the dialog accomplishing the purpose of notifying the user about the permission related issue.



_Code quote:_
```XML
    if (this.projectDoc?.data?.sync.lastSyncErrorCode === USER_PERMISSIONS_SYNC_ERROR_CODE)
      return this.i18n.translateAndInsertTags('sync.sync_user_permissions_failure_message', { projectName });
```
___
*[`src/SIL.XForge.Scripture/ClientApp/src/assets/i18n/non_checking_en.json` line 538 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/2794#-O8sC95-2tU703ZXNJg7:-O8sC95-2tU703ZXNJg8:b-d8jlny) ([raw file](https://github.com/sillsdev/web-xforge/blob/61884b63ec2d38743becaa57f9e9a741cb3bf680/src/SIL.XForge.Scripture/ClientApp/src/assets/i18n/non_checking_en.json#L538)):*
> ```JSON
>     "sync_is_disabled": "Synchronization for this project needed to be disabled, so it is not available at this time. Please contact {{ email }} to discuss what needs to be done so project synchronization can be enabled again.",
>     "sync_failure_support_message": "Something went wrong the last time Scripture Forge attempted to synchronize the project with Paratext. If it still doesn't work after you try again, please report the problem by writing to {{email}}.",
>     "sync_user_permissions_failure_message": "Something went wrong the last time Scripture Forge attempted to synchronize the project with Paratext. The last user to synchronize this project no longer has the permission to do so. Please contact the {{ projectName }} project administrator to learn more or restore synchronize permission.",
> ```

Let's remove this.



_Code quote:_
```JSON
sync_user_permissions_failure_message": "
```
___
*[`src/SIL.XForge.Scripture/Services/ParatextService.cs` line 708 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/2794#-O8sC_aV3IyjfyEs5-4g:-O8sC_aV3IyjfyEs5-4h:b-uiozt8) ([raw file](https://github.com/sillsdev/web-xforge/blob/61884b63ec2d38743becaa57f9e9a741cb3bf680/src/SIL.XForge.Scripture/Services/ParatextService.cs#L708)):*
> ```Smalltalk
> 
>             IEnumerable<SharedRepository> remotePtProjects = GetRepositories(ptRepoSource, contextInformation);
>             SharedRepository remotePtProject = null;
> ```

Any reason not to assign `remotePtProject` here instead of below?



_Code quote:_
```Smalltalk
 SharedRepository remotePtProject = null;
```
___
*[`src/SIL.XForge.Scripture/Services/ParatextService.cs` line 712 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/2794#-O8sCj0r4S6Gy8m_57Cl:-O8sCj0r4S6Gy8m_57Cm:b-v4iho) ([raw file](https://github.com/sillsdev/web-xforge/blob/61884b63ec2d38743becaa57f9e9a741cb3bf680/src/SIL.XForge.Scripture/Services/ParatextService.cs#L712)):*
> ```Smalltalk
>             remotePtProject = remotePtProjects.SingleOrDefault(p => p.SendReceiveId.Id == project.ParatextId);
> 
>             // if user id was not found then they have been removed from the project throwing ForbiddenException to notify user why the sync failed
> ```

Let's update this comment to be "if the paratext id could not be found then the user does not have access. Throw the ForbiddenException and fail the sync.
___
*[`test/SIL.XForge.Scripture.Tests/Services/ParatextSyncRunnerTests.cs` line 86 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/2794#-O8sDlId7NHO1ysjU5Uu:-O8sDlId7NHO1ysjU5Uv:bu7aexb) ([raw file](https://github.com/sillsdev/web-xforge/blob/61884b63ec2d38743becaa57f9e9a741cb3bf680/test/SIL.XForge.Scripture.Tests/Services/ParatextSyncRunnerTests.cs#L86)):*
> ```Smalltalk
>         env.SetupSFData(true, true, false, false);
>         env.SetupPTData(new Book("MAT", 2), new Book("MRK", 2));
>         env.DeltaUsxMapper.When(d => d.ToChapterDeltas(Arg.Any<XDocument>())).Do(x => throw new Exception());
> ```

Are you throwing an error from the DeltaUsxMapper for any particular reason? Seems to be unrelated.



_Code quote:_
```Smalltalk
        env.DeltaUsxMapper.When(d => d.ToChapterDeltas(Arg.Any<XDocument>())).Do(x => throw new Exception());
```
___
*[`test/SIL.XForge.Scripture.Tests/Services/ParatextSyncRunnerTests.cs` line 3799 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/2794#-O8sEGWbANLi-DALoNyv:-O8sEGWbANLi-DALoNyw:b74ap2e) ([raw file](https://github.com/sillsdev/web-xforge/blob/61884b63ec2d38743becaa57f9e9a741cb3bf680/test/SIL.XForge.Scripture.Tests/Services/ParatextSyncRunnerTests.cs#L3799)):*
> ```Smalltalk
>                 new SFProject
>                 {
>                     // this project is to test that the sync error code is written to the project when a user with previous sync permissions was removed from the project and no longer has sync permissions
> ```

Nit: Keep comments within the 120 character line limit. This should be broken into two lines



_Code quote:_
```Smalltalk
                    // this project is to test that the sync error code is written to the project when a user with previous sync permissions was removed from the project and no longer has sync permissions
```
___
*[`test/SIL.XForge.Scripture.Tests/Services/ParatextSyncRunnerTests.cs` line 3801 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/2794#-O8sE_HgDEYTXy3_GiDX:-O8sE_Hh178UaglJK0vq:b9ix7lp) ([raw file](https://github.com/sillsdev/web-xforge/blob/61884b63ec2d38743becaa57f9e9a741cb3bf680/test/SIL.XForge.Scripture.Tests/Services/ParatextSyncRunnerTests.cs#L3801)):*
> ```Smalltalk
>                     // this project is to test that the sync error code is written to the project when a user with previous sync permissions was removed from the project and no longer has sync permissions
>                     Id = "project06",
>                     Name = "project06",
> ```

I don't think you need to create a project06 since it is not a project related issue but a permission related issue on the remote PT repository.



_Code quote:_
```Smalltalk
                    Id = "project06",
                    Name = "project06",
```

**Review by kylebuss — COMMENTED** [review]
Thanks Raymond! Right after I pushed I thought: Hmm, I probably didn't need to create a new project for this one test.

> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/2794#-:-O8vbk7R4Zc3t5EH5Dy3:b-qdsmpx)* status: 6 of 10 files reviewed, 6 unresolved discussions (waiting on @RaymondLuong3)

___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/sync/sync.component.ts` line 99 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/2794#-O8sATdp4tkAIr4S5YPt:-O8vSaEwDsn53KTCmbSl:b-896fix) ([raw file](https://github.com/sillsdev/web-xforge/blob/61884b63ec2d38743becaa57f9e9a741cb3bf680/src/SIL.XForge.Scripture/ClientApp/src/app/sync/sync.component.ts#L99)):*
<details><summary><i>Previously, RaymondLuong3 (Raymond Luong) wrote…</i></summary><blockquote>

This can be an else if
</blockquote></details>

Done.
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/sync/sync.component.ts` line 128 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/2794#-O8sBqRy6QVLePv-a-e7:-O8vQzzIEOxvo4USuofB:b-jhz39e) ([raw file](https://github.com/sillsdev/web-xforge/blob/61884b63ec2d38743becaa57f9e9a741cb3bf680/src/SIL.XForge.Scripture/ClientApp/src/app/sync/sync.component.ts#L128)):*
<details><summary><i>Previously, RaymondLuong3 (Raymond Luong) wrote…</i></summary><blockquote>

Let's revert this change. It is not that helpful since we already have the dialog accomplishing the purpose of notifying the user about the permission related issue.
</blockquote></details>

This was something Peter brought up. The dialog only notifies the user if they are on the sync page when the sync completes. If they log out or navigate away after starting the sync they won't see the detailed error message.
___
*[`src/SIL.XForge.Scripture/ClientApp/src/assets/i18n/non_checking_en.json` line 538 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/2794#-O8sC95-2tU703ZXNJg7:-O8vReGq4FqIhPlZ4CKe:b-t2hpmm) ([raw file](https://github.com/sillsdev/web-xforge/blob/61884b63ec2d38743becaa57f9e9a741cb3bf680/src/SIL.XForge.Scripture/ClientApp/src/assets/i18n/non_checking_en.json#L538)):*
<details><summary><i>Previously, RaymondLuong3 (Raymond Luong) wrote…</i></summary><blockquote>

Let's remove this.
</blockquote></details>

See above note about dialog displaying.
___
*[`src/SIL.XForge.Scripture/Services/ParatextService.cs` line 712 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/2794#-O8sCj0r4S6Gy8m_57Cl:-O8vT_9D6Zf_cvLUmOXt:b-896fix) ([raw file](https://github.com/sillsdev/web-xforge/blob/61884b63ec2d38743becaa57f9e9a741cb3bf680/src/SIL.XForge.Scripture/Services/ParatextService.cs#L712)):*
<details><summary><i>Previously, RaymondLuong3 (Raymond Luong) wrote…</i></summary><blockquote>

Let's update this comment to be "if the paratext id could not be found then the user does not have access. Throw the ForbiddenException and fail the sync.
</blockquote></details>

Done.
___
*[`test/SIL.XForge.Scripture.Tests/Services/ParatextSyncRunnerTests.cs` line 86 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/2794#-O8sDlId7NHO1ysjU5Uu:-O8vU7c86GuXtvJAzCnU:b-896fix) ([raw file](https://github.com/sillsdev/web-xforge/blob/61884b63ec2d38743becaa57f9e9a741cb3bf680/test/SIL.XForge.Scripture.Tests/Services/ParatextSyncRunnerTests.cs#L86)):*
<details><summary><i>Previously, RaymondLuong3 (Raymond Luong) wrote…</i></summary><blockquote>

Are you throwing an error from the DeltaUsxMapper for any particular reason? Seems to be unrelated.
</blockquote></details>

Done.
___
*[`test/SIL.XForge.Scripture.Tests/Services/ParatextSyncRunnerTests.cs` line 3801 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/2794#-O8sE_HgDEYTXy3_GiDX:-O8vUAok71HXXr53IFyD:b-896fix) ([raw file](https://github.com/sillsdev/web-xforge/blob/61884b63ec2d38743becaa57f9e9a741cb3bf680/test/SIL.XForge.Scripture.Tests/Services/ParatextSyncRunnerTests.cs#L3801)):*
<details><summary><i>Previously, RaymondLuong3 (Raymond Luong) wrote…</i></summary><blockquote>

I don't think you need to create a project06 since it is not a project related issue but a permission related issue on the remote PT repository.
</blockquote></details>

Done.

**Review by RaymondLuong3 — CHANGES_REQUESTED** [review]
Nice! I suggested one more improvement and then it will be good to go.

> Reviewed 4 of 4 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/2794#-:-O8wImQjEwdGVLLUig6h:b-72lp2k)* status: all files reviewed, 2 unresolved discussions (waiting on @kylebuss)

___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/sync/sync.component.ts` line 128 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/2794#-O8sBqRy6QVLePv-a-e7:-O8wH_muCx3KKd_aanAV:bzdmpjs) ([raw file](https://github.com/sillsdev/web-xforge/blob/61884b63ec2d38743becaa57f9e9a741cb3bf680/src/SIL.XForge.Scripture/ClientApp/src/app/sync/sync.component.ts#L128)):*
<details><summary><i>Previously, kylebuss (Kyle Buss) wrote…</i></summary><blockquote>

This was something Peter brought up. The dialog only notifies the user if they are on the sync page when the sync completes. If they log out or navigate away after starting the sync they won't see the detailed error message.
</blockquote></details>

Hmm, that is a good point. So something to consider is that we can expect that users will not read a long message. We can improve this.
___
*[`src/SIL.XForge.Scripture/ClientApp/src/assets/i18n/non_checking_en.json` line 538 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/2794#-O8sC95-2tU703ZXNJg7:-O8wHw4cAsFaaaITXtFZ:byd7k74) ([raw file](https://github.com/sillsdev/web-xforge/blob/61884b63ec2d38743becaa57f9e9a741cb3bf680/src/SIL.XForge.Scripture/ClientApp/src/assets/i18n/non_checking_en.json#L538)):*
<details><summary><i>Previously, kylebuss (Kyle Buss) wrote…</i></summary><blockquote>

See above note about dialog displaying.
</blockquote></details>

Let's clean this up. Can we instead keep the previous message, but add a notice to the page with a very clear message? "The last user who attempted to sync the project had their permissions removed recently." That way, the notice will stand out.

**Review by kylebuss — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/2794)* status: 7 of 11 files reviewed, 2 unresolved discussions (waiting on @RaymondLuong3)

___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/sync/sync.component.ts` line 128 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/2794#-O8sBqRy6QVLePv-a-e7:-O9AKjOEED1CZXkLOrzr:b-896fix) ([raw file](https://github.com/sillsdev/web-xforge/blob/61884b63ec2d38743becaa57f9e9a741cb3bf680/src/SIL.XForge.Scripture/ClientApp/src/app/sync/sync.component.ts#L128)):*
<details><summary><i>Previously, RaymondLuong3 (Raymond Luong) wrote…</i></summary><blockquote>

Hmm, that is a good point. So something to consider is that we can expect that users will not read a long message. We can improve this.
</blockquote></details>

Done.
___
*[`src/SIL.XForge.Scripture/ClientApp/src/assets/i18n/non_checking_en.json` line 538 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/2794#-O8sC95-2tU703ZXNJg7:-O9AKiaVC2PdxbKq8rL5:b-896fix) ([raw file](https://github.com/sillsdev/web-xforge/blob/61884b63ec2d38743becaa57f9e9a741cb3bf680/src/SIL.XForge.Scripture/ClientApp/src/assets/i18n/non_checking_en.json#L538)):*
<details><summary><i>Previously, RaymondLuong3 (Raymond Luong) wrote…</i></summary><blockquote>

Let's clean this up. Can we instead keep the previous message, but add a notice to the page with a very clear message? "The last user who attempted to sync the project had their permissions removed recently." That way, the notice will stand out.
</blockquote></details>

Done.

**Review by RaymondLuong3 — APPROVED** [review]
> Reviewed 4 of 4 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/2794)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @kylebuss)

**Pull request merged**
