### PR TITLE
SF-2459 Add additional non-Biblical source/target files for Serval training

### PR DESCRIPTION
**Pull request by pmachapman**
This PR adds support for uploading extra-biblical material in CSV format for Serval pre-translation training.

Sample files are included in the JIRA ticket.

- - -
This change is [Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/2308)

### CODE REVIEW

**Review by pmachapman — COMMENTED** [review]
> Dismissed @github-advanced-security[bot] from a discussion.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/2308)* status: 0 of 70 files reviewed, all discussions resolved (waiting on @github-advanced-security[bot])

___
*[`src/SIL.XForge.Scripture/Services/MachineProjectService.cs` line 1108 at r8](https://reviewable.io/reviews/sillsdev/web-xforge/2308#gh-1477547872:-Npr3q02CCe0Li40bTGF:b-896fix) ([raw file](https://github.com/sillsdev/web-xforge/blob/9ec25e7052a3b39ee4b0d178167bd6546b07ed10/src/SIL.XForge.Scripture/Services/MachineProjectService.cs#L1108)):*
<details><summary><i>Previously, github-advanced-security[bot] wrote…</i></summary><blockquote>

## Nested 'if' statements can be combined

These 'if' statements can be combined.

[Show more details](https://github.com/sillsdev/web-xforge/security/code-scanning/716)
</blockquote></details>

Done.

**Review by RaymondLuong3 — CHANGES_REQUESTED** [review]
This is neat! It is too bad you had to implement a new upload dialog. Seems like we should have a generic upload dialog that we could adapt for different uses.
I still more files to get through and plan to do that tomorrow.

> Reviewed 4 of 24 files at r1, 21 of 45 files at r2, 13 of 24 files at r7, 3 of 7 files at r8, 4 of 6 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/2308#-:-Nqd7SWcExppF-N-bmF_:bm5yjtl)* status: 45 of 70 files reviewed, 11 unresolved discussions (waiting on @pmachapman)

___
*[`src/SIL.XForge.Scripture/SIL.XForge.Scripture.csproj` line 37 at r9](https://reviewable.io/reviews/sillsdev/web-xforge/2308#-NqdAxB-7XNujiyABUVq:-NqdAxB-7XNujiyABUVr:b-pclnzh) ([raw file](https://github.com/sillsdev/web-xforge/blob/f14f922c241fd52750fb86af3983176c69ba5d46/src/SIL.XForge.Scripture/SIL.XForge.Scripture.csproj#L37)):*
> ```XML
>     <PackageReference Include="Microsoft.FeatureManagement.AspNetCore" Version="3.1.1" />
>     <PackageReference Include="Microsoft.VisualStudio.Azure.Containers.Tools.Targets" Version="1.19.6" />
>     <PackageReference Include="NPOI" Version="2.6.2" />
> ```

What is this package for?
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-generation-steps/draft-generation-steps.component.ts` line 205 at r9](https://reviewable.io/reviews/sillsdev/web-xforge/2308#-NqdF11Q27i9coJhJymI:-NqdF11Q27i9coJhJymJ:b3rm26l) ([raw file](https://github.com/sillsdev/web-xforge/blob/f14f922c241fd52750fb86af3983176c69ba5d46/src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-generation-steps/draft-generation-steps.component.ts#L205)):*
> ```XML
>     this.userSelectedTrainingDataIds = selectedTrainingDataIds;
>     // If any of the passed data ids are not in the initial selected list, update the initial selected list
>     if (!selectedTrainingDataIds.every(dataId => this.initialSelectedTrainingDataIds.includes(dataId))) {
> ```

What if the `selectedTrainingDataIds` is a collection that has one less item then what was set in `this.initialSelectedTrainingDataIds`, wouldn't we still want to update `this.initialSelectedTrainingDataIds`? Or may I am not understanding this correctly



_Code quote:_
```XML
    if (!selectedTrainingDataIds.every(dataId => this.initialSelectedTrainingDataIds.includes(dataId))) {
```
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/training-data/training-data-multi-select.component.html` line 19 at r9](https://reviewable.io/reviews/sillsdev/web-xforge/2308#-NqdHDGa0_9pVNkyW9g1:-NqdHDGa0_9pVNkyW9g2:b-4u82qt) ([raw file](https://github.com/sillsdev/web-xforge/blob/f14f922c241fd52750fb86af3983176c69ba5d46/src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/training-data/training-data-multi-select.component.html#L19)):*
> ```HTML
>     <button mat-flat-button (click)="openUploadDialog()" color="accent">
>       <mat-icon matChipAvatar>file_upload</mat-icon>
>       {{ t("upload_csv") }}
> ```

This will probably be OK for now, but I suspect in the future, we will need to add documentation for what files will be accepted. I wonder if we should add a new task to created a mat-tool-tip to explain what format the csv file should look like.
Also, I assume that CSV is understood across languages. Does this translate well?



_Code quote:_
```HTML
      {{ t("upload_csv") }}
```
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/training-data/training-data-multi-select.component.ts` line 51 at r9](https://reviewable.io/reviews/sillsdev/web-xforge/2308#-NqdIIhSASRxRj-c0luh:-NqdIIhSASRxRj-c0lui:b-vggy6i) ([raw file](https://github.com/sillsdev/web-xforge/blob/f14f922c241fd52750fb86af3983176c69ba5d46/src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/training-data/training-data-multi-select.component.ts#L51)):*
> ```XML
>   async canDeleteTrainingData(trainingData: TrainingData): Promise<boolean> {
>     const userId = this.userService.currentUserId;
>     const project = this.activatedProjectService.projectDoc?.data;
> ```

Nit: Add types here and below.



_Code quote:_
```XML
    const userId = this.userService.currentUserId;
    const project = this.activatedProjectService.projectDoc?.data;
```
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/training-data/training-data-upload-dialog.component.html` line 12 at r9](https://reviewable.io/reviews/sillsdev/web-xforge/2308#-NqdNcXP8MJdlvIY0Xqq:-NqdNcXP8MJdlvIY0Xqr:b-6bdt9q) ([raw file](https://github.com/sillsdev/web-xforge/blob/f14f922c241fd52750fb86af3983176c69ba5d46/src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/training-data/training-data-upload-dialog.component.html#L12)):*
> ```HTML
>       <div class="wrapper valid">
>         <ng-container>
>           <mat-checkbox #skipFirstRow>{{ t("skip_first_row") }}</mat-checkbox>
> ```

Ideally, we could detect this automatically without the user needing to specify if the first row needs to be skipped. Is there a reason we cannot detect this and handle that scenario? Oh, I see. The data is expected to be strings, so it is not easy to differentiate headings vs training data value pairs.
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/training-data/training-data-upload-dialog.component.scss` line 120 at r9](https://reviewable.io/reviews/sillsdev/web-xforge/2308#-NqdQ6sC5ZlyGHaOZvRf:-NqdQ6sC5ZlyGHaOZvRg:b-f9ii52) ([raw file](https://github.com/sillsdev/web-xforge/blob/f14f922c241fd52750fb86af3983176c69ba5d46/src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/training-data/training-data-upload-dialog.component.scss#L120)):*
> ```SCSS
>     }
> 
>     .divider {
> ```

I don't see anything with this divider class.



_Code quote:_
```SCSS
   .divider {
```
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/training-data/training-data-upload-dialog.component.scss` line 127 at r9](https://reviewable.io/reviews/sillsdev/web-xforge/2308#-NqdQVrh9LEVCEgxmAkk:-NqdQVrh9LEVCEgxmAkl:b-348gh5) ([raw file](https://github.com/sillsdev/web-xforge/blob/f14f922c241fd52750fb86af3983176c69ba5d46/src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/training-data/training-data-upload-dialog.component.scss#L127)):*
> ```SCSS
> 
>     &.valid {
>       @include wrapperState(variables.$purpleLight, variables.$greyDark);
> ```

I wasn't able to get the dialog in an error state. Is this still applicable?



_Code quote:_
```SCSS
    &.valid {
      @include wrapperState(variables.$purpleLight, variables.$greyDark);
```
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/training-data/training-data-upload-dialog.component.ts` line 130 at r9](https://reviewable.io/reviews/sillsdev/web-xforge/2308#-NqdR8aH79VAXcez9gGS:-NqdR8aI2ynE-wc-SGrg:b4436zj) ([raw file](https://github.com/sillsdev/web-xforge/blob/f14f922c241fd52750fb86af3983176c69ba5d46/src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/training-data/training-data-upload-dialog.component.ts#L130)):*
> ```XML
>     this._isUploading = true;
>     const dataId: string = objectId();
>     const fileUrl: string | undefined = await this.fileService.uploadFile(
> ```

You can now use the new method `onlineUploadFileOrFail` which has just been merged.



_Code quote:_
```XML
 const fileUrl: string | undefined = await this.fileService.uploadFile(
```
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/training-data/training-data-upload-dialog.component.ts` line 161 at r9](https://reviewable.io/reviews/sillsdev/web-xforge/2308#-NqdRyMWAPk11WzxoFCU:-NqdRyMWAPk11WzxoFCV:b-yj609o) ([raw file](https://github.com/sillsdev/web-xforge/blob/f14f922c241fd52750fb86af3983176c69ba5d46/src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/training-data/training-data-upload-dialog.component.ts#L161)):*
> ```XML
>   }
> 
>   uploadedFiles(e: Event): void {
> ```

I was only able to upload one file at a time. Let's leave a comment here explaining that we only allow uploading one file each time to avoid confusion.
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/training-data/training-data.service.ts` line 28 at r9](https://reviewable.io/reviews/sillsdev/web-xforge/2308#-NqdT9ikBBDoM2Q7LVrM:-NqdT9ikBBDoM2Q7LVrN:b-595zia) ([raw file](https://github.com/sillsdev/web-xforge/blob/f14f922c241fd52750fb86af3983176c69ba5d46/src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/training-data/training-data.service.ts#L28)):*
> ```XML
> 
>     // Delete the training data file and document
>     await trainingDataDoc.deleteFile(FileType.TrainingData, trainingData.dataId, trainingData.ownerRef);
> ```

You could implement `deleteFile` in the `TrainingDataDoc` class and have that supply the `fileType` and `dataId` params. Not a big deal though.



_Code quote:_
```XML
    await trainingDataDoc.deleteFile(FileType.TrainingData, trainingData.dataId, trainingData.ownerRef);
```
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/training-data/training-data.service.spec.ts` line 86 at r9](https://reviewable.io/reviews/sillsdev/web-xforge/2308#-NqdUBFoAmNdzIWEYDo2:-NqdUBFoAmNdzIWEYDo3:b-je9hb9) ([raw file](https://github.com/sillsdev/web-xforge/blob/f14f922c241fd52750fb86af3983176c69ba5d46/src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/training-data/training-data.service.spec.ts#L86)):*
> ```XML
>       title: '',
>       ownerRef: 'user01'
>     };
> ```

You should check the doc exists before deleting it to make this test more robust.

**Review by RaymondLuong3 — COMMENTED** [review]
> Reviewed 6 of 24 files at r1, 6 of 45 files at r2, 2 of 24 files at r7, 1 of 7 files at r8, 1 of 6 files at r9, 9 of 11 files at r10, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/2308)* status: 60 of 70 files reviewed, 13 unresolved discussions (waiting on @pmachapman)

___
*[`src/SIL.XForge.Scripture/Controllers/SFProjectsUploadController.cs` line 29 at r10](https://reviewable.io/reviews/sillsdev/web-xforge/2308#-NqiWbgp8M3UsGfTsgNV:-NqiWbgqBwHRnQ253OZB:bqrz7p5) ([raw file](https://github.com/sillsdev/web-xforge/blob/e8e4c87f808b4a39b1cbf7d4852e0a76660c41b7/src/SIL.XForge.Scripture/Controllers/SFProjectsUploadController.cs#L29)):*
> ```Smalltalk
>     private readonly IUserAccessor _userAccessor;
> 
>     public SFProjectsUploadController(
> ```

I never thought about ordering the services alphabetically. I like it.
___
*[`src/SIL.XForge.Scripture/Controllers/SFProjectsUploadController.cs` line 116 at r10](https://reviewable.io/reviews/sillsdev/web-xforge/2308#-NqiX5uL3Fzkfc_Nd-X9:-NqiX5uL3Fzkfc_Nd-XA:bf6r17g) ([raw file](https://github.com/sillsdev/web-xforge/blob/e8e4c87f808b4a39b1cbf7d4852e0a76660c41b7/src/SIL.XForge.Scripture/Controllers/SFProjectsUploadController.cs#L116)):*
> ```Smalltalk
>     /// </remarks>
>     [HttpPost("training-data")]
>     [RequestSizeLimit(300_000_000)]
> ```

Didn't we decide the the limit for file uploads is 100mb?

**Review by RaymondLuong3 — CHANGES_REQUESTED** [review]
Phew, what a change! It will be exciting to see what kind of training data translation teams will find to train Serval with. Is there already an idea of the type of translated data that is available? It would be unfortunate if they have data, but it is not in the form of a csv file. Perhaps they are parallel texts in two different files, then they would need to create a new csv with the two parallel texts.

Anyway, this is a really good step forward, but just wanted to bring up the discussion of what would be existing translated text a team must have access to.

> Reviewed 3 of 45 files at r2, 3 of 24 files at r7, 1 of 7 files at r8, 1 of 6 files at r9.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/2308#-:-NqnsGTk6PIWeMQPqJIH:bmbfmaz)* status: 68 of 70 files reviewed, 20 unresolved discussions (waiting on @pmachapman)

___
*[`src/SIL.XForge.Scripture/Services/TrainingDataService.cs` line 24 at r10](https://reviewable.io/reviews/sillsdev/web-xforge/2308#-NqndKia1-NJ82DNQhpC:-NqndKia1-NJ82DNQhpD:bb752ax) ([raw file](https://github.com/sillsdev/web-xforge/blob/e8e4c87f808b4a39b1cbf7d4852e0a76660c41b7/src/SIL.XForge.Scripture/Services/TrainingDataService.cs#L24)):*
> ```Smalltalk
> {
>     /// <summary>
>     /// The training directory name. This si not the full path to the directory.
> ```

Typo



_Code quote:_
```Smalltalk
This si not the full path to the directory.
```
___
*[`src/SIL.XForge.Scripture/Services/TrainingDataService.cs` line 154 at r10](https://reviewable.io/reviews/sillsdev/web-xforge/2308#-Nqnflp51nRvMGP75mZF:-Nqnflp51nRvMGP75mZG:b-2ph0fw) ([raw file](https://github.com/sillsdev/web-xforge/blob/e8e4c87f808b4a39b1cbf7d4852e0a76660c41b7/src/SIL.XForge.Scripture/Services/TrainingDataService.cs#L154)):*
> ```Smalltalk
>             var sourceSegments = new List<SFTextSegment>();
>             var targetSegments = new List<SFTextSegment>();
>             int i = 0;
> ```

Can we give this a more descriptive name?



_Code quote:_
```Smalltalk
           int i = 0;
```
___
*[`src/SIL.XForge.Scripture/Services/TrainingDataService.cs` line 218 at r10](https://reviewable.io/reviews/sillsdev/web-xforge/2308#-NqnhAJgA8_10M_G3n69:-NqnhAJgA8_10M_G3n6A:benhus7) ([raw file](https://github.com/sillsdev/web-xforge/blob/e8e4c87f808b4a39b1cbf7d4852e0a76660c41b7/src/SIL.XForge.Scripture/Services/TrainingDataService.cs#L218)):*
> ```Smalltalk
>     /// <param name="dataId">The data identifier.</param>
>     /// <param name="path">The path to the temporary file.</param>
>     /// <returns>The asynchronous task.</returns>
> ```

It also returns the URI.



_Code quote:_
```Smalltalk
  /// <returns>The asynchronous task.</returns>
```
___
*[`src/SIL.XForge.Scripture/Services/TrainingDataService.cs` line 338 at r10](https://reviewable.io/reviews/sillsdev/web-xforge/2308#-NqnkBC-EKkOIKPJYd6i:-NqnkBC-EKkOIKPJYd6j:b-1lal2v) ([raw file](https://github.com/sillsdev/web-xforge/blob/e8e4c87f808b4a39b1cbf7d4852e0a76660c41b7/src/SIL.XForge.Scripture/Services/TrainingDataService.cs#L338)):*
> ```Smalltalk
>         {
>             IRow row = sheet.GetRow(rowNum);
>             if (row is null || row.FirstCellNum == -1 || row.LastCellNum - row.FirstCellNum < 2)
> ```

Just curious why you didn't just check `row.cells < 2`



_Code quote:_
```Smalltalk
            if (row is null || row.FirstCellNum == -1 || row.LastCellNum - row.FirstCellNum < 2)
```
___
*[`src/SIL.XForge.Scripture/Services/TrainingDataService.cs` line 374 at r10](https://reviewable.io/reviews/sillsdev/web-xforge/2308#-NqnkRnxDvbvlIzuMMY7:-NqnkRnxDvbvlIzuMMY8:beviauc) ([raw file](https://github.com/sillsdev/web-xforge/blob/e8e4c87f808b4a39b1cbf7d4852e0a76660c41b7/src/SIL.XForge.Scripture/Services/TrainingDataService.cs#L374)):*
> ```Smalltalk
>     /// <param name="projectId"></param>
>     /// <param name="dataId"></param>
>     /// <returns></returns>
> ```

Nit: these can be removed.



_Code quote:_
```Smalltalk
    /// <param name="userId"></param>
    /// <param name="projectId"></param>
    /// <param name="dataId"></param>
    /// <returns></returns>
```
___
*[`test/SIL.XForge.Scripture.Tests/Controllers/SFProjectsUploadControllerTests.cs` line 54 at r10](https://reviewable.io/reviews/sillsdev/web-xforge/2308#-NqnmK44E5SDbVNBkMQO:-NqnmK44E5SDbVNBkMQP:b-egeyuw) ([raw file](https://github.com/sillsdev/web-xforge/blob/e8e4c87f808b4a39b1cbf7d4852e0a76660c41b7/test/SIL.XForge.Scripture.Tests/Controllers/SFProjectsUploadControllerTests.cs#L54)):*
> ```Smalltalk
>         // Throw the exception when saving the audio
>         env.SFProjectService.SaveAudioAsync(User01, Project01, Data01, Arg.Any<string>())
>             .Throws(new ForbiddenException());
> ```

I wonder if you could name a test to be `UploadAudioAsync_ReturnsUploadErrors` and just modify this line for each of the error scenarios. Alternatively, you could create a method called `TestUploadException(Exception exception)` and move this boilerplate code there.
But there are advantages of having it all written out, too. It just makes for a larger file.



_Code quote:_
```Smalltalk
        env.SFProjectService.SaveAudioAsync(User01, Project01, Data01, Arg.Any<string>())
            .Throws(new ForbiddenException());
```
___
*[`test/SIL.XForge.Scripture.Tests/Controllers/SFProjectsUploadControllerTests.cs` line 358 at r10](https://reviewable.io/reviews/sillsdev/web-xforge/2308#-NqnoNQ_Dz3mR8XKULEM:-NqnoNQ_Dz3mR8XKULEN:b-mvelxj) ([raw file](https://github.com/sillsdev/web-xforge/blob/e8e4c87f808b4a39b1cbf7d4852e0a76660c41b7/test/SIL.XForge.Scripture.Tests/Controllers/SFProjectsUploadControllerTests.cs#L358)):*
> ```Smalltalk
>             var request = new HttpRequestMessage { Content = content };
> 
>             // Set up the HTTP context with this data
> ```

Could you explain why the HttpContext needs to be set on the controller? My understanding of what HttpContext does is limited.

**Review by RaymondLuong3 — CHANGES_REQUESTED** [review]
> Reviewed 1 of 11 files at r10, 14 of 14 files at r11, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/2308)* status: all files reviewed, 3 unresolved discussions (waiting on @pmachapman)

___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-generation-steps/draft-generation-steps.component.ts` line 205 at r9](https://reviewable.io/reviews/sillsdev/web-xforge/2308#-NqdF11Q27i9coJhJymI:-NrMJdbhCEGzK9UkpIXT:bsgbj02) ([raw file](https://github.com/sillsdev/web-xforge/blob/f14f922c241fd52750fb86af3983176c69ba5d46/src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-generation-steps/draft-generation-steps.component.ts#L205)):*
<details><summary><i>Previously, pmachapman (Peter Chapman) wrote…</i></summary><blockquote>

Done. Good spotting - thanks!
</blockquote></details>

Would there be an issue if we just always set `this.initialSelectedTrainingDataIds = selectedTrainingDataIds`. That is essentially what this is doing. The only difference I see is that the current implementation keeps the order of selected training data consistent (which I don't think matters).
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-generation-steps/draft-generation-steps.component.ts` line 182 at r11](https://reviewable.io/reviews/sillsdev/web-xforge/2308#-NrMJ2j0Af2yBDRg1hJr:-NrMJ2j0Af2yBDRg1hJs:bczvsb4) ([raw file](https://github.com/sillsdev/web-xforge/blob/ff135fb92226abef2f3c5d900ba6107762006863/src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-generation-steps/draft-generation-steps.component.ts#L182)):*
> ```XML
>               this.trainingDataQuery.remoteDocChanges$
>             ),
>             () => {
> ```

You could move `this.availableTrainingData = []` to before the if, and that way remove the else block.
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/training-data/training-data-upload-dialog.component.html` line 12 at r9](https://reviewable.io/reviews/sillsdev/web-xforge/2308#-NqdNcXP8MJdlvIY0Xqq:-NrMTwyM9ikhqetMAPt7:b-uar3ya) ([raw file](https://github.com/sillsdev/web-xforge/blob/f14f922c241fd52750fb86af3983176c69ba5d46/src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/training-data/training-data-upload-dialog.component.html#L12)):*
<details><summary><i>Previously, pmachapman (Peter Chapman) wrote…</i></summary><blockquote>

Yes - I struggled with the one - designing the backend to be flexible, yet the frontend simple. That is why the checkbox sets a numeric value of 1 in  the `skipRows` property of `training-data`.
</blockquote></details>

I see that. For now, I think it suits our needs.
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/training-data/training-data-upload-dialog.component.ts` line 130 at r9](https://reviewable.io/reviews/sillsdev/web-xforge/2308#-NqdR8aH79VAXcez9gGS:-NrMMBAj4qXONAJDc16B:b-9vfbzr) ([raw file](https://github.com/sillsdev/web-xforge/blob/f14f922c241fd52750fb86af3983176c69ba5d46/src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/training-data/training-data-upload-dialog.component.ts#L130)):*
<details><summary><i>Previously, pmachapman (Peter Chapman) wrote…</i></summary><blockquote>

Thanks! I am not sure that I should use it? I think `uploadFile` works well if there are connection issues?
</blockquote></details>

`UploadFile` is what should be used if you want something to work whether they are online or offline, but `onlineUploadFileOrFail` will fail if the upload fails and the user will have to try again.
I would not advise using `uploadFile` because this upload dialog should upload and have confirmation that it has been successfully uploaded (and not just cached to be uploaded).
___
*[`test/SIL.XForge.Scripture.Tests/Controllers/SFProjectsUploadControllerTests.cs` line 54 at r10](https://reviewable.io/reviews/sillsdev/web-xforge/2308#-NqnmK44E5SDbVNBkMQO:-NrMSMkb43lUXq9RM2OY:b-umqguo) ([raw file](https://github.com/sillsdev/web-xforge/blob/e8e4c87f808b4a39b1cbf7d4852e0a76660c41b7/test/SIL.XForge.Scripture.Tests/Controllers/SFProjectsUploadControllerTests.cs#L54)):*
<details><summary><i>Previously, pmachapman (Peter Chapman) wrote…</i></summary><blockquote>

I prefer to keep the separate tests, so if one or more of them fails, the cause is more easily diagnosed.

Because of the two memory streams that are created, the http request message, and because these are disposed when out of scope, I have implemented a method that should reduce the boiler plate code, but requires the text environment to be disposable.

Let me know if this has made it better or more convoluted.
</blockquote></details>

Ah yes, reducing the boilerplate is nice. It may be a little more convoluted, but at least all tests have been updated so in the future we know that we need to dispose the TestEnvironment.

**Review by pmachapman — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/2308)* status: all files reviewed, 1 unresolved discussion (waiting on @RaymondLuong3)

___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-generation-steps/draft-generation-steps.component.ts` line 205 at r9](https://reviewable.io/reviews/sillsdev/web-xforge/2308#-NqdF11Q27i9coJhJymI:-NrWxWjkB5jKx_TdZuMr:bexvlth) ([raw file](https://github.com/sillsdev/web-xforge/blob/f14f922c241fd52750fb86af3983176c69ba5d46/src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-generation-steps/draft-generation-steps.component.ts#L205)):*
<details><summary><i>Previously, RaymondLuong3 (Raymond Luong) wrote…</i></summary><blockquote>

Would there be an issue if we just always set `this.initialSelectedTrainingDataIds = selectedTrainingDataIds`. That is essentially what this is doing. The only difference I see is that the current implementation keeps the order of selected training data consistent (which I don't think matters).
</blockquote></details>

I have removed this and simplified this - I think I misunderstood the pattern that was used for selected training and translation books, and misapplied it to additional files.
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-generation-steps/draft-generation-steps.component.ts` line 182 at r11](https://reviewable.io/reviews/sillsdev/web-xforge/2308#-NrMJ2j0Af2yBDRg1hJr:-NrWt1zp1XizGiD1B13d:b-896fix) ([raw file](https://github.com/sillsdev/web-xforge/blob/ff135fb92226abef2f3c5d900ba6107762006863/src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-generation-steps/draft-generation-steps.component.ts#L182)):*
<details><summary><i>Previously, RaymondLuong3 (Raymond Luong) wrote…</i></summary><blockquote>

You could move `this.availableTrainingData = []` to before the if, and that way remove the else block.
</blockquote></details>

Done.
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/training-data/training-data-upload-dialog.component.ts` line 130 at r9](https://reviewable.io/reviews/sillsdev/web-xforge/2308#-NqdR8aH79VAXcez9gGS:-NrWyNDH11ZD8c_P_ox0:b-896fix) ([raw file](https://github.com/sillsdev/web-xforge/blob/f14f922c241fd52750fb86af3983176c69ba5d46/src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/training-data/training-data-upload-dialog.component.ts#L130)):*
<details><summary><i>Previously, RaymondLuong3 (Raymond Luong) wrote…</i></summary><blockquote>

`UploadFile` is what should be used if you want something to work whether they are online or offline, but `onlineUploadFileOrFail` will fail if the upload fails and the user will have to try again.
I would not advise using `uploadFile` because this upload dialog should upload and have confirmation that it has been successfully uploaded (and not just cached to be uploaded).
</blockquote></details>

Done.

**Review by RaymondLuong3 — APPROVED** [review]
Thanks for your work on this. :lgtm: 

> Reviewed 10 of 10 files at r12, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/2308#-:-NrakmOL1uczedFW4oZJ:b-68vy36)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @pmachapman)

___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-generation-steps/draft-generation-steps.component.ts` line 205 at r9](https://reviewable.io/reviews/sillsdev/web-xforge/2308#-NqdF11Q27i9coJhJymI:-NraguLK4s3p2xhS7oIo:b-v66aaf) ([raw file](https://github.com/sillsdev/web-xforge/blob/f14f922c241fd52750fb86af3983176c69ba5d46/src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-generation-steps/draft-generation-steps.component.ts#L205)):*
<details><summary><i>Previously, pmachapman (Peter Chapman) wrote…</i></summary><blockquote>

I have removed this and simplified this - I think I misunderstood the pattern that was used for selected training and translation books, and misapplied it to additional files.
</blockquote></details>

Great. I'm glad we do not need a distinction between the initial and the user selected training data.

**Review by RaymondLuong3 — APPROVED** [review]
> Reviewed 20 of 20 files at r13, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/2308)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @pmachapman)

**Review by RaymondLuong3 — APPROVED** [review]
> Reviewed 9 of 9 files at r14, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/2308)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @pmachapman)

**Pull request merged**
