### PR TITLE
SF-2716 Upgrade to TypeScript 5.1

### PR DESCRIPTION
**Pull request by Nateowami**
See the Angular version documentation here: https://angular.io/guide/versions

Angular 16 (our current version) supports TypeScript < 5.2, and version 17 supports TypeScript >= 5.2. To make the upcoming upgrade a little smoother, I'm updating TypeScript to the newest version supported by Angular 16, namely, TypeScript 5.1.

- - -
This change is [Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/2435)

### CODE REVIEW

**Review by pmachapman — CHANGES_REQUESTED** [review]
Some comments below about the order of the imports being rearranged on save in VS code - I thought these  were automatically cleaned up by our IDE?

I was also unable to run `npm run lint` in `src/RealtmeServer` because it complained:
```
=============

WARNING: You are currently running a version of TypeScript which is not officially supported by @typescript-eslint/typescript-estree.

You may find that it works just fine, or you may not.

SUPPORTED TYPESCRIPT VERSIONS: >=3.3.1 <5.0.0

YOUR TYPESCRIPT VERSION: 5.1.6

Please only submit bug reports when using the officially supported version.

=============
DeprecationWarning: 'originalKeywordKind' has been deprecated since v5.0.0 and will no longer be usable after v5.2.0. Use 'identifierToKeywordKind(identifier)' instead.
```

> Reviewed 4 of 8 files at r1, 4 of 4 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/2435#-:-NwlsTF9BlNhDM7Q_rqZ:byijw7q)* status: all files reviewed, 3 unresolved discussions (waiting on @Nateowami)

___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-generation.component.ts` line 15 at r2](https://reviewable.io/reviews/sillsdev/web-xforge/2435#-NwluG160r8u_h3VvX6v:-NwluG160r8u_h3VvX6w:b-red9at) ([raw file](https://github.com/sillsdev/web-xforge/blob/01cd8b2d94d78e1477dd169b4304f5a9cd9deac8/src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-generation.component.ts#L15)):*
> ```XML
> import { SystemRole } from 'realtime-server/lib/esm/common/models/system-role';
> import { ProjectType } from 'realtime-server/lib/esm/scriptureforge/models/translate-config';
> import { Subscription, combineLatest, of } from 'rxjs';
> ```

When I saved this in VS Code, the order was rearranged. Is my machine configured differently? 



_Code quote:_
```XML
import { Subscription, combineLatest, of } from 'rxjs';
```
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/users/collaborators/collaborators.component.spec.ts` line 5 at r2](https://reviewable.io/reviews/sillsdev/web-xforge/2435#-Nwlu_cH7jGqi_6sAYtK:-Nwlu_cH7jGqi_6sAYtL:b-s28io5) ([raw file](https://github.com/sillsdev/web-xforge/blob/01cd8b2d94d78e1477dd169b4304f5a9cd9deac8/src/SIL.XForge.Scripture/ClientApp/src/app/users/collaborators/collaborators.component.spec.ts#L5)):*
> ```XML
> import { HttpClientTestingModule } from '@angular/common/http/testing';
> import { DebugElement, getDebugNode } from '@angular/core';
> import { ComponentFixture, TestBed, fakeAsync, flush, tick } from '@angular/core/testing';
> ```

This files imports were also rearranged when I saved this in VS Code?



_Code quote:_
```XML
import { ComponentFixture, TestBed, fakeAsync, flush, tick } from '@angular/core/testing';
```

**Review by pmachapman — COMMENTED** [review]
> Reviewed 8 of 8 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/2435)* status: all files reviewed, 3 unresolved discussions (waiting on @Nateowami)

**Review by pmachapman — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/2435)* status: all files reviewed, 2 unresolved discussions (waiting on @Nateowami)

___
*[`src/SIL.XForge.Scripture/ClientApp/tsconfig.json` line 20 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/2435#-NwjmrQR6HNuS_ARy91M:-NxFIDwXCWY_Dr7ttEIp:bb6ywmx) ([raw file](https://github.com/sillsdev/web-xforge/blob/a9f222cde0b454a736df46c2d0d824b3e23d3478/src/SIL.XForge.Scripture/ClientApp/tsconfig.json#L20)):*
<details><summary><i>Previously, Nateowami (Nathaniel Paulus) wrote…</i></summary><blockquote>

Unfortunately `suppressImplicitAnyIndexErrors` is needed to prevent a large number of compiler errors, and since `suppressImplicitAnyIndexErrors` is going away, the `ignoreDeprecations` has to be set to prevent an error about our use of `suppressImplicitAnyIndexErrors`.
</blockquote></details>

LGTM

**Comment by Nateowami** [comment]
@pmachapman This looks good. I don't know why my editor was sorting imports. It looks like they were being sorted in a case-sensitive way, whereas previously it was a case-insensitive sort.

**Review by pmachapman — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/2435)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @Nateowami)

**Pull request merged**
