### PR TITLE
SF-2173 Restrict note updating in Scripture Forge

### PR DESCRIPTION
**Pull request by pmachapman**
**Summary**
This Pull Request restricts note editing and writing to Paratext to only those notes that are created in Scripture Forge.

**New Features and Changed Behavior**
 * A C# Feature Flag to enable Note writing to Paratext
 * Disabled the ability to edit or delete comments created or edited in Paratext by the logged in user

**Testing**
To enable writing Notes to Paratext, enable the feature flag by running the following in `src/SIL.XForge.Scripture/`:
```
dotnet user-secrets set "FeatureManagement:WriteNotesToParatext" true
```
See also the Acceptance test for the corresponding JIRA ticket.

- - -
This change is [Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1988)

### CODE REVIEW

**Review by RaymondLuong3 — CHANGES_REQUESTED** [review]
Good thinking with the feature flag. We can let testers know to enable the feature flag and test the feature. Thanks for adding the acceptance tests. I can confirm that the behaviour is what is laid out in the test.

> Reviewed 5 of 9 files at r1, 7 of 7 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1988#-:-NbM9WFMCC8-za6-ypWM:b-4x8w9k)* status: all files reviewed, 7 unresolved discussions (waiting on @github-code-scanning[bot] and @pmachapman)

___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/note-dialog/note-dialog.component.spec.ts` line 442 at r2](https://reviewable.io/reviews/sillsdev/web-xforge/1988#-NbMAFgbAi4SDKo2EVkW:-NbMAFgbAi4SDKo2EVkX:bg8q3a6) ([raw file](https://github.com/sillsdev/web-xforge/blob/a55ad1e3686efd3e81367c0ecf559285fbaee87f/src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/note-dialog/note-dialog.component.spec.ts#L442)):*
> ```XML
>     expect(env.notes.length).toEqual(4);
>     const noteNumbers = [1, 2, 3, 4];
>     noteNumbers.forEach(n => expect(env.noteHasEditActions(n)).toBe(false));
> ```

I think you meant for this to be `noteHasDeleteAction`.



_Code quote:_
```XML
   noteNumbers.forEach(n => expect(env.noteHasEditActions(n)).toBe(false));
```
___
*[`src/SIL.XForge.Scripture/Services/ParatextService.cs` line 2307 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/1988#gh-1281416341:-NbMCOiECjMU7gy7H5no:b-biq1x0) ([raw file](https://github.com/sillsdev/web-xforge/blob/a0f571e7b0786c39913ba2200042f563867d4ea5/src/SIL.XForge.Scripture/Services/ParatextService.cs#L2307)):*
<details><summary><i>Previously, github-code-scanning[bot] wrote…</i></summary><blockquote>

## Dereferenced variable may be null

Variable [comment.Contents](1) may be null at this access as suggested by [this](2) null check.

[Show more details](https://github.com/sillsdev/web-xforge/security/code-scanning/623)
</blockquote></details>

Do not-null assertions work in C#? I wasn't aware of that. It appears github is also not aware of that.
___
*[`src/SIL.XForge.Scripture/Services/ParatextService.cs` line 1266 at r2](https://reviewable.io/reviews/sillsdev/web-xforge/1988#-NbMDhlyAX9VfibPXq_8:-NbMDhlyAX9VfibPXq_9:bu8hqi8) ([raw file](https://github.com/sillsdev/web-xforge/blob/a55ad1e3686efd3e81367c0ecf559285fbaee87f/src/SIL.XForge.Scripture/Services/ParatextService.cs#L1266)):*
> ```Smalltalk
>                     matchedCommentIds.Add(matchedComment.Id);
>                     CommentTag commentIconTag = GetCommentTag(existingThread, matchedComment, commentTags);
>                     ChangeType changeType = GetCommentChangeType(matchedComment, note, commentIconTag, ptProjectUsers);
> ```

In `GetCommentChangeType` you will need to check the Version number also to see if that has changed. In most cases, you do not because the content would have changed in PT, and the resulting `NoteThreadChange` would have the most up to date version number. But in the case where nothing has changed except the version number (say a user edits a note, then edits it again back to the original text) then we miss updating the `NoteThread` with the updated version number.



_Code quote:_
```Smalltalk
                    ChangeType changeType = GetCommentChangeType(matchedComment, note, commentIconTag, ptProjectUsers);
```
___
*[`src/SIL.XForge.Scripture/Services/ParatextService.cs` line 2302 at r2](https://reviewable.io/reviews/sillsdev/web-xforge/1988#-NbMB_3zEl121Lj1jV6y:-NbMB_3zEl121Lj1jV6z:b-guw0ih) ([raw file](https://github.com/sillsdev/web-xforge/blob/a55ad1e3686efd3e81367c0ecf559285fbaee87f/src/SIL.XForge.Scripture/Services/ParatextService.cs#L2302)):*
> ```Smalltalk
> 
>                     // We can only update a note if the comment and note have the same version number
>                     if (note.VersionNumber == comment.VersionNumber)
> ```

I wonder when the version numbers would not match. Or is this to be extra safe. Oh, does it have to do with the fact that if we have an outdated version of a note, we drop what SF has in favour of what Paratext has?



_Code quote:_
```Smalltalk
                    if (note.VersionNumber == comment.VersionNumber)
```
___
*[`test/SIL.XForge.Scripture.Tests/Services/ParatextServiceTests.cs` line 2412 at r2](https://reviewable.io/reviews/sillsdev/web-xforge/1988#-NbMFUXM1zfYzdJH3_RQ:-NbMFUXM1zfYzdJH3_RR:b-ab98pj) ([raw file](https://github.com/sillsdev/web-xforge/blob/a55ad1e3686efd3e81367c0ecf559285fbaee87f/test/SIL.XForge.Scripture.Tests/Services/ParatextServiceTests.cs#L2412)):*
> ```Smalltalk
> 
>     [Test]
>     public async Task UpdateParatextComments_DoesNotEditNonEditableComment()
> ```

From looking at this test, I don't think that the text content of the PT notes and SF notes would have changed, so it might not actually be testing that the contents are unchanged. It would be better to show that the SF note content is different and then show that no changes are sent.



_Code quote:_
```Smalltalk
    public async Task UpdateParatextComments_DoesNotEditNonEditableComment()
```
___
*[`test/SIL.XForge.Scripture.Tests/Services/ParatextServiceTests.cs` line 2456 at r2](https://reviewable.io/reviews/sillsdev/web-xforge/1988#-NbMFECwEldMhCALwdaA:-NbMFECwEldMhCALwdaB:bgo0hzx) ([raw file](https://github.com/sillsdev/web-xforge/blob/a55ad1e3686efd3e81367c0ecf559285fbaee87f/test/SIL.XForge.Scripture.Tests/Services/ParatextServiceTests.cs#L2456)):*
> ```Smalltalk
>         await using IConnection conn = await env.RealtimeService.ConnectAsync();
>         IDocument<NoteThread> noteThreadDoc = await TestEnvironment.GetNoteThreadDocAsync(conn, dataId);
>         // Edit a comment
> ```

This comment can be removed.



_Code quote:_
```Smalltalk
        // Edit a comment
```
___
*[`test/SIL.XForge.Scripture.Tests/Services/ParatextServiceTests.cs` line 4734 at r2](https://reviewable.io/reviews/sillsdev/web-xforge/1988#-NbMHRnABLB2pnssTwrW:-NbMHRnABLB2pnssTwrX:b748dh0) ([raw file](https://github.com/sillsdev/web-xforge/blob/a55ad1e3686efd3e81367c0ecf559285fbaee87f/test/SIL.XForge.Scripture.Tests/Services/ParatextServiceTests.cs#L4734)):*
> ```Smalltalk
>                         Assignment = noteComponent.assignedPTUser,
>                         Editable = noteComponent.editable ?? comp.editable,
>                         VersionNumber = noteComponent.versionNumber ?? comp.versionNumber,
> ```

That is good you set the value of editable and versionNumber to be nullable, otherwise this would not work since the values would get set to the default values otherwise, and the null check would not work.



_Code quote:_
```Smalltalk
                        Assignment = noteComponent.assignedPTUser,
                        Editable = noteComponent.editable ?? comp.editable,
                        VersionNumber = noteComponent.versionNumber ?? comp.versionNumber,
```

**Review by pmachapman — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1988)* status: all files reviewed, 6 unresolved discussions (waiting on @github-code-scanning[bot] and @RaymondLuong3)

___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/note-dialog/note-dialog.component.spec.ts` line 442 at r2](https://reviewable.io/reviews/sillsdev/web-xforge/1988#-NbMAFgbAi4SDKo2EVkW:-NbMud9MEVGuK88qFDQU:b-o5zz2j) ([raw file](https://github.com/sillsdev/web-xforge/blob/a55ad1e3686efd3e81367c0ecf559285fbaee87f/src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/note-dialog/note-dialog.component.spec.ts#L442)):*
<details><summary><i>Previously, RaymondLuong3 (Raymond Luong) wrote…</i></summary><blockquote>

I think you meant for this to be `noteHasDeleteAction`.
</blockquote></details>

Both the edit and delete buttons are in a div that has the "edit-actions" class, which this method checks for (the edit and delete buttons have the same permissions).
___
*[`src/SIL.XForge.Scripture/Services/ParatextService.cs` line 2307 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/1988#gh-1281416341:-NbMvwXl8dT06q-v_0zf:bbaqprx) ([raw file](https://github.com/sillsdev/web-xforge/blob/a0f571e7b0786c39913ba2200042f563867d4ea5/src/SIL.XForge.Scripture/Services/ParatextService.cs#L2307)):*
<details><summary><i>Previously, RaymondLuong3 (Raymond Luong) wrote…</i></summary><blockquote>

Do not-null assertions work in C#? I wasn't aware of that. It appears github is also not aware of that.
</blockquote></details>

This is an old warning that I fixed with the `!` operator (I wish I could delete these when they are created in Draft PRs).
___
*[`src/SIL.XForge.Scripture/Services/ParatextService.cs` line 1266 at r2](https://reviewable.io/reviews/sillsdev/web-xforge/1988#-NbMDhlyAX9VfibPXq_8:-NbN76vWC5bjtn0yvflW:bw1wujr) ([raw file](https://github.com/sillsdev/web-xforge/blob/a55ad1e3686efd3e81367c0ecf559285fbaee87f/src/SIL.XForge.Scripture/Services/ParatextService.cs#L1266)):*
<details><summary><i>Previously, RaymondLuong3 (Raymond Luong) wrote…</i></summary><blockquote>

In `GetCommentChangeType` you will need to check the Version number also to see if that has changed. In most cases, you do not because the content would have changed in PT, and the resulting `NoteThreadChange` would have the most up to date version number. But in the case where nothing has changed except the version number (say a user edits a note, then edits it again back to the original text) then we miss updating the `NoteThread` with the updated version number.
</blockquote></details>

Good catch. Thank you!
___
*[`src/SIL.XForge.Scripture/Services/ParatextService.cs` line 2302 at r2](https://reviewable.io/reviews/sillsdev/web-xforge/1988#-NbMB_3zEl121Lj1jV6y:-NbN4eUI-lk0egEXdwl4:b-3oy7q3) ([raw file](https://github.com/sillsdev/web-xforge/blob/a55ad1e3686efd3e81367c0ecf559285fbaee87f/src/SIL.XForge.Scripture/Services/ParatextService.cs#L2302)):*
<details><summary><i>Previously, RaymondLuong3 (Raymond Luong) wrote…</i></summary><blockquote>

I wonder when the version numbers would not match. Or is this to be extra safe. Oh, does it have to do with the fact that if we have an outdated version of a note, we drop what SF has in favour of what Paratext has?
</blockquote></details>

It is in a sense being extra safe, but yes, if a note is outdated, it will be replaced with the contents from Paratext later in the sync.
___
*[`test/SIL.XForge.Scripture.Tests/Services/ParatextServiceTests.cs` line 2412 at r2](https://reviewable.io/reviews/sillsdev/web-xforge/1988#-NbMFUXM1zfYzdJH3_RQ:-NbMyIEr8LsMGKzIc2g-:bcgkrkt) ([raw file](https://github.com/sillsdev/web-xforge/blob/a55ad1e3686efd3e81367c0ecf559285fbaee87f/test/SIL.XForge.Scripture.Tests/Services/ParatextServiceTests.cs#L2412)):*
<details><summary><i>Previously, RaymondLuong3 (Raymond Luong) wrote…</i></summary><blockquote>

From looking at this test, I don't think that the text content of the PT notes and SF notes would have changed, so it might not actually be testing that the contents are unchanged. It would be better to show that the SF note content is different and then show that no changes are sent.
</blockquote></details>

Good idea - I have added a verification that the note content is different (i.e. edited) in SF compared to PT.
___
*[`test/SIL.XForge.Scripture.Tests/Services/ParatextServiceTests.cs` line 2456 at r2](https://reviewable.io/reviews/sillsdev/web-xforge/1988#-NbMFECwEldMhCALwdaA:-NbN1AjR2ialPHM5fnNK:b4huqxq) ([raw file](https://github.com/sillsdev/web-xforge/blob/a55ad1e3686efd3e81367c0ecf559285fbaee87f/test/SIL.XForge.Scripture.Tests/Services/ParatextServiceTests.cs#L2456)):*
<details><summary><i>Previously, RaymondLuong3 (Raymond Luong) wrote…</i></summary><blockquote>

This comment can be removed.
</blockquote></details>

Removed here and elsewhere (copy-pasta).

**Review by RaymondLuong3 — APPROVED** [review]
Nice work. I'll send this to the testers to verify the change.

> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1988#-:-NbQBs133bAyS_UlT3_y:btzos9k)* status: all files reviewed, 1 unresolved discussion (waiting on @github-code-scanning[bot])

___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/note-dialog/note-dialog.component.spec.ts` line 442 at r2](https://reviewable.io/reviews/sillsdev/web-xforge/1988#-NbMAFgbAi4SDKo2EVkW:-NbQAxi68QotsWB_ELUX:bc5n8oj) ([raw file](https://github.com/sillsdev/web-xforge/blob/a55ad1e3686efd3e81367c0ecf559285fbaee87f/src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/note-dialog/note-dialog.component.spec.ts#L442)):*
<details><summary><i>Previously, pmachapman (Peter Chapman) wrote…</i></summary><blockquote>

Both the edit and delete buttons are in a div that has the "edit-actions" class, which this method checks for (the edit and delete buttons have the same permissions).
</blockquote></details>

Ah yes, I see. This test doesn't test anything different from the one two tests above then. Feel free to remove it if you think it might cause confusion.

**Review by RaymondLuong3 — APPROVED** [review]
> Reviewed 4 of 4 files at r4, 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1988)* status: all files reviewed, 1 unresolved discussion (waiting on @github-code-scanning[bot])

**Pull request merged**
