### PR TITLE
SF-2209 Pause Audio When Navigating Away

### PR DESCRIPTION
**Pull request by josephmyers**
Commit history is wonky, since the original base branch was the Close button branch. The file diff is correct, though.

- - -
This change is [Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/2028)

### CODE REVIEW

**Comment by josephmyers** [comment]
Annoying #worksonmymachine
image

**Review by RaymondLuong3 — CHANGES_REQUESTED** [review]
> Reviewed 3 of 4 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/2028)* status: all files reviewed, 1 unresolved discussion (waiting on @josephmyers)

___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking.component.spec.ts` line 1736 at r2](https://reviewable.io/reviews/sillsdev/web-xforge/2028#-NdkSpAq1GXf1FfgRgtG:-NdkSpAq1GXf1FfgRgtH:bmcpkmr) ([raw file](https://github.com/sillsdev/web-xforge/blob/3440444480d45f99a0702fa47c40deb398bf863c/src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking.component.spec.ts#L1736)):*
> ```XML
> 
>       env.component.chapter = 99;
>       env.component.chapter = 99;
> ```

You probably don't need this second line. Maybe instead of using a chapter that doesn't exist, just use chapter 2. That way you are testing a scenario that can happen.



_Code quote:_
```XML
      env.component.chapter = 99;
```

**Review by josephmyers — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/2028)* status: 0 of 5 files reviewed, 1 unresolved discussion (waiting on @RaymondLuong3)

___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking.component.spec.ts` line 1736 at r2](https://reviewable.io/reviews/sillsdev/web-xforge/2028#-NdkSpAq1GXf1FfgRgtG:-NebU2QzC0ZfgX1cAeZH:b-p9vcqf) ([raw file](https://github.com/sillsdev/web-xforge/blob/3440444480d45f99a0702fa47c40deb398bf863c/src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking.component.spec.ts#L1736)):*
<details><summary><i>Previously, RaymondLuong3 (Raymond Luong) wrote…</i></summary><blockquote>

You probably don't need this second line. Maybe instead of using a chapter that doesn't exist, just use chapter 2. That way you are testing a scenario that can happen.
</blockquote></details>

The reason I had the second set was to demonstrate that setting it a second time doesn't trigger a second call. But it's not a big deal!

**Review by RaymondLuong3 — APPROVED** [review]
Alright, looks good to me.

> Reviewed 5 of 5 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/2028#-:-NedU7ERDUjTesC-TDgr:bdgy1jc)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @josephmyers)

**Review by RaymondLuong3 — APPROVED** [review]
> Reviewed 6 of 6 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/2028)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @josephmyers)

**Pull request merged**
