### PR TITLE
SF-1702 Improve support for other footnote callers

### PR DESCRIPTION
**Pull request by nigel-wells**
- Allow any time of note to be clicked
- Added support for hidden notes
- Use cross character for cross-references when a custom caller is not used
- Improved support for customer callers that are more than 1 character

image

- - -
This change is [Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1499)

### CODE REVIEW

**Review by Nateowami — CHANGES_REQUESTED** [review]
Just a couple issues. The color is grayish on my machine, unlike your screenshots. The border radius makes it into an oval, rather than rounded corners. If you set the border radius to a fixed value (e.g. 5em) rather than a percentage you can get consistent rounded corners. The height is set to `1.25em`, so we could set the the border radius to `0.625em`. Or we could just set it to `5em`, and the browser will limit the actual border radius to 50% of the smaller of the width or height (in order case, height is equal or less than width, so the border radius will end up being half the height).



> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1499#-:-NC6jUXvCYIZNkgWk54M:b-8zk81q)* status: all files reviewed, 1 unresolved discussion (waiting on @nigel-wells)

___
*[`-- commits` line 6 at r2](https://reviewable.io/reviews/sillsdev/web-xforge/1499#-NC7UX55Aqlr6AkKKJWI):*
"Type", not "time"



_Code quote:_
```
time
```

**Review by nigel-wells — COMMENTED** [review]
Good call, I thought it didn't look too bad in my screenshot but it does get worse if there are more characters. I've changed to `1em` and it looks better:


Regarding the gray colour, didn't we conclude that there was a setting either in your browser or your monitor that was causing colors to be off? I can't recall what the other issue was but I'm pretty sure it was only happening to you :) My experience with that happening to me is the incorrect color profile has been set for my monitor in Windows settings - not sure what or where it would be in Linux.

> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1499#-:-NC8JM6-59JUP4E9kyMd:b-5kqrw)* status: 0 of 2 files reviewed, 1 unresolved discussion (waiting on @Nateowami and @nigel-wells)

**Review by nigel-wells — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1499)* status: 0 of 2 files reviewed, 1 unresolved discussion (waiting on @Nateowami)

___
*[`-- commits` line 6 at r2](https://reviewable.io/reviews/sillsdev/web-xforge/1499#-NC7UX55Aqlr6AkKKJWI):*
<details><summary><i>Previously, Nateowami (Nathaniel Paulus) wrote…</i></summary><blockquote>

"Type", not "time"
</blockquote></details>

Done.

**Review by Nateowami — CHANGES_REQUESTED** [review]
The text color still seems to be off: 

I don't know why we wouldn't both be seeing the same thing. It clearly doesn't look the same in your screenshots.

Here's the rule applying the text color: 
``` scss
// _text.scss
.template-editor > .ql-container > .ql-editor *[contenteditable=false] {
    color: #7c7c7c;
}
```

> Reviewed 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1499#-:-NCLMoTRD2WuVNio6KTx:b-j2zflk)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @nigel-wells)

**Review by nigel-wells — COMMENTED** [review]
I've removed that style and added the colour to the chapter and verse as discussed. The testers can take a better look to see if it might need to be applied to other elements as well.

> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1499#-:-NCNmCJbBdPKwzQaw6qY:bwgcqgw)* status: 1 of 3 files reviewed, all discussions resolved (waiting on @Nateowami)

**Review by Nateowami — APPROVED** [review]
> Reviewed 2 of 2 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1499)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @nigel-wells)

**Review by Nateowami — APPROVED** [review]
> Reviewed 3 of 3 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1499)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @nigel-wells)

**Pull request merged**
