### PR TITLE
SF-1805 Improve performance of questions query in app component

### PR DESCRIPTION
**Pull request by Nateowami**
- Reverts temporary app component changes from #1576 (the `throttleTime`, as well as changes to the tests)
- Improved the performance of determining which books have questions

This change is [Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1577)

### CODE REVIEW

**Review by nigel-wells — CHANGES_REQUESTED** [review]
Great job on this - much more efficient and compact.

Just one query around offline support to consider.

> Reviewed 1 of 2 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1577#-:-NGDvgTr0bHFUVI8CO-I:b62sb0l)* status: all files reviewed, 2 unresolved discussions (waiting on @marksvc and @Nateowami)

___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/app.component.ts` line 556 at r2](https://reviewable.io/reviews/sillsdev/web-xforge/1577#-NGDv8QBAdSfvQDuSvRt:-NGDv8QBAdSfvQDuSvRu:b3ms0br) ([raw file](https://github.com/sillsdev/web-xforge/blob/654adbb98dd09ef72bff2f4be68edd2bae2d01b2/src/SIL.XForge.Scripture/ClientApp/src/app/app.component.ts#L556)):*
> ```XML
> 
>     const query = await this.projectService.queryQuestions(projectId, { activeOnly: true });
>     this.questionsQuery = query;
> ```

nit: `query` is not needed and you can just set straight onto `this.questionsQuery`



_Code quote:_
```XML
    const query = await this.projectService.queryQuestions(projectId, { activeOnly: true });
    this.questionsQuery = query;
```
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/app.component.ts` line 582 at r2](https://reviewable.io/reviews/sillsdev/web-xforge/1577#-NGDw2mA6I-TbFwwPqH0:-NGDw2mA6I-TbFwwPqH1:bm507ce) ([raw file](https://github.com/sillsdev/web-xforge/blob/a9d7caa44f4d05df67cd7149c82dc83025f36989/src/SIL.XForge.Scripture/ClientApp/src/app/app.component.ts#L582)):*
> ```XML
>         }
>         if (query.count > 0) {
>           this.selectedProjectDoc.loadTextDocs(bookNum);
> ```

Did we still want to do this as it was a nice side affect to help support community checking in offline mode while we don't have an interface to choose what gets downloaded.

**Review by Nateowami — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1577)* status: all files reviewed, 2 unresolved discussions (waiting on @marksvc and @nigel-wells)

___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/app.component.ts` line 556 at r2](https://reviewable.io/reviews/sillsdev/web-xforge/1577#-NGDv8QBAdSfvQDuSvRt:-NGEk-SQCzKD6cRSLnDc:btp4ym2) ([raw file](https://github.com/sillsdev/web-xforge/blob/654adbb98dd09ef72bff2f4be68edd2bae2d01b2/src/SIL.XForge.Scripture/ClientApp/src/app/app.component.ts#L556)):*
<details><summary><i>Previously, nigel-wells (Nigel Wells) wrote…</i></summary><blockquote>

nit: `query` is not needed and you can just set straight onto `this.questionsQuery`
</blockquote></details>

Good point. I'll fix it.
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/app.component.ts` line 582 at r2](https://reviewable.io/reviews/sillsdev/web-xforge/1577#-NGDw2mA6I-TbFwwPqH0:-NGEjrvB60vy9Etv6dXx:bctgg4w) ([raw file](https://github.com/sillsdev/web-xforge/blob/a9d7caa44f4d05df67cd7149c82dc83025f36989/src/SIL.XForge.Scripture/ClientApp/src/app/app.component.ts#L582)):*
<details><summary><i>Previously, nigel-wells (Nigel Wells) wrote…</i></summary><blockquote>

Did we still want to do this as it was a nice side affect to help support community checking in offline mode while we don't have an interface to choose what gets downloaded.
</blockquote></details>

Oh, good point. I missed this somehow. What do you think about just querying for all texts on the project?

**Review by nigel-wells — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1577)* status: all files reviewed, 2 unresolved discussions (waiting on @marksvc and @Nateowami)

___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/app.component.ts` line 582 at r2](https://reviewable.io/reviews/sillsdev/web-xforge/1577#-NGDw2mA6I-TbFwwPqH0:-NGExm2BDRZ5SgRk_8Bp:bj42wya) ([raw file](https://github.com/sillsdev/web-xforge/blob/a9d7caa44f4d05df67cd7149c82dc83025f36989/src/SIL.XForge.Scripture/ClientApp/src/app/app.component.ts#L582)):*
<details><summary><i>Previously, Nateowami (Nathaniel Paulus) wrote…</i></summary><blockquote>

Oh, good point. I missed this somehow. What do you think about just querying for all texts on the project?
</blockquote></details>

From a community checkers POV they only need the text for the books that have questions. Main consideration if we do all text is how much data that would download to a phone and if that would create an issue that they're unable to resolve on their own. I think go with minimal effort to achieve the same/similar functionality we already have as we'll no doubt address this more when we properly address offline support next year.

**Comment by marksvc** [comment]
:eyes:

**Review by marksvc — CHANGES_REQUESTED** [review]
Thanks for your work on this. :clap: 
I approve, except for my blocking comment, and offline texts that Nigel brought up.

> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1577#-:-NGIIt6S9VkedWXaxBHg:bcc00hm)* status: all files reviewed, 6 unresolved discussions (waiting on @marksvc, @Nateowami, and @nigel-wells)

___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/app.component.ts` line 295 at r2](https://reviewable.io/reviews/sillsdev/web-xforge/1577#-NGI3JEJ-ZD3etlkdyKK:-NGI3JEJ-ZD3etlkdyKL:b-nbrjbb) ([raw file](https://github.com/sillsdev/web-xforge/blob/654adbb98dd09ef72bff2f4be68edd2bae2d01b2/src/SIL.XForge.Scripture/ClientApp/src/app/app.component.ts#L295)):*
> ```XML
>   async ngOnInit(): Promise<void> {
>     this.loadingStarted();
>     if (await this.isLoggedIn) {
> ```

Wow, it looks like this could make use of a serious if-inversion. 



_Code quote:_
```XML
if (await this.isLoggedIn) {
```
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/app.component.ts` line 407 at r2](https://reviewable.io/reviews/sillsdev/web-xforge/1577#-NGI26LH9O_YYGIJQwkE:-NGI26LH9O_YYGIJQwkF:b-tsx4c0) ([raw file](https://github.com/sillsdev/web-xforge/blob/654adbb98dd09ef72bff2f4be68edd2bae2d01b2/src/SIL.XForge.Scripture/ClientApp/src/app/app.component.ts#L407)):*
> ```XML
>             this.selectedProjectDoc?.data != null &&
>             this.currentUserDoc != null &&
>             !(this.currentUserDoc.id in this.selectedProjectDoc.data.userRoles)
> ```

It seems like if there is a remote change and the current user is _no longer on the project_, then that user wouldn't have permission to _receive_ the remote change about it :-). 



_Code quote:_
```XML
   !(this.currentUserDoc.id in this.selectedProjectDoc.data.userRoles)
```
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/app.component.ts` line 428 at r2](https://reviewable.io/reviews/sillsdev/web-xforge/1577#-NGI8QGv5LscGQWOI3hf:-NGI8QGv5LscGQWOI3hg:b80ys1n) ([raw file](https://github.com/sillsdev/web-xforge/blob/654adbb98dd09ef72bff2f4be68edd2bae2d01b2/src/SIL.XForge.Scripture/ClientApp/src/app/app.component.ts#L428)):*
> ```XML
>       });
> 
>       this.subscribe(projectId$.pipe(filter(id => id != null)), async projectId => {
> ```

Previously, this code had a lambda saying `async projectId => await this...setCurrentProjectId(`. 
For my own understanding:  **In the context at hand** (where this is getting called from a subscribe), was the `await` without any influence on behaviour, and the behaviour would be the same without the `await`?



_Code quote:_
```XML
async 
```
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/app.component.ts` line 428 at r2](https://reviewable.io/reviews/sillsdev/web-xforge/1577#-NGII42P2A0ly4SSj5Y5:-NGII42P2A0ly4SSj5Y6:bn4z8f1) ([raw file](https://github.com/sillsdev/web-xforge/blob/654adbb98dd09ef72bff2f4be68edd2bae2d01b2/src/SIL.XForge.Scripture/ClientApp/src/app/app.component.ts#L428)):*
> ```XML
>       });
> 
>       this.subscribe(projectId$.pipe(filter(id => id != null)), async projectId => {
> ```

At present, the lambda has no `await`s in it, but we do specify the lambda as `async`. Is there any use or significance of specifying that the lambda is `async`? Is it going to be the same as if we omitted `async`?



_Code quote:_
```XML
async projectId
```
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/app.component.ts` line 430 at r2](https://reviewable.io/reviews/sillsdev/web-xforge/1577#-NGI3jbUC2h1-xvW0y1p:-NGI3jbUC2h1-xvW0y1q:bknmzml) ([raw file](https://github.com/sillsdev/web-xforge/blob/654adbb98dd09ef72bff2f4be68edd2bae2d01b2/src/SIL.XForge.Scripture/ClientApp/src/app/app.component.ts#L430)):*
> ```XML
>       this.subscribe(projectId$.pipe(filter(id => id != null)), async projectId => {
>         this.refreshQuestionsQuery(projectId);
>         this.userService.setCurrentProjectId(this.currentUserDoc!, projectId);
> ```

Hmm. I wonder if there would be any significance for a situation where a user is removed from their last SF project, that we set their current project id to null/undefined, instead of leaving it as the no-longer-really-valid id of the last project that they were on. 
Just thinking out loud. 

(This is not related to something your patch is doing.)



_Code quote:_
```XML
      this.subscribe(projectId$.pipe(filter(id => id != null)), async projectId => {
        this.refreshQuestionsQuery(projectId);
        this.userService.setCurrentProjectId(this.currentUserDoc!, projectId);
```
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/app.component.ts` line 557 at r2](https://reviewable.io/reviews/sillsdev/web-xforge/1577#-NGI4hOLA1L8cXxj0tUx:-NGI4hOLA1L8cXxj0tUy:b-hkmc1r) ([raw file](https://github.com/sillsdev/web-xforge/blob/654adbb98dd09ef72bff2f4be68edd2bae2d01b2/src/SIL.XForge.Scripture/ClientApp/src/app/app.component.ts#L557)):*
> ```XML
>     const query = await this.projectService.queryQuestions(projectId, { activeOnly: true });
>     this.questionsQuery = query;
>     query.docs$.subscribe(docs => {
> ```

I'm so glad this had an API comment over in realtime-query.ts :-)



_Code quote:_
```XML
.docs$
```
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/app.component.ts` line 559 at r2](https://reviewable.io/reviews/sillsdev/web-xforge/1577#-NGI7QQK9mMfgZcnkHeL:-NGI7QQK9mMfgZcnkHeM:besxg2a) ([raw file](https://github.com/sillsdev/web-xforge/blob/654adbb98dd09ef72bff2f4be68edd2bae2d01b2/src/SIL.XForge.Scripture/ClientApp/src/app/app.component.ts#L559)):*
> ```XML
>     query.docs$.subscribe(docs => {
>       const books = new Set<number>();
>       for (const question of docs) {
> ```

I think this could benefit from some throttling, because if I add 1000 questions to a project, then this might run 1000 times, each time iterating over all questions in the project and building the book number set (and so run the inner part of the loop  1000+999+998+...+1 times). This seems like something that could benefit from a debounce or throttling. Do you think?
Not that, as is, it's going to be slower than the previous version of the  code. 



_Code quote:_
```XML
    const query = await this.projectService.queryQuestions(projectId, { activeOnly: true });
    this.questionsQuery = query;
    query.docs$.subscribe(docs => {
      const books = new Set<number>();
      for (const question of docs) {
```
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/app.component.spec.ts` line 569 at r2](https://reviewable.io/reviews/sillsdev/web-xforge/1577#-NGICKQzDS40dBGYQ0qi:-NGICKQzDS40dBGYQ0qj:btt7zwp) ([raw file](https://github.com/sillsdev/web-xforge/blob/654adbb98dd09ef72bff2f4be68edd2bae2d01b2/src/SIL.XForge.Scripture/ClientApp/src/app/app.component.spec.ts#L569)):*
> ```XML
>       const parameters: QueryParameters = {};
>       if (options.bookNum != null) parameters[obj<Question>().pathStr(q => q.verseRef.bookNum)] = options.bookNum;
>       if (options.activeOnly) parameters[obj<Question>().pathStr(q => q.isArchived)] = false;
> ```

I had to think about this one for a bit to decide if it was doing the right thing :)



_Code quote:_
```XML
     if (options.activeOnly) parameters[obj<Question>().pathStr(q => q.isArchived)] = false;
```
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/app.component.spec.ts` line 855 at r2](https://reviewable.io/reviews/sillsdev/web-xforge/1577#-NGIEfqS6BzeakWYBA2a:-NGIEfqS6BzeakWYBA2b:b-8f2je9) ([raw file](https://github.com/sillsdev/web-xforge/blob/a9d7caa44f4d05df67cd7149c82dc83025f36989/src/SIL.XForge.Scripture/ClientApp/src/app/app.component.spec.ts#L855)):*
> ```XML
>     projectDoc.submitJson0Op(op => op.set<string>(p => p.userRoles['user01'], SFProjectRole.CommunityChecker), false);
>     this.currentUserDoc.submitJson0Op(op => op.add<string>(u => u.sites['sf'].projects, 'project04'), false);
>     this.waitForProjectDocChanges();
> ```

I see that in your throttling commit, you introduced this line, where there was no `this.wait()`. But this sort of method seems like something that would meaningfully benefit from a detectChanges() (such as via `this.wait()`), as being added to  a project should result in a change to the UI (such as a new project in the drop-down projects list). Do you think?



_Code quote:_
```XML
   this.waitForProjectDocChanges();
```

**Review by Nateowami — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1577)* status: 1 of 2 files reviewed, 5 unresolved discussions (waiting on @marksvc and @nigel-wells)

___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/app.component.ts` line 295 at r2](https://reviewable.io/reviews/sillsdev/web-xforge/1577#-NGI3JEJ-ZD3etlkdyKK:-NGIOUPYCimn1IfNAqr8:bvftvb2) ([raw file](https://github.com/sillsdev/web-xforge/blob/654adbb98dd09ef72bff2f4be68edd2bae2d01b2/src/SIL.XForge.Scripture/ClientApp/src/app/app.component.ts#L295)):*
<details><summary><i>Previously, marksvc wrote…</i></summary><blockquote>

Wow, it looks like this could make use of a serious if-inversion. 
</blockquote></details>

Good point. Probably this shouldn't be a conditional, but `await this.uponUserLoggedIn`.
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/app.component.ts` line 407 at r2](https://reviewable.io/reviews/sillsdev/web-xforge/1577#-NGI26LH9O_YYGIJQwkE:-NGIjkfJ44gBIre7MXP7:btugd1i) ([raw file](https://github.com/sillsdev/web-xforge/blob/654adbb98dd09ef72bff2f4be68edd2bae2d01b2/src/SIL.XForge.Scripture/ClientApp/src/app/app.component.ts#L407)):*
<details><summary><i>Previously, marksvc wrote…</i></summary><blockquote>

It seems like if there is a remote change and the current user is _no longer on the project_, then that user wouldn't have permission to _receive_ the remote change about it :-). 
</blockquote></details>

Yeah, that is kind of weird. It would be good to investigate this at some point.
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/app.component.ts` line 428 at r2](https://reviewable.io/reviews/sillsdev/web-xforge/1577#-NGI8QGv5LscGQWOI3hf:-NGIjx2d5VZjg0LKDxOq:b-5ired1) ([raw file](https://github.com/sillsdev/web-xforge/blob/654adbb98dd09ef72bff2f4be68edd2bae2d01b2/src/SIL.XForge.Scripture/ClientApp/src/app/app.component.ts#L428)):*
<details><summary><i>Previously, marksvc wrote…</i></summary><blockquote>

Previously, this code had a lambda saying `async projectId => await this...setCurrentProjectId(`. 
For my own understanding:  **In the context at hand** (where this is getting called from a subscribe), was the `await` without any influence on behaviour, and the behaviour would be the same without the `await`?



</blockquote></details>

As we discussed, I don't think it had any effect except possibly on stack traces.
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/app.component.ts` line 428 at r2](https://reviewable.io/reviews/sillsdev/web-xforge/1577#-NGII42P2A0ly4SSj5Y5:-NGIk35y62teSCcDqR4m:bbq2mkz) ([raw file](https://github.com/sillsdev/web-xforge/blob/654adbb98dd09ef72bff2f4be68edd2bae2d01b2/src/SIL.XForge.Scripture/ClientApp/src/app/app.component.ts#L428)):*
<details><summary><i>Previously, marksvc wrote…</i></summary><blockquote>

At present, the lambda has no `await`s in it, but we do specify the lambda as `async`. Is there any use or significance of specifying that the lambda is `async`? Is it going to be the same as if we omitted `async`?
</blockquote></details>

I just forgot to remove it. Fixed.
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/app.component.ts` line 430 at r2](https://reviewable.io/reviews/sillsdev/web-xforge/1577#-NGI3jbUC2h1-xvW0y1p:-NGIkAeeE2a8rYcB-M9D:b-o7dvvd) ([raw file](https://github.com/sillsdev/web-xforge/blob/654adbb98dd09ef72bff2f4be68edd2bae2d01b2/src/SIL.XForge.Scripture/ClientApp/src/app/app.component.ts#L430)):*
<details><summary><i>Previously, marksvc wrote…</i></summary><blockquote>

Hmm. I wonder if there would be any significance for a situation where a user is removed from their last SF project, that we set their current project id to null/undefined, instead of leaving it as the no-longer-really-valid id of the last project that they were on. 
Just thinking out loud. 

(This is not related to something your patch is doing.)
</blockquote></details>

As discussed on the call, I don't think this will really be an issue.
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/app.component.ts` line 556 at r2](https://reviewable.io/reviews/sillsdev/web-xforge/1577#-NGDv8QBAdSfvQDuSvRt:-NGIk8XI0VwRYSE_Ac3U:b-896fix) ([raw file](https://github.com/sillsdev/web-xforge/blob/654adbb98dd09ef72bff2f4be68edd2bae2d01b2/src/SIL.XForge.Scripture/ClientApp/src/app/app.component.ts#L556)):*
<details><summary><i>Previously, Nateowami (Nathaniel Paulus) wrote…</i></summary><blockquote>

Good point. I'll fix it.
</blockquote></details>

Done.
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/app.component.ts` line 557 at r2](https://reviewable.io/reviews/sillsdev/web-xforge/1577#-NGI4hOLA1L8cXxj0tUx:-NGIT73w-fN94OjruPrf:b5xdmrv) ([raw file](https://github.com/sillsdev/web-xforge/blob/654adbb98dd09ef72bff2f4be68edd2bae2d01b2/src/SIL.XForge.Scripture/ClientApp/src/app/app.component.ts#L557)):*
<details><summary><i>Previously, marksvc wrote…</i></summary><blockquote>

I'm so glad this had an API comment over in realtime-query.ts :-)
</blockquote></details>

Glad it was helpful.
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/app.component.ts` line 559 at r2](https://reviewable.io/reviews/sillsdev/web-xforge/1577#-NGI7QQK9mMfgZcnkHeL:-NGIVybiDrRy_NA-rBdy:b7nea0k) ([raw file](https://github.com/sillsdev/web-xforge/blob/654adbb98dd09ef72bff2f4be68edd2bae2d01b2/src/SIL.XForge.Scripture/ClientApp/src/app/app.component.ts#L559)):*
<details><summary><i>Previously, marksvc wrote…</i></summary><blockquote>

I think this could benefit from some throttling, because if I add 1000 questions to a project, then this might run 1000 times, each time iterating over all questions in the project and building the book number set (and so run the inner part of the loop  1000+999+998+...+1 times). This seems like something that could benefit from a debounce or throttling. Do you think?
Not that, as is, it's going to be slower than the previous version of the  code. 
</blockquote></details>

Well, possibly. At present adding questions is fairly slow, so debouncing wouldn't tend to do very much in my opinion. At present import speeds (which just increased dramatically due to these efficiency improvements), this would be firing an average of every 22ms when importing 1000 questions.

As a side note, the number of operations can be generalized as `(n*(n+1))/2`, so `(1000*(1000+1))/2` = 500,500. (I always forget the exact formula, and had way too much fun deriving it geometrically on paper). 

The checking overview component, on the other hand, is extraordinarily inefficient by comparison, sorting and filtering the question list many times _for every digest cycle_. It used to be much worse, because the number of digest cycles was out of control.
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/app.component.ts` line 582 at r2](https://reviewable.io/reviews/sillsdev/web-xforge/1577#-NGDw2mA6I-TbFwwPqH0:-NGIkHn95mbo-TC2h8zK:b68u1ng) ([raw file](https://github.com/sillsdev/web-xforge/blob/a9d7caa44f4d05df67cd7149c82dc83025f36989/src/SIL.XForge.Scripture/ClientApp/src/app/app.component.ts#L582)):*
<details><summary><i>Previously, nigel-wells (Nigel Wells) wrote…</i></summary><blockquote>

From a community checkers POV they only need the text for the books that have questions. Main consideration if we do all text is how much data that would download to a phone and if that would create an issue that they're unable to resolve on their own. I think go with minimal effort to achieve the same/similar functionality we already have as we'll no doubt address this more when we properly address offline support next year.
</blockquote></details>

Done. The new solution I came up with is hopefully temporary.
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/app.component.spec.ts` line 855 at r2](https://reviewable.io/reviews/sillsdev/web-xforge/1577#-NGIEfqS6BzeakWYBA2a:-NGIOO-CB5tOWndkuLOd:b1o9uzo) ([raw file](https://github.com/sillsdev/web-xforge/blob/a9d7caa44f4d05df67cd7149c82dc83025f36989/src/SIL.XForge.Scripture/ClientApp/src/app/app.component.spec.ts#L855)):*
<details><summary><i>Previously, marksvc wrote…</i></summary><blockquote>

I see that in your throttling commit, you introduced this line, where there was no `this.wait()`. But this sort of method seems like something that would meaningfully benefit from a detectChanges() (such as via `this.wait()`), as being added to  a project should result in a change to the UI (such as a new project in the drop-down projects list). Do you think?
</blockquote></details>

Yes, though it didn't appear to be necessary.

**Review by nigel-wells — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1577#-:-NGJ-PQR-0bhnUtK12pb:bnfp4nl)* status: all files reviewed, 5 unresolved discussions (waiting on @marksvc and @Nateowami)

___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/app.component.ts` line 559 at r2](https://reviewable.io/reviews/sillsdev/web-xforge/1577#-NGI7QQK9mMfgZcnkHeL:-NGIxQ1NB8fVyBoF4uYg:b3p2ilu) ([raw file](https://github.com/sillsdev/web-xforge/blob/654adbb98dd09ef72bff2f4be68edd2bae2d01b2/src/SIL.XForge.Scripture/ClientApp/src/app/app.component.ts#L559)):*
<details><summary><i>Previously, Nateowami (Nathaniel Paulus) wrote…</i></summary><blockquote>

Well, possibly. At present adding questions is fairly slow, so debouncing wouldn't tend to do very much in my opinion. At present import speeds (which just increased dramatically due to these efficiency improvements), this would be firing an average of every 22ms when importing 1000 questions.

As a side note, the number of operations can be generalized as `(n*(n+1))/2`, so `(1000*(1000+1))/2` = 500,500. (I always forget the exact formula, and had way too much fun deriving it geometrically on paper). 

The checking overview component, on the other hand, is extraordinarily inefficient by comparison, sorting and filtering the question list many times _for every digest cycle_. It used to be much worse, because the number of digest cycles was out of control.
</blockquote></details>

It's actually may be a bit more. My observation from testing is a change to a question (archiving and un-archiving) results in 2x remote changes. I haven't look closely at importing notes - I think it just triggered it once but I wasn't testing multiple browsers either. We could consider only setting/unsetting books but that may take more compute time then just clearing it out and adding them back in. What we could look for importing is some kind of "pause" on change events until the import is complete.
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/app.component.ts` line 582 at r2](https://reviewable.io/reviews/sillsdev/web-xforge/1577#-NGDw2mA6I-TbFwwPqH0:-NGIzjglCVNGmXtlu7Bl:b-u5wrpo) ([raw file](https://github.com/sillsdev/web-xforge/blob/a9d7caa44f4d05df67cd7149c82dc83025f36989/src/SIL.XForge.Scripture/ClientApp/src/app/app.component.ts#L582)):*
<details><summary><i>Previously, Nateowami (Nathaniel Paulus) wrote…</i></summary><blockquote>

Done. The new solution I came up with is hopefully temporary.
</blockquote></details>

Looks good and nice supporting comment.

**Review by Nateowami — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1577)* status: all files reviewed, 1 unresolved discussion (waiting on @nigel-wells)

___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/app.component.ts` line 582 at r2](https://reviewable.io/reviews/sillsdev/web-xforge/1577#-NGDw2mA6I-TbFwwPqH0:-NGN-COJ8UFkhTEqosSp:b-896fix) ([raw file](https://github.com/sillsdev/web-xforge/blob/a9d7caa44f4d05df67cd7149c82dc83025f36989/src/SIL.XForge.Scripture/ClientApp/src/app/app.component.ts#L582)):*
<details><summary><i>Previously, marksvc wrote…</i></summary><blockquote>

I am amused by "but for now it is" :)
</blockquote></details>

Done.

**Review by Nateowami — COMMENTED** [review]
> Dismissed @nigel-wells from a discussion.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1577)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @Nateowami)

**Pull request merged**
