### PR TITLE
SF-1844 Use SignalR for Sync Progress

### PR DESCRIPTION
**Pull request by pmachapman**
[SignalR](https://dotnet.microsoft.com/en-us/apps/aspnet/signalr) is included with ASP.NET 6.0, and is a cross-platform method of providing push notifications to clients. It is flexible, and can be scaled using Redis if SF was to grow beyond one server.

This PR
 * Changes the SF backend from updating `Sync.percentCompleted` with Paratext sync percentage updates to using a SignalR hub
 * Adds a project notification service utilizing SignalR to the frontend
 * Updates the Sync Progress component to use the new service (commit c8e17f5e181d09589f1d34c7115f656818c29adb)
 * Added more sync reporting of the different sync phases (commit 0d2c22cd8dc573803060f61cd352c2d08e4b9d4a)
 * Only shows indeterminate sync progress at the start of the sync (commit 258f4e9c190a66d528a9f21df1f80c8c123ace3d)

- - -
This change is [Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1654)

### CODE REVIEW

**Review by RaymondLuong3 — CHANGES_REQUESTED** [review]
My only complaint is that this makes our sync progress too beautiful. A Paratext user used to the cluncky-ness of the Paratext S/R progress experience may be surprised :exclamation: 

> Reviewed 20 of 20 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1654#-:-NLX9xzE5IRe1MfI7-ua:barcyc)* status: all files reviewed, 7 unresolved discussions (waiting on @pmachapman)

___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/connect-project/connect-project.component.spec.ts` line 559 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/1654#-NLWulI97Sq2xoDcVub8:-NLWulI97Sq2xoDcVub9:bndpxw7) ([raw file](https://github.com/sillsdev/web-xforge/blob/d74a427a7844e579d70a6efdc9339081e63316ad/src/SIL.XForge.Scripture/ClientApp/src/app/connect-project/connect-project.component.spec.ts#L559)):*
> ```XML
>   }
> 
>   emitSyncProgress(): void {
> ```

This might need to be renamed, like setQueuedCount. 



_Code quote:_
```XML
  emitSyncProgress(): void {
```
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/sync/sync.component.spec.ts` line 360 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/1654#-NLWwA6l92iMv1RKT3JW:-NLWwA6l92iMv1RKT3JX:bijpb0c) ([raw file](https://github.com/sillsdev/web-xforge/blob/d74a427a7844e579d70a6efdc9339081e63316ad/src/SIL.XForge.Scripture/ClientApp/src/app/sync/sync.component.spec.ts#L360)):*
> ```XML
>   }
> 
>   emitSyncProgress(projectId: string): void {
> ```

Similar to above.



_Code quote:_
```XML
  emitSyncProgress(projectId: string): void {
```
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/sync/sync-progress/sync-progress.component.ts` line 89 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/1654#-NLX1-ha-CvDMn0e5qAd:-NLX1-ha-CvDMn0e5qAe:b-enkywk) ([raw file](https://github.com/sillsdev/web-xforge/blob/d74a427a7844e579d70a6efdc9339081e63316ad/src/SIL.XForge.Scripture/ClientApp/src/app/sync/sync-progress/sync-progress.component.ts#L89)):*
> ```XML
>   }
> 
>   public updateProgressState(projectId: string, progressState: ProgressState) {
> ```

This could be simplified
```
const hasSourceProject = this.sourceProjectDoc?.data == null;
if (projectId === this._projectDoc?.id) {
  this.progressPercent = hasSourceProject ? 0.5 + progressState.progressValue * 0.5 : progressState.progressValue;
} else if (hasSourceProject && projectId === this.sourceProgjectDoc?.Id) {
this.progressPercent = progressState.progressValue * 0.5;
}
```
This should cover all the cases.



_Code quote:_
```XML
  public updateProgressState(projectId: string, progressState: ProgressState) {
    if (this.sourceProjectDoc?.data == null) {
      // There is no source project, so only check the target
      if (this._projectDoc?.id === projectId) {
        this.progressPercent = progressState.progressValue;
      }
    } else {
```
___
*[`src/SIL.XForge.Scripture/Services/NotificationHub.cs` line 12 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/1654#-NLX9oIE1uoAW-1Qf5ip:-NLX9oIE1uoAW-1Qf5iq:bh56cnm) ([raw file](https://github.com/sillsdev/web-xforge/blob/d74a427a7844e579d70a6efdc9339081e63316ad/src/SIL.XForge.Scripture/Services/NotificationHub.cs#L12)):*
> ```Smalltalk
>             await Clients.Group(projectId).NotifySyncProgress(projectId, progressState);
> 
>         public async Task SubscribeToProject(string projectId) =>
> ```

Where is this used? Or is it just to implement INotifier?



_Code quote:_
```Smalltalk
        public async Task SubscribeToProject(string projectId) =>
```
___
*[`src/SIL.XForge.Scripture/Services/ParatextSyncRunner.cs` line 514 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/1654#-NLX5-yGEXXMq90TwImq:-NLX5-yGEXXMq90TwImr:b-4rwup7) ([raw file](https://github.com/sillsdev/web-xforge/blob/d74a427a7844e579d70a6efdc9339081e63316ad/src/SIL.XForge.Scripture/Services/ParatextSyncRunner.cs#L514)):*
> ```Smalltalk
>             {
>                 i++;
>                 await NotifySyncProgress(SyncPhase.Phase5, i / targetBooks.Count);
> ```

It is worth moving this into the main RunAsync Method, so if this ever gets called in a different order, it doesn't get the sync phases messed up.



_Code quote:_
```Smalltalk
                await NotifySyncProgress(SyncPhase.Phase5, i / targetBooks.Count);
```
___
*[`src/SIL.XForge.Scripture/Services/ParatextSyncRunner.cs` line 1618 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/1654#-NLX9PhQ2YIsfUSQ3w1h:-NLX9PhQ2YIsfUSQ3w1i:bf7i00u) ([raw file](https://github.com/sillsdev/web-xforge/blob/d74a427a7844e579d70a6efdc9339081e63316ad/src/SIL.XForge.Scripture/Services/ParatextSyncRunner.cs#L1618)):*
> ```Smalltalk
>         }
> 
>         private enum SyncPhase
> ```

I'm not sure this is the best place to put this enum, but I'm not sure of a better place to put this.



_Code quote:_
```Smalltalk
        private enum SyncPhase
```
___
*[`src/SIL.XForge.Scripture/Services/ParatextSyncRunner.cs` line 1620 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/1654#-NLX6HCH2gBOLnp_kdYt:-NLX6HCH2gBOLnp_kdYu:b9gpa8a) ([raw file](https://github.com/sillsdev/web-xforge/blob/d74a427a7844e579d70a6efdc9339081e63316ad/src/SIL.XForge.Scripture/Services/ParatextSyncRunner.cs#L1620)):*
> ```Smalltalk
>         private enum SyncPhase
>         {
>             Phase1 = 0, // Initial methods
> ```

Did you mean for the first phase to have a value of 0? This would mean that any progress in phase 1 would like like no progress. Actually, this does look correct, I see that the phase forms the base value of the sync with the progress added onto it.



_Code quote:_
```Smalltalk
            Phase1 = 0, // Initial methods
```

**Review by pmachapman — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1654)* status: 15 of 20 files reviewed, 7 unresolved discussions (waiting on @RaymondLuong3)

___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/connect-project/connect-project.component.spec.ts` line 559 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/1654#-NLWulI97Sq2xoDcVub8:-NLXgPyo4oiH-a4mm3g_:b1ye1zv) ([raw file](https://github.com/sillsdev/web-xforge/blob/d74a427a7844e579d70a6efdc9339081e63316ad/src/SIL.XForge.Scripture/ClientApp/src/app/connect-project/connect-project.component.spec.ts#L559)):*
<details><summary><i>Previously, RaymondLuong3 (Raymond Luong) wrote…</i></summary><blockquote>

This might need to be renamed, like setQueuedCount. 
</blockquote></details>

Great idea - done!
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/sync/sync.component.spec.ts` line 360 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/1654#-NLWwA6l92iMv1RKT3JW:-NLXgS2R624eW8D-iisM:b-a2ujfl) ([raw file](https://github.com/sillsdev/web-xforge/blob/d74a427a7844e579d70a6efdc9339081e63316ad/src/SIL.XForge.Scripture/ClientApp/src/app/sync/sync.component.spec.ts#L360)):*
<details><summary><i>Previously, RaymondLuong3 (Raymond Luong) wrote…</i></summary><blockquote>

Similar to above.
</blockquote></details>

Changed.
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/sync/sync-progress/sync-progress.component.ts` line 89 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/1654#-NLX1-ha-CvDMn0e5qAd:-NLXm08b5944eCRELXgU:bltuuzg) ([raw file](https://github.com/sillsdev/web-xforge/blob/d74a427a7844e579d70a6efdc9339081e63316ad/src/SIL.XForge.Scripture/ClientApp/src/app/sync/sync-progress/sync-progress.component.ts#L89)):*
<details><summary><i>Previously, RaymondLuong3 (Raymond Luong) wrote…</i></summary><blockquote>

This could be simplified
```
const hasSourceProject = this.sourceProjectDoc?.data == null;
if (projectId === this._projectDoc?.id) {
  this.progressPercent = hasSourceProject ? 0.5 + progressState.progressValue * 0.5 : progressState.progressValue;
} else if (hasSourceProject && projectId === this.sourceProgjectDoc?.Id) {
this.progressPercent = progressState.progressValue * 0.5;
}
```
This should cover all the cases.
</blockquote></details>

Thank you so much for this! I spent time trying to optimize it, but kept introducing bugs, and then settling on commenting over the code smell. Thanks!
___
*[`src/SIL.XForge.Scripture/Services/NotificationHub.cs` line 12 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/1654#-NLX9oIE1uoAW-1Qf5ip:-NLXmYAtCkVWHzoMwI-9:b-l8rg72) ([raw file](https://github.com/sillsdev/web-xforge/blob/d74a427a7844e579d70a6efdc9339081e63316ad/src/SIL.XForge.Scripture/Services/NotificationHub.cs#L12)):*
<details><summary><i>Previously, RaymondLuong3 (Raymond Luong) wrote…</i></summary><blockquote>

Where is this used? Or is it just to implement INotifier?
</blockquote></details>

It is called only by the frontend project-notification.service.ts. Any public methods in a `Hub` will be exposed to the frontend over SignalR.

I only strongly typed it to `INotifier` to help reduce any typo related errors in the C# side of things.

The C# backend does not need to call it, as it does not need to subscribe to its own notifications.
___
*[`src/SIL.XForge.Scripture/Services/ParatextSyncRunner.cs` line 514 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/1654#-NLX5-yGEXXMq90TwImq:-NLXp5sJ7G-40_bqHJ8M:bsxi14s) ([raw file](https://github.com/sillsdev/web-xforge/blob/d74a427a7844e579d70a6efdc9339081e63316ad/src/SIL.XForge.Scripture/Services/ParatextSyncRunner.cs#L514)):*
<details><summary><i>Previously, RaymondLuong3 (Raymond Luong) wrote…</i></summary><blockquote>

It is worth moving this into the main RunAsync Method, so if this ever gets called in a different order, it doesn't get the sync phases messed up.
</blockquote></details>

Good thinking. I have made the Phase value a parameter of `UpdateDocsAsync`, as I think that will help with clarity, and hopefully stop the phase order being inadvertently jumbled, while keeping the per-book phase increments. It is OK for phases to be skipped (the progress bar will just jump a bit bigger than normal, which the user won't mind).
___
*[`src/SIL.XForge.Scripture/Services/ParatextSyncRunner.cs` line 1618 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/1654#-NLX9PhQ2YIsfUSQ3w1h:-NLXnjLx6ttmRnw3el11:b-nheywu) ([raw file](https://github.com/sillsdev/web-xforge/blob/d74a427a7844e579d70a6efdc9339081e63316ad/src/SIL.XForge.Scripture/Services/ParatextSyncRunner.cs#L1618)):*
<details><summary><i>Previously, RaymondLuong3 (Raymond Luong) wrote…</i></summary><blockquote>

I'm not sure this is the best place to put this enum, but I'm not sure of a better place to put this.
</blockquote></details>

Same - I agonize over this, settling on a `private enum` here because it is besides a `private class`, and this `enum` is not used by any other code. I am very open to ideas.
___
*[`src/SIL.XForge.Scripture/Services/ParatextSyncRunner.cs` line 1620 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/1654#-NLX6HCH2gBOLnp_kdYt:-NLXnxJc5QwnnqTqHjyT:b-psz9p3) ([raw file](https://github.com/sillsdev/web-xforge/blob/d74a427a7844e579d70a6efdc9339081e63316ad/src/SIL.XForge.Scripture/Services/ParatextSyncRunner.cs#L1620)):*
<details><summary><i>Previously, RaymondLuong3 (Raymond Luong) wrote…</i></summary><blockquote>

Did you mean for the first phase to have a value of 0? This would mean that any progress in phase 1 would like like no progress. Actually, this does look correct, I see that the phase forms the base value of the sync with the progress added onto it.
</blockquote></details>

Yes, this is a hard one.

I was going to start it at 1 (and adjust `NotifySyncProgress` to suit), but according to C# recommendations, an `enum` should start at 0.

I next thought of creating a `None` value for the `enum`, but it would not be used and just be for completion's sake.

I then thought of just not showing the numbers (which would still work perfectly, as these values are all the same as their implied numbers), but then I felt that a programmer might not understand what I was doing in `NotifySyncProgress()` then.

I also thought of naming the `enum` members descriptively, like `SyncPhase.InitialMethods`, but that would likely lead to the phases being used out of order (as happened to me when testing this option), and so not updating the frontend correctly. From testing this option though, I did stop the frontend progress bar jumping around by making it drop values that are less than the current value.

I finally settled on the comments and explicit values in the hope that despite its initial code smell. I have added some more documentation to the `enum` to try hopefully make the reasoning clearer.

Also, I have just refactored the maximum phase number to be calculated as a `static double`, as I think if the number of phases changes, a developer might forget to update this.

**Review by RaymondLuong3 — CHANGES_REQUESTED** [review]
Just a couple more minor changes.

> Reviewed 5 of 5 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1654#-:-NLY-fr06v-v4dZtKk5c:bz2a967)* status: all files reviewed, 3 unresolved discussions (waiting on @pmachapman)

___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/sync/sync-progress/sync-progress.component.ts` line 89 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/1654#-NLX1-ha-CvDMn0e5qAd:-NLXzRTDAX1wRsgQIj4E:byhrpj3) ([raw file](https://github.com/sillsdev/web-xforge/blob/d74a427a7844e579d70a6efdc9339081e63316ad/src/SIL.XForge.Scripture/ClientApp/src/app/sync/sync-progress/sync-progress.component.ts#L89)):*
<details><summary><i>Previously, pmachapman (Peter Chapman) wrote…</i></summary><blockquote>

Thank you so much for this! I spent time trying to optimize it, but kept introducing bugs, and then settling on commenting over the code smell. Thanks!
</blockquote></details>

Glad that it helped.
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/sync/sync-progress/sync-progress.component.spec.ts` line 236 at r2](https://reviewable.io/reviews/sillsdev/web-xforge/1654#-NLXzhwW2mzLnOD7m_f-:-NLXzhwW2mzLnOD7m_f0:b94bpbb) ([raw file](https://github.com/sillsdev/web-xforge/blob/acf00f1138785a2e040cf2473d3dbd70b5d349bf/src/SIL.XForge.Scripture/ClientApp/src/app/sync/sync-progress/sync-progress.component.spec.ts#L236)):*
> ```XML
>   }
> 
>   setQueuedCount(percentCompleted: number, projectId: string): void {
> ```

Actually, in this instance emitSyncProgress() is accurate. Or better yet, updateProgress() would be good.



_Code quote:_
```XML
 setQueuedCount(percentCompleted: number, projectId: string): void {
```
___
*[`src/SIL.XForge.Scripture/Services/NotificationHub.cs` line 12 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/1654#-NLX9oIE1uoAW-1Qf5ip:-NLY-5xq5jJC-8_mKqhy:b-1hh72o) ([raw file](https://github.com/sillsdev/web-xforge/blob/d74a427a7844e579d70a6efdc9339081e63316ad/src/SIL.XForge.Scripture/Services/NotificationHub.cs#L12)):*
<details><summary><i>Previously, pmachapman (Peter Chapman) wrote…</i></summary><blockquote>

It is called only by the frontend project-notification.service.ts. Any public methods in a `Hub` will be exposed to the frontend over SignalR.

I only strongly typed it to `INotifier` to help reduce any typo related errors in the C# side of things.

The C# backend does not need to call it, as it does not need to subscribe to its own notifications.
</blockquote></details>

Nice, could you add a comment here to describe that, so that it is clear in the future.
___
*[`src/SIL.XForge.Scripture/Services/ParatextSyncRunner.cs` line 514 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/1654#-NLX5-yGEXXMq90TwImq:-NLY-N302Ad7Mo07Rlzy:b-mbcpfk) ([raw file](https://github.com/sillsdev/web-xforge/blob/d74a427a7844e579d70a6efdc9339081e63316ad/src/SIL.XForge.Scripture/Services/ParatextSyncRunner.cs#L514)):*
<details><summary><i>Previously, pmachapman (Peter Chapman) wrote…</i></summary><blockquote>

Good thinking. I have made the Phase value a parameter of `UpdateDocsAsync`, as I think that will help with clarity, and hopefully stop the phase order being inadvertently jumbled, while keeping the per-book phase increments. It is OK for phases to be skipped (the progress bar will just jump a bit bigger than normal, which the user won't mind).
</blockquote></details>

Good thinking.
___
*[`src/SIL.XForge.Scripture/Services/ParatextSyncRunner.cs` line 1620 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/1654#-NLX6HCH2gBOLnp_kdYt:-NLY-_JO2afxAcfzNaNn:b-nsxxgz) ([raw file](https://github.com/sillsdev/web-xforge/blob/d74a427a7844e579d70a6efdc9339081e63316ad/src/SIL.XForge.Scripture/Services/ParatextSyncRunner.cs#L1620)):*
<details><summary><i>Previously, pmachapman (Peter Chapman) wrote…</i></summary><blockquote>

Yes, this is a hard one.

I was going to start it at 1 (and adjust `NotifySyncProgress` to suit), but according to C# recommendations, an `enum` should start at 0.

I next thought of creating a `None` value for the `enum`, but it would not be used and just be for completion's sake.

I then thought of just not showing the numbers (which would still work perfectly, as these values are all the same as their implied numbers), but then I felt that a programmer might not understand what I was doing in `NotifySyncProgress()` then.

I also thought of naming the `enum` members descriptively, like `SyncPhase.InitialMethods`, but that would likely lead to the phases being used out of order (as happened to me when testing this option), and so not updating the frontend correctly. From testing this option though, I did stop the frontend progress bar jumping around by making it drop values that are less than the current value.

I finally settled on the comments and explicit values in the hope that despite its initial code smell. I have added some more documentation to the `enum` to try hopefully make the reasoning clearer.

Also, I have just refactored the maximum phase number to be calculated as a `static double`, as I think if the number of phases changes, a developer might forget to update this.
</blockquote></details>

Ah good thinking about setting the phase number to a variable. Nice work.

**Review by pmachapman — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1654)* status: all files reviewed, 2 unresolved discussions (waiting on @RaymondLuong3)

___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/sync/sync-progress/sync-progress.component.spec.ts` line 236 at r2](https://reviewable.io/reviews/sillsdev/web-xforge/1654#-NLXzhwW2mzLnOD7m_f-:-NLY2Ptj3lBq5IlwiRxt:b-kljuy) ([raw file](https://github.com/sillsdev/web-xforge/blob/acf00f1138785a2e040cf2473d3dbd70b5d349bf/src/SIL.XForge.Scripture/ClientApp/src/app/sync/sync-progress/sync-progress.component.spec.ts#L236)):*
<details><summary><i>Previously, RaymondLuong3 (Raymond Luong) wrote…</i></summary><blockquote>

Actually, in this instance emitSyncProgress() is accurate. Or better yet, updateProgress() would be good.
</blockquote></details>

Global find/replace tricked me! Changed to `updateSyncProgress()` as it isn't really emitting.
___
*[`src/SIL.XForge.Scripture/Services/NotificationHub.cs` line 12 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/1654#-NLX9oIE1uoAW-1Qf5ip:-NLY3SKnBmmDWFljKqOX:bcvjgzc) ([raw file](https://github.com/sillsdev/web-xforge/blob/d74a427a7844e579d70a6efdc9339081e63316ad/src/SIL.XForge.Scripture/Services/NotificationHub.cs#L12)):*
<details><summary><i>Previously, RaymondLuong3 (Raymond Luong) wrote…</i></summary><blockquote>

Nice, could you add a comment here to describe that, so that it is clear in the future.
</blockquote></details>

Good idea. Done!

**Review by RaymondLuong3 — APPROVED** [review]
:lgtm: 

> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1654#-:-NLvX5AG4YpJrt4Q28Hx:bg7igkv)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @pmachapman)

___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/sync/sync-progress/sync-progress.component.spec.ts` line 236 at r2](https://reviewable.io/reviews/sillsdev/web-xforge/1654#-NLXzhwW2mzLnOD7m_f-:-NLvWo83BHrQcJ0151IN:brolbgu) ([raw file](https://github.com/sillsdev/web-xforge/blob/acf00f1138785a2e040cf2473d3dbd70b5d349bf/src/SIL.XForge.Scripture/ClientApp/src/app/sync/sync-progress/sync-progress.component.spec.ts#L236)):*
<details><summary><i>Previously, pmachapman (Peter Chapman) wrote…</i></summary><blockquote>

Global find/replace tricked me! Changed to `updateSyncProgress()` as it isn't really emitting.
</blockquote></details>

That does happen every now and then.

**Review by Nateowami — COMMENTED** [review]
@RaymondLuong3 
> My only complaint is that this makes our sync progress too beautiful. A Paratext user used to the cluncky-ness of the Paratext S/R progress experience may be surprised ❗

I'm a bit confused. I thought this was merely a change to the technical implementation and doesn't change anything user-facing? Perhaps you've been seeing some things that are non-ideal from a UX perspective that I've missed?

@pmachapman 
This is great. Might we use SignalR for the training progress as well? I think it currently uses polling?

> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1654#-:-NM1dWNJ4HsXv5RGbXjR:b-24mymi)* status: 19 of 20 files reviewed, all discussions resolved (waiting on @RaymondLuong3)

**Review by pmachapman — COMMENTED** [review]
@Nateowami I think it might be possible to do this once #1626 and #1662 are merged, and the in-process Machine is removed from SF.

I think the most practical way to do that would by to use the Machine API's webhooks to start a worker in SF that does the polling of the Machine API, and reports progress via SignalR to an updated `RemoteTranslationEngine`. This would also help reduce traffic to the Machine API server when more than one user has a project open that is currently in training.

Alternatively, if the Machine API implemented SignalR, SF could subscribe to them and relay the notifications to the web client(s).

Another way if SF and the Machine API are in the same datacenter, they might be able share a Redis backplane for SignalR (I haven't investigated this last idea too much...just hypothesizing).

> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1654#-:-NM5bsnkBlbAPVZHU-Lv:b2ysu9h)* status: 19 of 20 files reviewed, all discussions resolved (waiting on @RaymondLuong3)

**Pull request merged**
