### PR TITLE
SF-1167 Prevent import dialog from opening multiple times

### PR DESCRIPTION
**Pull request by RaymondLuong3**
* also SF-1206 show connecting state immediately on clicking connect on connect project page
* adjust sync progress component to initialize when a project doc is provide

---
This change is [Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/952)

### CODE REVIEW

**Review by irahopkinson — CHANGES_REQUESTED** [review]
> Reviewed 5 of 5 files at r1.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/952)* status: all files reviewed, 1 unresolved discussion (waiting on @RaymondLuong3)

___
*[src/SIL.XForge.Scripture/ClientApp/src/app/connect-project/connect-project.component.ts, line 89 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/952#-MTKN-53-bZKkN49jYHZ:-MTKN-53-bZKkN49jYH_:b-bvk93e) ([raw file](https://github.com/sillsdev/web-xforge/blob/228fe01ffe57e163067aa86763647d441c25a58e/src/SIL.XForge.Scripture/ClientApp/src/app/connect-project/connect-project.component.ts#L89)):*
> ```
> submitDisabled()
> ```
I realise this is perpetuating an existing problem and you are trying to improve it but this could just be moving this in the wrong direction. Please read **3.6.3 Forms** of our Func Spec and let me know what you think. If you don't think this applies here, perhaps you could let me know why. I also appreciate that you went looking for similar issues even though this is outside of the scope of SF-1167.

**Review by Nateowami — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/952)* status: all files reviewed, 1 unresolved discussion (waiting on @irahopkinson)

___
*[src/SIL.XForge.Scripture/ClientApp/src/app/connect-project/connect-project.component.ts, line 89 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/952#-MTKN-53-bZKkN49jYHZ:-MTMNJJ31Ycp5WQoxj1S:b-cabf3r) ([raw file](https://github.com/sillsdev/web-xforge/blob/228fe01ffe57e163067aa86763647d441c25a58e/src/SIL.XForge.Scripture/ClientApp/src/app/connect-project/connect-project.component.ts#L89)):*
<details><summary><i>Previously, irahopkinson (Ira Hopkinson) wrote…</i></summary><blockquote>

> ```
> submitDisabled()
> ```
I realise this is perpetuating an existing problem and you are trying to improve it but this could just be moving this in the wrong direction. Please read **3.6.3 Forms** of our Func Spec and let me know what you think. If you don't think this applies here, perhaps you could let me know why. I also appreciate that you went looking for similar issues even though this is outside of the scope of SF-1167.
</blockquote></details>

I don't think it applies here.

- If we detect that the user is offline, the submit button is disabled and an error message is shown indicating that the user is offline ("Please connect to the internet to enable connecting to a project").
- If the button has already been clicked, then we definitely don't want clicking it again to duplicate the action (It looks to me like there is a small delay before showing progress connecting. This seems wrong to me. I suspect it may be waiting for a network response).
- If there are no connectable projects, then there is a message that says "Looks like there are no connectable projects for you. Please go to Paratext to register a project to connect to." The submit button is then present, but disabled. There's no form fields though, so the submit button seems completely superfluous.

**Review by RaymondLuong3 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/952)* status: all files reviewed, 1 unresolved discussion (waiting on @irahopkinson)

___
*[src/SIL.XForge.Scripture/ClientApp/src/app/connect-project/connect-project.component.ts, line 89 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/952#-MTKN-53-bZKkN49jYHZ:-MTN3tsj5fzwZinJlquz:b9uq0qw) ([raw file](https://github.com/sillsdev/web-xforge/blob/228fe01ffe57e163067aa86763647d441c25a58e/src/SIL.XForge.Scripture/ClientApp/src/app/connect-project/connect-project.component.ts#L89)):*
<details><summary><i>Previously, Nateowami (Nathaniel Paulus) wrote…</i></summary><blockquote>

I don't think it applies here.

- If we detect that the user is offline, the submit button is disabled and an error message is shown indicating that the user is offline ("Please connect to the internet to enable connecting to a project").
- If the button has already been clicked, then we definitely don't want clicking it again to duplicate the action (It looks to me like there is a small delay before showing progress connecting. This seems wrong to me. I suspect it may be waiting for a network response).
- If there are no connectable projects, then there is a message that says "Looks like there are no connectable projects for you. Please go to Paratext to register a project to connect to." The submit button is then present, but disabled. There's no form fields though, so the submit button seems completely superfluous. 
</blockquote></details>

I think I'll take another look at this. Potentially there is an easy way to go right to the "connecting" state without the delay from the network requests.

**Review by irahopkinson — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/952)* status: all files reviewed, 2 unresolved discussions (waiting on @irahopkinson and @RaymondLuong3)

___
*[src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking-overview/checking-overview.component.ts, line 339 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/952#-MT_GoIt2nGJkxiRJ_tQ:-MT_GoIt2nGJkxiRJ_tR:b-rdrl0q) ([raw file](https://github.com/sillsdev/web-xforge/blob/228fe01ffe57e163067aa86763647d441c25a58e/src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking-overview/checking-overview.component.ts#L339)):*
> ```
> questionDialog
> ```
Curiously this dialog doesn't have the same issue and doesn't need to set a boolean when the dialog is open. Can you see why this is different?

**Review by RaymondLuong3 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/952)* status: all files reviewed, 2 unresolved discussions (waiting on @irahopkinson)

___
*[src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking-overview/checking-overview.component.ts, line 339 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/952#-MT_GoIt2nGJkxiRJ_tQ:-MTfXSoG9d1gbeJ39S8q:b-jw2u7e) ([raw file](https://github.com/sillsdev/web-xforge/blob/228fe01ffe57e163067aa86763647d441c25a58e/src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking-overview/checking-overview.component.ts#L339)):*
<details><summary><i>Previously, irahopkinson (Ira Hopkinson) wrote…</i></summary><blockquote>

> ```
> questionDialog
> ```
Curiously this dialog doesn't have the same issue and doesn't need to set a boolean when the dialog is open. Can you see why this is different?
</blockquote></details>

Yes, it appears that it was on purpose that the import dialog does not focus the first focusable element, but every other dialog I looked at will, by default, the first element. So only the import dialog shows this kind of behaviour.

**Review by Nateowami — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/952)* status: all files reviewed, 2 unresolved discussions (waiting on @irahopkinson and @RaymondLuong3)

___
*[src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking-overview/checking-overview.component.ts, line 339 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/952#-MT_GoIt2nGJkxiRJ_tQ:-MTgFMQy7hrW_yxDlMbW:b3udihl) ([raw file](https://github.com/sillsdev/web-xforge/blob/228fe01ffe57e163067aa86763647d441c25a58e/src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking-overview/checking-overview.component.ts#L339)):*
<details><summary><i>Previously, RaymondLuong3 (Raymond Luong) wrote…</i></summary><blockquote>

Yes, it appears that it was on purpose that the import dialog does not focus the first focusable element, but every other dialog I looked at will, by default, the first element. So only the import dialog shows this kind of behaviour.
</blockquote></details>

@raymondluong3 I can't remember why I set it to not focus. Typically the reason for that would be because it was automatically focusing the first focusable element, and it picked the wrong one, or it was unhelpful to focus it. It didn't occur to me that not auto focusing would cause the button in the background to be in focus. When I remove the `autoFocus: false` everything seems to still work as intended.

Previously we had some issues with the autofocus focusing the wrong element in the question dialog (the little dropdown icon in the first input had focus). Perhaps because of that I opted to just not focus the dialog. We can probably change that now.

**Review by irahopkinson — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/952)* status: all files reviewed, 2 unresolved discussions (waiting on @irahopkinson, @Nateowami, and @RaymondLuong3)

___
*[src/SIL.XForge.Scripture/ClientApp/src/app/connect-project/connect-project.component.ts, line 89 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/952#-MTKN-53-bZKkN49jYHZ:-MTk92Z167kMg_ygf4fs:b7qs6f) ([raw file](https://github.com/sillsdev/web-xforge/blob/228fe01ffe57e163067aa86763647d441c25a58e/src/SIL.XForge.Scripture/ClientApp/src/app/connect-project/connect-project.component.ts#L89)):*
<details><summary><i>Previously, RaymondLuong3 (Raymond Luong) wrote…</i></summary><blockquote>

I think I'll take another look at this. Potentially there is an easy way to go right to the "connecting" state without the delay from the network requests.
</blockquote></details>

@raymondluong3 have you looked into this yet?

**Review by RaymondLuong3 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/952)* status: 1 of 6 files reviewed, 1 unresolved discussion (waiting on @irahopkinson)

___
*[src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking-overview/checking-overview.component.ts, line 339 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/952#-MT_GoIt2nGJkxiRJ_tQ:-MTlelw_720jVogM3Zus:b-cdfcvj) ([raw file](https://github.com/sillsdev/web-xforge/blob/228fe01ffe57e163067aa86763647d441c25a58e/src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking-overview/checking-overview.component.ts#L339)):*
<details><summary><i>Previously, Nateowami (Nathaniel Paulus) wrote…</i></summary><blockquote>

@raymondluong3 I can't remember why I set it to not focus. Typically the reason for that would be because it was automatically focusing the first focusable element, and it picked the wrong one, or it was unhelpful to focus it. It didn't occur to me that not auto focusing would cause the button in the background to be in focus. When I remove the `autoFocus: false` everything seems to still work as intended.

Previously we had some issues with the autofocus focusing the wrong element in the question dialog (the little dropdown icon in the first input had focus). Perhaps because of that I opted to just not focus the dialog. We can probably change that now.
</blockquote></details>

Good to know. I tested this too and the autofocus doesn't do anything funky.
___
*[src/SIL.XForge.Scripture/ClientApp/src/app/connect-project/connect-project.component.ts, line 89 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/952#-MTKN-53-bZKkN49jYHZ:-MTleu6s4xMQKlrCDIoT:b8hpuao) ([raw file](https://github.com/sillsdev/web-xforge/blob/228fe01ffe57e163067aa86763647d441c25a58e/src/SIL.XForge.Scripture/ClientApp/src/app/connect-project/connect-project.component.ts#L89)):*
<details><summary><i>Previously, irahopkinson (Ira Hopkinson) wrote…</i></summary><blockquote>

@raymondluong3 have you looked into this yet?
</blockquote></details>

I made some changes so that the sync progress component can handle being created before a project doc is available. So there is no longer a need to disable the submit button in this case.

**Review by irahopkinson — APPROVED** [review]
:lgtm: thanks for working that through - a much cleaner solution.

> Reviewed 5 of 6 files at r2.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/952#-:-MToJGRO50ZRBa5XeviN:bdd12o)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
