### PR TITLE
SF-1074 Proceed as Paratext user if account exists

### PR DESCRIPTION
**Pull request by RaymondLuong3**
There are issues that arise when a user tries to log in with Paratext on the connect project page and the Paratext account is already linked to an existing auth0 profile. This fix prevents users from linking to a Paratext account if this is the case, and allows the user to proceed using the auth0 account that was linked to Paratext.

Ideally, the user would be told that they cannot link accounts, and back out. But looking at the [auth0](url) documentation, there is no way to back out once a user tries to log in with Paratext and succeeds. Auth0 no longer acknowledges the previous user, and we are stuck as the Paratext user.

Paratext_account_linking

---
This change is [Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/931)

### CODE REVIEW

**Review by marksvc — CHANGES_REQUESTED** [review]
> Reviewed 2 of 5 files at r1.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/931)* status: 2 of 5 files reviewed, 1 unresolved discussion (waiting on @RaymondLuong3)

___
*[src/SIL.XForge/Services/UserService.cs, line 174 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/931#-MSF2F0f2wllKvRgOi44:-MSF2F0gCQGEmBvuS18T:bg97cva) ([raw file](https://github.com/sillsdev/web-xforge/blob/bf88606ea119c84f36a5bc861836e1a038954c63/src/SIL.XForge/Services/UserService.cs#L174)):*
> ```Smalltalk
>         {
>             JObject userProfile = JObject.Parse(await _authService.GetUserAsync(authId));
>             if (!((string)userProfile["user_id"]).Contains("paratext"))
> ```

So maybe the comment above this line could say 
```cs 
// Is `authId`'s primary identity just a SF login? This would mean that `authId` has 
// a secondary identity of a Paratext account, which means that Paratext 
// account is already linked to an existing SF account.
```

**Review by marksvc — CHANGES_REQUESTED** [review]
> Reviewed 1 of 5 files at r1.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/931)* status: 3 of 5 files reviewed, 2 unresolved discussions (waiting on @RaymondLuong3)

___
*[src/SIL.XForge.Scripture/ClientApp/src/xforge-common/auth.service.ts, line 259 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/931#-MSF4ZOuCxv5gEt3nCSK:-MSF4ZOuCxv5gEt3nCSL:b-acfclm) ([raw file](https://github.com/sillsdev/web-xforge/blob/bf88606ea119c84f36a5bc861836e1a038954c63/src/SIL.XForge.Scripture/ClientApp/src/xforge-common/auth.service.ts#L259)):*
> ```XML
>       } catch (err) {
>         if (!(err.message as string).includes(PARATEXT_ACCOUNT_ALREADY_LINKED)) {
>           console.error(err);
> ```

Hmm. I would have thought we would re-throw the error here, or at least report it to bug snag. But I see that this is the pattern in the rest of the method.
___
*[src/SIL.XForge.Scripture/ClientApp/src/xforge-common/auth.service.ts, line 276 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/931#-MSF5LZYEzOBaxE8lnhy:-MSF5LZYEzOBaxE8lnhz:b-rvwp8h) ([raw file](https://github.com/sillsdev/web-xforge/blob/bf88606ea119c84f36a5bc861836e1a038954c63/src/SIL.XForge.Scripture/ClientApp/src/xforge-common/auth.service.ts#L276)):*
> ```XML
>             }
>             this.handleOnlineAuth(parsedHash);
>             this.locationService.go(this.locationService.origin + this.locationService.pathname);
> ```

Ok and so the comment here might say something like
// Re-navigate to this page for the new current user id to take effect.

Oh wait, would it be possible to do something like call this.localLogIn() instead?

**Review by marksvc — CHANGES_REQUESTED** [review]
I approve, minus comments.

> Reviewed 2 of 5 files at r1.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/931#-:-MSF89FA3Bqod9mEhTfQ:b3oek9x)* status: all files reviewed, 4 unresolved discussions (waiting on @RaymondLuong3)

___
*[test/SIL.XForge.Tests/Services/UserServiceTests.cs, line 93 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/931#-MSF7L8PCppzZgaGxCXH:-MSF7L8PCppzZgaGxCXI:b-blnzpy) ([raw file](https://github.com/sillsdev/web-xforge/blob/bf88606ea119c84f36a5bc861836e1a038954c63/test/SIL.XForge.Tests/Services/UserServiceTests.cs#L93)):*
> ```
> auth03
> ```
I guess maybe this line wasn't as important if it didn't cause a problem doing this :)
But it might be; let's adjust it by changing 'auth03' to 'paratext|paratext01'
(I think is what it should be?)
___
*[test/SIL.XForge.Tests/Services/UserServiceTests.cs, line 98 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/931#-MSF6rX2B5NpEXq0sulL:-MSF6rX2B5NpEXq0sulM:beyoceb) ([raw file](https://github.com/sillsdev/web-xforge/blob/bf88606ea119c84f36a5bc861836e1a038954c63/test/SIL.XForge.Tests/Services/UserServiceTests.cs#L98)):*
> ```Smalltalk
>             JObject ptProfile = env.CreateUserProfile("newPtProfile", "paratext|paratext01", env.IssuedAt);
>             env.AuthService.GetUserAsync("paratext|paratext01").Returns(Task.FromResult(ptProfile.ToString()));
>             Console.WriteLine("Link Account");
> ```

(oops)

**Review by RaymondLuong3 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/931)* status: 2 of 5 files reviewed, 4 unresolved discussions (waiting on @marksvc)

___
*[src/SIL.XForge/Services/UserService.cs, line 174 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/931#-MSF2F0f2wllKvRgOi44:-MSFWwKA9nS3j7EyTGiU:b-nrezy5) ([raw file](https://github.com/sillsdev/web-xforge/blob/bf88606ea119c84f36a5bc861836e1a038954c63/src/SIL.XForge/Services/UserService.cs#L174)):*
<details><summary><i>Previously, marksvc wrote…</i></summary><blockquote>

So maybe the comment above this line could say 
```cs 
// Is `authId`'s primary identity just a SF login? This would mean that `authId` has 
// a secondary identity of a Paratext account, which means that Paratext 
// account is already linked to an existing SF account.
```
</blockquote></details>

I made a change to the method name, and added a comment.
___
*[src/SIL.XForge.Scripture/ClientApp/src/xforge-common/auth.service.ts, line 276 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/931#-MSF5LZYEzOBaxE8lnhy:-MSFX7Kr9BycushS4866:bwpuxzt) ([raw file](https://github.com/sillsdev/web-xforge/blob/bf88606ea119c84f36a5bc861836e1a038954c63/src/SIL.XForge.Scripture/ClientApp/src/xforge-common/auth.service.ts#L276)):*
<details><summary><i>Previously, marksvc wrote…</i></summary><blockquote>

Ok and so the comment here might say something like
// Re-navigate to this page for the new current user id to take effect.

Oh wait, would it be possible to do something like call this.localLogIn() instead?

</blockquote></details>

I thought about just using localLogIn() but it is not enough. The page really needs a full refresh.
___
*[test/SIL.XForge.Tests/Services/UserServiceTests.cs, line 93 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/931#-MSF7L8PCppzZgaGxCXH:-MSFXKWn5bAxJE4VSkxa:bxo3al9) ([raw file](https://github.com/sillsdev/web-xforge/blob/bf88606ea119c84f36a5bc861836e1a038954c63/test/SIL.XForge.Tests/Services/UserServiceTests.cs#L93)):*
<details><summary><i>Previously, marksvc wrote…</i></summary><blockquote>

> ```
> auth03
> ```
I guess maybe this line wasn't as important if it didn't cause a problem doing this :)
But it might be; let's adjust it by changing 'auth03' to 'paratext|paratext01'
(I think is what it should be?)
</blockquote></details>

Oh yea, guess that's not really that important after all.
___
*[test/SIL.XForge.Tests/Services/UserServiceTests.cs, line 98 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/931#-MSF6rX2B5NpEXq0sulL:-MSFXPHD0s5F0HuiW5HR:b-896fix) ([raw file](https://github.com/sillsdev/web-xforge/blob/bf88606ea119c84f36a5bc861836e1a038954c63/test/SIL.XForge.Tests/Services/UserServiceTests.cs#L98)):*
<details><summary><i>Previously, marksvc wrote…</i></summary><blockquote>

(oops)
</blockquote></details>

Done.

**Review by marksvc — COMMENTED** [review]
> Reviewed 3 of 3 files at r2.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/931)* status: all files reviewed, 1 unresolved discussion (waiting on @RaymondLuong3)

___
*[src/SIL.XForge/Services/UserService.cs, line 174 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/931#-MSF2F0f2wllKvRgOi44:-MST_0sQ0L8B5vZoshny:b-ipc0l2) ([raw file](https://github.com/sillsdev/web-xforge/blob/bf88606ea119c84f36a5bc861836e1a038954c63/src/SIL.XForge/Services/UserService.cs#L174)):*
That's helpful, thank you. 

> this 'authId' is just another auth0 account.

But couldn't it be for an auth0 account that has a secondary identity of a Paratext account? 
I am only growing in my understanding of this area.

**Review by RaymondLuong3 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/931)* status: 3 of 5 files reviewed, all discussions resolved (waiting on @marksvc)

___
*[src/SIL.XForge/Services/UserService.cs, line 174 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/931#-MSF2F0f2wllKvRgOi44:-MSUGfHK-uyABKnb1vs3:b-dqicum) ([raw file](https://github.com/sillsdev/web-xforge/blob/bf88606ea119c84f36a5bc861836e1a038954c63/src/SIL.XForge/Services/UserService.cs#L174)):*
<details><summary><i>Previously, marksvc wrote…</i></summary><blockquote>

That's helpful, thank you. 

> this 'authId' is just another auth0 account.

But couldn't it be for an auth0 account that has a secondary identity of a Paratext account? 
I am only growing in my understanding of this area.
</blockquote></details>

Ok, I've updated the wording now.

**Review by marksvc — APPROVED** [review]
Thanks for your work on this. I approve, but made a couple comments about improvements that could be made.

> Reviewed 2 of 2 files at r3.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/931#-:-MSYf2aP5ZZTOg6BrNkq:b-dzhq5l)* status: all files reviewed, 2 unresolved discussions (waiting on @RaymondLuong3)

___
*[src/SIL.XForge/Services/UserService.cs, line 102 at r3](https://reviewable.io/reviews/sillsdev/web-xforge/931#-MSYe7MwAWj1E0ASOkfv:-MSYe7MwAWj1E0ASOkfw:b-w4b3fj) ([raw file](https://github.com/sillsdev/web-xforge/blob/bb122cbc620135736d3d283a04df58a864736220/src/SIL.XForge/Services/UserService.cs#L102)):*
> ```
> paratext_account_already_linked
> ```

It may be somewhat confusing that this looks like it's supposed to be an identifier, now that it isn't interpreted/used/processed as an identifier any more. If we don't use it as an identifier, then the string could be the same but without underscores.

Note that this is an opposite thought from the other comment that I am leaving :)
(The other comment being preferable.)
___
*[src/SIL.XForge.Scripture/ClientApp/src/xforge-common/auth.service.ts, line 257 at r3](https://reviewable.io/reviews/sillsdev/web-xforge/931#-MSYePH56zD__KL028Rk:-MSYePH62Xjw_pZWm94y:b-xkfxkm) ([raw file](https://github.com/sillsdev/web-xforge/blob/bb122cbc620135736d3d283a04df58a864736220/src/SIL.XForge.Scripture/ClientApp/src/xforge-common/auth.service.ts#L257)):*
> ```XML
>         await this.commandService.onlineInvoke(USERS_URL, 'linkParatextAccount', { authId: secondaryId });
>       } catch (err) {
>         if (!(err instanceof CommandError) || err.code !== CommandErrorCode.InvalidParams) {
> ```

This is less specific and might result in showing the message to users when something _else_ caused an argument exception, or invalid parameters error. But it didn't look like that will be a problem at present anyway. You could check that err is instanceof CommandError _and_ that it has a message containing the already-linked token.

**Review by RaymondLuong3 — COMMENTED** [review]
Ok, I've taken the improvement suggestions.

> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/931#-:-MSZ7u7G5ljuYZMsCpvp:b-10x2q9)* status: 3 of 5 files reviewed, 2 unresolved discussions (waiting on @marksvc)

___
*[src/SIL.XForge/Services/UserService.cs, line 102 at r3](https://reviewable.io/reviews/sillsdev/web-xforge/931#-MSYe7MwAWj1E0ASOkfv:-MSZ7zrNEcwoydbP0GaH:b-z0i7l8) ([raw file](https://github.com/sillsdev/web-xforge/blob/bb122cbc620135736d3d283a04df58a864736220/src/SIL.XForge/Services/UserService.cs#L102)):*
<details><summary><i>Previously, marksvc wrote…</i></summary><blockquote>

> ```
> paratext_account_already_linked
> ```

It may be somewhat confusing that this looks like it's supposed to be an identifier, now that it isn't interpreted/used/processed as an identifier any more. If we don't use it as an identifier, then the string could be the same but without underscores.

Note that this is an opposite thought from the other comment that I am leaving :)
(The other comment being preferable.)
</blockquote></details>

I've taken your other suggestion.
___
*[src/SIL.XForge.Scripture/ClientApp/src/xforge-common/auth.service.ts, line 257 at r3](https://reviewable.io/reviews/sillsdev/web-xforge/931#-MSYePH56zD__KL028Rk:-MSZ8EfN06quH2rP1N6c:bud1q1l) ([raw file](https://github.com/sillsdev/web-xforge/blob/bb122cbc620135736d3d283a04df58a864736220/src/SIL.XForge.Scripture/ClientApp/src/xforge-common/auth.service.ts#L257)):*
<details><summary><i>Previously, marksvc wrote…</i></summary><blockquote>

This is less specific and might result in showing the message to users when something _else_ caused an argument exception, or invalid parameters error. But it didn't look like that will be a problem at present anyway. You could check that err is instanceof CommandError _and_ that it has a message containing the already-linked token. 
</blockquote></details>

This should do the trick now.

**Pull request merged**
