### PR TITLE
Fix connection from db scripts to realtime server

### PR DESCRIPTION
**Pull request by marksvc**
This was broken in 677ac2c87dd9ebd49d4cf72b5db122f3a36ea20e (#1276) when
the realtime server started started checking the origin.

Remove rather than fix revert-docs script, since other scripts now cover
the same functionality and it wasn't part of the suite of scripts.

commit-id:25389851

**Issue references**: 

 - #1276---

**Stack**:
- #1325
- #1324
- #1323
- #1326 ⮜

⚠️ *Part of a stack created by [spr](https://github.com/ejoffe/spr). Do not merge manually using the UI - doing so may have unexpected results.*

### CODE REVIEW

**Review by RaymondLuong3 — APPROVED** [review]
:lgtm: 

> Reviewed 10 of 10 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1326#-:-N0bqIyj5VHV4S6iPHu1:bg7igkv)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @marksvc)

**Review by Nateowami — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1326)* status: all files reviewed, 1 unresolved discussion (waiting on @marksvc)

___
*[`scripts/db_tools/utils.js` line 1 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/1326#-N0bt_U17ocPAbpHkdnc:-N0bt_U17ocPAbpHkdnd:b-358ini) ([raw file](https://github.com/sillsdev/web-xforge/blob/8c92c29779ac880232ceea0b634abfca2e87f012/scripts/db_tools/utils.js#L1)):*
> ```JavaScript
> const WebSocket = utils.requireFromRealTimeServer('ws');
> ```

`utils` is not defined.

**Comment by marksvc** [comment]
*[`scripts/db_tools/utils.js` line 1 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/1326#-N0bt_U17ocPAbpHkdnc:-N0bwDgs2waIla1XuL4G:b-gyevwg) ([raw file](https://github.com/sillsdev/web-xforge/blob/8c92c29779ac880232ceea0b634abfca2e87f012/scripts/db_tools/utils.js#L1)):*
<details><summary><i>Previously, Nateowami (Nathaniel Paulus) wrote…</i></summary><blockquote>

`utils` is not defined.
</blockquote></details>

Oh, yeah, I fixed that in a followup. I can squash it into this one.

**Review by Nateowami — APPROVED** [review]
:lgtm:

> Reviewed 9 of 10 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1326#-:-N0bxbXt7xeQV4HprJVG:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @marksvc)

**Pull request merged**
