### PR TITLE
SF-2483 Mark chapters as having a draft on Serval build completion

### PR DESCRIPTION
**Pull request by pmachapman**
This PR:
 * Adds a `hasDraft` property to the `Chapter` class.
 * Adds a webhook that will be executed when a Serval build completes that will update this value on any chapters in the project.

Due to its technical nature, the acceptance test should be completed by a developer.

- - -
This change is [Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/2372)

### CODE REVIEW

**Review by josephmyers — APPROVED** [review]
Maybe I wasn't clear last week. I'll approve this, as to not impede anything, but we can also wait. What's the status of Serval 1.3?

> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/2372#-:-NtDvr3m6-ETWcjLQPzi:b-8y7ach)* status: all files reviewed, 3 unresolved discussions (waiting on @pmachapman)

**Review by pmachapman — COMMENTED** [review]
> What's the status of Serval 1.3?

I think delayed due to the conference. It might be ready this week or next.

> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/2372#-:-NtED5uR3UqZTYfFN0FD:b-35xljy)* status: all files reviewed, 3 unresolved discussions (waiting on @pmachapman)

**Review by pmachapman — COMMENTED** [review]
> Dismissed @github-advanced-security[bot] from 2 discussions.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/2372)* status: 15 of 16 files reviewed, 1 unresolved discussion (waiting on @josephmyers)

___
*[`src/SIL.XForge.Scripture/Services/MachineApiService.cs` line 120 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/2372#gh-1522315244:-NtTUBAA0INPikhT-Mn7:b-896fix) ([raw file](https://github.com/sillsdev/web-xforge/blob/558db82c06248d3229ae88c3541a5b9aeaa3b5a8/src/SIL.XForge.Scripture/Services/MachineApiService.cs#L120)):*
<details><summary><i>Previously, github-advanced-security[bot] wrote…</i></summary><blockquote>

## Missing Dispose call on local IDisposable

Disposable 'HMACSHA256' is created but not disposed.

[Show more details](https://github.com/sillsdev/web-xforge/security/code-scanning/755)
</blockquote></details>

Done.
___
*[`src/SIL.XForge.Scripture/Services/MachineApiService.cs` line 510 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/2372#gh-1522315243:-NtTUBrXD9bUT8yUT1ur:b-896fix) ([raw file](https://github.com/sillsdev/web-xforge/blob/558db82c06248d3229ae88c3541a5b9aeaa3b5a8/src/SIL.XForge.Scripture/Services/MachineApiService.cs#L510)):*
<details><summary><i>Previously, github-advanced-security[bot] wrote…</i></summary><blockquote>

## Generic catch clause

Generic catch clause.

[Show more details](https://github.com/sillsdev/web-xforge/security/code-scanning/754)
</blockquote></details>

Done.
___
*[`src/SIL.XForge.Scripture/Services/PreTranslationService.cs` line 271 at r3](https://reviewable.io/reviews/sillsdev/web-xforge/2372#-NsxCdRI3O5HTLX26eAd:-NtTUu_5Eb9Rg1qQfycD:bb2ur4f) ([raw file](https://github.com/sillsdev/web-xforge/blob/13e49a79c470bb4414ec552ffc3237da4e2dd600/src/SIL.XForge.Scripture/Services/PreTranslationService.cs#L271)):*
<details><summary><i>Previously, josephmyers wrote…</i></summary><blockquote>

Any value in using a HashSet here? To avoid this check
</blockquote></details>

Done. Great thinking - thank you!!!

**Comment by pmachapman** [comment]
@josephmyers Serval 1.3 is now on QA, so the PR can be tested.

**Comment by josephmyers** [comment]
Tested and was able to receive code 200 from Swagger. Awesome! I'll move this to test

**Comment by Nateowami** [comment]
@pmachapman I'm unclear about the status of testing this. It looks like the test team tested this after you had called for it to be tested by a developer? Are we happy that it's finished testing, or should I or someone else try to test it?

**Comment by pmachapman** [comment]
@Nateowami It has finished testing - I am merging it now.

**Pull request merged**
