### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by Nateowami**
- Clarify that repo pertains to Scripture Forge
- Remove references to Language Forge
- Add link to help site
- Update help email
- Replace TeamCity build status badges with GitHub Action status badges
- Replace live status badge with status and uptime from NodePing

- - -
This change is [Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/2818)

### CODE REVIEW

**Review by Nateowami — COMMENTED** [review]
I'm not sure, and perhaps that's a good reason to not include it. Our 30-day uptime is 100%, so it will take having an incident to be able to figure out with certainty what the timeframe is. See https://shields.io/badges/node-ping-uptime, where I thought it might be indicated. 

Judging by this though, I'd say it's 30 days: https://github.com/badges/shields/blob/master/services/nodeping/nodeping-uptime.service.js#L71

> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/2818#-:-O9kagAG2Nmfb7_ozIK8:b-scidl)* status: all files reviewed, 1 unresolved discussion (waiting on @RaymondLuong3)

___
*[`README.md` line 9 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/2818#-O9k-0GZ0ap0vcMylPah:-O9kaJQz-CHN00J9H9x7:bj1tqyp) ([raw file](https://github.com/sillsdev/web-xforge/blob/27dd82aab4b6a56bce2f908197201aa3bb696966/README.md#L9)):*
<details><summary><i>Previously, RaymondLuong3 (Raymond Luong) wrote…</i></summary><blockquote>

I think this makes it less likely for internet crawlers to spam this email. Is that right? If so, that is very smart
</blockquote></details>

Yes, that's the idea. I don't know how effective it is these days, and we already have our help email public on our help site. However, it's possible GitHub is more likely to be indexed by spam bots. I don't know. I thought about switching it to the actual email address, but I figure if someone is on a GitHub repo, they should be able to figure something this simple out, so I left it as it was before.

**Comment by Nateowami** [comment]
@RaymondLuong3 Should I change it to this? NodePing uptime

**Review by RaymondLuong3 — COMMENTED** [review]
I do like the descriptive uptime badge. Yes please.

> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/2818#-:-O9p7qIWD9GLsoojtwYw:b-ageu79)* status: 0 of 1 files reviewed, all discussions resolved (waiting on @Nateowami)

**Comment by Nateowami** [comment]
@RaymondLuong3 I already updated it yesterday.

**Review by RaymondLuong3 — APPROVED** [review]
ah yes, I missed the update. Thank you.

> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/2818#-:-O9prlWhCKGfHaGxkxdK:b-775zmy)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @Nateowami)

**Pull request merged**
