### PR TITLE
vagrant: Remove mongodb focal workaround

### PR DESCRIPTION
**Pull request by marksvc**
Now implemented conditionally in dependencies.yml.

---
This change is [Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/857)

### CODE REVIEW

**Review by Nateowami — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/857)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @marksvc)

___
*[deploy/vagrant/sfdev/base/provision, line 360 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/857#-ML9_RvBD1wSBabVv3_p:-ML9_RvBD1wSBabVv3_q:b9y32cj) ([raw file](https://github.com/sillsdev/web-xforge/blob/b2a7bf72714e99c06ca380f7bf27b109079fef41/deploy/vagrant/sfdev/base/provision#L360)):*
> ```
> # isn't about file permissions; it's part of triggering multi-line substitution. The regex
> # finds the 'update_cache: yes' line that follows a line ending in 'mongodb-org'
> perl -0777 -pi -e 's/(mongodb-org.*?)update_cache: yes/$1update_cache: no/s' ~/src/web-xforge/deploy/dependencies.yml
> ```

Is this line still necessary?

**Review by marksvc — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/857)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @Nateowami)

___
*[deploy/vagrant/sfdev/base/provision, line 360 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/857#-ML9_RvBD1wSBabVv3_p:-ML9uzjoE1L9Rm-2SfuK:bqmpus7) ([raw file](https://github.com/sillsdev/web-xforge/blob/b2a7bf72714e99c06ca380f7bf27b109079fef41/deploy/vagrant/sfdev/base/provision#L360)):*
<details><summary><i>Previously, Nateowami (Nathaniel Paulus) wrote…</i></summary><blockquote>

Is this line still necessary?
</blockquote></details>

I wondered at that when making the change-at-hand. I would need to run thru the steps again to know. I'd like to take this line out so I can remove the `git checkout ... dependencies.yml` command below, but would need to do some investigating to confidently do that.

**Comment by marksvc** [comment]
(And I don't plan to put the work into doing that for this PR unless you think that's important.)

**Review by Nateowami — APPROVED** [review]
It would be great to get it to the point where no rewriting of Ansible files is necessary, but this PR is an improvement over what's in master, so :lgtm:

> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/857#-:-MLyz28o9VjZ8LjFXdh7:b-wizr3c)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
