### PR TITLE
Add help search engine for fr

### PR DESCRIPTION
**Pull request by irahopkinson**
- I've created the Google Programmable Search Engine for fr
- this adds its ID
- the language help site has been verified on Google Search Console
- publish fr help and fix localName

The help for fr is now active but the search will take some time for Google to crawl and index it.

---
This change is [Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/882)

### CODE REVIEW

**Comment by irahopkinson** [comment]
@Nateowami this PR also fixes the spelling of localName for French.

**Review by Nateowami — COMMENTED** [review]
> Reviewed 2 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/882)* status: all files reviewed, 1 unresolved discussion (waiting on @irahopkinson)

___
*[src/Help/UpdateHelp/Program.cs, line 57 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/882#-MMzv-fL7UTI3UYUWDLj:-MMzv-fL7UTI3UYUWDLk:b-8u4f4b) ([raw file](https://github.com/sillsdev/web-xforge/blob/b4a41af25a8550876ade47f703e5343ae275f6e7/src/Help/UpdateHelp/Program.cs#L57)):*
> ```Smalltalk
>             // see https://programmablesearchengine.google.com/ to create an engine for each language
>             // copy existing setup from another language, include
>             // Look and feel > Layout > Two column
> ```

I don't understand this line and the line below. Is this a list of items? I normally see `>` used like this to indicate steps to follow through a GUI, but I don't see the context.

**Review by irahopkinson — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/882)* status: all files reviewed, 1 unresolved discussion (waiting on @Nateowami)

___
*[src/Help/UpdateHelp/Program.cs, line 57 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/882#-MMzv-fL7UTI3UYUWDLj:-MN1Yfv2BGb3EA3GuM-V:bfsjz5v) ([raw file](https://github.com/sillsdev/web-xforge/blob/b4a41af25a8550876ade47f703e5343ae275f6e7/src/Help/UpdateHelp/Program.cs#L57)):*
<details><summary><i>Previously, Nateowami (Nathaniel Paulus) wrote…</i></summary><blockquote>

I don't understand this line and the line below. Is this a list of items? I normally see `>` used like this to indicate steps to follow through a GUI, but I don't see the context.
</blockquote></details>

It's quite likely this could use some help making it understandable - its currently note form to remind me. Let me explain and perhaps you can suggest an improvement. Since I had to create another Google Programmable Search Engine for French (we have to create a search engine for each language), I took the opportunity to note 2 important settings here. These 4 comment lines all go together. The context is the first line - go to the link to create a new search engine, in this case for French. Each language's search engine needs to have the same settings (comment line 2) including comment line 3 & 4. And yes these 2 are GUI items for the link in comment line 1. Finally, and I realise not explcitly pointed out here, place the new search engine ID in the dictionary below.

**Comment by Nateowami** [comment]
Is this ready for review, or intentionally still a draft?

**Comment by irahopkinson** [comment]
Intentionally still draft. I needed to get back to my work PC to push the help repo and then actually create the fr help.

**Review by Nateowami — APPROVED** [review]
:shipit: 

> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/882#-:-MNUX0bS6R6CYhv5y3m8:bizlbj6)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
