### PR TITLE
SF-1724 Allow a user to delete a note from a thread

### PR DESCRIPTION
**Pull request by RaymondLuong3**
* show a confirmation dialog when a user clicks to delete a note
* delete the note from the thread if the user confirms
* delete the note thread doc if the note is the last one in the thread

image

- - -
This change is [Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1496)

### CODE REVIEW

**Review by Nateowami — COMMENTED** [review]
I looked into why the test is failing, and it's the Chromium 105 failure. If you rebase `feature/create-note` on master, then the builds should start to pass.

> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1496#-:-NBsS3vL9Sexb3kb-dNg:bmb27f1)* status: 0 of 8 files reviewed, all discussions resolved

**Review by Nateowami — CHANGES_REQUESTED** [review]
I reviewed everything except the tests. Just a couple questions and suggestions.

I tested this locally, and you can delete the latest note, and then there's no more delete button. But if you then close the dialog and open it again, there's an option to delete the last note again. Is that just an incomplete feature that will be addressed in a future PR, or is that something that's missing from this one?

> Reviewed 5 of 8 files at r2, 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1496#-:-NDU4RKTBHvnzRXn_Sed:b-xp8x4d)* status: 5 of 8 files reviewed, 5 unresolved discussions (waiting on @Nateowami and @RaymondLuong3)

___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/note-dialog/note-dialog.component.ts` line 229 at r3](https://reviewable.io/reviews/sillsdev/web-xforge/1496#-NDV2Ft582sysfWKEOg1:-NDV2Ft582sysfWKEOg2:bf8c3iu) ([raw file](https://github.com/sillsdev/web-xforge/blob/e0e3c1d5008f163106e21798d23c640947d8c182/src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/note-dialog/note-dialog.component.ts#L229)):*
> ```XML
>     const confirm: Observable<string> = this.i18n.translate('note_dialog.confirm');
>     const confirmed: boolean = await this.dialogService.confirm(message, confirm);
>     if (confirmed && this.threadDoc?.data != null) {
> ```

When reading this line, one of the first things I wonder is what happens if this condition is false. In order to find out, I have to find the matching curly brace, and see if anything comes after it (such as an `else if`, `else`, or just more lines of code). Doing so, I see that nothing happens if this condition fails.

If this was written as:
``` ts
if (!confirmed || this.threadDoc?.data == null) {
  return;
}
```
it would tell the reader immediately that this condition failing means the entire method completes, and everything that comes after this is dependent on this condition being true. There are no additional lines that will execute when this is false.

If this were a very short method like:
``` ts
if (a) {
  doB();
}
```
I probably wouldn't want it to be written as:
``` ts
if (!a) {
  return;
}
doB();
```
since that's less readable.

Maybe there's a countervailing argument I'm not thinking of? I just know that when I read this, I can't immediately comprehend it because I have to search for the matching curly brace, which is hard.
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/note-dialog/note-dialog.component.ts` line 229 at r3](https://reviewable.io/reviews/sillsdev/web-xforge/1496#-NDV6mK09cfpxLt56tQY:-NDV6mK09cfpxLt56tQZ:b-bivu05) ([raw file](https://github.com/sillsdev/web-xforge/blob/e0e3c1d5008f163106e21798d23c640947d8c182/src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/note-dialog/note-dialog.component.ts#L229)):*
> ```XML
>     const confirm: Observable<string> = this.i18n.translate('note_dialog.confirm');
>     const confirmed: boolean = await this.dialogService.confirm(message, confirm);
>     if (confirmed && this.threadDoc?.data != null) {
> ```

What about when `this.threadDoc?.data == null`? From what I can tell, this should never happen, so it would make more sense to assert that, than to silently do nothing.
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/note-dialog/note-dialog.component.ts` line 232 at r3](https://reviewable.io/reviews/sillsdev/web-xforge/1496#-NDV8KM9CWTISeARHgOY:-NDV8KM9CWTISeARHgOZ:b-8ylb3p) ([raw file](https://github.com/sillsdev/web-xforge/blob/e0e3c1d5008f163106e21798d23c640947d8c182/src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/note-dialog/note-dialog.component.ts#L232)):*
> ```XML
>       if (this.notesToDisplay.length === 1) {
>         // This may be the last note in the thread, so the thread may need to be deleted
>         this.dialogRef.close({ note, selectedText: '', position: { start: 0, length: 0 }, deleted: true });
> ```

I'm guessing there's some reason all these thread actions (creating, editing, deleting) need to be delegated to the editor component, rather than being done within the note dialog component itself? It seems slightly odd to essentially send messages to the opener of the dialog to tell it what it needs to do to the note thread.
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/note-dialog/note-dialog.component.ts` line 233 at r3](https://reviewable.io/reviews/sillsdev/web-xforge/1496#-NDV15B71eOn1N-95nby:-NDV15B8CdqsXOE8FL7J:b-trbk1n) ([raw file](https://github.com/sillsdev/web-xforge/blob/e0e3c1d5008f163106e21798d23c640947d8c182/src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/note-dialog/note-dialog.component.ts#L233)):*
> ```XML
>         // This may be the last note in the thread, so the thread may need to be deleted
>         this.dialogRef.close({ note, selectedText: '', position: { start: 0, length: 0 }, deleted: true });
>         return;
> ```

This is approximately the opposite complaint as above. How about doing:
``` ts
if (condition) {
  doThing();
}
else  {
  doOtherThing()
}
```
Instead of:
``` ts
if (condition) {
  doThing();
  return;
}
doOtherThing();
```
With an `if`/`else` it's pretty clear that there are two mutually exclusive, collectively exhaustive, possibilities. It's still possible to understand this by reading line by line, but the higher-level logic (do thing a, or do thing b) is partially hidden within thing a.

As above, since this is a stylistic argument that comes up because of how I read through it, there could be a countervailing argument I'm not thinking of. I just know how this looks to me when I read and try to understand the logic.
___
*[`src/SIL.XForge.Scripture/ClientApp/src/assets/i18n/non_checking_en.json` line 151 at r2](https://reviewable.io/reviews/sillsdev/web-xforge/1496#-ND4Vc0E2ILliBRKOxUA:-ND4Vc0E2ILliBRKOxUB:b-662ue6) ([raw file](https://github.com/sillsdev/web-xforge/blob/594050119d4c3921180125ce382a951ca6bdbc5d/src/SIL.XForge.Scripture/ClientApp/src/assets/i18n/non_checking_en.json#L151)):*
> ```JSON
>     "acceptance_change_heading": "Changes Paratext Accepted (current text):",
>     "close": "Close",
>     "confirm": "Confirm",
> ```

How about "Delete"?

**Review by RaymondLuong3 — COMMENTED** [review]
Good catch, I'll fix it here in this PR.

> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1496#-:-NDZ-bgu4eSvnDOo1Arw:bag8kz2)* status: 3 of 8 files reviewed, 5 unresolved discussions (waiting on @Nateowami)

___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/note-dialog/note-dialog.component.ts` line 229 at r3](https://reviewable.io/reviews/sillsdev/web-xforge/1496#-NDV2Ft582sysfWKEOg1:-NDZ0f9q7ODETmd8ipeT:b-ystrx0) ([raw file](https://github.com/sillsdev/web-xforge/blob/e0e3c1d5008f163106e21798d23c640947d8c182/src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/note-dialog/note-dialog.component.ts#L229)):*
<details><summary><i>Previously, Nateowami (Nathaniel Paulus) wrote…</i></summary><blockquote>

When reading this line, one of the first things I wonder is what happens if this condition is false. In order to find out, I have to find the matching curly brace, and see if anything comes after it (such as an `else if`, `else`, or just more lines of code). Doing so, I see that nothing happens if this condition fails.

If this was written as:
``` ts
if (!confirmed || this.threadDoc?.data == null) {
  return;
}
```
it would tell the reader immediately that this condition failing means the entire method completes, and everything that comes after this is dependent on this condition being true. There are no additional lines that will execute when this is false.

If this were a very short method like:
``` ts
if (a) {
  doB();
}
```
I probably wouldn't want it to be written as:
``` ts
if (!a) {
  return;
}
doB();
```
since that's less readable.

Maybe there's a countervailing argument I'm not thinking of? I just know that when I read this, I can't immediately comprehend it because I have to search for the matching curly brace, which is hard.
</blockquote></details>

Good thinking. I typically use that logic, but I missed it here.
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/note-dialog/note-dialog.component.ts` line 229 at r3](https://reviewable.io/reviews/sillsdev/web-xforge/1496#-NDV6mK09cfpxLt56tQY:-NDZ0lrm2SlBO-Z3YP0W:b-896fix) ([raw file](https://github.com/sillsdev/web-xforge/blob/e0e3c1d5008f163106e21798d23c640947d8c182/src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/note-dialog/note-dialog.component.ts#L229)):*
<details><summary><i>Previously, Nateowami (Nathaniel Paulus) wrote…</i></summary><blockquote>

What about when `this.threadDoc?.data == null`? From what I can tell, this should never happen, so it would make more sense to assert that, than to silently do nothing.
</blockquote></details>

Done.
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/note-dialog/note-dialog.component.ts` line 232 at r3](https://reviewable.io/reviews/sillsdev/web-xforge/1496#-NDV8KM9CWTISeARHgOY:-NDZ0pFEE9r4SNBO3lRJ:b2s2gdo) ([raw file](https://github.com/sillsdev/web-xforge/blob/e0e3c1d5008f163106e21798d23c640947d8c182/src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/note-dialog/note-dialog.component.ts#L232)):*
<details><summary><i>Previously, Nateowami (Nathaniel Paulus) wrote…</i></summary><blockquote>

I'm guessing there's some reason all these thread actions (creating, editing, deleting) need to be delegated to the editor component, rather than being done within the note dialog component itself? It seems slightly odd to essentially send messages to the opener of the dialog to tell it what it needs to do to the note thread.
</blockquote></details>

I plan to change that in a following PR. I wanted to get the functionality in, which seems to be almost done. And now we can do some refactoring.
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/note-dialog/note-dialog.component.ts` line 233 at r3](https://reviewable.io/reviews/sillsdev/web-xforge/1496#-NDV15B71eOn1N-95nby:-NDZ173A9fJmCccpiS2d:b-o9dby6) ([raw file](https://github.com/sillsdev/web-xforge/blob/e0e3c1d5008f163106e21798d23c640947d8c182/src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/note-dialog/note-dialog.component.ts#L233)):*
<details><summary><i>Previously, Nateowami (Nathaniel Paulus) wrote…</i></summary><blockquote>

This is approximately the opposite complaint as above. How about doing:
``` ts
if (condition) {
  doThing();
}
else  {
  doOtherThing()
}
```
Instead of:
``` ts
if (condition) {
  doThing();
  return;
}
doOtherThing();
```
With an `if`/`else` it's pretty clear that there are two mutually exclusive, collectively exhaustive, possibilities. It's still possible to understand this by reading line by line, but the higher-level logic (do thing a, or do thing b) is partially hidden within thing a.

As above, since this is a stylistic argument that comes up because of how I read through it, there could be a countervailing argument I'm not thinking of. I just know how this looks to me when I read and try to understand the logic.
</blockquote></details>

I like using else for the readability too, and the mutually exclusive argument is valid. Done.
___
*[`src/SIL.XForge.Scripture/ClientApp/src/assets/i18n/non_checking_en.json` line 151 at r2](https://reviewable.io/reviews/sillsdev/web-xforge/1496#-ND4Vc0E2ILliBRKOxUA:-NDZ1Fm0DED260ewoJ_J:bhqqiqv) ([raw file](https://github.com/sillsdev/web-xforge/blob/594050119d4c3921180125ce382a951ca6bdbc5d/src/SIL.XForge.Scripture/ClientApp/src/assets/i18n/non_checking_en.json#L151)):*
<details><summary><i>Previously, Nateowami (Nathaniel Paulus) wrote…</i></summary><blockquote>

How about "Delete"?
</blockquote></details>

Yes, I like it.

**Review by Nateowami — COMMENTED** [review]
One question. Still reviewing the tests. 

> Reviewed 1 of 2 files at r4, 2 of 3 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1496#-:-NDZ7n5j05ieb2pSHkAE:beikf6n)* status: 6 of 8 files reviewed, 1 unresolved discussion (waiting on @Nateowami and @RaymondLuong3)

___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.ts` line 827 at r2](https://reviewable.io/reviews/sillsdev/web-xforge/1496#-NDZ7c8s3hI-stuw8rtM:-NDZ7c8s3hI-stuw8rtN:b-hyoy0j) ([raw file](https://github.com/sillsdev/web-xforge/blob/594050119d4c3921180125ce382a951ca6bdbc5d/src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.ts#L827)):*
> ```XML
>       this.toggleNoteThreadVerses(true);
>     }
>     // Ensure cursor selection remains at the position of the note in case the focus was lost when the dialog was open
> ```

Why was this removed?

**Review by Nateowami — COMMENTED** [review]
> Reviewed 1 of 2 files at r4, 1 of 3 files at r5.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1496)* status: all files reviewed, 1 unresolved discussion (waiting on @RaymondLuong3)

**Review by RaymondLuong3 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1496)* status: all files reviewed, 1 unresolved discussion (waiting on @Nateowami)

___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.ts` line 827 at r2](https://reviewable.io/reviews/sillsdev/web-xforge/1496#-NDZ7c8s3hI-stuw8rtM:-NDZR2-_2o9fVkntQSP2:bn78acr) ([raw file](https://github.com/sillsdev/web-xforge/blob/594050119d4c3921180125ce382a951ca6bdbc5d/src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.ts#L827)):*
<details><summary><i>Previously, Nateowami (Nathaniel Paulus) wrote…</i></summary><blockquote>

Why was this removed?
</blockquote></details>

This was unfortunately moving the selection to the beginning of the segment, and it didn't appear that it was needed since the cursor reappears in the correct position when the user closes the dialog.

**Review by Nateowami — APPROVED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1496)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @RaymondLuong3)

**Pull request merged**
