### PR TITLE
SF-2928 Allow Serval admins to download drafts

### PR DESCRIPTION
**Pull request by pmachapman**
This PR adds support for Serval Administrators to download drafts as zip files.

I am going to mark as testing not required, as developer testing will be sufficient given the Serval Admin area is not publicly accessible.

- - -
This change is [Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/2679)

### CODE REVIEW

**Review by kylebuss — COMMENTED** [review]
I know this is just a draft, but I wanted to dip my toes in a code review a little. 

> Reviewed 7 of 9 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/2679#-:-O5-zprBD4rVbSpAqYAo:bmcqhol)* status: 7 of 9 files reviewed, 4 unresolved discussions (waiting on @github-advanced-security[bot] and @pmachapman)

___
*[`src/SIL.XForge.Scripture/Controllers/MachineApiController.cs` line 412 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/2679#-O5-vyrjCHgKYx6QHlIn:-O5-vyrjCHgKYx6QHlIo:by9utnp) ([raw file](https://github.com/sillsdev/web-xforge/blob/02cee3501cef78e88c724ae8b65d9c546710dda7/src/SIL.XForge.Scripture/Controllers/MachineApiController.cs#L412)):*
> ```Smalltalk
>                     cancellationToken
>                 );
>             }
> ```

Nit: If we update the `_machineApiService.GetPretranslateUsfmAsync` method to accept an additional boolean `isServalAdmin` parameter, this could remain a single method call.



_Code quote:_
```Smalltalk
            if (_userAccessor.SystemRoles.Contains(SystemRole.ServalAdmin))
            {
                // Get the USFM without checking permissions
                usfm = await _machineApiService.GetPreTranslationUsfmAsync(
                    sfProjectId,
                    bookNum,
                    chapterNum,
                    cancellationToken
                );
            }
            else
            {
                // Get the USFM, but ensure that the user has project permission
                usfm = await _machineApiService.GetPreTranslationUsfmAsync(
                    _userAccessor.UserId,
                    sfProjectId,
                    bookNum,
                    chapterNum,
                    cancellationToken
                );
            }
```
___
*[`src/SIL.XForge.Scripture/Services/MachineApiService.cs` line 531 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/2679#-O5-wrQ37bBMU1tiyM6d:-O5-wrQ37bBMU1tiyM6e:b-h4u7tq) ([raw file](https://github.com/sillsdev/web-xforge/blob/02cee3501cef78e88c724ae8b65d9c546710dda7/src/SIL.XForge.Scripture/Services/MachineApiService.cs#L531)):*
> ```Smalltalk
>     )
>     {
>         // Do not perform any permission checking
> ```

Nit: As noted above, we could eliminate the need for an overload method.



_Code quote (i):_
```Smalltalk
        await EnsureProjectPermissionAsync(curUserId, sfProjectId);

        // Call the overload of this method, as we have performed the permission check
        return await GetPreTranslationUsfmAsync(sfProjectId, bookNum, chapterNum, cancellationToken);
    }

    public async Task<string> GetPreTranslationUsfmAsync(
        string sfProjectId,
        int bookNum,
        int chapterNum,
        CancellationToken cancellationToken
    )
    {
        // Do not perform any permission checking
```



_Code snippet (ii):_
```Smalltalk
// could look something like this:
public async Task<string> GetPreTranslationUsfmAsync(
        string curUserId,
        string sfProjectId,
        int bookNum,
        int chapterNum,
        boolean isServalAdmin,
        CancellationToken cancellationToken
    )
    {

        if(!isServalAdmin) {
            // Check if non-serval admin user has permission on project
            await EnsureProjectPermissionAsync(curUserId, sfProjectId);
        }

       // remaing code unchanged
```
___
*[`test/SIL.XForge.Scripture.Tests/Services/MachineApiServiceTests.cs` line 381 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/2679#-O5-z_bGD_mLiRqs-RNi:-O5-z_bGD_mLiRqs-RNj:b-674dtz) ([raw file](https://github.com/sillsdev/web-xforge/blob/36b51a3ac623a628ee93efb6df485ef544d6ce17/test/SIL.XForge.Scripture.Tests/Services/MachineApiServiceTests.cs#L381)):*
> ```Smalltalk
>                         Step = step,
>                         Pretranslate = new List<PretranslateCorpus>
>                         {
> ```

Just curious on this one. What was the thought behind changing these from List to Array? Did it have to do with the methods returning T[] rather than List<T>?



_Code quote:_
```Smalltalk
                        Pretranslate = new List<PretranslateCorpus>
                        {
```

**Review by pmachapman — COMMENTED** [review]
No problem! Early feedback makes any fixes or changes easier/quicker/cheaper/etc.

> Dismissed @github-advanced-security[bot] from a discussion.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/2679#-:-O5B_8QEBwJwis0nvdqR:b-720uwy)* status: 4 of 9 files reviewed, 1 unresolved discussion (waiting on @github-advanced-security[bot] and @kylebuss)

___
*[`src/SIL.XForge.Scripture/Controllers/MachineApiController.cs` line 412 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/2679#-O5-vyrjCHgKYx6QHlIn:-O5BZl6U9-bvg5Ha_-wO:b-ydonir) ([raw file](https://github.com/sillsdev/web-xforge/blob/02cee3501cef78e88c724ae8b65d9c546710dda7/src/SIL.XForge.Scripture/Controllers/MachineApiController.cs#L412)):*
<details><summary><i>Previously, kylebuss (Kyle Buss) wrote…</i></summary><blockquote>

Nit: If we update the `_machineApiService.GetPretranslateUsfmAsync` method to accept a boolean `isServalAdmin` rather than passing the `curUserId`, this could remain a single method call.
</blockquote></details>

Done. Good idea.
___
*[`src/SIL.XForge.Scripture/Services/MachineApiService.cs` line 531 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/2679#-O5-wrQ37bBMU1tiyM6d:-O5BZotf8kXma06wnTKI:b-896fix) ([raw file](https://github.com/sillsdev/web-xforge/blob/02cee3501cef78e88c724ae8b65d9c546710dda7/src/SIL.XForge.Scripture/Services/MachineApiService.cs#L531)):*
<details><summary><i>Previously, kylebuss (Kyle Buss) wrote…</i></summary><blockquote>

Nit: As noted above, we could eliminate the need for an overload method.
</blockquote></details>

Done.
___
*[`test/SIL.XForge.Scripture.Tests/Services/MachineApiServiceTests.cs` line 381 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/2679#-O5-z_bGD_mLiRqs-RNi:-O5BZrJ8C91k5U6uuTT4:bvw5w5i) ([raw file](https://github.com/sillsdev/web-xforge/blob/36b51a3ac623a628ee93efb6df485ef544d6ce17/test/SIL.XForge.Scripture.Tests/Services/MachineApiServiceTests.cs#L381)):*
<details><summary><i>Previously, kylebuss (Kyle Buss) wrote…</i></summary><blockquote>

Just curious on this one. What was the thought behind changing these from List to Array? Did it have to do with the methods returning T[] rather than List<T>?
</blockquote></details>

It is still a list, I just cleaned up the syntax to use the C# 12 collection expression syntax to remove boilerplate.

**Review by kylebuss — COMMENTED** [review]
> Reviewed 4 of 10 files at r3, 11 of 11 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/2679)* status: all files reviewed, 3 unresolved discussions (waiting on @pmachapman)

___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/serval-administration/serval-project.component.html` line 20 at r4](https://reviewable.io/reviews/sillsdev/web-xforge/2679#-O5ON5rM4pXxRqxKANTS:-O5ON5rM4pXxRqxKANTT:b8x8giq) ([raw file](https://github.com/sillsdev/web-xforge/blob/6df33303551a76c9020b7ebae7604989885d5ab4/src/SIL.XForge.Scripture/ClientApp/src/app/serval-administration/serval-project.component.html#L20)):*
> ```HTML
>     >
>       Run webhook to update draft status
>     </button>
> ```

Nit: Does changing it to "Update Draft Status" lose meaning? Also would it make sense to move this button inline or below the "Last Draft Status" heading?

Side question: Are we able to get away from adding localization to this page because it's only for Serval Admins?



_Code quote:_
```HTML
    <button
      id="run-webhook"
      mat-raised-button
      color="primary"
      (click)="retrievePreTranslationStatus()"
      [disabled]="!isOnline"
    >
      Run webhook to update draft status
    </button>
```
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/serval-administration/serval-project.component.html` line 39 at r4](https://reviewable.io/reviews/sillsdev/web-xforge/2679#-O5ONTek2-Cih-_3W3Yk:-O5ONTek2-Cih-_3W3Yl:b-nbajgz) ([raw file](https://github.com/sillsdev/web-xforge/blob/6df33303551a76c9020b7ebae7604989885d5ab4/src/SIL.XForge.Scripture/ClientApp/src/app/serval-administration/serval-project.component.html#L39)):*
> ```HTML
>       <div class="zip-progress">Zipping file {{ downloadBooksProgress }} of {{ downloadBooksTotal }}...</div>
>     }
>   </div>
> ```

Nit: Button text could just say "Download Draft" as the `app-notice icon` notifies the user that it is downloaded as a Zip. Maybe updating the notice to say something like "A Zip file containing the Paratext files from the last project sync or latest updated draft".

Maybe a future enhancement, but could we show the downloadable draft(s) in the downloads table? This could potentially allow previous drafts be stored for serval admins in the event they want to compare the generated drafts results.



_Code quote:_
```HTML
  <div class="admin-tool-control">
    <button
      (click)="downloadDraft()"
      mat-raised-button
      color="primary"
      [disabled]="!isOnline || lastCompletedBuild == null || downloadBooksTotal > 0"
      id="download-draft"
    >
      Download draft as a zip file
    </button>
    <app-info text="This will download the last draft generated by Serval, if present."></app-info>
    @if (downloadBooksTotal > 0) {
      <div class="zip-progress">Zipping file {{ downloadBooksProgress }} of {{ downloadBooksTotal }}...</div>
    }
  </div>
```
___
*[`test/SIL.XForge.Scripture.Tests/Controllers/MachineApiControllerTests.cs` line 1031 at r4](https://reviewable.io/reviews/sillsdev/web-xforge/2679#-O5OZiqZ4hNeaDx1kzYX:-O5OZiqZ4hNeaDx1kzYY:b-tu9oh7) ([raw file](https://github.com/sillsdev/web-xforge/blob/6df33303551a76c9020b7ebae7604989885d5ab4/test/SIL.XForge.Scripture.Tests/Controllers/MachineApiControllerTests.cs#L1031)):*
> ```Smalltalk
>         // Set up test environment
>         var env = new TestEnvironment();
>         // Ensure that correct overload is called
> ```

Nit: This comment can be deleted



_Code quote:_
```Smalltalk
// Ensure that correct overload is called
```

**Review by Nateowami — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/2679)* status: all files reviewed, 4 unresolved discussions (waiting on @pmachapman)

___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-generation.service.ts` line 264 at r4](https://reviewable.io/reviews/sillsdev/web-xforge/2679#-O5PewK19VsnXXyvqMqU:-O5PewK19VsnXXyvqMqV:bie150v) ([raw file](https://github.com/sillsdev/web-xforge/blob/6df33303551a76c9020b7ebae7604989885d5ab4/src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-generation.service.ts#L264)):*
> ```XML
>           if (usfm != null) {
>             const fileName: string =
>               getBookFileNameDigits(bookNum) + Canon.bookNumberToId(bookNum) + projectShortName + '.sfm';
> ```

Most file extensions are lowercase, but Paratext uses capital `.SFM`. Does it make more sense to go lower case or follow what Paratext does?

**Review by Nateowami — COMMENTED** [review]
This is looking good in my testing, though I don't have a good way of testing it with a project I'm not actually on.

> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/2679#-:-O5PfMpx4f6S6YmGkMu5:b-1tebvj)* status: all files reviewed, 4 unresolved discussions (waiting on @pmachapman)

**Review by pmachapman — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/2679)* status: all files reviewed, 1 unresolved discussion (waiting on @kylebuss)

___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/serval-administration/serval-project.component.html` line 20 at r4](https://reviewable.io/reviews/sillsdev/web-xforge/2679#-O5ON5rM4pXxRqxKANTS:-O5Pis345XLjH7-QVbsS:b-j7zjod) ([raw file](https://github.com/sillsdev/web-xforge/blob/6df33303551a76c9020b7ebae7604989885d5ab4/src/SIL.XForge.Scripture/ClientApp/src/app/serval-administration/serval-project.component.html#L20)):*
> Nit: Does changing it to "Update Draft Status" lose meaning?

I think so - I called it run webhook to make it clear that this is a special debugging/development operation.

> Are we able to get away from adding localization to this page because it's only for Serval Admins?

Yes.
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/serval-administration/serval-project.component.html` line 39 at r4](https://reviewable.io/reviews/sillsdev/web-xforge/2679#-O5ONTek2-Cih-_3W3Yk:-O5Pk6193xLZ2TV2wSIh:b-3nydkf) ([raw file](https://github.com/sillsdev/web-xforge/blob/6df33303551a76c9020b7ebae7604989885d5ab4/src/SIL.XForge.Scripture/ClientApp/src/app/serval-administration/serval-project.component.html#L39)):*
> Nit: Button text could just say "Download Draft" as the `app-notice icon` notifies the user that it is downloaded as a Zip. Maybe updating the notice to say something like "A Zip file containing the Paratext files from the last project sync or latest updated draft".

Done.

> Maybe a future enhancement, but could we show the downloadable draft(s) in the downloads table? This could potentially allow previous drafts be stored for serval admins in the event they want to compare the generated drafts results.

We currently don't have anyway of storing Serval Drafts - there is only the latest draft from Serval.
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-generation.service.ts` line 264 at r4](https://reviewable.io/reviews/sillsdev/web-xforge/2679#-O5PewK19VsnXXyvqMqU:-O5PktkpAydzEKrwQ-X-:b-yjbofc) ([raw file](https://github.com/sillsdev/web-xforge/blob/6df33303551a76c9020b7ebae7604989885d5ab4/src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-generation.service.ts#L264)):*
<details><summary><i>Previously, Nateowami (Nathaniel Paulus) wrote…</i></summary><blockquote>

Most file extensions are lowercase, but Paratext uses capital `.SFM`. Does it make more sense to go lower case or follow what Paratext does?
</blockquote></details>

Done. I forgot Linux was case sensitive...
___
*[`test/SIL.XForge.Scripture.Tests/Controllers/MachineApiControllerTests.cs` line 1031 at r4](https://reviewable.io/reviews/sillsdev/web-xforge/2679#-O5OZiqZ4hNeaDx1kzYX:-O5Pl5T8-pseyLX03wf5:b-896fix) ([raw file](https://github.com/sillsdev/web-xforge/blob/6df33303551a76c9020b7ebae7604989885d5ab4/test/SIL.XForge.Scripture.Tests/Controllers/MachineApiControllerTests.cs#L1031)):*
<details><summary><i>Previously, kylebuss (Kyle Buss) wrote…</i></summary><blockquote>

Nit: This comment can be deleted
</blockquote></details>

Done.

**Review by kylebuss — APPROVED** [review]
:lgtm:

> Reviewed 4 of 4 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/2679#-:-O5yDb64EnV7WD-q9qCY:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @pmachapman)

**Review by Nateowami — DISMISSED** [review]
I have some concerns. Blocking for the moment.

**Review by kylebuss — COMMENTED** [review]
> Reviewed 2 of 3 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/2679)* status: 18 of 19 files reviewed, 1 unresolved discussion (waiting on @pmachapman)

___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/serval-administration/serval-project.component.html` line 100 at r7](https://reviewable.io/reviews/sillsdev/web-xforge/2679#-O5yPqobEjOvrZM3b-F2:-O5yPqobEjOvrZM3b-F3:bghtg29) ([raw file](https://github.com/sillsdev/web-xforge/blob/aa58462b610e6090c4fcc400b436496bbb7cfcf3/src/SIL.XForge.Scripture/ClientApp/src/app/serval-administration/serval-project.component.html#L100)):*
> ```HTML
>     key === 'servalConfig' ? draftConfig![key] : stringify(draftConfig![key])
>   }}</strong>
> }
> ```

nit: `{{ key }}...` should start on new line.



_Code quote:_
```HTML
@for (key of keys(draftConfig ?? {}); track key) {{{ key }}: <strong>{{
    key === 'servalConfig' ? draftConfig![key] : stringify(draftConfig![key])
  }}</strong>
}
```

**Review by kylebuss — COMMENTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/2679#-:-O5yTKUX3rYEusIQZevn:bnfp4nl)* status: 18 of 19 files reviewed, all discussions resolved (waiting on @pmachapman)

**Pull request merged**
