### PR TITLE
test: create test data from single source for SFProject, User

### PR DESCRIPTION
**Pull request by marksvc**
Test data is created in various tests. When new properties are added
to
the model, it can result in needing to update many files. This
change provides a single place where SFProject, SFProjectProfile,
User,
and UserProfile objects are created for tests. Tests request the test
object, and pass a partial object representing what should be
different
from the standard test data.

The clever parts of this were written by Nathaniel. And I applied its
use throughout the codebase.

commit-id:91256a7c

- - -
This change is [Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1947)

### CODE REVIEW

**Comment by marksvc** [comment]
@Nateowami Is this in line with what you are wanting to move toward?

**Comment by marksvc** [comment]
Converted to draft as fixing a bunch of things.

**Comment by marksvc** [comment]
Okay, _now_ it's ready for review.
@Nateowami , is this what you're looking for us to do?

**Review by pmachapman — CHANGES_REQUESTED** [review]
The change looks like it will make test scaffolding easier, and I like how very few test `expect` assertions had to be changed. I just noticed one possible accidental omission, and a few nits when reviewing it.

> Reviewed 10 of 33 files at r1, 35 of 35 files at r2, all commit messages.
> Dismissed @github-code-scanning[bot] from a discussion.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1947#-:-NZweHT_1Kg6REy9r3qk:b2ak2lx)* status: all files reviewed, 5 unresolved discussions (waiting on @marksvc)

___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking.component.spec.ts` line 1 at r2](https://reviewable.io/reviews/sillsdev/web-xforge/1947#-NZwazca8U5gx8h9Ak2D:-NZwazca8U5gx8h9Ak2E:bp1s95z) ([raw file](https://github.com/sillsdev/web-xforge/blob/cfa53602fba9c67788242a04e6182831387ea7e9/src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking.component.spec.ts#L1)):*
> ```XML
> import { createTestProject } from 'realtime-server/lib/esm/scriptureforge/models/sf-project-test-data';
> ```

NIT: Should this import be down where the other realtime-server imports are?

I am not sure why these are not being automatically sorted...
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking.component.spec.ts` line 57 at r2](https://reviewable.io/reviews/sillsdev/web-xforge/1947#-NZwaoNUAujzjXTKAGJZ:-NZwaoNUAujzjXTKAGJ_:b-fuzccc) ([raw file](https://github.com/sillsdev/web-xforge/blob/cfa53602fba9c67788242a04e6182831387ea7e9/src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking.component.spec.ts#L57)):*
> ```XML
> import { MatButtonHarness } from '@angular/material/button/testing';
> import { QueryParameters } from 'xforge-common/query-parameters';
> import { createTestUser } from 'realtime-server/lib/esm/common/models/user-test-data';
> ```

NIT: Should this import be up where the other realtime-server imports are?
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-text/checking-text.component.spec.ts` line 1 at r2](https://reviewable.io/reviews/sillsdev/web-xforge/1947#-NZwbFDPDhU3srrjSX_X:-NZwbFDPDhU3srrjSX_Y:b-2cmah4) ([raw file](https://github.com/sillsdev/web-xforge/blob/cfa53602fba9c67788242a04e6182831387ea7e9/src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-text/checking-text.component.spec.ts#L1)):*
> ```XML
> import { createTestUser } from 'realtime-server/lib/esm/common/models/user-test-data';
> ```

NIT: Should this import be down where `createTestUser` is imported?
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-text/checking-text.component.spec.ts` line 218 at r2](https://reviewable.io/reviews/sillsdev/web-xforge/1947#-NZwXI1H02uEwvHLHzuq:-NZwXI1H02uEwvHLHzur:b-xzfxds) ([raw file](https://github.com/sillsdev/web-xforge/blob/cfa53602fba9c67788242a04e6182831387ea7e9/src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-text/checking-text.component.spec.ts#L218)):*
> ```XML
>   private setupProject(): void {
>     this.realtimeService.addSnapshot<SFProjectProfile>(SFProjectProfileDoc.COLLECTION, {
>       id: 'project1',
> ```

NIT: Should this be `id: 'project01'`?
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking-overview/checking-overview.component.spec.ts` line 1035 at r2](https://reviewable.io/reviews/sillsdev/web-xforge/1947#-NZw_jAM0gP5N1Xrs86p:-NZw_jAM0gP5N1Xrs86q:bcjjyhr) ([raw file](https://github.com/sillsdev/web-xforge/blob/cfa53602fba9c67788242a04e6182831387ea7e9/src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking-overview/checking-overview.component.spec.ts#L1035)):*
> ```XML
>       user: createTestUser({
>         isDisplayNameConfirmed: nameConfirmed
>       }),
> ```

For consistency, should we be passing the idSuffix to `createTestUser`, i.e. `}, idSuffix),`?

**Review by Nateowami — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1947)* status: 31 of 45 files reviewed, 4 unresolved discussions (waiting on @marksvc and @pmachapman)

___
*[`src/RealtimeServer/common/models/user-test-data.ts` line 8 at r3](https://reviewable.io/reviews/sillsdev/web-xforge/1947#-N_9mJPN1YL0jKVmPHDs:-N_9mJPO2-bX1cOxlQd_:b2pay8u) ([raw file](https://github.com/sillsdev/web-xforge/blob/a728acdf003b3f739096b3434ffc7f5562b3f916/src/RealtimeServer/common/models/user-test-data.ts#L8)):*
@pmachapman I'm the origin of calling this variable "ordinal", and I'm not sure it's proper usage. Do you know what it should be named?

Or maybe it is correct? From Merriam-Webster:
> ### ordinal number
> #### noun
> 1 : a number designating the place (such as first, second, or third) occupied by an item in an ordered sequence

**Review by pmachapman — APPROVED** [review]
> Reviewed 14 of 14 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1947)* status: all files reviewed, 1 unresolved discussion (waiting on @Nateowami)

___
*[`src/RealtimeServer/common/models/user-test-data.ts` line 8 at r3](https://reviewable.io/reviews/sillsdev/web-xforge/1947#-N_9mJPN1YL0jKVmPHDs:-N_AUfB-8g2LYe4l6tUa:b-aqo7ev) ([raw file](https://github.com/sillsdev/web-xforge/blob/a728acdf003b3f739096b3434ffc7f5562b3f916/src/RealtimeServer/common/models/user-test-data.ts#L8)):*
<details><summary><i>Previously, Nateowami (Nathaniel Paulus) wrote…</i></summary><blockquote>

@pmachapman I'm the origin of calling this variable "ordinal", and I'm not sure it's proper usage. Do you know what it should be named?

Or maybe it is correct? From Merriam-Webster:
> ### ordinal number
> #### noun
> 1 : a number designating the place (such as first, second, or third) occupied by an item in an ordered sequence
</blockquote></details>

I think its correct - I immediately knew what it was when I saw it. Usually when I see ordinal, I think whole numbers, which is what was required for this method.

**Pull request merged**
