### PR TITLE
SF-1248 Show source even if user does not have edit rights on target text

### PR DESCRIPTION
**Pull request by RaymondLuong3**
I assume that this is important enough to be a hotfix, but since we are shipping anyways we could put this on master.

This change is [Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1020)

### CODE REVIEW

**Review by Nateowami — DISMISSED** [review]
> Reviewed 1 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1020)* status: 1 of 2 files reviewed, 2 unresolved discussions (waiting on @RaymondLuong3)

___
*[src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.ts, line 230 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/1020#-MYh1NjpDuhSl6ip3s7t:-MYh1NjpDuhSl6ip3s7u:b-k30kad) ([raw file](https://github.com/sillsdev/web-xforge/blob/d4c1e3abd7a6d578f6d0b9646469e530284021c0/src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.ts#L230)):*
> ```XML
>       if (chapter != null && chapter.permissions != null) {
>         const chapterPermission: string = chapter.permissions[this.userService.currentUserId];
>         return chapterPermission === TextInfoPermission.Write || chapterPermission === TextInfoPermission.Read;
> ```

This will always evaluate to true because `TextInfoPermission.Write || chapterPermission === TextInfoPermission.Read` means `TextInfoPermission.Write` is truthy OR `chapterPermission === TextInfoPermission.Read`. Since `TextInfoPermission.Write` is a non-empty string it is always truthy.
___
*[src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.ts, line 266 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/1020#-MYh2h5k7kDAiYZpiuJk:-MYh2h5k7kDAiYZpiuJl:b5bw34y) ([raw file](https://github.com/sillsdev/web-xforge/blob/d4c1e3abd7a6d578f6d0b9646469e530284021c0/src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.ts#L266)):*
> ```XML
>   private get hasSource(): boolean {
>     const sourceId = this.projectDoc?.data?.translateConfig.source?.projectRef;
>     // This no longer requires that a user have edit permissions for a target text to see the source text
> ```

I think you added this because I asked for a comment to be added. But I meant a comment on the Jira issue. The idea was to clarify to Ira what the underlying issue was and that from our perspective it wasn't entirely a bug.

**Review by Nateowami — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1020)* status: 1 of 2 files reviewed, 1 unresolved discussion (waiting on @RaymondLuong3)

___
*[src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.ts, line 230 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/1020#-MYh1NjpDuhSl6ip3s7t:-MYh3EhpBqPlRkUweThe:b-qvz6v3) ([raw file](https://github.com/sillsdev/web-xforge/blob/d4c1e3abd7a6d578f6d0b9646469e530284021c0/src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.ts#L230)):*
<details><summary><i>Previously, Nateowami (Nathaniel Paulus) wrote…</i></summary><blockquote>

This will always evaluate to true because `TextInfoPermission.Write || chapterPermission === TextInfoPermission.Read` means `TextInfoPermission.Write` is truthy OR `chapterPermission === TextInfoPermission.Read`. Since `TextInfoPermission.Write` is a non-empty string it is always truthy.
</blockquote></details>

Oh wow, how did I misread this?! I read this as some combination of `return TextInfoPermission.Write || chapterPermission === TextInfoPermission.Read` and `chapterPermission = TextInfoPermission.Write || chapterPermission === TextInfoPermission.Read`. 

Nevermind; it looks good!

**Review by irahopkinson — CHANGES_REQUESTED** [review]
Lets hotfix this against Live.

> Reviewed 2 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1020#-:-MYhQKml5pX6iuGiDZpJ:bp8xo1i)* status: all files reviewed, 2 unresolved discussions (waiting on @Nateowami and @RaymondLuong3)

___
*[src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.ts, line 266 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/1020#-MYh2h5k7kDAiYZpiuJk:-MYhQCf92zT4uTleHYgA:b-bsjpxb) ([raw file](https://github.com/sillsdev/web-xforge/blob/d4c1e3abd7a6d578f6d0b9646469e530284021c0/src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.ts#L266)):*
<details><summary><i>Previously, Nateowami (Nathaniel Paulus) wrote…</i></summary><blockquote>

I think you added this because I asked for a comment to be added. But I meant a comment on the Jira issue. The idea was to clarify to Ira what the underlying issue was and that from our perspective it wasn't entirely a bug.
</blockquote></details>

Comment not needed. Remove it.
___
*[src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.spec.ts, line 815 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/1020#-MYhQ2vECehXicM8nJ_f:-MYhQ2vECehXicM8nJ_g:bzewie7) ([raw file](https://github.com/sillsdev/web-xforge/blob/4e831417219d2d620ebed5940c7329a36489c15a/src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.spec.ts#L815)):*
> ```
> expect(env.isSourceAreaHidden).toBe(true);
> ```
Leave this in and expect to be false now.

**Review by irahopkinson — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1020#-:-MYhSbb0ALePZLyp5qTD:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @RaymondLuong3)

___
*[src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.spec.ts, line 815 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/1020#-MYhQ2vECehXicM8nJ_f:-MYhSUT2AtwfTZmSRQhQ:bb6un1j) ([raw file](https://github.com/sillsdev/web-xforge/blob/4e831417219d2d620ebed5940c7329a36489c15a/src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.spec.ts#L815)):*
<details><summary><i>Previously, irahopkinson (Ira Hopkinson) wrote…</i></summary><blockquote>

> ```
> expect(env.isSourceAreaHidden).toBe(true);
> ```
Leave this in and expect to be false now.
</blockquote></details>

Done

**Pull request merged**
