### PR TITLE
SF-2429 Allow creating quick translation draft builds

### PR DESCRIPTION
**Pull request by pmachapman**
This PR adds a new front end feature flag called "Allow Fast Pre-Translation Training", which when enabled adds an extra final step to the Generate Draft steps containing a checkbox appears allowing enabling of "Fast Training".

Clicking on that checkbox will show a warning, and allow the user to uncheck it, go back to the previous step, or generate the draft.

This value is not preserved between builds, as it could result in unexpected results when the feature flag is disabled, or if user discovers this feature flag and enables it. In cases where the value should be preserved between builds, it is suggested to update the Serval Config in Settings to contain a `max_steps` value.

- - -
This change is [Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/2254)

### CODE REVIEW

**Review by josephmyers — CHANGES_REQUESTED** [review]
Certainly makes things go quicker! Thanks

> Reviewed 16 of 16 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/2254#-:-Nmjag5w3ZEEEbvcsvHi:b-gbrr70)* status: all files reviewed, 4 unresolved discussions (waiting on @pmachapman)

___
*[`src/SIL.XForge.Scripture/ClientApp/src/assets/i18n/non_checking_en.json` line 181 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/2254#-NmjNkMcCjkqYkxDUbF4:-NmjNkMcCjkqYkxDUbF5:b-j3uqtj) ([raw file](https://github.com/sillsdev/web-xforge/blob/1dcf163bd4189dc70bb0e2a7bb0a6825ca3abb90/src/SIL.XForge.Scripture/ClientApp/src/assets/i18n/non_checking_en.json#L181)):*
> ```JSON
>     "choose_books_to_translate_error": "No books selected. Select books to translate to continue.",
>     "choose_books_to_translate": "Choose books to translate",
>     "draft_generation_subheader": "Configure advanced draft generation settings.",
> ```

This is basically identical to the header right above it. We can remove this
___
*[`src/SIL.XForge.Scripture/ClientApp/src/assets/i18n/non_checking_en.json` line 182 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/2254#-NmjV9Le4Q1z2_DVXFU6:-NmjV9Le4Q1z2_DVXFU7:b-1fxyzp) ([raw file](https://github.com/sillsdev/web-xforge/blob/1dcf163bd4189dc70bb0e2a7bb0a6825ca3abb90/src/SIL.XForge.Scripture/ClientApp/src/assets/i18n/non_checking_en.json#L182)):*
> ```JSON
>     "choose_books_to_translate": "Choose books to translate",
>     "draft_generation_subheader": "Configure advanced draft generation settings.",
>     "draft_generation": "Configure draft generation",
> ```

If you don't like "Configure draft generation" by itself, we could do something like "Configure advanced settings."
___
*[`src/SIL.XForge.Scripture/ClientApp/src/assets/i18n/non_checking_en.json` line 183 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/2254#-NmjORux5n2SP5QqveWn:-NmjORux5n2SP5QqveWo:bxrey0s) ([raw file](https://github.com/sillsdev/web-xforge/blob/1dcf163bd4189dc70bb0e2a7bb0a6825ca3abb90/src/SIL.XForge.Scripture/ClientApp/src/assets/i18n/non_checking_en.json#L183)):*
> ```JSON
>     "draft_generation_subheader": "Configure advanced draft generation settings.",
>     "draft_generation": "Configure draft generation",
>     "fast_training_warning": "This will create a very inaccurate pre-translation draft, but with a much faster training time.",
> ```

Wording could use some improvement. How about something like, "Enabling this will save time but greatly reduce accuracy"?
___
*[`src/SIL.XForge.Scripture/Models/BuildConfig.cs` line 38 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/2254#-NmjUgLB4a9sU64UMbJ0:-NmjUgLB4a9sU64UMbJ1:b-807ag8) ([raw file](https://github.com/sillsdev/web-xforge/blob/1dcf163bd4189dc70bb0e2a7bb0a6825ca3abb90/src/SIL.XForge.Scripture/Models/BuildConfig.cs#L38)):*
> ```Smalltalk
>     /// Gets or sets a value that configures the Serval build to run with a minimum number of steps.
>     /// </summary>
>     /// <value><c>true</c> if we ar performing a fast training build; otherwise, <c>false</c>.</value>
> ```

Typo!

**Review by pmachapman — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/2254)* status: 8 of 16 files reviewed, 3 unresolved discussions (waiting on @josephmyers)

___
*[`src/SIL.XForge.Scripture/ClientApp/src/assets/i18n/non_checking_en.json` line 181 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/2254#-NmjNkMcCjkqYkxDUbF4:-Nnaj1_R0qpt252Tj-dz:b-896fix) ([raw file](https://github.com/sillsdev/web-xforge/blob/1dcf163bd4189dc70bb0e2a7bb0a6825ca3abb90/src/SIL.XForge.Scripture/ClientApp/src/assets/i18n/non_checking_en.json#L181)):*
<details><summary><i>Previously, josephmyers wrote…</i></summary><blockquote>

This is basically identical to the header right above it. We can remove this
</blockquote></details>

Done.
___
*[`src/SIL.XForge.Scripture/ClientApp/src/assets/i18n/non_checking_en.json` line 182 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/2254#-NmjV9Le4Q1z2_DVXFU6:-Nnaj51_-AYFn-H9bRlB:b5npl4r) ([raw file](https://github.com/sillsdev/web-xforge/blob/1dcf163bd4189dc70bb0e2a7bb0a6825ca3abb90/src/SIL.XForge.Scripture/ClientApp/src/assets/i18n/non_checking_en.json#L182)):*
<details><summary><i>Previously, josephmyers wrote…</i></summary><blockquote>

If you don't like "Configure draft generation" by itself, we could do something like "Configure advanced settings."
</blockquote></details>

Done. Your wording looks much better
___
*[`src/SIL.XForge.Scripture/ClientApp/src/assets/i18n/non_checking_en.json` line 183 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/2254#-NmjORux5n2SP5QqveWn:-NnaiWo6DZ9Twie60Vv4:b-3xorgy) ([raw file](https://github.com/sillsdev/web-xforge/blob/1dcf163bd4189dc70bb0e2a7bb0a6825ca3abb90/src/SIL.XForge.Scripture/ClientApp/src/assets/i18n/non_checking_en.json#L183)):*
<details><summary><i>Previously, josephmyers wrote…</i></summary><blockquote>

Wording could use some improvement. How about something like, "Enabling this will save time but greatly reduce accuracy"?
</blockquote></details>

Done. Sounds good.
___
*[`src/SIL.XForge.Scripture/Models/BuildConfig.cs` line 38 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/2254#-NmjUgLB4a9sU64UMbJ0:-NnaiQzfCxGWnwg52JCZ:boyexb3) ([raw file](https://github.com/sillsdev/web-xforge/blob/1dcf163bd4189dc70bb0e2a7bb0a6825ca3abb90/src/SIL.XForge.Scripture/Models/BuildConfig.cs#L38)):*
<details><summary><i>Previously, josephmyers wrote…</i></summary><blockquote>

Typo!
</blockquote></details>

Done. Thanks!

**Review by josephmyers — APPROVED** [review]
> Reviewed 8 of 8 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/2254)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @pmachapman)

**Review by Nateowami — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/2254)* status: 14 of 16 files reviewed, 1 unresolved discussion (waiting on @josephmyers and @pmachapman)

___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-generation-steps/draft-generation-steps.component.html` line 105 at r3](https://reviewable.io/reviews/sillsdev/web-xforge/2254#-NniVFk67bcVQehvYHtI:-NniVFk67bcVQehvYHtJ:b-36psam) ([raw file](https://github.com/sillsdev/web-xforge/blob/c4c9c4f41fbef60332a320d546f070b9a674878c/src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-generation-steps/draft-generation-steps.component.html#L105)):*
> ```HTML
>         </ng-template>
>         <div>
>           <mat-checkbox [(ngModel)]="fastTraining">{{ t("fast_training") }}</mat-checkbox>
> ```

There's really no need to localize this, as it's not going to be used outside of testing.

**Review by pmachapman — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/2254)* status: 14 of 16 files reviewed, 1 unresolved discussion (waiting on @josephmyers and @Nateowami)

___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-generation-steps/draft-generation-steps.component.html` line 105 at r3](https://reviewable.io/reviews/sillsdev/web-xforge/2254#-NniVFk67bcVQehvYHtI:-NnkEoz4895svo7yIrMv:bgreef3) ([raw file](https://github.com/sillsdev/web-xforge/blob/c4c9c4f41fbef60332a320d546f070b9a674878c/src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-generation-steps/draft-generation-steps.component.html#L105)):*
<details><summary><i>Previously, Nateowami (Nathaniel Paulus) wrote…</i></summary><blockquote>

There's really no need to localize this, as it's not going to be used outside of testing.
</blockquote></details>

Yes, true. I localized this section primarily so it wouldn't stick out like a sore thumb as a set of unlocalized strings. I also think that this section will likely have other options added to it (like the 50/50 split mentioned in the meeting today), so "configure advanced settings" may become more user visible in the future.

**Pull request merged**
