### PR TITLE
SF-2765 Allow multiple request origins to be configured

### PR DESCRIPTION
**Pull request by pmachapman**
This PR adds support for configuring an alternate domain name to be used for Scripture Forge.

**Important:** This PR does not allow alternate domain name support for the invitation email. The rationale for this is that the email will require an alternate website name. To resolve this, it is likely a more sophisticated template system may need to be implemented? I have recorded this issue for the Invitation email as SF-2798.

- - -
This change is [Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/2534)

### CODE REVIEW

**Review by nigel-wells — CHANGES_REQUESTED** [review]
This works pretty well Peter - I did make a note on your note about the invitation email.
We'll also need to decide how to handle the Auth0 email templates as well i.e. password reset, verify email, login, etc... We do have control over the login and password reset templates but it will likely get quite messy. We may need to have SF handle the full process and use the Auth0 Management IP - this is how the transparent authentication works.

I assume QA and Live will need server aliases setup to resolve whatever alternative domains are added?

Does bugsnag care where the request was made from?

Any other cross domain policies in place we need to consider or update?

> Reviewed 21 of 21 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/2534#-:-O-t4do_4EL_lPwS9OEJ:b-ewymje)* status: all files reviewed, 1 unresolved discussion (waiting on @pmachapman)

___
*[`src/SIL.XForge.Scripture/Services/SFProjectService.cs` line 614 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/2534#-O-t0fklB6vrBb8mFi50:-O-t0fklB6vrBb8mFi51:ba9fd0t) ([raw file](https://github.com/sillsdev/web-xforge/blob/88416c3dd57cffd302480e7065dcc3fd20a817d4/src/SIL.XForge.Scripture/Services/SFProjectService.cs#L614)):*
> ```Smalltalk
>         }
>         string key = projectSecret.ShareKeys.Single(sk => sk.Email == email).Key;
>         string origin = siteOptions.Origin.Split(';', StringSplitOptions.RemoveEmptyEntries).First();
> ```

For completeness we could still have the URL correct as that is the main purpose of this PR rather than getting our translation strings resolved.

**Review by pmachapman — COMMENTED** [review]
> I assume QA and Live will need server aliases setup to resolve whatever alternative domains are added?

Yes, these will be configured via the `ALTERNATE_DOMAIN` environment variable for `scripts/build-and-ship`.

> Does bugsnag care where the request was made from?

No, our bugsnag is configured to receive from any domain.

> Any other cross domain policies in place we need to consider or update?

Not that I am aware of. I think setting up a QA alternate domain will help us catch any of these. I could not determine any on my dev environment.

> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/2534#-:-O05dfDk7JFNJp7n9yLN:b-dhuqbq)* status: all files reviewed, 1 unresolved discussion (waiting on @nigel-wells)

___
*[`src/SIL.XForge.Scripture/Services/SFProjectService.cs` line 614 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/2534#-O-t0fklB6vrBb8mFi50:-O05sD6H58gxwqcwmroy:bu131kn) ([raw file](https://github.com/sillsdev/web-xforge/blob/88416c3dd57cffd302480e7065dcc3fd20a817d4/src/SIL.XForge.Scripture/Services/SFProjectService.cs#L614)):*
<details><summary><i>Previously, nigel-wells (Nigel Wells) wrote…</i></summary><blockquote>

For completeness we could still have the URL correct as that is the main purpose of this PR rather than getting our translation strings resolved.
</blockquote></details>

Done. To do that, I needed to inject the request into the `RpcController`. I found a service that had been orphaned (`IHttpRequestAccessor`), and updated it to use the logic to get the site root.

**Review by nigel-wells — APPROVED** [review]
Does the `ALTERNATE_ DOMAIN` variable get used to configure Apache though - looks like you just used it in the app secrets.

Should the invite tests be moved to the same place as the other ones in `SFProjectServiceTests.cs`?

> Reviewed 10 of 10 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/2534#-:-O06MZ3J195fvWK8lywb:b5pj9cp)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @pmachapman)

___
*[`src/SIL.XForge.Scripture/Services/SFProjectService.cs` line 614 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/2534#-O-t0fklB6vrBb8mFi50:-O06UK0K2YRBiAlYuYvV:bfi2qnf) ([raw file](https://github.com/sillsdev/web-xforge/blob/88416c3dd57cffd302480e7065dcc3fd20a817d4/src/SIL.XForge.Scripture/Services/SFProjectService.cs#L614)):*
<details><summary><i>Previously, pmachapman (Peter Chapman) wrote…</i></summary><blockquote>

Done. To do that, I needed to inject the request into the `RpcController`. I found a service that had been orphaned (`IHttpRequestAccessor`), and updated it to use the logic to get the site root.
</blockquote></details>

Thanks - works as expected.

**Review by pmachapman — COMMENTED** [review]
> Does the `ALTERNATE_DOMAIN` variable get used to configure Apache though - looks like you just used it in the app secrets.

No, these values would be configured in ansible, and by the look of the ansible config, domain specific vhosts are not configured.

> Should the invite tests be moved to the same place as the other ones in `SFProjectServiceTests.cs`?

Doing so would break the git change history for the tests, so I think it is OK to leave them where they are for now. The test file is pretty massive, and I might have a think on how we can make these smaller and saner (I get sick of scrolling to `TestEnvironment`!)

> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/2534#-:-O06ZDM93r71uRBubxqk:bomdwzt)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @pmachapman)

**Review by Nateowami — COMMENTED** [review]
> Reviewed 6 of 6 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/2534)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @pmachapman)

**Pull request merged**
